###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Afficher/Masquer les niveaux de groupe
AddLevelHandleAction_TransName=Afficher/Masquer les niveaux de groupe
AddMesureViewHandleAction.DisplayName=Afficher/Masquer les mesures
AddMesureViewHandleAction.TransName=Afficher/Masquer les mesures
AddSubTotalAction.LabelName=Total global
AddSubTotalAction.TransName=Agrégation
AddSubTotalAction.DisplayName=Totaux
AddSubTotalAction.TotalName=TOTAL
CrosstabMenuBuilder.EditCubeAction.DisplayName=Modifier cube de données
DeleteDimensionViewHandleAction.TransName=Supprimer Dimensionviewhandle
DeleteDimensionViewHandleAction.DisplayName=Supprimer
DeleteMeasureHandleAction.DisplayName=Supprimer
DeleteMeasureHandleAction.TransName=Supprimer MeasureViewHandle
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Ajouter DimensionHandle
AddMeasureViewHandleCommand.TransName=Ajouter MeasureHandle
ChangeAreaCommand.TransName=Ignorer le descripteur de dimension
ChangeMeasureOrderCommand.TransName=Modifier l'ordre de mesure
CreateDimensionViewCommand.TransName=Créer DimensionViewHandle
CreateMeasureViewCommand.TransName=Créer MeasureViewHandle
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tableau croisé
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Champ de données
GrandTotalProvider.Column.Function=Fonction
SubTotalProvider.Column.DataField=Champ de données
SubTotalProvider.Column.Function=Fonction
SubTotalProvider.Column.AggregateOn=Regrouper par
LevelViewDialog.Title=Afficher/Masquer les niveaux de groupe
LevelViewDialog.Label.Info=Sélectionner les niveaux à afficher sur le tableau croisé :
AggregationDialog.Title=Totaux
AggregationDialog.Label.Grand=Totaux généraux :
AggregationDialog.Label.Sub=Sous-totaux :
ShowSummaryFieldDialog.Title=Afficher/Masquer les champs de récapitulation
ShowSummaryFieldDialog.Label.Info=Sélectionner les niveaux à afficher sur le tableau croisé :

DeleteBindingDialog.Title=Supprimer les liaisons inutilisées ?
DeleteBindingDialog.Message=Cette action donnera des liaisons de données inutilisées.\n\nVoulez-vous supprimer les liaisons inutilisées ?
DeleteBindingDialog.ToggleMessage=Ne plus afficher ce message
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Zone de colonne
AreaNodeProvider.RowArea=Zone de ligne
AreaNodeProvider.DetailArea=Zone de détails
CrossTabViewNodeProvider.ColumnArea=Zone de colonne
CrossTabViewNodeProvider.RowArea=Zone de ligne
CrossTabCellNodeProvider.Cell=Cellule
CrossTabLevelNodeProvider.Level=Niveau - 
CrossTabMeasureNodeProvider.Detail=Détails - 
MeasureSubNodeProvider.Header=En-tête
MeasureSubNodeProvider.Detail=Détails
MeasureSubNodeProvider.Aggregation=Agrégation

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Erreur
SortkeyBuilder.DialogTitle.Label.Key=Clé :
CrosstabSortingModelProvider.ColumnName.GroupLevel=Niveau de groupe
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Niveau de groupe :
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Cliquez ici pour appeler le Générateur d'expression
SortkeyBuilder.DialogTitle.Label.Direction=Direction :

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=Général
CrosstabPageGenerator.List.Margin=Marge
CrosstabPageGenerator.List.Font=Police
CrosstabPageGenerator.List.Borders=Bordure
CrosstabPageGenerator.List.Section=Saut de page
CrosstabPageGenerator.List.Visibility=Visibilité
CrosstabPageGenerator.List.TOC=Table des matières
CrosstabPageGenerator.List.Bookmark=Signet
CrosstabPageGenerator.List.NamedExpressions=Expressions nommées
CrosstabPageGenerator.List.UserProperties=Propriétés de l'utilisateur
CrosstabPageGenerator.List.AdvancedProperty=Avancé

CrosstabPageGenerator.TabItem.Binding=Liaison
CrosstabPageGenerator.TabItem.RowArea=Zone de ligne
CrosstabPageGenerator.TabItem.ColumnArea=Zone de colonne
CrosstabPageGenerator.TabItem.DetailArea=Zone de détails
CrosstabPageGenerator.TabItem.Filters=Filtres
CrosstabPageGenerator.TabItem.Highlights=Surbrillances
CrosstabPageGenerator.TabItem.map=Mappage
CrosstabPageGenerator.TabItem.Sorting=Tri en cours

CrosstabGeneraPage.ForEmptyCell=Pour les cellules vides, afficher :
CrosstabGeneraPage.FormatOption=Options de format :
LayoutMeasuresProvider.DisplayName=Présentation verticale des champs de données dans la zone de détails


parameterBinding.title=Liaison de paramètre de jeu de données...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Trier selon :
Element.ReportItem.dataSet=Jeu de données :
Element.ReportElement.Cube=&Données :
BindingPage.None=Aucun


FilterHandleProvider.Label.Filterby=Filtrer par :

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Propriétés


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=Nouvelle condition de filtre
FilterConditionBuilder.DialogTitle.Edit=Modifier la condition de filtre
FilterConditionBuilder.choice.ValueOfThisDataItem=Valeur de l'élément de données
FilterConditionBuilder.tooltip.ExpBuilder=Cliquez ici pour appeler le Générateur d'expression.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Entrer une condition de filtre :
FilterConditionBuilder.text.GroupLevel=Niveau de groupe :
FilterConditionBuilder.list.item1=Valeur
FilterConditionBuilder.button.edit=Modifier...
FilterConditionBuilder.button.delete=Supprimer
FilterConditionBuilder.button.deleteall=Supprimer tout
FilterConditionBuilder.button.add=Ajouter
FilterConditionBuilder.button.edit.tooltip=Modifier la valeur sélectionnée dans la liste
FilterConditionBuilder.button.delete.tooltip=Supprimer la valeur sélectionnée de la liste
FilterConditionBuilder.button.deleteall.tooltip=Supprimer toutes les valeurs de la liste
FilterConditionBuilder.button.add.tooltip=Ajouter la valeur à la liste
CrosstabFilterConditionBuilder.DialogMessage.New=Select the group level to apply the filter on, then set filter condition.
CrosstabFilterConditionBuilder.DialogMessage.Edit=Select the group level to apply the filter on, then set filter condition.

FilterbyTree.Bindings.Catogory.Measures=Measures
FilterbyTree.Bindings.Catogory.Dimension=Dimension
FilterbyTree.Bindings.Catogory.GrandTotal=Total global
FilterbyTree.Bindings.Catogory.SubTotal=Sous-total
FilterbyTree.Bindings.Catogory.Undefined=Undefined
FilterbyTree.Title=Filter By
FilterbyTree.Message=Filter By

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Ignorer le(s) champ(s) de données pour définir les colonnes ici
Blank.text.row=Ignorer le(s) champ(s) de données pour définir les lignes ici
Blank.text.measure=Ignorer le(s) champ(s) de données à résumer ici

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Total global
CrosstabGrandTotalDialog.Text.DataField=Champ de données :
CrosstabGrandTotalDialog.Text.Function=Fonction :


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=Niveau de groupe
CrosstabPageBreakProvider.Column.Before=Avant
CrosstabPageBreakProvider.Column.After=Après

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Regrouper par
CrosstabSubToatalProvider.Column.DataField=Champ de données
CrosstabSubToatalProvider.Column.Function=Fonction

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Saut de page
CrosstabPageBreakDialog.Text.GroupLevel=Niveau de groupe :
CrosstabPageBreakDialog.Text.PageBreakBefore=Avant :
CrosstabPageBreakDialog.Text.PageBreakAfter=Après :

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Sous-total
SubTotalDialog.Text.AggregateOn=Regrouper par :
SubTotalDialog.Text.Function=Fonction :
SubTotalDialog.Text.DataField=Champ de données :

FormPage.Menu.ModifyProperty=Modifier

CrosstabPageGenerator.List.SubTotals=Sous-totaux
CrosstabPageGenerator.List.GrandTotals=Totaux généraux
CrosstabPageGenerator.List.PageBreak=Saut de page

PageLayoutPropertyDescriptorProvider.PageLayout=Mise en page :
CrosstabSectionPage.RepeatColumnHeader=Répéter l'en-tête de colonne

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Générer une expression...>
ExpressionValueCellEditor.selectValueAction=<Sélectionner une valeur...>
ExpressionValueCellEditor.filterBy=<Filter by...>
ExpressionValueCellEditor.title=Sélectionner une valeur
CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Sélectionnez une valeur de membre de colonne
CrosstabSortKeyBuilder.Label.SelRowMemberValue=Sélectionnez une valeur de membre de ligne
CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Sélectionnez une valeur de membre de colonne
CrosstabFilterConditionBuilder.Label.SelRowMemberValue=Sélectionnez une valeur de membre de ligne
CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=Niveau de groupe :
SelColumnMemberValue.Column.Level=Niveau
SelColumnMemberValue.Column.Value=Valeur
ChoiceSetFactory.choice.None=Aucun

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Erreur de récupération de la liste
SelectValueDialog.messages.error.selectVauleUnavailable=La valeur de l'expression ne peut pas être récupérée.
SelectValueDialog.noExpressionSet=Une expression n'a pas été définie
SelectValueDialog.retrieving=Récupération de la liste...
SelectValueDialog.selectValue=Sélectionner une valeur
SelectValueDialog.messages.info.selectVauleUnavailable=La liste de valeurs n'est pas disponible.

CrosstabPreferencePage.Title=Tableau croisé
CrosstabPreferencePage.filterLimit=Limite de filtre
CrosstabPreferencePage.filterLimit.prompt=Nombre maximum de valeurs à afficher :
CrosstabPreferencePage.Error.MaxRowInvalid=La valeur numérique est incorrecte.
CrosstabPreferencePage.autoDelBindings.Text=Toujours demander avant de supprimer des liaisons inutilisées.
CrosstabPreferencePage.promptGroup=Invite


###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=Changer le cube ?
CrosstabDataBinding.message.changeCube=Vous allez modifier la liaison des données du tableau croisé.  \n\nVoulez-vous effacer toutes les liaisons de colonnes de données ?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=Cube de données
