###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Mostrar/ocultar &niveles de grupo

AddLevelHandleAction_TransName=Mostrar/ocultar niveles de grupo

AddMesureViewHandleAction.DisplayName=Mostrar/ocultar &medidas

AddMesureViewHandleAction.TransName=Mostrar/ocultar medidas

AddSubTotalAction.LabelName=Total general

AddSubTotalAction.TransName=Editar totales

AddSubTotalAction.DisplayName=Tota&les

AddSubTotalAction.TotalName=TOTAL

CrosstabMenuBuilder.EditCubeAction.DisplayName=&Editar cubo de datos

DeleteDimensionViewHandleAction.TransName=Eliminar dimensión

DeleteDimensionViewHandleAction.DisplayName=Qui&tar

DeleteMeasureHandleAction.DisplayName=Qui&tar

DeleteMeasureHandleAction.TransName=Eliminar medida

AddComputedMesureHandleAction.DisplayName=Añadir &medida derivada

AddComputedMesureHandleAction.TransName=Añadir medida derivada

AddComputedSummaryDialog.Title=Medida derivada

AddComputedSummaryDialog.Label.Name=&Nombre:

AddComputedSummaryDialog.Label.Expression=&Expresión:

AddComputedSummaryDialog.Label.DataType=Tipo de &datos:

AddComputedSummaryDialog.ErrMsg.Msg1=El nombre de medida no puede estar vacío.

AddComputedSummaryDialog.ErrMsg.Msg2=El nombre de medida ya existe.

AddComputedSummaryDialog.ErrMsg.Msg3=La expresión no puede estar vacía.

ShowAsViewAction.DisplayName=Mostrar como

ShowAsViewAction.TransName=Mostrar como

MeasureComboPropertyDescriptorProvider.TransName=Cambiar la orientación de la tabla de referencias cruzadas

MeasureHandleDropAdapter_trans_name=Añadir medida

###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Añadir dimensión

AddMeasureViewHandleCommand.TransName=Añadir medida

AddRelativeTimePeriodAction_action_label=Añadir período de tiempo re&lativo

AddRelativeTimePeriodAction_trans_label=Añadir período de tiempo relativo

ChangeAreaCommand.TransName=Suprimir dimensión

ChangeMeasureOrderCommand.TransName=Cambiar orden de medida

CreateDimensionViewCommand.TransName=Crear dimensión

CreateMeasureViewCommand.TransName=Crear medida

MergeCrosstabHeaderCellAction_name=&Combinar celdas de encabezado

SplitCrosstabHeadCellAction_name=&Dividir celda de encabezado

ExtendedDataColumnXtabDropAdapter.trans.add=Añadir {0}

###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tabla de referencias cruzadas
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.AggregateOn=Agregar en

GrandTotalProvider.Column.DataField=Campo de datos

GrandTotalProvider.Column.View=Ver

GrandTotalProvider.Column.Position=Posición

GrandTotalProvider.Column.Function=Funciones

GrandTotalProvider.ViewStatus=Mantener vista actual

GrandTotalProvider.ShowAs=Mostrar como {0}

SubTotalProvider.Column.DataField=Campo de datos

SubTotalProvider.Column.Function=Funciones

SubTotalProvider.Column.AggregateOn=Agregar en

SubTotalProvider.Column.ViewStatus=Mantener vista actual

SubTotalProvider.Column.View=Ver

SubTotalProvider.Column.Position=Posición

SubTotalProvider.ShowAs=Mostrar como {0}

LevelViewDialog.Title=Mostrar/ocultar niveles de grupo

LevelViewDialog.Label.Info=Seleccionar niveles para mostrar en tabla de referencias cruzadas:

LevelViewDialog.Button.Regular.Text=G&rupo regular

LevelViewDialog.Button.Date.Text=&Grupo de fecha

AggregationDialog.Title=Totales

AggregationDialog.Label.Grand=Totales generales:

AggregationDialog.Label.Sub=Subtotales:

AggregationDialog.TabItem.Title.RowArea=Área de fila

AggregationDialog.TabItem.Title.ColumnArea=Área de columna

ShowSummaryFieldDialog.Title=Mostrar/ocultar medidas

ShowSummaryFieldDialog.Label.Info=Seleccionar medida para mostrar en Tabla de referencias cruzadas:

ShowSummaryFieldDialog.Column.Measures=Medidas

ShowSummaryFieldDialog.Column.View=Vistas

ShowSummaryFieldDialog.ViewStatus=Mantener vista actual

DeleteBindingDialog.Title=¿Eliminar los enlaces no utilizados?

DeleteBindingDialog.Message=Esta acción producirá enlaces de datos no utilizados.\n\n¿Desea eliminar los enlaces no utilizados?

DeleteBindingDialog.ToggleMessage=&Recordar mi decisión
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Área de columna

AreaNodeProvider.RowArea=Área de fila

AreaNodeProvider.DetailArea=Área de detalle

CrossTabViewNodeProvider.ColumnArea=Área de columna

CrossTabViewNodeProvider.RowArea=Área de fila

CrossTabCellNodeProvider.Cell=Celda

CrossTabLevelNodeProvider.Level=Nivel -

CrossTabMeasureNodeProvider.Detail=Detalle -

MeasureSubNodeProvider.Header=Encabezado

MeasureSubNodeProvider.Detail=Detalle

MeasureSubNodeProvider.Aggregation=Agregación

CrosstabSortingModelProvider.ColumnName.GroupLevel=Nivel de grupo

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Error

SortkeyBuilder.DialogTitle.Label.Key=&Clave:

CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=Destino

CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=&Nivel de grupo:

SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Hacer clic para llamar al compilador de expresiones

SortkeyBuilder.DialogTitle.Label.Direction=Di&rección

SortkeyBuilder.Label.Locale=&Configuración regional:

SortkeyBuilder.Label.Strength=&Intensidad:

SortkeyBuilder.Locale.Auto=Automático

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=General

CrosstabPageGenerator.List.Margin=Margen

CrosstabPageGenerator.List.Font=Fuente

CrosstabPageGenerator.List.Borders=Borde

CrosstabPageGenerator.List.Section=Salto de página

CrosstabPageGenerator.List.Visibility=Visibilidad

CrosstabPageGenerator.List.TOC=Tabla de contenido

CrosstabPageGenerator.List.Bookmark=Marcador

CrosstabPageGenerator.List.NamedExpressions=Expresiones con nombre

CrosstabPageGenerator.List.UserProperties=Propiedades de usuario

CrosstabPageGenerator.List.AdvancedProperty=Avanzada

CrosstabPageGenerator.List.EmptyRowColumn=Vaciar filas/columnas

CrosstabPageGenerator.TabItem.Binding=Enlace

CrosstabPageGenerator.TabItem.RowArea=Área de fila

CrosstabPageGenerator.TabItem.ColumnArea=Área de columna

CrosstabPageGenerator.TabItem.DetailArea=Área de detalle

CrosstabPageGenerator.TabItem.Filters=Filtros

CrosstabPageGenerator.TabItem.Highlights=Resaltados

CrosstabPageGenerator.TabItem.map=Asignar

CrosstabPageGenerator.TabItem.Sorting=Ordenar

CrosstabGeneralPage.ForEmptyCell=En las celdas vacías, &mostrar:

LayoutMeasuresSection.DisplayName=O&rientación:

CrosstabGeneralPage.HideMeasureHeader=&Ocultar encabezado de medidas

###########################################################
#CrosstabEventHandlerPage properties
CrosstabEventHandlerPage.dialog.Browse=&Examinar...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Ordenar según:

Element.ReportItem.dataSet=Conjunto de datos:

Element.ReportElement.Cube=Da&tos:

BindingPage.None=Ninguno

FilterHandleProvider.Label.Filterby=Filtrar por:

###########################################################
#EmptyRowColumnProvider properties
EmptyRowColumnPage.Label.Text=Seleccione la casilla de verificación si las filas y columnas vacías deben aparecer en un nivel de tabla de referencias cruzadas.

EmptyRowColumnProvider.RowView.Button.Text=Mostrar &filas vacías

EmptyRowColumnProvider.ColumnView.Button.Text=Mostrar &columnas vacías

###########################################################
#CategoryPageGenerator properties
CategoryPageGenerator.TabItem.Attributes=Propiedades


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogMessage.Edit=

FilterConditionBuilder.DialogMessage.New=

FilterConditionBuilder.DialogTitle.New=Nueva condición de filtro

FilterConditionBuilder.DialogTitle.Edit=Editar condición de filtro

FilterConditionBuilder.choice.ValueOfThisDataItem=Valor de este elemento de datos

FilterConditionBuilder.tooltip.ExpBuilder=Hacer clic para llamar al compilador de expresiones.

FilterConditionBuilder.text.AND=Y

FilterConditionBuilder.text.Condition=&Condición de filtro:

FilterConditionBuilder.text.GroupLevel=Nivel de &grupo:

FilterConditionBuilder.list.item1=Valor

FilterConditionBuilder.button.edit=&Editar...

FilterConditionBuilder.button.delete=Eli&minar

FilterConditionBuilder.button.deleteall=Elimi&nar todos

FilterConditionBuilder.button.add=&Añadir

FilterConditionBuilder.button.edit.tooltip=Editar la selección en lista de valores

FilterConditionBuilder.button.delete.tooltip=Eliminar el valor seleccionado de la lista

FilterConditionBuilder.button.deleteall.tooltip=Eliminar todos los valores de la lista

FilterConditionBuilder.button.add.tooltip=Añadir el valor a la lista de valores

CrosstabFilterConditionBuilder.Item.Decorator=--------

CrosstabFilterConditionBuilder.Button.Detal=&Detalle

CrosstabFilterConditionBuilder.Item.SelectLevel=---Seleccionar nivel---

CrosstabFilterConditionBuilder.Item.SelectMeasure=---Seleccionar medida---

CrosstabFilterConditionBuilder.DialogMessage.New=Seleccione el nivel de grupo de destino o medida a la que aplicar el filtro y, a continuación, establezca la condición de filtro.

CrosstabFilterConditionBuilder.DialogMessage.Edit=Seleccione el nivel de grupo de destino o medida a la que aplicar el filtro y, a continuación, establezca la condición de filtro.

CrosstabFilterConditionBuilder.label.value=Valor

CrosstabFilterConditionBuilder.Label.Target=Destino:

CrosstabFilterConditionBuilder.Button.GroupLevel=&Nivel de grupo

CrosstabFilterConditionBuilder.Button.Measure=&Medida

CrosstabFilterConditionBuilder.Button.Cube=&Cubo

FilterbyTree.Bindings.Catogory.Measures=Medida

FilterbyTree.Bindings.Catogory.Dimension=Dimensión

FilterbyTree.Bindings.Catogory.GrandTotal=Total general

FilterbyTree.Bindings.Catogory.SubTotal=Subtotal

FilterbyTree.Bindings.Catogory.OtherType=Otro tipo

FilterbyTree.Bindings.Catogory.Undefined=sin definir

FilterbyTree.Title=Filtrar por

FilterbyTree.Message=Filtrar por

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Suprimir los campos de datos para definir aquí las columnas

Blank.text.row=Suprimir los campos de datos\npara definir aquí las filas

Blank.text.measure=Suprimir los campos de datos para resumirlos aquí

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Total general

CrosstabGrandTotalDialog.Text.DataField=&Campo de datos:

CrosstabGrandTotalDialog.Text.Function=&Función:


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=Nivel de grupo

CrosstabPageBreakProvider.Column.Before=Antes

CrosstabPageBreakProvider.Column.After=Después

CrosstabPageBreakProvider.Column.Inside=Interior

CrosstabPageBreakProvider.Column.Interval=Intervalo

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Agregar en

CrosstabSubToatalProvider.Column.DataField=Campo de datos

CrosstabSubToatalProvider.Column.Function=Función

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Salto de página

CrosstabPageBreakDialog.Text.GroupLevel=&Nivel de grupo:

CrosstabPageBreakDialog.Text.PageBreakBefore=&Antes:

CrosstabPageBreakDialog.Text.PageBreakAfter=&Después:

CrosstabPageBreakDialog.Text.PageBreakInside=&Interior:

CrosstabPageBreakDialog.Text.PageBreakInterval=&Intervalo de salto de página:

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Subtotal

SubTotalDialog.Text.AggregateOn=&Agregar en:

SubTotalDialog.Text.Function=&Función:

SubTotalDialog.Text.DataField=&Campo de datos:

FormPage.Menu.ModifyProperty=Modificar

CrosstabPageGenerator.List.SubTotals=Subtotales

CrosstabPageGenerator.List.GrandTotals=Totales generales

CrosstabPageGenerator.List.PageBreak=Salto de página

PageLayoutPropertyDescriptorProvider.PageLayout=Diseño de página:

RowPageBreak.RepeatColumnHeader=Repetir &encabezado de columna

ColumnPageBreak.RepeatRowHeader=Re&petir encabezado de fila

###########################################################
#ExpressionValueCellEditor properties
ExpressionValueCellEditor.buildExpressionAction=<Compilar expresión...>

ExpressionValueCellEditor.selectValueAction=<Seleccionar valor...>

ExpressionValueCellEditor.filterBy=<Filtrar por...>

ExpressionValueCellEditor.title=Seleccionar valor

CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Seleccionar columna Valor de miembro

CrosstabSortKeyBuilder.Label.SelRowMemberValue=Seleccionar fila Valor de miembro

CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Seleccionar columna Valor de miembro

CrosstabFilterConditionBuilder.Label.SelRowMemberValue=Seleccionar fila Valor de miembro

CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=Nivel de &grupo:

CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=Me&dida:

SelColumnMemberValue.Column.Level=Nivel

SelColumnMemberValue.Column.Value=Valor

ChoiceSetFactory.choice.None=Ninguno

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Error al recuperar la lista

SelectValueDialog.messages.error.selectVauleUnavailable=No se puede recuperar el valor de la expresión.

SelectValueDialog.noExpressionSet=No se ha ajustado ninguna expresión

SelectValueDialog.retrieving=Recuperando lista...

SelectValueDialog.selectValue=Seleccionar valor

SelectValueDialog.messages.info.selectVauleUnavailable=La lista de valores no está disponible.

CrosstabPreferencePage.Title=Tabla de referencias cruzadas

CrosstabPreferencePage.filterLimit=Límite de filtro

CrosstabPreferencePage.filterLimit.prompt=Número máximo de &valores que mostrar:

CrosstabPreferencePage.Error.MaxRowInvalid=El valor de número no es válido.

CrosstabPreferencePage.autoDelBindings.Text=Eliminar los enlaces no utilizados después de los cambios estructurales de la tabla de referencias cruzadas

CrosstabPreferencePage.autoDelBindings.Text.Prompt=&Solicitar

CrosstabPreferencePage.autoDelBindings.Text.Always=S&iempre

CrosstabPreferencePage.autoDelBindings.Text.Never=&Nunca

CrosstabPreferencePage.promptGroup=Solicitar

CrosstabPreferencePage.cubePopup.Text=Su&gerencia después de colocar los campos en la tabla de referencias cruzadas y crear un cubo correctamente.

###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=¿Cambiar cubo?

CrosstabDataBinding.message.changeCube=Va a cambiar el enlace de datos de la tabla de referencias cruzadas.  \n\n¿Desea borrar todos los enlaces de columna de datos existentes?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=Cubo de datos

CubeBuilder.warning.title=Tabla de referencias cruzadas

CubeBuilder.warning.message=Se ha creado un cubo de datos correctamente.\nPara terminar de crear una tabla de referencias cruzadas, arrastre los campos desde el cubo de datos que ha creado hasta el contenedor de tablas de referencias cruzadas.

CubeBuilder.warning.prompt=No &volver a mostrar este mensaje

###########################################################
#Crosstab drag tracker
CrosstabColumnDragTracker.ResizeColumn=Cambiar tamaño de columna

CrosstabColumnDragTracker.Show.Label=Ancho:

CrosstabRowDragTracker.Show.Label=Altura:

###########################################################
#AggregationCellTextViewProvider
AggregationCellTextViewProvider.displayName=Texto


###########################################################
#CrosstabSortKeyBuilder properties
CrosstabSortKeyBuilder.choice.ValueOfThisDataItem=Valor de este elemento de datos

CrosstabSortKeyBuilder.tooltip.ExpBuilder=Abrir el compilador de expresiones

CrosstabSortKeyBuilder.MSG.CreateNew=Nuevo...

InsertCubeInLayoutAction.menu.text=&Editar

InsertCubeInLayoutAction.action.text=I&nsertar en diseño

InsertCubeInLayoutAction.action.message=Crear tabla de referencias cruzadas desde cubo

MapRuleBuilderDialog.MsgDlg.Title=Advertencia

MapRuleBuilderDialog.MsgDlg.Msg=El valor no puede estar vacío.

LevelHandleDropAdapter.ActionText=Añadir una dimensión

LevelPropertyDialog.MSG.CreateNew=


###########################################################
#CrosstabHighlightRuleBuilder properties
CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstab=tabla de referencias cruzadas

CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstabcell=celda de tabla de referencias cruzadas

CrosstabHighlightRuleBuilderDialog.text.Description.Element.ReportElement=elemento de informe

CrosstabHighlightRuleBuilderDialog.text.Description=Aplique formato condicional a {0}. Especifique la expresión y el formato condicional.\nEl formato se aplicará si la expresión se evalúa con True.

###########################################################
#CrosstabFilterConditionBuilder properties
CrosstabFilterConditionBuilder.ExpressionEditor.Title=Editor de expresión

CrosstabFilterConditionBuilder.MsgDlg.Msg=Advertencia

CrosstabFilterConditionBuilder.MsgDlg.Title=El valor no puede estar vacío.

CrosstabFilterConditionBuilder.Button.UpdateAggregation=Recalcular &totales

###########################################################
#Breadcrumb provider properties
VirtualCrosstabCellNodeProvider.Display.ColumnArea=Área de columna

VirtualCrosstabCellNodeProvider.Display.DetailArea=Área de detalle

VirtualCrosstabCellNodeProvider.Display.RowArea=Área de fila

VirtualCrosstabCellNodeProvider.Display.UnknownArea=Área desconocida

CrosstabBindingComboPropertyDescriptorProvider.Flag.DataModel=\ (Modelo de datos)

CrosstabBindingRefresh.action.message=Actualizar enlaces de tabla de referencias cruzadas
