###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Mostrar/ocultar niveles de grupo
AddLevelHandleAction_TransName=Mostrar/ocultar niveles de grupo
AddMesureViewHandleAction.DisplayName=Mostrar/ocultar medidas
AddMesureViewHandleAction.TransName=Mostrar/ocultar medidas
AddSubTotalAction.LabelName=Total general
AddSubTotalAction.TransName=Agregación
AddSubTotalAction.DisplayName=Agregación
AddSubTotalAction.TotalName=TOTAL
CrosstabMenuBuilder.EditCubeAction.DisplayName=Editar cubo de datos
DeleteDimensionViewHandleAction.TransName=Eliminar Dimensionviewhandle
DeleteDimensionViewHandleAction.DisplayName=Quitar
DeleteMeasureHandleAction.DisplayName=Quitar
DeleteMeasureHandleAction.TransName=Eliminar MeasureViewHandle
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Agregar DiminsionHandle
AddMeasureViewHandleCommand.TransName=Agregar MeasureHandle
ChangeAreaCommand.TransName=Suprimir controlador de dimensión
ChangeMeasureOrderCommand.TransName=Cambiar el orden de las medidas
CreateDimensionViewCommand.TransName=Crear DiminsionViewHandle
CreateMeasureViewCommand.TransName=Crear MeasureViewHandle
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tabla de referencias cruzadas
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Campo de datos
GrandTotalProvider.Column.Function=Función
SubTotalProvider.Column.DataField=Campo de datos
SubTotalProvider.Column.Function=Función
SubTotalProvider.Column.AggregateOn=Agregar en
LevelViewDialog.Title=Mostrar/ocultar niveles de grupo
LevelViewDialog.Label.Info=Seleccionar niveles para mostrar en tabla de referencias cruzadas:
AggregationDialog.Title=Agregación
AggregationDialog.Label.Grand=Totales generales:
AggregationDialog.Label.Sub=Subtotales:
ShowSummaryFieldDialog.Title=Mostrar/ocultar campos de resumen
ShowSummaryFieldDialog.Label.Info=Seleccionar niveles para mostrar en tabla de referencias cruzadas:
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Área de columna
AreaNodeProvider.RowArea=Área de fila
AreaNodeProvider.DetailArea=Área de detalle
CrossTabViewNodeProvider.ColumnArea=Área de columna
CrossTabViewNodeProvider.RowArea=Área de fila
CrosstTabCellNodeProvider.Cell=Celda
CrosstTabLevelNodeProvider.Level=Nivel - 
CrosstTabMeasureNodeProvider.Detail=Detalle - 
MeasureSubNodeProvider.Header=Encabezado
MeasureSubNodeProvider.Detail=Detalle
MeasureSubNodeProvider.Aggregation=Agregación

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Error
SortkeyBuilder.DialogTitle.Label.Key=Clave:
CrosstabSortingModelProvider.ColumnName.GroupLevel=Nivel de grupo
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Nivel de grupo:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Hacer clic para llamar al compilador de expresiones
SortkeyBuilder.DialogTitle.Label.Direction=Dirección:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=General
CrosstabPageGenerator.List.Margin=Margen
CrosstabPageGenerator.List.Font=Fuente
CrosstabPageGenerator.List.Borders=Borde
CrosstabPageGenerator.List.Section=Salto de página
CrosstabPageGenerator.List.Visibility=Visibilidad
CrosstabPageGenerator.List.TOC=Tabla de contenido
CrosstabPageGenerator.List.Bookmark=Marcador
CrosstabPageGenerator.List.NamedExpressions=Expresiones con nombre
CrosstabPageGenerator.List.UserProperties=Propiedades de usuario
CrosstabPageGenerator.List.AdvancedProperty=Avanzada

CrosstabPageGenerator.TabItem.Binding=Enlace
CrosstabPageGenerator.TabItem.RowArea=Área de fila
CrosstabPageGenerator.TabItem.ColumnArea=Área de columna
CrosstabPageGenerator.TabItem.DetailArea=Área de detalle
CrosstabPageGenerator.TabItem.Filters=Filtros
CrosstabPageGenerator.TabItem.Highlights=Resaltados
CrosstabPageGenerator.TabItem.map=Asignar
CrosstabPageGenerator.TabItem.Sorting=Ordenar

CrosstabGeneraPage.ForEmptyCell=En las celdas vacias, mostrar:
CrosstabGeneraPage.FormatOption=Opciones de formato:
LayoutMeasuresProvider.DisplayName=Campos de datos de diseño en área de detalle verticalmente


parameterBinding.title=Enlace de parámetros de conjunto de datos...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Ordenar según:
Element.ReportItem.dataSet=Conjunto de datos:
Element.ReportElement.Cube=&Datos:
BindingPage.None=Ninguno


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Propiedades


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
