###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Gruppenebenen einblenden/ausblenden
AddLevelHandleAction_TransName=Gruppenebenen einblenden/ausblenden
AddMesureViewHandleAction.DisplayName=Maßeinheiten einblenden/ausblenden
AddMesureViewHandleAction.TransName=Maßeinheiten einblenden/ausblenden
AddSubTotalAction.LabelName=Gesamtsumme
AddSubTotalAction.TransName=Aggregat
AddSubTotalAction.DisplayName=Summen
AddSubTotalAction.TotalName=GESAMT
CrosstabMenuBuilder.EditCubeAction.DisplayName=Datenquader bearbeiten
DeleteDimensionViewHandleAction.TransName=Dimensionviewhandle löschen
DeleteDimensionViewHandleAction.DisplayName=Entfernen
DeleteMeasureHandleAction.DisplayName=Entfernen
DeleteMeasureHandleAction.TransName=MeasureViewHandle löschen
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=DimensionHandle hinzufügen
AddMeasureViewHandleCommand.TransName=MeasureHandle hinzufügen
ChangeAreaCommand.TransName=DimensionHandle verwerfen
ChangeMeasureOrderCommand.TransName=Reihenfolge der Maßeinheiten ändern
CreateDimensionViewCommand.TransName=DimensionHandle erstellen
CreateMeasureViewCommand.TransName=MeasureViewHandle erstellen
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Kreuztabelle
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Datenfeld
GrandTotalProvider.Column.Function=Funktion
SubTotalProvider.Column.DataField=Datenfeld
SubTotalProvider.Column.Function=Funktion
SubTotalProvider.Column.AggregateOn=Aggregat ein
LevelViewDialog.Title=Gruppenebenen einblenden/ausblenden
LevelViewDialog.Label.Info=Ebenen zum Anzeigen in Kreuztabelle auswählen:
AggregationDialog.Title=Summen
AggregationDialog.Label.Grand=Gesamtsummen:
AggregationDialog.Label.Sub=Zwischensumme:
ShowSummaryFieldDialog.Title=Zusammenfassungsfelder einblenden/ausblenden
ShowSummaryFieldDialog.Label.Info=Ebenen zum Anzeigen in Kreuztabelle auswählen:

DeleteBindingDialog.Title=Remove Unused Bindings?
DeleteBindingDialog.Message=This action will result in unused data bindings.\n\nDo you wish to remove unused bindings?
DeleteBindingDialog.ToggleMessage=Don't show this message again
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Spaltenbereich
AreaNodeProvider.RowArea=Zeilenbereich
AreaNodeProvider.DetailArea=Detailbereich
CrossTabViewNodeProvider.ColumnArea=Spaltenbereich
CrossTabViewNodeProvider.RowArea=Zeilenbereich
CrosstTabCellNodeProvider.Cell=Zelle
CrosstTabLevelNodeProvider.Level=Ebene - 
CrosstTabMeasureNodeProvider.Detail=Detail - 
MeasureSubNodeProvider.Header=Kopfzeile
MeasureSubNodeProvider.Detail=Detail
MeasureSubNodeProvider.Aggregation=Aggregat

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Fehler
SortkeyBuilder.DialogTitle.Label.Key=Schlüssel:
CrosstabSortingModelProvider.ColumnName.GroupLevel=Gruppenebene
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Gruppenebene:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Zum Öffnen der Ausdruckserstellung hier klicken
SortkeyBuilder.DialogTitle.Label.Direction=Richtung:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=Allgemein
CrosstabPageGenerator.List.Margin=Rand
CrosstabPageGenerator.List.Font=Schriftart
CrosstabPageGenerator.List.Borders=Rahmen
CrosstabPageGenerator.List.Section=Seitenumbruch
CrosstabPageGenerator.List.Visibility=Sichtbarkeit
CrosstabPageGenerator.List.TOC=Inhaltsverzeichnis
CrosstabPageGenerator.List.Bookmark=Lesezeichen
CrosstabPageGenerator.List.NamedExpressions=Benannte Ausdrücke
CrosstabPageGenerator.List.UserProperties=Benutzereigenschaften
CrosstabPageGenerator.List.AdvancedProperty=Erweitert

CrosstabPageGenerator.TabItem.Binding=Bindung
CrosstabPageGenerator.TabItem.RowArea=Zeilenbereich
CrosstabPageGenerator.TabItem.ColumnArea=Spaltenbereich
CrosstabPageGenerator.TabItem.DetailArea=Detailbereich
CrosstabPageGenerator.TabItem.Filters=Filter
CrosstabPageGenerator.TabItem.Highlights=Kennzeichnungen
CrosstabPageGenerator.TabItem.map=Zuordnung
CrosstabPageGenerator.TabItem.Sorting=Sortierung

CrosstabGeneraPage.ForEmptyCell=Leere Zellen anzeigen als:
CrosstabGeneraPage.FormatOption=Formatierungsoptionen:
LayoutMeasuresProvider.DisplayName=Datenfelder im Detailbereich vertikal darstellen


parameterBinding.title=Parameterbindung für Datensatz...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Sortieren nach:
Element.ReportItem.dataSet=Datensatz:
Element.ReportElement.Cube=&Daten:
BindingPage.None=Ohne


FilterHandleProvider.Label.Filterby=Filtern nach:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Eigenschaften


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=Neue Filterbedingung
FilterConditionBuilder.DialogTitle.Edit=Filterbedingung bearbeiten
FilterConditionBuilder.choice.ValueOfThisDataItem=Wert dieses Datenelements
FilterConditionBuilder.tooltip.ExpBuilder=Zum Öffnen der Ausdruckserstellung hier klicken.
FilterConditionBuilder.text.AND=UND
FilterConditionBuilder.text.Condition=Filterbedingung eingeben:
FilterConditionBuilder.text.GroupLevel=Gruppenebene:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Datenfeld/er verwerfen, um Spalten hier zu definieren
Blank.text.row=Datenfeld/er verwerfen,\num Zeilen hier zu definieren
Blank.text.measure=Datenfeld/er verwerfen, um sie hier zusammenzufassen

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Gesamtsumme
CrosstabGrandTotalDialog.Text.DataField=Datenfeld:
CrosstabGrandTotalDialog.Text.Function=Funktion:


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=Gruppenebene
CrosstabPageBreakProvider.Column.Before=Vor
CrosstabPageBreakProvider.Column.After=Nach

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Aggregate On
CrosstabSubToatalProvider.Column.DataField=Datenfeld
CrosstabSubToatalProvider.Column.Function=Funktion

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Seitenumbruch
CrosstabPageBreakDialog.Text.GroupLevel=Gruppenebene:
CrosstabPageBreakDialog.Text.PageBreakBefore=Vorher:
CrosstabPageBreakDialog.Text.PageBreakAfter=Nachher:

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Zwischensumme
SubTotalDialog.Text.AggregateOn=Aggregat ein:
SubTotalDialog.Text.Function=Funktion:
SubTotalDialog.Text.DataField=Datenfeld:

FormPage.Menu.ModifyProperty=Bearbeiten

CrosstabPageGenerator.List.SubTotals=Zwischensumme
CrosstabPageGenerator.List.GrandTotals=Gesamtsummen
CrosstabPageGenerator.List.PageBreak=Seitenumbruch

PageLayoutPropertyDescriptorProvider.PageLayout=Seitenlayout:
CrosstabSectionPage.RepeatColumnHeader=Spaltenüberschrift wiederholen

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Ausdruckserstellung ...>
ExpressionValueCellEditor.selectValueAction=<Wert auswählen ...>
ExpressionValueCellEditor.title=Wert auswählen
CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Gruppenebene
CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Mitgliedswert der Spalte auswählen
SelColumnMemberValue.Column.Level=Ebene
SelColumnMemberValue.Column.Value=Wert
ChoiceSetFactory.choice.None=Ohne

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Fehler beim Abrufen der Liste
SelectValueDialog.messages.error.selectVauleUnavailable=Der Wert für den Ausdruck kann nicht abgerufen werden.
SelectValueDialog.noExpressionSet=Ein Ausdruck wurde nicht angegeben.
SelectValueDialog.retrieving=Liste wird abgerufen ...
SelectValueDialog.selectValue=Wert auswählen
SelectValueDialog.messages.info.selectVauleUnavailable=Werteliste ist nicht verfügbar.

CrosstabPreferencePage.Title=Kreuztabelle
CrosstabPreferencePage.filterLimit=Filter-Limit
CrosstabPreferencePage.filterLimit.prompt=Maximale Anzahl anzuzeigender Werte:
CrosstabPreferencePage.Error.MaxRowInvalid=Der numerische Wert ist ungültig.
CrosstabPreferencePage.autoDelBindings.Text=Always ask before removing unused bindings.
CrosstabPreferencePage.promptGroup=Prompt


###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=Quader ändern?
CrosstabDataBinding.message.changeCube=Sie sind im Begriff, die Datenbindung der Kreuztabelle zu ändern.\n\nMöchten Sie alle bestehenden Datenspaltenbindungen löschen?
