###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=그룹 수준 표시/숨기기(&G)

AddLevelHandleAction_TransName=그룹 수준 표시/숨기기

AddMesureViewHandleAction.DisplayName=측정값 표시/숨기기(&M)

AddMesureViewHandleAction.TransName=측정 표시/숨기기

AddSubTotalAction.LabelName=총합계

AddSubTotalAction.TransName=합계 편집

AddSubTotalAction.DisplayName=합계(&L)

AddSubTotalAction.TotalName=합계

CrosstabMenuBuilder.EditCubeAction.DisplayName=데이터 큐브 편집(&E)

DeleteDimensionViewHandleAction.TransName=차원 삭제

DeleteDimensionViewHandleAction.DisplayName=제거(&V)

DeleteMeasureHandleAction.DisplayName=제거(&V)

DeleteMeasureHandleAction.TransName=측정값 삭제

AddComputedMesureHandleAction.DisplayName=파생 측정값 추가(&M)

AddComputedMesureHandleAction.TransName=파생 측정값 추가

AddComputedSummaryDialog.Title=파생 측정값

AddComputedSummaryDialog.Label.Name=이름(&N):

AddComputedSummaryDialog.Label.Expression=식(&E):

AddComputedSummaryDialog.Label.DataType=데이터 형식(&D):

AddComputedSummaryDialog.ErrMsg.Msg1=측정값 이름은 비어 있으면 안 됩니다.

AddComputedSummaryDialog.ErrMsg.Msg2=측정값 이름이 이미 있습니다.

AddComputedSummaryDialog.ErrMsg.Msg3=식은 비어 있으면 안 됩니다.

ShowAsViewAction.DisplayName=표시

ShowAsViewAction.TransName=표시

MeasureComboPropertyDescriptorProvider.TransName=크로스 탭 방향 변경

MeasureHandleDropAdapter_trans_name=측정값 추가

###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=차원 추가

AddMeasureViewHandleCommand.TransName=측정값 추가

AddRelativeTimePeriodAction_action_label=상대 시간 추가(&L)

AddRelativeTimePeriodAction_trans_label=상대 시간 추가

ChangeAreaCommand.TransName=차원 놓기

ChangeMeasureOrderCommand.TransName=측정값 순서 변경

CreateDimensionViewCommand.TransName=차원 생성

CreateMeasureViewCommand.TransName=측정값 생성

MergeCrosstabHeaderCellAction_name=머리글 셀 병합(&M)

SplitCrosstabHeadCellAction_name=머리글 셀 분할(&S)

ExtendedDataColumnXtabDropAdapter.trans.add={0} 추가

###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=크로스 탭
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.AggregateOn=집계 대상

GrandTotalProvider.Column.DataField=데이터 필드

GrandTotalProvider.Column.View=보기

GrandTotalProvider.Column.Position=위치

GrandTotalProvider.Column.Function=함수

GrandTotalProvider.ViewStatus=현재 보기 유지

GrandTotalProvider.ShowAs={0}(으)로 표시

SubTotalProvider.Column.DataField=데이터 필드

SubTotalProvider.Column.Function=함수

SubTotalProvider.Column.AggregateOn=집계 대상:

SubTotalProvider.Column.ViewStatus=현재 보기 유지

SubTotalProvider.Column.View=보기

SubTotalProvider.Column.Position=위치

SubTotalProvider.ShowAs={0}(으)로 표시

LevelViewDialog.Title=그룹 수준 표시/숨기기

LevelViewDialog.Label.Info=크로스 탭에 표시할 수준 선택:

LevelViewDialog.Button.Regular.Text=일반 그룹(&R)

LevelViewDialog.Button.Date.Text=날짜 그룹(&D)

AggregationDialog.Title=전체

AggregationDialog.Label.Grand=총합계:

AggregationDialog.Label.Sub=부분합:

AggregationDialog.TabItem.Title.RowArea=행 영역

AggregationDialog.TabItem.Title.ColumnArea=열 영역

ShowSummaryFieldDialog.Title=측정 표시/숨기기

ShowSummaryFieldDialog.Label.Info=크로스 탭에 표시할 측정값 선택:

ShowSummaryFieldDialog.Column.Measures=측정값

ShowSummaryFieldDialog.Column.View=보기

ShowSummaryFieldDialog.ViewStatus=현재 보기 유지

DeleteBindingDialog.Title=사용하지 않는 바인딩을 제거하시겠습니까?

DeleteBindingDialog.Message=이 작업을 수행하면 사용하지 않는 데이터 바인딩이 발생합니다.\n\n사용하지 않는 바인딩을 제거하시겠습니까?

DeleteBindingDialog.ToggleMessage=선택 저장(&R)
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=열 영역

AreaNodeProvider.RowArea=행 영역

AreaNodeProvider.DetailArea=세부 영역

CrossTabViewNodeProvider.ColumnArea=열 영역

CrossTabViewNodeProvider.RowArea=행 영역

CrossTabCellNodeProvider.Cell=셀

CrossTabLevelNodeProvider.Level=수준 -

CrossTabMeasureNodeProvider.Detail=상세 정보 -

MeasureSubNodeProvider.Header=머리글

MeasureSubNodeProvider.Detail=상세 정보

MeasureSubNodeProvider.Aggregation=집계

CrosstabSortingModelProvider.ColumnName.GroupLevel=그룹 수준

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=오류

SortkeyBuilder.DialogTitle.Label.Key=키(&K):

CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=대상

CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=그룹 수준(&G):

SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=식 빌더를 호출하려면 누릅니다.

SortkeyBuilder.DialogTitle.Label.Direction=방향(&D):

SortkeyBuilder.Label.Locale=로케일(&L):

SortkeyBuilder.Label.Strength=수준(&S):

SortkeyBuilder.Locale.Auto=자동

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=일반

CrosstabPageGenerator.List.Margin=여백

CrosstabPageGenerator.List.Font=글꼴

CrosstabPageGenerator.List.Borders=테두리

CrosstabPageGenerator.List.Section=페이지 나누기

CrosstabPageGenerator.List.Visibility=표시 유형

CrosstabPageGenerator.List.TOC=목차

CrosstabPageGenerator.List.Bookmark=책갈피

CrosstabPageGenerator.List.NamedExpressions=명명된 식

CrosstabPageGenerator.List.UserProperties=사용자 속성

CrosstabPageGenerator.List.AdvancedProperty=고급

CrosstabPageGenerator.List.EmptyRowColumn=빈 행/열

CrosstabPageGenerator.TabItem.Binding=바인딩

CrosstabPageGenerator.TabItem.RowArea=행 영역

CrosstabPageGenerator.TabItem.ColumnArea=열 영역

CrosstabPageGenerator.TabItem.DetailArea=세부 영역

CrosstabPageGenerator.TabItem.Filters=필터

CrosstabPageGenerator.TabItem.Highlights=강조

CrosstabPageGenerator.TabItem.map=맵

CrosstabPageGenerator.TabItem.Sorting=정렬

CrosstabGeneralPage.ForEmptyCell=빈 셀의 경우 표시(&S):

LayoutMeasuresSection.DisplayName=방향(&R):

CrosstabGeneralPage.HideMeasureHeader=측정값 머리글 숨기기(&H)

###########################################################
#CrosstabEventHandlerPage properties
CrosstabEventHandlerPage.dialog.Browse=찾아보기(&B)...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=정렬 방법:

Element.ReportItem.dataSet=데이터 집합:

Element.ReportElement.Cube=데이터(&T):

BindingPage.None=없음

FilterHandleProvider.Label.Filterby=필터링 기준:

###########################################################
#EmptyRowColumnProvider properties
EmptyRowColumnPage.Label.Text=확인란을 사용하여 비어 있는 행과 열을 크로스 탭 수준에 표시할지 여부를 선택합니다.

EmptyRowColumnProvider.RowView.Button.Text=빈 행 표시(&R)

EmptyRowColumnProvider.ColumnView.Button.Text=빈 열 표시(&C)

###########################################################
#CategoryPageGenerator properties
CategoryPageGenerator.TabItem.Attributes=속성


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogMessage.Edit=

FilterConditionBuilder.DialogMessage.New=

FilterConditionBuilder.DialogTitle.New=새 필터 조건

FilterConditionBuilder.DialogTitle.Edit=필터 조건 편집

FilterConditionBuilder.choice.ValueOfThisDataItem=이 데이터 항목 값

FilterConditionBuilder.tooltip.ExpBuilder=식 빌더를 호출하려면 누릅니다.

FilterConditionBuilder.text.AND=및

FilterConditionBuilder.text.Condition=필터 조건(&C):

FilterConditionBuilder.text.GroupLevel=그룹 수준(&L):

FilterConditionBuilder.list.item1=값

FilterConditionBuilder.button.edit=편집(&E)...

FilterConditionBuilder.button.delete=제거(&M)

FilterConditionBuilder.button.deleteall=모두 제거(&O)

FilterConditionBuilder.button.add=추가(&A)

FilterConditionBuilder.button.edit.tooltip=값 목록에서 선택한 값 편집

FilterConditionBuilder.button.delete.tooltip=목록에서 선택한 값 삭제

FilterConditionBuilder.button.deleteall.tooltip=목록에서 모든 값 삭제

FilterConditionBuilder.button.add.tooltip=값 목록에 값 추가

CrosstabFilterConditionBuilder.Item.Decorator=--------

CrosstabFilterConditionBuilder.Button.Detal=상세 정보(&D)

CrosstabFilterConditionBuilder.Item.SelectLevel=---수준 선택---

CrosstabFilterConditionBuilder.Item.SelectMeasure=---측정값 선택---

CrosstabFilterConditionBuilder.DialogMessage.New=필터를 적용할 대상 그룹 수준 또는 측정값을 선택한 다음 필터 조건을 설정합니다.

CrosstabFilterConditionBuilder.DialogMessage.Edit=필터를 적용할 대상 그룹 수준 또는 측정값을 선택한 다음 필터 조건을 설정합니다.

CrosstabFilterConditionBuilder.label.value=값

CrosstabFilterConditionBuilder.Label.Target=대상:

CrosstabFilterConditionBuilder.Button.GroupLevel=그룹 수준(&G)

CrosstabFilterConditionBuilder.Button.Measure=측정값(&U)

CrosstabFilterConditionBuilder.Button.Cube=큐브(&C)

FilterbyTree.Bindings.Catogory.Measures=측정

FilterbyTree.Bindings.Catogory.Dimension=차원

FilterbyTree.Bindings.Catogory.GrandTotal=총합계

FilterbyTree.Bindings.Catogory.SubTotal=부분합

FilterbyTree.Bindings.Catogory.OtherType=다른 형식

FilterbyTree.Bindings.Catogory.Undefined=정의되지 않음

FilterbyTree.Title=필터링 기준

FilterbyTree.Message=필터링 기준

###########################################################
#VirtualCellEditPart.java
Blank.text.column=열을 정의하려면 데이터 필드를 여기에 내려 놓으십시오.

Blank.text.row=행을 정의하려면 데이터\n필드를 여기에 내려 놓으십시오.

Blank.text.measure=요약하려면 데이터 필드를 여기에 내려 놓으십시오.

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=총합계

CrosstabGrandTotalDialog.Text.DataField=데이터 필드(&D):

CrosstabGrandTotalDialog.Text.Function=함수(&F):


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=그룹 수준

CrosstabPageBreakProvider.Column.Before=전

CrosstabPageBreakProvider.Column.After=후

CrosstabPageBreakProvider.Column.Inside=안쪽

CrosstabPageBreakProvider.Column.Interval=간격

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=집계 대상

CrosstabSubToatalProvider.Column.DataField=데이터 필드

CrosstabSubToatalProvider.Column.Function=함수

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=페이지 나누기

CrosstabPageBreakDialog.Text.GroupLevel=그룹 수준(&G):

CrosstabPageBreakDialog.Text.PageBreakBefore=다음 이전(&B):

CrosstabPageBreakDialog.Text.PageBreakAfter=다음 이후(&A):

CrosstabPageBreakDialog.Text.PageBreakInside=안쪽(&I):

CrosstabPageBreakDialog.Text.PageBreakInterval=페이지 나누기 간격(&P):

###########################################################
#SubTotalDialog
SubTotalDialog.Title=부분합

SubTotalDialog.Text.AggregateOn=집계 대상(&A):

SubTotalDialog.Text.Function=함수(&F):

SubTotalDialog.Text.DataField=데이터 필드(&D):

FormPage.Menu.ModifyProperty=수정

CrosstabPageGenerator.List.SubTotals=부분합

CrosstabPageGenerator.List.GrandTotals=총합계

CrosstabPageGenerator.List.PageBreak=페이지 나누기

PageLayoutPropertyDescriptorProvider.PageLayout=페이지 레이아웃:

RowPageBreak.RepeatColumnHeader=열 머리글 반복(&C)

ColumnPageBreak.RepeatRowHeader=행 머리글 반복(&P)

###########################################################
#ExpressionValueCellEditor properties
ExpressionValueCellEditor.buildExpressionAction=<식 빌드...>

ExpressionValueCellEditor.selectValueAction=<값 선택...>

ExpressionValueCellEditor.filterBy=<필터링 기준...>

ExpressionValueCellEditor.title=값 선택

CrosstabSortKeyBuilder.Label.SelColumnMemberValue=열 구성원 값 선택

CrosstabSortKeyBuilder.Label.SelRowMemberValue=행 구성원 값 선택

CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=열 구성원 값 선택

CrosstabFilterConditionBuilder.Label.SelRowMemberValue=행 구성원 값 선택

CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=그룹 수준(&L):

CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=측정값(&S):

SelColumnMemberValue.Column.Level=수준

SelColumnMemberValue.Column.Value=값

ChoiceSetFactory.choice.None=없음

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=목록을 검색하는 도중 오류가 발생했습니다.

SelectValueDialog.messages.error.selectVauleUnavailable=식의 값을 검색할 수 없습니다.

SelectValueDialog.noExpressionSet=식이 설정되지 않았습니다.

SelectValueDialog.retrieving=목록 검색...

SelectValueDialog.selectValue=값 선택

SelectValueDialog.messages.info.selectVauleUnavailable=값 목록을 사용할 수 없습니다.

CrosstabPreferencePage.Title=크로스 탭

CrosstabPreferencePage.filterLimit=필터 제한

CrosstabPreferencePage.filterLimit.prompt=표시할 최대 값 수(&V):

CrosstabPreferencePage.Error.MaxRowInvalid=숫자 값이 잘못되었습니다.

CrosstabPreferencePage.autoDelBindings.Text=크로스 탭 구조 변경 후 사용하지 않는 바인딩 제거

CrosstabPreferencePage.autoDelBindings.Text.Prompt=묻기(&P)

CrosstabPreferencePage.autoDelBindings.Text.Always=항상(&L)

CrosstabPreferencePage.autoDelBindings.Text.Never=안 함(&N)

CrosstabPreferencePage.promptGroup=묻기

CrosstabPreferencePage.cubePopup.Text=필드를 크로스 탭으로 끌어 놓고 큐브를 생성한 후 힌트 제공(&H)

###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=큐브 변경?

CrosstabDataBinding.message.changeCube=교차 테이블의 데이터 바인딩을 변경하려고 합니다.  \n\n기존의 데이터 열 바인딩을 모두 지우시겠습니까?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=데이터 큐브

CubeBuilder.warning.title=크로스 탭

CubeBuilder.warning.message=데이터 큐브가 생성되었습니다.\n크로스 탭 생성을 종료하려면 생성된 데이터 큐브의 필드를 크로스 탭 컨테이너로 끌어 놓습니다.

CubeBuilder.warning.prompt=이 메시지를 다시 표시 안 함(&D)

###########################################################
#Crosstab drag tracker
CrosstabColumnDragTracker.ResizeColumn=열 크기 조정

CrosstabColumnDragTracker.Show.Label=너비:

CrosstabRowDragTracker.Show.Label=높이:

###########################################################
#AggregationCellTextViewProvider
AggregationCellTextViewProvider.displayName=텍스트


###########################################################
#CrosstabSortKeyBuilder properties
CrosstabSortKeyBuilder.choice.ValueOfThisDataItem=이 데이터 항목의 값

CrosstabSortKeyBuilder.tooltip.ExpBuilder=식 빌더 열기

CrosstabSortKeyBuilder.MSG.CreateNew=새로 만들기...

InsertCubeInLayoutAction.menu.text=편집(&E)

InsertCubeInLayoutAction.action.text=레이아웃에 삽입(&N)

InsertCubeInLayoutAction.action.message=큐브에서 크로스 탭 생성

MapRuleBuilderDialog.MsgDlg.Title=경고

MapRuleBuilderDialog.MsgDlg.Msg=값을 입력해야 합니다.

LevelHandleDropAdapter.ActionText=차원 추가

LevelPropertyDialog.MSG.CreateNew=


###########################################################
#CrosstabHighlightRuleBuilder properties
CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstab=크로스 탭

CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstabcell=크로스 탭 셀

CrosstabHighlightRuleBuilderDialog.text.Description.Element.ReportElement=보고서 요소

CrosstabHighlightRuleBuilderDialog.text.Description={0}에 조건부 서식을 적용합니다. 조건식 및 서식을 지정하십시오.\n조건식 계산 결과가 True인 경우 서식이 적용됩니다.

###########################################################
#CrosstabFilterConditionBuilder properties
CrosstabFilterConditionBuilder.ExpressionEditor.Title=식 편집기

CrosstabFilterConditionBuilder.MsgDlg.Msg=경고

CrosstabFilterConditionBuilder.MsgDlg.Title=값을 입력해야 합니다.

CrosstabFilterConditionBuilder.Button.UpdateAggregation=합계 다시 계산(&T)

###########################################################
#Breadcrumb provider properties
VirtualCrosstabCellNodeProvider.Display.ColumnArea=열 영역

VirtualCrosstabCellNodeProvider.Display.DetailArea=세부 영역

VirtualCrosstabCellNodeProvider.Display.RowArea=행 영역

VirtualCrosstabCellNodeProvider.Display.UnknownArea=알 수 없는 영역

CrosstabBindingComboPropertyDescriptorProvider.Flag.DataModel=\(데이터 모델)

CrosstabBindingRefresh.action.message=크로스 탭 바인딩 새로 고침
