###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Afficher/Masquer les niveaux de groupe
AddLevelHandleAction_TransName=Afficher/Masquer les niveaux de groupe
AddMesureViewHandleAction.DisplayName=Afficher/Masquer les mesures
AddMesureViewHandleAction.TransName=Afficher/Masquer les mesures
AddSubTotalAction.LabelName=Total global
AddSubTotalAction.TransName=Agrégation
AddSubTotalAction.DisplayName=Agrégation
AddSubTotalAction.TotalName=TOTAL
CrosstabMenuBuilder.EditCubeAction.DisplayName=Modifier cube de données
DeleteDimensionViewHandleAction.TransName=Supprimer Dimensionviewhandle
DeleteDimensionViewHandleAction.DisplayName=Supprimer
DeleteMeasureHandleAction.DisplayName=Supprimer
DeleteMeasureHandleAction.TransName=Supprimer MeasureViewHandle
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Ajouter DimensionHandle
AddMeasureViewHandleCommand.TransName=Ajouter MeasureHandle
ChangeAreaCommand.TransName=Ignorer le descripteur de dimension
ChangeMeasureOrderCommand.TransName=Modifier l'ordre de mesure
CreateDimensionViewCommand.TransName=Créer DimensionViewHandle
CreateMeasureViewCommand.TransName=Créer MeasureViewHandle
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tableau croisé
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Champ de données
GrandTotalProvider.Column.Function=Fonction
SubTotalProvider.Column.DataField=Champ de données
SubTotalProvider.Column.Function=Fonction
SubTotalProvider.Column.AggregateOn=Regrouper par
LevelViewDialog.Title=Afficher/Masquer les niveaux de groupe
LevelViewDialog.Label.Info=Sélectionner les niveaux à afficher sur le tableau croisé :
AggregationDialog.Title=Agrégation
AggregationDialog.Label.Grand=Totaux généraux :
AggregationDialog.Label.Sub=Sous-totaux :
ShowSummaryFieldDialog.Title=Afficher/Masquer les champs de récapitulation
ShowSummaryFieldDialog.Label.Info=Sélectionner les niveaux à afficher sur le tableau croisé :
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Zone de colonne
AreaNodeProvider.RowArea=Zone de ligne
AreaNodeProvider.DetailArea=Zone de détails
CrossTabViewNodeProvider.ColumnArea=Zone de colonne
CrossTabViewNodeProvider.RowArea=Zone de ligne
CrosstTabCellNodeProvider.Cell=Cellule
CrosstTabLevelNodeProvider.Level=Niveau - 
CrosstTabMeasureNodeProvider.Detail=Détails - 
MeasureSubNodeProvider.Header=En-tête
MeasureSubNodeProvider.Detail=Détails
MeasureSubNodeProvider.Aggregation=Agrégation

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Erreur
SortkeyBuilder.DialogTitle.Label.Key=Clé :
CrosstabSortingModelProvider.ColumnName.GroupLevel=Niveau de groupe
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Niveau de groupe :
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Cliquez ici pour appeler le Générateur d'expression
SortkeyBuilder.DialogTitle.Label.Direction=Direction :

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=Général
CrosstabPageGenerator.List.Margin=Marge
CrosstabPageGenerator.List.Font=Police
CrosstabPageGenerator.List.Borders=Bordure
CrosstabPageGenerator.List.Section=Saut de page
CrosstabPageGenerator.List.Visibility=Visibilité
CrosstabPageGenerator.List.TOC=Table des matières
CrosstabPageGenerator.List.Bookmark=Signet
CrosstabPageGenerator.List.NamedExpressions=Expressions nommées
CrosstabPageGenerator.List.UserProperties=Propriétés de l'utilisateur
CrosstabPageGenerator.List.AdvancedProperty=Avancé

CrosstabPageGenerator.TabItem.Binding=Liaison
CrosstabPageGenerator.TabItem.RowArea=Zone de ligne
CrosstabPageGenerator.TabItem.ColumnArea=Zone de colonne
CrosstabPageGenerator.TabItem.DetailArea=Zone de détails
CrosstabPageGenerator.TabItem.Filters=Filtres
CrosstabPageGenerator.TabItem.Highlights=Surbrillances
CrosstabPageGenerator.TabItem.map=Mappage
CrosstabPageGenerator.TabItem.Sorting=Tri en cours

CrosstabGeneraPage.ForEmptyCell=Pour les cellules vides, afficher :
CrosstabGeneraPage.FormatOption=Options de format :
LayoutMeasuresProvider.DisplayName=Présentation verticale des champs de données dans la zone de détails


parameterBinding.title=Liaison de paramètre de jeu de données...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Trier selon :
Element.ReportItem.dataSet=Jeu de données :
Element.ReportElement.Cube=&Données :
BindingPage.None=Aucun


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Propriétés


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
