###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Afficher/Masquer les &niveaux de groupe

AddLevelHandleAction_TransName=Afficher/Masquer les niveaux de groupe

AddMesureViewHandleAction.DisplayName=Afficher/Masquer les &mesures

AddMesureViewHandleAction.TransName=Afficher/Masquer les mesures

AddSubTotalAction.LabelName=Total global

AddSubTotalAction.TransName=Modifier les totaux

AddSubTotalAction.DisplayName=Tota&ux

AddSubTotalAction.TotalName=TOTAL

CrosstabMenuBuilder.EditCubeAction.DisplayName=&Modifier un cube de données

DeleteDimensionViewHandleAction.TransName=Supprimer la dimension

DeleteDimensionViewHandleAction.DisplayName=Suppri&mer

DeleteMeasureHandleAction.DisplayName=Suppri&mer

DeleteMeasureHandleAction.TransName=Supprimer la mesure

AddComputedMesureHandleAction.DisplayName=Ajouter une &mesure dérivée

AddComputedMesureHandleAction.TransName=Ajouter une mesure dérivée

AddComputedSummaryDialog.Title=Mesure dérivée

AddComputedSummaryDialog.Label.Name=&Nom :

AddComputedSummaryDialog.Label.Expression=&Expression :

AddComputedSummaryDialog.Label.DataType=Type de &données :

AddComputedSummaryDialog.ErrMsg.Msg1=Le nom de la mesure doit être renseigné.

AddComputedSummaryDialog.ErrMsg.Msg2=Le nom de la mesure existe déjà.

AddComputedSummaryDialog.ErrMsg.Msg3=L'expression doit être renseignée.

ShowAsViewAction.DisplayName=Afficher sous

ShowAsViewAction.TransName=Afficher sous

MeasureComboPropertyDescriptorProvider.TransName=Modifier l'orientation du tableau croisé

MeasureHandleDropAdapter_trans_name=Ajouter une mesure

###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Ajouter une dimension

AddMeasureViewHandleCommand.TransName=Ajouter une mesure

AddRelativeTimePeriodAction_action_label=Ajouter la période de temps re&latif

AddRelativeTimePeriodAction_trans_label=Ajouter la période de temps relatif

ChangeAreaCommand.TransName=Ignorer la dimension

ChangeMeasureOrderCommand.TransName=Modifier l'ordre de mesure

CreateDimensionViewCommand.TransName=Créer une dimension

CreateMeasureViewCommand.TransName=Créer une mesure

MergeCrosstabHeaderCellAction_name=&Fusionner les cellules d'en-tête

SplitCrosstabHeadCellAction_name=F&ractionner les cellules d'en-tête

ExtendedDataColumnXtabDropAdapter.trans.add=Ajouter {0}

###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tableau croisé
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.AggregateOn=Regrouper par

GrandTotalProvider.Column.DataField=Champ de données

GrandTotalProvider.Column.View=Vue

GrandTotalProvider.Column.Position=Position

GrandTotalProvider.Column.Function=Fonctions

GrandTotalProvider.ViewStatus=Conserver la Vue actuelle

GrandTotalProvider.ShowAs=Afficher sous {0}

SubTotalProvider.Column.DataField=Champ de données

SubTotalProvider.Column.Function=Fonctions

SubTotalProvider.Column.AggregateOn=Regrouper par

SubTotalProvider.Column.ViewStatus=Conserver la Vue actuelle

SubTotalProvider.Column.View=Affichage

SubTotalProvider.Column.Position=Position

SubTotalProvider.ShowAs=Afficher sous {0}

LevelViewDialog.Title=Afficher/Masquer les niveaux de groupe

LevelViewDialog.Label.Info=Sélectionner les niveaux à afficher sur le tableau croisé :

LevelViewDialog.Button.Regular.Text=Groupe &normal

LevelViewDialog.Button.Date.Text=Groupe de &dates

AggregationDialog.Title=Totaux

AggregationDialog.Label.Grand=Totaux généraux :

AggregationDialog.Label.Sub=Sous-totaux :

AggregationDialog.TabItem.Title.RowArea=Zone de ligne

AggregationDialog.TabItem.Title.ColumnArea=Zone de colonne

ShowSummaryFieldDialog.Title=Afficher/Masquer les mesures

ShowSummaryFieldDialog.Label.Info=Sélectionner les mesures à afficher sur le tableau croisé :

ShowSummaryFieldDialog.Column.Measures=Mesures

ShowSummaryFieldDialog.Column.View=Vues

ShowSummaryFieldDialog.ViewStatus=Conserver la Vue actuelle

DeleteBindingDialog.Title=Supprimer les liaisons inutilisées ?

DeleteBindingDialog.Message=Cette action donnera des liaisons de données inutilisées.\n\nVoulez-vous supprimer les liaisons inutilisées ?

DeleteBindingDialog.ToggleMessage=Mémo&riser ma décision
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Zone de colonne

AreaNodeProvider.RowArea=Zone de ligne

AreaNodeProvider.DetailArea=Zone de détails

CrossTabViewNodeProvider.ColumnArea=Zone de colonne

CrossTabViewNodeProvider.RowArea=Zone de ligne

CrossTabCellNodeProvider.Cell=Cellule

CrossTabLevelNodeProvider.Level=Niveau -

CrossTabMeasureNodeProvider.Detail=Détails -

MeasureSubNodeProvider.Header=En-tête

MeasureSubNodeProvider.Detail=Détails

MeasureSubNodeProvider.Aggregation=Agrégation

CrosstabSortingModelProvider.ColumnName.GroupLevel=Niveau de groupe

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Erreur

SortkeyBuilder.DialogTitle.Label.Key=&Clé :

CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=Cible

CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Niveau de &groupe :

SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Cliquez ici pour appeler le Générateur d'expression

SortkeyBuilder.DialogTitle.Label.Direction=&Direction :

SortkeyBuilder.Label.Locale=&Local :

SortkeyBuilder.Label.Strength=&Intensité :

SortkeyBuilder.Locale.Auto=Auto

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=Général

CrosstabPageGenerator.List.Margin=Marge

CrosstabPageGenerator.List.Font=Police

CrosstabPageGenerator.List.Borders=Bordure

CrosstabPageGenerator.List.Section=Saut de page

CrosstabPageGenerator.List.Visibility=Visibilité

CrosstabPageGenerator.List.TOC=Table des matières

CrosstabPageGenerator.List.Bookmark=Signet

CrosstabPageGenerator.List.NamedExpressions=Expressions nommées

CrosstabPageGenerator.List.UserProperties=Propriétés de l'utilisateur

CrosstabPageGenerator.List.AdvancedProperty=Avancé

CrosstabPageGenerator.List.EmptyRowColumn=Lignes et colonnes vides

CrosstabPageGenerator.TabItem.Binding=Liaison

CrosstabPageGenerator.TabItem.RowArea=Zone de ligne

CrosstabPageGenerator.TabItem.ColumnArea=Zone de colonne

CrosstabPageGenerator.TabItem.DetailArea=Zone de détails

CrosstabPageGenerator.TabItem.Filters=Filtres

CrosstabPageGenerator.TabItem.Highlights=Surbrillances

CrosstabPageGenerator.TabItem.map=Mappage

CrosstabPageGenerator.TabItem.Sorting=Tri en cours

CrosstabGeneralPage.ForEmptyCell=Pour les cellules vides, &afficher :

LayoutMeasuresSection.DisplayName=O&rientation :

CrosstabGeneralPage.HideMeasureHeader=&Masquer l'en-tête de Mesure

###########################################################
#CrosstabEventHandlerPage properties
CrosstabEventHandlerPage.dialog.Browse=&Parcourir...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Trier selon :

Element.ReportItem.dataSet=Jeu de données :

Element.ReportElement.Cube=Don&nées :

BindingPage.None=Aucun

FilterHandleProvider.Label.Filterby=Filtrer par :

###########################################################
#EmptyRowColumnProvider properties
EmptyRowColumnPage.Label.Text=Cochez cette case si des lignes ou des colonnes vides s'affichent au niveau d'un tableau croisé.

EmptyRowColumnProvider.RowView.Button.Text=Afficher les &lignes vides

EmptyRowColumnProvider.ColumnView.Button.Text=Afficher les &colonnes vides

###########################################################
#CategoryPageGenerator properties
CategoryPageGenerator.TabItem.Attributes=Propriétés


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogMessage.Edit=

FilterConditionBuilder.DialogMessage.New=

FilterConditionBuilder.DialogTitle.New=Nouvelle condition de filtre

FilterConditionBuilder.DialogTitle.Edit=Modifier la condition de filtre

FilterConditionBuilder.choice.ValueOfThisDataItem=Valeur de l'élément de données

FilterConditionBuilder.tooltip.ExpBuilder=Cliquez ici pour appeler le Générateur d'expression.

FilterConditionBuilder.text.AND=ET

FilterConditionBuilder.text.Condition=&Condition de filtre :

FilterConditionBuilder.text.GroupLevel=Niveau de gr&oupe :

FilterConditionBuilder.list.item1=Valeur

FilterConditionBuilder.button.edit=Modifi&er...

FilterConditionBuilder.button.delete=Suppri&mer

FilterConditionBuilder.button.deleteall=Supprimer t&out

FilterConditionBuilder.button.add=&Ajouter

FilterConditionBuilder.button.edit.tooltip=Modifier la valeur sélectionnée dans la liste

FilterConditionBuilder.button.delete.tooltip=Supprimer la valeur sélectionnée de la liste

FilterConditionBuilder.button.deleteall.tooltip=Supprimer toutes les valeurs de la liste

FilterConditionBuilder.button.add.tooltip=Ajouter la valeur à la liste

CrosstabFilterConditionBuilder.Item.Decorator=--------

CrosstabFilterConditionBuilder.Button.Detal=&Détails

CrosstabFilterConditionBuilder.Item.SelectLevel=---Sélectionner un niveau---

CrosstabFilterConditionBuilder.Item.SelectMeasure=---Sélectionner une mesure---

CrosstabFilterConditionBuilder.DialogMessage.New=Sélectionnez le niveau ou la mesure de groupe cible sur lequel vous souhaitez appliquer le filtre, puis définissez la condition de filtre.

CrosstabFilterConditionBuilder.DialogMessage.Edit=Sélectionnez le niveau ou la mesure de groupe cible sur lequel vous souhaitez appliquer le filtre, puis définissez la condition de filtre.

CrosstabFilterConditionBuilder.label.value=Valeur

CrosstabFilterConditionBuilder.Label.Target=Cible :

CrosstabFilterConditionBuilder.Button.GroupLevel=Niveau de &groupe

CrosstabFilterConditionBuilder.Button.Measure=Mes&ure

CrosstabFilterConditionBuilder.Button.Cube=&Cube

FilterbyTree.Bindings.Catogory.Measures=Mesure

FilterbyTree.Bindings.Catogory.Dimension=Dimension

FilterbyTree.Bindings.Catogory.GrandTotal=Total global

FilterbyTree.Bindings.Catogory.SubTotal=Sous-total

FilterbyTree.Bindings.Catogory.OtherType=Autre type

FilterbyTree.Bindings.Catogory.Undefined=Non défini

FilterbyTree.Title=Filtrer par

FilterbyTree.Message=Filtrer par

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Ignorer le(s) champ(s) de données pour définir les colonnes ici

Blank.text.row=Ignorer le(s) champ(s) de données pour définir les lignes ici

Blank.text.measure=Ignorer le(s) champ(s) de données à résumer ici

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Total global

CrosstabGrandTotalDialog.Text.DataField=&Champ de données :

CrosstabGrandTotalDialog.Text.Function=&Fonction :


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=Niveau de groupe

CrosstabPageBreakProvider.Column.Before=Avant

CrosstabPageBreakProvider.Column.After=Après

CrosstabPageBreakProvider.Column.Inside=A l'intérieur

CrosstabPageBreakProvider.Column.Interval=Intervalle

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Regrouper par

CrosstabSubToatalProvider.Column.DataField=Champ de données

CrosstabSubToatalProvider.Column.Function=Fonction

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Saut de page

CrosstabPageBreakDialog.Text.GroupLevel=Niveau de &groupe :

CrosstabPageBreakDialog.Text.PageBreakBefore=&Avant :

CrosstabPageBreakDialog.Text.PageBreakAfter=&Après :

CrosstabPageBreakDialog.Text.PageBreakInside=&A l'intérieur :

CrosstabPageBreakDialog.Text.PageBreakInterval=Intervalle de saut de &page :

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Sous-total

SubTotalDialog.Text.AggregateOn=Regrouper p&ar :

SubTotalDialog.Text.Function=&Fonction :

SubTotalDialog.Text.DataField=&Champ de données :

FormPage.Menu.ModifyProperty=Modifier

CrosstabPageGenerator.List.SubTotals=Sous-totaux

CrosstabPageGenerator.List.GrandTotals=Totaux généraux

CrosstabPageGenerator.List.PageBreak=Saut de page

PageLayoutPropertyDescriptorProvider.PageLayout=Mise en page :

RowPageBreak.RepeatColumnHeader=Répéter l'en-tête de &colonne

ColumnPageBreak.RepeatRowHeader=Ré&péter l'en-tête de ligne

###########################################################
#ExpressionValueCellEditor properties
ExpressionValueCellEditor.buildExpressionAction=<Générer une expression...>

ExpressionValueCellEditor.selectValueAction=<Sélectionner une valeur...>

ExpressionValueCellEditor.filterBy=<Filtrer par...>

ExpressionValueCellEditor.title=Sélectionner une valeur

CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Sélectionnez une valeur de membre de colonne

CrosstabSortKeyBuilder.Label.SelRowMemberValue=Sélectionnez une valeur de membre de ligne

CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Sélectionnez une valeur de membre de colonne

CrosstabFilterConditionBuilder.Label.SelRowMemberValue=Sélectionnez une valeur de membre de ligne

CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=Niveau de gr&oupe :

CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=Me&sure :

SelColumnMemberValue.Column.Level=Niveau

SelColumnMemberValue.Column.Value=Valeur

ChoiceSetFactory.choice.None=Aucun

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Erreur de récupération de la liste

SelectValueDialog.messages.error.selectVauleUnavailable=La valeur de l'expression ne peut pas être récupérée.

SelectValueDialog.noExpressionSet=Une expression n'a pas été définie

SelectValueDialog.retrieving=Récupération de la liste...

SelectValueDialog.selectValue=Sélectionner une valeur

SelectValueDialog.messages.info.selectVauleUnavailable=La liste de valeurs n'est pas disponible.

CrosstabPreferencePage.Title=Tableau croisé

CrosstabPreferencePage.filterLimit=Limite de filtre

CrosstabPreferencePage.filterLimit.prompt=Nombre maximum de &valeurs à afficher :

CrosstabPreferencePage.Error.MaxRowInvalid=La valeur numérique est incorrecte.

CrosstabPreferencePage.autoDelBindings.Text=Supprimer les liaisons inutilisées après modification de la structure du tableau croisé.

CrosstabPreferencePage.autoDelBindings.Text.Prompt=&Invite

CrosstabPreferencePage.autoDelBindings.Text.Always=T&oujours

CrosstabPreferencePage.autoDelBindings.Text.Never=&Jamais

CrosstabPreferencePage.promptGroup=Invite

CrosstabPreferencePage.cubePopup.Text=I&ndication après avoir déposé des champs dans un tableau croisé et avoir réussi à créer un cube.

###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=Changer le cube ?

CrosstabDataBinding.message.changeCube=Vous allez modifier la liaison des données du tableau croisé.  \n\nVoulez-vous effacer toutes les liaisons de colonnes de données ?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=Cube de données

CubeBuilder.warning.title=Tableau croisé

CubeBuilder.warning.message=La création d'un cube de données a réussi.\nPour finaliser la création d'un tableau croisé, faites glisser les champs du cube de données créé vers le conteneur du tableau croisé.

CubeBuilder.warning.prompt=&Ne plus afficher ce message

###########################################################
#Crosstab drag tracker
CrosstabColumnDragTracker.ResizeColumn=Redimensionner la colonne

CrosstabColumnDragTracker.Show.Label=Largeur :

CrosstabRowDragTracker.Show.Label=Hauteur :

###########################################################
#AggregationCellTextViewProvider
AggregationCellTextViewProvider.displayName=Texte


###########################################################
#CrosstabSortKeyBuilder properties
CrosstabSortKeyBuilder.choice.ValueOfThisDataItem=Valeur de l'élément de données

CrosstabSortKeyBuilder.tooltip.ExpBuilder=Ouvrir le Générateur d'expression

CrosstabSortKeyBuilder.MSG.CreateNew=Nouveau...

InsertCubeInLayoutAction.menu.text=Modifi&er

InsertCubeInLayoutAction.action.text=I&nsérer dans la mise en page

InsertCubeInLayoutAction.action.message=Créer un tableau croisé à partir du cube

MapRuleBuilderDialog.MsgDlg.Title=Avertissement

MapRuleBuilderDialog.MsgDlg.Msg=La valeur ne peut pas être vierge.

LevelHandleDropAdapter.ActionText=Ajouter une dimension

LevelPropertyDialog.MSG.CreateNew=


###########################################################
#CrosstabHighlightRuleBuilder properties
CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstab=tableau croisé

CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstabcell=cellule du tableau croisé

CrosstabHighlightRuleBuilderDialog.text.Description.Element.ReportElement=élément d'état

CrosstabHighlightRuleBuilderDialog.text.Description=Appliquer un formatage conditionnel dans {0}. Spécifier l'expression conditionnelle et le format.\nLe format sera appliqué si l'expression est True.

###########################################################
#CrosstabFilterConditionBuilder properties
CrosstabFilterConditionBuilder.ExpressionEditor.Title=Editeur d'expression

CrosstabFilterConditionBuilder.MsgDlg.Msg=Avertissement

CrosstabFilterConditionBuilder.MsgDlg.Title=La valeur ne peut pas être vierge.

CrosstabFilterConditionBuilder.Button.UpdateAggregation=Recalculer &Totaux

###########################################################
#Breadcrumb provider properties
VirtualCrosstabCellNodeProvider.Display.ColumnArea=Zone de colonne

VirtualCrosstabCellNodeProvider.Display.DetailArea=Zone de détails

VirtualCrosstabCellNodeProvider.Display.RowArea=Zone de ligne

VirtualCrosstabCellNodeProvider.Display.UnknownArea=Zone inconnue

CrosstabBindingComboPropertyDescriptorProvider.Flag.DataModel=\ (Modèle de données)

CrosstabBindingRefresh.action.message=Réactualiser les liaisons de tableau croisé
