###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=グループレベルの表示/非表示
AddLevelHandleAction_TransName=グループレベルの表示/非表示
AddMesureViewHandleAction.DisplayName=計測の表示/非表示
AddMesureViewHandleAction.TransName=計測の表示/非表示
AddSubTotalAction.LabelName=総計
AddSubTotalAction.TransName=総計
AddSubTotalAction.DisplayName=総計
AddSubTotalAction.TotalName=合計
CrosstabMenuBuilder.EditCubeAction.DisplayName=データキューブの編集
DeleteDimensionViewHandleAction.TransName=DimensionViewHandle の削除
DeleteDimensionViewHandleAction.DisplayName=削除
DeleteMeasureHandleAction.DisplayName=削除
DeleteMeasureHandleAction.TransName=MeasureViewHandle の削除
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=DimensionHandle の追加
AddMeasureViewHandleCommand.TransName=MeasureHandle の追加
ChangeAreaCommand.TransName=DimensionHandle の削除
ChangeMeasureOrderCommand.TransName=計測順の変更
CreateDimensionViewCommand.TransName=DimensionViewHandle の作成
CreateMeasureViewCommand.TransName=MeasureViewHandle の作成
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=クロスタブ
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=データフィールド
GrandTotalProvider.Column.Function=関数
SubTotalProvider.Column.DataField=データフィールド
SubTotalProvider.Column.Function=関数
SubTotalProvider.Column.AggregateOn=総計条件
LevelViewDialog.Title=グループレベルの表示/非表示
LevelViewDialog.Label.Info=クロスタブに表示するレベルの選択 :
AggregationDialog.Title=総計
AggregationDialog.Label.Grand=総計 :
AggregationDialog.Label.Sub=小計 :
ShowSummaryFieldDialog.Title=サマリフィールドの表示/非表示
ShowSummaryFieldDialog.Label.Info=クロスタブに表示するレベルの選択 :
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=列の領域
AreaNodeProvider.RowArea=行の領域
AreaNodeProvider.DetailArea=詳細の領域
CrossTabViewNodeProvider.ColumnArea=列の領域
CrossTabViewNodeProvider.RowArea=行の領域
CrosstTabCellNodeProvider.Cell=セル
CrosstTabLevelNodeProvider.Level=レベル - 
CrosstTabMeasureNodeProvider.Detail=詳細 - 
MeasureSubNodeProvider.Header=ヘッダ
MeasureSubNodeProvider.Detail=詳細
MeasureSubNodeProvider.Aggregation=総計

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=エラー
SortkeyBuilder.DialogTitle.Label.Key=キー :
CrosstabSortingModelProvider.ColumnName.GroupLevel=グループレベル
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=グループレベル :
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=式ビルダを起動するには、ここをクリックしてしてください
SortkeyBuilder.DialogTitle.Label.Direction=方向 :

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=全般
CrosstabPageGenerator.List.Margin=余白
CrosstabPageGenerator.List.Font=フォント
CrosstabPageGenerator.List.Borders=罫線
CrosstabPageGenerator.List.Section=ページ区切り
CrosstabPageGenerator.List.Visibility=表示/非表示
CrosstabPageGenerator.List.TOC=目次
CrosstabPageGenerator.List.Bookmark=ブックマーク
CrosstabPageGenerator.List.NamedExpressions=名前付き式
CrosstabPageGenerator.List.UserProperties=ユーザのプロパティ
CrosstabPageGenerator.List.AdvancedProperty=詳細設定

CrosstabPageGenerator.TabItem.Binding=バインド
CrosstabPageGenerator.TabItem.RowArea=行の領域
CrosstabPageGenerator.TabItem.ColumnArea=列の領域
CrosstabPageGenerator.TabItem.DetailArea=詳細の領域
CrosstabPageGenerator.TabItem.Filters=フィルタ
CrosstabPageGenerator.TabItem.Highlights=ハイライト
CrosstabPageGenerator.TabItem.map=マップ
CrosstabPageGenerator.TabItem.Sorting=ソート

CrosstabGeneraPage.ForEmptyCell=空のセルに次を表示 :
CrosstabGeneraPage.FormatOption=書式設定オプション :
LayoutMeasuresProvider.DisplayName=詳細の領域にデータフィールドを垂直方向に表示


parameterBinding.title=データセットパラメタのバインド...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=ソート :
Element.ReportItem.dataSet=データセット :
Element.ReportElement.Cube=データ(&D) :
BindingPage.None=なし


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=プロパティ


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
