###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=그룹 수준 표시/숨기기
AddLevelHandleAction_TransName=그룹 수준 표시/숨기기
AddMesureViewHandleAction.DisplayName=측정 표시/숨기기
AddMesureViewHandleAction.TransName=측정 표시/숨기기
AddSubTotalAction.LabelName=총합계
AddSubTotalAction.TransName=집계
AddSubTotalAction.DisplayName=Totals
AddSubTotalAction.TotalName=합계
CrosstabMenuBuilder.EditCubeAction.DisplayName=데이터 큐브 편집
DeleteDimensionViewHandleAction.TransName=Dimensionviewhandle 삭제
DeleteDimensionViewHandleAction.DisplayName=제거
DeleteMeasureHandleAction.DisplayName=제거
DeleteMeasureHandleAction.TransName=MeasureViewHandle 삭제
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=DiminsionHandle 추가
AddMeasureViewHandleCommand.TransName=MeasureHandle 추가
ChangeAreaCommand.TransName=차원 핸들 삭제
ChangeMeasureOrderCommand.TransName=측정 순서 변경
CreateDimensionViewCommand.TransName=DiminsionViewHandle 생성
CreateMeasureViewCommand.TransName=MeasureViewHandle 생성
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=크로스 탭
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=데이터 필드
GrandTotalProvider.Column.Function=함수
SubTotalProvider.Column.DataField=데이터 필드
SubTotalProvider.Column.Function=함수
SubTotalProvider.Column.AggregateOn=집계 대상:
LevelViewDialog.Title=그룹 수준 표시/숨기기
LevelViewDialog.Label.Info=크로스 탭에 표시할 수준 선택:
AggregationDialog.Title=집계
AggregationDialog.Label.Grand=총합계:
AggregationDialog.Label.Sub=부분합:
ShowSummaryFieldDialog.Title=요약 필드 표시/숨기기
ShowSummaryFieldDialog.Label.Info=크로스 탭에 표시할 수준 선택:
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=열 영역
AreaNodeProvider.RowArea=행 영역
AreaNodeProvider.DetailArea=세부 영역
CrossTabViewNodeProvider.ColumnArea=열 영역
CrossTabViewNodeProvider.RowArea=행 영역
CrosstTabCellNodeProvider.Cell=셀
CrosstTabLevelNodeProvider.Level=수준 - 
CrosstTabMeasureNodeProvider.Detail=상세 정보 - 
MeasureSubNodeProvider.Header=머리글
MeasureSubNodeProvider.Detail=상세 정보
MeasureSubNodeProvider.Aggregation=집계

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=오류
SortkeyBuilder.DialogTitle.Label.Key=키:
CrosstabSortingModelProvider.ColumnName.GroupLevel=그룹 수준
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=그룹 수준:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=식 빌더를 호출하려면 누릅니다.
SortkeyBuilder.DialogTitle.Label.Direction=방향:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=일반
CrosstabPageGenerator.List.Margin=여백
CrosstabPageGenerator.List.Font=글꼴
CrosstabPageGenerator.List.Borders=테두리
CrosstabPageGenerator.List.Section=페이지 나누기
CrosstabPageGenerator.List.Visibility=표시 유형
CrosstabPageGenerator.List.TOC=목차
CrosstabPageGenerator.List.Bookmark=책갈피
CrosstabPageGenerator.List.NamedExpressions=명명된 식
CrosstabPageGenerator.List.UserProperties=사용자 속성
CrosstabPageGenerator.List.AdvancedProperty=고급

CrosstabPageGenerator.TabItem.Binding=바인딩
CrosstabPageGenerator.TabItem.RowArea=행 영역
CrosstabPageGenerator.TabItem.ColumnArea=열 영역
CrosstabPageGenerator.TabItem.DetailArea=세부 영역
CrosstabPageGenerator.TabItem.Filters=필터
CrosstabPageGenerator.TabItem.Highlights=강조
CrosstabPageGenerator.TabItem.map=맵
CrosstabPageGenerator.TabItem.Sorting=정렬

CrosstabGeneraPage.ForEmptyCell=빈 셀 표시 기호:
CrosstabGeneraPage.FormatOption=서식 옵션:
LayoutMeasuresProvider.DisplayName=데이터 필드를 세부 영역에 세로로 배치


parameterBinding.title=데이터 집합 매개 변수 바인딩...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=정렬 방법:
Element.ReportItem.dataSet=데이터 집합:
Element.ReportElement.Cube=데이터(&D):
BindingPage.None=없음


FilterHandleProvider.Label.Filterby=필터링 기준:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=속성


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=새 필터 조건
FilterConditionBuilder.DialogTitle.Edit=필터 조건 편집
FilterConditionBuilder.choice.ValueOfThisDataItem=이 데이터 항목 값
FilterConditionBuilder.tooltip.ExpBuilder=식 빌더를 호출하려면 누릅니다.
FilterConditionBuilder.text.AND=및 
FilterConditionBuilder.text.Condition=필터 조건 입력:
FilterConditionBuilder.text.GroupLevel=그룹 수준:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=열을 정의하려면 데이터 필드를 여기에 내려 놓으십시오.
Blank.text.row=행을 정의하려면 데이터\n필드를 여기에 내려 놓으십시오.
Blank.text.measure=요약하려면 데이터 필드를 여기에 내려 놓으십시오.

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=총합계
CrosstabGrandTotalDialog.Text.DataField=Data Field:
CrosstabGrandTotalDialog.Text.Function=Function:


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=그룹 수준
CrosstabPageBreakProvider.Column.Before=Before
CrosstabPageBreakProvider.Column.After=After

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Aggregate On
CrosstabSubToatalProvider.Column.DataField=데이터 필드
CrosstabSubToatalProvider.Column.Function=함수

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=페이지 나누기
CrosstabPageBreakDialog.Text.GroupLevel=그룹 수준:
CrosstabPageBreakDialog.Text.PageBreakBefore=Before:
CrosstabPageBreakDialog.Text.PageBreakAfter=After:

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Sub Total
SubTotalDialog.Text.AggregateOn=Aggregate On:
SubTotalDialog.Text.Function=Function:
SubTotalDialog.Text.DataField=Data Field:

FormPage.Menu.ModifyProperty=Modify

CrosstabPageGenerator.List.SubTotals=Sub Totals
CrosstabPageGenerator.List.GrandTotals=Grand Totals
CrosstabPageGenerator.List.PageBreak=페이지 나누기

PageLayoutPropertyDescriptorProvider.PageLayout=페이지 레이아웃:
CrosstabSectionPage.RepeatColumnHeader=열 머리글 반복

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Build expression...>
ExpressionValueCellEditor.selectValueAction=<Select value...>
ExpressionValueCellEditor.title=Select value
CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Select Column Member Value
CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Select Column Member Value
SelColumnMemberValue.Column.Level=Level
SelColumnMemberValue.Column.Value=Value
ChoiceSetFactory.choice.None=없음

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Error retrieving list
SelectValueDialog.messages.error.selectVauleUnavailable=The expression's value can not be retrieved.
SelectValueDialog.noExpressionSet=An expression has not been set
SelectValueDialog.retrieving=Retrieving list...
SelectValueDialog.selectValue=Select value
SelectValueDialog.messages.info.selectVauleUnavailable=Value list is unavailable.

CrosstabPreferencePage.Title=Crosstab
CrosstabPreferencePage.filterLimit=Filter Limit
CrosstabPreferencePage.filterLimit.prompt=Maximum number of values to display:
CrosstabPreferencePage.Error.MaxRowInvalid=The number value is invalid