###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=显示/隐藏组级别
AddLevelHandleAction_TransName=显示/隐藏组级别
AddMesureViewHandleAction.DisplayName=显示/隐藏度量
AddMesureViewHandleAction.TransName=显示/隐藏度量
AddSubTotalAction.LabelName=总计
AddSubTotalAction.TransName=聚合
AddSubTotalAction.DisplayName=总计
AddSubTotalAction.TotalName=合计
CrosstabMenuBuilder.EditCubeAction.DisplayName=编辑多维数据集
DeleteDimensionViewHandleAction.TransName=删除维视图句柄
DeleteDimensionViewHandleAction.DisplayName=删除
DeleteMeasureHandleAction.DisplayName=删除
DeleteMeasureHandleAction.TransName=删除度量视图句柄
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=添加维句柄
AddMeasureViewHandleCommand.TransName=添加度量句柄
ChangeAreaCommand.TransName=删除维句柄
ChangeMeasureOrderCommand.TransName=更改度量顺序
CreateDimensionViewCommand.TransName=创建维视图句柄
CreateMeasureViewCommand.TransName=创建度量视图句柄
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=交叉表
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=数据字段
GrandTotalProvider.Column.Function=函数
SubTotalProvider.Column.DataField=数据字段
SubTotalProvider.Column.Function=函数
SubTotalProvider.Column.AggregateOn=聚合条件
LevelViewDialog.Title=显示/隐藏组级别
LevelViewDialog.Label.Info=选择要在交叉表上显示的级别:
AggregationDialog.Title=总计
AggregationDialog.Label.Grand=总计:
AggregationDialog.Label.Sub=小计:
AggregationDialog.TabItem.Title.RowArea=行区域
AggregationDialog.TabItem.Title.ColumnArea=列区域
ShowSummaryFieldDialog.Title=显示/隐藏摘要字段
ShowSummaryFieldDialog.Label.Info=选择要在交叉表上显示的级别:

DeleteBindingDialog.Title=删除未使用的绑定?
DeleteBindingDialog.Message=此操作将产生未使用的数据绑定。\n\n是否要删除未使用的绑定?
DeleteBindingDialog.ToggleMessage=不再显示此消息
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=列区域
AreaNodeProvider.RowArea=行区域
AreaNodeProvider.DetailArea=详细信息区域
CrossTabViewNodeProvider.ColumnArea=列区域
CrossTabViewNodeProvider.RowArea=行区域
CrossTabCellNodeProvider.Cell=单元格
CrossTabLevelNodeProvider.Level=级别 - 
CrossTabMeasureNodeProvider.Detail=详细资料 - 
MeasureSubNodeProvider.Header=页眉
MeasureSubNodeProvider.Detail=详细资料
MeasureSubNodeProvider.Aggregation=聚合

CrosstabSortingModelProvider.ColumnName.GroupLevel=组级别
SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=错误
SortkeyBuilder.DialogTitle.Label.Key=关键字:
CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=目标
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=组级别:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=单击以调用表达式生成器
SortkeyBuilder.DialogTitle.Label.Direction=方向:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=常规
CrosstabPageGenerator.List.Margin=边距
CrosstabPageGenerator.List.Font=字体
CrosstabPageGenerator.List.Borders=边框
CrosstabPageGenerator.List.Section=分页符
CrosstabPageGenerator.List.Visibility=可见性
CrosstabPageGenerator.List.TOC=目录
CrosstabPageGenerator.List.Bookmark=书签
CrosstabPageGenerator.List.NamedExpressions=命名表达式
CrosstabPageGenerator.List.UserProperties=用户属性
CrosstabPageGenerator.List.AdvancedProperty=高级

CrosstabPageGenerator.TabItem.Binding=绑定
CrosstabPageGenerator.TabItem.RowArea=行区域
CrosstabPageGenerator.TabItem.ColumnArea=列区域
CrosstabPageGenerator.TabItem.DetailArea=详细信息区域
CrosstabPageGenerator.TabItem.Filters=筛选器
CrosstabPageGenerator.TabItem.Highlights=突出显示
CrosstabPageGenerator.TabItem.map=映射
CrosstabPageGenerator.TabItem.Sorting=排序

CrosstabGeneraPage.ForEmptyCell=对于空单元格，显示:
CrosstabGeneraPage.FormatOption=格式选项:
LayoutMeasuresSection.DisplayName=方向:


parameterBinding.title=数据集参数绑定...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=排序依据:
Element.ReportItem.dataSet=数据集:
Element.ReportElement.Cube=数据(&D):
BindingPage.None=无


FilterHandleProvider.Label.Filterby=筛选依据:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=属性


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=新建筛选条件
FilterConditionBuilder.DialogTitle.Edit=编辑筛选条件
FilterConditionBuilder.choice.ValueOfThisDataItem=此数据项的值
FilterConditionBuilder.tooltip.ExpBuilder=单击以调用表达式生成器。
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=筛选条件:
FilterConditionBuilder.text.GroupLevel=组级别:
FilterConditionBuilder.list.item1=值
FilterConditionBuilder.button.edit=编辑...
FilterConditionBuilder.button.delete=删除
FilterConditionBuilder.button.deleteall=全部删除
FilterConditionBuilder.button.add=添加
FilterConditionBuilder.button.edit.tooltip=编辑值列表中的选定值
FilterConditionBuilder.button.delete.tooltip=从列表中删除选定值
FilterConditionBuilder.button.deleteall.tooltip=从列表中删除所有值
FilterConditionBuilder.button.add.tooltip=将值添加到值列表
CrosstabFilterConditionBuilder.DialogMessage.New=选择要应用筛选的组级别，然后设置筛选条件。
CrosstabFilterConditionBuilder.DialogMessage.Edit=选择要应用筛选的组级别，然后设置筛选条件。
CrosstabFilterConditionBuilder.label.value=值

FilterbyTree.Bindings.Catogory.Measures=度量
FilterbyTree.Bindings.Catogory.Dimension=维
FilterbyTree.Bindings.Catogory.GrandTotal=总计
FilterbyTree.Bindings.Catogory.SubTotal=小计
FilterbyTree.Bindings.Catogory.Undefined=未定义
FilterbyTree.Title=筛选依据
FilterbyTree.Message=筛选依据

###########################################################
#VirtualCellEditPart.java
Blank.text.column=将要定义列的数据字段放置到此处
Blank.text.row=将要定义行的数据字段放置到此处
Blank.text.measure=将要汇总的数据字段放置到此处

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=总计
CrosstabGrandTotalDialog.Text.DataField=数据字段:
CrosstabGrandTotalDialog.Text.Function=函数:


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=组级别
CrosstabPageBreakProvider.Column.Before=之前
CrosstabPageBreakProvider.Column.After=之后

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=聚合条件
CrosstabSubToatalProvider.Column.DataField=数据字段
CrosstabSubToatalProvider.Column.Function=函数

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=分页符
CrosstabPageBreakDialog.Text.GroupLevel=组级别:
CrosstabPageBreakDialog.Text.PageBreakBefore=之前:
CrosstabPageBreakDialog.Text.PageBreakAfter=之后:

###########################################################
#SubTotalDialog
SubTotalDialog.Title=小计
SubTotalDialog.Text.AggregateOn=聚合条件:
SubTotalDialog.Text.Function=函数:
SubTotalDialog.Text.DataField=数据字段:

FormPage.Menu.ModifyProperty=修改

CrosstabPageGenerator.List.SubTotals=小计
CrosstabPageGenerator.List.GrandTotals=总计
CrosstabPageGenerator.List.PageBreak=分页符

PageLayoutPropertyDescriptorProvider.PageLayout=页面布局:
CrosstabSectionPage.RepeatColumnHeader=重复列标题

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<生成表达式...>
ExpressionValueCellEditor.selectValueAction=<选择值...>
ExpressionValueCellEditor.filterBy=<筛选依据...>
ExpressionValueCellEditor.title=选择值
CrosstabSortKeyBuilder.Label.SelColumnMemberValue=选择列成员值
CrosstabSortKeyBuilder.Label.SelRowMemberValue=选择行成员值
CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=选择列成员值
CrosstabFilterConditionBuilder.Label.SelRowMemberValue=选择行成员值
CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=组级别:
CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=度量:
SelColumnMemberValue.Column.Level=级别
SelColumnMemberValue.Column.Value=值
ChoiceSetFactory.choice.None=无

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=检索列表时出错
SelectValueDialog.messages.error.selectVauleUnavailable=无法检索该表达式的值。
SelectValueDialog.noExpressionSet=尚未设置表达式
SelectValueDialog.retrieving=正在检索列表...
SelectValueDialog.selectValue=选择值
SelectValueDialog.messages.info.selectVauleUnavailable=值列表不可用。

CrosstabPreferencePage.Title=交叉表
CrosstabPreferencePage.filterLimit=筛选限制
CrosstabPreferencePage.filterLimit.prompt=要显示的最大值数:
CrosstabPreferencePage.Error.MaxRowInvalid=数值无效
CrosstabPreferencePage.autoDelBindings.Text=删除未使用的绑定之前始终询问。
CrosstabPreferencePage.promptGroup=提示
CrosstabPreferencePage.cubePopup.Text=在将字段拖动到交叉表并成功创建多维数据集之后提示。

###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=更改多维数据集?
CrosstabDataBinding.message.changeCube=您将要更改交叉表的数据绑定。\n\n是否要清除全部现有的数据列绑定?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=多维数据集

CubeBuilder.warning.title=交叉表
CubeBuilder.warning.message=已成功地创建多维数据集。\n要完成交叉表创建，请将字段从创建的多维数据集拖动到交叉表容器。
CubeBuilder.warning.prompt=不再显示此消息
