###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Gruppenebenen einblenden/ausblenden
AddLevelHandleAction_TransName=Gruppenebenen einblenden/ausblenden
AddMesureViewHandleAction.DisplayName=Maßeinheiten einblenden/ausblenden
AddMesureViewHandleAction.TransName=Maßeinheiten einblenden/ausblenden
AddSubTotalAction.LabelName=Gesamtsumme
AddSubTotalAction.TransName=Aggregat
AddSubTotalAction.DisplayName=Aggregat
AddSubTotalAction.TotalName=GESAMT
CrosstabMenuBuilder.EditCubeAction.DisplayName=Datenquader bearbeiten
DeleteDimensionViewHandleAction.TransName=Dimensionviewhandle löschen
DeleteDimensionViewHandleAction.DisplayName=Entfernen
DeleteMeasureHandleAction.DisplayName=Entfernen
DeleteMeasureHandleAction.TransName=MeasureViewHandle löschen
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=DimensionHandle hinzufügen
AddMeasureViewHandleCommand.TransName=MeasureHandle hinzufügen
ChangeAreaCommand.TransName=DimensionHandle verwerfen
ChangeMeasureOrderCommand.TransName=Reihenfolge der Maßeinheiten ändern
CreateDimensionViewCommand.TransName=DimensionHandle erstellen
CreateMeasureViewCommand.TransName=MeasureViewHandle erstellen
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Kreuztabelle
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Datenfeld
GrandTotalProvider.Column.Function=Funktion
SubTotalProvider.Column.DataField=Datenfeld
SubTotalProvider.Column.Function=Funktion
SubTotalProvider.Column.AggregateOn=Aggregat ein
LevelViewDialog.Title=Gruppenebenen einblenden/ausblenden
LevelViewDialog.Label.Info=Ebenen zum Anzeigen in Kreuztabelle auswählen:
AggregationDialog.Title=Aggregat
AggregationDialog.Label.Grand=Gesamtsummen:
AggregationDialog.Label.Sub=Zwischensumme:
ShowSummaryFieldDialog.Title=Zusammenfassungsfelder einblenden/ausblenden
ShowSummaryFieldDialog.Label.Info=Ebenen zum Anzeigen in Kreuztabelle auswählen:
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Spaltenbereich
AreaNodeProvider.RowArea=Zeilenbereich
AreaNodeProvider.DetailArea=Detailbereich
CrossTabViewNodeProvider.ColumnArea=Spaltenbereich
CrossTabViewNodeProvider.RowArea=Zeilenbereich
CrosstTabCellNodeProvider.Cell=Zelle
CrosstTabLevelNodeProvider.Level=Ebene - 
CrosstTabMeasureNodeProvider.Detail=Detail - 
MeasureSubNodeProvider.Header=Kopfzeile
MeasureSubNodeProvider.Detail=Detail
MeasureSubNodeProvider.Aggregation=Aggregat

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Fehler
SortkeyBuilder.DialogTitle.Label.Key=Schlüssel:
CrosstabSortingModelProvider.ColumnName.GroupLevel=Gruppenebene
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Gruppenebene:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Zum Öffnen der Ausdruckserstellung hier klicken
SortkeyBuilder.DialogTitle.Label.Direction=Richtung:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=Allgemein
CrosstabPageGenerator.List.Margin=Rand
CrosstabPageGenerator.List.Font=Schriftart
CrosstabPageGenerator.List.Borders=Rahmen
CrosstabPageGenerator.List.Section=Seitenumbruch
CrosstabPageGenerator.List.Visibility=Sichtbarkeit
CrosstabPageGenerator.List.TOC=Inhaltsverzeichnis
CrosstabPageGenerator.List.Bookmark=Lesezeichen
CrosstabPageGenerator.List.NamedExpressions=Benannte Ausdrücke
CrosstabPageGenerator.List.UserProperties=Benutzereigenschaften
CrosstabPageGenerator.List.AdvancedProperty=Erweitert

CrosstabPageGenerator.TabItem.Binding=Bindung
CrosstabPageGenerator.TabItem.RowArea=Zeilenbereich
CrosstabPageGenerator.TabItem.ColumnArea=Spaltenbereich
CrosstabPageGenerator.TabItem.DetailArea=Detailbereich
CrosstabPageGenerator.TabItem.Filters=Filter
CrosstabPageGenerator.TabItem.Highlights=Kennzeichnungen
CrosstabPageGenerator.TabItem.map=Zuordnung
CrosstabPageGenerator.TabItem.Sorting=Sortierung

CrosstabGeneraPage.ForEmptyCell=Leere Zellen anzeigen als:
CrosstabGeneraPage.FormatOption=Formatierungsoptionen:
LayoutMeasuresProvider.DisplayName=Datenfelder im Detailbereich vertikal darstellen


parameterBinding.title=Parameterbindung für Datensatz...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Sortieren nach:
Element.ReportItem.dataSet=Datensatz:
Element.ReportElement.Cube=&Daten:
BindingPage.None=Ohne


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Eigenschaften


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
