###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=显示/隐藏组级别(&G)

AddLevelHandleAction_TransName=显示/隐藏组级别

AddMesureViewHandleAction.DisplayName=显示/隐藏度量(&M)

AddMesureViewHandleAction.TransName=显示/隐藏度量

AddSubTotalAction.LabelName=总计

AddSubTotalAction.TransName=编辑总计

AddSubTotalAction.DisplayName=总计(&L)

AddSubTotalAction.TotalName=合计

CrosstabMenuBuilder.EditCubeAction.DisplayName=编辑多维数据集(&E)

DeleteDimensionViewHandleAction.TransName=删除维

DeleteDimensionViewHandleAction.DisplayName=删除(&V)

DeleteMeasureHandleAction.DisplayName=删除(&V)

DeleteMeasureHandleAction.TransName=删除度量

AddComputedMesureHandleAction.DisplayName=添加衍生度量(&M)

AddComputedMesureHandleAction.TransName=添加衍生度量

AddComputedSummaryDialog.Title=衍生度量

AddComputedSummaryDialog.Label.Name=名称(&N):

AddComputedSummaryDialog.Label.Expression=表达式(&E):

AddComputedSummaryDialog.Label.DataType=数据类型(&D):

AddComputedSummaryDialog.ErrMsg.Msg1=度量名称不能为空。

AddComputedSummaryDialog.ErrMsg.Msg2=度量名称已存在。

AddComputedSummaryDialog.ErrMsg.Msg3=表达式不能为空。

ShowAsViewAction.DisplayName=显示为

ShowAsViewAction.TransName=显示为

MeasureComboPropertyDescriptorProvider.TransName=更改交叉表方向

MeasureHandleDropAdapter_trans_name=添加度量

###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=添加维

AddMeasureViewHandleCommand.TransName=添加度量

AddRelativeTimePeriodAction_action_label=添加相对时间周期(&L)

AddRelativeTimePeriodAction_trans_label=添加相对时间周期

ChangeAreaCommand.TransName=废弃维

ChangeMeasureOrderCommand.TransName=更改度量顺序

CreateDimensionViewCommand.TransName=创建维

CreateMeasureViewCommand.TransName=创建度量

MergeCrosstabHeaderCellAction_name=合并标题单元格(&M)

SplitCrosstabHeadCellAction_name=拆分标题单元格(&S)

ExtendedDataColumnXtabDropAdapter.trans.add=添加 {0}

###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=交叉表
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.AggregateOn=聚合条件

GrandTotalProvider.Column.DataField=数据字段

GrandTotalProvider.Column.View=视图

GrandTotalProvider.Column.Position=位置

GrandTotalProvider.Column.Function=函数

GrandTotalProvider.ViewStatus=保留当前视图

GrandTotalProvider.ShowAs=显示为 {0}

SubTotalProvider.Column.DataField=数据字段

SubTotalProvider.Column.Function=函数

SubTotalProvider.Column.AggregateOn=聚合条件

SubTotalProvider.Column.ViewStatus=保留当前视图

SubTotalProvider.Column.View=视图

SubTotalProvider.Column.Position=位置

SubTotalProvider.ShowAs=显示为 {0}

LevelViewDialog.Title=显示/隐藏组级别

LevelViewDialog.Label.Info=选择要在交叉表上显示的级别:

LevelViewDialog.Button.Regular.Text=常规组(&R)

LevelViewDialog.Button.Date.Text=日期组(&D)

AggregationDialog.Title=总计

AggregationDialog.Label.Grand=总计:

AggregationDialog.Label.Sub=小计:

AggregationDialog.TabItem.Title.RowArea=行区域

AggregationDialog.TabItem.Title.ColumnArea=列区域

ShowSummaryFieldDialog.Title=显示/隐藏度量

ShowSummaryFieldDialog.Label.Info=选择要在交叉表上显示的度量:

ShowSummaryFieldDialog.Column.Measures=度量

ShowSummaryFieldDialog.Column.View=视图

ShowSummaryFieldDialog.ViewStatus=保留当前视图

DeleteBindingDialog.Title=删除未使用的绑定?

DeleteBindingDialog.Message=此操作将产生未使用的数据绑定。\n\n是否要删除未使用的绑定?

DeleteBindingDialog.ToggleMessage=记住我的决定(&R)
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=列区域

AreaNodeProvider.RowArea=行区域

AreaNodeProvider.DetailArea=详细信息区域

CrossTabViewNodeProvider.ColumnArea=列区域

CrossTabViewNodeProvider.RowArea=行区域

CrossTabCellNodeProvider.Cell=单元格

CrossTabLevelNodeProvider.Level=级别 -

CrossTabMeasureNodeProvider.Detail=详细资料 -

MeasureSubNodeProvider.Header=页眉

MeasureSubNodeProvider.Detail=详细资料

MeasureSubNodeProvider.Aggregation=聚合

CrosstabSortingModelProvider.ColumnName.GroupLevel=组级别

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=错误

SortkeyBuilder.DialogTitle.Label.Key=关键字(&K):

CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=目标

CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=组级别(&G):

SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=单击以调用表达式生成器

SortkeyBuilder.DialogTitle.Label.Direction=方向(&D):

SortkeyBuilder.Label.Locale=区域设置(&L):

SortkeyBuilder.Label.Strength=强度(&S):

SortkeyBuilder.Locale.Auto=自动

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=常规

CrosstabPageGenerator.List.Margin=边距

CrosstabPageGenerator.List.Font=字体

CrosstabPageGenerator.List.Borders=边框

CrosstabPageGenerator.List.Section=分页符

CrosstabPageGenerator.List.Visibility=可见性

CrosstabPageGenerator.List.TOC=目录

CrosstabPageGenerator.List.Bookmark=书签

CrosstabPageGenerator.List.NamedExpressions=命名表达式

CrosstabPageGenerator.List.UserProperties=用户属性

CrosstabPageGenerator.List.AdvancedProperty=高级

CrosstabPageGenerator.List.EmptyRowColumn=空行/列

CrosstabPageGenerator.TabItem.Binding=绑定

CrosstabPageGenerator.TabItem.RowArea=行区域

CrosstabPageGenerator.TabItem.ColumnArea=列区域

CrosstabPageGenerator.TabItem.DetailArea=详细信息区域

CrosstabPageGenerator.TabItem.Filters=筛选器

CrosstabPageGenerator.TabItem.Highlights=突出显示

CrosstabPageGenerator.TabItem.map=映射

CrosstabPageGenerator.TabItem.Sorting=排序

CrosstabGeneralPage.ForEmptyCell=对于空单元格，显示(&S):

LayoutMeasuresSection.DisplayName=方向(&R):

CrosstabGeneralPage.HideMeasureHeader=隐藏度量头(&H)

###########################################################
#CrosstabEventHandlerPage properties
CrosstabEventHandlerPage.dialog.Browse=浏览(&B)...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=排序依据:

Element.ReportItem.dataSet=数据集:

Element.ReportElement.Cube=数据(&T):

BindingPage.None=无

FilterHandleProvider.Label.Filterby=筛选依据:

###########################################################
#EmptyRowColumnProvider properties
EmptyRowColumnPage.Label.Text=如果要在交叉表级别显示空行和列，请选择该复选框

EmptyRowColumnProvider.RowView.Button.Text=显示空行(&R)

EmptyRowColumnProvider.ColumnView.Button.Text=显示空列(&C)

###########################################################
#CategoryPageGenerator properties
CategoryPageGenerator.TabItem.Attributes=属性


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogMessage.Edit=

FilterConditionBuilder.DialogMessage.New=

FilterConditionBuilder.DialogTitle.New=新建筛选条件

FilterConditionBuilder.DialogTitle.Edit=编辑筛选条件

FilterConditionBuilder.choice.ValueOfThisDataItem=此数据项的值

FilterConditionBuilder.tooltip.ExpBuilder=单击以调用表达式生成器。

FilterConditionBuilder.text.AND=与

FilterConditionBuilder.text.Condition=筛选条件(&C):

FilterConditionBuilder.text.GroupLevel=组级别(&L):

FilterConditionBuilder.list.item1=值

FilterConditionBuilder.button.edit=编辑(&E)...

FilterConditionBuilder.button.delete=删除(&M)

FilterConditionBuilder.button.deleteall=全部删除(&O)

FilterConditionBuilder.button.add=添加(&A)

FilterConditionBuilder.button.edit.tooltip=编辑值列表中的选定值

FilterConditionBuilder.button.delete.tooltip=从列表中删除选定值

FilterConditionBuilder.button.deleteall.tooltip=从列表中删除所有值

FilterConditionBuilder.button.add.tooltip=将值添加到值列表

CrosstabFilterConditionBuilder.Item.Decorator=--------

CrosstabFilterConditionBuilder.Button.Detal=详细资料(&D)

CrosstabFilterConditionBuilder.Item.SelectLevel=---选择级别---

CrosstabFilterConditionBuilder.Item.SelectMeasure=---选择度量---

CrosstabFilterConditionBuilder.DialogMessage.New=选择要应用筛选的目标组级别或度量，然后设置筛选条件。

CrosstabFilterConditionBuilder.DialogMessage.Edit=选择要应用筛选的目标组级别或度量，然后设置筛选条件。

CrosstabFilterConditionBuilder.label.value=值

CrosstabFilterConditionBuilder.Label.Target=目标:

CrosstabFilterConditionBuilder.Button.GroupLevel=组级别(&G)

CrosstabFilterConditionBuilder.Button.Measure=度量(&U)

CrosstabFilterConditionBuilder.Button.Cube=多维数据集(&C)

FilterbyTree.Bindings.Catogory.Measures=度量

FilterbyTree.Bindings.Catogory.Dimension=维

FilterbyTree.Bindings.Catogory.GrandTotal=总计

FilterbyTree.Bindings.Catogory.SubTotal=小计

FilterbyTree.Bindings.Catogory.OtherType=其他类型

FilterbyTree.Bindings.Catogory.Undefined=未定义

FilterbyTree.Title=筛选依据

FilterbyTree.Message=筛选依据

###########################################################
#VirtualCellEditPart.java
Blank.text.column=将要定义列的数据字段放置到此处

Blank.text.row=将要定义行的数据字段放置到此处

Blank.text.measure=将要汇总的数据字段放置到此处

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=总计

CrosstabGrandTotalDialog.Text.DataField=数据字段(&D):

CrosstabGrandTotalDialog.Text.Function=函数(&F):


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=组级别

CrosstabPageBreakProvider.Column.Before=之前

CrosstabPageBreakProvider.Column.After=之后

CrosstabPageBreakProvider.Column.Inside=内部

CrosstabPageBreakProvider.Column.Interval=间隔

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=聚合条件

CrosstabSubToatalProvider.Column.DataField=数据字段

CrosstabSubToatalProvider.Column.Function=函数

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=分页符

CrosstabPageBreakDialog.Text.GroupLevel=组级别(&G):

CrosstabPageBreakDialog.Text.PageBreakBefore=之前(&B):

CrosstabPageBreakDialog.Text.PageBreakAfter=之后(&A):

CrosstabPageBreakDialog.Text.PageBreakInside=内部(&I):

CrosstabPageBreakDialog.Text.PageBreakInterval=分页符间隔(&P):

###########################################################
#SubTotalDialog
SubTotalDialog.Title=小计

SubTotalDialog.Text.AggregateOn=聚合条件(&A):

SubTotalDialog.Text.Function=函数(&F):

SubTotalDialog.Text.DataField=数据字段(&D):

FormPage.Menu.ModifyProperty=修改

CrosstabPageGenerator.List.SubTotals=小计

CrosstabPageGenerator.List.GrandTotals=总计

CrosstabPageGenerator.List.PageBreak=分页符

PageLayoutPropertyDescriptorProvider.PageLayout=页面布局:

RowPageBreak.RepeatColumnHeader=重复列标题(&C)

ColumnPageBreak.RepeatRowHeader=重复行标题(&P)

###########################################################
#ExpressionValueCellEditor properties
ExpressionValueCellEditor.buildExpressionAction=<生成表达式...>

ExpressionValueCellEditor.selectValueAction=<选择值...>

ExpressionValueCellEditor.filterBy=<筛选依据...>

ExpressionValueCellEditor.title=选择值

CrosstabSortKeyBuilder.Label.SelColumnMemberValue=选择列成员值

CrosstabSortKeyBuilder.Label.SelRowMemberValue=选择行成员值

CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=选择列成员值

CrosstabFilterConditionBuilder.Label.SelRowMemberValue=选择行成员值

CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=组级别(&L):

CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=度量(&S):

SelColumnMemberValue.Column.Level=级别

SelColumnMemberValue.Column.Value=值

ChoiceSetFactory.choice.None=无

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=检索列表时出错

SelectValueDialog.messages.error.selectVauleUnavailable=无法检索该表达式的值。

SelectValueDialog.noExpressionSet=尚未设置表达式

SelectValueDialog.retrieving=正在检索列表...

SelectValueDialog.selectValue=选择值

SelectValueDialog.messages.info.selectVauleUnavailable=值列表不可用。

CrosstabPreferencePage.Title=交叉表

CrosstabPreferencePage.filterLimit=筛选限制

CrosstabPreferencePage.filterLimit.prompt=要显示的最大值数(&V):

CrosstabPreferencePage.Error.MaxRowInvalid=数值无效

CrosstabPreferencePage.autoDelBindings.Text=交叉表结果更改后删除未使用的绑定

CrosstabPreferencePage.autoDelBindings.Text.Prompt=提示(&P)

CrosstabPreferencePage.autoDelBindings.Text.Always=始终(&L)

CrosstabPreferencePage.autoDelBindings.Text.Never=从不(&N)

CrosstabPreferencePage.promptGroup=提示

CrosstabPreferencePage.cubePopup.Text=在将字段拖动到交叉表并成功创建多维数据集之后提示(&H)。

###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=更改多维数据集?

CrosstabDataBinding.message.changeCube=您将要更改交叉表的数据绑定。\n\n是否要清除全部现有的数据列绑定?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=多维数据集

CubeBuilder.warning.title=交叉表

CubeBuilder.warning.message=已成功地创建多维数据集。\n要完成交叉表创建，请将字段从创建的多维数据集拖动到交叉表容器。

CubeBuilder.warning.prompt=不再显示此消息(&D)

###########################################################
#Crosstab drag tracker
CrosstabColumnDragTracker.ResizeColumn=重新设定列大小

CrosstabColumnDragTracker.Show.Label=宽度:

CrosstabRowDragTracker.Show.Label=高度:

###########################################################
#AggregationCellTextViewProvider
AggregationCellTextViewProvider.displayName=文本


###########################################################
#CrosstabSortKeyBuilder properties
CrosstabSortKeyBuilder.choice.ValueOfThisDataItem=此数据项的值

CrosstabSortKeyBuilder.tooltip.ExpBuilder=打开表达式生成器

CrosstabSortKeyBuilder.MSG.CreateNew=新建...

InsertCubeInLayoutAction.menu.text=编辑(&E)

InsertCubeInLayoutAction.action.text=在布局中插入(&N)

InsertCubeInLayoutAction.action.message=使用多维数据集创建交叉表

MapRuleBuilderDialog.MsgDlg.Title=警告

MapRuleBuilderDialog.MsgDlg.Msg=值不能为空。

LevelHandleDropAdapter.ActionText=添加维

LevelPropertyDialog.MSG.CreateNew=


###########################################################
#CrosstabHighlightRuleBuilder properties
CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstab=交叉表

CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstabcell=交叉表单元格

CrosstabHighlightRuleBuilderDialog.text.Description.Element.ReportElement=报表元素

CrosstabHighlightRuleBuilderDialog.text.Description=向 {0} 应用条件格式。请指定条件表达式和格式。\n如果表达式判定为“真”，则将应用格式。

###########################################################
#CrosstabFilterConditionBuilder properties
CrosstabFilterConditionBuilder.ExpressionEditor.Title=表达式编辑器

CrosstabFilterConditionBuilder.MsgDlg.Msg=警告

CrosstabFilterConditionBuilder.MsgDlg.Title=值不能为空。

CrosstabFilterConditionBuilder.Button.UpdateAggregation=重新计算总计(&T)

###########################################################
#Breadcrumb provider properties
VirtualCrosstabCellNodeProvider.Display.ColumnArea=列区域

VirtualCrosstabCellNodeProvider.Display.DetailArea=详细信息区域

VirtualCrosstabCellNodeProvider.Display.RowArea=行区域

VirtualCrosstabCellNodeProvider.Display.UnknownArea=未知区域

CrosstabBindingComboPropertyDescriptorProvider.Flag.DataModel=\ (数据模型)

CrosstabBindingRefresh.action.message=刷新交叉表绑定
