###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=그룹 수준 표시/숨기기
AddLevelHandleAction_TransName=그룹 수준 표시/숨기기
AddMesureViewHandleAction.DisplayName=측정 표시/숨기기
AddMesureViewHandleAction.TransName=측정 표시/숨기기
AddSubTotalAction.LabelName=총합계
AddSubTotalAction.TransName=집계
AddSubTotalAction.DisplayName=집계
AddSubTotalAction.TotalName=합계
CrosstabMenuBuilder.EditCubeAction.DisplayName=데이터 큐브 편집
DeleteDimensionViewHandleAction.TransName=Dimensionviewhandle 삭제
DeleteDimensionViewHandleAction.DisplayName=제거
DeleteMeasureHandleAction.DisplayName=제거
DeleteMeasureHandleAction.TransName=MeasureViewHandle 삭제
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=DiminsionHandle 추가
AddMeasureViewHandleCommand.TransName=MeasureHandle 추가
ChangeAreaCommand.TransName=차원 핸들 삭제
ChangeMeasureOrderCommand.TransName=측정 순서 변경
CreateDimensionViewCommand.TransName=DiminsionViewHandle 생성
CreateMeasureViewCommand.TransName=MeasureViewHandle 생성
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=크로스 탭
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=데이터 필드
GrandTotalProvider.Column.Function=함수
SubTotalProvider.Column.DataField=데이터 필드
SubTotalProvider.Column.Function=함수
SubTotalProvider.Column.AggregateOn=집계 대상:
LevelViewDialog.Title=그룹 수준 표시/숨기기
LevelViewDialog.Label.Info=크로스 탭에 표시할 수준 선택:
AggregationDialog.Title=집계
AggregationDialog.Label.Grand=총합계:
AggregationDialog.Label.Sub=부분합:
ShowSummaryFieldDialog.Title=요약 필드 표시/숨기기
ShowSummaryFieldDialog.Label.Info=크로스 탭에 표시할 수준 선택:
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=열 영역
AreaNodeProvider.RowArea=행 영역
AreaNodeProvider.DetailArea=세부 영역
CrossTabViewNodeProvider.ColumnArea=열 영역
CrossTabViewNodeProvider.RowArea=행 영역
CrosstTabCellNodeProvider.Cell=셀
CrosstTabLevelNodeProvider.Level=수준 - 
CrosstTabMeasureNodeProvider.Detail=상세 정보 - 
MeasureSubNodeProvider.Header=머리글
MeasureSubNodeProvider.Detail=상세 정보
MeasureSubNodeProvider.Aggregation=집계

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=오류
SortkeyBuilder.DialogTitle.Label.Key=키:
CrosstabSortingModelProvider.ColumnName.GroupLevel=그룹 수준
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=그룹 수준:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=식 빌더를 호출하려면 누릅니다.
SortkeyBuilder.DialogTitle.Label.Direction=방향:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=일반
CrosstabPageGenerator.List.Margin=여백
CrosstabPageGenerator.List.Font=글꼴
CrosstabPageGenerator.List.Borders=테두리
CrosstabPageGenerator.List.Section=페이지 나누기
CrosstabPageGenerator.List.Visibility=표시 유형
CrosstabPageGenerator.List.TOC=목차
CrosstabPageGenerator.List.Bookmark=책갈피
CrosstabPageGenerator.List.NamedExpressions=명명된 식
CrosstabPageGenerator.List.UserProperties=사용자 속성
CrosstabPageGenerator.List.AdvancedProperty=고급

CrosstabPageGenerator.TabItem.Binding=바인딩
CrosstabPageGenerator.TabItem.RowArea=행 영역
CrosstabPageGenerator.TabItem.ColumnArea=열 영역
CrosstabPageGenerator.TabItem.DetailArea=세부 영역
CrosstabPageGenerator.TabItem.Filters=필터
CrosstabPageGenerator.TabItem.Highlights=강조
CrosstabPageGenerator.TabItem.map=맵
CrosstabPageGenerator.TabItem.Sorting=정렬

CrosstabGeneraPage.ForEmptyCell=빈 셀 표시 기호:
CrosstabGeneraPage.FormatOption=서식 옵션:
LayoutMeasuresProvider.DisplayName=데이터 필드를 세부 영역에 세로로 배치


parameterBinding.title=데이터 집합 매개 변수 바인딩...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=정렬 방법:
Element.ReportItem.dataSet=데이터 집합:
Element.ReportElement.Cube=데이터(&D):
BindingPage.None=없음


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=속성


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
