###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=显示/隐藏组级别
AddLevelHandleAction_TransName=显示/隐藏组级别
AddMesureViewHandleAction.DisplayName=显示/隐藏度量
AddMesureViewHandleAction.TransName=显示/隐藏度量
AddSubTotalAction.LabelName=总计
AddSubTotalAction.TransName=聚合
AddSubTotalAction.DisplayName=聚合
AddSubTotalAction.TotalName=合计
CrosstabMenuBuilder.EditCubeAction.DisplayName=编辑多维数据集
DeleteDimensionViewHandleAction.TransName=删除维视图句柄
DeleteDimensionViewHandleAction.DisplayName=删除
DeleteMeasureHandleAction.DisplayName=删除
DeleteMeasureHandleAction.TransName=删除度量视图句柄
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=添加维句柄
AddMeasureViewHandleCommand.TransName=添加度量句柄
ChangeAreaCommand.TransName=删除维句柄
ChangeMeasureOrderCommand.TransName=更改度量顺序
CreateDimensionViewCommand.TransName=创建维视图句柄
CreateMeasureViewCommand.TransName=创建度量视图句柄
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=交叉表
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=数据字段
GrandTotalProvider.Column.Function=函数
SubTotalProvider.Column.DataField=数据字段
SubTotalProvider.Column.Function=函数
SubTotalProvider.Column.AggregateOn=聚合条件
LevelViewDialog.Title=显示/隐藏组级别
LevelViewDialog.Label.Info=选择要在交叉表上显示的级别:
AggregationDialog.Title=聚合
AggregationDialog.Label.Grand=总计:
AggregationDialog.Label.Sub=小计:
ShowSummaryFieldDialog.Title=显示/隐藏摘要字段
ShowSummaryFieldDialog.Label.Info=选择要在交叉表上显示的级别:
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=列区域
AreaNodeProvider.RowArea=行区域
AreaNodeProvider.DetailArea=详细信息区域
CrossTabViewNodeProvider.ColumnArea=列区域
CrossTabViewNodeProvider.RowArea=行区域
CrosstTabCellNodeProvider.Cell=单元格
CrosstTabLevelNodeProvider.Level=级别 - 
CrosstTabMeasureNodeProvider.Detail=详细资料 - 
MeasureSubNodeProvider.Header=页眉
MeasureSubNodeProvider.Detail=详细资料
MeasureSubNodeProvider.Aggregation=聚合

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=错误
SortkeyBuilder.DialogTitle.Label.Key=关键字:
CrosstabSortingModelProvider.ColumnName.GroupLevel=组级别
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=组级别:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=单击以调用表达式生成器
SortkeyBuilder.DialogTitle.Label.Direction=方向:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=常规
CrosstabPageGenerator.List.Margin=边距
CrosstabPageGenerator.List.Font=字体
CrosstabPageGenerator.List.Borders=边框
CrosstabPageGenerator.List.Section=分页符
CrosstabPageGenerator.List.Visibility=可见性
CrosstabPageGenerator.List.TOC=目录
CrosstabPageGenerator.List.Bookmark=书签
CrosstabPageGenerator.List.NamedExpressions=命名表达式
CrosstabPageGenerator.List.UserProperties=用户属性
CrosstabPageGenerator.List.AdvancedProperty=高级

CrosstabPageGenerator.TabItem.Binding=绑定
CrosstabPageGenerator.TabItem.RowArea=行区域
CrosstabPageGenerator.TabItem.ColumnArea=列区域
CrosstabPageGenerator.TabItem.DetailArea=详细信息区域
CrosstabPageGenerator.TabItem.Filters=筛选器
CrosstabPageGenerator.TabItem.Highlights=突出显示
CrosstabPageGenerator.TabItem.map=映射
CrosstabPageGenerator.TabItem.Sorting=排序

CrosstabGeneraPage.ForEmptyCell=对于空单元格，显示:
CrosstabGeneraPage.FormatOption=格式选项:
LayoutMeasuresProvider.DisplayName=在详细信息区域中垂直布局数据字段


parameterBinding.title=数据集参数绑定...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=排序时间:
Element.ReportItem.dataSet=数据集:
Element.ReportElement.Cube=数据(&D):
BindingPage.None=无


FilterHandleProvider.Label.Filterby=Filter by:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=属性


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=New Filter Condition
FilterConditionBuilder.DialogTitle.Edit=Edit Filter Condition
FilterConditionBuilder.choice.ValueOfThisDataItem=Value of this data item
FilterConditionBuilder.tooltip.ExpBuilder=Click to invoke the Expression Builder.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Enter a filter condition:
FilterConditionBuilder.text.GroupLevel=Group Level:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Drop data field(s) to define columns here
Blank.text.row=Drop data field(s)\nto define rows here
Blank.text.measure=Drop data field(s) to be summarized here
