###########################################################
# Crosstab Action mame and trans name
AddLevelHandleAction_Displayname=Mostrar/ocultar niveles de grupo
AddLevelHandleAction_TransName=Mostrar/ocultar niveles de grupo
AddMesureViewHandleAction.DisplayName=Mostrar/ocultar medidas
AddMesureViewHandleAction.TransName=Mostrar/ocultar medidas
AddSubTotalAction.LabelName=Total general
AddSubTotalAction.TransName=Agregación
AddSubTotalAction.DisplayName=Totales
AddSubTotalAction.TotalName=TOTAL
CrosstabMenuBuilder.EditCubeAction.DisplayName=Editar cubo de datos
DeleteDimensionViewHandleAction.TransName=Eliminar Dimensionviewhandle
DeleteDimensionViewHandleAction.DisplayName=Quitar
DeleteMeasureHandleAction.DisplayName=Quitar
DeleteMeasureHandleAction.TransName=Eliminar MeasureViewHandle
###########################################################
# Crosstab Command trans name
AddDimensionViewHandleCommand.TransName=Agregar DiminsionHandle
AddMeasureViewHandleCommand.TransName=Agregar MeasureHandle
ChangeAreaCommand.TransName=Suprimir controlador de dimensión
ChangeMeasureOrderCommand.TransName=Cambiar el orden de las medidas
CreateDimensionViewCommand.TransName=Crear DiminsionViewHandle
CreateMeasureViewCommand.TransName=Crear MeasureViewHandle
###########################################################
# Crosstab EditPart
###########################################################
# Crosstab Command trans name
CrosstabTableEditPart.GuideText=Tabla de referencias cruzadas
###########################################################
# Crosstab Dialog trans name
GrandTotalProvider.Column.DataField=Campo de datos
GrandTotalProvider.Column.Function=Función
SubTotalProvider.Column.DataField=Campo de datos
SubTotalProvider.Column.Function=Función
SubTotalProvider.Column.AggregateOn=Agregar en
LevelViewDialog.Title=Mostrar/ocultar niveles de grupo
LevelViewDialog.Label.Info=Seleccionar niveles para mostrar en tabla de referencias cruzadas:
AggregationDialog.Title=Totales
AggregationDialog.Label.Grand=Totales generales:
AggregationDialog.Label.Sub=Subtotales:
ShowSummaryFieldDialog.Title=Mostrar/ocultar campos de resumen
ShowSummaryFieldDialog.Label.Info=Seleccionar niveles para mostrar en tabla de referencias cruzadas:

DeleteBindingDialog.Title=¿Eliminar los enlaces no utilizados?
DeleteBindingDialog.Message=Esta acción producirá enlaces de datos no utilizados.\n\n¿Desea eliminar los enlaces no utilizados?
DeleteBindingDialog.ToggleMessage=No volver a mostrar este mensaje
###########################################################
# Crosstab Outline Node
AreaNodeProvider.ColumnArea=Área de columna
AreaNodeProvider.RowArea=Área de fila
AreaNodeProvider.DetailArea=Área de detalle
CrossTabViewNodeProvider.ColumnArea=Área de columna
CrossTabViewNodeProvider.RowArea=Área de fila
CrossTabCellNodeProvider.Cell=Celda
CrossTabLevelNodeProvider.Level=Nivel - 
CrossTabMeasureNodeProvider.Detail=Detalle - 
MeasureSubNodeProvider.Header=Encabezado
MeasureSubNodeProvider.Detail=Detalle
MeasureSubNodeProvider.Aggregation=Agregación

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Error
SortkeyBuilder.DialogTitle.Label.Key=Clave:
CrosstabSortingModelProvider.ColumnName.GroupLevel=Nivel de grupo
CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=Nivel de grupo:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Hacer clic para llamar al compilador de expresiones
SortkeyBuilder.DialogTitle.Label.Direction=Dirección:

###########################################################
#GrossTabPageGenerator properties
CrosstabPageGenerator.List.General=General
CrosstabPageGenerator.List.Margin=Margen
CrosstabPageGenerator.List.Font=Fuente
CrosstabPageGenerator.List.Borders=Borde
CrosstabPageGenerator.List.Section=Salto de página
CrosstabPageGenerator.List.Visibility=Visibilidad
CrosstabPageGenerator.List.TOC=Tabla de contenido
CrosstabPageGenerator.List.Bookmark=Marcador
CrosstabPageGenerator.List.NamedExpressions=Expresiones con nombre
CrosstabPageGenerator.List.UserProperties=Propiedades de usuario
CrosstabPageGenerator.List.AdvancedProperty=Avanzada

CrosstabPageGenerator.TabItem.Binding=Enlace
CrosstabPageGenerator.TabItem.RowArea=Área de fila
CrosstabPageGenerator.TabItem.ColumnArea=Área de columna
CrosstabPageGenerator.TabItem.DetailArea=Área de detalle
CrosstabPageGenerator.TabItem.Filters=Filtros
CrosstabPageGenerator.TabItem.Highlights=Resaltados
CrosstabPageGenerator.TabItem.map=Asignar
CrosstabPageGenerator.TabItem.Sorting=Ordenar

CrosstabGeneraPage.ForEmptyCell=En las celdas vacias, mostrar:
CrosstabGeneraPage.FormatOption=Opciones de formato:
LayoutMeasuresProvider.DisplayName=Campos de datos de diseño en área de detalle verticalmente


parameterBinding.title=Enlace de parámetros de conjunto de datos...

###########################################################
#SortingHandleProvider properties
SortingHandleProvider.Label.SortOn=Ordenar según:
Element.ReportItem.dataSet=Conjunto de datos:
Element.ReportElement.Cube=&Datos:
BindingPage.None=Ninguno


FilterHandleProvider.Label.Filterby=Filtrar por:

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Propiedades


###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=Nueva condición de filtro
FilterConditionBuilder.DialogTitle.Edit=Editar condición de filtro
FilterConditionBuilder.choice.ValueOfThisDataItem=Valor de este elemento de datos
FilterConditionBuilder.tooltip.ExpBuilder=Hacer clic para llamar al compilador de expresiones.
FilterConditionBuilder.text.AND=Y
FilterConditionBuilder.text.Condition=Introducir una condicion de filtro:
FilterConditionBuilder.text.GroupLevel=Nivel de grupo:

###########################################################
#VirtualCellEditPart.java
Blank.text.column=Suprimir los campos de datos para definir aquí las columnas
Blank.text.row=Suprimir los campos de datos\npara definir aquí las filas
Blank.text.measure=Suprimir los campos de datos para resumirlos aquí

###########################################################
#CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Total general
CrosstabGrandTotalDialog.Text.DataField=Campo de datos:
CrosstabGrandTotalDialog.Text.Function=Función:


###########################################################
# Crosstab RowArea PageBreak
CrosstabPageBreakProvider.Column.GroupLevel=Nivel de grupo
CrosstabPageBreakProvider.Column.Before=Antes
CrosstabPageBreakProvider.Column.After=Después

###########################################################
# Crosstab RowArea SubTotal
CrosstabSubToatalProvider.Column.AggregateOn=Agregar en
CrosstabSubToatalProvider.Column.DataField=Campo de datos
CrosstabSubToatalProvider.Column.Function=Función

###########################################################
#CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Salto de página
CrosstabPageBreakDialog.Text.GroupLevel=Nivel de grupo:
CrosstabPageBreakDialog.Text.PageBreakBefore=Antes:
CrosstabPageBreakDialog.Text.PageBreakAfter=Después de:

###########################################################
#SubTotalDialog
SubTotalDialog.Title=Subtotal
SubTotalDialog.Text.AggregateOn=Agregar en:
SubTotalDialog.Text.Function=Función:
SubTotalDialog.Text.DataField=Campo de datos:

FormPage.Menu.ModifyProperty=Modificar

CrosstabPageGenerator.List.SubTotals=Subtotales
CrosstabPageGenerator.List.GrandTotals=Totales generales
CrosstabPageGenerator.List.PageBreak=Salto de página

PageLayoutPropertyDescriptorProvider.PageLayout=Diseño de página:
CrosstabSectionPage.RepeatColumnHeader=Repetir encabezado de columna

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Compilar expresión...>
ExpressionValueCellEditor.selectValueAction=<Seleccionar valor...>
ExpressionValueCellEditor.title=Seleccionar valor
CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Seleccionar columna Valor de miembro
CrosstabSortKeyBuilder.Label.SelRowMemberValue=Seleccionar fila Valor de miembro
CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Seleccionar columna Valor de miembro
CrosstabFilterConditionBuilder.Label.SelRowMemberValue=Seleccionar fila Valor de miembro
CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=Nivel de grupo:
SelColumnMemberValue.Column.Level=Nivel
SelColumnMemberValue.Column.Value=Valor
ChoiceSetFactory.choice.None=Ninguno

###########################################################
#SelectValueDialog properties
SelectValueDialog.errorRetrievinglist=Error al recuperar la lista
SelectValueDialog.messages.error.selectVauleUnavailable=No se puede recuperar el valor de la expresión.
SelectValueDialog.noExpressionSet=No se ha ajustado ninguna expresión
SelectValueDialog.retrieving=Recuperando lista...
SelectValueDialog.selectValue=Seleccionar valor
SelectValueDialog.messages.info.selectVauleUnavailable=La lista de valores no está disponible.

CrosstabPreferencePage.Title=Tabla de referencias cruzadas
CrosstabPreferencePage.filterLimit=Límite de filtro
CrosstabPreferencePage.filterLimit.prompt=Número máximo de valores que mostrar:
CrosstabPreferencePage.Error.MaxRowInvalid=El valor de número no es válido.
CrosstabPreferencePage.autoDelBindings.Text=Preguntar siempre antes de eliminar los enlaces no utilizados.
CrosstabPreferencePage.promptGroup=Solicitar


###########################################################
#Crosstab DataBinding properties
CrosstabDataBinding.title.ChangeCube=¿Cambiar cubo?
CrosstabDataBinding.message.changeCube=Va a cambiar el enlace de datos de la tabla de referencias cruzadas.  \n\n¿Desea borrar todos los enlaces de columna de datos existentes?

###########################################################
#Crosstab DropAdapter properties
DataColumnXTabDropAdapter.DataCube=Cubo de datos
