###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC Databases Profile Data Source ODA Runtime Driver
data.source.name=Datenquellenprofil für BIRT-JDBC-Datenbanken [Prototyp]
data.set.name=SQL Select-Abfrage [Abfrage-Editor-Prototyp]
connection.profile.name=Verbindungsprofil für BIRT-JDBC-Datenbanken

