###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC 데이터베이스 연결 데이터 원본 ODA 런타임 드라이버
data.source.name=쿼리 빌더에 대한 JDBC 데이터베이스 연결
data.set.name=SQL Select 쿼리[쿼리 빌더 프로토타입]
connection.profile.name=BIRT JDBC 데이터베이스 연결 프로필
dataset.property.parameterMetaData=BIRT JDBC 매개 변수 메타데이터
datasource.property.username=사용자 이름(&N)
datasource.property.password=암호(&W)
datasource.property.jdbcURL=JDBC 드라이버 URL(&R)
datasource.property.driverClass=JDBC 드라이버 클래스(&C)
datasource.property.jarlist=',' 구분 기호를 사용하는 JDBC 드라이버 JAR 목록(&J)
datasource.property.databasename=데이터베이스(&D)
