###############################################################################
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC Database Connection Data Source ODA Runtime Driver
data.source.name=クエリビルダの JDBC データベース接続 [プロトタイプ]
data.set.name=SQL Select クエリ [クエリビルダのプロトタイプ]
connection.profile.name=BIRT JDBC データベース接続プロファイル
dataset.property.parameterMetaData=BIRT JDBC パラメタメタデータ
datasource.property.username=ユーザ名(&N)
datasource.property.password=パスワード(&W)
datasource.property.jdbcURL=JDBC ドライバ URL(&R)
datasource.property.driverClass=JDBC ドライバクラス(&C)
datasource.property.jarlist=JDBC ドライバ JAR リスト (コンマ区切り) (&J)
datasource.property.databasename=データベース(&D)
