###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC Databases Profile Data Source ODA Runtime Driver
data.source.name=Fuente de datos del perfil de bases de datos JDBC BIRT [Prototipo]
data.set.name=Consulta de selección de SQL [Prototipo de compilador de consultas]
connection.profile.name=Perfil de conexión de bases de datos JDBC BIRT
dataset.property.parameterMetaData=Metadatos de parámetros JDBC BIRT
