###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=ODA-Laufzeittreiber für Datenquellenverbindung für JDBC-Datenbanken
data.source.name=JDBC-Datenbankverbindung für Abfrageerstellung
data.set.name=SQL Select-Abfrage [Abfrage-Editor-Prototyp]
connection.profile.name=BIRT-JDBC-Datenbankverbindungsprofil
dataset.property.parameterMetaData=BIRT-JDBC-Parameter-Metadaten
datasource.property.username=Benutzer&name
datasource.property.password=Kenn&wort
datasource.property.jdbcURL=JDBC-Treiber-&URL
datasource.property.driverClass=JDBC-Treiber&klasse
datasource.property.jarlist=&JAR-Liste für JDBC-Treiber mit ';' als Trennzeichen
datasource.property.databasename=&Datenbank
