###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC Database Connection Data Source ODA Runtime Driver
data.source.name=Conexión de base de datos JDBC para compilador de consultas

data.set.name=Consulta de selección de SQL [Prototipo de compilador de consultas]

connection.profile.name=BIRT JDBC Database Connection Profile
dataset.property.parameterMetaData=BIRT JDBC Parameter MetaData
datasource.property.username=&Nombre de usuario

datasource.property.password=Cont&raseña

datasource.property.jdbcURL=UR&L del controlador JDBC

datasource.property.driverClass=&Clase del controlador JDBC

datasource.property.jarlist=Controlador JDBC y lista de archivos &jar

datasource.property.databasename=&Base de datos
