###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Pilote d'exécution ODA de source de données de connexion aux bases de données JDBC
data.source.name=Connexion aux bases de données JDBC pour générateur de requête
data.set.name=Requête de sélection SQL [Prototype de générateur de requête]
connection.profile.name=Profil de connexion aux bases de données JDBC BIRT
dataset.property.parameterMetaData=Métadonnées du paramètre BIRT JDBC
datasource.property.username=&Nom d'utilisateur
datasource.property.password=&Mot de passe
datasource.property.jdbcURL=U&RL de pilote JDBC
datasource.property.driverClass=&Classe de pilote JDBC
datasource.property.jarlist=Liste &JAR de pilote JDBC utilisant le séparateur ';'
datasource.property.databasename=&Base de données
