###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=JDBC Database Connection Data Source ODA Runtime Driver
data.source.name=JDBC Database Connection for Query Builder

data.set.name=SQL Select Query [Query Builder]

connection.profile.name=BIRT JDBC Database Connection Profile
dataset.property.parameterMetaData=BIRT JDBC Parameter MetaData
datasource.property.username=User &Name

datasource.property.password=Pass&word

datasource.property.jdbcURL=JDBC Driver U&RL

datasource.property.driverClass=JDBC Driver &Class

datasource.property.jarlist=JDBC Driver &JAR List

datasource.property.databasename=データベース(&D)
