ChartImpl.ChartTitle=グラフのタイトル

ChartImpl.AltText=このグラフにはデータがありません。

ChartWithAxesImpl.X_Axis.title=X 軸のタイトル

ChartWithAxesImpl.Y_Axis.title=Y 軸のタイトル

ChartWithAxesImpl.Z_Axis.title=Z 軸のタイトル

ChartWithoutAxesImpl.Unsupported3Dimension=パイグラフでは 3D はサポートされません。

exception.convert.double=値 {0} を倍精度の値に変換できません。

exception.data.outofsync=入力データが同期していません。カテゴリ系列に {0} 個の値が含まれていますが、値系列に {1} 個の値が含まれています。

exception.out.of.bounds=範囲外

exception.step.zoom.out=ステップ {0} で zoomOut を実行できませんでした。

exception.no3d.support=3D グラフは、まだサポートされていません。

exception.curve.label.position.not.supported=曲線にはラベル位置 [{0}] を使用できません。

exception.convert.calendar=値 {0} をカレンダーの値に変換できません。

exception.anchor.transpose=軸の向き {1} のアンカー {0} を置き換えることはできません。

exception.tick.computations=目盛の演算にエラーがあります。

exception.curve.visibility.unset=曲線の可視性は、線の属性で設定する必要があります。

exception.angle.range.transpose=[角度={0}] は、範囲 (90 >= 0 >= -90) を超えて置き換えることはできません。

exception.legend.direction.tblr=凡例の方向が上下または左右のいずれかに明確に指定されていません。

exception.scale.null.location=スケール {0} の NULL 値の座標が見つかりません。

exception.illegal.icon.palette.type.for.marker=''{0}'' 形式のイメージは、マーカのアイコンには使用できません。

exception.illegal.filltype.crosshair.marker=マーカ CROSSHAIR のパレットの色には {0} を設定できません。

exception.illegal.filltype.cross.marker=マーカ CROSS のパレットの色には {0} を設定できません。

exception.invalid.step.size =軸スケールに指定した ''step size({0}) <= 0'' が無効です。

exception.invalid.step.number =軸スケールに指定した ''step number({0}) < 1'' が無効です。

exception.curve.line.visibility.not.defined=曲線の可視性プロパティが正しく定義されていません。

exception.min.largerthan.max=軸スケールに指定したエントリ ''min({0}) > max({1})'' が無効です。

exception.combination.axis.label.position=軸 = {0} とラベル位置 = {1} の組み合わせは無効です。

exception.cannot.locate.start.marker.range=マーカの範囲 {1} に含まれる値 {0} の開始位置を見つけられませんでした。

exception.cannot.locate.value.marker.line=マーカの線 {1} に含まれる値 {0} を見つけられませんでした。

exception.combination.axis.tick.style=軸 = {0} と目盛スタイル = {1} の組み合わせは無効です。

exception.invalid.axis.data.type=軸に指定したデータ型が、データフィールド値のデータ型と異なります : ({0})

exception.undefined.axis.data.type=軸 {0} のデータ型が定義されていません。

exception.unsupported.compare.text=テキストデータ要素の比較はサポートされていません。

exception.unsupported.comparison=オブジェクト {0} は、PrimitiveRenderingEvent の比較には含めることができません。

exception.unsupported.internal.draw=このイベントでは {0} を内部で描画できません。

exception.unsupported.internal.fill=このイベントでは {0} を内部で塗つぶすことができません。

exception.unsupported.chart.model=モデル [{0}] で定義したグラフを計算できません。

exception.unsupported.bounds=イベント {0} の範囲を計算できません。

exception.unsupported.copy=イベント {0} のコピーを作成できません。

exception.unsupported.step.number=ステップ番号には数値しか使用できません。

exception.undefined.data.point=系列の定義に関連付けられている DataPoint の値が指定されていません。

exception.unit.size.failure=目盛の座標が定義されていないため、単位のサイズを計算できません。

exception.process.content.type={1} 型に {0} として指定したデータセットのコンテンツを処理できません。

exception.undefined.axis.label.visibility={0} 軸のラベルの可視性が定義されていません。

exception.undefined.axis.title.visibility={0} 軸のタイトルの可視性が定義されていません。

exception.undefined.axis.label.position={0} 軸のラベルの位置が定義されていません。

exception.undefined.axis.title.position={0} 軸のタイトルの位置が定義されていません。

exception.undefined.data.label.position={0} 系列のデータラベルの位置が定義されていません。

exception.undefined.axis.type=軸の型が定義されていません。

exception.unset.series.stacked.property=積み上げ可能な {0} 系列の積み上げプロパティが明示的に指定されていません。

exception.undefined.axis.major.tick.style={0} 軸の目盛線の目盛のスタイルが定義されていません。

exception.undefined.axis.minor.tick.style={0} 軸の補助目盛線の目盛のスタイルが定義されていません。

exception.zero.negative.logarithmic.scale=対数軸には、0 および負の値を使用できません。

exception.illegal.vaxis.label.position=縦軸 {1} のラベル位置に、無効な値 {0} が指定されました。

exception.illegal.vaxis.title.position=縦軸 {1} のタイトル位置に、無効な値 {0} が指定されました。

exception.illegal.vaxis.major.tick.style=縦軸 {1} の目盛に、無効なスタイル {0} が指定されました。

exception.illegal.vaxis.minor.tick.style=縦軸 {1} の補助目盛に、無効なスタイル {0} が指定されました。

exception.illegal.haxis.label.position=横軸 {1} のラベル位置に、無効な値 {0} が指定されました。

exception.illegal.haxis.title.position=横軸 {1} のタイトル位置に、無効な値 {0} が指定されました。

exception.illegal.rotation.angle.label=ラベル {0} の回転角度 (-90 <= ANGLE <= 90) が正しく指定されていません。

exception.illegal.rendering.direction=凡例のレンダリングの方向に、無効な引数 {0} が指定されました。

exception.illegal.rendering.orientation=凡例のレンダリングの向きに、無効な引数 {0} が指定されました。

exception.illegal.legend.direction=凡例のレンダリングの方向に、無効な引数 {0} が指定されました。

exception.illegal.null.value=グラフを構築する引数として、無効な NULL 値が渡されました。

exception.cannot.find.plugin.entry=使用可能なすべてのプラグインの plugin.xml ファイルに lookup={0}; element=({1}:{2}) のエントリが見つかりません。

exception.cannot.split.major=単位を {0} 個の補助単位に分割できません。

exception.illegal.legend.orientation=凡例のレンダリングの向きに、無効な引数 {0} が指定されました。

exception.cwoa.single.runtime.series=軸のないグラフには、実行時系列を 1 つしか定義できません。

exception.illegal.haxis.major.tick.style=横軸 {1} の目盛に、無効なスタイル {0} が指定されました。

exception.illegal.haxis.minor.tick.style=横軸 {1} の補助目盛に、無効なスタイル {0} が指定されました。

exception.client.area.outline.visibility=クライアント領域の外枠の可視性が指定されていません。

exception.cannot.locate.end.marker.range=マーカの範囲 {1} に含まれる値 {0} の終了位置を見つけられませんでした。

exception.runtime.dataset.count.mismatch=積み上げ実行時系列のデータセット数が一致しません ({0}\!={1})。

exception.illegal.base.runtime.series.count=軸のないグラフには、カテゴリ実行時系列の数 (ここでは {0}) を 1 に指定する必要があります。

exception.unstackable.is.stacked=積み上げられない系列 {0} が、積み上げに指定されています。

exception.unset.label.visibility=ラベル {0} の可視性が設定されていません。

exception.marker.line.null.value=マーカの線 {0} で定義されている NULL 値には、レンダリングする線をプロットできません。

exception.unset.axis.visibility=軸の可視性が設定されていないため、結果があいまいになります。

exception.unset.line.visibility={0} にある線の表示属性が明示的に指定されていません。

exception.stacked.datetime.axis.series=日付 / 時間軸 {0} には、積み上げ系列を定義できません。

exception.stacked.unstacked.mix.series=系列の定義 {0} に、積み上げ系列と積み上げでない系列が混在しています。

exception.internal.stack.series.setup=軸 {0} の積み上げ系列が正しく指定されていません。

exception.invalid.minimum.scale.value=軸の型 {1} に指定したスケールの最小値 {0} が無効です。

exception.invalid.maximum.scale.value=軸の型 {1} に指定したスケールの最大値 {0} が無効です。

exception.legend.orientation.horzvert=凡例の向きが横または縦のいずれかに明確に指定していません。

exception.legend.orientation.InvalidMaxPercent=最大の割合 (%) は、0 から 1 の範囲で指定してください。

info.processing.stacked.info={0} 軸の積み上げ情報を処理中。

info.eclenv.creating.device=(ECLIPSE 環境) デバイス {0} を {1} として作成中。

info.stdenv.creating.device=(スタンドアローン環境) デバイス {0} を {1} として作成中。

info.eclenv.creating.display=(ECLIPSE 環境) Display Server {0} を {1} として作成中。

info.stdenv.creating.display=(スタンドアローン環境) Display Server {0} を {1} として作成中。

exception.percent.stacked.non.numerical=数値以外のデータが含まれているため、割合 / 積み上げグラフの軸を計算できません。

exception.text.data.numerical.datetime.axis=数値 / 日時の軸には、テキストデータをレンダリングできません。

exception.numerical.data.datetime.axis=日時の軸には、日時以外のデータをレンダリングできません。

exception.datetime.data.numerical.axis=数値の軸には、数値以外のデータをレンダリングできません。

exception.cwoa.single.series.definition=軸のないグラフには、系列を 1 つしか定義できません。

exception.parse.value.format.specifier=書式指定子が {1} の値 {0} を解析できません。

exception.orthogonal.axis.numerical.datetime=値軸には、数値や日時の書式しか設定できません。

exception.axis.series.link.broken=系列 {0} の軸の定義が見つかりません。

exception.process.content.dataset=データセット {1} に {0} として指定したデータセットのコンテンツを処理できません。

exception.base.orthogonal.inconsistent.count=カテゴリ軸には {0} 個の項目、値軸には {1} 個の項目が含まれています。

exception.base.orthogonal.null.datapoint=指定したデータポイントには、無効な null 値が含まれています。

exception.base.orthogonal.null.datadefinition=指定したデータ定義の式は無効です。.

exception.dataset.non.numerical.to.numerical=データセットに数値以外のデータ型 {0} が含まれているため、数値に変換できません。

exception.dataset.non.datetime=X 軸にバインドされているデータ型は、DateTime の書式ではありません。

exception.scale.tick.max=ステップが多すぎて表示できません。目盛りの間隔か、単位を調整してください。

exception.unknown.axis.type.tick.computations=目盛を計算するために必要な軸の型を識別できません。

exception.unknown.trigger.datatype=トリガデータが無効か、不明なデータ型です。

exception.unsupported.compare.unknown.objects=DE1={0} と DE2={1} を比較するために指定したデータ要素はサポートされていません。

exception.unsupported.compare.different.objects=DE1={0} と DE2={1} を比較するために指定したデータ要素が混在してます。

exception.resultset.data.type.retrieval.failed=結果セットのデータ型を識別できません。

exception.base.axis.no.series.definitions=カテゴリの主軸に系列の定義が含まれていません。

exception.no.stack.percent.3D.chart=3D グラフでは、積み上げやパーセントを表せません。

exception.dial.dimension=ダイヤルの系列では ''{0}'' を使用できません。

exception.pie.dimension=パイの系列では ''{0}'' を使用できません。

exception.scatter.dimension=分布の系列では ''{0}'' を使用できません。

exception.stock.dimension=株価の系列では ''{0}'' を使用できません。

exception.multi.orthogonal.3D.not.supported=3D グラフでは複数の値軸を使用できません。

exception.scatter.3D.not.supported=3D グラフでは分布カテゴリ軸を使用できません。

exception.no.transposed.3D.chart=3D グラフでは交差を使用できません。

exception.3D.points.length.less.than.3=3D のレンダリングイベントでは、ポイント一覧を 3 以上の長さに指定してください。

exception.unsupported.area3d.getOjbect3D=Area3DRenderEvent から Object3D に直接アクセスすることはできません。サブ I3DRenderEvent を繰り返して処理してください。

exception.javascript.error={0} がグラフスクリプト ''{2}'' の {1} 行目にあります。

exception.null.legend.layout.hints=レイアウトヒントオブジェクトが Null の凡例はレンダリングできません。

exception.null.legend.item.hints=項目ヒントオブジェクトが Null の凡例項目はレンダリングできません。

info.elapsed.render.time=レンダリング完了までの所要時間 = {0} ミリ秒

info.elapsed.time.render=レンダリング完了までの所要時間 = {0} ミリ秒

info.eclenv.creating.dsp=(ECLIPSE 環境) DSP {0} の作成中

info.datapoint.to.string={0}:{1}
info.stdenv.creating.dsp=(スタンドアローン環境) DSP {0} の作成中

constant.undefined.string=<指定されていません>

constant.null.string=null

error.invalid.enumerator=値 ''{0}'' は ''{1}'' の有効な列挙値ではありません。

error.invalid.classifier=データ型 ''{0}'' は有効な分類子ではありません。

error.invalid.argument.for.barSeries={0} は、BarSeriesImpl の引数としては使用できません。グラフのモデルには、org.eclipse.birt.chart.model.ChartWithAxes のインスタンスを指定する必要があります。

error.invalid.argument.for.lineSeries={0} は、LineSeriesImpl の引数としては使用できません。グラフのモデルには、org.eclipse.birt.chart.model.ChartWithAxes のインスタンスを指定する必要があります。

error.invalid.argument.for.stockSeries={0} は、StockSeriesImpl の引数としては使用できません。グラフのモデルには、org.eclipse.birt.chart.model.ChartWithAxes のインスタンスを指定する必要があります。

error.legend.position=グラフのコンポーネントを正しく配置するには、凡例ブロックの位置を指定する必要があります。

error.null.source=ソースの値は null にすることができません。

error.unknown.palette=不明なパレット {0} がリクエストされました。デフォルトが使用されます。

error.type.not.set=使用する DateFormatSpecifier のインスタンスの型が設定されていません。

error.eclenv.cannot.find.dsp=(ECLIPSE 環境) {0} の DSP の実装が見つかりませんでした。

error.stdenv.cannot.find.dsp=(スタンドアローン環境) {0} の DSP の実装が見つかりません。

info.eclenv.creating.series.renderer=(ECLIPSE 環境) 系列レンダリング機能 {0} の作成中

info.eclenv.creating.datapoint.definition=(ECLIPSE 環境) データポイント定義 {0} を作成中です。

error.eclenv.cannot.find.series.renderer=(ECLIPSE 環境) {0} の系列レンダリング機能の実装が見つかりません。

info.stdenv.creating.series.renderer=(スタンドアローン環境) Series Renderer {0} の作成中

info.compute.elapsed.time.without.axes=プロット計算の所要時間 (軸なし) = {0} ミリ秒

info.compute.elapsed.time.with.axes=プロット計算の所要時間 (軸あり) = {0} ミリ秒

error.stdenv.cannot.find.series.renderer=(スタンドアローン環境) {0} 系列レンダリング機能の実装が見つかりません。

error.stdenv.cannot.find.datapoint.definition=(スタンドアローン環境) データポイント定義の {0} への実装が見つかりません。

error.eclenv.cannot.find.device=(ECLIPSE 環境) {0} のデバイスレンダリング機能の実装が見つかりません。

error.stdenv.cannot.find.device=(スタンドアローン環境) {0} のデバイスレンダリング機能の実装が見つかりません。

error.eclenv.cannot.find.display=(ECLIPSE 環境) {0} の Display Server の実装が見つかりません。

error.stdenv.cannot.find.display=(スタンドアローン環境) {0} の Display Server の実装が見つかりません。

info.log.script=[スクリプト]: {0}

info.render.series={0}: renderSeries() [{1}/{2}]
info.log.info=[情報]: {0}

info.log.warn=[警告]: {0}

info.log.err=[エラー]: {0}

info.log.fatal=[重大]: {0}

prefix.marker.range.caption=[
separator.marker.range.caption=\ ～

suffix.marker.range.caption=]
wrapped.instruction.to.string={0}: モデル = {1}、範囲 = {2}

exception.mixed.data.types=集計関数 {0} で集計しようとした入力データの型が混在してます。

info.eclenv.creating.function=(ECLIPSE 環境) 集計関数 {0} を作成中です。

error.eclenv.cannot.find.function=(ECLIPSE 環境) {0} の集計関数の実装が見つかりません。

info.stdenv.creating.function=(スタンドアローン環境) 集計関数 {0} を作成中です。

error.stdenv.cannot.find.function=(スタンドアローン環境) {0} の集計関数の実装が見つかりません。

Info.try.load.java.handler=Chart Java イベントハンドラのクラスを読み込んでいます...

Info.java.handler.loaded=Chart Java イベントハンドラのクラス [{0}] を読み込みました。

Info.invalid.java.handler=無効な Chart Java イベントハンドラのクラス [{0}] が検出されたか、無視されました。

Info.try.register.javascript.content=Chart JavaScript のコンテンツを読み込んでいます...

Info.javascript.content.registered=Chart JavaScript のコンテンツを読み込みました。

warn.unspecified.sorting={0} にソート順が指定されていません。

##################################################
# Attributes 
#
# !!the key is bound to those attribute literal' name value, 
# !!if that changes, this must be updated accordingly.
#
SeriesImpl.displayName=単純な系列

AreaSeriesImpl.displayName=面積の系列

BarSeriesImpl.displayName=棒の系列

BarSeriesImpl.coneDisplayName=円錐系列

BarSeriesImpl.tubeDisplayName=円筒系列

BarSeriesImpl.pyramidDisplayName=ピラミッド系列

DialSeriesImpl.displayName=ダイヤル系列

LineSeriesImpl.displayName=線の系列

PieSeriesImpl.displayName=パイの系列

ScatterSeriesImpl.displayName=分布の系列

StockSeriesImpl.displayName=株価の系列

BubbleSeriesImpl.displayName=バブルの系列

GanttSeriesImpl.displayName=ガントの系列

DifferenceSeriesImpl.displayName=差分の系列

AxisType.Linear.displayName=線形

AxisType.Logarithmic.displayName=対数

AxisType.Text.displayName=テキスト

AxisType.DateTime.displayName=DateTime
IntersectionType.Min.displayName=Min

IntersectionType.Max.displayName=Max

IntersectionType.Value.displayName=値

ScaleUnitType.Seconds.displayName=秒

ScaleUnitType.Minutes.displayName=分

ScaleUnitType.Hours.displayName=時間

ScaleUnitType.Days.displayName=日

ScaleUnitType.Weeks.displayName=週

ScaleUnitType.Months.displayName=月

ScaleUnitType.Quarters.displayName=四半期

ScaleUnitType.Years.displayName=年

SortOption.Ascending.displayName=昇順

SortOption.Descending.displayName=降順

TriggerCondition.MouseHover.displayName=マウスでポイントする (非推奨)

TriggerCondition.MouseClick.displayName=マウスでクリックする (非推奨)

TriggerCondition.onclick.displayName=マウスでクリックする

TriggerCondition.ondblclick.displayName=マウスでダブルクリックする

TriggerCondition.onmousedown.displayName=マウスボタンを押したままにする

TriggerCondition.onmouseup.displayName=マウスボタンを放す

TriggerCondition.onmouseover.displayName=マウスポインタを上で動かす

TriggerCondition.onmousemove.displayName=マウスポインタを移動する

TriggerCondition.onmouseout.displayName=マウスポインタを外す

TriggerCondition.onfocus.displayName=フォーカス

TriggerCondition.onblur.displayName=フォーカスを外す

TriggerCondition.onkeydown.displayName=キーを押したままにする

TriggerCondition.onkeypress.displayName=キーを押す

TriggerCondition.onkeyup.displayName=キーを放す

TriggerCondition.onload.displayName=読み込み

ActionType.URLRedirect.displayName=ハイパーリンク

ActionType.ShowTooltip.displayName=ツールチップを表示する

ActionType.ToggleVisibility.displayName=表示と非表示を切り替える

ActionType.InvokeScript.displayName=スクリプトを起動する

ActionType.Highlight.displayName=強調表示

ActionType.CallBack.displayName=コールバック

ActionType.ToggleDataPointVisibility.displayName=データポイントの表示と非表示を切り替える

TickStyle.Across.displayName=交差

TickStyle.Left.displayName=左

TickStyle.Right.displayName=右

TickStyle.Above.displayName=上

TickStyle.Below.displayName=下

DataPointComponentType.BaseValue.displayName=カテゴリデータ

DataPointComponentType.OrthogonalValue.displayName=値データ

DataPointComponentType.SeriesValue.displayName=値系列の名前

DataPointComponentType.PercentileOrthogonalValue.displayName=パーセンテージ

LeaderLineStyle.FixedLength.displayName=固定長

LeaderLineStyle.StretchToSide.displayName=対象に合わせて伸縮

MarkerType.Crosshair.displayName=十字線

MarkerType.Triangle.displayName=三角形

MarkerType.Box.displayName=ボックス

MarkerType.Circle.displayName=円形

MarkerType.Icon.displayName=アイコン

MarkerType.Nabla.displayName=ナブラ

MarkerType.Diamond.displayName=菱形

MarkerType.FourDiamonds.displayName=菱形 (4 つ)

MarkerType.Ellipse.displayName=楕円

MarkerType.SemiCircle.displayName=半円

MarkerType.Hexagon.displayName=六角形

MarkerType.Rectangle.displayName=四角形

MarkerType.Star.displayName=星形

MarkerType.Column.displayName=列

MarkerType.Cross.displayName=交差

RiserType.Rectangle.displayName=四角形

RiserType.Triangle.displayName=三角形

RiserType.Tube.displayName=円筒

RiserType.Cone.displayName=円錐

Anchor.North.displayName=上

Anchor.NorthEast.displayName=右上

Anchor.East.displayName=右

Anchor.SouthEast.displayName=右下

Anchor.South.displayName=下

Anchor.SouthWest.displayName=左下

Anchor.West.displayName=左

Anchor.NorthWest.displayName=左上

AnchorVertical.North.displayName=上

AnchorVertical.South.displayName=下端揃え

AnchorVertical.West.displayName=中央揃え (上下)

AnchorHorizontal.East.displayName=右

AnchorHorizontal.South.displayName=中央揃え (上下)

AnchorHorizontal.West.displayName=左

AutoScale.Exception.IsInfiite=\ は無限です。

AutoScale.Exception.IsNaN=\ は NaN (非数値) です。

AutoScale.ValueName.StepSize=ステップのサイズ

Stretch.Horizontal.displayName=横

Stretch.Vertical.displayName=縦

Stretch.Both.displayName=両方

Orientation.Horizontal.displayName=横

Orientation.Vertical.displayName=縦

Direction.LeftRight.displayName=左右

Direction.TopBottom.displayName=上下

LegendItemType.Series.displayName=値系列

LegendItemType.Categories.displayName=カテゴリ

Position.Above.displayName=上

Position.Below.displayName=下

Position.Left.displayName=左

Position.Right.displayName=右

Position.Inside.displayName=内側

Position.Outside.displayName=外側

UnitsOfMeasurement.Pixels.displayName=ピクセル

UnitsOfMeasurement.Points.displayName=ポイント

UnitsOfMeasurement.Inches.displayName=インチ

UnitsOfMeasurement.Centimeters.displayName=センチメートル

DataType.Numeric.displayName=数値

DataType.DateTime.displayName=DateTime
DataType.Text.displayName=テキスト

GroupingUnitType.Seconds.displayName=秒

GroupingUnitType.Minutes.displayName=分

GroupingUnitType.Hours.displayName=時間

GroupingUnitType.Days.displayName=日

GroupingUnitType.Weeks.displayName=週

GroupingUnitType.Months.displayName=月

GroupingUnitType.Years.displayName=年

GroupingUnitType.Quarters.displayName=四半期

GroupingUnitType.String.displayName=文字列

GroupingUnitType.StringPrefix.displayName=頭文字

DateFormatType.Long.displayName=Long 型

DateFormatType.Short.displayName=Short 型

DateFormatType.Medium.displayName=Medium 型

DateFormatType.Full.displayName=Full 型

DateFormatDetail.Date.displayName=日付

DateFormatDetail.DateTime.displayName=日時

ChartUtil.Text.Day='D'
ChartUtil.Text.Week='W'
DefaultValueProvider_BaseSeries=基本系列

DefaultValueProvider_ChartSubType.Standard=標準

DefaultValueProvider_ChartSubType.StandardMeterChart=標準メーターグラフ

DefaultValueProvider_ChartTitle=グラフのタイトル

DefaultValueProvider_ChartUnits.Points=ポイント

LegendBehaviorType.None.displayName=なし

LegendBehaviorType.ToggleSerieVisibility.displayName=系列の表示と非表示を切り替える

LegendBehaviorType.HighlightSerie.displayName=系列を強調表示する

# Defines cursor display names.
Cursor.Auto.displayName=自動

Cursor.Crosshair.displayName=十字線

Cursor.Default.displayName=デフォルト

Cursor.Pointer.displayName=手動

Cursor.Move.displayName=移動

Cursor.Text.displayName=テキスト

Cursor.Wait.displayName=待ち状態

Cursor.EResize.displayName=東

Cursor.NEResize.displayName=北東

Cursor.NWResize.displayName=北西

Cursor.NResize.displayName=北

Cursor.SEResize.displayName=南東

Cursor.SWResize.displayName=南西

Cursor.SResize.displayName=南

Cursor.WResize.displayName=西

Cursor.Custom.displayName=カスタム

ActionType.URLRedirect.DisplayName=URL を転送する

ActionType.InvokeScript.DisplayName=スクリプトを起動する

ActionType.Highlight.DisplayName=強調表示する

ActionType.ToggleVisibility.DisplayName=表示と非表示を切り替える

ActionType.ToggleDataPointVisibility.DisplayName=データポイントの表示と非表示を切り替える

# End of Attributes
##################################################
dataprocessor.log.baseSeriesDefn3=カテゴリ系列の定義 ({0}) が静的な式として使用されます。

dataprocessor.exception.CannotDecipher=複数のカテゴリ系列の定義を含むグラフのコンテンツは解釈できません。

dataprocessor.exception.FoundDefnAssociatedWithX=カテゴリ (X) 系列の式に関連付けられた {0} 個のデータ定義が見つかりました。カテゴリ系列のデータの定義は、1 つしかサポートされません。

dataprocessor.exception.DefinitionUnspecified=カテゴリ系列のデータの定義が指定されていません。

dataprocessor.exception.DefnExpMustAssociateY=データ定義の式は、値 (Y) 系列に関連付けられている必要があります ({1} で定義された {0})。

dataprocessor.exception.AtLeastOneDefnExpMustAssociateY=少なくとも 1 つのデータ定義の式が値 (Y) 系列に関連付けられている必要があります ({1} で定義された {0})。

dataprocessor.exception.CannotDecipher2=複数のカテゴリ系列の定義を含むグラフのコンテンツは解釈できません。

dataprocessor.log.XSeriesDefn=X 系列の定義 ({0}) が静的な式として使用されます。

dataprocessor.exception.FoundMoreThanOneDefnAssociateX=X 系列の式に関連付けられた {0} 個のデータの定義が見つかりました。X 系列のデータの定義は、1 つしかサポートされません。

edataprocessor.xception.definitionsAssociatedWithX=X 系列のデータの定義が指定されていません。

dataprocessor.log.baseSeriesDefnBeStatic=カテゴリ系列の定義 ({0}) が静的な式として使用されます。

exception.data.max.row.count={0} 行以上のデータをバインドするグラフはレンダリングできません。


# Default chart title
BarChart.Title=棒グラフのタイトル

LineChart.Title=線グラフのタイトル

AreaChart.Title=面積グラフのタイトル

PieChart.Title=パイグラフのタイトル

MeterChart.Title=メーターグラフのタイトル

ScatterChart.Title=分布グラフのタイトル

StockChart.Title=株価グラフのタイトル

BubbleChart.Title=バブルチャートのタイトル

DifferenceChart.Title=差分チャートのタイトル

GanttChart.Title=ガントチャートのタイトル

TubeChart.Title=円筒グラフのタイトル

PyramidChart.Title=ピラミッドグラフのタイトル

ConeChart.Title=円錐グラフのタイトル

RadarChart.Title=レーダーチャートのタイトル

ColumnChart.Title=縦棒グラフのタイトル

DoughnutChart.Title=ドーナツグラフのタイトル