ChartImpl.ChartTitle=图表标题

ChartImpl.AltText=此图表不包含数据。

ChartWithAxesImpl.X_Axis.title=X 轴标题

ChartWithAxesImpl.Y_Axis.title=Y 轴标题

ChartWithAxesImpl.Z_Axis.title=Z 轴标题

ChartWithoutAxesImpl.Unsupported3Dimension=饼图不支持 3D。

exception.convert.double=无法将值 {0} 转换为双精度值

exception.data.outofsync=输入数据不同步；类别系列包含 {0} 个值；值系列包含 {1} 个值。

exception.out.of.bounds=超出边界

exception.step.zoom.out=无法为步骤={0} 缩小

exception.no3d.support=尚不支持三维图表

exception.curve.label.position.not.supported=曲线拟合不支持标签位置 [{0}]。

exception.convert.calendar=无法将值 {0} 转换为日历值

exception.anchor.transpose=无法为轴方向 {1 }转置定位点 {0}

exception.tick.computations=刻度计算错误

exception.curve.visibility.unset=对于曲线，必须在线条属性上设置可见性

exception.angle.range.transpose=无法置换 [角度={0}]，该角度超出范围 (90 >= 0 >= -90)

exception.legend.direction.tblr=图例方向未明确设置为“顶-底”或“左-右”

exception.scale.null.location=无法按刻度 {0} 定位空值的坐标轴

exception.illegal.icon.palette.type.for.marker=''{0}'' 不是标记图标的有效图像类型。

exception.illegal.filltype.crosshair.marker=无法在标记 CROSSHAIR 上将调色板颜色设置为 {0}

exception.illegal.filltype.cross.marker=无法在标记 CROSS 上将调色板颜色设置为 {0}

exception.invalid.step.size =为轴刻度指定的 ''step size({0}) <= 0'' 无效

exception.invalid.step.number =为轴刻度指定的 ''step number({0}) < 1'' 无效

exception.curve.line.visibility.not.defined=未正确定义曲线的可见性属性。

exception.min.largerthan.max=为轴刻度指定的条目 ''min({0}) > max({1})'' 无效

exception.combination.axis.label.position=不应出现 axis={0} 与 labelposition={1} 的组合

exception.cannot.locate.start.marker.range=无法找到包含在标记区域 {1} 中的值 {0} 的区域起始位置

exception.cannot.locate.value.marker.line=无法找到包含在标记线条 {1} 中的值 {0}

exception.combination.axis.tick.style=不应出现 axis={0} 与 tickstyle={1} 的组合

exception.invalid.axis.data.type=为坐标轴指定的数据类型与数据字段值不匹配: ({0})

exception.undefined.axis.data.type=未为轴 {0} 定义数据类型

exception.unsupported.compare.text=不支持文本数据元素比较

exception.unsupported.comparison=对象 {0} 可能不参与 ''pre'' 比较

exception.unsupported.internal.draw=无法通过事件对 {0} 进行内部绘制

exception.unsupported.internal.fill=无法通过事件对 {0} 进行内部填充

exception.unsupported.chart.model=无法计算模型 [{0}] 定义的图表

exception.unsupported.bounds=无法计算事件 {0} 的边界

exception.unsupported.copy=无法创建事件 {0} 的副本

exception.unsupported.step.number=步数不支持非数字值。

exception.undefined.data.point=未定义与系列定义关联的数据点值

exception.unit.size.failure=由于未定义刻度轴，因此无法计算单位大小

exception.process.content.type=无法为类型 {1} 处理指定为 {0} 的数据集内容

exception.undefined.axis.label.visibility=未定义轴 {0} 的标签可见性

exception.undefined.axis.title.visibility=未定义轴 {0} 的标题可见性

exception.undefined.axis.label.position=未定义轴 {0} 的标签位置

exception.undefined.axis.title.position=未定义轴 {0} 的标题位置

exception.undefined.data.label.position=未定义系列 {0} 的数据标签位置

exception.undefined.axis.type=轴未定义轴类型

exception.unset.series.stacked.property=未明确设置可堆积系列 {0} 的堆积属性

exception.undefined.axis.major.tick.style=未定义轴 {0} 的主要网格刻度样式

exception.undefined.axis.minor.tick.style=未定义轴 {0} 的次要网格刻度样式

exception.zero.negative.logarithmic.scale=无法按对数刻度找到 0 或负值

exception.illegal.vaxis.label.position=为垂直轴 {1} 指定的标签位置值 {0} 无效

exception.illegal.vaxis.title.position=为垂直轴 {1} 指定的标题位置值 {0} 无效

exception.illegal.vaxis.major.tick.style=为垂直轴 {1} 指定为 {0} 的主要刻度样式无效

exception.illegal.vaxis.minor.tick.style=为垂直轴 {1} 指定为 {0} 的次要刻度样式无效

exception.illegal.haxis.label.position=为水平轴 {1} 指定的标签位置值 {0} 无效

exception.illegal.haxis.title.position=为水平轴 {1} 指定的标题位置值 {0} 无效

exception.illegal.rotation.angle.label=未正确指定标签 {0} 的旋转角度 (-90 <= ANGLE <= 90)

exception.illegal.rendering.direction=为图例绘制方向 = {0} 指定的参数无效

exception.illegal.rendering.orientation=为图例绘制方位 = {0} 指定的参数无效

exception.illegal.legend.direction=为图例绘制方向 = {0} 指定的参数无效

exception.illegal.null.value=作为构建图表的参数而传递的 ''null'' 值无效

exception.cannot.find.plugin.entry=在所有可用插件的任意 plugin.xml 文件中，无法找到 lookup={0}; element=({1}:{2}) 的任何项

exception.cannot.split.major=无法将主要单位分解成 {0} 次要单位

exception.illegal.legend.orientation=为图例绘制方位 = {0} 指定的参数无效

exception.cwoa.single.runtime.series=无坐标轴的图表可能仅包含一个时间系列

exception.illegal.haxis.major.tick.style=为水平轴 {1} 指定为 {0} 的主要刻度样式无效

exception.illegal.haxis.minor.tick.style=为水平轴 {1} 指定为 {0} 的次要刻度样式无效

exception.client.area.outline.visibility=未指定客户区域大纲的可见性

exception.cannot.locate.end.marker.range=无法找到包含在标记区域 {1} 中的值 {0} 的区域结束位置

exception.runtime.dataset.count.mismatch=在堆积时间系列中，找到了数据集计数中不匹配的 ({0}\!={1})

exception.illegal.base.runtime.series.count=无坐标图表的类别运行时系列计数（此处为 {0}）必须为 1

exception.unstackable.is.stacked=序列 {0}（其可能不是堆积）被设置为堆积

exception.unset.label.visibility=标签 {0} 未设置可见性

exception.marker.line.null.value=无法为标记线条 {0} 中定义的空值绘制线条

exception.unset.axis.visibility=未设置轴可见性，因此结果将变得不明确

exception.unset.line.visibility=未明确设置 {0} 的线条属性的可见性

exception.stacked.datetime.axis.series=无法在日期时间轴上定义堆积系列

exception.stacked.unstacked.mix.series=系列定义 {0} 具有堆积和非堆积系列的混合。

exception.internal.stack.series.setup=未正确设置轴 {0} 的堆积系列

exception.invalid.minimum.scale.value=为轴类型 {1} 指定的最小刻度值 {0} 无效

exception.invalid.maximum.scale.value=为轴类型 {1} 指定的最大刻度值 {0} 无效

exception.legend.orientation.horzvert=图例方位未明确设置为“水平”或“垂直”

exception.legend.orientation.InvalidMaxPercent=最大百分比必须在 0 与 1 之间。

info.processing.stacked.info=正在处理轴 {0} 的堆积信息

info.eclenv.creating.device=（日蚀式环境）将设备 {0} 创建为 {1}

info.stdenv.creating.device=（独立环境）将设备 {0} 创建为 {1}

info.eclenv.creating.display=（日蚀式环境）将显示服务器 {0} 创建为 {1}

info.stdenv.creating.display=（独立环境）将显示服务器 {0} 创建为 {1}

exception.percent.stacked.non.numerical=无法计算包含非数值数据的百分比/堆积轴

exception.text.data.numerical.datetime.axis=无法使用文本数据绘制数值/日期时间轴。

exception.numerical.data.datetime.axis=无法使用非日期时间数据绘制日期时间轴。

exception.datetime.data.numerical.axis=无法使用非数值数据绘制数值轴。

exception.cwoa.single.series.definition=无坐标轴的图表可能仅包含一个系列定义

exception.parse.value.format.specifier=用格式说明符 {1} 分析值 {0} 失败

exception.orthogonal.axis.numerical.datetime=值轴只能具有数值或日期时间格式

exception.axis.series.link.broken=无法找到系列 {0} 的轴定义

exception.process.content.dataset=无法为数据 {1} 处理指定为 {0} 的数据集内容

exception.base.orthogonal.inconsistent.count=类别轴包含 {0} 个项目；值轴包含 {1} 个项目。

exception.base.orthogonal.null.datapoint=给定的数据点包含无效的空值。

exception.base.orthogonal.null.datadefinition=给定的数据定义表达式无效。.

exception.dataset.non.numerical.to.numerical=在数据集中发现了意外的非数值数据类型{0}; 无法转换成数值。

exception.dataset.non.datetime=受 X 轴约束的数据类型不是 DateTime 格式

exception.scale.tick.max=无法绘制太多步。请调整刻度步长或单位。

exception.unknown.axis.type.tick.computations=无法确定用于计算刻度线的轴类型

exception.unknown.trigger.datatype=触发器数据无效或其类型未知。

exception.unsupported.compare.unknown.objects=为比较 DE1={0} 和 DE2={1}，提供了不支持的数据元素

exception.unsupported.compare.different.objects=为比较 DE1={0} 和 DE2={1} 提供了混合的数据元素

exception.resultset.data.type.retrieval.failed=无法从结果集中确定数据类型

exception.base.axis.no.series.definitions=主类别轴不包含任何系列定义

exception.no.stack.percent.3D.chart=三维图表不支持堆积和百分比功能。

exception.dial.dimension=标度图系列不支持 ''{0}''。

exception.pie.dimension=饼图系列不支持 ''{0}''。

exception.scatter.dimension=散点图系列不支持 ''{0}''。

exception.stock.dimension=股票图系列不支持 ''{0}''。

exception.multi.orthogonal.3D.not.supported=三维图表不支持多个值轴。

exception.scatter.3D.not.supported=三维图表不支持离散类别轴。

exception.no.transposed.3D.chart=三维图表不支持置换。

exception.3D.points.length.less.than.3=对于三维绘制事件，点列表长度至少为 3 (>=3)。

exception.unsupported.area3d.getOjbect3D=不支持从 Area3DRenderEvent 直接访问 Object3D 对象。 请分别迭代每个子 I3DRenderEvent 进行处理。

exception.javascript.error=图表脚本“{2}”的第 {1} 行的 {0}

exception.null.legend.layout.hints=无法呈现具有 'null' 布局提示对象的图例。

exception.null.legend.item.hints=无法呈现具有 'null' 项提示对象的图例项。

info.elapsed.render.time=绘制时间 = {0} 毫米

info.elapsed.time.render=绘制时间 = {0} 毫米

info.eclenv.creating.dsp=（日蚀式环境）正在创建 dsp {0}

info.datapoint.to.string={0}:{1}
info.stdenv.creating.dsp=（独立环境）正在创建 dsp {0}

constant.undefined.string=<未定义>

constant.null.string=null

error.invalid.enumerator=值 ''{0}'' 不是 ''{1}'' 的有效枚举器

error.invalid.classifier=数据类型 ''{0}'' 不是有效的分类器

error.invalid.argument.for.barSeries={0} 是 BarSeriesImpl 的无效参数。图表模型必须是 org.eclipse.birt.chart.model.ChartWithAxes 的实例。

error.invalid.argument.for.lineSeries={0} 是 LineSeriesImpl 的无效参数。图表模型必须是 org.eclipse.birt.chart.model.ChartWithAxes 的实例。

error.invalid.argument.for.stockSeries={0} 是 StockSeriesImpl 的无效参数。图表模型必须是 org.eclipse.birt.chart.model.ChartWithAxes 的实例。

error.legend.position=必须指定图例块位置才能正确地布置图表组件

error.null.source=源值不能为 null

error.unknown.palette=请求的调色板 {0} 未知，使用默认设置

error.type.not.set=没有为 DateFormatSpecifier 的此实例设置 TYPE

error.eclenv.cannot.find.dsp=（日蚀式环境）无法找到 {0} 的 dsp impl

error.stdenv.cannot.find.dsp=（独立环境）无法找到 {0} 的 dsp impl

info.eclenv.creating.series.renderer=（日蚀式环境）正在创建系列呈现器 {0}

info.eclenv.creating.datapoint.definition=(ECLIPSE-ENV) 正在创建数据点定义 {0}

error.eclenv.cannot.find.series.renderer=（日蚀式环境）无法找到 {0} 的系列呈现器 impl

info.stdenv.creating.series.renderer=（独立环境）正在创建系列呈现器 {0}

info.compute.elapsed.time.without.axes=计算图形的时间（无坐标轴） = {0} 毫秒

info.compute.elapsed.time.with.axes=计算图形的时间（有坐标轴） = {0} 毫秒

error.stdenv.cannot.find.series.renderer=（独立环境）无法找到 {0} 的系列呈现器 impl

error.stdenv.cannot.find.datapoint.definition=(STANDALONE-ENV) 无法找到 {0} 的数据点定义 impl

error.eclenv.cannot.find.device=（日蚀式环境）无法找到 {0} 的设备呈现器 impl

error.stdenv.cannot.find.device=（独立环境）无法找到 {0} 的设备呈现器 impl

error.eclenv.cannot.find.display=（日蚀式环境）无法找到 {0} 的显示服务器 impl

error.stdenv.cannot.find.display=（独立环境）无法找到 {0} 的显示服务器 impl

info.log.script=[脚本]: {0}

info.render.series={0}: renderSeries() [{1}/{2}]
info.log.info=[信息]: {0}

info.log.warn=[警告]: {0}

info.log.err=[错误]: {0}

info.log.fatal=[致命错误]: {0}

prefix.marker.range.caption=[
separator.marker.range.caption=\ 至

suffix.marker.range.caption=]
wrapped.instruction.to.string={0}:模型={1}； 边界={2}

exception.mixed.data.types=聚合函数 {0} 遇到要汇总的混合输入数据

info.eclenv.creating.function=（日蚀式环境）正在创建聚合函数 {0}

error.eclenv.cannot.find.function=（日蚀式环境）无法找到 {0} 的聚合函数 impl

info.stdenv.creating.function=（独立环境）正在创建聚合函数 {0}

error.stdenv.cannot.find.function=（独立环境）无法找到 {0} 的聚合函数 impl

Info.try.load.java.handler=正在尝试加载图表 Java 事件处理程序类...

Info.java.handler.loaded=已成功加载图表 Java 事件处理程序类 [{0}]。

Info.invalid.java.handler=已检测到并忽略无效的图表 Java 事件处理程序类 [{0}]。

Info.try.register.javascript.content=正在尝试加载图表 JavaScript 内容...

Info.javascript.content.registered=已成功加载图表 JavaScript 内容。

warn.unspecified.sorting=未为 {0} 指定排序。

##################################################
# Attributes 
#
# !!the key is bound to those attribute literal' name value, 
# !!if that changes, this must be updated accordingly.
#
SeriesImpl.displayName=简单系列

AreaSeriesImpl.displayName=面积图系列

BarSeriesImpl.displayName=条形图系列

BarSeriesImpl.coneDisplayName=锥形系列

BarSeriesImpl.tubeDisplayName=管形系列

BarSeriesImpl.pyramidDisplayName=棱锥系列

DialSeriesImpl.displayName=标度图系列

LineSeriesImpl.displayName=折线图系列

PieSeriesImpl.displayName=饼图系列

ScatterSeriesImpl.displayName=散点图系列

StockSeriesImpl.displayName=股票图系列

BubbleSeriesImpl.displayName=气泡图系列

GanttSeriesImpl.displayName=甘特图系列

DifferenceSeriesImpl.displayName=差异系列

AxisType.Linear.displayName=线性

AxisType.Logarithmic.displayName=对数

AxisType.Text.displayName=文本

AxisType.DateTime.displayName=DateTime
IntersectionType.Min.displayName=Min

IntersectionType.Max.displayName=Max

IntersectionType.Value.displayName=值

ScaleUnitType.Seconds.displayName=秒

ScaleUnitType.Minutes.displayName=分钟

ScaleUnitType.Hours.displayName=小时

ScaleUnitType.Days.displayName=日

ScaleUnitType.Weeks.displayName=周

ScaleUnitType.Months.displayName=月

ScaleUnitType.Quarters.displayName=季

ScaleUnitType.Years.displayName=年

SortOption.Ascending.displayName=升序

SortOption.Descending.displayName=降序

TriggerCondition.MouseHover.displayName=鼠标悬停(过时)

TriggerCondition.MouseClick.displayName=鼠标单击(过时)

TriggerCondition.onclick.displayName=鼠标单击

TriggerCondition.ondblclick.displayName=鼠标双击

TriggerCondition.onmousedown.displayName=鼠标按下

TriggerCondition.onmouseup.displayName=鼠标释放

TriggerCondition.onmouseover.displayName=鼠标移过

TriggerCondition.onmousemove.displayName=鼠标移动

TriggerCondition.onmouseout.displayName=鼠标移出

TriggerCondition.onfocus.displayName=焦点

TriggerCondition.onblur.displayName=模糊

TriggerCondition.onkeydown.displayName=键按下

TriggerCondition.onkeypress.displayName=击键

TriggerCondition.onkeyup.displayName=键释放

TriggerCondition.onload.displayName=加载

ActionType.URLRedirect.displayName=超级链接

ActionType.ShowTooltip.displayName=显示工具提示

ActionType.ToggleVisibility.displayName=切换可见性

ActionType.InvokeScript.displayName=调用脚本

ActionType.Highlight.displayName=突出显示

ActionType.CallBack.displayName=回调

ActionType.ToggleDataPointVisibility.displayName=切换数据点可见性

TickStyle.Across.displayName=交叉

TickStyle.Left.displayName=左侧

TickStyle.Right.displayName=右侧

TickStyle.Above.displayName=上方

TickStyle.Below.displayName=下方

DataPointComponentType.BaseValue.displayName=类别数据

DataPointComponentType.OrthogonalValue.displayName=值数据

DataPointComponentType.SeriesValue.displayName=值系列名称

DataPointComponentType.PercentileOrthogonalValue.displayName=百分位值数据

LeaderLineStyle.FixedLength.displayName=固定长度

LeaderLineStyle.StretchToSide.displayName=侧向伸展

MarkerType.Crosshair.displayName=交叉线

MarkerType.Triangle.displayName=三角形

MarkerType.Box.displayName=箱形

MarkerType.Circle.displayName=圆形

MarkerType.Icon.displayName=图标

MarkerType.Nabla.displayName=倒三角形

MarkerType.Diamond.displayName=菱形

MarkerType.FourDiamonds.displayName=四个菱形

MarkerType.Ellipse.displayName=椭圆

MarkerType.SemiCircle.displayName=半圆形

MarkerType.Hexagon.displayName=六边形

MarkerType.Rectangle.displayName=矩形

MarkerType.Star.displayName=星形

MarkerType.Column.displayName=圆柱形

MarkerType.Cross.displayName=十字形

RiserType.Rectangle.displayName=矩形

RiserType.Triangle.displayName=三角形

RiserType.Tube.displayName=管形

RiserType.Cone.displayName=圆锥

Anchor.North.displayName=上

Anchor.NorthEast.displayName=右上

Anchor.East.displayName=右

Anchor.SouthEast.displayName=右下

Anchor.South.displayName=下

Anchor.SouthWest.displayName=左下

Anchor.West.displayName=左

Anchor.NorthWest.displayName=左上

AnchorVertical.North.displayName=顶部

AnchorVertical.South.displayName=底部

AnchorVertical.West.displayName=中间

AnchorHorizontal.East.displayName=右

AnchorHorizontal.South.displayName=中间

AnchorHorizontal.West.displayName=左

AutoScale.Exception.IsInfiite=\ 无限制

AutoScale.Exception.IsNaN=\ 不是数值

AutoScale.ValueName.StepSize=步长

Stretch.Horizontal.displayName=水平

Stretch.Vertical.displayName=垂直

Stretch.Both.displayName=水平和垂直

Orientation.Horizontal.displayName=水平

Orientation.Vertical.displayName=垂直

Direction.LeftRight.displayName=左右

Direction.TopBottom.displayName=上下

LegendItemType.Series.displayName=值系列

LegendItemType.Categories.displayName=类别

Position.Above.displayName=上方

Position.Below.displayName=下方

Position.Left.displayName=左侧

Position.Right.displayName=右侧

Position.Inside.displayName=内部

Position.Outside.displayName=外部

UnitsOfMeasurement.Pixels.displayName=像素

UnitsOfMeasurement.Points.displayName=点

UnitsOfMeasurement.Inches.displayName=英寸

UnitsOfMeasurement.Centimeters.displayName=厘米

DataType.Numeric.displayName=数值

DataType.DateTime.displayName=DateTime
DataType.Text.displayName=文本

GroupingUnitType.Seconds.displayName=秒

GroupingUnitType.Minutes.displayName=分钟

GroupingUnitType.Hours.displayName=小时

GroupingUnitType.Days.displayName=日

GroupingUnitType.Weeks.displayName=周

GroupingUnitType.Months.displayName=月

GroupingUnitType.Years.displayName=年

GroupingUnitType.Quarters.displayName=季

GroupingUnitType.String.displayName=字符串

GroupingUnitType.StringPrefix.displayName=字符串前缀

DateFormatType.Long.displayName=长

DateFormatType.Short.displayName=短

DateFormatType.Medium.displayName=中等

DateFormatType.Full.displayName=完全

DateFormatDetail.Date.displayName=日期

DateFormatDetail.DateTime.displayName=日期时间

ChartUtil.Text.Day='D'
ChartUtil.Text.Week='W'
DefaultValueProvider_BaseSeries=基本系列

DefaultValueProvider_ChartSubType.Standard=标准

DefaultValueProvider_ChartSubType.StandardMeterChart=标准仪表图

DefaultValueProvider_ChartTitle=图表标题

DefaultValueProvider_ChartUnits.Points=点

LegendBehaviorType.None.displayName=无

LegendBehaviorType.ToggleSerieVisibility.displayName=切换系列可见性

LegendBehaviorType.HighlightSerie.displayName=突出显示系列

# Defines cursor display names.
Cursor.Auto.displayName=自动

Cursor.Crosshair.displayName=交叉线

Cursor.Default.displayName=默认

Cursor.Pointer.displayName=手

Cursor.Move.displayName=移动

Cursor.Text.displayName=文本

Cursor.Wait.displayName=等待

Cursor.EResize.displayName=东

Cursor.NEResize.displayName=东北

Cursor.NWResize.displayName=西北

Cursor.NResize.displayName=北

Cursor.SEResize.displayName=东南

Cursor.SWResize.displayName=西南

Cursor.SResize.displayName=南

Cursor.WResize.displayName=西

Cursor.Custom.displayName=自定义

ActionType.URLRedirect.DisplayName=URL 重定向

ActionType.InvokeScript.DisplayName=调用脚本

ActionType.Highlight.DisplayName=突出显示

ActionType.ToggleVisibility.DisplayName=切换可见性

ActionType.ToggleDataPointVisibility.DisplayName=切换数据点可见性

# End of Attributes
##################################################
dataprocessor.log.baseSeriesDefn3=类别系列定义 ({0}) 将用作静态表达式。

dataprocessor.exception.CannotDecipher=无法将包含多个类别系列定义的图表的内容解码。

dataprocessor.exception.FoundDefnAssociatedWithX=找到与类别 (X) 系列表达式关联的 {0} 个数据定义。仅支持一个类别系列数据定义。

dataprocessor.exception.DefinitionUnspecified=未指定类别系列的数据定义。

dataprocessor.exception.DefnExpMustAssociateY=数据定义表达式必须与值 (Y) 系列关联 - {1} 定义的 {0}。

dataprocessor.exception.AtLeastOneDefnExpMustAssociateY=至少一个数据定义表达式必须与值 (Y) 系列关联 - {1} 定义的 {0}。

dataprocessor.exception.CannotDecipher2=无法将包含多个类别系列定义的图表的内容解码。

dataprocessor.log.XSeriesDefn=X 系列定义 ({0}) 将用作静态表达式。

dataprocessor.exception.FoundMoreThanOneDefnAssociateX=找到与 X 系列表达式关联的 {0} 个数据定义。仅支持一个 X 系列数据定义。

edataprocessor.xception.definitionsAssociatedWithX=未指定 X 系列的数据定义。

dataprocessor.log.baseSeriesDefnBeStatic=类别系列定义 ({0}) 将用作静态表达式。

exception.data.max.row.count=无法绘制绑定超过 {0} 行数据的图表。


# Default chart title
BarChart.Title=条形图标题

LineChart.Title=折线图标题

AreaChart.Title=面积图标题

PieChart.Title=饼图标题

MeterChart.Title=仪表图标题

ScatterChart.Title=散点图标题

StockChart.Title=股票图标题

BubbleChart.Title=气泡图标题

DifferenceChart.Title=差异图标题

GanttChart.Title=甘特图标题

TubeChart.Title=管形图标题

PyramidChart.Title=棱锥图标题

ConeChart.Title=锥形图标题

RadarChart.Title=雷达图标题

ColumnChart.Title=柱形图标题

DoughnutChart.Title=圆环图标题