ChartImpl.ChartTitle=차트 제목

ChartImpl.AltText=이 차트에는 데이터가 없습니다.

ChartWithAxesImpl.X_Axis.title=X축 제목

ChartWithAxesImpl.Y_Axis.title=Y축 제목

ChartWithAxesImpl.Z_Axis.title=Z축 제목

ChartWithoutAxesImpl.Unsupported3Dimension=원형 차트에서는 3D를 지원하지 않습니다.

exception.convert.double=값 {0}을(를) double 값으로 변환할 수 없습니다.

exception.data.outofsync=입력 데이터가 동기화되지 않았습니다. 범주 계열에는 {0} 값이 들어 있고 값 계열에는 {1} 값이 들어 있습니다.

exception.out.of.bounds=범위 밖

exception.step.zoom.out=단계={0}으로 zoomOut할 수 없습니다.

exception.no3d.support=3D 차트는 아직 지원되지 않습니다.

exception.curve.label.position.not.supported=곡선 근사에 대해 레이블 위치 [{0}]이(가) 지원되지 않습니다.

exception.convert.calendar=값 {0}을(를) 일정 값으로 변환할 수 없습니다.

exception.anchor.transpose=앵커 {0}을(를) 축 방향 {1}(으)로 바꿀 수 없습니다.

exception.tick.computations=틱 계산에 오류가 발생했습니다.

exception.curve.visibility.unset=곡선의 선 특성에 대한 표시 유형을 설정해야 합니다.

exception.angle.range.transpose=[각도={0}]을(를) 범위(90 >= 0 >= -90) 밖으로 바꿀 수 없습니다.

exception.legend.direction.tblr=범례의 방향이 위-아래 또는 왼쪽-오른쪽으로 명확히 설정되지 않았습니다.

exception.scale.null.location=배율 {0}의 널(null) 값에 대한 좌표를 찾을 수 없습니다.

exception.illegal.icon.palette.type.for.marker=''{0}''은(는) 표지 아이콘에 대해 올바른 이미지 형식이 아닙니다.

exception.illegal.filltype.crosshair.marker=표지 CROSSHAIR에 대한 색상표 색을 {0}(으)로 설정할 수 없습니다.

exception.illegal.filltype.cross.marker=표지 CROSS에 대한 색상표 색을 {0}(으)로 설정할 수 없습니다.

exception.invalid.step.size =축 배율에 잘못된 ''step size({0}) <= 0''이 지정되었습니다.

exception.invalid.step.number =축 배율에 잘못된 ''step number({0}) < 1''이 지정되었습니다.

exception.curve.line.visibility.not.defined=곡선의 표시 유형 속성이 정확하게 정의되지 않았습니다.

exception.min.largerthan.max=축 배율에 잘못된 항목 ''min({0}) > max({1})''가 지정되었습니다.

exception.combination.axis.label.position=축={0} 및 레이블 위치={1}의 조합을 필요로 하지 않습니다.

exception.cannot.locate.start.marker.range=표지 범위 {1}에 포함된 값 {0}의 범위 시작을 찾을 수 없습니다.

exception.cannot.locate.value.marker.line=표지선 {1}에 포함된 값 {0}을(를) 찾을 수 없습니다.

exception.combination.axis.tick.style=틱={0} 및 틱 스타일={1}의 조합을 필요로 하지 않습니다.

exception.invalid.axis.data.type=축에 지정한 데이터 형식이 데이터 필드 값({0})의 형식과 일치하지 않습니다.

exception.undefined.axis.data.type=축 {0}에 대한 데이터 형식이 정의되지 않았습니다.

exception.unsupported.compare.text=텍스트 데이터 요소 비교가 지원되지 않습니다.

exception.unsupported.comparison=객체 {0}은(는) ''pre'' 비교에 참여할 수 없습니다.

exception.unsupported.internal.draw=이벤트를 통해 {0}을(를) 내부적으로 그릴 수 없습니다.

exception.unsupported.internal.fill=이벤트를 통해 {0}을(를) 내부적으로 채울 수 없습니다.

exception.unsupported.chart.model=모델 [{0}]에서 정의된 차트를 계산할 수 없습니다.

exception.unsupported.bounds=이벤트 {0}에 대한 경계를 계산할 수 없습니다.

exception.unsupported.copy=이벤트 {0}에 대한 복사본을 만들 수 없습니다.

exception.unsupported.step.number=숫자가 아닌 값에 대해 단계 번호가 지원되지 않습니다.

exception.undefined.data.point=계열 정의와 연결된 DataPoint 값이 정의되지 않았습니다.

exception.unit.size.failure=틱 좌표가 정의되지 않았기 때문에 단위 크기를 계산할 수 없습니다.

exception.process.content.type=형식 {1}에 대해 {0}(으)로 지정된 데이터 집합 내용을 처리할 수 없습니다.

exception.undefined.axis.label.visibility=축 {0}에 대한 레이블 표시 유형이 정의되지 않았습니다.

exception.undefined.axis.title.visibility=축 {0}에 대한 제목 표시 유형이 정의되지 않았습니다.

exception.undefined.axis.label.position=축 {0}에 대한 레이블 위치가 정의되지 않았습니다.

exception.undefined.axis.title.position=축 {0}에 대한 제목 위치가 정의되지 않았습니다.

exception.undefined.data.label.position=계열 {0}에 대한 데이터 레이블 위치가 정의되지 않았습니다.

exception.undefined.axis.type=축에 대해 축 유형이 정의되지 않았습니다.

exception.unset.series.stacked.property=누적 가능 계열 {0}에 대한 누적 속성이 명확히 설정되지 않았습니다.

exception.undefined.axis.major.tick.style=축 {0}에 대한 주 눈금 틱 스타일이 정의되지 않았습니다.

exception.undefined.axis.minor.tick.style=축 {0}에 대한 부 눈금 틱 스타일이 정의되지 않았습니다.

exception.zero.negative.logarithmic.scale=로그 배율에는 0 또는 음수 값이 있을 수 없습니다.

exception.illegal.vaxis.label.position=세로 축 {1}에 잘못된 레이블 위치 값 {0}이(가) 지정되었습니다.

exception.illegal.vaxis.title.position=세로 축 {1}에 잘못된 제목 위치 값 {0}이(가) 지정되었습니다.

exception.illegal.vaxis.major.tick.style=세로 축 {1}에 대해 잘못된 주 틱 스타일이 {0}(으)로 지정되었습니다.

exception.illegal.vaxis.minor.tick.style=세로 축 {1}에 대해 잘못된 부 틱 스타일이 {0}(으)로 지정되었습니다.

exception.illegal.haxis.label.position=가로 축 {1}에 잘못된 레이블 위치 값 {0}이(가) 지정되었습니다.

exception.illegal.haxis.title.position=가로 축 {1}에 잘못된 제목 위치 값 {0}이(가) 지정되었습니다.

exception.illegal.rotation.angle.label=레이블 {0}에 대한 회전 각도(-90 <= 각도 <= 90)가 잘못 지정되었습니다.

exception.illegal.rendering.direction=범례 렌더링 방향 = {0}에 잘못된 인수가 지정되었습니다.

exception.illegal.rendering.orientation=범례 렌더링 방향 = {0}에 잘못된 인수가 지정되었습니다.

exception.illegal.legend.direction=범례 렌더링 방향 = {0}에 잘못된 인수가 지정되었습니다.

exception.illegal.null.value=잘못된 ''널(null)'' 값이 차트를 빌드하기 위한 인수로 전달되었습니다.

exception.cannot.find.plugin.entry=사용 가능한 모든 플러그인의 plugin.xml 파일에서 조사={0}; 요소=({1}:{2})에 대한 항목을 찾을 수 없습니다.

exception.cannot.split.major=주 단위를 {0} 부 단위로 분할할 수 없습니다.

exception.illegal.legend.orientation=범례 렌더링 방향 = {0}에 잘못된 인수가 지정되었습니다.

exception.cwoa.single.runtime.series=축이 없는 차트에는 단일 런타임 계열만 포함될 수 있습니다.

exception.illegal.haxis.major.tick.style=가로 축 {1}에 대해 잘못된 주 틱 스타일이 {0}(으)로 지정되었습니다.

exception.illegal.haxis.minor.tick.style=가로 축 {1}에 대해 잘못된 부 틱 스타일이 {0}(으)로 지정되었습니다.

exception.client.area.outline.visibility=클라이언트 영역 표시 유형이 지정되지 않았습니다.

exception.cannot.locate.end.marker.range=표지 범위 {1}에 포함된 값 {0}의 범위 끝을 찾을 수 없습니다.

exception.runtime.dataset.count.mismatch=누적된 런타임 계열의 데이터 집합 개수에 불일치({0}\!={1})가 있습니다.

exception.illegal.base.runtime.series.count=축이 없는 차트에 대한 범주 런타임 계열 개수(여기서는 {0})는 1이 되어야 합니다.

exception.unstackable.is.stacked=누적될 수 없는 계열 {0}을(를) 누적하도록 설정되었습니다.

exception.unset.label.visibility=레이블 {0}에 표시 유형 설정이 없습니다.

exception.marker.line.null.value=표지선 {0}에 정의된 대로 널(null) 값의 렌더링 선을 그릴 수 없습니다.

exception.unset.axis.visibility=축 표시 유형이 설정되지 않았고 결과가 모호합니다.

exception.unset.line.visibility={0}에서 선 특성의 표시 유형이 명확히 설정되지 않았습니다.

exception.stacked.datetime.axis.series=날짜 시간 축에 누적된 계열을 정의할 수 없습니다.

exception.stacked.unstacked.mix.series=계열 정의 {0}에 누적된 계열과 누적되지 않은 계열이 혼합되어 있습니다.

exception.internal.stack.series.setup=축 {0}에 대한 누적된 계열이 잘못 설정되었습니다.

exception.invalid.minimum.scale.value=축 유형 {1}에 잘못된 최소 배율 값 {0}이(가) 지정되었습니다.

exception.invalid.maximum.scale.value=축 유형 {1}에 잘못된 최대 배율 값 {0}이(가) 지정되었습니다.

exception.legend.orientation.horzvert=범례의 방향이 가로 또는 세로로 명확히 설정되지 않았습니다.

exception.legend.orientation.InvalidMaxPercent=최대 백분율은 0과 1 사이여야 합니다.

info.processing.stacked.info=축 {0}에 대해 누적된 정보를 처리하는 중입니다.

info.eclenv.creating.device=(이클립스 환경) 장치 {0}을(를) {1}(으)로 만드는 중입니다.

info.stdenv.creating.device=(독립 실행형 환경) 장치 {0}을(를) {1}(으)로 만드는 중입니다.

info.eclenv.creating.display=(이클립스 환경) 디스플레이 서버 {0}을(를) {1}(으)로 만드는 중입니다.

info.stdenv.creating.display=(독립 실행형 환경) 디스플레이 서버 {0}을(를) {1}(으)로 만드는 중입니다.

exception.percent.stacked.non.numerical=숫자가 아닌 데이터가 들어 있는 백분율/누적 축을 계산할 수 없습니다.

exception.text.data.numerical.datetime.axis=숫자/날짜 시간 축을 렌더링하는 데 텍스트 데이터를 사용할 수 없습니다.

exception.numerical.data.datetime.axis=날짜 시간 축을 렌더링하는 데 날짜 시간이 아닌 데이터를 사용할 수 없습니다.

exception.datetime.data.numerical.axis=숫자 축을 렌더링하는 데 숫자가 아닌 데이터를 사용할 수 없습니다.

exception.cwoa.single.series.definition=축이 없는 차트에는 단일 계열 정의만 포함될 수 있습니다.

exception.parse.value.format.specifier=형식 지정자 {1}(으)로 값 {0}을(를) 분석하지 못했습니다.

exception.orthogonal.axis.numerical.datetime=값 축에는 숫자 또는 날짜 시간 형식만 포함될 수 있습니다.

exception.axis.series.link.broken=계열 {0}에 대한 축 정의를 찾을 수 없습니다.

exception.process.content.dataset=데이터 집합 {1}에 대해 {0}(으)로 지정된 데이터 집합 내용을 처리할 수 없습니다.

exception.base.orthogonal.inconsistent.count=범주 축에는 {0}개 항목이 포함되어 있고 값 축에는 {1}개 항목이 포함되어 있습니다.

exception.base.orthogonal.null.datapoint=지정한 데이터 요소에 잘못된 널(null) 값이 있습니다.

exception.base.orthogonal.null.datadefinition=지정한 데이터 정의 식이 잘못되었습니다..

exception.dataset.non.numerical.to.numerical=데이터 집합에 숫자가 아닌 예상치 못한 데이터 형식 {0}이(가) 있습니다. 숫자 값으로 변환할 수 없습니다.

exception.dataset.non.datetime=X 축에 바인딩된 데이터 형식이 날짜 시간 형식이 아닙니다.

exception.scale.tick.max=단계가 너무 많아 렌더링할 수 없습니다. 배율 단계 또는 단위를 조정하십시오.

exception.unknown.axis.type.tick.computations=틱을 계산하는 데 필요한 축 유형을 확인할 수 없습니다.

exception.unknown.trigger.datatype=트리거 데이터가 잘못되었거나 형식을 알 수 없습니다.

exception.unsupported.compare.unknown.objects=비교 DE1={0} 및 DE2={1}에 지원되지 않은 데이터 요소가 제공되었습니다.

exception.unsupported.compare.different.objects=비교 DE1={0} 및 DE2={1}에 혼합된 데이터 요소가 제공되었습니다.

exception.resultset.data.type.retrieval.failed=결과 집합에서 데이터 형식을 확인할 수 없습니다.

exception.base.axis.no.series.definitions=주 범주 축에 계열 정의가 포함되어 있지 않습니다.

exception.no.stack.percent.3D.chart=3D 차트에 대해 스택 및 퍼센트 기능이 지원되지 않습니다.

exception.dial.dimension=''{0}''은(는) 다이얼 시리즈에서 지원되지 않습니다.

exception.pie.dimension=''{0}''은(는) 원형 시리즈에서 지원되지 않습니다.

exception.scatter.dimension=''{0}''은(는) 분산형 시리즈에서 지원되지 않습니다.

exception.stock.dimension=''{0}''은(는) 주식형 시리즈에서 지원되지 않습니다.

exception.multi.orthogonal.3D.not.supported=다중 값 축은 3D 차트에서 지원되지 않습니다.

exception.scatter.3D.not.supported=분산형 범주 축은 3D 차트에서 지원되지 않습니다.

exception.no.transposed.3D.chart=전위는 3D 차트에서 지원되지 않습니다.

exception.3D.points.length.less.than.3=3D 렌더링 이벤트에 대한 포인트 목록 길이는 3 이상이어야 합니다(>=3).

exception.unsupported.area3d.getOjbect3D=Area3DRenderEvent에서 Object3D 개체에 직접 액세스할 수 없습니다. 처리하려면 각 하위 I3DRenderEvent를 반복하십시오.

exception.javascript.error={0}, 줄 {1}, 차트 스크립트 ''{2}''

exception.null.legend.layout.hints='널(null)' 레이아웃 힌트 개체로 범례를 렌더링할 수 없습니다.

exception.null.legend.item.hints='널(null)' 레이아웃 힌트 개체로 범례 항목을 렌더링할 수 없습니다.

info.elapsed.render.time=모든 것을 렌더링하는 시간 = {0}ms

info.elapsed.time.render=모든 것을 렌더링하는 시간 = {0}ms

info.eclenv.creating.dsp=(이클립스 환경) DataSetProcessor {0}을(를) 만드는 중입니다.

info.datapoint.to.string={0}:{1}
info.stdenv.creating.dsp=(독립 실행형 환경) DataSetProcessor {0}을(를) 만드는 중입니다.

constant.undefined.string=<정의되지 않음>

constant.null.string=널(null)

error.invalid.enumerator=''{0}'' 값은 올바른 ''{1}'' 열거자가 아닙니다.

error.invalid.classifier=''{0}'' 데이터 형식은 올바른 분류자가 아닙니다.

error.invalid.argument.for.barSeries=BarSeriesImpl에 대해 {0}은(는) 잘못된 인수입니다. 차트 모델은 org.eclipse.birt.chart.model.ChartWithAxes의 인스턴스여야 합니다.

error.invalid.argument.for.lineSeries=LineSeriesImpl에 대해 {0}은(는) 잘못된 인수입니다. 차트 모델은 org.eclipse.birt.chart.model.ChartWithAxes의 인스턴스여야 합니다.

error.invalid.argument.for.stockSeries=StockSeriesImpl에 대해 {0}은(는) 잘못된 인수입니다. 차트 모델은 org.eclipse.birt.chart.model.ChartWithAxes의 인스턴스여야 합니다.

error.legend.position=차트 구성 요소를 올바르게 배열하려면 범례 블록 위치를 지정해야 합니다.

error.null.source=소스 값이 널(null)이 될 수 없습니다.

error.unknown.palette=알 수 없는 색상표 {0}이(가) 요청되었습니다. 기본값을 사용합니다.

error.type.not.set=이 DateFormatSpecifier 인스턴스에 대해 형식이 설정되지 않았습니다.

error.eclenv.cannot.find.dsp=(이클립스 환경) {0}에 대한 DataSetProcessor 구현을 찾을 수 없습니다.

error.stdenv.cannot.find.dsp=(독립 실행형 환경) {0}에 대한 DataSetProcessor 구현을 찾을 수 없습니다.

info.eclenv.creating.series.renderer=(이클립스 환경) 계열 렌더러 {0}을(를) 만드는 중입니다.

info.eclenv.creating.datapoint.definition=(ECLIPSE-ENV) 데이터 요소 정의 {0}을(를) 만드는 중입니다.

error.eclenv.cannot.find.series.renderer=(이클립스 환경) {0}에 대한 계열 렌더러 구현을 찾을 수 없습니다.

info.stdenv.creating.series.renderer=(독립 실행형 환경) 계열 렌더러 {0}을(를) 만드는 중입니다.

info.compute.elapsed.time.without.axes=축 없는 플롯을 계산하는 시간 = {0}ms

info.compute.elapsed.time.with.axes=축 있는 플롯을 계산하는 시간 = {0}ms

error.stdenv.cannot.find.series.renderer=(독립 실행형 환경) {0}에 대한 계열 렌더러 구현을 찾을 수 없습니다.

error.stdenv.cannot.find.datapoint.definition=(STANDALONE-ENV) {0}에 대한 데이터 요소 정의 impl을 찾을 수 없습니다.

error.eclenv.cannot.find.device=(이클립스 환경) {0}에 대한 장치 렌더러 구현을 찾을 수 없습니다.

error.stdenv.cannot.find.device=(독립 실행형 환경) {0}에 대한 장치 렌더러 구현을 찾을 수 없습니다.

error.eclenv.cannot.find.display=(이클립스 환경) {0}에 대한 디스플레이 서버 구현을 찾을 수 없습니다.

error.stdenv.cannot.find.display=(독립 실행형 환경) {0}에 대한 디스플레이 서버 구현을 찾을 수 없습니다.

info.log.script=[SCRIPT]: {0}

info.render.series={0}: renderSeries() [{1}/{2}]
info.log.info=[INFO]: {0}

info.log.warn=[WARN]: {0}

info.log.err=[ERR]: {0}

info.log.fatal=[FATAL]: {0}

prefix.marker.range.caption=[
separator.marker.range.caption=\ -

suffix.marker.range.caption=]
wrapped.instruction.to.string={0}: 모델={1}; 바운딩={2}

exception.mixed.data.types=집계 함수 {0}에 요약할 혼합 입력 데이터가 있습니다.

info.eclenv.creating.function=(이클립스 환경) 집계 함수 {0}을(를) 만드는 중입니다.

error.eclenv.cannot.find.function=(이클립스 환경) {0}에 대한 집계 함수 구현을 찾을 수 없습니다.

info.stdenv.creating.function=(독립 실행형 환경) 집계 함수 {0}을(를) 만드는 중입니다.

error.stdenv.cannot.find.function=(독립 실행형 환경) {0}에 대한 집계 함수 구현을 찾을 수 없습니다.

Info.try.load.java.handler=차트 Java 이벤트 처리기 클래스를 로드하려는 중...

Info.java.handler.loaded=차트 Java 이벤트 처리기 클래스 [{0}]이(가) 로드되었습니다.

Info.invalid.java.handler=잘못된 차트 Java 이벤트 처리기 클래스 [{0}]이(가) 발견되어 무시되었습니다.

Info.try.register.javascript.content=차트 JavaScript 내용을 로드하려는 중...

Info.javascript.content.registered=차트 JavaScript 내용이 로드되었습니다.

warn.unspecified.sorting={0}에 대한 정렬이 지정되지 않았습니다.

##################################################
# Attributes 
#
# !!the key is bound to those attribute literal' name value, 
# !!if that changes, this must be updated accordingly.
#
SeriesImpl.displayName=기본 계열

AreaSeriesImpl.displayName=영역형 계열

BarSeriesImpl.displayName=막대형 계열

BarSeriesImpl.coneDisplayName=원뿔 계열

BarSeriesImpl.tubeDisplayName=튜브 계열

BarSeriesImpl.pyramidDisplayName=피라미드 계열

DialSeriesImpl.displayName=다이얼 시리즈

LineSeriesImpl.displayName=선형 계열

PieSeriesImpl.displayName=원형 계열

ScatterSeriesImpl.displayName=분산형 계열

StockSeriesImpl.displayName=주식형 계열

BubbleSeriesImpl.displayName=거품형 계열

GanttSeriesImpl.displayName=Gantt 계열

DifferenceSeriesImpl.displayName=차이 계열

AxisType.Linear.displayName=선형

AxisType.Logarithmic.displayName=로그

AxisType.Text.displayName=텍스트

AxisType.DateTime.displayName=DateTime
IntersectionType.Min.displayName=Min

IntersectionType.Max.displayName=Max

IntersectionType.Value.displayName=값

ScaleUnitType.Seconds.displayName=초

ScaleUnitType.Minutes.displayName=분

ScaleUnitType.Hours.displayName=시간

ScaleUnitType.Days.displayName=일

ScaleUnitType.Weeks.displayName=주

ScaleUnitType.Months.displayName=월

ScaleUnitType.Quarters.displayName=분기

ScaleUnitType.Years.displayName=연

SortOption.Ascending.displayName=오름차순

SortOption.Descending.displayName=내림차순

TriggerCondition.MouseHover.displayName=마우스 가리킴(사용되지 않음)

TriggerCondition.MouseClick.displayName=마우스 클릭(사용되지 않음)

TriggerCondition.onclick.displayName=마우스 클릭

TriggerCondition.ondblclick.displayName=마우스 두 번 클릭

TriggerCondition.onmousedown.displayName=마우스 누름

TriggerCondition.onmouseup.displayName=마우스 누름 해제

TriggerCondition.onmouseover.displayName=마우스를 위에 놓음

TriggerCondition.onmousemove.displayName=마우스 이동

TriggerCondition.onmouseout.displayName=마우스를 다른 곳으로 이동

TriggerCondition.onfocus.displayName=초점

TriggerCondition.onblur.displayName=흐리게

TriggerCondition.onkeydown.displayName=키 누른 상태

TriggerCondition.onkeypress.displayName=키 누름

TriggerCondition.onkeyup.displayName=키 누르지 않은 상태

TriggerCondition.onload.displayName=로드

ActionType.URLRedirect.displayName=하이퍼링크

ActionType.ShowTooltip.displayName=도구 설명 표시

ActionType.ToggleVisibility.displayName=표시 유형 전환

ActionType.InvokeScript.displayName=스크립트 호출

ActionType.Highlight.displayName=강조

ActionType.CallBack.displayName=콜백

ActionType.ToggleDataPointVisibility.displayName=데이터 요소 표시 유형 전환

TickStyle.Across.displayName=옆으로

TickStyle.Left.displayName=왼쪽

TickStyle.Right.displayName=오른쪽

TickStyle.Above.displayName=위

TickStyle.Below.displayName=아래

DataPointComponentType.BaseValue.displayName=범주 데이터

DataPointComponentType.OrthogonalValue.displayName=값 데이터

DataPointComponentType.SeriesValue.displayName=값 계열 이름:

DataPointComponentType.PercentileOrthogonalValue.displayName=백분위수 값 데이터

LeaderLineStyle.FixedLength.displayName=고정 길이

LeaderLineStyle.StretchToSide.displayName=측면에 맞춤

MarkerType.Crosshair.displayName=십자 기호

MarkerType.Triangle.displayName=삼각형

MarkerType.Box.displayName=상자

MarkerType.Circle.displayName=원

MarkerType.Icon.displayName=아이콘

MarkerType.Nabla.displayName=나블라

MarkerType.Diamond.displayName=다이아몬드

MarkerType.FourDiamonds.displayName=4개의 다이아몬드

MarkerType.Ellipse.displayName=타원

MarkerType.SemiCircle.displayName=반원

MarkerType.Hexagon.displayName=육각형

MarkerType.Rectangle.displayName=사각형

MarkerType.Star.displayName=별형

MarkerType.Column.displayName=열

MarkerType.Cross.displayName=교차

RiserType.Rectangle.displayName=사각형

RiserType.Triangle.displayName=삼각형

RiserType.Tube.displayName=튜브

RiserType.Cone.displayName=원뿔

Anchor.North.displayName=위쪽

Anchor.NorthEast.displayName=오른쪽 위

Anchor.East.displayName=오른쪽

Anchor.SouthEast.displayName=오른쪽 아래

Anchor.South.displayName=아래쪽

Anchor.SouthWest.displayName=왼쪽 아래

Anchor.West.displayName=왼쪽

Anchor.NorthWest.displayName=왼쪽 위

AnchorVertical.North.displayName=위쪽

AnchorVertical.South.displayName=아래쪽

AnchorVertical.West.displayName=중간

AnchorHorizontal.East.displayName=오른쪽

AnchorHorizontal.South.displayName=중간

AnchorHorizontal.West.displayName=왼쪽

AutoScale.Exception.IsInfiite=\ 무한대

AutoScale.Exception.IsNaN=\ NaN

AutoScale.ValueName.StepSize=step size

Stretch.Horizontal.displayName=가로

Stretch.Vertical.displayName=세로

Stretch.Both.displayName=모두

Orientation.Horizontal.displayName=가로

Orientation.Vertical.displayName=세로

Direction.LeftRight.displayName=왼쪽/오른쪽

Direction.TopBottom.displayName=위쪽/아래쪽

LegendItemType.Series.displayName=값 계열

LegendItemType.Categories.displayName=범주

Position.Above.displayName=위

Position.Below.displayName=아래

Position.Left.displayName=왼쪽

Position.Right.displayName=오른쪽

Position.Inside.displayName=안쪽

Position.Outside.displayName=바깥쪽

UnitsOfMeasurement.Pixels.displayName=픽셀

UnitsOfMeasurement.Points.displayName=포인트

UnitsOfMeasurement.Inches.displayName=인치

UnitsOfMeasurement.Centimeters.displayName=센티미터

DataType.Numeric.displayName=숫자

DataType.DateTime.displayName=DateTime
DataType.Text.displayName=텍스트

GroupingUnitType.Seconds.displayName=초

GroupingUnitType.Minutes.displayName=분

GroupingUnitType.Hours.displayName=시간

GroupingUnitType.Days.displayName=일

GroupingUnitType.Weeks.displayName=주

GroupingUnitType.Months.displayName=월

GroupingUnitType.Years.displayName=연

GroupingUnitType.Quarters.displayName=분기

GroupingUnitType.String.displayName=문자열

GroupingUnitType.StringPrefix.displayName=문자열 접두사

DateFormatType.Long.displayName=Long

DateFormatType.Short.displayName=짧게

DateFormatType.Medium.displayName=중간

DateFormatType.Full.displayName=전체

DateFormatDetail.Date.displayName=날짜

DateFormatDetail.DateTime.displayName=날짜/시간

DefaultValueProvider_BaseSeries=기본 계열

DefaultValueProvider_ChartSubType.Standard=표준

DefaultValueProvider_ChartSubType.StandardMeterChart=표준 측정기 차트

DefaultValueProvider_ChartTitle=차트 제목

DefaultValueProvider_ChartUnits.Points=포인트

LegendBehaviorType.None.displayName=없음

LegendBehaviorType.ToggleSerieVisibility.displayName=계열 표시 유형 전환

LegendBehaviorType.HighlightSerie.displayName=계열 강조

# Defines cursor display names.
Cursor.Auto.displayName=자동

Cursor.Crosshair.displayName=십자 기호

Cursor.Default.displayName=기본

Cursor.Pointer.displayName=손 모양

Cursor.Move.displayName=이동

Cursor.Text.displayName=텍스트

Cursor.Wait.displayName=검색 중

Cursor.EResize.displayName=동

Cursor.NEResize.displayName=북동

Cursor.NWResize.displayName=북서

Cursor.NResize.displayName=북쪽

Cursor.SEResize.displayName=남동

Cursor.SWResize.displayName=남서

Cursor.SResize.displayName=남

Cursor.WResize.displayName=서

Cursor.Custom.displayName=사용자 지정

ActionType.URLRedirect.DisplayName=URL 리디렉션

ActionType.InvokeScript.DisplayName=스크립트 호출

ActionType.Highlight.DisplayName=강조

ActionType.ToggleVisibility.DisplayName=표시 유형 전환

ActionType.ToggleDataPointVisibility.DisplayName=데이터 요소 표시 유형 전환

# End of Attributes
##################################################
dataprocessor.log.baseSeriesDefn3=범주 계열 정의 ({0})가 정적 식으로 사용됩니다.

dataprocessor.exception.CannotDecipher=다중 범주 계열 정의를 포함하는 차트의 내용을 해독할 수 없습니다.

dataprocessor.exception.FoundDefnAssociatedWithX=범주(X) 계열 식과 연결된 데이터 정의가 {0}개 있습니다. 범주 계열 데이터 정의는 하나만 지원됩니다.

dataprocessor.exception.DefinitionUnspecified=범주 계열에 대한 데이터 정의가 지정되지 않았습니다.

dataprocessor.exception.DefnExpMustAssociateY=데이터 정의 식은 {1}에서 정의된 값 (Y) 계열-{0}와(과) 연결되어야 합니다.

dataprocessor.exception.AtLeastOneDefnExpMustAssociateY=적어도 하나 이상의 데이터 정의 식이 {1}에서 정의된 값 (Y) 계열-{0}와(과) 연결되어야 합니다.

dataprocessor.exception.CannotDecipher2=다중 범주 계열 정의를 포함하는 차트의 내용을 해독할 수 없습니다.

dataprocessor.log.XSeriesDefn=X 계열 정의({0})가 정적 식으로 사용됩니다.

dataprocessor.exception.FoundMoreThanOneDefnAssociateX=X 계열 식과 연결된 데이터 정의가 {0}개 있습니다. X 계열 데이터 정의는 하나만 지원됩니다.

edataprocessor.xception.definitionsAssociatedWithX=X 계열에 대한 데이터 정의가 지정되지 않았습니다.

dataprocessor.log.baseSeriesDefnBeStatic=범주 계열 정의 ({0})가 정적 식으로 사용됩니다.

exception.data.max.row.count={0} 행의 데이터를 바인딩 하는 차트를 렌더링할 수 없습니다.


# Default chart title
BarChart.Title=막대형 차트 제목

LineChart.Title=선형 차트 제목

AreaChart.Title=영역형 차트 제목

PieChart.Title=원형 차트 제목

MeterChart.Title=측정기 차트 제목

ScatterChart.Title=분산형 차트 제목

StockChart.Title=주식형 차트 제목

BubbleChart.Title=거품형 차트 제목

DifferenceChart.Title=차이점 차트 제목

GanttChart.Title=간트 차트 제목

TubeChart.Title=튜브 차트 제목

PyramidChart.Title=피라미드 차트 제목

ConeChart.Title=원뿔 차트 제목

RadarChart.Title=방사형 차트 제목

ColumnChart.Title=세로 막대형 차트 제목

DoughnutChart.Title=도넛형 차트 제목