ChartImpl.ChartTitle=Diagrammtitel

ChartImpl.AltText=Dieses Diagramm enthält keine Daten.

ChartWithAxesImpl.X_Axis.title=Titel der X-Achse

ChartWithAxesImpl.Y_Axis.title=Titel der Y-Achse

ChartWithAxesImpl.Z_Axis.title=Titel der z-Achse

ChartWithoutAxesImpl.Unsupported3Dimension=Kreisdiagramm unterstützt 3D nicht.

exception.convert.double=Wert {0} kann nicht in einen Doppelwert umgewandelt werden

exception.data.outofsync=Eingabedaten nicht synchronisiert; Kategorie-Datenreihe enthält {0} Werte; Wert-Datenreihe enthält {1} Werte.

exception.out.of.bounds=Außerhalb der zulässigen Grenzen

exception.step.zoom.out=zoomOut für Schritt={0} nicht möglich

exception.no3d.support=3D-Diagramme werden noch nicht unterstützt

exception.curve.label.position.not.supported=Die Beschriftungsposition [{0}] wird bei der Kurvenanpassung nicht unterstützt.

exception.convert.calendar=Wert {0} kann nicht in einen Kalenderwert umgewandelt werden

exception.anchor.transpose=Anker {0} kann nicht für Achsenausrichtung {1} transponiert werden

exception.tick.computations=Fehler bei Skalenberechnung

exception.curve.visibility.unset=Die Sichtbarkeit muss für die Linienattribute der Kurve gesetzt werden

exception.angle.range.transpose=[Winkel={0}] kann nicht außerhalb des Bereichs (90 >= 0 >= -90) transponiert werden

exception.legend.direction.tblr=Die Richtung der Legende wurde nicht ausdrücklich auf Oben-Unten oder Links-Rechts festgelegt

exception.scale.null.location=Koordinate für Null-Wert auf Skala {0} kann nicht gefunden werden

exception.illegal.icon.palette.type.for.marker=''{0}'' ist kein gültiger Bildtyp für das Markierungssymbol.

exception.illegal.filltype.crosshair.marker=Palettenfarbe kann auf Markierungs-CROSSHAIR nicht als {0} festgelegt werden

exception.illegal.filltype.cross.marker=Palettenfarbe kann auf Markierungs-CROSS nicht als {0} festgelegt werden

exception.invalid.step.size =Ungültige "step size({0}) <= 0" für Achsenskala festgelegt

exception.invalid.step.number =Ungültige ''step number({0}) < 1'' für Achsenskala festgelegt

exception.curve.line.visibility.not.defined=Die Eigenschaft "Sichtbarkeit" der Kurvenlinie ist nicht korrekt definiert.

exception.min.largerthan.max=Ungültige Einträge "min({0}) > max({1})" für Achsenskala festgelegt

exception.combination.axis.label.position=Unerwartete Kombination von Achse={0} und Beschriftungsposition={1}

exception.cannot.locate.start.marker.range=Bereichsanfang für Wert {0} in Markierungsbereich {1} konnte nicht gefunden werden

exception.cannot.locate.value.marker.line=Wert {0} in Markierungslinie {1} konnte nicht gefunden werden

exception.combination.axis.tick.style=Unerwartete Kombination von Achse={0} und Skalentyp={1}

exception.invalid.axis.data.type=Der für die Achse angegebene Datentyp stimmt nicht mit dem Datenfeldwert überein: ({0})

exception.undefined.axis.data.type=Der Datentyp ist für Achse {0} nicht definiert

exception.unsupported.compare.text=Vergleich von Textdatenelementen wird nicht unterstützt

exception.unsupported.comparison=Objekt {0} kann nicht Teil von Vergleich mit früheren Versionen sein

exception.unsupported.internal.draw={0} kann nicht intern über das Ereignis gezeichnet werden

exception.unsupported.internal.fill={0} kann nicht intern über das Ereignis gefüllt werden

exception.unsupported.chart.model=Durch Modell [{0}] definiertes Diagramm kann nicht berechnet werden

exception.unsupported.bounds=Grenzen für Ereignis {0} können nicht berechnet werden

exception.unsupported.copy=Kopie von Ereignis {0} kann nicht erstellt werden

exception.unsupported.step.number=Schrittnummer wird für nicht numerischen Wert nicht unterstützt.

exception.undefined.data.point=Der mit der Datenreihendefinition verknüpfte DataPoint-Wert ist nicht definiert

exception.unit.size.failure=Einheitengröße kann nicht berechnet werden, da Skalenkoordinaten nicht definiert sind

exception.process.content.type=Als {0} festgelegte Datensatzinhalte für Typ {1} können nicht verarbeitet werden

exception.undefined.axis.label.visibility=Die Sichtbarkeit für Beschriftungen der Achse {0} ist nicht definiert

exception.undefined.axis.title.visibility=Die Sichtbarkeit für Titel der Achse {0} ist nicht definiert

exception.undefined.axis.label.position=Die Beschriftungsposition für Achse {0} ist nicht definiert

exception.undefined.axis.title.position=Die Titelposition für Achse {0} ist nicht definiert

exception.undefined.data.label.position=Die Datenbeschriftungsposition für Datenreihe {0} ist nicht definiert

exception.undefined.axis.type=Der Achsentyp ist nicht definiert für Achse

exception.unset.series.stacked.property=Die Eigenschaft ''Gestapelt'' wurde für stapelbare Datenreihe {0} nicht ausdrücklich festgelegt.

exception.undefined.axis.major.tick.style=Der Hauptraster-Skalenstil für Achse {0} ist nicht definiert

exception.undefined.axis.minor.tick.style=Der Zusatzraster-Skalenstil für Achse {0} ist nicht definiert

exception.zero.negative.logarithmic.scale=Logarithmische Skala darf keine Null-Werte oder negativen Werte enthalten

exception.illegal.vaxis.label.position=Ungültiger Wert der Beschriftungsposition {0} für vertikale Achse {1} festgelegt

exception.illegal.vaxis.title.position=Ungültiger Wert der Titelposition {0} für vertikale Achse {1} festgelegt

exception.illegal.vaxis.major.tick.style=Ungültiger Hauptskalenstil als {0} für vertikale Achse {1} festgelegt

exception.illegal.vaxis.minor.tick.style=Ungültiger Zusatzskalenstil als {0} für vertikale Achse {1} festgelegt

exception.illegal.haxis.label.position=Ungültiger Wert der Beschriftungsposition {0} für horizontale Achse {1} festgelegt

exception.illegal.haxis.title.position=Ungültiger Wert der Titelposition {0} für horizontale Achse {1} festgelegt

exception.illegal.rotation.angle.label=Der Rotationswinkel (-90 <= WINKEL <= 90) wurde für Beschriftung {0} ungültig festgelegt

exception.illegal.rendering.direction=Ungültiges Argument für Legenden-Darstellungsrichtung = {0} festgelegt

exception.illegal.rendering.orientation=Ungültiges Argument für Legenden-Darstellungsausrichtung = {0} festgelegt

exception.illegal.legend.direction=Ungültiges Argument für Legenden-Darstellungsrichtung = {0} festgelegt

exception.illegal.null.value=Ungültiger Null-Wert als Argument für Diagrammerstellung übergeben

exception.cannot.find.plugin.entry=Es wurden keine Werte für Nachschlagen={0} gefunden; Element=({1}:{2}) in allen Dateien "plugin.xml" aller verfügbaren Plugins

exception.cannot.split.major=Haupteinheit kann nicht in {0} Zusatzeinheit(en) aufgeteilt werden.

exception.illegal.legend.orientation=Ungültiges Argument für Legenden-Darstellungsausrichtung = {0} festgelegt

exception.cwoa.single.runtime.series=Diagramme ohne Achsen dürfen nur eine einzige Laufzeitdatenreihe enthalten

exception.illegal.haxis.major.tick.style=Ungültiger Hauptskalenstil als {0} für horizontale Achse {1} festgelegt

exception.illegal.haxis.minor.tick.style=Ungültiger Zusatzskalenstil als {0} für horizontale Achse {1} festgelegt

exception.client.area.outline.visibility=Sichtbarkeit für Client-Flächenumriss wurde nicht festgelegt

exception.cannot.locate.end.marker.range=Bereichsende für Wert {0} in Markierungsbereich {1} konnte nicht gefunden werden

exception.runtime.dataset.count.mismatch=Diskrepanz ({0}\!={1}) der Datensatzanzahl in gestapelter Laufzeitdatenreihe gefunden

exception.illegal.base.runtime.series.count=Anzahl der Kategorie-Laufzeitdatenreihen (hier {0}) für ein Diagramm ohne Achsen muss 1 sein

exception.unstackable.is.stacked=Eine Datenreihe {0}, die nicht gestapelt werden darf, wurde als gestapelt festgelegt

exception.unset.label.visibility=Für Beschriftung {0} ist die Sichtbarkeit nicht festgelegt

exception.marker.line.null.value=Renderlinie für einen Null-Wert wie in Markierungslinie {0} definiert kann nicht gezeichnet werden

exception.unset.axis.visibility=Die Achsensichtbarkeit ist nicht festgelegt; dies führt zu nicht eindeutigen Ergebnissen

exception.unset.line.visibility=Sichtbarkeit der Linienattribute in {0} wurde nicht ausdrücklich festgelegt

exception.stacked.datetime.axis.series=Gestapelte Datenreihe kann auf Datum-/Zeitachse nicht definiert werden.

exception.stacked.unstacked.mix.series=Datenreihendefinition {0} enthält Kombination aus gestapelten und nicht gestapelten Datenreihen.

exception.internal.stack.series.setup=Gestapelte Datenreihe für Achse {0} nicht korrekt definiert

exception.invalid.minimum.scale.value=Ungültiger minimaler Skalenwert {0} für Achsentyp {1} festgelegt

exception.invalid.maximum.scale.value=Ungültiger maximaler Skalenwert {0} für Achsentyp {1} festgelegt

exception.legend.orientation.horzvert=Die Ausrichtung der Legende wurde nicht ausdrücklich auf horizontal oder vertikal festgelegt

exception.legend.orientation.InvalidMaxPercent=Max. Prozentsatz muss zwischen 0 und 1 liegen.

info.processing.stacked.info=Gestapelte Informationen für Achse {0} werden verarbeitet

info.eclenv.creating.device=(ECLIPSE-UMG) Gerät {0} wird als {1} erstellt

info.stdenv.creating.device=(EINZELPLATZ-UMG) Gerät {0} wird als {1} erstellt

info.eclenv.creating.display=(ECLIPSE-UMG) Anzeigeserver {0} wird als {1} erstellt

info.stdenv.creating.display=(EINZELPLATZ-UMG) Anzeigeserver {0} wird als {1} erstellt

exception.percent.stacked.non.numerical=Prozentachse/gestapelte Achse mit nicht numerischen Daten kann nicht berechnet werden

exception.text.data.numerical.datetime.axis=Verwenden von Textdaten zum Rendern einer numerischen oder Datum-/Uhrzeit-Achse nicht möglich.

exception.numerical.data.datetime.axis=Verwenden von nicht datum- oder uhrzeitbezogenen Daten zum Rendern einer Datum-/Uhrzeit-Achse nicht möglich.

exception.datetime.data.numerical.axis=Verwenden von nicht numerischen Daten zum Rendern einer numerischen Achse nicht möglich.

exception.cwoa.single.series.definition=Diagramme ohne Achsen dürfen nur eine einzige Datenreihendefinition enthalten

exception.parse.value.format.specifier=Wert {0} mit Formatbezeichner {1} konnte nicht analysiert werden

exception.orthogonal.axis.numerical.datetime=Die Wertachse darf nur numerisches oder Datum/Uhrzeit-Format haben

exception.axis.series.link.broken=Achsendefinition für Datenreihe {0} konnte nicht gefunden werden

exception.process.content.dataset=Als {0} festgelegte Datensatzinhalte für Datensatz {1} können nicht verarbeitet werden

exception.base.orthogonal.inconsistent.count=Kategorieachse enthält {0} Objekte; Wertachse enthält {1} Objekte.

exception.base.orthogonal.null.datapoint=Die angegebenen Datenpunkte enthalten einen ungültigen Null-Wert.

exception.base.orthogonal.null.datadefinition=Der angegebene Datendefinitionsausdruck ist ungültig..

exception.dataset.non.numerical.to.numerical=Unerwarteter nicht numerischer Datentyp {0} in Datensatz gefunden; Umwandlung in numerischen Wert nicht möglich.

exception.dataset.non.datetime=Der an die X-Achse gebundene Datentyp hat nicht das Format "Datum/Uhrzeit"

exception.scale.tick.max=Rendern zu vieler Raster nicht möglich. Passen Sie den Skalenschritt oder die Skaleneinheit an.

exception.unknown.axis.type.tick.computations=Achsentyp zur Berechnung der Skalenunterteilung kann nicht bestimmt werden

exception.unknown.trigger.datatype=Die Auslöserdaten sind ungültig, oder der Typ ist unbekannt.

exception.unsupported.compare.unknown.objects=Nicht unterstützte Datenelemente für Vergleich DE1={0} und DE2={1} angegeben

exception.unsupported.compare.different.objects=Gemischte Datenelemente für Vergleich DE1={0} und DE2={1} angegeben

exception.resultset.data.type.retrieval.failed=Datentypen können aus Ergebnis nicht bestimmt werden

exception.base.axis.no.series.definitions=Die primäre Kategorieachse enthält keine Datenreihendefinitionen

exception.no.stack.percent.3D.chart=Stapel- und Prozentfunktion werden in 3D-Diagrammen nicht unterstützt.

exception.dial.dimension="{0}" wird von der Tachometer-Datenreihe nicht unterstützt.

exception.pie.dimension="{0}" wird von der Kreisdiagramm-Datenreihe nicht unterstützt.

exception.scatter.dimension="{0}" wird von der Punktdiagramm-Datenreihe nicht unterstützt.

exception.stock.dimension="{0}" wird von der Kursdiagramm-Datenreihe nicht unterstützt.

exception.multi.orthogonal.3D.not.supported=3D-Diagramme unterstützen nur eine Wertachse.

exception.scatter.3D.not.supported=Punktdiagramm-Kategorieachse wird von 3D-Diagrammen nicht unterstützt.

exception.no.transposed.3D.chart=Transposition wird von 3D-Diagrammen nicht unterstützt.

exception.3D.points.length.less.than.3=Die Länge der Punkteliste für das 3D-Render-Ereignis muss mindestens 3(>=3) betragen.

exception.unsupported.area3d.getOjbect3D=Direkter Zugriff von Area3DRenderEvent auf Object3D wird nicht unterstützt. Wiederholen Sie zum Verarbeiten jedes untergeordnete I3DRenderEvent.

exception.javascript.error={0} in Zeile {1} des Diagrammskripts:''{2}''

exception.null.legend.layout.hints=Rendern der Legende mit 'null' Layouthinweisen für das Objekt nicht möglich.

exception.null.legend.item.hints=Rendern des Legendenelements mit 'null' Elementhinweisen für das Objekt nicht möglich.

info.elapsed.render.time=Zeit für vollständiges Rendern = {0} ms

info.elapsed.time.render=Zeit für vollständiges Rendern = {0} ms

info.eclenv.creating.dsp=(ECLIPSE-UMG) DataSetProcessor {0} wird erstellt

info.datapoint.to.string={0}:{1}
info.stdenv.creating.dsp=(EINZELPLATZ-UMG) DataSetProcessor {0} wird erstellt

constant.undefined.string=<nicht definiert>

constant.null.string=Null

error.invalid.enumerator=Der Wert ''{0}'' ist kein gültiger Zähler von ''{1}''

error.invalid.classifier=Der Datentyp ''{0}'' ist kein gültiger Klassifikator

error.invalid.argument.for.barSeries={0} ist ein ungültiges Argument für BarSeriesImpl. Das Diagrammmodel muss eine Instanz von org.eclipse.birt.chart.model.ChartWithAxes sein.

error.invalid.argument.for.lineSeries={0} ist ein ungültiges Argument für LineSeriesImpl. Das Diagrammmodel muss eine Instanz von org.eclipse.birt.chart.model.ChartWithAxes sein.

error.invalid.argument.for.stockSeries={0} ist ein ungültiges Argument für StockSeriesImpl. Das Diagrammmodel muss eine Instanz von org.eclipse.birt.chart.model.ChartWithAxes sein.

error.legend.position=Die Position des Legendenblocks muss angegeben werden, damit die Diagrammbestandteile korrekt dargestellt werden können.

error.null.source=Quellwert darf nicht Null sein

error.unknown.palette=Eine unbekannte Palette {0} wurde angefordert, Standardpalette wird verwendet

error.type.not.set=Es wurde kein TYP für diese Instanz von DateFormatSpecifier festgelegt.

error.eclenv.cannot.find.dsp=(ECLIPSE-UMG) DataSetProcessor-Implementierung für {0} nicht gefunden

error.stdenv.cannot.find.dsp=(EINZELPLATZ-UMG) DataSetProcessor-Implementierung für {0} nicht gefunden

info.eclenv.creating.series.renderer=(ECLIPSE-UMG) Datenreihen-Renderer {0} wird erstellt

info.eclenv.creating.datapoint.definition=(ECLIPSE-UMG) Datenpunktdefinition {0} wird erstellt

error.eclenv.cannot.find.series.renderer=(ECLIPSE-UMG) Datenreihen-Renderer-Implementierung für {0} nicht gefunden

info.stdenv.creating.series.renderer=(EINZELPLATZ-UMG) Datenreihen-Renderer {0} wird erstellt

info.compute.elapsed.time.without.axes=Zeit für Berechnung des Diagramms (ohne Achsen) = {0} ms

info.compute.elapsed.time.with.axes=Zeit für Berechnung des Diagramms (mit Achsen) = {0} ms

error.stdenv.cannot.find.series.renderer=(EINZELPLATZ-UMG) Datenreihen-Renderer-Implementierung für {0} nicht gefunden

error.stdenv.cannot.find.datapoint.definition=(EINZELPLATZ-UMG) Datenpunktdefinition-Implementierung für {0} nicht gefunden

error.eclenv.cannot.find.device=(ECLIPSE-UMG) Geräte-Renderer-Implementierung für {0} nicht gefunden

error.stdenv.cannot.find.device=(EINZELPLATZ-UMG) Geräte-Renderer-Implementierung für {0} nicht gefunden

error.eclenv.cannot.find.display=(ECLIPSE-UMG) Anzeigeserver-Implementierung für {0} nicht gefunden

error.stdenv.cannot.find.display=(EINZELPLATZ-UMG) Anzeigeserver-Implementierung für {0} nicht gefunden

info.log.script=[SKRIPT]: {0}

info.render.series={0}: renderSeries() [{1}/{2}]
info.log.info=[INFO]: {0}

info.log.warn=[WARN]: {0}

info.log.err=[FEHLER]: {0}

info.log.fatal=[NICHT BEHEBBAR]: {0}

prefix.marker.range.caption=[
separator.marker.range.caption=\ bis

suffix.marker.range.caption=]
wrapped.instruction.to.string={0}: Modell={1}; Grenzen={2}

exception.mixed.data.types=Bei der Aggregatfunktion {0} wurden gemischte Eingabedaten für die Zusammenfassung gefunden

info.eclenv.creating.function=(ECLIPSE-UMG) Aggregatfunktion {0} wird erstellt

error.eclenv.cannot.find.function=(ECLIPSE-UMG) Aggregatfunktion-Implementierung für {0} nicht gefunden

info.stdenv.creating.function=(EINZELPLATZ-UMG) Aggregatfunktion {0} wird erstellt

error.stdenv.cannot.find.function=(EINZELPLATZ-UMG) Aggregatfunktion-Implementierung für {0} nicht gefunden

Info.try.load.java.handler=Diagramm-Java-Ereignis-Handler-Klasse wird geladen ...

Info.java.handler.loaded=Eine Diagramm-Java-Ereignis-Handler-Klasse [{0}] wurde geladen.

Info.invalid.java.handler=Eine ungültige Diagramm-Java-Ereignis-Handler-Klasse [{0}] wurde gefunden und ignoriert.

Info.try.register.javascript.content=Diagramm-JavaScript-Inhalt wird geladen ...

Info.javascript.content.registered=Diagramm-JavaScript-Inhalt wurde geladen.

warn.unspecified.sorting=Keine Sortierung angegeben für {0}.

##################################################
# Attributes 
#
# !!the key is bound to those attribute literal' name value, 
# !!if that changes, this must be updated accordingly.
#
SeriesImpl.displayName=Einfache Datenreihe

AreaSeriesImpl.displayName=Flächendiagramm-Datenreihe

BarSeriesImpl.displayName=Balkendiagramm-Datenreihe

BarSeriesImpl.coneDisplayName=Kegelreihe

BarSeriesImpl.tubeDisplayName=Röhrenreihe

BarSeriesImpl.pyramidDisplayName=Pyramidenreihe

DialSeriesImpl.displayName=Tachometerdiagramm-Datenreihe

LineSeriesImpl.displayName=Liniendiagramm-Datenreihe

PieSeriesImpl.displayName=Kreisdiagramm-Datenreihe

ScatterSeriesImpl.displayName=Punktdiagramm-Datenreihe

StockSeriesImpl.displayName=Kursdiagramm-Datenreihe

BubbleSeriesImpl.displayName=Blasen-Reihe

GanttSeriesImpl.displayName=Gantt-Reihe

DifferenceSeriesImpl.displayName=Differenz-Reihe

AxisType.Linear.displayName=Linear

AxisType.Logarithmic.displayName=Logarithmisch

AxisType.Text.displayName=Text

AxisType.DateTime.displayName=DateTime
IntersectionType.Min.displayName=Min

IntersectionType.Max.displayName=Max

IntersectionType.Value.displayName=Wert

ScaleUnitType.Seconds.displayName=Sekunden

ScaleUnitType.Minutes.displayName=Minuten

ScaleUnitType.Hours.displayName=Stunden

ScaleUnitType.Days.displayName=Tage

ScaleUnitType.Weeks.displayName=Wochen

ScaleUnitType.Months.displayName=Monate

ScaleUnitType.Quarters.displayName=Quartalen

ScaleUnitType.Years.displayName=Jahre

SortOption.Ascending.displayName=Aufsteigend

SortOption.Descending.displayName=Absteigend

TriggerCondition.MouseHover.displayName=Mouseover (Veraltet)

TriggerCondition.MouseClick.displayName=Mausklick (Veraltet)

TriggerCondition.onclick.displayName=Mausklick

TriggerCondition.ondblclick.displayName=Maus: Doppelklick

TriggerCondition.onmousedown.displayName=Maus: Nach unten

TriggerCondition.onmouseup.displayName=Maus: Nach oben

TriggerCondition.onmouseover.displayName=Mouseover

TriggerCondition.onmousemove.displayName=Maus: Bewegung

TriggerCondition.onmouseout.displayName=Mouseout

TriggerCondition.onfocus.displayName=Fokus

TriggerCondition.onblur.displayName=Verzerrung

TriggerCondition.onkeydown.displayName=Taste: Nach unten

TriggerCondition.onkeypress.displayName=Taste: Drücken

TriggerCondition.onkeyup.displayName=Taste: Nach oben

TriggerCondition.onload.displayName=Laden

ActionType.URLRedirect.displayName=Hyperlink

ActionType.ShowTooltip.displayName=QuickInfo anzeigen

ActionType.ToggleVisibility.displayName=Sichtbarkeit ein/aus

ActionType.InvokeScript.displayName=Skript aufrufen

ActionType.Highlight.displayName=Markieren

ActionType.CallBack.displayName=Callback

ActionType.ToggleDataPointVisibility.displayName=Datenpunkt-Sichtbarkeit ein/aus

TickStyle.Across.displayName=Quer

TickStyle.Left.displayName=Links

TickStyle.Right.displayName=Rechts

TickStyle.Above.displayName=Oben

TickStyle.Below.displayName=Unten

DataPointComponentType.BaseValue.displayName=Kategoriedaten

DataPointComponentType.OrthogonalValue.displayName=Wertdaten

DataPointComponentType.SeriesValue.displayName=Name der Wert-Datenreihe

DataPointComponentType.PercentileOrthogonalValue.displayName=Perzentilwertdaten

LeaderLineStyle.FixedLength.displayName=Feste Länge

LeaderLineStyle.StretchToSide.displayName=Seitlich strecken

MarkerType.Crosshair.displayName=Fadenkreuz

MarkerType.Triangle.displayName=Dreieck

MarkerType.Box.displayName=Feld

MarkerType.Circle.displayName=Kreis

MarkerType.Icon.displayName=Symbol

MarkerType.Nabla.displayName=Nabla

MarkerType.Diamond.displayName=Raute

MarkerType.FourDiamonds.displayName=Vier Rauten

MarkerType.Ellipse.displayName=Ellipse

MarkerType.SemiCircle.displayName=Halbkreis

MarkerType.Hexagon.displayName=Sechseck

MarkerType.Rectangle.displayName=Rechteck

MarkerType.Star.displayName=Stern

MarkerType.Column.displayName=Reihe

MarkerType.Cross.displayName=Kreuz

RiserType.Rectangle.displayName=Rechteck

RiserType.Triangle.displayName=Dreieck

RiserType.Tube.displayName=Röhre

RiserType.Cone.displayName=Kegel

Anchor.North.displayName=Oben

Anchor.NorthEast.displayName=Oben rechts

Anchor.East.displayName=Rechts

Anchor.SouthEast.displayName=Unten rechts

Anchor.South.displayName=Unten

Anchor.SouthWest.displayName=Unten links

Anchor.West.displayName=Links

Anchor.NorthWest.displayName=Oben links

AnchorVertical.North.displayName=Oben

AnchorVertical.South.displayName=Unten

AnchorVertical.West.displayName=Mitte

AnchorHorizontal.East.displayName=Rechts

AnchorHorizontal.South.displayName=Mitte

AnchorHorizontal.West.displayName=Nach-links

AutoScale.Exception.IsInfiite=\ ist unendlich

AutoScale.Exception.IsNaN=\ ist keine Zahl

AutoScale.ValueName.StepSize=Schrittgröße

Stretch.Horizontal.displayName=Horizontal

Stretch.Vertical.displayName=Vertikal

Stretch.Both.displayName=Beides

Orientation.Horizontal.displayName=Horizontal

Orientation.Vertical.displayName=Vertikal

Direction.LeftRight.displayName=Von links nach rechts

Direction.TopBottom.displayName=Von oben nach unten

LegendItemType.Series.displayName=Wert-Datenreihe

LegendItemType.Categories.displayName=Kategorien

Position.Above.displayName=Oben

Position.Below.displayName=Unten

Position.Left.displayName=Links

Position.Right.displayName=Rechts

Position.Inside.displayName=Innen

Position.Outside.displayName=Außen

UnitsOfMeasurement.Pixels.displayName=Pixel

UnitsOfMeasurement.Points.displayName=Punkte

UnitsOfMeasurement.Inches.displayName=Zoll

UnitsOfMeasurement.Centimeters.displayName=Zentimeter

DataType.Numeric.displayName=Numerisch

DataType.DateTime.displayName=DateTime
DataType.Text.displayName=Text

GroupingUnitType.Seconds.displayName=Sekunden

GroupingUnitType.Minutes.displayName=Minuten

GroupingUnitType.Hours.displayName=Stunden

GroupingUnitType.Days.displayName=Tage

GroupingUnitType.Weeks.displayName=Wochen

GroupingUnitType.Months.displayName=Monate

GroupingUnitType.Years.displayName=Jahre

GroupingUnitType.Quarters.displayName=Quartale

GroupingUnitType.String.displayName=Zeichenfolge

GroupingUnitType.StringPrefix.displayName=Zeichenfolge-Präfix

DateFormatType.Long.displayName=Lang

DateFormatType.Short.displayName=Kurz

DateFormatType.Medium.displayName=Mittel

DateFormatType.Full.displayName=Vollständig

DateFormatDetail.Date.displayName=Datum

DateFormatDetail.DateTime.displayName=Datum/Uhrzeit

ChartUtil.Text.Day='L'
ChartUtil.Text.Week='S'
DefaultValueProvider_BaseSeries=Basis-Datenreihe

DefaultValueProvider_ChartSubType.Standard=Standard

DefaultValueProvider_ChartSubType.StandardMeterChart=Standard-Tachometerdiagramm

DefaultValueProvider_ChartTitle=Diagrammtitel

DefaultValueProvider_ChartUnits.Points=Punkte

LegendBehaviorType.None.displayName=Keine

LegendBehaviorType.ToggleSerieVisibility.displayName=Sichtbarkeit der Datenreihe ein/aus

LegendBehaviorType.HighlightSerie.displayName=Datenreihe markieren

# Defines cursor display names.
Cursor.Auto.displayName=Automatisch

Cursor.Crosshair.displayName=Fadenkreuz

Cursor.Default.displayName=Standard

Cursor.Pointer.displayName=Hand

Cursor.Move.displayName=Verschieben

Cursor.Text.displayName=Text

Cursor.Wait.displayName=Warten

Cursor.EResize.displayName=Osten

Cursor.NEResize.displayName=Nordosten

Cursor.NWResize.displayName=Nordwesten

Cursor.NResize.displayName=Norden

Cursor.SEResize.displayName=Südosten

Cursor.SWResize.displayName=Südwesten

Cursor.SResize.displayName=Süden

Cursor.WResize.displayName=Westen

Cursor.Custom.displayName=Benutzerdefiniert

ActionType.URLRedirect.DisplayName=URL-Umleitung

ActionType.InvokeScript.DisplayName=Skript aufrufen

ActionType.Highlight.DisplayName=Markieren

ActionType.ToggleVisibility.DisplayName=Sichtbarkeit ein/aus

ActionType.ToggleDataPointVisibility.DisplayName=Datenpunkt-Sichtbarkeit ein/aus

# End of Attributes
##################################################
dataprocessor.log.baseSeriesDefn3=Kategorie-Datenreihendefinition ({0}) wird als statischer Ausdruck verwendet.

dataprocessor.exception.CannotDecipher=Inhalt eines Diagramms mit mehreren Kategorie-Datenreihendefinitionen kann nicht entschlüsselt werden.

dataprocessor.exception.FoundDefnAssociatedWithX={0} mit dem Kategorie-Datenreihenausdruck (X) verknüpfte Datendefinition(en) gefunden. Es wird nur eine Kategorie-Datenreihen-Datendefinition unterstützt.

dataprocessor.exception.DefinitionUnspecified=Es wurde keine Datendefinition für die Kategorie-Datenreihe angegeben.

dataprocessor.exception.DefnExpMustAssociateY=Ein Datendefinitionsausdruck muss mit der durch {1} definierten Wert-(Y)-Datenreihe-{0} verknüpft sein.

dataprocessor.exception.AtLeastOneDefnExpMustAssociateY=Mindestens ein Datendefinitionsausdruck muss mit der durch {1} definierten Wert-(Y)-Datenreihe-{0} verknüpft sein.

dataprocessor.exception.CannotDecipher2=Inhalt eines Diagramms mit mehreren Kategorie-Datenreihendefinitionen kann nicht entschlüsselt werden.

dataprocessor.log.XSeriesDefn=X-Datenreihendefinition ({0}) wird als statischer Ausdruck verwendet.

dataprocessor.exception.FoundMoreThanOneDefnAssociateX={0} mit dem Datenreihenausdruck (X) verknüpfte Datendefinition(en) gefunden. Es wird nur eine Datenreihen-Datendefinition für X unterstützt.

edataprocessor.xception.definitionsAssociatedWithX=Es wurde keine Datendefinition für die X-Datenreihe angegeben.

dataprocessor.log.baseSeriesDefnBeStatic=Kategorie-Datenreihendefinition ({0}) wird als statischer Ausdruck verwendet.

exception.data.max.row.count=Rendern eines Diagramms, das mehr als {0} Datenzeilen bindet, ist nicht möglich.


# Default chart title
BarChart.Title=Balkendiagrammtitel

LineChart.Title=Liniendiagrammtitel

AreaChart.Title=Flächendiagrammtitel

PieChart.Title=Kreisdiagrammtitel

MeterChart.Title=Tachometerdiagrammtitel

ScatterChart.Title=Punktdiagrammtitel

StockChart.Title=Kursdiagrammtitel

BubbleChart.Title=Blasendiagrammtitel

DifferenceChart.Title=Differenzdiagrammtitel

GanttChart.Title=Gantt-Diagrammtitel

TubeChart.Title=Röhrendiagrammtitel

PyramidChart.Title=Pyramidendiagrammtitel

ConeChart.Title=Kegeldiagrammtitel

RadarChart.Title=Radardiagrammtitel

ColumnChart.Title=Spaltendiagrammtitel

DoughnutChart.Title=Ringdiagrammtitel