###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive Data Source
newwizard.description=创建 BIRT Hive 连接配置文件

wizard.window.title=新建 Hive 数据源配置文件

wizard.data.source.page.title=新建 Hive 数据源

profile.propertypage.name=BIRT Hive Data Source Connection Properties
dataset.editor.page.query=HQL Query
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=新建数据集