###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive Data Source
newwizard.description=Crear un perfil de conexión Hive BIRT

wizard.window.title=Nuevo perfil de fuente de datos Hive

wizard.data.source.page.title=Nueva fuente de datos Hive

profile.propertypage.name=BIRT Hive Data Source Connection Properties
dataset.editor.page.query=HQL Query
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=Nuevo conjunto de datos