dataset.editor.page.query=Query

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive 数据源
newwizard.description=创建 BIRT Hive 连接配置文件
wizard.window.title=新建 Hive 数据源配置文件
wizard.data.source.page.title=新建 Hive 数据源
profile.propertypage.name=BIRT Hive 数据源连接属性
