dataset.editor.page.query=Query

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive-Datenquelle
newwizard.description=BIRT Hive-Verbindungsprofil erstellen
wizard.window.title=Neues Hive-Datenquellenprofil
wizard.data.source.page.title=Neue Hive-Datenquelle
profile.propertypage.name=BIRT Hive-Datenquellen-Verbindungseigenschaften
