###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hiveデータソース
newwizard.description=BIRT Hive の接続プロファイルの作成
wizard.window.title=Hiveデータソースプロファイルの新規作成
wizard.data.source.page.title=Hiveデータソースの新規作成
profile.propertypage.name=BIRT Hiveデータソース接続プロパティ
dataset.editor.page.query=HQL クエリ
