###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive Data Source
newwizard.description=BIRT Hive-Verbindungsprofil erstellen

wizard.window.title=Neues Hive-Datenquellenprofil

wizard.data.source.page.title=Neue Hive-Datenquelle

profile.propertypage.name=BIRT Hive Data Source Connection Properties
dataset.editor.page.query=HQL Query
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=Neuer Datensatz