###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive Data Source
newwizard.description=BIRT Hive 연결 프로필을 생성합니다.

wizard.window.title=새 Hive 데이터 원본 프로필

wizard.data.source.page.title=새 Hive 데이터 원본

profile.propertypage.name=BIRT Hive Data Source Connection Properties
dataset.editor.page.query=HQL Query
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=새 데이터 집합