dataset.editor.page.query=Query

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive データソース
newwizard.description=BIRT Hive の接続プロファイルの作成
wizard.window.title=Hive データソースプロファイルの新規作成
wizard.data.source.page.title=Hive データソースの新規作成
profile.propertypage.name=BIRT Hive データソース接続プロパティ
