###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Hive Designer
newwizard.name=BIRT Hive Data Source
newwizard.description=Créer un profil de connexion BIRT Hive

wizard.window.title=Nouveau profil de source de données Hive

wizard.data.source.page.title=Nouvelle source de données Hive

profile.propertypage.name=BIRT Hive Data Source Connection Properties
dataset.editor.page.query=HQL Query
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=Nouveau jeu de données