###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=Controlador ODA de POJO

Query.Closed=La consulta está cerrada.

Query.NoQueryText=El texto de consulta no está.

Query.FailedToParse=Error al analizar la consulta de POJO: [{0}].

Query.MissAttributeInElement=El atributo "{0}" está vacío o falta en un elemento "{1}".

Query.Miss2Elements=Los subelementos "{0}" y "{1}" no existen en el elemento "{2}".

Driver.UnkownDataTypeCode=Código de tipo de datos desconocido: {0}.

Driver.UnkownDataTypeName=Nombre de tipo de datos desconocido: {0}.

ResultSet.InvalidAppContextValue=El tipo de valor "{0}" AppContext es "{1}", no es matriz, iterador ni colección.

ResultSet.MissDataSetClassName=Falta el nombre de clase del conjunto de datos POJO.

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod=El tipo devuelto del método "next()" está vacío o es primitivo.

ReferenceGraph.DuplicateColumnName=Nombre de columna duplicado: {0}.

ReferenceGraph.DuplicateColumnIndex=Índice de columna duplicado: {0}.

ReferenceGraph.InexistentColumnName=Nombre de columna inexistente: {0}.

ResultSetFromPojoInstance.Invalid1ToNMaps=Hay dos asignaciones 1-a-n donde uno no es transición del otro.

QueryParameters.OneMethodParameterWith2Types=El parámetro de método "{0}" no puede aparecer con 2 tipos: "{1}", "{2}".

QueryParameters.InexistentParameter=Parámetro no existente: "{0}".

MethodSource.MissingPrameterValue=El valor del parámetro "{0}" aún no se ha definido.

DataTypeUtil.FailToTransferType=Error al transferir "{0}" al tipo de destino: {1}.

IllegalArgument.errorMessage=Argumento no válido definido para el método: