###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=POJO ODA 드라이버

Query.Closed=쿼리가 닫혔습니다.

Query.NoQueryText=쿼리 텍스트가 없습니다.

Query.FailedToParse=POJO 쿼리를 구문 분석하지 못했습니다: [{0}].

Query.MissAttributeInElement=특성 "{0}"이(가) 비어 있거나 "{1}" 요소에서 누락되었습니다.

Query.Miss2Elements="{2}" 요소에 "{0}" 또는 "{1}" 하위 요소가 모두 없습니다.

Driver.UnkownDataTypeCode=알 수 없는 데이터 형식 코드: {0}.

Driver.UnkownDataTypeName=알 수 없는 데이터 형식 이름: {0}.

ResultSet.InvalidAppContextValue=AppContext "{0}" 값의 형식은 "{1}"이며, 배열, 반복자 또는 컬렉션이 아닙니다.

ResultSet.MissDataSetClassName=POJO 데이터 집합 클래스 이름이 없습니다.

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod="next()" 메서드의 반환 형식은 void 또는 primitive입니다.

ReferenceGraph.DuplicateColumnName=중복된 열 이름: {0}.

ReferenceGraph.DuplicateColumnIndex=중복된 열 인덱스: {0}.

ReferenceGraph.InexistentColumnName=존재하지 않는 열 이름: {0}.

ResultSetFromPojoInstance.Invalid1ToNMaps=맵 간에 서로 전환되지 않는 일대다(1-to-n) 맵이 두 개 있습니다.

QueryParameters.OneMethodParameterWith2Types=메서드 매개 변수 "{0}"은(는) 다음 두 개의 형식일 수 없습니다: "{1}", "{2}".

QueryParameters.InexistentParameter=존재하지 않는 매개 변수: "{0}".

MethodSource.MissingPrameterValue=매개 변수 "{0}"의 값이 아직 설정되지 않았습니다.

DataTypeUtil.FailToTransferType="{0}"을(를) 대상 형식으로 전송하지 못했습니다: {1}.

IllegalArgument.errorMessage=메서드에 잘못된 인수가 정의되었습니다.