###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=POJO ODA ドライバ

Query.Closed=クエリは閉じています。

Query.NoQueryText=クエリテキストがありません。

Query.FailedToParse=POJO クエリを解析できません: [{0}]

Query.MissAttributeInElement=属性 "{0}" は、"{1}" 要素で空か、見つかりません。

Query.Miss2Elements="{0}" または "{1}" の下位要素が "{2}" 要素に存在しません。

Driver.UnkownDataTypeCode=データ型コードが不明です: {0}

Driver.UnkownDataTypeName=データ型名が不明です: {0}

ResultSet.InvalidAppContextValue=AppContext の型 "{0}" の値は "{1}" です。配列、反復子、またはコレクションではありません。

ResultSet.MissDataSetClassName=POJO データセットのクラス名が見つかりません。

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod="next()" メソッドの戻り値の型が無効か、またはプリミティブです。

ReferenceGraph.DuplicateColumnName=列名が重複しています: {0}

ReferenceGraph.DuplicateColumnIndex=列インデックスが重複しています: {0}

ReferenceGraph.InexistentColumnName=列名が存在しません: {0}

ResultSetFromPojoInstance.Invalid1ToNMaps=一方のマップからもう一方のマップが転送されていない複数マップが 2 つ存在します。

QueryParameters.OneMethodParameterWith2Types=メソッドパラメタ "{0}" に次の 2 つの型は使用できません: "{1}"、"{2}"

QueryParameters.InexistentParameter=パラメタが存在しません: "{0}"

MethodSource.MissingPrameterValue=パラメタ "{0}" の値が設定されていません。

DataTypeUtil.FailToTransferType="{0}" をターゲットの型に転送できません: {1}

IllegalArgument.errorMessage=メソッドに定義された引数が正しくありません: