###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=POJO ODA-Treiber

Query.Closed=Abfrage ist geschlossen.

Query.NoQueryText=Abfragetext fehlt.

Query.FailedToParse=Fehler bei Analyse von POJO-Abfrage: [{0}].

Query.MissAttributeInElement=Attribut '{0}' ist leer oder fehlt in einem Element '{1}'.

Query.Miss2Elements=Weder Unterelement '{0}' noch '{1}' in einem Element '{2}' vorhanden.

Driver.UnkownDataTypeCode=Unbekannter Datentypcode: {0}.

Driver.UnkownDataTypeName=Unbekannter Datentypname: {0}.

ResultSet.InvalidAppContextValue=Der Typ des Werts von AppContext '{0}' ist '{1}', nicht Array, Iteration oder Sammlung.

ResultSet.MissDataSetClassName=POJO-Datensatzklassenname fehlt.

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod=Der Ausgabetyp von Methode 'next()' ist ungültig oder primitiv.

ReferenceGraph.DuplicateColumnName=Doppelter Spaltenname: {0}.

ReferenceGraph.DuplicateColumnIndex=Doppelter Spaltenindex: {0}.

ReferenceGraph.InexistentColumnName=Nicht vorhandener Spaltenname: {0}.

ResultSetFromPojoInstance.Invalid1ToNMaps=Es sind zwei nicht vorübergehende 1-zu-n-Zuordnungen vorhanden.

QueryParameters.OneMethodParameterWith2Types=Methodenparameter '{0}' darf nicht 2 Typen haben: '{1}', '{2}'.

QueryParameters.InexistentParameter=Nicht vorhandener Parameter: '{0}'.

MethodSource.MissingPrameterValue=Parameterwert '{0}' wurde noch nicht festgelegt.

DataTypeUtil.FailToTransferType=Fehler bei Übertragung von '{0}' zum Zieltyp: {1}.

IllegalArgument.errorMessage=Unzulässiges Argument definiert für Methode: