###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=Pilote ODA POJO

Query.Closed=La requête est fermée.

Query.NoQueryText=Le texte de la requête est manquant.

Query.FailedToParse=Impossible d'analyser la requête POJO : [{0}].

Query.MissAttributeInElement=L'attribut "{0}" est vide ou manquant dans un élément "{1}".

Query.Miss2Elements=Aucun des sous-éléments "{0}" et "{1}" n'existe dans un élément "{2}".

Driver.UnkownDataTypeCode=Code de type de données inconnu : {0}.

Driver.UnkownDataTypeName=Nom de type de données inconnu : {0}.

ResultSet.InvalidAppContextValue=Le type de valeur AppContext "{0}" est "{1}" et non Tableau, Itérateur ou Collecte.

ResultSet.MissDataSetClassName=Le nom de la classe de jeu de données POJO est manquant.

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod=Le type de retour de la méthode "next()" est nul ou primitif.

ReferenceGraph.DuplicateColumnName=Nom de colonne en double : {0}.

ReferenceGraph.DuplicateColumnIndex=Index de colonne en double : {0}.

ReferenceGraph.InexistentColumnName=Nom de colonne inexistant : {0}.

ResultSetFromPojoInstance.Invalid1ToNMaps=Existe deux mappages 1 à x où l'un n'est pas en transition par rapport à l'autre.

QueryParameters.OneMethodParameterWith2Types=Le paramètre de méthode "{0}" ne peut comporter deux types : "{1}", "{2}".

QueryParameters.InexistentParameter=Paramètre inexistant : "{0}".

MethodSource.MissingPrameterValue=La valeur du paramètre "{0}" n'est pas encore définie.

DataTypeUtil.FailToTransferType=Impossible de transférer "{0}" vers le type cible : {1}.

IllegalArgument.errorMessage=L'argument défini est incorrect pour cette méthode :