# ==============================================================================
# Workbench Actions
# ==============================================================================

Workbench_title = BIRT Report Designer

# --- File Menu ---
Workbench_file = ファイル(&F)

Workbench_openFile = ファイルを開く(&O)...

Workbench_new = 新規(&N)

Action_newReport = レポートの新規作成(&R)...

Action_openReport = レポートを開く(&R)...

# --- Edit Menu ---
Workbench_edit = 編集(&E)

# --- Window Menu ---
Workbench_window = ウィンドウ(&W)

Workbench_openPerspective = パースペクティブを開く(&O)

Workbench_showView = ビューの表示(&V)

Workbench_openNewWindow = 新しいウィンドウを開く(&N)

# --- Help Menu ---
Workbench_help = ヘルプ(&H)

Action_newLibrary = ライブラリの新規作成(&L)...

Action_openLibrary = ライブラリを開く(&L)...

Action_newTemplate = テンプレートの新規作成(&T)...

Action_openTemplate = テンプレートを開く(&T)...

Dialog_openFile = ファイルを開く

SaveAsWizardWindowTitle=名前を付けて保存

SaveAsWizardPageTitle=名前を付けて保存

SaveAsWizardPageDesc=ファイルを別の場所に保存します。

ReportSettingPageTitle=ページのプロパティの設定
