# ==============================================================================
# Workbench Actions
# ==============================================================================

Workbench_title = BIRT Report Designer

# --- File Menu ---
Workbench_file = &Datei

Workbench_openFile = &Datei öffnen...

Workbench_new = &Neu

Action_newReport = &Neuer Bericht...

Action_openReport = &Bericht öffnen...

# --- Edit Menu ---
Workbench_edit = &Bearbeiten

# --- Window Menu ---
Workbench_window = &Fenster

Workbench_openPerspective = &Perspektive öffnen

Workbench_showView = Ansicht &anzeigen

Workbench_openNewWindow = &Neues Fenster

# --- Help Menu ---
Workbench_help = &Hilfe

Action_newLibrary = Neue &Bibliothek...

Action_openLibrary = Bibliothek &öffnen...

Action_newTemplate = Neue &Vorlage...

Action_openTemplate = Vorlage &öffnen...

Dialog_openFile = Datei öffnen

SaveAsWizardWindowTitle=Speichern unter

SaveAsWizardPageTitle=Speichern unter

SaveAsWizardPageDesc=Speichern Sie die Datei an einem anderen Ort.

ReportSettingPageTitle=Seiteneigenschaften festlegen
