# ==============================================================================
# Workbench Actions
# ==============================================================================

Workbench_title = BIRT Report Designer

# --- File Menu ---
Workbench_file = &Archivo

Workbench_openFile = &Abrir archivo...

Workbench_new = &Nuevo

Action_newReport = Nuevo &informe...

Action_openReport = Abrir &informe...

# --- Edit Menu ---
Workbench_edit = &Editar

# --- Window Menu ---
Workbench_window = Ve&ntana

Workbench_openPerspective = A&brir perspectiva

Workbench_showView = Mostrar &vista

Workbench_openNewWindow = &Nueva ventana

# --- Help Menu ---
Workbench_help = A&yuda

Action_newLibrary = Nueva &librería...

Action_openLibrary = Abrir &librería...

Action_newTemplate = Nueva &plantilla...

Action_openTemplate = Nueva &plantilla...

Dialog_openFile = Abrir archivo

SaveAsWizardWindowTitle=Guardar como

SaveAsWizardPageTitle=Guardar como

SaveAsWizardPageDesc=Guarde el archivo en otra ubicación.

ReportSettingPageTitle=Establecer propiedades de página
