###########################################################
#Primitive Charts
SideBySideBar=Gruppierte Balkendiagramme stellen Balken jeder Datenreihe nebeneinander dar. Die Balken sind so angeordnet, dass alle dieselbe Breite besitzen. Die Balkenbreite hängt von der Anzahl der abgebildeten Datenreihen ab.

StackedBar=Gestapelte Balkendiagramme stellen übereinander gestapelte Balken dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.

PercentStackedBar=Gestapelte Balkendiagramme (100 %) stellen übereinander gestapelte Balken dar, so dass die Gesamthöhe der gestapelten Balken (vom niedrigsten zum höchsten Punkt) stets 100 beträgt.

OverlayLine=Überlagerungs-Liniendiagramme stellen Linien aus jeder Datenreihe unabhängig voneinander dar. Die Linien verbinden dabei die Werte der jeweiligen Datenreihe.

StackedLine=Gestapelte Liniendiagramme stellen übereinander gestapelte Linien dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.

PercentStackedLine=Gestapelte Liniendiagramme (100 %) stellen übereinander gestapelte Linien dar, so dass die Gesamthöhe der gestapelten Linien (vom niedrigsten zum höchsten Punkt jeder Einheit) stets 100 beträgt.

OverlayArea=Überlagerte Flächendiagramme stellen Flächen aus jeder Datenreihe unabhängig voneinander dar. Die Flächen verbinden dabei die Werte der jeweiligen Datenreihe.

StackedArea=Gestapelte Flächendiagramme stellen übereinander gestapelte Flächen dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.

PercentStackedArea=Gestapelte Flächendiagramme (100 %) stellen übereinander gestapelte Flächen dar, so dass die Gesamthöhe der gestapelten Flächen (vom niedrigsten zum höchsten Punkt jeder Einheit) stets 100 beträgt.

Pie=Kreisdiagramme stellen Werte als Segmente eines Kreises dar. Die Größe des Segments ist proportional zum dargestellten Wert. Kreisdiagramme für mehrere Datenreihen werden mit mehreren Kreisen abgebildet, die jeweils für eine Datenreihe stehen.

StandardMeter=Standard-Tachometerdiagramme enthalten einen einzelnen Tachometer mit einem oder mehreren Bereichen. Der Hintergrund des Tachometers kann in Bereiche mit unterschiedlichen Farben unterteilt werden.

SuperImposedMeter=Übereinandergelagerte Tachometerdiagramme enthalten mehrere Tachometer mit identischen Bereichen. Die Tachometer überlappen sich, so dass innerhalb eines einzigen Bereichs mehrere Nadeln dargestellt werden können.

Scatter=In Punktdiagrammen sind die Werte entsprechend der Kategorie und der Datenwerte als Koordinaten angeordnet. Jeder Datenwert wird durch eine Markierung gekennzeichnet.

BarStickStock=Ein Barstick-Kursdiagramm enthält eine senkrechte Linie, an die zwei waagerechte Linien angefügt sind. Die obersten und untersten Punkte der senkrechten Linie entsprechen dem Höchst- und dem Tiefstwert der Aktie. Die beiden waagerechten Linien stellen Eröffnung- und Schlusswert dar.

CandleStickStock=Ein Candlestick-Kursdiagramm enthält ein Feld mit Linien, die an den Enden nach oben und nach unten erweitert sind. Die oberen und unteren Kanten des Felds stellen die Werte für den Eröffnungskurs und Schlusskurs dar. Die oberen und unteren Punkte der Linie repräsentieren die Höchst- und Tiefstwerte.

Bubble=Blasendiagramme sind eine Erweiterung von Punktdiagrammen und zeigen die Punkte als Blasen. Die Blasendurchmesser sind proportional zu einem dritten Datenwert neben den X- und Y-Koordinaten.

Difference=Differenz-Diagramme zeigen den Bereich zwischen zwei Linien, geben alle Datenreiheneigenschaften wieder und können auch einen negativen Bereich andersfarbig darstellen.

Gantt=Gantt-Diagramme werden zur Verfolgung der Dauer und des Fortschritts von Aufgaben verwendet. Dazu werden auf einer Y-Achse vom Typ 'Datum/Uhrzeit' Balken mit benutzerdefinierter Breite mit optionalen Start- und Endmarkierungen dargestellt. Jeder Balken ist durch Kategorie, Beschriftung für Aufgabe, Anfangs- und Endzeit definiert. Zur Verfolgung des Fortschritts geplanter Aufgaben etwa können mehrere Gantt-Reihen mit verschiedenen Breiten überlagert werden.

Tube=Röhrendiagramme sind ähnlich wie Balkendiagramme, wobei die Balken als Röhren dargestellt werden.

Cone=Kegeldiagramme sind ähnlich wie Balkendiagramme, wobei die Balken als Kegel dargestellt werden.

Pyramid=Pyramidendiagramme sind ähnlich wie Balkendiagramme, wobei die Balken als Pyramiden dargestellt werden.

Radar=Standardradardiagramme enthalten ein zirkuläres Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.

###########################################################
#3D Charts
Bar=Dreidimensionales gruppiertes Balkendiagramm.

Line=Dreidimensionales überlagertes Liniendiagramm.

Area=Dreidimensionales überlagertes Flächendiagramm.

Tube3D=Dreidimensionales gruppiertes Röhrendiagramm.

Cone3D=Dreidimensionales gruppiertes Kegeldiagramm.

Pyramid3D=Dreidimensionales gruppiertes Pyramidendiagramm.

###########################################################
#Combination Charts
BarAndLine=Kombinationsdiagramme aus Balken und Linien enthalten zwei Datenreihen. Diese verwenden denselben Kategoriewert.


###########################################################
#Formatted Charts
AxisLabelFormat=Geben Sie das Format für die Achsenbeschriftungen an: Y-Achse ($###,###) und X-Achse (dd/MM/yyyy). Darüber hinaus können die Benutzer die Farbe, die Schriftart, den Umriss und andere Attribute für die Beschriftung festlegen.

AxisTitleFormat=Sämtliche Beschriftungsattribute können auf den Achsentitel angewendet werden.

ColoredByCategorySeries=Legen Sie den Legendenelementtyp als Kategorie fest.

OpenJavaSourceAction.Text.Description=Java Source aus dem relevanten Verzeichnis öffnen

OpenJavaSourceAction.Text.ToolTip=Java Source öffnen

SaveXMLAction.MessageBox.Message=Die XML-Quelldatei ist im Verzeichnis bereits vorhanden.\nErsetzen?

SaveXMLAction.MessageBox.Text=XML-Quelldatei speichern

SaveXMLAction.Text.Description=XML-Quelldatei im angegebenen Verzeichnis speichern

SaveXMLAction.Text.ToolTip=XML-Quelldatei speichern

ColoredByValueSeries=Legen Sie den Legendenelementtyp als Datenreihe fest.

CurveFittingArea=Aktivieren Sie das Kurvenanpassungsattribut für Flächendatenreihen.

CurveFittingBar=Erstellen Sie eine Kurvenattributslinie für Balkendatenreihen.

CurveFittingLine=Das Kurvenanpassungsattribut für Liniendatenreihen aktivieren.

CurveFittingStock=Erstellen Sie eine Kurvenattributslinie für Kursdiagramm-Datenreihen.

LegendFormat=Die Legende kann links, rechts, oben und unten und innen positioniert werden. Die Client-Fläche befindet sich innerhalb der Legende. Sie enthält die Legendenelemente.

MarkerLine=Es kann eine Markierungslinie sowohl für die X-Achse als auch für die Y-Achse erstellt werden (nur für Diagrammtypen mit Achsen).

MarkerRange=Es kann ein Markierungsbereich sowohl für die X-Achse als auch für die Y-Achse erstellt werden (nur für Diagrammtypen mit Achsen).

MultiplePie=Ein einzelnes Kreisdiagramm enthält mehrere Kreisdiagramm-Datenreihen. Diese bilden eine Kreisgruppe, um den Wertevergleich darzustellen.

MDialSRegionMeter=Mehrere Nadeln in einem einzelnen Tachometer.

SDialSRegionMeter=Eine Nadel in einem einzelnen Tachometer.

PercentageValueFormat=Stellen Sie den Datenreihenwert als Prozentzahl dar.

PlotFormat=Geben Sie die Darstellung der Diagramm- und Client-Fläche an.

SeriesValueFormat=Geben Sie das Format für Wertedaten ($###,###.00) und Beschriftung der X-Achse (tt/MM/jjjj) an.

###########################################################
#Scripted Charts
AxisLabelScript=Mit beforeDrawAxisLabel() können die Benutzer Attribute für Achsen und Beschriftungen (Axis.getLabel()) bearbeiten.

AxisTitleScript=Mit beforeDrawAxisTitle() können die Benutzer Attribute für Achsen und Beschriftungen (Axis.getTitle()) bearbeiten.

BlockScript=Mit beforeDrawBlock() können die Benutzer Attribute für den Block (z. B. Diagramm, Titel, Legende) bearbeiten.

CurveFittingScript=Mit beforeDrawFittingCurve() können die Benutzer Attribute für CurveFitting bearbeiten.

DataPointLabelScript=Mit beforeDrawDataPointLabel() können die Benutzer Attribute für DataPointHints und Beschriftungen bearbeiten.

LegendScript=beforeDrawLegendItem() ermöglicht den Benutzern die Bearbeitung von Legendenelementen und Grenzenattributen.

MarkerLineScript=Mit beforeDrawMarkerLine() können die Benutzer Attribute für Achsen und die Markierungslinie bearbeiten.

MarkerRangeScript=Mit beforeDrawMarkerRange() können die Benutzer Attribute für Achsen und MarkerRange bearbeiten.

SeriesScript=Mit beforeDrawSeries() können die Benutzer Attribute für Datenreihen und ISeriesRenderer (BaseRenderer oder AxesRenderer) bearbeiten.

SeriesTitleScript=Mit beforeDrawSeriesTitle() können die Benutzer Attribute für Datenreihen und Beschriftungen (Series.getTitle()) bearbeiten. Das gilt nur für Kreisdiagramme.

###########################################################
#Data Operations
MinSlice=Der Benutzer hat die Möglichkeit, den Mindestwert (absolut oder in Prozent) für ein Segment anzugeben. Das Kreisdiagrammsegment kann ausgerückt dargestellt werden, indem ein Ausdruck für das Ausrückungsattribut festgelegt wird.

MultipleYAxes=Ein Diagramm kann mehr als eine Y-Achse enthalten.

MultipleYSeries=Ein Diagramm kann mehr als eine Y-Datenreihe (Wert) enthalten.

WorkingWithBIRTDataEngine=Ein Diagramm arbeitet mit ODA/DtE (BIRT-Datenengine), um gruppierte/aggregierte Daten abzurufen, ohne selbst zu gruppieren/aggregieren.

###########################################################
#Default
DefaultDescription=Wählen Sie ein Beispiel aus den Kategorien aus.

###########################################################
#Example View labels
ChartExamples.Description=Beschreibung

ChartExamples.Preview=Vorschau

ChartExamples.SelectExamples=Beispiele auswählen

############################################################
#Category Names
SampleChartCategory.PrimitiveCharts=Primitive Diagramme

SampleChartCategory.3DCharts=3D-Diagramme

SampleChartCategory.CombinationCharts=Kombinationsdiagramme

SampleChartCategory.FormattedCharts=Formatierte Diagramme

SampleChartCategory.ScriptedCharts=Geskriptete Diagramme

SampleChartCategory.DataOperations=Datenvorgänge
#Sample Chart Names
#Primitive Charts
SampleChartName.SideBySideBar=Gruppierte Balken

SampleChartName.StackedBar=Stapelbalken

SampleChartName.PercentStackedBar=Stapelbalken (prozentual)

SampleChartName.OverlayLine=Überlagerungslinie

SampleChartName.StackedLine=Stapellinie

SampleChartName.PercentStackedLine=Stapellinie (prozentual)

SampleChartName.OverlayArea=Überlagerte Fläche

SampleChartName.StackedArea=Stapelfläche

SampleChartName.PercentStackedArea=Stapelfläche (prozentual)

SampleChartName.Pie=Kreis

SampleChartName.StandardMeter=Standard-Tachometer

SampleChartName.SuperImposedMeter=Überlagertes Tachometer

SampleChartName.Scatter=Punkt

SampleChartName.BarStickStock=Balken-Kurs

SampleChartName.CandleStickStock=Candlestick-Kurs

SampleChartName.Bubble=Blasen

SampleChartName.Difference=Differenz

SampleChartName.Gantt=Gantt

SampleChartName.Tube=Röhre

SampleChartName.Cone=Kegel

SampleChartName.Pyramid=Pyramide

SampleChartName.Radar=Radar
#3D Charts
SampleChartName.Bar=Balken

SampleChartName.Line=Linie

SampleChartName.Area=Fläche

SampleChartName.Tube3D=Röhre

SampleChartName.Cone3D=Kegel

SampleChartName.Pyramid3D=Pyramide
#Combination Charts
SampleChartName.BarAndLine=Balken und Linien
#Formatted Charts
SampleChartName.AxisLabelFormat=Formatierung für Achsenbeschriftung

SampleChartName.AxisTitleFormat=Formatierung für Achsentitel

SampleChartName.ColoredByCategorySeries=Färbung nach Kategorie-Datenreihe

SampleChartName.ColoredByValueSeries=Färbung nach Wert-Datenreihe

SampleChartName.CurveFittingArea=Kurvenanpassung für Fläche

SampleChartName.CurveFittingBar=Kurvenanpassung für Balken

SampleChartName.CurveFittingLine=Kurvenanpassung für Linie

SampleChartName.CurveFittingStock=Kurvenanpassung für Kurs

SampleChartName.LegendFormat=Formatierung für Legende

SampleChartName.MarkerLine=Markierungslinie

SampleChartName.MarkerRange=Markierungsbereich

SampleChartName.MultiplePie=Mehrere Kreisdiagramme

SampleChartName.MDialSRegionMeter=Tachometer, mehrere Zeiger, eine Region

SampleChartName.SDialSRegionMeter=Tachometer, ein Zeiger, eine Region

SampleChartName.PercentageValueFormat=Prozentzahlformat

SampleChartName.PlotFormat=Formatierung für Zeichnung

SampleChartName.SeriesValueFormat=Formatierung für Datenreihenwert
#Scripted Charts
SampleChartName.AxisLabelScript=Achsenbeschriftungsskript

SampleChartName.AxisTitleScript=Achsentitelskript

SampleChartName.BlockScript=Blockskript

SampleChartName.CurveFittingScript=Kurvenanpassungsskript

SampleChartName.DataPointLabelScript=Datenpunktbeschriftungsskript

SampleChartName.LegendScript=Legendenskript

SampleChartName.MarkerLineScript=Markierungslinienskript

SampleChartName.MarkerRangeScript=Markierungsbereichskript

SampleChartName.SeriesScript=Datenreihenskript

SampleChartName.SeriesTitleScript=Datenreihentitelskript
#Data Operations
SampleChartName.MinSlice=Mindestgröße für Segment

SampleChartName.MultipleYAxes=Mehrere Y-Achsen

SampleChartName.MultipleYSeries=Mehrere Y-Datenreihen

SampleChartName.WorkingWithBIRTDataEngine=Verwenden der BIRT-Datenengine


