###########################################################
#Primitive Charts

SideBySideBar=Gruppierte Balkendiagramme stellen Balken jeder Datenreihe nebeneinander dar. Die Balken sind so angeordnet, dass alle dieselbe Breite besitzen. Die Balkenbreite hängt von der Anzahl der abgebildeten Datenreihen ab.
StackedBar=Gestapelte Balkendiagramme stellen übereinander gestapelte Balken dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.
PercentStackedBar=Gestapelte Balkendiagramme (100 %) stellen übereinander gestapelte Balken dar, so dass die Gesamthöhe der gestapelten Balken (vom niedrigsten zum höchsten Punkt) stets 100 beträgt.
OverlayLine=Überlagerungs-Liniendiagramme stellen Linien aus jeder Datenreihe unabhängig voneinander dar. Die Linien verbinden dabei die Werte der jeweiligen Datenreihe.
StackedLine=Gestapelte Liniendiagramme stellen übereinander gestapelte Linien dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.
PercentStackedLine=Gestapelte Liniendiagramme (100 %) stellen übereinander gestapelte Linien dar, so dass die Gesamthöhe der gestapelten Linien (vom niedrigsten zum höchsten Punkt jeder Einheit) stets 100 beträgt.
OverlayArea=Überlagerte Flächendiagramme stellen Flächen aus jeder Datenreihe unabhängig voneinander dar. Die Flächen verbinden dabei die Werte der jeweiligen Datenreihe.
StackedArea=Gestapelte Flächendiagramme stellen übereinander gestapelte Flächen dar. Positive und negative Werte werden separat über bzw. unter dem Ursprung gestapelt.
PercentStackedArea=Gestapelte Flächendiagramme (100 %) stellen übereinander gestapelte Flächen dar, so dass die Gesamthöhe der gestapelten Flächen (vom niedrigsten zum höchsten Punkt jeder Einheit) stets 100 beträgt.
Pie=Kreisdiagramme stellen Werte als Segmente eines Kreises dar. Die Größe des Segments ist proportional zum dargestellten Wert. Kreisdiagramme für mehrere Datenreihen werden mit mehreren Kreisen abgebildet, die jeweils für eine Datenreihe stehen.
StandardMeter=Standard-Tachometerdiagramme enthalten einen einzelnen Tachometer mit einem oder mehreren Bereichen. Der Hintergrund des Tachometers kann in Bereiche mit unterschiedlichen Farben unterteilt werden.
SuperImposedMeter=Übereinandergelagerte Tachometerdiagramme enthalten mehrere Tachometer mit identischen Bereichen. Die Tachometer überlappen sich, so dass innerhalb eines einzigen Bereichs mehrere Nadeln dargestellt werden können.
Scatter=In Punktdiagrammen sind die Werte entsprechend der Kategorie und der Datenwerte als Koordinaten angeordnet. Jeder Datenwert wird durch eine Markierung gekennzeichnet.
BarStickStock=Ein Balken-Kursdiagramm enthält eine vertikale Linie mit zwei daran angefügten horizontalen Linien. Die oberen und die unteren Punkte der vertikalen Linie stellen die Eröffnungs- und Schlusswerte dar. Die beiden horizontalen Linien repräsentieren die Höchst- und Tiefstwerte.
CandleStickStock=Ein Candlestick-Kursdiagramm enthält ein Feld mit Linien, die an den Enden nach oben und nach unten erweitert sind. Die oberen und unteren Kanten des Felds stellen die Werte für den Eröffnungskurs und Schlusskurs dar. Die oberen und unteren Punkte der Linie repräsentieren die Höchst- und Tiefstwerte. 

###########################################################
#3D Charts

Bar=Dreidimensionales gruppiertes Balkendiagramm.
Line=Dreidimensionales überlagertes Liniendiagramm.
Area=Dreidimensionales überlagertes Flächendiagramm.

###########################################################
#Combination Charts

BarAndLine=Kombinationsdiagramme aus Balken und Linien enthalten zwei Datenreihen. Diese verwenden denselben Kategoriewert.


###########################################################
#Formatted Charts

AxisLabelFormat=Geben Sie das Format für die Achsenbeschriftungen an: Y-Achse ($###,###) und X-Achse (dd/MM/yyyy). Darüber hinaus können die Benutzer die Farbe, die Schriftart, den Umriss und andere Attribute für die Beschriftung festlegen.
AxisTitleFormat=Sämtliche Beschriftungsattribute können auf den Achsentitel angewendet werden.
ColoredByCategorySeries=Legen Sie den Legendenelementtyp als Kategorie fest.
OpenJavaSourceAction.Text.Description=Open Java Source from the relevant directory
OpenJavaSourceAction.Text.ToolTip=Open Java Source
SaveXMLAction.MessageBox.Message=The XML source already exists in the directory. \nDo you want to replace it?
SaveXMLAction.MessageBox.Text=Save XML Source
SaveXMLAction.Text.Description=Save XML Source to the designated directory
SaveXMLAction.Text.ToolTip=Save XML Source
ColoredByValueSeries=Legen Sie den Legendenelementtyp als Datenreihe fest.
CurveFittingArea=Aktivieren Sie das Kurvenanpassungsattribut für Flächendatenreihen.
CurveFittingBar=Erstellen Sie eine Kurvenattributslinie für Balkendatenreihen.
CurveFittingLine=Aktivieren Sie das Kurvenanpassungsattribut für Flächendatenreihen.
CurveFittingStock=Erstellen Sie eine Kurvenattributslinie für Kursdiagramm-Datenreihen.
LegendFormat=Die Legende kann links, rechts, oben und unten und innen positioniert werden. Die Client-Fläche befindet sich innerhalb der Legende. Sie enthält die Legendenelemente.
MarkerLine=Es kann eine Markierungslinie sowohl für die X-Achse als auch für die Y-Achse erstellt werden (nur für Diagrammtypen mit Achsen).
MarkerRange=Es kann ein Markierungsbereich sowohl für die X-Achse als auch für die Y-Achse erstellt werden (nur für Diagrammtypen mit Achsen).
MultiplePie=Ein einzelnes Kreisdiagramm enthält mehrere Kreisdiagramm-Datenreihen. Diese bilden eine Kreisgruppe, um den Wertevergleich darzustellen.
MDialSRegionMeter=Mehrere Nadeln in einem einzelnen Tachometer.
SDialSRegionMeter=Eine Nadel in einem einzelnen Tachometer.
PercentageValueFormat=Stellen Sie den Datenreihenwert als Prozentzahl dar.
PlotFormat=Geben Sie die Darstellung der Diagramm- und Client-Fläche an.
SeriesValueFormat=Geben Sie das Format für Wertedaten ($###,###.00) und Kategoriedaten (dd/MM/yyyy) an.

###########################################################
#Scripted Charts

AxisLabelScript=Mit beforeDrawAxisLabel() können die Benutzer Attribute für Achsen und Beschriftungen (Axis.getLabel()) bearbeiten.
AxisTitleScript=Mit beforeDrawAxisTitle() können die Benutzer Attribute für Achsen und Beschriftungen (Axis.getTitle()) bearbeiten.
BlockScript=Mit beforeDrawBlock() können die Benutzer Attribute für den Block (z. B. Diagramm, Titel, Legende) bearbeiten.
CurveFittingScript=Mit beforeDrawFittingCurve() können die Benutzer Attribute für CurveFitting bearbeiten.
DataPointLabelScript=Mit beforeDrawDataPointLabel() können die Benutzer Attribute für DataPointHints und Beschriftungen bearbeiten.
LegendScript=Mit beforeDrawLegendEntry() können die Benutzer Attribute für Beschriftungen (für die jeweilige Legende) bearbeiten.
MarkerLineScript=Mit beforeDrawMarkerLine() können die Benutzer Attribute für Achsen und die Markierungslinie bearbeiten.
MarkerRangeScript=Mit beforeDrawMarkerRange() können die Benutzer Attribute für Achsen und MarkerRange bearbeiten.
SeriesScript=Mit beforeDrawSeries() können die Benutzer Attribute für Datenreihen und ISeriesRenderer (BaseRenderer oder AxesRenderer) bearbeiten.
SeriesTitleScript=Mit beforeDrawSeriesTitle() können die Benutzer Attribute für Datenreihen und Beschriftungen (Series.getTitle()) bearbeiten. Das gilt nur für Kreisdiagramme.

###########################################################
#Data Operations

MinSlice=Der Benutzer hat die Möglichkeit, den Mindestwert (absolut oder in Prozent) für ein Segment anzugeben. Das Kreisdiagrammsegment kann ausgerückt dargestellt werden, indem ein Ausdruck für das Ausrückungsattribut festgelegt wird.
MultipleYAxes=Ein Diagramm kann mehr als eine Y-Achse enthalten.
MultipleYSeries=Ein Diagramm kann mehr als eine Y-Datenreihe (Wert) enthalten. 

###########################################################
#Default
DefaultDescription=Wählen Sie ein Beispiel aus den Kategorien aus.

###########################################################
#Example View labels
ChartExamples.Description=Description
ChartExamples.Preview=Preview
ChartExamples.SelectExamples=Select Examples
