###########################################################
#Primitive Charts
SideBySideBar=Los diagramas de barras laterales muestran barras de cada serie una junto a la otra. Estas barras se organizan para que tengan el mismo ancho, según el número de series que se vaya a procesar.

StackedBar=Los diagramas de barras apiladas muestran las barras apiladas una sobre la otra. Los valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

PercentStackedBar=Los diagramas de barras apiladas de porcentaje muestran barras apiladas una sobre la otra de forma que la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

OverlayLine=Los diagramas de líneas superpuestas muestran las líneas de cada serie por separado. Las líneas se muestran vinculando los valores de la serie.

StackedLine=Los diagramas de líneas apiladas muestran las líneas apiladas una sobre la otra. Los valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

PercentStackedLine=Los diagramas de líneas apiladas de porcentaje muestran las líneas apiladas una sobre la otra de forma que la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

OverlayArea=Los diagramas de áreas superpuestas muestran las áreas de cada serie por separado. Las áreas se muestran vinculando los valores de la serie.

StackedArea=Los diagramas de áreas apiladas muestran las áreas apiladas una sobre la otra. Los valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

PercentStackedArea=Los diagramas de áreas apiladas de porcentaje muestran las áreas apiladas una sobre la otra de forma que la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

Pie=Los diagramas circulares muestran los valores como cortes de un círculo. El tamaño de cada corte es proporcional al valor que representa. Los diagramas circulares de varias series se dibujan como múltiples círculos, uno para cada serie.

StandardMeter=Los diagramas métricos estándar presentan un solo cuadrante con una o varias regiones. El fondo del cuadrante puede dividirse en varias regiones con diferentes colores.

SuperImposedMeter=Los diagramas métricos superpuestos contienen varios cuadrantes con idénticas regiones. Los cuadrantes se superponen, por lo que pueden presentar múltiples indicadores dentro de una misma región.

Scatter=Los diagramas de dispersión organizan los valores en el dibujo usando los datos de categoría y de valor como coordenadas. Cada valor de datos se indica con un marcador.

BarStickStock=Un diagrama de cotización contiene una línea vertical con dos líneas horizontales adjuntadas a él. Los puntos superior e inferior de la línea vertical son los valores máximo y mínimo de la cotización. Las dos líneas horizontales son los valores de apertura y de cierre.

CandleStickStock=Un diagrama de cotización de velas contiene un cuadro con líneas que se extienden hacia arriba y hacia abajo de los extremos. Los bordes superior e inferior del cuadro son los valores de cotización de apertura y cierre. Los puntos superior e inferior de la línea son los valores máximo y mínimo.

Bubble=Los diagramas de burbujas son una extensión de los diagramas de dispersión y muestran los puntos como burbujas. Los diámetros de las burbujas son proporcionales a un tercer valor de datos, junto a las coordenadas x e y.

Difference=Los diagramas de diferencia muestran el área entre dos líneas de valores. Heredan todas las propiedades de serie de área y pueden mostrar, además, un área negativa en un color diferente.

Gantt=Los diagramas de Gantt se utilizan para seguir la duración y el progreso de las tareas. Se representan en un eje Y de fecha y hora, con barras de una anchura personalizada con marcadores de inicio y finalización opcionales. Cada barra se define por su categoría, etiqueta de tarea y hora de inicio y de finalización. Se pueden superponer varias series de Gantt de diferente anchura para seguir, por ejemplo, el progreso real de tareas programadas.

Tube=Los diagramas de tubos se parecen a los diagramas de barras, pero con las barras representadas como tubos.

Cone=Los diagramas de conos se parecen a los diagramas de barras, pero con las barras representadas como conos.

Pyramid=Los diagramas de pirámides se parecen a los diagramas de barras, pero con las barras representadas como pirámides.

Radar=Los diagramas radiales estándar contienen una cuadrícula circular a la que se superponen series de líneas o polígonos.

###########################################################
#3D Charts
Bar=Diagramas de barras laterales en 3 dimensiones.

Line=Diagramas de líneas superpuestas en 3 dimensiones.

Area=Diagramas de áreas superpuestas en 3 dimensiones.

Tube3D=Diagrama de tubos laterales en 3 dimensiones.

Cone3D=Diagrama de conos laterales en 3 dimensiones.

Pyramid3D=Diagrama de pirámides laterales en 3 dimensiones.

###########################################################
#Combination Charts
BarAndLine=Los diagramas de combinación de barras y líneas contienen 2 series. Comparten el mismo valor de categoría.


###########################################################
#Formatted Charts
AxisLabelFormat=Especifique el formato para etiquetas de eje: eje Y ($###,###) y eje X (MM/dd/yyyy). Los usuarios también han podido establecer el color, fuente, contorno y otros atributos de las etiquetas.

AxisTitleFormat=Todos los atributos de etiqueta se pueden aplicar al título del eje.

ColoredByCategorySeries=Establezca Tipo de elemento de leyenda como categoría.

OpenJavaSourceAction.Text.Description=Abrir fuente Java en el directorio relevante

OpenJavaSourceAction.Text.ToolTip=Abrir fuente Java

SaveXMLAction.MessageBox.Message=La fuente XML ya existe en el directorio. \n¿Desea sustituirla?

SaveXMLAction.MessageBox.Text=Guardar fuente XML

SaveXMLAction.Text.Description=Guardar fuente XML en el directorio designado

SaveXMLAction.Text.ToolTip=Guardar fuente XML

ColoredByValueSeries=Establezca Tipo de elemento de leyenda como serie.

CurveFittingArea=Active atributo de la curva ajustada de la serie de áreas.

CurveFittingBar=Cree una curva ajustada a línea para la serie de barras.

CurveFittingLine=Active atributo de la curva ajustada de la serie de líneas.

CurveFittingStock=Cree una curva ajustada a línea para la serie de cotización de acciones.

LegendFormat=La leyenda se puede situar a la izquierda, derecha, arriba, abajo y en el interior. El área del cliente se encuentra dentro de la leyenda. Contiene los elementos de leyenda.

MarkerLine=La línea de marcador se puede crear para los ejes X e Y (sólo para el tipo ChartWithAxes).

MarkerRange=El intervalo de marcador se puede crear para los ejes X e Y (sólo para el tipo ChartWithAxes).

MultiplePie=Un diagrama circular individual contiene varias series circulares que pueden formar un grupo circular para presentar la comparación de valores.

MDialSRegionMeter=Múltiples indicadores en un tablón de cuadrante individual.

SDialSRegionMeter=Un indicador en un tablón de cuadrante individual.

PercentageValueFormat=Presente el valor de serie como una figura de porcentaje.

PlotFormat=Especifique la apariencia de un área de dibujo y del cliente.

SeriesValueFormat=Especifique el formato de los datos de valor ($###,###.00) y etiqueta del eje X (MM/dd/aaaa).

###########################################################
#Scripted Charts
AxisLabelScript=beforeDrawAxisLabel() permite a los usuarios manipular atributos de eje y etiqueta (Axis.getLabel()).

AxisTitleScript=beforeDrawAxisTitle() permite a los usuarios manipular atributos de eje y etiqueta (Axis.getTitle()).

BlockScript=beforeDrawBlock() permite a los usuarios manipular atributos de bloque (p. ej., dibujo, título, leyenda).

CurveFittingScript=beforeDrawFittingCurve() permite a los usuarios manipular atributos de curva ajustada.

DataPointLabelScript=beforeDrawDataPointLabel() permite a los usuarios manipular atributos de etiqueta y DataPointHints.

LegendScript=beforeDrawLegendItem() permite a los usuarios manipular elementos de leyenda y delimitar atributos.

MarkerLineScript=beforeDrawMarkerLine() permite a los usuarios manipular atributos de línea de marcador.

MarkerRangeScript=beforeDrawMarkerRange() permite a los usuarios manipular atributos de intervalo de marcador.

SeriesScript=beforeDrawSeries() permite a los usuarios manipular atributos de serie y ISeriesRenderer (BaseRenderer o AxesRenderer).

SeriesTitleScript=beforeDrawSeriesTitle() permite a los usuarios manipular atributos de serie y etiqueta (Series.getTitle()). Sólo se aplica al diagrama circular.

###########################################################
#Data Operations
MinSlice=El usuario puede especificar el valor mínimo (absoluto o porcentaje) de un corte. El diagrama circular se puede separar estableciendo la expresión en atributo de separación.

MultipleYAxes=Un diagrama puede contener más de un eje Y.

MultipleYSeries=Un diagrama puede contener más de una serie Y (valor).

WorkingWithBIRTDataEngine=Un diagrama funciona con ODA/DtE (motor de datos BIRT) para obtener datos agrupados/agregados sin realizar la agrupación/agregación por el propio diagrama.

###########################################################
#Default
DefaultDescription=Seleccione un ejemplo entre las categorías.

###########################################################
#Example View labels
ChartExamples.Description=Descripción

ChartExamples.Preview=Vista previa

ChartExamples.SelectExamples=Seleccionar Ejemplos

############################################################
#Category Names
SampleChartCategory.PrimitiveCharts=Diagramas originales

SampleChartCategory.3DCharts=Diagramas 3D

SampleChartCategory.CombinationCharts=Diagramas combinados

SampleChartCategory.FormattedCharts=Diagramas con formato

SampleChartCategory.ScriptedCharts=Diagramas en script

SampleChartCategory.DataOperations=Operaciones de datos
#Sample Chart Names
#Primitive Charts
SampleChartName.SideBySideBar=Barra lateral

SampleChartName.StackedBar=Barra apilada

SampleChartName.PercentStackedBar=Barra apilada de porcentaje

SampleChartName.OverlayLine=Línea vertical

SampleChartName.StackedLine=Línea apilada

SampleChartName.PercentStackedLine=Línea apilada de porcentaje

SampleChartName.OverlayArea=Área superpuesta

SampleChartName.StackedArea=Área apilada

SampleChartName.PercentStackedArea=Área apilada de porcentaje

SampleChartName.Pie=Circular

SampleChartName.StandardMeter=Métrico estándar

SampleChartName.SuperImposedMeter=Métrico superpuesto

SampleChartName.Scatter=Dispersión

SampleChartName.BarStickStock=Cotización de barras

SampleChartName.CandleStickStock=Cotización de recuadros

SampleChartName.Bubble=Burbuja

SampleChartName.Difference=Diferencia

SampleChartName.Gantt=Gantt

SampleChartName.Tube=Tubo

SampleChartName.Cone=Cono

SampleChartName.Pyramid=Pirámide

SampleChartName.Radar=Radial
#3D Charts
SampleChartName.Bar=Barra

SampleChartName.Line=Línea

SampleChartName.Area=Área

SampleChartName.Tube3D=Tubo

SampleChartName.Cone3D=Cono

SampleChartName.Pyramid3D=Pirámide
#Combination Charts
SampleChartName.BarAndLine=Barras y líneas
#Formatted Charts
SampleChartName.AxisLabelFormat=Formato de etiquetas de eje

SampleChartName.AxisTitleFormat=Formato de título de eje

SampleChartName.ColoredByCategorySeries=Color por series de categoría

SampleChartName.ColoredByValueSeries=Color por series de valor

SampleChartName.CurveFittingArea=Curva ajustada al área

SampleChartName.CurveFittingBar=Curva ajustada a la barra

SampleChartName.CurveFittingLine=Curva ajustada a la línea

SampleChartName.CurveFittingStock=Curva ajustada a cotización

SampleChartName.LegendFormat=Formato de la leyenda

SampleChartName.MarkerLine=Línea de marcador

SampleChartName.MarkerRange=Intervalo de marcador

SampleChartName.MultiplePie=Circular múltiple

SampleChartName.MDialSRegionMeter=Indicadores múltiples en el tablón del cuadrante individual

SampleChartName.SDialSRegionMeter=Indicador único en el tablón del cuadrante individual

SampleChartName.PercentageValueFormat=Formato del valor del porcentaje

SampleChartName.PlotFormat=Formato del dibujo

SampleChartName.SeriesValueFormat=Formato del valor de la serie
#Scripted Charts
SampleChartName.AxisLabelScript=Script de la etiqueta del eje

SampleChartName.AxisTitleScript=Script del título del eje

SampleChartName.BlockScript=Script del bloque

SampleChartName.CurveFittingScript=Curva ajustada al script

SampleChartName.DataPointLabelScript=Script de la etiqueta del punto de datos

SampleChartName.LegendScript=Script de la leyenda

SampleChartName.MarkerLineScript=Script de la línea del marcador

SampleChartName.MarkerRangeScript=Script del intervalo del marcador

SampleChartName.SeriesScript=Script de las series

SampleChartName.SeriesTitleScript=Script del título de la serie
#Data Operations
SampleChartName.MinSlice=Corte mínimo

SampleChartName.MultipleYAxes=Varios ejes Y

SampleChartName.MultipleYSeries=Varias series Y

SampleChartName.WorkingWithBIRTDataEngine=Trabajo con motor de datos BIRT


