###########################################################
#Primitive Charts
SideBySideBar=Les graphiques à barres côte à côte affichent les barres de chaque série l'une à côté de l'autre. Ces barres sont arrangées de sorte qu'elles aient la même largeur. La largeur des barres dépend du nombre de séries tracées.

StackedBar=Les graphiques à barres empilées affichent des barres les unes sur les autres. Les valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

PercentStackedBar=Les graphiques à barres empilées à pourcentage affichent les barres empilées les unes sur les autres, de sorte que la hauteur totale des barres empilées (du point le plus bas au point le plus haut) atteigne 100.

OverlayLine=Les graphiques à lignes superposées affichent les lignes de chaque série indépendamment des autres. Les lignes regroupent les valeurs pour la série.

StackedLine=Les graphiques de lignes empilées affichent des lignes les unes sur les autres. Les valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

PercentStackedLine=Les graphiques de lignes empilées à pourcentage affichent des lignes empilées les unes sur les autres de telle manière que la hauteur totale des lignes (du point le plus bas au point le plus haut dans chaque unité) représente 100.

OverlayArea=Les graphiques en aires superposées affichent les aires de chaque série indépendamment des autres. Les aires regroupent les valeurs pour la série.

StackedArea=Les graphiques en aires empilées affichent des aires les unes sur les autres. Les valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

PercentStackedArea=Les graphiques en aires empilées à pourcentage affichent des aires empilées les unes sur les autres de telle manière que la hauteur totale des aires (du point le plus bas au point le plus haut dans chaque unité) représente 100.

Pie=Les graphiques à secteurs affichent les valeurs sous la forme de tranches de secteur. La taille de chaque tranche est proportionnelle à la valeur qu'elle représente. Les graphiques à secteurs pour séries multiples sont tracés sous la forme de secteurs multiples, un secteur par série.

StandardMeter=Les graphiques à cadrans standard contiennent un seul cadran par zone(s). L'arrière-plan du cadran peut être divisé en zones de différentes couleurs.

SuperImposedMeter=Les graphiques à cadrans superposés contiennent plusieurs cadrans avec des zones identiques. Les cadrans se chevauchent afin que plusieurs aiguilles apparaissent dans une même zone.

Scatter=Les graphiques en nuage de points affichent les valeurs disposées sur le tracé en utilisant les données de catégorie et de valeur comme coordonnées. Chaque valeur de données est indiquée par un repère.

BarStickStock=Un graphique boursier à barres contient une ligne verticale reliée à deux lignes horizontales. Les points supérieur et inférieur de la ligne verticale correspondent à la valeur boursière la plus élevée et la plus basse. Les deux lignes horizontales correspondent aux valeurs d'ouverture et de fermeture.

CandleStickStock=Un graphique boursier en chandelier se présente sous la forme d'un cadre dont les côtés sont joints par des courbes. Les coins supérieurs et inférieurs du cadre correspondent aux valeurs d'ouverture et de fermeture. Les points supérieur et inférieur de la ligne correspondent à la valeur la plus élevée et la plus basse.

Bubble=Les graphiques à bulles sont une extension des graphiques à nuages de points : les points sont simplement remplacés par des bulles. Le diamètre des bulles correspond au tiers de la valeur des données et ne correspond en rien à l'abscisse et à l'ordonnée.

Difference=Les graphiques de différence représentent l'aire comprise entre deux lignes de valeurs. Ils héritent de toutes les propriétés des séries d'aires et peuvent également représenter une aire négative, à l'aide d'une couleur différente.

Gantt=Les graphiques de Gantt sont utilisés pour suivre la durée et la progression des tâches. Elle sont représentées sur un axe vertical dateheure, à l'aide de barres ayant une largeur personnalisée et des repères de début et de fin (en option). Chaque barre est définie par sa catégorie, son étiquette de tâches, son heure de début et son heure de fin. Il est possible de superposer plusieurs séries Gantt de différentes largeurs, par exemple, pour suivre le progrès réel des tâches planifiées.

Tube=Les graphiques à cylindres ressemblent aux graphiques à barres, au détail près que les barres sont représentées par des cylindres.

Cone=Les graphiques à cônes ressemblent aux graphiques à barres, au détail près que les barres sont représentées par des cônes.

Pyramid=Les graphiques à pyramides ressemblent aux graphiques à barres, au détail près que les barres sont représentées par des pyramides.

Radar=Les graphiques en radar standard contiennent une grille circulaire superposée à un(e) ou plusieurs polygones/lignes de série.

###########################################################
#3D Charts
Bar=Graphique à barres côte à côte en 3 dimensions.

Line=Graphique à lignes superposées en 3 dimensions.

Area=Graphique en aires superposées en 3 dimensions.

Tube3D=Graphique à cylindres côte à côte en 3 dimensions.

Cone3D=Graphique à cônes côte à côte en 3 dimensions.

Pyramid3D=Graphique à pyramides côte à côte en 3 dimensions.

###########################################################
#Combination Charts
BarAndLine=Les graphiques à barres et à lignes contiennent 2 séries. Elles partagent la même valeur de catégorie.


###########################################################
#Formatted Charts
AxisLabelFormat=Spécifiez le format des étiquettes d'axe : axe des Y($###,###) et axe des X(MM/dd/yyyy). Les utilisateurs ont également la possibilité de définir la couleur, la police, le contour ainsi que d'autres attributs d'étiquette.

AxisTitleFormat=Tous les attributs d'étiquette peuvent être appliqués au titre des axes.

ColoredByCategorySeries=Définissez le type d'élément de légende en tant que catégorie.

OpenJavaSourceAction.Text.Description=Ouvrir la source Java du répertoire correspondant

OpenJavaSourceAction.Text.ToolTip=Ouvrir la source Java

SaveXMLAction.MessageBox.Message=La source XML existe déjà dans ce répertoire. \nVoulez-vous la remplacer ?

SaveXMLAction.MessageBox.Text=Enregistrer la source XML

SaveXMLAction.Text.Description=Enregistrer la source XML dans le répertoire de votre choix

SaveXMLAction.Text.ToolTip=Enregistrer la source XML

ColoredByValueSeries=Définissez le type d'élément de légende en tant que série.

CurveFittingArea=Activez l'attribut d'ajustement de courbe de la série d'aires.

CurveFittingBar=Créez une ligne d'ajustement de courbe pour la série de barres.

CurveFittingLine=Activez l'attribut d'ajustement de courbe de la série de lignes.

CurveFittingStock=Créez une ligne d'ajustement de courbe pour la série d'actions.

LegendFormat=La légende peut être placée sur la gauche, sur la droite, en haut, en bas ou à l'intérieur. La zone client se trouve dans la légende. Elle contient les éléments de légende.

MarkerLine=La ligne de repères peut être créée pour l'axe des X et l'axe des Y (pour le type ChartWithAxes seulement).

MarkerRange=La gamme de repères peut être créée pour l'axe des X et l'axe des Y (pour le type ChartWithAxes seulement).

MultiplePie=Un graphique à secteurs contient plusieurs séries secteur. Elles peuvent constituer un groupe de secteurs représentant une comparaison de valeurs.

MDialSRegionMeter=Plusieurs aiguilles dans un même tableau à cadran.

SDialSRegionMeter=Une aiguille dans un seul tableau à cadran.

PercentageValueFormat=Représentez la valeur de série en tant que valeur de pourcentage.

PlotFormat=Spécifiez l'apparence de la zone de tracé et de la zone client.

SeriesValueFormat=Spécifiez le format des données de valeur ($###,###.00) et l'étiquette de l'axe horizontal (MM/jj/aaaa).

###########################################################
#Scripted Charts
AxisLabelScript=beforeDrawAxisLabel() permet aux utilisateurs de manipuler les attributs Axis et Label(Axis.getLabel()).

AxisTitleScript=beforeDrawAxisTitle() permet aux utilisateurs de manipuler les attributs Axis et Label(Axis.getTitle()).

BlockScript=beforeDrawBlock() permet aux utilisateurs de manipuler les attributs Block (par exemple, Tracé, Titre, Légende).

CurveFittingScript=beforeDrawFittingCurve() permet aux utilisateurs de manipuler les attributs CurveFitting.

DataPointLabelScript=beforeDrawDataPointLabel() permet aux utilisateurs de manipuler les attributs DataPointHints et Label.

LegendScript=beforeDrawLegendItem() permet aux utilisateurs de manipuler les éléments de légende et les attributs de limites.

MarkerLineScript=beforeDrawMarkerLine() permet aux utilisateurs de manipuler les attributs Axis et MarkerLine.

MarkerRangeScript=beforeDrawMarkerRange() permet aux utilisateurs de manipuler les attributs Axis et MarkerRange.

SeriesScript=beforeDrawSeries() permet aux utilisateurs de manipuler les attributs Series et ISeriesRenderer(BaseRenderer ou AxesRenderer).

SeriesTitleScript=beforeDrawSeriesTitle() permet aux utilisateurs de manipuler les attributs Series et Label(Series.getTitle()). Il s'applique uniquement aux graphiques à secteurs.

###########################################################
#Data Operations
MinSlice=L'utilisateur peut spécifier une valeur minimale (valeur absolue ou pourcentage) pour une tranche. Les tranches de graphiques à secteurs peuvent être éclatées en définissant l'expression sur l'attribut d'éclatement.

MultipleYAxes=Un graphique peut contenir plusieurs axes des Y.

MultipleYSeries=Un graphique peut contenir plusieurs séries (de valeurs) Y.

WorkingWithBIRTDataEngine=Un graphique fonctionne avec ODA/DtE (BIRT Data Engine) pour obtenir des données groupées / agrégées sans les grouper / les agréger lui-même.

###########################################################
#Default
DefaultDescription=Sélectionnez un exemple dans les catégories

###########################################################
#Example View labels
ChartExamples.Description=Description

ChartExamples.Preview=Aperçu

ChartExamples.SelectExamples=Sélectionner Exemples

############################################################
#Category Names
SampleChartCategory.PrimitiveCharts=Graphiques primitifs

SampleChartCategory.3DCharts=Graphiques en 3D

SampleChartCategory.CombinationCharts=Graphiques de combinaison

SampleChartCategory.FormattedCharts=Graphiques formatés

SampleChartCategory.ScriptedCharts=Graphiques nécessitant un script

SampleChartCategory.DataOperations=Opérations de données
#Sample Chart Names
#Primitive Charts
SampleChartName.SideBySideBar=Barres adjacentes

SampleChartName.StackedBar=Barres empilées

SampleChartName.PercentStackedBar=Barres empilées à pourcentage

SampleChartName.OverlayLine=Lignes superposées

SampleChartName.StackedLine=Lignes empilées

SampleChartName.PercentStackedLine=Lignes empilées à pourcentage

SampleChartName.OverlayArea=Aires superposées

SampleChartName.StackedArea=Aires empilées

SampleChartName.PercentStackedArea=Aires empilées à pourcentage

SampleChartName.Pie=Secteur

SampleChartName.StandardMeter=Cadrans standard

SampleChartName.SuperImposedMeter=Cadrans superposés

SampleChartName.Scatter=Nuage de points

SampleChartName.BarStickStock=Graphique boursier à barres

SampleChartName.CandleStickStock=Graphique boursier en chandelier

SampleChartName.Bubble=Bulle

SampleChartName.Difference=Différence

SampleChartName.Gantt=Gantt

SampleChartName.Tube=Cylindre

SampleChartName.Cone=Cône

SampleChartName.Pyramid=Pyramide

SampleChartName.Radar=Graphique en radar
#3D Charts
SampleChartName.Bar=Barre

SampleChartName.Line=Ligne

SampleChartName.Area=Aire

SampleChartName.Tube3D=Cylindre

SampleChartName.Cone3D=Cône

SampleChartName.Pyramid3D=Pyramide
#Combination Charts
SampleChartName.BarAndLine=Barres et lignes
#Formatted Charts
SampleChartName.AxisLabelFormat=Format de l'étiquette de l'axe

SampleChartName.AxisTitleFormat=Format du titre de l'axe

SampleChartName.ColoredByCategorySeries=Couleur par série de catégories

SampleChartName.ColoredByValueSeries=Couleur par série de valeurs

SampleChartName.CurveFittingArea=Aire d'ajustement de courbe

SampleChartName.CurveFittingBar=Barre d'ajustement de courbe

SampleChartName.CurveFittingLine=Ligne d'ajustement de courbe

SampleChartName.CurveFittingStock=Action d'ajustement de courbe

SampleChartName.LegendFormat=Format de la légende

SampleChartName.MarkerLine=Ligne de repères

SampleChartName.MarkerRange=Gamme de repères

SampleChartName.MultiplePie=Secteur multiple

SampleChartName.MDialSRegionMeter=Cadran par zone unique à aiguilles multiples

SampleChartName.SDialSRegionMeter=Cadran par zone unique à aiguille unique

SampleChartName.PercentageValueFormat=Format de la valeur en pourcentage

SampleChartName.PlotFormat=Format du tracé

SampleChartName.SeriesValueFormat=Format de la valeur de série
#Scripted Charts
SampleChartName.AxisLabelScript=Script de l'étiquette de l'axe

SampleChartName.AxisTitleScript=Script du titre de l'axe

SampleChartName.BlockScript=Script du bloc

SampleChartName.CurveFittingScript=Script d'ajustement de courbe

SampleChartName.DataPointLabelScript=Script de l'étiquette de point de données

SampleChartName.LegendScript=Script de la légende

SampleChartName.MarkerLineScript=Script de la ligne de repères

SampleChartName.MarkerRangeScript=Script de la gamme de repères

SampleChartName.SeriesScript=Script de la série

SampleChartName.SeriesTitleScript=Script du titre de la série
#Data Operations
SampleChartName.MinSlice=Tranche Min

SampleChartName.MultipleYAxes=Axes Y multiples

SampleChartName.MultipleYSeries=Séries Y multiples

SampleChartName.WorkingWithBIRTDataEngine=Utilisation de BIRT Data Engine


