###########################################################
#Primitive Charts
SideBySideBar=연속 막대형 차트에는 각 계열의 막대가 나란히 표시됩니다. 이 막대는 동일한 너비로 정렬됩니다. 막대의 너비는 그려지는 계열 수에 따라 달라집니다.

StackedBar=누적 막대형 차트에는 서로 누적된 막대가 표시됩니다. 양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

PercentStackedBar=백분율 누적 막대형 차트에는 누적된 막대(가장 낮은 점에서부터 가장 높은 점까지)의 총 높이가 100이 되도록 막대가 서로 누적되어 표시됩니다.

OverlayLine=이중 선형 차트에는 각 계열의 선이 서로 독립적으로 표시됩니다. 계열의 값을 결합하는 선이 표시됩니다.

StackedLine=누적 선형 차트에는 서로 누적된 선이 표시됩니다. 양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

PercentStackedLine=백분율 누적 선형 차트에는 누적된 선(각 단위에서 가장 낮은 점에서부터 가장 높은 점까지)의 총 높이가 100이 되도록 선이 서로 누적되어 표시됩니다.

OverlayArea=이중 영역형 차트에는 각 계열의 영역이 서로 독립적으로 표시됩니다. 계열의 값을 결합하는 영역이 표시됩니다.

StackedArea=누적 영역형 차트에는 서로 누적된 영역이 표시됩니다. 양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

PercentStackedArea=백분율 누적 영역형 차트에는 누적된 영역(각 단위에서 가장 낮은 점에서부터 가장 높은 점까지)의 총 높이가 100이 되도록 영역이 서로 누적되어 표시됩니다.

Pie=원형 차트에는 값이 원형의 조각으로 표시됩니다. 각 조각의 크기는 해당 조각이 나타내는 값에 비례합니다. 복수 계열의 원형 차트는 각 계열에 하나씩 복수의 원형으로 그려집니다.

StandardMeter=표준 측정기 차트에는 영역을 포함한 단일 다이얼이 포함됩니다. 다이얼 배경은 다른 색상을 가진 영역으로 분류할 수 있습니다.

SuperImposedMeter=중첩 측정기 차트에는 동일한 영역을 포함한 다중 다이얼이 포함됩니다. 다이얼이 동시에 겹치므로 단일 영역 내 여러 바늘을 나타낼 수 있습니다.

Scatter=분산형 차트에는 범주와 값 데이터를 좌표로 사용하여 플롯 위에 정렬된 값이 표시됩니다. 각 데이터 값은 표지로 표시됩니다.

BarStickStock=막대형 주식 차트에는 수직선 한 개와 이 수직선에 붙어 있는 수평선 두 개가 있습니다. 수직선의 위쪽 끝과 아래쪽 끝이 주식의 시가와 종가 값입니다. 두 수평선은 고가와 저가를 나타냅니다.

CandleStickStock=원통형 주식 차트에는 상자 한 개가 있고 상자의 위 아래로 선이 나와 있습니다. 상자의 위쪽 가장자리와 아래쪽 가장자리가 주식의 시가와 종가 값입니다. 위로 나온 선은 고가를, 아래로 나온 선은 저가를 나타냅니다.

Bubble=거품형 차트는 분산형 차트로 확장되며 거품으로 값을 표시합니다. 거품의 지름은 x, y 좌표 외에 세 번째 데이터 값에 비례합니다.

Difference=차이점 차트는 값을 나타내는 두 선 사이의 영역을 표시합니다. 이 차트는 영역 계열의 속성을 모두 상속받고 서로 다른 색상으로 음수 영역을 표시할 수도 있습니다.

Gantt=간트 차트는 작업 기간 및 진행 상황을 추적하는 데 사용됩니다. 이 차트의 Y 축에는 날짜/시간이 표시되며 사용자 지정 너비의 막대를 사용해 시작/종료 표지를 나타냅니다. 각각의 막대는 해당 범주, 작업 레이블, 시작 시간 및 종료 시간으로 정의됩니다. 서로 다른 너비의 여러 간트 계열을 오버레이하여 인스턴스에 대해 예약된 작업의 실제 진행 상황을 추적할 수 있습니다.

Tube=튜브형 차트는 막대형 차트와 유사하게 튜브 모양의 막대로 표시됩니다.

Cone=원뿔형 차트는 막대형 차트와 유사하게 원뿔 모양의 막대로 표시됩니다.

Pyramid=피라미드 차트는 막대형 차트와 유사하게 피라피드 모양의 막대로 표시됩니다.

Radar=표준 방사형 차트에는 하나 이상의 다각형/선 계열과 겹치는 원형 눈금이 포함됩니다.

###########################################################
#3D Charts
Bar=3차원 연속 막대형 차트입니다.

Line=3차원 이중 선형 차트입니다.

Area=3차원 이중 영역형 차트입니다.

Tube3D=3차원 연속 튜브형 차트입니다.

Cone3D=3차원 연속 원뿔형 차트입니다.

Pyramid3D=3차원 연속 피라미드형 차트입니다.

###########################################################
#Combination Charts
BarAndLine=막대 및 선 결합 차트에는 2개의 계열이 있습니다. 2개의 계열은 동일한 범주 값을 사용합니다.


###########################################################
#Formatted Charts
AxisLabelFormat=Y축($###,###) 및 X축(MM/dd/yyyy)의 축 레이블 서식을 지정합니다. 또한 사용자가 레이블 색상, 글꼴, 윤곽선 및 기타 특성도 설정할 수 있습니다.

AxisTitleFormat=모든 레이블 특성은 축 제목에 적용할 수 있습니다.

ColoredByCategorySeries=범례 항목 형식을 범주로 설정합니다.

OpenJavaSourceAction.Text.Description=관련 디렉터리에서 Java 소스를 엽니다.

OpenJavaSourceAction.Text.ToolTip=Java 소스 열기

SaveXMLAction.MessageBox.Message=XML 소스가 이미 디렉터리에 있습니다. \n바꾸시겠습니까?

SaveXMLAction.MessageBox.Text=XML 소스 저장

SaveXMLAction.Text.Description=XML 소스를 지정된 디렉터리에 저장합니다.

SaveXMLAction.Text.ToolTip=XML 소스 저장

ColoredByValueSeries=범례 항목 형식을 계열로 설정합니다.

CurveFittingArea=영역형 계열의 곡선 근사 특성을 사용합니다.

CurveFittingBar=막대형 계열에 곡선 근사 줄을 생성합니다.

CurveFittingLine=선형 계열의 곡선 근사 특성을 사용합니다.

CurveFittingStock=주식형 계열에 곡선 근사 줄을 생성합니다.

LegendFormat=범례는 왼쪽, 오른쪽, 위쪽, 아래쪽 및 안쪽에 위치할 수 있습니다. 클라이언트 영역은 범례 내에 위치하며, 범례 항목을 포함합니다.

MarkerLine=MarkerLine은 X축 및 Y축 모두에 만들 수 있습니다(ChartWithAxes 형식에만 해당).

MarkerRange=MarkerRange는 X축 및 Y축 모두에 만들 수 있습니다(ChartWithAxes 형식에만 해당).

MultiplePie=개별 원형 차트에는 여러 조각의 계열이 포함됩니다. 계열은 조각의 그룹을 구성하여 값을 비교할 수 있습니다.

MDialSRegionMeter=개별 다이얼 보드의 복수 바늘입니다.

SDialSRegionMeter=개별 다이얼 보드의 바늘입니다.

PercentageValueFormat=계열 값을 백분율 수치로 표시합니다.

PlotFormat=플롯 및 클라이언트 영역의 모양을 지정합니다.

SeriesValueFormat=값 데이터($###,###.00) 및 X축 레이블(yyyy/MM/dd)의 형식을 지정합니다.

###########################################################
#Scripted Charts
AxisLabelScript=beforeDrawAxisLabel()을 사용해 축 및 레이블(Axis.getLabel()) 특성을 조작할 수 있습니다.

AxisTitleScript=beforeDrawAxisTitle()을 사용해 축 및 레이블(Axis.getTitle()) 특성을 조작할 수 있습니다.

BlockScript=beforeDrawBlock()을 사용해 블록(예: 플롯, 제목, 범례) 특성을 조작할 수 있습니다.

CurveFittingScript=beforeDrawFittingCurve()를 사용해 CurveFitting 특성을 조작할 수 있습니다.

DataPointLabelScript=beforeDrawDataPointLabel()을 사용해 DataPointHints 및 레이블 특성을 조작할 수 있습니다.

LegendScript=beforeDrawLegendItem()을 사용해 범례 항목 및 바운드 특성을 조작할 수 있습니다.

MarkerLineScript=beforeDrawMarkerLine()을 사용해 축 및 MarkerLine 특성을 조작할 수 있습니다.

MarkerRangeScript=beforeDrawMarkerRange()를 사용해 축 및 MarkerRange 특성을 조작할 수 있습니다.

SeriesScript=beforeDrawSeries()를 사용해 계열 및 ISeriesRenderer(BaseRenderer 또는 AxesRenderer) 특성을 조작할 수 있습니다.

SeriesTitleScript=beforeDrawSeriesTitle()을 사용해 계열 및 레이블(Series.getTitle()) 특성을 조작할 수 있습니다. 이는 원형 차트에만 적용됩니다.

###########################################################
#Data Operations
MinSlice=사용자가 조각의 최소값(절대값 또는 백분율)을 지정할 수 있습니다. 원형 차트 조각은 쪼개기 특성을 식에 설정하여 쪼갤 수 있습니다.

MultipleYAxes=차트는 한 개 이상의 Y축을 포함할 수 있습니다.

MultipleYSeries=차트는 한 개 이상의 Y(값) 계열을 포함할 수 있습니다.

WorkingWithBIRTDataEngine=ODA/DtE(BIRT데이터 엔진)와 함께 사용하여 차트에서 직접 그룹화/집계하지 않아도 데이터를 그룹화/집계할 수 있습니다.

###########################################################
#Default
DefaultDescription=범주에서 예를 선택하십시오.

###########################################################
#Example View labels
ChartExamples.Description=설명

ChartExamples.Preview=미리 보기

ChartExamples.SelectExamples=예제 선택

############################################################
#Category Names
SampleChartCategory.PrimitiveCharts=기본 차트

SampleChartCategory.3DCharts=3D 차트

SampleChartCategory.CombinationCharts=복합 차트

SampleChartCategory.FormattedCharts=서식이 지정된 차트

SampleChartCategory.ScriptedCharts=스크립트된 차트

SampleChartCategory.DataOperations=데이터 작업
#Sample Chart Names
#Primitive Charts
SampleChartName.SideBySideBar=연속 막대

SampleChartName.StackedBar=누적 막대형

SampleChartName.PercentStackedBar=누적 백분율 막대

SampleChartName.OverlayLine=이중 선형

SampleChartName.StackedLine=누적 꺾은선형

SampleChartName.PercentStackedLine=백분율 누적 선형

SampleChartName.OverlayArea=이중 영역형

SampleChartName.StackedArea=누적 영역형

SampleChartName.PercentStackedArea=누적 백분율 영역형

SampleChartName.Pie=원형

SampleChartName.StandardMeter=표준 측정기

SampleChartName.SuperImposedMeter=중첩 측정기

SampleChartName.Scatter=분산형

SampleChartName.BarStickStock=막대형 주식

SampleChartName.CandleStickStock=원통형 주식

SampleChartName.Bubble=거품형

SampleChartName.Difference=차이

SampleChartName.Gantt=간트

SampleChartName.Tube=튜브

SampleChartName.Cone=원뿔

SampleChartName.Pyramid=피라미드

SampleChartName.Radar=방사형
#3D Charts
SampleChartName.Bar=막대형

SampleChartName.Line=꺽은선형

SampleChartName.Area=영역형

SampleChartName.Tube3D=튜브

SampleChartName.Cone3D=원뿔

SampleChartName.Pyramid3D=피라미드
#Combination Charts
SampleChartName.BarAndLine=막대 및 선
#Formatted Charts
SampleChartName.AxisLabelFormat=축 레이블 형식

SampleChartName.AxisTitleFormat=축 제목 형식

SampleChartName.ColoredByCategorySeries=범주 계열별 색상 지정

SampleChartName.ColoredByValueSeries=값 계열별 색상 지정

SampleChartName.CurveFittingArea=곡선 근사 영역

SampleChartName.CurveFittingBar=곡선 근사 막대

SampleChartName.CurveFittingLine=곡선 근사 줄

SampleChartName.CurveFittingStock=곡선 근사 주식

SampleChartName.LegendFormat=범례 형식

SampleChartName.MarkerLine=표지 선

SampleChartName.MarkerRange=표지 범위

SampleChartName.MultiplePie=복수 원형

SampleChartName.MDialSRegionMeter=M 다이얼 S 영역 측정기

SampleChartName.SDialSRegionMeter=S 다이얼 S 영역 측정기

SampleChartName.PercentageValueFormat=백분율 값 형식

SampleChartName.PlotFormat=플롯 형식

SampleChartName.SeriesValueFormat=계열 값 형식
#Scripted Charts
SampleChartName.AxisLabelScript=축 레이블 스크립트

SampleChartName.AxisTitleScript=축 제목 스크립트

SampleChartName.BlockScript=블록 스크립트

SampleChartName.CurveFittingScript=곡선 근사 스크립트

SampleChartName.DataPointLabelScript=데이터 요소 레이블 스크립트

SampleChartName.LegendScript=범례 스크립트

SampleChartName.MarkerLineScript=표지 선 스크립트

SampleChartName.MarkerRangeScript=표지 범위 스크립트

SampleChartName.SeriesScript=계열 스크립트

SampleChartName.SeriesTitleScript=계열 제목 스크립트
#Data Operations
SampleChartName.MinSlice=최소 조각

SampleChartName.MultipleYAxes=다중 Y 축

SampleChartName.MultipleYSeries=다중 Y 계열

SampleChartName.WorkingWithBIRTDataEngine=BIRT 데이터 엔진 작업


