#************************************************************************
# Copyright (c) 2012 Megha Nidhi Dahal and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    Megha Nidhi Dahal - initial API and implementation
#    Actuate Corporation - enhanced and refined user messages
#************************************************************************
#
# User messages for the Excel File ODA Runtime Driver
connection_CONNECTION_PROPERTIES_MISSING=接続プロパティがありません。
#connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Cannot open Excel file under directory:
connection_MISSING_FILELOCATION=Excel データソースファイルのプロパティが定義されていません。Excel 入力ファイルのファイルパスまたは URI が必要です。

connection_invalidSource=指定された Excel データソースファイルの URI が無効か間違っています。

connection_missingResourceIdentifier=Excel データソースの相対パスを解決するリソース ID がありません。

fileSource_excelFileNotFound=指定された Excel データソースフォルダまたはファイル ({0}) が見つかりません。

query_COMMAND_IS_EMPTY=クエリコマンドが空です。

query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=クロステーブルはクエリできません。

query_COMMAND_NOT_VALID=指定された Excel ファイル内のヘッダ情報が無効です。

query_ARGUMENT_ERROR=引数は 'NAME' と 'TYPE' のいずれかを指定してください。

query_IO_EXCEPTION=ファイルの読み込み中に I/O 例外が発生しました。

query_SOURCE_DATA_ERROR=データソース内で列名が重複しています。

query_COLUMN_NAME_ERROR=列名エラー

query_INVALID_EXCEL_FILE=ワークシートにデータが含まれていません。 別のシートを選択してください。

query_text_error=クエリテキストの書式エラー

query_WORKSHEET_CANNOT_BE_NULL=ワークシート名は null にできません。

resultSet_COLUMN_NOT_FOUND=列が見つかりません :

resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=カーソルが初期化されていません。

resultSetMetaData_INVALID_COLUMN_INDEX=列インデックスが無効です :

savedSelectedColumnsInfoString_INVALID=保存された列情報が無効です。

dataTypes_TYPE_NAME_INVALID=データ型名が無効です :

dataSetMetaData_PRODUCT_NAME=Excel ODA データソースのプロバイダ

common_ARGUMENT_CANNOT_BE_NULL=引数は null にできません。

common_CONNECTION_HAS_NOT_OPEN=接続が開いていません。

common_CANNOT_FIND_COLUMN=列が見つかりません。

common_NULL_QUERY_TEXT = クエリテキストが NULL です。

data_read_error=データを正しく読み取れません。データソースの設定が変更された可能性があります。

Invalid_column_name = 列名が無効です。

invalid_excelfile_format = Excel ファイルの形式が無効です。

date_format_null = 日付形式は null にできません。

invalid_date_value = {0} を有効な日付として解析することができません。 データセットのプロパティで日付形式を確認してください。

invalid_sheet_name = 指定されたファイルに {0} という名前のシートが含まれていません。

query_streamClosed=ストリームが閉じられました。

query_invalidTableName=無効なテーブル名 :

dateUtil.ConvertFails=日付に変換できません。 ソース :

dateFormatISO_cannotConvert={0} の値を変換できません。