#************************************************************************
# Copyright (c) 2012 Megha Nidhi Dahal and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#    Megha Nidhi Dahal - initial API and implementation
#    Actuate Corporation - enhanced and refined user messages
#************************************************************************
#
# User messages for the Excel File ODA Runtime Driver
connection_CONNECTION_PROPERTIES_MISSING=Faltan las propiedades de conexión.
#connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Cannot open Excel file under directory:
connection_MISSING_FILELOCATION=La propiedad de archivo de fuente de datos de Excel no está definida. Se necesita una ruta de archivo o URI para el archivo de entrada de Excel.

connection_invalidSource=URI especificada para el archivo de fuente de datos de Excel no válida o incorrecta.

connection_missingResourceIdentifier=No hay ningún identificador de recurso disponible para resolver la ruta relativa de la fuente de datos de Excel:

fileSource_excelFileNotFound=No es posible localizar la carpeta de fuente de datos de Excel o el archivo ({0}).

query_COMMAND_IS_EMPTY=El comando de consulta está vacío.

query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=No se admite la consulta de tabla de referencias cruzadas.

query_COMMAND_NOT_VALID=Información de encabezado en el archivo de Excel proporcionado no válida.

query_ARGUMENT_ERROR=El argumento debe ser 'NAME' o 'TYPE'.

query_IO_EXCEPTION=Se ha producido una excepción de E/S al leer el archivo.

query_SOURCE_DATA_ERROR=Se han encontrado nombres de columna duplicados en los datos fuente.

query_COLUMN_NAME_ERROR=Error de nombre de columna

query_INVALID_EXCEL_FILE=La hoja de trabajo no contiene ningún dato. Seleccione una hoja diferente.

query_text_error=Error de formato de texto de consulta

query_WORKSHEET_CANNOT_BE_NULL=El nombre de la hoja de trabajo no puede ser nulo.

resultSet_COLUMN_NOT_FOUND=No se ha encontrado la columna:

resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=Todavía no se ha inicializado el cursor.

resultSetMetaData_INVALID_COLUMN_INDEX=Índice de columna no válido:

savedSelectedColumnsInfoString_INVALID=Información guardada sobre columnas no válida

dataTypes_TYPE_NAME_INVALID=Nombre de tipo de datos no válido:

dataSetMetaData_PRODUCT_NAME=Proveedor de fuente de datos ODA de Excel

common_ARGUMENT_CANNOT_BE_NULL=Los argumentos no pueden ser nulos.

common_CONNECTION_HAS_NOT_OPEN=La conexión no está abierta.

common_CANNOT_FIND_COLUMN=No se puede encontrar ninguna columna.

common_NULL_QUERY_TEXT = El texto de consulta es nulo

data_read_error=Los datos no se pueden leer correctamente. Los ajustes de fuente de datos pueden haber cambiado

Invalid_column_name = Nombre de columna no válido

invalid_excelfile_format = Formato de archivo de Excel no válido

date_format_null = El formato de fecha no puede ser nulo.

invalid_date_value = {0} no se puede analizar como una fecha válida. Compruebe el formato de fecha en las propiedades del conjunto de datos.

invalid_sheet_name = El archivo proporcionado no contiene ninguna hoja con el nombre {0}

query_streamClosed=Secuencia cerrada

query_invalidTableName=Nombre de tabla no válido:

dateUtil.ConvertFails=Error al convertir la fecha. Fuente:

dateFormatISO_cannotConvert=No se puede convertir el valor de {0}.