#************************************************************************
# Copyright (c) 2012 Megha Nidhi Dahal and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    Megha Nidhi Dahal - initial API and implementation
#    Actuate Corporation - enhanced and refined user messages
#************************************************************************
#
# User messages for the Excel File ODA Runtime Driver
connection_CONNECTION_PROPERTIES_MISSING=缺少连接属性。
#connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Cannot open Excel file under directory:
connection_MISSING_FILELOCATION=未定义 Excel 数据源文件属性；需要 Excel 输入文件的文件路径或 URI。

connection_invalidSource=为 Excel 数据源文件指定的 URI 无效或格式错误。

connection_missingResourceIdentifier=无法找到资源标识符来解析 Excel 数据源的相对路径:

fileSource_excelFileNotFound=无法定位指定的 Excel 数据源文件夹或文件 ({0})。

query_COMMAND_IS_EMPTY=查询命令为空。

query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=不支持交叉表查询。

query_COMMAND_NOT_VALID=提供的 Excel 文件中存在无效标题信息。

query_ARGUMENT_ERROR=参数应为 'NAME' 或 'TYPE'。

query_IO_EXCEPTION=读取文件时发生 I/O 异常。

query_SOURCE_DATA_ERROR=源数据中发现重复列名称。

query_COLUMN_NAME_ERROR=列名称错误

query_INVALID_EXCEL_FILE=该工作表未包含任何数据。 请选择另一个工作表。

query_text_error=查询文本格式错误

query_WORKSHEET_CANNOT_BE_NULL=工作表名称不能为空。

resultSet_COLUMN_NOT_FOUND=未找到列:

resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=光标尚未初始化。

resultSetMetaData_INVALID_COLUMN_INDEX=无效列索引:

savedSelectedColumnsInfoString_INVALID=无效的保存列信息

dataTypes_TYPE_NAME_INVALID=无效的数据类型名称:

dataSetMetaData_PRODUCT_NAME=Excel ODA 数据源提供程序

common_ARGUMENT_CANNOT_BE_NULL=参数不能为空。

common_CONNECTION_HAS_NOT_OPEN=连接未打开。

common_CANNOT_FIND_COLUMN=找不到任何列。

common_NULL_QUERY_TEXT = 查询文本为空

data_read_error=无法正确读取数据，数据源设置可能已更改

Invalid_column_name = 无效列名称

invalid_excelfile_format = 无效 Excel 文件格式

date_format_null = 日期格式不能为空。

invalid_date_value = 无法将 {0} 分析为有效日期。 请检查数据集属性中的日期格式。

invalid_sheet_name = 提供的文件不包含任何名称为 {0} 的工作表

query_streamClosed=流已关闭

query_invalidTableName=无效表名称:

dateUtil.ConvertFails=转换为日期失败。 源:

dateFormatISO_cannotConvert=无法转换 {0} 的值。