#************************************************************************
# Copyright (c) 2012 Megha Nidhi Dahal and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#    Megha Nidhi Dahal - initial API and implementation
#    Actuate Corporation - enhanced and refined user messages
#************************************************************************
#
# User messages for the Excel File ODA Runtime Driver
connection_CONNECTION_PROPERTIES_MISSING=연결 속성이 누락되었습니다.
#connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Cannot open Excel file under directory:
connection_MISSING_FILELOCATION=Excel 데이터 원본 파일 속성이 정의되지 않았습니다. Excel 입력 파일에 대한 파일 경로 또는 URI가 필요합니다.

connection_invalidSource=Excel 데이터 원본 파일에 대해 지정된 URI가 유효하지 않거나 잘못되었습니다.

connection_missingResourceIdentifier=Excel 데이터 원본의 상대 경로를 해결할 리소스 식별자가 없습니다.

fileSource_excelFileNotFound=지정된 Excel 데이터 원본 폴더 또는 파일({0})을 찾을 수 없습니다.

query_COMMAND_IS_EMPTY=쿼리 명령이 비어 있습니다.

query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=교차 테이블 쿼리는 지원되지 않습니다.

query_COMMAND_NOT_VALID=제공된 Excel 파일의 머리글 정보가 잘못되었습니다.

query_ARGUMENT_ERROR=인수는 '이름'이나 형식'이어야 합니다.

query_IO_EXCEPTION=파일을 읽는 동안 I/O 예외가 발생했습니다.

query_SOURCE_DATA_ERROR=원본 데이터에 중복된 열 이름이 있습니다.

query_COLUMN_NAME_ERROR=열 이름 오류

query_INVALID_EXCEL_FILE=워크시트에 데이터가 없습니다. 다른 시트를 선택하십시오.

query_text_error=쿼리 텍스트 서식 오류

query_WORKSHEET_CANNOT_BE_NULL=워크시트 이름은 널(null)이 될 수 없습니다.

resultSet_COLUMN_NOT_FOUND=열 없음:

resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=커서가 아직 초기화되지 않았습니다.

resultSetMetaData_INVALID_COLUMN_INDEX=잘못된 열 인덱스:

savedSelectedColumnsInfoString_INVALID=잘못 저장된 열 정보

dataTypes_TYPE_NAME_INVALID=잘못된 데이터 형식 이름:

dataSetMetaData_PRODUCT_NAME=Excel ODA 데이터 원본 공급자

common_ARGUMENT_CANNOT_BE_NULL=인수는 널(null)일 수 없습니다.

common_CONNECTION_HAS_NOT_OPEN=연결이 열리지 않습니다.

common_CANNOT_FIND_COLUMN=열을 찾을 수 없습니다.

common_NULL_QUERY_TEXT = 쿼리 텍스트가 Null입니다.

data_read_error=데이터를 정확하게 읽을 수 없습니다. 원본 데이터가 변경된 것 같습니다.

Invalid_column_name = 잘못된 열 이름입니다.

invalid_excelfile_format = 잘못된 Excel 파일 형식

date_format_null = 날짜 형식은 널(null)이 될 수 없습니다.

invalid_date_value = {0}을(를) 유효한 날짜로 구문 분석할 수 없습니다. 데이터 집합 속성의 날짜 형식을 확인하십시오.

invalid_sheet_name = 입력한 파일에 이름이 {0}인 시트가 없습니다.

query_streamClosed=닫힌 스트림

query_invalidTableName=잘못된 테이블 이름:

dateUtil.ConvertFails=날짜로 변환 실패 원본:

dateFormatISO_cannotConvert={0}의 값을 변환할 수 없습니다.