###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Lib Design
LibraryEditor=ライブラリエディタ

WizardCategoryName=Business Intelligence and Reporting Tools
LibraryWizard=ライブラリ

LibraryWizardDescription=このウィザードでは、新しいライブラリを作成します。

LibraryProjectWizard=ライブラリプロジェクト

LibraryProjectWizardDescription=新しいライブラリプロジェクトを作成します。

library.layout=レイアウト(&O)

library.script=スクリプト(&S)

library.xmlsource=XML ソース(&X)

design.masterPage=マスタページ(&M)