###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Lib Design
LibraryEditor=Bibliothekeditor

WizardCategoryName=Business Intelligence and Reporting Tools
LibraryWizard=Bibliothek

LibraryWizardDescription=Mit diesem Assistenten wird eine neue Bibliothek erstellt.

LibraryProjectWizard=Bibliotheksprojekt

LibraryProjectWizardDescription=Erstellt ein neues Bibliotheksprojekt.

library.layout=Lay&out

library.script=&Skript

library.xmlsource=&XML-Quelldatei

design.masterPage=&Master-Seite