###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Lib Design
LibraryEditor=Editeur de bibliothèque

WizardCategoryName=Business Intelligence and Reporting Tools
LibraryWizard=Bibliothèque

LibraryWizardDescription=Cet assistant crée une nouvelle bibliothèque.

LibraryProjectWizard=Projet de bibliothèque

LibraryProjectWizardDescription=Crée un projet de bibliothèque.

library.layout=&Mise en page

library.script=&Script

library.xmlsource=Source &XML

design.masterPage=&Page maître