###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Lib Design
LibraryEditor=库编辑器

WizardCategoryName=Business Intelligence and Reporting Tools
LibraryWizard=库

LibraryWizardDescription=此向导创建新库。

LibraryProjectWizard=库项目

LibraryProjectWizardDescription=新建库项目。

library.layout=布局(&O)

library.script=脚本(&S)

library.xmlsource=XML 源(&X)

design.masterPage=主页(&M)