###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Lib Design
LibraryEditor=Editor de librerías

WizardCategoryName=Business Intelligence and Reporting Tools
LibraryWizard=Librería

LibraryWizardDescription=Este asistente crea una nueva librería.

LibraryProjectWizard=Proyecto de librería

LibraryProjectWizardDescription=Crea un nuevo proyecto de librería.

library.layout=Diseñ&o

library.script=&Script

library.xmlsource=&Fuente XML

design.masterPage=&Página maestra