cheatsheet.category=Business Intelligence and Reporting Tools
cheatsheet.simplelisting=Bericht mit einfacher Liste

cheatsheet.groupedlisting=Bericht mit gruppierter Liste

cheatsheet.dualcolumnlisting=Bericht mit zweispaltiger Liste

cheatsheet.chartlisting=Bericht mit Diagramm und Liste

cheatsheet.sidebysidechartlisting=Bericht mit Diagramm und Liste nebeneinander

cheatsheet.dualcolumnchartlisting=Bericht mit Zwei-Spalten-Diagramm und -Listen

cheatsheet.firstreport=Der erste Bericht

cheatsheet.crosstab=Kreuztabellenbericht