cheatsheet.category=Business Intelligence and Reporting Tools
cheatsheet.simplelisting=Etat - Listes simples

cheatsheet.groupedlisting=Etat - Listes groupées

cheatsheet.dualcolumnlisting=Etat - Listes de colonnes doubles

cheatsheet.chartlisting=Etat - Graphiques et listes

cheatsheet.sidebysidechartlisting=Etat - Graphiques et listes juxtaposés

cheatsheet.dualcolumnchartlisting=Etat - Graphiques et listes de colonnes doubles

cheatsheet.firstreport=Mon premier état

cheatsheet.crosstab=Etat de tableau croisé