###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=쿼리
datasource.name=Classic Models Inc. 예제 데이터베이스
select.dataset.name=SQL 쿼리 선택
jdbc.driver.name=Classic Models Inc. 예제 데이터베이스 드라이버
dataset.property.queryTimeOut=쿼리 시간 제한(초)(&Q)
#
oda.data.source.name=Classic Models Inc. 예제 데이터베이스
connection.profile.name=BIRT 예제 DB 데이터 원본 연결 프로필
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
