###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=クエリ
datasource.name=Classic Models Inc. のサンプルデータベース
select.dataset.name=SQL Select クエリ
jdbc.driver.name=Classic Models Inc. SampleDB Driver
#
oda.data.source.name=BIRT Sample DB
connection.profile.name=BIRT Sample DB Data Source Connection Profile
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
