###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Requête
datasource.name=Base de données exemple Classic Models Inc.
select.dataset.name=Requête de sélection SQL
jdbc.driver.name=Pilote de la base de données exemple Classic Models Inc.
dataset.property.queryTimeOut=Délai d'expiration de re&quête (en secondes)
#
oda.data.source.name=Base de données exemple Classic Models Inc.
connection.profile.name=Profil de connexion à la source de données de la BD exemple BIRT
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
