###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Consulta
datasource.name=Base de datos de muestra Classic Models Inc.
select.dataset.name=Consulta de selección de SQL
jdbc.driver.name=Controlador de bases de datos de muestra Classic Models Inc.
#
oda.data.source.name=Base de datos de muestra BIRT
connection.profile.name=Perfil de conexión de fuente de datos de base de datos de muestra BIRT
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
