###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=查询
datasource.name=Classic Models Inc. 示例数据库
select.dataset.name=SQL 选择查询
jdbc.driver.name=Classic Models Inc. 示例数据库驱动程序
#
oda.data.source.name=BIRT 示例数据库
connection.profile.name=BIRT 示例数据库数据源连接配置文件
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
