###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Query

datasource.name=Classic Models Inc. Sample Database

select.dataset.name=SQL Select Query

jdbc.driver.name=Classic Models Inc. SampleDB Driver
dataset.property.queryTimeOut=&Query Time Out (in seconds)

dataset.property.rowFetchSize=Abzurufende &Zeilenanzahl
#
oda.data.source.name=Classic Models Inc. Sample Database

connection.profile.name=Verbindungsprofil für BIRT-Beispieldatenbank-Datenquelle
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
