###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Abfrage
datasource.name=Beispieldatenbank "Classic Models Inc."
select.dataset.name=SQL-Auswahlabfrage
jdbc.driver.name=Treiber für Beispieldatenbank Classic Models Inc.
#
oda.data.source.name=BIRT-Beispieldatenbank
connection.profile.name=Verbindungsprofil für BIRT-Beispieldatenbank-Datenquelle
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
