###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.mongodb
#
###############################################################################
# NLS strings
#
plugin.name=MongoDB Data Source ODA Designer
newwizard.name=MongoDB Data Source
newwizard.description=Créer un profil de connexion à la source de données MongoDB

wizard.window.title=Nouveau profil de source de données MongoDB

wizard.data.source.page.title=MongoDB Data Source
profile.propertypage.name=MongoDB Data Source Connection Properties
wizard.data.set.window.title=Nouveau jeu de données du MongoDB

wizard.data.set.page.title=Requête
