###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.mongodb
#
###############################################################################
# NLS strings
#
plugin.name=MongoDB Data Source ODA Designer
newwizard.name=MongoDB Data Source
newwizard.description=创建 MongoDB 数据源连接配置文件

wizard.window.title=新建 MongoDB 数据源配置文件

wizard.data.source.page.title=MongoDB Data Source
profile.propertypage.name=MongoDB Data Source Connection Properties
wizard.data.set.window.title=新建 MongoDB 数据集

wizard.data.set.page.title=查询
