###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.mongodb
#
###############################################################################
# NLS strings
#
plugin.name=MongoDB Data Source ODA Designer
newwizard.name=MongoDB Data Source
newwizard.description=Ein MongoDB-Datenquellen-Verbindungsprofil erstellen

wizard.window.title=Neues MongoDB-Datenquellenprofil

wizard.data.source.page.title=MongoDB Data Source
profile.propertypage.name=MongoDB Data Source Connection Properties
wizard.data.set.window.title=Neuer MongoDB-Datensatz

wizard.data.set.page.title=Abfrage
