#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Docx Emitter
DocxEmitter.Description=配置用于以 XML Document 2007 格式呈现报表的选项。

DocxEmitter.DisplayName=Word (DOCX)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=图表 DPI

OptionDisplayValue.EmbedHtml=嵌入 HTML

###########################################################
#Option Description
OptionDescription.ChartDpi=用于生成图表的 DPI。

OptionDescription.EmbedHtml=允许 DOCX 使用已嵌入的 HTML

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。 例如，192。

Tooltip.EmbedHtml=HTML 内容是否应直接嵌入到 DOCX 输出