#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Docx Emitter
DocxEmitter.Description=XML 문서 2007 형식의 보고서 렌더링 옵션을 구성합니다.

DocxEmitter.DisplayName=Word (DOCX)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=차트 DPI

OptionDisplayValue.EmbedHtml=HTML 포함

###########################################################
#Option Description
OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.

OptionDescription.EmbedHtml=DOCX에서 포함된 HTML을 사용하도록 허용합니다.

###########################################################
#tooltip
Tooltip.ChartDpi=차트 엔진에서 차트를 생성하는 데 사용하는 DPI입니다. 예: 192.

Tooltip.EmbedHtml=HTML 내용이 DOCX 출력에 직접 포함되어야 하는 경우