#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Docx Emitter
DocxEmitter.Description=Optionen zum Rendern eines Berichts im Format XML Document 2007 konfigurieren.

DocxEmitter.DisplayName=Word (DOCX)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=Diagramm-DPI

OptionDisplayValue.EmbedHtml=HTML einbetten

###########################################################
#Option Description
OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

OptionDescription.EmbedHtml=Zulassen, dass DOCX eingebettetes HTML verwendet

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.

Tooltip.EmbedHtml=Falls HTML-Inhalt direkt in DOCX-Output eingebettet werden sollte