#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Docx Emitter
DocxEmitter.Description=Configure las opciones para presentar un informe en formato de documento XML 2007.

DocxEmitter.DisplayName=Word (DOCX)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=Diagrama DPI

OptionDisplayValue.EmbedHtml=Incrustar HTML

###########################################################
#Option Description
OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

OptionDescription.EmbedHtml=Permitir que el DOCX utilice HTML incrustado

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.

Tooltip.EmbedHtml=Si el contenido HTML estuviera incrustado directamente a la salida del DOCX