###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

About=Business Intelligence and Reporting Tools
ApplicationName=BIRT Report Designer
ReportPerspective=BIRT Report Designer
CHEAT_SHEETS=Consejos útiles

CHEAT_SHEETS_MENU=&Consejos útiles...

ReportEditor=Editor de informes

ReportDocumentEditor=Editor de documentos de informe

LibraryEditor=Editor de librerías

TemplateEditor=Editor de plantillas


WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Informe

ReportWizardDescription=Este asistente le ayuda a crear un nuevo informe BIRT a partir de una plantilla predefinida.

TemplateWizard=Plantilla

TemplateWizardDescription=Este asistente crea una nueva plantilla BIRT.

LibraryWizard=Librería

LibraryWizardDescription=Este asistente crea una nueva librería de informes BIRT.
