###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
About=Business Intelligence and Reporting Tools
ApplicationName=BIRT RCP Designer
ReportPerspective=BIRT RCP Designer
CHEAT_SHEETS=ガイドの表示
CHEAT_SHEETS_MENU=ガイドの表示(&C)...
ReportEditor=レポートエディタ
LibraryEditor=ライブラリエディタ
TemplateEditor=テンプレートエディタ

WizardCategoryName=ビジネスインテリジェンスおよびレポーティングツール
ReportWizard=レポート
ReportWizardDescription=このウィザードでは、定義済みのテンプレートを使って新しい BIRT レポートを作成します。
TemplateWizard=テンプレート
TemplateWizardDescription=このウィザードでは、新しい BIRT テンプレートを作成します。
LibraryWizard=ライブラリ
LibraryWizardDescription=このウィザードでは、新しい BIRT レポートライブラリを作成します。
