###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

About=Business Intelligence and Reporting Tools
ApplicationName=BIRT Report Designer
ReportPerspective=BIRT Report Designer
CHEAT_SHEETS=备忘单

CHEAT_SHEETS_MENU=备忘单(&C)...

ReportEditor=报表编辑器

ReportDocumentEditor=报表文档编辑器

LibraryEditor=库编辑器

TemplateEditor=模板编辑器


WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=报表

ReportWizardDescription=此向导使用预定义模板创建新的 BIRT 报表。

TemplateWizard=模板

TemplateWizardDescription=此向导创建新的 BIRT 模板。

LibraryWizard=库

LibraryWizardDescription=此向导创建新的 BIRT 报表库。
