###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

About=Business Intelligence and Reporting Tools
ApplicationName=BIRT Report Designer
ReportPerspective=BIRT Report Designer
CHEAT_SHEETS=치트 시트

CHEAT_SHEETS_MENU=치트 시트(&C)...

ReportEditor=보고서 편집기

ReportDocumentEditor=보고서 문서 편집기

LibraryEditor=라이브러리 편집기

TemplateEditor=템플릿 편집기


WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=보고서

ReportWizardDescription=이 마법사는 미리 정의된 템플릿에서 새 BIRT 보고서를 생성합니다.

TemplateWizard=템플릿

TemplateWizardDescription=이 마법사는 새 BIRT 템플릿을 생성합니다.

LibraryWizard=라이브러리

LibraryWizardDescription=이 마법사는 새 BIRT 보고서 라이브러리를 생성합니다.
