###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

About=Business Intelligence and Reporting Tools
ApplicationName=BIRT Report Designer
ReportPerspective=BIRT Report Designer
CHEAT_SHEETS=Feuilles de fraude

CHEAT_SHEETS_MENU=&Feuilles de fraude...

ReportEditor=Editeur d'état

ReportDocumentEditor=Editeur d'état

LibraryEditor=Editeur de bibliothèque

TemplateEditor=Editeur de modèles


WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Etat

ReportWizardDescription=Cet assistant crée un nouvel état BIRT à partir d'un modèle prédéfini.

TemplateWizard=Modèle

TemplateWizardDescription=Cet assistant crée un nouveau modèle BIRT.

LibraryWizard=Bibliothèque

LibraryWizardDescription=Cet assistant crée une nouvelle bibliothèque d'états BIRT.
