###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS Strings
#
plugin.name=BIRT Sample Database Connection Profile Plug-in
connection.profile.name=BIRT Classic Models 示例数据库
driver.template.name=BIRT SampleDb Derby Embedded JDBC Driver
driver.definition.name=BIRT SampleDb Derby 嵌入式驱动程序
#
driver.template.property.class = Driver class
driver.template.property.vendor = Vendor
driver.template.property.version = Version
driver.template.property.dbname = Database
driver.template.property.connection.url = Connection URL
driver.template.property.user = User name
driver.template.property.password = Password
