###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS Strings
#
plugin.name=BIRT Sample Database Connection Profile Plug-in
connection.profile.name=BIRT Classic Models Sample Database
driver.template.name=BIRT SampleDb Derby Embedded JDBC Driver
driver.definition.name=BIRT SampleDb Derby Embedded Driver
#
driver.template.property.class =Treiberklasse

driver.template.property.vendor =Anbieter

driver.template.property.version =Version

driver.template.property.dbname =Datenbank

driver.template.property.connection.url =Verbindungs-URL

driver.template.property.user =Benutzername

driver.template.property.password =Kennwort

driver.template.property.save.password =Kennwort speichern
