###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS Strings
#
plugin.name=BIRT Sample Database Connection Profile Plug-in
connection.profile.name=Base de datos de muestra BIRT Classic Models
driver.template.name=Controlador JDBC incrustado BIRT SampleDb Derby
driver.definition.name=Controlador incrustado BIRT SampleDb Derby
#
driver.template.property.class = Clase de controlador
driver.template.property.vendor = Proveedor
driver.template.property.version = Versión
driver.template.property.dbname = Base de datos
driver.template.property.connection.url = URL de conexión
driver.template.property.user = Nombre de usuario
driver.template.property.password = Contraseña
