###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS Strings
#
plugin.name=BIRT Sample Database Connection Profile Plug-in
connection.profile.name=BIRT Classic Models 샘플 데이터베이스
driver.template.name=BIRT SampleDb Derby 임베디드 JDBC 드라이버
driver.definition.name=BIRT SampleDb Derby 임베디드 드라이버
#
driver.template.property.class = 드라이버 클래스
driver.template.property.vendor = 공급업체
driver.template.property.version = 버전
driver.template.property.dbname = 데이터베이스
driver.template.property.connection.url = 연결 URL
driver.template.property.user = 사용자 이름
driver.template.property.password = 암호
