###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS Strings
#
plugin.name=BIRT Sample Database Connection Profile Plug-in
connection.profile.name=BIRT Classic Models Sample Database
driver.template.name=BIRT SampleDb Derby Embedded JDBC Driver
driver.definition.name=BIRT SampleDb Derby Embedded Driver
#
driver.template.property.class =ドライバクラス

driver.template.property.vendor =ベンダ

driver.template.property.version =バージョン

driver.template.property.dbname =データベース

driver.template.property.connection.url =接続 URL

driver.template.property.user =ユーザ名

driver.template.property.password =パスワード

driver.template.property.save.password =パスワードの保存
