SVGRendererImpl.exception.UnableToWriteChartImage={0}¿¡¼­ Á¤ÀÇµÈ SVG Ãâ·Â ÇÚµé¿¡ Â÷Æ® ÀÌ¹ÌÁö¸¦ ¾µ ¼ö ¾ø½À´Ï´Ù.

SVGGraphics2D.drawImage.image=SVG ·»´õ·¯ - drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawImage.buffer=SVG ·»´õ·¯ -drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2,\tint arg3) - Áö¿ø ¾ÈµÊ

SVGGraphics2D.drawRenderImage.RenderImage=SVG ·»´õ·¯ -drawRenderedImage(RenderedImage arg0, AffineTransform arg1) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawRenderableImage.RenderableImage=SVG ·»´õ·¯ - drawRenderableImage(RenderableImage arg0, AffineTransform arg1) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawString.StringInt=SVG ·»´õ·¯ - drawString(String arg0, int arg1, int arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawString.StringFloat=SVG ·»´õ·¯ - drawString(String arg0, float arg1, float arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawString.AttributeInt=SVG ·»´õ·¯ - drawString(AttributedCharacterIterator arg0, int arg1, int arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.drawString.AttributeFloat=SVG ·»´õ·¯ - drawString(AttributedCharacterIterator arg0, float arg1, float arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.hit.Rectangle=SVG ·»´õ·¯ - hit(Rectangle arg0, Shape arg1, boolean arg2) - Áö¿ø ¾È µÊ

SVGGraphics2D.getDeviceConfig=SVG ·»´õ·¯ - GraphicsConfiguration getDeviceConfiguration() - Áö¿ø ¾È µÊ

SVGGraphics2D.setComposite=SVG ·»´õ·¯ - setComposite(Composite arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.getRenderingHint.Key=SVG ·»´õ·¯ - getRenderingHint(Key arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.setRenderingHints.Map=SVG ·»´õ·¯ - setRenderingHints(Map arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.ddRenderingHints.Map=SVG ·»´õ·¯ - ddRenderingHints(Map arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.getRenderingHints=SVG ·»´õ·¯ - getRenderingHints() - Áö¿ø ¾È µÊ

SVGGraphics2D.transform.AffineTransform=SVG ·»´õ·¯ - transform(AffineTransform arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.setTransform.Affine=SVG ·»´õ·¯ - setTransform(AffineTransform arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.getTransform=SVG ·»´õ·¯ - AffineTransform getTransform() - Áö¿ø ¾È µÊ

SVGGraphics2D.getComposite=SVG ·»´õ·¯ - Composite getComposite() - Áö¿ø ¾È µÊ

SVGGraphics2D.setPaintMode=SVG ·»´õ·¯ - setPaintMode() - Áö¿ø ¾È µÊ

SVGGraphics2D.setXORModel.Color=SVG ·»´õ·¯ - setXORMode(Color arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.getFontMetrics.Font=SVG ·»´õ·¯ - FontMetrics getFontMetrics(Font arg0) - Áö¿ø ¾È µÊ

SVGGraphics2D.CopyArea.Int=SVG ·»´õ·¯ - CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) - Áö¿ø ¾È µÊ

SVGGraphics2D.clearRect.Int=SVG ·»´õ·¯ - clearRect(int arg0, int arg1, int arg2, int arg3)  - Áö¿ø ¾È µÊ

SVGGraphics2D.drawPolyline.Int=SVG ·»´õ·¯ - drawPolyline(int[] arg0, int[] arg1, int arg2) - Áö¿ø ¾È µÊ
