SVGRendererImpl.exception.UnableToWriteChartImage=Impossible d'écrire l'image du graphique vers le descripteur de sortie SVG défini par {0}

SVGGraphics2D.drawImage.image=Moteur de rendu SVG -drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) - non pris en charge

SVGGraphics2D.drawImage.buffer=Moteur de rendu SVG -drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2,\tint arg3) - non pris en charge

SVGGraphics2D.drawRenderImage.RenderImage=Moteur de rendu SVG -drawRenderedImage(RenderedImage arg0, AffineTransform arg1) - non pris en charge

SVGGraphics2D.drawRenderableImage.RenderableImage=Moteur de rendu SVG - drawRenderableImage(RenderableImage arg0, AffineTransform arg1) - non pris en charge

SVGGraphics2D.drawString.StringInt=Moteur de rendu SVG - drawString(String arg0, int arg1, int arg2) - non pris en charge

SVGGraphics2D.drawString.StringFloat=Moteur de rendu SVG - drawString(String arg0, float arg1, float arg2) - non pris en charge

SVGGraphics2D.drawString.AttributeInt=Moteur de rendu SVG - drawString(AttributedCharacterIterator arg0, int arg1, int arg2) - non pris en charge

SVGGraphics2D.drawString.AttributeFloat=Moteur de rendu SVG - drawString(AttributedCharacterIterator arg0, float arg1, float arg2) - non pris en charge

SVGGraphics2D.hit.Rectangle=Moteur de rendu SVG - hit(Rectangle arg0, Shape arg1, boolean arg2) - non pris en charge

SVGGraphics2D.getDeviceConfig=Moteur de rendu SVG - GraphicsConfiguration getDeviceConfiguration() - non pris en charge

SVGGraphics2D.setComposite=Moteur de rendu SVG - setComposite(Composite arg0) - non pris en charge

SVGGraphics2D.getRenderingHint.Key=Moteur de rendu SVG - getRenderingHint(Key arg0) - non pris en charge

SVGGraphics2D.setRenderingHints.Map=Moteur de rendu SVG - setRenderingHints(Map arg0) - non pris en charge

SVGGraphics2D.ddRenderingHints.Map=Moteur de rendu SVG - ddRenderingHints(Map arg0) - non pris en charge

SVGGraphics2D.getRenderingHints=Moteur de rendu SVG - getRenderingHints() - non pris en charge

SVGGraphics2D.transform.AffineTransform=Moteur de rendu SVG - transform(AffineTransform arg0) - non pris en charge

SVGGraphics2D.setTransform.Affine=Moteur de rendu SVG - setTransform(AffineTransform arg0) - non pris en charge

SVGGraphics2D.getTransform=Moteur de rendu SVG - AffineTransform getTransform() - non pris en charge

SVGGraphics2D.getComposite=Moteur de rendu SVG - Composite getComposite() - non pris en charge

SVGGraphics2D.setPaintMode=Moteur de rendu SVG - setPaintMode() - non pris en charge

SVGGraphics2D.setXORModel.Color=Moteur de rendu SVG - setXORMode(Color arg0) - non pris en charge

SVGGraphics2D.getFontMetrics.Font=Moteur de rendu SVG - FontMetrics getFontMetrics(Font arg0) - non pris en charge

SVGGraphics2D.CopyArea.Int=Moteur de rendu SVG - CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) - non pris en charge

SVGGraphics2D.clearRect.Int=Moteur de rendu SVG - clearRect(int arg0, int arg1, int arg2, int arg3) - non pris en charge

SVGGraphics2D.drawPolyline.Int=Moteur de rendu SVG - drawPolyline(int[] arg0, int[] arg1, int arg2) - non pris en charge
