SVGRendererImpl.exception.UnableToWriteChartImage=No es posible escribir la imagen del diagrama a un controlador de salida SVG definido por {0}

SVGGraphics2D.drawImage.image=Procesador SVG -drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) - no admitido

SVGGraphics2D.drawImage.buffer=Procesador SVG -drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2,\tint arg3) - no admitido

SVGGraphics2D.drawRenderImage.RenderImage=Procesador SVG -drawRenderedImage(RenderedImage arg0, AffineTransform arg1) - no admitido

SVGGraphics2D.drawRenderableImage.RenderableImage=Procesador SVG - drawRenderableImage(RenderableImage arg0, AffineTransform arg1) - no admitido

SVGGraphics2D.drawString.StringInt=Procesador SVG - drawString(String arg0, int arg1, int arg2) - no admitido

SVGGraphics2D.drawString.StringFloat=Procesador SVG - drawString(String arg0, float arg1, float arg2) - no admitido

SVGGraphics2D.drawString.AttributeInt=Procesador SVG - drawString(AttributedCharacterIterator arg0, int arg1, int arg2) - no admitido

SVGGraphics2D.drawString.AttributeFloat=Procesador SVG - drawString(AttributedCharacterIterator arg0, float arg1, float arg2) - no admitido

SVGGraphics2D.hit.Rectangle=Procesador SVG - hit(Rectangle arg0, Shape arg1, boolean arg2) - no admitido

SVGGraphics2D.getDeviceConfig=Procesador SVG - GraphicsConfiguration getDeviceConfiguration() - no admitido

SVGGraphics2D.setComposite=Procesador SVG - setComposite(Composite arg0) - no admitido

SVGGraphics2D.getRenderingHint.Key=Procesador SVG - getRenderingHint(Key arg0) - no admitido

SVGGraphics2D.setRenderingHints.Map=Procesador SVG - setRenderingHints(Map arg0) - no admitido

SVGGraphics2D.ddRenderingHints.Map=Procesador SVG - ddRenderingHints(Map arg0) - no admitido

SVGGraphics2D.getRenderingHints=Procesador SVG - getRenderingHints() - no admitido

SVGGraphics2D.transform.AffineTransform=Procesador SVG - transform(AffineTransform arg0) - no admitido

SVGGraphics2D.setTransform.Affine=Procesador SVG - setTransform(AffineTransform arg0) - no admitido

SVGGraphics2D.getTransform=Procesador SVG - AffineTransform getTransform() - no admitido

SVGGraphics2D.getComposite=Procesador SVG - Composite getComposite() - no admitido

SVGGraphics2D.setPaintMode=Procesador SVG - setPaintMode() - no admitido

SVGGraphics2D.setXORModel.Color=Procesador SVG - setXORMode(Color arg0) - no admitido

SVGGraphics2D.getFontMetrics.Font=Procesador SVG - FontMetrics getFontMetrics(Font arg0) - no admitido

SVGGraphics2D.CopyArea.Int=Procesador SVG - CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) - no admitido

SVGGraphics2D.clearRect.Int=Procesador SVG - clearRect(int arg0, int arg1, int arg2, int arg3)  - no admitido

SVGGraphics2D.drawPolyline.Int=Procesador SVG - drawPolyline(int[] arg0, int[] arg1, int arg2) - no admitido
