SVGRendererImpl.exception.UnableToWriteChartImage=Diagrammbild konnte nicht in durch {0} definiertes SVG-Ausgabe-Handle geschrieben werden

SVGGraphics2D.drawImage.image=SVG-Renderer – drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) – nicht unterstützt

SVGGraphics2D.drawImage.buffer=SVG-Renderer – drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2.\tint arg3) – nicht unterstützt

SVGGraphics2D.drawRenderImage.RenderImage=SVG-Renderer – drawRenderedImage(RenderedImage arg0, AffineTransform arg1) – nicht unterstützt

SVGGraphics2D.drawRenderableImage.RenderableImage=SVG-Renderer – drawRenderableImage(RenderableImage arg0, AffineTransform arg1) – nicht unterstützt

SVGGraphics2D.drawString.StringInt=SVG-Renderer – drawString(String arg0, int arg1, int arg2) – nicht unterstützt

SVGGraphics2D.drawString.StringFloat=SVG-Renderer – drawString(String arg0, float arg1, float arg2) – nicht unterstützt

SVGGraphics2D.drawString.AttributeInt=SVG-Renderer – drawString(AttributedCharacterIterator arg0, int arg1, int arg2) – nicht unterstützt

SVGGraphics2D.drawString.AttributeFloat=SVG-Renderer – drawString(AttributedCharacterIterator arg0, float arg1, float arg2) – nicht unterstützt

SVGGraphics2D.hit.Rectangle=SVG-Renderer – hit(Rectangle arg0, Shape arg1, boolean arg2) – nicht unterstützt

SVGGraphics2D.getDeviceConfig=SVG-Renderer – GraphicsConfiguration getDeviceConfiguration() – nicht unterstützt

SVGGraphics2D.setComposite=SVG-Renderer – setComposite(Composite arg0) – nicht unterstützt

SVGGraphics2D.getRenderingHint.Key=SVG-Renderer – getRenderingHint(Key arg0) – nicht unterstützt

SVGGraphics2D.setRenderingHints.Map=SVG-Renderer – setRenderingHints(Map arg0) – nicht unterstützt

SVGGraphics2D.ddRenderingHints.Map=SVG-Renderer – ddRenderingHints(Map arg0) – nicht unterstützt

SVGGraphics2D.getRenderingHints=SVG-Renderer – getRenderingHints() – nicht unterstützt

SVGGraphics2D.transform.AffineTransform=SVG-Renderer – transform(AffineTransform arg0) – nicht unterstützt

SVGGraphics2D.setTransform.Affine=SVG-Renderer – setTransform(AffineTransform arg0) – nicht unterstützt

SVGGraphics2D.getTransform=SVG-Renderer – AffineTransform getTransform() – nicht unterstützt

SVGGraphics2D.getComposite=SVG-Renderer – Composite getComposite() – nicht unterstützt

SVGGraphics2D.setPaintMode=SVG-Renderer – setPaintMode() – nicht unterstützt

SVGGraphics2D.setXORModel.Color=SVG-Renderer – setXORMode(Color arg0) – nicht unterstützt

SVGGraphics2D.getFontMetrics.Font=SVG-Renderer – FontMetrics getFontMetrics(Font arg0) – nicht unterstützt

SVGGraphics2D.CopyArea.Int=SVG-Renderer – CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) – nicht unterstützt

SVGGraphics2D.clearRect.Int=SVG-Renderer – clearRect(int arg0, int arg1, int arg2, int arg3) – nicht unterstützt

SVGGraphics2D.drawPolyline.Int=SVG-Renderer – drawPolyline(int[] arg0, int[] arg1, int arg2) – nicht unterstützt
