SVGRendererImpl.exception.UnableToWriteChartImage=无法将图表图像写入由 {0} 定义的 SVG 输出句柄

SVGGraphics2D.drawImage.image=SVG 呈现器 - rawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) - 不支持

SVGGraphics2D.drawImage.buffer=SVG 呈现器 - drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2,\tint arg3) - 不支持

SVGGraphics2D.drawRenderImage.RenderImage=SVG 呈现器 - drawRenderedImage(RenderedImage arg0, AffineTransform arg1) - 不支持

SVGGraphics2D.drawRenderableImage.RenderableImage=SVG 呈现器 - drawRenderableImage(RenderableImage arg0, AffineTransform arg1) - 不支持

SVGGraphics2D.drawString.StringInt=SVG 呈现器 - drawString(String arg0, int arg1, int arg2) - 不支持

SVGGraphics2D.drawString.StringFloat=SVG 呈现器 - drawString(String arg0, float arg1, float arg2) - 不支持

SVGGraphics2D.drawString.AttributeInt=SVG 呈现器 - drawString(AttributedCharacterIterator arg0, int arg1, int arg2) - 不支持

SVGGraphics2D.drawString.AttributeFloat=SVG 呈现器 - drawString(AttributedCharacterIterator arg0, float arg1, float arg2) - 不支持

SVGGraphics2D.hit.Rectangle=SVG 呈现器 - hit(Rectangle arg0, Shape arg1, boolean arg2) - 不支持

SVGGraphics2D.getDeviceConfig=SVG 呈现器 - GraphicsConfiguration getDeviceConfiguration() - 不支持

SVGGraphics2D.setComposite=SVG 呈现器 - setComposite(Composite arg0) - 不支持

SVGGraphics2D.getRenderingHint.Key=SVG 呈现器 - getRenderingHint(Key arg0) - 不支持

SVGGraphics2D.setRenderingHints.Map=SVG 呈现器 - setRenderingHints(Map arg0) - 不支持

SVGGraphics2D.ddRenderingHints.Map=SVG 呈现器 - ddRenderingHints(Map arg0) - 不支持

SVGGraphics2D.getRenderingHints=SVG 呈现器 - getRenderingHints() - 不支持

SVGGraphics2D.transform.AffineTransform=SVG 呈现器 - transform(AffineTransform arg0) - 不支持

SVGGraphics2D.setTransform.Affine=SVG 呈现器 - setTransform(AffineTransform arg0) - 不支持

SVGGraphics2D.getTransform=SVG 呈现器 - AffineTransform getTransform() - 不支持

SVGGraphics2D.getComposite=SVG 呈现器 - Composite getComposite() - 不支持

SVGGraphics2D.setPaintMode=SVG 呈现器 - setPaintMode() - 不支持

SVGGraphics2D.setXORModel.Color=SVG 呈现器 - setXORMode(Color arg0) - 不支持

SVGGraphics2D.getFontMetrics.Font=SVG 呈现器 - FontMetrics getFontMetrics(Font arg0) - 不支持

SVGGraphics2D.CopyArea.Int=SVG 呈现器 - CcopyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) - 不支持

SVGGraphics2D.clearRect.Int=SVG 呈现器 - clearRect(int arg0, int arg1, int arg2, int arg3)  - 不支持

SVGGraphics2D.drawPolyline.Int=SVG 呈现器 - drawPolyline(int[] arg0, int[] arg1, int arg2) - 不支持
