# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.


###########################################################
#for test only
Error.Msg001={1}에 {0}이(가) 없습니다.

###########################################################
# Boolean type names
Property.Boolean.True=참

Property.Boolean.False=거짓

###########################################################
# Property type names
Property.boolean=부울

Property.choice=선택

Property.float=고정 해제

Property.color=색

Property.dateTime=DateTime
Property.dimension=차원

Property.expression=식

Property.html=Html
Property.integer=정수

Property.messageId=메시지 ID

Property.name=이름

Property.number=숫자

Property.points=포인트

Property.string=문자열

Property.uri=Uri
Property.xml=Xml
Property.elementRef=요소 참조

Property.column=열

Property.variant=변형

Property.structList=구조 목록

Property.extends=확장

Property.script=스크립트

Property.list=목록

Property.memberKey=구성원 키

Property.literalString=리터럴 문자열

Property.element=요소

Property.structRef=구조 참조

Property.contentElement=속성 값 요소

Property.locale=로케일

Property.struct=구조

###########################################################
# Choice values
  
#0.colors
Choices.colors.maroon=적갈색

Choices.colors.red=빨강

Choices.colors.orange=주황

Choices.colors.yellow=노랑

Choices.colors.olive=올리브

Choices.colors.purple=자주

Choices.colors.fuchsia=밝은 자홍

Choices.colors.white=흰색

Choices.colors.lime=라임

Choices.colors.green=녹색

Choices.colors.navy=짙은 파랑

Choices.colors.blue=파랑

Choices.colors.aqua=바다색

Choices.colors.teal=청록

Choices.colors.black=검정

Choices.colors.silver=은색

Choices.colors.gray=회색
  
#1.fontWeight
Choices.fontWeight.normal=기본

Choices.fontWeight.bold=굵게

Choices.fontWeight.bolder=더 굵게

Choices.fontWeight.lighter=더 얇게

Choices.fontWeight.100=100

Choices.fontWeight.200=200

Choices.fontWeight.300=300

Choices.fontWeight.400=400

Choices.fontWeight.500=500

Choices.fontWeight.600=600

Choices.fontWeight.700=700

Choices.fontWeight.800=800

Choices.fontWeight.900=900

#2.textUnderline
Choices.textUnderline.none=밑줄 없음

Choices.textUnderline.underline=밑줄
  
#3.lineStyle
Choices.lineStyle.none=선 스타일 없음

Choices.lineStyle.solid=실선

Choices.lineStyle.dotted=굵은 점선

Choices.lineStyle.dashed=파선

Choices.lineStyle.double=이중 실선

Choices.lineStyle.groove=홈 음각

Choices.lineStyle.ridge=홈 양각

Choices.lineStyle.inset=음각

Choices.lineStyle.outset=양각
  
#4.units
Choices.units.in=인치

Choices.units.cm=cm

Choices.units.mm=mm

Choices.units.pt=points

Choices.units.pc=picas

Choices.units.em=ems

Choices.units.ex=exs

Choices.units.px=픽셀

Choices.units.%=%

#5.paramDataType
Choices.paramType.string=문자열

Choices.paramType.float=실수

Choices.paramType.decimal=십진수

Choices.paramType.dateTime=날짜 시간

Choices.paramType.boolean=부울

Choices.paramType.integer=정수

Choices.paramType.any=모두

Choices.paramType.date=날짜

Choices.paramType.time=시간

Choices.paramType.javaObject=Java 개체

#6.paramControl
Choices.paramControl.text-box=텍스트 상자

Choices.paramControl.list-box=콤보/목록 상자

Choices.paramControl.radio-button=라디오 단추

Choices.paramControl.check-box=확인란

Choices.paramControl.auto-suggest=입력란 - 자동 제안

#7.textAlign
Choices.textAlign.left=왼쪽

Choices.textAlign.center=가운데

Choices.textAlign.right=오른쪽

Choices.textAlign.justify=양쪽 맞춤
  
#8.pageSize
Choices.pageSize.custom=사용자 지정

Choices.pageSize.us-letter=US Letter

Choices.pageSize.us-legal=US Legal

Choices.pageSize.a4=A4
Choices.pageSize.a3=A3
Choices.pageSize.a5=A5
Choices.pageSize.us-ledger=US Ledger

Choices.pageSize.us-super-b=US Super B
  
#9.pageOrientation
Choices.pageOrientation.auto=자동

Choices.pageOrientation.portrait=세로

Choices.pageOrientation.landscape=가로
   
#12.interval
Choices.interval.none=간격 없음

Choices.interval.prefix=접두사

Choices.interval.year=연

Choices.interval.quarter=분기

Choices.interval.month=월

Choices.interval.week=주

Choices.interval.day=일

Choices.interval.hour=시

Choices.interval.minute=분

Choices.interval.second=초

Choices.interval.interval=간격

#interval type
Choices.intervalType.none=간격 없음

Choices.intervalType.prefix=접두사

Choices.intervalType.interval=간격

#13.sortDirection
Choices.sortDirection.asc=오름차순

Choices.sortDirection.desc=내림차순
  
#14.mapOperator
Choices.mapOperator.eq=같음

Choices.mapOperator.ne=같지 않음

Choices.mapOperator.lt=작음

Choices.mapOperator.le=작거나 같음

Choices.mapOperator.ge=크거나 같음

Choices.mapOperator.gt=큼

Choices.mapOperator.between=사이에 있음

Choices.mapOperator.notBetween=사이에 있지 않음

Choices.mapOperator.isNull=널(null)임

Choices.mapOperator.isNotNull=널(null)이 아님

Choices.mapOperator.isTrue=참

Choices.mapOperator.isFalse=거짓

Choices.mapOperator.like=유사

Choices.mapOperator.match=일치

Choices.mapOperator.any=모두

Choices.mapOperator.top-n=상위 n

Choices.mapOperator.bottom-n=하위 n

Choices.mapOperator.top-percent=상위 퍼센트

Choices.mapOperator.bottom-percent=하위 퍼센트

Choices.mapOperator.not-like=유사하지 않음

Choices.mapOperator.not-match=일치하지 않음

Choices.mapOperator.not-in=NOT IN

Choices.mapOperator.in=포함
  
#15.imageRefType
Choices.imageRefType.none=이미지 없음

Choices.imageRefType.url=URL
Choices.imageRefType.file=파일

Choices.imageRefType.expr=식

Choices.imageRefType.embed=내장된 이미지
  
#16.imageSize
Choices.imageSize.size-to-image=Size to Image

Choices.imageSize.scale-to-item=Scale to Item

Choices.imageSize.clip=자르기
  
#17.lineOrientation
Choices.lineOrientation.horizontal=가로

Choices.lineOrientation.vertical=세로
  
#18.rowAlign
Choices.rowAlign.top=위쪽

Choices.rowAlign.middle=중간

Choices.rowAlign.bottom=아래쪽
  
#19.sectionAlign
Choices.sectionAlign.left=왼쪽

Choices.sectionAlign.center=가운데

Choices.sectionAlign.right=오른쪽
  
#21.dropType
Choices.dropType.none=없음

Choices.dropType.detail=상세 정보

Choices.dropType.all=모두
    
#22.imageType
Choices.imageType.image/bmp=image/bmp

Choices.imageType.image/gif=image/gif

Choices.imageType.image/png=image/png

Choices.imageType.image/x-png=image/x-png

Choices.imageType.image/jpeg=image/jpeg

Choices.imageType.image/ico=이미지/ico

Choices.imageType.image/tiff=이미지/tiff

Choices.imageType.image/svg+xml=이미지/svg+xml

Choices.imageType.image/x-icon=이미지/x 아이콘
  
#23.lineSpacing
Choices.lineSpacing.lines=줄

Choices.lineSpacing.exact=정확히
  
#24.lineType
Choices.lineType.none=선 형식 없음

Choices.lineType.solid=실선

Choices.lineType.dotted=굵은 점선

Choices.lineType.dashed=파선

Choices.lineType.double=이중 실선
  
#25.pageBreakBefore
Choices.pageBreakBefore.auto=자동

Choices.pageBreakBefore.always=항상

Choices.pageBreakBefore.avoid=피하기

Choices.pageBreakBefore.alwaysExcludingFirst=항상 먼저 제외하기

#26.pageBreakAfter
Choices.pageBreakAfter.auto=자동

Choices.pageBreakAfter.always=항상

Choices.pageBreakAfter.avoid=피하기

Choices.pageBreakAfter.alwaysExcludingLast=항상 마지막에 제외하기

#27.actionLinkType
Choices.actionLinkType.none=작업 링크 형식 없음

Choices.actionLinkType.hyperlink=HyperLink
Choices.actionLinkType.drill-through=확장

Choices.actionLinkType.bookmark-link=책갈피 링크
  
# actionFormatType
Choices.actionFormatType.html=html
Choices.actionFormatType.pdf=pdf
  
#28.drillThroughLinkType
Choices.drillThroughType.none=드릴스루 형식 없음

Choices.drillThroughType.bookmark-link=책갈피 링크

Choices.drillThroughType.search=검색
 
#29.fontSize
Choices.fontSize.x-small=매우 작음(X Small)

Choices.fontSize.xx-small=가장 작음(XX Small)

Choices.fontSize.small=작음

Choices.fontSize.medium=중간

Choices.fontSize.large=큼

Choices.fontSize.x-large=매우 큼(X Large)

Choices.fontSize.xx-large=가장 큼(XX Large)

Choices.fontSize.larger=크게

Choices.fontSize.smaller=작게

#30.fontFamily
Choices.fontFamily.serif=Serif

Choices.fontFamily.sans-serif=Sans Serif

Choices.fontFamily.cursive=Cursive

Choices.fontFamily.fantasy=Fantasy

Choices.fontFamily.monospace=Monospace

#31.fontStyle
Choices.fontStyle.normal=기본

Choices.fontStyle.italic=기울임꼴

Choices.fontStyle.oblique=오블리크

#32.fontVariant
Choices.fontVariant.normal=기본

Choices.fontVariant.small-caps=소문자를 작은 대문자로

#33.backgroundRepeat
Choices.backgroundRepeat.repeat=반복

Choices.backgroundRepeat.repeat-x=X 반복

Choices.backgroundRepeat.repeat-y=Y 반복

Choices.backgroundRepeat.no-repeat=반복 없음

#34.backgroundAttachment
Choices.backgroundAttachment.scroll=스크롤

Choices.backgroundAttachment.fixed=고정

#35.backgroundPositionX
Choices.backgroundPositionX.left=왼쪽

Choices.backgroundPositionX.center=가운데

Choices.backgroundPositionX.right=오른쪽

#36.backgroundPositionY
Choices.backgroundPositionY.top=위쪽

Choices.backgroundPositionY.center=가운데

Choices.backgroundPositionY.bottom=아래쪽

#37.transform
Choices.transform.capitalize=첫 글자를 대문자로

Choices.transform.uppercase=대문자

Choices.transform.lowercase=소문자

Choices.transform.none=변환 없음

#38.normal
Choices.normal.normal=기본

#39.verticalAlign
Choices.verticalAlign.baseline=기준선

Choices.verticalAlign.sub=아래 첨자

Choices.verticalAlign.super=위 첨자

Choices.verticalAlign.top=위쪽

Choices.verticalAlign.text-top=텍스트 위쪽

Choices.verticalAlign.middle=중간

Choices.verticalAlign.bottom=아래쪽

Choices.verticalAlign.text-bottom=텍스트 아래쪽

#40.whiteSpace
Choices.whiteSpace.normal=기본

Choices.whiteSpace.pre=서식 설정되어 있음

Choices.whiteSpace.nowrap=배치 안함

#41.display
Choices.display.block=블록

Choices.display.inline=인라인

Choices.display.none=표시 없음

#43.pageBreakInside
Choices.pageBreakInside.avoid=피하기

Choices.pageBreakInside.auto=자동

#44.margin
Choices.margine.auto=자동

#45.textOverline
Choices.textOverline.none=텍스트 위에 줄 없음

Choices.textOverline.overline=윗줄

#46.textLineThrough
Choices.textLineThrough.none=텍스트 가운데에 줄 없음

Choices.textLineThrough.line-through=가운데 줄

#48.lineWidth
Choices.lineWidth.thin=가늘게

Choices.lineWidth.medium=중간

Choices.lineWidth.thick=굵게

#49.inherit
Choices.inherit.inherit=상속

#50. textContentType
Choices.textContentType.auto=자동

Choices.textContentType.plain=일반

Choices.textContentType.html=HTML
Choices.textContentType.rtf=RTF

#51. formatType
Choices.formatType.all=모두

Choices.formatType.viewer=뷰어

Choices.formatType.email=전자 메일

Choices.formatType.print=인쇄

Choices.formatType.pdf=Pdf

Choices.formatType.rtf=Rtf

Choices.formatType.reportlet=리포틀릿

Choices.formatType.excel=Excel
Choices.formatType.word=Word
Choices.formatType.powerpoint=Powerpoint

#52. filterOperator
Choices.filterOperator.eq=같음

Choices.filterOperator.ne=같지 않음

Choices.filterOperator.lt=작음

Choices.filterOperator.le=작거나 같음

Choices.filterOperator.ge=크거나 같음

Choices.filterOperator.gt=큼

Choices.filterOperator.between=사이에 있음

Choices.filterOperator.notBetween=사이에 있지 않음

Choices.filterOperator.isNull=Null

Choices.filterOperator.isNotNull=Null이 아님

Choices.filterOperator.isTrue=참

Choices.filterOperator.isFalse=거짓

Choices.filterOperator.like=유사

Choices.filterOperator.not-like=유사하지 않음

Choices.filterOperator.top-n=위쪽 n

Choices.filterOperator.bottom-n=아래쪽 n

Choices.filterOperator.top-percent=위쪽 퍼센트

Choices.filterOperator.bottom-percent=아래쪽 퍼센트

Choices.filterOperator.any=모두

Choices.filterOperator.match=일치

Choices.filterOperator.not-match=일치하지 않음

Choices.filterOperator.in=포함

Choices.filterOperator.not-in=포함 안 함

#53. propertyMaskType
Choices.propertyMaskType.change=변경

Choices.propertyMaskType.lock=잠금

Choices.propertyMaskType.hide=숨기기

#53. columnDataType
Choices.columnDataType.any=모두

Choices.columnDataType.integer=정수

Choices.columnDataType.string=문자열

Choices.columnDataType.date-time=날짜 시간

Choices.columnDataType.decimal=십진수

Choices.columnDataType.float=실수

Choices.columnDataType.structure=구조

Choices.columnDataType.table=테이블

Choices.columnDataType.boolean=부울

Choices.columnDataType.time=시간

Choices.columnDataType.date=날짜

Choices.columnDataType.blob=Blob

Choices.columnDataType.javaObject=Java 개체

#54. searchType
Choices.searchType.any=모두

Choices.searchType.indexed=인덱스된

Choices.searchType.none=검색 형식 없음

#55. exportType
Choices.exportType.none=내보내기 형식 없음

Choices.exportType.if-realized=인식된 경우

Choices.exportType.always=항상

#56. analysisType
Choices.analysisType.dimension=차원

Choices.analysisType.attribute=특성

Choices.analysisType.measure=측정

#57. scalarParamAlign
Choices.scalarParamAlign.auto=자동

Choices.scalarParamAlign.left=왼쪽

Choices.scalarParamAlign.center=가운데

Choices.scalarParamAlign.right=오른쪽

#58. columnAlign
Choices.columnAlign.left=왼쪽

Choices.columnAlign.center=가운데

Choices.columnAlign.right=오른쪽

#59. dateTimeFormat
Choices.dateTimeFormat.unformatted=형식 없음

Choices.dateTimeFormat.generalDate=일반 날짜

Choices.dateTimeFormat.longDate=긴 날짜

Choices.dateTimeFormat.mediumDate=중간 날짜

Choices.dateTimeFormat.shortDate=짧은 날짜

Choices.dateTimeFormat.longTime=긴 시간

Choices.dateTimeFormat.mediumTime=중간 시간

Choices.dateTimeFormat.shortTime=짧은 시간

Choices.dateTimeFormat.custom=사용자 지정

#59. dateFormat
Choices.dateFormat.unformatted=형식 없음

Choices.dateFormat.generalDate=일반 날짜

Choices.dateFormat.longDate=긴 날짜

Choices.dateFormat.mediumDate=중간 날짜

Choices.dateFormat.shortDate=짧은 날짜

Choices.dateFormat.custom=사용자 지정

#59. timeFormat
Choices.timeFormat.unformatted=형식 없음

Choices.timeFormat.longTime=긴 시간

Choices.timeFormat.mediumTime=중간 시간

Choices.timeFormat.shortTime=짧은 시간

Choices.timeFormat.custom=사용자 지정
    
#60. numberFormat
Choices.numberFormat.unformatted=형식 없음

Choices.numberFormat.generalNumber=일반 숫자

Choices.numberFormat.currency=통화

Choices.numberFormat.fixed=고정

Choices.numberFormat.percent=백분율

Choices.numberFormat.scientific=공학용

Choices.numberFormat.standard=표준

Choices.numberFormat.custom=사용자 지정
    
#59. StringFormat
Choices.stringFormat.unformatted=형식 없음

Choices.stringFormat.upper=대문자

Choices.stringFormat.lower=소문자

Choices.stringFormat.zipCode=우편 번호

Choices.stringFormat.zipCode+4=우편 번호 + 4

Choices.stringFormat.phoneNumber=전화 번호

Choices.stringFormat.socialSecurityNumber=주민등록번호

Choices.stringFormat.custom=사용자 지정

#60. targetNames
Choices.targetNames.blank=비어 있음

Choices.targetNames.self=자체

Choices.targetNames.parent=상위

Choices.targetNames.top=위쪽

#50. textDataContentType
Choices.textDataContentType.auto=자동

Choices.textDataContentType.plain=일반

Choices.textDataContentType.html=HTML
Choices.textDataContentType.rtf=RTF

#51. paramaValueType
Choices.paramValueType.static=정적

Choices.paramValueType.dynamic=동적

#52. templateElementType
Choices.templateElementType.table=테이블

Choices.templateElementType.freeForm=FreeForm
Choices.templateElementType.data=데이터

Choices.templateElementType.grid=눈금

Choices.templateElementType.image=이미지

Choices.templateElementType.label=레이블

Choices.templateElementType.list=목록

Choices.templateElementType.text=텍스트

Choices.templateElementType.extendedItem=ExtendedItem
Choices.templateElementType.textData=TextData
Choices.templateElementType.dataSet=데이터 집합

#61. sortType
Choices.sortType.none=정렬 형식 없음

Choices.sortType.sortOnGroupkey=그룹 키 정렬

Choices.sortType.complexSort=복합 정렬

#62. joinType
Choices.joinType.inner=내부 조인

Choices.joinType.leftOut=왼쪽 외부 조인

Choices.joinType.rightOut=오른쪽 외부 조인

Choices.joinType.fullOut=완전 외부 조인

#63. joinOperator
Choices.joinOperator.equals=같음

#64. actionTargetFileType
Choices.actionTargetFileType.report-design=보고서 디자인

Choices.actionTargetFileType.report-document=보고서 문서

#65. actionBookmarkType
Choices.actionBookmarkType.bookmark=책갈피

Choices.actionBookmarkType.toc=목차

#66. autoTextType
Choices.autoTextType.page-number=페이지 번호

Choices.autoTextType.total-page=전체 페이지

Choices.autoTextType.page-number-unfiltered=필터링되지 않은 페이지 번호

Choices.autoTextType.total-page-unfiltered=필터링되지 않은 전체 페이지

Choices.autoTextType.page-variable=페이지 변수

#67. dataSetMode
Choices.dataSetMode.single=단일 데이터 집합

Choices.dataSetMode.multiple=다중 데이터 집합

#68. filterTarget
Choices.filterTarget.DataSet=데이터 집합

Choices.filterTarget.ResultSet=결과 집합

Choices.filterTarget.OdaDataSet=ODA 데이터 집합

#69. viewAction
Choices.viewAction.NoChange=변경 사항 없음

Choices.viewAction.Changed=변경됨

Choices.viewAction.Added=추가됨

Choices.viewAction.Deleted=삭제됨

#70. aggregationFunction
Choices.aggregationFunction.sum=SUM

Choices.aggregationFunction.count=COUNT

Choices.aggregationFunction.min=MIN

Choices.aggregationFunction.max=MAX

Choices.aggregationFunction.average=AVERAGE

Choices.aggregationFunction.weighted-avg=WEIGHTEDAVG

Choices.aggregationFunction.stddev=STDDEV

Choices.aggregationFunction.first=FIRST

Choices.aggregationFunction.last=LAST

Choices.aggregationFunction.mode=MODE

Choices.aggregationFunction.moving-ave=MOVINGAVE

Choices.aggregationFunction.median=MEDIAN

Choices.aggregationFunction.variance=VARIANCE

Choices.aggregationFunction.running-sum=RUNNINGSUM

Choices.aggregationFunction.irr=IRR

Choices.aggregationFunction.mirr=MIRR

Choices.aggregationFunction.npv=NPV

Choices.aggregationFunction.running-npv=RUNNINGNPV

Choices.aggregationFunction.count-distinct=COUNTDISTINCT

Choices.aggregationFunction.running-count=RUNNINGCOUNT

Choices.aggregationFunction.is-top-n=IS-TOP-N

Choices.aggregationFunction.is-bottom-n=IS-BOTTOM-N

Choices.aggregationFunction.is-top-n-percent=IS-TOP-N-PERCENT

Choices.aggregationFunction.is-bottom-n-percent=IS-BOTTOM-N-PERCENT

Choices.aggregationFunction.percent-rank=PERCENT-RANK

Choices.aggregationFunction.percentile=PERCENTILE

Choices.aggregationFunction.quartile=QUARTILE

Choices.aggregationFunction.percent-sum=PERCENT-SUM

Choices.aggregationFunction.rank=RANK

#71. levelType
Choices.levelType.dynamic=동적

Choices.levelType.mirrored=미러

#72. accessPermission
Choices.accessPermission.allow=허용

Choices.accessPermission.disallow=허용 안 함

#73. paramSortValues
Choices.paramSortValues.value=값

Choices.paramSortValues.label=표시 텍스트

#74. reportLayoutPreference
Choices.reportLayoutPreference.fixedLayout=고정된 레이아웃

Choices.reportLayoutPreference.autoLayout=자동 레이아웃

#75. dateTimeLevelType
Choices.dateTimeLevelType.year=연

Choices.dateTimeLevelType.month=월

Choices.dateTimeLevelType.quarter=분기

Choices.dateTimeLevelType.weekOfMonth=한 달의 주

Choices.dateTimeLevelType.weekOfYear=한 해의 주

Choices.dateTimeLevelType.dayOfWeek=한 주의 날

Choices.dateTimeLevelType.dayOfMonth=한 달의 날

Choices.dateTimeLevelType.dayOfYear=한 해의 날

Choices.dateTimeLevelType.hour=시

Choices.dateTimeLevelType.minute=분

Choices.dateTimeLevelType.second=초

#76. scalarParamType
Choices.scalarParamType.simple=단순

Choices.scalarParamType.multi-value=복수 값

#77. bidiLayoutOrientation   
Choices.bidiDirection.rtl=오른쪽에서 왼쪽

Choices.bidiDirection.ltr=왼쪽에서 오른쪽

#78. backgroundSize
Choices.backgroundSize.auto=자동

Choices.backgroundSize.contain=포함

Choices.backgroundSize.cover=덮어쓰기

#79 scopeType
Choices.scopeType.row=행

Choices.scopeType.col=열

Choices.scopeType.rowgroup=행 그룹

Choices.scopeType.colgroup=열 그룹

#80 dynamicFilterChoice
Choices.dynamicFilterChoice.simple=단순

Choices.dynamicFilterChoice.advanced=고급

#81 variableType
Choices.variableType.report=보고서 변수

Choices.variableType.page=페이지 변수

#82 nullValueOrderingType
Choices.nullValueOrderingType.unknown=알 수 없음

Choices.nullValueOrderingType.nullIsFirst=Nulls First

Choices.nullValueOrderingType.nullIsLast=Nulls Last

#83 dataVersion
Choices.dataVersion.transient=임시

Choices.dataVersion.latest=최신

#84 selectorType
Choices.selectorType.list=목록

Choices.selectorType.dropdown=드롭다운

Choices.selectorType.slider=슬라이더

Choices.selectorType.checkBox=확인란

Choices.selectorType.radioButton=RadioButton
Choices.selectorType.textBox=텍스트 상자

Choices.selectorType.calendar=달력

Choices.selectorType.currentSelections=현재 선택한 항목

#85 thumbType
Choices.thumbType.single=단일

Choices.thumbType.dual=이중

#86
Choices.accessType.transient=임시

Choices.accessType.latest=최신

Choices.accessType.specificVersion=SpecificVersion

#87 overflow
Choices.overflow.visible=표시

Choices.overflow.hidden=숨김

Choices.overflow.scroll=스크롤

Choices.overflow.auto=자동

#88 GadgetContentType
Choices.gadgetContentType.html=HTML
Choices.gadgetContentType.url=URL
Choices.gadgetContentType.video=비디오

Choices.gadgetContentType.videourl=비디오 URL

Choices.gadgetContentType.text=텍스트

Choices.gadgetContentType.image=이미지

#89 WindowStatus
Choices.windowStatus.normal=기본

Choices.windowStatus.maximized=최대화

#90 reportItemThemeType
Choices.reportItemThemeType.Table=테이블 테마

Choices.reportItemThemeType.List=목록 테마

Choices.reportItemThemeType.Grid=눈금 테마

#91 nullsOrdering
Choices.nullsOrdering.nullsLowest=널(Null) 최하위

Choices.nullsOrdering.nullsHighest=널(null) 최상위

Choices.nullsOrdering.excludeNulls=널(Null) 제외

#92 filterConditionType
Choices.filterConditionType.slicer=슬라이서

Choices.filterConditionType.simple=단순

#93 flyoutPosition
Choices.flyoutPosition.left=왼쪽

Choices.flyoutPosition.right=오른쪽

#94 referenceDateType
Choices.referenceDateType.today=오늘

Choices.referenceDateType.fixedDate=고정일

Choices.referenceDateType.endingDateInDimension=차원의 종료일

###########################################################
# Classes

Class.optionalArgument=...

#0.String
Class.String=문자열 함수

Class.String.toolTip=객체 형식의 구성원이며 기본 제공 문자열 객체 인스턴스입니다

Class.String.String=문자열

Class.String.String.toolTip=ToString(값)에서 계산된 문자열 값을 반환합니다

Class.String.length=길이

Class.String.length.toolTip=문자열의 길이를 반환합니다

Class.String.fromCharCode=fromCharCode
Class.String.fromCharCode.toolTip=유니코드 문자 값에서 문자열을 반환합니다

Class.String.charAt=charAt

Class.String.charAt.toolTip=문자열 객체의 지정된 인덱스에 문자를 반환합니다

Class.String.charCodeAt=charCodeAt

Class.String.charCodeAt.toolTip=문자의 유니코드 인코딩을 나타내는 정수를 문자열 객체 내의 지정된 위치로 반환합니다

Class.String.concat=concat

Class.String.concat.toolTip=제공된 문자열과 현재 문자열의 연결을 포함한 문자열 값을 반환합니다

Class.String.indexOf=indexOf

Class.String.indexOf.toolTip=문자열 객체 내 부분 문자열의 첫 번째 항목을 반환합니다

Class.String.lastIndexOf=lastIndexOf

Class.String.lastIndexOf.toolTip=문자열 객체 내 부분 문자열의 마지막 항목을 반환합니다

Class.String.localeCompare=localeCompare
Class.String.localeCompare.toolTip=현재 로케일에서 두 문자열이 동일한지 여부를 나타내는 값을 반환합니다

Class.String.match=일치

Class.String.match.toolTip=정규식 패턴을 사용하는 문자열 검색을 실행하여, 검색 결과를 포함하는 배열을 반환합니다

Class.String.replace=바꾸기

Class.String.replace.toolTip=정규식 또는 검색 문자열을 사용하여 대체된 텍스트를 포함하는 문자열의 복사본을 반환합니다

Class.String.search=검색

Class.String.search.toolTip=정규식 검색에서 일치하는 첫 번째 부분 문자열 위치를 반환합니다

Class.String.slice=조각

Class.String.slice.toolTip=이 객체를 문자열로 변환시킨 결과의 부분 문자열을 반환합니다

Class.String.split=분할

Class.String.split.toolTip=하나의 문자열을 부분 문자열로 분리한 결과의 문자열 배열을 반환합니다

Class.String.substr=substr

Class.String.substr.toolTip=지정된 위치에서 시작하며 지정된 길이를 가지는 부분 문자열을 반환합니다

Class.String.substring=부분 문자열

Class.String.substring.toolTip=부분 문자열을 문자열 객체 내 지정된 위치로 반환합니다

Class.String.toLowerCase=toLowerCase

Class.String.toLowerCase.toolTip=문자열 내 문자를 차례로 소문자로 변환합니다.

Class.String.toLocaleLowerCase=toLocaleLowerCase

Class.String.toLocaleLowerCase.toolTip=호스트 환경의 현재 로케일에 따라 모든 영문자가 소문자로 변환된 문자열을 반환합니다

Class.String.toUpperCase=toUpperCase

Class.String.toUpperCase.toolTip=문자열 내 문자를 차례로 대문자로 변환합니다.

Class.String.toLocaleUpperCase=toLocaleUpperCase

Class.String.toLocaleUpperCase.toolTip=호스트 환경의 현재 로케일에 따라 모든 영문자가 대문자로 변환된 문자열을 반환합니다

Class.String.toString=toString
Class.String.toString.toolTip=이 문자열 값을 반환합니다

Class.String.valueOf=valueOf
Class.String.valueOf.toolTip=이 문자열 값을 반환합니다

Class.String.String.object=객체

Class.String.fromCharCode.c=c

Class.String.charAt.n=n
Class.String.charCodeAt.n=n
Class.String.concat.value=값

Class.String.indexOf.substring=부분 문자열

Class.String.indexOf.start=시작

Class.String.lastIndexOf.substring=부분 문자열

Class.String.lastIndexOf.start=시작

Class.String.localeCompare.target=대상

Class.String.match.regexp=regexp

Class.String.replace.regexp=regexp

Class.String.replace.replacement=대체

Class.String.search.regexp=regexp

Class.String.slice.start=시작

Class.String.slice.end=끝

Class.String.split.delimitor=구분 기호

Class.String.split.limit=제한

Class.String.substr.start=시작

Class.String.substr.length=길이

Class.String.substring.from=시작

Class.String.substring.to=끝

#1.Global
Class.Global=전역 함수

Class.Global.toolTip=전역 메서드를 하나의 객체로 수집하는 내장 객체입니다

Class.Global.NaN=NaN

Class.Global.NaN.toolTip=초기 값이 숫자가 아닙니다

Class.Global.Infinity=무한대

Class.Global.Infinity.toolTip=Number.POSITIVE_INFINITY(JScript에 표시될 수 있는 가장 큰 숫자(Number.MAX_VALUE)보다 큰 값) 값을 반환합니다

Class.Global.undefined=정의되지 않음

Class.Global.undefined.toolTip=초기 값이 정의되지 않았습니다

Class.Global.decodeURI=decodeURI
Class.Global.decodeURI.toolTip=인코딩된 URI(Uniform Resource Identifier)의 인코딩되지 않은 버전을 반환합니다

Class.Global.decodeURIComponent=decodeURIComponent
Class.Global.decodeURIComponent.toolTip=인코딩된 URI(Uniform Resource Identifier) 구성 요소의 인코딩되지 않은 버전을 반환합니다

Class.Global.encodeURI=encodeURI
Class.Global.encodeURI.toolTip=인코딩된 문자열을 올바른 URI(Uniform Resource Identifier)로 반환합니다

Class.Global.encodeURIComponent=encodeURIComponent
Class.Global.encodeURIComponent.toolTip=인코딩된 문자열을 올바른 URI(Uniform Resource Identifier) 구성 요소로 반환합니다

Class.Global.escape=escape

Class.Global.escape.toolTip=모든 컴퓨터에서 읽을 수 있는 인코딩된 문자열 객체를 반환합니다

Class.Global.eval=eval

Class.Global.eval.toolTip=JScript 코드를 계산하여 실행합니다

Class.Global.isNaN=isNaN

Class.Global.isNaN.toolTip=인수에 ToNumber를 적용하여 그 결과가 Nan이면 참 값을 반환합니다

Class.Global.isFinite=isFinite
Class.Global.isFinite.toolTip=제공된 숫자가 유한일 경우 나타나는 부울 값을 반환합니다

Class.Global.parseFloat=parseFloat
Class.Global.parseFloat.toolTip=문자열에서 변환된 부동 소수점 숫자를 반환합니다

Class.Global.parseInt=parseInt

Class.Global.parseInt.toolTip=문자열에서 변환된 정수를 반환합니다

Class.Global.unescape=unescape

Class.Global.unescape.toolTip=이스케이프 메서드로 인코딩된 문자열 객체에서 디코딩된 문자열로 반환합니다


Class.Global.decodeURI.uri=uri
Class.Global.decodeURIComponent.s=S

Class.Global.encodeURI.uri=uri
Class.Global.encodeURIComponent.s=S

Class.Global.escape.s=S

Class.Global.eval.code=코드

Class.Global.isNaN.x=x
Class.Global.isFinite.n=n
Class.Global.parseFloat.s=S

Class.Global.parseInt.s=S

Class.Global.parseInt.radix=radix

Class.Global.unescape.s=S

#2.Array
Class.Array=배열 함수

Class.Array.toolTip=모든 데이터 형식의 크기 조정 가능 배열을 지원합니다.

Class.Array.Array=배열

Class.Array.Array.toolTip=신규 배열 개체를 생성 및 초기화합니다.

Class.Array.length=길이

Class.Array.length.toolTip=배열에서 정의된 최상위 요소보다 한 단계 높은 정수값을 반환합니다

Class.Array.concat=concat

Class.Array.concat.toolTip=현재 배열과 추가 항목의 조합으로 구성된 신규 배열을 반환합니다

Class.Array.join=조인

Class.Array.join.toolTip=지정된 구분 문자에 의해 함께 연결되고 분리된 모든 배열 요소로 구성된 문자열 값을 반환합니다

Class.Array.pop=pop

Class.Array.pop.toolTip=배열에서 마지막 배열 요소를 제거하여 반환합니다

Class.Array.push=push

Class.Array.push.toolTip=인수가 나타나는 순서대로 배열의 마지막에 추가됩니다

Class.Array.reverse=역방향

Class.Array.reverse.toolTip=배열 요소를 다시 정렬하여 순서를 역순으로 정렬합니다

Class.Array.shift=이동

Class.Array.shift.toolTip=배열의 처음 요소를 제거하여 반환합니다

Class.Array.slice=조각

Class.Array.slice.toolTip=배열 섹션을 포함하는 배열을 반환합니다

Class.Array.sort=정렬

Class.Array.sort.toolTip=이 배열의 요소가 정렬됩니다

Class.Array.splice=겹쳐 잇기

Class.Array.splice.toolTip=배열에서 요소를 제거하고 필요하면 그 자리에 신규 요소를 삽입하여 삭제된 요소를 반환합니다. 배열에서 제거된 요소를 반환합니다

Class.Array.toLocaleString=toLocaleString
Class.Array.toLocaleString.toolTip=배열 요소를 문자열로 변환합니다

Class.Array.toString=toString
Class.Array.toString.toolTip=인수가 없는 이 객체에 대해 기본 제공 조인 메서드를 호출한 것처럼 동일하게 반환합니다

Class.Array.unshift=이동 취소

Class.Array.unshift.toolTip=인수가 배열의 시작에 추가되어 배열 내 순서가 인수 목록에 나타난 것과 동일하도록 합니다

Class.Array.Array.size=크기

Class.Array.Array.element=요소

Class.Array.concat.value=값

Class.Array.join.separator=구분 기호

Class.Array.push.value=값

Class.Array.slice.start=시작

Class.Array.slice.end=끝

Class.Array.sort.orderfunc=orderfunc

Class.Array.splice.start=시작

Class.Array.splice.deleteCount=deleteCount
Class.Array.unshift.value=값

#3. Boolean
Class.Boolean=부울 함수

Class.Boolean.toolTip=객체 형식의 구성원이며 기본 제공 부울 객체 인스턴스입니다

Class.Boolean.Boolean=부울

Class.Boolean.Boolean.toolTip=ToBoolean(값)에서 계산된 부울 값을 반환합니다

Class.Boolean.toString=toString
Class.Boolean.toString.toolTip=객체의 문자열 표시를 반환합니다

Class.Boolean.valueOf=valueOf
Class.Boolean.valueOf.toolTip=이 부울 값을 반환합니다

Class.Boolean.Boolean.value=값

#4. Date
Class.Date=날짜 함수

Class.Date.toolTip=날짜와 시간의 기본 저장 및 검색을 사용할 수 있도록 하는 객체입니다

Class.Date.Date=날짜

Class.Date.Date.toolTip=현재 시간을 표시하는 문자열을 반환합니다

Class.Date.getDate=getDate
Class.Date.getDate.toolTip=현지 시간을 사용하여 날짜 객체에서 날짜 값을 반환합니다

Class.Date.getDay=getDay
Class.Date.getDay.toolTip=현지 시간을 사용하여 날짜 객체에서 요일 값을 반환합니다

Class.Date.getFullYear=getFullYear
Class.Date.getFullYear.toolTip=현지 시간을 사용하여 날짜 객체에서 연도 값을 반환합니다

Class.Date.getHours=getHours
Class.Date.getHours.toolTip=현지 시간을 사용하여 날짜 객체에서 시간 값을 반환합니다

Class.Date.getMilliseconds=getMilliseconds
Class.Date.getMilliseconds.toolTip=현지 시간을 사용하여 날짜 객체에서  밀리초 값을 반환합니다

Class.Date.getMinutes=getMinutes
Class.Date.getMinutes.toolTip=현지 시간을 사용하여 날짜 객체에서 분 값을 반환합니다

Class.Date.getMonth=getMonth
Class.Date.getMonth.toolTip=현지 시간을 사용하여 날짜 객체에서 월 값을 반환합니다

Class.Date.getSeconds=getSeconds
Class.Date.getSeconds.toolTip=현지 시간을 사용하여 날짜 객체에서 초 값을 반환합니다

Class.Date.getTime=getTime
Class.Date.getTime.toolTip=날짜 객체에서 시간 값을 반환합니다

Class.Date.getTimezoneOffset=getTimezoneOffset
Class.Date.getTimezoneOffset.toolTip=현지 시간과 UTC 시간 사이의 차이를 분 단위로 반환합니다

Class.Date.getUTCDate=getUTCDate
Class.Date.getUTCDate.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 날짜를 반환합니다

Class.Date.getUTCDay=getUTCDay
Class.Date.getUTCDay.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 요일을 반환합니다

Class.Date.getUTCFullYear=getUTCFullYear
Class.Date.getUTCFullYear.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 연도 값을 반환합니다

Class.Date.getUTCHours=getUTCHours
Class.Date.getUTCHours.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 시간 값을 반환합니다

Class.Date.getUTCMilliseconds=getUTCMilliseconds
Class.Date.getUTCMilliseconds.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 밀리초 값을 반환합니다

Class.Date.getUTCMinutes=getUTCMinutes
Class.Date.getUTCMinutes.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 분 값을 반환합니다

Class.Date.getUTCMonth=getUTCMonth
Class.Date.getUTCMonth.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 월 값을 반환합니다

Class.Date.getUTCSeconds=getUTCSeconds
Class.Date.getUTCSeconds.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 초 값을 반환합니다

Class.Date.getYear=getYear
Class.Date.getYear.toolTip=날짜 객체에서 연도 값을 반환합니다

Class.Date.parse=parse

Class.Date.parse.toolTip=날짜가 들어 있는 문자열을 구문 분석하여 밀리초 수를 반환합니다

Class.Date.setDate=setDate
Class.Date.setDate.toolTip=현지 표준 시간대에서 날짜 객체의 날짜를 설정합니다

Class.Date.setFullYear=setFullYear
Class.Date.setFullYear.toolTip=현지 시간을 사용하여 날짜 객체에서 연도 값을 설정합니다

Class.Date.setHours=setHours
Class.Date.setHours.toolTip=현지 시간을 사용하여 날짜 객체에서 시간 값을 설정합니다

Class.Date.setMilliseconds=setMilliseconds
Class.Date.setMilliseconds.toolTip=현지 시간을 사용하여 날짜 객체에서 밀리초 값을 설정합니다

Class.Date.setMinutes=setMinutes
Class.Date.setMinutes.toolTip=현지 시간을 사용하여 날짜 객체에서 분 값을 설정합니다

Class.Date.setMonth=setMonth
Class.Date.setMonth.toolTip=현지 시간을 사용하여 날짜 객체에서 월 값을 설정합니다

Class.Date.setSeconds=setSeconds
Class.Date.setSeconds.toolTip=현지 시간을 사용하여 날짜 객체에서 초 값을 설정합니다

Class.Date.setTime=setTime
Class.Date.setTime.toolTip=현지 시간을 사용하여 날짜 객체에서 시간 값을 설정합니다

Class.Date.setUTCDate=setUTCDate
Class.Date.setUTCDate.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 숫자 날짜를 설정합니다

Class.Date.setUTCFullYear=setUTCFullYear
Class.Date.setUTCFullYear.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 연도 값을 설정합니다

Class.Date.setUTCHours=setUTCHours
Class.Date.setUTCHours.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 시간 값을 설정합니다

Class.Date.setUTCMilliseconds=setUTCMilliseconds
Class.Date.setUTCMilliseconds.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 밀리초 값을 설정합니다

Class.Date.setUTCMinutes=setUTCMinutes
Class.Date.setUTCMinutes.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 분 값을 설정합니다

Class.Date.setUTCMonth=setUTCMonth
Class.Date.setUTCMonth.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 월 값을 설정합니다

Class.Date.setUTCSeconds=setUTCSeconds
Class.Date.setUTCSeconds.toolTip=UTC(Coordinated Universal Time)를 사용하여 날짜 객체에서 초 값을 설정합니다

Class.Date.setYear=setYear
Class.Date.setYear.toolTip=날짜 객체에서 연도 값을 설정합니다

Class.Date.toDateString=toDateString
Class.Date.toDateString.toolTip="날짜"를 표시하는 문자열 값을 반환합니다

Class.Date.toGMTString=toGMTString
Class.Date.toGMTString.toolTip=GMT 날짜를 표시하는 문자열 값을 반환합니다

Class.Date.toLocaleDateString=toLocaleDateString
Class.Date.toLocaleDateString.toolTip=현재 표준 시간대에서 "날짜"를 표시하는 문자열 값을 반환합니다

Class.Date.toLocaleString=toLocaleString
Class.Date.toLocaleString.toolTip=현재 표준 시간대에서 날짜를 표시하는 문자열 값을 반환합니다

Class.Date.toLocaleTimeString=toLocaleTimeString
Class.Date.toLocaleTimeString.toolTip=현재 표준 시간대에서 "시간"을 표시하는 문자열 값을 반환합니다

Class.Date.toString=toString
Class.Date.toString.toolTip=문자열 값을 반환합니다

Class.Date.toTimeString=toTimeString
Class.Date.toTimeString.toolTip="시간"을 표시하는 문자열 값을 반환합니다

Class.Date.toUTCString=toUTCString
Class.Date.toUTCString.toolTip=UTC에서 날짜를 표시하는 문자열 값을 편리하고 사람이 인식할 수 있는 형식으로 반환합니다

Class.Date.UTC=UTC
Class.Date.UTC.toolTip=연도, 월 및 날짜(선택적), 시간, 분, 초, 밀리초로 날짜를 계산합니다

Class.Date.valueOf=valueOf
Class.Date.valueOf.toolTip=이 시간 값인 숫자를 반환합니다

Class.Date.Date.milliseconds=밀리초

Class.Date.Date.datestring=날짜 문자열

Class.Date.Date.year=연

Class.Date.Date.month=월

Class.Date.Date.day=일

Class.Date.Date.hours=시

Class.Date.Date.minutes=분

Class.Date.Date.seconds=초

Class.Date.Date.ms=ms

Class.Date.parse.date=날짜

Class.Date.setDate.day_of_month=day_of_month
Class.Date.setFullYear.year=연

Class.Date.setFullYear.month=월

Class.Date.setFullYear.minutes=분

Class.Date.setFullYear.day=일

Class.Date.setHours.hours=시

Class.Date.setHours.minutes=분

Class.Date.setHours.seconds=초

Class.Date.setHours.millis=밀리초

Class.Date.setMilliseconds.millis=밀리초

Class.Date.setMinutes.minutes=분

Class.Date.setMinutes.seconds=초

Class.Date.setMinutes.millis=밀리초

Class.Date.setMonth.month=월

Class.Date.setMonth.day=일

Class.Date.setSeconds.seconds=초

Class.Date.setSeconds.millis=밀리초

Class.Date.setTime.millis=밀리초

Class.Date.setUTCDate.day_of_month=day_of_month
Class.Date.setUTCFullYear.year=연

Class.Date.setUTCFullYear.month=월

Class.Date.setUTCFullYear.minutes=분

Class.Date.setUTCFullYear.day=일

Class.Date.setUTCHours.hours=시

Class.Date.setUTCHours.minutes=분

Class.Date.setUTCHours.seconds=초

Class.Date.setUTCHours.millis=밀리초

Class.Date.setUTCMilliseconds.millis=밀리초

Class.Date.setUTCMinutes.minutes=분

Class.Date.setUTCMinutes.seconds=초

Class.Date.setUTCMinutes.millis=밀리초

Class.Date.setUTCMonth.month=월

Class.Date.setUTCMonth.day=일

Class.Date.setUTCSeconds.seconds=초

Class.Date.setUTCSeconds.millis=밀리초

Class.Date.setYear.year=연

Class.Date.UTC.year=연

Class.Date.UTC.month=월

Class.Date.UTC.day=일

Class.Date.UTC.hours=시

Class.Date.UTC.minutes=분

Class.Date.UTC.seconds=초

Class.Date.UTC.ms=ms

#5. Math
Class.Math=Math 함수

Class.Math.toolTip=기본 수학 기능 및 상수를 제공하는 내장 객체입니다

Class.Math.E=E

Class.Math.E.toolTip=e에 대한 숫자 값은 대략 2.7182818284590452354입니다

Class.Math.LN10=LN10

Class.Math.LN10.toolTip=10의 자연 로그에 대한 숫자 값이며 대략 2.302585092994046입니다

Class.Math.LN2=LN2

Class.Math.LN2.toolTip=2의 자연 로그에 대한 숫자 값이며 대략 0.6931471805599453입니다

Class.Math.LOG10E=LOG10E

Class.Math.LOG10E.toolTip=밑수가 10인 e의 로그의 숫자 값은 대략 0.4342944819032518입니다

Class.Math.LOG2E=LOG2E

Class.Math.LOG2E.toolTip=밑수가 2인 e의 로그의 숫자 값은 대략 1.4426950408889634 입니다

Class.Math.PI=PI

Class.Math.PI.toolTip=PI, 즉 원주율의 숫자 값이며 대략 3.1415926535897932입니다

Class.Math.SQRT1_2=SQRT1_2
Class.Math.SQRT1_2.toolTip=1/2의 제곱근의 숫자 값이며 대략 0.7071067811865476입니다

Class.Math.SQRT2=SQRT2

Class.Math.SQRT2.toolTip=2의 제곱근의 숫자 값이며 대략 1.4142135623730951입니다

Class.Math.abs=abs

Class.Math.abs.toolTip=절대 값을 반환합니다

Class.Math.acos=acos

Class.Math.acos.toolTip=아크코사인에 대한 구현 종속 근사값을 반환합니다

Class.Math.asin=asin

Class.Math.asin.toolTip=아크사인에 대한 구현 종속 근사값을 반환합니다

Class.Math.atan=atan

Class.Math.atan.toolTip=아크탄젠트에 대한 구현 종속 근사값을 반환합니다

Class.Math.atan2=atan2

Class.Math.atan2.toolTip=인수 y와 x, 지수 y/x의 아크탄젠트에 대한 구현 종속 근사값을 반환합니다. 이때 y와 x의 기호를 사용하여 결과의 사분면을 결정합니다

Class.Math.ceil=ceil

Class.Math.ceil.toolTip=x보다 작지 않고 수치 정수와 같은 최소 숫자 값을 반환합니다

Class.Math.cos=cos

Class.Math.cos.toolTip=코사인에 대한 구현 종속 근사값을 반환합니다

Class.Math.exp=exp

Class.Math.exp.toolTip=지수 함수에 대한 구현 종속 근사값을 반환합니다

Class.Math.floor=floor

Class.Math.floor.toolTip=x보다 크지 않고 수치 정수와 같은 최대 숫자 값을 반환합니다

Class.Math.log=log

Class.Math.log.toolTip=자연 로그에 대한 구현 종속 근사값을 반환합니다

Class.Math.max=max

Class.Math.max.toolTip=가장 큰 결과 값을 반환합니다

Class.Math.min=min

Class.Math.min.toolTip=최소 결과 값을 반환합니다

Class.Math.pow=pow

Class.Math.pow.toolTip=x를 y제곱한 결과의 구현 종속 근사값을 반환합니다

Class.Math.random=random

Class.Math.random.toolTip=0보다 크거나 같고 1보다 작은 양수 숫자 값을 반환합니다

Class.Math.round=round

Class.Math.round.toolTip=x에 가장 가깝고 수치 정수와 같은 숫자 값을 반환합니다

Class.Math.sin=sin

Class.Math.sin.toolTip=사인에 대한 구현 종속 근사값을 반환합니다

Class.Math.sqrt=sqrt

Class.Math.sqrt.toolTip=제곱근에 대한 구현 종속 근사값을 반환합니다

Class.Math.tan=tan

Class.Math.tan.toolTip=탄젠트에 대한 구현 종속 근사값을 반환합니다


Class.Math.abs.x=x
Class.Math.acos.x=x
Class.Math.asin.x=x
Class.Math.atan.x=x
Class.Math.atan2.y=y

Class.Math.atan2.x=x
Class.Math.ceil.x=x
Class.Math.cos.x=x
Class.Math.exp.x=x
Class.Math.floor.x=x
Class.Math.log.x=x
Class.Math.max.args=args

Class.Math.min.args=args

Class.Math.pow.x=x
Class.Math.pow.y=y

Class.Math.round.x=x
Class.Math.sin.x=x
Class.Math.sqrt.x=x
Class.Math.tan.x=x


#6. Number
Class.Number=숫자 함수

Class.Number.toolTip=숫자 데이터 및 숫자 상수의 자리 표시자를 나타내는 객체입니다

Class.Number.Number=숫자

Class.Number.Number.toolTip=ToNumber(값)에서 계산된 숫자 값을 반환합니다

Class.Number.MAX_VALUE=MAX_VALUE
Class.Number.MAX_VALUE.toolTip=숫자 형식에 대한 최대 유한 양수 값이며 대략 1.79E+308입니다

Class.Number.MIN_VALUE=MIN_VALUE
Class.Number.MIN_VALUE.toolTip=숫자 형식에 대한 최소 양수 값이며 대략 5.00E-324입니다

Class.Number.NaN=NaN

Class.Number.NaN.toolTip=숫자가 아닙니다

Class.Number.NEGATIVE_INFINITY=NEGATIVE_INFINITY
Class.Number.NEGATIVE_INFINITY.toolTip=JScript에 표시될 수 있는 가장 큰 숫자의 음수(-Number.MAX_VALUE)보다 더 큰 숫자의 음수 값을 반환합니다

Class.Number.POSITIVE_INFINITY=POSITIVE_INFINITY
Class.Number.POSITIVE_INFINITY.toolTip=JScript에 표시될 수 있는 가장 큰 숫자(Number.MAX_VALUE)보다 더 큰 값을 반환합니다

Class.Number.toExponential=toExponential

Class.Number.toExponential.toolTip=지수 표기법으로 표시된 숫자를 포함하고 있는 문자열을 반환합니다

Class.Number.toFixed=toFixed

Class.Number.toFixed.toolTip=고정 소수점 표기법을 표시하는 문자열을 반환합니다

Class.Number.toLocaleString=toLocaleString
Class.Number.toLocaleString.toolTip=호스트 환경의 현재 로케일에 적절한 문자열 값으로 값을 반환합니다

Class.Number.toPrecision=toPrecision

Class.Number.toPrecision.toolTip=지수 표기법 또는 지정한 자릿수를 가지는 고정 소수점 표기법으로 표시된 숫자를 포함하고 있는 문자열을 반환합니다

Class.Number.toString=toString
Class.Number.toString.toolTip=객체의 문자열 표현을 반환합니다

Class.Number.valueOf=valueOf
Class.Number.valueOf.toolTip=지정한 객체의 기본 값을 반환합니다

Class.Number.Number.value=값

Class.Number.toExpoential.digits=숫자

Class.Number.toFixed.digits=숫자

Class.Number.toPrecision.precision=정밀도

Class.Number.toString.radix=radix

#7. Object
Class.Object=객체 함수

Class.Object.toolTip=형식 객체의 구성원입니다

Class.Object.Object=객체

Class.Object.Object.toolTip=객체를 생성합니다

Class.Object.hasOwnProperty=hasOwnProperty

Class.Object.hasOwnProperty.toolTip=객체가 지정한 이름의 속성을 가지는지 여부를 나타내는 부울 값을 반환합니다

Class.Object.isPrototypeOf=isPrototypeOf

Class.Object.isPrototypeOf.toolTip=다른 객체의 프로토타입 체인에 객체가 존재하는지 여부를 나타내는 부울 값을 반환합니다

Class.Object.propertyIsEnumerable=propertyIsEnumerable
Class.Object.propertyIsEnumerable.toolTip=지정한 속성이 객체의 일부분인지 그리고 셀 수 있는지 여부를 나타내는 부울 값을 반환합니다

Class.Object.toLocaleString=toLocaleString
Class.Object.toLocaleString.toolTip=현재 로케일을 사용하여 문자열로 변환한 날짜를 반환합니다

Class.Object.toString=toString
Class.Object.toString.toolTip=객체의 문자열 표현을 반환합니다

Class.Object.valueOf=valueOf
Class.Object.valueOf.toolTip=현재 로케일을 사용하여 문자열로 변환한 날짜를 반환합니다

Class.Object.Object.value=값

Class.Object.hasOwnProperty.propname=propname

Class.Object.isPrototypeOf.o=o

Class.Object.propertyIsEnumerable.propname=propname

#8. RegExp
Class.RegExp=RegExp 함수

Class.RegExp.toolTip=간단한 정규식 지원을 제공합니다

Class.RegExp.RegExp=RegExp

Class.RegExp.RegExp.toolTip=입력 패턴 문자열에 문법을 적용합니다

Class.RegExp.global=전역

Class.RegExp.global.toolTip=패턴이 전체 검색 문자열의 모든 항목과 일치해야 하는지 아니면 첫번째 항목과 일치하면 되는지 여부를 나타내는 부울 값을 설정 또는 반환합니다

Class.RegExp.ignoreCase=ignoreCase
Class.RegExp.ignoreCase.toolTip=패턴 검색이 대/소문자를 구분하는지 여부를 나타내는 부울 값을 설정 또는 반환합니다

Class.RegExp.lastIndex=lastIndex
Class.RegExp.lastIndex.toolTip=다음 일치를 시작할 문자열 위치를 지정하는 정수입니다

Class.RegExp.source=원본

Class.RegExp.source.toolTip=현재 정규식을 나타내는 패턴 형식의 문자열입니다

Class.RegExp.exec=exec

Class.RegExp.exec.toolTip=정규식에 대해 문자열의 정규식 일치를 수행합니다

Class.RegExp.test=테스트

Class.RegExp.test.toolTip=지정한 문자열에 대해 정규식 검색을 실행하여 패턴 일치를 찾았는지 여부를 나타내는 부울 값을 반환합니다

Class.RegExp.toString=toString
Class.RegExp.toString.toolTip=현재 정규식을 나타내는 패턴 형식의 문자열로 변환합니다

Class.RegExp.RegExp.pattern=pattern

Class.RegExp.RegExp.attributes=특성

Class.RegExp.exec.string=소문자 문자열

Class.RegExp.test.string=소문자 문자열

#9.  ElementDefn
Class.ElementDefn=ElementDefn 클래스

Class.ElementDefn.toolTip=보고서 요소에 대한 디자인 정보를 제공합니다

Class.ElementDefn.name=이름

Class.ElementDefn.name.toolTip=요소의 이름을 제공합니다

Class.ElementDefn.extendsElement=extendsElement
Class.ElementDefn.extendsElement.toolTip=이 요소가 확장한 상위 요소의 이름을 제공합니다

Class.ElementDefn.propertyDefns=propertyDefns
Class.ElementDefn.propertyDefns.toolTip=속성 정의 배열입니다

Class.ElementDefn.slotDefns=slotDefns
Class.ElementDefn.slotDefns.toolTip=슬롯 정의 배열입니다

Class.ElementDefn.property=[anyProperty]
Class.ElementDefn.property.toolTip=이 이름을 가진 디자인-시간 속성 값을 제공합니다

Class.ElementDefn.properties=속성

Class.ElementDefn.properties.toolTip=속성 이름으로 인덱스된 속성 값의 배열입니다

Class.ElementDefn.slots=슬롯

Class.ElementDefn.slots.toolTip=많은 요소가 컨테이너이며 이들은 다른 보고서 요소를 포함하고 있습니다

Class.ElementDefn.allowsUserProperties=allowsUserProperties
Class.ElementDefn.allowsUserProperties.toolTip=요소가 사용자 속성을 허용하는 경우 참 값이며, 그렇지 않은 경우 거짓 값입니다

Class.ElementDefn.hasStyle=hasStyle
Class.ElementDefn.hasStyle.toolTip=요소에 스타일이 있는 경우 참 값이며, 그렇지 않은 경우 거짓 값입니다

Class.ElementDefn.container=컨테이너

Class.ElementDefn.container.toolTip=만약 있다면 이 요소를 포함하고 있는 있는 요소 정의를 반환합니다

Class.ElementDefn.containerSlot=containerSlot
Class.ElementDefn.containerSlot.toolTip=이 요소를 포함하는 슬롯의 이름을 가져옵니다


#10. ElementState

Class.ElementState=ElementState
Class.ElementState.toolTip=보고서 요소의 런타임 상태를 나타냅니다

Class.ElementState.design=디자인

Class.ElementState.design.toolTip=이 인스턴스에 대한 요소 정의 객체를 반환합니다

Class.ElementState.property=속성

Class.ElementState.property.toolTip=주어진 이름을 가진 보고서 요소 속성의 런타임 값을 가져오거나 설정하는 응용 프로그램을 허용합니다

Class.ElementState.container=컨테이너

Class.ElementState.container.toolTip=있는 경우 이 요소를 포함하고 있는 요소 상태 객체를 반환합니다

Class.ElementState.slot=슬롯

Class.ElementState.slot.toolTip=이 요소를 포함하고 있는 요소들에 대한 액세스를 제공합니다

#11. Color
Class.Color=색상 클래스

Class.Color.toolTip=이름 또는 RGB 값으로 색 값을 사용하는 메서드를 제공합니다.

Class.Color.transparent=투명

Class.Color.transparent.toolTip=속성이 CSS 투명 값으로 설정된 경우 참 값을 반환합니다

Class.Color.rgb=RGB

Class.Color.rgb.toolTip=색을 RGB 값으로 가져옵니다

Class.Color.value=값

Class.Color.value.toolTip=이름(이름으로 설정되어 있을 경우) 또는 CSS RGB 문자열(RGB로 설정되어 있을 경우)로 색을 가져옵니다

Class.Color.cssValue=cssValue
Class.Color.cssValue.toolTip=CSS 색 이름이든 RGB 값이든 CSS로 설정할 수 있는 형식으로 색을 가져옵니다


#12. Dimension
Class.Dimension=차원 클래스

Class.Dimension.toolTip=차원 속성 객체는 CSS 차원 속성의 구문 분석을 처리합니다

Class.Dimension.value=값

Class.Dimension.value.toolTip=CSS와 호환되는 차원 값을 반환합니다

Class.Dimension.measure=측정

Class.Dimension.measure.toolTip=차원의 측정 부분을 가져옵니다. 차원이 상수를 사용하여 정의된 경우 널(null)입니다

Class.Dimension.units=단위

Class.Dimension.units.toolTip=차원의 단위 부분을 가져옵니다. 차원이 상수를 사용하여 정의된 경우 널(null)입니다

#13. PropertyDefn
Class.PropertyDefn=PropertyDefn 클래스

Class.PropertyDefn.toolTip=속성 정의 객체는 BIRT 또는 사용자 정의 속성에 대한 메타 데이터 정보를 제공합니다

Class.PropertyDefn.isUserProperty=isUserProperty
Class.PropertyDefn.isUserProperty.toolTip=사용자 정의 속성인 경우 참 값, 시스템 정의 속성인 경우 거짓 값입니다

Class.PropertyDefn.name=이름

Class.PropertyDefn.name.toolTip=내부 속성 이름

Class.PropertyDefn.group=그룹

Class.PropertyDefn.group.toolTip=속성을 포함하는 그룹 이름

Class.PropertyDefn.canInherit=canInherit
Class.PropertyDefn.canInherit.toolTip=속성을 상속할 수 있는 경우 참 값, 그렇지 않은 경우 거짓 값입니다

Class.PropertyDefn.isStyle=isStyle
Class.PropertyDefn.isStyle.toolTip=속성이 요소 스타일의 일부분인 경우 참 값, 그렇지 않은 경우 거짓 값입니다

Class.PropertyDefn.type=형식

Class.PropertyDefn.type.toolTip=속성 형식입니다

Class.PropertyDefn.choices=선택

Class.PropertyDefn.choices.toolTip=속성에 대한 선택 배열입니다

Class.PropertyDefn.defaultValue=defaultValue
Class.PropertyDefn.defaultValue.toolTip=속성에 대한 기본 값입니다

#14. Report
Class.Report=보고서 클래스

Class.Report.toolTip=보고서가 실행 중인 보고서 및 컨텍스트에 대한 모든 정보에 대한 액세스를 제공합니다

Class.Report.design=디자인

Class.Report.design.toolTip=보고서 설계를 설명하는 보고서 정의 객체입니다

Class.Report.document=문서

Class.Report.document.toolTip=공장에서 생성되었거나 프리젠테이션 엔진에서 읽는 보고서 문서에 대한 정보를 제공하는 보고서 문서 객체를 반환합니다

Class.Report.params=params

Class.Report.params.toolTip=보고서에 전달된 매개 변수 값의 객체 배열을 반환합니다

Class.Report.dataSets=datasets

Class.Report.dataSets.toolTip=보고서에 정의된 데이터 집합의 배열을 반환합니다

Class.Report.dataSources=dataSources
Class.Report.dataSources.toolTip=보고서에 정의된 데이터 소스(연결)를 반환합니다

Class.Report.config=config

Class.Report.config.toolTip=보고서에 사용 가능한 구성 변수의 배열을 반환합니다

Class.Report.reportContext=reportContext
Class.Report.reportContext.toolTip=이 보고서와 관련된 컨텍스트

#15. ReportDoc
Class.ReportDoc=ReportDoc

Class.ReportDoc.toolTip=생성 중이거나 보고 있는 보고서에 대한 정보를 제공합니다

Class.ReportDoc.design=디자인

Class.ReportDoc.design.toolTip=이 인스턴스에 대한 루트 디자인 객체를 반환합니다

Class.ReportDoc.fileName=fileName
Class.ReportDoc.fileName.toolTip=이 파일에 대한 파일 이름(있을 경우)이 작성됩니다

Class.ReportDoc.destination=대상

Class.ReportDoc.destination.toolTip=파일 시스템 또는 임시와 같은 대상 종류입니다

Class.ReportDoc.body=본문

Class.ReportDoc.body.toolTip=본문 내 섹션 목록입니다


#16. ReportDefn

Class.ReportDefn=ReportDefn
Class.ReportDefn.toolTip=보고서에 대한 전체 디자인 정보를 제공합니다

Class.ReportDefn.findStyle=findStyle
Class.ReportDefn.findStyle.toolTip=스타일 이름이 지정된 스타일을 찾습니다

Class.ReportDefn.findStyle.styleName=styleName
Class.ReportDefn.findReportItem=findReportItem
Class.ReportDefn.findReportItem.toolTip=보고서 항목 이름이 지정된 보고서 항목을 찾습니다

Class.ReportDefn.findReportItem.itemName=itemName
Class.ReportDefn.findDataSource=findDataSource
Class.ReportDefn.findDataSource.toolTip=데이터 원본 이름이 지정된 데이터 원본을 찾습니다

Class.ReportDefn.findDataSource.sourceName=sourceName
Class.ReportDefn.findDataSet=findDataSet
Class.ReportDefn.findDataSet.toolTip=데이터 집합 이름이 지정된 데이터 집합을 찾습니다

Class.ReportDefn.findDataSet.dataSetName=dataSetName
Class.ReportDefn.findParameter=findParameter
Class.ReportDefn.findParameter.toolTip=매개 변수 이름이 지정된 매개 변수를 찾습니다

Class.ReportDefn.findParameter.parameterName=parameterName


#17. DataSet
Class.DataSet=DataSet 클래스

Class.DataSet.toolTip=데이터 집합에 대한 디자인 및 런타임 정보를 모두 제공합니다

Class.DataSet.row=행

Class.DataSet.row.toolTip=현재 가장 안쪽 행을 나타냅니다

Class.DataSet.rows=행

Class.DataSet.rows.toolTip=이 계층 내의 행에 대한 액세스를 허용합니다

Class.DataSet.queryText=queryText
Class.DataSet.queryText.toolTip=ODA 데이터 원본으로 보낼 쿼리 텍스트를 제공합니다

Class.DataSet.columnDefns=columnDefns
Class.DataSet.columnDefns.toolTip=열 정의 배열입니다

Class.DataSet.schema=스키마

Class.DataSet.schema.toolTip=ODA 데이터 원본에 대한 스키마 정보를 제공하는 DataSetParamMetadata 객체입니다

Class.DataSet.inputParams=inputParams
Class.DataSet.inputParams.toolTip=매개 변수 배열인 입력 매개 변수 값에 액세스를 제공합니다

Class.DataSet.outputParams=outputParams
Class.DataSet.outputParams.toolTip=데이터 집합에 대한 출력 매개 변수 값의 배열입니다

Class.DataSet.extensionProperties=extensionProperties
Class.DataSet.extensionProperties.toolTip=ODA 데이터 집합에 대한 ODA 공용 속성을 제공합니다

Class.DataSet.privateProperties=privateProperties
Class.DataSet.privateProperties.toolTip=ODA 데이터 집합에 대한 ODA 개인 속성을 제공합니다

Class.DataSet.dataSource=DataSource
Class.DataSet.dataSource.toolTip=이 데이터 집합에서 사용된 데이터 원본 객체를 반환합니다.


#18. DataRow
Class.DataRow=DataRow 클래스

Class.DataRow.toolTip=데이터 집합에서 반입한 하나의 행을 나타냅니다

Class.DataRow.DataRow=DataRow

Class.DataRow.DataRow.toolTip=지정된 데이터 집합에서 빈 데이터 행을 만들거나 빈 데이터 행을 다른 데이터 행의 복사본으로 만드십시오

Class.DataRow.DataRow.ds=ds

Class.DataRow.DataRow.r=r

Class.DataRow.column=열

Class.DataRow.column.toolTip=지정한 열 이름의 열 값을 반환합니다

Class.DataRow.rowNo=rowNo

Class.DataRow.rowNo.toolTip=결과 집합 내 행의 위치입니다

Class.DataRow.dataSet=dataSet

Class.DataRow.dataSet.toolTip=행을 생성한 데이터 집합 객체를 반환합니다

Class.DataRow.schema=스키마

Class.DataRow.schema.toolTip=데이터 행에 대한 열 설명의 배열을 반환합니다

Class.DataRow.columnDefns=columnDefns
Class.DataRow.columnDefns.toolTip=열 메타데이터를 정의하는 ColumnDefn 배열입니다. dataSet.columnDefns에 대한 바로 가기입니다.

#19. ColumnDefn
Class.ColumnDefn=ColumnDefn 클래스

Class.ColumnDefn.toolTip=데이터 행 열의 메타 데이터를 설명합니다

Class.ColumnDefn.index=인덱스

Class.ColumnDefn.index.toolTip=데이터 집합에 대한 결과 집합 데이터 행 내의 열 인덱스를 반환합니다

Class.ColumnDefn.name=이름

Class.ColumnDefn.name.toolTip=데이터 집합에서 정의된 열 이름을 반환합니다

Class.ColumnDefn.type=형식

Class.ColumnDefn.type.toolTip=열의 데이터 형식을 반환합니다

Class.ColumnDefn.expr=expr

Class.ColumnDefn.expr.toolTip=BIRT 식을 사용하여 열을 정의할 수 있습니다

Class.ColumnDefn.INTEGER=INTEGER

Class.ColumnDefn.INTEGER.toolTip=정수 열에 대한 상수입니다

Class.ColumnDefn.FLOAT=FLOAT

Class.ColumnDefn.FLOAT.toolTip=부동 소수점 열에 대한 상수입니다

Class.ColumnDefn.DECIMAL=DECIMAL

Class.ColumnDefn.DECIMAL.toolTip=고정 정밀도 10진수에 대한 상수입니다

Class.ColumnDefn.BOOLEAN=BOOLEAN

Class.ColumnDefn.BOOLEAN.toolTip=부울 값에 대한 상수입니다

Class.ColumnDefn.STRING=STRING

Class.ColumnDefn.STRING.toolTip=문자열 열에 대한 상수입니다

Class.ColumnDefn.BLOB=BLOB

Class.ColumnDefn.BLOB.toolTip=BLOB(Binary Large OBject) 열에 대한 상수입니다


#20. DataSetParamMetaData
Class.DataSetParamMetaData=DataSetParamMetaData 클래스

Class.DataSetParamMetaData.toolTip=ODA 데이터 집합의 입력 및 출력 매개 변수에 대한 정보를 제공합니다

Class.DataSetParamMetaData.description=설명

Class.DataSetParamMetaData.description.toolTip=ODA 공급자가 공급한 데이터 집합 설명입니다

Class.DataSetParamMetaData.resultSets=resultSets
Class.DataSetParamMetaData.resultSets.toolTip=ODA 데이터 집합이 반환한 각각의 결과 집합을 설명하는 ResultSetDefn 객체 배열입니다

Class.DataSetParamMetaData.inputParams=inputParams
Class.DataSetParamMetaData.inputParams.toolTip=DataSetInputParam 객체 형식의 입력 매개 변수 정의 배열입니다

Class.DataSetParamMetaData.outputParams=outputParams
Class.DataSetParamMetaData.outputParams.toolTip=DataSetOutputParam 객체 형식의 출력 매개 변수 정의 배열입니다

#21. ResultSetDefn
Class.ResultSetDefn=ResultSetDefn

Class.ResultSetDefn.toolTip=열 정의 배열을 제공합니다

Class.ResultSetDefn.name=이름

Class.ResultSetDefn.name.toolTip=결과 집합의 이름입니다

Class.ResultSetDefn.columns=열

Class.ResultSetDefn.columns.toolTip=ODA 데이터 집합에 그들이 반환한 고정된 열 집합이 있습니다

Class.ResultSetDefn.dataSet=dataSet

Class.ResultSetDefn.dataSet.toolTip=이 결과 집합을 제공하는 데이터 집합에 대한 참조입니다

#22. ResultSetColumn
Class.ResultSetColumn=ResultSetColumn

Class.ResultSetColumn.toolTip=ODA 결과 집합 내의 열을 설명합니다

Class.ResultSetColumn.name=이름

Class.ResultSetColumn.name.toolTip=데이터 행-열에 대한 외부 고유 이름입니다

Class.ResultSetColumn.position=위치

Class.ResultSetColumn.position.toolTip=결과 집합 내 열에 대한 1 기반의 인덱스 위치(왼쪽에서 오른쪽 순서)입니다

Class.ResultSetColumn.displayName=displayName
Class.ResultSetColumn.displayName.toolTip=열의 비즈니스 이름입니다

Class.ResultSetColumn.nativeTypeCode=nativeTypeCode
Class.ResultSetColumn.nativeTypeCode.toolTip=열에 대한 고유 데이터 형식 코드입니다

Class.ResultSetColumn.nativeTypeName=nativeTypeName
Class.ResultSetColumn.nativeTypeName.toolTip=고유 데이터 형식의 이름을 표시하십시오

Class.ResultSetColumn.displayLength=displayLength
Class.ResultSetColumn.displayLength.toolTip=데이터 값의 기본 표시 길이입니다

Class.ResultSetColumn.displayFormat=displayFormat
Class.ResultSetColumn.displayFormat.toolTip=보고서 출력에서 이 데이터를 표시할 기본 형식을 나타내는 문자열입니다

Class.ResultSetColumn.horizAlign=horizAlign
Class.ResultSetColumn.horizAlign.toolTip=열 값을 기본적으로 왼쪽, 중앙, 오른쪽 아니면 자동 맞춤으로 표시할지 여부를 나타내는 열거된 값입니다

Class.ResultSetColumn.heading=heading

Class.ResultSetColumn.heading.toolTip=열 머리글에서 열을 식별하는 자유 형식 문자열입니다

Class.ResultSetColumn.description=설명

Class.ResultSetColumn.description.toolTip=열에 대해 자세한 설명을 제공하는 자유 형식 문자열입니다

Class.ResultSetColumn.helpText=helpText
Class.ResultSetColumn.helpText.toolTip=열에 대해 자세한 설명을 제공하는 자유 형식 문자열입니다

Class.ResultSetColumn.lineage=lineage

Class.ResultSetColumn.lineage.toolTip=열 값의 원본을 명명하는 자유 형식 문자열입니다

Class.ResultSetColumn.axis=축

Class.ResultSetColumn.axis.toolTip=다중 차원 데이터 원본에서 열을 가져온 경우 적용할 수 있습니다

Class.ResultSetColumn.axisType=axisType
Class.ResultSetColumn.axisType.toolTip=값이 차원 구성원, 차원 특성 또는 측정 중 하나입니다

Class.ResultSetColumn.onColumnLayout=onColumnLayout

Class.ResultSetColumn.onColumnLayout.toolTip=보고서 출력에서 이 열을 어떻게 레이아웃하는지에 대한 힌트입니다

Class.ResultSetColumn.DIMENSION_MEMBER=DIMENSION_MEMBER
Class.ResultSetColumn.DIMENSION_MEMBER.toolTip=axisType 속성에 대한 선택입니다

Class.ResultSetColumn.DIMENSION_ATTRIBUTE=DIMENSION_ATTRIBUTE
Class.ResultSetColumn.DIMENSION_ATTRIBUTE.toolTip=axisType 속성에 대한 선택입니다

Class.ResultSetColumn.MEASURE=MEASURE

Class.ResultSetColumn.MEASURE.toolTip=axisType 속성에 대한 선택입니다


#23. DataSetInputParam
Class.DataSetInputParam=DataSetInputParam 클래스

Class.DataSetInputParam.toolTip=ODA 데이터 집합에 대해 하나의 입력 매개 변수를 설명합니다

Class.DataSetInputParam.name=이름

Class.DataSetInputParam.name.toolTip=입력 매개 변수의 고유 이름입니다

Class.DataSetInputParam.displayName=DataSetInputParam

Class.DataSetInputParam.displayName.toolTip=입력 매개 변수의 비즈니스 이름입니다

Class.DataSetInputParam.description=설명

Class.DataSetInputParam.description.toolTip=매개 변수에 대해 자세한 설명을 제공하는 자유 형식 문자열입니다

Class.DataSetInputParam.nativeTypeCode=nativeTypeCode
Class.DataSetInputParam.nativeTypeCode.toolTip=매개 변수의 고유 데이터 형식 코드입니다

Class.DataSetInputParam.nativeTypeName=nativeTypeName
Class.DataSetInputParam.nativeTypeName.toolTip=고유 데이터 형식의 이름을 표시합니다

Class.DataSetInputParam.recordDefn=recordDefn
Class.DataSetInputParam.recordDefn.toolTip=복합 매개 변수 내의 각 필드에 대한 정의입니다



#24. DataSetOutputParam
Class.DataSetOutputParam=DataSetOutputParam 클래스

Class.DataSetOutputParam.toolTip=ODA 데이터 집합에 대한 하나의 출력 매개 변수를 설명합니다

Class.DataSetOutputParam.name=이름

Class.DataSetOutputParam.name.toolTip=출력 매개 변수의 고유 이름입니다

Class.DataSetOutputParam.displayName=displayName
Class.DataSetOutputParam.displayName.toolTip=출력 매개 변수의 비즈니스 이름입니다

Class.DataSetOutputParam.description=설명

Class.DataSetOutputParam.description.toolTip=매개 변수에 대한 자세한 설명을 제공하는 자유 형식 문자열입니다

Class.DataSetOutputParam.nativeTypeCode=nativeTypeCode
Class.DataSetOutputParam.nativeTypeCode.toolTip=매개 변수의 고유 데이터 형식 코드입니다

Class.DataSetOutputParam.nativeTypeName=nativeTypeName
Class.DataSetOutputParam.nativeTypeName.toolTip=고유 데이터 형식의 이름을 표시합니다

Class.DataSetOutputParam.recordDefn=recordDefn
Class.DataSetOutputParam.recordDefn.toolTip=복합 매개 변수 내 각 필드의 정의입니다


#25. ItemState

Class.ItemState=ItemState
Class.ItemState.toolTip=보고서 요소에 대한 런타임 상태를 나타냅니다

Class.ItemState.row=행

Class.ItemState.row.toolTip=현재 가장 안쪽 행을 나타냅니다

Class.ItemState.rows=행

Class.ItemState.rows.toolTip=이 계층 내의 행에 대해 액세스를 허용합니다


#26. Total
Class.Total=합계(집계) 함수

Class.Total.toolTip=집계 함수의 표시자입니다

Class.Total.OVERALL=OVERALL

Class.Total.OVERALL.toolTip=데이터 집합에 대한 전체 합계를 요청하는 그룹 인수에서 사용하는 상수입니다

Class.Total.NO_FILTER=NO_FILTER
Class.Total.NO_FILTER.toolTip=필터가 없음을 표시하기 위해 집계 함수의 필터 인수에 사용되는 상수

Class.Total.sum=합

Class.Total.sum.toolTip=숫자 시퀀스의 합계입니다

Class.Total.runningSum=runningSum

Class.Total.runningSum.toolTip=합계와 유사하지만 보고서의 지정된 지점에서 누계를 표시합니다

Class.Total.count=수

Class.Total.count.toolTip=행의 수입니다

Class.Total.runningCount=runningCount
Class.Total.runningCount.toolTip=현재 그룹에서 실행 중인 행의 수

Class.Total.countDistinct=countDistinct
Class.Total.countDistinct.toolTip=고유 값의 수입니다

Class.Total.max=max

Class.Total.max.toolTip=숫자 시퀀스, 문자열 또는 날짜의 최대값입니다

Class.Total.min=min

Class.Total.min.toolTip=숫자 시퀀스, 문자열 또는 날짜의 최소값입니다

Class.Total.ave=ave

Class.Total.ave.toolTip=숫자 시퀀스 또는 날짜의 평균값입니다

Class.Total.weightedAve=weightedAve

Class.Total.weightedAve.toolTip=숫자 시퀀스의 가중치입니다

Class.Total.weightedAve.weight=weight

Class.Total.movingAve=movingAve

Class.Total.movingAve.toolTip=평균을 계산할 때 사용자가 숫자 값을 지정한 숫자 시퀀스의 누계입니다

Class.Total.movingAve.window=window

Class.Total.median=중앙값

Class.Total.median.toolTip=숫자 시퀀스의 수치 중앙값입니다

Class.Total.mode=모드

Class.Total.mode.toolTip=값 시퀀스의 수치 모드입니다

Class.Total.stdDev=stdDev

Class.Total.stdDev.toolTip=숫자 시퀀스의 수치 표준 편차입니다

Class.Total.variance=분산

Class.Total.variance.toolTip=숫자 시퀀스의 수치 편차입니다

Class.Total.first=처음

Class.Total.first.toolTip=시퀀스의 첫 번째 값입니다

Class.Total.last=마지막

Class.Total.last.toolTip=시퀀스의 마지막 값입니다

Class.Total.rank=등급

Class.Total.rank.toolTip=계열의 숫자, 문자열 또는 날짜/시간 값의 등급(1부터 시작)을 반환합니다.

Class.Total.rank.ascending=오름차순

Class.Total.percentRank=percentRank
Class.Total.percentRank.toolTip=값의 비율 등급을 반환합니다. 반환값은 [0..1] 범위의 숫자입니다.

Class.Total.percentile=백분위수

Class.Total.percentile.toolTip=백분위수 값을 반환합니다. pct의 범위는 0에서 1까지입니다. pct가 0인 경우 Total.min(expr)와 같은 값을 반환하고, pct가 1인 경우 Total.max(expr)와 같은 값을 반환합니다.

Class.Total.percentile.pct=백분율

Class.Total.quartile=4분위수

Class.Total.quartile.toolTip=백분위수 값을 반환합니다. 4분위수는 1에서 4까지의 정수 범위에 있습니다. 4분위수가 1이면 Total.percentile(expr,0.25)과 같은 값을 반환하고, 4분위수가  2이면 Total.percentile(expr,0.5)과 같은 값을 반환합니다

Class.Total.quartile.quart=quart

Class.Total.percentSum=percentSum

Class.Total.percentSum.toolTip=Total.Equals 대 expr/Total.sum(expr, [group])의 백분율

Class.Total.isTopN=isTopN

Class.Total.isTopN.toolTip=해당 값이 그룹에 있는 상위 n 값 중 하나일 경우 참 값을 반환합니다.

Class.Total.isTopN.n=n
Class.Total.isTopNPercent=isTopNPercent

Class.Total.isTopNPercent.toolTip=해당 값이 그룹에 있는 상위(pct * 100) 백분율 값 중 하나일 경우 참 값을 반환합니다. 그렇지 않은 경우 거짓 값을 반환합니다.

Class.Total.isTopNPercent.pct=백분율

Class.Total.isBottomN=isBottomN

Class.Total.isBottomN.toolTip=해당 값이 그룹에 있는 하위 n 값 중 하나일 경우 참 값을 반환합니다. 그렇지 않은 경우 거짓 값을 반환합니다.

Class.Total.isBottomN.n=n
Class.Total.isBottomNPercent=isBottomNPercent

Class.Total.isBottomNPercent.toolTip=해당 값이 그룹에 있는 하위(pct * 100) 백분율 값 중 하나일 경우 참 값을 반환합니다. 그렇지 않은 경우 거짓 값을 반환합니다.

Class.Total.isBottomNPercent.pct=백분율

#27. Finance
Class.Finance=재무 함수

Class.Finance.toolTip=정적 재무 함수의 컬렉션입니다

Class.Finance.ddb=ddb

Class.Finance.ddb.toolTip=주어진 한 기간 동안 이중 체감법을 사용한 자산의 감가 상각액입니다

Class.Finance.ddb.initialCost=initialCost
Class.Finance.ddb.salvageValue=salvageValue
Class.Finance.ddb.assetLifespan=assetLifespan
Class.Finance.ddb.singlePeriod=singlePeriod
Class.Finance.sln=sln

Class.Finance.sln.toolTip=한 기간 동안 정율법에 의한 자산의 감가 상각액입니다

Class.Finance.sln.initialCost=initialCost
Class.Finance.sln.salvageValue=salvageValue
Class.Finance.sln.assetLifespan=assetLifespan 
Class.Finance.syd=syd

Class.Finance.syd.toolTip=주어진 기간 동안 연수 합계법에 의한 자산의 감가 상각액입니다

Class.Finance.syd.initialCost=initialCost
Class.Finance.syd.salvageValue=salvageValue
Class.Finance.syd.assetLifespan=assetLifespan
Class.Finance.syd.singlePeriod=singlePeriod
Class.Finance.fv=fv

Class.Finance.fv.toolTip=주기적이고 고정적인 지급과 고정적인 이자율에 근거한 연금의 예측값입니다

Class.Finance.fv.ratePerPeriod=ratePerPeriod

Class.Finance.fv.numberPayPeriods=numberPayPeriods

Class.Finance.fv.eachPmt=eachPmt

Class.Finance.fv.presentValue=presentValue
Class.Finance.fv.whenDue=whenDue

Class.Finance.ipmt=ipmt

Class.Finance.ipmt.toolTip=주기적이고 고정적인 지급과 고정적인 이자율에 근거한 주어진 기간 동안의 연금에 대한 이자 지급입니다

Class.Finance.ipmt.ratePerPeriod=ratePerPeriod

Class.Finance.ipmt.singlePeriod=singlePeriod
Class.Finance.ipmt.numberPayPeriods=numberPayPeriods

Class.Finance.ipmt.presentValue=presentValue
Class.Finance.ipmt.futureValue=futureValue
Class.Finance.ipmt.whenDue=whenDue

Class.Finance.nper=nper

Class.Finance.nper.toolTip=주기적이고 고정적인 지급과 고정적인 이자율에 근거한 연금에 대한 기간 수입니다

Class.Finance.nper.ratePerPeriod=ratePerPeriod

Class.Finance.nper.eachPmt=eachPmt

Class.Finance.nper.presentValue=presentValue
Class.Finance.nper.futureValue=futureValue
Class.Finance.nper.whenDue=whenDue

Class.Finance.pmt=pmt

Class.Finance.pmt.toolTip=주기적이고 고정적인 지급과 고정적인 이자율에 근거한 연금에 대한 지급입니다

Class.Finance.pmt.ratePerPeriod=ratePerPeriod

Class.Finance.pmt.numberPayPeriods=numberPayPeriods

Class.Finance.pmt.presentValue=presentValue
Class.Finance.pmt.futureValue=futureValue
Class.Finance.pmt.whenDue=whenDue

Class.Finance.ppmt=ppmt

Class.Finance.ppmt.toolTip=주기적이고 고정적인 지급과 고정적인 이자율에 근거한 주어진 기간 동안의 연금에 대한 원금 지급입니다

Class.Finance.ppmt.ratePerPeriod=ratePerPeriod

Class.Finance.ppmt.singlePeriod=singlePeriod
Class.Finance.ppmt.numberPayPeriods=numberPayPeriods

Class.Finance.ppmt.presentValue=presentValue
Class.Finance.ppmt.futureValue=futureValue
Class.Finance.ppmt.whenDue=whenDue

Class.Finance.pv=pv

Class.Finance.pv.toolTip=미래에 지불할 주기적이고 고정적인 지급과 고정적인 이자율에 근거한 연금에 대한 현재 값입니다

Class.Finance.pv.ratePerPeriod=ratePerPeriod

Class.Finance.pv.numberPayPeriods=numberPayPeriods

Class.Finance.pv.eachPmt=eachPmt

Class.Finance.pv.futureValue=futureValue
Class.Finance.pv.whenDue=whenDue

Class.Finance.rate=비율

Class.Finance.rate.toolTip=연금에 대한 기간별 이자율입니다

Class.Finance.rate.numberPayPeriods=numberPayPeriods

Class.Finance.rate.eachPmt=eachPmt

Class.Finance.rate.presentValue=presentValue
Class.Finance.rate.futureValue=futureValue
Class.Finance.rate.whenDue=whenDue

Class.Finance.rate.startingGuess=startingGuess
Class.Finance.irr=irr

Class.Finance.irr.toolTip=기존 배열에서 일련의 주기적 현금 흐름, 지급 및 수금에 대한 내부 수익률입니다

Class.Finance.irr.cashArray=cashArray
Class.Finance.irr.startingGuess=startingGuess
Class.Finance.npv=npv

Class.Finance.npv.toolTip=주어진 이자율에서 일련의 여러 양수 값 및 음수 값의 주기적 현금 흐름에 대한 순 현재 가치입니다

Class.Finance.npv.rate=비율

Class.Finance.npv.cashArray=cashArray 
Class.Finance.runningnpv=npv

Class.Finance.runningnpv.toolTip=주어진 이자율에서 일련의 여러 주기적 현금 흐름(증가 또는 감소)에 대한 순 현재 가치입니다.

Class.Finance.runningnpv.rate=비율

Class.Finance.runningnpv.cashArray=cashArray 
Class.Finance.mirr=mirr

Class.Finance.mirr.toolTip=기존 배열에서 일련의 주기적 현금 흐름(지급 및 수금)에 대한 수정된 내부 수익률입니다

Class.Finance.mirr.cashArray=cashArray
Class.Finance.mirr.rate=비율

Class.Finance.percent=percent

Class.Finance.percent.toolTip=두 숫자의 백분율을 계산합니다

Class.Finance.percent.denom=denom

Class.Finance.percent.num=num

Class.Finance.percent.rate=비율

#28. DateTimeSpan
Class.DateTimeSpan=DateTimeSpan 함수

Class.DateTimeSpan.toolTip=두 날짜 또는 시간 범위에서 작업하는 함수의 컬렉션입니다

Class.DateTimeSpan.years=연

Class.DateTimeSpan.years.toolTip=두 날짜 사이의 전체 연도 수를 반환합니다

Class.DateTimeSpan.years.startDate=startDate
Class.DateTimeSpan.years.endDate=endDate
Class.DateTimeSpan.months=월

Class.DateTimeSpan.months.toolTip=두 날짜 사이의 전체 월 수를 반환합니다

Class.DateTimeSpan.months.startDate=startDate
Class.DateTimeSpan.months.endDate=endDate
Class.DateTimeSpan.days=일

Class.DateTimeSpan.days.toolTip=두 날짜 사이의 날짜 수를 반환합니다

Class.DateTimeSpan.days.startDate=startDate
Class.DateTimeSpan.days.endDate=endDate
Class.DateTimeSpan.hours=시

Class.DateTimeSpan.hours.toolTip=두 날짜/시간 사이의 시간 수를 반환합니다

Class.DateTimeSpan.hours.startDate=startDate
Class.DateTimeSpan.hours.endDate=endDate
Class.DateTimeSpan.minutes=분

Class.DateTimeSpan.minutes.toolTip=두 날짜/시간 사이의 분 수를 반환합니다

Class.DateTimeSpan.minutes.startDate=startDate
Class.DateTimeSpan.minutes.endDate=endDate
Class.DateTimeSpan.seconds=초

Class.DateTimeSpan.seconds.toolTip=두 날짜/시간 사이의 초 수를 반환합니다

Class.DateTimeSpan.seconds.startDate=startDate
Class.DateTimeSpan.seconds.endDate=endDate

Class.DateTimeSpan.addDate=addDate
Class.DateTimeSpan.addDate.toolTip=날짜에 연도 수, 월 수 또는 날짜 수를 추가합니다

Class.DateTimeSpan.addDate.startDate=startDate
Class.DateTimeSpan.addDate.years=연

Class.DateTimeSpan.addDate.months=월

Class.DateTimeSpan.addDate.days=일



Class.DateTimeSpan.addTime=addTime
Class.DateTimeSpan.addTime.toolTip=날짜/시간에 시간 수,분 수 또는 초 수를 추가합니다

Class.DateTimeSpan.addTime.startDate=startDate
Class.DateTimeSpan.addTime.hours=시

Class.DateTimeSpan.addTime.minutes=분

Class.DateTimeSpan.addTime.seconds=초


Class.DateTimeSpan.subDate=subDate
Class.DateTimeSpan.subDate.toolTip=날짜에서 연도 수, 월 수 또는 날짜 수를 뺍니다

Class.DateTimeSpan.subDate.startDate=startDate
Class.DateTimeSpan.subDate.years=연

Class.DateTimeSpan.subDate.months=월

Class.DateTimeSpan.subDate.days=일



Class.DateTimeSpan.subTime=subTime
Class.DateTimeSpan.subTime.toolTip=날짜에서 시간 수, 분 수 또는 초 수를 뺍니다

Class.DateTimeSpan.subTime.startDate=startDate
Class.DateTimeSpan.subTime.hours=시

Class.DateTimeSpan.subTime.minutes=분

Class.DateTimeSpan.subTime.seconds=초

#29.GlobalBirt
Class.GlobalBirt=전역 변수

Class.GlobalBirt.toolTip=식과 스크립트가 데이터 행 및 보고서 정보에 대해 액세스 하도록 허용하는 전역 변수의 수를 제공합니다

Class.GlobalBirt.datasets=Birt 데이터 집합

Class.GlobalBirt.datasets.toolTip=보고서에 정의된 데이터 집합의 배열을 반환합니다

Class.GlobalBirt.params=Birt 매개 변수

Class.GlobalBirt.params.toolTip=보고서에 전달된 매개 변수 값의 객체 배열을 반환합니다

Class.GlobalBirt.row=Birt 행

Class.GlobalBirt.row.toolTip=데이터 집합 또는 보고서 요소에 대한 현재 데이터 행입니다

Class.GlobalBirt.rows=Birt 행

Class.GlobalBirt.rows.toolTip=현재 컨텍스트에 대해 정의된 행 스택입니다

Class.GlobalBirt.config=Birt 구성

Class.GlobalBirt.config.toolTip=보고서에서 사용 가능한 구성 변수의 배열을 반환합니다. 이름/값 쌍으로 표시합니다

Class.GlobalBirt.report=Birt 보고서

Class.GlobalBirt.report.toolTip=보고서에 대한 모든 정보 및 보고서가 실행하는 컨텍스트에 대한 액세스를 제공합니다

Class.GlobalBirt.CurrentPage=현재 페이지 번호

Class.GlobalBirt.CurrentPage.toolTip=현재 페이지 번호를 반환합니다.

Class.GlobalBirt.TotalPage=전체 페이지 수

Class.GlobalBirt.TotalPage.toolTip=전체 페이지 수를 반환합니다.

Class.GlobalBirt.this=개체

Class.GlobalBirt.this.toolTip=개체를 표시합니다.

Class.GlobalBirt.appContext=AppContext
Class.GlobalBirt.appContext.toolTip=이 보고서와 관련된 컨텍스트

#30 DataSource
Class.DataSource=데이터 원본 클래스

Class.DataSource.toolTip=데이터 원본 클래스는 데이터 원본의 공장 시간 상태로의 액세스를 제공합니다. 데이터 원본 객체는 이 객체를 사용하는 데이터 집합 객체를 통해 액세스할 수 있습니다.

Class.DataSource.extensionID=extensionID

Class.DataSource.extensionID.toolTip=ODA 드라이버 확장명에서 정의한 바와 같이 ODA 데이터 원본의 extensionID 값을 반환합니다. extensionID는 BIRT 환경의 데이터 원본 형식을 고유하게 확인하며, 이 속성은 업데이트할 수 없습니다.

Class.DataSource.isOpen=isOpen

Class.DataSource.isOpen.toolTip=데이터 원본 연결 여부를 나타내는 부울 값을 반환합니다.

Class.DataSource.extensionProperties=extensionProperties
Class.DataSource.extensionProperties.toolTip=ODA 데이터 원본의 개별 속성을 제공합니다.

#31. BirtComp
 
Class.BirtComp=BirtComp
Class.BirtComp.toolTip=Birt 데이터 비교 지원 제공

Class.BirtComp.equalTo=equalsTo

Class.BirtComp.equalTo.toolTip=x는 y와 같음

Class.BirtComp.equalTo.x=x
Class.BirtComp.equalTo.y=y

Class.BirtComp.greaterThan=greaterThan
Class.BirtComp.greaterThan.toolTip=x는 y보다 큼

Class.BirtComp.greaterThan.x=x
Class.BirtComp.greaterThan.y=y

Class.BirtComp.lessThan=lessThan
Class.BirtComp.lessThan.toolTip=x는 y보다 작음

Class.BirtComp.lessThan.x=x
Class.BirtComp.lessThan.y=y

Class.BirtComp.greaterOrEqual=greaterOrEqual

Class.BirtComp.greaterOrEqual.toolTip=x는 y보다 크거나 같음

Class.BirtComp.greaterOrEqual.x=x
Class.BirtComp.greaterOrEqual.y=y

Class.BirtComp.lessOrEqual=lessOrEqual

Class.BirtComp.lessOrEqual.toolTip=x는 y보다 작거나 같음

Class.BirtComp.lessOrEqual.x=x
Class.BirtComp.lessOrEqual.y=y

Class.BirtComp.notEqual=notEqual
Class.BirtComp.notEqual.toolTip=x는 y와 같지 않음

Class.BirtComp.notEqual.x=x
Class.BirtComp.notEqual.y=y

Class.BirtComp.between=-

Class.BirtComp.between.toolTip=값은 r1보다 크거나 같고 r2보다 작거나 같음

Class.BirtComp.between.val=값

Class.BirtComp.between.r1=r1

Class.BirtComp.between.r2=r2

Class.BirtComp.like=유사

Class.BirtComp.like.toolTip=x는 SQL 패턴 y와 일치함

Class.BirtComp.like.x=x
Class.BirtComp.like.y=y

Class.BirtComp.match=일치

Class.BirtComp.match.toolTip=x는 Javascript 패턴 y와 일치함

Class.BirtComp.match.x=x
Class.BirtComp.match.y=y

Class.BirtComp.anyOf=anyOf

Class.BirtComp.anyOf.toolTip=값이 다음 인수에 있는지 확인

Class.BirtComp.anyOf.val=값


###########################################################
# Structures
Structure.MapRule=MapRule
Structure.HighlightRule=HighlightRule
Structure.CustomColor=CustomColor
Structure.SearchKey=SearchKey

Structure.Action=작업

Structure.UserProperty=UserProperty
Structure.SortKey=정렬 키

Structure.FilterCondition=필터 조건

Structure.ConfigVar=구성 변수

Structure.HideRule=숨기기

Structure.IncludeScript=스크립트 포함

Structure.EmbeddedImage=내장된 이미지

Structure.OdaProperty=ODA 속성

Structure.ParamBinding=매개 변수 바인딩

Structure.ResultSetColumn=열

Structure.ComputedColumn=계산 열

Structure.ColumnHint=열 힌트

Structure.IncludedLibrary=포함된 라이브러리

Structure.DataSetParam=데이터 집합 매개 변수

Structure.PropertyMask=속성 마스크

Structure.ExtendedProperty=확장 속성

Structure.CachedMetaData=캐시된 메타데이터

Structure.NumberFormatValue=숫자 형식 값

Structure.StringFormatValue=문자열 형식 값

Structure.DateTimeFormatValue=날짜/시간 형식 값

Structure.DateFormatValue = 데이터 형식 값

Structure.TimeFormatValue = 시간 형식 값

Structure.UserMethod=사용자 메서드

Structure.PropertyBinding=속성 바인딩

Structure.JoinCondition=조인 조건

Structure.ParameterFormatValue=매개 변수 형식 값

Structure.OdaDesignerState=ODA 디자이너 상태

Structure.ScriptLib=스크립트 Lib

Structure.IncludedCssStyleSheet=CSS 스타일시트 포함

Structure.DimensionJoinCondition=차원 조인 조건

Structure.FormatValue =형식 값

Structure.CalculationArgument=계산 인수

#0.MapRule
Structure.MapRule.testExpr=TestExpression
Structure.MapRule.operator=연산자

Structure.MapRule.value1=value1

Structure.MapRule.value2=value2

Structure.MapRule.display=표시

Structure.MapRule.displayID=displayID

Structure.MapRule.isDesignTime=디자인 시간 여부
  
#1.HighlightRule
Structure.HighlightRule.operator=연산자

Structure.HighlightRule.isDesignTime=디자인 시간 여부

Structure.HighlightRule.value1=값 1

Structure.HighlightRule.value2=값 2

Structure.HighlightRule.testExpr = TestExpression
Structure.HighlightRule.strikethrough=취소선

Structure.HighlightRule.border.top.style=스타일

Structure.HighlightRule.border.top.width=너비

Structure.HighlightRule.border.top.color=색

Structure.HighlightRule.border.left.style=스타일

Structure.HighlightRule.border.left.width=너비

Structure.HighlightRule.border.left.color=색

Structure.HighlightRule.border.bottom.style=스타일

Structure.HighlightRule.border.bottom.width=너비

Structure.HighlightRule.border.bottom.color=색

Structure.HighlightRule.border.right.style=스타일

Structure.HighlightRule.border.right.width=너비

Structure.HighlightRule.border.right.color=색

Structure.HighlightRule.background.color=배경색

Structure.HighlightRule.background.image=배경 이미지

Structure.HighlightRule.backgroundRepeat=배경 반복

Structure.HighlightRule.format.dateTime=날짜 시간 형식

Structure.HighlightRule.format.number=숫자 형식

Structure.HighlightRule.format.number.align=숫자 맞춤

Structure.HighlightRule.format.string=문자열 형식

Structure.HighlightRule.font.family=글꼴

Structure.HighlightRule.font.size=글꼴 크기

Structure.HighlightRule.font.style=글꼴 스타일

Structure.HighlightRule.font.weight=글꼴 두께

Structure.HighlightRule.font.variant=글꼴 변형

Structure.HighlightRule.font.color=색

Structure.HighlightRule.font.textUnderline=밑줄

Structure.HighlightRule.font.textOverline=윗줄

Structure.HighlightRule.font.textLineThrough=가운데 줄

Structure.HighlightRule.padding.top=안쪽 여백 위쪽

Structure.HighlightRule.padding.left=안쪽 여백 왼쪽

Structure.HighlightRule.padding.bottom=안쪽 여백 아래쪽

Structure.HighlightRule.padding.right=안쪽 여백 오른쪽

Structure.HighlightRule.text.align=텍스트 맞춤

Structure.HighlightRule.text.indent=텍스트 들여쓰기

Structure.HighlightRule.text.transform=텍스트 변환

Structure.HighlightRule.style=스타일

Structure.HighlightRule.text.direction=텍스트 방향

#2.CustomColor
Structure.CustomColor.name=이름

Structure.CustomColor.color=색

Structure.CustomColor.displayName=표시 이름

Structure.CustomColor.displayNameID=표시 이름 키
  
#4.DrillThroughSearchKeys
Structure.SearchKey.expression=식
  
#5.UserProperty
Structure.UserProperty.name=이름

Structure.UserProperty.type=형식

Structure.UserProperty.isVisible=표시 여부

Structure.UserProperty.displayNameID=표시 이름 키

Structure.UserProperty.displayName=표시 이름

#6.ConfigVar
Structure.ConfigVar.name=이름

Structure.ConfigVar.value=값

#7. SortKey
Structure.SortKey.key=정렬 키

Structure.SortKey.direction=정렬 방향

Structure.SortKey.strength=수준 정렬

Structure.SortKey.locale=로케일 정렬

#8. Hide
Structure.HideRule.format=형식

Structure.HideRule.valueExpr=식

#9. IncludeScript
Structure.IncludeScript.fileName=파일 이름

#10.EmbeddedImage
Structure.EmbeddedImage.name=이름

Structure.EmbeddedImage.type=형식

Structure.EmbeddedImage.data=데이터

Structure.EmbeddedImage.libReference=라이브러리 참조

#11.FilterCondition
Structure.FilterCondition.operator=연산자

Structure.FilterCondition.expr=식

Structure.FilterCondition.value1=값 1

Structure.FilterCondition.value2=값 2

Structure.FilterCondition.filterTarget=대상 필터

Structure.FilterCondition.isOptional=옵션 항목입니다.

Structure.FilterCondition.extensionName=확장 이름

Structure.FilterCondition.extensionExprId=확장 식 ID

Structure.FilterCondition.pushDown=아래로 밀어내기

Structure.FilterCondition.dynamicFilterParameter=동적 필터 매개 변수

Structure.FilterCondition.type=형식

Structure.FilterCondition.updateAggregation=집계 업데이트

#10. PropertyMask
Structure.PropertyMask.name=이름

Structure.PropertyMask.mask=마스크

#11.OdaProperty
Structure.OdaProperty.name=이름

Structure.OdaProperty.value=값

#13. ParamBinding
Structure.ParamBinding.paramName=매개 변수 이름

Structure.ParamBinding.expression=식

#14. ResultSetColumn
Structure.ResultSetColumn.position=위치

Structure.ResultSetColumn.name=이름

Structure.ResultSetColumn.dataType=데이터 형식

Structure.ResultSetColumn.nativeDataType=고유 데이터 형식 코드

#15. ComputedColumn
Structure.ComputedColumn.name=열 이름

Structure.ComputedColumn.displayName=열 표시 이름

Structure.ComputedColumn.displayNameID=열 표시 이름 ID

Structure.ComputedColumn.expression=식

Structure.ComputedColumn.dataType=데이터 형식

Structure.ComputedColumn.aggregateOn=AggregateOn 식

Structure.ComputedColumn.aggregateFunction=AggregateOn 함수

Structure.ComputedColumn.arguments=AggregateOn 함수 인수

Structure.ComputedColumn.filterExpr=필터 식

Structure.ComputedColumn.allowExport=내보내기 허용

Structure.ComputedColumn.calculationType=계산 형식

Structure.ComputedColumn.calculationArguments=계산 인수

Structure.ComputedColumn.refDateType=참조 날짜 형식

Structure.ComputedColumn.refDateValue=참조 날짜 값

Structure.ComputedColumn.timeDimension=시간 차원

#16. ColumnHint
Structure.ColumnHint.columnName=열 이름

Structure.ColumnHint.alias=별칭

Structure.ColumnHint.searching=검색

Structure.ColumnHint.export=내보내기

Structure.ColumnHint.analysis=분석

Structure.ColumnHint.parentLevel=상위 수준

Structure.ColumnHint.format=형식

Structure.ColumnHint.helpText=도움말 텍스트

Structure.ColumnHint.helpTextID=도움말 텍스트 리소스 키

Structure.ColumnHint.displayName=표시 이름

Structure.ColumnHint.displayNameID=표시 이름 리소스 키

Structure.ColumnHint.onColumnLayout=열 레이아웃 시

Structure.ColumnHint.heading=머리글

Structure.ColumnHint.headingID=머리글 리소스 키

Structure.ColumnHint.displayLength=표시 길이

Structure.ColumnHint.horizontalAlign=수평 맞춤

Structure.ColumnHint.wordWrap=자동 줄 바꿈

Structure.ColumnHint.textFormat=텍스트 형식

Structure.ColumnHint.description=설명

Structure.ColumnHint.descriptionID=설명 리소스 키

Structure.ColumnHint.action=작업

Structure.ColumnHint.ACLExpression=ACL 식

Structure.ColumnHint.analysisColumn=분석 열

Structure.ColumnHint.valueFormat=값 형식

Structure.ColumnHint.indexColumn=인덱스 열

Structure.ColumnHint.compressed=압축됨

#12. SelectionList Choice
Structure.SelectionChoice=선택 영역 선택

Structure.SelectionChoice.value=값

Structure.SelectionChoice.label=레이블

Structure.SelectionChoice.labelID=레이블 리소스 키

#13. IncludedLibrary
Structure.IncludedLibrary.fileName=파일 이름

Structure.IncludedLibrary.namespace=네임스페이스

#14. IncludedCssStyleSheet
Structure.IncludedCssStyleSheet.fileName=파일 이름

Structure.IncludedCssStyleSheet.externalCssURI=외부 CSS URI

Structure.IncludedCssStyleSheet.useExternalCss=외부 CSS 사용

#15. DataSetParam
Structure.DataSetParam.name=이름

Structure.DataSetParam.dataType=데이터 형식

Structure.DataSetParam.position=위치

Structure.DataSetParam.defaultValue=기본값

Structure.DataSetParam.isOptional=옵션 항목입니다.

Structure.DataSetParam.allowNull=널(null) 허용

Structure.DataSetParam.isInput=입력 매개 변수입니다.

Structure.DataSetParam.isOutput=출력 매개 변수입니다.

Structure.DataSetParam.nativeDataType=고유 데이터 형식 코드

Structure.DataSetParam.displayName=표시 이름

Structure.DataSetParam.displayNameID=표시 이름 리소스 키

Structure.DataSetParam.heading=머리글

Structure.DataSetParam.headingID=머리글 리소스 키

Structure.DataSetParam.helpText=도움말 텍스트

Structure.DataSetParam.helpTextID=도움말 텍스트 리소스 키

Structure.DataSetParam.description=설명

Structure.DataSetParam.descriptionID=설명 리소스 키

#16. ExtendedProperty
Structure.ExtendedProperty.name=이름

Structure.ExtendedProperty.value=값

#17. Action
Structure.Action.linkType=링크 형식

Structure.Action.toolTip=도구 설명

Structure.Action.targetWindow=대상

Structure.Action.linkExpr=링크 식

Structure.Action.uri=위치

Structure.Action.targetBookmark=책갈피 링크

Structure.Action.reportName=보고서 이름

Structure.Action.paramBindings=매개 변수 바인딩

Structure.Action.search=검색 키

Structure.Action.formatType=서식 형식

Structure.Action.targetFileType=대상 파일 형식

Structure.Action.targetBookmarkType=대상 책갈피 형식

#18. CachedMetaData
Structure.CachedMetaData.parameters=매개 변수

Structure.CachedMetaData.resultSet=결과 집합 열

#19. NumberFormatValue
Structure.NumberFormatValue.category=범주

Structure.NumberFormatValue.pattern=패턴

Structure.NumberFormatValue.locale=로케일

#20. StringFormatValue
Structure.StringFormatValue.category=범주

Structure.StringFormatValue.pattern=패턴

Structure.StringFormatValue.locale=로케일

#21. DateTimeFormatValue
Structure.DateTimeFormatValue.category=범주

Structure.DateTimeFormatValue.pattern=패턴

Structure.DateTimeFormatValue.locale=로케일

#21. DateFormatValue
Structure.DateFormatValue.category=범주

Structure.DateFormatValue.pattern=패턴

Structure.DateFormatValue.locale=로케일

#21. TimeFormatValue
Structure.TimeFormatValue.category=범주

Structure.TimeFormatValue.pattern=패턴

Structure.TimeFormatValue.locale=로케일

#22. UserMethod
Structure.UserMethod.name=이름

#23. PropertyBinding
Structure.PropertyBinding.name=이름

Structure.PropertyBinding.id=요소 ID

Structure.PropertyBinding.value=값

#24. JoinCondition
Structure.JoinCondition.joinType=조인 형식

Structure.JoinCondition.joinOperator=조인 연산자

Structure.JoinCondition.leftDataSet=왼쪽 데이터 집합

Structure.JoinCondition.rightDataSet=오른쪽 데이터 집합

Structure.JoinCondition.leftExpression=좌변

Structure.JoinCondition.rightExpression=우변

#25. ParameterFormatValue
Structure.ParameterFormatValue.category=범주

Structure.ParameterFormatValue.pattern=패턴

Structure.ParameterFormatValue.locale=로케일

#26. OdaDesignerState
Structure.OdaDesignerState.version=버전

Structure.OdaDesignerState.stateContentAsString=상태 내용을 문자열로 표시

Structure.OdaDesignerState.stateContentAsBlob=상태 내용을 BLOB로 표시

#27. OdaResultSetColumn
Structure.OdaResultSetColumn=OdaResultSetColumn

Structure.OdaResultSetColumn.position=위치

Structure.OdaResultSetColumn.name=이름

Structure.OdaResultSetColumn.nativeName=고유 이름

Structure.OdaResultSetColumn.dataType=데이터 형식

Structure.OdaResultSetColumn.nativeDataType=고유 데이터 형식 코드

#28. OdaDataSetParam
Structure.OdaDataSetParam=OdaDataSetParam

Structure.OdaDataSetParam.name=이름

Structure.OdaDataSetParam.paramName=매개 변수 이름

Structure.OdaDataSetParam.nativeName=고유 이름

Structure.OdaDataSetParam.dataType=데이터 형식

Structure.OdaDataSetParam.nativeDataType=고유 데이터 형식 코드

Structure.OdaDataSetParam.position=위치

Structure.OdaDataSetParam.defaultValue=기본값

Structure.OdaDataSetParam.isOptional=옵션 여부

Structure.OdaDataSetParam.allowNull=널(null) 허용

Structure.OdaDataSetParam.isInput=입력 여부

Structure.OdaDataSetParam.isOutput=출력 여부

Structure.OdaDataSetParam.displayName=표시 이름

Structure.OdaDataSetParam.displayNameID=표시 이름 리소스 키

Structure.OdaDataSetParam.heading=머리글

Structure.OdaDataSetParam.headingID=머리글 리소스 키

Structure.OdaDataSetParam.helpText=도움말 텍스트

Structure.OdaDataSetParam.helpTextID=도움말 텍스트 리소스 키

Structure.OdaDataSetParam.description=설명

Structure.OdaDataSetParam.descriptionID=설명 리소스 키

#27. ScriptLib
Structure.ScriptLib.name =스크립트 Lib 이름

#28. TOC
Structure.TOC=목차

Structure.TOC.Expression=식

Structure.TOC.TOCStyle=TOC 스타일

Structure.TOC.border.top.style=테두리 위쪽 스타일

Structure.TOC.border.top.width=테두리 위쪽 너비

Structure.TOC.border.top.color=테두리 위쪽 색

Structure.TOC.border.left.style=테두리 왼쪽 스타일

Structure.TOC.border.left.width=테두리 왼쪽 너비

Structure.TOC.border.left.color=테두리 왼쪽 색

Structure.TOC.border.bottom.style=테두리 아래쪽 스타일

Structure.TOC.border.bottom.width=테두리 아래쪽 너비

Structure.TOC.border.bottom.color=테두리 아래쪽 색

Structure.TOC.border.right.style=테두리 오른쪽 스타일

Structure.TOC.border.right.width=테두리 오른쪽 너비

Structure.TOC.border.right.color=테두리 오른쪽 색

Structure.TOC.background.color=배경색

Structure.TOC.format.dateTime=날짜 시간 형식

Structure.TOC.format.number=숫자 형식

Structure.TOC.format.number.align=숫자 맞춤 형식

Structure.TOC.format.string=문자열 형식

Structure.TOC.font.family=글꼴 패밀리

Structure.TOC.font.size=글꼴 크기

Structure.TOC.font.style=글꼴 스타일

Structure.TOC.font.weight=글꼴 두께

Structure.TOC.font.variant=글꼴 변형

Structure.TOC.font.color=글꼴 색상

Structure.TOC.font.textUnderline=글꼴 텍스트 밑줄

Structure.TOC.font.textOverline=글꼴 텍스트 윗줄

Structure.TOC.font.textLineThrough=글꼴 텍스트 취소선

Structure.TOC.text.align=텍스트 맞춤

Structure.TOC.text.indent=텍스트 들여쓰기

Structure.TOC.text.transform=텍스트 변환

Structure.TOC.text.direction=텍스트 방향

#29. DimensionCondition
Structure.DimensionCondition=차원 조건

Structure.DimensionCondition.joinConditions=조인 조건

Structure.DimensionCondition.hierarchy=계층

#30. Rule
Structure.Rule=규칙

Structure.Rule.ruleExpre=규칙 식

Structure.Rule.displayExpre=표시 식

#31. LevelAttribute
Structure.LevelAttribute=수준 특성

Structure.LevelAttribute.name=이름

Structure.LevelAttribute.dataType=데이터 형식

#32. OdaLevelAttribute
Structure.OdaLevelAttribute=ODA 수준 특성

Structure.OdaLevelAttribute.name=이름

Structure.OdaLevelAttribute.dataType=데이터 형식

Structure.OdaLevelAttribute.nativeName=고유 이름

Structure.OdaLevelAttribute.nativeDataType=고유 데이터 형식 코드

#33. DimensionJoinCondition
Structure.DimensionJoinCondition.cubeKey=큐브 키

Structure.DimensionJoinCondition.hierarchyKey=계층 키

Structure.DimensionJoinCondition.level=수준

#34. AggregationArgument
Structure.AggregationArgument=집계 인수

Structure.AggregationArgument.name=인수 이름

Structure.AggregationArgument.value=인수 값

#35. Variable
Structure.Variable=변수

Structure.Variable.name=이름

Structure.Variable.value=값

#36. SortHint
Structure.SortHint=힌트 정렬

Structure.SortHint.columnName=열 이름

Structure.SortHint.position=열 위치

Structure.SortHint.direction=정렬 방향

Structure.SortHint.nullValueOrdering=널(Null) 값 순서

Structure.SortHint.isOptional=옵션

#37. IncludedDataMart
Structure.IncludedDataMart=데이터 마트 포함

Structure.IncludedDataMart.fileName=파일 이름

Structure.IncludedDataMart.namespace=네임스페이스

#38. TimeInterval
Structure.TimeInterval=시간 간격

Structure.TimeInterval.measure=측정

Structure.TimeInterval.unit=단위

#39. FormatValue
Structure.FormatValue.category=범주

Structure.FormatValue.pattern=패턴

Structure.FormatValue.locale=로케일

#40. CalculationArgument
Structure.CalculationArgument.name=계산 인수 이름

Structure.CalculationArgument.value=계산 인수 값

###########################################################
# Element names
Element.Module=모듈

Element.LayoutModule=레이아웃 모듈

Element.ReportDesign=보고서 디자인

Element.DesignElement=디자인 요소

Element.ReportElement=보고서 요소

Element.DataSource=데이터 원본

Element.JdbcDataSource=JDBC 데이터 원본

Element.DataSet=데이터 집합

Element.SimpleDataSet=단순 데이터 집합

Element.JdbcSelectDataSet=JDBC 선택 데이터 집합

Element.Parameter=매개 변수

Element.AbstractScalarParameter=추상적 스칼라 매개 변수

Element.ScalarParameter=ScalarParameter
Element.DynamicFilterParameter=동적 필터 매개 변수

Element.ParameterGroup=매개 변수 그룹

Element.CascadingParameterGroup=계단식 매개변수 그룹

Element.Style=스타일

Element.MasterPage=MasterPage
Element.ReportItem=보고서 항목

Element.Label=레이블

Element.AutoText=AutoText
Element.FreeForm=FreeForm
Element.Data=데이터

Element.Text=텍스트

Element.Library=라이브러리

Element.ListingGroup=열거 그룹

Element.List=목록

Element.ListGroup=목록 그룹

Element.Listint=열거

Element.Table=테이블

Element.TableGroup=테이블 그룹

Element.Column=열

Element.Row=행

Element.Cell=셀

Element.Image=이미지

Element.Grid=눈금

Element.Line=꺾은선형

Element.Tile=바둑판형

Element.Rectangle=사각형

Element.GraphicMasterPage=그래픽 마스터 페이지

Element.SimpleMasterPage=단순 마스터 페이지

Element.TextData=동적 텍스트

Element.ExtendedItem=확장 항목

Element.ScriptDataSource=스크립트 데이터 원본

Element.ScriptDataSet=스크립트 데이터 집합

Element.Listing=열거

Element.OdaDataSet=ODA 데이터 집합

Element.OdaDataSource=ODA 데이터 원본

Element.Theme=테마

Element.TemplateParameterDefinition=템플릿 매개 변수 정의

Element.TemplateElement=템플릿 요소

Element.TemplateReportItem=템플릿 보고서 항목

Element.TemplateDataSet=템플릿 데이터 집합

Element.JointDataSet=조인 데이터 집합

Element.Cube=Cube
Element.Dimension=차원

Element.Hierarchy=계층

Element.Level=수준

Element.Measure=측정

Element.MeasureGroup=측정값 그룹

Element.TabularCube=테이블 큐브

Element.TabularDimension=테이블 차원

Element.TabularHierarchy=테이블 계층

Element.TabularLevel=테이블 수준

Element.TabularMeasure=테이블 측정

Element.TabularMeasureGroup=테이블 측정값 그룹

Element.OdaCube=ODA 큐브

Element.OdaDimension=ODA 차원

Element.OdaHierarchy=ODA 계층

Element.OdaLevel=ODA 수준

Element.OdaMeasure=ODA 측정

Element.OdaMeasureGroup=ODA 측정값 그룹

Element.MemberValue=구성원 값

Element.SortElement=정렬 요소

Element.FilterConditionElement=필터 조건 요소

Element.AbstractMultiViews=요약 다중 보기

Element.MultiViews=다중 보기

Element.VariableElement=변수

Element.DataGroup=데이터 그룹

Element.DerivedDataSet=파생 데이터 집합

Element.DataMart=데이터 개체

Element.DataMartDataSource=데이터 개체 데이터 원본

Element.DataMartDataSet=데이터 개체 데이터 집합

Element.DataMartCube=데이터 개체 큐브

Element.TimeDimension=시간 차원

Element.ReportItemTheme=보고서 항목 테마

Element.AbstractTheme=추상적 테마

Element.DataMartLinkedDataModel=데이터 개체 데이터 모델

Element.AliasDataSet =별칭 데이터 집합

Element.LinkedDataModel =링크된 데이터 모델

Element.CategoryColumn =범주 열

Element.LinkedDataModel.pushDown=데이터 모델 아래로 밀어내기

Element.Category = 범주

Element.ColumnLink = 열 링크

Element.ColumnLinkPath = 열 링크 경로

Element.DrillPath = 드릴 경로

Element.LinkedDataModelCube = 링크된 데이터 모델 큐브

Element.LinkedDataModelDataSet = 링크된 데이터 모델 데이터 집합

###########################################################
# Element property names

# Module ( Prefix = Element.Module )
Element.Module.author=만든 이

Element.Module.title=제목

Element.Module.titleID=제목 키

Element.Module.description=설명

Element.Module.descriptionID=설명 키

Element.Module.comments=설명

Element.Module.includeResource=리소스 파일: Element.Module.base=기본

Element.Module.createdBy=만든 사람

Element.Module.includeScripts=스크립트 포함

Element.Module.scriptLibs=스크립트 라이브러리

Element.Module.externalMetadata=외부 메타데이터

Element.Module.propertyBindings=속성 바인딩

# LayoutModule ( Prefix = Element.LayoutModule )
Element.LayoutModule.subject=제목

Element.LayoutModule.helpGuide=도움말 설명서

Element.LayoutModule.colorPalette=색상표

Element.LayoutModule.configVars=구성 변수

Element.LayoutModule.images=이미지

Element.LayoutModule.libraries=라이브러리

Element.LayoutModule.base=기본

Element.LayoutModule.units=단위

Element.LayoutModule.theme=테마


# Library ( Prefix = Element.Library )
Element.Library.slot.styles=스타일

Element.Library.slot.parameters=매개 변수

Element.Library.slot.dataSources=데이터 원본

Element.Library.slot.dataSets=데이터 집합

Element.Library.slot.pageSetup=페이지 설정

Element.Library.slot.components=구성 요소

Element.Library.slot.themes=테마

Element.Library.slot.cubes=큐브

#1. Report Design ( Prefix = Element.ReportDesign )
Element.ReportDesign.refreshRate=새로 고침 빈도

Element.ReportDesign.eventHandlerClass=이벤트 처리기 클래스

Element.ReportDesign.newHandlerOnEachEvent=각 이벤트 시 새 처리기

Element.ReportDesign.beforeFactory=공장 이전

Element.ReportDesign.beforeFactory.this=보고서 디자인

Element.ReportDesign.beforeFactory.reportContext=보고서 컨텍스트

Element.ReportDesign.afterFactory=공장 이후

Element.ReportDesign.afterFactory.reportContext=보고서 컨텍스트

Element.ReportDesign.beforeOpenDoc=문서를 열기 전

Element.ReportDesign.beforeOpenDoc.reportContext=보고서 컨텍스트

Element.ReportDesign.afterOpenDoc=문서 열기 이후

Element.ReportDesign.afterOpenDoc.reportContext=보고서 컨텍스트

Element.ReportDesign.beforeCloseDoc=문서 닫기 이전

Element.ReportDesign.beforeCloseDoc.reportContext=보고서 컨텍스트

Element.ReportDesign.afterCloseDoc=문서 닫기 이후

Element.ReportDesign.afterCloseDoc.reportContext=보고서 컨텍스트

Element.ReportDesign.beforeRender=렌더링 이전

Element.ReportDesign.beforeRender.reportContext=보고서 컨텍스트

Element.ReportDesign.afterRender=렌더링 이후

Element.ReportDesign.afterRender.reportContext=보고서 컨텍스트

Element.ReportDesign.onPageStart.this=마스터 페이지

Element.ReportDesign.onPageStart.reportContext=보고서 컨텍스트

Element.ReportDesign.onPageEnd.this=마스터 페이지

Element.ReportDesign.onPageEnd.reportContext=보고서 컨텍스트

Element.ReportDesign.displayNameID=표시 이름 키

Element.ReportDesign.displayName=표시 이름

Element.ReportDesign.iconFile=아이콘 파일

Element.ReportDesign.cheatSheet=치트 시트

Element.ReportDesign.thumbnail=Thumbnail

Element.ReportDesign.layoutPreference=레이아웃 기본 설정

Element.ReportDesign.bidiLayoutOrientation=보고서 방향

Element.ReportDesign.beforeFactory.toolTip=onPrepare() 메서드 이후 및 보고서 문서(있는 경우) 열기 이전 공장 시작 시 호출됩니다.

Element.ReportDesign.afterFactory.toolTip=보고서 문서(있는 경우) 닫기 이후 공장 종료 시 호출됩니다. 공장에서 호출된 마지막 메서드입니다

Element.ReportDesign.beforeOpenDoc.toolTip=공장에서 보고서 문서를 열기 직전 호출됩니다

Element.ReportDesign.afterOpenDoc.toolTip=공장에서 보고서 문서를 열기 직후 호출됩니다

Element.ReportDesign.beforeCloseDoc.toolTip=공장에서 보고서 문서를 닫기 직전 호출됩니다

Element.ReportDesign.afterCloseDoc.toolTip=공장에서 보고서 문서를 닫기 직후 호출됩니다

Element.ReportDesign.beforeRender.toolTip=프리젠테이션 시간 작업 시작 전에 호출됩니다

Element.ReportDesign.afterRender.toolTip=프리젠테이션 시간 작업 시작 후에 호출됩니다

Element.ReportDesign.onPageStart.toolTip=페이지 시작 시 호출됩니다.

Element.ReportDesign.onPageEnd.toolTip=페이지 종료 시 호출됩니다.

Element.ReportDesign.slot.styles=스타일

Element.ReportDesign.slot.parameters=매개 변수

Element.ReportDesign.slot.dataSources=데이터 원본

Element.ReportDesign.slot.dataSets=데이터 집합

Element.ReportDesign.slot.pageSetup=페이지 설정

Element.ReportDesign.slot.components=구성 요소

Element.ReportDesign.slot.body=본문

Element.ReportDesign.slot.scratchPad=스크래치 패드

Element.ReportDesign.slot.templateParameterDefinitions=템플릿 매개 변수 정의

Element.ReportDesign.slot.cubes=큐브 요소

Element.ReportDesign.slot.themes=테마

Element.ReportDesign.initialize=초기화

Element.ReportDesign.initialize.toolTip=보고서 실행 시작 시 호출됩니다.

Element.ReportDesign.initialize.reportContext=보고서 컨텍스트

Element.ReportDesign.cssStyleSheets=CSS 스타일시트

Element.ReportDesign.enableACL=데이터 보안 설정 사용

Element.ReportDesign.ACLExpression=ACL 식

Element.ReportDesign.cascadeACL=ACL 하위 전달

Element.ReportDesign.imageDPI=이미지 DPI

Element.ReportDesign.pageVariables=페이지 변수

Element.ReportDesign.dataObjects= 데이터 개체

Element.ReportDesign.locale=로케일

Element.ReportDesign.onPageStart=페이지 시작 시

Element.ReportDesign.onPageEnd=페이지 종료 시

Element.ReportDesign.dataMarts=DataMarts
Element.ReportDesign.onPrepare=준비 시

Element.ReportDesign.onPrepare.this=보고서 디자인

Element.ReportDesign.onPrepare.toolTip=요소 설정 중 실행합니다. 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.ReportDesign.onPrepare.reportContext=보고서 컨텍스트

Element.ReportDesign.onContentUpdate= 내용 업데이트 시

Element.ReportDesign.onContentUpdate.toolTip=BIRT Viewer에서 보고서 내용이 업데이트될 때 클라이언트 측에서 실행합니다.

Element.ReportDesign.onContentUpdate.this=보고서 디자인

Element.ReportDesign.clientInitialize=클라이언트 초기화

Element.ReportDesign.clientInitialize.toolTip=클라이언트 측 Java 스크립트 라이브러리를 로드할 수 없습니다.

Element.ReportDesign.clientInitialize.this=보고서 디자인

Element.ReportDesign.language=언어

Element.ReportDesign.PDFAccessible=Accessible PDF

#2. Report Element ( Prefix = Element.ReportElement )
Element.ReportElement.displayName=표시 이름

Element.ReportElement.displayNameID=표시 이름 키

Element.ReportElement.comments=설명

Element.ReportElement.propertyMask=속성 마스크

Element.ReportElement.name=이름

Element.ReportElement.extends=확장

Element.ReportElement.style=스타일

Element.ReportElement.eventHandlerClass=이벤트 처리기 클래스

Element.ReportElement.newHandlerOnEachEvent=각 이벤트 시 새 처리기

Element.ReportElement.viewAction=작업 보기

#3. JdbcDataSource  ( prefix  Element.JdbcDataSource )
Element.JdbcDataSource.url=Url

Element.JdbcDataSource.userName=사용자 이름

Element.JdbcDataSource.password=암호

Element.JdbcDataSource.driver=드라이버

Element.JdbcDataSource.dataSource=데이터 원본

#4. DataSet  ( prefix  Element.DataSet )
Element.DataSet.resultSetHints=결과 집합 힌트

Element.DataSet.computedColumns=계산 열

Element.DataSet.filter=필터

Element.DataSet.columnHints=열 힌트

Element.DataSet.cachedMetaData=캐시된 메타데이터

Element.DataSet.rowFetchLimit=데이터 집합에서 인출할 최대 행 수

Element.DataSet.needsCache=데이터 엔진용 캐시가 필요합니다.

Element.DataSet.parameters=데이터 집합 매개 변수

Element.DataSet.sortHints=힌트 정렬

Element.DataSet.ACLExpression=ACL 식

Element.DataSet.RowACLExpression=행 ACL 식

Element.DataSet.isVisible=표시

Element.DataSet.locale=로케일

Element.DataSet.nullsOrdering=널(Null) 순서

#4. SimpleDataSet  ( prefix  Element.SimpleDataSet )
Element.SimpleDataSet.beforeOpen=열기 이전

Element.SimpleDataSet.beforeOpen.toolTip=BIRT가 데이터 집합을 열기 직전 호출됩니다

Element.SimpleDataSet.beforeOpen.this=데이터 집합

Element.SimpleDataSet.beforeOpen.reportContext=보고서 컨텍스트

Element.SimpleDataSet.beforeClose=닫기 이전

Element.SimpleDataSet.beforeClose.this=데이터 집합

Element.SimpleDataSet.beforeClose.toolTip=BIRT가 데이터 집합을 닫기 직전 호출됩니다

Element.SimpleDataSet.beforeClose.reportContext=보고서 컨텍스트

Element.SimpleDataSet.onFetch=인출 시

Element.SimpleDataSet.onFetch.toolTip=BIRT가 데이터 집합에서 데이터 행을 인출하기 직전 호출됩니다

Element.SimpleDataSet.onFetch.reportContext=보고서 컨텍스트

Element.SimpleDataSet.onFetch.this=데이터 집합

Element.SimpleDataSet.onFetch.row=데이터 집합 행

Element.SimpleDataSet.afterOpen=열기 이후

Element.SimpleDataSet.afterOpen.this=데이터 집합

Element.SimpleDataSet.afterOpen.toolTip=BIRT가 데이터 집합을 연 직후 호출됩니다

Element.SimpleDataSet.afterOpen.reportContext=보고서 컨텍스트

Element.SimpleDataSet.afterClose=닫기 이후

Element.SimpleDataSet.afterClose.toolTip=BIRT가 데이터 집합을 닫은 직후 호출됩니다

Element.SimpleDataSet.afterClose.reportContext=보고서 컨텍스트

Element.SimpleDataSet.paramBindings=매개 변수 바인딩

Element.SimpleDataSet.refTemplateParameter=참조 템플릿 매개 변수 정의

Element.SimpleDataSet.cachedRowCount=캐시된 행 수

Element.SimpleDataSet.dataSetRowLimit=데이터 집합 행 제한
  
#5. JdbcSelectDataSet  ( prefix  Element.JdbcSelectDataSet )
Element.JdbcSelectDataSet.statement=문

Element.JdbcSelectDataSet.getStatement=문 가져오기

Element.JdbcSelectDataSet.getStatement.toolTip=쿼리에 대해 사용자 지정된 SQL 문을 반환합니다
  
#6. Parameter  ( prefix  Element.Parameter )
Element.Parameter.helpText=도움말 텍스트

Element.Parameter.helpTextID=도움말 텍스트 키

Element.Parameter.hidden=숨김

Element.Parameter.validate=유효성 검사

Element.Parameter.validate.reportContext=보고서 컨텍스트

Element.Parameter.validate.toolTip=매개 변수의 사용자 지정 유효성 검사에 대해 참 또는 거짓 값을 반환합니다.

Element.Parameter.promptText=프롬프트 텍스트

Element.Parameter.promptTextID=프롬프트 텍스트 키
  
#7. ScalarParameter  ( prefix  Element.ScalarParameter )
Element.ScalarParameter.paramType=스칼라 매개 변수 형식

Element.ScalarParameter.displayPrompt=프롬프트 표시

Element.ScalarParameter.concealValue=값 숨기기

Element.ScalarParameter.format=형식

Element.ScalarParameter.controlType=컨트롤 형식

Element.ScalarParameter.alignment=맞춤

Element.ScalarParameter.selectionList=선택 목록

Element.ScalarParameter.selectionList.mustMatch=일치해야 함

Element.ScalarParameter.selectionList.fixedOrder=고정된 순서

Element.ScalarParameter.boundDataColumns=바인딩된 데이터 열

Element.ScalarParameter.autoSuggestThreshold=자동 제안 임계값

Element.ScalarParameter.getDefaultValueList=기본값 목록 가져오기

Element.ScalarParameter.getDefaultValueList.reportContext=보고서 컨텍스트

Element.ScalarParameter.getDefaultValueList.toolTip=매개 변수의 기본값 목록을 반환합니다.

Element.ScalarParameter.getSelectionValueList=선택값 목록 가져오기

Element.ScalarParameter.getSelectionValueList.reportContext=보고서 컨텍스트

Element.ScalarParameter.getSelectionValueList.toolTip=매개 변수 컨트롤 형식이 "목록" 또는 "콤보"인 경우 선택값을 반환합니다.

Element.ScalarParameter.defaultValue=기본값
  
#8. ParameterGroup  ( prefix  Element.ParameterGroup )
Element.ParameterGroup.startExpanded=시작 확장됨

Element.ParameterGroup.helpText=도움말 텍스트

Element.ParameterGroup.helpTextID=도움말 텍스트 키

Element.ParameterGroup.promptText=프롬프트 텍스트

Element.ParameterGroup.promptTextID=프롬프트 텍스트 키

Element.ParameterGroup.slot.parameters=매개 변수

# CascadingParameterGroup (prefix Element.CascadingParameterGroup)
Element.CascadingParameterGroup.dataSet=데이터 집합

Element.CascadingParameterGroup.dataSetMode=단일 또는 다중 데이터 집합

Element.CascadingParameterGroup.slot.parameters=매개 변수

#9. MasterPage ( Prefix = Element.MasterPage )
Element.MasterPage.type=형식

Element.MasterPage.height=높이

Element.MasterPage.width=너비

Element.MasterPage.orientation=방향

Element.MasterPage.columns=열

Element.MasterPage.columnSpacing=열 간격

Element.MasterPage.margin=여백

Element.MasterPage.topMargin=위쪽 여백

Element.MasterPage.leftMargin=왼쪽 여백

Element.MasterPage.bottomMargin=아래쪽 여백

Element.MasterPage.rightMargin=오른쪽 여백

Element.MasterPage.slot.contents=내용

Element.MasterPage.onPageStart=페이지 시작 시

Element.MasterPage.onPageEnd=페이지 종료 시

Element.MasterPage.onPageStart.toolTip=페이지 시작 시 호출됩니다.

Element.MasterPage.onPageEnd.toolTip=페이지 종료 시 호출됩니다.

Element.MasterPage.onPageStart.this=마스터 페이지

Element.MasterPage.onPageStart.reportContext=보고서 컨텍스트

Element.MasterPage.onPageEnd.this=마스터 페이지

Element.MasterPage.onPageEnd.reportContext=보고서 컨텍스트

#9. Style ( Prefix = Element.Style)
Element.Style.background=배경

Element.Style.background.attachment=배경 첨부

Element.Style.background.color=배경색

Element.Style.background.image=배경 이미지

Element.Style.background.imageType=배경 이미지 형식

Element.Style.background.positionX=가로 위치

Element.Style.background.positionY=세로 위치

Element.Style.background.repeat=배경 반복

Element.Style.background.size.width=배경 크기 너비

Element.Style.background.size.height=배경 크기 높이

Element.Style.border=테두리

Element.Style.border.bottom.color=테두리 아래쪽 색

Element.Style.border.bottom.style=테두리 아래쪽 스타일

Element.Style.border.bottom.width=테두리 아래쪽 너비

Element.Style.border.fillColor=테두리 채우기 색

Element.Style.border.hmiddle.color=테두리 가로 중간 색

Element.Style.border.hmiddle.style=테두리 가로 중간 스타일

Element.Style.border.hmiddle.width=테두리 가로 중간 너비

Element.Style.border.left.color=테두리 왼쪽 색

Element.Style.border.left.style=테두리 왼쪽 스타일

Element.Style.border.left.width=테두리 왼쪽 너비

Element.Style.border.right.color=테두리 오른쪽 색

Element.Style.border.right.style=테두리 오른쪽 스타일

Element.Style.border.right.width=테두리 오른쪽 너비

Element.Style.border.top.color=테두리 위쪽 색

Element.Style.border.top.style=테두리 위쪽 스타일

Element.Style.border.top.width=테두리 위쪽 너비

Element.Style.border.vmiddle.color=테두리 세로 중간 색

Element.Style.border.vmiddle.style=테두리 세로 중간 스타일

Element.Style.border.vmiddle.width=테두리 세로 중간 너비

Element.Style.box=상자

Element.Style.canShrink=축소

Element.Style.display=표시

Element.Style.font=글꼴

Element.Style.color=글꼴 색

Element.Style.font.family=글꼴 집합

Element.Style.font.size=글꼴 크기

Element.Style.font.style=글꼴 스타일

Element.Style.font.textLineThrough=가운데 줄

Element.Style.font.textUnderline=밑줄

Element.Style.font.textOverline=윗줄

Element.Style.font.variant=글꼴 변형

Element.Style.font.weight=글꼴 두께

Element.Style.format=형식

Element.Style.format.dateTime=날짜 시간 형식

Element.Style.format.date=날짜 형식

Element.Style.format.time=시간 형식

Element.Style.format.number=숫자 형식

Element.Style.format.number.align=숫자 맞춤

Element.Style.format.string=문자열 형식

Element.Style.highlight.testExpr=테스트 식 강조

Element.Style.highlight.rules=규칙 강조

Element.Style.letterSpacing=문자 간격

Element.Style.lineHeight=줄 높이

Element.Style.map.rules=맵 규칙

Element.Style.margin.top=여백 위쪽

Element.Style.margin.bottom=여백 아래쪽

Element.Style.margin.left=여백 왼쪽

Element.Style.margin.right=여백 오른쪽

Element.Style.masterPage=마스터 페이지

Element.Style.padding=안쪽 여백

Element.Style.padding.bottom=안쪽 여백 아래쪽

Element.Style.padding.left=안쪽 여백 왼쪽

Element.Style.padding.right=안쪽 여백 오른쪽

Element.Style.padding.top=안쪽 여백 위쪽

Element.Style.pageBreakBefore=앞에 페이지 나누기

Element.Style.pageBreakAfter=뒤에 페이지 나누기

Element.Style.pageBreakInside=사이에 페이지 나누기

Element.Style.section=섹션

Element.Style.showIfBlank=비어있는 경우 표시

Element.Style.text=텍스트

Element.Style.text.align=텍스트 맞춤

Element.Style.text.direction=텍스트 방향

Element.Style.text.indent=텍스트 들여쓰기

Element.Style.text.transform=텍스트 변환

Element.Style.verticalAlign=세로 맞춤

Element.Style.whiteSpace=공백

Element.Style.widows=창

Element.Style.orphans=고아

Element.Style.wordSpacing=단어 간격

Element.Style.overflow=오버플로

Element.Style.height=높이

Element.Style.width=너비

#10.ReportItem  ( prefix  Element.ReportItem )
Element.ReportItem.bookmark=책갈피

Element.ReportItem.bookmarkDisplayName=책갈피 표시 이름

Element.ReportItem.toc=목차

Element.ReportItem.dataSet=데이터 집합

Element.ReportItem.cube=데이터 큐브

Element.ReportItem.x=X
Element.ReportItem.y=Y
Element.ReportItem.height=높이

Element.ReportItem.width=너비

Element.ReportItem.visibility=표시 유형

Element.ReportItem.paramBindings=매개 변수 바인딩

Element.ReportItem.refTemplateParameter=참조 템플릿 매개 변수 정의

Element.ReportItem.boundDataColumns=바인딩된 데이터 열

Element.ReportItem.zIndex=Z 인덱스

Element.ReportItem.dataBindingRef=데이터 바인딩 참조

Element.ReportItem.multiViews=다중 보기

Element.ReportItem.ACLExpression=ACL 식

Element.ReportItem.cascadeACL=ACL 하위 전달

Element.ReportItem.allowExport=내보내기 허용

Element.ReportItem.pushDown=아래로 밀어내기

Element.ReportItem.theme=테마

Element.ReportItem.language=언어

Element.ReportItem.order=순서

Element.ReportItem.altText=대체 텍스트

Element.ReportItem.altTextID=대체 텍스트 키

Element.ReportItem.linkedDataModel=링크된 데이터 모델

#11.Label  ( prefix  Element.Label )
Element.Label.text=내용

Element.Label.textID=내용 키

Element.Label.helpTextID=도움말 텍스트 키

Element.Label.helpText=도움말 텍스트

Element.Label.action=작업

Element.Label.onPrepare=준비 중

Element.Label.onPrepare.this=레이블

Element.Label.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Label.onPrepare.reportContext=보고서 컨텍스트

Element.Label.onCreate=생성 시

Element.Label.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Label.onCreate.this=레이블 인스턴스

Element.Label.onCreate.reportContext=보고서 컨텍스트

Element.Label.onRender=렌더링 시

Element.Label.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Label.onRender.this=레이블 인스턴스

Element.Label.onRender.reportContext=보고서 컨텍스트

Element.Label.onPageBreak=페이지 나누기

Element.Label.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Label.onPageBreak.this=레이블 인스턴스

Element.Label.onPageBreak.reportContext=보고서 컨텍스트

Element.Label.tagType=PDF 태그 형식

Element.Label.altText=대체 텍스트
  
#12.Element.FreeForm  ( Prefix Element.FreeForm )
Element.FreeForm.slot.reportItems=보고서 항목
  
#12.Container  ( prefix  Element.Container )
Element.Container.slot.reportItems=보고서 항목
  
#13.Data  ( prefix  Element.Data )
Element.Data.resultSetColumn=결과 집합 열

Element.Data.helpText=도움말 텍스트

Element.Data.helpTextID=도움말 텍스트 키

Element.Data.action=작업

Element.Data.onPrepare=준비 중

Element.Data.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Data.onPrepare.this=데이터

Element.Data.onPrepare.reportContext=보고서 컨텍스트

Element.Data.onCreate=생성 시

Element.Data.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Data.onCreate.this=데이터 인스턴스

Element.Data.onCreate.reportContext=보고서 컨텍스트

Element.Data.onRender=렌더링 시

Element.Data.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Data.onRender.this=데이터 인스턴스

Element.Data.onRender.reportContext=보고서 컨텍스트

Element.Data.onPageBreak=페이지 나누기

Element.Data.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Data.onPageBreak.this=데이터 인스턴스

Element.Data.onPageBreak.reportContext=보고서 컨텍스트

Element.Data.tagType=PDF 태그 형식

Element.Data.altText=대체 텍스트
  
#14.Text  ( prefix  Element.Text )
Element.Text.content=내용

Element.Text.contentType=내용 형식

Element.Text.contentID=내용 키

Element.Text.onPrepare=준비 중

Element.Text.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Text.onPrepare.this=텍스트

Element.Text.onPrepare.reportContext=보고서 컨텍스트

Element.Text.onCreate=생성 시

Element.Text.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Text.onCreate.this=텍스트 인스턴스

Element.Text.onCreate.reportContext=보고서 컨텍스트

Element.Text.onRender=렌더링 시

Element.Text.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Text.onRender.this=텍스트 인스턴스

Element.Text.onRender.reportContext=보고서 컨텍스트

Element.Text.onPageBreak=페이지 나누기

Element.Text.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Text.onPageBreak.this=텍스트 인스턴스

Element.Text.onPageBreak.reportContext=보고서 컨텍스트

Element.Text.hasExpression=식 값

Element.Text.tagType=PDF 태그 형식

Element.Text.altText=대체 텍스트
  
#15.ListingGroup  ( prefix  Element.ListingGroup )
Element.ListingGroup.keyExpr=키 식

Element.ListingGroup.sort=정렬

Element.ListingGroup.bookmark=책갈피

Element.ListingGroup.bookmarkDisplayName=책갈피 표시 이름

Element.ListingGroup.toc=목차

Element.ListingGroup.hideDetail=상세 정보 숨기기

Element.ListingGroup.groupName=이름

Element.ListingGroup.Interval=간격

Element.ListingGroup.intervalBase=간격 기준

Element.ListingGroup.interval=간격

Element.ListingGroup.intervalRange=간격 범위

Element.ListingGroup.sortDirection=정렬 방향

Element.ListingGroup.eventHandlerClass=이벤트 처리기 클래스

Element.ListingGroup.newHandlerOnEachEvent=각 이벤트 시 새 처리기

Element.ListingGroup.pageBreakBefore=앞에 페이지 나누기

Element.ListingGroup.pageBreakAfter=뒤에 페이지 나누기

Element.ListingGroup.pageBreakInside=사이에 페이지 나누기

Element.ListingGroup.filter=필터

Element.ListingGroup.repeatHeader=머리글 반복

Element.ListingGroup.onStart=시작 시

Element.ListingGroup.onStart.toolTip=데이터 집합이 열렸지만 머리글 밴드가 생성되기 이전이며, 첫 번째 행이 이 요소에 대한 데이터 집합에서 검색되기 전에 호출됩니다

Element.ListingGroup.onRow=행에서

Element.ListingGroup.onRow.toolTip=이 요소에 대한 데이터 집합에서 검색된 각 행에 대해 해당 행에 대한 내용을 생성하기 전에 호출됩니다

Element.ListingGroup.onFinish=종료 시

Element.ListingGroup.onFinish.toolTip=이 요소에 대한 데이터 집합에서 마지막 행을 읽은 이후이며, 바닥글 밴드가 생성되기 이전에 호출됩니다

Element.ListingGroup.sortType=정렬화 형식

Element.ListingGroup.boundDataColumns=바인딩된 데이터 열

Element.ListingGroup.viewAction=작업 보기

Element.ListingGroup.onCreate=생성 중

Element.ListingGroup.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.ListingGroup.onCreate.this=열거 그룹

Element.ListingGroup.onCreate.reportContext=보고서 컨텍스트

Element.ListingGroup.onRender=렌더링 중

Element.ListingGroup.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.ListingGroup.onRender.this=열거 그룹

Element.ListingGroup.onRender.reportContext=보고서 컨텍스트

Element.ListingGroup.ACLExpression=ACL 식

Element.ListingGroup.cascadeACL=ACL 하위 전달

Element.ListingGroup.showDetailFilter=필터 상세 정보 표시

#16.List  ( prefix  Element.List )
Element.List.slot.header=머리글

Element.List.slot.groups=그룹

Element.List.slot.detail=상세 정보

Element.List.slot.footer=바닥글

Element.List.onPrepare=준비 중

Element.List.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.List.onPrepare.this=목록

Element.List.onPrepare.reportContext=보고서 컨텍스트

Element.List.onCreate=생성 시

Element.List.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.List.onCreate.this=목록 인스턴스

Element.List.onCreate.reportContext=보고서 컨텍스트

Element.List.onRender=렌더링 시

Element.List.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.List.onRender.this=목록 인스턴스

Element.List.onRender.reportContext=보고서 컨텍스트

Element.List.onPageBreak=페이지 나누기

Element.List.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.List.onPageBreak.this=목록 인스턴스

Element.List.onPageBreak.reportContext=보고서 컨텍스트

Element.List.tagType=PDF 태그 형식

Element.List.altText=대체 텍스트
  
#17.ListGroup  ( prefix  Element.ListGroup )
Element.ListGroup.slot.header=머리글

Element.ListGroup.slot.footer=바닥글

Element.ListGroup.onPrepare=준비 중

Element.ListGroup.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.ListGroup.onPrepare.this=목록 그룹

Element.ListGroup.onPrepare.reportContext=보고서 컨텍스트

Element.ListGroup.onPageBreak=페이지 나누기

Element.ListGroup.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.ListGroup.onPageBreak.this=목록 그룹

Element.ListGroup.onPageBreak.reportContext=보고서 컨텍스트
  
#18.Table  ( prefix  Element.Table )
Element.Table.caption=캡션

Element.Table.summary=요약

Element.Table.isSummaryTable=요약 테이블

Element.Table.captionID=캡션 키

Element.Table.slot.header=머리글

Element.Table.slot.groups=그룹

Element.Table.slot.detail=상세 정보

Element.Table.slot.footer=바닥글

Element.Table.slot.columns=열

Element.Table.onPrepare=준비 중

Element.Table.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Table.onPrepare.this=테이블

Element.Table.onPrepare.reportContext=보고서 컨텍스트

Element.Table.onPrepare.object=객체

Element.Table.onCreate=생성 시

Element.Table.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Table.onCreate.this=테이블 인스턴스

Element.Table.onCreate.reportContext=보고서 컨텍스트

Element.Table.onCreate.object=객체

Element.Table.onRender=렌더링 시

Element.Table.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Table.onRender.this=테이블 인스턴스

Element.Table.onRender.reportContext=보고서 컨텍스트

Element.Table.onRender.object=객체

Element.Table.onPageBreak=페이지 나누기

Element.Table.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Table.onPageBreak.this=테이블 인스턴스

Element.Table.onPageBreak.reportContext=보고서 컨텍스트

Element.Table.tagType=PDF 태그 형식
  
#19.TableGroup  ( prefix  Element.TableGroup )
Element.TableGroup.slot.header=머리글

Element.TableGroup.slot.footer=바닥글

Element.TableGroup.onPrepare=준비 중

Element.TableGroup.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.TableGroup.onPrepare.this=테이블 그룹

Element.TableGroup.onPrepare.reportContext=보고서 컨텍스트

Element.TableGroup.onPageBreak=페이지 나누기

Element.TableGroup.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.TableGroup.onPageBreak.this=테이블 그룹

Element.TableGroup.onPageBreak.reportContext=보고서 컨텍스트
  
#20.Column  ( prefix  Element.Column )
Element.Column.repeat=반복

Element.Column.width=너비

Element.Column.alignment=맞춤

Element.Column.suppressDuplicates=중복 항목 숨기기

Element.Column.visibility=표시 유형

Element.Column.viewAction=작업 보기
  
#21.Row  ( prefix  Element.Row )
Element.Row.visibility=표시 유형

Element.Row.height=높이

Element.Row.bookmark=책갈피

Element.Row.bookmarkDisplayName=책갈피 표시 이름

Element.Row.eventHandlerClass=이벤트 처리기 클래스

Element.Row.newHandlerOnEachEvent=각 이벤트 시 새 처리기

Element.Row.slot.cells=셀

Element.Row.onPrepare=준비 중

Element.Row.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Row.onPrepare.this=행

Element.Row.onPrepare.reportContext=보고서 컨텍스트

Element.Row.onCreate=생성 중

Element.Row.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Row.onCreate.this=행 인스턴스

Element.Row.onCreate.reportContext=보고서 컨텍스트

Element.Row.onRender=렌더링 중

Element.Row.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Row.onRender.this=행 인스턴스

Element.Row.onRender.reportContext=보고서 컨텍스트

Element.Row.suppressDuplicates=중복 항목 숨기기

Element.Row.viewAction=작업 보기

Element.Row.repeatable=반복 가능

Element.Row.tagType=PDF 태그 형식

Element.Row.language=언어
  
#22.Cell  ( prefix  Element.Cell )
Element.Cell.column=열

Element.Cell.colSpan=열 범위

Element.Cell.rowSpan=행 범위

Element.Cell.verticalAlign=세로 맞춤

Element.Cell.drop=삭제

Element.Cell.height=높이

Element.Cell.slot.content=내용

Element.Cell.width=너비

Element.Cell.eventHandlerClass=이벤트 처리기 클래스

Element.Cell.newHandlerOnEachEvent=각 이벤트 시 새 처리기

Element.Cell.scope=범위

Element.Cell.bookmark=책갈피

Element.Cell.bookmarkDisplayName=책갈피 표시 이름

Element.Cell.headers=머리글

Element.Cell.onPrepare=준비 중

Element.Cell.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Cell.onPrepare.this=셀

Element.Cell.onPrepare.reportContext=보고서 컨텍스트

Element.Cell.onCreate=생성 중

Element.Cell.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Cell.onCreate.this=셀 인스턴스

Element.Cell.onCreate.reportContext=보고서 컨텍스트

Element.Cell.onRender=렌더링 중

Element.Cell.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Cell.onRender.this=셀 인스턴스

Element.Cell.onRender.reportContext=보고서 컨텍스트

Element.Cell.viewAction=작업 보기

Element.Cell.diagonal=대각선

Element.Cell.diagonalNumber=대각선 수

Element.Cell.antidiagonalNumber=반대각선 수

Element.Cell.diagonalThickness=대각선 두께

Element.Cell.diagonalColor=대각선 색

Element.Cell.antidiagonalThickness=반대각선 두께

Element.Cell.diagonalStyle=대각선 스타일

Element.Cell.antidiagonalStyle=반대각선 스타일

Element.Cell.antidiagonalColor=주 대각선 색

Element.Cell.tagType=PDF 태그 형식

Element.Cell.language=언어

Element.Cell.altText=대체 텍스트
  
#23.Image  ( prefix  Element.Image )
Element.Image.altText=대체 텍스트

Element.Image.altTextID=대체 텍스트 키

Element.Image.helpText=도움말 텍스트

Element.Image.helpTextID=도움말 텍스트 키

Element.Image.size=크기

Element.Image.scale=배율

Element.Image.source=원본

Element.Image.uri=URI
Element.Image.imageName=이미지 이름

Element.Image.valueExpr=값 식

Element.Image.typeExpr=식 입력

Element.Image.action=작업

Element.Image.onPrepare=준비 중

Element.Image.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Image.onPrepare.this=이미지

Element.Image.onPrepare.reportContext=보고서 컨텍스트

Element.Image.onCreate=생성 시

Element.Image.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Image.onCreate.this=이미지 인스턴스

Element.Image.onCreate.dataRow=데이터 행

Element.Image.onCreate.reportContext=보고서 컨텍스트

Element.Image.onRender=렌더링 시

Element.Image.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Image.onRender.this=이미지 인스턴스

Element.Image.onRender.reportContext=보고서 컨텍스트

Element.Image.onPageBreak=페이지 나누기

Element.Image.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Image.onPageBreak.this=이미지 인스턴스

Element.Image.onPageBreak.reportContext=보고서 컨텍스트

Element.Image.fitToContainer=컨테이너에 맞추기

Element.Image.proportionalScale=비례 배율

Element.Image.tagType=PDF 태그 형식
  
#24.Grid  ( prefix  Element.Grid )
Element.Grid.slot.columns=열

Element.Grid.slot.rows=행

Element.Grid.onPrepare=준비 중

Element.Grid.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.Grid.onPrepare.this=눈금

Element.Grid.onPrepare.reportContext=보고서 컨텍스트

Element.Grid.onCreate=생성 시

Element.Grid.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.Grid.onCreate.this=눈금 인스턴스

Element.Grid.onCreate.dataRow=데이터 행

Element.Grid.onCreate.reportContext=보고서 컨텍스트

Element.Grid.onRender=렌더링 시

Element.Grid.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.Grid.onRender.this=눈금 인스턴스

Element.Grid.onRender.reportContext=보고서 컨텍스트

Element.Grid.onPageBreak=페이지 나누기

Element.Grid.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.Grid.onPageBreak.this=눈금 인스턴스

Element.Grid.onPageBreak.reportContext=보고서 컨텍스트

Element.Grid.caption=캡션

Element.Grid.captionID=캡션 키

Element.Grid.summary=요약

Element.Grid.tagType=PDF 태그 형식
  
#25.Line  ( prefix  Element.Line )
Element.Line.orientation=방향
  
#26.TextData  ( prefix  Element.TextData )
Element.TextData.valueExpr=값 식

Element.TextData.contentType=내용 형식

Element.TextData.onPrepare=준비 중

Element.TextData.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.TextData.onPrepare.this=동적 텍스트

Element.TextData.onPrepare.reportContext=보고서 컨텍스트

Element.TextData.onPrepare.object=객체

Element.TextData.onCreate=생성 시

Element.TextData.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.TextData.onCreate.this=동적 텍스트 인스턴스

Element.TextData.onCreate.dataRow=데이터 행

Element.TextData.onCreate.reportContext=보고서 컨텍스트

Element.TextData.onRender=렌더링 시

Element.TextData.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.TextData.onRender.this=동적 텍스트 인스턴스

Element.TextData.onRender.reportContext=보고서 컨텍스트

Element.TextData.onPageBreak=페이지 나누기

Element.TextData.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.TextData.onPageBreak.this=동적 텍스트 인스턴스

Element.TextData.onPageBreak.reportContext=보고서 컨텍스트

Element.TextData.hasExpression=식 값

Element.TextData.tagType=PDF 태그 형식

Element.TextData.altText=대체 텍스트

#27.ExtendedItem   ( prefix  Element.ExtendedItem )
Element.ExtendedItem.altText=대체 텍스트

Element.ExtendedItem.altTextID=대체 텍스트 키:

Element.ExtendedItem.extensionName=확장 이름

Element.ExtendedItem.filter=필터

Element.ExtendedItem.onPrepare=준비 중

Element.ExtendedItem.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.ExtendedItem.onPrepare.this=확장 항목

Element.ExtendedItem.onPrepare.reportContext=보고서 컨텍스트

Element.ExtendedItem.onCreate=생성 시

Element.ExtendedItem.onCreate.toolTip=공장에서 요소 생성 시 실행됩니다

Element.ExtendedItem.onCreate.this=확장 항목 인스턴스

Element.ExtendedItem.onCreate.reportContext=보고서 컨텍스트

Element.ExtendedItem.onRender=렌더링 시

Element.ExtendedItem.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 실행됩니다.

Element.ExtendedItem.onRender.this=확장 항목 인스턴스

Element.ExtendedItem.onRender.reportContext=보고서 컨텍스트

Element.ExtendedItem.onPageBreak=페이지 나누기

Element.ExtendedItem.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.ExtendedItem.onPageBreak.this=확장 항목 인스턴스

Element.ExtendedItem.onPageBreak.reportContext=보고서 컨텍스트

Element.ExtendedItem.extensionVersion=확장 버전

#28.DataSource ( prefix Element.DataSource )
Element.DataSource.beforeOpen=열기 이전

Element.DataSource.beforeOpen.toolTip=이 메서드는 BIRT가 데이터 원본을 열기 직전 호출됩니다

Element.DataSource.beforeOpen.this=데이터 원본

Element.DataSource.beforeOpen.reportContext=보고서 컨텍스트

Element.DataSource.beforeClose=닫기 이전

Element.DataSource.beforeClose.toolTip=이 메서드는 BIRT가 데이터 원본을 닫기 직전 호출됩니다

Element.DataSource.beforeClose.reportContext=보고서 컨텍스트

Element.DataSource.beforeClose.this=데이터 원본

Element.DataSource.afterOpen=열기 이후

Element.DataSource.afterOpen.toolTip=이 메서드는 BIRT가 데이터 원본을 연 직후 호출됩니다

Element.DataSource.afterOpen.reportContext=보고서 컨텍스트

Element.DataSource.afterOpen.this=데이터 원본

Element.DataSource.afterClose=닫기 이후

Element.DataSource.afterClose.toolTip=이 메서드는 BIRT가 데이터 원본을 닫은 직후 호출됩니다

Element.DataSource.afterClose.reportContext=보고서 컨텍스트

#29.ScriptDataSource ( prefix Element.ScriptDataSource )
Element.ScriptDataSource.open=열기

Element.ScriptDataSource.open.toolTip=데이터 원본으로 연결합니다

Element.ScriptDataSource.open.this=스크립트 데이터 원본

Element.ScriptDataSource.close=닫기

Element.ScriptDataSource.close.toolTip=데이터 원본에 대한 연결을 삭제합니다

Element.ScriptDataSource.close.this=스크립트 데이터 원본

#31 ScriptDataSet ( prefix Element.ScriptDataSet )
Element.ScriptDataSet.dataSource=데이터 원본

Element.ScriptDataSet.open=열기

Element.ScriptDataSet.open.toolTip=데이터 집합을 엽니다

Element.ScriptDataSet.open.this=스크립트 데이터 집합

Element.ScriptDataSet.describe=설명

Element.ScriptDataSet.describe.toolTip=결과 집합을 설명합니다

Element.ScriptDataSet.describe.reportContext=보고서 컨텍스트

Element.ScriptDataSet.describe.this=스크립트 데이터 집합

Element.ScriptDataSet.describe.dataSetMetaData=데이터 집합 메타데이터

Element.ScriptDataSet.fetch=인출

Element.ScriptDataSet.fetch.currentRow=현재 행

Element.ScriptDataSet.fetch.toolTip=형식 DataRow의 객체를 생성, 등록 및 반환합니다

Element.ScriptDataSet.fetch.reportContext=보고서 컨텍스트

Element.ScriptDataSet.fetch.this=스크립트 데이터 집합

Element.ScriptDataSet.close=닫기

Element.ScriptDataSet.close.toolTip=데이터 집합을 닫습니다

Element.ScriptDataSet.close.this=스크립트 데이터 집합

Element.ScriptDataSet.resultSetHints=결과 집합 힌트

#32 Listing ( prefix Element.Lising )
Element.Listing.sorting=정렬

Element.Listing.filter=필터

Element.Listing.repeatHeader=머리글 반복

Element.Listing.pageBreakInterval=페이지 나누기 간격

Element.Listing.sortByGroups=그룹별 정렬

Element.Listing.onStart=시작 시

Element.Listing.onStart.toolTip=데이터 집합이 열렸지만 머리글 밴드가 생성되기 이전이며, 첫 번째 행이 이 요소에 대한 데이터 집합에서 검색되기 전에 호출됩니다

Element.Listing.onRow=행에서

Element.Listing.onRow.toolTip=이 요소에 대한 데이터 집합에서 검색된 각 행에 대해 해당 행에 대한 내용을 생성하기 전에 호출됩니다

Element.Listing.onFinish=종료 시

Element.Listing.onFinish.toolTip=이 요소에 대한 데이터 집합에서 마지막 행을 읽은 이후이며 바닥글 밴드가 생성되기 이전에 호출됩니다

#33 GraphicMasterPage ( Prefix Element.GraphicMasterPage)
Element.GraphicMasterPage.slot.contents=내용

#34 SimpleMasterPage ( Prefix Element.SimpleMasterPage)
Element.SimpleMasterPage.showHeaderOnFirst=첫 페이지에 머리글 표시

Element.SimpleMasterPage.showFooterOnLast=마지막 페이지에 머리글 표시

Element.SimpleMasterPage.headerHeight=머리글 높이

Element.SimpleMasterPage.footerHeight=바닥글 높이

Element.SimpleMasterPage.floatingFooter=부동 바닥글

Element.SimpleMasterPage.slot.pageHeader=페이지 머리글

Element.SimpleMasterPage.slot.pageFooter=페이지 바닥글

#35 OdaDataSource ( Prefix Element.OdaDataSource )
Element.OdaDataSource.driverName=드라이버 이름

Element.OdaDataSource.extensionID=확장 ID

Element.OdaDataSource.publicDriverProperties=공용 드라이버 속성

Element.OdaDataSource.privateDriverProperties=개인 드라이버 속성

Element.OdaDataSource.designerState=디자이너 상태

#36 OdaDataSet ( Prefix Element.OdaDataSet )
Element.OdaDataSet.extensionID=확장 ID

Element.OdaDataSet.resultSet=결과 집합 열

Element.OdaDataSet.queryText=쿼리

Element.OdaDataSet.type=형식

Element.OdaDataSet.resultSetName=결과 집합 이름

Element.OdaDataSet.publicDriverProperties=공용 드라이버 속성

Element.OdaDataSet.privateDriverProperties=개인 드라이버 속성

Element.OdaDataSet.designerState=디자이너 상태

Element.OdaDataSet.designerValues=디자이너 값

Element.OdaDataSet.resultSetNumber=결과 집합 수

Element.OdaDataSet.dataSource=데이터 원본

#37 DesignElement ( Prefix Element.DesignElement )
Element.DesignElement.customXml=사용자 지정 XML

Element.DesignElement.propertyMasks=속성 마스크

Element.DesignElement.userProperties=사용자 속성

#38 Theme ( Prefix Element.Theme )
Element.Theme.slot.styles=스타일

#39 TemplateParameterDefinition ( Prefix Element.TemplateParameterDefinition )
Element.TemplateParameterDefinition.name=이름

Element.TemplateParameterDefinition.allowedType=허용된 형식

Element.TemplateParameterDefinition.description=설명

Element.TemplateParameterDefinition.descriptionID=설명 ID

Element.TemplateParameterDefinition.slot.default=기본값

#40 TemplateElement ( Prefix Element.TemplateElement )
Element.TemplateElement.name=이름

Element.TemplateElement.refTemplateParameter=참조 템플릿 매개 변수

Element.TemplateElement.displayName=표시 이름

Element.TemplateElement.displayNameID=표시 이름 ID

#41 JointDataset ( Prefix Element.JointDataset )
Element.JointDataSet.resultSet=결과 집합 열

Element.JointDataSet.dataSets=데이터 집합

Element.JointDataSet.joinConditions=조인 조건

#42 Rectangle  ( prefix  Element.Rectangle )

#43. TemplateReportItem
Element.TemplateReportItem.visibility=표시 유형

#44.AutoText ( prefix Element.AutoText )
Element.AutoText.type = AutoText 형식

Element.AutoText.onPrepare=준비 중

Element.AutoText.onPrepare.this=AutoText
Element.AutoText.onPrepare.toolTip=요소 설정 중 실행 여기에서 요소 디자인을 변경합니다. 아직 데이터 바인딩을 실행할 수 없습니다.

Element.AutoText.onPrepare.reportContext=보고서 컨텍스트

Element.AutoText.onCreate=생성 중

Element.AutoText.onCreate.toolTip=공장에서 요소가 생성될 때 스크립트가 실행됩니다.

Element.AutoText.onCreate.this=AutoText 인스턴스

Element.AutoText.onCreate.reportContext=보고서 컨텍스트

Element.AutoText.onRender=렌더링 중

Element.AutoText.onRender.toolTip=프리젠테이션 엔진에서 요소가 렌더링 준비되었을 때 스크립트가 실행됩니다.

Element.AutoText.onRender.this=AutoText 인스턴스

Element.AutoText.onRender.reportContext=보고서 컨텍스트

Element.AutoText.onPageBreak=페이지 나누기

Element.AutoText.onPageBreak.toolTip=페이지가 나누어질 때 해당 페이지에 있는 모든 보고서 항목에 대해 실행합니다.

Element.AutoText.onPageBreak.this=AutoText 인스턴스

Element.AutoText.onPageBreak.reportContext=보고서 컨텍스트

Element.AutoText.pageVariable=페이지 변수

#45. Cube ( prefix Element.Cube )
Element.Cube.filter=필터 조건

Element.Cube.defaultMeasureGroup=기본 측정값 그룹

Element.Cube.ACLExpression=ACL 식

#46. Dimension ( prefix Element.Dimension )
Element.Dimension.isTimeType=시간 유형 조건

Element.Dimension.defaultHierarchy=기본 계층 구조

Element.Dimension.ACLExpression=ACL 식

#47. Hierarchy ( prefix Element.Hierarchy )
Element.Hierarchy.filter=필터 조건

#48. Level ( prefix Element.Level )
Element.Level.dataType=데이터 형식

Element.Level.dateTimeLevelType=날짜 시간 수준 형식

Element.Level.dateTimeFormat=날짜 시간 형식

Element.Level.Interval=간격

Element.Level.intervalBase=간격 기준

Element.Level.interval=간격

Element.Level.intervalRange=간격 범위

Element.Level.levelType=수준 형식

Element.Level.staticValues=정적 값

Element.Level.defaultValue=기본값

Element.Level.ACLExpression=ACL 식

Element.Level.MemberACLExpression=구성원 ACL 식

Element.Level.action=작업

Element.Level.format=형식

Element.Level.alignment=맞춤

#49. Measure ( prefix Element.Measure )
Element.Measure.function=함수

Element.Measure.isCalculated=계산 조건

Element.Measure.measureExpression=측정값 식

Element.Measure.dataType=데이터 형식

Element.Measure.ACLExpression=ACL 식

Element.Measure.action=작업

Element.Measure.format=형식

Element.Measure.alignment=맞춤

Element.Measure.isVisible=표시

#50. MeasureGroup ( prefix Element.MeasureGroup )
Element.MeasureGroup.measures=측정값

#51. TabularCube ( prefix Element.TabularCube )
Element.TabularCube.dataSet=데이터 집합

Element.TabularCube.dimensions=차원

Element.TabularCube.measureGroups=측정값 그룹

Element.TabularCube.dimensionConditions=차원 조건

Element.TabularCube.autoKey=자동 기본 키

#52. TabularDimension ( prefix Element.TabularDimension )
Element.TabularDimension.hierarchies=계층

Element.TabularDimension.internalDimensionRef=내부 차원 참조

#53. TabularHierarchy ( prefix Element.TabularHierarchy )
Element.TabularHierarchy.dataSet=데이터 집합

Element.TabularHierarchy.levels=수준

Element.TabularHierarchy.primaryKeys=기본 키

#54. TabularLevel ( prefix Element.TabularLevel )
Element.TabularLevel.columnName=열 이름

Element.TabularLevel.displayColumnName=열 이름 표시

Element.TabularLevel.attributes=특성

#55. OdaCube ( prefix Element.OdaCube )
Element.OdaCube.dimensions=차원

Element.OdaCube.measureGroups=측정값 그룹

Element.OdaCube.nativeName=고유 이름

#56. OdaDimension ( prefix Element.OdaDimension )
Element.OdaDimension.hierarchies=계층

Element.OdaDimension.nativeName=고유 이름

#57. OdaHierarchy ( prefix Element.OdaHierarchy )
Element.OdaHierarchy.levels=수준

Element.OdaHierarchy.nativeName=고유 이름

#58. OdaLevel ( prefix Element.OdaLevel )
Element.OdaLevel.attributes=특성

#59. MemberValue ( prefix Element.MemberValue )
Element.MemberValue.value=값

Element.MemberValue.level=수준

Element.MemberValue.memberValues=구성원 값

Element.MemberValue.filter=필터

#60. SortElement ( prefix Element.SortElement )
Element.SortElement.key=키

Element.SortElement.direction=방향

Element.SortElement.member=구성원

Element.SortElement.strength=수준 정렬

Element.SortElement.locale=로케일 정렬

#61. FilterConditionElement ( prefix Element.FilterConditionElement )
Element.FilterConditionElement.operator=연산자

Element.FilterConditionElement.expr=식

Element.FilterConditionElement.value1=Value1

Element.FilterConditionElement.value2=Value2

Element.FilterConditionElement.filterTarget=대상 필터

Element.FilterConditionElement.member=구성원

Element.FilterConditionElement.isOptional=옵션 여부

Element.FilterConditionElement.extensionName=확장 이름

Element.FilterConditionElement.extensionExprId=확장 식 ID

Element.FilterConditionElement.pushDown=아래로 밀어내기

Element.FilterConditionElement.dynamicFilterParameter=동적 필터 매개 변수

Element.FilterConditionElement.type=형식

Element.FilterConditionElement.updateAggregation=집계 업데이트


#62. AbstractMultiViews ( prefix Element.AbstractMultiViews )
Element.AbstractMultiViews.index=인덱스

#63. MultiViews ( prefix Element.MultiViews )
Element.MultiViews.views=보기

#64. VariableElement ( prefix Element.VariableElement )
Element.VariableElement.name=이름

Element.VariableElement.value=값

Element.VariableElement.type=형식

#65. DataGroup  ( prefix  Element.DataGroup )
Element.DataGroup.groupName=이름

Element.DataGroup.keyExpr=키 식

Element.DataGroup.sort=정렬

Element.DataGroup.filter=필터

Element.DataGroup.Interval=간격

Element.DataGroup.interval=간격

Element.DataGroup.intervalBase=간격 기준

Element.DataGroup.intervalRange=간격 범위

Element.DataGroup.sortDirection=정렬 방향

Element.DataGroup.sortType=정렬 형식

#66. DerivedDataSet ( prefix Element.DerivedDataSet )
Element.DerivedDataSet.inputDataSets=입력 데이터 집합

Element.DerivedDataSet.queryText=쿼리 텍스트

Element.DerivedDataSet.extensionID=확장 ID

#67. AbstractScalarParameter  ( prefix  AbstractScalarParameter )
Element.AbstractScalarParameter.isRequired=필요

Element.AbstractScalarParameter.dynamicList=동적 목록

Element.AbstractScalarParameter.dynamicList.dataSetName=데이터 집합 이름

Element.AbstractScalarParameter.dynamicList.linkedDataModelName=연결된 데이터 모델 이름

Element.AbstractScalarParameter.dynamicList.valueExpr=값 식

Element.AbstractScalarParameter.dynamicList.labelExpr=레이블 식

Element.AbstractScalarParameter.listLimit=목록 제한

Element.AbstractScalarParameter.sortDirection=정렬 방향

Element.AbstractScalarParameter.sortBy=정렬 기준

Element.AbstractScalarParameter.valueType=값 형식

Element.AbstractScalarParameter.sortByColumn=열을 기준으로 정렬

Element.AbstractScalarParameter.selectionList=선택 목록

Element.AbstractScalarParameter.dataType=데이터 형식

Element.AbstractScalarParameter.distinct=고유

#68. DynamicFilterParameter  ( prefix  Element.DynamicFilterParameter )
Element.DynamicFilterParameter.displayType=표시 형식

Element.DynamicFilterParameter.filterOperator=필터 연산자

Element.DynamicFilterParameter.column=열

Element.DynamicFilterParameter.defaultValue=기본값

Element.DynamicFilterParameter.nativeDataType=고유 데이터 형식

Element.DynamicFilterParameter.controlType=컨트롤 형식

#78 DataMart ( prefix  Element.DataMart )
Element.DataMart.slot.dataSources=데이터 원본

Element.DataMart.slot.dataSets=데이터 집합

Element.DataMart.slot.cubes=큐브

Element.DataMart.slot.parameters=매개 변수

Element.DataMart.slot.dimensions=공유 차원

Element.DataMart.enableACL=데이터 보안 설정 사용

Element.DataMart.ACLExpression=ACL 식

Element.DataMart.enableIncrementalUpdate=증분 업데이트 사용

#79 DataMartDataSource ( prefix Element.DataMartDataSource )
Element.DataMartDataSource.datamartURL =Data Mart URL

Element.DataMartDataSource.datamartVersion=Data Mart 버전

Element.DataMartDataSource.paramBindings=매개 변수 바인딩

Element.DataMartDataSource.accessType=액세스 유형

#80 DataMartDataSet ( prefix Element.DataMartDataSet )
Element.DataMartDataSet.dataSource=데이터 원본

Element.DataMartDataSet.dataObject=데이터 개체

Element.DataMartDataSet.selectedColumns=선택한 열

#81 DataMartCube ( prefix Element.DataMartCube )
Element.DataMartCube.dataSource=데이터 원본

Element.DataMartCube.dataObject=데이터 개체

#82 TimeDimension ( prefix Element.TimeDimension )
Element.TimeDimension.startTimePoint=시작 시점

Element.TimeDimension.endTimePoint=종료 시점

Element.TimeDimension.hierarchies=계층

#83 DataMartLinkedDataModel ( prefix Element.DataMartLinkedDataModel )
Element.DataMartLinkedDataModel.dataSource=데이터 원본

Element.DataMartLinkedDataModel.dataObject=데이터 개체

#63 ReportItemTheme ( Prefix Element.ReportItemTheme )
Element.ReportItemTheme.slot.styles=스타일

Element.ReportItemTheme.type=형식

Element.ReportItemTheme.customValues=사용자 지정 값

#64 AbstractTheme ( Prefix Element.AbstractTheme )
Element.AbstractTheme.cssStyleSheets=CSS 스타일시트

#Category
Element.Category.helpText = 도움말 텍스트

Element.Category.helpTextKey = 도움말 텍스트 리소스 키

#Category Column
Element.CategoryColumn.aggregationFunction = 집계 함수

Element.CategoryColumn.aliasDataSet = 별칭 데이터 집합

Element.CategoryColumn.dataType = 데이터 형식

Element.CategoryColumn.expression =식

Element.CategoryColumn.resultSetColumnName = 결과 집합 열 이름

Element.CategoryColumn.helpText =도움말 텍스트

Element.CategoryColumn.ACLExpression =ACL 식

Element.CategoryColumn.heading =머리글

Element.CategoryColumn.horizontalAlign =가로 맞춤

Element.CategoryColumn.format =형식

Element.CategoryColumn.valueFormat =값 형식

Element.CategoryColumn.action =작업

Element.CategoryColumn.analysis =분석

###########################################################
# Predefined style
Style.Report=보고서

Style.List=(목록)


Style.GroupHeader1=GroupHeader1
Style.GroupHeader2=GroupHeader1
Style.GroupHeader3=GroupHeader1
Style.GroupHeader4=GroupHeader1
Style.GroupHeader5=GroupHeader1
Style.GroupHeader6=GroupHeader1
Style.GroupHeader7=GroupHeader1
Style.GroupHeader8=GroupHeader8
Style.GroupHeader9=GroupHeader9
Style.GroupFooter1=GroupFooter1
Style.GroupFooter2=GroupFooter2
Style.GroupFooter3=GroupFooter3
Style.GroupFooter4=GroupFooter4
Style.GroupFooter5=GroupFooter5
Style.GroupFooter6=GroupFooter6
Style.GroupFooter7=GroupFooter7
Style.GroupFooter8=GroupFooter8
Style.GroupFooter9=GroupFooter9

Style.ListHeader=ListHeader
Style.ListFooter=ListFooter
Style.ListGroupHeader1=ListGroupHeader1

Style.ListGroupHeader2=ListGroupHeader2

Style.ListGroupHeader3=ListGroupHeader3

Style.ListGroupHeader4=ListGroupHeader4

Style.ListGroupHeader5=ListGroupHeader5

Style.ListGroupHeader6=ListGroupHeader6

Style.ListGroupHeader7=ListGroupHeader7

Style.ListGroupHeader8=ListGroupHeader8

Style.ListGroupHeader9=ListGroupHeader9

Style.ListGroupFooter1=ListGroupFooter1

Style.ListGroupFooter2=ListGroupFooter2

Style.ListGroupFooter3=ListGroupFooter3

Style.ListGroupFooter4=ListGroupFooter4

Style.ListGroupFooter5=ListGroupFooter5

Style.ListGroupFooter6=ListGroupFooter6

Style.ListGroupFooter7=ListGroupFooter7

Style.ListGroupFooter8=ListGroupFooter8

Style.ListGroupFooter9=ListGroupFooter9


Style.ListDetail=ListDetail
Style.Table=테이블

Style.TableHeader=TableHeader
Style.TableHeaderCell=TableHeaderCell
Style.TableFooter=TableFooter
Style.TableFooterCell=TableFooterCell
Style.TableGroupHeader1=TableGroupHeader1

Style.TableGroupHeader2=TableGroupHeader2

Style.TableGroupHeader3=TableGroupHeader3

Style.TableGroupHeader4=TableGroupHeader4

Style.TableGroupHeader5=TableGroupHeader5

Style.TableGroupHeader6=TableGroupHeader6

Style.TableGroupHeader7=TableGroupHeader7

Style.TableGroupHeader8=TableGroupHeader8

Style.TableGroupHeader9=TableGroupHeader9

Style.TableGroupHeaderCell=TableGroupHeaderCell

Style.TableGroupFooter1=TableGroupFooter1

Style.TableGroupFooter2=TableGroupFooter2

Style.TableGroupFooter3=TableGroupFooter3

Style.TableGroupFooter4=TableGroupFooter4

Style.TableGroupFooter5=TableGroupFooter5

Style.TableGroupFooter6=TableGroupFooter6

Style.TableGroupFooter7=TableGroupFooter7

Style.TableGroupFooter8=TableGroupFooter8

Style.TableGroupFooter9=TableGroupFooter9

Style.TableGroupFooterCell=TableGroupFooterCell


Style.TableColumnHeader=TableColumnHeader
Style.TableDetail=TableDetail
Style.TableDetailCell=TableDetailCell
Style.Page=페이지

Style.Matrix=매트릭스

Style.MatrixRowHeader1=MatrixRowHeader1

Style.MatrixRowHeader2=MatrixRowHeader2

Style.MatrixRowHeader3=MatrixRowHeader3

Style.MatrixRowHeader4=MatrixRowHeader4

Style.MatrixRowHeader5=MatrixRowHeader5

Style.MatrixRowHeader6=MatrixRowHeader6

Style.MatrixRowHeader7=MatrixRowHeader7

Style.MatrixRowHeader8=MatrixRowHeader8

Style.MatrixRowHeader9=MatrixRowHeader9

Style.MatrixRowFooter1=MatrixRowFooter1

Style.MatrixRowFooter2=MatrixRowFooter2

Style.MatrixRowFooter3=MatrixRowFooter3

Style.MatrixRowFooter4=MatrixRowFooter4

Style.MatrixRowFooter5=MatrixRowFooter5

Style.MatrixRowFooter6=MatrixRowFooter6

Style.MatrixRowFooter7=MatrixRowFooter7

Style.MatrixRowFooter8=MatrixRowFooter8

Style.MatrixRowFooter9=MatrixRowFooter9

Style.MatrixColumnHeader1=MatrixColumnHeader1

Style.MatrixColumnHeader2=MatrixColumnHeader2

Style.MatrixColumnHeader3=MatrixColumnHeader3

Style.MatrixColumnHeader4=MatrixColumnHeader4

Style.MatrixColumnHeader5=MatrixColumnHeader5

Style.MatrixColumnHeader6=MatrixColumnHeader6

Style.MatrixColumnHeader7=MatrixColumnHeader7

Style.MatrixColumnHeader8=MatrixColumnHeader8

Style.MatrixColumnHeader9=MatrixColumnHeader9

Style.MatrixColumnFooter1=MatrixColumnFooter1

Style.MatrixColumnFooter2=MatrixColumnFooter2

Style.MatrixColumnFooter3=MatrixColumnFooter3

Style.MatrixColumnFooter4=MatrixColumnFooter4

Style.MatrixColumnFooter5=MatrixColumnFooter5

Style.MatrixColumnFooter6=MatrixColumnFooter6

Style.MatrixColumnFooter7=MatrixColumnFooter7

Style.MatrixColumnFooter8=MatrixColumnFooter8

Style.MatrixColumnFooter9=MatrixColumnFooter9


Style.MatrixCell=MatrixCell
Style.Chart=차트

Style.ChartTitle=ChartTitle
Style.ChartLegend=ChartLegend
Style.ChartValue=ChartValue
Style.ChartAxis=ChartAxis
Style.Label=레이블

Style.Data=데이터

Style.Number=번호

Style.String=문자열

Style.Text=텍스트

Style.Grid=눈금

Style.Toc=TOC 수준0

Style.Toc1=TOC 수준1

Style.Toc2=TOC 수준2

Style.Toc3=TOC 수준3

Style.Toc4=TOC 수준4

Style.Toc5=TOC 수준5

Style.Toc6=TOC 수준6

Style.Toc7=TOC 수준7

Style.Toc8=TOC 수준8

Style.Toc9=TOC 수준9


Style.FreeForm=FreeForm
Style.Line=꺽은선형

Style.Rectangle=사각형

Style.TextData=TextData
Style.ExtendedItem=ExtendedItem
Style.Image=이미지

###########################################################
# Messages.
Message.NamePrefixNew=새

Message.ChangeProperty=속성 변경:{0}

Message.ChangePropertyDefinition=속성 정의 변경

Message.MoveItem=항목 이동

Message.AddTranslation=변환 추가

Message.DropTranslation=변환 삭제

Message.ChangeTranslation=변환 변경

Message.MoveContent=내용 이동

Message.AddProperty=속성 추가

Message.DropProperty=속성 삭제

Message.SetName=이름 설정

Message.AddElement=요소 추가

Message.DropElement=요소 삭제

Message.SetStyle=스타일 설정

Message.ReplaceItem=항목 바꾸기

Message.SetLocale=로캘 설정

Message.SetTranslationText=변환 텍스트 설정

Message.MoveElement=요소 이동

Message.InsertElement=요소 삽입

Message.DeleteElement=요소 삭제

Message.SetExtends=확장 설정

Message.ChangeItem=항목 변경

Message.AddItem=항목 추가

Message.InsertItem=항목 삽입

Message.RemoveItem=항목 제거

Message.ReplaceElement=요소 바꾸기

Message.SetTheme=테마 설정

Message.ChangePropertyEncryption=속성 {0}의 암호화 변경

Message.RenameCSSFile=CSS 파일 이름 바꾸기

Message.ImportCSSStyles=CSS 스타일 가져오기

Message.InsertAndPasteColumnBand=열 삽입 및 붙여넣기

Message.PasteColumnBand=열 붙여넣기

Message.ShiftColumnBand=열 이동

Message.InsertColumnBand=열 삽입

Message.InsertRow=행 삽입

Message.InsertAndPasteRow=행 삽입 및 붙여넣기

Message.PasteRow=행 붙여넣기

Message.ShiftRow=행 이동

Message.ClearProperties=속성 지우기

Message.CreateTemplateElement=템플릿 요소 생성

Message.TransformToReportItem=보고서 항목으로 변환

Message.TransformToDataSet=데이터 집합으로 변환

Message.ExportElementToLibrary=라이브러리로 요소 내보내기

Message.ExportElementToDataMart=DataMart로 요소 내보내기

###########################################################
#Element new names.

New.ReportDesign=NewReportDesign
New.Parameter=NewParameter
New.CascadingParameterGroup=새 계단식 매개 변수 그룹

New.ScalarParameter=NewParameter
New.DynamicFilterParameter=새 동적 필터 매개 변수

New.ParameterGroup=NewParameterGroup
New.Style=NewStyle
New.MasterPage=NewMasterPage
New.ReportItem=NewReportItem
New.Label=NewLabel
New.FreeForm=NewFreeForm
New.Data=NewData
New.Text=NewText
New.ListingGroup=NewListingGroup
New.List=NewList
New.ListGroup=NewListGroup
New.Listint=NewListing
New.Table=NewTable
New.TableGroup=NewTableGroup
New.Column=NewColumn
New.Row=새 행

New.Cell=NewCell
New.Image=NewImage
New.Grid=NewGrid
New.Line=NewLine
New.Tile=NewTile
New.Rectangle=NewRectangle
New.GraphicMasterPage=새 그래픽 마스터 페이지

New.SimpleMasterPage=새 단순 마스터 페이지

New.TextData=NewTextData
New.ExtendedItem=NewExtendedItem
New.ScriptDataSource=새 스크립트 데이터 원본

New.ScriptDataSet=새 스크립트 데이터 집합

New.OdaDataSource=새 ODA 데이터 원본

New.OdaDataSet=새 ODA 데이터 집합

New.TemplateParameterDefinition=새 템플릿 매개 변수 정의

New.TemplateDataSet=새 템플릿 데이터 집합

New.TemplateReportItem=새 템플릿 보고서 항목

New.Theme=NewTheme
New.AutoText=NewAutoText
New.TabularCube=데이터 큐브

New.TabularDimension=그룹

New.TabularHierarchy=NewTabularHierarchy
New.TabularLevel=NewTabularLevel
New.TabularMeasure=NewTabularMeasure
New.TabularMeasureGroup=요약 필드

New.OdaCube=NewOdaCube

New.OdaDimension=NewOdaDimension
New.OdaHierarchy=NewOdaHierarchy
New.OdaLevel=NewOdaLevel
New.OdaMeasure=NewOdaMeasure
New.OdaMeasureGroup=NewOdaMeasureGroup
New.DerivedDataSet=NewDerivedDataSet
New.VariableElement=NewVariableElement
New.DataMartDataSource=NewDataMartDataSource
New.DataMartDataSet=NewDataMartDataSet
New.DataMartCube=NewDataMartCube
New.TimeDimension=NewTimeDimension
New.ReportItemTheme=새 보고서 항목 테마

New.CategoryColumn=NewCategoryColumn

###########################################################
#Default theme name.
Theme.defaultThemeName=defaultTheme

###########################################################
# Error Messages

#ContentException
Error.ContentException.SLOT_NOT_FOUND={0}에 슬롯(id:{1})이 정의되어 있지 않습니다.

Error.ContentException.WRONG_TYPE={1}이(가) {0}의 슬롯({2})에서 허용되지 않습니다.

Error.ContentException.CONTENT_NOT_FOUND={0}이(가) {2}의 슬롯({1}) 내에 나타나지 않습니다.

Error.ContentException.NOT_CONTAINER={0}은(는) 컨테이너가 아닙니다.

Error.ContentException.SLOT_IS_FULL={1}의 슬롯({0})이(가) 가득 찼습니다.

Error.ContentException.RECURSIVE=일정 수준에서 {0}에 {1}이(가) 포함되어 있어 {0}을(를) {1}(으)로 이동할 수 없습니다.

Error.ContentException.HAS_NO_CONTAINER={0}에 컨테이너가 없으므로 보고서에 추가할 수 없습니다.

Error.ContentException.MOVE_FORBIDDEN={0} 또는 해당 내용을 참조했으므로 {0}을(를) 이동할 수 없습니다.

Error.ContentException.HAS_DESCENDENTS={0}에 파생물이 있어 {0}을(를) 이동 또는 제거할 수 없습니다.

Error.ContentException.INVALID_CONTEXT_CONTAINMENT={0}이(가) 직접 또는 간접적으로 {1}'의 슬롯({2}) 안에서 허용되지 않습니다.

Error.ContentException.STRUCTURE_CHANGE_FORBIDDEN=요소 "{0}"은(는) 자식 요소이거나 가상 요소(자식 내부)이므로 구조를 변경할 수 없습니다.

Error.ContentException.CONTENT_NAME_REQUIRED={0}은(는) 이름이 없으므로 {1}의 {2} 슬롯에 추가할 수 없습니다.

Error.ContentException.INVALID_TEMPLATE_ELEMENT={0}에 명시적인 템플릿 매개 변수 정의가 없어서 {1}의 슬롯({2})에 삽입할 수 없습니다.

Error.ContentException.TEMPLATE_TRANSFORM_FORBIDDEN=요소를 템플릿으로 바꿀 수 없습니다.

Error.ContentException.GROUPS_CHANGE_FORBIDDEN=요소 "{0}"은(는) 보고서 항목을 공유하기 때문에 그룹을 추가, 제거, 또는 이동할 수 없습니다.

Error.ContentException.CONTENT_NOT_ALLOWED_PASTED=복사본이 잘못되어 {0}의 슬롯 {1}에 붙여 넣을 수 없습니다.

Error.ContentException.CONTENT_ALREADY_INSERTED="{0}" 요소가 이미 디자인 트리에 있으므로 "{1}"의 ({2})에 추가할 수 없습니다.

Error.ContentException.INVALID_POSITION=위치가 범위를 벗어났으며 잘못되었습니다.

Error.ContentException.SHARE_DIMENSION_NOT_EXIST=공유 차원 [{1}]이(가) 없으므로 보고서/라이브러리에 요소 [{0}]을(를) 삽입할 수 없습니다.

#CustomMsgException
Error.CustomMsgException.RESOURCE_KEY_REQUIRED=변환 리소스 키를 제공해야 합니다.

Error.CustomMsgException.DUPLICATE_LOCALE=리소스 "{1}"의 로캘 "{0}"에 대한 변환이 이미 정의되었습니다.

Error.CustomMsgException.INVALID_LOCALE=로캘 "{0}"은(는) 잘못된 로캘 이름입니다.

Error.CustomMsgException.TRANSLATION_NOT_FOUND=리소스 "{1}"의 로캘 "{0}"에 대한 변환이 없습니다.

    
#ExtendsException

#InvalidParentException
Error.InvalidParentException.NO_PARENT=요소 "{0}"에 상위가 없으므로 지역화할 수 없습니다.

Error.InvalidParentException.PARENT_NOT_FOUND=상위 요소 "{0}"이(가) 없습니다.

Error.InvalidParentException.UNNAMED_PARENT=상위 요소에 이름이 없습니다.

Error.InvalidParentException.PARENT_NOT_INCLUDE=상위 요소 "{0}"의 라이브러리가 포함되어 있지 않습니다.

#WrongTypeException
Error.WrongTypeException.WRONG_TYPE=상위 {0}은(는) 대상 {1}과(와) 확장자 유형이 다릅니다.

Error.WrongTypeException.WRONG_EXTENSION_TYPE=상위 {0}은(는) 대상 {1}과(와) 확장자 유형이 다릅니다.

#CircularExtendsException
Error.CircularExtendsException.SELF_EXTEND={0} 자체를 확장할 수 없습니다.

Error.CircularExtendsException.CIRCULAR={0}이(가) {1}에서 이미 확장되었으므로 순환 확장이 발견되었습니다.

#ExtendsForbiddenException
Error.ExtendsForbiddenException.PARENT_NOT_IN_COMPONENT=상위 요소 "{0}"이(가) 구성 요소에서 최상위 보고서 항목이 아닙니다.

Error.ExtendsForbiddenException.EXTENDS_FORBIDDEN=요소 "{0}"은(는) 자식 요소 내부에 있거나 이미 부모가 있으므로 확장할 수 없습니다.

Error.ExtendsForbiddenException.CANT_EXTEND=요소 "{0}"을(를) 파생할 수 없습니다.

Error.ExtendsForbiddenException.RESULT_SET_SHARED_CANT_EXTEND=공유 결과 집합 보고서 항목 "{0}"(은)는 파생이 허용되지 않습니다.
    
#NameException
Error.NameException.NAME_REQUIRED={0}의 이름이 필요합니다.

Error.NameException.NAME_FORBIDDEN={0}은(는) 이름을 가질 수 없습니다.

Error.NameException.DUPLICATE=이름 "{0}"이(가) 기존 이름과 중복됩니다. 다른 이름을 선택하십시오.

Error.NameException.HAS_REFERENCES={0}에 파생된 요소가 있어 이름을 지울 수 없습니다.

Error.NameException.INVALID_NAME=이름 "{0}"이(가) 잘못되었습니다. 다음과 같은 문자를 포함하면 안 됩니다. ".", "/", "\", "!", ";", ","

Error.NameException.INVALID_STYLE_NAME=스타일 이름 "{0}"은(는) CSS2 사양에 알맞지 않습니다.
    
#PropertyNameException
Error.PropertyNameException.PROPERTY_NOT_VALID=속성 "{0}"은(는) 요소 "{1}"에 알맞지 않습니다.

Error.PropertyNameException.MEMBER_NOT_VALID=구성원 "{0}"은(는) 구조 {1}"에 알맞지 않습니다.

    
#PropertyValueException
Error.PropertyValueException.INVALID_VALUE=값 "{0}"은(는) 형식 "{1}"에 알맞지 않습니다.

Error.PropertyValueException.PROPERTY_CHANGE_FORBIDDEN=속성 "{0}" 값은 요소 "{1}"이(가) 자식 요소에 있으므로 변경할 수 없습니다.

Error.PropertyValueException.CHOICE_NOT_FOUND=선택 값 "{0}"을(를) 찾을 수 없습니다.

Error.PropertyValueException.NOT_LIST_TYPE=속성 "{0}"은(는) 목록 형식이 아닙니다.

Error.PropertyValueException.ITEM_NOT_FOUND=지정한 구조가 속성 "{0}"에 없습니다.

Error.PropertyValueException.WRONG_ELEMENT_TYPE="{0}"이(가) 올바른 요소 참조 유형이 아닙니다.

Error.PropertyValueException.VALUE_EXISTS=값 "{0}"이(가) 이미 있습니다.

Error.PropertyValueException.VALUE_REQUIRED=속성 "{0}" 값이 필요합니다.

Error.PropertyValueException.VALUE_LOCKED=속성 값이 잠겨 있어 속성 "{0}" 값을 설정할 수 없습니다.

Error.PropertyValueException.UNIT_NOT_ALLOWED=단위 "{0}"이(가) 속성 "{1}"에 허용되지 않습니다.

Error.PropertyValueException.CHOICE_NOT_ALLOWED=선택 값 "{0}"이(가) 허용되지 않습니다.

Error.PropertyValueException.WRONG_ITEM_TYPE=구조 형식은 "{1}"이(가) 아니라 "{0}"입니다.

Error.PropertyValueException.NEGATIVE_VALUE=속성 "{1}"에 대한 값 "{0}"이(가) 잘못되었습니다. 값은 음수일 수 없습니다.

Error.PropertyValueException.NON_POSITIVE_VALUE=속성 "{1}"에 대한 값 "{0}"이(가) 잘못되었습니다. 값은 양수여야 합니다.

Error.PropertyValueException.EXTENSION_SETTING_FORBIDDEN=확장 항목 "{1}"의 속성 "{0}"이(가) 명령으로 설정 금지되었습니다.

Error.PropertyValueException.DOT_FORBIDDEN="." 문자를 포함하므로 "{0}" 이름이 잘못되었습니다.

Error.PropertyValueException.NOT_SUPPORTED_REPORT_ITEM_THEME_TYPE=보고서 항목 테마 형식 "{0}"이(가) 지원되지 않습니다.
    
#SemanticError
Error.SemanticError.INCONSISTENT_TABLE_COL_COUNT=테이블 "{0}"에 일치하지 않는 열 수가 있습니다.

Error.SemanticError.INCONSISTENT_TABLE_COL_COUNT_COZ_DROP=그룹 머리글의 일부 셀의 삭제 속성으로 인해 테이블 "{0}"에 일치하지 않는 열 수가 있습니다.

Error.SemanticError.INCONSISTENT_GRID_COL_COUNT=눈금 "{0}"에 일치하지 않는 열 수가 있습니다.

Error.SemanticError.OVERLAPPING_CELLS={0}의 행에 겹치는 셀이 있습니다.

Error.SemanticError.INCONSISTENT_TABLE_DROP_HEADINGS=테이블 "{0}"에 잘못된 삭제 머리글이 정의되어 있습니다.

Error.SemanticError.INVALID_PAGE_SIZE=마스터 페이지 "{0}"의 페이지 크기가 잘못되었습니다.

Error.SemanticError.MISSING_PAGE_SIZE=페이지 형식이 사용자 지정이므로 마스터 페이지 "{0}"의 크기가 필요합니다.

Error.SemanticError.CANNOT_SPECIFY_PAGE_SIZE=마스터 페이지 "{0}"의 페이지 형식이 사용자 지정이 아니므로 크기를 지정할 수 없습니다.

Error.SemanticError.INVALID_PAGE_MARGINS=마스터 페이지 "{0}"의 여백 값이 잘못되었습니다.

Error.SemanticError.MISSING_MASTER_PAGE=보고서에 하나 이상의 마스터 페이지가 있어야 합니다.

Error.SemanticError.INVALID_MULTI_COLUMN=마스터 페이지 "{0}"에 페이지 내용 밖으로 걸쳐진 열이 있습니다.

Error.SemanticError.INVALID_ELEMENT_REF=요소 "{0}"에 정의되지 않은 요소를 참조하거나 자신을 참조하는 속성 "{1}"이(가) 있습니다: "{2}".

Error.SemanticError.INVALID_DATA_BINDING_REF=요소 "{0}"에 요소의 컨테이너 또는 내용인 요소 "{1}"을(를) 참조하는 속성 dataBindingRef가 있습니다.

Error.SemanticError.MISSING_SQL_STMT=JDBC 선택 데이터 집합 "{0}"에는 SQL 문이 있어야 합니다.

Error.SemanticError.MISSING_DATA_SET={0}은(는) 하나의 데이터 집합을 액세스할 수 있어야 합니다.

Error.SemanticError.INVALID_IMAGE_SCALE_VALUE=이미지 "{0}"의 배율 값이 양수여야 합니다.

Error.SemanticError.IMAGE_FILE_NOT_FOUND=이미지 "{1}"에 정의된 파일 "{0}"이(가) 없습니다.

Error.SemanticError.NEGATIVE_REPORT_REFRESH_RATE=보고서의 새로 고침 빈도는 음수값이 아니어야 합니다.

Error.SemanticError.NEGATIVE_CELL_COLUMN=테이블/눈금/테이블 그룹 "{0}"에 음수로 시작하는 열을 가진 셀이 있습니다.

Error.SemanticError.NEGATIVE_WIDTH=요소 "{0}" 또는 해당 내용의 너비가 음수일 수 없습니다.

Error.SemanticError.NEGATIVE_HEIGHT=요소 "{0}" 또는 해당 내용의 높이가 음수일 수 없습니다.

Error.SemanticError.INVALID_COLUMN_REPEAT=테이블 "{0}"에 반복이 1보다 작은 열이 있습니다.

Error.SemanticError.INVALID_PAGE_COLUMNS=마스터 페이지 "{0}"에 1보다 작은 열이 있습니다.

Error.SemanticError.NEGATIVE_FONT_SIZE=스타일 "{0}"의 글꼴 크기가 음수일 수 없습니다.

Error.SemanticError.NEGATIVE_BORDER_WIDTH=스타일 "{0}"의 테두리 너비가 음수일 수 없습니다.

Error.SemanticError.INVALID_PROPERTY_NAME=요소 "{1}"의 속성 "{0}"이(가) 정의되지 않았습니다.

Error.SemanticError.UNSUPPORTED_ELEMENT=요소 {0}이(가) 아직 지원되지 않습니다.

Error.SemanticError.AT_LEAST_ONE_COLUMN=데이터 집합 "{0}"의 결과 집합에 하나 이상의 결과 집합 열이 있어야 합니다.

Error.SemanticError.NEGATIVE_LINE_HEIGHT=요소 "{0}"의 줄 높이는 음수 값이 아니어야 합니다.

Error.SemanticError.DUPLICATE_GROUP_NAME=테이블/목록 "{0}"에 중복 그룹 이름 "{1}"이(가) 있습니다.

Error.SemanticError.INVALID_CUSTOM_COLOR_NAME=사용자 지정 색상 이름 "{0}"이(가) CSS 표준 색상 이름이므로 사용할 수 없습니다.

Error.SemanticError.DUPLICATE_CUSTOM_COLOR_NAME=색상 팔레트에 중복 사용자 지정 색상 이름 "{0}"이(가) 있습니다.

Error.SemanticError.EXTENSION_NOT_FOUND=요소 "{1}"의 확장 이름 "{0}"을(를) 찾을 수 없습니다.

Error.SemanticError.MISSING_EXTENSION=요소 "{0}"의 확장 이름을 정의해야 합니다.

Error.SemanticError.PROPERTY_COPY_FORBIDDEN=속성 "{0}"을(를) 복사하는 것은 금지되어 있습니다.

Error.SemanticError.COLUMN_COPY_FORBIDDEN=요소 "{1}"의 "{0}" 열을 복사하는 것은 금지되어 있습니다.

Error.SemanticError.COLUMN_PASTE_FORBIDDEN=요소 "{1}"을 붙여넣는 것은 금지되어 있습니다.

Error.SemanticError.COLUMN_PASTE_DIFFERENT_LAYOUT=붙여넣기 영역에 복사한 영역을 포함한 다른 레이아웃이 있습니다..

Error.SemanticError.INVALID_STRUCTURE_REF=요소 "{0}"에 정의되지 않은 구조 "{2}"을(를) 참조하는 속성 "{1}"이(가) 있습니다.

Error.SemanticError.INVALID_SCALAR_PARAMETER_TYPE=형식 스칼라 매개변수 "{0}"이(가) 잘못되었습니다. 계단식 매개변수 그룹 내 매개변수는 동적 형식이어야 합니다.

Error.SemanticError.MISSING_TEMPLATE_PARAMETER_TYPE=요소 {0}이(가) "allowedType"을 명시적으로 정의해야 합니다.

Error.SemanticError.INCONSISTENT_TEMPLATE_PARAMETER_TYPE=요소 {0}의 기본 요소 {1}은(는) {2}의 종류가 아닙니다.

Error.SemanticError.INVALID_LIBRARY_REFERENCE=참조 구조가 없으므로 {0} "{1}"의 라이브러리 참조 "{2}"이(가) 잘못되었습니다.

Error.SemanticError.INVALID_PROPERTY_BINDING_ID={0}의 "{1}" 속성 바인딩이 존재하지 않는 요소를 참조합니다.

Error.SemanticError.PROPERTY_BINDING_FORBIDDEN=요소 "{0}"이(가) 디자인 트리에 없으므로 속성 바인딩을 설정할 수 없습니다.

Error.SemanticError.INVALID_MASTER_PAGE_CONTEXT_CONTAINMENT=테이블 또는 목록은 마스터 페이지 "{0}" 안에 직접적으로나 간접적으로나 사용할 수 없습니다.

Error.SemanticError.DATA_SET_MISSED_IN_JOINT_DATA_SET = 조인 데이터 집합 "{0}"에 데이터 집합 "{1}"이(가) 누락되었습니다.

Error.SemanticError.MISSING_COLUMN_BINDING = "{1}" 열 이름의 "{0}" 데이터에 대한 열 바인딩이 정의되지 않았습니다.

Error.SemanticError.COLUMN_INSERT_FORBIDDEN=요소 "{0}"에 대한 삽입 작업은 금지되었습니다.

Error.SemanticError.CANNOT_SPECIFY_VALUE=\"{4}\"의 값 \"{3}\"(으)로 인해 요소 "{0}"이(가) 속성 \"{2}\"의 값 \"{1}\"을(를) 지정할 수 없습니다.

Error.SemanticError.ROW_COPY_FORBIDDEN=요소 "{0}"을(를) 복사하는 것은 금지되어 있습니다.

Error.SemanticError.ROW_PASTE_FORBIDDEN=요소 "{0}"을(를) 붙여넣는 것은 금지되어 있습니다.

Error.SemanticError.ROW_INSERT_FORBIDDEN=요소 "{0}"을(를) 삽입하는 것은 금지되어 있습니다.

Error.SemanticError.ROW_SHIFT_FORBIDDEN=요소 "{0}"을(를) 이동하는 것은 금지되어 있습니다.

Error.SemanticError.ROW_INSERTANDPASTE_FORBIDDEN=요소 "{0}"을(를) 삽입 및 붙여 넣는 것은 금지되어 있습니다.

Error.SemanticError.CIRCULAR_ELEMENT_REFERNECE= {0}은 이미 {1}을 참조하므로 순환 요소 참조를 찾을 수 있습니다.

Error.SemanticError.INCONSISTENT_DATA_GROUP=요소 {0}의 데이터 바인딩 참조의 그룹 수와 참조하고 있는 요소 {1}의 그룹 수가 다릅니다.

Error.SemanticError.INVALID_MANIFEST=요소 {0}에 잘못된 매니페스트가 있습니다.

Error.SemanticError.VALUE_FORBIDDEN=목록 속성 "{0}"이(가) 비어 있어 어떤 항목도 가질 수 없습니다.

Error.SemanticError.TABLE_NO_COLUMN_FOUND = 열을 찾을 수 없으므로 테이블의 너비를 계산할 수 없습니다.

Error.SemanticError.TABLE_COLUMN_WITH_NO_WIDTH = 인덱스 {0}에 열의 너비가 정의되지 않았으므로 테이블의 너비를 계산할 수 없습니다.

Error.SemanticError.TABLE_COLUMN_INCONSISTENT_UNIT_TYPE = 테이블에 백분율이 아닌 절대 단위 및 상대 단위를 사용한 열이 다수 포함되어 있으므로 테이블의 너비를 계산할 수 없습니다.

Error.SemanticError.TABLE_COLUMN_INCONSISTENT_RELATIVE_UNIT = 테이블에 서로 다른 상대 단위를 사용한 열이 다수 포함되어 있으므로 테이블의 너비를 계산할 수 없습니다.

Error.SemanticError.TABLE_COLUMN_ILLEGAL_PERCENTAGE = 백분율을 사용한 열의 너비 합이 100% 이상이므로 테이블의 너비를 계산할 수 없습니다.

Error.SemanticError.CANNOT_SPECIFY_DATA_OBJECT=외부 보고서 항목에서 다른 큐브 또는 데이터 집합과 다중 보기를 정의했으므로 보고서 항목 "{0}"은(는) 큐브 또는 데이터 집합을 지정할 수 없습니다.

#SemanticException
Error.SemanticException.EXPORT_ELEMENT_FAIL=대상 라이브러리에 중복된 요소 이름이 있습니다. 요소 {0}을(를) 내보낼 수 없습니다. 내보낸 요소 이름을 변경하십시오.

#StyleException
Error.StyleException.FORBIDDEN={0}은(는) 스타일을 가질 수 없습니다.

Error.StyleException.NOT_FOUND={1}에서 사용된 스타일 "{0}"이(가) 없습니다.
    
#ThemeException
Error.ThemeException.NOT_FOUND={1}에서 사용하는 테마 "{0}"이(가) 없습니다.

Error.ThemeException.WRONG_TYPE={1}에서 사용하는 테마 "{0}"이(가) 잘못된 형식의 보고서 항목 테마입니다.
    
#DesignParserException
Error.DesignParserException.FILE_NOT_FOUND=파일 "{0}"이(가) 없습니다.

Error.DesignParserException.FILE_FORMAT_NOT_SUPPORT=파일 "{0}" 형식이 지원되지 않습니다.

Error.DesignParserException.RGB_REQUIRED=사용자 지정 색상이 올바른 RGB값을 가져야 합니다.

Error.DesignParserException.COLOR_NAME_REQUIRED=사용자 지정 색상에 색 이름이 있어야 합니다.

Error.DesignParserException.ILLEGAL_EXTENDS=요소를 확장할 수 없습니다.

Error.DesignParserException.IMAGE_REF_CONFLICT=이미지에 충돌 참조가 있습니다.

Error.DesignParserException.INVALID_IMAGEREF_EXPR_VALUE=이미지 참조 식 값이 잘못되었습니다.

Error.DesignParserException.INVALID_IMAGE_URL_VALUE=이미지 URL 값이 잘못되었습니다.

Error.DesignParserException.INVALID_IMAGE_NAME_VALUE=이미지 이름 값이 잘못되었습니다.

Error.DesignParserException.ACTION_REPORTNAME_REQUIRED=작업에 보고서 이름이 필요합니다.

Error.DesignParserException.ACTION_PARAMETER_NAME_REQUIRED=작업 시 매개 변수 이름이 필요합니다.

Error.DesignParserException.CHOICE_RESTRICTION_VIOLATION=선택 제한이 위반되었습니다.

Error.DesignParserException.MESSAGE_KEY_REQUIRED=사용자 정의 메시지에서 "키" 값을 지정해야 합니다.

Error.DesignParserException.DUPLICATE_TRANSLATION_LOCALE=동일한 로캘을 가진 두 개의 변환이 사용자 정의 메시지에 나타납니다.

Error.DesignParserException.NAME_REQUIRED=요소 속성 이름 또는 구조 구성원 이름이 필요합니다.

Error.DesignParserException.WRONG_STRUCTURE_LIST_TYPE=이러한 요소 속성 또는 구조 구성원은 구조 목록 형식이 아닙니다.

Error.DesignParserException.WRONG_EXTENDED_PROPERTY_TYPE=속성이 확장된 속성이 아닙니다.

Error.DesignParserException.INVALID_STRUCTURE_NAME=이름이 구조 이름이 아닙니다.

Error.DesignParserException.INVALID_PROPERTY_SYNTAX=속성이 요소의 특성으로 정의되어야 합니다.

Error.DesignParserException.UNDEFINED_PROPERTY=속성 "{0}"이(가) 정의되지 않았습니다.

Error.DesignParserException.UNSUPPORTED_ENCODING=이 XML 파일의 인코딩 형식은 지원되지 않습니다.

Error.DesignParserException.PROPERTY_IS_NOT_ENCRYPTABLE=속성 "{0}"을(를) 암호화할 수 없습니다.

Error.DesignParserException.UNSUPPORTED_VERSION=버전 "{0}"의 보고서 파일이 잘못되었습니다. 최신 지원 파일보다 크면 안 됩니다.

Error.DesignParserException.INVALID_VERSION=보고서 버전 "{0}"이(가) 잘못되었습니다.

Error.DesignParserException.INVALID_ELEMENT_ID={0}의 ID {1}이(가) 잘못되었습니다.

Error.DesignParserException.VIRTUAL_PARENT_NOT_FOUND=BaseID "{0}"은(는) 가상 부모나 부모에 없는 참조 부모를 참조할 수 없습니다.

Error.DesignParserException.DUPLICATE_ELEMENT_ID={0}의 ID가 {1}의 ID와 중복됩니다.

Error.DesignParserException.INCONSISTENT_TEMPLATE_ELEMENT_TYPE=템플릿 요소 {0}이(가) 참조 템플릿 매개 변수 정의 {1}의 기본 요소와 일치하지 않습니다.

Error.DesignParserException.MISSING_TEMPLATE_PARAMETER_DEFAULT=요소 {0}이(가) 기본 요소를 명시적으로 정의해야 합니다.

Error.DesignParserException.WRONG_SIMPLE_LIST_TYPE=요소 속성이 단순 목록 형식이 아닙니다.

#DesignFileException
Error.DesignFileException.SYNTAX_ERROR=구문 오류가 있습니다. 오류 상세 정보를 참조하십시오.

Error.DesignFileException.SEMANTIC_WARNING=의미 경고가 있습니다. 경고 상세 정보를 참조하십시오.

Error.DesignFileException.SEMANTIC_ERROR=의미 오류가 있습니다. 오류 상세 정보를 참조하십시오.

Error.DesignFileException.INVALID_XML=디자인 파일이 잘못된 xml 파일입니다.

#XMLParserException
Error.XMLParserException.UNKNOWN_TAG=XML 파일에 지원되지 않는 요소가 있습니다.

Error.XMLParserException.SAX_ERROR=SAX이 파일의 기본 XML 구문에서 오류를 검색했습니다.

Error.XMLParserException.INVALID_BOOLEAN=부울 특성에 알맞은 값이 없습니다.

Error.XMLParserException.WARNINGS_FOUND=구문 분석이 완료되었으나 복구할 수 있는 오류가 발생했습니다.

Error.XMLParserException.EXCEPTION=일반 예외가 발생했습니다.

Error.XMLParserException.INVALID_INTEGER=정수 특성에 잘못된 값이 있습니다.
    
#UserPropertyException
Error.UserPropertyException.NAME_REQUIRED=사용 속성에 이름이 있어야 합니다.

Error.UserPropertyException.DUPLICATE_NAME=이름이 "{0}"인 사용자 속성이 이미 있습니다.

Error.UserPropertyException.INVALID_TYPE=사용자 속성 형식이 잘못되었습니다.

Error.UserPropertyException.MISSING_CHOICES=사용자 속성 형식이 선택이지만 선택이 정의되지 않았습니다.

Error.UserPropertyException.INVALID_DISPLAY_ID=표시 이름 ID 및 표시 이름이 사용자 속성 "{0}"에서 둘 다 정의되지 않았습니다.

Error.UserPropertyException.NOT_FOUND=사용자 속성 "{0}"을(를) 찾을 수 없습니다.

Error.UserPropertyException.USER_PROP_DISALLOWED={0}은(는) 사용자 속성을 가질 수 없습니다.

Error.UserPropertyException.CHOICE_VALUE_REQUIRED=사용자 정의 선택 값이 사용자 속성 "{0}"에 필요합니다.

Error.UserPropertyException.CHOICE_NAME_REQUIRED=사용자 정의 선택 이름이 사용자 속성 "{0}"에 필요합니다.

Error.UserPropertyException.INVALID_CHOICE_VALUE=선택 값이 사용자 속성 "{0}"의 형식에 알맞지 않습니다.

Error.UserPropertyException.INVALID_DEFINITION=사용자 속성 정의가 잘못되었습니다.

Error.UserPropertyException.INVALID_DEFAULT_VALUE={0}에 있는 사용자 속성 "{1}"의 기본값 "{2}"이(가) 형식 "{3}"에 알맞지 않습니다.

#MetaDataReaderException
Error.MetaDataReaderException.META_DATA_ERROR=메타데이터가 잘못되었습니다.

#LibraryException
Error.LibraryException.LIBRARY_NOT_FOUND=네임스페이스가 "{0}"인 라이브러리를 찾을 수 없습니다.

Error.LibraryException.DUPLICATE_LIBRARY_NAMESPACE=라이브러리 네임스페이스 "{0}"이(가) 이미 있습니다.

Error.LibraryException.LIBRARY_INCLUDED_RECURSIVELY=네임스페이스가 "{0}"인 라이브러리가 반복 포함됩니다.

Error.LibraryException.LIBRARY_HAS_DESCENDENTS=현재 모듈에 하위 항목 "{1}"이(가) 있으므로 라이브러리 "{0}"을(를) 삭제할 수 없습니다.

Error.LibraryException.LIBRARY_ALREADY_INCLUDED=라이브러리 "{0}"이(가) 이미 포함되어 있으며 라이브러리는 두 번 추가할 수 없습니다.

Error.LibraryException.INVALID_LIBRARY_NAMESPACE=라이브러리의 네임스페이스 "{0}"이(가) 잘못되었습니다. 비어 있거나 잘못된 문자를 포함하고 있습니다.

#StyleSheetException
Error.StyleSheetException.STYLE_SHEET_NOT_FOUND=스타일시트 리소스가 없습니다.

Error.StyleSheetException.SYNTAX_ERROR=CSS2와 일치하지 않는 일부 구문 오류가 있습니다.

#IncludedCssStyleSheetException
Error.CSSException.CSS_NOT_FOUND=이름이 "{0}"인 스타일시트를 찾을 수 없습니다.

Error.CSSException.DUPLICATE_CSS=이름이 "{0}"인 CSS 스타일시트가 이미 있습니다.

Error.CSSException.BADCSSFILE="{0}" 파일에 구문 오류가 있습니다.

Error.CssException.READONLY="{0}" 파일에 있는 스타일이 읽기 전용입니다.

#StyleSheetParserException
Error.StyleSheetParserException.RULE_NOT_SUPPORTED=규칙 "{0}"이(가) 지원되지 않습니다.

Error.StyleSheetParserException.STYLE_NOT_SUPPORTED=스타일 "{0}"이(가) 지원되지 않습니다.

Error.StyleSheetParserException.PROPERTY_NOT_SUPPORTED=CSS2 속성 "{0}"에 대한 "{1}" 값이 지원되지 않습니다.

Error.StyleSheetParserException.INVALID_SHORT_HAND_CSSPROPERTY_VALUE=CSS2 문법에 대한 약식 속성 "{0}"의 값 "{1}"이(가) 잘못되었습니다.

Error.StyleSheetParserException.INVALID_SIMPLE_CSSPROPERTY_VALUE=속성 "{0}"에 대한 값 "{1}"이(가) 잘못되었습니다.
	
#TemplateException
Error.TemplateException.INVALID_TEMPLATE_ELEMENT_TYPE={0}이(가) 보고서 항목이 아니거나 데이터 집합 요소가 아니므로 템플릿 요소로 변환할 수 없습니다.

Error.TemplateException.TRANSFORM_TO_REPORT_ITEM_FORBIDDEN={0}에 명시적 템플릿 매개 변수 정의가 없으므로 보고서 항목으로 변환할 수 없습니다.

Error.TemplateException.TRANSFORM_TO_DATA_SET_FORBIDDEN={0}에 명시적 템플릿 매개 변수 정의가 없으므로 데이터 집합으로 변환할 수 없습니다.

Error.TemplateException.REVERT_TO_TEMPLATE_FORBIDDEN={0}에 명시적 템플릿 매개 변수 정의가 없으므로 템플릿 요소로 되돌릴 수 없습니다.

Error.TemplateException.CREATE_TEMPLATE_ELEMENT_FORBIDDEN={0}이(가) 보고서에 없으므로 변환을 수행할 수 없습니다.

Error.TemplateException.TEMPLATE_ELEMENT_NOT_SUPPORTED=템플릿 요소가 라이브러리에서 지원되지 않습니다.

#VersionInfo
Info.VersionInfo.INVALID_DESIGN_FILE=열린 디자인 파일이 올바른 디자인 파일이 아니거나 해당 파일이 없습니다.

Info.VersionInfo.CONVERT_INFO=이전 버전의 BIRT에서 만든 디자인 파일입니다. 현재 버전에서 지원하는 형식으로 변환하려면 확인을 누르십시오.

Info.VersionInfo.INVALID_VERSION=버전 {0}의 보고서 파일이 지원되지 않습니다.

Info.VersionInfo.LATER_VERSION=최신 버전의 BIRT에서 만든 디자인 파일입니다. 현재 버전에서 지원하는 형식으로 변환하려면 확인을 누르십시오.

Info.VersionInfo.EXTENSION_COMPATIBILITY =열린 디자인/라이브러리 또는 포함된 라이브러리는 이전 버전과 호환되므로 디자인/라이브러리가 변경될 수 있습니다.

#EncryptionException
Error.EncryptionException.INVALID_ENCRYPTABLE_PROPERTY={0}의 속성 {1}이(가) 암호화 가능 상태가 아니므로 암호화를 변경할 수 없습니다.

Error.EncryptionException.INVALID_ENCRYPTION=암호화 ID "{0}"이(가) 잘못되었습니다. 존재하지 않는 암호화입니다.

#Dashboard Exporter
Message.ExportGadgetToSharedGadgetFile=공유 가젯 파일로 가젯을 내보냅니다.

Message.ExportTabToSharedTabFile=공유 탭 파일로 탭을 내보냅니다.

#Dashboard Exception
Error.ExternalGadgetFileIncludedRecursively=외부 가젯이 재귀적으로 포함되어 있습니다.

Error.NotFoundExporter=대시보드 내보내기를 찾을 수 없습니다.
