ChartCubeQueryHelper.Error.MustBindCube=El diagrama debe vincular un cubo a los datos de alimentación.

ChartReportItemPresentationImpl.error.NoData=El conjunto de datos enlazado al diagrama no ha devuelto ninguna fila.

ChartReportItemPresentationImpl.error.InvalidCubeBinding=El conjunto de datos que utiliza este diagrama se ha modificado. Ya no se puede procesar este diagrama.

ChartReportItemPresentationImpl.log.UnableToLocateWrapper=No se puede localizar el empaquetador de elementos de informe para el objeto de diagrama.

ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl: onRowSets(...) - inicio

ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl: onRowSets(...) - diagrama de compilación

ChartReportItemPresentationImpl.log.WritingFile=Escribiendo el archivo {0} a las {1}

ChartReportItemPresentationImpl.exception.tmpPngFileCreation=Creación de archivo PNG temporal

ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=La presentación utiliza enlaces: {0}

ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) - diagrama de procesamiento

ChartReportItemPresentationImpl.exception.inputStreamCreation=creación de secuencia de entrada

ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) - error

ChartReportItemPresentationImpl.exception.UnexpectedError=Error inesperado

ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) - final

ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) - inicio

ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) - final

ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp=Archivo {0} temporal eliminado con éxito en {1}.

ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) - final

ChartWithoutAxesImpl.exception.3DNotSupported=3D no compatible con ChartWithoutAxes.

ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) - inicio

ChartReportItemPresentationImpl.log.CouldNotDeleteTemp=No se ha podido eliminar el archivo {0} temporal creado en {1}.

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) - excepción

ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) - final

ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) - inicio

ChartReportItemQueryImpl.exception.getReportQueries=Obteniendo consultas de informe

ChartReportItemQueryImpl.log.UnableToLocate=No se puede localizar el empaquetador de elementos de informe para el objeto de diagrama.

ChartReportItemImpl.log.validate=validando(...)

ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=No se puede establecer el estado 'transpuesto' en un diagrama sin ejes.

ChartReportItemImpl.log.UnexpectedChoiceName=Encontrado nombre de selección inesperado:

ChartReportItemImpl.log.RequestForPropertyDefn=Se ha recibido la solicitud para las definiciones de propiedades antes de que se creara el modelo.

ChartReportItemImpl.log.RequestForScriptPropertyDefn=Solicite la definición de propiedades del script.

ChartReportItemImpl.log.checkProperty=CheckProperty(...) - {0} con valor {1}

ChartReportItemImpl.log.setProperty=SetProperty(...) - {0} con valor {1}

QueryHelper.exception.UnexpectedNull=Definición de consulta 'nula' inesperada proporcionada por el frame de la extesión: motor/generación de informe.

QueryHelper.Text.CategroySeries=Serie de categoría

QueryHelper.Text.ValueSeries=Serie del valor

QueryHelper.Text.XSeries=Serie X

QueryHelper.Text.YSeries=Serie Y

QueryHelper.NoDataDefinitionFor=No existen entradas de definición de datos para {0}

QueryHelper.dataDefnUndefined=No se ha definido una entrada de definición de datos para {0}.

QueryHelper.InconsitentDataTypesForAxis=Todas las definiciones de datos del mismo eje Y deben ser del mismo tipo de datos.

QueryHelper.InconsitentDataTypesForValueSeries=Todas las definiciones de datos de la serie del valor deben ser del mismo tipo de datos.

ChartElementCommandImpl.editChart=Editar diagrama

ChartElementCommandImpl.setProperty.chart.dimension=Establecer dimensión

ChartElementCommandImpl.setProperty.chart.instance=Establecer Modelo de diagrama

ChartElementCommandImpl.setProperty.plot.transposed=Establecer como transpuesto

ChartElementCommandImpl.setProperty.script=Editar script de diagrama

ChartElementCommandImpl.setProperty.onRender=Editar script de diagrama

ChartImpl.error.DimensionUnitNotSupported=La unidad de dimensión ({0}) no es compatible con el diagrama API simple.

################################################
# Display names for report model extension 
################################################
Element.Chart=Diagrama

Element.Chart.xmlRepresentation=Modelo XML

Element.Chart.outputFormat=Formato de salida

Element.Chart.action=Acción

Element.Chart.altText=Texto alternativo

Element.Chart.altTextID=Clave de texto alternativo


choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=2D con profundidad

choice.chart.dimension.three_dimensional=3D
property.category.general=General

property.category.types=Tipos

property.label.title.value=Título:

property.label.title.font.rotation=Rotación de título:

property.label.legend.position=Posición de la leyenda:

property.label.legend.anchor=Delimitador de la leyenda:

property.label.chart.dimension=Dimensión:

property.label.chart.plot.transposed=Transpuesto

property.script=Script

property.onRender=onRender

exception.no.cube.edge=Cursor de cubo de datos sin extremo. Compruebe si las expresiones de la consulta son correctas.

exception.script.syntaxError=Error de sintaxis de script: {0}

