ChartReportItemPresentationImpl.error.NoData=차트에 바인딩된 데이터 집합에서 반환된 행이 없습니다.
ChartReportItemPresentationImpl.log.UnableToLocateWrapper=차트 객체에 대해 보고서 항목 래퍼를 찾을 수 없습니다.
ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl: onRowSets(...) - 시작
ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl: onRowSets(...) - 차트 빌드 중
ChartReportItemPresentationImpl.log.WritingFile={1}에 {0} 파일을 쓰는 중
ChartReportItemPresentationImpl.exception.tmpPngFileCreation=임시 PNG 파일 생성
ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=프리젠테이션에서 {0} 바운드를 사용합니다.
ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) - 차트 렌더링 중
ChartReportItemPresentationImpl.exception.inputStreamCreation=입력 스트림 생성
ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) - 실패
ChartReportItemPresentationImpl.exception.UnexpectedError=예기치 못한 오류
ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) - 종료
ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) - 시작
ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) - 종료
ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp={1}에서 {0} 임시 파일이 삭제되었습니다. 
ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) - end
ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) - 시작
ChartReportItemPresentationImpl.log.CouldNotDeleteTemp={1}에서 만들어진 {0} 임시 파일을 삭제할 수 없습니다.

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) - 예외
ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) - 종료
ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) - start
ChartReportItemQueryImpl.exception.getReportQueries=보고서 쿼리를 가져오는 중
ChartReportItemQueryImpl.log.UnableToLocate=차트 개체에 대한 보고서 항목 래퍼를 찾을 수 없습니다.

ChartReportItemImpl.log.validate=확인 중(...)
ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=축이 없는 차트에는 '바꿈' 상태를 설정할 수 없습니다.
ChartReportItemImpl.log.UnexpectedChoiceName=예기치 못한 선택 이름 발견: 
ChartReportItemImpl.log.RequestForPropertyDefn=모델이 만들어지기 전에 수신된 속성 정의 요청입니다.
ChartReportItemImpl.log.RequestForScriptPropertyDefn=스크립트 속성 정의 요청입니다.
ChartReportItemImpl.log.checkProperty=CheckProperty(...) - 값 {1}을(를) 가진 {0}
ChartReportItemImpl.log.setProperty=SetProperty(...) - 값 {1}을(를) 가진 {0}

QueryHelper.exception.UnexpectedNull=확장 프레임워크 - 보고서 엔진/생성에서 예기지 못한 'null' 쿼리 정의를 제공했습니다.
QueryHelper.Text.CategroySeries=범주 계열
QueryHelper.Text.ValueSeries=값 계열
QueryHelper.Text.XSeries=X 계열
QueryHelper.Text.YSeries=Y 계열

SeriesQueries.NoDataDefinitionFor={0}에 대한 데이터 정의 항목이 없습니다.
SeriesQueries.dataDefnUndefined={0}에 대한 데이터 정의 항목이 정의되지 않았습니다.
ChartElementCommandImpl.editChart=차트 편집
ChartElementCommandImpl.setProperty.chart.dimension=차원 설정
ChartElementCommandImpl.setProperty.plot.transposed=바꿈 설정
ChartElementCommandImpl.setProperty.script=차트 스크립트 편집

################################################
# Display names for report model extension 
################################################

Element.Chart=차트
Element.Chart.xmlRepresentation=XML 모델
Element.Chart.outputFormat=출력 형식

choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=2D(깊이)
choice.chart.dimension.three_dimensional=3D

property.category.general=일반
property.category.types=형식

property.label.title.value=제목:
property.label.title.font.rotation=제목 회전:
property.label.legend.position=범례 위치:
property.label.legend.anchor=범례 앵커:
property.label.chart.dimension=차원:
property.label.chart.plot.transposed=바꿈
property.script=스크립트

exception.script.syntaxError=스크립트 구문 오류: {0}

