ChartCubeQueryHelper.Error.MustBindCube=图表必须绑定多维数据集以植入数据。

ChartReportItemPresentationImpl.error.NoData=联接至图表的数据集未返回行.

ChartReportItemPresentationImpl.error.InvalidCubeBinding=此图表使用的数据集已更改。 此图表将不再呈现。

ChartReportItemPresentationImpl.log.UnableToLocateWrapper=无法为图表对象找到报表项包装程序。

ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl: onRowSets(...) - 开始

ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl: onRowSets(...) - 生成图表

ChartReportItemPresentationImpl.log.WritingFile=正在写入 {1} 处的 {0} 文件

ChartReportItemPresentationImpl.exception.tmpPngFileCreation=创建临时 PNG 文件

ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=表示使用界限: {0}

ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) - 呈现图表

ChartReportItemPresentationImpl.exception.inputStreamCreation=创建输入流

ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) - 失败

ChartReportItemPresentationImpl.exception.UnexpectedError=意外错误

ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) - 结束

ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) - 开始

ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) - 结束

ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp=已成功删除 {1} 处的临时 {0} 文件。

ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) - 结束

ChartWithoutAxesImpl.exception.3DNotSupported=对于 ChartWithoutAxes，不支持 3D。

ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) - 开始

ChartReportItemPresentationImpl.log.CouldNotDeleteTemp=无法删除在 {1} 处创建的临时 {0} 文件。

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) - 异常

ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) - 结束

ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) - 开始

ChartReportItemQueryImpl.exception.getReportQueries=正在获取报表查询

ChartReportItemQueryImpl.log.UnableToLocate=无法为图表对象找到报表项包装程序。

ChartReportItemImpl.log.validate=正在验证(...)

ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=无法在没有轴的情况下对图表设置“已变换”状态。

ChartReportItemImpl.log.UnexpectedChoiceName=找到意外的选项名称:

ChartReportItemImpl.log.RequestForPropertyDefn=创建模型之前收到对属性定义的请求。

ChartReportItemImpl.log.RequestForScriptPropertyDefn=请求脚本属性定义。

ChartReportItemImpl.log.checkProperty=CheckProperty(...) - {0}，具有值 {1}

ChartReportItemImpl.log.setProperty=SetProperty(...) - {0}，具有值 {1}

QueryHelper.exception.UnexpectedNull=扩展框架提供意外的 'null' 查询定义 - 报表引擎/生成。

QueryHelper.Text.CategroySeries=类别系列

QueryHelper.Text.ValueSeries=值系列

QueryHelper.Text.XSeries=X 系列

QueryHelper.Text.YSeries=Y 系列

QueryHelper.NoDataDefinitionFor={0} 没有数据定义条目

QueryHelper.dataDefnUndefined=未定义 {0} 的数据定义条目。

QueryHelper.InconsitentDataTypesForAxis=同一 Y 轴中所有数据定义的数据类型应该相同。

QueryHelper.InconsitentDataTypesForValueSeries=值系列中所有数据定义的数据类型应该相同。

ChartElementCommandImpl.editChart=编辑图表

ChartElementCommandImpl.setProperty.chart.dimension=设置维

ChartElementCommandImpl.setProperty.chart.instance=设置图表模型

ChartElementCommandImpl.setProperty.plot.transposed=设置转置

ChartElementCommandImpl.setProperty.script=编辑图表脚本

ChartElementCommandImpl.setProperty.onRender=编辑图表脚本

ChartImpl.error.DimensionUnitNotSupported=Chart Simple API 不支持维单位 ({0})

################################################
# Display names for report model extension 
################################################
Element.Chart=图表

Element.Chart.xmlRepresentation=XML 模型

Element.Chart.outputFormat=输出格式

Element.Chart.action=操作

Element.Chart.altText=替代文本

Element.Chart.altTextID=替代文本关键字


choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=二维并具有深度

choice.chart.dimension.three_dimensional=3D
property.category.general=常规

property.category.types=类型

property.label.title.value=标题:

property.label.title.font.rotation=标题旋转:

property.label.legend.position=图例位置:

property.label.legend.anchor=图例定位标记:

property.label.chart.dimension=维:

property.label.chart.plot.transposed=转置

property.script=脚本

property.onRender=呈现时

exception.no.cube.edge=多维数据集游标没有边。请检查查询表达式是否正确。

exception.script.syntaxError=脚本语法错误: {0}

