ChartCubeQueryHelper.Error.MustBindCube=グラフには、データをフィードするキューブを関連付ける必要があります。

ChartReportItemPresentationImpl.error.NoData=グラフにバインドされているデータセットからは行が返されません。.

ChartReportItemPresentationImpl.error.InvalidCubeBinding=このグラフで使用するデータセットが変更されました。 このグラフはレンダリングできなくなります。

ChartReportItemPresentationImpl.log.UnableToLocateWrapper=グラフオブジェクトのレポート項目ラッパーが見つかりません。

ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl : onRowSets(...) - 開始

ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl : onRowSets(...) - グラフを構築

ChartReportItemPresentationImpl.log.WritingFile={1} の {0} ファイルに書き込み中です。

ChartReportItemPresentationImpl.exception.tmpPngFileCreation=一時ファイル (PNG) の作成

ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=プレゼンテーションで使用する範囲 : {0}

ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) - グラフを描画

ChartReportItemPresentationImpl.exception.inputStreamCreation=入力ストリームの作成

ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) - 失敗

ChartReportItemPresentationImpl.exception.UnexpectedError=予期しないエラー

ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) - 終了

ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) - 開始

ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) - 終了

ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp={1} から一時ファイル {0} を削除しました。

ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) - 終了

ChartWithoutAxesImpl.exception.3DNotSupported=ChartWithoutAxes では 3D を使用できません。

ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) - 開始

ChartReportItemPresentationImpl.log.CouldNotDeleteTemp={1} に作成した一時ファイル {0} を削除できませんでした。

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) - 例外

ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) - 終了

ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) - 開始

ChartReportItemQueryImpl.exception.getReportQueries=レポートクエリの取得

ChartReportItemQueryImpl.log.UnableToLocate=グラフオブジェクトのレポート項目ラッパーが見つかりません。

ChartReportItemImpl.log.validate=検証中 (...)

ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=軸のないグラフには、'置き換え後' ステータスを設定できません。

ChartReportItemImpl.log.UnexpectedChoiceName=予期しない選択名が見つかりました :

ChartReportItemImpl.log.RequestForPropertyDefn=モデルが作成される前に受け取ったプロパティの定義をリクエストします。

ChartReportItemImpl.log.RequestForScriptPropertyDefn=スクリプトプロパティの定義のリクエスト

ChartReportItemImpl.log.checkProperty=CheckProperty(...) - 値 {1} を持つ {0}

ChartReportItemImpl.log.setProperty=SetProperty(...) - 値 {1} を持つ {0}

QueryHelper.exception.UnexpectedNull=拡張フレームワークによって予期しない 'null' クエリ定義が指定されました - レポートエンジン / 生成

QueryHelper.Text.CategroySeries=カテゴリ系列

QueryHelper.Text.ValueSeries=値系列

QueryHelper.Text.XSeries=X 系列

QueryHelper.Text.YSeries=Y 系列

QueryHelper.NoDataDefinitionFor={0} には、データ定義エントリがありません。

QueryHelper.dataDefnUndefined={0} のデータ定義エントリが指定されていません。

QueryHelper.InconsitentDataTypesForAxis=同じ Y 軸にあるすべてのデータ定義には同じデータ型を指定してください。

QueryHelper.InconsitentDataTypesForValueSeries=値系列のすべてのデータ定義には同じデータ型を指定してください。

ChartElementCommandImpl.editChart=グラフの編集

ChartElementCommandImpl.setProperty.chart.dimension=ディメンジョンの設定

ChartElementCommandImpl.setProperty.chart.instance=グラフのモデルを設定

ChartElementCommandImpl.setProperty.plot.transposed=置き換え後の設定

ChartElementCommandImpl.setProperty.script=グラフスクリプトの編集

ChartElementCommandImpl.setProperty.onRender=グラフスクリプトの編集

ChartImpl.error.DimensionUnitNotSupported=Chart Simple API ではディメンジョンの単位 ({0}) を使用できません。

################################################
# Display names for report model extension 
################################################
Element.Chart=グラフ

Element.Chart.xmlRepresentation=XML モデル

Element.Chart.outputFormat=出力書式

Element.Chart.action=アクション

Element.Chart.altText=代替テキスト

Element.Chart.altTextID=代替テキストキー


choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=2D 奥行き付き

choice.chart.dimension.three_dimensional=3D
property.category.general=全般

property.category.types=型

property.label.title.value=タイトル :

property.label.title.font.rotation=タイトルの回転 :

property.label.legend.position=凡例の位置 :

property.label.legend.anchor=凡例のアンカー :

property.label.chart.dimension=ディメンション:

property.label.chart.plot.transposed=置き換え後

property.script=スクリプト

property.onRender=onRender

exception.no.cube.edge=データキューブのカーソルにエッジが定義されていません。クエリ式が正しいことを確認してください。

exception.script.syntaxError=スクリプトの構文エラー : {0}

