ChartCubeQueryHelper.Error.MustBindCube=Le graphique doit lier un cube à des données d'alimentation.

ChartReportItemPresentationImpl.error.NoData=Le jeu de données lié au graphique n'a renvoyé aucune ligne.

ChartReportItemPresentationImpl.error.InvalidCubeBinding=Le jeu de données utilisé par ce graphique a été modifié. Le rendu de ce tableau ne peut plus être effectué.

ChartReportItemPresentationImpl.log.UnableToLocateWrapper=Impossible de localiser le wrapper d'élément d'état pour l'objet de graphique.

ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl: onRowSets(...) - début

ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl: onRowSets(...) - création du graphique

ChartReportItemPresentationImpl.log.WritingFile=Ecriture du fichier {0} sous {1}

ChartReportItemPresentationImpl.exception.tmpPngFileCreation=Création du fichier PNG temporaire

ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=La présentation utilise les limites : {0}

ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) - rendu du graphique

ChartReportItemPresentationImpl.exception.inputStreamCreation=création du flux d'entrée

ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) - échec

ChartReportItemPresentationImpl.exception.UnexpectedError=Erreur inattendue

ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) - fin

ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) - début

ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) - fin

ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp=Le fichier {0} temporaire sous {1} a été supprimé.

ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) - fin

ChartWithoutAxesImpl.exception.3DNotSupported=3D n'est pas pris en charge par ChartWithoutAxes.

ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) - début

ChartReportItemPresentationImpl.log.CouldNotDeleteTemp=Impossible de supprimer le fichier {0} temporaire créé sous {1}.

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) - exception

ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) - fin

ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) - début

ChartReportItemQueryImpl.exception.getReportQueries=Récupération des requêtes d'état

ChartReportItemQueryImpl.log.UnableToLocate=Impossible de localiser le wrapper d'élément d'état pour l'objet de graphique.

ChartReportItemImpl.log.validate=validation(...)

ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=Impossible de définir l'état 'transposé' sur un graphique sans axes.

ChartReportItemImpl.log.UnexpectedChoiceName=Détection d'un nom de choix inattendu :

ChartReportItemImpl.log.RequestForPropertyDefn=Réception de la requête concernant les définitions de propriétés avant la création du modèle.

ChartReportItemImpl.log.RequestForScriptPropertyDefn=Requête de définition de la propriété du script.

ChartReportItemImpl.log.checkProperty=CheckProperty(...) - {0} avec la valeur {1}

ChartReportItemImpl.log.setProperty=SetProperty(...) - {0} avec la valeur {1}

QueryHelper.exception.UnexpectedNull=Définition de requête 'nulle' inattendue fournie par la structure d'extension - moteur/génération d'états.

QueryHelper.Text.CategroySeries=Série de catégories

QueryHelper.Text.ValueSeries=Série de valeurs

QueryHelper.Text.XSeries=Série X

QueryHelper.Text.YSeries=Série Y

QueryHelper.NoDataDefinitionFor=Aucune entrée de définition de données n'existe pour {0}.

QueryHelper.dataDefnUndefined=Une entrée de définition de données pour {0} n'est pas définie.

QueryHelper.InconsitentDataTypesForAxis=Toutes les définitions de données sur un même axe vertical doivent être du même type.

QueryHelper.InconsitentDataTypesForValueSeries=Toutes les définitions de données sur les séries de valeur doivent être du même type.

ChartElementCommandImpl.editChart=Modifier le graphique

ChartElementCommandImpl.setProperty.chart.dimension=Définir la dimension

ChartElementCommandImpl.setProperty.chart.instance=Définir le modèle de graphique

ChartElementCommandImpl.setProperty.plot.transposed=Définir l'état Transposé

ChartElementCommandImpl.setProperty.script=Modifier le script du graphique

ChartElementCommandImpl.setProperty.onRender=Modifier le script du graphique

ChartImpl.error.DimensionUnitNotSupported=L''unité de dimension ({0}) n''est pas prise en charge par l''API graphique simple

################################################
# Display names for report model extension 
################################################
Element.Chart=Graphique

Element.Chart.xmlRepresentation=Modèle XML

Element.Chart.outputFormat=Format de sortie

Element.Chart.action=Action

Element.Chart.altText=Autre texte

Element.Chart.altTextID=Clé d'autre texte


choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=Profondeur 2D

choice.chart.dimension.three_dimensional=3D
property.category.general=Général

property.category.types=Types

property.label.title.value=Titre :

property.label.title.font.rotation=Rotation du titre :

property.label.legend.position=Position de la légende :

property.label.legend.anchor=Ancre de la légende :

property.label.chart.dimension=Dimension :

property.label.chart.plot.transposed=Transposé

property.script=Script

property.onRender=onRender

exception.no.cube.edge=Le curseur du cube de données n'a pas de bord. Vérifiez que les expressions des requêtes sont correctes.

exception.script.syntaxError=Erreur de syntaxe de script : {0}

