/* Generated By:JavaCC: Do not edit this line. CssParserConstants.java */
package  org.eclipse.birt.report.engine.executor.css;

public interface CssParserConstants {

  int EOF = 0;
  int S = 1;
  int INHERIT = 2;
  int CDO = 3;
  int CDC = 4;
  int LBRACE = 5;
  int RBRACE = 6;
  int DASHMATCH = 7;
  int INCLUDES = 8;
  int PREFIXMATCH = 9;
  int SUFFIXMATCH = 10;
  int SUBSTRINGMATCH = 11;
  int TILDE = 12;
  int EQ = 13;
  int PLUS = 14;
  int MINUS = 15;
  int COMMA = 16;
  int SEMICOLON = 17;
  int PRECEDES = 18;
  int DIV = 19;
  int LBRACKET = 20;
  int RBRACKET = 21;
  int ANY = 22;
  int DOT = 23;
  int LPARAN = 24;
  int RPARAN = 25;
  int COLON = 26;
  int AND = 27;
  int MEDIARESTRICTOR = 28;
  int NONASCII = 29;
  int H = 30;
  int UNICODE = 31;
  int ESCAPE = 32;
  int NMSTART = 33;
  int NMCHAR = 34;
  int STRINGCHAR = 35;
  int D = 36;
  int NAME = 37;
  int STRING = 38;
  int NUMBER = 39;
  int _URL = 40;
  int URL = 41;
  int PERCENTAGE = 42;
  int LENGTH = 43;
  int EMS = 44;
  int EXS = 45;
  int ANGLE = 46;
  int TIME = 47;
  int FREQ = 48;
  int RESOLUTION = 49;
  int DATE = 50;
  int ABSOLUTE_SIZE = 51;
  int RELATIVE_SIZE = 52;
  int COLOR = 53;
  int NORMAL = 54;
  int AUTO = 55;
  int FONT_TAG = 56;
  int FONT_VAL = 57;
  int FONT_STYLE = 58;
  int FONT_VARIANT = 59;
  int FONT_WEIGHT = 60;
  int BACKGROUND_TAG = 61;
  int BACKGROUND_REPEAT = 62;
  int BACKGROUND_ATTACHMENT = 63;
  int BACKGROUND_POSITION = 64;
  int BORDER_TAG = 65;
  int BORDER_WIDTH_TAG = 66;
  int BORDER_STYLE_TAG = 67;
  int BORDER_TOP_TAG = 68;
  int BORDER_RIGHT_TAG = 69;
  int BORDER_BOTTOM_TAG = 70;
  int BORDER_LEFT_TAG = 71;
  int BORDER_STYLE = 72;
  int BORDER_WIDTH = 73;
  int MARGIN_TAG = 74;
  int PADDING_TAG = 75;
  int IDENT = 76;
  int DIMEN = 77;
  int HASH = 78;
  int RANGE0 = 79;
  int RANGE1 = 80;
  int RANGE2 = 81;
  int RANGE3 = 82;
  int RANGE4 = 83;
  int RANGE5 = 84;
  int RANGE6 = 85;
  int RANGE = 86;
  int UNI = 87;
  int UNICODERANGE = 88;
  int FUNCTION = 89;
  int UNKNOWN = 90;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"inherit\"",
    "\"<!--\"",
    "\"-->\"",
    "\"{\"",
    "\"}\"",
    "\"|=\"",
    "\"~=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"~\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "<AND>",
    "<MEDIARESTRICTOR>",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "<STRING>",
    "<NUMBER>",
    "<_URL>",
    "<URL>",
    "<PERCENTAGE>",
    "<LENGTH>",
    "<EMS>",
    "<EXS>",
    "<ANGLE>",
    "<TIME>",
    "<FREQ>",
    "<RESOLUTION>",
    "<DATE>",
    "<ABSOLUTE_SIZE>",
    "<RELATIVE_SIZE>",
    "<COLOR>",
    "\"normal\"",
    "\"auto\"",
    "\"font\"",
    "<FONT_VAL>",
    "<FONT_STYLE>",
    "\"small-caps\"",
    "<FONT_WEIGHT>",
    "\"background\"",
    "<BACKGROUND_REPEAT>",
    "<BACKGROUND_ATTACHMENT>",
    "<BACKGROUND_POSITION>",
    "\"border\"",
    "\"border-width\"",
    "\"border-style\"",
    "\"border-top\"",
    "\"border-right\"",
    "\"border-bottom\"",
    "\"border-left\"",
    "<BORDER_STYLE>",
    "<BORDER_WIDTH>",
    "\"margin\"",
    "\"padding\"",
    "<IDENT>",
    "<DIMEN>",
    "<HASH>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<FUNCTION>",
    "<UNKNOWN>",
  };

}
