exception.base.orthogonal.null.datadefinition=La expresión de definición de datos indicada no es válida.

exception.dataset.stockseries=Las entradas de datos enlazadas a la serie de cotizaciones están incompletas. Deben contener cuatro valores: Alto, Bajo, Apertura y Cierre.

exception.dataset.null.stockentry=La entrada de datos tiene un valor nulo o no numérico que no es válido

exception.dataset.invalid.ganttentry=La entrada de datos tiene un valor de tipo no válido.

exception.empty.dataset=Se ha encontrado un conjunto de datos vacío

exception.empty.palette=La paleta asociada con la serie {0} está vacía

exception.null.values=No se pueden definir valores "todo nulo" en un dibujo

exception.unknown.datatype=El conjunto de datos utilizado por el diagrama no es válido

exception.dataset.booleantype=No se permite el tipo booleano

exception.undefined.riser=El tipo de ganancia no está definido en la serie de barras {0}

exception.stock.entry.invalid.highlow=La entrada de cotización no es válida. {0} alto es menor que {1} bajo.

exception.stock.entry.invalid.high=La entrada de cotización no es válida. {0} alto es menor que {1} apertura/cierre.

exception.stock.entry.invalid.low=La entrada de cotización no es válida. {0} bajo es mayor que {1} apertura/cierre.

exception.series.visibility=La visibilidad no se ha ajustado de forma explícita para la serie {0}

exception.xvalue.scale.bars=Las barras podrían no procesarse en una escala de valores

exception.xvalue.scale.lines=Las líneas podrían no procesarse en una escala de valores

exception.xvalue.scale.stock=Las velas podrían no procesarse en una escala de valores

exception.invalid.tick.style.dial=Se ha especificado un estilo de marca no válido para la serie de cuadrante.

exception.unknown.custom.dataset=No es posible descifrar el tipo de datos personalizado {0} definido por {1}

exception.curve.visibility.unset=La visibilidad debe ajustarse en los atributos de línea para la curva

exception.visibility.line.unset=La visibilidad debe ajustarse en los atributos de línea para la línea

exception.cannot.parse.sample=No es posible analizar los valores de datos de muestra que se van a asociar con el conjunto de datos de serie

exception.no.stack.percent.3D.chart=El diagrama de 3D no admite las funciones de pila y porcentaje.

exception.dial.dimension=La serie de cuadrante no admite el valor ''{0}''.

exception.pie.dimension=La serie circular no admite el valor ''{0}''.

exception.scatter.dimension=La serie de dispersión no admite el valor ''{0}''.

exception.stock.dimension=No se puede procesar una serie de cotizaciones de acciones usando la dimensión {0}

exception.multi.orthogonal.3D.not.supported=El gráfico 3D no admite varios ejes de valor.

exception.scatter.3D.not.supported=El gráfico 3D no admite el eje de categoría dispersa.

exception.no.transposed.3D.chart=El gráfico 3D no admite la transposición.

exception.no.transposed.stock.chart=El diagrama de cotización no admite la transposición.

exception.no.transposed.gantt.chart=El diagrama de Gantt sólo admite la transposición.

exception.3D.points.length.less.than.3=La longitud de la lista de puntos para un evento de procesamiento 3D es al menos 3 (>=3).

exception.empty.icon.list=La lista de paleta de iconos para el marcador está vacía.

info.sample.formats=Ejemplos\nNumérico: 1,2,3\nFecha: 26/01/05,27/01/05,28/01/05\nTexto: 'a,b,c'\ncon todos los valores múltiples separados por comas.

info.render.series={0}: renderSeries() [{1}/{2}]
info.stock.sample.format=Ejemplo: H2.30 L4.50 O1.53 C7.01, H5.4 L3.5 O2.9 C6.7

info.datapoint.BubbleValue=Valor de la burbuja

info.datapoint.BubbleSize=Tamaño de la burbuja

info.datapoint.PositiveValue=Valor positivo

info.datapoint.NegativeValue=Valor negativo

info.datapoint.GanttStartDate=Fecha de inicio

info.datapoint.GanttEndDate=Fecha de finalización

info.datapoint.GanttDecorationLabel=Etiqueta de tarea

info.datapoint.High=Alta

info.datapoint.Low=Baja

info.datapoint.Open=Abrir

info.datapoint.Close=Cerrar

exception.missing.series.for.palette.index=No es posible localizar la serie {0} en la definición de serie {1} necesaria para procesar el índice de paleta

exception.pie.negative.dataset.values=Una serie circular no puede contener valores negativos en su conjunto de datos

exception.stock.lineattr.visibility=Los atributos de línea del elemento de cotización de acciones deben ajustarse como visibles

exception.legend.graphic.unknown.riser=No es posible procesar un gráfico de leyenda para un tipo de ganancia desconocido {0}

exception.unspecified.visible.series.title=No se ha especificado la posición del título de la serie para un título de serie visible

exception.unspecified.riser.type=Se ha especificado un tipo de ganancia desconocido {0}.

exception.invalid.data.point.position.scatter=La posición de la etiqueta del punto de datos {0} no se admite al procesarse en una serie de dispersión. Los valores permitidos son ARRIBA, ABAJO, IZQUIERDA y DERECHA.

exception.invalid.data.point.position.bubble=La posición de la etiqueta del punto de datos {0} no se admite al procesarse en una serie de burbujas. Los valores permitidos son ABOVE, BELOW, LEFT y RIGHT.

exception.invalid.data.point.outbound.bubble=No hay ninguna burbuja en el intervalo del área de dibujo. Compruebe la escala del eje.

exception.illegal.pie.series.title.position=Se ha especificado un valor no válido para la posición del título de serie = {0}

exception.illegal.datapoint.position.bar=La posición de la etiqueta de punto de datos {0} no se admite al procesarse en una serie de barras. Los valores permitidos son EXTERIOR e INTERIOR.

exception.illegal.datapoint.position.line=La posición de la etiqueta del punto de datos {0} no se admite al procesarse en una serie de líneas. Los valores permitidos son ARRIBA, ABAJO, IZQUIERDA y DERECHA.

exception.illegal.datapoint.position.stock=La posición de la etiqueta del punto de datos {0} no se admite al procesarse en una serie de cotización de acciones. Los valores permitidos son ABOVE, BELOW, LEFT y RIGHT.

exception.unspecified.datapoint.visibility.pie=No se ha ajustado la visibilidad del punto de datos para la serie {0}

exception.invalid.datapoint.position.pie=La posición de la etiqueta del punto de datos {0} no es válida

exception.invalid.datapoint.dial=No se pueden dibujar series métricas con puntos de datos nulos o no numéricos.

exception.unspecified.pie.series.title.visibility=No se ha ajustado la visibilidad del título de serie del modelo para {0}

exception.unspecified.marker.linestyle.visibility=No se ha ajustado la visibilidad del estilo de línea de marcador

exception.unsupported.aggregate.function.input=La función de agregación {0} ha encontrado un tipo de datos no admitido

exception.illegal.datapoint.position.bar3d=El diagrama de barras tridimensional no admite etiquetas de serie en su interior.

Irr.AggregateFunction.Parameters.Label.Intrate=Intrate

Mirr.AggregateFunction.Parameters.Label.FinanceRate=Finance Rate

Mirr.AggregateFunction.Parameters.Label.ReinvestmentRate=Reinvestment Rate

Npv.AggregateFunction.Parameters.Label.Rate=Rate

Percentile.AggregateFunction.Parameters.Label.Percentage=Percentage

Quartile.AggregateFunction.Parameters.Label.Quart=Quart

WeightedAverage.AggregateFunction.Parameters.Label.Weight=Weight

MovingAverage.AggregateFunction.Parameters.Label.Window=Window

RunningNpv.AggregateFunction.Parameters.Label.Rate=Rate

Rank.AggregateFunction.Parameters.Label.Ascending=Ascendente

Top.AggregateFunction.Parameters.Label.N=Top n

TopPercent.AggregateFunction.Parameters.Label.Percentage=Percentage

Bottom.AggregateFunction.Parameters.Label.N=Bottom n

BottomPercent.AggregateFunction.Parameters.Label.Percentage=Percentage

DataSetProcessorImpl_exception.dataset.receivednumeric=El tipo de datos recibidos debe ser numérico.
