exception.base.orthogonal.null.datadefinition=지정한 데이터 정의 식이 잘못되었습니다.

exception.dataset.stockseries=주식형 계열에 바인딩된 데이터 항목이 불완전합니다. 이 항목에는 높음, 낮음, 열기 및 닫기 값이 있어야 합니다.

exception.dataset.null.stockentry=데이터 항목에 잘못된 널(null) 값이 있거나 숫자가 아닌 값이 있습니다.

exception.dataset.invalid.ganttentry=데이터 항목에 잘못된 형식의 값이 있습니다.

exception.empty.dataset=빈 데이터 집합이 있습니다.

exception.empty.palette=계열 {0}과(와) 연결된 색상표가 비어 있습니다.

exception.null.values=플롯에서 '모든 널(null)' 값을 정의할 수 없습니다.

exception.unknown.datatype=차트에서 사용된 데이터 집합이 잘못되었습니다.

exception.dataset.booleantype=부울 형식은 허용되지 않습니다.

exception.undefined.riser=막대형 계열 {0}에서 계단 형식이 정의되지 않았습니다.

exception.stock.entry.invalid.highlow=주식 항목이 잘못되었습니다. 고가 {0}이(가) 저가{1}보다 작습니다.

exception.stock.entry.invalid.high=주식 항목이 잘못되었습니다. 고가 {0}이(가) 시가/종가 {1}보다 작습니다.

exception.stock.entry.invalid.low=주식 항목이 잘못되었습니다. 저가 {0}이(가) 시가/종가 {1}보다 큽니다.

exception.series.visibility=계열 {0}에 대한 표시 유형이 명확히 설정되지 않았습니다.

exception.xvalue.scale.bars=막대를 값 배율로 렌더링할 수 없습니다.

exception.xvalue.scale.lines=선을 값 배율로 렌더링할 수 없습니다.

exception.xvalue.scale.stock=원통형을 값 배율로 렌더링할 수 없습니다.

exception.invalid.tick.style.dial=다이얼 시리즈에 지정된 틱 스타일이 잘못되었습니다.

exception.unknown.custom.dataset={1}에서 정의된 사용자 지정 데이터 집합 {0}을(를) 암호 해독할 수 없습니다.

exception.curve.visibility.unset=곡선의 선 특성에 대한 표시 유형을 설정해야 합니다.

exception.visibility.line.unset=선의 선 특성에 대한 표시 유형을 설정해야 합니다.

exception.cannot.parse.sample=계열 데이터 집합과 연결할 샘플 데이터 값을 구문 분석할 수 없습니다.

exception.no.stack.percent.3D.chart=3D 차트에 대해 스택 및 퍼센트 기능이 지원되지 않습니다.

exception.dial.dimension=''{0}''은(는) 다이얼 시리즈에서 지원되지 않습니다.

exception.pie.dimension=''{0}''은(는) 원형 시리즈에서 지원되지 않습니다.

exception.scatter.dimension=''{0}''은(는) 분산형 시리즈에서 지원되지 않습니다.

exception.stock.dimension=차원 {0}을(를) 사용하여 주식형 계열을 렌더링할 수 없습니다.

exception.multi.orthogonal.3D.not.supported=다중 값 축은 3D 차트에서 지원되지 않습니다.

exception.scatter.3D.not.supported=분산형 범주 축은 3D 차트에서 지원되지 않습니다.

exception.no.transposed.3D.chart=전위는 3D 차트에서 지원되지 않습니다.

exception.no.transposed.stock.chart=전위는 주식형 차트에서 지원되지 않습니다.

exception.no.transposed.gantt.chart=전위는 간트 차트에서만 지원됩니다.

exception.3D.points.length.less.than.3=3D 렌더링 이벤트에 대한 포인트 목록 길이는 3 이상이어야 합니다(>=3).

exception.empty.icon.list=표지에 대한 아이콘 색상표 목록이 비어 있습니다.

info.sample.formats=예\n숫자: 1,2,3\n날짜: 05-01-26,05-01-27,05-01-28\n텍스트: 'a,b,c'\n복수 값은 모두 쉼표로 분리됩니다.

info.render.series={0}: renderSeries() [{1}/{2}]
info.stock.sample.format=예: H2.30 L4.50 O1.53 C7.01, H5.4 L3.5 O2.9 C6.7

info.datapoint.BubbleValue=거품 값

info.datapoint.BubbleSize=거품 크기

info.datapoint.PositiveValue=양수 값

info.datapoint.NegativeValue=음수 값

info.datapoint.GanttStartDate=시작 날짜

info.datapoint.GanttEndDate=종료 날짜

info.datapoint.GanttDecorationLabel=작업 레이블

info.datapoint.High=높음

info.datapoint.Low=낮음

info.datapoint.Open=열기

info.datapoint.Close=닫기

exception.missing.series.for.palette.index=색상표 인덱스를 계산하는 데 필요한 대로 계열 정의 {1}에서 계열 {0}을(를) 찾을 수 없습니다.

exception.pie.negative.dataset.values=원형 계열의 데이터 집합에는 음수 값이 포함될 수 없습니다.

exception.stock.lineattr.visibility=주식형 요소의 선 특성은 표시로 설정되어야 합니다.

exception.legend.graphic.unknown.riser=알 수 없는 계단 형식 {0}에 대한 범례 그래픽을 렌더링할 수 없습니다.

exception.unspecified.visible.series.title=표시되는 계열 제목에 대한 계열 제목 위치가 지정되지 않았습니다.

exception.unspecified.riser.type=알 수 없는 계단 형식 {0}이(가) 지정되었습니다.

exception.invalid.data.point.position.scatter=분산형 계열에서 렌더링할 때는 데이터 요소 레이블 위치 {0}이(가) 지원되지 않습니다. 허용되는 값은 ABOVE, BELOW, LEFT 및 RIGHT입니다.

exception.invalid.data.point.position.bubble=거품형 계열에서 렌더링할 때는 데이터 요소 레이블 위치 {0}이(가) 지원되지 않습니다. 허용되는 값은 ABOVE, BELOW, LEFT 및 RIGHT입니다.

exception.invalid.data.point.outbound.bubble=어떤 거품도 플롯 영역에 있지 않습니다. 축 배율을 확인하십시오.

exception.illegal.pie.series.title.position=계열 제목 위치 = {0}에 잘못된 값이 지정되었습니다.

exception.illegal.datapoint.position.bar=막대형 계열에서 렌더링할 때는 데이터 요소 레이블 위치 {0}이(가) 지원되지 않습니다. 허용되는 값은 OUTSIDE 및 INSIDE입니다.

exception.illegal.datapoint.position.line=선형 계열에서 렌더링할 때는 데이터 요소 레이블 위치 {0}이(가) 지원되지 않습니다. 허용되는 값은 ABOVE, BELOW, LEFT 및 RIGHT입니다.

exception.illegal.datapoint.position.stock=주식형 계열에서 렌더링할 때는 데이터 요소 레이블 위치 {0}이(가) 지원되지 않습니다. 허용되는 값은 ABOVE, BELOW, LEFT 및 RIGHT입니다.

exception.unspecified.datapoint.visibility.pie=계열 {0}에 대한 데이터 요소 표시 유형이 설정되지 않았습니다.

exception.invalid.datapoint.position.pie=데이터 요소 레이블 위치 {0}이(가) 잘못되었습니다.

exception.invalid.datapoint.dial=널(null) 또는 숫자가 아닌 데이터 요소로 측정기 계열을 그릴 수 없습니다.

exception.unspecified.pie.series.title.visibility={0}의 모델에 계열 제목 표시 유형이 설정되지 않았습니다.

exception.unspecified.marker.linestyle.visibility=표지선 스타일 표시 유형이 설정되지 않았습니다.

exception.unsupported.aggregate.function.input=집계 함수 {0}에 지원되지 않는 데이터 형식이 있습니다.

exception.illegal.datapoint.position.bar3d=3D 막대 차트는 차트 내에 계열 레이블을 사용할 수 없습니다.

Irr.AggregateFunction.Parameters.Label.Intrate=INTRATE

Mirr.AggregateFunction.Parameters.Label.FinanceRate=금융 금리

Mirr.AggregateFunction.Parameters.Label.ReinvestmentRate=재투자 금리

Npv.AggregateFunction.Parameters.Label.Rate=금리

Percentile.AggregateFunction.Parameters.Label.Percentage=백분율

Quartile.AggregateFunction.Parameters.Label.Quart=4분위수

WeightedAverage.AggregateFunction.Parameters.Label.Weight=가중치

MovingAverage.AggregateFunction.Parameters.Label.Window=창

RunningNpv.AggregateFunction.Parameters.Label.Rate=금리

Rank.AggregateFunction.Parameters.Label.Ascending=오름차순

Top.AggregateFunction.Parameters.Label.N=상위 n

TopPercent.AggregateFunction.Parameters.Label.Percentage=백분율

Bottom.AggregateFunction.Parameters.Label.N=하위 n

BottomPercent.AggregateFunction.Parameters.Label.Percentage=백분율

DataSetProcessorImpl_exception.dataset.receivednumeric=받은 데이터 형식은 숫자여야 합니다.
