exception.base.orthogonal.null.datadefinition=Der angegebene Datendefinitionsausdruck ist ungültig.

exception.dataset.stockseries=Die an die Kursreihe gebundenen Dateneinträge sind unvollständig. Sie müssen vier Werte enthalten: Hoch, Niedrig, Öffnen und Schließen.

exception.dataset.null.stockentry=Der Dateneintrag hat einen ungültigen Null- oder Nichtzahl-Wert.

exception.dataset.invalid.ganttentry=Der Dateneintrag hat einen ungültigen Wert.

exception.empty.dataset=Leeren Datensatz gefunden

exception.empty.palette=Die mit der Datenreihe {0} verknüpfte Palette ist leer

exception.null.values='Alle Null'-Werte in einem Diagramm können nicht definiert werden

exception.unknown.datatype=Der vom Diagramm verwendete Datensatz ist ungültig

exception.dataset.booleantype=Der Boolesche Typ ist nicht zulässig

exception.undefined.riser=Der Anstiegstyp in Balkenreihe {0} ist nicht definiert

exception.stock.entry.invalid.highlow=Kurseintrag ist ungültig. "Hoch" {0} ist kleiner als "Niedrig" {1}.

exception.stock.entry.invalid.high=Kurseintrag ist ungültig. "Hoch" {0} ist kleiner als "Öffnen/Schließen" {1}.

exception.stock.entry.invalid.low=Kurseintrag ist ungültig. "Niedrig" {0} ist größer als "Öffnen/Schließen" {1}.

exception.series.visibility=Die Sichtbarkeit ist für Datenreihe {0} nicht ausdrücklich festgelegt

exception.xvalue.scale.bars=Balken können auf einer Werteskala nicht gerendert werden

exception.xvalue.scale.lines=Linien können auf einer Werteskala nicht gerendert werden

exception.xvalue.scale.stock=Candlestick-Kurse können auf einer Werteskala nicht gerendert werden

exception.invalid.tick.style.dial=Für die Tachometer-Datenreihe ist ein ungültiger Skalenstil angegeben.

exception.unknown.custom.dataset=Der durch {1} definierte benutzerdefinierte Datensatz {0} kann nicht entschlüsselt werden

exception.curve.visibility.unset=Die Sichtbarkeit muss für die Linienattribute der Kurve gesetzt werden

exception.visibility.line.unset=Die Sichtbarkeit muss für die Linienattribute der Linie gesetzt werden

exception.cannot.parse.sample=Die Beispieldatenwerte, die mit dem Datenreihen-Datensatz verknüpft werden sollen, können nicht analysiert werden

exception.no.stack.percent.3D.chart=Stapel- und Prozentfunktion werden in 3D-Diagrammen nicht unterstützt.

exception.dial.dimension="{0}" wird von der Tachometer-Datenreihe nicht unterstützt.

exception.pie.dimension="{0}" wird von der Kreisdiagramm-Datenreihe nicht unterstützt.

exception.scatter.dimension="{0}" wird von der Punktdiagramm-Datenreihe nicht unterstützt.

exception.stock.dimension=Kursreihe kann nicht mit Dimension {0} gerendert werden

exception.multi.orthogonal.3D.not.supported=3D-Diagramme unterstützen nur eine Wertachse.

exception.scatter.3D.not.supported=Punktdiagramm-Kategorieachse wird von 3D-Diagrammen nicht unterstützt.

exception.no.transposed.3D.chart=Transposition wird von 3D-Diagrammen nicht unterstützt.

exception.no.transposed.stock.chart=Transposition wird von Kursdiagramm nicht unterstützt.

exception.no.transposed.gantt.chart=Gantt-Diagramm unterstützt nur Transposition.

exception.3D.points.length.less.than.3=Die Länge der Punkteliste für das 3D-Render-Ereignis muss mindestens 3(>=3) betragen.

exception.empty.icon.list=Die Symbol-Palettenliste für Markierungen enthält keine Elemente.

info.sample.formats=Beispiele\nNumerisch: 1,2,3\nDatum: 01/26/2005,01/27/2005,01/28/2005\nText: 'a,b,c',\nmehrere Werte jeweils durch Komma getrennt.

info.render.series={0}: renderSeries() [{1}/{2}]
info.stock.sample.format=Beispiel: H2.30 L4.50 O1.53 C7.01, H5.4 L3.5 O2.9 C6.7

info.datapoint.BubbleValue=Blasenwert

info.datapoint.BubbleSize=Blasengröße

info.datapoint.PositiveValue=Positiver Wert

info.datapoint.NegativeValue=Negativer Wert

info.datapoint.GanttStartDate=Startdatum

info.datapoint.GanttEndDate=Enddatum

info.datapoint.GanttDecorationLabel=Beschriftung für Aufgabe

info.datapoint.High=Hoch

info.datapoint.Low=Tief

info.datapoint.Open=Öffnen

info.datapoint.Close=Schließ.en

exception.missing.series.for.palette.index=Datenreihe {0}, die zur Berechnung des Palettenindex erforderlich ist, kann in Datenreihendefinition {1} nicht gefunden werden

exception.pie.negative.dataset.values=Eine Kreisdiagramm-Datenreihe darf keine negativen Werte im Datensatz enthalten

exception.stock.lineattr.visibility=Die Linienattribute des Kurselements müssen als sichtbar festgelegt werden

exception.legend.graphic.unknown.riser=Legendengrafik für unbekannten Anstiegstyp {0} kann nicht gerendert werden

exception.unspecified.visible.series.title=Die Titelposition der Datenreihe wurde für einen sichtbaren Datenreihentitel nicht festgelegt

exception.unspecified.riser.type=Unbekannter Anstiegstyp {0} festgelegt.

exception.invalid.data.point.position.scatter=Datenpunkt-Beschriftungsposition {0} wird beim Rendern von Punktdatenreihen nicht unterstützt. Gültige Werte sind ABOVE, BELOW, LEFT und RIGHT.

exception.invalid.data.point.position.bubble=Datenpunkt-Beschriftungsposition {0} wird beim Rendern von Blasen-Reihen nicht unterstützt. Gültige Werte sind ABOVE, BELOW, LEFT und RIGHT.

exception.invalid.data.point.outbound.bubble=Es befindet sich keine Blase im Bereich der Diagrammfläche. Überprüfen Sie die Achsenskala.

exception.illegal.pie.series.title.position=Ungültiger Wert für Titelposition = {0} der Datenreihe festgelegt

exception.illegal.datapoint.position.bar=Datenpunkt-Beschriftungsposition {0} wird beim Rendern von Balkendatenreihen nicht unterstützt. Gültige Werte sind OUTSIDE und INSIDE.

exception.illegal.datapoint.position.line=Datenpunkt-Beschriftungsposition {0} wird beim Rendern von Liniendatenreihen nicht unterstützt. Gültige Werte sind ABOVE, BELOW, LEFT und RIGHT

exception.illegal.datapoint.position.stock=Datenpunkt-Beschriftungsposition {0} wird beim Rendern von Kursreihen nicht unterstützt. Gültige Werte sind ABOVE, BELOW, LEFT und RIGHT.

exception.unspecified.datapoint.visibility.pie=Datenpunkt-Sichtbarkeit für Datenreihe {0} nicht festgelegt

exception.invalid.datapoint.position.pie=Datenpunkt-Beschriftungsposition {0} ist ungültig

exception.invalid.datapoint.dial=Zum Zeichnen einer Messwert-Datenreihe ist ein numerischer Datenpunkt erforderlich. Dieser darf nicht Null lauten.

exception.unspecified.pie.series.title.visibility=Die Sichtbarkeit des Datenreihentitels im Modell wurde für {0} nicht festgelegt

exception.unspecified.marker.linestyle.visibility=Die Sichtbarkeit des Markierungslinienstils wurde nicht festgelegt

exception.unsupported.aggregate.function.input=Bei der Aggregatfunktion {0} wurde ein nicht unterstützter Datentyp gefunden

exception.illegal.datapoint.position.bar3d=In 3D-Balkendiagrammen ist keine Datenreihenbeschriftung innerhalb der Balken möglich.

Irr.AggregateFunction.Parameters.Label.Intrate=Intrate

Mirr.AggregateFunction.Parameters.Label.FinanceRate=Finance Rate

Mirr.AggregateFunction.Parameters.Label.ReinvestmentRate=Reinvestment Rate

Npv.AggregateFunction.Parameters.Label.Rate=Rate

Percentile.AggregateFunction.Parameters.Label.Percentage=Prozentsatz

Quartile.AggregateFunction.Parameters.Label.Quart=Quart

WeightedAverage.AggregateFunction.Parameters.Label.Weight=Gewichtung

MovingAverage.AggregateFunction.Parameters.Label.Window=Fenster

RunningNpv.AggregateFunction.Parameters.Label.Rate=Rate

Rank.AggregateFunction.Parameters.Label.Ascending=Aufsteigend

Top.AggregateFunction.Parameters.Label.N=Erste n

TopPercent.AggregateFunction.Parameters.Label.Percentage=Prozentsatz

Bottom.AggregateFunction.Parameters.Label.N=Letzte n

BottomPercent.AggregateFunction.Parameters.Label.Percentage=Prozentsatz

DataSetProcessorImpl_exception.dataset.receivednumeric=Der Typ des erhaltenen Datentyps muss numerisch sein.
