# Localized messages for the DTE Engine. Messages here give 
# the text of Design Engine exceptions.

###########################################################
#for test only
Error.Msg001=El valor {0} no se encuentra en {0}.

###########################################################

#load data engine factory exception
load.factory.error=Hay un error al cargar la fábrica del adaptador de datos.

context.null.error=El contexto de datos no puede ser nulo.
context.invalidDesigntimeMethod=El método ReportContext [{0}] sólo puede utilizarse en tiempo de ejecución.

adaptor.invalid.mode=El valor de modo {0} del contexto del adaptador de datos no es válido.
invalid.cache.option=El valor de opción {0} del contexto del adaptador de datos no es válido.

datasource.null.error=La fuente de datos de este conjunto de datos no puede ser nula.
datasource.exid.error=Falta el id de la extensión en la definición de la fuente de datos: {0}

datasethandle.null.error=DataSetHandle no puede ser nulo.
datasethandle.invalidColumnIndex=El índice de columna no es válido.
