# Localized messages for the DTE Engine. Messages here give 
# the text of Design Engine exceptions.

###########################################################
#for test only
Error.Msg001={0} 在 {0} 中未找到。

###########################################################

#load data engine factory exception
load.factory.error=加载数据适配器的工厂时出错。

context.null.error=数据上下文不能为空。
context.invalidDesigntimeMethod=ReportContext 方法 [{0}] 只能用于运行时。

adaptor.invalid.mode=数据适配器上下文的模式值 {0} 无效。
invalid.cache.option=数据适配器上下文的选项值 {0} 无效。

datasource.null.error=此数据集的数据源不能为空。
datasource.exid.error=数据源定义中缺少扩展 ID: {0}

datasethandle.null.error=DataSetHandle 不能为空。
datasethandle.invalidColumnIndex=列索引无效。
