# Localized messages for the DTE Engine. Messages here give 
# the text of Design Engine exceptions.

###########################################################
#for test only
Error.Msg001={0}이(가) {0}에 없습니다.

###########################################################

#load data engine factory exception
load.factory.error=데이터 어댑터 팩토리 로드 중 오류가 발생했습니다.

context.null.error=데이터 컨텍스트는 널(null)이 될 수 없습니다.
context.invalidDesigntimeMethod=ReportContext 메서드 [{0}]은(는) 런타임에서만 사용될 수 있습니다.

adaptor.invalid.mode=데이터 어댑터 컨텍스트의 모드 값 {0}이(가) 잘못되었습니다.
invalid.cache.option=데이터 어댑터 컨텍스트의 모드 값 {0}이(가) 잘못되었습니다.

datasource.null.error=이 데이터 집합의 데이터 원본은 널(null)이 될 수 없습니다.
datasource.exid.error=데이터 원본 정의 {0}에 확장 ID가 누락되었습니다.

datasethandle.null.error=DataSetHandle은 널(null)이 될 수 없습니다.
datasethandle.invalidColumnIndex=잘못된 열 인덱스입니다.
