#************************************************************************
# Copyright (c) 2012 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#************************************************************************
#
# User messages for the Excel File ODA Designer
wizard.defaultMessage.selectExcelFile=选择或输入 Excel 数据源文件路径或 URI。

wizard.defaultMessage.selectDataSet=为数据集选择工作表和列。

connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=无法在选择的文件夹中打开 Excel 数据源文件。

ui.ExcelFileNotFound=无法定位指定的 Excel 数据源文件

label.selectFolder=选择文件夹(&E):

label.selectFile=选择文件(&I):

label.selectworksheet=选择工作表(&H):

label.includeTypeLine=将第二行用作数据类型指示器(&D)。

label.includeColumnNameLine= 将第一行用作列名称指示器(&A)。

button.selectFolder.browse=浏览(&R)...

button.moveUp=上移(&U)

button.moveDown=下移(&O)

button.delete=删除(&E)

button.selectFileURI.menuItem.relativePath=相对路径(&R)

button.selectFileURI.menuItem.absolutePath=绝对路径(&A)

editor.title.name=名称

editor.title.originalName=原始名称

editor.title.type=类型

datatypes.dateTime=日期时间

datatypes.decimal=小数

datatypes.float=浮点

datatypes.integer=整型

datatypes.string=字符串

datatypes.date=日期

datatypes.time=时间

datatypes.boolean=布尔

tooltip.columnnameline=请确保选定的文件第一行\n中存在列名称。

tooltip.typeline=请确保选定的文件第二行\n中存在数据类型指示器。

tooltip.button.add=将左表中所有选定的列添加到 Excel 文件数据集。

tooltip.button.up=上移选定项目。

tooltip.button.down=下移选定项目。

tooltip.button.delete=删除选定项目。

tooltip.trailNull=读取数据行时出现空后缀列。

error.selectFolder=请选择有效文件夹。

error.selectWorksheet=请为该数据集选择工作表。

error.selectColumns=请至少为此数据集选择一个列。

error.emptyPath=请输入路径。

error.unexpectedError=发生意外错误。

error.invalidConnectionFilePath=指定的连接配置文件源路径“{0}”不存在。

error.errorExist=当前页存在错误。  是否仍要保存?

error.noFile=Excel 数据源文件 ({0}) 不存在。

error.invalidFilePath=文件路径无效。  是否继续?

error.emptyFilePath=文件路径为空。  是否继续?

error.duplicatedNameValueOrEmpty=名称值重复或为空

error.emptyFolder=未在选定的文件夹中找到 Excel 数据源文件。

title.warning=警告

warning.fileExtensionInvalid=选定的文件可能不是有效的 Excel 文件。

confirm.reselectWorksheetTitle=确认选择另一个工作表。

confirm.reselectWorksheetMessage=选择另一工作表将不保存以上操作。\n\n您确定吗？

confirm.reselectFileTitle=确认选择另一文件。

confirm.reselectFileMessage=选择另一文件将不保存以上操作。\n\n您确定吗？

RelativeFolderSelectionDialog.Title.SelectFolder=选择文件夹

RelativeFileSelectionDialog.button.importFile=导入文件...

RelativeFileSelectionDialog.title.error=错误

RelativeFileSelectionDialog.title.overwrite=覆盖

RelativeFileSelectionDialog.overwrite.msg=具有此名称的文件已经存在，是否要覆盖它?

RelativeFileSelectionDialog.import.msg=正在导入文件...

SelectFile.Title=选择文件
