#************************************************************************
# Copyright (c) 2012 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#************************************************************************
#
# User messages for the Excel File ODA Designer
wizard.defaultMessage.selectExcelFile=Wählen Sie einen Excel-Datenquellendateipfad oder URI, oder geben Sie einen ein.

wizard.defaultMessage.selectDataSet=Wählen Sie das Arbeitsblatt und die Spalten für den Datensatz aus.

connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Excel-Datenquellendatei kann im ausgewählten Ordner nicht geöffnet werden.

ui.ExcelFileNotFound=Die angegebene Excel-Datenquellendatei wurde nicht gefunden.

label.selectFolder=Ordner aus&wählen:

label.selectFile=Date&i auswählen:

label.selectworksheet=Wählen Sie ein &Arbeitsblatt:

label.includeTypeLine=Zweite Zeile als &Datentypindikator verwenden.

label.includeColumnNameLine= Erste Zeile &als Spaltennamenindikator verwenden.

button.selectFolder.browse=Du&rchsuchen...

button.moveUp=Nach &oben

button.moveDown=Nach &unten

button.delete=Lösch&en

button.selectFileURI.menuItem.relativePath=&Relativer Pfad

button.selectFileURI.menuItem.absolutePath=&Absoluter Pfad

editor.title.name=Name

editor.title.originalName=Ursprünglicher Name

editor.title.type=Typ

datatypes.dateTime=Datum/Uhrzeit

datatypes.decimal=Decimal

datatypes.float=Gleitkomma

datatypes.integer=Ganzzahl

datatypes.string=Zeichenfolge

datatypes.date=Datum

datatypes.time=Zeit

datatypes.boolean=Boolesch

tooltip.columnnameline=Stellen Sie sicher, dass die erste Zeile\nder ausgewählten Datei Spaltennamen enthält.

tooltip.typeline=Stellen Sie sicher, dass die zweite Zeile\nder gewählten Datei einen Datentypindikator enthält.

tooltip.button.add=Alle ausgewählten Spalten aus der Tabelle links zum Datensatz für Excel-Datei hinzufügen.

tooltip.button.up=Ausgewähltes Element nach oben verschieben.

tooltip.button.down=Ausgewähltes Element nach unten verschieben.

tooltip.button.delete=Ausgewähltes Objekt löschen.

tooltip.trailNull=Spalten mit Nullen in Endposition beim Lesen von Datenzeilen.

error.selectFolder=Wählen Sie einen gültigen Ordner aus.

error.selectWorksheet=Wählen Sie ein Arbeitsblatt für den Datensatz aus.

error.selectColumns=Wählen Sie für diesen Datensatz mindestens eine Spalte aus.

error.emptyPath=Geben Sie einen Pfad ein.

error.unexpectedError=Es ist ein unbekannter Fehler aufgetreten.

error.invalidConnectionFilePath=Der angegebene Quellpfad "{0}" für das Verbindungsprofil ist nicht vorhanden.

error.errorExist=Fehler auf aktueller Seite.  Trotzdem speichern?

error.noFile=Die Excel-Datenquellendatei ({0}) existiert nicht.

error.invalidFilePath=Der Dateipfad ist ungültig.  Möchten Sie fortfahren?

error.emptyFilePath=Der Dateipfad ist leer.  Möchten Sie fortfahren?

error.duplicatedNameValueOrEmpty=Doppelter Namenswert oder leer

error.emptyFolder=Keine Excel-Datenquellendatei im ausgewählten Ordner gefunden.

title.warning=Warnung

warning.fileExtensionInvalid=Bei der ausgewählten Datei handelt es sich möglicherweise nicht um eine gültige Excel-Datei.

confirm.reselectWorksheetTitle=Bestätigen Sie zum Auswählen eines anderen Blatts.

confirm.reselectWorksheetMessage=Bei Auswahl eines anderen Blatts werden vorherige Vorgänge nicht gespeichert.\n\nTrotzdem fortfahren?

confirm.reselectFileTitle=Bestätigen Sie zum Auswählen einer anderen Datei.

confirm.reselectFileMessage=Bei Auswahl einer anderen Datei werden vorherige Vorgänge nicht gespeichert.\n\nTrotzdem fortfahren?

RelativeFolderSelectionDialog.Title.SelectFolder=Wählen Sie einen Ordner aus.

RelativeFileSelectionDialog.button.importFile=Importdatei...

RelativeFileSelectionDialog.title.error=Fehler

RelativeFileSelectionDialog.title.overwrite=Überschreiben

RelativeFileSelectionDialog.overwrite.msg=Eine Datei mit diesem Namen ist bereits vorhanden. Soll sie überschrieben werden?

RelativeFileSelectionDialog.import.msg=Datei wird importiert...

SelectFile.Title=Datei auswählen
