###############################################################################
# Copyright (c) 2004,2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=Fuente de datos XML BIRT
dataset.name=Conjunto de datos XML BIRT

datasource.property.xmlFile=Archivo de fuente de datos XML
datasource.property.schemaFile=Archivo del esquema XML
