###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=Alte BIRT 2.1.x-XML-Datenquelle

dataset.name=BIRT 2.1.x-XML-Datensatz

datasource.property.xmlFile=XML-Datenquellendatei

datasource.property.schemaFile=XML-Schema-Datei