###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=Source de données XML héritée BIRT 2.1.x

dataset.name=Jeu de données XML BIRT 2.1.x

datasource.property.xmlFile=Fichier de source de données XML

datasource.property.schemaFile=Fichier de schéma XML