###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=旧式 BIRT 2.1.x XML 数据源

dataset.name=BIRT 2.1.x XML 数据集

datasource.property.xmlFile=XML 数据源文件

datasource.property.schemaFile=XML 架构文件