###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=보고서 보기
designer.preview.previewaction.label.webviewer=웹 뷰어에서 보고서 보기(&B)
designer.preview.previewaction.label.html=HTML로 보고서 보기(&H)
designer.preview.previewaction.label.pdf=PDF로 보고서 보기(&D)
ActionSet.Preview=미리 보기

template.preview=미리 보기
design.preview=미리 보기

preference.preview=미리 보기
preference.preview.server=서버 미리 보기

###############################################################################
# Actions
###############################################################################
Menu.Report=보고서
Action.RunReport=보고서 실행
Action.ViewDocument=문서 보기
