###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=查看报表
designer.preview.previewcascadingmenugroup.label=查看报表
ActionSet.Preview=预览

template.preview=New Preview Prototype
design.preview=New Preview Prototype

preference.preview=预览
preference.preview.server=预览服务器

###############################################################################
# Actions
###############################################################################
Menu.Report=报表
Action.RunReport=运行报表
Action.ViewDocument=查看文档
