###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Ver informe
designer.preview.previewcascadingmenugroup.label=Ver &Informe
ActionSet.Preview=Vista previa

template.preview=Nuevo pro&totipo de vista previa
design.preview=Nuevo pro&totipo de vista previa

preference.preview=Vista previa
preference.preview.server=Servidor de vista previa

###############################################################################
# Actions
###############################################################################
Menu.Report=Repor&t
Action.RunReport=&Run Report
Action.ViewDocument=&View Document
