###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=查看报表
designer.preview.previewcascadingmenugroup.label=查看报表(&R)
ActionSet.Preview=预览

template.preview=新建预览原型(&T)
design.preview=新建预览原型(&T)

preference.preview=预览
preference.preview.server=预览服务器

###############################################################################
# Actions
###############################################################################
Menu.Report=Repor&t
Action.RunReport=&Run Report
Action.ViewDocument=&View Document
