###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Bericht anzeigen
designer.preview.previewcascadingmenugroup.label=Bericht anzeigen
ActionSet.Preview=Vorschau

template.preview=Neuer Vorschauprototyp
design.preview=Neuer Vorschauprototyp

preference.preview=Vorschau
preference.preview.server=Vorschau-Server

###############################################################################
# Actions
###############################################################################
Menu.Report=Bericht
Action.RunReport=Bericht ausführen
Action.ViewDocument=Dokument anzeigen
