###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=보고서 보기

designer.preview.previewcascadingmenugroup.label=보고서 보기(&R)

ActionSet.Preview=미리 보기

template.preview=새 미리 보기 프로토타입(&T)

design.preview=새 미리 보기 프로토타입(&T)

preference.preview=미리 보기

preference.preview.server=서버 미리 보기

###############################################################################
# Actions
###############################################################################
Menu.Report=보고서(&T)

Action.RunReport=보고서 실행(&R)

Action.ViewDocument=문서 보기(&V)