###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Afficher l'état
designer.preview.previewcascadingmenugroup.label=Afficher l'état
ActionSet.Preview=Aperçu

template.preview=New Preview Prototype
design.preview=New Preview Prototype

preference.preview=Aperçu
preference.preview.server=Serveur de prévisualisation

###############################################################################
# Actions
###############################################################################
Menu.Report=Etat
Action.RunReport=Exécuter l'état
Action.ViewDocument=Afficher le document
