###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=보고서 보기
designer.preview.previewcascadingmenugroup.label=보고서 보기(&R)
ActionSet.Preview=미리 보기

template.preview=새 미리 보기 프로토타입(&T)
design.preview=새 미리 보기 프로토타입(&T)

preference.preview=미리 보기
preference.preview.server=서버 미리 보기

###############################################################################
# Actions
###############################################################################
Menu.Report=Repor&t
Action.RunReport=&Run Report
Action.ViewDocument=&View Document
