###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Bericht anzeigen

designer.preview.previewcascadingmenugroup.label=&Bericht anzeigen

ActionSet.Preview=Vorschau

template.preview=Neuer Vorschaupro&totyp

design.preview=Neuer Vorschaupro&totyp

preference.preview=Vorschau

preference.preview.server=Vorschau-Server

###############################################################################
# Actions
###############################################################################
Menu.Report=Berich&t

Action.RunReport=Bericht aus&führen

Action.ViewDocument=Dokument an&zeigen