###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Ver informe
designer.preview.previewcascadingmenugroup.label=Ver informe
ActionSet.Preview=Vista previa

template.preview=Nuevo prototipo de previsualización
design.preview=Nuevo prototipo de previsualización

preference.preview=Vista previa
preference.preview.server=Servidor de vista previa

###############################################################################
# Actions
###############################################################################
Menu.Report=Informe
Action.RunReport=Ejecutar informe
Action.ViewDocument=Ver documento
