###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=レポートの表示

designer.preview.previewcascadingmenugroup.label=レポートの表示(&R)

ActionSet.Preview=プレビュー

template.preview=プレビューのプロトタイプの新規作成(&T)

design.preview=プレビューのプロトタイプの新規作成(&T)

preference.preview=プレビュー

preference.preview.server=プレビュー用のサーバ

###############################################################################
# Actions
###############################################################################
Menu.Report=レポート(&T)

Action.RunReport=レポートの実行（&R)

Action.ViewDocument=文書の表示(&V)