###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=XML-Datenquelle

oda.xml.dataset=XML-Datensatz

oda.xml.tablemapping=Tabellenzuordnung

oda.xml.columnmapping=Spaltenzuordnung


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=Alte BIRT 2.1.x-XML-Datenquelle

connection.profile.name=XML-Datenquellen-Verbindungsprofil

newwizard.name=Alte BIRT 2.1.x-XML-Datenquelle

newwizard.description=BIRT 2.1.x-XML-Datenquellen-Verbindungsprofil erstellen

wizard.window.title=Neues XML-Datenquellenprofil

wizard.data.source.page.title=Geben Sie die URLs und die Schemainformation für die XML-Datei an.

profile.propertypage.name=XML-Datenquellen-Verbindungseigenschaften

preference.datasetpreview=XML-Datensatz
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
