###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=XML Data Source
oda.xml.dataset=Conjunto de datos XML
oda.xml.tablemapping=Asignación de tablas
oda.xml.columnmapping=Asignación de columnas

oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=Legacy BIRT 2.1.x XML Data Source
connection.profile.name=XML Data Source Connection Profile
newwizard.name=Legacy BIRT 2.1.x XML Data Source
newwizard.description=Create a BIRT 2.1.x XML data source connection profile
wizard.window.title=New XML Data Source Profile
wizard.data.source.page.title=Definir las URL al archivo XML y la información de esquema.
profile.propertypage.name=XML Data Source Connection Properties
preference.datasetpreview=Conjunto de datos XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
