###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=XML データソース

oda.xml.dataset=XML データセット

oda.xml.tablemapping=テーブルのマッピング

oda.xml.columnmapping=列のマッピング


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=BIRT 2.1.x XML の旧データソース

connection.profile.name=XML データソース接続プロファイル

newwizard.name=BIRT 2.1.x XML の旧データソース

newwizard.description=BIRT 2.1.x XML データソース接続プロファイルの作成

wizard.window.title=XML データソースプロファイルの新規作成

wizard.data.source.page.title=XML ファイルとスキーマ情報への URL を定義してください。

profile.propertypage.name=XML データソースの接続プロパティ

preference.datasetpreview=XML データセット
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
