###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Source de données XML

oda.xml.dataset=Jeu de données XML

oda.xml.tablemapping=Mise en correspondance de table

oda.xml.columnmapping=Mise en correspondance de colonne


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=Source de données XML héritée BIRT 2.1.x

connection.profile.name=Profil de connexion à la source de données XML

newwizard.name=Source de données XML héritée BIRT 2.1.x

newwizard.description=Créer un profil de connexion à une source de données XML BIRT 2.1.x

wizard.window.title=Nouveau profil de source de données XML

wizard.data.source.page.title=Définir les URL du fichier XML et les informations du schéma

profile.propertypage.name=Propriétés de la connexion à la source de données XML

preference.datasetpreview=Jeu de données XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
