###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Fuente de datos XML

oda.xml.dataset=Conjunto de datos XML

oda.xml.tablemapping=Asignación de tablas

oda.xml.columnmapping=Asignación de columnas


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=Fuente de datos XML de versión antigua de BIRT 2.1.x

connection.profile.name=Perfil de conexión de fuente de datos XML

newwizard.name=Fuente de datos XML de versión antigua de BIRT 2.1.x

newwizard.description=Crear un perfil de conexión de fuente de datos XML BIRT 2.1.x

wizard.window.title=Nuevo perfil de fuente de datos XML

wizard.data.source.page.title=Definir las URL al archivo XML y la información de esquema.

profile.propertypage.name=Propiedades de conexión de fuente de datos XML

preference.datasetpreview=Conjunto de datos XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
