###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=XML 데이터 원본

oda.xml.dataset=XML 데이터 집합

oda.xml.tablemapping=테이블 매핑

oda.xml.columnmapping=열 매핑


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT ODA XML Designer
oda.data.source.name=레거시 BIRT 2.1.x XML 데이터 원본

connection.profile.name=XML 데이터 원본 연결 프로필

newwizard.name=레거시 BIRT 2.1.x XML 데이터 원본

newwizard.description=BIRT 2.1.x XML 데이터 원본 연결 프로필을 생성합니다.

wizard.window.title=새 XML 데이터 원본 프로필

wizard.data.source.page.title=XML 파일과 스키마 정보의 URL 정의

profile.propertypage.name=XML 데이터 원본 연결 속성

preference.datasetpreview=XML 데이터 집합
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
