###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Fuente de datos XML
oda.xml.dataset=Conjunto de datos XML
oda.xml.tablemapping=Asignación de tablas
oda.xml.columnmapping=Asignación de columnas

oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT XML File Designer
oda.data.source.name=Archivos XML BIRT
connection.profile.name=Perfil de conexión de fuente de datos de archivo XML BIRT
newwizard.name=Fuente de datos de archivo XML BIRT
newwizard.description=Crear un perfil de conexión del archivo XML BIRT
wizard.window.title=Nuevo perfil de fuente de datos del archivo XML
wizard.data.source.page.title=Definir las URL al archivo XML y la información de esquema.
profile.propertypage.name=Propiedades de conexión de fuente de datos de archivo XML BIRT
preference.datasetpreview=Conjunto de datos XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
