###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Source de données XML
oda.xml.dataset=Jeu de données XML
oda.xml.tablemapping=Mise en correspondance de table
oda.xml.columnmapping=Mise en correspondance de colonne

oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT XML File Designer
oda.data.source.name=Fichiers XML BIRT
connection.profile.name=Profil de connexion de source de données sous forme de fichier XML BIRT
newwizard.name=Source de données sous forme de fichier XML BIRT
newwizard.description=Créer un profil de connexion de fichier XML BIRT
wizard.window.title=Nouveau profil de source de données sous forme de fichier XML
wizard.data.source.page.title=Définir les URL du fichier XML et les informations du schéma
profile.propertypage.name=Propriétés de connexion de source de données sous forme de fichier XML BIRT
preference.datasetpreview=Jeu de données XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
