###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=이 마법사는 미리 정의된 템플릿에서 새 보고서를 생성합니다.

ReportProjectWizardDescription=새 보고서 프로젝트를 생성합니다.

ReportPerspective=보고서 디자인

ReportViews=보고서 디자인

WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=보고서

ReportProjectWizard=보고서 프로젝트

ReportEditor=보고서 편집기


###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=보고서 확장 요소 UI

###############################################################################
# Preference
###############################################################################
preference.birt=보고서 디자인

preference.datasetpreview=데이터 집합 편집기

preference.preview=미리 보기

preference.preview.server=미리보기 서버

preference.elementnames=요소 이름

preference.library=라이브러리

preference.template=템플릿

preference.resource=리소스

preference.commenttemplates=설명 템플릿
#hcg_bidi
preference.bidiproperties=양방향 속성

preference.layout=레이아웃

preference.expressionsyntax=식 구문

designer.action.undo.label=실행 취소

designer.action.redo.label=다시 실행

extension.odadatasource=ODA 데이터 원본 확장점

publish.template=새 보고서 마법사를 템플릿에 등록(&Z)...

publish.library=공유 리소스 폴더로 라이브러리 복사(&B)...

ActionSet.Publish=리소스 게시

Dummy.label=

preference.classpath=클래스 경로

parameter.actions=새 보고서 매개 변수(&P)
