###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=このウィザードでは、定義済みのテンプレートを使って新しいレポートを作成します。
ReportProjectWizardDescription=新しいレポートプロジェクトを作成します。
ReportPerspective=レポートデザイン
ReportViews=レポートデザイン
WizardCategoryName=ビジネスインテリジェンスおよびレポーティングツール
ReportWizard=レポート
ReportProjectWizard=レポートプロジェクト
ReportEditor=レポートエディタ
QuickEditView=プロパティエディタ
DataExplorerView=データエクスプローラ

###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=レポートの拡張要素 UI

preference.birt=レポートデザイン
preference.datasetpreview=データセットエディタ
preference.preview=プレビュー
preference.preview.server=プレビュー用のサーバ
preference.elementnames=要素名
preference.library=ライブラリ
preference.template=テンプレート
preference.resource=リソース
preference.commenttemplates=コメントテンプレート

designer.action.undo.label=元に戻す
designer.action.redo.label=やり直し

extension.odadatasource=ODA データソースの拡張ポイント

publish.template=テンプレートフォルダへ公開...
publish.library=リソースフォルダにライブラリを公開...

ActionSet.Publish=公開

