###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=Cet assistant crée un nouvel état à partir d'un modèle prédéfini.

ReportProjectWizardDescription=Créez un nouveau projet d'état.

ReportPerspective=Modèle d'état

ReportViews=Modèle d'état

WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Etat

ReportProjectWizard=Projet d'état

ReportEditor=Editeur d'état


###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=Interface utilisateur - Elément d'état étendu

###############################################################################
# Preference
###############################################################################
preference.birt=Modèle d'état

preference.datasetpreview=Editeur de jeu de données

preference.preview=Aperçu

preference.preview.server=Serveur de prévisualisation

preference.elementnames=Noms des éléments

preference.library=Bibliothèque

preference.template=Modèle

preference.resource=Ressource

preference.commenttemplates=Modèle de commentaire
#hcg_bidi
preference.bidiproperties=Propriétés bidirectionnelles

preference.layout=Mise en page

preference.expressionsyntax=Syntaxe d'expression

designer.action.undo.label=Annuler

designer.action.redo.label=Rétablir

extension.odadatasource=Point d'extension de la source de données ODA

publish.template=Enregistrer le modèle avec l'&assistant Nouvel état...

publish.library=Copier la bi&bliothèque dans le dossier de ressources partagées...

ActionSet.Publish=Publier les ressources

Dummy.label=

preference.classpath=Classpath

parameter.actions=Nouveau &paramètre d'état
