###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=此向导使用预定义模板创建新报表。

ReportProjectWizardDescription=创建新报表项目。

ReportPerspective=报表设计

ReportViews=报表设计

WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=报表

ReportProjectWizard=报表项目

ReportEditor=报表编辑器


###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=报表扩展元素 UI

###############################################################################
# Preference
###############################################################################
preference.birt=报表设计

preference.datasetpreview=数据集编辑器

preference.preview=预览

preference.preview.server=预览服务器

preference.elementnames=元素名称

preference.library=库

preference.template=模板

preference.resource=资源

preference.commenttemplates=注释模板
#hcg_bidi
preference.bidiproperties=双向属性

preference.layout=布局

preference.expressionsyntax=表达式语法

designer.action.undo.label=撤消

designer.action.redo.label=重复

extension.odadatasource=ODA 数据源扩展点

publish.template=使用新建报表向导来注册模板(&Z)...

publish.library=将库复制到共享资源文件夹...

ActionSet.Publish=发布资源

Dummy.label=

preference.classpath=类路径

parameter.actions=新报表参数(&P)
