###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=Este asistente crea un nuevo informe a partir de una plantilla predefinida.
ReportProjectWizardDescription=Crea un nuevo proyecto de informe.
ReportPerspective=Diseño de informe
ReportViews=Diseño de informe
WizardCategoryName=Herramientas de generación de informe para la actividad empresarial
ReportWizard=Informe
ReportProjectWizard=Proyecto de informe
ReportEditor=Editor de informes
QuickEditView=Editor de propiedades
DataExplorerView=Explorador de datos
cheatsheet.category=Business Intelligence and Reporting Tools
cheatsheet.simplelisting=Simple Listing Report
cheatsheet.groupedlisting=Grouped Listing Report
cheatsheet.dualcolumnlisting=Dual Column Listing Report
cheatsheet.chartlisting=Chart & Listing Report
cheatsheet.sidebysidechartlisting=Side by side Chart Listing Report
cheatsheet.dualcolumnchartlisting=Dual Column Chart Listing Report
cheatsheet.firstreport=My First Report

###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=Interfaz de usuario de elemento ampliado de informe

preference.birt=Diseño de informe
preference.datasetpreview=Editor de conjunto de datos
preference.preview=Vista previa
preference.preview.server=Servidor de vista previa
preference.elementnames=Nombres de elemento
preference.library=Librería
preference.template=Plantilla
preference.resource=Recurso
preference.commenttemplates=Plantilla de comentario

designer.action.undo.label=Deshacer
designer.action.redo.label=Rehacer

extension.odadatasource=Punto de extensión de fuente de datos ODA

publish.template=Publicar en carpeta de plantillas...
publish.library=Publicar librería en la carpeta de recursos...

ActionSet.Publish=Publicar

