###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=このウィザードでは、定義済みのテンプレートを使って新しいレポートを作成します。

ReportProjectWizardDescription=新しいレポートプロジェクトを作成します。

ReportPerspective=レポートデザイン

ReportViews=レポートデザイン

WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=レポート

ReportProjectWizard=レポートプロジェクト

ReportEditor=レポートエディタ


###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=レポートの拡張要素 UI

###############################################################################
# Preference
###############################################################################
preference.birt=レポートデザイン

preference.datasetpreview=データセットエディタ

preference.preview=プレビュー

preference.preview.server=プレビュー用のサーバ

preference.elementnames=要素名

preference.library=ライブラリ

preference.template=テンプレート

preference.resource=リソース

preference.commenttemplates=コメントテンプレート
#hcg_bidi
preference.bidiproperties=双方向プロパティ

preference.layout=レイアウト

preference.expressionsyntax=式構文

designer.action.undo.label=元に戻す

designer.action.redo.label=やり直し

extension.odadatasource=ODA データソースの拡張ポイント

publish.template=テンプレートをレポートの新規作成ウィザードに登録(&Z)...

publish.library=共有リソースフォルダへのライブラリのコピー(&B)...

ActionSet.Publish=リソースの公開

Dummy.label=

preference.classpath=クラスパス

parameter.actions=レポートパラメタの新規作成(&P)
