###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Fuente de datos de Excel
newwizard.description=Crear un perfil de conexión de fuente de datos de Excel
wizard.window.title=Nuevo perfil de fuente de datos de Excel
wizard.data.source.page.title=Fuente de datos de Excel
profile.propertypage.name=Propiedades de conexión de fuente de datos de Excel
wizard.data.set.window.title=Nuevo conjunto de datos de Excel
wizard.data.set.page.title=Seleccionar columnas
