###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel 数据源
newwizard.description=创建 Excel 数据源连接配置文件
wizard.window.title=新建 Excel 数据源配置文件
wizard.data.source.page.title=Excel 数据源
profile.propertypage.name=Excel 数据源连接属性
wizard.data.set.window.title=新建 Excel 数据集
wizard.data.set.page.title=选择列
