###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel Data Source
newwizard.description=Crear un perfil de conexión de fuente de datos de Excel

wizard.window.title=Nuevo perfil de fuente de datos de Excel

wizard.data.source.page.title=Excel Data Source
profile.propertypage.name=Excel Data Source Connection Properties
wizard.data.set.window.title=Nuevo conjunto de datos de Excel

wizard.data.set.page.title=Seleccionar columnas
