###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel Data Source
newwizard.description=Excel データソース接続プロファイルを作成します。

wizard.window.title=Excel データソースプロファイルの新規作成

wizard.data.source.page.title=Excel Data Source
profile.propertypage.name=Excel Data Source Connection Properties
wizard.data.set.window.title=新規 Excel データセット

wizard.data.set.page.title=列の選択
