###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel-Datenquelle
newwizard.description=Ein Excel-Datenquellen-Verbindungsprofil erstellen
wizard.window.title=Neues Excel-Datenquellenprofil
wizard.data.source.page.title=Excel-Datenquelle
profile.propertypage.name=Excel-Datenquellen-Verbindungseigenschaften
wizard.data.set.window.title=Neuer Excel-Datensatz
wizard.data.set.page.title=Spalten auswählen
