###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel 데이터 원본
newwizard.description=Excel 데이터 원본 연결 프로필 생성
wizard.window.title=새 Excel 데이터 원본 프로필
wizard.data.source.page.title=Excel 데이터 원본
profile.propertypage.name=Excel 데이터 원본 연결 속성
wizard.data.set.window.title=새 Excel 데이터 집합
wizard.data.set.page.title=열 선택
