###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Excel データソース
newwizard.description=Excel データソース接続プロファイルを作成します。
wizard.window.title=Excel データソースプロファイルの新規作成
wizard.data.source.page.title=Excel データソース
profile.propertypage.name=Excel データソースの接続プロパティ
wizard.data.set.window.title=新規 Excel データセット
wizard.data.set.page.title=列の選択
