###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS strings
#
plugin.name=Excel Data Source ODA Designer
newwizard.name=Source de données Excel
newwizard.description=Créez un profil de connexion à la source de données Excel
wizard.window.title=Nouveau profil de source de données Excel
wizard.data.source.page.title=Source de données Excel
profile.propertypage.name=Propriétés de la connexion à la source de données Excel
wizard.data.set.window.title=Nouveau jeu de données Excel
wizard.data.set.page.title=Sélectionnez les colonnes
