Templates.jspbirthtml.name=新規 JSP ファイル (HTML、BIRT タグ)
Templates.jspbirthtml.desc=JSP (HTML マークアップと BIRT タグを使用) 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>ここにタイトルを入力してください</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=JSP taglib (BIRT)
Templates.jspbirttag.desc=JSP taglib (BIRTレポート作成ツール用) 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
