Templates.jspbirthtml.name=Neue JSP-Datei (HTML, BIRT-Tag)
Templates.jspbirthtml.desc=JSP mit HTML-Markup und BIRT-Tag 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Titel hier einfügen</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=JSP-Taglib (BIRT)
Templates.jspbirttag.desc=JSP-Taglib für BIRT-Reporting-Tools 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
