Templates.jspbirthtml.name=Nouveau fichier JSP (balise BIRT, html)
Templates.jspbirthtml.desc=JSP avec balises html et BIRT 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4,01 Transitional//EN" "http://www.w3,org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Insérer le titre ici</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=taglib JSP (BIRT)
Templates.jspbirttag.desc=taglib JSP pour les outils de reporting BIRT 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
