Templates.jspbirthtml.name=새 JSP 파일(html, BIRT 태그)
Templates.jspbirthtml.desc=html 및 BIRT 태그를 사용한 JSP 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Insert title here</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=JSP taglib(BIRT)
Templates.jspbirttag.desc=BIRT 보고 도구용 JSP taglib 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
