Templates.jspbirthtml.name=新建 JSP 文件(html、BIRT 标记)
Templates.jspbirthtml.desc=具有 html 标记和 BIRT 标记的 JSP 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>在此处插入标题</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=JSP taglib (BIRT)
Templates.jspbirttag.desc=JSP taglib for BIRT 报告工具 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
