Templates.jspbirthtml.name=Nuevo archivo JSP (html, etiqueta BIRT)
Templates.jspbirthtml.desc=JSP con código html y etiqueta BIRT 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Insertar título aquí</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=Librería de etiquetas JSP (BIRT)
Templates.jspbirttag.desc=Librería de etiquetas JSP para herramientas de generación de informes BIRT 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n
