#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.script=スクリプト(&S)

template.script=スクリプト(&S)

library.script=スクリプト(&S)

pageSet.script=スクリプトページ(&S)