#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sampleDbFactory_invalidDirectory={0}에 샘플 데이터베이스를 만들 수 없습니다.

sampleDbFactory_noSampleDbJarFile=내부 오류: 샘플 데이터베이스 jar 파일({0})을(를) 찾을 수 없습니다.
