#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sampleDbFactory_invalidDirectory={0} にサンプルデータベースを作成できません。

sampleDbFactory_noSampleDbJarFile=内部エラー : サンプルデータベースの jar ファイル ({0}) が見つかりません。
