#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sampleDbFactory_invalidDirectory=Impossible de créer une base de données exemple dans {0}.

sampleDbFactory_noSampleDbJarFile=Erreur interne : impossible de trouver le fichier jar de la base de données exemple ({0}).
