#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sampleDbFactory_invalidDirectory=No es posible crear una base de datos de muestra en {0}.

sampleDbFactory_noSampleDbJarFile=Error interno: no ha sido posible localizar el archivo jar ({0}) de la base de datos de muestra.
