#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sampleDbFactory_invalidDirectory=Beispieldatenbank in {0} kann nicht erstellt werden.

sampleDbFactory_noSampleDbJarFile=Interner Fehler: JAR-Datei für Beispieldatenbank nicht gefunden: ({0}).
