Templates.jsp_birt_chart_html.name=New JSP File (html, BIRT Chart tag)
Templates.jsp_birt_chart_html.desc=JSP with html markup and BIRT Chart tag 
Templates.jsp_birt_chart_html.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/chart.tld" prefix="chart" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Insert title here</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jsp_birt_chart_tag.name=JSP taglib (BIRT グラフ)
Templates.jsp_birt_chart_tag.desc=JSP taglib (BIRT グラフ作成ツール用) 
Templates.jsp_birt_chart_tag.content=<%@ taglib uri="/chart.tld" prefix="chart" %>\n