###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=Editor de informes
TemplateEditor=Editor de plantillas
ReportPerspective=Diseño de informe

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Herramientas de generación de informe para la actividad empresarial
ReportWizard=Informe
ReportWizardDescription=Este asistente crea un nuevo informe a partir de una plantilla predefinida.
TemplateWizard=Plantilla
TemplateWizardDescription=Este asistente crea una nueva plantilla.
ReportProjectWizard=Proyecto de informe
ReportProjectWizardDescription=Crea un nuevo proyecto de informe.

LibraryEditor=Editor de librerías
LibraryWizard=Librería
LibraryWizardDescription=Este asistente crea una nueva librería de informes.

OdaRuntimeWizard=ODA Runtime Driver Plug-in Project
OdaRuntimeWizardDesc=Create a new ODA runtime driver plug-in.
OdaDesignerWizard=ODA Designer Plug-in Project
OdaDesignerWizardDesc=Create a new ODA designer plug-in.

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=Diseño de informe
org.eclipse.birt.category.description=Herramientas de generación de informe para la actividad empresarial

###############################################################################
# Actions
###############################################################################
Action.Publish=Publicar en &carpeta de plantillas...
Action.PublishLibrary=Publicar librería en &carpeta de recursos...
