###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=보고서 편집기
TemplateEditor=템플릿 편집기
ReportPerspective=보고서 디자인

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence 및 보고 도구
ReportWizard=보고서
ReportWizardDescription=이 마법사는 미리 정의된 템플릿에서 새 보고서를 생성합니다.
TemplateWizard=템플릿
TemplateWizardDescription=이 마법사는 새 템플릿을 생성합니다.
ReportProjectWizard=보고서 프로젝트
ReportProjectWizardDescription=새 보고서 프로젝트를 생성합니다.

LibraryEditor=라이브러리 편집기
LibraryWizard=라이브러리
LibraryWizardDescription=이 마법사는 새 보고서 라이브러리를 생성합니다.

OdaRuntimeWizard=ODA Runtime Driver Plug-in Project
OdaRuntimeWizardDesc=Create a new ODA runtime driver plug-in.
OdaDesignerWizard=ODA Designer Plug-in Project
OdaDesignerWizardDesc=Create a new ODA designer plug-in.

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=보고서 디자인
org.eclipse.birt.category.description=Business Intelligence 및 보고서 도구

###############################################################################
# Actions
###############################################################################
Action.Publish=새 보고서 마법사를 템플릿에 등록...
Action.PublishLibrary=리소스 폴더에 라이브러리 배치..
