###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=报表编辑器
TemplateEditor=模板编辑器
ReportPerspective=报表设计

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=业务智能和报告工具
ReportWizard=报表
ReportWizardDescription=此向导使用预定义模板创建新报表。
TemplateWizard=模板
TemplateWizardDescription=此向导创建新模板。
ReportProjectWizard=报表项目
ReportProjectWizardDescription=创建新的报表项目。

LibraryEditor=库编辑器
LibraryWizard=库
LibraryWizardDescription=此向导创建新报表库。

OdaRuntimeWizard=ODA Runtime Driver Plug-in Project
OdaRuntimeWizardDesc=Create a new ODA runtime driver plug-in.
OdaDesignerWizard=ODA Designer Plug-in Project
OdaDesignerWizardDesc=Create a new ODA designer plug-in.

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=报表设计
org.eclipse.birt.category.description=业务智能和报表工具

###############################################################################
# Actions
###############################################################################
Action.Publish=使用新建报表向导来注册模板...
Action.PublishLibrary=将库置于资源文件夹...

