###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=Editeur d'état
TemplateEditor=Editeur de modèles
ReportPerspective=Modèle d'état

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Outils de reporting et de Business Intelligence
ReportWizard=Etat
ReportWizardDescription=Cet assistant crée un nouvel état à partir d'un modèle prédéfini.
TemplateWizard=Modèle
TemplateWizardDescription=Cet assistant crée un nouveau modèle.
ReportProjectWizard=Projet d'état
ReportProjectWizardDescription=Crée un projet d'état.

LibraryEditor=Editeur de bibliothèque
LibraryWizard=Bibliothèque
LibraryWizardDescription=Cet assistant crée une nouvelle bibliothèque d'états.

OdaRuntimeWizard=ODA Runtime Driver Plug-in Project
OdaRuntimeWizardDesc=Create a new ODA runtime driver plug-in.
OdaDesignerWizard=ODA Designer Plug-in Project
OdaDesignerWizardDesc=Create a new ODA designer plug-in.

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=Modèle d'état
org.eclipse.birt.category.description=Outils de reporting et de Business Intelligence

###############################################################################
# Actions
###############################################################################
Action.Publish=Enregistrer le modèle avec l'assistant Nouvel état...
Action.PublishLibrary=Placer la bibliothèque dans le dossier de ressources...
