###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=レポートエディタ

TemplateEditor=テンプレートエディタ

ReportPerspective=レポートデザイン

ReportDocumentEditor=レポート文書エディタ

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=レポート

ReportWizardDescription=このウィザードでは、定義済みのテンプレートを使って新しいレポートを作成します。

TemplateWizard=テンプレート

TemplateWizardDescription=このウィザードでは、新しいテンプレートを作成します。

ReportProjectWizard=レポートプロジェクト

ReportProjectWizardDescription=新しいレポートプロジェクトを作成します。

LibraryEditor=ライブラリエディタ

LibraryWizard=ライブラリ

LibraryWizardDescription=このウィザードでは、新しいレポートライブラリを作成します。

OdaRuntimeWizard=ODA 実行時ドライバのプラグインプロジェクト

OdaRuntimeWizardDesc=ODA 実行時ドライバの新しいプラグインを作成します。

OdaDesignerWizard=ODA デザイナのプラグインプロジェクト

OdaDesignerWizardDesc=ODA デザイナの新しいプラグインを作成します。

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=テンプレートをレポートの新規作成ウィザードに登録(&Z)...

Action.PublishLibrary=共有リソースフォルダへのライブラリのコピー(&B)...

Action.AddReportNature=レポートサポートの追加

Menu.Report=レポート

birtproblemName=レポートの問題

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=構文の色