###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=보고서 편집기

TemplateEditor=템플릿 편집기

ReportPerspective=보고서 디자인

ReportDocumentEditor=보고서 문서 편집기

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=보고서

ReportWizardDescription=이 마법사는 미리 정의된 템플릿에서 새 보고서를 생성합니다.

TemplateWizard=템플릿

TemplateWizardDescription=이 마법사는 새 템플릿을 생성합니다.

ReportProjectWizard=보고서 프로젝트

ReportProjectWizardDescription=새 보고서 프로젝트를 생성합니다.

LibraryEditor=라이브러리 편집기

LibraryWizard=라이브러리

LibraryWizardDescription=이 마법사는 새 보고서 라이브러리를 생성합니다.

OdaRuntimeWizard=ODA 런타임 드라이버 플러그인 프로젝트

OdaRuntimeWizardDesc=새 ODA 런타임 드라이버 플러그인을 생성하십시오.

OdaDesignerWizard=ODA 디자이너 플러그인 프로젝트

OdaDesignerWizardDesc=새 ODA 디자이너 플러그인을 생성하십시오.

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=새 보고서 마법사를 템플릿에 등록(&Z)...

Action.PublishLibrary=공유 리소스 폴더로 라이브러리 복사(&B)...

Action.AddReportNature=보고서 추가 지원

Menu.Report=보고서

birtproblemName=보고서 문제

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=구문 색상 지정