###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=Editeur d'état

TemplateEditor=Editeur de modèles

ReportPerspective=Modèle d'état

ReportDocumentEditor=Editeur d'état

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Etat

ReportWizardDescription=Cet assistant crée un nouvel état à partir d'un modèle prédéfini.

TemplateWizard=Modèle

TemplateWizardDescription=Cet assistant crée un nouveau modèle.

ReportProjectWizard=Projet d'état

ReportProjectWizardDescription=Créez un nouveau projet d'état.

LibraryEditor=Editeur de bibliothèque

LibraryWizard=Bibliothèque

LibraryWizardDescription=Cet assistant crée une nouvelle bibliothèque d'états.

OdaRuntimeWizard=Projet Plug-in de pilote d'exécution ODA

OdaRuntimeWizardDesc=Créez un nouveau plug-in de pilote d'exécution ODA.

OdaDesignerWizard=Projet Plug-in de conception ODA

OdaDesignerWizardDesc=Créez un nouveau plug-in de conception ODA.

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=Enregistrer le modèle avec l'&assistant Nouvel état...

Action.PublishLibrary=Copier la bi&bliothèque dans le dossier de ressources partagées...

Action.AddReportNature=Ajouter Assistance rapport

Menu.Report=Rapport

birtproblemName=Problème d'état

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=Coloration syntaxique