###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=Editor de informes

TemplateEditor=Editor de plantillas

ReportPerspective=Diseño de informe

ReportDocumentEditor=Editor de documentos de informe

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Informe

ReportWizardDescription=Este asistente crea un nuevo informe a partir de una plantilla predefinida.

TemplateWizard=Plantilla

TemplateWizardDescription=Este asistente crea una nueva plantilla.

ReportProjectWizard=Proyecto de informe

ReportProjectWizardDescription=Crear un nuevo proyecto de informe.

LibraryEditor=Editor de librerías

LibraryWizard=Librería

LibraryWizardDescription=Este asistente crea una nueva librería de informes.

OdaRuntimeWizard=Proyecto de complemento de controlador de tiempo de ejecución ODA

OdaRuntimeWizardDesc=Cree un nuevo complemento de controlador de tiempo de ejecución ODA.

OdaDesignerWizard=Proyecto de complemento de diseñador ODA

OdaDesignerWizardDesc=Cree un nuevo complemento de diseñador ODA.

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=Registrar plantilla con el as&istente de nuevos informes...

Action.PublishLibrary=Copiar Li&brería para compartir carpeta de recursos...

Action.AddReportNature=Añadir asistencia de informe

Menu.Report=Informe

birtproblemName=Problemas del informe

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=Colores de sintaxis