###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=レポートエディタ
TemplateEditor=テンプレートエディタ
ReportPerspective=レポートデザイン

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=ビジネスインテリジェンスおよびレポーティングツール
ReportWizard=レポート
ReportWizardDescription=このウィザードでは、定義済みのテンプレートを使って新しいレポートを作成します。
TemplateWizard=テンプレート
TemplateWizardDescription=このウィザードでは、新しいテンプレートを作成します。
ReportProjectWizard=レポートプロジェクト
ReportProjectWizardDescription=新しいレポートプロジェクトを作成します。

LibraryEditor=ライブラリエディタ
LibraryWizard=ライブラリ
LibraryWizardDescription=このウィザードでは、新しいレポートライブラリを作成します。

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=レポートデザイン
org.eclipse.birt.category.description=ビジネスインテリジェンスおよびレポートツール

###############################################################################
# Actions
###############################################################################
Action.Publish=テンプレートフォルダへ公開(&T)...
Action.PublishLibrary=リソースフォルダにライブラリを公開(&R)...
