###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=Bericht-Editor

TemplateEditor=Vorlageneditor

ReportPerspective=Berichtdesign

ReportDocumentEditor=Berichtdokument-Editor

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=Bericht

ReportWizardDescription=Mit diesem Assistenten wird ein neuer Bericht aus einer vordefinierten Vorlage erstellt.

TemplateWizard=Vorlage

TemplateWizardDescription=Mit diesem Assistenten wird eine neue Vorlage erstellt.

ReportProjectWizard=Berichtprojekt

ReportProjectWizardDescription=Neues Berichtprojekt erstellen

LibraryEditor=Bibliothekeditor

LibraryWizard=Bibliothek

LibraryWizardDescription=Mit diesem Assistenten wird eine neue Berichtbibliothek erstellt.

OdaRuntimeWizard=ODA-Laufzeittreiber-Plug-In-Projekt

OdaRuntimeWizardDesc=Ein neues ODA-Laufzeittreiber-Plug-In erstellen.

OdaDesignerWizard=Plug-In-Projekt für ODA-Designer

OdaDesignerWizardDesc=Ein neues Plug-In-Projekt für ODA-Designer erstellen.

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=Vorlage mit Ass&istent für neuen Bericht registrieren...

Action.PublishLibrary=&Bibliothek in Ordner für gemeinsame Ressourcen kopieren...

Action.AddReportNature=Berichtunterstützung hinzufügen

Menu.Report=Bericht

birtproblemName=Bericht-Problem

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=Syntaxfarbe