###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@
ReportEditor=Bericht-Editor
TemplateEditor=Vorlageneditor
ReportPerspective=Berichtdesign

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence & Reporting Tools
ReportWizard=Bericht
ReportWizardDescription=Mit diesem Assistenten wird ein neuer Bericht aus einer vordefinierten Vorlage erstellt.
TemplateWizard=Vorlage
TemplateWizardDescription=Mit diesem Assistenten wird eine neue Vorlage erstellt.
ReportProjectWizard=Berichtprojekt
ReportProjectWizardDescription=Erstellt ein neues Berichtprojekt.

LibraryEditor=Bibliothekeditor
LibraryWizard=Bibliothek
LibraryWizardDescription=Mit diesem Assistenten wird eine neue Berichtbibliothek erstellt.

OdaRuntimeWizard=ODA-Laufzeittreiber-Plug-In-Projekt
OdaRuntimeWizardDesc=Ein neues ODA-Laufzeittreiber-Plug-In erstellen.
OdaDesignerWizard=Plug-In-Projekt für ODA-Designer
OdaDesignerWizardDesc=Ein neues Plug-In-Projekt für ODA-Designer erstellen.

###############################################################################
# Activities
###############################################################################
org.eclipse.birt.activity.description=Berichtdesign
org.eclipse.birt.category.description=Business Intelligence and Report Tools

###############################################################################
# Actions
###############################################################################
Action.Publish=Vorlage mit Assistent für neuen Bericht registrieren...
Action.PublishLibrary=Bibliothek in Ressourcenordner aufnehmen..


