###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=报表编辑器

TemplateEditor=模板编辑器

ReportPerspective=报表设计

ReportDocumentEditor=报表文档编辑器

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Business Intelligence and Reporting Tools
ReportWizard=报表

ReportWizardDescription=此向导使用预定义模板创建新报表。

TemplateWizard=模板

TemplateWizardDescription=此向导创建新模板。

ReportProjectWizard=报表项目

ReportProjectWizardDescription=创建新报表项目。

LibraryEditor=库编辑器

LibraryWizard=库

LibraryWizardDescription=此向导创建新报表库。

OdaRuntimeWizard=ODA 运行时驱动程序插件项目

OdaRuntimeWizardDesc=创建新的 ODA 运行时驱动程序插件。

OdaDesignerWizard=ODA 设计器插件项目

OdaDesignerWizardDesc=创建新的 ODA 设计器插件。

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=使用新建报表向导来注册模板(&Z)...

Action.PublishLibrary=将库复制到共享资源文件夹...

Action.AddReportNature=添加报表支持

Menu.Report=报表

birtproblemName=报表问题

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=语法色彩