###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=새 BIRT 웹 프로젝트

BIRTProjectConfigurationPage_title=BIRT 구성

BIRTProjectConfigurationPage_desc=web.xml에서 정의된 BIRT 배포 설정 구성

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=BIRT 배포 설정 구성

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=배포 폴더 설정

BIRTConfiguration_group_others=기타 설정

BIRTConfiguration_resource_folder_button_text=찾아보기&...

BIRTConfiguration_working_folder_button_text=찾아보기(&R)...

BIRTConfiguration_document_folder_button_text=찾아보기(&O)...

BIRTConfiguration_image_folder_button_text=찾아보기(&W)...

BIRTConfiguration_scriptlib_folder_button_text=찾아보기(&S)...

BIRTConfiguration_log_folder_button_text=찾아보기(&E)...

BIRTConfiguration_resource_label=리소스 폴더(&U):

BIRTConfiguration_resource_dialog_title=리소스 폴더 찾아보기

BIRTConfiguration_resource_dialog_message=기본 리소스 폴더를 선택하십시오.

BIRTConfiguration_working_label=작업 폴더(&K):

BIRTConfiguration_working_dialog_title=작업 폴더 찾아보기

BIRTConfiguration_working_dialog_message=기본 작업 폴더를 선택하십시오.

BIRTConfiguration_document_label=임시 문서 폴더(&D):

BIRTConfiguration_document_dialog_title=임시 문서 폴더 찾아보기

BIRTConfiguration_document_dialog_message=기본 임시 문서 폴더를 선택하십시오.

BIRTConfiguration_image_label=임시 이미지 폴더(&I):

BIRTConfiguration_image_dialog_title=임시 이미지 폴더 찾아보기

BIRTConfiguration_image_dialog_message=기본 임시 이미지 폴더를 선택하십시오.

BIRTConfiguration_scriptlib_label=ScriptLib 폴더&:

BIRTConfiguration_scriptlib_dialog_title=ScriptLib 폴더 찾아보기

BIRTConfiguration_scriptlib_dialog_message=기본 scriptlib 폴더를 선택하십시오.

BIRTConfiguration_log_label=로그 폴더(&L):

BIRTConfiguration_log_dialog_title=로그 폴더 찾아보기

BIRTConfiguration_log_dialog_message=기본 로그 폴더를 선택하십시오.

BIRTConfiguration_report_access_message=작업 폴더의 보고서 및 문서에만 액세스(&Y)

BIRTConfiguration_overwrite_message=생성된 문서 파일 항상 덮어쓰기(&A)

BIRTConfiguration_maxrows_label=데이터 집합 최대 행(&T):

BIRTConfiguration_maxrowlevels_label=행 수준을 가져오는 최대 큐브(&M):

BIRTConfiguration_maxcolumnlevels_label=열 수준을 가져오는 최대 큐브(&X):

BIRTConfiguration_cubememsize_label=큐브 생성에 필요한 최대 메모리 크기(&Z):

BIRTConfiguration_loglevel_label=로그 수준 선택(&V):

BIRTConfiguration_loglevel_all=모두

BIRTConfiguration_loglevel_severe=심각

BIRTConfiguration_loglevel_warning=경고

BIRTConfiguration_loglevel_info=정보

BIRTConfiguration_loglevel_config=구성

BIRTConfiguration_loglevel_fine=양호

BIRTConfiguration_loglevel_finer=아주 양호

BIRTConfiguration_loglevel_finest=가장 양호

BIRTConfiguration_loglevel_off=끄기

BIRTConfiguration_printserver_label=서버 쪽에서 보고서 인쇄(&P):

BIRTConfiguration_import_clear_message=오래된 BIRT 런타임 파일 지우기(&C)

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=대화 상자 덮어쓰기

BIRTOverwriteQuery_message={0}을(를) 덮어쓰시겠습니까?

BIRTOverwriteQuery_webartifact_title=배포 설명자 덮어쓰기 대화 상자

BIRTOverwriteQuery_webartifact_message={0}이(가) web.xml에 존재합니다. 덮어쓰시겠습니까?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=가져오기가 중단되었습니다. 올바른 원본 ZIP 파일을 가져올 수 없습니다.

BIRTErrors_wrong_webcontent=올바른 웹 컨텐츠 폴더를 가져올 수 없습니다.