###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Neues BIRT-Webprojekt

BIRTProjectConfigurationPage_title=BIRT-Konfiguration
BIRTProjectConfigurationPage_desc=In Datei "web.xml" definierte Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=Einstellungen für Bereitstellungsordner
BIRTConfiguration_group_others=Andere Einstellungen
BIRTConfiguration_folder_button_text=Ordner au&swählen...

BIRTConfiguration_resource_label=&Ressourcenordner:
BIRTConfiguration_resource_dialog_title=Nach Ressourcenordner suchen
BIRTConfiguration_resource_dialog_message=Wählen Sie den Standard-Ressourcenordner:

BIRTConfiguration_working_label=Arbeits&ordner:
BIRTConfiguration_working_dialog_title=Nach Arbeitsordner suchen
BIRTConfiguration_working_dialog_message=Wählen Sie den Standard-Arbeitsordner:

BIRTConfiguration_document_label=&Dokumentordner:
BIRTConfiguration_document_dialog_title=Nach Dokumentordner suchen
BIRTConfiguration_document_dialog_message=Wählen Sie den Standard-Dokumentordner:

BIRTConfiguration_image_label=B&ildordner:
BIRTConfiguration_image_dialog_title=Nach Bildordner suchen
BIRTConfiguration_image_dialog_message=Wählen Sie den Standard-Bildordner:

BIRTConfiguration_scriptlib_label=&ScriptLib-Ordner:
BIRTConfiguration_scriptlib_dialog_title=Nach ScriptLib-Ordner suchen
BIRTConfiguration_scriptlib_dialog_message=Wählen Sie den Standard-ScriptLib-Ordner:

BIRTConfiguration_log_label=Protoko&llordner:
BIRTConfiguration_log_dialog_title=Nach Protokollordner suchen
BIRTConfiguration_log_dialog_message=Wählen Sie den Standard-Protokollordner:

BIRTConfiguration_report_access_message=&Nur auf den Bericht und das Dokument im Arbeitsordner zugreifen
BIRTConfiguration_overwrite_message=Die erstellte Dokumentdatei &immer überschreiben

BIRTConfiguration_maxrows_label=Maximale Zeilenanzahl für &Datensatz:
BIRTConfiguration_loglevel_label=Protokollebene au&swählen:

BIRTConfiguration_import_clear_message=&Alte BIRT Runtime-Dateien löschen.

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Dialogfeld "Überschreiben"
BIRTOverwriteQuery_message={0} überschreiben?

BIRTOverwriteQuery_webartifact_title=Dialogfeld "Bereitstellungs-Deskriptor überschreiben"
BIRTOverwriteQuery_webartifact_message={0} ist in der Datei "web.xml" bereits vorhanden. Überschreiben?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Import beendet. Richtige Quell-ZIP-Datei kann nicht abgerufen werden.
BIRTErrors_wrong_webcontent=Richtiger Webinhaltsordner kann nicht abgerufen werden.
