###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Nuevo proyecto web BIRT

BIRTProjectConfigurationPage_title=Configuración BIRT
BIRTProjectConfigurationPage_desc=Configurar ajustes de implantación de BIRT definidos en web.xml

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=Configurar ajustes de implantación de BIRT

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=Ajustes de carpeta de implantación
BIRTConfiguration_group_others=Otros ajustes
BIRTConfiguration_folder_button_text=&Seleccionar carpeta...

BIRTConfiguration_resource_label=&Carpeta de recursos:
BIRTConfiguration_resource_dialog_title=Buscar carpeta de recursos
BIRTConfiguration_resource_dialog_message=Seleccione la carpeta de recursos predeterminada:

BIRTConfiguration_working_label=&Carpeta de trabajo:
BIRTConfiguration_working_dialog_title=Buscar carpeta de trabajo
BIRTConfiguration_working_dialog_message=Seleccione la carpeta de trabajo predeterminada:

BIRTConfiguration_document_label=Carpeta de &documentos:
BIRTConfiguration_document_dialog_title=Buscar carpeta de documentos
BIRTConfiguration_document_dialog_message=Seleccione la carpeta de documentos predeterminada:

BIRTConfiguration_image_label=Carpeta de &imágenes:
BIRTConfiguration_image_dialog_title=Buscar carpeta de imágenes
BIRTConfiguration_image_dialog_message=Seleccione la carpeta de imágenes predeterminada:

BIRTConfiguration_scriptlib_label=Carpeta de librería de &scripts:
BIRTConfiguration_scriptlib_dialog_title=Buscar carpeta de librería de scripts
BIRTConfiguration_scriptlib_dialog_message=Seleccione la carpeta de librería de scripts predeterminada:

BIRTConfiguration_log_label=Carpeta de &registro:
BIRTConfiguration_log_dialog_title=Buscar carpeta de registro
BIRTConfiguration_log_dialog_message=Seleccione la carpeta de registro predeterminada:

BIRTConfiguration_report_access_message=Acceder sól&o al informe y documento de la carpeta de trabajo
BIRTConfiguration_overwrite_message=Sobrescribir siempre el &archivo de documento generado

BIRTConfiguration_maxrows_label=Número máximo de filas de conjunto de &datos:
BIRTConfiguration_loglevel_label=&Seleccionar nivel de registro:

BIRTConfiguration_import_clear_message=Eliminar los ar&chivos de tiempo de ejecución BIRT antiguos.

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Cuadro de diálogo de sobrescritura
BIRTOverwriteQuery_message=¿Desea sobrescribir {0}?

BIRTOverwriteQuery_webartifact_title=Cuadro de diálogo de sobrescritura de descriptor de implantación
BIRTOverwriteQuery_webartifact_message={0} existe en web.xml. ¿Desea sobrescribirlo?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Importación finalizada. No se puede obtener el archivo zip fuente correcto.
BIRTErrors_wrong_webcontent=No se puede obtener la carpeta de contenido web correcta.
