###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=새 BIRT 웹 프로젝트

BIRTProjectConfigurationPage_title=BIRT 구성
BIRTProjectConfigurationPage_desc=web.xml에서 정의된 BIRT 배포 설정 구성

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=BIRT 배포 설정 구성

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=배포 폴더 설정
BIRTConfiguration_group_others=기타 설정
BIRTConfiguration_folder_button_text=폴더 선택(&S)...

BIRTConfiguration_resource_label=리소스 폴더(&R):
BIRTConfiguration_resource_dialog_title=리소스 폴더 찾아보기
BIRTConfiguration_resource_dialog_message=기본 리소스 폴더를 선택하십시오.

BIRTConfiguration_working_label=&Working Folder:
BIRTConfiguration_working_dialog_title=Browse For Working Folder
BIRTConfiguration_working_dialog_message=Please select the default working folder:

BIRTConfiguration_document_label=문서 폴더(&D):
BIRTConfiguration_document_dialog_title=문서 폴더 찾아보기
BIRTConfiguration_document_dialog_message=기본 문서 폴더를 선택하십시오.

BIRTConfiguration_image_label=이미지 폴더(&I):
BIRTConfiguration_image_dialog_title=이미지 폴더 찾아보기
BIRTConfiguration_image_dialog_message=기본 이미지 폴더를 선택하십시오.

BIRTConfiguration_scriptlib_label=ScriptLib 폴더(&S):
BIRTConfiguration_scriptlib_dialog_title=ScriptLib 폴더 찾아보기
BIRTConfiguration_scriptlib_dialog_message=기본 scriptlib 폴더를 선택하십시오.

BIRTConfiguration_log_label=로그 폴더(&L):
BIRTConfiguration_log_dialog_title=로그 폴더 찾아보기
BIRTConfiguration_log_dialog_message=기본 로그 폴더를 선택하십시오.

BIRTConfiguration_report_access_message=&Only access the report and document under working folder
BIRTConfiguration_overwrite_message=생성된 문서 파일 항상 덮어쓰기(&A) 

BIRTConfiguration_maxrows_label=데이터 집합 최대 행(&D):
BIRTConfiguration_loglevel_label=로그 수준 선택(&S):

BIRTConfiguration_import_clear_message=오래된 BIRT 런타임 파일 지우기(&C)

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=대화 상자 덮어쓰기 
BIRTOverwriteQuery_message={0}을(를) 덮어쓰시겠습니까?

BIRTOverwriteQuery_webartifact_title=배포 설명자 덮어쓰기 대화 상자
BIRTOverwriteQuery_webartifact_message={0}이(가) web.xml에 존재합니다. 덮어쓰시겠습니까?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=가져오기가 중단되었습니다. 올바른 원본 ZIP 파일을 가져올 수 없습니다.
BIRTErrors_wrong_webcontent=올바른 웹 컨텐츠 폴더를 가져올 수 없습니다.
