###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Nouveau projet Web BIRT

BIRTProjectConfigurationPage_title=Configuration BIRT

BIRTProjectConfigurationPage_desc=Configurer les paramètres de déploiement BIRT définis dans web.xml

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=Configurer les paramètres de déploiement BIRT

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=Paramètres du dossier de déploiement

BIRTConfiguration_group_others=Autres paramètres

BIRTConfiguration_resource_folder_button_text=&Parcourir...

BIRTConfiguration_working_folder_button_text=Pa&rcourir...

BIRTConfiguration_document_folder_button_text=Parc&ourir...

BIRTConfiguration_image_folder_button_text=Par&courir...

BIRTConfiguration_scriptlib_folder_button_text=&Parcourir...

BIRTConfiguration_log_folder_button_text=Parco&urir...

BIRTConfiguration_resource_label=Dossier de resso&urces :

BIRTConfiguration_resource_dialog_title=Parcourir le dossier de ressources

BIRTConfiguration_resource_dialog_message=Sélectionnez le dossier de ressources par défaut :

BIRTConfiguration_working_label=Dossier de tra&vail :

BIRTConfiguration_working_dialog_title=Parcourir le dossier de travail

BIRTConfiguration_working_dialog_message=Sélectionnez le dossier de travail par défaut :

BIRTConfiguration_document_label=Dossier de &documents temporaires :

BIRTConfiguration_document_dialog_title=Parcourir le dossier de documents temporaires

BIRTConfiguration_document_dialog_message=Sélectionnez le dossier de documents temporaires par défaut :

BIRTConfiguration_image_label=Dossier d'&images temporaires :

BIRTConfiguration_image_dialog_title=Parcourir le dossier d'images temporaires

BIRTConfiguration_image_dialog_message=Sélectionnez le dossier d'images temporaires par défaut :

BIRTConfiguration_scriptlib_label=Dossier &ScriptLib :

BIRTConfiguration_scriptlib_dialog_title=Parcourir le dossier ScriptLib

BIRTConfiguration_scriptlib_dialog_message=Sélectionnez le dossier ScriptLib par défaut :

BIRTConfiguration_log_label=Dossier du journa&l :

BIRTConfiguration_log_dialog_title=Parcourir le dossier du journal

BIRTConfiguration_log_dialog_message=Sélectionnez le dossier du journal par défaut :

BIRTConfiguration_report_access_message=Accéder u&niquement aux états et documents du dossier de travail

BIRTConfiguration_overwrite_message=Toujours écr&aser le document généré

BIRTConfiguration_maxrows_label=Nombre maximal de lignes de jeux de &données :

BIRTConfiguration_maxrowlevels_label=Lignes &max de récupération de cube :

BIRTConfiguration_maxcolumnlevels_label=Colonnes ma&x de récupération de cube :

BIRTConfiguration_cubememsize_label=Taille maximale de la mémoire ré&servée à la création de cube :

BIRTConfiguration_loglevel_label=Sélectionnez le ni&veau de journalisation :

BIRTConfiguration_loglevel_all=TOUT

BIRTConfiguration_loglevel_severe=SEVERE

BIRTConfiguration_loglevel_warning=AVERTISSEMENT

BIRTConfiguration_loglevel_info=INFOS

BIRTConfiguration_loglevel_config=CONFIG

BIRTConfiguration_loglevel_fine=FIN

BIRTConfiguration_loglevel_finer=MIEUX

BIRTConfiguration_loglevel_finest=PLUS FIN

BIRTConfiguration_loglevel_off=DESACTIVE

BIRTConfiguration_printserver_label=Im&primer l'état sur le serveur :

BIRTConfiguration_import_clear_message=&Effacer les anciens fichiers d'exécution BIRT.

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Boîte de dialogue Ecrasement

BIRTOverwriteQuery_message=Voulez-vous écraser {0} ?

BIRTOverwriteQuery_webartifact_title=Boîte de dialogue Ecraser le descripteur de déploiement

BIRTOverwriteQuery_webartifact_message={0} existe dans web.xml. Souhaitez-vous l'écraser ?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Importation terminée. Impossible d'obtenir le fichier zip source correct.

BIRTErrors_wrong_webcontent=Impossible d'obtenir le contenu Web correct.