###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Neues BIRT-Webprojekt

BIRTProjectConfigurationPage_title=BIRT-Konfiguration

BIRTProjectConfigurationPage_desc=In Datei "web.xml" definierte Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=Einstellungen für Bereitstellungsordner

BIRTConfiguration_group_others=Andere Einstellungen

BIRTConfiguration_resource_folder_button_text=Durchsuchen&...

BIRTConfiguration_working_folder_button_text=Du&rchsuchen...

BIRTConfiguration_document_folder_button_text=Durchs&uchen...

BIRTConfiguration_image_folder_button_text=Durchsu&chen...

BIRTConfiguration_scriptlib_folder_button_text=Durch&suchen...

BIRTConfiguration_log_folder_button_text=Durchsuch&en...

BIRTConfiguration_resource_label=Resso&urcenordner:

BIRTConfiguration_resource_dialog_title=Nach Ressourcenordner suchen

BIRTConfiguration_resource_dialog_message=Wählen Sie den Standard-Ressourcenordner:

BIRTConfiguration_working_label=Arbei&tsordner:

BIRTConfiguration_working_dialog_title=Nach Arbeitsordner suchen

BIRTConfiguration_working_dialog_message=Wählen Sie den Standard-Arbeitsordner:

BIRTConfiguration_document_label=Temporärer &Dokumentordner:

BIRTConfiguration_document_dialog_title=Nach temporärem Dokumentordner durchsuchen

BIRTConfiguration_document_dialog_message=Wählen Sie den standardmäßigen temporären Dokumentordner:

BIRTConfiguration_image_label=Temporärer B&ildordner:

BIRTConfiguration_image_dialog_title=Nach temporärem Bildordner durchsuchen

BIRTConfiguration_image_dialog_message=Wählen Sie den standardmäßigen temporären Bildordner:

BIRTConfiguration_scriptlib_label=ScriptLib-Ordner&:

BIRTConfiguration_scriptlib_dialog_title=Nach ScriptLib-Ordner suchen

BIRTConfiguration_scriptlib_dialog_message=Wählen Sie den Standard-ScriptLib-Ordner:

BIRTConfiguration_log_label=Protoko&llordner:

BIRTConfiguration_log_dialog_title=Nach Protokollordner suchen

BIRTConfiguration_log_dialog_message=Wählen Sie den Standard-Protokollordner:

BIRTConfiguration_report_access_message=Nu&r auf den Bericht und das Dokument im Arbeitsordner zugreifen

BIRTConfiguration_overwrite_message=Die erstellte Dokumentdatei &immer überschreiben

BIRTConfiguration_maxrows_label=Maximale &Datensatzzeilen:

BIRTConfiguration_maxrowlevels_label=&Maximale Abrufzeilenebenen für Quader:

BIRTConfiguration_maxcolumnlevels_label=Ma&ximale Abrufspaltenebenen für Quader:

BIRTConfiguration_cubememsize_label=Maximale Speicherg&röße zum Erstellen von Quadern:

BIRTConfiguration_loglevel_label=Protokolle&bene auswählen:

BIRTConfiguration_loglevel_all=ALLE

BIRTConfiguration_loglevel_severe=SCHWER

BIRTConfiguration_loglevel_warning=WARNUNG

BIRTConfiguration_loglevel_info=INFO

BIRTConfiguration_loglevel_config=KONFIGURATION

BIRTConfiguration_loglevel_fine=FEIN

BIRTConfiguration_loglevel_finer=FEINER

BIRTConfiguration_loglevel_finest=SEHR FEIN

BIRTConfiguration_loglevel_off=AUS

BIRTConfiguration_printserver_label=&Bericht auf Server drucken:

BIRTConfiguration_import_clear_message=&Alte BIRT Runtime-Dateien löschen.

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Dialogfeld "Überschreiben"

BIRTOverwriteQuery_message={0} überschreiben?

BIRTOverwriteQuery_webartifact_title=Dialogfeld "Bereitstellungs-Deskriptor überschreiben"

BIRTOverwriteQuery_webartifact_message={0} ist in der Datei "web.xml" bereits vorhanden. Überschreiben?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Import beendet. Richtige Quell-ZIP-Datei kann nicht abgerufen werden.

BIRTErrors_wrong_webcontent=Richtiger Webinhaltsordner kann nicht abgerufen werden.