###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=BIRT Web プロジェクトの新規作成

BIRTProjectConfigurationPage_title=BIRT の設定

BIRTProjectConfigurationPage_desc=BIRT の配布設定を web.xml に定義します。

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=BIRT の配布設定

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=配布フォルダの設定

BIRTConfiguration_group_others=その他の設定

BIRTConfiguration_resource_folder_button_text=参照(&.)...

BIRTConfiguration_working_folder_button_text=参照(&R)...

BIRTConfiguration_document_folder_button_text=参照(&O)...

BIRTConfiguration_image_folder_button_text=参照(&W)...

BIRTConfiguration_scriptlib_folder_button_text=参照(&S)...

BIRTConfiguration_log_folder_button_text=参照(&E)...

BIRTConfiguration_resource_label=リソースフォルダ(&U) :

BIRTConfiguration_resource_dialog_title=リソースフォルダの参照

BIRTConfiguration_resource_dialog_message=デフォルトのリソースフォルダを選択してください :

BIRTConfiguration_working_label=作業フォルダ(&K) :

BIRTConfiguration_working_dialog_title=作業フォルダを参照

BIRTConfiguration_working_dialog_message=デフォルトの作業フォルダを選択してください :

BIRTConfiguration_document_label=一時文書フォルダ(&D) :

BIRTConfiguration_document_dialog_title=一時文書フォルダの参照

BIRTConfiguration_document_dialog_message=デフォルトの一時文書フォルダを選択してください :

BIRTConfiguration_image_label=一時イメージフォルダ(&I) :

BIRTConfiguration_image_dialog_title=一時イメージフォルダの参照

BIRTConfiguration_image_dialog_message=デフォルトの一時イメージフォルダを選択してください :

BIRTConfiguration_scriptlib_label=ScriptLib フォルダ(&:) :

BIRTConfiguration_scriptlib_dialog_title=ScriptLib フォルダの参照

BIRTConfiguration_scriptlib_dialog_message=デフォルトの ScriptLib フォルダを選択してください :

BIRTConfiguration_log_label=ログフォルダ(&L) :

BIRTConfiguration_log_dialog_title=ログフォルダの参照

BIRTConfiguration_log_dialog_message=デフォルトのログフォルダを選択してください :

BIRTConfiguration_report_access_message=作業フォルダ内のレポートと文書だけにアクセスする(&Y)

BIRTConfiguration_overwrite_message=生成した文書ファイルを常に上書きする(&A)

BIRTConfiguration_maxrows_label=データセットの最大行数(&T) :

BIRTConfiguration_maxrowlevels_label=キューブがフェッチできる最大行レベル(&M) :

BIRTConfiguration_maxcolumnlevels_label=キューブがフェッチできる最大列レベル(&X) :

BIRTConfiguration_cubememsize_label=作成できるキューブの最大メモリサイズ(&Z) :

BIRTConfiguration_loglevel_label=ログレベルの選択(&V) :

BIRTConfiguration_loglevel_all=ALL

BIRTConfiguration_loglevel_severe=SEVERE

BIRTConfiguration_loglevel_warning=WARNING

BIRTConfiguration_loglevel_info=INFO

BIRTConfiguration_loglevel_config=CONFIG

BIRTConfiguration_loglevel_fine=FINE

BIRTConfiguration_loglevel_finer=FINER

BIRTConfiguration_loglevel_finest=FINEST

BIRTConfiguration_loglevel_off=OFF

BIRTConfiguration_printserver_label=レポートをサーバサイドで印刷(&P) :

BIRTConfiguration_import_clear_message=BIRT の古いランタイムファイルを削除する(&C)

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=上書き

BIRTOverwriteQuery_message={0} を上書きしますか ?

BIRTOverwriteQuery_webartifact_title=配布記述子の上書き

BIRTOverwriteQuery_webartifact_message=web.xml に {0} が存在します。上書きしますか ?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=インポート処理が強制終了しました。正しいソース zip ファイルを取得できませんでした。

BIRTErrors_wrong_webcontent=正しい Web コンテンツフォルダを取得できませんでした。