###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Neues BIRT-Webprojekt

BIRTProjectConfigurationPage_title=BIRT-Konfiguration
BIRTProjectConfigurationPage_desc=In Datei "web.xml" definierte Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=Einstellungen für BIRT-Bereitstellung konfigurieren

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=Einstellungen für Bereitstellungsordner
BIRTConfiguration_group_others=Andere Einstellungen

BIRTConfiguration_resource_folder_button_text=Browse&...
BIRTConfiguration_working_folder_button_text=B&rowse...
BIRTConfiguration_document_folder_button_text=Br&owse...
BIRTConfiguration_image_folder_button_text=Bro&wse...
BIRTConfiguration_scriptlib_folder_button_text=Brow&se...
BIRTConfiguration_log_folder_button_text=Brows&e...

BIRTConfiguration_resource_label=Reso&urce Folder:
BIRTConfiguration_resource_dialog_title=Nach Ressourcenordner suchen
BIRTConfiguration_resource_dialog_message=Wählen Sie den Standard-Ressourcenordner:

BIRTConfiguration_working_label=Wor&king Folder:
BIRTConfiguration_working_dialog_title=Nach Arbeitsordner suchen
BIRTConfiguration_working_dialog_message=Wählen Sie den Standard-Arbeitsordner:

BIRTConfiguration_document_label=&Dokumentordner:
BIRTConfiguration_document_dialog_title=Nach Dokumentordner suchen
BIRTConfiguration_document_dialog_message=Wählen Sie den Standard-Dokumentordner:

BIRTConfiguration_image_label=B&ildordner:
BIRTConfiguration_image_dialog_title=Nach Bildordner suchen
BIRTConfiguration_image_dialog_message=Wählen Sie den Standard-Bildordner:

BIRTConfiguration_scriptlib_label=ScriptLib Folder&:
BIRTConfiguration_scriptlib_dialog_title=Nach ScriptLib-Ordner suchen
BIRTConfiguration_scriptlib_dialog_message=Wählen Sie den Standard-ScriptLib-Ordner:

BIRTConfiguration_log_label=Protoko&llordner:
BIRTConfiguration_log_dialog_title=Nach Protokollordner suchen
BIRTConfiguration_log_dialog_message=Wählen Sie den Standard-Protokollordner:

BIRTConfiguration_report_access_message=Onl&y access the report and document under working folder
BIRTConfiguration_overwrite_message=Die erstellte Dokumentdatei &immer überschreiben

BIRTConfiguration_maxrows_label=Maximale &Datensatzzeilen:
BIRTConfiguration_maxrowlevels_label=&Maximale Abrufzeilenebenen für Quader:
BIRTConfiguration_maxcolumnlevels_label=Ma&x cube fetching column levels:
BIRTConfiguration_cubememsize_label=Max memory si&ze for creating cube:

BIRTConfiguration_loglevel_label=Select Log Le&vel:
BIRTConfiguration_loglevel_all=ALLE
BIRTConfiguration_loglevel_severe=SCHWER
BIRTConfiguration_loglevel_warning=WARNUNG
BIRTConfiguration_loglevel_info=INFO
BIRTConfiguration_loglevel_config=KONFIGURATION
BIRTConfiguration_loglevel_fine=FEIN
BIRTConfiguration_loglevel_finer=FEINER
BIRTConfiguration_loglevel_finest=SEHR FEIN
BIRTConfiguration_loglevel_off=AUS

BIRTConfiguration_printserver_label=&Bericht auf Server drucken:

BIRTConfiguration_import_clear_message=&Alte BIRT Runtime-Dateien löschen.

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Dialogfeld "Überschreiben"
BIRTOverwriteQuery_message={0} überschreiben?

BIRTOverwriteQuery_webartifact_title=Dialogfeld "Bereitstellungs-Deskriptor überschreiben"
BIRTOverwriteQuery_webartifact_message={0} ist in der Datei "web.xml" bereits vorhanden. Überschreiben?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Import beendet. Richtige Quell-ZIP-Datei kann nicht abgerufen werden.
BIRTErrors_wrong_webcontent=Richtiger Webinhaltsordner kann nicht abgerufen werden.
