###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=新建 BIRT Web 项目

BIRTProjectConfigurationPage_title=BIRT 配置

BIRTProjectConfigurationPage_desc=配置 web.xml 中定义的 BIRT 部署设置

###############################################################################
# BIRT Configuration Dialog
###############################################################################
BIRTConfigurationDialog_title=配置 BIRT 部署设置

###############################################################################
# BIRT Configuration Components
###############################################################################
BIRTConfiguration_group_paths=部署文件夹设置

BIRTConfiguration_group_others=其它设置

BIRTConfiguration_resource_folder_button_text=浏览(&.)...

BIRTConfiguration_working_folder_button_text=浏览(&R)...

BIRTConfiguration_document_folder_button_text=浏览(&O)...

BIRTConfiguration_image_folder_button_text=浏览(&W)...

BIRTConfiguration_scriptlib_folder_button_text=浏览(&S)...

BIRTConfiguration_log_folder_button_text=浏览(&E)...

BIRTConfiguration_resource_label=资源文件夹(&U):

BIRTConfiguration_resource_dialog_title=浏览资源文件夹

BIRTConfiguration_resource_dialog_message=请选择默认资源文件夹:

BIRTConfiguration_working_label=工作文件夹(&K):

BIRTConfiguration_working_dialog_title=浏览工作文件夹

BIRTConfiguration_working_dialog_message=请选择默认工作文件夹:

BIRTConfiguration_document_label=临时文档文件夹(&D):

BIRTConfiguration_document_dialog_title=浏览临时文档文件夹

BIRTConfiguration_document_dialog_message=请选择默认的临时文档文件夹:

BIRTConfiguration_image_label=临时图像文件夹(&I):

BIRTConfiguration_image_dialog_title=浏览临时图像文件夹

BIRTConfiguration_image_dialog_message=请选择默认的临时图像文件夹:

BIRTConfiguration_scriptlib_label=脚本库文件夹(&:):

BIRTConfiguration_scriptlib_dialog_title=浏览脚本库文件夹

BIRTConfiguration_scriptlib_dialog_message=请选择默认脚本库文件夹:

BIRTConfiguration_log_label=日志文件夹(&L):

BIRTConfiguration_log_dialog_title=浏览日志文件夹

BIRTConfiguration_log_dialog_message=请选择默认日志文件夹:

BIRTConfiguration_report_access_message=仅访问工作文件夹下的报表和文档(&Y)

BIRTConfiguration_overwrite_message=始终覆盖生成的文档文件(&A)

BIRTConfiguration_maxrows_label=数据集最大行数(&T):

BIRTConfiguration_maxrowlevels_label=最大多维数据集取数行级别数(&M):

BIRTConfiguration_maxcolumnlevels_label=最大多维数据集取数列级别数(&X):

BIRTConfiguration_cubememsize_label=用于创建多维数据集的最大内存大小(&Z):

BIRTConfiguration_loglevel_label=选择日志级别(&V):

BIRTConfiguration_loglevel_all=全部

BIRTConfiguration_loglevel_severe=严重

BIRTConfiguration_loglevel_warning=警告

BIRTConfiguration_loglevel_info=信息

BIRTConfiguration_loglevel_config=配置

BIRTConfiguration_loglevel_fine=精细

BIRTConfiguration_loglevel_finer=更精细

BIRTConfiguration_loglevel_finest=最精细

BIRTConfiguration_loglevel_off=关

BIRTConfiguration_printserver_label=在服务器端打印报表(&P):

BIRTConfiguration_import_clear_message=清除旧的 BIRT 运行时文件(&C)。

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=覆盖对话框

BIRTOverwriteQuery_message=要覆盖 {0} 吗?

BIRTOverwriteQuery_webartifact_title=部署描述符覆盖对话框

BIRTOverwriteQuery_webartifact_message=web.xml 中存在 {0}。要覆盖吗?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=导入终止。无法获得正确的源 zip 文件。

BIRTErrors_wrong_webcontent=无法获得正确的 web 内容文件夹。