Element.Crosstab=Tabla de referencias cruzadas

###########################################################
# Crosstab exception
Error.CrosstabException.DUPLICATE_DIMENSION=El elemento de dimensiones cúbicas {0} dispone de un duplicado aplicado para la visualización de dimensiones en la tabla de referencias cruzadas {1}.
Error.CrosstabException.DUPLICATE_MEASURE=El elemento de medidas cúbicas {0} dispone de un duplicado aplicado para la visualización de medidas en la tabla de referencias cruzadas {1}.
Error.CrosstabException.DUPLICATE_LEVEL=