###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=BIRT グラフ作成 Web プロジェクトの新規作成

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=上書き

BIRTOverwriteQuery_message={0} を上書きしますか ?

BIRTOverwriteQuery_webartifact_title=配布記述子の上書き

BIRTOverwriteQuery_webartifact_message=web.xml に {0} が存在します。上書きしますか ?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=インポート処理が強制終了しました。正しいソース zip ファイルを取得できませんでした。

BIRTErrors_wrong_webcontent=正しい Web コンテンツフォルダを取得できませんでした。