###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=新建 BIRT 图表 Web 项目

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=覆盖对话框

BIRTOverwriteQuery_message=要覆盖 {0} 吗?

BIRTOverwriteQuery_webartifact_title=部署描述符覆盖对话框

BIRTOverwriteQuery_webartifact_message=web.xml 中存在 {0}。要覆盖吗?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=导入终止。无法获得正确的源 zip 文件。

BIRTErrors_wrong_webcontent=无法获得正确的 web 内容文件夹。