###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Nuevo proyecto Web de diagramas BIRT

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Cuadro de diálogo de sobrescritura

BIRTOverwriteQuery_message=¿Desea sobrescribir {0}?

BIRTOverwriteQuery_webartifact_title=Cuadro de diálogo de sobrescritura de descriptor de implantación

BIRTOverwriteQuery_webartifact_message={0} existe en web.xml. ¿Desea sobrescribirlo?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Importación finalizada. No se puede obtener el archivo zip fuente correcto.

BIRTErrors_wrong_webcontent=No se puede obtener la carpeta de contenido Web correcta.