###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=Neues BIRT-Diagramm-Webprojekt

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=Dialogfeld "Überschreiben"

BIRTOverwriteQuery_message={0} überschreiben?

BIRTOverwriteQuery_webartifact_title=Dialogfeld "Bereitstellungs-Deskriptor überschreiben"

BIRTOverwriteQuery_webartifact_message={0} ist in der Datei "web.xml" bereits vorhanden. Überschreiben?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=Import beendet. Richtige Quell-ZIP-Datei kann nicht abgerufen werden.

BIRTErrors_wrong_webcontent=Richtiger Webinhaltsordner kann nicht abgerufen werden.