###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# BIRT Wizard Configuration Page
###############################################################################
BIRTProjectCreationWizard_title=새 BIRT 차트 웹 프로젝트

###############################################################################
# Overwrite Query Dialog
###############################################################################
BIRTOverwriteQuery_title=대화 상자 덮어쓰기

BIRTOverwriteQuery_message={0}을(를) 덮어쓰시겠습니까?

BIRTOverwriteQuery_webartifact_title=배포 설명자 덮어쓰기 대화 상자

BIRTOverwriteQuery_webartifact_message={0}이(가) web.xml에 존재합니다. 덮어쓰시겠습니까?

###############################################################################
# Error Message
###############################################################################
BIRTErrors_miss_source=가져오기가 중단되었습니다. 올바른 원본 ZIP 파일을 가져올 수 없습니다.

BIRTErrors_wrong_webcontent=올바른 웹 컨텐츠 폴더를 가져올 수 없습니다.