exception.dataextraction.options.outputstream_required=Se necesita la opción OutputStream y no puede ser nula.

exception.dataextraction.missing_implementation=La subclase debe implementar el método de salida ().

exception.dataextraction.exception_occured=Excepción al extraer los datos.

exception.dataextraction.no_extraction_result_error=No se han encontrado resultados en la tarea de ejecución.
