exception.dataextraction.options.outputstream_required=L'option OutputStream est nécessaire et ne peut pas être nulle.

exception.dataextraction.missing_implementation=La méthode de sortie() doit être implémentée par la sous-classe.

exception.dataextraction.exception_occured=Une exception s'est produite lors de l'extraction des données.

exception.dataextraction.no_extraction_result_error=Aucun résultat n'a été trouvé lors de la tâche d'exécution.
