exception.dataextraction.options.outputstream_required=Die OutputStream-Option ist erforderlich und darf nicht Null sein.

exception.dataextraction.missing_implementation=Die output()-Methode muss von der Unterklasse implementiert werden.

exception.dataextraction.exception_occured=Ausnahme beim Extrahieren von Daten.

exception.dataextraction.no_extraction_result_error=Keine Ergebnisse in der Ausführungsaufgabe gefunden.
