JavaxImageIOWriter.exception.no.bounds=Les limites de l'image doivent être précisées avant le début du rendu

JavaxImageIOWriter.exception.invalid.image.size=La largeur ou la hauteur de l'image donnée est incorrecte(<=0).

JavaxImageIOWriter.exception.no.imagewriter.mimetype.and.format=Impossible de détecter un éditeur d''images enregistré pour le type mime [{0}] et le format [{1}] pour {2}

JavaxImageIOWriter.exception.no.imagewriter.mimetype=Impossible de détecter un éditeur d''images enregistré pour le type mime [{0}]

JavaxImageIOWriter.info.using.imagewriter=Utilisation de l''éditeur d''images {0} {1}

JavaxImageIOWriter.exception.caption=Exception :

JavaxImageIOWriter.wrapped.caption=Réparti dans :

JavaxImageIOWriter.message.caption=Message :

JavaxImageIOWriter.trace.caption=Trace :

JavaxImageIOWriter.trace.detail={0}:{1}(...):{2}
Chunk.exception.invalid.png.chunk=Type d'unité PNG incorrect : {0}

BmpRendererImpl.exception.unable.write.output.identifier=Impossible d''écrire l''image du graphique vers le descripteur de sortie défini par [{0}]

BmpRendererImpl.info.use.custom.image.writer=Utilisation de l"éditeur d'images personnalisées [{1}] avec un type d''image [{0}]

PngWriter.exception.error.open.fileoutputstream=IOException survenue lors de l''ouverture de FileOutputStream : {0}

PngWriter.exception.error.create.imageproducer=Impossible de créer le générateur d''image

PngWriter.error.fail.cleanup.tempfile=Echec du nettoyage du fichier temporaire [{0}]

PngWriter.error.open.randomaccessfile=IOException survenue lors de l''ouverture de RandomAccessFile : {0}

PngWriter.info.save.elapse.time=Enregistrer l''image en tant que {0} [temps écoulé = {1} ms]

SwingImageCache.exception.media.tracker=MediaTracker a renvoyé une erreur dans {0}

SwingImageCache.info.loading.swing.image=Chargement de l''image SWING depuis {0}

SwingImageCache.info.using.swing.cached.image=Utilisation de l''image SWING en cache depuis {0}

SwingImageCache.info.flushed.swing.images=Image(s) SWING en cache vidée(s) {0}

SwingRendererImpl.exception.gradient.angle=Impossible de créer un rendu de dégradé à l''angle={0} ; la fourchette prise en charge est [90 >= 0 >= -90]

SwingRendererImpl.exception.unspecified.text.rendering.action=Action de rendu de texte non spécifiée ; la commande TextRenderEvent.setAction(...) n'a pas été appelée correctement

SwingRendererImpl.exception.missing.component.interaction=Impossible d'autoriser l'interaction si aucun IUpdateNotifier n'est associé au moteur de rendu.

SwingRendererImpl.info.using.graphics.context=Utilisation du contexte graphique {0}

SwingTextMetrics.exception.undefined.shadow.color=Rendu d'ombre impossible avec une couleur non définie

SwingTextMetrics.exception.undefined.text.color=Rendu de texte impossible avec une couleur non définie

SwingEventHandler.info.toggle.visibility=Basculer la visibilité : {0}

SwingEventHandler.info.toggle.datapoint.visibility=Basculer la visibilité du point de données : {0}

SwingEventHandler.info.cannot.find.series=Impossible de trouver la série heure de conception pour la série heure d''exécution : {0}

SwingEventHandler.info.improper.callback.notifier=Notificateur : [{0}] est détecté, mais un implémenteur ICallBackNotifer est attendu.

SwingEventHandler.info.redirect.url=Rediriger vers l''URL : {0}

SwingDisplayServer.info.display.server=Serveur d''affichage SWING : {0} version {1}
