JavaxImageIOWriter.exception.no.bounds=Los límites de la imagen se deben especificar antes de iniciar el procesamiento

JavaxImageIOWriter.exception.invalid.image.size=La anchura o altura indicada de la imagen no es válida(<=0).

JavaxImageIOWriter.exception.no.imagewriter.mimetype.and.format=No es posible encontrar ningún redactor de imágenes registrado para el tipo de MIME [{0}] y formato [{1}] para {2}

JavaxImageIOWriter.exception.no.imagewriter.mimetype=No es posible encontrar ningún redactor de imágenes registrado para el tipo de MIME [{0}]

JavaxImageIOWriter.info.using.imagewriter=Uso de redactor de imágenes {0} {1}

JavaxImageIOWriter.exception.caption=Excepción:

JavaxImageIOWriter.wrapped.caption=Empaquetado en:

JavaxImageIOWriter.message.caption=Mensaje:

JavaxImageIOWriter.trace.caption=Rastreo:

JavaxImageIOWriter.trace.detail={0}:{1}(...):{2}
Chunk.exception.invalid.png.chunk=Tipo de trozo PNG no válido: {0}

BmpRendererImpl.exception.unable.write.output.identifier=No es posible escribir la imagen del diagrama a un controlador de salida definido por [{0}]

BmpRendererImpl.info.use.custom.image.writer=Uso del redactor de imágenes personalizadas [{1}] para el tipo de imagen [{0}]

PngWriter.exception.error.open.fileoutputstream=IOException al abrir FileOutputStream : {0}

PngWriter.exception.error.create.imageproducer=No es posible crear el productor de imagen

PngWriter.error.fail.cleanup.tempfile=Error al limpiar el archivo temporal [{0}]

PngWriter.error.open.randomaccessfile=IOException al abrir RandomAccessFile: {0}

PngWriter.info.save.elapse.time=Guardar imagen como {0} [elapsed = {1} ms]

SwingImageCache.exception.media.tracker=MediaTracker ha devuelto un error en {0}

SwingImageCache.info.loading.swing.image=Cargando imagen SWING de {0}

SwingImageCache.info.using.swing.cached.image=Uso de imagen SWING en caché desde {0}

SwingImageCache.info.flushed.swing.images=Vaciado de {0} imágenes SWIN en caché

SwingRendererImpl.exception.gradient.angle=No se puede procesar un gradiente con el ángulo={0}; el intervalo admitido es [90 >= 0 >= -90]

SwingRendererImpl.exception.unspecified.text.rendering.action=Acción de procesamiento de texto sin especificar; no se ha llamado correctamente a TextRenderEvent.setAction(...).

SwingRendererImpl.exception.missing.component.interaction=No se puede activar la interacción si no se asocia un IUpdateNotifier con el procesador.

SwingRendererImpl.info.using.graphics.context=Uso de contexto de gráficos {0}

SwingTextMetrics.exception.undefined.shadow.color=No se puede procesar la sombra con un color sin definir

SwingTextMetrics.exception.undefined.text.color=No se puede procesar el texto con un color sin definir

SwingEventHandler.info.toggle.visibility=Alternar visibilidad: {0}

SwingEventHandler.info.toggle.datapoint.visibility=Alternar visibilidad del punto de datos: {0}

SwingEventHandler.info.cannot.find.series=No es posible localizar la serie de tiempo de diseño para la serie de tiempo de ejecución: {0}

SwingEventHandler.info.improper.callback.notifier=Se ha detectado un notificador [{0}], pero se espera un implementador ICallBackNotifer.

SwingEventHandler.info.redirect.url=Redirigir a URL: {0}

SwingDisplayServer.info.display.server=Servidor de visualización SWING: {0} v{1}
