JavaxImageIOWriter.exception.no.bounds=レンダリングを開始する前に、イメージの範囲を指定する必要があります。

JavaxImageIOWriter.exception.invalid.image.size=イメージの幅または高さに、無効な負の数値が指定されました。

JavaxImageIOWriter.exception.no.imagewriter.mimetype.and.format=MIME 型 [{0}] および {2} 用の [{1}] 形式に対応する登録済みのイメージライターが見つかりません。

JavaxImageIOWriter.exception.no.imagewriter.mimetype=MIME 型 [{0}] に対応する登録済みのイメージライターが見つかりません。

JavaxImageIOWriter.info.using.imagewriter={0} イメージライター {1} を使用中

JavaxImageIOWriter.exception.caption=例外 :

JavaxImageIOWriter.wrapped.caption=ネスト先 :

JavaxImageIOWriter.message.caption=メッセージ :

JavaxImageIOWriter.trace.caption=トレース :

JavaxImageIOWriter.trace.detail={0}:{1}(...):{2}
Chunk.exception.invalid.png.chunk=PNG テキストブロックの種類が無効です : {0}

BmpRendererImpl.exception.unable.write.output.identifier=[{0}] で定義した出力ハンドルにグラフイメージを書き込めません。

BmpRendererImpl.info.use.custom.image.writer=イメージの種類 [{0}] にカスタムイメージライター [{1}] を使用中

PngWriter.exception.error.open.fileoutputstream=FileOutputStream を開くときに IOException が発生しました : {0}

PngWriter.exception.error.create.imageproducer=イメージ生成を作成できません。

PngWriter.error.fail.cleanup.tempfile=一時ファイル [{0}] をクリーンアップすることができませんでした。

PngWriter.error.open.randomaccessfile=RandomAccessFile を開くときに IOException が発生しました : {0}

PngWriter.info.save.elapse.time=イメージを {0} 形式で保存 [経過時間 = {1} ms]

SwingImageCache.exception.media.tracker=MediaTracker から {0} のエラーが返されました。

SwingImageCache.info.loading.swing.image={0} から SWING イメージを読み込み中

SwingImageCache.info.using.swing.cached.image=キャッシュされた SWING イメージを {0} から読み込み中

SwingImageCache.info.flushed.swing.images=キャッシュされた {0} 個の SWING イメージがフラッシュされました。

SwingRendererImpl.exception.gradient.angle=角度が {0} のグラデーションはレンダリングできません。レンダリング可能な角度は [90 >= 0 >= -90] です。

SwingRendererImpl.exception.unspecified.text.rendering.action=テキストのレンダリング中に例外が発生しました。TextRenderEvent.setAction(...) が正しく呼び出されませんでした。

SwingRendererImpl.exception.missing.component.interaction=IUpdateNotifier はレンダリング機能と関連付けらていないため、操作できません。

SwingRendererImpl.info.using.graphics.context=図形コンテキスト {0} を使用中

SwingTextMetrics.exception.undefined.shadow.color=未定義の色を使用している影はレンダリングできません。

SwingTextMetrics.exception.undefined.text.color=未定義の色を使用しているテキストはレンダリングできません。

SwingEventHandler.info.toggle.visibility=表示と非表示の切り替え : {0}

SwingEventHandler.info.toggle.datapoint.visibility=データポイントの表示と非表示を切り替える : {0}

SwingEventHandler.info.cannot.find.series=実行時系列に使用する設計時系列が見つかりません : {0}

SwingEventHandler.info.improper.callback.notifier=通知ツール [{0}] が検出されましたが、ICallBackNotifer インプリメンタが必要です。

SwingEventHandler.info.redirect.url=次の URL に転送 : {0}

SwingDisplayServer.info.display.server=SWING Display Server: {0} v{1}
