JavaxImageIOWriter.exception.no.bounds=렌더링을 시작하기 전에 이미지의 바인딩을 지정해야 합니다.

JavaxImageIOWriter.exception.invalid.image.size=지정된 이미지의 너비 또는 높이가 잘못되었습니다(<=0).

JavaxImageIOWriter.exception.no.imagewriter.mimetype.and.format={2}의 MIME 형식 [{0}] 및 형식 [{1}]에 대해 등록된 이미지 작성기를 찾을 수 없습니다.

JavaxImageIOWriter.exception.no.imagewriter.mimetype=MIME 형식 [{0}]에 대해 등록된 이미지 작성기를 찾을 수 없습니다.

JavaxImageIOWriter.info.using.imagewriter={0} 이미지 작성기 {1} 사용

JavaxImageIOWriter.exception.caption=예외:

JavaxImageIOWriter.wrapped.caption=랩 위치:

JavaxImageIOWriter.message.caption=메시지:

JavaxImageIOWriter.trace.caption=추적:

JavaxImageIOWriter.trace.detail={0}:{1}(...):{2}
Chunk.exception.invalid.png.chunk=잘못된 PNG 청크 형식: {0}

BmpRendererImpl.exception.unable.write.output.identifier=[{0}]에서 정의된 출력 핸들에 차트 이미지를 쓸 수 없습니다.

BmpRendererImpl.info.use.custom.image.writer=이미지 형식 [{0}]에 대해 사용자 지정 이미지 작성기 [{1}] 사용

PngWriter.exception.error.open.fileoutputstream=FileOutputStream을 여는 동안 IOException 발생 : {0}

PngWriter.exception.error.create.imageproducer=이미지 제작자를 만들 수 없습니다.

PngWriter.error.fail.cleanup.tempfile=[{0}] 임시 파일을 정리하지 못했습니다.

PngWriter.error.open.randomaccessfile=RandomAccessFile을 여는 동안 RandomAccessFile 발생 : {0}

PngWriter.info.save.elapse.time={0}으로 이미지 저장 [경과 시간 = {1} ms]

SwingImageCache.exception.media.tracker=MediaTracker가 {0}에서 오류를 반환했습니다.

SwingImageCache.info.loading.swing.image={0}에서 SWING 이미지를 로드하는 중

SwingImageCache.info.using.swing.cached.image={0}에서 캐시된 SWING 이미지 사용

SwingImageCache.info.flushed.swing.images={0}개의 캐시된 SWING 이미지가 플러시되었습니다.

SwingRendererImpl.exception.gradient.angle=각도={0}에서 그라데이션을 렌더링할 수 없습니다. 지원되는 범위는 [90 >= 0 >= -90]입니다.

SwingRendererImpl.exception.unspecified.text.rendering.action=지정되지 않은 텍스트 렌더링 작업입니다. TextRenderEvent.setAction(...)이 올바르게 호출되지 않았습니다.

SwingRendererImpl.exception.missing.component.interaction=IUpdateNotifier가 렌더러와 연결되어 있지 않으면 상호 작용을 사용할 수 없습니다.

SwingRendererImpl.info.using.graphics.context=그래픽 컨텍스트 {0} 사용

SwingTextMetrics.exception.undefined.shadow.color=그림자를 정의되지 않은 색으로 렌더링할 수 없습니다.

SwingTextMetrics.exception.undefined.text.color=텍스트를 정의되지 않은 색으로 렌더링할 수 없습니다.

SwingEventHandler.info.toggle.visibility=표시 유형 전환: {0}

SwingEventHandler.info.toggle.datapoint.visibility=데이터 요소 표시 유형 전환: {0}

SwingEventHandler.info.cannot.find.series=런타임 계열에 대한 디자인 타임 계열을 찾을 수 없습니다: {0}

SwingEventHandler.info.improper.callback.notifier=알림: [{0}]이(가) 검색되었지만 ICallBackNotifer 실행자가 필요합니다.

SwingEventHandler.info.redirect.url=다음 URL로 리디렉션: {0}

SwingDisplayServer.info.display.server=SWING Display Server: {0} v{1}
