/*******************************************************************************
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/.
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   See git history
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. PropertyParserConstants.java */
package org.eclipse.birt.report.model.css.property;

public interface PropertyParserConstants {

	int EOF = 0;
	int S = 1;
	int INHERIT = 2;
	int CDO = 3;
	int CDC = 4;
	int LBRACE = 5;
	int RBRACE = 6;
	int DASHMATCH = 7;
	int INCLUDES = 8;
	int PREFIXMATCH = 9;
	int SUFFIXMATCH = 10;
	int SUBSTRINGMATCH = 11;
	int TILDE = 12;
	int EQ = 13;
	int PLUS = 14;
	int MINUS = 15;
	int COMMA = 16;
	int SEMICOLON = 17;
	int PRECEDES = 18;
	int DIV = 19;
	int LBRACKET = 20;
	int RBRACKET = 21;
	int ANY = 22;
	int DOT = 23;
	int LPARAN = 24;
	int RPARAN = 25;
	int AND = 26;
	int MEDIARESTRICTOR = 27;
	int NONASCII = 28;
	int H = 29;
	int UNICODE = 30;
	int ESCAPE = 31;
	int NMSTART = 32;
	int NMCHAR = 33;
	int STRINGCHAR = 34;
	int D = 35;
	int NAME = 36;
	int STRING = 37;
	int NUMBER = 38;
	int _URL = 39;
	int URL = 40;
	int PERCENTAGE = 41;
	int LENGTH = 42;
	int ABSOLUTE_SIZE = 43;
	int RELATIVE_SIZE = 44;
	int COLOR = 45;
	int NORMAL = 46;
	int AUTO = 47;
	int FONT_VAL = 48;
	int FONT_STYLE = 49;
	int FONT_VARIANT = 50;
	int FONT_WEIGHT = 51;
	int BACKGROUND_REPEAT = 52;
	int BACKGROUND_ATTACHMENT = 53;
	int BACKGROUND_POSITION = 54;
	int BORDER_STYLE = 55;
	int BORDER_WIDTH = 56;
	int IDENT = 57;
	int DIMEN = 58;
	int HASH = 59;
	int RANGE0 = 60;
	int RANGE1 = 61;
	int RANGE2 = 62;
	int RANGE3 = 63;
	int RANGE4 = 64;
	int RANGE5 = 65;
	int RANGE6 = 66;
	int RANGE = 67;
	int UNI = 68;
	int UNICODERANGE = 69;
	int FUNCTION = 70;
	int UNKNOWN = 71;

	int DEFAULT = 0;
	int IN_COMMENT = 1;

	String[] tokenImage = { "<EOF>", "<S>", "\"inherit\"", "\"<!--\"", "\"-->\"", "\"{\"", "\"}\"", "\"|=\"", "\"~=\"",
			"\"^=\"", "\"$=\"", "\"*=\"", "\"~\"", "\"=\"", "\"+\"", "\"-\"", "\",\"", "\";\"", "\">\"", "\"/\"",
			"\"[\"", "\"]\"", "\"*\"", "\".\"", "\")\"", "\"(\"", "<AND>", "<MEDIARESTRICTOR>", "<NONASCII>", "<H>",
			"<UNICODE>", "<ESCAPE>", "<NMSTART>", "<NMCHAR>", "<STRINGCHAR>", "<D>", "<NAME>", "<STRING>", "<NUMBER>",
			"<_URL>", "<URL>", "<PERCENTAGE>", "<LENGTH>", "<ABSOLUTE_SIZE>", "<RELATIVE_SIZE>", "<COLOR>",
			"\"normal\"", "\"auto\"", "<FONT_VAL>", "<FONT_STYLE>", "\"small-caps\"", "<FONT_WEIGHT>",
			"<BACKGROUND_REPEAT>", "<BACKGROUND_ATTACHMENT>", "<BACKGROUND_POSITION>", "<BORDER_STYLE>",
			"<BORDER_WIDTH>", "<IDENT>", "<DIMEN>", "<HASH>", "<RANGE0>", "<RANGE1>", "<RANGE2>", "<RANGE3>",
			"<RANGE4>", "<RANGE5>", "<RANGE6>", "<RANGE>", "<UNI>", "<UNICODERANGE>", "<FUNCTION>", "<UNKNOWN>", };

}
