###############################################################################
# Copyright (c) 2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.chart=차트

menu.lable.chart=차트(&C)

preference.description=차트 항목을 삽입합니다.