###############################################################################
# Copyright (c) 2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.chart=グラフ

menu.lable.chart=グラフ(&C)

preference.description=グラフ項目の挿入