#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
ExcelEmitter.Description=Optionen zum Rendern eines Berichts im Format XML Spreadsheet 2003 konfigurieren.

ExcelEmitter.DisplayName=Excel (XLS)

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=Zeilenumbruch aktivieren

OptionDisplayValue.OfficeVersion=Ausgabeversion:

OptionDisplayValue.Office2003=Microsoft Office 2003
OptionDisplayValue.Office2007=Microsoft Office 2007
OptionDisplayValue.ChartDpi=Diagramm-DPI

OptionDisplayValue.HideGridlines=Rasterlinien ausblenden

###########################################################
#Option Description
OptionDescription.WrappingText=Gibt an, ob der Text Zeilenumbrüche enthält.

OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

OptionDescription.HideGridlines=Rasterlinien ausblenden.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.