#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
ExcelEmitter.Description=XML スプレッドシート 2003 形式でレポートをレンダリングするためのオプションを設定します。
ExcelEmitter.DisplayName=Excel (XML スプレッドシート 2003)

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=文字列の折り返しを有効にする
OptionDisplayValue.OfficeVersion=出力バージョン :
OptionDisplayValue.Office2003=Microsoft Office 2003
OptionDisplayValue.Office2007=Microsoft Office 2007
OptionDisplayValue.ChartDpi=Chart DPI

###########################################################
#Option Description
OptionDescription.WrappingText=文字列を折り返すかどうかを示します。
OptionDescription.ChartDpi=The DPI used to generate chart.
