#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
ExcelEmitter.Description=Configure las opciones para presentar un informe en formato de hoja de cálculo XML 2003.
ExcelEmitter.DisplayName=Excel (hoja de cálculo XML 2003)

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=Activar autoajuste de texto
OptionDisplayValue.OfficeVersion=Versión de salida:
OptionDisplayValue.Office2003=Microsoft Office 2003
OptionDisplayValue.Office2007=Microsoft Office 2007
OptionDisplayValue.ChartDpi=Chart DPI

###########################################################
#Option Description
OptionDescription.WrappingText=Indica si el texto se puede autoajustar.
OptionDescription.ChartDpi=The DPI used to generate chart.
