#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
ExcelEmitter.Description=Configurez les options pour un rendu de rapport au format feuille de calcul XML 2003.

ExcelEmitter.DisplayName=Excel (XLS)

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=Activer le retour à la ligne automatique

OptionDisplayValue.OfficeVersion=Version de sortie :

OptionDisplayValue.Office2003=Microsoft Office 2003
OptionDisplayValue.Office2007=Microsoft Office 2007
OptionDisplayValue.ChartDpi=DPI de graphique

OptionDisplayValue.HideGridlines=Cacher les lignes de la grille

###########################################################
#Option Description
OptionDescription.WrappingText=Indique si le retour à la ligne est autorisé pour le texte.

OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

OptionDescription.HideGridlines=Cacher les lignes de la grille.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.