#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=Abfrageportwert nicht vorhanden.

ReportLauncher.FailToStartDebugServer=Debug-Server konnte nicht gestartet werden.

ReportLauncher.FailToStartReportPlatform=Berichtplattform konnte nicht gestartet werden.

ReportLauncher.UserClassPathReceived=Benutzerklassenpfad erhalten:

ReportLauncher.EngineException=Ausnahme Engine

ReportLauncher.IOException=Ausnahme IO

########################################
#ReportVMClient
ReportVMClient.ServerConnected=[Client] Server verbunden

ReportVMClient.ServerShutDown=[Client] Server bereits heruntergefahren

ReportVMClient.ClientDisconnected=[Client] Client-Verbindung getrennt

ReportVMClient.EnterEventDispatching=[Client] hat Ereignis-Dispatch eingeleitet

ReportVMClient.ReceivedVMEvent=[Client] hat VM-Ereignis erhalten:

ReportVMClient.ServerShuttingDown=[Client] Server wird heruntergefahren

ReportVMClient.RequestIgnored.ServerDisconnected=[Client] Server-Verbindung bereits getrennt, Auftrag ignoriert:

ReportVMClient.RequestIgnored.ServerShuttingDown=[Client] Server wird heruntergefahren, Auftrag ignoriert:

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=[Server] Client akzeptiert

ReportVMServer.ClientDisconnected=[Server] Client-Verbindung getrennt

ReportVMServer.ServerShutDown=[Server] Server ist heruntergefahren

ReportVMServer.EnterRequestDispatching=[Server] hat Auftrags-Dispatch eingeleitet

ReportVMServer.ReceivedRequest=[Server] hat Auftrag erhalten:

ReportVMServer.SendBackResponse=[Server] sendet Antwort

ReportVMServer.ServerShuttingDown=[Server] Server wird heruntergefahren

ReportVMServer.SendVMEvent=[Server] sendet VM-Ereignis:
