#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=La valeur du port de la requête est manquante.

ReportLauncher.FailToStartDebugServer=Echec du démarrage du serveur de débogage.

ReportLauncher.FailToStartReportPlatform=Echec du démarrage de la plateforme de rapport.

ReportLauncher.UserClassPathReceived=Chemin de classe de l'utilisateur reçu :

ReportLauncher.EngineException=Exception du moteur

ReportLauncher.IOException=Exception E/S

########################################
#ReportVMClient
ReportVMClient.ServerConnected=Serveur [Client] connecté

ReportVMClient.ServerShutDown=Serveur [Client] déjà arrêté

ReportVMClient.ClientDisconnected=Client [Client] déconnecté

ReportVMClient.EnterEventDispatching=[Client] entre la distribution de l'événement

ReportVMClient.ReceivedVMEvent=[Client] a reçu un événement vm :

ReportVMClient.ServerShuttingDown=Arrêt du serveur [Client] en cours

ReportVMClient.RequestIgnored.ServerDisconnected=Serveur [Client] déjà déconnecté, requête ignorée :

ReportVMClient.RequestIgnored.ServerShuttingDown=Arrêt du serveur [Client] en cours, requête ignorée :

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=Client [Serveur] accepté

ReportVMServer.ClientDisconnected=Client [Serveur] déconnecté

ReportVMServer.ServerShutDown=Serveur [Serveur] arrêté

ReportVMServer.EnterRequestDispatching=[Serveur] entre la distribution de la requête

ReportVMServer.ReceivedRequest=[Serveur] a reçu une requête :

ReportVMServer.SendBackResponse=[Serveur] renvoie une réponse

ReportVMServer.ServerShuttingDown=Arrêt du serveur [Serveur] en cours

ReportVMServer.SendVMEvent=[Serveur] envoie un événement vm :
