#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=缺少请求端口值。

ReportLauncher.FailToStartDebugServer=无法启动调试服务器。

ReportLauncher.FailToStartReportPlatform=无法启动报表平台。

ReportLauncher.UserClassPathReceived=收到的用户类路径:

ReportLauncher.EngineException=引擎异常

ReportLauncher.IOException=IO 异常

########################################
#ReportVMClient
ReportVMClient.ServerConnected=[客户端] 服务器已连接

ReportVMClient.ServerShutDown=[客户端] 服务器已关闭

ReportVMClient.ClientDisconnected=[客户端] 客户端已断开连接

ReportVMClient.EnterEventDispatching=[客户端] 进入事件调度

ReportVMClient.ReceivedVMEvent=[客户端] 接收的 vm 事件:

ReportVMClient.ServerShuttingDown=[客户端] 服务器正在关闭

ReportVMClient.RequestIgnored.ServerDisconnected=[客户端] 服务器已断开连接，已忽略请求:

ReportVMClient.RequestIgnored.ServerShuttingDown=[客户端] 服务器正在关闭，已忽略请求:

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=[服务器] 客户端已接受

ReportVMServer.ClientDisconnected=[Server] 客户端已断开连接

ReportVMServer.ServerShutDown=[服务器] 服务器已关闭

ReportVMServer.EnterRequestDispatching=[服务器] 进入请求调度

ReportVMServer.ReceivedRequest=[服务器] 接收的请求:

ReportVMServer.SendBackResponse=[服务器] 发回响应

ReportVMServer.ServerShuttingDown=[服务器] 服务器正在关闭

ReportVMServer.SendVMEvent=[服务器] 发送 vm 事件:
