#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=リクエストされたポートの値がありません。

ReportLauncher.FailToStartDebugServer=デバッグサーバを起動できません。

ReportLauncher.FailToStartReportPlatform=レポートプラットフォームを起動できません。

ReportLauncher.UserClassPathReceived=ユーザクラスパスを受け付けました :

ReportLauncher.EngineException=エンジンの例外が発生しました。

ReportLauncher.IOException=IO の例外が発生しました。

########################################
#ReportVMClient
ReportVMClient.ServerConnected=[クライアント] サーバに接続しました。

ReportVMClient.ServerShutDown=[クライアント] サーバはすでにシャットダウンしています。

ReportVMClient.ClientDisconnected=[クライアント] クライアントは切断されました。

ReportVMClient.EnterEventDispatching=[クライアント] イベントディスパッチングを入力してください。

ReportVMClient.ReceivedVMEvent=[クライアント]vm イベントを受け付けました:

ReportVMClient.ServerShuttingDown=[クライアント] サーバをシャットダウンしています。

ReportVMClient.RequestIgnored.ServerDisconnected=[クライアント] サーバはすでに切断されています。リクエストは無視されました :

ReportVMClient.RequestIgnored.ServerShuttingDown=[クライアント] サーバをシャットダウンしています。リクエストは無視されました :

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=[サーバ] クライアントが受け付けました。

ReportVMServer.ClientDisconnected=[サーバ] クライアントが切断されました。

ReportVMServer.ServerShutDown=[サーバ] サーバをシャットダウンしています。

ReportVMServer.EnterRequestDispatching=[サーバ] リクエストディスパッチングを入力してください。

ReportVMServer.ReceivedRequest=[サーバ] リクエストを受け付けました:

ReportVMServer.SendBackResponse=[サーバ] 応答を返信しました。

ReportVMServer.ServerShuttingDown=[サーバ] サーバをシャットダウンしています。

ReportVMServer.SendVMEvent=[サーバ]vm イベントを送信しました:
