#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=El valor de puerto de la solicitud se encuentra ausente.

ReportLauncher.FailToStartDebugServer=No se ha podido iniciar el servidor de depuración.

ReportLauncher.FailToStartReportPlatform=No se ha podido iniciar la plataforma de informes.

ReportLauncher.UserClassPathReceived=Se ha recibido la ruta de clase de usuario:

ReportLauncher.EngineException=Excepción del motor

ReportLauncher.IOException=Excepción de E/S

########################################
#ReportVMClient
ReportVMClient.ServerConnected=Conectado al servidor [Cliente]

ReportVMClient.ServerShutDown=El servidor [Cliente] ya está cerrado

ReportVMClient.ClientDisconnected=El cliente [Cliente] se ha desconectado

ReportVMClient.EnterEventDispatching=[Cliente] introduce la distribución de eventos

ReportVMClient.ReceivedVMEvent=[Cliente] ha recibido el evento vm:

ReportVMClient.ServerShuttingDown=El servidor [Cliente] se está cerrando

ReportVMClient.RequestIgnored.ServerDisconnected=El servidor [Cliente] ya se ha desconectado, se ha omitido la solicitud:

ReportVMClient.RequestIgnored.ServerShuttingDown=El servidor [Cliente] se está cerrando, se ha omitido la solicitud:

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=El cliente [Servidor] ha sido aceptado

ReportVMServer.ClientDisconnected=El cliente [Servidor] se ha desconectado

ReportVMServer.ServerShutDown=El servidor [Servidor] está cerrado

ReportVMServer.EnterRequestDispatching=[Servidor] introduce la distribución de solicitudes

ReportVMServer.ReceivedRequest=[Servidor] ha recibido la solicitud:

ReportVMServer.SendBackResponse=[Servidor] ha enviado una repuesta

ReportVMServer.ServerShuttingDown=El servidor [Servidor] se está cerrando

ReportVMServer.SendVMEvent=[Servidor] ha enviado un evento vm:
