#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
#ReportLauncher
ReportLauncher.PortValueAbsent=포트 값 요청이 없습니다.

ReportLauncher.FailToStartDebugServer=디버그 서버를 시작하지 못했습니다.

ReportLauncher.FailToStartReportPlatform=보고서 플랫폼을 시작하지 못했습니다.

ReportLauncher.UserClassPathReceived=받은 사용자 클래스 경로:

ReportLauncher.EngineException=엔진 예외

ReportLauncher.IOException=IO 예외

########################################
#ReportVMClient
ReportVMClient.ServerConnected=[클라이언트] 서버가 연결되었습니다.

ReportVMClient.ServerShutDown=[클라이언트] 서버가 이미 종료되었습니다.

ReportVMClient.ClientDisconnected=[클라이언트] 클라이언트 연결이 끊겼습니다.

ReportVMClient.EnterEventDispatching=[클라이언트]에서 발송 중인 이벤트를 입력합니다.

ReportVMClient.ReceivedVMEvent=[클라이언트]에서 받은 vm 이벤트:

ReportVMClient.ServerShuttingDown=[클라이언트] 서버를 종료하고 있습니다.

ReportVMClient.RequestIgnored.ServerDisconnected=[클라이언트] 서버 연결이 이미 끊겼으므로 요청이 무시됩니다.

ReportVMClient.RequestIgnored.ServerShuttingDown=[클라이언트] 서버를 종료하고 있으므로 요청이 무시됩니다.

########################################
#ReportVMServer
ReportVMServer.ClientAccpted=[서버] 클라이언트가 수락되었습니다.

ReportVMServer.ClientDisconnected=[Server] 클라이언트 연결이 끊겼습니다.

ReportVMServer.ServerShutDown=[서버] 서버를 종료합니다.

ReportVMServer.EnterRequestDispatching=[서버]에서 발송 중인 요청을 입력합니다.

ReportVMServer.ReceivedRequest=[서버]에서 받은 요청:

ReportVMServer.SendBackResponse=[서버]에서 응답을 보냅니다.

ReportVMServer.ServerShuttingDown=[서버] 서버를 종료하고 있습니다.

ReportVMServer.SendVMEvent=[서버]에서 vm 이벤트 보내기:
