###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel Data Source
data.set.name=Excel Data Set
connection.profile.name=Excel Data Source Connection Profile

datasource.property.uri=U&RI
datasource.property.incltypeline=2 行目をデータ型のインジケータとして使用する(&D)

datasource.property.inclcolumnnameline=1 行目を列名のインジケータとして使用する(&N)

datasource.property.no=いいえ

datasource.property.yes=はい

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Excel ファイルの選択

datasource.property.worksheets=ワークシート(&S)

dataset.property.worksheets.dateFormat=日付形式
#
###############################################################################
