###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel Data Source
data.set.name=Excel Data Set
connection.profile.name=Excel Data Source Connection Profile

datasource.property.uri=U&RI
datasource.property.incltypeline=Utilisez la deuxième ligne comme indicateur du type de &données

datasource.property.inclcolumnnameline=Utiliser la première ligne en tant qu'indicateur de &nom de colonne

datasource.property.no=NO

datasource.property.yes=YES

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Sélectionnez un fichier Excel

datasource.property.worksheets=Feuille(s) de calc&ul

dataset.property.worksheets.dateFormat=Format de date
#
###############################################################################
