###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel 데이터 원본
data.set.name=Excel 데이터 집합
connection.profile.name=Excel 데이터 원본 연결 프로필

datasource.property.uri=URI(&R)
datasource.property.incltypeline=데이터 형식 표시기로 두 번째 줄 사용(&D)
datasource.property.inclcolumnnameline=열 이름 표시기로 첫 번째 줄 사용(&N)

datasource.property.no=아니요
datasource.property.yes=예

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Excel 파일 선택
datasource.property.worksheets=워크시트(&H)
dataset.property.worksheets.dateFormat=날짜 형식
#
###############################################################################
