###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel Data Source
data.set.name=Excel Data Set
connection.profile.name=Excel Data Source Connection Profile

datasource.property.uri=U&RI
datasource.property.incltypeline=Zweite Zeile als &Datentypindikator verwenden

datasource.property.inclcolumnnameline=Erste Zeile als Spalten&namenindikator verwenden

datasource.property.no=NEIN

datasource.property.yes=JA

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Wählen Sie die Excel-Datei.

datasource.property.worksheets=Arbei&tsblätter

dataset.property.worksheets.dateFormat=Datenformat
#
###############################################################################
