###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel Data Source
data.set.name=Excel Data Set
connection.profile.name=Excel Data Source Connection Profile

datasource.property.uri=U&RI
datasource.property.incltypeline=Utilizar la segunda línea como indicador de tipo de &datos

datasource.property.inclcolumnnameline=Utilizar la primera línea como indicador del &nombre de la columna.

datasource.property.no=NO

datasource.property.yes=SÍ

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Seleccionar el archivo de Excel

datasource.property.worksheets=Hojas de t&rabajo

dataset.property.worksheets.dateFormat=Formato de fecha
#
###############################################################################
