###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Source de données Excel
data.set.name=Jeu de données Excel
connection.profile.name=Profil de connexion à la source de données Excel

datasource.property.uri=U&RI
datasource.property.incltypeline=Utilisez la deuxième ligne comme indicateur du type de &données
datasource.property.inclcolumnnameline=Utiliser la première ligne en tant qu'indicateur de &nom de colonne

datasource.property.no=NO
datasource.property.yes=YES

###############################################################################
#	Date Set Properties
datasource.property.excelFile=Sélectionnez un fichier Excel
datasource.property.worksheets=Cla&sseur(s)
dataset.property.worksheets.dateFormat=Format de date
#
###############################################################################
