###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel 数据源
data.set.name=Excel 数据集
connection.profile.name=Excel 数据源连接配置文件

datasource.property.uri=&URI
datasource.property.incltypeline=将第二行用作数据类型指示器(&D)
datasource.property.inclcolumnnameline=使用第一行作为列名称指示器(&N)

datasource.property.no=NO（否）
datasource.property.yes=YES（是）

###############################################################################
#	Date Set Properties
datasource.property.excelFile=选择 Excel 文件
datasource.property.worksheets=工作表
dataset.property.worksheets.dateFormat=日期格式
#
###############################################################################
