###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Excel Data Source ODA Runtime Driver
data.source.name=Excel Data Source
data.set.name=Excel Data Set
connection.profile.name=Excel Data Source Connection Profile

datasource.property.uri=U&RI
datasource.property.incltypeline=将第二行用作数据类型指示器(&D)

datasource.property.inclcolumnnameline=使用第一行作为列名称指示器(&N)

datasource.property.no=否

datasource.property.yes=是

###############################################################################
#	Date Set Properties
datasource.property.excelFile=选择 Excel 文件

datasource.property.worksheets=工作表(&H)

dataset.property.worksheets.dateFormat=日期格式
#
###############################################################################
