#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
OdsEmitter.Description=OpenDocument スプレッドシート形式でレポートをレンダリングするためのオプションを設定します。

OdsEmitter.DisplayName=OpenDocument スプレッドシート

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=文字列の折り返し

OptionDisplayValue.ChartDpi=グラフの DPI

OptionDisplayValue.HideGridlines=罫線を非表示

###########################################################
#Option Description
OptionDescription.WrappingText=文字列を折り返すことができるかどうかを示します。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

OptionDescription.HideGridlines=罫線を非表示にします。

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。例: 192。