#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
OdsEmitter.Description=OpenDocument 스프레드시트 형식의 보고서 렌더링 옵션을 구성합니다.

OdsEmitter.DisplayName=OpenDocument 스프레드시트

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=텍스트 줄 바꿈

OptionDisplayValue.ChartDpi=차트 DPI

OptionDisplayValue.HideGridlines=눈금선 숨기기

###########################################################
#Option Description
OptionDescription.WrappingText=텍스트 줄 바꿈 가능 여부를 나타냅니다.

OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.

OptionDescription.HideGridlines=눈금선을 숨깁니다.

###########################################################
#tooltip
Tooltip.ChartDpi=차트 엔진에서 차트를 생성하는 데 사용하는 DPI입니다. 예: 192.