#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
OdsEmitter.Description=配置用于以 OpenDocument Spreadsheet 格式呈现报表的选项。

OdsEmitter.DisplayName=OpenDocument Spreadsheet

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=文字环绕

OptionDisplayValue.ChartDpi=图表 DPI

OptionDisplayValue.HideGridlines=隐藏网格线

###########################################################
#Option Description
OptionDescription.WrappingText=表示文字可否环绕。

OptionDescription.ChartDpi=用于生成图表的 DPI。

OptionDescription.HideGridlines=隐藏网格线。

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。例如，192。