#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Excel Emitter
OdsEmitter.Description=Configure las opciones para procesar un informe en formato de hoja de cálculo OpenDocument.

OdsEmitter.DisplayName=Hoja de cálculo OpenDocument

###########################################################
#Option Display Value
OptionDisplayValue.WrappingText=Autoajuste de texto

OptionDisplayValue.ChartDpi=Diagrama DPI

OptionDisplayValue.HideGridlines=Ocultar líneas de cuadrícula

###########################################################
#Option Description
OptionDescription.WrappingText=Indica si el texto se puede autoajustar.

OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

OptionDescription.HideGridlines=Ocultar líneas de cuadrícula.

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.