#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=Aufbau einer Verbindung zur Erstellung einer SQL-Abfrage nicht möglich. Überprüfen Sie die Datenquellen-Verbindungseigenschaften.

sqbWizPage_cannotOpenConnectionTitle=Verbindungsfehler

sqbWizPage_dataSourceDesignError=Datenquellen-Designfehler

sqbWizPage_dbErrorMsg=Datenbank-Fehlermeldung:

sqbWizPage_defaultMessage=SQL Select-Abfrage erstellen.

sqbWizPage_detectExternalSqlTextChangedMsg=Der SQL-Abfragetext wurde extern im Datensatz-Design geändert. Möchten Sie die Inhalte der SQL-Abfrageerstellung mit diesen Änderungen ersetzen?

sqbWizPage_detectSqlTextChangedTitle=SQL-Abfragetext geändert

sqbWizPage_inputFailOnOpenAskUserMessage=Möchten Sie fortfahren?

sqbWizPage_invalidSqbStateMsg=SQL-Abfrageerstellung kann nicht in vorherigen Zustand zurückgesetzt werden.

sqbWizPage_invalidSqbStateTitle=SQL-Abfrageerstellung - Ungültiger Zustand

sqbWizPage_noConnProfileMsg=Das Datenbankverbindungsprofil ist nicht vorhanden oder ungültig. Öffnen der SQL-Abfrageerstellung nicht möglich.

sqbWizPage_connectingDB=Verbindung zur Datenbank wird hergestellt...

sqbDesignState_invalidSqbStateVersion=Ungültige Version im gespeicherten SQL-Abfrageerstellungszustand
