#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=Impossible d'établir une connexion pour créer une requête SQL. Vérifiez les propriétés de la connexion à la source de données.

sqbWizPage_cannotOpenConnectionTitle=Erreur de connexion

sqbWizPage_dataSourceDesignError=Erreur de conception de la source de données

sqbWizPage_dbErrorMsg=Message d'erreur de la base de données :

sqbWizPage_defaultMessage=Créer une requête de sélection SQL.

sqbWizPage_detectExternalSqlTextChangedMsg=Le texte de la requête SQL a été modifié en externe dans la conception du jeu de données. Voulez-vous remplacer le contenu du générateur de requête SQL par ces modifications ?

sqbWizPage_detectSqlTextChangedTitle=Le texte de la requête SQL a été modifié

sqbWizPage_inputFailOnOpenAskUserMessage=Voulez-vous continuer ?

sqbWizPage_invalidSqbStateMsg=Impossible de restaurer l'état précédent du générateur de requête SQL.

sqbWizPage_invalidSqbStateTitle=Etat du générateur de requête SQL non valide

sqbWizPage_noConnProfileMsg=Le profil de connexion de la base de données est introuvable ou non valide. Impossible d'ouvrir le générateur de requête SQL.

sqbWizPage_connectingDB=Connexion à la base de données...

sqbDesignState_invalidSqbStateVersion=Version non valide dans l'état du générateur de requête SQL enregistré.
