#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=SQL クエリを構築するための接続が確立できません。データソースの接続プロパティを確認してください。

sqbWizPage_cannotOpenConnectionTitle=接続エラー

sqbWizPage_dataSourceDesignError=データソースデザインエラー

sqbWizPage_dbErrorMsg=データベースエラーメッセージ :

sqbWizPage_defaultMessage=SQL Select クエリを構築します。

sqbWizPage_detectExternalSqlTextChangedMsg=SQL クエリテキストが、データセットデザインにて外部で変更されました。SQL クエリビルダのコンテンツをこの変更内容と置換しますか？

sqbWizPage_detectSqlTextChangedTitle=SQL クエリテキストが変更されました。

sqbWizPage_inputFailOnOpenAskUserMessage=続行してよろしいですか ?

sqbWizPage_invalidSqbStateMsg=SQL クエリビルダを元の状態に戻せません。

sqbWizPage_invalidSqbStateTitle=SQL クエリビルダの状態が無効です。

sqbWizPage_noConnProfileMsg=データベース接続プロファイルが見つからないか無効です。SQL クエリビルダを開けません。

sqbWizPage_connectingDB=データベースに接続...

sqbDesignState_invalidSqbStateVersion=保存されたSQL クエリビルダの状態のバージョンが無効です。
