#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=SQL 쿼리를 작성하기 위해 연결할 수 없습니다. 데이터 원본 연결 속성을 확인하십시오.

sqbWizPage_cannotOpenConnectionTitle=연결 오류

sqbWizPage_dataSourceDesignError=데이터 원본 디자인 오류

sqbWizPage_dbErrorMsg=데이터베이스 오류 메시지:

sqbWizPage_defaultMessage=SQL Select 쿼리를 작성합니다.

sqbWizPage_detectExternalSqlTextChangedMsg=데이터 집합 디자인의 SQL 쿼리 텍스트가 외부에서 변경되었습니다. SQL 쿼리 빌더의 내용을 이 변경 내용으로 바꾸시겠습니까?

sqbWizPage_detectSqlTextChangedTitle=SQL 쿼리 텍스트 변경

sqbWizPage_inputFailOnOpenAskUserMessage=계속하시겠습니까?

sqbWizPage_invalidSqbStateMsg=SQL 쿼리 빌더의 이전 상태를 복원할 수 없습니다.

sqbWizPage_invalidSqbStateTitle=잘못된 SQL 쿼리 빌더 상태

sqbWizPage_noConnProfileMsg=데이터베이스 연결 프로필이 없거나 잘못되었습니다. SQL 쿼리 빌더를 열 수 없습니다.

sqbWizPage_connectingDB=데이터베이스에 연결하는 중...

sqbDesignState_invalidSqbStateVersion=저장된 SQL 쿼리 빌더 상태의 버전이 잘못되었습니다.
