#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=No es posible establecer la conexión para compilar consultas SQL. Compruebe las propiedades de conexión de la fuente de datos.

sqbWizPage_cannotOpenConnectionTitle=Error de conexión

sqbWizPage_dataSourceDesignError=Error de diseño de fuente de datos

sqbWizPage_dbErrorMsg=Mensaje de error de la base de datos:

sqbWizPage_defaultMessage=Compilar una consulta de selección de SQL.

sqbWizPage_detectExternalSqlTextChangedMsg=Se ha modificado externamente el texto de la consulta SQL en el diseño del conjunto de datos. ¿Desea reemplazar el contenido del compilador de consultas SQL con estos cambios?

sqbWizPage_detectSqlTextChangedTitle=Texto modificado en la consulta SQL

sqbWizPage_inputFailOnOpenAskUserMessage=¿Desea continuar?

sqbWizPage_invalidSqbStateMsg=No es posible restaurar el compilador de consultas SQL al estado anterior.

sqbWizPage_invalidSqbStateTitle=Estado del compilador de consultas SQL no válido

sqbWizPage_noConnProfileMsg=No se encuentra el perfil de conexión de la base de datos o no es válido. No es posible abrir el compilador de consultas SQL.

sqbWizPage_connectingDB=Conectando con la base de datos...

sqbDesignState_invalidSqbStateVersion=La versión guardada en el estado del compilador de consultas SQL no es válida.
