#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=无法建立连接以生成 SQL 查询。请检查数据源连接属性。

sqbWizPage_cannotOpenConnectionTitle=连接错误

sqbWizPage_dataSourceDesignError=数据源设计错误

sqbWizPage_dbErrorMsg=数据库错误消息:

sqbWizPage_defaultMessage=生成 SQL 选择查询。

sqbWizPage_detectExternalSqlTextChangedMsg=SQL 查询文本已在数据集设计外部更改。是否要使用这些更改替换 SQL 查询生成器内容?

sqbWizPage_detectSqlTextChangedTitle=SQL 查询文本已更改

sqbWizPage_inputFailOnOpenAskUserMessage=是否要继续?

sqbWizPage_invalidSqbStateMsg=无法恢复 SQL 查询生成器的先前状态。

sqbWizPage_invalidSqbStateTitle=无效的 SQL 查询生成器状态

sqbWizPage_noConnProfileMsg=数据库连接配置文件找不到或无效。无法打开 SQL 查询生成器。

sqbWizPage_connectingDB=正在连接到数据库...

sqbDesignState_invalidSqbStateVersion=保存的 SQL 查询生成器状态中的版本无效。
