###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Consulta
datasource.name=Fuente de datos Hive
select.dataset.name=Consulta de selección de HQL
jdbc.driver.name=Controlador de Hive
dataset.property.queryTimeOut=Tiem&po límite de consulta (en segundos)
dataset.property.rowFetchSize=Tamaño de recuperación de &fila
dataset.property.addListFile=&Añadir archivo de lista
#
oda.data.source.name=Hive
connection.profile.name=Perfil de conexión de fuente de datos de archivo Hive BIRT
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
