###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages

datasource.name=Hive Data Source
select.dataset.name=HQL Select Query

jdbc.driver.name=Hive Driver
dataset.property.queryTimeOut=&Query Time Out (in seconds)

dataset.property.rowFetchSize=&Row Fetch Size

dataset.property.addListFile=Datei mit Liste &hinzufügen
#
oda.data.source.name=Hive Data Source
connection.profile.name=Hive Data Source Connection Profile
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
