###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Requête
datasource.name=Source de données HIVE
select.dataset.name=Requête de sélection HQL
jdbc.driver.name=Pilote Hive
dataset.property.queryTimeOut=Délai d'expiration de re&quête (en secondes)
dataset.property.rowFetchSize=Taille d'ext&raction de lignes
dataset.property.addListFile=&Ajouter un fichier de listes
#
oda.data.source.name=Hive
connection.profile.name=Profil de connexion à la source de données BIRT Hive
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
