###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=查询
datasource.name=Hive 数据源
select.dataset.name=HQL 选择查询
jdbc.driver.name=Hive 驱动程序
dataset.property.queryTimeOut=查询超时(秒)(&Q)
dataset.property.rowFetchSize=行取数大小(&R)
dataset.property.addListFile=添加列表文件(&A)
#
oda.data.source.name=Hive
connection.profile.name=BIRT Hive 数据源连接配置文件
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
