###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Query
datasource.name=Hive Datasource
select.dataset.name=HQL Select Query
jdbc.driver.name=Hive Driver
dataset.property.queryTimeOut=&Query Time Out (in seconds)
dataset.property.rowFetchSize=&Row Fetch Size
dataset.property.addListFile=&Add List File
#
oda.data.source.name=Hive
connection.profile.name=BIRT Hive Data Source Connection Profile
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
