###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=쿼리
datasource.name=Hive 데이터원본
select.dataset.name=HQL Select 쿼리
jdbc.driver.name=Hive 드라이버
dataset.property.queryTimeOut=쿼리 시간 제한(초)(&Q)
dataset.property.rowFetchSize=행 인출 크기(&R)
dataset.property.addListFile=목록 파일 추가(&A)
#
oda.data.source.name=Hive
connection.profile.name=BIRT Hive 데이터 원본 연결 프로필
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
