###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages

datasource.name=Hive Data Source
select.dataset.name=Consulta de selección de HQL

jdbc.driver.name=Hive Driver
dataset.property.queryTimeOut=Tiem&po límite de consulta (en segundos)

dataset.property.rowFetchSize=Tamaño de recuperación de &fila

dataset.property.addListFile=&Añadir archivo de lista
#
oda.data.source.name=Hive Data Source
connection.profile.name=Hive Data Source Connection Profile
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA Connection Factory
