###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=Abfrage
datasource.name=Hive-Datenquelle
select.dataset.name=HQL Select-Abfrage
jdbc.driver.name=Hive-Treiber
dataset.property.queryTimeOut=Zeitüberschreitung für Ab&frage (in Sekunden)
dataset.property.rowFetchSize=&Abzurufende Zeilenanzahl
dataset.property.addListFile=D&atei mit Liste hinzufügen
#
oda.data.source.name=Hive
connection.profile.name=BIRT Hive-Datenquellen-Verbindungsprofil
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
