###############################################################################
# Plug-in Configuration
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
dataset.editor.page.query=クエリ
datasource.name=Hive データソース
select.dataset.name=HQL Select クエリ
jdbc.driver.name=Hive ドライバ
dataset.property.queryTimeOut=クエリのタイムアウト (秒)(&Q)
dataset.property.rowFetchSize=フェッチする行サイズ(&R)
dataset.property.addListFile=リストファイルを追加(&A)
#
oda.data.source.name=Hive
connection.profile.name=BIRT Hive データソース接続プロファイル
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリ
