###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=POJO Data Source ODA Runtime Driver
data.source.name=POJO Data Source
data.set.name=POJO Data Set
connection.profile.name=POJO Data Source Connection Profile
datasource.property.pojoDataSetClassPath=Emp&lacement partagé de classes de jeu de données POJO personnalisées

datasource.property.pojoClassPath=Emplacement partagé des classes POJO
