###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=POJO Data Source ODA Runtime Driver
data.source.name=POJO Data Source
data.set.name=POJO Data Set
connection.profile.name=POJO Data Source Connection Profile
datasource.property.pojoDataSetClassPath=사용자 지정 POJO 데이터 집합 클래스의 공유 위치(&L)

datasource.property.pojoClassPath=POJO 클래스 공유 위치
