###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=POJO データソース ODA 実行時のドライバ
data.source.name=POJO データソース
data.set.name=POJO データセット
connection.profile.name=POJO データソース接続プロファイル
datasource.property.pojoDataSetClassPath=カスタム POJO データセットクラスの共有先(&L)
datasource.property.pojoClassPath=POJO クラスの共有先
