###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Controlador de tiempo de ejecución ODA de fuente de datos POJO
data.source.name=Fuente de datos POJO
data.set.name=Conjunto de datos POJO
connection.profile.name=Perfil de conexión de fuente de datos POJO
datasource.property.pojoDataSetClassPath=&Ubicación compartida de las clases de conjuntos de datos POJO personalizadas
datasource.property.pojoClassPath=Ubicación compartida de las clases POJO
