###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=ODA-Laufzeittreiber für POJO-Datenquelle
data.source.name=POJO-Datenquelle
data.set.name=POJO-Datensatz
connection.profile.name=POJO-Datenquellen-Verbindungsprofil
datasource.property.pojoDataSetClassPath=Gemeinsamer &Speicherort für benutzerdefinierte POJO-Datensatzklassen
datasource.property.pojoClassPath=Gemeinsamer Speicherort von POJO-Klassen
