###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=POJO 数据源 ODA 运行时驱动程序
data.source.name=POJO 数据源
data.set.name=POJO 数据集
connection.profile.name=POJO 数据源连接配置文件
datasource.property.pojoDataSetClassPath=自定义 POJO 数据集类的共享位置(&L)
datasource.property.pojoClassPath=POJO 类的共享位置
