birt.web.category.name=&Business Intelligence & Reporting Tools

birt.web.project.name=Webprojekt mit Diagramm-Runtime

birt.web.project.description=Ein Webprojekt mit der BIRT-Diagrammkomponente erstellen

birt.web.actionsets.description=Aktionen für BIRT-Diagramm-Webprojekt

create.birt.web.module=BIRT-Diagramm-Webmodul erstellen

BIRT_FACET_LABEL=BIRT-Diagramm-Runtime-Komponente

BIRT_FACET_DESCRIPTION=BIRT-Diagramm-Runtime-Komponente

BIRT_FACET_TEMPLATE_LABEL=BIRT-Diagramm-Webprojekt

BIRT_FACET_TEMPLATE_DESCRIPTION=Webprojekt mit der BIRT Diagramm-Runtime-Komponente

JSP_New_context_type_Extension_Element.name=Neue JSP mit BIRT-Diagramm-Tag

JSP_Tag_context_type_Extension_Element.name=Neuer BIRT-Diagramm-JSP-Tag

birtResourcesDefinition= Ressourcendefinition für Diagramm-Webanwendung

birt.action.importruntime.name=&Diagramm-Runtime-Komponente importieren...

##################Do not externalize the version number
runtime.version=4.4.0
