birt.web.category.name=Outils de reporting et de &Business Intelligence

birt.web.project.name=Projet Web avec exécution de création de graphiques

birt.web.project.description=Créer un projet Web contenant le composant de création de graphiques BIRT

birt.web.actionsets.description=Actions pour le projet Web de création de graphiques BIRT

create.birt.web.module=Créer un module Web de création de graphiques BIRT

BIRT_FACET_LABEL=Composant d'exécution de création de graphiques BIRT

BIRT_FACET_DESCRIPTION=Composant d'exécution de création de graphiques BIRT

BIRT_FACET_TEMPLATE_LABEL=Projet Web de création de graphiques BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Projet Web avec le composant d'exécution de création de graphiques BIRT

JSP_New_context_type_Extension_Element.name=Nouveau JSP avec balise de création de graphiques BIRT

JSP_Tag_context_type_Extension_Element.name=Nouvelle balise JSP de création de graphiques BIRT

birtResourcesDefinition= Définition des ressources d'application Web de création de graphiques

birt.action.importruntime.name=Importer le &composant d'exécution de création de graphiques...

##################Do not externalize the version number
runtime.version=4.4.0
