birt.web.category.name=商业智能及报表工具(&B)

birt.web.project.name=具有图表运行时的 Web 项目

birt.web.project.description=创建包含 BIRT 图表组件的 Web 项目

birt.web.actionsets.description=对 BIRT 图表 Web 项目的操作

create.birt.web.module=创建 BIRT 图表 Web 模块

BIRT_FACET_LABEL=BIRT 图表运行时组件

BIRT_FACET_DESCRIPTION=BIRT 图表运行时组件

BIRT_FACET_TEMPLATE_LABEL=BIRT 图表 Web 项目

BIRT_FACET_TEMPLATE_DESCRIPTION=具有 BIRT 图表运行时组件的 Web 项目

JSP_New_context_type_Extension_Element.name=新建具有 BIRT 图表标记的 JSP

JSP_Tag_context_type_Extension_Element.name=新建 BIRT 图表 JSP 标记

birtResourcesDefinition= Web 应用程序资源定义图表

birt.action.importruntime.name=导入图表运行时组件(&C)...

##################Do not externalize the version number
runtime.version=4.4.0
