birt.web.category.name=Business Intelligence and Reporting Tools
birt.web.project.name=BIRT Charting Web Project
birt.web.project.description=Create a web project containing BIRT Chart Component
birt.web.actionsets.description=Actions for BIRT Charting Web Project
create.birt.web.module=Create a BIRT Charting Web Module

BIRT_FACET_LABEL=BIRT Charting Runtime Component
BIRT_FACET_DESCRIPTION=BIRT Charting Runtime Component
BIRT_FACET_TEMPLATE_LABEL=BIRT Charting Web Project

JSP_New_context_type_Extension_Element.name=New JSP With BIRT Charting Tag
JSP_Tag_context_type_Extension_Element.name=New BIRT Charting JSP Tag