birt.web.category.name=ビジネスインテリジェンスとレポート作成ツール(&B)

birt.web.project.name=グラフランタイム付き Web プロジェクト

birt.web.project.description=BIRT グラフコンポーネントを含む Web プロジェクトを作成します。

birt.web.actionsets.description=BIRT グラフ作成 Web プロジェクトでの操作

create.birt.web.module=BIRT グラフ作成 Web モジュールの作成

BIRT_FACET_LABEL=BIRT グラフ作成ランタイムコンポーネント

BIRT_FACET_DESCRIPTION=BIRT グラフ作成ランタイムコンポーネント

BIRT_FACET_TEMPLATE_LABEL=BIRT グラフ作成 Web プロジェクト

BIRT_FACET_TEMPLATE_DESCRIPTION=BIRT グラフ作成ランタイムコンポーネントの Web プロジェクト

JSP_New_context_type_Extension_Element.name=新規 JSP (BIRT グラフ作成タグを使用)

JSP_Tag_context_type_Extension_Element.name=新規 BIRT グラフ作成 JSP タグ

birtResourcesDefinition= グラフ作成用の Web アプリケーションリソースの定義

birt.action.importruntime.name=グラフ作成用のランタイムコンポーネントのインポート(&C)...

##################Do not externalize the version number
runtime.version=4.4.0
