birt.web.category.name=&Herramientas de generación de informe para la actividad empresarial

birt.web.project.name=Proyecto Web con tiempo de ejecución de diagramas

birt.web.project.description=Crear un proyecto Web que contenga un componente de diagramas BIRT

birt.web.actionsets.description=Acciones para proyecto Web de diagramas BIRT

create.birt.web.module=Crear un módulo Web de diagramas BIRT

BIRT_FACET_LABEL=Componente de tiempo de ejecución de diagramas BIRT

BIRT_FACET_DESCRIPTION=Componente de tiempo de ejecución de diagramas BIRT

BIRT_FACET_TEMPLATE_LABEL=Proyecto Web de diagramas BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Proyecto web con el componente de tiempo de ejecución de diagramas BIRT

JSP_New_context_type_Extension_Element.name=Nuevo JSP con etiqueta de diagramas BIRT

JSP_Tag_context_type_Extension_Element.name=Nueva etiqueta JSP de diagramas BIRT

birtResourcesDefinition= Definición de recursos de aplicación Web de diagramas

birt.action.importruntime.name=Im&portar componente de tiempo de ejecución de diagramas...

##################Do not externalize the version number
runtime.version=4.4.0
