#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=Impossible de trouver le profil de connexion référencé par les propriétés de la connexion à la source de données.

connection_openFailed=Impossible d'ouvrir une connexion avec le profil de connexion de la base de données.

dBProfileStatement_nullPropertyNameArg=L'argument du nom de propriété spécifié dans {0} est nul.
