#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=No se encuentra el perfil de conexión al que se hace referencia en las propiedades de conexión de fuente de datos.

connection_openFailed=No es posible realizar la conexión con el perfil de conexión de base de datos.

dBProfileStatement_nullPropertyNameArg=El argumento del nombre de la propiedad especificado en {0} es nulo.
