#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=데이터 원본 연결 속성에서 참조한 연결 프로필을 찾을 수 없습니다.

connection_openFailed=데이터베이스 연결 프로필과의 연결을 열 수 없습니다.

dBProfileStatement_nullPropertyNameArg={0}에 지정된 속성 이름 인수가 널(null)입니다.
