#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=找不到数据源连接属性引用的连接配置文件。

connection_openFailed=无法通过数据库连接配置文件打开连接。

dBProfileStatement_nullPropertyNameArg={0} 中指定的属性名称参数为空。
