#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=データソースの接続プロパティで参照された接続プロファイルが見つかりません。

connection_openFailed=データベース接続プロファイルとの接続を開くことができません。

dBProfileStatement_nullPropertyNameArg={0} にはNull プロパティ名引数が指定されています。
