#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=Das in den Datenquellen-Verbindungseigenschaften angegebene Verbindungsprofil konnte nicht gefunden werden.

connection_openFailed=Öffnen einer Verbindung mit dem Datenbankverbindungsprofil nicht möglich.

dBProfileStatement_nullPropertyNameArg=Null-Argument für Eigenschaftsname in {0} angegeben.
