/* Generated By:JJTree: Do not edit this line. ASTEbody_content.java */

package org.eclipse.birt.core.template;

public class ASTEbody_content extends SimpleNode {
	public ASTEbody_content(int id) {
		super(id);
	}

	public ASTEbody_content(Parser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
