/* Generated By:JJTree: Do not edit this line. ASTText.java */

package org.eclipse.birt.core.template;

public class ASTText extends SimpleNode {
	public ASTText(int id) {
		super(id);
	}

	public ASTText(Parser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	protected StringBuffer content = new StringBuffer();

	public void appendContent(String content) {
		this.content.append(content);
	}

	public String getContent() {
		return content.toString();
	}
}
