/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package org.eclipse.birt.core.template;

public interface ParserVisitor {
	public Object visit(SimpleNode node, Object data);

	public Object visit(ASTAttribute node, Object data);

	public Object visit(ASTEbody_content node, Object data);

	public Object visit(ASTImage node, Object data);

	public Object visit(ASTValueOf node, Object data);

	public Object visit(ASTViewTimeValueOf node, Object data);

	public Object visit(ASTText node, Object data);

	public Object visit(ASTTemplate node, Object data);
}
/*
 * JavaCC - OriginalChecksum=b43077d5be17902f322d964bfe31a4f3 (do not edit this
 * line)
 */
