/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.eclipse.birt.core.template;

public interface ParserConstants {

  int EOF = 0;
  int START_VALUEOF = 2;
  int END_VALUEOF = 3;
  int START_IMAGE = 4;
  int END_IMAGE = 5;
  int TEXT = 6;
  int TAGC = 8;
  int ELEMENTC = 9;
  int A_EQ = 10;
  int ALPHA = 11;
  int NUM = 12;
  int ALPHANUM = 13;
  int A_NAME = 14;
  int CDATA = 15;

  int DEFAULT = 0;
  int ATTLIST = 1;
  int ATTRVAL = 2;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"<value-of\"",
    "\"</value-of\"",
    "\"<image\"",
    "\"</image\"",
    "<TEXT>",
    "<token of kind 7>",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "<A_NAME>",
    "<CDATA>",
  };

}
