/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.eclipse.birt.core.template;

public interface ParserTreeConstants {
	public int JJTATTRIBUTE = 0;
	public int JJTEBODY_CONTENT = 1;
	public int JJTIMAGE = 2;
	public int JJTVALUEOF = 3;
	public int JJTVIEWTIMEVALUEOF = 4;
	public int JJTTEXT = 5;
	public int JJTTEMPLATE = 6;

	public String[] jjtNodeName = { "Attribute", "Ebody_content", "Image", "ValueOf", "ViewTimeValueOf", "Text",
			"Template", };
}
/*
 * JavaCC - OriginalChecksum=ba1752d327cc368a7b995517dec13e68 (do not edit this
 * line)
 */
