/*******************************************************************************
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   See git history
 *******************************************************************************/
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.eclipse.birt.core.template;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int START_VALUEOF = 2;
	/** RegularExpression Id. */
	int END_VALUEOF = 3;
	/** RegularExpression Id. */
	int START_VIEWTIMEVALUEOF = 4;
	/** RegularExpression Id. */
	int END_VIEWTIMEVALUEOF = 5;
	/** RegularExpression Id. */
	int START_IMAGE = 6;
	/** RegularExpression Id. */
	int END_IMAGE = 7;
	/** RegularExpression Id. */
	int TEXT = 8;
	/** RegularExpression Id. */
	int TAGC = 10;
	/** RegularExpression Id. */
	int ELEMENTC = 11;
	/** RegularExpression Id. */
	int A_EQ = 12;
	/** RegularExpression Id. */
	int ALPHA = 13;
	/** RegularExpression Id. */
	int NUM = 14;
	/** RegularExpression Id. */
	int ALPHANUM = 15;
	/** RegularExpression Id. */
	int A_NAME = 16;
	/** RegularExpression Id. */
	int CDATA = 17;

	/** Lexical state. */
	int DEFAULT = 0;
	/** Lexical state. */
	int ATTLIST = 1;
	/** Lexical state. */
	int ATTRVAL = 2;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "<token of kind 1>", "\"<value-of\"", "\"</value-of\"", "\"<viewtime-value-of\"",
			"\"</viewtime-value-of\"", "\"<image\"", "\"</image\"", "<TEXT>", "<token of kind 9>", "\">\"", "\"/>\"",
			"\"=\"", "<ALPHA>", "<NUM>", "<ALPHANUM>", "<A_NAME>", "<CDATA>", };

}
