/* Generated By:JJTree: Do not edit this line. ParserVisitor.java */

package org.eclipse.birt.core.template;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTEbody_content node, Object data);
  public Object visit(ASTImage node, Object data);
  public Object visit(ASTValueOf node, Object data);
  public Object visit(ASTText node, Object data);
  public Object visit(ASTTemplate node, Object data);
}
