SwtRendererImpl.exception.gradient.angle=角度が {0} のグラデーションはレンダリングできません。レンダリング可能な角度は [90 >= 0 >= -90] です。

SwtRendererImpl.exception.unspecified.text.rendering.action=テキストのレンダリング中に例外が発生しました。TextRenderEvent.setAction(...) が正しく呼び出されませんでした。

SwtRendererImpl.exception.missing.component.interaction=IUpdateNotifier はレンダリング機能と関連付けらていないため、操作できません。

SwtRendererImpl.info.graphics.context=図形コンテキスト {0}@{1} を使用中

SwtTextRenderer.exception.undefined.shadow.color=未定義の色を使用している影はレンダリングできません。

SwtTextRenderer.exception.undefined.text.color=未定義の色を使用しているテキストはレンダリングできません。

SwtDisplayServer.exception.display.server=SWT Display Server のインスタンスを取得できませんでした。

SwtDisplayServer.info.display.server=SWT Display Server: {0} v{1}

SwtEventHandler.info.toggle.visibility=表示と非表示の切り替え : {0}

SwtEventHandler.info.toggle.datapoint.visibility=データポイントの表示と非表示を切り替える : {0}

SwtEventHandler.info.cannot.find.series=実行時系列に使用する設計時系列が見つかりません : {0}

SwtEventHandler.info.improper.callback.notifier=通知ツール [{0}] が検出されましたが、ICallBackNotifer インプリメンタが必要です。

SwtEventHandler.info.redirect.url=次の URL に転送 : {0}

R31Enhance.info.advanced.enabled=SWT の高度なグラフィック機能が有効になりました。

R31Enhance.info.advanced.disabled=SWT の高度なグラフィック機能が無効になりました。