SwtRendererImpl.exception.gradient.angle=Verlauf mit Winkel={0} kann nicht gerendert werden; der unterstützte Bereich ist [90 >= 0 >= -90]

SwtRendererImpl.exception.unspecified.text.rendering.action=Fehlende Text-Rendering-Aktion; TextRenderEvent.setAction(...) wurde nicht korrekt aufgerufen

SwtRendererImpl.exception.missing.component.interaction=Interaktion kann nicht aktiviert werden, wenn kein IUpdateNotifier mit Renderer verknüpft ist

SwtRendererImpl.info.graphics.context=Grafikkontext {0} ({1}) wird verwendet

SwtTextRenderer.exception.undefined.shadow.color=Schatten mit nicht definierter Farbe kann nicht gerendert werden

SwtTextRenderer.exception.undefined.text.color=Text mit nicht definierter Farbe kann nicht gerendert werden

SwtDisplayServer.exception.display.server=SWTDisplayServer-Instanz konnte nicht abgerufen werden

SwtDisplayServer.info.display.server=SWT Anzeigeserver: {0} Version {1}

SwtEventHandler.info.toggle.visibility=Sichtbarkeit ein/aus: {0}

SwtEventHandler.info.toggle.datapoint.visibility=Datenpunkt-Sichtbarkeit ein/aus: {0}

SwtEventHandler.info.cannot.find.series=Entwurfszeit-Datenreihe nicht gefunden für Laufzeit-Datenreihe: {0}

SwtEventHandler.info.improper.callback.notifier=Benachrichtigung: [{0}] wurde erkannt, doch es wird eine ICallBackNotifer-Implementierung erwartet.

SwtEventHandler.info.redirect.url=Umleitung an URL: {0}

R31Enhance.info.advanced.enabled=Erweiterte SWT-Grafikfunktionen aktiviert.

R31Enhance.info.advanced.disabled=Erweiterte SWT-Grafikfunktionen deaktiviert.