SwtRendererImpl.exception.gradient.angle=[SDL]각도={0}에서 그라데이션을 렌더링할 수 없습니다. 지원되는 범위는 [90 >= 0 >= -90]입니다.

SwtRendererImpl.exception.unspecified.text.rendering.action=[SDL]지정되지 않은 텍스트 렌더링 작업입니다. TextRenderEvent.setAction(...)이 올바르게 호출되지 않았습니다.

SwtRendererImpl.exception.missing.component.interaction=[SDL]IUpdateNotifier가 렌더러와 연결되어 있지 않으면 상호 작용을 사용할 수 없습니다.

SwtRendererImpl.info.graphics.context=[SDL]그래픽 컨텍스트 {0}@{1} 사용

SwtTextRenderer.exception.undefined.shadow.color=[SDL]그림자를 정의되지 않은 색으로 렌더링할 수 없습니다.

SwtTextRenderer.exception.undefined.text.color=[SDL]텍스트를 정의되지 않은 색으로 렌더링할 수 없습니다.

SwtDisplayServer.exception.display.server=[SDL]SWT Display Server 인스턴스를 가져오지 못했습니다.

SwtDisplayServer.info.display.server=SWT Display Server: {0} v{1}

SwtEventHandler.info.toggle.visibility=[SDL]표시 유형 전환: {0}

SwtEventHandler.info.toggle.datapoint.visibility=[SDL]데이터 요소 표시 유형 전환: {0}

SwtEventHandler.info.cannot.find.series=[SDL]런타임 계열에 대한 디자인 타임 계열을 찾을 수 없습니다: {0}

SwtEventHandler.info.improper.callback.notifier=[SDL]알림: [{0}]이(가) 검색되었지만 ICallBackNotifer 실행자가 필요합니다.

SwtEventHandler.info.redirect.url=[SDL]다음 URL로 리디렉션: {0}

R31Enhance.info.advanced.enabled=[SDL]고급 SWT 그래픽 기능을 사용합니다.

R31Enhance.info.advanced.disabled=[SDL]고급 SWT 그래픽 기능을 사용하지 않습니다.