SwtRendererImpl.exception.gradient.angle=Impossible de créer un rendu de dégradé à l'angle={0} ; la fourchette prise en charge est [90 >= 0 >= -90]

SwtRendererImpl.exception.unspecified.text.rendering.action=Action de rendu de texte non spécifiée ; la commande TextRenderEvent.setAction(...) n'a pas été appelée correctement

SwtRendererImpl.exception.missing.component.interaction=Impossible d'autoriser l'interaction si aucun IUpdateNotifier n'est associé au moteur de rendu.

SwtRendererImpl.info.graphics.context=Utilisation du contexte graphique {0}@{1}

SwtTextRenderer.exception.undefined.shadow.color=Rendu d'ombre impossible avec une couleur non définie

SwtTextRenderer.exception.undefined.text.color=Rendu de texte impossible avec une couleur non définie

SwtDisplayServer.exception.display.server=Echec de l'instance SWTDisplayServer

SwtDisplayServer.info.display.server=Serveur d''affichage SWT : {0} version {1}

SwtEventHandler.info.toggle.visibility=Basculer la visibilité : {0}

SwtEventHandler.info.toggle.datapoint.visibility=Basculer la visibilité du point de données : {0}

SwtEventHandler.info.cannot.find.series=Impossible de trouver la série heure de conception pour la série heure d''exécution : {0}

SwtEventHandler.info.improper.callback.notifier=Notificateur : [{0}] est détecté, mais un implémenteur ICallBackNotifer est attendu.

SwtEventHandler.info.redirect.url=Rediriger vers l''URL : {0}

R31Enhance.info.advanced.enabled=Fonctions de graphiques SWT avancées activées.

R31Enhance.info.advanced.disabled=Fonctions de graphiques SWT avancées désactivées.