SwtRendererImpl.exception.gradient.angle=No se puede procesar un gradiente con el ángulo={0}; el intervalo admitido es [90 >= 0 >= -90]

SwtRendererImpl.exception.unspecified.text.rendering.action=Acción de procesamiento de texto sin especificar; no se ha llamado correctamente a TextRenderEvent.setAction(...).

SwtRendererImpl.exception.missing.component.interaction=No se puede activar la interacción si no se asocia un IUpdateNotifier con el procesador.

SwtRendererImpl.info.graphics.context=Uso de contexto de gráficos {0} en {1}

SwtTextRenderer.exception.undefined.shadow.color=No se puede procesar la sombra con un color sin definir

SwtTextRenderer.exception.undefined.text.color=No se puede procesar el texto con un color sin definir

SwtDisplayServer.exception.display.server=Error al obtener una instancia de SWT Display Server

SwtDisplayServer.info.display.server=SWT Display Server: {0} v{1}

SwtEventHandler.info.toggle.visibility=Alternar visibilidad: {0}

SwtEventHandler.info.toggle.datapoint.visibility=Alternar visibilidad del punto de datos: {0}

SwtEventHandler.info.cannot.find.series=No es posible localizar la serie de tiempo de diseño para la serie de tiempo de ejecución: {0}

SwtEventHandler.info.improper.callback.notifier=Se ha detectado un notificador [{0}], pero se espera un implementador ICallBackNotifer.

SwtEventHandler.info.redirect.url=Redirigir a URL: {0}

R31Enhance.info.advanced.enabled=Funciones de gráficos SWT avanzadas activadas.

R31Enhance.info.advanced.disabled=Funciones de gráficos SWT avanzadas desactivadas.