SwtRendererImpl.exception.gradient.angle=在角度={0} 时，无法绘制渐变；支持的角度范围为 [90 >= 0 >= -90]

SwtRendererImpl.exception.unspecified.text.rendering.action=未指定的文本绘制操作；TextRenderEvent.setAction(...) 未被正确调用

SwtRendererImpl.exception.missing.component.interaction=如果 IUpdateNotifier 与呈现器不关联，无法启用交互功能。

SwtRendererImpl.info.graphics.context=使用图形上下文 {0}@{1}

SwtTextRenderer.exception.undefined.shadow.color=无法用未定义的颜色绘制阴影

SwtTextRenderer.exception.undefined.text.color=无法用未定义的颜色绘制文本

SwtDisplayServer.exception.display.server=获取 SWT Display Server 实例失败

SwtDisplayServer.info.display.server=SWT 显示服务器: {0} v{1}

SwtEventHandler.info.toggle.visibility=切换可见性: {0}

SwtEventHandler.info.toggle.datapoint.visibility=切换数据点可见性: {0}

SwtEventHandler.info.cannot.find.series=无法找到设计时系列以用于运行时序列: {0}

SwtEventHandler.info.improper.callback.notifier=通知: 检测到 [{0}]，但是预期为 ICallBackNotifer 实现函数。

SwtEventHandler.info.redirect.url=重定向至 URL: {0}

R31Enhance.info.advanced.enabled=启用高级 SWT 图形功能。

R31Enhance.info.advanced.disabled=禁用高级 SWT 图形功能。