#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#OpenDocument Text Emitter
OdtEmitter.Description=Configure las opciones para procesar un informe en formato de texto OpenDocument.

OdtEmitter.DisplayName=Texto OpenDocument

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=Diagrama DPI

###########################################################
#Option Description
OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.