#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#OpenDocument Text Emitter
OdtEmitter.Description=配置用于以 OpenDocument Text 格式呈现报表的选项。

OdtEmitter.DisplayName=OpenDocument 文本

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=图表 DPI

###########################################################
#Option Description
OptionDescription.ChartDpi=用于生成图表的 DPI。