# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=Tipo de datos no válido.
INVALID_EXPRSSION=Expresión Javascript no válida: {0}
CONVERT_FAILS=No se puede convertir el valor de {0} al tipo {1}.

birt.core.JavascriptCommonError=Han ocurrido errores durante la evaluación del script "{0}":\n{1}
birt.core.JavascriptError=Error al evaluar la expresión Javascript. Error de motor de script: {0}\n Fuente de script: {1}, línea: {2}, texto:\n{3}
birt.core.BirtComp.invalidRegularExpression=Invalid regular expression.
