# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=Type de données non valide.
INVALID_EXPRSSION=Expression Javascript incorrecte : {0}
CONVERT_FAILS=Impossible de convertir la valeur de {0} au type {1}.

birt.core.JavascriptCommonError=Des erreurs sont survenues lors de l'évaluation du script "{0}" :\n{1}
birt.core.JavascriptError=Erreur lors de l''évaluation de l''expression Javascript. Erreur de moteur de script : {0}\n Source de script : {1}, ligne : {2}, texte :\n{3}
birt.core.BirtComp.invalidRegularExpression=Invalid regular expression.

error.NoSuchScriptExtension = No such script extension : {0}.
error.InvalidSeekOffset = Invalid position {0}.
error.ExceedFileLength = Exceed the file length.
error.CanotchangeReadOnlyBuffer = Cannot change the read only buffer.
error.FileOpenedInReadOnlyMode = The file is opened in read only mode.
error.FileHasBeenClosed = The archive file has been closed.
error.UnparseableString = String value cannot be parsed: "{0}".
error.CannotStartupOSGIPlatform = Can not startup the OSGI framework.
error.UnsupportedFileMode = Unsupported file mode: {0}.
error.FolderNameIsNull = The folder name is null or empty string..
error.FileNameIsNull = The file name is null or empty string.
error.NotExt2Archive = Not a Ext2 archive, the magic code is : {0}.
error.NotCompoundFile = Not a compound file, the magic code is : {0}.
error.ReadOnlyArchive = Read only archive.
error.UnsupportedArchiveVersion = Unsupported archive version {0}.
error.UnsupportedBlockSize = Unsupported block size.
error.InvalidIndex = Invalid index at block {0}. 
error.UnsupportedNodeType = unexpected node type: {0} for node {1}. 
error.NotSerializable = Not serializable.
error.InvalidLockType = Invalid lock type : {0}.
error.ArchiveOpenForWrite = Archive must be opened for write. System ID: {0}.
error.ExceedMaxBlockSize = The size of archive header can not be larger than: {0}.
error.InvalidArchiveName= {0} doesn't exist or is not a folder.
error.NullSource = source archive or destination is null.
error.OutOfRange = The seek position is out of range.
error.ReadOnlyTree = Can not insert a entry into a read only tree.
error.CannotLoadNode = Can not load node: {0}.
error.KeySizeError = The key size is {0} instead of {1}.
error.MismatchKeyLength = Mismatch key length for fixed length key.
error.ValueSizeError = The value size is {0} instead of {1}.
error.MismatchValueLength = Mismatch value length for fixed length value.
error.InvaldMagicTag = Invalid magic tag: {0}.
error.UnsupportedVersion = Unsupported version: {0}.
error.InvalidCursor = Invalid cursor.
error.CusorNotInitialized = Must initialize the cursor first.
error.UnexpectedEqualKeys = Unexpected equal keys.
error.UnknownValueType = Unknown values type :{0}.
error.ExceedMaxBlock = {0} exceed the max block in RAM {1}. 
error.MalformedInputError = Malformed input: partial character at end.
error.MalformedInputAroundByte = Malformed input around byte {0}.>>>>>>> 1.8
