# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################
INVALID_TYPE=Ungültiger Datentyp.

INVALID_EXPRSSION=Ungültiger Javascript-Ausdruck: {0}

CONVERT_FAILS=Wert von "{0}" kann nicht in Typ "{1}" umgewandelt werden.

birt.core.JavascriptCommonError=Fehler beim Auswerten von Skript '{0}':\n{1}.

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=Berichtsparameter '{0}' nicht vorhanden.

birt.core.Javascript.variableNotExist=Berichtvariable '{0}' nicht vorhanden.

birt.core.Javascript.nativeNotFound={0} nicht gefunden.

birt.core.BirtComp.invalidRegularExpression=Ungültiger Standardausdruck.

error.NoSuchScriptExtension = Skript-Erweiterung nicht vorhanden: {0}.

error.InvalidSeekOffset = Ungültige Position {0}.

error.ExceedFileLength = Dateilänge überschritten.

error.CanotchangeReadOnlyBuffer = Der einzige Puffer kann nicht geändert werden.

error.FileOpenedInReadOnlyMode = Die Datei ist in schreibgeschütztem Modus geöffnet.

error.FileHasBeenClosed = Die Archivdatei wurde geschlossen.

error.UnparseableString = Zeichenfolgenwert kann nicht analysiert werden: '{0}'.

error.CannotStartupOSGIPlatform = OSGI-Framework kann nicht gestartet werden.

error.UnsupportedFileMode = Nicht unterstützter Dateimodus: {0}.

error.FolderNameIsNull = Die Eingabe für den Ordnernamen ist entweder Null oder leer.

error.FileNameIsNull = Die Eingabe für den Dateinamen ist entweder Null oder leer.

error.NotExt2Archive = Kein Ext2-Archiv; der magische Code lautet: {0}.

error.NotCompoundFile = Keine zusammengesetzte Datei; der magische Code lautet: {0}.

error.ReadOnlyArchive = Das Archiv ist schreibgeschützt.

error.UnsupportedArchiveVersion = Nicht unterstützte Archivversion: {0}.

error.UnsupportedBlockSize = Nicht unterstützte Blockgröße.

error.InvalidIndex = Ungültiger Index bei Block {0}.

error.UnsupportedNodeType = Unerwarteter Knotentyp: {0} für Knoten {1}.

error.NotSerializable = Nicht serialisierbar.

error.UnsupportedDataType = Dieser Datentyp wird noch nicht unterstützt oder ist nicht serialisierbar.

error.InvalidLockType = Ungültiger Sperrtyp: {0}.

error.ArchiveOpenForWrite = Archiv muss zum Schreiben geöffnet werden. System-ID: {0}.

error.ExceedMaxBlockSize = Die Größe der Archivkopfzeile darf folgenden Wert nicht überschreiten: {0}.

error.InvalidArchiveName= {0} ist nicht vorhanden oder kein Ordner.

error.NullSource = Quellarchiv oder Zielordner ist Null.

error.OutOfRange = Die Suchposition liegt außerhalb des gültigen Bereichs.

error.ReadOnlyTree = In eine schreibgeschützte Baumstruktur kann kein Eintrag eingefügt werden.

error.CannotLoadNode = Folgender Knoten kann nicht geladen werden: {0}.

error.KeySizeError = Statt {1} beträgt die Schlüsselgröße {0}.

error.MismatchKeyLength = Länge des Schlüssels stimmt nicht mit der festgelegten Schlüssellänge überein.

error.ValueSizeError = Statt {1} beträgt die Wertgröße {0}.

error.MismatchValueLength = Länge des Werts stimmt nicht mit der festgelegten Wertlänge überein.

error.InvaldMagicTag = Ungültiger magischer Tag: {0}.

error.UnsupportedVersion = Nicht unterstützte Version: {0}.

error.InvalidCursor = Ungültiger Cursor.

error.CusorNotInitialized = Zuerst muss der Cursor initialisiert werden.

error.UnexpectedEqualKeys = Unerwartete gleiche Schlüssel.

error.UnknownValueType = Unbekannter Wertetyp: {0}.

error.ExceedMaxBlock = {0} überschreitet den maximalen Block in RAM {1}.

error.MalformedInputError = Falsch geformte Eingabe: Unvollständiges Zeichen am Ende.

error.MalformedInputAroundByte = Falsch geformte Eingabe bei Byte {0}.>>>>>>> 1,8