# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=Ungültiger Datentyp.
INVALID_EXPRSSION=Ungültiger Javascript-Ausdruck: {0}
CONVERT_FAILS=Wert von "{0}" kann nicht in Typ "{1}" umgewandelt werden.

birt.core.JavascriptCommonError=Fehler beim Auswerten von Skript '{0}':\n{1}.
birt.core.JavascriptError=Beim Evaluieren des Javascript-Ausdrucks ist ein Fehler aufgetreten. Skript-Engine-Fehler: {0}\n Skriptquelle: {1}, Zeile: {2}, Text:\n{3}
birt.core.BirtComp.invalidRegularExpression=Invalid regular expression.


