# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################
INVALID_TYPE=Type de données non valide.

INVALID_EXPRSSION=Expression Javascript incorrecte : {0}

CONVERT_FAILS=Impossible de convertir la valeur de {0} au type {1}.

birt.core.JavascriptCommonError=Des erreurs sont survenues lors de l'évaluation du script "{0}" :\n{1}

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=Le paramètre de l'état "{0}" n'existe pas.

birt.core.Javascript.variableNotExist=La variable de l'état "{0}" n'existe pas.

birt.core.Javascript.nativeNotFound={0} introuvable.

birt.core.BirtComp.invalidRegularExpression=Expression régulière incorrecte.

error.NoSuchScriptExtension = Aucune extension de script de ce type : {0}.

error.InvalidSeekOffset = Position non valide {0}.

error.ExceedFileLength = Dépasse la longueur du fichier.

error.CanotchangeReadOnlyBuffer = Impossible de modifier le tampon en lecture seule.

error.FileOpenedInReadOnlyMode = Le fichier est ouvert en mode lecture seule.

error.FileHasBeenClosed = Le fichier archivé a été fermé.

error.UnparseableString = La valeur de chaîne ne peut être interprétée : "{0}".

error.CannotStartupOSGIPlatform = Impossible de démarrer la structure OSGI.

error.UnsupportedFileMode = Mode de fichier non pris en charge : {0}.

error.FolderNameIsNull = Le nom du dossier est une valeur nulle ou une chaîne vide.

error.FileNameIsNull = Le nom du fichier est une valeur nulle ou une chaîne vide.

error.NotExt2Archive = Pas une archive Ext2, le mot de passe est : {0}.

error.NotCompoundFile = Pas un fichier composé, le mot de passe est : {0}.

error.ReadOnlyArchive = Archive en lecture seule.

error.UnsupportedArchiveVersion = Version d'archive non prise en charge {0}.

error.UnsupportedBlockSize = Taille de bloc non prise en charge.

error.InvalidIndex = Index non valide au bloc {0}.

error.UnsupportedNodeType = Type de nœud inattendu : {0} pour le nœud {1}.

error.NotSerializable = Non sérialisable.

error.UnsupportedDataType = Ce type de données n'est pas encore pris en charge ou est non sérialisable.

error.InvalidLockType = Type de verrouillage non valide : {0}.

error.ArchiveOpenForWrite = L'archive doit être ouverte pour pouvoir y écrire. ID du système : {0}.

error.ExceedMaxBlockSize = La taille de l'en-tête de l'archive ne peut pas être plus grande que : {0}.

error.InvalidArchiveName= {0} n'existe pas ou n'est pas un dossier.

error.NullSource = L'archive de la source ou la destination est nulle.

error.OutOfRange = La position recherchée est en dehors de l'intervalle.

error.ReadOnlyTree = Impossible d'insérer une entrée dans une arborescence en lecture seule.

error.CannotLoadNode = Impossible de charger le nœud : {0}.

error.KeySizeError = La taille de la clé est {0} au lieu de {1}.

error.MismatchKeyLength = Longueur de clé incompatible avec une clé de longueur fixe.

error.ValueSizeError = La taille de la valeur est {0} au lieu de {1}.

error.MismatchValueLength = Longueur de valeur incompatible avec une valeur de longueur fixe.

error.InvaldMagicTag = Balise magique non valide : {0}.

error.UnsupportedVersion = Version non prise en charge : {0}.

error.InvalidCursor = Curseur non valide.

error.CusorNotInitialized = Le curseur doit d'abord être initialisé.

error.UnexpectedEqualKeys = Clés égales inattendues.

error.UnknownValueType = Type de valeurs inconnu :{0}.

error.ExceedMaxBlock = {0} dépasse le bloc maximal dans la RAM {1}.

error.MalformedInputError = Entrée incorrecte : caractère partiel à la fin.

error.MalformedInputAroundByte = Entrée incorrecte vers l'octet {0}.>>>>>>> 1.8