# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=잘못된 데이터 형식입니다.
INVALID_EXPRSSION=잘못된 Javascript 식: {0}
CONVERT_FAILS={0} 값을 {1} 형식으로변환할 수 없습니다.

birt.core.JavascriptCommonError=스크립트 "{0}"을(를) 평가하는 도중 오류가 발생했습니다.\n{1}
birt.core.JavascriptError=Javascript 식을 평가하는 도중 오류가 발생했습니다. 스크립트 엔진 오류: {0}\n 스크립트 원본: {1}, 줄: {2}, 텍스트:\n{3}
birt.core.BirtComp.invalidRegularExpression=Invalid regular expression.


