# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################
INVALID_TYPE=无效的数据源类型。

INVALID_EXPRSSION=无效 javascript 表达式：{0}

CONVERT_FAILS=无法将数值 {0} 转换成类型 {1}。

birt.core.JavascriptCommonError=判定脚本“{0}”时出错: \n{1}

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=报表参数“{0}”不存在。

birt.core.Javascript.variableNotExist=报表变量“{0}”不存在。

birt.core.Javascript.nativeNotFound=未找到 {0}。

birt.core.BirtComp.invalidRegularExpression=正则表达式无效。

error.NoSuchScriptExtension = 无此类脚本扩展: {0}。

error.InvalidSeekOffset = 无效位置 {0}。

error.ExceedFileLength = 超过文件长度。

error.CanotchangeReadOnlyBuffer = 无法更改只读缓冲区。

error.FileOpenedInReadOnlyMode = 文件以只读模式打开。

error.FileHasBeenClosed = 存档文件已关闭。

error.UnparseableString = 无法分析字符串值:“{0}”。

error.CannotStartupOSGIPlatform = 无法启动 OSGI 框架。

error.UnsupportedFileMode = 不支持的文件模式: {0}。

error.FolderNameIsNull = 文件夹名称为空或空字符串。

error.FileNameIsNull = 文件名称为空或空字符串。

error.NotExt2Archive = 不是 Ext2 存档，逻辑代码是: {0}。

error.NotCompoundFile = 不是复合文件，逻辑代码是: {0}。

error.ReadOnlyArchive = 只读存档。

error.UnsupportedArchiveVersion = 不支持的存档版本 {0}。

error.UnsupportedBlockSize = 不支持的块大小。

error.InvalidIndex = 块 {0} 处的索引无效。

error.UnsupportedNodeType = 意外节点类型: {0}，节点 {1}。

error.NotSerializable = 不可序列化。

error.UnsupportedDataType = 此数据类型不受支持或不可序列化。

error.InvalidLockType = 无效锁类型: {0}。

error.ArchiveOpenForWrite = 存档必须打开才能写入。 系统 ID: {0}。

error.ExceedMaxBlockSize = 存档标头的大小不能大于: {0}。

error.InvalidArchiveName= {0} 不存在或不是文件夹。

error.NullSource = 源存档或目标为空。

error.OutOfRange = 查找位置超出范围。

error.ReadOnlyTree = 无法将条目插入只读树。

error.CannotLoadNode = 无法加载节点: {0}。

error.KeySizeError = 密钥大小为 {0} 而不是 {1}。

error.MismatchKeyLength = 固定长度密钥的密钥长度不匹配。

error.ValueSizeError = 值大小为 {0} 而不是 {1}。

error.MismatchValueLength = 固定长度值的值长度不匹配。

error.InvaldMagicTag = 无效 magic 标记: {0}。

error.UnsupportedVersion = 不支持的版本: {0}。

error.InvalidCursor = 无效光标。

error.CusorNotInitialized = 必须首先初始化光标。

error.UnexpectedEqualKeys = 意外相等密钥。

error.UnknownValueType = 未知值类型: {0}。

error.ExceedMaxBlock = {0} 超过 RAM {1} 中的最大块。

error.MalformedInputError = 格式错误的输入: 结尾部分字符。

error.MalformedInputAroundByte = 格式错误的输入字节 {0}。>>>>>>> 1.8