# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################
INVALID_TYPE=잘못된 데이터 형식입니다.

INVALID_EXPRSSION=잘못된 Javascript 식: {0}

CONVERT_FAILS={0} 값을 {1} 형식으로변환할 수 없습니다.

birt.core.JavascriptCommonError=스크립트 "{0}"을(를) 평가하는 도중 오류가 발생했습니다.\n{1}

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=보고서 매개 변수 "{0}"이(가) 없습니다.

birt.core.Javascript.variableNotExist=보고서 변수 "{0}"이(가) 없습니다.

birt.core.Javascript.nativeNotFound={0}을(를) 찾을 수 없습니다.

birt.core.BirtComp.invalidRegularExpression=잘못된 정규식입니다.

error.NoSuchScriptExtension = 스크립트 확장명이 없습니다: {0}.

error.InvalidSeekOffset = 위치 {0}이(가) 잘못되었습니다.

error.ExceedFileLength = 파일 길이를 초과했습니다.

error.CanotchangeReadOnlyBuffer = 읽기 전용 버퍼를 변경할 수 없습니다.

error.FileOpenedInReadOnlyMode = 파일이 읽기 전용 모드로 열려 있습니다.

error.FileHasBeenClosed = 아카이브 파일이 닫혔습니다.

error.UnparseableString = 문자열 값을 구문 분석할 수 없습니다: "{0}".

error.CannotStartupOSGIPlatform = OSGI 프레임워크를 시작할 수 없습니다.

error.UnsupportedFileMode = 지원되지 않는 파일 모드입니다: {0}.

error.FolderNameIsNull = 폴더 이름이 널(null)이거나 빈 문자열입니다..

error.FileNameIsNull = 파일 이름이 널(null)이거나 빈 문자열입니다.

error.NotExt2Archive = Ext2 아카이브가 아니며 매직 코드는 다음과 같습니다: {0}.

error.NotCompoundFile = 복합 파일이 아니며 매직 코드는 다음과 같습니다: {0}.

error.ReadOnlyArchive = 읽기 전용 아카이브입니다.

error.UnsupportedArchiveVersion = 지원되지 않는 아카이브 버전 {0}입니다.

error.UnsupportedBlockSize = 지원되지 않는 블록 크기입니다.

error.InvalidIndex = 블록 {0}에서 인덱스가 잘못되었습니다.

error.UnsupportedNodeType = 예기지 않은 노드 형식입니다: {1} 노드의 {0}입니다.

error.NotSerializable = 직렬화할 수 없습니다.

error.UnsupportedDataType = 이 데이터 형식은 아직 지원되지 않거나 직렬화할 수 없습니다.

error.InvalidLockType = 잘못된 잠금 형식입니다: {0}.

error.ArchiveOpenForWrite = 아카이브는 쓸 수 있는 상태로 열려야 합니다. 시스템 ID: {0}.

error.ExceedMaxBlockSize = 아카이브 헤더 크기는 다음보다 작아야 합니다: {0}.

error.InvalidArchiveName= {0}이(가) 없거나 또는 폴더가 아닙니다.

error.NullSource = 원본 아카이브 또는 대상이 널(null)입니다.

error.OutOfRange = 검색 위치가 범위를 벗어났습니다.

error.ReadOnlyTree = 항목을 읽기 전용 트리로 삽입할 수 없습니다.

error.CannotLoadNode = 노드를 로드할 수 없습니다: {0}.

error.KeySizeError = 키 크기는 {1} 대신 {0}입니다.

error.MismatchKeyLength = 키 길이가 고정 길이 키와 일치하지 않습니다.

error.ValueSizeError = 값 크기는 {1} 대신 {0}입니다.

error.MismatchValueLength = 값 길이가 고정 길이 값과 일치하지 않습니다.

error.InvaldMagicTag = 잘못된 매직 태그입니다: {0}.

error.UnsupportedVersion = 지원되지 않는 버전입니다: {0}.

error.InvalidCursor = 잘못된 커서입니다.

error.CusorNotInitialized = 커서를 먼저 초기화해야 합니다.

error.UnexpectedEqualKeys = 예기치 않은 동일한 키입니다.

error.UnknownValueType = 알 수 없는 값 형식입니다: {0}.

error.ExceedMaxBlock = RAM {1}에서 {0}이(가) 최대 블록을 초과합니다.

error.MalformedInputError = 잘못된 입력: 끝의 일부 문자

error.MalformedInputAroundByte = {0}바이트 주변에 입력이 잘못되었습니다.>>>>>>> 1.8