# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=データ型が無効です。
INVALID_EXPRSSION=JavaScript 式が無効です : {0}
CONVERT_FAILS={0} の値を {1} 型に変換できません。

birt.core.JavascriptCommonError=スクリプト "{0}" の評価中にエラーが発生しました : \n{1}
birt.core.JavascriptError=JavaScript 式の評価エラーが発生しました。 スクリプトエンジンエラー : {0}\n スクリプトのソース : {1}, 行 : {2}, テキスト :\n{3}
birt.core.BirtComp.invalidRegularExpression=Invalid regular expression.
