# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################

INVALID_TYPE=Type de données non valide.
CONVERT_FAILS=Impossible de convertir la valeur de {0} au type {1}.

birt.core.JavascriptError=Erreur lors de l''évaluation de l''expression Javascript. Erreur de moteur de script : {0}\n Source de script : {1}, ligne : {2}, texte :\n{3}
