# Localized messages for BIRT. Messages here give 
# the text of Design Engine exceptions.

###########################################################
INVALID_TYPE=Tipo de datos no válido.

INVALID_EXPRSSION=Expresión Javascript no válida: {0}

CONVERT_FAILS=No se puede convertir el valor de {0} al tipo {1}.

birt.core.JavascriptCommonError=Han ocurrido errores durante la evaluación del script "{0}":\n{1}

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=El parámetro de informe "{0}" no existe.

birt.core.Javascript.variableNotExist=La variable de informe "{0}" no existe.

birt.core.Javascript.nativeNotFound=No se ha encontrado {0}.

birt.core.BirtComp.invalidRegularExpression=Expresión regular no válida.

error.NoSuchScriptExtension = No existe la extensión del script: {0}.

error.InvalidSeekOffset = Posición no válida {0}.

error.ExceedFileLength = Longitud de archivo superada.

error.CanotchangeReadOnlyBuffer = No se puede cambiar el búfer de sólo lectura.

error.FileOpenedInReadOnlyMode = El archivo está abierto en modo de sólo lectura.

error.FileHasBeenClosed = El archivo archivado se ha cerrado.

error.UnparseableString = No se puede analizar el valor de string: "{0}".

error.CannotStartupOSGIPlatform = No se puede iniciar el frame OSGI.

error.UnsupportedFileMode = Modo de archivo no admitido: {0}.

error.FolderNameIsNull = El nombre de la carpeta es una cadena nula o vacía.

error.FileNameIsNull = El nombre del archivo es una cadena nula o vacía.

error.NotExt2Archive = No es un archivo Ext2, la contraseña es: {0}.

error.NotCompoundFile = No es un archivo compuesto, la contraseña es: {0}.

error.ReadOnlyArchive = Archivo de sólo lectura.

error.UnsupportedArchiveVersion = Versión de archivo no admitida {0}.

error.UnsupportedBlockSize = Tamaño de bloque no admitido.

error.InvalidIndex = Índice no válido en el bloque {0}.

error.UnsupportedNodeType = tipo de nodo inesperado: {0} para nodo {1}.

error.NotSerializable = No serializable.

error.UnsupportedDataType = Este tipo de datos no es compatible todavía o no es serializable.

error.InvalidLockType = Tipo de bloqueo no válido: {0}.

error.ArchiveOpenForWrite = El archivo se debe abrir para su escritura. ID de sistema: {0}.

error.ExceedMaxBlockSize = El tamaño del encabezado del archivo no puede ser mayor de: {0}.

error.InvalidArchiveName= {0} no existe o no es una carpeta.

error.NullSource = el archivo de fuente o destino es nulo.

error.OutOfRange = La posición de búsqueda está fuera de los límites.

error.ReadOnlyTree = No se puede insertar una entrada en un árbol de sólo lectura.

error.CannotLoadNode = No se puede cargar el nodo: {0}.

error.KeySizeError = El tamaño de la clave es {0} en lugar de {1}.

error.MismatchKeyLength = Error de coincidencia de longitud de clave para clave de longitud fija.

error.ValueSizeError = El tamaño del valor es {0} en lugar de {1}.

error.MismatchValueLength = Error de coincidencia de longitud de valor para valor de longitud fija.

error.InvaldMagicTag = Etiqueta mágica no válida: {0}.

error.UnsupportedVersion = Versión no compatible: {0}.

error.InvalidCursor = Cursor no válido.

error.CusorNotInitialized = Se debe iniciar primero el cursor.

error.UnexpectedEqualKeys = Claves iguales inesperadas.

error.UnknownValueType = Tipo de valores desconocido: {0}.

error.ExceedMaxBlock = {0} ha superado el bloque máximo en RAM {1}.

error.MalformedInputError = Entrada incorrecta: carácter parcial al final.

error.MalformedInputAroundByte = Entrada incorrecta cerca del byte {0}.>>>>>>> 1.8