#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTEmitter.Description=Configurez les options pour un rendu de rapport au format MHTML (Single File Web Archive).

PPTEmitter.DisplayName=PowerPoint (PPT)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI

OptionDisplayValue.TextWrapping=Retour à la ligne automatique

OptionDisplayValue.PageOverFlow=Traitement du dépassement de page

OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu

OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages

OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page

OptionDisplayValue.FontSubstitution=Changement de police

OptionDisplayValue.ChartDpi=DPI de graphique

OptionDisplayValue.Export2Office2010And2013=Fichier d'exportation pour Microsoft Office 2010/2013

###########################################################
#Option Description
OptionDescription.BidiProcessing=Prend en charge le texte bidirectionnel.

OptionDescription.TextWrapping=Indique si le retour à la ligne est autorisé pour le texte.

OptionDescription.PageOverFlow=Contrôle le mode de répartition du contenu.

OptionDescription.FontSubstitution=Sélectionne des polices automatiquement lorsque la police spécifiée ne peut pas afficher le caractère.

OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

OptionDescription.Export2Office2010And2013=Prend en charge le format .mht dans ppt lorsque Office 2010/2013 est utilisé.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.