#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTEmitter.Description=Configure las opciones para presentar un informe en formato de archivo único de página Web (MHTML).
PPTEmitter.DisplayName=PowerPoint (MHTML)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Procesamiento de BIDI
OptionDisplayValue.TextWrapping=Autoajuste de texto
OptionDisplayValue.PageOverFlow=Procesamiento del desbordamiento de página
OptionDisplayValue.CLIP_CONTENT=Cortar contenido
OptionDisplayValue.FIT_TO_PAGE_SIZE=Ajustar a tamaño de página
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Salida de varias páginas
OptionDisplayValue.ENLARGE_PAGE_SIZE=Aumentar tamaño de página
OptionDisplayValue.FontSubstitution=Sustitución de fuente
OptionDisplayValue.ChartDpi=Chart DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=Se utiliza el procesamiento de BIDI.
OptionDescription.TextWrapping=El texto debe autoajustarse.
OptionDescription.PageOverFlow=Controle cómo se va a mostrar el contenido.
OptionDescription.FontSubstitution=Debe comprobar si el carácter existe en la fuente seleccionada.
OptionDescription.ChartDpi=The DPI used to generate chart.
