#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTEmitter.Description=配置用于以单一文件 Web 存档(MHTML)格式呈现报表的选项。

PPTEmitter.DisplayName=PowerPoint (PPT)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 处理

OptionDisplayValue.TextWrapping=自动换行

OptionDisplayValue.PageOverFlow=页面溢出处理

OptionDisplayValue.CLIP_CONTENT=剪裁内容

OptionDisplayValue.FIT_TO_PAGE_SIZE=适合大小

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=输出多页

OptionDisplayValue.ENLARGE_PAGE_SIZE=扩大页面大小

OptionDisplayValue.FontSubstitution=字体替代

OptionDisplayValue.ChartDpi=图表 DPI

OptionDisplayValue.Export2Office2010And2013=导出 Microsoft Office 2010/2013 文件

###########################################################
#Option Description
OptionDescription.BidiProcessing=支持双向文本。

OptionDescription.TextWrapping=表示文本是否可自动换行。

OptionDescription.PageOverFlow=控制如何输出内容。

OptionDescription.FontSubstitution=指定的字体无法显示该字符时自动选择字体。

OptionDescription.ChartDpi=DPI 用于生成图表。

OptionDescription.Export2Office2010And2013=使用 Office 2010/2013 时，ppt 支持 .mht 格式。

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。 例如，192。