#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTEmitter.Description=単一ファイル Web アーカイブ (MHTML) 形式でレポートをレンダリングするためのオプションを設定します。

PPTEmitter.DisplayName=PowerPoint (PPT)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=双方向テキストの処理

OptionDisplayValue.TextWrapping=文字列の折り返し

OptionDisplayValue.PageOverFlow=オーバーフローしているページの処理

OptionDisplayValue.CLIP_CONTENT=コンテンツの切り抜き

OptionDisplayValue.FIT_TO_PAGE_SIZE=ページサイズに合わせる

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=複数ページに出力

OptionDisplayValue.ENLARGE_PAGE_SIZE=ページサイズを大きくする

OptionDisplayValue.FontSubstitution=フォントの置き換え

OptionDisplayValue.ChartDpi=グラフの DPI

OptionDisplayValue.Export2Office2010And2013=Microsoft Office 2010/2013 のファイルをエクスポートする

###########################################################
#Option Description
OptionDescription.BidiProcessing=双方向テキストをサポートします。

OptionDescription.TextWrapping=文字列を折り返すかどうかを示します。

OptionDescription.PageOverFlow=コンテンツの出力方法を制御します。

OptionDescription.FontSubstitution=指定されたフォントで表示できない文字がある場合は、フォントを自動的に選択します。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

OptionDescription.Export2Office2010And2013=Office 2010/2013 を使用するときに PPT 内の .mht 形式をサポートします。

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。 例 : 192