#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTEmitter.Description=웹 보관 파일(MHTML) 형식의 보고서 렌더링 옵션을 구성합니다.

PPTEmitter.DisplayName=PowerPoint (PPT)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 처리

OptionDisplayValue.TextWrapping=텍스트 배치

OptionDisplayValue.PageOverFlow=페이지 오버플로 처리

OptionDisplayValue.CLIP_CONTENT=내용 자르기

OptionDisplayValue.FIT_TO_PAGE_SIZE=페이지 크기에 맞추기

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=여러 페이지로 출력

OptionDisplayValue.ENLARGE_PAGE_SIZE=페이지 크기 확대

OptionDisplayValue.FontSubstitution=글꼴 대체

OptionDisplayValue.ChartDpi=차트 DPI

OptionDisplayValue.Export2Office2010And2013=Microsoft Office 2010/2013 형식으로 파일 내보내기

###########################################################
#Option Description
OptionDescription.BidiProcessing=양방향 텍스트를 지원합니다.

OptionDescription.TextWrapping=텍스트 줄 바꿈 가능 여부를 나타냅니다.

OptionDescription.PageOverFlow=내용 출력 방식을 제어합니다.

OptionDescription.FontSubstitution=지정된 글꼴이 문자를 표시하지 못하는 경우 자동으로 글꼴을 선택합니다.

OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.

OptionDescription.Export2Office2010And2013=Office 2010/2013 사용 시 PPT에서 .mht 형식을 지원합니다.

###########################################################
#tooltip
Tooltip.ChartDpi=차트 엔진에서 차트를 생성하는 데 사용하는 DPI입니다. 예: 192.