TasksManager.Exception.RegisterTask=La tâche est nulle ou l''ID de tâche {0} existe déjà \!

TasksManager.Exception.DeregisterTask=Aucune tâche n''est enregistrées avec l''ID {0} \!

TasksManager.Excepion.RegisterWizard=L'ID d'assistant est nul \!

WizardBase.Excepion.RegisterWizard=L''ID de tâche {0} n''est pas enregistré \!

WizardBase.error.ErrorsEncountered=Erreurs rencontrées

WizardBase.Next=Suivant >

WizardBase.Back=< Retour

WizardBase.Finish=&Fin

WizardBase.Cancel=Annuler

WizardBase.error.FollowingErrorsReportedByTask=Les erreurs suivantes ont été renvoyées par le panneau de tâches que vous venez de quitter.

WizardBase.error.FollowingErrorEncountered=Les erreurs suivantes ont été rencontrées.

WizardBase.error.FollowingErrorsReportedWhileVerifying=Les erreurs suivantes ont été rapportées lors de la vérification de la définition du graphique.

ErrorDialog.text.ErrorList=Liste d'erreurs :

ErrorDialog.text.ShowDetails=Afficher les détail&s...

ErrorDialog.text.SuggestedFixes=Solutions proposées :

ErrorDialog.text.FixIt=\ \ \ &Réparer

ErrorDialog.text.ProceedWithoutFixing=Continuer sans ré&parer

ErrorDialog.text.Exception=Exception :

ErrorDialog.text.ShowTrace=Afficher la trace...

ErrorDialog.text.StackTrace=Trace de la pile :

ErrorDialog.text.Ok=\ \ \ \ \ OK

ErrorDialog.text.CausedBy=\n\nCausé par :

SubtaskHistory.Tooltip.Back=Revenir à {0}

SubtaskHistory.Text.Back=Précédent

SubtaskHistory.Tooltip.Forward=Avancer à {0}

SubtaskHistory.Text.Forward=Suivant

SubtaskHistory.Text.Invalid=\#Non valide
