TasksManager.Exception.RegisterTask=任务为空或任务 ID {0} 已存在\!

TasksManager.Exception.DeregisterTask=没有已注册 ID {0} 的任务\!

TasksManager.Excepion.RegisterWizard=向导 ID 为空\!

WizardBase.Excepion.RegisterWizard=任务 ID {0} 未注册\!

WizardBase.error.ErrorsEncountered=遇到错误

WizardBase.Next=下一步 >

WizardBase.Back=< 上一步

WizardBase.Finish=完成(&F)

WizardBase.Cancel=取消

WizardBase.error.FollowingErrorsReportedByTask=您刚才离开的任务面板报告下列错误

WizardBase.error.FollowingErrorEncountered=遇到下列错误

WizardBase.error.FollowingErrorsReportedWhileVerifying=验证图表定义时报告下列错误

ErrorDialog.text.ErrorList=错误列表:

ErrorDialog.text.ShowDetails=显示详细信息(&S)...

ErrorDialog.text.SuggestedFixes=建议的修复方法:

ErrorDialog.text.FixIt=\ \ \ 修复(&F)

ErrorDialog.text.ProceedWithoutFixing=继续而不修复(&P)

ErrorDialog.text.Exception=异常:

ErrorDialog.text.ShowTrace=显示跟踪...

ErrorDialog.text.StackTrace=堆栈跟踪:

ErrorDialog.text.Ok=\ \ \ \ \ 确定

ErrorDialog.text.CausedBy=\n\n原因:

SubtaskHistory.Tooltip.Back=后退到 {0}

SubtaskHistory.Text.Back=后退

SubtaskHistory.Tooltip.Forward=前进到 {0}

SubtaskHistory.Text.Forward=前进

SubtaskHistory.Text.Invalid=\#无效
