TasksManager.Exception.RegisterTask=タスクが NULL か、タスク ID {0} がすでに存在します。

TasksManager.Exception.DeregisterTask=ID が {0} のタスクは登録されていません。

TasksManager.Excepion.RegisterWizard=ウィザード ID が NULL です。

WizardBase.Excepion.RegisterWizard=タスク ID {0} は登録されていません。

WizardBase.error.ErrorsEncountered=エラー

WizardBase.Next=次へ >

WizardBase.Back=< 戻る

WizardBase.Finish=完了(&F)

WizardBase.Cancel=キャンセル

WizardBase.error.FollowingErrorsReportedByTask=今閉じたタスクパネルからエラーが報告されました。

WizardBase.error.FollowingErrorEncountered=次のエラーが発生しました。

WizardBase.error.FollowingErrorsReportedWhileVerifying=グラフの定義を検証中に、次のエラーが報告されました。

ErrorDialog.text.ErrorList=エラーの一覧 :

ErrorDialog.text.ShowDetails=詳細を表示(&S)...

ErrorDialog.text.SuggestedFixes=エラーの修正案 :

ErrorDialog.text.FixIt=\ \ \ 修正する(&F)

ErrorDialog.text.ProceedWithoutFixing=修正しないで続行(&P)

ErrorDialog.text.Exception=例外 :

ErrorDialog.text.ShowTrace=トレースを表示...

ErrorDialog.text.StackTrace=スタックトレース :

ErrorDialog.text.Ok=\ \ \ \ \ OK

ErrorDialog.text.CausedBy=\n\n原因 :

SubtaskHistory.Tooltip.Back={0} に戻る

SubtaskHistory.Text.Back=戻る

SubtaskHistory.Tooltip.Forward={0} に進む

SubtaskHistory.Text.Forward=進む

SubtaskHistory.Text.Invalid=\#無効
