TasksManager.Exception.RegisterTask=작업이 널(null)이거나 작업 ID {0}이(가) 이미 있습니다\!

TasksManager.Exception.DeregisterTask=ID가 {0}인 작업이 등록되지 않았습니다\!

TasksManager.Excepion.RegisterWizard=마법사 ID가 널(null)입니다\!

WizardBase.Excepion.RegisterWizard=작업 ID {0}이(가) 등록되지 않았습니다\!

WizardBase.error.ErrorsEncountered=오류 발생

WizardBase.Next=다음 >

WizardBase.Back=< 뒤로

WizardBase.Finish=마침(&F)

WizardBase.Cancel=취소

WizardBase.error.FollowingErrorsReportedByTask=다음 오류는 최근까지 작업한 작업 패널에서 보고되었습니다.

WizardBase.error.FollowingErrorEncountered=다음 오류가 발생되었습니다.

WizardBase.error.FollowingErrorsReportedWhileVerifying=다음 오류는 차트 정의를 확인하는 도중 보고되었습니다.

ErrorDialog.text.ErrorList=오류 목록:

ErrorDialog.text.ShowDetails=상세 정보 표시(&S)...

ErrorDialog.text.SuggestedFixes=제안된 수정:

ErrorDialog.text.FixIt=\ \ \ 수정(&F)

ErrorDialog.text.ProceedWithoutFixing=수정하지 않고 계속(&P)

ErrorDialog.text.Exception=예외:

ErrorDialog.text.ShowTrace=추적 표시...

ErrorDialog.text.StackTrace=추적 누적:

ErrorDialog.text.Ok=\ \ \ \ \ 확인

ErrorDialog.text.CausedBy=\n\n발생 원인:

SubtaskHistory.Tooltip.Back={0}(으)로 돌아가기

SubtaskHistory.Text.Back=뒤로

SubtaskHistory.Tooltip.Forward={0} 앞으로 가기

SubtaskHistory.Text.Forward=정방향

SubtaskHistory.Text.Invalid=\#잘못됨
