TasksManager.Exception.RegisterTask=La tarea es nula o el ID de tarea {0} ya existe.

TasksManager.Exception.DeregisterTask=No hay ninguna tarea con el ID {0} registrada.

TasksManager.Excepion.RegisterWizard=El ID de asistente es nulo.

WizardBase.Excepion.RegisterWizard=El ID de tarea {0} no está registrado.

WizardBase.error.ErrorsEncountered=Se han encontrado errores

WizardBase.Next=Siguiente >

WizardBase.Back=< Anterior

WizardBase.Finish=&Finalizar

WizardBase.Cancel=Cancelar

WizardBase.error.FollowingErrorsReportedByTask=El panel de tareas que acaba de abandonar ha detectado los siguientes errores

WizardBase.error.FollowingErrorEncountered=Se han detectado los siguientes errores

WizardBase.error.FollowingErrorsReportedWhileVerifying=Se han detectado los siguientes errores al verificar la definición del diagrama

ErrorDialog.text.ErrorList=Lista de errores:

ErrorDialog.text.ShowDetails=&Mostrar detalles...

ErrorDialog.text.SuggestedFixes=Correcciones propuestas:

ErrorDialog.text.FixIt=\ \ \ &Corregirlo

ErrorDialog.text.ProceedWithoutFixing=&Continuar sin corregir

ErrorDialog.text.Exception=Excepción:

ErrorDialog.text.ShowTrace=Mostrar rastreo...

ErrorDialog.text.StackTrace=Apilar rastreo:

ErrorDialog.text.Ok=\ \ \ \ \ Aceptar

ErrorDialog.text.CausedBy=\n\nCausado por:

SubtaskHistory.Tooltip.Back=Volver a {0}

SubtaskHistory.Text.Back=Anterior

SubtaskHistory.Tooltip.Forward=Seguir a {0}

SubtaskHistory.Text.Forward=Siguiente

SubtaskHistory.Text.Invalid=\#No válido
