###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=请从类别中选择一个示例报表
SampleReportsView.Text.Explorer=示例报表
SampleReportsView.Text.Preview=预览
SampleReportsView.Text.Description=说明
SampleReportsView.MessageDialog.Title=问题
SampleReportsView.MessageDialog.Message=“{0}”已存在。要替换它吗?
SampleReportsView.Action.exportSampleReport=保存
SampleReportsView.Action.openSampleReport=打开
SampleReportsView.Action.exportSampleReport.toolTipText=导出选择的示例报表
SampleReportsView.Action.openSampleReport.toolTipText.ide=创建报表项目并将报表放入项目文件夹
SampleReportsView.Action.openSampleReport.toolTipText.rcp=将选择的示例报表直接导出到 RCP 工作区文件夹
SampleReportsView.Text.Contribute_Samples=提供示例
IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=Project name:
IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=Project Name
IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=Project Exists
IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=The project already exists. Press ''{0}'' to use this project, press ''{1}'' to clear the existing project and create a new one, press ''{2}'' to cancel. 
IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=Overwrite

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=文件系统不区分大小写。存在一个与 ''{0}'' 冲突的现有项目。
NewReportProjectWizard.description=创建新报表项目。
NewReportProjectWizard.errorMessage=创建新报表项目时出现问题。
NewReportProjectWizard.errorOpeningWindow=打开某个窗口时出现问题。
NewReportProjectWizard.internalError=内部错误:{0}
NewReportProjectWizard.javaProject=创建 Java 项目
NewReportProjectWizard.perspSwitchMessage=此项目类型与 {0} 透视图相关联。是否立即切换至此透视图？
NewReportProjectWizard.perspSwitchTitle=确定切换透视图
NewReportProjectWizard.projectSetting=项目设置
NewReportProjectWizard.src=src
NewReportProjectWizard.title=报表项目
NewReportProjectWizard.windowTitle=新建报表项目
