###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=Sélectionnez un exemple d'état dans les catégories

SampleReportsView.Text.Explorer=Exemples d'états

SampleReportsView.Text.Preview=Aperçu

SampleReportsView.Text.Description=Description

SampleReportsView.MessageDialog.Title=Question

SampleReportsView.MessageDialog.Message=''{0}'' existe déjà. Voulez-vous le remplacer ?

SampleReportsView.Action.exportSampleReport=Enregistrer

SampleReportsView.Action.openSampleReport=&Ouvrir

SampleReportsView.Action.exportSampleReport.toolTipText=Exporter l'exemple d'état sélectionné

SampleReportsView.Action.openSampleReport.toolTipText.ide=Créer un projet d'état et placer l'état dans le dossier de projet

SampleReportsView.Action.openSampleReport.toolTipText.rcp=Exporter directement l'exemple d'état sélectionné dans le dossier de l'espace de travail RCP

SampleReportsView.Text.Contribute_Samples=Exemples de contribution

IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=&Nom du projet :

IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=Nom du projet

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=Le projet existe.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=Le projet existe déjà. Appuyez sur ''{0}'' pour utiliser ce projet, appuyez sur ''{1}'' pour supprimer le projet existant et en créer un nouveau, appuyez sur ''{2}'' pour annuler.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=&Ecraser

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=La casse n''est pas prise en compte par le système de fichiers. Un projet existant est en conflit avec ''{0}''.

NewReportProjectWizard.description=Créez un nouveau projet d'état.

NewReportProjectWizard.errorMessage=Problème lors de la création du projet d'état

NewReportProjectWizard.errorOpeningWindow=Problème d'ouverture d'une fenêtre.

NewReportProjectWizard.internalError=Erreur interne : {0}

NewReportProjectWizard.javaProject=Créer un projet Java

NewReportProjectWizard.perspSwitchMessage=Ce type de projet est associé à la perspective {0}. Souhaitez-vous basculer vers cette perspective maintenant ?

NewReportProjectWizard.perspSwitchTitle=Confirmer le changement de perspective

NewReportProjectWizard.projectSetting=Paramètre du projet

NewReportProjectWizard.src=src
NewReportProjectWizard.title=Projet d'état

NewReportProjectWizard.windowTitle=Nouveau projet d'état