###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=サンプルレポートをカテゴリから選択してください。

SampleReportsView.Text.Explorer=サンプルレポート

SampleReportsView.Text.Preview=プレビュー

SampleReportsView.Text.Description=説明

SampleReportsView.MessageDialog.Title=質問

SampleReportsView.MessageDialog.Message=''{0}'' はすでに存在します。置き換えますか ?

SampleReportsView.Action.exportSampleReport=保存

SampleReportsView.Action.openSampleReport=開く(&O)

SampleReportsView.Action.exportSampleReport.toolTipText=選択したサンプルレポートをエクスポートします

SampleReportsView.Action.openSampleReport.toolTipText.ide=レポートプロジェクトを作成して、レポートをプロジェクトフォルダに配置します

SampleReportsView.Action.openSampleReport.toolTipText.rcp=選択したサンプルレポートを RCP 作業フォルダに直接エクスポートします

SampleReportsView.Text.Contribute_Samples=サンプルの提供

IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=プロジェクト名(&N) :

IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=プロジェクト名

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=プロジェクトが存在します

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=すでにプロジェクトが存在します。このプロジェクトを使用するには、''{0}'' をクリックしてください。既存のプロジェクトをクリアして新しいプロジェクトを作成するには、''{1}'' をクリックしてください。キャンセルするには ''{2}'' をクリックしてください。

IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=上書き(&O)

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=ファイルシステムでは、大文字と小文字が区別されないため、既存のプロジェクトと同じ名前 "{0}" は使用できません。

NewReportProjectWizard.description=新しいレポートプロジェクトを作成します。

NewReportProjectWizard.errorMessage=新しいレポートプロジェクトを作成中にエラーが発生しました。

NewReportProjectWizard.errorOpeningWindow=ウィンドウを開けませんでした。

NewReportProjectWizard.internalError=内部エラー : {0}

NewReportProjectWizard.javaProject=Java プロジェクトの作成

NewReportProjectWizard.perspSwitchMessage=この種類のプロジェクトは {0} パースペクティブに関連付けられています。今すぐこのパースペクティブに切り替えますか ?

NewReportProjectWizard.perspSwitchTitle=パースペクティブの切り替え確認

NewReportProjectWizard.projectSetting=プロジェクトの設定

NewReportProjectWizard.src=src
NewReportProjectWizard.title=レポートプロジェクト

NewReportProjectWizard.windowTitle=新規レポートプロジェクト