###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=Seleccione un informe de muestra entre las categorías

SampleReportsView.Text.Explorer=Informes de muestras

SampleReportsView.Text.Preview=Vista previa

SampleReportsView.Text.Description=Descripción

SampleReportsView.MessageDialog.Title=Pregunta

SampleReportsView.MessageDialog.Message=El ''{0}'' ya existe. ¿Desea sustituirlo?

SampleReportsView.Action.exportSampleReport=Guardar

SampleReportsView.Action.openSampleReport=&Abrir

SampleReportsView.Action.exportSampleReport.toolTipText=Exportar el informe de muestras seleccionado

SampleReportsView.Action.openSampleReport.toolTipText.ide=Crear un proyecto de informe y colocar el informe en la carpeta del proyecto

SampleReportsView.Action.openSampleReport.toolTipText.rcp=Exportar el informe de muestra seleccionado directamente a la carpeta del área de trabajo RCP

SampleReportsView.Text.Contribute_Samples=Muestras de aportación

IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=&Nombre de proyecto:

IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=Nombre de proyecto

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=El proyecto ya existe

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=El proyecto ya existe. Pulse ''{0}'' para utilizar este proyecto, pulse ''{1}'' para  borrar el proyecto existente y crear uno nuevo o pulse ''{2}'' para cancelar.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=S&obrescribir

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=El sistema de archivos no distingue entre mayúsculas y minúsculas. Hay un proyecto existente que entra en conflicto con ''{0}''.

NewReportProjectWizard.description=Crear un nuevo proyecto de informe.

NewReportProjectWizard.errorMessage=Se ha producido un problema al crear el nuevo proyecto de informe.

NewReportProjectWizard.errorOpeningWindow=Se ha producido un problema al abrir una ventana.

NewReportProjectWizard.internalError=Error interno: {0}

NewReportProjectWizard.javaProject=Crear un proyecto Java

NewReportProjectWizard.perspSwitchMessage=Este tipo de proyecto está asociado a la perspectiva {0}. ¿Desea cambiar a esta perspectiva ahora?

NewReportProjectWizard.perspSwitchTitle=Confirmar cambio de perspectiva

NewReportProjectWizard.projectSetting=Ajustes de proyecto

NewReportProjectWizard.src=src
NewReportProjectWizard.title=Proyecto de informe

NewReportProjectWizard.windowTitle=Nuevo proyecto de informe