###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=Wählen Sie aus den Kategorien einen Beispielbericht aus

SampleReportsView.Text.Explorer=Beispielberichte

SampleReportsView.Text.Preview=Vorschau

SampleReportsView.Text.Description=Beschreibung

SampleReportsView.MessageDialog.Title=Frage

SampleReportsView.MessageDialog.Message=''{0}'' ist bereits vorhanden. Ersetzen?

SampleReportsView.Action.exportSampleReport=Speichern

SampleReportsView.Action.openSampleReport=Ö&ffnen

SampleReportsView.Action.exportSampleReport.toolTipText=Ausgewählten Beispielbericht exportieren

SampleReportsView.Action.openSampleReport.toolTipText.ide=Berichtprojekt erstellen und Bericht im Projektordner aufnehmen

SampleReportsView.Action.openSampleReport.toolTipText.rcp=Ausgewählten Beispielbericht direkt in den Ordner des RCP-Arbeitsbereichs exportieren

SampleReportsView.Text.Contribute_Samples=Beispiele beitragen

IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=Projekt&name:

IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=Projektname

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=Projekt bereits vorhanden.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=Das Projekt ist bereits vorhanden. Drücken Sie '{0}', um dieses Projekt zu verwenden, '{1}', um das vorhandene Projekt zu löschen und ein neues zu erstellen, oder '{2}', um den Vorgang abzubrechen.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=Ü&berschreiben

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=Im Dateisystem wird Groß- und Kleinschreibung nicht unterschieden. Es ist bereits ein Projekt vorhanden, dessen Benennung zu ''{0}'' im Widerspruch steht.

NewReportProjectWizard.description=Neues Berichtprojekt erstellen

NewReportProjectWizard.errorMessage=Beim Erstellen des neuen Berichtprojekts ist ein Fehler aufgetreten.

NewReportProjectWizard.errorOpeningWindow=Beim Öffnen eines Fensters ist ein Fehler aufgetreten.

NewReportProjectWizard.internalError=Interner Fehler: {0}

NewReportProjectWizard.javaProject=Java-Projekt erstellen

NewReportProjectWizard.perspSwitchMessage=Diese Art von Projekt ist mit der Perspektive {0} verknüpft. Jetzt zu dieser Perspektive wechseln?

NewReportProjectWizard.perspSwitchTitle=Wechsel der Perspektive bestätigen

NewReportProjectWizard.projectSetting=Projekteinstellung

NewReportProjectWizard.src=src
NewReportProjectWizard.title=Berichtprojekt

NewReportProjectWizard.windowTitle=Neues Berichtprojekt