ChartAggregationCellViewProvider.Chart.DisplayName=Diagrama

ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Seleccionar enlace de datos:

ChartDataSetBindingSheetImpl.Title.SheetTitle=Datos - Seleccionar conjunto de datos

ChartPageGenerator.List.General=General

ChartPageGenerator.List.AltText=Texto alternativo

ChartDataBindingPage.Lbl.Parameter=Parámetros

ChartDataBindingPage.Lbl.DataType=Tipo de datos

ChartDataBindingPage.Lbl.Value=Valor

ChartDataBindingPage.Lbl.None=Ninguno

ChartDataBindingPage.Lbl.DefaultValue=(Valor predeterminado)

ChartDataBindingPage.Lbl.DataSet=Conjunto de datos

ChartDataBindingPage.Lbl.SaveParameterBinding=Guardar enlace de parámetros

ChartDataBindingPage.Lbl.SaveDataSet=Cambiar conjunto de datos

ChartDataBindingPage.Msg.AskSaveDataSet=¿Desea cambiar el conjunto de datos enlazado?

DesignerRepresentation.error.Error=Error:

DesignerRepresentation.log.UnableToFind=No es posible encontrar el modelo de diagrama mientras se procesa en el diseñador.

DesignerRepresentation.msg.InvalidChart=El diagrama actual no es válido. Si desea continuar trabajando en él, primero debe eliminarlo.

ChartReportItemBuilderImpl.problem.hasNotBeenFound=El diagrama no se ha enlazado aún a un conjunto de datos o cubo de datos.

ChartReportItemBuilderImpl.log.UnableToLocate=No se puede localizar el empaquetador de elementos de informe para el objeto de diagrama.

ChartPreferencePage.Label.MaxRowNumber=&Número de fila máximo de vista previa de datos:

ChartPreferencePage.Error.MaxRowInvalid=El número de fila máximo debe ser entero e inferior a {0}

ChartPreferencePage.Label.EnableLivePreview=&Activar la vista previa en tiempo real en el compilador de diagramas

ChartReportItemUIImpl.Command.ResizeChart=Cambiar tamaño del diagrama

ChartReportItemUIImpl.log.ReceivedNotification=Se ha recibido la notificación para disponer de la figura de diagrama extendida.

ChartReportItemViewProvider.BarChart.Text.Title=Título del diagrama de barras

ChartReportItemViewProvider.ChartViewName=Diagrama

ChartExpressionProvider.Category.ChartVariables=Variables

ChartExpressionProvider.ChartVariables.DataPoints=Punto de datos de diagrama

ChartExpressionProvider.ChartVariables.LegendItems=Leyendas de diagrama

ChartExpressionProvider.DataPoints.BaseValue=Datos de categoría

ChartExpressionProvider.DataPoints.OrthogonalValue=Datos de valor

ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=Evento

ChartExpressionProvider.DataPoints.SeriesValue=Datos de serie

ChartColumnBindingDialog.Button.Refresh=Ac&tualizar

OpenChartTaskAction.Text.SelectChartType=Se&leccionar tipo de diagrama...

OpenChartTaskAction.Text.SelectData=S&eleccionar datos:

OpenChartTaskAction.Text.FormatChart=Formato de d&iagrama...

FlipAxisAction.Text.FlipAxis=I&nvertir eje

GeneralPage.Library.Included=Librería:

ChartEventHandlerPage.dialog.Browse=&Examinar...

ReportDataServiceProvider.Label.DataModel=(Modelo de datos)

ReportDataServiceProvider.Option.None=<Ninguno>

ReportDataServiceProvider.Option.Inherits=<Container''s {0}>

ReportDataServiceProvider.Tooltip.Aggregate=Total

ReportDataServiceProvider.Tooltip.GroupExpression=Expresión de grupo:

ReportDataServiceProvider.Tooltip.OnGroup=En grupo:

ShowAxisAction.Text.ShowValueAxis=Mostrar eje de valor

StandardChartDataSheet.CheckCubeWarning=Los enlaces de columna deben contener una dimensión y una medida como mínimo.

StandardChartDataSheet.Combo.DataCubes=---------Cubos de datos---------

StandardChartDataSheet.Combo.DataSets=----------Conjuntos de datos----------

StandardChartDataSheet.Combo.InheritColumnsGroups=Heredar columnas y grupos

StandardChartDataSheet.Combo.InheritColumnsOnly=Heredar sólo columnas

StandardChartDataSheet.Combo.ReportItems=--------Elementos de informe--------

StandardChartDataSheet.Label.Axis=Eje

StandardChartDataSheet.Label.ToBindADataColumn=Use el menú que aparece al hacer clic con el botón derecho para vincular los datos al diagrama

StandardChartDataSheet.Label.SelectDataSet=Seleccionar datos

StandardChartDataSheet.Label.UseReportData=&Heredar datos de contenedor

StandardChartDataSheet.Label.UseReportItem=Usar elemento de info&rme

StandardChartDataSheet.Label.UseDataSet=Utilizar &Datos de

StandardChartDataSheet.Label.DataPreview=Vista previa de datos

StandardChartDataSheet.Label.DataBinding=Enl&ace de datos...

StandardChartDataSheet.Label.Filters=Fil&tros...

StandardChartDataSheet.Label.Parameters=&Parámetros...

StandardChartDataSheet.Task.Description=Seleccione el conjunto de datos que desea mostrar en el diagrama y enlácelo a la serie.

StandardChartDataSheet.Exception.UnableToSwitchToDataset=No es posible cambiar al conjunto de datos

StandardChartDataSheet.Label.InsertAggregation=Insertar agregación

StandardChartDataSheet.Label.DataExpressionBuilder=Compilador de expresiones de datos

StandardChartDataSheet.Label.DragCube=Hacer clic con el botón derecho o arrastrar los niveles a Serie de categoría o Serie Y opcional, Medidas a serie de valor.

StandardChartDataSheet.Label.Component=\ Componente

StandardChartDataSheet.Label.CubeTree=Cubo de datos: Grupos y resúmenes

StandardChartDataSheet.Label.Overlay=Superposición

StandardChartDataSheet.Label.Series=Series

StandardChartDataSheet.Label.ShareCrossTab=En la serie (Y) del valor, haga clic en el botón de flecha y seleccione una medida de la lista.

StandardChartDataSheet.Label.ShowDataPreview=&Mostrar vista previa.

StandardChartDataSheet.Label.UseAsCategoryXAxis=&Usar como eje (X) de la categoría

StandardChartDataSheet.Label.UseAsCategorySeries=&Usar como serie de categoría

StandardChartDataSheet.Label.PlotAsValueYSeries=&Dibujar como serie (Y) del valor

StandardChartDataSheet.Label.PlotAsGaugeValue=&Dibujar como valor métrico

StandardChartDataSheet.Label.PlotAsValueSeries=&Dibujar como serie del valor

StandardChartDataSheet.Label.UseToGroupYSeries=U&sar para agrupar serie Y

StandardChartDataSheet.Label.EnableLivePreview=Activar la vista previa del diagrama en tiempo real

StandardChartDataSheet.Label.UseToGroupValueSeries=U&sar para agrupar serie del valor

StandardChartDataSheet.Message.RetrieveData=Recuperar datos para vista previa

StandardChartDataSheet.NewDataCube=<Nuevo cubo de datos...>

StandardChartDataSheet.NewDataSet=<Nuevo conjunto de datos...>

ChartBindingGroupDescriptorProvider.DataSets.Default=---Conjuntos de datos---

ChartBindingGroupDescriptorProvider.DataCubes.Default=---Cubos de datos---

BindingPage.Data.Label=Datos:

BindingPage.ReportItem.NoName=Sin nombre

Error.ChartShouldIncludeAxes=El diagrama debería contener ejes.

ChartCubeFilterConditionBuilder.Expression.CategoryItem.Prefix=Categoría:

ChartCubeFilterConditionBuilder.Expression.ValueItemPrefix=Valor:

ChartCubeFilterConditionBuilder.Expression.YOptionItem.Prefix=Opción Y:

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.selectVauleUnavailable=Lista de valores no disponible con la expresión indicada.

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.illegalVauleExpr=Sólo se puede obtener la lista de valores de las expresiones con un formato datos["nombre"]/[nombre].
