ChartAggregationCellViewProvider.Chart.DisplayName=차트

ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=데이터 바인딩 선택:

ChartDataSetBindingSheetImpl.Title.SheetTitle=데이터 - 데이터 집합 선택

ChartPageGenerator.List.General=일반

ChartPageGenerator.List.AltText=ALT 텍스트

ChartDataBindingPage.Lbl.Parameter=매개 변수

ChartDataBindingPage.Lbl.DataType=데이터 형식

ChartDataBindingPage.Lbl.Value=값

ChartDataBindingPage.Lbl.None=없음

ChartDataBindingPage.Lbl.DefaultValue=(기본값)

ChartDataBindingPage.Lbl.DataSet=데이터 집합

ChartDataBindingPage.Lbl.SaveParameterBinding=매개 변수 바인딩 저장

ChartDataBindingPage.Lbl.SaveDataSet=데이터 집합 변경

ChartDataBindingPage.Msg.AskSaveDataSet=바인딩된 데이터 집합을 변경하시겠습니까?

DesignerRepresentation.error.Error=오류:

DesignerRepresentation.log.UnableToFind=디자이너에서 렌더링하는 동안에는 차트 모델을 찾을 수 없습니다.

DesignerRepresentation.msg.InvalidChart=현재 차트가 잘못되었습니다. 이 차트에서 작업을 계속하려면 먼저 삭제하십시오.

ChartReportItemBuilderImpl.problem.hasNotBeenFound=차트가 아직 데이터 집합이나 데이터 큐브에 바인딩되지 않았습니다.

ChartReportItemBuilderImpl.log.UnableToLocate=차트 개체에 대한 보고서 항목 래퍼를 찾을 수 없습니다.

ChartPreferencePage.Label.MaxRowNumber=최대 데이터 미리 보기 행 번호(&M):

ChartPreferencePage.Error.MaxRowInvalid=최대 행 번호는 {0} 이상의 정수이어야 합니다.

ChartPreferencePage.Label.EnableLivePreview=차트 빌더에서 실시간 미리 보기 사용(&E)

ChartReportItemUIImpl.Command.ResizeChart=차트 크기 조정

ChartReportItemUIImpl.log.ReceivedNotification=확장 차트 그림을 삭제하기 위한 통지가 수신되었습니다.

ChartReportItemViewProvider.BarChart.Text.Title=막대 차트 제목

ChartReportItemViewProvider.ChartViewName=차트

ChartExpressionProvider.Category.ChartVariables=변수

ChartExpressionProvider.ChartVariables.DataPoints=차트 데이터 요소

ChartExpressionProvider.ChartVariables.LegendItems=차트 범례

ChartExpressionProvider.DataPoints.BaseValue=범주 데이터

ChartExpressionProvider.DataPoints.OrthogonalValue=값 데이터

ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=이벤트

ChartExpressionProvider.DataPoints.SeriesValue=계열 데이터

ChartColumnBindingDialog.Button.Refresh=새로 고침(&F)

OpenChartTaskAction.Text.SelectChartType=차트 형식 선택(&L)...

OpenChartTaskAction.Text.SelectData=데이터 선택(&E)...

OpenChartTaskAction.Text.FormatChart=차트 형식 지정(&H)...

FlipAxisAction.Text.FlipAxis=축 반전(&P)

GeneralPage.Library.Included=라이브러리:

ChartEventHandlerPage.dialog.Browse=찾아보기(&B)...

ReportDataServiceProvider.Label.DataModel=(데이터 모델)

ReportDataServiceProvider.Option.None=<없음>

ReportDataServiceProvider.Option.Inherits=<컨테이너의 {0}>

ReportDataServiceProvider.Tooltip.Aggregate=집계:

ReportDataServiceProvider.Tooltip.GroupExpression=그룹 식:

ReportDataServiceProvider.Tooltip.OnGroup=그룹 위치:

ShowAxisAction.Text.ShowValueAxis=값 축 표시

StandardChartDataSheet.CheckCubeWarning=열 바인딩에는 차원 및 측정값이 하나 이상 포함되어야 합니다.

StandardChartDataSheet.Combo.DataCubes=---------데이터 큐브---------

StandardChartDataSheet.Combo.DataSets=----------데이터 집합----------

StandardChartDataSheet.Combo.InheritColumnsGroups=열 및 그룹 상속

StandardChartDataSheet.Combo.InheritColumnsOnly=열만 상속

StandardChartDataSheet.Combo.ReportItems=--------보고서 항목--------

StandardChartDataSheet.Label.Axis=축

StandardChartDataSheet.Label.ToBindADataColumn=데이터를 차트로 바인딩하려면 마우스 오른쪽 단추를 사용하십시오.

StandardChartDataSheet.Label.SelectDataSet=데이터 선택

StandardChartDataSheet.Label.UseReportData=컨테이너에서 데이터 상속(&I)

StandardChartDataSheet.Label.UseReportItem=보고서 항목 사용(&R)

StandardChartDataSheet.Label.UseDataSet=데이터 사용 위치(&D)

StandardChartDataSheet.Label.DataPreview=데이터 미리 보기

StandardChartDataSheet.Label.DataBinding=데이터 바인딩(&A)...

StandardChartDataSheet.Label.Filters=필터(&T)...

StandardChartDataSheet.Label.Parameters=매개 변수(&P)...

StandardChartDataSheet.Task.Description=차트에 표시하고 계열에 바인딩할 데이터를 선택합니다.

StandardChartDataSheet.Exception.UnableToSwitchToDataset=데이터 집합으로 전환할 수 없음

StandardChartDataSheet.Label.InsertAggregation=집계 삽입

StandardChartDataSheet.Label.DataExpressionBuilder=데이터 식 빌더

StandardChartDataSheet.Label.DragCube=수준을 마우스 오른쪽 단추로 누르거나 범주 계열 또는 옵션 Y 계열로 끌고, 측정값을 마우스 오른쪽 단추로 누르거나 값 계열로 끄십시오.

StandardChartDataSheet.Label.Component=\ 구성 요소

StandardChartDataSheet.Label.CubeTree=데이터 큐브: 그룹 및 요약

StandardChartDataSheet.Label.Overlay=이중

StandardChartDataSheet.Label.Series=계열

StandardChartDataSheet.Label.ShareCrossTab=값(Y) 계열에서 화살표 단추를 클릭하고 목록에서 측정값을 선택합니다.

StandardChartDataSheet.Label.ShowDataPreview=미리 보기 표시(&S)

StandardChartDataSheet.Label.UseAsCategoryXAxis=범주 (X) 축으로 사용(&U)

StandardChartDataSheet.Label.UseAsCategorySeries=범주 계열로 사용(&U)

StandardChartDataSheet.Label.PlotAsValueYSeries=값 (Y) 계열로 플롯(&P)

StandardChartDataSheet.Label.PlotAsGaugeValue=미터 값으로 플롯(&P)

StandardChartDataSheet.Label.PlotAsValueSeries=값 계열로 플롯(&P)

StandardChartDataSheet.Label.UseToGroupYSeries=Y 계열을 그룹화하는 데 사용(&S)

StandardChartDataSheet.Label.EnableLivePreview=실시간 차트 미리 보기 사용

StandardChartDataSheet.Label.UseToGroupValueSeries=값 계열을 그룹화하는 데 사용(&S)

StandardChartDataSheet.Message.RetrieveData=미리 볼 데이터를 검색하십시오.

StandardChartDataSheet.NewDataCube=<새 데이터 큐브...>

StandardChartDataSheet.NewDataSet=<새 데이터 집합...>

ChartBindingGroupDescriptorProvider.DataSets.Default=---데이터 집합---

ChartBindingGroupDescriptorProvider.DataCubes.Default=---데이터 큐브---

BindingPage.Data.Label=데이터:

BindingPage.ReportItem.NoName=이름 없음

Error.ChartShouldIncludeAxes=차트에는 축이 포함되어야 합니다.

ChartCubeFilterConditionBuilder.Expression.CategoryItem.Prefix=범주:

ChartCubeFilterConditionBuilder.Expression.ValueItemPrefix=값:

ChartCubeFilterConditionBuilder.Expression.YOptionItem.Prefix=Y 옵션:

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.selectVauleUnavailable=지정한 식으로 값 목록을 사용할 수 없습니다.

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.illegalVauleExpr=데이터["이름"]/[이름] 형식의 식만 값 목록을 가져올 수 있습니다.
