ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Datenbindung auswählen:
ChartDataSetBindingSheetImpl.Title.SheetTitle=Daten - Datensatz auswählen

ChartDataBindingPage.Lbl.Parameter=Parameter
ChartDataBindingPage.Lbl.DataType=Datentyp
ChartDataBindingPage.Lbl.Value=Wert
ChartDataBindingPage.Lbl.None=Keine
ChartDataBindingPage.Lbl.DefaultValue=(Standardwert)
ChartDataBindingPage.Lbl.DataSet=Datensatz
ChartDataBindingPage.Lbl.SaveParameterBinding=Parameterbindung speichern
ChartDataBindingPage.Lbl.SaveDataSet=Datensatz ändern
ChartDataBindingPage.Msg.AskSaveDataSet=Möchten Sie den gebundenen Datensatz ändern?

DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.log.UnableToFind=Diagrammmodel konnte während des Renderns im Designer nicht gefunden werden.

ChartReportItemBuilderImpl.problem.hasNotBeenFound=Das Diagramm wurde noch nicht mit einem Datensatz verknüpft.
ChartReportItemBuilderImpl.log.UnableToLocate=Berichtobjekt-Wrapper für Diagrammobjekt kann nicht gefunden werden.

ChartPreferencePage.Label.MaxRowNumber=&Maximale Zeilenzahl der Datenvorschau:
ChartPreferencePage.Error.MaxRowInvalid=Die maximale Zeilenzahl muss eine ganze Zahl und kleiner als {0} sein.
ChartPreferencePage.Label.EnableLivePreview=&Live-Vorschau im Chart Builder aktivieren

ChartReportItemUIImpl.log.ReceivedNotification=Auftrag zur Entfernung einer erweiterten Diagrammabbildung erhalten.

ChartExpressionProvider.Category.ChartVariables=Diagrammvariablen
ChartExpressionProvider.ChartVariables.DataPoints=Datenpunkte
ChartExpressionProvider.DataPoints.BaseValue=Kategoriedaten
ChartExpressionProvider.DataPoints.OrthogonalValue=Wertdaten
ChartExpressionProvider.DataPoints.SeriesValue=Datenreihendaten

OpenChartTaskAction.Text.SelectChartType=&Diagrammtyp auswählen...
OpenChartTaskAction.Text.SelectData=D&aten auswählen...
OpenChartTaskAction.Text.FormatChart=Diagramm &formatieren...

ChartGeneralTabUIImpl.category.general=Allgemein
ChartGeneralTabUIImpl.category.types=Typen

GeneralPage.Library.Included=Bibliothek:
