ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=选择数据绑定:
ChartDataSetBindingSheetImpl.Title.SheetTitle=数据 - 选择数据集

ChartDataBindingPage.Lbl.Parameter=参数
ChartDataBindingPage.Lbl.DataType=数据类型
ChartDataBindingPage.Lbl.Value=值
ChartDataBindingPage.Lbl.None=无
ChartDataBindingPage.Lbl.DefaultValue=（默认值）
ChartDataBindingPage.Lbl.DataSet=数据集
ChartDataBindingPage.Lbl.SaveParameterBinding=保存参数绑定
ChartDataBindingPage.Lbl.SaveDataSet=更改数据集
ChartDataBindingPage.Msg.AskSaveDataSet=是否要更改绑定数据集?

DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.log.UnableToFind=设计器中执行呈现操作时无法找到图表模型
ChartReportItemBuilderImpl.problem.hasNotBeenFound=该图表尚未绑定到数据集。
ChartReportItemBuilderImpl.log.UnableToLocate=无法为图表对象找到报表项包装程序。

ChartPreferencePage.Label.MaxRowNumber=数据预览的最大行号(&M):
ChartPreferencePage.Error.MaxRowInvalid=最大行号必须为小于 {0} 的整数
ChartPreferencePage.Label.EnableLivePreview=在图表生成器中启用实时预览(&E)

ChartReportItemUIImpl.log.ReceivedNotification=收到关于清除扩展图表的通知。

ChartExpressionProvider.Category.ChartVariables=变量
ChartExpressionProvider.ChartVariables.DataPoints=图表数据点
ChartExpressionProvider.DataPoints.BaseValue=类别数据
ChartExpressionProvider.DataPoints.OrthogonalValue=值数据
ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=事件
ChartExpressionProvider.DataPoints.SeriesValue=系列数据
ChartColumnBindingDialog.Button.AddAggregation=添加聚合...
ChartColumnBindingDialog.Button.Refresh=刷新

OpenChartTaskAction.Text.SelectChartType=选择图表类型(&S)...
OpenChartTaskAction.Text.SelectData=选择数据(&A)...
OpenChartTaskAction.Text.FormatChart=图表格式(&F)...
FlipAxisAction.Text.FlipAxis=Fli&p Axis

GeneralPage.Library.Included=库:
ChartEventHandlerPage.dialog.Browse=浏览(&B)...
ReportDataServiceProvider.Option.None=<无>
ReportDataServiceProvider.Tooltip.Aggregate=聚合: 
ReportDataServiceProvider.Tooltip.GroupExpression=组表达式: 
ReportDataServiceProvider.Tooltip.OnGroup=按组: 

StandardChartDataSheet.Combo.DataCubes=---------Data Cubes---------
StandardChartDataSheet.Combo.DataSets=----------Data Sets----------
StandardChartDataSheet.Combo.ReportItems=--------Report Items--------
StandardChartDataSheet.Label.ToBindADataColumn=使用右键菜单或将列拖到系列字段中。
StandardChartDataSheet.Label.SelectDataSet=选择数据
StandardChartDataSheet.Label.UseReportData=从容器继承数据(&I)
StandardChartDataSheet.Label.UseReportItem=使用报表项(&R)
StandardChartDataSheet.Label.UseDataSet=使用以下来源的数据(&D)
StandardChartDataSheet.Label.DataPreview=数据预览
StandardChartDataSheet.Label.DataBinding=数据绑定(&A)...
StandardChartDataSheet.Label.Filters=筛选器(&T)...
StandardChartDataSheet.Label.Parameters=参数(&P)...
StandardChartDataSheet.Task.Description=选择图表中要显示的数据并将其绑定到系列。
StandardChartDataSheet.Exception.UnableToSwitchToDataset=无法切换到数据集 
StandardChartDataSheet.Label.InsertAggregation=插入聚合
StandardChartDataSheet.Label.DataExpressionBuilder=数据表达式生成器
StandardChartDataSheet.Label.DragCube=右键单击或将级别拖动到“类别系列”或“可选 Y 系列”，将“度量”拖动到“值系列”。
StandardChartDataSheet.Label.Component=\ 组件
StandardChartDataSheet.Label.CubeTree=多维数据集: 组和摘要
StandardChartDataSheet.Label.Overlay=覆盖 
StandardChartDataSheet.Label.Series=系列 
StandardChartDataSheet.Label.UseAsCategoryXAxis=用作类别 (X) 轴
StandardChartDataSheet.Label.UseAsCategorySeries=用作类别系列
StandardChartDataSheet.Label.PlotAsValueYSeries=绘制为值 (Y) 系列
StandardChartDataSheet.Label.PlotAsGaugeValue=绘制为仪表值
StandardChartDataSheet.Label.PlotAsValueSeries=绘制为值系列
StandardChartDataSheet.Label.UseToGroupYSeries=用来将 Y 系列分组
StandardChartDataSheet.Label.EnableLivePreview=启用实时图表预览
StandardChartDataSheet.Label.UseToGroupValueSeries=用来将值系列分组
StandardChartDataSheet.NewDataCube=<New Data Cube...>
StandardChartDataSheet.NewDataSet=<New Data Set...>

ChartBindingGroupDescriptorProvider.DataSets.Default=---数据集---
ChartBindingGroupDescriptorProvider.DataCubes.Default=---多维数据集---
BindingPage.Data.Label=数据:
Error.ChartShouldIncludeAxes=Chart is expected to include axes.
