ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=データバインドの選択 :
ChartDataSetBindingSheetImpl.Title.SheetTitle=データ - データセットの選択

ChartDataBindingPage.Lbl.Parameter=パラメタ
ChartDataBindingPage.Lbl.DataType=データ型
ChartDataBindingPage.Lbl.Value=値
ChartDataBindingPage.Lbl.None=なし
ChartDataBindingPage.Lbl.DefaultValue=(デフォルト値)
ChartDataBindingPage.Lbl.DataSet=データセット
ChartDataBindingPage.Lbl.SaveParameterBinding=パラメタバインドの保存
ChartDataBindingPage.Lbl.SaveDataSet=データセットの変更
ChartDataBindingPage.Msg.AskSaveDataSet=バインドされたデータセットを変更しますか ?

DesignerRepresentation.error.Error=エラー : 
DesignerRepresentation.error.Error=エラー : 
DesignerRepresentation.log.UnableToFind=デザイナで描画中に、グラフのモデルが見つかりません。

ChartReportItemBuilderImpl.problem.hasNotBeenFound=グラフはデータセットにバインドされていません。
ChartReportItemBuilderImpl.log.UnableToLocate=グラフオブジェクトのレポート項目ラッパーが見つかりません。

ChartPreferencePage.Label.MaxRowNumber=データプレビューの最大行数 (&M):
ChartPreferencePage.Error.MaxRowInvalid=最大行数には、{0} より小さい整数を指定してください。
ChartPreferencePage.Label.EnableLivePreview=グラフビルダでライブプレビューを有効化する(&E)

ChartReportItemUIImpl.log.ReceivedNotification=拡張された図表を破棄する通知を受け取りました。

ChartExpressionProvider.Category.ChartVariables=グラフの変数
ChartExpressionProvider.ChartVariables.DataPoints=データポイント
ChartExpressionProvider.DataPoints.BaseValue=カテゴリデータ
ChartExpressionProvider.DataPoints.OrthogonalValue=値データ
ChartExpressionProvider.DataPoints.SeriesValue=系列データ

OpenChartTaskAction.Text.SelectChartType=グラフの種類の選択(&S)...
OpenChartTaskAction.Text.SelectData=データの選択(&A)...
OpenChartTaskAction.Text.FormatChart=グラフの書式設定(&F)...

ChartGeneralTabUIImpl.category.general=全般
ChartGeneralTabUIImpl.category.types=型

GeneralPage.Library.Included=ライブラリ :

