ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Sélectionner la liaison de données :
ChartDataSetBindingSheetImpl.Title.SheetTitle=Données - Sélectionner un jeu de données

ChartDataBindingPage.Lbl.Parameter=Paramètres
ChartDataBindingPage.Lbl.DataType=Type de données
ChartDataBindingPage.Lbl.Value=Valeur
ChartDataBindingPage.Lbl.None=Aucun
ChartDataBindingPage.Lbl.DefaultValue=(Valeur par défaut)
ChartDataBindingPage.Lbl.DataSet=Jeu de données
ChartDataBindingPage.Lbl.SaveParameterBinding=Enregistrer la liaison de paramètres
ChartDataBindingPage.Lbl.SaveDataSet=Modifier le jeu de données
ChartDataBindingPage.Msg.AskSaveDataSet=Souhaitez-vous modifier le jeu de données lié ?

DesignerRepresentation.error.Error=Erreur : 
DesignerRepresentation.error.Error=Erreur : 
DesignerRepresentation.log.UnableToFind=Impossible de trouver le modèle de graphique pendant le rendu dans Designer.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=Le graphique n'a pas encore été lié à un jeu de données.
ChartReportItemBuilderImpl.log.UnableToLocate=Impossible de localiser le wrapper d'élément d'état pour l'objet de graphique.

ChartPreferencePage.Label.MaxRowNumber=&Nombre max. de lignes dans la prévisualisation des données :
ChartPreferencePage.Error.MaxRowInvalid=Le nombre max. de lignes doit être un nombre entier inférieur à {0}
ChartPreferencePage.Label.EnableLivePreview=Activer l'aperçu direct dans le générateur de graphiques(&E)

ChartReportItemUIImpl.log.ReceivedNotification=Réception d'une notification de rejet des données du graphique étendu.

ChartExpressionProvider.Category.ChartVariables=Variables de graphique
ChartExpressionProvider.ChartVariables.DataPoints=Points de données
ChartExpressionProvider.DataPoints.BaseValue=Données de catégorie
ChartExpressionProvider.DataPoints.OrthogonalValue=Données de valeur
ChartExpressionProvider.DataPoints.SeriesValue=Données de la série

OpenChartTaskAction.Text.SelectChartType=&Sélectionner le type de graphique...
OpenChartTaskAction.Text.SelectData=Sélectionner des d&onnées...
OpenChartTaskAction.Text.FormatChart=&Formater le graphique...

GeneralPage.Library.Included=Bibliothèque :
ChartEventHandlerPage.dialog.Browse=&Browse...
