ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=选择数据绑定:
ChartDataSetBindingSheetImpl.Title.SheetTitle=数据 - 选择数据集

ChartDataBindingPage.Lbl.Parameter=参数
ChartDataBindingPage.Lbl.DataType=时期类型
ChartDataBindingPage.Lbl.Value=值
ChartDataBindingPage.Lbl.None=无
ChartDataBindingPage.Lbl.DefaultValue=（默认值）
ChartDataBindingPage.Lbl.DataSet=数据集
ChartDataBindingPage.Lbl.SaveParameterBinding=保存参数绑定
ChartDataBindingPage.Lbl.SaveDataSet=更改数据集
ChartDataBindingPage.Msg.AskSaveDataSet=是否要更改绑定数据集？

DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.log.UnableToFind=设计器中执行呈现操作时无法找到图表模型
ChartReportItemBuilderImpl.problem.hasNotBeenFound=该图表尚未绑定到数据集。
ChartReportItemBuilderImpl.log.UnableToLocate=无法为图表对象找到报表项包装程序。

ChartPreferencePage.Label.MaxRowNumber=数据预览的最大行号(&M):
ChartPreferencePage.Error.MaxRowInvalid=最大行号必须为小于 {0} 的整数
ChartPreferencePage.Label.EnableLivePreview=在图表生成器中启用实时预览(&E)

ChartReportItemUIImpl.log.ReceivedNotification=收到关于清除扩展图表的通知。

ChartExpressionProvider.Category.ChartVariables=图表变量
ChartExpressionProvider.ChartVariables.DataPoints=数据点
ChartExpressionProvider.DataPoints.BaseValue=类别数据
ChartExpressionProvider.DataPoints.OrthogonalValue=值数据
ChartExpressionProvider.DataPoints.SeriesValue=系列数据

OpenChartTaskAction.Text.SelectChartType=选择图表类型(&S)...
OpenChartTaskAction.Text.SelectData=选择数据(&A)...
OpenChartTaskAction.Text.FormatChart=图表格式(&F)...

GeneralPage.Library.Included=库:
ChartEventHandlerPage.dialog.Browse=&Browse...
