ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=选择数据绑定:
ChartDataSetBindingSheetImpl.Title.SheetTitle=数据 - 选择数据集

ChartDataBindingPage.Lbl.Parameter=参数
ChartDataBindingPage.Lbl.DataType=数据类型
ChartDataBindingPage.Lbl.Value=值
ChartDataBindingPage.Lbl.None=无
ChartDataBindingPage.Lbl.DefaultValue=（默认值）
ChartDataBindingPage.Lbl.DataSet=数据集
ChartDataBindingPage.Lbl.SaveParameterBinding=保存参数绑定
ChartDataBindingPage.Lbl.SaveDataSet=更改数据集
ChartDataBindingPage.Msg.AskSaveDataSet=是否要更改绑定数据集?

DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.error.Error=错误: 
DesignerRepresentation.log.UnableToFind=设计器中执行呈现操作时无法找到图表模型
ChartReportItemBuilderImpl.problem.hasNotBeenFound=该图表尚未绑定到数据集。
ChartReportItemBuilderImpl.log.UnableToLocate=无法为图表对象找到报表项包装程序。

ChartPreferencePage.Label.MaxRowNumber=数据预览的最大行号(&M):
ChartPreferencePage.Error.MaxRowInvalid=最大行号必须为小于 {0} 的整数
ChartPreferencePage.Label.EnableLivePreview=在图表生成器中启用实时预览(&E)

ChartReportItemUIImpl.log.ReceivedNotification=收到关于清除扩展图表的通知。

ChartExpressionProvider.Category.ChartVariables=图表变量
ChartExpressionProvider.ChartVariables.DataPoints=数据点
ChartExpressionProvider.DataPoints.BaseValue=类别数据
ChartExpressionProvider.DataPoints.OrthogonalValue=值数据
ChartExpressionProvider.DataPoints.SeriesValue=系列数据
ChartColumnBindingDialog.Button.AddAggregation=添加聚合...

OpenChartTaskAction.Text.SelectChartType=选择图表类型(&S)...
OpenChartTaskAction.Text.SelectData=选择数据(&A)...
OpenChartTaskAction.Text.FormatChart=图表格式(&F)...

GeneralPage.Library.Included=库:
ChartEventHandlerPage.dialog.Browse=浏览(&B)...
ReportDataServiceProvider.Option.None=<无>

StandardChartDataSheet.Label.ToBindADataColumn=Use the right-click menu or drag the column into series fields.
StandardChartDataSheet.Label.SelectDataSet=Select Data
StandardChartDataSheet.Label.UseReportData=&Inherit Data from Container
StandardChartDataSheet.Label.UseReportItem=Use &Report Item
StandardChartDataSheet.Label.UseDataSet=Use &Data Set
StandardChartDataSheet.Label.CreateNew=&Create New...
StandardChartDataSheet.Label.DataPreview=Data Preview
StandardChartDataSheet.Label.DataBinding=D&ata Binding...
StandardChartDataSheet.Label.Filters=Fil&ters...
StandardChartDataSheet.Label.Parameters=&Parameters...
StandardChartDataSheet.Task.Description=Select the data to display in the chart and bind it to the series.
StandardChartDataSheet.Exception.UnableToSwitchToDataset=Unable to switch to dataset 
StandardChartDataSheet.Label.InsertAggregation=Insert aggregation
StandardChartDataSheet.Label.DataExpressionBuilder=Data Expression Builder
StandardChartDataSheet.Label.Component=\ Component
StandardChartDataSheet.Label.Overlay=Overlay 
StandardChartDataSheet.Label.Series=Series 
StandardChartDataSheet.Label.UseAsCategoryXAxis=Use as Category (X) axis
StandardChartDataSheet.Label.UseAsCategorySeries=Use as Category series
StandardChartDataSheet.Label.PlotAsValueYSeries=Plot as Value (Y) series
StandardChartDataSheet.Tooltip.CreateNewDataset=Create a new data set
StandardChartDataSheet.Label.PlotAsGaugeValue=Plot as Meter value
StandardChartDataSheet.Label.PlotAsValueSeries=Plot as Value series
StandardChartDataSheet.Label.UseToGroupYSeries=Use to group Y series
StandardChartDataSheet.Label.EnableLivePreview=Enable Live Chart Preview
StandardChartDataSheet.Label.UseToGroupValueSeries=Use to group Value series
