ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Datenbindung auswählen:
ChartDataSetBindingSheetImpl.Title.SheetTitle=Daten - Datensatz auswählen

ChartDataBindingPage.Lbl.Parameter=Parameter
ChartDataBindingPage.Lbl.DataType=Datentyp
ChartDataBindingPage.Lbl.Value=Wert
ChartDataBindingPage.Lbl.None=Keine
ChartDataBindingPage.Lbl.DefaultValue=(Standardwert)
ChartDataBindingPage.Lbl.DataSet=Datensatz
ChartDataBindingPage.Lbl.SaveParameterBinding=Parameterbindung speichern
ChartDataBindingPage.Lbl.SaveDataSet=Datensatz ändern
ChartDataBindingPage.Msg.AskSaveDataSet=Möchten Sie den gebundenen Datensatz ändern?

DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.log.UnableToFind=Diagrammmodel konnte während des Renderns im Designer nicht gefunden werden.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=Das Diagramm wurde noch nicht mit einem Datensatz verknüpft.
ChartReportItemBuilderImpl.log.UnableToLocate=Berichtobjekt-Wrapper für Diagrammobjekt kann nicht gefunden werden.

ChartPreferencePage.Label.MaxRowNumber=&Maximale Zeilenzahl der Datenvorschau:
ChartPreferencePage.Error.MaxRowInvalid=Die maximale Zeilenzahl muss eine ganze Zahl und kleiner als {0} sein.
ChartPreferencePage.Label.EnableLivePreview=&Live-Vorschau im Chart Builder aktivieren

ChartReportItemUIImpl.log.ReceivedNotification=Auftrag zur Entfernung einer erweiterten Diagrammabbildung erhalten.

ChartExpressionProvider.Category.ChartVariables=Variablen
ChartExpressionProvider.ChartVariables.DataPoints=Diagramm-Datenpunkt
ChartExpressionProvider.DataPoints.BaseValue=Kategoriedaten
ChartExpressionProvider.DataPoints.OrthogonalValue=Wertdaten
ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=Ereignis
ChartExpressionProvider.DataPoints.SeriesValue=Datenreihendaten
ChartColumnBindingDialog.Button.AddAggregation=Aggregat hinzufügen...
ChartColumnBindingDialog.Button.Refresh=Aktualisieren

OpenChartTaskAction.Text.SelectChartType=&Diagrammtyp auswählen...
OpenChartTaskAction.Text.SelectData=D&aten auswählen...
OpenChartTaskAction.Text.FormatChart=Diagramm &formatieren...
FlipAxisAction.Text.FlipAxis=Fli&p Axis

GeneralPage.Library.Included=Bibliothek:
ChartEventHandlerPage.dialog.Browse=&Durchsuchen...
ReportDataServiceProvider.Option.None=<keine>
ReportDataServiceProvider.Tooltip.Aggregate=Aggregat: 
ReportDataServiceProvider.Tooltip.GroupExpression=Gruppenausdruck: 
ReportDataServiceProvider.Tooltip.OnGroup=Bei Gruppe: 

ShowAxisAction.Text.ShowValueAxis=Show Value Axis
StandardChartDataSheet.Combo.DataCubes=---------Data Cubes---------
StandardChartDataSheet.Combo.DataSets=----------Data Sets----------
StandardChartDataSheet.Combo.ReportItems=--------Report Items--------
StandardChartDataSheet.Label.ToBindADataColumn=Verwenden Sie das Kontextmenü, oder ziehen Sie die Spalte auf Reihenfelder.
StandardChartDataSheet.Label.SelectDataSet=Daten auswählen
StandardChartDataSheet.Label.UseReportData=&Daten aus Container vererben
StandardChartDataSheet.Label.UseReportItem=&Berichtobjekt verwenden
StandardChartDataSheet.Label.UseDataSet=&Daten verwenden aus
StandardChartDataSheet.Label.DataPreview=Datenvorschau
StandardChartDataSheet.Label.DataBinding=D&atenbindung...
StandardChartDataSheet.Label.Filters=&Filter...
StandardChartDataSheet.Label.Parameters=&Parameter...
StandardChartDataSheet.Task.Description=Wählen Sie die Daten, die im Diagramm angezeigt werden sollen, und verbinden Sie sie mit der Datenreihe.
StandardChartDataSheet.Exception.UnableToSwitchToDataset=Wechseln zu Datensatz nicht möglich 
StandardChartDataSheet.Label.InsertAggregation=Aggregat einfügen
StandardChartDataSheet.Label.DataExpressionBuilder=Datenausdruckerstellung
StandardChartDataSheet.Label.DragCube=Klicken Sie mit der rechten Maustaste auf die Ebenen, oder ziehen Sie sie auf Kategorie-Datenreihen, optionale Y-Datenreihen oder Einheiten-zu-Wert-Datenreihen.
StandardChartDataSheet.Label.Component=\ Komponente
StandardChartDataSheet.Label.CubeTree=Datenquader: Gruppen und Zusammenfassungen
StandardChartDataSheet.Label.Overlay=Überlagerung 
StandardChartDataSheet.Label.Series=Datenreihe 
StandardChartDataSheet.Label.UseAsCategoryXAxis=Als Kategorien-Achse (X-Achse) verwenden
StandardChartDataSheet.Label.UseAsCategorySeries=Als Kategorie-Datenreihe verwenden
StandardChartDataSheet.Label.PlotAsValueYSeries=Als Wert-Datenreihe (Y-Achse) zeichnen
StandardChartDataSheet.Label.PlotAsGaugeValue=Als Messwert zeichnen
StandardChartDataSheet.Label.PlotAsValueSeries=Als Wert-Datenreihe zeichnen
StandardChartDataSheet.Label.UseToGroupYSeries=Zum Gruppieren von Datenreihe (auf Y-Achse) verwenden
StandardChartDataSheet.Label.EnableLivePreview=Live-Diagrammvorschau aktivieren
StandardChartDataSheet.Label.UseToGroupValueSeries=Zum Gruppieren von Wert-Datenreihen verwenden
StandardChartDataSheet.NewDataCube=<New Data Cube...>
StandardChartDataSheet.NewDataSet=<New Data Set...>

ChartBindingGroupDescriptorProvider.DataSets.Default=---Datensätze---
ChartBindingGroupDescriptorProvider.DataCubes.Default=---Datenquader---
BindingPage.Data.Label=Daten:
Error.ChartShouldIncludeAxes=Chart is expected to include axes.
