ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Seleccionar enlace de datos:
ChartDataSetBindingSheetImpl.Title.SheetTitle=Datos - Seleccionar conjunto de datos

ChartDataBindingPage.Lbl.Parameter=Parámetros
ChartDataBindingPage.Lbl.DataType=Tipo de datos
ChartDataBindingPage.Lbl.Value=Valor
ChartDataBindingPage.Lbl.None=Ninguno
ChartDataBindingPage.Lbl.DefaultValue=(Valor predeterminado)
ChartDataBindingPage.Lbl.DataSet=Conjunto de datos
ChartDataBindingPage.Lbl.SaveParameterBinding=Guardar enlace de parámetros
ChartDataBindingPage.Lbl.SaveDataSet=Cambiar conjunto de datos
ChartDataBindingPage.Msg.AskSaveDataSet=¿Desea cambiar el conjunto de datos enlazado?

DesignerRepresentation.error.Error=Error: 
DesignerRepresentation.error.Error=Error: 
DesignerRepresentation.log.UnableToFind=No es posible encontrar el modelo de diagrama mientras se procesa en el diseñador.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=El diagrama no se ha enlazado aún a un conjunto de datos.
ChartReportItemBuilderImpl.log.UnableToLocate=No se puede localizar el empaquetador de elementos de informe para el objeto de diagrama.

ChartPreferencePage.Label.MaxRowNumber=&Número de fila máximo de vista previa de datos:
ChartPreferencePage.Error.MaxRowInvalid=El número de fila máximo debe ser entero e inferior a {0}
ChartPreferencePage.Label.EnableLivePreview=&Activar la vista previa en tiempo real en el compilador de diagramas

ChartReportItemUIImpl.log.ReceivedNotification=Se ha recibido la notificación para disponer de la figura de diagrama extendida.

ChartExpressionProvider.Category.ChartVariables=Variables de diagrama
ChartExpressionProvider.ChartVariables.DataPoints=Puntos de datos
ChartExpressionProvider.DataPoints.BaseValue=Datos de categoría
ChartExpressionProvider.DataPoints.OrthogonalValue=Datos de valor
ChartExpressionProvider.DataPoints.SeriesValue=Datos de serie

OpenChartTaskAction.Text.SelectChartType=&Seleccionar tipo de diagrama...
OpenChartTaskAction.Text.SelectData=Seleccionar d&atos...
OpenChartTaskAction.Text.FormatChart=&Formato de diagrama...

GeneralPage.Library.Included=Librería:
ChartEventHandlerPage.dialog.Browse=&Examinar...
