ChartAggregationCellViewProvider.Chart.DisplayName=Graphique
ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Sélectionner la liaison de données :
ChartDataSetBindingSheetImpl.Title.SheetTitle=Données - Sélectionner un jeu de données

ChartDataBindingPage.Lbl.Parameter=Paramètres
ChartDataBindingPage.Lbl.DataType=Type de données
ChartDataBindingPage.Lbl.Value=Valeur
ChartDataBindingPage.Lbl.None=Aucun
ChartDataBindingPage.Lbl.DefaultValue=(Valeur par défaut)
ChartDataBindingPage.Lbl.DataSet=Jeu de données
ChartDataBindingPage.Lbl.SaveParameterBinding=Enregistrer la liaison de paramètres
ChartDataBindingPage.Lbl.SaveDataSet=Modifier le jeu de données
ChartDataBindingPage.Msg.AskSaveDataSet=Souhaitez-vous modifier le jeu de données lié ?

DesignerRepresentation.error.Error=Erreur : 
DesignerRepresentation.log.UnableToFind=Impossible de trouver le modèle de graphique pendant le rendu dans Designer.
DesignerRepresentation.msg.InvalidChart=Le graphique actuel est incorrect. Pour continuer à travailler sur ce graphique, veuillez commencer par le supprimer.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=Le graphique n'a pas encore été lié à un jeu de données.
ChartReportItemBuilderImpl.log.UnableToLocate=Impossible de localiser le wrapper d'élément d'état pour l'objet de graphique.

ChartPreferencePage.Label.MaxRowNumber=&Nombre max. de lignes dans la prévisualisation des données :
ChartPreferencePage.Error.MaxRowInvalid=Le nombre max. de lignes doit être un nombre entier inférieur à {0}
ChartPreferencePage.Label.EnableLivePreview=Activer l'aperçu direct dans le générateur de graphiques(&E)

ChartReportItemUIImpl.log.ReceivedNotification=Réception d'une notification de rejet des données du graphique étendu.
ChartReportItemViewProvider.BarChart.Text.Title=Titre du graphique à barres

ChartExpressionProvider.Category.ChartVariables=Variables
ChartExpressionProvider.ChartVariables.DataPoints=Point de données du graphique
ChartExpressionProvider.DataPoints.BaseValue=Données de catégorie
ChartExpressionProvider.DataPoints.OrthogonalValue=Données de valeur
ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=Evénement
ChartExpressionProvider.DataPoints.SeriesValue=Données de la série
ChartColumnBindingDialog.Button.Refresh=Actualiser

OpenChartTaskAction.Text.SelectChartType=&Sélectionner le type de graphique...
OpenChartTaskAction.Text.SelectData=Sél&ectionner des données...
OpenChartTaskAction.Text.FormatChart=Formater le grap&hique...
FlipAxisAction.Text.FlipAxis=In&verser l'axe

GeneralPage.Library.Included=Bibliothèque :
ChartEventHandlerPage.dialog.Browse=& Parcourir...
ReportDataServiceProvider.Option.None=<Aucun>
ReportDataServiceProvider.Option.Inherits=<{0} du conteneur>
ReportDataServiceProvider.Tooltip.Aggregate=Agrégat : 
ReportDataServiceProvider.Tooltip.GroupExpression=Expression de groupe : 
ReportDataServiceProvider.Tooltip.OnGroup=Dans le groupe : 

ShowAxisAction.Text.ShowValueAxis=Afficher l'axe de valeurs
StandardChartDataSheet.Combo.DataCubes=---------Cubes de données---------
StandardChartDataSheet.Combo.DataSets=----------Jeux de données----------
StandardChartDataSheet.Combo.ReportItems=--------Eléments d'état--------
StandardChartDataSheet.Label.Axis=Axe  
StandardChartDataSheet.Label.ToBindADataColumn=Utilisez le menu contextuel ou faites glisser la colonne dans les champs de série.
StandardChartDataSheet.Label.SelectDataSet=Sélectionner des données
StandardChartDataSheet.Label.UseReportData=&Hériter les données du conteneur
StandardChartDataSheet.Label.UseReportItem=Utiliser un élément de &rapport
StandardChartDataSheet.Label.UseDataSet=Utiliser les &données provenant de
StandardChartDataSheet.Label.DataPreview=Prévisualisation des données
StandardChartDataSheet.Label.DataBinding=Li&aison des données...
StandardChartDataSheet.Label.Filters=Fil&tres...
StandardChartDataSheet.Label.Parameters=&Paramètres...
StandardChartDataSheet.Task.Description=Sélectionner les données à afficher dans le graphique et les lier à la série.
StandardChartDataSheet.Exception.UnableToSwitchToDataset=Impossible d'utiliser le jeu de données 
StandardChartDataSheet.Label.InsertAggregation=Insérer une agrégation
StandardChartDataSheet.Label.DataExpressionBuilder=Générateur d'expression de données
StandardChartDataSheet.Label.DragCube=Faites un clic droit avec votre souris ou faites glisser les niveaux vers Série de catégories ou Série verticale facultatives (Mesures vers Séries de valeur).
StandardChartDataSheet.Label.Component=\ Composant
StandardChartDataSheet.Label.CubeTree=Cube de données : Groupes et résumés
StandardChartDataSheet.Label.Overlay=Superposition 
StandardChartDataSheet.Label.Series=Série 
StandardChartDataSheet.Label.UseAsCategoryXAxis=Utiliser comme axe horizontal de catégories
StandardChartDataSheet.Label.UseAsCategorySeries=Utiliser comme série de catégories
StandardChartDataSheet.Label.PlotAsValueYSeries=Tracer une série verticale de valeurs
StandardChartDataSheet.Label.PlotAsGaugeValue=Tracer une valeur de mesure
StandardChartDataSheet.Label.PlotAsValueSeries=Tracer une série de valeurs
StandardChartDataSheet.Label.UseToGroupYSeries=Utiliser la série verticale de groupes
StandardChartDataSheet.Label.EnableLivePreview=Activer l'aperçu direct du graphique
StandardChartDataSheet.Label.UseToGroupValueSeries=Utiliser la série de valeurs de groupes
StandardChartDataSheet.NewDataCube=<Nouveau cube de données>
StandardChartDataSheet.NewDataSet=<Nouveau jeu de données>

ChartBindingGroupDescriptorProvider.DataSets.Default=---Jeux de données---
ChartBindingGroupDescriptorProvider.DataCubes.Default=---Cubes de données---
BindingPage.Data.Label=Données :
Error.ChartShouldIncludeAxes=Le graphique doit inclure les axes.

ChartCubeFilterConditionBuilder.Information=Veuillez tout d'abord sélectionner la valeur pour la série de valeurs ou la série de catégories.
ChartCubeFilterConditionBuilder.Expression.CategoryItem.Prefix=Catégorie :  
ChartCubeFilterConditionBuilder.Expression.ValueItemPrefix=Valeur :  
ChartCubeFilterConditionBuilder.Expression.YOptionItem.Prefix=Série verticale facultative  
ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.selectVauleUnavailable=Liste de valeurs non disponible avec l'expression spécifiée. 
ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.illegalVauleExpr=Seules les expressions dont le format est du type données["nom"] peuvent obtenir la liste de valeurs.

