ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Datenbindung auswählen:
ChartDataSetBindingSheetImpl.Title.SheetTitle=Daten - Datensatz auswählen

ChartDataBindingPage.Lbl.Parameter=Parameter
ChartDataBindingPage.Lbl.DataType=Datentyp
ChartDataBindingPage.Lbl.Value=Wert
ChartDataBindingPage.Lbl.None=Keine
ChartDataBindingPage.Lbl.DefaultValue=(Standardwert)
ChartDataBindingPage.Lbl.DataSet=Datensatz
ChartDataBindingPage.Lbl.SaveParameterBinding=Parameterbindung speichern
ChartDataBindingPage.Lbl.SaveDataSet=Datensatz ändern
ChartDataBindingPage.Msg.AskSaveDataSet=Möchten Sie den gebundenen Datensatz ändern?

DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.error.Error=Fehler: 
DesignerRepresentation.log.UnableToFind=Diagrammmodel konnte während des Renderns im Designer nicht gefunden werden.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=Das Diagramm wurde noch nicht mit einem Datensatz verknüpft.
ChartReportItemBuilderImpl.log.UnableToLocate=Berichtobjekt-Wrapper für Diagrammobjekt kann nicht gefunden werden.

ChartPreferencePage.Label.MaxRowNumber=&Maximale Zeilenzahl der Datenvorschau:
ChartPreferencePage.Error.MaxRowInvalid=Die maximale Zeilenzahl muss eine ganze Zahl und kleiner als {0} sein.
ChartPreferencePage.Label.EnableLivePreview=&Live-Vorschau im Chart Builder aktivieren

ChartReportItemUIImpl.log.ReceivedNotification=Auftrag zur Entfernung einer erweiterten Diagrammabbildung erhalten.

ChartExpressionProvider.Category.ChartVariables=Diagrammvariablen
ChartExpressionProvider.ChartVariables.DataPoints=Datenpunkte
ChartExpressionProvider.DataPoints.BaseValue=Kategoriedaten
ChartExpressionProvider.DataPoints.OrthogonalValue=Wertdaten
ChartExpressionProvider.DataPoints.SeriesValue=Datenreihendaten
ChartColumnBindingDialog.Button.AddAggregation=Aggregat hinzufügen...

OpenChartTaskAction.Text.SelectChartType=&Diagrammtyp auswählen...
OpenChartTaskAction.Text.SelectData=D&aten auswählen...
OpenChartTaskAction.Text.FormatChart=Diagramm &formatieren...

GeneralPage.Library.Included=Bibliothek:
ChartEventHandlerPage.dialog.Browse=&Durchsuchen...
ReportDataServiceProvider.Option.None=<keine>

StandardChartDataSheet.Label.ToBindADataColumn=Use the right-click menu or drag the column into series fields.
StandardChartDataSheet.Label.SelectDataSet=Select Data
StandardChartDataSheet.Label.UseReportData=&Inherit Data from Container
StandardChartDataSheet.Label.UseReportItem=Use &Report Item
StandardChartDataSheet.Label.UseDataSet=Use &Data Set
StandardChartDataSheet.Label.CreateNew=&Create New...
StandardChartDataSheet.Label.DataPreview=Data Preview
StandardChartDataSheet.Label.DataBinding=D&ata Binding...
StandardChartDataSheet.Label.Filters=Fil&ters...
StandardChartDataSheet.Label.Parameters=&Parameters...
StandardChartDataSheet.Task.Description=Select the data to display in the chart and bind it to the series.
StandardChartDataSheet.Exception.UnableToSwitchToDataset=Unable to switch to dataset 
StandardChartDataSheet.Label.InsertAggregation=Insert aggregation
StandardChartDataSheet.Label.DataExpressionBuilder=Data Expression Builder
StandardChartDataSheet.Label.Component=\ Component
StandardChartDataSheet.Label.Overlay=Overlay 
StandardChartDataSheet.Label.Series=Series 
StandardChartDataSheet.Label.UseAsCategoryXAxis=Use as Category (X) axis
StandardChartDataSheet.Label.UseAsCategorySeries=Use as Category series
StandardChartDataSheet.Label.PlotAsValueYSeries=Plot as Value (Y) series
StandardChartDataSheet.Tooltip.CreateNewDataset=Create a new data set
StandardChartDataSheet.Label.PlotAsGaugeValue=Plot as Meter value
StandardChartDataSheet.Label.PlotAsValueSeries=Plot as Value series
StandardChartDataSheet.Label.UseToGroupYSeries=Use to group Y series
StandardChartDataSheet.Label.EnableLivePreview=Enable Live Chart Preview
StandardChartDataSheet.Label.UseToGroupValueSeries=Use to group Value series
