ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=데이터 바인딩 선택:
ChartDataSetBindingSheetImpl.Title.SheetTitle=데이터 - 데이터 집합 선택

ChartDataBindingPage.Lbl.Parameter=매개 변수
ChartDataBindingPage.Lbl.DataType=데이터 형식
ChartDataBindingPage.Lbl.Value=값
ChartDataBindingPage.Lbl.None=없음
ChartDataBindingPage.Lbl.DefaultValue=(기본값)
ChartDataBindingPage.Lbl.DataSet=데이터 집합
ChartDataBindingPage.Lbl.SaveParameterBinding=매개 변수 바인딩 저장
ChartDataBindingPage.Lbl.SaveDataSet=데이터 집합 변경
ChartDataBindingPage.Msg.AskSaveDataSet=바인딩된 데이터 집합을 변경하시겠습니까?

DesignerRepresentation.error.Error=오류: 
DesignerRepresentation.error.Error=오류: 
DesignerRepresentation.log.UnableToFind=디자이너에서 렌더링하는 동안에는 차트 모델을 찾을 수 없습니다.
ChartReportItemBuilderImpl.problem.hasNotBeenFound=차트가 데이터 집합에 아직 바인딩되지 않았습니다.
ChartReportItemBuilderImpl.log.UnableToLocate=차트 개체에 대한 보고서 항목 래퍼를 찾을 수 없습니다.

ChartPreferencePage.Label.MaxRowNumber=최대 데이터 미리 보기 행 번호(&M):
ChartPreferencePage.Error.MaxRowInvalid=최대 행 번호는 {0} 이상의 정수이어야 합니다.
ChartPreferencePage.Label.EnableLivePreview=차트 빌더에서 실시간 미리 보기 사용(&E)

ChartReportItemUIImpl.log.ReceivedNotification=확장 차트 그림을 삭제하기 위한 통지가 수신되었습니다.

ChartExpressionProvider.Category.ChartVariables=차트 변수
ChartExpressionProvider.ChartVariables.DataPoints=데이터 요소
ChartExpressionProvider.DataPoints.BaseValue=범주 데이터
ChartExpressionProvider.DataPoints.OrthogonalValue=값 데이터
ChartExpressionProvider.DataPoints.SeriesValue=계열 데이터

OpenChartTaskAction.Text.SelectChartType=차트 형식 선택(&S)...
OpenChartTaskAction.Text.SelectData=데이터 선택(&A)...
OpenChartTaskAction.Text.FormatChart=차트 형식 지정(&F)...

GeneralPage.Library.Included=라이브러리:
ChartEventHandlerPage.dialog.Browse=&Browse...
