ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=データバインドの選択 :
ChartDataSetBindingSheetImpl.Title.SheetTitle=データ - データセットの選択

ChartDataBindingPage.Lbl.Parameter=パラメタ
ChartDataBindingPage.Lbl.DataType=データ型
ChartDataBindingPage.Lbl.Value=値
ChartDataBindingPage.Lbl.None=なし
ChartDataBindingPage.Lbl.DefaultValue=(デフォルト値)
ChartDataBindingPage.Lbl.DataSet=データセット
ChartDataBindingPage.Lbl.SaveParameterBinding=パラメタバインドの保存
ChartDataBindingPage.Lbl.SaveDataSet=データセットの変更
ChartDataBindingPage.Msg.AskSaveDataSet=バインドされたデータセットを変更しますか ?

DesignerRepresentation.error.Error=エラー : 
DesignerRepresentation.error.Error=エラー : 
DesignerRepresentation.log.UnableToFind=デザイナで描画中に、グラフのモデルが見つかりません。
ChartReportItemBuilderImpl.problem.hasNotBeenFound=グラフはデータセットにバインドされていません。
ChartReportItemBuilderImpl.log.UnableToLocate=グラフオブジェクトのレポート項目ラッパーが見つかりません。

ChartPreferencePage.Label.MaxRowNumber=データプレビューの最大行数 (&M):
ChartPreferencePage.Error.MaxRowInvalid=最大行数には、{0} より小さい整数を指定してください。
ChartPreferencePage.Label.EnableLivePreview=グラフビルダでライブプレビューを有効化する(&E)

ChartReportItemUIImpl.log.ReceivedNotification=拡張された図表を破棄する通知を受け取りました。

ChartExpressionProvider.Category.ChartVariables=グラフの変数
ChartExpressionProvider.ChartVariables.DataPoints=データポイント
ChartExpressionProvider.DataPoints.BaseValue=カテゴリデータ
ChartExpressionProvider.DataPoints.OrthogonalValue=値データ
ChartExpressionProvider.DataPoints.SeriesValue=系列データ
ChartColumnBindingDialog.Button.AddAggregation=集計の追加...

OpenChartTaskAction.Text.SelectChartType=グラフの種類の選択(&S)...
OpenChartTaskAction.Text.SelectData=データの選択(&A)...
OpenChartTaskAction.Text.FormatChart=グラフの書式設定(&F)...

GeneralPage.Library.Included=ライブラリ :
ChartEventHandlerPage.dialog.Browse=参照(&B)...
ReportDataServiceProvider.Option.None=<なし>

StandardChartDataSheet.Label.ToBindADataColumn=Use the right-click menu or drag the column into series fields.
StandardChartDataSheet.Label.SelectDataSet=Select Data
StandardChartDataSheet.Label.UseReportData=&Inherit Data from Container
StandardChartDataSheet.Label.UseReportItem=Use &Report Item
StandardChartDataSheet.Label.UseDataSet=Use &Data Set
StandardChartDataSheet.Label.CreateNew=&Create New...
StandardChartDataSheet.Label.DataPreview=Data Preview
StandardChartDataSheet.Label.DataBinding=D&ata Binding...
StandardChartDataSheet.Label.Filters=Fil&ters...
StandardChartDataSheet.Label.Parameters=&Parameters...
StandardChartDataSheet.Task.Description=Select the data to display in the chart and bind it to the series.
StandardChartDataSheet.Exception.UnableToSwitchToDataset=Unable to switch to dataset 
StandardChartDataSheet.Label.InsertAggregation=Insert aggregation
StandardChartDataSheet.Label.DataExpressionBuilder=Data Expression Builder
StandardChartDataSheet.Label.Component=\ Component
StandardChartDataSheet.Label.Overlay=Overlay 
StandardChartDataSheet.Label.Series=Series 
StandardChartDataSheet.Label.UseAsCategoryXAxis=Use as Category (X) axis
StandardChartDataSheet.Label.UseAsCategorySeries=Use as Category series
StandardChartDataSheet.Label.PlotAsValueYSeries=Plot as Value (Y) series
StandardChartDataSheet.Tooltip.CreateNewDataset=Create a new data set
StandardChartDataSheet.Label.PlotAsGaugeValue=Plot as Meter value
StandardChartDataSheet.Label.PlotAsValueSeries=Plot as Value series
StandardChartDataSheet.Label.UseToGroupYSeries=Use to group Y series
StandardChartDataSheet.Label.EnableLivePreview=Enable Live Chart Preview
StandardChartDataSheet.Label.UseToGroupValueSeries=Use to group Value series
