#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTXEmitter.Description=配置用于以单一文件 Web 存档 (MHTML) 格式呈现报表的选项。

PPTXEmitter.DisplayName=PowerPoint (PPTX)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 处理

OptionDisplayValue.TextWrapping=文字环绕

OptionDisplayValue.PageOverFlow=页面溢出处理

OptionDisplayValue.CLIP_CONTENT=剪切内容

OptionDisplayValue.FIT_TO_PAGE_SIZE=适合页面大小

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=输出多页

OptionDisplayValue.ENLARGE_PAGE_SIZE=增加页面大小

OptionDisplayValue.FontSubstitution=字体替换

OptionDisplayValue.ChartDpi=图表 DPI

OptionDisplayValue.RepaginateForPDF=呈现 PPTX 时重标页码

###########################################################
#Option Description
OptionDescription.BidiProcessing=支持双向文字。

OptionDescription.TextWrapping=表示文字可否环绕。

OptionDescription.PageOverFlow=控制内容输出方式。

OptionDescription.FontSubstitution=指定的字体无法显示该字符时自动选择字体。

OptionDescription.ChartDpi=用于生成图表的 DPI。

OptionDescription.RepaginateForPDF=呈现 PPTX 时重标页码。

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。例如，192。
