#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTXEmitter.Description=Optionen zum Rendern eines Berichts im Format Single File Web Archive (MHTML) konfigurieren.

PPTXEmitter.DisplayName=PowerPoint (PPTX)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung

OptionDisplayValue.TextWrapping=Zeilenumbruch

OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung

OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden

OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben

OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern

OptionDisplayValue.FontSubstitution=Schriftart ersetzen

OptionDisplayValue.ChartDpi=Diagramm-DPI

OptionDisplayValue.RepaginateForPDF=Während des Renderns der PPTX neu paginieren

###########################################################
#Option Description
OptionDescription.BidiProcessing=Unterstützt bidirektionalen Text.

OptionDescription.TextWrapping=Gibt an, ob der Text Zeilenumbrüche enthält.

OptionDescription.PageOverFlow=Legt fest, wie der Inhalt ausgegeben wird.

OptionDescription.FontSubstitution=Wählt Schriftarten automatisch aus, wenn die angegebene Schriftart das Zeichen nicht darstellen kann.

OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

OptionDescription.RepaginateForPDF=Während des Renderns der PPTX neu paginieren.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.
