#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTXEmitter.Description=Configurar las opciones para procesar un informe en formato de archivo único de página Web (MHTML).

PPTXEmitter.DisplayName=PowerPoint (PPTX)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Procesamiento de BIDI

OptionDisplayValue.TextWrapping=Autoajuste de texto

OptionDisplayValue.PageOverFlow=Procesamiento del desbordamiento de página

OptionDisplayValue.CLIP_CONTENT=Cortar contenido

OptionDisplayValue.FIT_TO_PAGE_SIZE=Ajustar a tamaño de página

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Salida de varias páginas

OptionDisplayValue.ENLARGE_PAGE_SIZE=Aumentar tamaño de página

OptionDisplayValue.FontSubstitution=Sustitución de fuente

OptionDisplayValue.ChartDpi=Diagrama DPI

OptionDisplayValue.RepaginateForPDF=Repaginar mientras se procesa el PPTX
OptionDisplayValue.EditMode=Modo de edición

###########################################################
#Option Description
OptionDescription.BidiProcessing=Admite texto bidireccional.

OptionDescription.TextWrapping=Indica si el texto se puede autoajustar.

OptionDescription.PageOverFlow=Controla cómo se va a mostrar el contenido.

OptionDescription.FontSubstitution=Selecciona fuentes automáticamente cuando la fuente especificada no puede mostrar el carácter.

OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

OptionDescription.RepaginateForPDF=Repaginar mientras se procesa el PPTX.
OptionDescription.EditMode=Componentes editables en PPTX

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.
