#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PPT Emitter
PPTXEmitter.Description=単一ファイル Web アーカイブ (MHTML) 形式でレポートをレンダリングするためのオプションを設定します。

PPTXEmitter.DisplayName=PowerPoint (PPTX)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=双方向テキストの処理

OptionDisplayValue.TextWrapping=文字列の折り返し

OptionDisplayValue.PageOverFlow=オーバーフローしているページの処理

OptionDisplayValue.CLIP_CONTENT=コンテンツのクリッピング

OptionDisplayValue.FIT_TO_PAGE_SIZE=ページサイズに合わせる

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=複数ページを出力

OptionDisplayValue.ENLARGE_PAGE_SIZE=ページサイズを大きくする

OptionDisplayValue.FontSubstitution=フォントの置き換え

OptionDisplayValue.ChartDpi=グラフの DPI

OptionDisplayValue.RepaginateForPDF=PPTX のレンダリングのページ数再割り当て
OptionDisplayValue.EditMode=編集モード

###########################################################
#Option Description
OptionDescription.BidiProcessing=双方向テキストをサポートします。

OptionDescription.TextWrapping=文字列を折り返すことができるかどうかを示します。

OptionDescription.PageOverFlow=コンテンツの出力方法を制御します。

OptionDescription.FontSubstitution=指定されたフォントで表示できない文字がある場合は、フォントを自動的に選択します。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

OptionDescription.RepaginateForPDF=PPTX のレンダリングのページ数再割り当て。
OptionDescription.EditMode=PPTX にある編集可能なコンポーネント

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。例: 192。
