###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

preference.crosstabPage=Tabla de referencias cruzadas
crosstab.menu=Tabla de referencias cr&uzadas
Crosstab.desc=Inserte una tabla de referencias cruzadas en el diseño
newcube.menu=&Cubo de datos nuevo
