###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

preference.crosstabPage=크로스 탭
crosstab.menu=크로스 테이블(&O)
Crosstab.desc=크로스 테이블을 레이아웃에 삽입
newcube.menu=New Data Cube
