###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.crosstabPage=Tabla de referencias cruzadas

crosstab.menu=Tabla de referencias cr&uzadas

Crosstab.desc=Introduzca una tabla de referencias cruzadas para visualizar los datos agregados en el formato de fila y columna.

newcube.menu=&Cubo de datos nuevo

paletteEntry.label.crosstab= Tabla de referencias cruzadas

command.name.createCrosstab= Crear tabla de referencias cruzadas

command.name.createCube= Crear cubo

command.mnemonic.c=C