###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.crosstabPage=クロスタブ

crosstab.menu=クロスタブ(&O)

Crosstab.desc=クロスタブを挿入すると、列と行で集計データが表示されます。

newcube.menu=データキューブの新規作成(&C)

paletteEntry.label.crosstab= クロスタブ

command.name.createCrosstab= クロスタブの作成

command.name.createCube= キューブの作成

command.mnemonic.c=C