###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

preference.crosstabPage=交叉表
crosstab.menu=交叉表(&O)
Crosstab.desc=将交叉表插入到布局
newcube.menu=新建数据和多维数据集
