###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.crosstabPage=交叉表

crosstab.menu=交叉表(&O)

Crosstab.desc=插入交叉表以按行和列格式显示聚合数据。

newcube.menu=新建数据和多维数据集(&C)

paletteEntry.label.crosstab= 交叉表

command.name.createCrosstab= 创建交叉表

command.name.createCube= 创建多维数据集

command.mnemonic.c=C