#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=Kann Verbindung mit den angegebenen Eigenschaften nicht öffnen.

mDbConnection_invalidDatabaseName=Die angegebene Datenbank ({0}) existiert nicht.

mDbConnection_missingValueDBName=Fehlender erforderlicher Wert in der Eigenschaft 'Datenbankname'.

mDbConnection_noConnection=Keine offene Verbindung zum Vorbereiten der Abfrage.

mDbDriver_missingValueServerHost=Fehlender erforderlicher Wert in der Eigenschaft 'Server-Host'.

mDbDriver_nonDefinedDataType=Nicht definiert

mDbDriver_readPrefNearest=nächstes

mDbDriver_readPrefPrimary=primär

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=sekundär

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=Ungültiger Sammlungsname: {0}

mDbMetaData_missingCmdExprText=Fehlender Ausdruck für den {0} Befehlsvorgang.

mDbQuery_invalidQueryExecQuery=Die Abfrage ist ungültig und kann nicht ausgeführt werden.

mDbQuery_invalidQueryGetMD=Die Abfrage ist ungültig und kann die Metadata-Ergebnisse nicht vorbereiten.

driverUtil_invalidExpr=Unerwarteter Ausdruckstyp: {0}.

driverUtil_parsingError=Fehler bei der Analyse des JSON-Ausdrucks: {0}

mDbOp_aggrCmdFailed=Ausführen des Aggregatbefehlsvorgangs nicht möglich. \nPrüfen Sie, ob der verbundene MongoDB-Server Version 2.2 oder höher ist.

mDbOp_dbCmdFailed=Ausführen des Befehlsvorgangs ({0}) nicht möglich

mDbOp_invalidQueryExpr=Ungültiger Abfrageausdruck; Ausführen der Abfrage nicht möglich.

mDbOp_mapReduceCmdFailed=Ausführen des MapReduce-Befehlsvorgangs ({0}) nicht möglich

mDbOp_noCmdResults=Keine Befehlsergebnisse verfügbar.

mDbResultSet_cannotConvertFieldData=Feldwert '{0}' ({1}) in Datentyp {2} kann nicht in Wert {3} konvertiert werden

queryModel_emptyExprErrorMsg=<leerer Ausdruck>

queryModel_invalidCollectionName=Ungültiger Sammlungsname (${0}).

queryModel_invalidDbCmdKeyValue=Der Datenbankbefehl ({0}) wird nur unterstützt mit: \n {1}

queryModel_invalidModelToExec=Ungültige Abfragedefinition; Ausführen der Abfrage nicht möglich.

queryModel_invalidModelToPrepare=Ungültige Abfragedefinition; Vorbereiten der Abfrage nicht möglich.

queryModel_invalidPipelineOp=Ungültiger Pipeline-Vorgang: {0}

queryModel_invalidQuerySortExpr=Ein Abfragesortierungsausdruck muss einen positiven oder negativen Wert für die Sortierungsreihenfolge angeben: \n {0}

queryModel_invalidSortAggrValue=Ein {0} Pipeline-Vorgang muss einen Wert von 1 oder -1 im Sortierschlüssel festlegen: \n {1}

queryModel_missingCollectionName=Es ist keine MongoDB-Sammlung in der Datensatz-Abfrage definiert.

queryModel_missingGroupAggrKey=Ein {0} Pipeline-Vorgang muss ein {1} Feld festlegen: \n {2}

queryModel_missingMapReduceKey=Der Befehlsausdruck fehlt im erforderlichen Schlüssel: {0}

queryModel_missingMapReduceValue=Der Befehlsausdrucksschlüssel {0} erfordert einen Wert.

queryModel_missingQueryProps=Es ist keine Abfrage im Datensatz definiert.

queryModel_nonSupportedDbCmd=Der Datenbankbefehlstyp wird nicht unterstützt: \n {0}

queryProperties_aggrCmdName=Aggregat

queryProperties_dbCmdName=Befehl 'Datenbank ausführen'

queryProperties_errDeSerializeDBObject=Deserialisieren des MongoDB-Ausdrucks nicht möglich: {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=Ungültiger Feldname: {0}
