#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=No es posible abrir la conexión con las propiedades especificadas.

mDbConnection_invalidDatabaseName=La base de datos \"{0}\" especificada no existe.

mDbConnection_missingValueDBName=Falta un valor necesario en la propiedad de Nombre de base de datos.

mDbConnection_noConnection=No existe conexión abierta para preparar la consulta.

mDbDriver_missingValueServerHost=Falta un valor necesario en la propiedad de Anfitrión del servidor.

mDbDriver_nonDefinedDataType=Sin definir

mDbDriver_readPrefNearest=más cercano

mDbDriver_readPrefPrimary=primario

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=secundario

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=Nombre de colección no válido: {0}

mDbMetaData_missingCmdExprText=Falta la expresión de la operación de comando {0}.

mDbQuery_invalidQueryExecQuery=La consulta no es válida y no se puede ejecutar.

mDbQuery_invalidQueryGetMD=La consulta no es válida y no se pueden preparar los metadatos del conjunto de resultados.

driverUtil_invalidExpr=Tipo de expresión inesperado: {0}.

driverUtil_parsingError=Error al analizar la expresión JSON: {0}

mDbOp_aggrCmdFailed=No es posible ejecutar la operación de comando Agregar. \nCompruebe que su servidor MongoDB conectado es la versión 2.2 o posterior.

mDbOp_dbCmdFailed=No es posible ejecutar la operación de comando ({0})

mDbOp_invalidQueryExpr=Expresión de consulta no válida; no se puede ejecutar la consulta.

mDbOp_mapReduceCmdFailed=No es posible ejecutar la operación de comando MapReduce ({0})

mDbOp_noCmdResults=No hay resultados de comando disponibles.

mDbResultSet_cannotConvertFieldData=No se ha podido convertir el valor de campo '{0}' ({1}) en el tipo de datos {2} a un valor {3}

queryModel_emptyExprErrorMsg=<expresión vacía>

queryModel_invalidCollectionName=Nombre de colección no válido (${0}).

queryModel_invalidDbCmdKeyValue=El comando ({0}) de la base de datos solo es compatible con: \n    {1}

queryModel_invalidModelToExec=Definición de consulta no válida; no se puede ejecutar la consulta.

queryModel_invalidModelToPrepare=Definición de consulta no válida; no se puede preparar la consulta.

queryModel_invalidPipelineOp=Operación de canalización no válida: {0}

queryModel_invalidQuerySortExpr=La expresión de ordenación de una consulta debe especificar un valor positivo o negativo para el orden: \n    {0}

queryModel_invalidSortAggrValue=Una operación de canalización {0} debe especificar un valor de 1 o -1 en la clave de ordenación: \n    {1}

queryModel_missingCollectionName=No se ha definido una colección MongoDB en la consulta de conjunto de datos.

queryModel_missingGroupAggrKey=Una operación de canalización {0} debe especificar un campo {1}: \n    {2}

queryModel_missingMapReduceKey=Falta la clave de la expresión de comando: {0}

queryModel_missingMapReduceValue=La clave de la expresión de comando {0} requiere un valor.

queryModel_missingQueryProps=No se ha definido una consulta en el conjunto de datos.

queryModel_nonSupportedDbCmd=El tipo de comando de la base de datos no es compatible: \n    {0}

queryProperties_aggrCmdName=Total

queryProperties_dbCmdName=Ejecutar comando de la base de datos

queryProperties_errDeSerializeDBObject=No es posible deserializar la expresión MongoDB: {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=Nombre de campo no válido: {0}
