#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=无法打开具有指定属性的连接。

mDbConnection_invalidDatabaseName=指定的数据库 ({0}) 不存在。

mDbConnection_missingValueDBName=“数据库名称”属性缺少必需值。

mDbConnection_noConnection=没有打开的连接可以进行查询准备。

mDbDriver_missingValueServerHost=“服务器主机”属性缺少必需值。

mDbDriver_nonDefinedDataType=未定义

mDbDriver_readPrefNearest=最近

mDbDriver_readPrefPrimary=主要

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=次要

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=无效集合名称: {0}

mDbMetaData_missingCmdExprText=缺少 {0} 命令运算的表达式。

mDbQuery_invalidQueryExecQuery=查询无效，无法执行。

mDbQuery_invalidQueryGetMD=查询无效，无法准备结果集元数据。

driverUtil_invalidExpr=意外表达式类型: {0}。

driverUtil_parsingError=分析 JSON 表达式时出错: {0}

mDbOp_aggrCmdFailed=无法运行聚合命令运算。 \n检查已连接的 MongoDB Server 是否是 2.2 版或更高版本。

mDbOp_dbCmdFailed=无法运行命令运算 ({0})

mDbOp_invalidQueryExpr=无效查询表达式；无法执行查询。

mDbOp_mapReduceCmdFailed=无法运行 MapReduce 命令运算 ({0})

mDbOp_noCmdResults=没有可用的命令结果。

mDbResultSet_cannotConvertFieldData=无法将 {2} 数据类型中的“{0}”字段值 ({1}) 转换为 {3} 值

queryModel_emptyExprErrorMsg=<空表达式>

queryModel_invalidCollectionName=集合名称 (${0}) 无效。

queryModel_invalidDbCmdKeyValue=数据库命令 ({0}) 的唯一支持工具: \n    {1}

queryModel_invalidModelToExec=无效查询定义; 无法执行查询。

queryModel_invalidModelToPrepare=无效查询定义; 无法准备查询。

queryModel_invalidPipelineOp=无效流水线运算: {0}

queryModel_invalidQuerySortExpr=查询排序表达式必须为排序顺序指定一个正值或负值: \n    {0}

queryModel_invalidSortAggrValue={0} 流水线运算必须在排序键中指定值 1 或 -1: \n    {1}

queryModel_missingCollectionName=数据集查询中未定义 MongoDB 集合。

queryModel_missingGroupAggrKey={0} 流水线运算必须指定 {1} 字段: \n    {2}

queryModel_missingMapReduceKey=命令表达式缺少所需键: {0}

queryModel_missingMapReduceValue=命令表达式键 {0} 需要一个值。

queryModel_missingQueryProps=数据集中未定义查询。

queryModel_nonSupportedDbCmd=不支持数据库命令类型: \n    {0}

queryProperties_aggrCmdName=聚合

queryProperties_dbCmdName=运行数据库命令

queryProperties_errDeSerializeDBObject=无法反序列化 MongoDB 表达式: {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=无效的字段名称:{0}
