#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=指定したプロパティで接続を開くことができません。

mDbConnection_invalidDatabaseName=指定したデータベース ({0}) が存在しません。

mDbConnection_missingValueDBName=データベース名プロパティに必要な値がありません。

mDbConnection_noConnection=クエリを準備するための開かれた接続がありません。

mDbDriver_missingValueServerHost=サーバホストのプロパティに必要な値がありません。

mDbDriver_nonDefinedDataType=定義なし

mDbDriver_readPrefNearest=最も近い

mDbDriver_readPrefPrimary=プライマリ

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=セカンダリ

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=コレクション名が無効です: {0}

mDbMetaData_missingCmdExprText={0} コマンド操作の式がありません。

mDbQuery_invalidQueryExecQuery=クエリは無効であるため実行できません。

mDbQuery_invalidQueryGetMD=クエリは無効であり、結果セットのメタデータを準備できません。

driverUtil_invalidExpr=予期しない式の型: {0}。

driverUtil_parsingError=JSON 式の解析中にエラーが発生しました: {0}

mDbOp_aggrCmdFailed=集計コマンドの操作を実行できません。 \n接続した MongoDB サーバがバージョン 2.2 以降であることを確認してください。

mDbOp_dbCmdFailed=コマンド操作 ({0}) を実行できません

mDbOp_invalidQueryExpr=クエリ式が無効です。クエリを実行できません。

mDbOp_mapReduceCmdFailed=MapReduce コマンド操作 ({0}) を実行できません

mDbOp_noCmdResults=使用可能なコマンドの結果がありません。

mDbResultSet_cannotConvertFieldData={2} データタイプの '{0}' フィールド値 ({1}) は {3} 値に変換できません。

queryModel_emptyExprErrorMsg=<空白の式>

queryModel_invalidCollectionName=コレクション名 (${0}) が無効です。

queryModel_invalidDbCmdKeyValue=データベースコマンド ({0}) は次でのみサポートされます: \n    {1}

queryModel_invalidModelToExec=クエリ定義が無効です。クエリを実行できません。

queryModel_invalidModelToPrepare=クエリ定義が無効です。クエリを準備できません。

queryModel_invalidPipelineOp=パイプライン操作が無効です: {0}

queryModel_invalidQuerySortExpr=クエリのソート式ではソート順として正または負の値を指定する必要があります: \n    {0}

queryModel_invalidSortAggrValue={0} パイプライン操作では、ソートキーで 1 または -1 の値を指定する必要があります: \n    {1}

queryModel_missingCollectionName=データセットクエリ内で MongoDB コレクションが定義されていません。

queryModel_missingGroupAggrKey={0} パイプライン操作では、{1} フィールドを指定する必要があります: \n    {2}

queryModel_missingMapReduceKey=コマンド式に必要なキーが見つかりません: {0}

queryModel_missingMapReduceValue=コマンド式のキー {0} に値が必要です。

queryModel_missingQueryProps=データセット内でクエリが定義されていません。

queryModel_nonSupportedDbCmd=データベースコマンドのタイプがサポートされていません: \n    {0}

queryProperties_aggrCmdName=集計

queryProperties_dbCmdName=データベースコマンドの実行

queryProperties_errDeSerializeDBObject=MongoDB 式をシリアル化解除できません: {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=フィールド名が無効です: {0}
