#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=Impossible d'établir la connexion avec les propriétés spécifiées.

mDbConnection_invalidDatabaseName=La base de données spécifiée ({0}) n'existe pas.

mDbConnection_missingValueDBName=Valeur requise manquante dans la propriété Nom de la base de données.

mDbConnection_noConnection=Aucune connexion établie pour préparer la requête.

mDbDriver_missingValueServerHost=Valeur requise manquante dans la propriété Hôte du serveur.

mDbDriver_nonDefinedDataType=Non défini

mDbDriver_readPrefNearest=le plus proche

mDbDriver_readPrefPrimary=primaire

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=secondaire

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=Nom de collection non valide : {0}

mDbMetaData_missingCmdExprText=Expression manquante pour l'exécution de la commande {0}.

mDbQuery_invalidQueryExecQuery=La requête est non valide et ne peut pas être exécutée.

mDbQuery_invalidQueryGetMD=La requête est non valide et ne peut pas préparer les métadonnées du jeu de résultats.

driverUtil_invalidExpr=Type d'expression inattendue : {0}.

driverUtil_parsingError=Erreur dans l'analyse de l'expression JSON : {0}

mDbOp_aggrCmdFailed=Impossible d'exécuter la commande Regrouper. \nVérifiez que la version du serveur MongoDB connecté correspond à la version 2.2 ou ultérieure.

mDbOp_dbCmdFailed=Impossible d'exécuter la commande ({0})

mDbOp_invalidQueryExpr=Expression de la requête non valide, impossible d'exécuter la requête.

mDbOp_mapReduceCmdFailed=Impossible d'exécuter la commande RéduireCarte ({0})

mDbOp_noCmdResults=Aucun résultat de commande disponible.

mDbResultSet_cannotConvertFieldData=Impossible de convertir la valeur de champ '{0}' ({1}) de type de données {2} en valeur {3}

queryModel_emptyExprErrorMsg=<expression vide>

queryModel_invalidCollectionName=Nom de collection non valide (${0}).

queryModel_invalidDbCmdKeyValue=La commande de la base de données ({0}) est uniquement prise en charge par : \n    {1}

queryModel_invalidModelToExec=Définition de requête non valide, impossible d'exécuter la requête.

queryModel_invalidModelToPrepare=Définition de requête non valide, impossible de préparer la requête.

queryModel_invalidPipelineOp=Pipeline non valide : {0}

queryModel_invalidQuerySortExpr=Une expression de tri de requête doit spécifier une valeur positive ou négative pour l'ordre de tri : \n    {0}

queryModel_invalidSortAggrValue=Une {0} pipeline doit spécifier une valeur de 1 ou de -1 dans la clé de tri : \n    {1}

queryModel_missingCollectionName=Aucune collection MongoDB n'est définie dans la requête de jeu de données.

queryModel_missingGroupAggrKey=Une {0} pipeline doit spécifier un champ {1} : \n    {2}

queryModel_missingMapReduceKey=L'expression de la commande ne contient pas la valeur requise : {0}

queryModel_missingMapReduceValue=La clé de l'expression de la commande nécessite {0} une valeur.

queryModel_missingQueryProps=Aucune requête n'est définie dans le jeu de données.

queryModel_nonSupportedDbCmd=Le type de commande de la base de données n'est pas pris en charge : \n    {0}

queryProperties_aggrCmdName=Agrégat

queryProperties_dbCmdName=Exécuter la commande de la base de données

queryProperties_errDeSerializeDBObject=Impossible de désérialiser l'expression MongoDB : {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=Nom de champ incorrect : {0}
