#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=지정한 속성으로 연결을 열 수 없습니다.

mDbConnection_invalidDatabaseName=지정한 데이터베이스({0})가 없습니다.

mDbConnection_missingValueDBName=데이터베이스 이름 속성의 필수 값이 누락되었습니다.

mDbConnection_noConnection=쿼리를 준비하기 위해 열린 연결이 없습니다.

mDbDriver_missingValueServerHost=서버 호스트 속성의 필수 값이 누락되었습니다.

mDbDriver_nonDefinedDataType=정의되지 않음

mDbDriver_readPrefNearest=근접

mDbDriver_readPrefPrimary=기본

mDbDriver_readPrefPrimaryPreferred=primaryPreferred
mDbDriver_readPrefSecondary=보조

mDbDriver_readPrefSecondaryPreferred=secondaryPreferred
mDbDSMetaData_dataSourceName=MongoDB Data Source
mDbMetaData_invalidCollectionName=잘못된 컬렉션 이름: {0}

mDbMetaData_missingCmdExprText={0} 명령 연산의 식이 누락되었습니다.

mDbQuery_invalidQueryExecQuery=쿼리가 잘못되어 실행할 수 없습니다.

mDbQuery_invalidQueryGetMD=쿼리가 잘못되어 결과 집합 메타데이터를 준비할 수 없습니다.

driverUtil_invalidExpr=예기치 않은 식 형식: {0}.

driverUtil_parsingError=JSON 식 구문 분석 오류: {0}

mDbOp_aggrCmdFailed=집계 명령 연산을 실행할 수 없습니다. \n연결된 MongoDB 서버가 2.2 이상 버전인지 확인하십시오.

mDbOp_dbCmdFailed=명령 연산({0})을 실행할 수 없습니다.

mDbOp_invalidQueryExpr=쿼리 식이 잘못되어 쿼리를 실행할 수 없습니다.

mDbOp_mapReduceCmdFailed=MapReduce 명령 연산({0})을 실행할 수 없습니다.

mDbOp_noCmdResults=사용 가능한 명령 결과가 없습니다.

mDbResultSet_cannotConvertFieldData={2} 데이터 형식의 '{0}' 필드 값 ({1})을(를) {3} 값으로 변환할 수 없습니다.

queryModel_emptyExprErrorMsg=<비어 있는 식>

queryModel_invalidCollectionName=잘못된 컬렉션 이름(${0})입니다.

queryModel_invalidDbCmdKeyValue=데이터베이스 명령({0})은 다음 항목에서만 지원됩니다. \n    {1}

queryModel_invalidModelToExec=쿼리 정의가 잘못되어 쿼리를 실행할 수 없습니다.

queryModel_invalidModelToPrepare=쿼리 정의가 잘못되어 쿼리를 준비할 수 없습니다.

queryModel_invalidPipelineOp=잘못된 파이프라인 연산: {0}

queryModel_invalidQuerySortExpr=쿼리 정렬 식이 정렬 순서의 양수 또는 음수 값을 지정해야 합니다. \n    {0}

queryModel_invalidSortAggrValue={0} 파이프라인 연산이 정렬 키의 값을 1 또는 -1로 지정해야 합니다. \n    {1}

queryModel_missingCollectionName=데이터 집합 쿼리에 정의된 MongoDB 컬렉션이 없습니다.

queryModel_missingGroupAggrKey={0} 파이프라인 연산이 {1} 필드를 지정해야 합니다. \n    {2}

queryModel_missingMapReduceKey=명령 식에 {0} 필수 키가 누락되었습니다.

queryModel_missingMapReduceValue=명령 식 키 {0}에 값을 입력해야 합니다.

queryModel_missingQueryProps=데이터 집합에 정의된 쿼리가 없습니다.

queryModel_nonSupportedDbCmd=데이터베이스 명령 형식이 지원되지 않습니다. \n    {0}

queryProperties_aggrCmdName=집계

queryProperties_dbCmdName=데이터베이스 명령 실행

queryProperties_errDeSerializeDBObject=MongoDB 식을 역직렬화할 수 없습니다. {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=필드 이름이 잘못되었습니다: {0}
