###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

birt.viewer.title=BIRT Report Viewer
birt.viewer.title.navigation=ナビゲーション

birt.viewer.title.error=エラー

birt.viewer.title.complete=完了

birt.viewer.title.message=メッセージ

birt.viewer.parameter=パラメタ

birt.viewer.runreport=レポートの実行

birt.viewer.required=アスタリスク (<FONT COLOR="red">*</FONT>) が付いているパラメタは必須です。

birt.viewer.viewinpdf=PDF 形式で表示

birt.viewer.maximize=レポートパラメタを非表示にします。

birt.viewer.restore=レポートパラメタを表示します。

birt.viewer.error=エラーメッセージ

birt.viewer.error.noparameter=このレポートにはパラメタがありません。

birt.viewer.error.parameter.invalid=パラメタ "{0}" は無効です。

birt.viewer.error.noprinter=PostScript 形式をサポートする使用可能なプリンタが見つかりません。

birt.viewer.error.unknownerror=不明なエラーです。

birt.viewer.error.generatereportfirst=先にレポート文書を生成してください。

birt.viewer.error.copiesnumber=有効なコピー番号を入力してください。

birt.viewer.error.parameterrequired=必須パラメタ [{0}] の値が指定されていません。

birt.viewer.error.parameternotallowblank=パラメタ "{0}" は空白にできません。

birt.viewer.error.parameternotselected=パラメタ "{0}" の値を選択してください。

birt.viewer.error.noviewingsession=表示セッションは使用できないか、有効期限切れになっています。

birt.viewer.error.viewingsessionexpired=表示セッションが有効期限切れになっています。

birt.viewer.error.viewingsessionlocked=表示セッションがロックされているため中止できません。

birt.viewer.error.viewingsessionmaxreached=表示セッションの最大数に到達しました。

birt.viewer.error.columnrequired=列が選択されていません。エクスポートする列を少なくとも 1 つ選択してください。

birt.viewer.message.taskcanceled=現在の処理を中止しました。

###############################################################################
# Toolbar
###############################################################################
birt.viewer.toolbar.print=レポートの印刷

birt.viewer.toolbar.printserver=レポートをサーバ上で印刷

birt.viewer.toolbar.toc=目次の表示

birt.viewer.toolbar.parameter=レポートの実行

birt.viewer.toolbar.export=データのエクスポート

birt.viewer.toolbar.font=フォントの変更

birt.viewer.toolbar.enableiv=インタラクティブビューアの起動

birt.viewer.toolbar.exportreport=レポートのエクスポート

###############################################################################
# navbar
###############################################################################
birt.viewer.navbar.first=最初のページ

birt.viewer.navbar.previous=前のページ

birt.viewer.navbar.next=次のページ

birt.viewer.navbar.last=最後のページ

birt.viewer.navbar.goto=ジャンプ

birt.viewer.navbar.lable.goto=ページ指定ジャンプ :

birt.viewer.navbar.prompt.one=表示中のページ

birt.viewer.navbar.prompt.two=/

birt.viewer.navbar.error.blankpagenum=有効なページ番号を入力してください。

###############################################################################
# progress bar
###############################################################################
birt.viewer.progressbar.prompt=処理中です。しばらくお待ちください...

birt.viewer.progressbar.confirmcanceltask=現在の処理を中止しますか ?

###############################################################################
# Dialog 
###############################################################################
birt.viewer.dialog.ok=OK

birt.viewer.dialog.cancel=キャンセル

birt.viewer.dialog.run=レポートの実行

birt.viewer.dialog.close=閉じる

birt.viewer.dialog.page=ページ

birt.viewer.dialog.page.all=すべてのページ

birt.viewer.dialog.page.current=現在のページ

birt.viewer.dialog.page.range=ページ :

birt.viewer.dialog.page.range.description=(ページ番号をコンマで区切って指定するか、ページ範囲を指定してください。例 : 1-6 または 1,3,6)

birt.viewer.dialog.page.error.invalidpagerange=ページ範囲が無効です。

###############################################################################
# Dialog title
###############################################################################
birt.viewer.dialog.exception.title=例外

birt.viewer.dialog.exportReport.title=レポートのエクスポート

birt.viewer.dialog.parameter.title=パラメタ

birt.viewer.dialog.simpleExportData.title=データのエクスポート

birt.viewer.dialog.printReport.title=レポートの印刷

birt.viewer.dialog.printReportServer.title=レポートをサーバ上で印刷

###############################################################################
# Export report dialog 
###############################################################################
birt.viewer.dialog.export.format=エクスポート形式 :

birt.viewer.dialog.export.format.pdf=PDF
birt.viewer.dialog.export.format.excel=EXCEL
birt.viewer.dialog.export.all=詳細レポートをエクスポートする

birt.viewer.dialog.export.all.detail=現在のビューで変更した内容は反映せずに、<br>すべてのレポートデータをエクスポートします。

birt.viewer.dialog.export.modified=現在の変更をレポートに反映してエクスポートする

birt.viewer.dialog.export.modified.detail=表示されているデータだけをエクスポートします。<BR>フィルタによって隠されているデータはエクスポートされません。

birt.viewer.dialog.export.pdf.fitto=合わせる

birt.viewer.dialog.export.pdf.fittoauto=自動

birt.viewer.dialog.export.pdf.fittoactual=実寸

birt.viewer.dialog.export.pdf.fittowidth=ページの幅に合わせる

birt.viewer.dialog.export.pdf.fittowhole=全体表示

###############################################################################
# Print Report dialog 
###############################################################################
birt.viewer.dialog.print.format=印刷形式

birt.viewer.dialog.print.format.html=HTML
birt.viewer.dialog.print.format.pdf=PDF
birt.viewer.dialog.print.printpreviewalreadyopen=印刷プレビューのウィンドウはすでに開いています。

###############################################################################
# Print report on the server dialog 
###############################################################################
birt.viewer.dialog.printserver.onserver=出力文書ファイルをサーバ上で印刷する

birt.viewer.dialog.printserver.printer=プリンタ :

birt.viewer.dialog.printserver.status=状態:

birt.viewer.dialog.printserver.model=モデル :

birt.viewer.dialog.printserver.description=説明 :

birt.viewer.dialog.printserver.status.acceptingjobs=ジョブの受信中

birt.viewer.dialog.printserver.status.notacceptingjobs=ジョブを許可しない

birt.viewer.dialog.printserver.settings=印刷設定を指定してください。

birt.viewer.dialog.printserver.settings.copies=部数 :

birt.viewer.dialog.printserver.settings.collate=部単位で印刷 :

birt.viewer.dialog.printserver.settings.mode=モード :

birt.viewer.dialog.printserver.settings.mode.bw=モノクロ

birt.viewer.dialog.printserver.settings.mode.color=カラー

birt.viewer.dialog.printserver.settings.duplex=両面印刷:

birt.viewer.dialog.printserver.settings.duplex.simplex=片面印刷

birt.viewer.dialog.printserver.settings.duplex.horizontal=横

birt.viewer.dialog.printserver.settings.duplex.vertical=縦

birt.viewer.dialog.printserver.settings.pagesize=用紙サイズ :

birt.viewer.dialog.printserver.settings.print=印刷 :

birt.viewer.dialog.printserver.complete=文書ファイルをサーバ上の選択したプリンタに送信しました。

birt.viewer.dialog.printserver.error.noprinter=プリンタがありません。
###############################################################################
# Confirmation dialog 
###############################################################################
birt.viewer.dialog.confirmation.title=確認
 
###############################################################################
# Export data dialog 
###############################################################################
birt.viewer.dialog.exportdata.tab.field=データフィールド

birt.viewer.dialog.exportdata.tab.filter=フィルタの適用条件

birt.viewer.dialog.exportdata.resultsets=使用可能な結果セット

birt.viewer.dialog.exportdata.availablecolumn=使用可能な列

birt.viewer.dialog.exportdata.selectedcolumn=選択済みの列

birt.viewer.dialog.exportdata.extension=エクスポート形式 :

birt.viewer.dialog.exportdata.encoding=出力エンコード :

birt.viewer.dialog.exportdata.encoding.other=その他

birt.viewer.dialog.exportdata.encoding.comment=(空白の場合は PC の地域設定のエンコードを使用)

birt.viewer.dialog.exportdata.addall=すべて追加

birt.viewer.dialog.exportdata.add=追加

birt.viewer.dialog.exportdata.removeall=すべて削除

birt.viewer.dialog.exportdata.remove=削除

birt.viewer.dialog.exportdata.up=上へ

birt.viewer.dialog.exportdata.down=下へ

birt.viewer.dialog.exportdata.separator=区切り文字 :

birt.viewer.dialog.exportdata.datatype=列のデータ型をエクスポートする

birt.viewer.dialog.exportdata.localeneutral=ロケールに中立的な形式でエクスポートする

birt.viewer.dialog.exportdata.carriage_return=データを復帰改行付きでエクスポート

birt.viewer.sep.0=コンマ (,)

birt.viewer.sep.1=セミコロン (;)

birt.viewer.sep.2=コロン (:)

birt.viewer.sep.3=縦線 (|)

birt.viewer.sep.4=タブ (\\t)

###############################################################################
# General exception
###############################################################################
birt.viewer.generalException.DOCUMENT_FILE_ERROR=文書ファイル {0} は存在しないか、誤りがあります。

birt.viewer.generalException.DOCUMENT_ACCESS_ERROR=文書ファイル {0} にアクセスできません。

birt.viewer.generalException.REPORT_FILE_ERROR=レポートファイル {0} は存在しないか、誤りがあります。

birt.viewer.generalException.REPORT_ACCESS_ERROR=レポートファイル {0} にアクセスできません。

birt.viewer.generalException.DOCUMENT_FILE_PROCESSING=文書ファイルを処理しています。後でやり直してください。

birt.viewer.generalException.NO_REPORT_DESIGN=レポートデザインオブジェクトがありません。

birt.viewer.generalException.MULTIPLE_EXCEPTIONS=複数の例外が発生しました。

###############################################################################
# Report service exception
###############################################################################
birt.viewer.reportServiceException.EXTRACT_DATA_NO_DOCUMENT=データを抽出する文書ファイルがありません。

birt.viewer.reportServiceException.EXTRACT_DATA_NO_RESULT_SET=データを抽出する結果セットがありません。

birt.viewer.reportServiceException.INVALID_TOC=目次のクエリが無効です。

birt.viewer.reportServiceException.INVALID_PARAMETER=パラメタ {0} は定義されていないため、無効です。

birt.viewer.reportServiceException.STARTUP_REPORTENGINE_ERROR=レポートエンジンの開始時に重大なエラーが発生しました。

birt.viewer.reportServiceException.INVALID_EXTRACTFORMAT=データの抽出形式が無効か、指定されていません。

birt.viewer.reportServiceException.INVALID_EXTRACTEXTENSION=データ抽出拡張 ID が無効です。
###############################################################################
# Birt action handler exception
###############################################################################
birt.viewer.actionException.NO_REPORT_DOCUMENT=レポート文書のインスタンスが空です。

birt.viewer.actionException.INVALID_BOOKMARK=ブックマーク {0} が無効です。確認して、リンクを設定し直してください。

birt.viewer.actionException.INVALID_PAGE_NUMBER=ページ番号 ({0}/{1}) が無効です。

birt.viewer.actionException.PAGE_NUMBER_PARSE_ERROR=ページ番号: {0} が無効です。

birt.viewer.actionException.INVALID_ID_FORMAT=ID の形式が無効です (ID={0})。

birt.viewer.actionException.DOCUMENT_FILE_NO_EXIST=セッションがタイムアウトになったか、文書ファイルがありません。

###############################################################################
# Birt soap bingding impl exception
###############################################################################
birt.viewer.soapBindingException.NO_HANDLER_FOR_TARGET=このターゲットにハンドラが見つかりません (ターゲット : {0})。

###############################################################################
# Component processor exception
###############################################################################
birt.viewer.componentProcessorException.MISSING_OPERATOR=エラー : 演算子が見つかりません。

###############################################################################
# Exception dialog
###############################################################################
birt.viewer.exceptionDialog.stackTrace=スタックトレース :

birt.viewer.exceptionDialog.showStackTrace=例外スタックトレースの表示

birt.viewer.exceptionDialog.hideStackTrace=例外スタックトレースの非表示

###############################################################################
# Birt Viewer JSP Taglib
###############################################################################
birt.viewer.taglib.NO_ATTR_ID=属性 ID を指定してください。

birt.viewer.taglib.INVALID_ATTR_ID=属性 ID に無効な文字が指定されています。

birt.viewer.taglib.ATTR_ID_DUPLICATE=属性 ID には、他で使われていないものを指定してください。

birt.viewer.taglib.PARAM_NAME_DUPLICATE=重複するパラメタ名は使用できません。

birt.viewer.taglib.NO_REPORT_SOURCE=レポートデザインまたは文書ファイルを指定してください。

birt.viewer.taglib.NO_REPORT_DOCUMENT=Reportlet ではレポート文書ファイルが必要です。

birt.viewer.taglib.NO_REQUESTER_NAME=parameterPage タグの "name" 属性が必要です。

###############################################################################
# Birt Viewer Message
###############################################################################
birt.viewer.message.document.successful=レポート文書ファイルが生成されました。

###############################################################################
# Birt Viewer General Exceptions
###############################################################################
birt.viewer.exception.maybe_disabled_cookies=これは、クライアント側で cookies が無効になっていることが原因で発生する場合があります。
