###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

birt.viewer.title=BIRT Report Viewer
birt.viewer.title.navigation=Navigation

birt.viewer.title.error=Fehler

birt.viewer.title.complete=Abgeschlossen

birt.viewer.title.message=Meldung

birt.viewer.parameter=Parameter

birt.viewer.runreport=Bericht ausführen

birt.viewer.required=Mit <FONT COLOR="red">*</FONT> gekennzeichnete Parameter sind erforderlich.

birt.viewer.viewinpdf=Im PDF-Format anzeigen

birt.viewer.maximize=Berichtparameter ausblenden

birt.viewer.restore=Berichtparameter anzeigen

birt.viewer.error=Fehlermeldung

birt.viewer.error.noparameter=Für diesen Bericht sind keine Parameter vorhanden.

birt.viewer.error.parameter.invalid=Der Parameter "{0}" ist ungültig.

birt.viewer.error.noprinter=Es kann kein verfügbarer Drucker gefunden werden, der das Postscript-Format unterstützt.

birt.viewer.error.unknownerror=Unbekannter Fehler.

birt.viewer.error.generatereportfirst=Berichtdokument muss zuerst generiert werden.

birt.viewer.error.copiesnumber=Geben Sie eine gültige Anzahl von Kopien ein.

birt.viewer.error.parameterrequired=Der Wert des erforderlichen Parameters [{0}] wurde nicht festgelegt.

birt.viewer.error.parameternotallowblank=Der Parameter "{0}" darf nicht leer sein.

birt.viewer.error.parameternotselected=Wählen Sie den Wert für den Parameter "{0}" aus.

birt.viewer.error.noviewingsession=Die Ansichtssitzung ist nicht verfügbar oder abgelaufen.

birt.viewer.error.viewingsessionexpired=Die Ansichtssitzung ist abgelaufen.

birt.viewer.error.viewingsessionlocked=Die Ansichtssitzung ist gesperrt und kann nicht beendet werden.

birt.viewer.error.viewingsessionmaxreached=Die Höchstanzahl an Ansichtssitzungen wurde erreicht.

birt.viewer.error.columnrequired=Keine Spalte ausgewählt, bitte mindestens eine Spalte für den Export auswählen.

birt.viewer.message.taskcanceled=Der aktuelle Vorgang wurde abgebrochen.

###############################################################################
# Toolbar
###############################################################################
birt.viewer.toolbar.print=Bericht drucken

birt.viewer.toolbar.printserver=Bericht auf dem Server drucken

birt.viewer.toolbar.toc=Inhaltsverzeichnis anzeigen

birt.viewer.toolbar.parameter=Bericht ausführen

birt.viewer.toolbar.export=Daten exportieren

birt.viewer.toolbar.font=Schriftart ändern

birt.viewer.toolbar.enableiv=Interaktiven Viewer aufrufen

birt.viewer.toolbar.exportreport=Bericht exportieren

###############################################################################
# navbar
###############################################################################
birt.viewer.navbar.first=Erste Seite

birt.viewer.navbar.previous=Vorherige Seite

birt.viewer.navbar.next=Nächste Seite

birt.viewer.navbar.last=Letzte Seite

birt.viewer.navbar.goto=Gehe zu

birt.viewer.navbar.lable.goto=Gehe zu Seite:

birt.viewer.navbar.prompt.one=Angezeigte Seite: Seite

birt.viewer.navbar.prompt.two=von

birt.viewer.navbar.error.blankpagenum=Geben Sie eine gültige Seitenzahl ein.

###############################################################################
# progress bar
###############################################################################
birt.viewer.progressbar.prompt=Vorgang läuft. Bitte warten ...

birt.viewer.progressbar.confirmcanceltask=Soll der aktuelle Vorgang abgebrochen werden?

###############################################################################
# Dialog 
###############################################################################
birt.viewer.dialog.ok=OK

birt.viewer.dialog.cancel=Abbrechen

birt.viewer.dialog.run=Bericht ausführen

birt.viewer.dialog.close=Schließ.en

birt.viewer.dialog.page=Seiten

birt.viewer.dialog.page.all=Alle Seiten

birt.viewer.dialog.page.current=Aktuelle Seite

birt.viewer.dialog.page.range=Seiten:

birt.viewer.dialog.page.range.description=(Seitenzahl(en) und/oder Seitenbereich(e) eingeben. Beispiel: 1-6 oder 1,3,6)

birt.viewer.dialog.page.error.invalidpagerange=Ungültiger Seitenbereich

###############################################################################
# Dialog title
###############################################################################
birt.viewer.dialog.exception.title=Ausnahme

birt.viewer.dialog.exportReport.title=Bericht exportieren

birt.viewer.dialog.parameter.title=Parameter

birt.viewer.dialog.simpleExportData.title=Daten exportieren

birt.viewer.dialog.printReport.title=Bericht drucken

birt.viewer.dialog.printReportServer.title=Bericht auf dem Server drucken

###############################################################################
# Export report dialog 
###############################################################################
birt.viewer.dialog.export.format=Exportformat:

birt.viewer.dialog.export.format.pdf=PDF
birt.viewer.dialog.export.format.excel=EXCEL
birt.viewer.dialog.export.all=Detaillierten Bericht exportieren

birt.viewer.dialog.export.all.detail=Sämtliche verfügbaren Berichtdaten werden unabhängig von der<br>aktuellen Ansicht exportiert.

birt.viewer.dialog.export.modified=Bericht mit aktuellen Änderungen exportieren

birt.viewer.dialog.export.modified.detail=Es werden nur sichtbare Daten exportiert. Herausgefilterte oder<br>ausgeblendete Daten werden nicht exportiert.

birt.viewer.dialog.export.pdf.fitto=Anpassen

birt.viewer.dialog.export.pdf.fittoauto=Automatisch

birt.viewer.dialog.export.pdf.fittoactual=Tatsächliche Größe

birt.viewer.dialog.export.pdf.fittowidth=An Seitenbreite anpassen

birt.viewer.dialog.export.pdf.fittowhole=An ganze Seite anpassen

###############################################################################
# Print Report dialog 
###############################################################################
birt.viewer.dialog.print.format=Druckformat

birt.viewer.dialog.print.format.html=HTML
birt.viewer.dialog.print.format.pdf=PDF
birt.viewer.dialog.print.printpreviewalreadyopen=Ein Fenster mit der Seitenansicht ist bereits geöffnet.

###############################################################################
# Print report on the server dialog 
###############################################################################
birt.viewer.dialog.printserver.onserver=Ausgabedokument auf dem Server drucken

birt.viewer.dialog.printserver.printer=Drucker:

birt.viewer.dialog.printserver.status=Status:

birt.viewer.dialog.printserver.model=Modell:

birt.viewer.dialog.printserver.description=Beschreibung:

birt.viewer.dialog.printserver.status.acceptingjobs=Aufträge werden angenommen

birt.viewer.dialog.printserver.status.notacceptingjobs=Aufträge werden nicht angenommen

birt.viewer.dialog.printserver.settings=Druckeinstellungen festlegen

birt.viewer.dialog.printserver.settings.copies=Anzahl der Exemplare:

birt.viewer.dialog.printserver.settings.collate=Sortieren:

birt.viewer.dialog.printserver.settings.mode=Modus:

birt.viewer.dialog.printserver.settings.mode.bw=Schwarzweiß

birt.viewer.dialog.printserver.settings.mode.color=Farbe

birt.viewer.dialog.printserver.settings.duplex=Duplex:

birt.viewer.dialog.printserver.settings.duplex.simplex=Simplex

birt.viewer.dialog.printserver.settings.duplex.horizontal=Horizontal

birt.viewer.dialog.printserver.settings.duplex.vertical=Vertikal

birt.viewer.dialog.printserver.settings.pagesize=Seitengröße:

birt.viewer.dialog.printserver.settings.print=Drucken:

birt.viewer.dialog.printserver.complete=Dokument an ausgewählten Drucker auf dem Server gesendet.

birt.viewer.dialog.printserver.error.noprinter=Kein Drucker
###############################################################################
# Confirmation dialog 
###############################################################################
birt.viewer.dialog.confirmation.title=Bestätigung
 
###############################################################################
# Export data dialog 
###############################################################################
birt.viewer.dialog.exportdata.tab.field=Datenfelder

birt.viewer.dialog.exportdata.tab.filter=Filterkriterien

birt.viewer.dialog.exportdata.resultsets=Verfügbare Ergebnisse

birt.viewer.dialog.exportdata.availablecolumn=Verfügbare Spalten

birt.viewer.dialog.exportdata.selectedcolumn=Ausgewählte Spalten

birt.viewer.dialog.exportdata.extension=Exportformat:

birt.viewer.dialog.exportdata.encoding=Ausgabecodierung:

birt.viewer.dialog.exportdata.encoding.other=Andere

birt.viewer.dialog.exportdata.encoding.comment=(Wenn leer, lokale Codierung verwenden)

birt.viewer.dialog.exportdata.addall=Alle hinzufügen

birt.viewer.dialog.exportdata.add=Hinzuf

birt.viewer.dialog.exportdata.removeall=Alles entfernen

birt.viewer.dialog.exportdata.remove=Entfernen

birt.viewer.dialog.exportdata.up=Aufwärts

birt.viewer.dialog.exportdata.down=Abwärts

birt.viewer.dialog.exportdata.separator=Trennzeichen:

birt.viewer.dialog.exportdata.datatype=Spalten-Datenytpen exportieren

birt.viewer.dialog.exportdata.localeneutral=Spalte als gebietsschemaneutral exportieren

birt.viewer.dialog.exportdata.carriage_return=Daten mit Zeilenumbruch exportieren

birt.viewer.sep.0=Komma (,)

birt.viewer.sep.1=Semikolon (;)

birt.viewer.sep.2=Doppelpunkt (:)

birt.viewer.sep.3=Vertikale Linie (|)

birt.viewer.sep.4=Tab (\\t)

###############################################################################
# General exception
###############################################################################
birt.viewer.generalException.DOCUMENT_FILE_ERROR=Die Dokumentdatei : {0} ist nicht vorhanden oder fehlerhaft.

birt.viewer.generalException.DOCUMENT_ACCESS_ERROR=Zugriff auf die Dokumentdatei : {0} nicht möglich.

birt.viewer.generalException.REPORT_FILE_ERROR=Die Berichtdatei : {0} ist nicht vorhanden oder fehlerhaft.

birt.viewer.generalException.REPORT_ACCESS_ERROR=Zugriff auf die Berichtdatei nicht möglich : {0}.

birt.viewer.generalException.DOCUMENT_FILE_PROCESSING=Dokumentdatei wird verarbeitet. Versuchen Sie es später erneut.

birt.viewer.generalException.NO_REPORT_DESIGN=Kein Berichtdesignobjekt verfügbar.

birt.viewer.generalException.MULTIPLE_EXCEPTIONS=Es sind mehrere Ausnahmen aufgetreten.

###############################################################################
# Report service exception
###############################################################################
birt.viewer.reportServiceException.EXTRACT_DATA_NO_DOCUMENT=Für die Extrahierung der Daten ist keine Dokumentdatei verfügbar.

birt.viewer.reportServiceException.EXTRACT_DATA_NO_RESULT_SET=Für die Extrahierung der Daten ist kein Ergebnis verfügbar.

birt.viewer.reportServiceException.INVALID_TOC=Ungültige Inhaltsverzeichnis-Anfrage.

birt.viewer.reportServiceException.INVALID_PARAMETER=Ungültiger Parameter: {0}; er ist nicht definiert.

birt.viewer.reportServiceException.STARTUP_REPORTENGINE_ERROR=Beim Versuch, die Berichts-Engine zu starten, ist ein nicht behebbarer Fehler aufgetreten.

birt.viewer.reportServiceException.INVALID_EXTRACTFORMAT=Datenextrahierungsformat ist ungültig oder wurde nicht angegeben.

birt.viewer.reportServiceException.INVALID_EXTRACTEXTENSION=Ungültige Erweiterungs-ID für Datenextrahierung
###############################################################################
# Birt action handler exception
###############################################################################
birt.viewer.actionException.NO_REPORT_DOCUMENT=Berichtdokument-Instanz ist leer.

birt.viewer.actionException.INVALID_BOOKMARK=Das Lesezeichen {0} ist ungültig. Bitte prüfen und Verknüpfung zurücksetzen.

birt.viewer.actionException.INVALID_PAGE_NUMBER=Ungültige Seitennummer {0} von {1}.

birt.viewer.actionException.PAGE_NUMBER_PARSE_ERROR=Die Seitennummer {0} ist ungültig.

birt.viewer.actionException.INVALID_ID_FORMAT=Ungültiges ID-Format. Id={0}.

birt.viewer.actionException.DOCUMENT_FILE_NO_EXIST=Sitzung wegen Zeitüberschreitung abgebrochen bzw. keine Dokumentdatei verfügbar.

###############################################################################
# Birt soap bingding impl exception
###############################################################################
birt.viewer.soapBindingException.NO_HANDLER_FOR_TARGET=Für dieses Ziel wurde kein Handler gefunden. Ziel: {0}.

###############################################################################
# Component processor exception
###############################################################################
birt.viewer.componentProcessorException.MISSING_OPERATOR=Fehler: Fehlender Operator!

###############################################################################
# Exception dialog
###############################################################################
birt.viewer.exceptionDialog.stackTrace=Ablaufverfolgungsstapel:

birt.viewer.exceptionDialog.showStackTrace=Ausnahme für Ablaufverfolgungsstapel einblenden

birt.viewer.exceptionDialog.hideStackTrace=Ausnahme für Ablaufverfolgungsstapel ausblenden

###############################################################################
# Birt Viewer JSP Taglib
###############################################################################
birt.viewer.taglib.NO_ATTR_ID=Attribut-ID muss angegeben werden.

birt.viewer.taglib.INVALID_ATTR_ID=Attribut-ID enthält ungültige Zeichen.

birt.viewer.taglib.ATTR_ID_DUPLICATE=Attribut-ID muss eindeutig sein.

birt.viewer.taglib.PARAM_NAME_DUPLICATE=Parametername darf nicht doppelt vorhanden sein.

birt.viewer.taglib.NO_REPORT_SOURCE=Berichtdesign oder Dokumentdatei muss angegeben werden.

birt.viewer.taglib.NO_REPORT_DOCUMENT=Reportlet benötigt Berichtsdokument.

birt.viewer.taglib.NO_REQUESTER_NAME=Das Attribut "Name" des Tags parameterPage ist erforderlich.

###############################################################################
# Birt Viewer Message
###############################################################################
birt.viewer.message.document.successful=Das Berichtsdokument wurde erfolgreich erstellt.

###############################################################################
# Birt Viewer General Exceptions
###############################################################################
birt.viewer.exception.maybe_disabled_cookies=Das Problem wird möglicherweise durch deaktivierte Cookies auf der Client-Seite verursacht.
