###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

birt.viewer.title=BIRT Report Viewer
birt.viewer.title.navigation=导航　

birt.viewer.title.error=错误

birt.viewer.title.complete=完成

birt.viewer.title.message=消息

birt.viewer.parameter=参数

birt.viewer.runreport=运行报表

birt.viewer.required=需要带有 <FONT COLOR="red">*</FONT> 标记的参数。

birt.viewer.viewinpdf=以 PDF 查看

birt.viewer.maximize=隐藏报表参数

birt.viewer.restore=显示报表参数

birt.viewer.error=错误消息

birt.viewer.error.noparameter=此报表无参数。

birt.viewer.error.parameter.invalid=参数“{0}”无效。

birt.viewer.error.noprinter=无法找到支持 PostScript 格式的任何可用打印机。

birt.viewer.error.unknownerror=未知错误。

birt.viewer.error.generatereportfirst=应首先生成报表文档。

birt.viewer.error.copiesnumber=请输入有效份数。

birt.viewer.error.parameterrequired=未指定所需参数 [{0}] 的值。

birt.viewer.error.parameternotallowblank=参数“{0}”不能为空白。

birt.viewer.error.parameternotselected=请为参数“{0}”选择值。

birt.viewer.error.noviewingsession=查看会话不可用或已过期。

birt.viewer.error.viewingsessionexpired=查看会话已过期。

birt.viewer.error.viewingsessionlocked=查看会话被锁定，不能终止。

birt.viewer.error.viewingsessionmaxreached=已达到查看会话最大数量。

birt.viewer.error.columnrequired=尚未选择列，请至少选择一个要导出的列。

birt.viewer.message.taskcanceled=当前操作已取消。

###############################################################################
# Toolbar
###############################################################################
birt.viewer.toolbar.print=打印报表

birt.viewer.toolbar.printserver=在服务器上打印报表

birt.viewer.toolbar.toc=显示目录

birt.viewer.toolbar.parameter=运行报表

birt.viewer.toolbar.export=导出数据

birt.viewer.toolbar.font=更改字体

birt.viewer.toolbar.enableiv=调用交互式查看器

birt.viewer.toolbar.exportreport=导出报表

###############################################################################
# navbar
###############################################################################
birt.viewer.navbar.first=第一页

birt.viewer.navbar.previous=上一页

birt.viewer.navbar.next=下一页

birt.viewer.navbar.last=最后一页

birt.viewer.navbar.goto=转到

birt.viewer.navbar.lable.goto=转到页:

birt.viewer.navbar.prompt.one=显示页

birt.viewer.navbar.prompt.two=/

birt.viewer.navbar.error.blankpagenum=请输入有效页码。

###############################################################################
# progress bar
###############################################################################
birt.viewer.progressbar.prompt=正在处理，请稍候 ...

birt.viewer.progressbar.confirmcanceltask=您要取消当前操作吗?

###############################################################################
# Dialog 
###############################################################################
birt.viewer.dialog.ok=确定

birt.viewer.dialog.cancel=取消

birt.viewer.dialog.run=运行报表

birt.viewer.dialog.close=关闭

birt.viewer.dialog.page=页

birt.viewer.dialog.page.all=所有页

birt.viewer.dialog.page.current=当前页

birt.viewer.dialog.page.range=页:

birt.viewer.dialog.page.range.description=(输入页码和/或页范围。例如: 1-6 或 1,3,6)

birt.viewer.dialog.page.error.invalidpagerange=无效页范围

###############################################################################
# Dialog title
###############################################################################
birt.viewer.dialog.exception.title=异常

birt.viewer.dialog.exportReport.title=导出报表

birt.viewer.dialog.parameter.title=参数

birt.viewer.dialog.simpleExportData.title=导出数据

birt.viewer.dialog.printReport.title=打印报表

birt.viewer.dialog.printReportServer.title=在服务器上打印报表

###############################################################################
# Export report dialog 
###############################################################################
birt.viewer.dialog.export.format=导出格式:

birt.viewer.dialog.export.format.pdf=PDF
birt.viewer.dialog.export.format.excel=EXCEL
birt.viewer.dialog.export.all=导出详细报表

birt.viewer.dialog.export.all.detail=将导出所有可用报表数据，不考虑<br>当前视图的修改。

birt.viewer.dialog.export.modified=导出具有当前修改的报表

birt.viewer.dialog.export.modified.detail=将只导出可见数据。将不导出<BR>已被筛选掉或隐藏的数据。

birt.viewer.dialog.export.pdf.fitto=适合

birt.viewer.dialog.export.pdf.fittoauto=自动

birt.viewer.dialog.export.pdf.fittoactual=实际大小

birt.viewer.dialog.export.pdf.fittowidth=适合页面宽度

birt.viewer.dialog.export.pdf.fittowhole=适合整页

###############################################################################
# Print Report dialog 
###############################################################################
birt.viewer.dialog.print.format=打印格式

birt.viewer.dialog.print.format.html=HTML
birt.viewer.dialog.print.format.pdf=PDF
birt.viewer.dialog.print.printpreviewalreadyopen=打印预览窗口已打开。

###############################################################################
# Print report on the server dialog 
###############################################################################
birt.viewer.dialog.printserver.onserver=在服务器上打印输出文档文件

birt.viewer.dialog.printserver.printer=打印机:

birt.viewer.dialog.printserver.status=状态:

birt.viewer.dialog.printserver.model=型号:

birt.viewer.dialog.printserver.description=描述:

birt.viewer.dialog.printserver.status.acceptingjobs=正在接受作业

birt.viewer.dialog.printserver.status.notacceptingjobs=未接受作业

birt.viewer.dialog.printserver.settings=请指定打印设置

birt.viewer.dialog.printserver.settings.copies=份数:

birt.viewer.dialog.printserver.settings.collate=逐份打印:

birt.viewer.dialog.printserver.settings.mode=模式:

birt.viewer.dialog.printserver.settings.mode.bw=黑白

birt.viewer.dialog.printserver.settings.mode.color=颜色

birt.viewer.dialog.printserver.settings.duplex=双面:

birt.viewer.dialog.printserver.settings.duplex.simplex=单面

birt.viewer.dialog.printserver.settings.duplex.horizontal=水平

birt.viewer.dialog.printserver.settings.duplex.vertical=垂直

birt.viewer.dialog.printserver.settings.pagesize=页面大小:

birt.viewer.dialog.printserver.settings.print=打印:

birt.viewer.dialog.printserver.complete=已将文档文件发送到服务器上选择的打印机。

birt.viewer.dialog.printserver.error.noprinter=无打印机
###############################################################################
# Confirmation dialog 
###############################################################################
birt.viewer.dialog.confirmation.title=确认
 
###############################################################################
# Export data dialog 
###############################################################################
birt.viewer.dialog.exportdata.tab.field=数据字段

birt.viewer.dialog.exportdata.tab.filter=筛选标准

birt.viewer.dialog.exportdata.resultsets=可用结果集

birt.viewer.dialog.exportdata.availablecolumn=可用列

birt.viewer.dialog.exportdata.selectedcolumn=选择的列

birt.viewer.dialog.exportdata.extension=导出格式:

birt.viewer.dialog.exportdata.encoding=输出编码:

birt.viewer.dialog.exportdata.encoding.other=其它

birt.viewer.dialog.exportdata.encoding.comment=(如果为空白，使用本地编码)

birt.viewer.dialog.exportdata.addall=全部添加

birt.viewer.dialog.exportdata.add=添加

birt.viewer.dialog.exportdata.removeall=全部删除

birt.viewer.dialog.exportdata.remove=删除

birt.viewer.dialog.exportdata.up=上移

birt.viewer.dialog.exportdata.down=下移

birt.viewer.dialog.exportdata.separator=分隔符:

birt.viewer.dialog.exportdata.datatype=导出列的数据类型

birt.viewer.dialog.exportdata.localeneutral=不分区域设置导出列

birt.viewer.dialog.exportdata.carriage_return=使用回车符导出数据

birt.viewer.sep.0=逗号 ( , )

birt.viewer.sep.1=分号 ( ; )

birt.viewer.sep.2=冒号 ( : )

birt.viewer.sep.3=垂直线 ( | )

birt.viewer.sep.4=制表符 ( \\t )

###############################################################################
# General exception
###############################################################################
birt.viewer.generalException.DOCUMENT_FILE_ERROR=文档文件: {0} 不存在或包含错误。

birt.viewer.generalException.DOCUMENT_ACCESS_ERROR=无法访问文档文件: {0}。

birt.viewer.generalException.REPORT_FILE_ERROR=报表文件: {0} 不存在或包含错误。

birt.viewer.generalException.REPORT_ACCESS_ERROR=无法访问报表文件: {0}。

birt.viewer.generalException.DOCUMENT_FILE_PROCESSING=正在处理文档文件，请稍后再试。

birt.viewer.generalException.NO_REPORT_DESIGN=没有可用的报表设计对象。

birt.viewer.generalException.MULTIPLE_EXCEPTIONS=出现多个异常。

###############################################################################
# Report service exception
###############################################################################
birt.viewer.reportServiceException.EXTRACT_DATA_NO_DOCUMENT=没有可供提取数据的文档文件。

birt.viewer.reportServiceException.EXTRACT_DATA_NO_RESULT_SET=没有可供提取数据的结果集。

birt.viewer.reportServiceException.INVALID_TOC=无效 TOC 查询。

birt.viewer.reportServiceException.INVALID_PARAMETER=无效参数: {0}，因此它未定义。

birt.viewer.reportServiceException.STARTUP_REPORTENGINE_ERROR=尝试启动报表引擎时出现致命错误。

birt.viewer.reportServiceException.INVALID_EXTRACTFORMAT=数据提取格式无效或未指定。

birt.viewer.reportServiceException.INVALID_EXTRACTEXTENSION=无效的数据提取扩展 ID。
###############################################################################
# Birt action handler exception
###############################################################################
birt.viewer.actionException.NO_REPORT_DOCUMENT=报表文档实例为空。

birt.viewer.actionException.INVALID_BOOKMARK=书签: {0} 无效。请检查并重置链接。

birt.viewer.actionException.INVALID_PAGE_NUMBER=无效页码第 {0} 页，共 {1} 页。

birt.viewer.actionException.PAGE_NUMBER_PARSE_ERROR=页码: {0} 无效。

birt.viewer.actionException.INVALID_ID_FORMAT=无效 id 格式。Id={0}。

birt.viewer.actionException.DOCUMENT_FILE_NO_EXIST=会话超时或没有可用的文档文件。

###############################################################################
# Birt soap bingding impl exception
###############################################################################
birt.viewer.soapBindingException.NO_HANDLER_FOR_TARGET=无法为此目标找到处理程序。目标: {0}。

###############################################################################
# Component processor exception
###############################################################################
birt.viewer.componentProcessorException.MISSING_OPERATOR=错误: 缺少运算符!!!

###############################################################################
# Exception dialog
###############################################################################
birt.viewer.exceptionDialog.stackTrace=堆栈跟踪:

birt.viewer.exceptionDialog.showStackTrace=显示异常堆栈跟踪

birt.viewer.exceptionDialog.hideStackTrace=隐藏异常堆栈跟踪

###############################################################################
# Birt Viewer JSP Taglib
###############################################################################
birt.viewer.taglib.NO_ATTR_ID=必须指定属性 ID。

birt.viewer.taglib.INVALID_ATTR_ID=属性 ID 包含无效字符。

birt.viewer.taglib.ATTR_ID_DUPLICATE=属性 ID 必须唯一。

birt.viewer.taglib.PARAM_NAME_DUPLICATE=无法复制参数名称。

birt.viewer.taglib.NO_REPORT_SOURCE=应指定报表设计或文档文件。

birt.viewer.taglib.NO_REPORT_DOCUMENT=reportlet 需要报表文档文件。

birt.viewer.taglib.NO_REQUESTER_NAME=参数页标记的 "name" 属性是必需的。

###############################################################################
# Birt Viewer Message
###############################################################################
birt.viewer.message.document.successful=报表文档文件已成功生成。

###############################################################################
# Birt Viewer General Exceptions
###############################################################################
birt.viewer.exception.maybe_disabled_cookies=这可能是由客户端上禁用的 Cookie 引起的。
