#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension
invalid.function.name=関数名が無効です。

invalid.number.of.argument=関数に対して引数の数が無効です。

invalid.type.of.argument=関数に対して引数の型が無効です。

error.arguement.cannot.empty=関数の引数を空白にすることはできません。

error.incorrect.number.function.fixedArgument=引数の数が正しくありません。引数の数は <{0}> を指定することが必要ですが、<{1}> が指定されました。

error.incorrect.number.function.variableArgument=引数の数が正しくありません。引数の数は <{0}> 以上を指定することが必要ですが、<{1}> が指定されました。

error.argument.number.outofValidRange=引数の数が正しくありません。引数の数は <{0}> 以下または、<{1}> 以上を指定することが必要ですが、<{2}> が指定されました。

error.incorrect.type.function.argument=引数の型が正しくありません。

error.BirtMath.ceiling.significance.notApplied=指定した重要度 "{0}" を数 "{1}" に適用できません。

error.BirtMath.mod.invalid.divisor=除数は 0 にすることができません。

error.BirtDateTime.cannotBeNull.DateValue=日付の値は null にすることができません。

error.BirtStr.left.invalidArgument=引数 n の値 "{0}" は、スクリプト関数に対して無効です。

error.BirtStr.right.invalidArgument=引数 n の値 "{0}" は、スクリプト関数に対して無効です。

error.BirtStr.indexOf.invalidArgument=開始引数の値 "{0}" は、スクリプト関数に対して無効です。

error.BirtStr.search.invalidArgument=開始引数の値 "{0}" は、スクリプト関数に対して無効です。

error.BirtDuration.literal.invalidArgument=スクリプト関数に無効な引数の値 "{0}" が指定されています。

