#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension
invalid.function.name=Nom de fonction non valide :

invalid.number.of.argument=Nombre d'arguments non valide pour la fonction :

invalid.type.of.argument=Type d'argument non valide pour la fonction :

error.arguement.cannot.empty=L'argument pour la fonction ne peut pas être vierge.

error.incorrect.number.function.fixedArgument=Nombre d'argument(s) incorrect. Le nombre d'argument(s) était de <{1}> alors qu'il aurait dû être de <{0}>.

error.incorrect.number.function.variableArgument=Nombre d'argument(s) incorrect. Le nombre d'argument(s) était de <{1}> alors qu'il aurait dû être inférieur à <{0}>.

error.argument.number.outofValidRange=Nombre d'argument(s) incorrect. Le nombre d'argument(s) était de <{2}> alors qu'il aurait dû être supérieur à <{0}> ou inférieur à <{1}>.

error.incorrect.type.function.argument=Type d'argument incorrect.

error.BirtMath.ceiling.significance.notApplied=La signification spécifiée "{0}" ne peut pas être appliquée au nombre "{1}".

error.BirtMath.mod.invalid.divisor=Le diviseur ne peut pas être 0.

error.BirtDateTime.cannotBeNull.DateValue=La valeur de date ne peut pas être nulle.

error.BirtStr.left.invalidArgument=La valeur "{0}" de l'argument n est incorrecte pour la fonction de script.

error.BirtStr.right.invalidArgument=La valeur "{0}" de l'argument n est incorrecte pour la fonction de script.

error.BirtStr.indexOf.invalidArgument=La valeur "{0}" du début de l'argument est incorrecte pour la fonction de script.

error.BirtStr.search.invalidArgument=La valeur "{0}" du début de l'argument est incorrecte pour la fonction de script.

error.BirtDuration.literal.invalidArgument=La valeur "{0}" de l'argument est incorrecte pour la fonction de script.

