#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension

invalid.function.name=잘못된 함수 이름: 
invalid.number.of.argument=함수에 대한 잘못된 인수 개수:
invalid.type.of.argument=함수에 대한 잘못된 인수 형식:
