#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension
invalid.function.name=无效的函数名称:

invalid.number.of.argument=无效的函数参数数:

invalid.type.of.argument=无效的函数参数类型:

error.arguement.cannot.empty=函数参数不能为空。

error.incorrect.number.function.fixedArgument=参数数量不正确。参数的数量应该是 <{0}>，但却是 <{1}>。

error.incorrect.number.function.variableArgument=参数数量不正确。参数的数量不应该超过 <{0}>，但却是 <{1}>。

error.argument.number.outofValidRange=参数数量不正确。参数的数量不应该小于 <{0}> 或超过 <{1}>，但它却是 <{2}>。

error.incorrect.type.function.argument=参数类型不正确。

error.BirtMath.ceiling.significance.notApplied=给定的有效值“{0}”无法应用到数值“{1}”。

error.BirtMath.mod.invalid.divisor=除数不能为 0。

error.BirtDateTime.cannotBeNull.DateValue=日期值不能为空!

error.BirtStr.left.invalidArgument=参数 n 的值“{0}”对于脚本函数无效。

error.BirtStr.right.invalidArgument=参数 n 的值“{0}”对于脚本函数无效。

error.BirtStr.indexOf.invalidArgument=参数开始的值“{0}”对于脚本函数无效。

error.BirtStr.search.invalidArgument=参数开始的值“{0}”对于脚本函数无效。

error.BirtDuration.literal.invalidArgument=参数的值“{0}”对于脚本函数无效。

