#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension
invalid.function.name=Nombre de función no válido:

invalid.number.of.argument=Número de argumentos para la función no válido:

invalid.type.of.argument=Tipo de argumento para la función no válido:

error.arguement.cannot.empty=El argumento de la función no puede estar vacío.

error.incorrect.number.function.fixedArgument=Número incorrecto de argumentos. El número de argumentos <{1}> debe ser <{0}>.

error.incorrect.number.function.variableArgument=Número incorrecto de argumentos. El número de argumentos no debe ser superior a <{0}> pero era de <{1}>.

error.argument.number.outofValidRange=Número incorrecto de argumentos. El número de argumentos no puede ser inferior a <{0}> ni superior a <{1}> pero era de <{2}>.

error.incorrect.type.function.argument=El tipo de argumento es incorrecto.

error.BirtMath.ceiling.significance.notApplied=No se puede aplicar el valor "{0}" dado al número "{1}".

error.BirtMath.mod.invalid.divisor=El divisor no puede ser 0.

error.BirtDateTime.cannotBeNull.DateValue=El valor de fecha no puede ser nulo

error.BirtStr.left.invalidArgument=El valor "{0}" del n de argumento no es válido por la función de script.

error.BirtStr.right.invalidArgument=El valor "{0}" del n de argumento no es válido por la función de script.

error.BirtStr.indexOf.invalidArgument=El valor "{0}" del inicio de argumento no es válido por la función de script.

error.BirtStr.search.invalidArgument=El valor "{0}" del inicio de argumento no es válido por la función de script.

error.BirtDuration.literal.invalidArgument=El valor "{0}" del argumento no es válido por la función de script.

