#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension
invalid.function.name=Ungültiger Funktionsname:

invalid.number.of.argument=Ungültige Argumentanzahl für Funktion:

invalid.type.of.argument=Ungültiger Argumenttyp für Funktion:

error.arguement.cannot.empty=Das Funktionsargument darf nicht leer sein.

error.incorrect.number.function.fixedArgument=Ungültige Argumentanzahl. Erwartete Anzahl: <{0}>, tatsächliche Anzahl: <{1}>.

error.incorrect.number.function.variableArgument=Ungültige Argumentanzahl. Erwartete Anzahl: maximal <{0}>, tatsächliche Anzahl: <{1}>.

error.argument.number.outofValidRange=Ungültige Argumentanzahl. Erwartete Anzahl: mindestens <{0}> und maximal <{1}>, tatsächliche Anzahl: <{2}>.

error.incorrect.type.function.argument=Falscher Argumenttyp.

error.BirtMath.ceiling.significance.notApplied=Angegebene Signifikanz '{0}' kann nicht auf Zahl '{1}' angewendet werden.

error.BirtMath.mod.invalid.divisor=Divisor darf nicht 0 sein.

error.BirtDateTime.cannotBeNull.DateValue=Datumswert darf nicht Null sein.

error.BirtStr.left.invalidArgument=Wert '{0}' von Argument n ist für Skriptfunktion ungültig.

error.BirtStr.right.invalidArgument=Wert '{0}' von Argument n ist für Skriptfunktion ungültig.

error.BirtStr.indexOf.invalidArgument=Wert '{0}' von Argumentanfang ist für Skriptfunktion ungültig.

error.BirtStr.search.invalidArgument=Wert '{0}' von Argumentanfang ist für Skriptfunktion ungültig.

error.BirtDuration.literal.invalidArgument=Wert '{0}' von Argument ist für Skriptfunktion ungültig.

