#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Exception messages for the BIRT Script Function Extension

invalid.function.name=ŠÖ”–¼‚ª–³Œø‚Å‚·B 
invalid.number.of.argument=ŠÖ”‚É‘Î‚µ‚Äˆø”‚Ì”‚ª–³Œø‚Å‚·B
invalid.type.of.argument=ŠÖ”‚É‘Î‚µ‚Äˆø”‚ÌŒ^‚ª–³Œø‚Å‚·B
