Series=Série

ValueYSeries=Série verticale de valeurs

CategorySeries=Série de catégories

ValueSeries=Série de valeurs

Needle=Aiguille

ChartArea=Zone graphique

Axis=Axe

XAxis=Axe horizontal

YAxis=Axe vertical

ZAxis=Axe de profondeur

Plot=Tracé

Legend=Légende

Title=Titre

preference.chart.fieldassist=Assistant de champ

preference.chart.fieldassist.contentassist=Assistant de contenu