###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=Somme

Average.displayName=Moyenne

Count.displayName=Nombre

DistinctCount.displayName=Nombre distinct

First.displayName=Premier

Last.displayName=Dernier

Min.displayName=Minimum

Max.displayName=Maximum

WeightedAverage.displayName=Moyenne pondérée

Median.displayName=Médiane

Mode.displayName=Mode

STDDEV.displayName=STDDEV

Variance.displayName=Variance

Irr.displayName=Irr

Mirr.displayName=Mirr

NPV.displayName=NPV

Percentile.displayName=Centile

Quartile.displayName=Quartile
#Running aggregates.
MovingAverage.displayName=Moyenne mobile

RunningSum.displayName=Cumul

RunningNPV.displayName=VAN

Rank.displayName=Titre

Top.displayName=Is-Top-N

TopPercent.displayName=Is-Top-N-Percent

Bottom.displayName=Is-Bottom-N

BottomPercent.displayName=Is-Bottom-N-Percent

PercentRank.displayName=Rang de pourcentage

PercentSum.displayName=Somme de pourcentage

RunningCount.displayName=Nombre en cours