###############################################################################
# Copyright (c) 2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

Sum.displayName=Suma
Average.displayName=Media
Count.displayName=Recuento
DistinctCount.displayName=Recuento diferenciado
First.displayName=Primero
Last.displayName=Último
Min.displayName=Mínimo
Max.displayName=Máximo
