###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=합

Average.displayName=평균

Count.displayName=카운트

DistinctCount.displayName=고유 카운트

First.displayName=첫째

Last.displayName=마지막

Min.displayName=최소값

Max.displayName=최대값

WeightedAverage.displayName=가중 평균

Median.displayName=중앙값

Mode.displayName=최빈값

STDDEV.displayName=STDDEV

Variance.displayName=분산

Irr.displayName=IRR

Mirr.displayName=MIRR

NPV.displayName=NPV

Percentile.displayName=백분위수

Quartile.displayName=사분위수
#Running aggregates.
MovingAverage.displayName=이동 평균

RunningSum.displayName=누적 합계

RunningNPV.displayName=누적 NPV

Rank.displayName=등급

Top.displayName=상위 N

TopPercent.displayName=상위 N 백분율

Bottom.displayName=하위 N

BottomPercent.displayName=하위 N 백분율

PercentRank.displayName=백분율 등급

PercentSum.displayName=백분율 합계

RunningCount.displayName=누적 카운트