###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=合計

Average.displayName=平均

Count.displayName=カウント

DistinctCount.displayName=個別のカウント

First.displayName=最初

Last.displayName=最後

Min.displayName=最小

Max.displayName=最大

WeightedAverage.displayName=加重平均

Median.displayName=中央値

Mode.displayName=モード

STDDEV.displayName=STDDEV

Variance.displayName=分散

Irr.displayName=Irr

Mirr.displayName=Mirr

NPV.displayName=NPV

Percentile.displayName=百分位

Quartile.displayName=四分位数
#Running aggregates.
MovingAverage.displayName=移動平均

RunningSum.displayName=累計

RunningNPV.displayName=累積 NPV

Rank.displayName=順位

Top.displayName=Is-Top-N

TopPercent.displayName=Is-Top-N-Percent

Bottom.displayName=Is-Bottom-N

BottomPercent.displayName=Is-Bottom-N-Percent

PercentRank.displayName=割合 (%)

PercentSum.displayName=割合 (合計)

RunningCount.displayName=ランニングカウント