###############################################################################
# Copyright (c) 2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

Sum.displayName=求和
Average.displayName=平均值
Count.displayName=计数
DistinctCount.displayName=特异计数
First.displayName=第一
Last.displayName=最后
Min.displayName=最小值
Max.displayName=最大值
