###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=Summe

Average.displayName=Durchschnitt

Count.displayName=Anzahl

DistinctCount.displayName=Distinct-Anzahl

First.displayName=Erste

Last.displayName=Letzte

Min.displayName=Minimum

Max.displayName=Maximum

WeightedAverage.displayName=Gewichteter Durchschnitt

Median.displayName=Median

Mode.displayName=Modus

STDDEV.displayName=STDDEV

Variance.displayName=Abweichung

Irr.displayName=Irr

Mirr.displayName=Mirr

NPV.displayName=NPV

Percentile.displayName=Perzentil

Quartile.displayName=Quartil
#Running aggregates.
MovingAverage.displayName=Bewegungsdurchschnitt

RunningSum.displayName=Laufende Summe

RunningNPV.displayName=Running-NPV

Rank.displayName=Rank

Top.displayName=Is-Top-N

TopPercent.displayName=Is-Top-N-Percent

Bottom.displayName=Is-Bottom-N

BottomPercent.displayName=Is-Bottom-N-Percent

PercentRank.displayName=Prozent-Rang

PercentSum.displayName=Prozent-Summe

RunningCount.displayName=Laufende Anzahl