###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=求和

Average.displayName=平均值

Count.displayName=计数

DistinctCount.displayName=特异计数

First.displayName=第一

Last.displayName=最后

Min.displayName=最小值

Max.displayName=最大值

WeightedAverage.displayName=加权平均

Median.displayName=中位数

Mode.displayName=众数

STDDEV.displayName=STDDEV

Variance.displayName=方差

Irr.displayName=Irr

Mirr.displayName=Mirr

NPV.displayName=NPV

Percentile.displayName=百分位

Quartile.displayName=四分位数
#Running aggregates.
MovingAverage.displayName=移动平均

RunningSum.displayName=连续总计

RunningNPV.displayName=连续 NPV

Rank.displayName=等级

Top.displayName=前 N 个

TopPercent.displayName=前 N%

Bottom.displayName=后 N 个

BottomPercent.displayName=后 N%

PercentRank.displayName=百分比等级

PercentSum.displayName=百分比总计

RunningCount.displayName=连续计数