###############################################################################
# Copyright (c) 2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

Sum.displayName=合計
Average.displayName=平均
Count.displayName=カウント
DistinctCount.displayName=個別のカウント
First.displayName=最初
Last.displayName=最後
Min.displayName=最小
Max.displayName=最大
