###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=Suma

Average.displayName=Media

Count.displayName=Recuento

DistinctCount.displayName=Recuento diferenciado

First.displayName=Primero

Last.displayName=Último

Min.displayName=Mínimo

Max.displayName=Máximo

WeightedAverage.displayName=Media ponderada

Median.displayName=Mediana

Mode.displayName=Modo

STDDEV.displayName=STDDEV

Variance.displayName=Varianza

Irr.displayName=Irr

Mirr.displayName=Mirr

NPV.displayName=NPV

Percentile.displayName=Percentil

Quartile.displayName=Cuartil
#Running aggregates.
MovingAverage.displayName=Media de traslado

RunningSum.displayName=Suma en ejecución

RunningNPV.displayName=NPV en ejecución

Rank.displayName=Rango

Top.displayName=Is-Top-N

TopPercent.displayName=Is-Top-N-Percent

Bottom.displayName=Is-Bottom-N

BottomPercent.displayName=Is-Bottom-N-Percent

PercentRank.displayName=Rango de porcentaje

PercentSum.displayName=Suma de porcentaje

RunningCount.displayName=Recuento en ejecución