RadarSeriesImpl.displayName=Radardatenreihe

RadarChart.Txt.DefaultRadarChartTitle=Radardiagrammtitel

RadarChart.Txt.DisplayName=Radar

RadarChart.SubType.Standard=Standardradardiagramm

RadarChart.SubType.Spider=Netzradardiagramm

RadarChart.SubType.Bullseye=Punktradardiagramm

RadarChart.Tooltip.InputExpression=Geben Sie einen Ausdruck ein, der für jedes Objekt als Legendentext angezeigt wird.

RadarChart.Txt.HelpText=Radardiagramme zeigen den aktuellen Datenwert einer bestimmten Messgröße an. Die verschiedenfarbigen Abschnitte stellen die Bereiche der Messgrößenwerte dar. Nadeln sind mit Tachometern verknüpft und zeigen deren Wert an.

RadarChart.Txt.Description=Standardradardiagramme enthalten ein zirkuläres Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.

RadarChart.Txt.SpiderDescription=Netzradardiagramme enthalten ein polygonales Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.

RadarChart.Txt.BullseyeDescription=Punktradardiagramme enthalten ein zirkuläres, gefülltes Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.

RadarSeriesAttributeComposite.Lbl.Radius=Radi&us:

RadarSeriesAttributeComposite.Lbl.StartAngle=&Startwinkel:

RadarSeriesAttributeComposite.Lbl.StopAngle=Endwink&el:

RadarSeriesAttributeSheetImpl.Lbl.Type=Geben Sie Folgendes ein:

RadarSeriesAttributeSheetImpl.Lbl.Fill=Füllung:

RadarSeriesAttributeComposite.Lbl.DialTicks=&Häkchen

RadarSeriesAttributeComposite.Lbl.DialScale=S&kalierung

RadarBaseSeriesComponent.Label.CategoryDefinition=&Kategoriedefinition:

RadarSeriesAttributeComposite.Lbl.ShowWeb=&Webbeschriftungen anzeigen

RadarSeriesAttributeComposite.Lbl.ShowCat=Kategoriebes&chriftungen anzeigen

RadarSeriesAttributeComposite.Exception.IllegalArgument=Datenreihe vom Typ {0} ist ein ungültiges Argument für RadarSeriesAttributeComposite.

RadarSeriesAttributeComposite.Lbl.LinePalette=&Palette für Datenreihe als Linienfarbe verwenden

RadarSeriesAttributeComposite.Lbl.FillPoly=Poly&gons füllen

RadarSeriesAttributeComposite.Lbl.ConnectPoints=Datensatzendpunkte verbinden (polygonal)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=&Linien als Kurven anzeigen

RadarSeriesMarkerSheet.Label.Markers=&Markierung

RadarSeriesMarkerSheet.GroupLabel.Markers=Markierung

RadarSeriesMarkerSheet.Label.Web=Konfiguration der Radarlinie

RadarSeriesMarkerSheet.Label.Series=Reihenlinienkonfiguration

Radar.Composite.Label.ScaleCount.MinMaxWarning=Anzahl der Schritte muss im Bereich { 0}?{ 1 } liegen!

Radar.Composite.Label.ScaleCount=A&nzahl der Schritte

Radar.Composite.Label.ScaleCountToolTip=Anzahl Skalenschritte zum Erstellen im Diagramm

Radar.Composite.Label.bullsEye=Punktfarben als transparent festlegen

Format.Button.Web.Label=Webbeschri&ftungen formatieren

Format.Button.Cat.Label=Kategoriebeschri&ftungen formatieren

WebLabel.Tooltip.FormatSpecifier=Webbeschriftungen formatieren

CatLabel.Tooltip.FormatSpecifier=Kategoriebeschriftungen formatieren

RadarSeriesMarkerSheet.Label.WebLabel=Webbeschriftungen konfigurieren

RadarSeriesMarkerSheet.Label.CatLabel=Kategoriebeschriftungen konfigurieren

RadarSeriesUIProvider..Title.RadarLine=Radarlinie

RadarSeriesUIProvider.Label.CategoryLabels=Kate&goriebeschriftungen

RadarSeriesUIProvider.Label.RadarLine=Ra&darlinie

RadarSeriesUIProvider.Label.ValueDefinition=Radarwertdefinition:

RadarSeriesUIProvider.Label.WebLabels=&Webbeschriftungen

RadarSeriesUIProvider.Title.CategoryLabels=Kategoriebeschriftungen

RadarSeriesUIProvider.Title.WebLabels=Webbeschriftungen

Radar.Composite.Label.ScaleAuto=Automatisch skalieren

Radar.Composite.Label.ScaleAutoTooltip=Chart wird automatisch skaliert

Radar.Composite.Label.ScaleMax=Maximalwert für Skalierung

Radar.Composite.Label.ScaleMaxToolTip=Maximalwert für Skalierung des Charts festlegen

Radar.Composite.Label.ScaleMin=Minimalwert für Skalierung

Radar.Composite.Label.ScaleMinToolTip=Minimalwert für Skalierung des Charts festlegen

Radar.Composite.Label.PlotPercentageToolTip=Prozentsatz der Zeichnungsfläche, der für den Radar erforderlich ist

ItemLabel.Visible=Sichtbar:

ItemLabel.Auto=Automatisch

ItemLabel.True=True

ItemLabel.False=False

ItemLabel.Show=Anzeigen

ItemLabel.Hide=Ausblenden

ItemLabel.Enable=Aktivieren

ItemLabel.Disable=Deaktivieren