RadarSeriesImpl.displayName=방사형 계열

RadarChart.Txt.DefaultRadarChartTitle=방사형 차트 제목

RadarChart.Txt.DisplayName=방사형

RadarChart.SubType.Standard=표준 방사형 차트

RadarChart.SubType.Spider=스파이더 방사형 차트

RadarChart.SubType.Bullseye=동그라미 방사형 차트

RadarChart.Tooltip.InputExpression=각 항목의 범례 텍스트로 표시되는 식을 입력합니다.

RadarChart.Txt.HelpText=방사형 차트에는 특정 측정에 대한 현재 데이터 값이 표시됩니다. 다른 색상의 영역은 측정 값 범위를 나타냅니다. 바늘은 다이얼과 연결되며, 다이얼 값을 표시합니다.

RadarChart.Txt.Description=표준 방사형 차트에는 하나 이상의 다각형/선 계열과 겹치는 원형 눈금이 포함됩니다.

RadarChart.Txt.SpiderDescription=스파이더 방사형 차트에는 하나 이상의 다각형/선 계열과 겹치는 다각형 눈금이 포함됩니다.

RadarChart.Txt.BullseyeDescription=동그라미 방사형 차트에는 하나 이상의 다각형/선 계열과 겹치는 채워진 원형 눈금이 포함됩니다.

RadarSeriesAttributeComposite.Lbl.Radius=반경(&U):

RadarSeriesAttributeComposite.Lbl.StartAngle=시작 각도(&G):

RadarSeriesAttributeComposite.Lbl.StopAngle=중지 각도(&E):

RadarSeriesAttributeSheetImpl.Lbl.Type=유형:

RadarSeriesAttributeSheetImpl.Lbl.Fill=채우기:

RadarSeriesAttributeComposite.Lbl.DialTicks=눈금(&T)

RadarSeriesAttributeComposite.Lbl.DialScale=배율(&C)

RadarBaseSeriesComponent.Label.CategoryDefinition=범주 정의(&C):

RadarSeriesAttributeComposite.Lbl.ShowWeb=웹 레이블 표시(&W)

RadarSeriesAttributeComposite.Lbl.ShowCat=범주 레이블 표시(&C)

RadarSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 RadarSeriesAttributeComposite에 대한 잘못된 인수입니다.

RadarSeriesAttributeComposite.Lbl.LinePalette=선 색으로 계열 색상표 사용(&P)

RadarSeriesAttributeComposite.Lbl.FillPoly=다각형 채우기(&G)

RadarSeriesAttributeComposite.Lbl.ConnectPoints=데이터 집합 끝점 연결(다각형)(&C)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=선을 곡선으로 표시(&H)

RadarSeriesMarkerSheet.Label.Markers=마커(&M)

RadarSeriesMarkerSheet.GroupLabel.Markers=마커

RadarSeriesMarkerSheet.Label.Web=방사형 선 구성

RadarSeriesMarkerSheet.Label.Series=계열 선 구성

Radar.Composite.Label.ScaleCount.MinMaxWarning=단계 수는 {0} - {1} 사이여야 합니다.

Radar.Composite.Label.ScaleCount=단계 수(&N)

Radar.Composite.Label.ScaleCountToolTip=차트에서 만들 숫자 배율 단계

Radar.Composite.Label.bullsEye=동그라미 색을 반투명으로 설정

Format.Button.Web.Label=웹 레이블 형식(&F)

Format.Button.Cat.Label=범주 레이블 형식(&F)

WebLabel.Tooltip.FormatSpecifier=웹 레이블 형식

CatLabel.Tooltip.FormatSpecifier=범주 레이블 형식

RadarSeriesMarkerSheet.Label.WebLabel=웹 레이블 구성

RadarSeriesMarkerSheet.Label.CatLabel=범주 레이블 구성

RadarSeriesUIProvider..Title.RadarLine=방사형 선

RadarSeriesUIProvider.Label.CategoryLabels=범주 레이블(&G)

RadarSeriesUIProvider.Label.RadarLine=방사형 선(&D)

RadarSeriesUIProvider.Label.ValueDefinition=방사형 값 정의:

RadarSeriesUIProvider.Label.WebLabels=웹 레이블(&W)

RadarSeriesUIProvider.Title.CategoryLabels=범주 레이블

RadarSeriesUIProvider.Title.WebLabels=웹 레이블

Radar.Composite.Label.ScaleAuto=자동 배율

Radar.Composite.Label.ScaleAutoTooltip=차트의 배율은 자동으로 조정됩니다.

Radar.Composite.Label.ScaleMax=최대 배율

Radar.Composite.Label.ScaleMaxToolTip=차트 최대 배율을 설정합니다.

Radar.Composite.Label.ScaleMin=최소 배율

Radar.Composite.Label.ScaleMinToolTip=차트 최소 배율을 설정합니다.

Radar.Composite.Label.PlotPercentageToolTip=방사형에서 사용할 플롯 영역의 백분율

ItemLabel.Visible=표시:

ItemLabel.Auto=자동

ItemLabel.True=참

ItemLabel.False=거짓

ItemLabel.Show=표시

ItemLabel.Hide=숨기기

ItemLabel.Enable=사용

ItemLabel.Disable=사용 안 함