RadarSeriesImpl.displayName=レーダー系列

RadarChart.Txt.DefaultRadarChartTitle=レーダーチャートのタイトル

RadarChart.Txt.DisplayName=レーダー

RadarChart.SubType.Standard=標準レーダーチャート

RadarChart.SubType.Spider=スパイダーレーダーチャート

RadarChart.SubType.Bullseye=ブルズアイレーダーチャート

RadarChart.Tooltip.InputExpression=各項目の凡例として表示されている式を入力してください。

RadarChart.Txt.HelpText=レーダーチャート。データの測定値を示します。 測定値の範囲に応じて領域を色分けします。 レーダー上のダイアルを指す針によって値が示されます。

RadarChart.Txt.Description=標準レーダーチャート。円形のグリッド上に多角形と線を重ね合わせて表示します。

RadarChart.Txt.SpiderDescription=スパイダーレーダーチャート。多角形のグリッド上に多角形と線を重ね合わせて表示します。

RadarChart.Txt.BullseyeDescription=ブルズアイレーダーチャート。円形の塗りつぶされたグリッド上に多角形と線を重ね合わせて表示します。

RadarSeriesAttributeComposite.Lbl.Radius=半径(&U):

RadarSeriesAttributeComposite.Lbl.StartAngle=始点の角度(&G) :

RadarSeriesAttributeComposite.Lbl.StopAngle=終端の角度(&E) :

RadarSeriesAttributeSheetImpl.Lbl.Type=型 :

RadarSeriesAttributeSheetImpl.Lbl.Fill=塗りつぶし :

RadarSeriesAttributeComposite.Lbl.DialTicks=目盛を付ける(&T)

RadarSeriesAttributeComposite.Lbl.DialScale=スケール(&C)

RadarBaseSeriesComponent.Label.CategoryDefinition=カテゴリの定義(&C) :

RadarSeriesAttributeComposite.Lbl.ShowWeb=Web ラベルを表示(&W)

RadarSeriesAttributeComposite.Lbl.ShowCat=カテゴリラベルを表示(&C)

RadarSeriesAttributeComposite.Exception.IllegalArgument={0} 型の系列は、RadarSeriesAttributeComposite の引数としては使用できません。

RadarSeriesAttributeComposite.Lbl.LinePalette=系列パレットを線の色として使用する(&P)

RadarSeriesAttributeComposite.Lbl.FillPoly=多角形の塗りつぶし(&G)

RadarSeriesAttributeComposite.Lbl.ConnectPoints=データセットエンドポイントの接続（多角形）(&C)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=線を曲線で表示(&H)

RadarSeriesMarkerSheet.Label.Markers=マーカ(&M)

RadarSeriesMarkerSheet.GroupLabel.Markers=マーカ

RadarSeriesMarkerSheet.Label.Web=レーダーの線の設定

RadarSeriesMarkerSheet.Label.Series=系列の線の設定

Radar.Composite.Label.ScaleCount.MinMaxWarning=ステップ数は {0} ? {1} 以内である必要があります!

Radar.Composite.Label.ScaleCount=ステップ数(&N)

Radar.Composite.Label.ScaleCountToolTip=グラフで使用する目盛を設定

Radar.Composite.Label.bullsEye=ブルズアイの色を半透明に設定

Format.Button.Web.Label=Web ラベルの書式設定(&F)

Format.Button.Cat.Label=カテゴリラベルの書式設定(&F)

WebLabel.Tooltip.FormatSpecifier=Web ラベルの書式設定

CatLabel.Tooltip.FormatSpecifier=カテゴリラベルの書式設定

RadarSeriesMarkerSheet.Label.WebLabel=Web ラベルの設定

RadarSeriesMarkerSheet.Label.CatLabel=カテゴリラベルの設定

RadarSeriesUIProvider..Title.RadarLine=レーダーの線

RadarSeriesUIProvider.Label.CategoryLabels=カテゴリラベル(&G)

RadarSeriesUIProvider.Label.RadarLine=レーダーの線(&D)

RadarSeriesUIProvider.Label.ValueDefinition=レーダー値の定義 :

RadarSeriesUIProvider.Label.WebLabels=Web ラベル(&W)

RadarSeriesUIProvider.Title.CategoryLabels=カテゴリラベル

RadarSeriesUIProvider.Title.WebLabels=Web ラベル

Radar.Composite.Label.ScaleAuto=自動スケール

Radar.Composite.Label.ScaleAutoTooltip=グラフのサイズは自動的に変更されます

Radar.Composite.Label.ScaleMax=スケールの最大値

Radar.Composite.Label.ScaleMaxToolTip=グラフのサイズを最大に設定

Radar.Composite.Label.ScaleMin=スケールの最小値

Radar.Composite.Label.ScaleMinToolTip=グラフのサイズを最小に設定

Radar.Composite.Label.PlotPercentageToolTip=レーダーチャートで使用するプロット領域の割合

ItemLabel.Visible=可視:

ItemLabel.Auto=自動

ItemLabel.True=True

ItemLabel.False=False

ItemLabel.Show=表示

ItemLabel.Hide=非表示

ItemLabel.Enable=有効化

ItemLabel.Disable=無効化