RadarSeriesImpl.displayName=Serie radial

RadarChart.Txt.DefaultRadarChartTitle=Título de diagrama radial

RadarChart.Txt.DisplayName=Radial

RadarChart.SubType.Standard=Diagrama radial estándar

RadarChart.SubType.Spider=Diagrama radial de araña

RadarChart.SubType.Bullseye=Diagrama radial de ojo de buey

RadarChart.Tooltip.InputExpression=Introduzca una expresión que se muestre como texto de leyenda para cada elemento

RadarChart.Txt.HelpText=Los diagramas radiales muestran el valor de los datos actuales de una medida. Las regiones con colores diferentes representan los intervalos de los valores de medida. Un indicador asociado a un cuadrante muestra su valor.

RadarChart.Txt.Description=Los diagramas radiales estándar contienen una cuadrícula circular a la que se superponen series de líneas o polígonos

RadarChart.Txt.SpiderDescription=Los diagramas radiales de araña contienen una cuadrícula de polígonos a la que se superponen series de líneas o polígonos

RadarChart.Txt.BullseyeDescription=Los diagramas radiales de ojo de buey contienen una cuadrícula circular rellena a la que se superponen series de líneas o polígonos

RadarSeriesAttributeComposite.Lbl.Radius=Radi&o:

RadarSeriesAttributeComposite.Lbl.StartAngle=Án&gulo de inicio:

RadarSeriesAttributeComposite.Lbl.StopAngle=Áng&ulo de detención:

RadarSeriesAttributeSheetImpl.Lbl.Type=Tipo:

RadarSeriesAttributeSheetImpl.Lbl.Fill=Relleno:

RadarSeriesAttributeComposite.Lbl.DialTicks=&Marcas

RadarSeriesAttributeComposite.Lbl.DialScale=E&scala

RadarBaseSeriesComponent.Label.CategoryDefinition=Definición de &categoría:

RadarSeriesAttributeComposite.Lbl.ShowWeb=Mostrar etiquetas &Web

RadarSeriesAttributeComposite.Lbl.ShowCat=Mostrar etiquetas de &categoría

RadarSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para RadarSeriesAttributeComposite.

RadarSeriesAttributeComposite.Lbl.LinePalette=Usar &paleta de series como color de línea

RadarSeriesAttributeComposite.Lbl.FillPoly=Rellenar polí&gonos

RadarSeriesAttributeComposite.Lbl.ConnectPoints=&Conectar puntos finales de conjunto de datos (polígono)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=M&ostrar líneas como curvas

RadarSeriesMarkerSheet.Label.Markers=&Marcador

RadarSeriesMarkerSheet.GroupLabel.Markers=Marcador

RadarSeriesMarkerSheet.Label.Web=Configuración de línea radial

RadarSeriesMarkerSheet.Label.Series=Configuración de línea de serie

Radar.Composite.Label.ScaleCount.MinMaxWarning=Él número de pasos debe estar entre {0} - {1}!

Radar.Composite.Label.ScaleCount=&Número de pasos

Radar.Composite.Label.ScaleCountToolTip=Numero de pasos de escala con los que crear el diagrama

Radar.Composite.Label.bullsEye=Establecer los colores de ojo de buey como translúcidos

Format.Button.Web.Label=&Etiquetas Web de formato

Format.Button.Cat.Label=&Etiquetas de categoría de formato

WebLabel.Tooltip.FormatSpecifier=Etiquetas Web de formato

CatLabel.Tooltip.FormatSpecifier=Etiquetas de categoría de formato

RadarSeriesMarkerSheet.Label.WebLabel=Configurar etiquetas Web

RadarSeriesMarkerSheet.Label.CatLabel=Configurar etiquetas de categoría

RadarSeriesUIProvider..Title.RadarLine=Línea radial

RadarSeriesUIProvider.Label.CategoryLabels=Etiquetas de cate&goría

RadarSeriesUIProvider.Label.RadarLine=Línea ra&dial

RadarSeriesUIProvider.Label.ValueDefinition=Definición de valor radial:

RadarSeriesUIProvider.Label.WebLabels=Etiquetas &Web

RadarSeriesUIProvider.Title.CategoryLabels=Etiquetas de categoría

RadarSeriesUIProvider.Title.WebLabels=Etiquetas Web

Radar.Composite.Label.ScaleAuto=Escala automática

Radar.Composite.Label.ScaleAutoTooltip=La escala del diagrama se ajusta automáticamente

Radar.Composite.Label.ScaleMax=Máx. de escala

Radar.Composite.Label.ScaleMaxToolTip=Establecer el máximo de escala del diagrama

Radar.Composite.Label.ScaleMin=Mín. de escala

Radar.Composite.Label.ScaleMinToolTip=Establecer el mínimo de escala del diagrama

Radar.Composite.Label.PlotPercentageToolTip=Porcentaje de área de dibujo que consumirá el radial

ItemLabel.Visible=Visible:

ItemLabel.Auto=Automático

ItemLabel.True=True

ItemLabel.False=False

ItemLabel.Show=Mostrar

ItemLabel.Hide=Ocultar

ItemLabel.Enable=Activar

ItemLabel.Disable=Desactivar