RadarSeriesImpl.displayName=レーダ系列

RadarChart.Txt.DefaultRadarChartTitle=レーダグラフのタイトル
RadarChart.Txt.DisplayName=レーダ
RadarChart.SubType.Standard=標準レーダグラフ
RadarChart.SubType.Spider=スパイダーレーダグラフ
RadarChart.SubType.Bullseye=ブルズアイレーダグラフ

RadarChart.Tooltip.InputExpression=各項目の凡例として表示されている式を入力してください。
RadarChart.Txt.HelpText=レーダグラフ。データの測定値を示します。 測定値の範囲に応じて領域を色分けします。 レーダ上のダイアルを指す針によって値が示されます。
RadarChart.Txt.Description=標準レーダグラフ。円形のグリッド上に多角形と線を重ね合わせて表示します。
RadarChart.Txt.SpiderDescription=スパイダーレーダグラフ。多角形のグリッド上に多角形と線を重ね合わせて表示します。
RadarChart.Txt.BullseyeDescription=ブルズアイレーダグラフ。円形の塗りつぶされたグリッド上に多角形と線を重ね合わせて表示します。

RadarSeriesAttributeComposite.Lbl.Radius=半径(&U) :
RadarSeriesAttributeComposite.Lbl.StartAngle=始点の角度(&G) :
RadarSeriesAttributeComposite.Lbl.StopAngle=終端の角度(&E) :
RadarSeriesAttributeSheetImpl.Lbl.Type=型 :
RadarSeriesAttributeSheetImpl.Lbl.Fill=塗りつぶし :
RadarSeriesAttributeComposite.Lbl.DialTicks=目盛を付ける(&T)
RadarSeriesAttributeComposite.Lbl.DialScale=スケール(&C)
RadarBaseSeriesComponent.Label.CategoryDefinition=カテゴリの定義(&C) :
RadarSeriesAttributeComposite.Lbl.ShowWeb=Web / レーダラベルを表示(&W)
RadarSeriesAttributeComposite.Lbl.ShowCat=Show Web/Radar &Category Labels


RadarSeriesAttributeComposite.Exception.IllegalArgument={0} 型の系列は、RadarSeriesAttributeComposite の引数としては使用できません。
RadarSeriesAttributeComposite.Lbl.LinePalette=系列パレットを線の色として使用する(&P)
RadarSeriesAttributeComposite.Lbl.FillPoly=多角形の塗りつぶし(&G)
RadarSeriesAttributeComposite.Lbl.ConnectPoints=データセットエンドポイントの接続（多角形）(&C)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=線を曲線で表示(&H)

RadarSeriesMarkerSheet.Label.Markers=マーカ(&M)
RadarSeriesMarkerSheet.GroupLabel.Markers=マーカ

RadarSeriesMarkerSheet.Label.Web=Radar Line Configuration
RadarSeriesMarkerSheet.Label.Series=系列の線の設定

Radar.Composite.Label.ScaleCount=グラフの目盛(&N)
Radar.Composite.Label.ScaleCountToolTip=グラフで使用する目盛を設定
Radar.Composite.Label.bullsEye=ブルズアイの色を半透明に設定
Format.Button.Web.Label=Format Web Labels
Format.Button.Cat.Label=Format Category Labels
WebLabel.Tooltip.FormatSpecifier=Format Web Labels
CatLabel.Tooltip.FormatSpecifier=Format Category Labels
RadarSeriesMarkerSheet.Label.WebLabel=Configure Web Labels
RadarSeriesMarkerSheet.Label.CatLabel=Configure Category Labels
RadarSeriesUIProvider..Title.RadarLine=Radar Line
RadarSeriesUIProvider.Label.CategoryLabels=Cate&gory Labels
RadarSeriesUIProvider.Label.RadarLine=Ra&dar Line
RadarSeriesUIProvider.Label.WebLabels=&Web Labels
RadarSeriesUIProvider.Title.CategoryLabels=Category Labels
RadarSeriesUIProvider.Title.WebLabels=Web/Radar Labels

Radar.Composite.Label.ScaleAuto=Auto Scale
Radar.Composite.Label.ScaleAutoTooltip=Chart is Automatically Scaled
Radar.Composite.Label.ScaleMax=Scale Max
Radar.Composite.Label.ScaleMaxToolTip=Set the Chart Scale Maximum
Radar.Composite.Label.ScaleMin=Scale Min
Radar.Composite.Label.ScaleMinToolTip=Set the Chart Scale Minimum


Radar.Composite.Label.PlotPercentageToolTip=レーダグラフで使用するプロット領域の割合
