RadarSeriesImpl.displayName=Série en radar

RadarChart.Txt.DefaultRadarChartTitle=Titre du graphique en radar

RadarChart.Txt.DisplayName=Graphique en radar

RadarChart.SubType.Standard=Graphique en radar standard

RadarChart.SubType.Spider=Graphique en radar avec toile d'araignée

RadarChart.SubType.Bullseye=Graphique en radar avec cercles concentriques

RadarChart.Tooltip.InputExpression=Entrer une expression affichée comme texte de légende pour chaque élément

RadarChart.Txt.HelpText=Les graphiques en radar indiquent la valeur de données actuelle d'une mesure spécifique. Les zones de différentes couleurs représentent les plages de valeurs de mesure. Une aiguille est associée à un cadran et indique la valeur correspondante.

RadarChart.Txt.Description=Les graphiques en radar standard contiennent une grille circulaire superposée à un ou plusieurs polygones/lignes de série

RadarChart.Txt.SpiderDescription=Les graphiques en radar avec toile d'araignée contiennent une grille circulaire superposée à un ou plusieurs polygones/lignes de série

RadarChart.Txt.BullseyeDescription=Les graphiques en radar avec cercles concentriques contiennent une grille circulaire superposée à un ou plusieurs polygones/lignes de série

RadarSeriesAttributeComposite.Lbl.Radius=Ray&on :

RadarSeriesAttributeComposite.Lbl.StartAngle=An&gle de début :

RadarSeriesAttributeComposite.Lbl.StopAngle=An&gle de fin :

RadarSeriesAttributeSheetImpl.Lbl.Type=Type :

RadarSeriesAttributeSheetImpl.Lbl.Fill=Remplissage :

RadarSeriesAttributeComposite.Lbl.DialTicks=&Repères

RadarSeriesAttributeComposite.Lbl.DialScale=E&chelle :

RadarBaseSeriesComponent.Label.CategoryDefinition=Définition de &catégorie :

RadarSeriesAttributeComposite.Lbl.ShowWeb=Afficher les &étiquettes Web

RadarSeriesAttributeComposite.Lbl.ShowCat=Afficher les &étiquettes de catégorie

RadarSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour RadarSeriesAttributeComposite.

RadarSeriesAttributeComposite.Lbl.LinePalette=Utiliser la &palette de série pour la couleur de trait

RadarSeriesAttributeComposite.Lbl.FillPoly=Remplir les poly&gones

RadarSeriesAttributeComposite.Lbl.ConnectPoints=&Connecter les points finaux du jeu de données (polygone)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=A&fficher les lignes sous la forme de courbes

RadarSeriesMarkerSheet.Label.Markers=&Repère

RadarSeriesMarkerSheet.GroupLabel.Markers=Repère

RadarSeriesMarkerSheet.Label.Web=Configuration des lignes en radar

RadarSeriesMarkerSheet.Label.Series=Configuration des lignes de série

Radar.Composite.Label.ScaleCount.MinMaxWarning=Le nombre d'étapes doit être compris entre {0} et {1}.

Radar.Composite.Label.ScaleCount=&Nombre d'étapes

Radar.Composite.Label.ScaleCountToolTip=Numéroter les étapes (échelles) à partir desquelles créer le graphique

Radar.Composite.Label.bullsEye=Définir les couleurs des cercles concentriques sur Translucide

Format.Button.Web.Label=&Formater les étiquettes Web

Format.Button.Cat.Label=&Formater les étiquettes de catégorie

WebLabel.Tooltip.FormatSpecifier=Formater les étiquettes Web

CatLabel.Tooltip.FormatSpecifier=Formater les étiquettes de catégorie

RadarSeriesMarkerSheet.Label.WebLabel=Configurer les étiquettes Web

RadarSeriesMarkerSheet.Label.CatLabel=Configurer les étiquettes de catégorie

RadarSeriesUIProvider..Title.RadarLine=Ligne en radar

RadarSeriesUIProvider.Label.CategoryLabels=Etiquettes de caté&gorie

RadarSeriesUIProvider.Label.RadarLine=Ligne en ra&dar

RadarSeriesUIProvider.Label.ValueDefinition=Définition de la valeur de radar :

RadarSeriesUIProvider.Label.WebLabels=Etiquettes &Web

RadarSeriesUIProvider.Title.CategoryLabels=Etiquettes de catégorie

RadarSeriesUIProvider.Title.WebLabels=Etiquettes Web

Radar.Composite.Label.ScaleAuto=Echelle automatique

Radar.Composite.Label.ScaleAutoTooltip=L'échelle du graphique est automatiquement ajustée

Radar.Composite.Label.ScaleMax=Echelle maximale

Radar.Composite.Label.ScaleMaxToolTip=Définir l'échelle du graphique au maximum

Radar.Composite.Label.ScaleMin=Echelle minimale

Radar.Composite.Label.ScaleMinToolTip=Définir l'échelle du graphique au minimum

Radar.Composite.Label.PlotPercentageToolTip=Pourcentage de zone de tracé occupée par le graphique en radar

ItemLabel.Visible=Visible :

ItemLabel.Auto=Auto

ItemLabel.True=Vrai

ItemLabel.False=Faux

ItemLabel.Show=Afficher

ItemLabel.Hide=Masquer

ItemLabel.Enable=Activer

ItemLabel.Disable=Désactiver