###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS strings
#
plugin.name=Conception ODA de source de données BIRT POJO
newwizard.name=Source de données POJO BIRT
newwizard.description=Créer un profil de connexion à la source de données BIRT POJO
wizard.window.title=Nouveau profil de source de données BIRT POJO
wizard.data.source.page.title=Source de données POJO BIRT
profile.propertypage.name=Propriétés de connexion à la source de données BIRT POJO
wizard.data.set.window.title=Nouveau jeu de données BIRT POJO
wizard.data.set.propertiesPage.title=Propriétés
wizard.data.set.columnMappingPage.title=Mise en correspondance de colonne
