###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# NLS strings
#
plugin.name=BIRT POJO Data Source ODA Designer
newwizard.name=BIRT POJO Data Source
newwizard.description=BIRT POJO データソース接続プロファイルの作成

wizard.window.title=BIRT POJO データソースプロファイルの新規作成

wizard.data.source.page.title=BIRT POJO Data Source
profile.propertypage.name=BIRT POJO Data Source Connection Properties
wizard.data.set.window.title=BIRT POJO データセットの新規作成

wizard.data.set.propertiesPage.title=プロパティ

wizard.data.set.columnMappingPage.title=列マッピング
