Shared.Lbl.OK=\ \ \ Aceptar

Shared.Lbl.Cancel=Cancelar

Shared.Lbl.Triggers=Activadores

Shared.Tooltip.FormatSpecifier=Llamar al editor de especificador de formato

Shared.mne.Visibile_v=&Visible

Shared.mne.Visibile_s=Vi&sible

Shared.mne.Background_K=Fon&do:

ChartWithAxesImpl.Z_Axis.title=Título del eje Z

ChartSheetImpl.Buttom.Auto=A&utomática

ChartSheetImpl.Button.AutoHide=O&cultar diagrama si no hay datos que mostrar.

ChartSheetImpl.Button.EnableStudyLayout=Activar diseño de estudio

ChartSheetImpl.Button.ShowEmptyMsg=Mostrar el diagrama con el siguiente &mensaje:

ChartSheetImpl.Group.EmptyMessage=Visibilidad

ChartSheetImpl.Group.EmptyMessage&=&Visibilidad

ChartSheetImpl.Label.Outline=Contorno:

ChartLegendImpl.Group.Rotation=Rotación

ChartPlotSheetImpl.Label.Outline=Contorno:

ChartPlotSheetImpl.Label.Visible=&Visible

ChartPlotSheetImpl.Label.Visible2=V&isible

ChartPlotSheetImpl.Label.PlotArea=Área de dibujo

ChartPlotSheetImpl.Label.AreaFormat=Formato del área

ChartPlotSheetImpl.Label.AreaFormat&=&Formato del área

ChartTitleSheetImpl.Label.ChartTitle=T&ítulo del diagrama:

ChartTitleSheetImpl.Label.Interactivity=Interactividad del título

ChartTitleSheetImpl.Titel.Tooltip=Información sobre herramientas de título

ChartTitleSheetImpl.Label.Tooltip=Información sobre herramientas:

ScriptSheetImpl.Lbl.Script=Script:

ScriptSheetImpl.Lbl.Update=Actualizar

ScriptSheetImpl.Title.SheetTitle=Scripts - Establecer/editar scripts para diagrama

GeneralSheetImpl.Lbl.ChartTitle=Título del diagrama:

GeneralSheetImpl.Lbl.Description=&Descripción:

GeneralSheetImpl.Lbl.GeneralProperties=Propiedades generales

GeneralSheetImpl.Lbl.Type=Tipo:

GeneralSheetImpl.Lbl.Subtype=Subtipo:

GeneralSheetImpl.Lbl.Units=Unidades:

GeneralSheetImpl.Lbl.ColumnCount=Número de\ncolumnas:

GeneralSheetImpl.Lbl.ChartBackground=Fondo:

GeneralSheetImpl.Lbl.ChartWall=Pared:

GeneralSheetImpl.Lbl.ChartFloor=Suelo:

GeneralSheetImpl.Lbl.ChartOutline=Contorno del diagrama

GeneralSheetImpl.Lbl.TitleProperties=Propiedades del título

GeneralSheetImpl.Lbl.ExtendedProperties=Propiedades ampliadas

GeneralSheetImpl.Lbl.SeriesWidth=&Profundidad de serie: \n ({0})

GeneralSheetImpl.Title.SheetTitle=General - Establecer propiedades de diagrama general

BaseAxisDataSheetImpl.Lbl.Type=Tipo:

BaseAxisDataSheetImpl.Lbl.Title=Título del eje:

BaseAxisDataSheetImpl.Lbl.Origin=Origen:

BaseAxisDataSheetImpl.Lbl.Value=Val&or:

BaseAxisDataSheetImpl.Lbl.YAxisCount=Número de ejes Y:

AbstractScaleSheet.AutoExpand=A&mpliar automáticamente

AbstractScaleSheet.Label.Step=Paso

AbstractScaleSheet.Label.Auto=&Automático

AbstractScaleSheet.Label.Factor=&Factor(Valor/Puntos):

BaseAxisDataSheetImpl.Lbl.Minimum=&Mínimo:

BaseAxisDataSheetImpl.Lbl.MajorGridStepNum=&Número de paso de la cuadrícula principal:

BaseAxisDataSheetImpl.Lbl.Maximum=Má&ximo:

AbstractScaleSheet.Label.StepSize=&Intervalo de paso:

BaseAxisDataSheetImpl.Lbl.Unit=&Unidad:

BaseAxisDataSheetImpl.Lbl.MinorGridCount=&Recuento de cuadrículas secundarias por unidad:

BaseAxisDataSheetImpl.Lbl.BaseAxis=Eje de categoría

BaseAxisDataSheetImpl.Title.SheetTitle=Datos > Eje X - Establecer datos del eje X

BaseAxisDataSheetImpl.Lbl.BaseAxis2=Eje de categoría ({0})

BaseAxisAttributeSheetImpl.Lbl.GapWidth=Ancho del espacio:

BaseAxisAttributeSheetImpl.Lbl.MajorGrid=Cuadrícula principal

BaseAxisAttributeSheetImpl.Lbl.MinorGrid=Cuadrícula secundaria

BaseAxisAttributeSheetImpl.Lbl.Orientation=Orientación:

BaseAxisAttributeSheetImpl.Lbl.PercentSign=%
BaseAxisAttributeSheetImpl.Lbl.ShowAxisLine=Mostrar línea del e&je

BaseAxisAttributeSheetImpl.Lbl.IsTickBetweenCategories=Cruce &entre categorías

BaseAxisAttributeSheetImpl.Lbl.AxisLineColor=&Color de línea de eje:

BaseAxisAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos del eje...el diagrama deber ser del tipo ChartWithAxes

BaseAxisAttributeSheetImpl.Title.SheetTitle=Atributos > Eje X - Personalizar atributos del eje X

BaseAxisMarkerAttributeSheetImpl.Lbl.Value=Val&or:

BaseAxisMarkerAttributeSheetImpl.Lbl.Anchor=Del&imitador:

BaseAxisMarkerAttributeSheetImpl.Lbl.Fill=&Relleno:

BaseAxisLabelAttributeSheetImpl.Lbl.Label=Etiqueta

BaseAxisLabelAttributeSheetImpl.Lbl.Title=Título

BaseAxisLabelAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos de etiqueta del eje...el diagrama deber ser del tipo ChartWithAxes

BaseAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=Mostrar etiquetas en sucesión

BaseAxisLabelAttributeSheetImpl.Title.SheetTitle=Atributos > Eje X > Etiquetas - Personalizar etiquetas del eje X

BaseAxisMarkerAttributeSheetImpl.Lbl.AddLine=&Añadir línea

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRange=Aña&dir intervalo

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRegion=&Añadir región

BaseAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=&Eliminar entrada

BaseAxisMarkerAttributeSheetImpl.Lbl.StartValue=&Valor inicial:

BaseAxisMarkerAttributeSheetImpl.Lbl.EndValue=&Valor de fin:

BaseAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=Contorno del intervalo

BaseAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ para el eje

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=Atributos de línea de marcador

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=Propiedades del marcador

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0} {1}
BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange {0} {1}
BaseAxisMarkerAttributeSheetImpl.Title.SheetTitle=Atributos > Eje X > Marcadores - Establecer marcadores del eje X

BaseAxisMarkerAttributeSheetImpl.Lbl.InnerRadius=Radio &interno:

BaseAxisMarkerAttributeSheetImpl.Lbl.OuterRadius=Radio &externo:

BaseAxisMarkerAttributeSheetImpl.Lbl.DialProperties=Propiedades de región

BaseAxisMarkerAttributeSheetImpl.Lbl.DialLabelProperties=Propiedades de la etiqueta de región

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=Propiedades de la etiqueta del marcador

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveDown=Aba&jo

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveUp=A&rriba

BaseAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos de marcador del eje...el diagrama deber ser del tipo ChartWithAxes

BaseSeriesDataSheetImpl.Choice.Unsorted=Sin orden

BaseSeriesDataSheetImpl.Lbl.DataSorting=&Orden de los datos:

BaseSeriesDataSheetImpl.Lbl.YSeriesCount=Número de series Y:

BaseSeriesAttributeSheetImpl.Lbl.Palette=Paleta

BaseAxisDataSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos del eje...el diagrama deber ser del tipo ChartWithAxes

BaseSeriesAttributeSheetImpl.Lbl.SeriesType=Tipo de serie:

BaseSeriesAttributeSheetImpl.Title.SheetTitle=Atributos > Serie X - Personalizar atributos de la serie (X) de categoría

BaseSeriesDataSheetImpl.Lbl.DataDefinitions=Definiciones de datos

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinitions=Definiciones de serie del valor

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinition=Definición de serie del valor

BaseSeriesDataSheetImpl.Title.SheetTitle=Datos > Serie (X) de categoría - Establecer datos de la serie (X) de categoría

BaseSeriesDataSheetImpl.Lbl.DialSeriesCount=Número de cuadrantes:

BaseSeriesDataSheetImpl.Lbl.DialSeriesDefinitions=Definiciones de series de cuadrantes

DialScaleDialog.Title.DialScale=Escala del cuadrante

DialTicksDialog.Title.DialTicks=Marcas del cuadrante

OrthogonalAxisAttributeSheetImpl.Lbl.HideAxisLine=Ocultar línea de ejes

OrthogonalAxisAttributeSheetImpl.Lbl.Orientation=Orientación:

OrthogonalAxisAttributeSheetImpl.Lbl.PercentSign=%
OrthogonalAxisAttributeSheetImpl.Lbl.GapWidth=Ancho del espacio:

OrthogonalAxisAttributeSheetImpl.Lbl.MajorGrid=Cuadrícula principal

OrthogonalAxisAttributeSheetImpl.Lbl.MinorGrid=Cuadrícula secundaria

OrthogonalAxisAttributeSheetImpl.Lbl.AxisLineColor=Color de línea del eje:

OrthogonalAxisAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos del eje...el diagrama deber ser del tipo ChartWithAxes

OrthogonalAxisAttributeSheetImpl.Title.SheetTitle=Atributos > Eje Y - Personalizar atributos del eje Y

OrthogonalAxisDataSheetImpl.Lbl.Type=Ti&po:

OrthogonalAxisDataSheetImpl.Lbl.Title=Título del eje:

OrthogonalAxisDataSheetImpl.Lbl.Origin=&Origen:

OrthogonalAxisDataSheetImpl.Lbl.Value=Valor:

OrthogonalAxisDataSheetImpl.Lbl.PrimaryAxis=Es eje principal

OrthogonalAxisDataSheetImpl.Lbl.Scale=Escala

OrthogonalAxisDataSheetImpl.Lbl.Minimum=Mínimo:

OrthogonalAxisDataSheetImpl.Lbl.Maximum=Máximo:

OrthogonalAxisDataSheetImpl.Lbl.Step=Paso:

OrthogonalAxisDataSheetImpl.Lbl.Unit=Unidad:

OrthogonalAxisDataSheetImpl.Lbl.MinorGridCount=Recuento de cuadrículas secundarias por unidad:

OrthogonalAxisDataSheetImpl.Lbl.SeriesDefinitionCount=Número de definiciones de serie:

OrthogonalAxisDataSheetImpl.Lbl.SeriesGroupingKey=Clave de agrupación de series (opcional)

OrthogonalAxisDataSheetImpl.Lbl.OrthogonalAxis=Eje de valor

OrthogonalAxisDataSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos del eje...el diagrama deber ser del tipo ChartWithAxes

OrthogonalAxisDataSheetImpl.Title.SheetTitle=Datos > Eje Y - Establecer datos del eje Y

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Label=Etiqueta

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Title=Título

OrthogonalAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=Mostrar etiquetas en sucesión

OrthogonalAxisLabelAttributeSheetImpl.Title.SheetTitle=Atributos > Eje Y > Etiquetas - Personalizar etiquetas del eje Y

OrthogonalAxisLabelAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos de etiqueta del eje...el diagrama deber ser del tipo ChartWithAxes

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Values=Valor:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Anchor=Delimitador:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddLine=Añadir línea

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddRange=Añadir intervalo

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.EndValue=Valor de fin:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ para el eje {0}

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=Eliminar entrada

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.StartValue=Valor de inicio:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=Contorno del intervalo

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0,number,integer} {1}
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange 
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Fill=Relleno:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=Propiedades del marcador

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=Atributos de línea de marcador

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=Propiedades de la etiqueta del marcador

OrthogonalAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=Argumento no válido para la hoja de atributos de marcador del eje...el diagrama deber ser del tipo ChartWithAxes

OrthogonalSeriesAttributeSheetImpl.Lbl.Remove=&Quitar

OrthogonalSeriesAttributeSheetImpl.Lbl.Add=&Añadir

OrthogonalSeriesAttributeSheetImpl.Lbl.Up=A&rriba

OrthogonalSeriesAttributeSheetImpl.Lbl.Down=&Abajo

OrthogonalSeriesAttributeSheetImpl.Lbl.Prefix=Pre&fijo:

OrthogonalSeriesAttributeSheetImpl.Lbl.Suffix=Sufi&jo:

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesType=Tipo de serie:

OrthogonalSeriesAttributeSheetImpl.Lbl.HideSeries=Ocultar serie

OrthogonalSeriesAttributeSheetImpl.Lbl.Palette=Paleta

OrthogonalSeriesAttributeSheetImpl.Lbl.DataPoint=Punto de datos

OrthogonalSeriesAttributeSheetImpl.Lbl.Separator=S&eparador:

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDetails=Detalles de la serie

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPoint=DataPoint de la serie

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPointComponent=Componente DataPoint de la serie - {0}

OrthogonalSeriesAttributeSheetImpl.Lbl.StackSeriesElements=Elementos de series de apilamiento

OrthogonalSeriesAttributeSheetImpl.Title.SheetTitle=Atributos > Serie Y - Personalizar atributos de la serie (Y) del valor

OrthogonalSeriesDataSheetImpl.Lbl.Triggers=Interactividad

OrthogonalSeriesDataSheetImpl.Lbl.DataDefinitions=Definiciones de datos

OrthogonalSeriesDataSheetImpl.Lbl.Scale=Escala

OrthogonalSeriesDataSheetImpl.Lbl.Minimum=&Mínimo:

OrthogonalSeriesDataSheetImpl.Lbl.Maximum=Má&ximo:

OrthogonalSeriesDataSheetImpl.Lbl.Step=&Paso:

OrthogonalSeriesDataSheetImpl.Lbl.Unit=Unidad:

OrthogonalSeriesDataSheetImpl.Lbl.MinorGridCount=Recuento de cuadrículas secundarias por &unidad:

OrthogonalSeriesDataSheetImpl.Lbl.MajorGrid=Cuadrícula principal

OrthogonalSeriesDataSheetImpl.Lbl.MinorGrid=Cuadrícula secundaria

OrthogonalSeriesDataSheetImpl.Title.SheetTitle=Datos > Serie (Y) del valor - Establecer datos de la serie (Y) del valor

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Label=Etiqueta

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Title=Título

OrthogonalSeriesLabelAttributeSheetImpl.Title.SheetTitle=Atributos > Serie Y > Etiquetas - Personalizar etiquetas de la serie (Y) del valor

AreaChart.Txt.PercentStackedDescription=Los diagramas de áreas apiladas de porcentaje muestran las áreas apiladas una sobre la otra de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

AreaChart.Txt.StackedDescription=Los diagramas de áreas apiladas muestran las áreas apiladas una sobre la otra.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

AreaChart.Txt.OverlayDescription=Los diagramas de áreas superpuestas muestran las áreas de cada serie por separado.\nLas áreas se muestran vinculando los valores de la serie.

AreaChart.Txt.HelpText=Una área representa una serie en procesamiento. Se pueden usar marcadores opcionales para resaltar los puntos para los que se está dibujando datos. Las áreas apiladas muestran cada punto de categoría con relación a la posición inferior del punto de datos de la serie de áreas. Las áreas de porcentaje apiladas muestran los valores de los datos dibujados como el porcentaje total de la categoría.

AreaChart.Txt.DefaultAreaChartTitle=Título del diagrama de área

AreaChart.Txt.DisplayName=Área

AreaChart.SubType.Stacked=Apilado

AreaChart.SubType.PercentStacked=Porcentaje apilado

AreaChart.SubType.Overlay=Superposición

AreaSeriesUIProvider.Lbl.SeriesDefinition=Definición de series

MeterChart.Txt.DefaultMeterChartTitle=Título del diagrama métrico

MeterChart.Txt.DisplayName=Métrico

MeterChart.SubType.Standard=Diagrama métrico estándar

MeterChart.SubType.Superimposed=Diagrama métrico superpuesto

MeterChart.Tooltip.InputExpression=Introduzca una expresión que se muestre como texto de leyenda para cada elemento

MeterChart.Txt.HelpText=Los diagramas métricos muestran los valores de datos actuales de una determinada medida. Las regiones con diferentes colores representan los intervalos de los valores medidos. Cada cuadrante tiene un indicador asociado que muestra su valor.

MeterChart.Txt.Description=Los diagramas métricos estándar presentan un solo cuadrante con una o varias regiones.\nEl fondo del cuadrante puede dividirse en varias regiones con diferentes colores.

MeterChart.Txt.SuperimposedDescription=Los diagramas métricos superpuestos contienen varios cuadrantes con idénticas regiones.\nLos cuadrantes se superponen, por lo que pueden presentar múltiples indicadores dentro de una misma región.

MeterSeriesAttributeComposite.Lbl.Radius=Radi&o:

MeterSeriesAttributeComposite.Lbl.StartAngle=Án&gulo de inicio:

MeterSeriesAttributeComposite.Lbl.StopAngle=Ángulo de d&etención:

MeterSeriesAttributeSheetImpl.Lbl.Type=Tipo:

MeterSeriesAttributeSheetImpl.Lbl.Fill=&Relleno:

MeterSeriesAttributeComposite.Lbl.DialTicks=&Marcas

MeterSeriesAttributeComposite.Lbl.DialScale=Es&cala

BarSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para BarSeriesAttributeComposite.

BarSeriesUIProvider.Lbl.SeriesDefinition=Definición de series

BarSeriesAttributeComposite.Lbl.SeriesOutline=C&ontorno de series:

BarBottomAreaComponent.Label.CategoryXSeries=Serie de &categoría (X):

StockSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para StockSeriesAttributeComposite.

StockSeriesDataDefinitionComposite.Lbl.StockSeriesDefinition=Definición de series de cotización de acciones

StockSeriesAttributeComposite.Lbl.CandleFill=Relleno de vela:

StockSeriesAttributeComposite.Lbl.StickLength=Longitud de la barra:

StockSeriesAttributeComposite.Lbl.Line=Línea

StockSeriesDataDefinitionComposite.Lbl.High=Alto:

StockSeriesDataDefinitionComposite.Lbl.HighValue=\ - Valor alto

StockSeriesDataDefinitionComposite.Lbl.Low=Bajo:

StockSeriesDataDefinitionComposite.Lbl.LowValue=\ - Valor bajo

StockSeriesDataDefinitionComposite.Lbl.Open=Abrir:

StockSeriesDataDefinitionComposite.Lbl.OpenValue=\ - Abrir valor

StockSeriesDataDefinitionComposite.Lbl.Close=Cerrar:

StockSeriesDataDefinitionComposite.Lbl.CloseValue=\ - Cerrar valor

StockChart.Txt.DefaultStockChartTitle=Título de diagrama de cotización

StockChart.Txt.DisplayName=Cotización de acciones

StockChart.Txt.BarStickDescription=Un diagrama de cotización de barras contiene una línea vertical con dos líneas horizontales pegadas. \Los puntos superior e inferior de la línea vertical son los valores de cotización de apertura y cierre. \nLas dos líneas horizontales son los valores máximo y mínimo.

StockChart.Txt.CandleStickDescription=Un diagrama de cotización de velas contiene un cuadro con líneas que se extienden hacia arriba y hacia abajo de los extremos. \Los bordes superior e inferior del cuadro son los valores de cotización de apertura y cierre. \Los puntos superior e inferior de la línea son los valores máximo y mínimo.

StockChart.Txt.HelpText=Los diagramas de cotización de acciones se componen de elementos gráficos para representar, con cada elemento, una sesión de negociación. El extremo superior de la línea indica el valor alto de la sesión. El extremo inferior de la línea indica el valor bajo de la sesión. Una barra vincula los valores de apertura y cierre.

StockChart.SubType.CandleStick=Diagrama de cotización de velas

StockChart.SubType.BarStick=Diagrama de cotización de barras

LineAttributesComposite.Lbl.Style=Estilo:

LineAttributesComposite.Lbl.Width=Ancho:

LineAttributesComposite.Lbl.Color=Color:

LineAttributesComposite.Lbl.IsVisible=Visible

LineSeriesUIProvider.Lbl.SeriesDefinition=Definición de series

LineSeriesAttributeComposite.Lbl.ShadowColor=Som&bra:

LineSeriesAttributeComposite.Lbl.Marker=Marcador

LineChart.Txt.PercentStackedDescription=Los diagramas de líneas apiladas de porcentaje muestran las líneas apiladas una sobre la otra de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

LineSeriesAttributeComposite.Lbl.IsVisible=&Visible

LineSeriesAttributeComposite.Lbl.Type=Tipo:

LineSeriesAttributeComposite.Lbl.Size=&Tamaño:

LineSeriesAttributeComposite.Lbl.Line=Línea

LineSeriesMarkerSheet.Label.Markers=Marcadores

LineSeriesMarkerSheet.Label.Add=&Añadir

LineSeriesMarkerSheet.Label.Remove=&Quitar

LineSeriesAttributeComposite.Lbl.LinePalette=Usar &paleta de series como color de línea

LineChart.Txt.DefaultLineChartTitle=Título del diagrama de líneas

LineSeriesAttributeComposite.Lbl.ConnectMissingValue=C&onectar los valores que faltan

LineChart.Txt.DisplayName=Línea

LineChart.SubType.Stacked=Apilado

LineChart.SubType.PercentStacked=Porcentaje apilado

LineChart.SubType.Overlay=Superposición

LineChart.Txt.StackedDescription=Los diagramas de líneas apiladas muestran las líneas apiladas una sobre la otra.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

LineChart.Txt.OverlayDescription=Los diagramas de líneas superpuestas muestran las líneas de cada serie por separado.\nLas líneas se muestran vinculando los valores de la serie.

LineSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para LineSeriesAttributeComposite.

LineSeriesAttributeComposite.Lbl.ShowLinesAsCurves=M&ostrar líneas como curvas

LineChart.Txt.HelpText=Una línea representa una serie en procesamiento. Se pueden usar marcadores opcionales para resaltar los puntos para los que se está dibujando datos. Las líneas apiladas muestran cada punto de categoría con relación a la posición inferior del punto de datos de la serie de línea. Las líneas de porcentaje apiladas muestran los valores de los datos dibujados como el porcentaje total de la categoría.

ScatterChart.Txt.Description=Los diagramas de dispersión organizan los valores en el dibujo usando los datos de categoría y de valor como coordenadas. \nCada valor de datos se indica con un marcador.

ScatterChart.Txt.HelpText=Los diagramas de dispersión muestran los valores de los datos espaciados aleatoriamente asociados con ejes que no son de categoría. Cada punto de datos se asocia con la escala del eje X e Y.

ScatterSeriesUIProvider.Lbl.SeriesDefinition=Definición de series

ScatterChart.Txt.DefaultScatterChartTitle=Título de diagrama de dispersión

ScatterChart.Txt.DisplayName=Dispersión

ScatterChart.SubType.Standard=Diagrama de dispersión estándar

BarChart.Txt.DefaultBarChartTitle=Título del diagrama de barras

BarChart.Txt.DisplayName=Barra

BarChart.SubType.Stacked=Apilado

BarChart.SubType.PercentStacked=Porcentaje apilado

BarChart.SubType.Side=Lateral

BarChart.Txt.StackedDescription=Los diagramas de barras apiladas muestran las barras apiladas una sobre la otra.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

BarChart.Txt.PercentStackedDescription=Los diagramas de barras apiladas de porcentaje muestran barras apiladas una sobre la otra de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

BarChart.Txt.HelpText=Los diagramas de barras se crean para comparar clases o grupos de datos. Los valores de los datos de las diferentes series de una misma categoría aparecen en una sucesión de columnas independientes o apiladas como secciones en una sola columna (según el subtipo seleccionado).

BarChart.Txt.SideBySideDescription=Los diagramas de barras laterales muestran barras de cada serie una junto a la otra. \nEstas barras se organizan para que tengan el mismo ancho. \nEl ancho de las barras dependerá del número de series que se vaya a procesar.

TubeChart.Txt.DefaultTubeChartTitle=Título de diagrama de tubos

TubeChart.Txt.DisplayName=Tubo

TubeChart.SubType.Stacked=Apilado

TubeChart.SubType.PercentStacked=Porcentaje apilado

TubeChart.SubType.Side=Lateral

TubeChart.Txt.StackedDescription=Los diagramas de tubos apilados muestran los tubos apilados uno sobre otro.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

TubeChart.Txt.PercentStackedDescription=Los diagramas de tubos apilados de porcentaje muestran tubos apilados uno sobre otro de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

TubeChart.Txt.HelpText=Los diagramas de tubos se crean para comparar clases o grupos de datos. Los valores de los datos de las diferentes series de una misma categoría aparecen en una sucesión de columnas independientes o apiladas como secciones en una sola columna (según el subtipo seleccionado).

TubeChart.Txt.SideBySideDescription=Los diagramas de tubos laterales muestran tubos de cada serie uno junto al otro.\nEstos tubos se organizan para que tengan el mismo ancho, según el número de series que se vaya a procesar.

ConeChart.Txt.DefaultConeChartTitle=Título del diagrama de conos

ConeChart.Txt.DisplayName=Cono

ConeChart.SubType.Stacked=Apilado

ConeChart.SubType.PercentStacked=Porcentaje apilado

ConeChart.SubType.Side=Lateral

ConeChart.Txt.StackedDescription=Los diagramas de conos apilados muestran los conos apilados uno sobre otro.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

ConeChart.Txt.PercentStackedDescription=Los diagramas de conos apilados de porcentaje muestran conos apilados uno sobre otro de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

ConeChart.Txt.HelpText=Los diagramas de conos se crean para comparar clases o grupos de datos. Los valores de los datos de las diferentes series de una misma categoría aparecen en una sucesión de columnas independientes o apiladas como secciones en una sola columna (según el subtipo seleccionado).

ConeChart.Txt.SideBySideDescription=Los diagramas de conos laterales muestran conos de cada serie una junto a otro.\nEstos conos se organizan para que tengan el mismo ancho, según el número de series que se vaya a procesar.

PyramidChart.Txt.DefaultPyramidChartTitle=Título de diagrama piramidal

PyramidChart.Txt.DisplayName=Pirámide

PyramidChart.SubType.Stacked=Apilado

PyramidChart.SubType.PercentStacked=Porcentaje apilado

PyramidChart.SubType.Side=Lateral

PyramidChart.Txt.StackedDescription=Los diagramas de pirámides apiladas muestran las pirámides apiladas una sobre otra.\nLos valores positivos y negativos se apilan por separado, por encima y por debajo del origen.

PyramidChart.Txt.PercentStackedDescription=Los diagramas de pirámides apiladas de porcentaje muestran pirámides apiladas una sobre otra de forma\nque la altura total sea 100, midiendo desde el punto más bajo hasta el más alto de cada unidad.

PyramidChart.Txt.HelpText=Los diagramas de pirámides se crean para comparar clases o grupos de datos. Los valores de los datos de las diferentes series de una misma categoría aparecen en una sucesión de columnas independientes o apiladas como secciones en una sola columna (según el subtipo seleccionado).

PyramidChart.Txt.SideBySideDescription=Los diagramas de pirámides laterales muestran pirámides de cada serie una junto a otra.\nEstas barras se organizan para que tengan el mismo ancho, según el número de series que se vaya a procesar.

PieChart.Txt.DefaultPieChartTitle=Título del diagrama circular

PieChart.Txt.DisplayName=Circular

PieChart.SubType.Standard=Diagrama circular estándar

PieSeriesUIProvider.Lbl.OrthogonalPrefix=Valor

PieSeriesUIProvider.Lbl.SeriesDefinition=Definición de series

PieBottomAreaComponent.Label.Percentage=Porcentaje

PieSeriesAttributeComposite.Button.Direction=En el sentido de las agujas del reloj

PieSeriesAttributeComposite.Button.Direction.ToolTipText=Especifica si los cortes de diagrama circular se procesan en el sentido de las agujas del reloj.

PieSeriesAttributeComposite.Button.InnerRadius=Radio interno:

PieSeriesAttributeComposite.Grp.Slice=Corte

PieSeriesAttributeComposite.Lbl.SliceOutline=Contorno del &corte:

PieSeriesAttributeComposite.Lbl.LeaderLine=Línea inicial

PieSeriesAttributeComposite.Lbl.LeaderLineStyle=Esti&lo de línea inicial:

PieSeriesAttributeComposite.Lbl.LeaderLineLength=Longitud de línea &inicial:

PieBottomAreaComponent.Label.AnySliceWithASize=Cualquier corte cuyo tamaño sea inferior a la entrada se combinará en otra categoría.

PieBottomAreaComponent.Label.ExplodeSliceWhen=S&eparar corte cuando:

PieBottomAreaComponent.Label.ByDistance=Por &distancia:

PieBaseSeriesComponent.Label.CategoryDefinition=Definición de &categoría:

PieBaseSeriesComponent.Text.SpecifyExplodeSlice=Especificar corte de separación

PieBaseSeriesComponent.Tooltip.EnterBooleanExpression=Introduzca una expresión booleana para seleccionar el corte que desea separar. Si se deja en blanco, la distancia de separación se aplicará a todos los cortes.

PieLeftAreaComponent.Label.SliceSizeDefinition=Definición del tamaño de corte:

PieSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para PieSeriesAttributeComposite.

PieSeriesAttributeComposite.InnerRadiusType.Points=Puntos

PieSeriesAttributeComposite.Lbl.Explosion=Separación:

PiesBottomAreaComponent.Label.TheRotationOfTheChart=Rotación circular: el ángulo de inicio del primer corte circular

PieBottomAreaComponent.Label.Rotation=Rotació&n circular:

PieBottomAreaComponent.Label.MinimumSlice=&Corte mínimo:

PieBottomAreaComponent.Label.MinSliceLabel=&Etiqueta de corte:

PieSeriesUIProvider.Lbl.BasePrefix=Categoría

PieBottomAreaComponent.Label.Value=Valor

PieBottomAreaComponent.Label.Ratio=&Proporción circular:

PieBottomAreaComponent.Label.TheRatioOfTheChart=Proporción circular: proporción altura/anchura (0: ajuste automático de proporción)

PieChart.Txt.Description=Los diagramas circulares muestran los valores como cortes de un círculo.\nEl tamaño de cada corte es proporcional al valor que representa.\nLos diagramas circulares de varias series se dibujan como múltiples círculos, uno para cada serie.

PieChart.Txt.HelpText=Los diagramas circulares muestran los valores de los datos de una serie o categoría como un porcentaje de corte del círculo entero. Las diversas series circulares se presentan en una cuadrícula.

SeriesUIProvider.Lbl.OrthogonalPrefix=Valor

SeriesUIProvider.Lbl.SeriesDefinition=Definición de series

SeriesSheetImpl.Label.CategoryBaseSeries=Serie de categoría

SeriesUIProvider.Lbl.BasePrefix=Categoría

SeriesSheetImpl.Label.Title=Título

SeriesSheetImpl.Label.Visible=Visible

SeriesSheetImpl.Label.Stacked=Apilado

SeriesSheetImpl.Label.Series=Series

SeriesYSheetImpl.Label.Needles=Indicadores

SeriesYSheetImpl.Label.Needles&=&Indicadores

SeriesYSheetImpl.Label.Region=Regiones

SeriesYSheetImpl.Label.Region&=Regi&ones

SeriesYSheetImpl.Label.Labels=Etiquetas de serie

SeriesYSheetImpl.Label.Labels&=Etiqu&etas

SeriesYSheetImpl.Label.DialLabels=Etiquetas de cuadrante

SeriesYSheetImpl.Label.DialLabels&=Etiquetas de cua&drante

SeriesYSheetImpl.Label.Titles=Títulos

SeriesYSheetImpl.Label.Titles&=&Títulos

SeriesYSheetImpl.Label.Markers=Marcadores de series

SeriesYSheetImpl.Label.PositiveMarkers=Marcadores positivos

SeriesYSheetImpl.Label.NegativeMarkers=Marcadores negativos

SeriesYSheetImpl.Label.Markers&=&Marcadores

SeriesYSheetImpl.Label.PositiveMarkers&=Marcadores &positivos

SeriesYSheetImpl.Label.NegativeMarkers&=Marcadores &negativos

SeriesYSheetImpl.Label.Decoration=Tareas

SeriesYSheetImpl.Label.Decoration&=&Etiquetas de tareas

SeriesLabelSheet.Label.Format=Formato

SeriesLabelSheet.Label.Values=Valores

SeriesGroupingComposite.Lbl.Type=&Tipo:

SeriesGroupingComposite.Lbl.Unit=&Unidad:

SeriesYSheetImpl.Label.Trendline=Curva ajustada a línea

SeriesYSheetImpl.Label.Trendline&=&Curva ajustada a línea

SeriesTrendlineSheet.Label.Label=Etiqueta

SeriesTrendlineSheet.Label.Label&=&Etiqueta:

SeriesGroupingComposite.Lbl.Grouping=Agrupación

SeriesGroupingComposite.Lbl.Enabled=&Activado

SeriesSheetImpl.Label.ValueYSeries=Serie (Y) del valor

SeriesSheetImpl.Label.Translucent=Translúcido

SeriesSheetImpl.Label.SeriesPalette=Paleta de series

SeriesSheetImpl.Label.SeriesPalette&=&Paleta de series

SeriesYSheetImpl.Label.DataPoint=Punto de datos

SeriesTrendlineSheet.Label.Outline=Contorno

SeriesTrendlineSheet.SeriesTrendlineSheet.Lbl.IsVisible=V&isible

SeriesGroupingComposite.Lbl.Interval=Inter&valo:

SeriesYSheetImpl.Label.ShowLabels=&Mostrar etiquetas de serie

SeriesYSheetImpl.Label.ShowDialLabels=&Mostrar etiquetas de cuadrante

SeriesYSheetImpl.Label.ShowDecoLabels=&Mostrar etiquetas de tarea

SeriesYSheetImpl.Label.ShowTrendline=&Mostrar curva ajustada a línea

SeriesYSheetImpl.Label.Interactivity&=Inte&ractividad

SeriesYSheetImpl.Label.Interactivity=Interactividad de la serie

SeriesGroupingComposite.Lbl.AggregateExpression=&Función:
SeriesGroupingComposite.Tooltip.SelectIntervalForGrouping=Seleccione el intervalo para la agrupación. 0 indica una agrupación por valor de categoría/X

SeriesPaletteSheet.Label.Auto=Au&tomático

SeriesPaletteSheet.Tab.Axis=Eje

SeriesPaletteSheet.Tab.Series=Serie

SeriesSheetImpl.Label.ValueOrthogonalSeries=Serie del valor

TitleBlockAttributeSheetImpl.Lbl.Caption=Título de la etiqueta:

TitleBlockAttributeSheetImpl.Lbl.BlockProperties=Propiedades del bloque

TitleBlockAttributeSheetImpl.Lbl.IsBlockVisible=Es bloque visible

TitleBlockAttributeSheetImpl.Lbl.Anchor=Delimitador:

TitleBlockAttributeSheetImpl.Lbl.Stretch=Extensión:

TitleBlockAttributeSheetImpl.Lbl.Background=Fondo:

TitleBlockAttributeSheetImpl.Lbl.Insets=Bajos relieves

TitlePropertiesSheet.Label.TitleArea=Área de título

TitlePropertiesSheet.Label.Background=Fo&ndo:

TitleBlockAttributeSheetImpl.Lbl.Outline=Contorno

TitlePropertiesSheet.Label.Interactivity=Interactividad

TitleBlockAttributeSheetImpl.Lbl.LabelProperties=Propiedades de la etiqueta

TitleBlockAttributeSheetImpl.Lbl.ChartTitle=Título de diagrama

TitleBlockAttributeSheetImpl.Title.SheetTitle=Diseño > Bloque de título - Formato del área del título del diagrama

LegendAttributeSheetImpl.Lbl.GeneralProperties=Propiedades generales - Leyenda alrededor del área

LegendAttributeSheetImpl.Lbl.ClientAreaProperties=Propiedades del área del cliente  - Área de leyenda

LegendAttributeSheetImpl.Title.SheetTitle=Diseño > Leyenda - Formato del área de leyendas

LegendLayoutSheet.Label.TitlePercent=&Porcentaje de título:

LegendLayoutSheet.Label.MaxPercent=&Porcentaje máximo:

LegendLayoutSheet.Label.WrappingWidth=&Ancho del autoajuste:

SampleDataSheetImpl.Lbl.XSeries=Serie X

SampleDataSheetImpl.Lbl.BaseSampleValues=Valores de muestra:\n {0}

SampleDataSheetImpl.Lbl.SampleValues=Valores de muestra:

SampleDataSheetImpl.Lbl.YSeries=Serie Y

SampleDataSheetImpl.Lbl.SimulateSeriesCount=Recuento de series de simulación:

SampleDataSheetImpl.Lbl.Update=Actualizar

SampleDataSheetImpl.Title.SheetTitle=Datos > Muestra - Establecer datos de muestra para vista previa

PlotAttributeSheetImpl.Lbl.GeneralProperties=Propiedades generales - Área que incluye ejes

PlotAttributeSheetImpl.Lbl.ClientAreaProperties=Propiedades del área del cliente - Área dentro de los ejes

PlotAttributeSheetImpl.Title.SheetTitle=Diseño > Dibujo - Formato del área de dibujo

LabelBlockAttributeSheetImpl.Lbl.LabelCaption=Título de la etiqueta:

LabelBlockAttributeSheetImpl.Lbl.BlockProperties=Propiedades del bloque

LabelBlockAttributeSheetImpl.Lbl.IsBlockVisible=Es bloque visible

LabelBlockAttributeSheetImpl.Lbl.Anchor=Delimitador:

LabelBlockAttributeSheetImpl.Lbl.Stretch=Extensión:

LabelBlockAttributeSheetImpl.Lbl.Background=Fondo:

LabelBlockAttributeSheetImpl.Lbl.Insets=Bajos relieves

LabelAttributesComposite.Lbl.IsVisible=&Visible

LabelAttributesComposite.Lbl.IsVisible2=Visibl&e

LabelAttributesComposite.Lbl.Position=&Posición:

LabelAttributesComposite.Lbl.Background=Fo&ndo:

LabelAttributesComposite.Lbl.Outline=Contorno

LabelBlockAttributeSheetImpl.Lbl.Outline=Contorno

LabelBlockAttributeSheetImpl.Lbl.LabelProperties=Propiedades de la etiqueta

LabelBlockAttributeSheetImpl.Lbl.LabelBlock=Bloque de etiqueta

DataDefinitionComposite.Tooltip.InvokeExpressionBuilder=Llamar al compilador de expresiones

DataDefinitionSelector.Exception.NotSupportedForMultipleAxes=\ no se admite para ejes múltiples\!

DataDefinitionComposite.Tooltip.InvokeRuleEditor=Llamar al editor de reglas

RuleEditorDialog.Title.RuleEditor=Editor de reglas - {0}

RuleEditorDialog.Lbl.Rules=Reglas

RuleEditorDialog.Lbl.Type=Tipo:

RuleEditorDialog.Lbl.Value=Valor:

RuleEditorDialog.Lbl.Remove=Quitar

RuleEditorDialog.Lbl.Add=Añadir

RuleEditorDialog.Lbl.Update=Actualizar

RuleEditorDialog.Exception.InvalidRule=ERROR\! Se ha transmitido un índice de reglas no válido.

FillCanvas.Transparent=Transparente

FillCanvas.Auto=Automático

FillChooserComposite.Button.Pattern=Patrón

FillChooserComposite.Lbl.Opacity=Opacidad: {0, number, integer}

FillChooserComposite.Lbl.Gradient=Gradiente

FillChooserComposite.Lbl.Transparent=Transparente

FillChooserComposite.Lbl.CustomColor=Color personalizado

FillChooserComposite.Lbl.Image=Imagen

FillChooserComposite.Lbl.PositiveNegative=Positivo/Negativo

FillChooserComposite.Lbl.Auto=Automático

ClientAreaAttributeComposite.Lbl.Background=Fondo:

ClientAreaAttributeComposite.Lbl.Shadow=Som&bra:

ClientAreaAttributeComposite.Lbl.Outline=Contorno

InsetsComposite.Lbl.Insets=Bajos relieves ({0})

InsetsComposite.Lbl.Top=&Superior:

InsetsComposite.Lbl.Left=&Izquierda:

InsetsComposite.Lbl.Bottom=&Abajo:

InsetsComposite.Lbl.Right=&Derecha:

InsetsEditorDialog.Title.InsetsEditor=Cuadro de diálogo del editor de bajos relieves

InsetsEditorDialog.Lbl.UnitsMessage=* Todos los valores están en {0}

ExternalizedTextEditorDialog.Title.ExternalizeText=Texto externalizado

ExternalizedTextEditorDialog.Lbl.ExternalizeText=Te&xto externalizado

ExternalizedTextEditorComposite.Warn.KeyNotFound=No se ha encontrado la clave en el archivo de propiedades... o el archivo de propiedades no está presente.

ExternalizedTextEditorComposite.Lbl.EditText=Llamar al editor de texto externalizado

ExternalizedTextEditorDialog.Lbl.LookupKey=&Clave de búsqueda:

ExternalizedTextEditorDialog.Lbl.DefaultValue=&Valor predeterminado:

ExternalizedTextEditorDialog.Lbl.ExternalizedValue=Valor externalizado:

ExternalizedTextEditorDialog.Warn.KeyNotFound=No se ha encontrado la clave en el archivo de propiedades... o el archivo de propiedades no está presente.

ExternalizedTextEditorDialog.Lbl.Value=<Valor de clave ''{0}''>

Format.Button.Label=Formato

Format.Button.Lbl&=F&ormato

FormatSpecifierComposite.error.Title=Error de especificador de formato

FormatSpecifierComposite.error.Message=Valor del parámetro de especificador de formato no válido: "{0}"

FormatSpecifierComposite.Label.DenominatorDigits=Dígitos del denominador

FormatSpecifierComposite.Label.NumeratorValue=Valor del numerador

FormatSpecifierComposite.Lbl.DataType=Tipo de &datos:

FormatSpecifierComposite.Lbl.DateTime=Fecha/hora

FormatSpecifierComposite.Lbl.Undefined=&Ninguno

FormatSpecifierComposite.Lbl.Numerator=&Valor del numerador (1-100):

FormatSpecifierComposite.Lbl.Standard=&Estándar

FormatSpecifierComposite.Lbl.String=String

FormatSpecifierComposite.Lbl.Type=Ti&po:

FormatSpecifierComposite.Lbl.None=<Ninguno>

FormatSpecifierComposite.Lbl.Details=D&etalles:

FormatSpecifierComposite.Lbl.Delimiter=D&elimitador:

FormatSpecifierComposite.Lbl.Pattern=&Patrón:

FormatSpecifierComposite.Lbl.Prefix=&Prefijo:

FormatSpecifierComposite.Lbl.Preview=Vista previa:

FormatSpecifierComposite.Lbl.Approximate=Ap&roximado:

FormatSpecifierComposite.Lbl.Suffix=Sufi&jo:

FormatSpecifierComposite.Lbl.Number=Número

FormatSpecifierPreview.Lbl.NoFormat=No se ha especificado el formato

FormatSpecifierComposite.Lbl.Multiplier=&Multiplicador:

FormatSpecifierComposite.Lbl.FractionDigits=Dí&gitos de fracción:

FormatSpecifierComposite.Tooltip.InputAPositiveInteger=Introduzca un entero positivo como numerador fijo

FormatSpecifierComposite.Tooltip.FractionDigits=Propiedades avanzadas: se utiliza para determinar la precisión aproximada

FormatSpecifierComposite.Lbl.MaxRecursionTimes=Dígitos máximos del den&ominador(1-8):

FormatSpecifierComposite.Lbl.Fraction=&Fracción

FormatSpecifierDialog.Title.EditFormat=Editar formato

FormatSpecifierComposite.Lbl.Advanced=&Avanzado

FormatSpecifierComposite.Lbl.DatePattern=&Patrón:

FormatSpecifierComposite.Lbl.ExampleFormats=Formatos de &ejemplo:

FormatSpecifierComposite.Lbl.NumberPattern=&Patrón:

FormatSpecifierComposite.StringFormat.LowerCase=Minúsculas

FormatSpecifierComposite.StringFormat.PhoneNumber=Teléfono

FormatSpecifierComposite.StringFormat.SocialSNumber=Número de la seguridad social (US)

FormatSpecifierComposite.StringFormat.UpperCase=Mayúsculas

FormatSpecifierComposite.StringFormat.WhiteSpace=Mantenga el espacio en blanco

FormatSpecifierComposite.StringFormat.ZipCode=Código postal +4

FormatSpecifierPreview.Lbl.NotAvailable=No disponible

GridAttributesComposite.Lbl.Ticks=Marcas

GridAttributesComposite.Lbl.Style=Estilo:

GradientEditorDialog.Lbl.EndColor=Color de fin:

GradientEditorDialog.Lbl.Rotation=Rotación

FontDefinitionDialog.Lbl.Rotation=Rotación:

FontDefinitionDialog.Tooltip.Accept=Aceptar

FontDefinitionDialog.Tooltip.Bold=Negrita

FontDefinitionDialog.Tooltip.Italic=Cursiva

FontDefinitionDialog.Tooltip.AlignTopCenter=Alineación - Superior central

FontDefinitionDialog.Tooltip.AlignCenter=Alineación - Centro

FontDefinitionDialog.Tooltip.Underline=Subrayado

FontDefinitionDialog.Tooltip.AlignTopRight=Alineación - Superior derecha

FontDefinitionDialog.Tooltip.Strikethrough=Tachado

FontDefinitionDialog.Title.FontDescriptor=Editar fuente

FontDefinitionDialog.Lbl.Font=&Fuente:

FontDefinitionDialog.Lbl.Size=Tam&año:

FontDefinitionDialog.Lbl.Color=&Color:

FontDefinitionDialog.Lbl.Style=Estilo:

FontDefinitionDialog.Lbl.Format=Formato:

FontDefinitionDialog.Lbl.Wrap=Empaquetado

FontDefinitionDialog.Lbl.Preview=Vista previa:

FontDefinitionDialog.Lbl.Alignment=Alineación:

FontDefinitionDialog.Label.Degree=&Grados:

FontDefinitionDialog.Tooltip.AlignTopLeft=Alineación - Superior izquierda

FontDefinitionDialog.Tooltip.AlignCenterLeft=Alineación - Central izquierda

FontDefinitionDialog.Tooltip.AlignCenterRight=Alineación - Central derecha

FontDefinitionDialog.Tooltip.AlignBottomLeft=Alineación - Inferior izquierda

FontDefinitionDialog.Tooltip.AlignBottomCenter=Alineación - Inferior central

FontDefinitionDialog.Tooltip.AlignBottomRight=Alineación - Inferior derecha

FontDefinitionDialog.Lbl.Strikethrough=&Tachado

FontDefinitionComposite.Tooltip.FontDialog=Llamar al editor de fuentes

TriggerEditorDialog.Title.TriggerEditor=Editor de interacciones - {0}

TriggerDataComposite.Lbl.ActionDetails=Detalles de acción

TriggerDataComposite.Lbl.SeriesDefinition=Definición de series:

TriggerDataComposite.Label.CallbackDescription=La acción de devolución de llamada es para el uso de API en procesamientos SWT o Swing y permite adjuntar un controlador de evento de Java.

TriggerDataComposite.Label.HighlightDescription=Resalta el elemento de datos correspondiente cuando es necesario.

TriggerDataComposite.Label.VisiblityDescription=Alterna la visibilidad del elemento de datos correspondiente cuando es necesario.

TriggerDataComposite.Label.Description=Editar la URL según su tipo, incluyendo URI, marcador interno y aumento.

TriggerDataComposite.Label.DPVisibilityDescription=Alterna la visibilidad de la etiqueta del elemento de datos correspondiente cuando es necesario.

TriggerDataComposite.Label.OptionalURLParameters=Nombrar parámetros de URL opcionales que representen, para cada punto de datos, sus siguientes valores:

TriggerDataComposite.Label.TooltipUsingDataLabelOfSeries=Si el texto de información sobre herramientas no está especificado, se utilizará en su lugar la etiqueta de datos de la serie correspondiente.

TriggerDataComposite.Tooltip.InvokeURLBuilder=Llamar al compilador de URL

TriggerDataComposite.Tooltip.Advanced=Mostrar parámetros de URL opcionales

TriggerDataComposite.Label.None=Ninguno

TriggerDataComposite.Tooltip.ParameterCategory=Nombre del parámetro de la categoría: ...&&&name=<categoría>

TriggerDataComposite.Tooltip.ParameterValue=Nombre del parámetro del valor: ...&&&name=<valor>

TriggerDataComposite.Tooltip.ParameterSeries=Nombre del parámetro de la serie: ...&&&name=<serie>

TriggerDataComposite.Lbl.TooltipDelay=Retardo de la &información sobre herramientas (en ms):

TriggerDataComposite.Lbl.ParameterNames=Parámetros de URL de punto de datos opcionales

TriggerDataComposite.Lbl.CategorySeries=&Serie de categoría:

TriggerDataComposite.Lbl.Cursor=Cur&sor:

TriggerDataComposite.TemporaryName.Hyperlink=Hyperlink

TriggerDataComposite.Text.EditBaseURL=Editar &URL base...

TriggerDataComposite.Text.Advanced=&Avanzado>>

TriggerDataComposite.Text.OpenAdvanced=&Avanzado<<

TriggerDataComposite.Lbl.ValueSeries=&Serie de valor:

TriggerDataComposite.Lbl.ValueSeriesName=Nombre de la &serie de valor:

TriggerDataComposite.Tooltip.InputScript=\ Introduzca un script (normalmente JavaScript) para ejecutarlo en el entorno de procesamiento.

TriggerEditorComposite.Lbl.Remove=&Quitar

TriggerEditorComposite.Lbl.Add=&Añadir

TriggerDataComposite.Lbl.Event=E&vento:

TriggerDataComposite.Lbl.None.accessibility=<Ninguno>

TriggerDataComposite.Lbl.None.MouseClick=<Ninguno>

TriggerDataComposite.Lbl.None.MouseHover=<Ninguno>

TriggerDataComposite.Lbl.None.onblur=<Ninguno>

TriggerDataComposite.Lbl.None.onclick=<Ninguno>

TriggerDataComposite.Lbl.None.ondblclick=<Ninguno>

TriggerDataComposite.Lbl.None.onfocus=<Ninguno>

TriggerDataComposite.Lbl.None.onkeydown=<Ninguno>

TriggerDataComposite.Lbl.None.onkeypress=<Ninguno>

TriggerDataComposite.Lbl.None.onkeyup=<Ninguno>

TriggerDataComposite.Lbl.None.onload=<Ninguno>

TriggerDataComposite.Lbl.None.onmousedown=<Ninguno>

TriggerDataComposite.Lbl.None.onmousemove=<Ninguno>

TriggerDataComposite.Lbl.None.onmouseout=<Ninguno>

TriggerDataComposite.Lbl.None.onmouseover=<Ninguno>

TriggerDataComposite.Lbl.None.onmouseup=<Ninguno>

TriggerDataComposite.Lbl.Action=A&cción:

TriggerDataComposite.Lbl.Script=Scri&pt:

TriggerDataComposite.Lbl.Target=Destino:

TriggerEditorComposite.Lbl.Update=<< &Actualizar

TriggerDataComposite.Lbl.TooltipText=Te&xto de información sobre herramientas:

TriggerDataComposite.Btn.Format=&Formato

TriggerDataComposite.Lbl.BaseURL=Editar URL base:

TriggerDataComposite.Lbl.Image=&Imagen

GradientEditorDialog.Lbl.GradientEditor=Editor de gradientes

GradientEditorDialog.Lbl.StartColor=Color de inicio:

GradientEditorDialog.Lbl.Preview=Vista previa

PaletteEditorComposite.Label.EditColor=Editar color

PaletteEditorComposite.Lbl.Add=&Añadir

PaletteEditorComposite.Lbl.Remove=&Quitar

PaletteEditorComposite.Lbl.Up=Arriba

PaletteEditorComposite.Lbl.Down=Abajo

PatternImageEditorDialog.Button.Cancel=&Cancelar

PatternImageEditorDialog.Button.OK=&Aceptar

PatternImageEditorDialog.Group.Color=Color:

PatternImageEditorDialog.Group.Pattern=Patrón:

PatternImageEditorDialog.Label.Background=Fo&ndo:

PatternImageEditorDialog.Label.Foreground=&Primer plano:

PatternImageEditorDialog.Title.PatternFillEditor=Editor de imagen de patrón

LabelAttributesComposite.Lbl.Label=Etiqueta

LabelAttributesComposite.Lbl.Font=&Fuente:

LabelAttributesComposite.Lbl.Shadow=&Sombra:

LabelBlockAttributeSheetImpl.Title.SheetTitle=Diseño > Bloque de etiqueta - Formato del área del bloque de etiqueta

BlockAttributeComposite.Lbl.IsBlockVisible=Es bloque visible

BlockAttributeComposite.Lbl.Anchor=&Delimitador:

BlockAttributeComposite.Lbl.Stretch=Exten&sión:

BlockAttributeComposite.Lbl.Insets=Bajos relieves

BlockPropertiesSheet.Label.Outline=Contorno

BlockAttributeComposite.Lbl.Outline=Contorno

BlockAttributeComposite.Lbl.HorizontalSpacing=Separación &horizontal:

BlockAttributeComposite.Lbl.VerticalSpacing=Separación &vertical:

BlockAttributeComposite.Lbl.Orientation=&Orientación:

BlockAttributeComposite.Lbl.Direction=&Dirección:

BlockAttributeComposite.Lbl.Position=&Posición:

BlockAttributeComposite.Lbl.ItemType=Tipo de elemento:

BlockAttributeComposite.Title.PlotBlock=Bloque de dibujo

BlockAttributeComposite.Title.LegendBlock=Bloque de leyenda

BlockAttributeComposite.Title.TitleBlock=Bloque de título

BlockAttributeComposite.Title.LabelBlock=Bloque de etiqueta

BlockPropertiesSheet.Label.Interactivity=Interactividad

LayoutSheetImpl.Lbl.ChartProperties=Propiedades de bloque de diagrama

LayoutSheetImpl.Lbl.Background=Fondo:

LayoutSheetImpl.Lbl.Insets=Bajos relieves

LayoutSheetImpl.Lbl.Outline=Contorno

LayoutSheetImpl.Title.SheetTitle=Diseño - Formato de bloque de diagrama

AttributeSheetImpl.Lbl.ChartProperties=Propiedades del diagrama

AttributeSheetImpl.Lbl.Type=Tipo:

AttributeSheetImpl.Lbl.Subtype=Subtipo:

AttributeSheetImpl.Lbl.Units=&Unidades:

AttributeSheetImpl.Lbl.ColumnCount=Recuento de &columnas de cuadrícula:

AttributeSheetImpl.Lbl.ChartBackground=Fondo del diagrama:

AttributeSheetImpl.Lbl.PropertyEditorDialog=Propiedades ampliadas

AttributeSheetImpl.Lbl.ChartWall=Pared del &diagrama:

AttributeSheetImpl.Lbl.ChartFloor=Suelo del &diagrama:

AttributeSheetImpl.Lbl.UnitSpacing=Se&paración de unidades (0-100):

AttributeSheetImpl.Title.SheetTitle=Atributos - Personalizar atributos del diagrama

PropertyEditorDialog.Title.PropertyEditorDialog=Editor de propiedades ampliadas

PropertyEditorDialog.Lbl.Key=Clave

PropertyEditorDialog.Lbl.Value=Valor

PropertyEditorDialog.Lbl.Add=&Añadir

PropertyEditorDialog.Lbl.Remove=&Quitar

HeadStyleAttributeComposite.Lbl.HeadStyle=Estilo de encabezado

HyperlinkEditorDialog.BaseURL.Message=Establezca la URL base.

HyperlinkEditorDialog.ErrorMessage.ExistingText=El nombre introducido ya existe, modifíquelo.

HyperlinkEditorDialog.ErrorMessage.NullText=El nombre no puede estar en blanco\.

HyperlinkEditorDialog.HyperlinkName.Title.Warning=Advertencia

HyperlinkEditorDialog.Text.MenuLabel=&Nombre:

HyperlinkEditorDialog.Title.HyperlinkEditor=Editor de hyperlink

TaskSelectType.TaskExp=Seleccionar tipo de diagrama

TaskSelectType.Label.Preview=Vista previa del diagrama

TaskSelectType.Label.Oritention=Orientación:

TaskSelectType.Label.FlipAxis=Invertir E&je

TaskSelectType.Selection.None=Ninguno

TaskSelectType.Label.MultipleYAxis=&Varios ejes Y:

TaskSelectType.Label.AddSecondaryAxis=Añadir eje secundario

TaskSelectType.Selection.SecondaryAxis=Eje secundario

TaskSelectType.Label.SeriesType=&Tipo de serie:

TaskSelectType.Task.Description=Seleccione el tipo de diagrama y elija un formato de salida.

TaskSelectType.Label.OutputFormat=&Formato de salida:

TaskSelectType.Selection.MoreAxes=Más ejes

TaskSelectType.Label.SelectChartType=Seleccionar tipo de diagrama

TaskSelectType.Label.SelectSubtype=Seleccionar subtipo

TaskSelectType.Exception.CannotSupportAxes=No se admiten ejes en ChartWithoutAxes.

TaskSelectType.Exception.NotSupportedForMultipleAxes=\ no se admite para ejes múltiples\!

TaskSelectType.Label.ChartTypes=Tipos de diagrama

TaskSelectType.Label.Dimension=&Dimensión:

TaskSelectType.Label.ChartSubtypes=Subtipos de diagrama

TaskSelectData.TaskExp=Seleccionar datos

TaskSelectData.Label.ToBindADataColumn=Use el menú que aparece al hacer clic con el botón derecho del ratón o arrastre la columna a los campos de series.

TaskSelectData.Label.ChartPreview=Vista previa del diagrama

TaskSelectData.Label.SelectDataSet=Seleccionar datos

TaskSelectData.Label.UseReportData=&Heredar datos de contenedor

TaskSelectData.Label.UseReportItem=Usar elemento de info&rme

TaskSelectData.Label.UseDataSet=Usar conjunto de &datos

TaskSelectData.Label.CreateNew=&Crear nuevo...

TaskSelectData.Label.DataPreview=Vista previa de datos

TaskSelectData.Label.DataBinding=Enl&ace de datos...

TaskSelectData.Warning.TypeCheck=El tipo de datos de {0} no es compatible con {1}, corrija la expresión.

TaskSelectData.Label.Filters=Fil&tros...

TaskSelectData.Label.Parameters=&Parámetros...

TaskSelectData.Task.Description=Seleccione los datos que mostrar en el diagrama y vincúlelos a la serie.

TaskSelectData.Exception.UnableToSwitchToDataset=No es posible cambiar al conjunto de datos

TaskSelectData.Label.InsertAggregation=Insertar agregación

TaskSelectData.Label.DataExpressionBuilder=Compilador de expresiones de datos

TaskSelectData.Label.Component=\ Componente

TaskSelectData.Label.Overlay=Superposición

TaskSelectData.Label.Series=Series

TaskSelectData.Label.UseAsCategoryXAxis=Usar como eje (X) de la categoría

TaskSelectData.Label.UseAsCategorySeries=Usar como serie de categoría

TaskSelectData.Label.PlotAsValueYSeries=Dibujar como serie (Y) del valor

TaskSelectData.Tooltip.CreateNewDataset=Crear un nuevo conjunto de datos

TaskSelectData.Label.PlotAsGaugeValue=Dibujar como valor métrico

TaskSelectData.Label.PlotAsValueSeries=Dibujar como serie del valor

TaskSelectData.Label.UseToGroupYSeries=Usar para agrupar serie Y

TaskSelectData.Label.EnableLivePreview=Activar la vista previa del diagrama en tiempo real

TaskSelectData.Label.UseToGroupValueSeries=Usar para agrupar serie del valor

TaskFormatChart.TaskExp=Formato de diagrama

TaskFormatChart.Label.Preview=Vista previa del diagrama

TaskFormatChart.LivePreviewTask.BindData=Recuperando y enlazando datos para vista previa de diagrama

TaskFormatChart.Task.Description=Realice un ajuste preciso del diagrama definiendo las propiedades de la serie, la interactividad, el diseño, así como el formato general de texto, las sombras, el fondo y los bordes.

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=Se ha especificado un índice de columna {0} no válido o no se han definido aún columnas.

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=Se ha especificado un índice de columna no válido.

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=Se ha especificado un índice de columna {0} no válido. La tabla tiene sólo {1} columnas.

CustomPreviewTable.Exception.RowIndexGreaterThan0=El índice de fila debe ser superior o igual a 0.

AbstractSelectDataCustomizeUI.Label.SeriesGrouping=Agrupación de series

AbstractSelectDataCustomizeUI.Label.YAxis=Eje Y

AbstractSelectDataCustomizeUI.Label.Series=Series

AbstractScaleSheet.Label.ShowValuesOutside=Mostrar valores &fuera de rango de eje

MultipleHyperlinksComposite.Btn.Add=&Añadir

MultipleHyperlinksComposite.Btn.Delete=&Eliminar

MultipleHyperlinksComposite.Btn.Down=Aba&jo

MultipleHyperlinksComposite.Btn.Edit=&Editar

MultipleHyperlinksComposite.Btn.Properties=&Propiedades

MultipleHyperlinksComposite.Btn.Up=A&rriba

MultipleHyperlinksComposite.Group.Hyperlinks=Hyperlinks

MultipleHyperlinksComposite.Label.Tooltip=Información sobre la herramien&ta:

MultipleSeriesComponent.Label.OptionalYSeriesGrouping=Agrupación de series Y &opcional:

MultipleSeriesComponent.Label.OptionalOverlayGrouping=Agrupación de superposición &opcional:

MultipleSeriesComponent.Label.OptionalGrouping=Agrupación &opcional:

MultipleSeriesComponent.Label.GroupSorting=&Orden de grupo:

SelectDataChartWithAxisUI.Label.ValueYSeries=Serie (Y) del valor:

MultipleSeriesComponent.Label.Series=Series

SelectDataChartWithoutAxisUI.Label.Series=Series

DataDefinitionSelector.Label.Series=Series

DataDefinitionSelector.Text.NewSeries=<Nueva serie...>

DataDefinitionSelector.Text.NewAxis=<Nuevo eje...>

DataDefinitionSelector.Tooltip.RemoveSeries=Quitar series seleccionadas

DataDefinitionSelector.Tooltip.RemoveAxis=Quitar eje seleccionado

DataDefinitionSelector.Label.YAxis=Eje Y

DataDefinitionSelector.Label.Axis=Eje

DataDefinitionSelector.Label.DeleteAxis=Eliminar eje

DataDefinitionSelector.Label.DeleteSeries=Eliminar serie

DialBottomAreaComponent.Label.Dial=Cuadrante

DialBottomAreaComponent.Label.GaugeValueDefinition=Definición de valor métrico:

PieBottomAreaComponent.Label.TheExplosionCondition=La condición de separación permite la separación por cortes basada en la condición.

PieBottomAreaComponent.Label.TheAmplitudeOfTheExplosion=La amplitud de la separación especifica cuánto se ha separado el corte.

AxisGridLinesSheet.MajorLabel.LineIsVisible=&Visible

AxisGridLinesSheet.MajorLabel.TickIsVisible=V&isible

AxisGridLinesSheet.MinorLabel.LineIsVisible=Vi&sible

AxisGridLinesSheet.MinorLabel.TickIsVisible=Visib&le

AxisLabelSheet.Label.Ellipsis=Elips&is:

AxisLabelSheet.Label.Ellipsis.Tooltip=Establece el número mínimo de caracteres que se deben mostrar antes de la elipsis.

AxisSheetImpl.Label.Aligned=Alineado

AxisSheetImpl.Label.Axis=Eje

AxisSheetImpl.Label.AxisPercent=Eje de porcentaje

AxisSheetImpl.Label.Visible=Visible

AxisSheetImpl.Label.ValueY=Valor (Y)

AxisYSheetImpl.Label.Labels=E&tiquetas:

AxisSheetImpl.Label.Type=Tipo

AxisSheetImpl.Label.Color=Color

AxisYSheetImpl.Label.Title=&Título:

AxisYSheetImpl.Label.Scale=Escala de eje

AxisYSheetImpl.Label.Scale&=E&scala

AxisSheetImpl.Label.CategoryX=Categoría (X)

AxisSheetImpl.Label.AncillaryZ=Complementario (Z)

AxisSheetImpl.Label.SideBySide=En paralelo

AxisXSheetImpl.Label.Visible=Visible

AxisYSheetImpl.Label.LabelFormat=Etiqueta de eje

AxisYSheetImpl.Label.LabelFormat&=&Etiqueta

AxisYSheetImpl.Label.TitleFormat=Título de eje

AxisYSheetImpl.Label.TitleFormat&=&Título

AxisYSheetImpl.Label.Gridlines=Líneas de cuadrícula de eje

AxisYSheetImpl.Label.Gridlines&=Líneas &de cuadrícula

AbstractAxisSubtask.Button.Fixed=Fijo

AbstractAxisSubtask.Lbl.IsCategoryAxis=Es el eje de la &categoría

AbstractAxisSubtask.Label.Visible2=V&isible

AbstractScaleSheet.Label.StepNumber=&Número de pasos:

AxisYSheetImpl.Label.Markers=Marcadores de eje

AxisYSheetImpl.Label.Markers&=&Marcadores

AxisZSheetImpl.Label.Visible=&Visible

AxisXSheetImpl.Label.AxisData=Datos del eje

AbstractAxisSubtask.Label.Stagger=Esca&lonar

AbstractAxisSubtask.Label.Interactivity=Interactividad de eje

AbstractAxisSubtask.Label.LabelSpan=Extensión de &etiqueta:

AbstractAxisSubtask.Label.Points=(Puntos)

AbstractAxisSubtask.Label.ReverseCategory=Invertir &categorías

AxisTextSheet.Label.Interval=Int&ervalo:

AxisMarkersSheet.Title.MarkerLine=Línea de marcador

AxisMarkersSheet.Label.Label=&Etiqueta:

AxisMarkersSheet.Title.MarkerRange=Intervalo de marcador

ChartLegendSheetImpl.Label.Outline=Contorno:

ChartLegendSheetImpl.Label.ShowValue=Mostrar &valor

ChartPlotSheetImpl.Label.Background=Fon&do:

ChartPlotSheetImpl.Label.Background2=Fon&do:

ChartPlotSheetImpl.Label.ClientArea=Área del cliente

ChartTitleSheetImpl.Text.Auto=&Automático

ChartTitleSheetImpl.Text.TitleLayout=Diseño de título

ChartTitleSheetImpl.Text.Layout&=&Diseño

ChartTitleSheetImpl.Text.TitleText=Texto de título

ChartTitleSheetImpl.Text.TitleText&=&Texto

ChartSheetImpl.Title.ChartTitle=Título de diagrama

ChartSheetImpl.Title.ChartArea=Área del diagrama

ChartSheetImpl.Label.Visible=&Visible

ChartSheetImpl.Label.ColorBy=&Color por:

ChartSheetImpl.Label.Coverage=Cober&tura:

ChartSheetImpl.Label.Background=Fon&do:

ChartLegendSheetImpl.Label.Entries=&Entradas

ChartLegendSheetImpl.Label.LegendTitle&=&Título

ChartLegendSheetImpl.Title.LegendLayout=Diseño de leyenda

ChartLegendSheetImpl.Tooltip.ShowDataPointValue=Muestra el valor punto de datos de la primera línea situada bajo el texto de entrada de la leyenda para cada entrada de leyenda.

ChartLegendSheetImpl.Title.LegendEntries=Entradas de leyenda

ChartLegendSheetImpl.Title.LegendTitle=Título de leyenda

ChartLegendSheetImpl.Label.Layout=Di&seño

ChartLegendSheetImpl.Label.Legend=Leyenda

ChartLegendSheetImpl.Label.Title=Tít&ulo:

ChartLegendSheetImpl.Label.Value=Valor:

ChartLegendSheetImpl.Title.Tooltip=Información sobre herramientas de leyenda

ChartLegendSheetImpl.Label.Interactivity=Interactividad de leyenda

ChartPlotSheetImpl.Label.AreaIncludingAxes=Área incluidos ejes

ChartSheetImpl.Label.EnableInPreview=&Vista previa

ChartSheetImpl.Label.Font=Fuen&te:

ChartSheetImpl.Label.ResetValue=Restablecer &valor

ChartPlotSheetImpl.Label.AreaWithinAxes=Área dentro de los ejes

ChartSheetImpl.Label.Style=&Estilo:

ChartSheetImpl.Label.None=Ninguno

ChartSheetImpl.Text.Outline=Contorno

ChartSheetImpl.Text.Outline&=C&ontorno

ChartSheetImpl.Text.GeneralProperties=Propiedades generales

ChartSheetImpl.Text.GeneralProperties&=Propiedades &generales

ChartSheetImpl.Text.TitleInteractivity=&Interactividad del título

ChartSheetImpl.Text.CustomProperties=Propiedades de personalización

ChartSheetImpl.Text.CustomProperties&=Propiedades de personaliza&ción

ChartSheetImpl.Text.ChartAreaInteractivity=Inter&actividad del área de diagrama

ChartSheetImpl.Label.Interactivity=Interactividad de área de diagrama

ChartSheetImpl.Label.InteractivityEnable=&Activar interactividad de diagrama

ChartSheetImpl.Label.Text=Te&xto:

ChartLegendSheetImpl.Label.LegendBehaviorType=Compo&rtamiento:

ChartLivePreviewThread_Text.PleaseWait=, espere...

ChartLivePreviewThread.ErrorMessage.NoDataEngine=No hay motor de datos para procesar los datos. Consulte la excepción anterior para obtener más información.

SeriesSheetImpl.Label.Type=Tipo

SeriesSheetImpl.Label.ZOrder=Orden en Z

LegendTextSheet.Label.Ellipsis=&Elipsis:

LegendTextSheet.Label.Font=&Fuente:

LegendTextSheet.Label.Separator=Separador

LegendTextSheet.Tooltip.Ellipsis=Establece el número mínimo de caracteres que se deben mostrar antes de la elipsis.

MoreOptionsChartLegendSheet.Label.TextArea=Área de texto

MoreOptionsChartLegendSheet.Label.Outline=Contorno

MoreOptionsChartLegendSheet.Label.LegendArea=Área de la leyenda

MoreOptionsChartPlotSheet.Label.AreaIncludingAxes=Área incluidos ejes

MoreOptionsChartPlotSheet.Label.Interactivity=Interactividad

MoreOptionsChartPlotSheet.Label.AreaWithinAxes=Área dentro de los ejes

MoreOptionsChartPlotSheet.Label.Anchor=Delimit&ador:

MoreOptionsChartPlotSheet.Label.Outline=Contorno

MoreOptionsChartPlotSheet.Label.Stretch=&Extensión:

TitlePropertiesSheet.Label.Title=&Título

TitlePropertiesSheet.Label.Visible=Visible

TitlePropertiesSheet.Label.Anchor=&Delimitador:

TitlePropertiesSheet.Label.Stretch=&Extensión:

TitlePropertiesSheet.Label.Outline=Contorno

TitlePropertiesSheet.Label.Text=Texto

BaseDataDefinitionComponent.Text.SpecifyDataDefinition=Especificar definición de datos

BaseDataDefinitionComponent.Label.EditGroupSorting=Editar agrupación y orden
BaseDataDefinitionComponent.Tooltip.InputValueExpression=Expresión del valor de entrada

BaseDataDefinitionComponent.Text.EditFormat=Editar formato

BaseDataDefinitionComponent.WarningMessage.ExpressionsForbidden=No se pueden seleccionar expresiones de una dimensión para establecer en serie de categoría e Y opcional al mismo tiempo.

BaseGroupSortingDialog.Label.SortOn=&Ordenar según:

MarkerEditorComposite.Button.Outline=C&ontorno

MarkerEditorComposite.Label.MarkerType=Tipo

MarkerIconDialog.Button.EmbeddedImage=I&magen incrustada

MarkerIconDialog.Title.MarkerIconSelector=Selector de icono de marcador

MarkerIconDialog.Label.Description.EmbeddedImage=Seleccionar imagen incrustada como icono de marcador.

MarkerIconDialog.Lbl.SelectIconFrom=Seleccionar icono desde:

MarkerIconDialog.Lbl.URL=&URL

MarkerIconDialog.Lbl.Local=&Local

MarkerIconDialog.Lbl.EnterURL=&Introducir URL:

MarkerIconDialog.Lbl.Browse=&Examinar

MarkerIconDialog.Lbl.Preview=&Vista previa

MarkerIconDialog.Lbl.Add=Añadir

MarkerIconDialog.Chooser.Title=Selector de icono de marcador

MarkerIconDialog.Lbl.Remove=Quitar

MarkerIconDialog.Lbl.Description=Importar el icono de marcador de los archivos de imagen local.

MarkerIconDialog.Exception.ImageNotAvailable=La imagen no está disponible actualmente.

MarkerIconDialog.Exception.InvalidURL=URL no válida, corríjala.

MarkerIconDialog.ImageNotAvailableWarning=Advertencia

MarkerIconDialog.ImageNotAvailableWarningMessage=¿Desea usarla de todas formas?

exception.data.DataBindingsAreNull=Uno o varios enlaces de datos son nulos.

DialLabelSheet.Label.Format=Formato:

ImageDialog.AddImage=&Añadir imagen...

ImageDialog.FileExist=El nombre de archivo ya existe, cámbielo y cárguelo de nuevo.

ImageDialog.ImportFail=Error al importar

ImageDialog.label.SelectImageType=Seleccionar tipo de imagen:

ImageDialog.label.URLImage=Imagen de &URL

ImageDialog.label.EmbeddedImage=I&magen incrustada

ImageDialog.label.EnterURL=&Introducir URI de la imagen:

ImageDialog.label.EnterEmbed=&Introduzca la ruta de la imagen que va a incrustar:

ImageDialog.label.Browse=&Examinar...

ImageDialog.label.SelectFile=Seleccionar archivo

ImageDialog.label.Preview=Vista &previa

ImageDialog.Label.ResourceImage=Archivo de &imagen en recursos compartidos

ImageDialog.label.SelectImage=Seleccionar imagen

ImageDialog.uri.tooltip=(Ejemplos: http://host/cursor.gif, uri/cursor.gif)

ImageDialog.label.LocalImage=Archivo de imagen l&ocal

ImageDialog.label.EnterLocal=Introduzca la ruta de la imag&en local:

TextEditorComposite.Tooltip.EnterDecimalOrFractionValue=Introduzca un valor entero, decimal o de fracción

PlotClientAreaSheet.Btn.Auto=A&utomática

PlotClientAreaSheet.Btn.Auto2=Aut&omático

PlotClientAreaSheet.Label.HeightHint=Sugerencia de a&ltura:

PlotClientAreaSheet.Label.WidthHint=Sugerencia de a&nchura:


AxisMarkersSheet.MarkerLine.displayName=MarkerLine
AxisMarkersSheet.MarkerRange.displayName=MarkerRange
AxisMarkersSheet.Label.Interactivity=&Interactividad

AxisMarkersSheet.Label.IsVisible=Vi&sible

AbstractPopupSheet.Label.Close=Cerrar

AbstractPopupSheet.Label.Help=Ayuda

AggregateEditorComposite.Aggregate.Enabled=Activado

AggregateEditorComposite.AggregateDisplayName.Default=Predeterminado

AggregateEditorComposite.AggregateDisplayName.None=Ninguno

AggregateEditorComposite.AggregateParameterDefinition.Title=Agregar definición de parámetro

AggregateEditorComposite.Button.Cancel=Cancelar

AggregateEditorComposite.Button.OK=Aceptar

AggregateEditorComposite.Tooltip.SetAggregateFunction=Establecer función de agregación

LocalizedNumberEditorComposite.error.Title=Error de formato de número

LocalizedNumberEditorComposite.error.Message=Valor de número no válido: "{0}"

SeriesRegionSheet.message.dialRegion=RegiónCuadrante -

GroupSortingDialog.Composite.Group.Sorting=Ordenar

GroupSortingDialog.Composite.Label.SortLocale=&Configuración regional:

GroupSortingDialog.Composite.Label.SortStrength=Intensida&d:

GroupSortingDialog.Label.GroupAndSorting=Agrupación y orden
GroupSortingDialog.Sort.Locale.Auto=Automático

GroupSortingDialog.Sort.Strength.ASCII=ASCII
GroupSortingDialog.Sort.Strength.IDENTICAL=IDÉNTICO

GroupSortingDialog.Sort.Strength.PRIMARY=PRIMARIO

GroupSortingDialog.Sort.Strength.QUATENARY=CUATERNARIO

GroupSortingDialog.Sort.Strength.SECONDARY=SECUNDARIO

GroupSortingDialog.Sort.Strength.TERTIARY=TERCIARIO

GroupSortingDialog.Sort.SortOn.Warning.Title=Advertencia de SortOn

GroupSortingDialog.Sort.SortOn.Warning.Message=La expresión SortOn no puede estar vacía.

GanttSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para GanttSeriesAttributeComposite.

GanttChart.Txt.DefaultGanttChartTitle=Título del diagrama de Gantt

GanttChart.Txt.DisplayName=Gantt

GanttChart.Txt.Description=Los diagramas de Gantt estándar contienen una línea de conexión con marcadores de inicio y finalización.

GanttChart.Txt.HelpText=El objetivo de los diagramas de Gantt es mostrar el tiempo de las tareas o actividades según se producen.

GanttChart.SubType.Standard=Diagrama de Gantt estándar

GanttSeriesAttributeComposite.Lbl.Marker=Marcadores

GanttSeriesAttributeComposite.Lbl.Start=Inicio:

GanttSeriesAttributeComposite.Lbl.End=Final:

GanttSeriesAttributeComposite.Lbl.Bars=Barras

GanttSeriesAttributeComposite.Lbl.Outline=Contorno

GanttSeriesAttributeComposite.Lbl.OutlineFill=Relleno de contorno:

GanttSeriesAttributeComposite.Lbl.BarPalette=Usar &paleta de series como color de barra

DecorationSheet.Label.DecorationLabels=Etiquetas de tareas

BubbleChart.Txt.DefaultBubbleChartTitle=Título del diagrama de burbujas

BubbleChart.Txt.Description=Los diagramas de burbujas organizan los valores en el dibujo usando los datos de categoría y de valor como coordenadas. \nCada valor de datos se indica con un marcador.

BubbleChart.Txt.HelpText=Los diagramas de burbujas muestran los valores de los datos espaciados aleatoriamente asociados con ejes que no son de categoría. Cada punto de datos se asocia con la escala del eje X e Y.

BubbleChart.Txt.DisplayName=Burbuja

BubbleChart.SubType.Standard=Diagrama de burbujas estándar

BubbleSeriesAttributeComposite.Lbl.ShadowColor=&Sombra:

BubbleSeriesAttributeComposite.Lbl.Marker=Marcador

BubbleSeriesAttributeComposite.Lbl.IsVisible=Visible

BubbleSeriesAttributeComposite.Lbl.Type=Tipo:

BubbleSeriesAttributeComposite.Lbl.Size=Tamaño:

BubbleSeriesAttributeComposite.Lbl.Line=Línea

BubbleSeriesAttributeComposite.Lbl.AccLine=Línea de aceleración

BubbleSeriesAttributeComposite.Lbl.LinePalette=Usar &paleta de series como color de línea

BubbleSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para BubbleSeriesAttributeComposite.

BubbleSeriesAttributeComposite.Lbl.ShowLinesAsCurves=Mostrar líneas como cur&vas

BubbleSeriesAttributeComposite.Lbl.Orientation=&Orientación

DifferenceChart.Txt.DefaultDifferenceChartTitle=Título de diagrama de diferencias

DifferenceChart.Txt.Description=Los diagramas de diferencias utilizan dos rellenos para representar las zonas positivas y negativas.

DifferenceChart.Txt.HelpText=Los diagramas de diferencias se suelen utilizar para representar diferencias entre dos campos de datos.

DifferenceChart.Txt.DisplayName=Diferencia

DifferenceChart.SubType.Standard=Diagrama de diferencias estándar

DifferenceSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para DifferenceSeriesAttributeComposite.

DifferenceSeriesAttributeComposite.Lbl.Line=Líneas

DifferenceSeriesAttributeComposite.Lbl.PositiveLine=Positivo

DifferenceSeriesAttributeComposite.Lbl.NegativeLine=Negativo

DifferenceSeriesAttributeComposite.Lbl.ShowLinesAsCurves=Mostrar líneas como cur&vas

DifferenceSeriesAttributeComposite.Lbl.LinePalette=&Usar paleta de series como color de línea

PositiveNegativeColorDialog.Lbl.PositiveNegativeColorEditor=Editor de colores positivo/negativo

PositiveNegativeColorDialog.Lbl.PositiveColor=Color positivo

PositiveNegativeColorDialog.Lbl.NegativeColor=Color negativo

PositiveNegativeColorDialog.Lbl.Preview=Vista previa

########### Field Assist Preferences ###########################
ssPreferencesContentAssistKey= Tecla de ayuda de contenido:

ssPreferencesContentAssistKeyCtlSpace= Ctrl+&Espacio

ssPreferencesContentAssistKeyAsterisk= * (Aster&isco)

ssPreferencesContentAssistKeyAnyKey= Tec&la alfanumérica (en retardo de activación automática)

ssPreferencesContentAssistKeyCustom= &Personalizada

ssPreferencesContentAssistKeyPropagate= &Propagar pulsaciones para controlar cuándo está activo el elemento emergente

ssPreferencesContentAssistDelay= Retar&do (en milisegundos) cuando la ayuda de contenido está activada automáticamente:

ssPreferencesDescription= Esta página controla la decoración utilizada en el cuadro de diálogo del compilador de diagrama.

ssPreferencesDecoratorVert= Ubicación vertical:

ssPreferencesDecoratorTop= &Arriba

ssPreferencesDecoratorCenter= &Centro

ssPreferencesDecoratorBottom= &Abajo

ssPreferencesDecoratorHorz= Ubicación horizontal:

ssPreferencesDecoratorLeft= &Izquierda

ssPreferencesDecoratorRight= &Derecha

ssPreferencesDecoratorMargin= Anc&ho de margen:

ssPreferencesContentAssistDescription= Esta página controla el comportamiento de la ayuda de contenido.

ssPreferencesContentAssistResult= Cuando se selecciona una propuesta de contenido:

ssPreferencesContentAssistResultReplace= Ree&mplazar contenido de campo

ssPreferencesContentAssistResultInsert= Insertar en c&ontenido de campo

ssPreferencesContentAssistFilter= Al escribir mientras el elemento emergente está abierto:

ssPreferencesContentAssistFilterCumulative= &Filtrar contenido emergente con escritura acumulativa

ssPreferencesContentAssistFilterCharacter= Filtrar elemento emer&gente según el último carácter escrito

ssPreferencesContentAssistFilterNone= &No filtrar

ssPreferencesShowRequiredFieldLabelIndicator= &Identificar los campos necesarios

ssPreferencesAssistSymbol= Ubicación del símbolo de ayuda

ssDecoratorContentAssist= Este campo dispone de ayuda de contenido, pulse {0}

ssDecorationMenuItem=Eliminar caracteres no válidos


### Multiple Hyperlinks ###
MenuStyleDialog.Column.Properties=Propiedades

MenuStyleDialog.Column.Value=Valor

MenuStyleDialog.Style.Menu=Menú

MenuStyleDialog.Style.MenuItem=Elemento de menú

MenuStyleDialog.Style.OnMouseOver=Al pasar el ratón

MenuStyleDialog.Style.OnMouseOut=Al mover el ratón fuera

MenuStylesDialog.Btn.Add=&Añadir

MenuStylesDialog.Btn.Remove=&Quitar

MenuStylesDialog.Label.Style=&Estilo:

MenuStylesDialog.title=Propiedades del menú de hyperlink

MenuStylesDialog.Title=Estilos del menú de hyperlink

ItemLabel.Auto=Automático
