Shared.Lbl.OK=\ \ \ OK

Shared.Lbl.Cancel=Annuler

Shared.Lbl.Triggers=Déclencheurs

Shared.Tooltip.FormatSpecifier=Appeler l'éditeur de spécification de format

Shared.mne.Visibile_v=&Visible

Shared.mne.Visibile_s=Vi&sible

Shared.mne.Background_K=A&rrière-plan :

ChartWithAxesImpl.Z_Axis.title=Titre de l'axe des z

ChartSheetImpl.Buttom.Auto=A&uto

ChartSheetImpl.Button.AutoHide=Masquer le graphique s'il n'y a pas de &données à afficher.

ChartSheetImpl.Button.EnableStudyLayout=Activer la mise en page de l'étude

ChartSheetImpl.Button.ShowEmptyMsg=Afficher le graphique avec le &message suivant :

ChartSheetImpl.Group.EmptyMessage=Visibilité

ChartSheetImpl.Group.EmptyMessage&=&Visibilité

ChartSheetImpl.Label.Outline=Contour :

ChartLegendImpl.Group.Rotation=Rotation

ChartPlotSheetImpl.Label.Outline=Contour :

ChartPlotSheetImpl.Label.Visible=&Visible

ChartPlotSheetImpl.Label.Visible2=V&isible

ChartPlotSheetImpl.Label.PlotArea=Zone de tracé

ChartPlotSheetImpl.Label.AreaFormat=Format de la zone

ChartPlotSheetImpl.Label.AreaFormat&=&Format de la zone

ChartTitleSheetImpl.Label.ChartTitle=Titre du grap&hique :

ChartTitleSheetImpl.Label.Interactivity=Interactivité du titre

ChartTitleSheetImpl.Titel.Tooltip=Titre de l'infobulle

ChartTitleSheetImpl.Label.Tooltip=Infobulle :

ScriptSheetImpl.Lbl.Script=Script :

ScriptSheetImpl.Lbl.Update=Mettre à jour

ScriptSheetImpl.Title.SheetTitle=Scripts - Définir/Modifier les scripts du graphique

GeneralSheetImpl.Lbl.ChartTitle=Titre du graphique :

GeneralSheetImpl.Lbl.Description=&Description :

GeneralSheetImpl.Lbl.GeneralProperties=Propriétés générales

GeneralSheetImpl.Lbl.Type=Type :

GeneralSheetImpl.Lbl.Subtype=Sous-type :

GeneralSheetImpl.Lbl.Units=Unités :

GeneralSheetImpl.Lbl.ColumnCount=Nombre de\ncolonnes :

GeneralSheetImpl.Lbl.ChartBackground=Arrière-plan :

GeneralSheetImpl.Lbl.ChartWall=Parois :

GeneralSheetImpl.Lbl.ChartFloor=Base :

GeneralSheetImpl.Lbl.ChartOutline=Contour du graphique

GeneralSheetImpl.Lbl.TitleProperties=Propriétés du titre

GeneralSheetImpl.Lbl.ExtendedProperties=Propriétés étendues

GeneralSheetImpl.Lbl.SeriesWidth=&Profondeur de la série : \n ({0})

GeneralSheetImpl.Title.SheetTitle=Général - Définir les propriétés générales du graphique

BaseAxisDataSheetImpl.Lbl.Type=Type :

BaseAxisDataSheetImpl.Lbl.Title=Titre de l'axe :

BaseAxisDataSheetImpl.Lbl.Origin=Origine :

BaseAxisDataSheetImpl.Lbl.Value=Vale&ur :

BaseAxisDataSheetImpl.Lbl.YAxisCount=Nombre d'axes Y :

AbstractScaleSheet.AutoExpand=Développer a&utomatiquement

AbstractScaleSheet.Label.Step=Escalier

AbstractScaleSheet.Label.Auto=&Automatique

AbstractScaleSheet.Label.Factor=&Facteur (Valeur/Points) :

BaseAxisDataSheetImpl.Lbl.Minimum=&Min :

BaseAxisDataSheetImpl.Lbl.MajorGridStepNum=&Numéro de l'escalier de la grille principale :

BaseAxisDataSheetImpl.Lbl.Maximum=Ma&x :

AbstractScaleSheet.Label.StepSize=Intervalle d'étape :

BaseAxisDataSheetImpl.Lbl.Unit=&Unité :

BaseAxisDataSheetImpl.Lbl.MinorGridCount=&Nombre de grilles secondaires par unité :

BaseAxisDataSheetImpl.Lbl.BaseAxis=Axe de catégories

BaseAxisDataSheetImpl.Title.SheetTitle=Données > Axe horizontal - Définir les données de l'axe horizontal

BaseAxisDataSheetImpl.Lbl.BaseAxis2=Axe de catégories ({0})

BaseAxisAttributeSheetImpl.Lbl.GapWidth=Largeur de l'intervalle :

BaseAxisAttributeSheetImpl.Lbl.MajorGrid=Grille principale

BaseAxisAttributeSheetImpl.Lbl.MinorGrid=Grille secondaire

BaseAxisAttributeSheetImpl.Lbl.Orientation=Orientation

BaseAxisAttributeSheetImpl.Lbl.PercentSign=%
BaseAxisAttributeSheetImpl.Lbl.ShowAxisLine=Afficher la ligne de l'a&xe

BaseAxisAttributeSheetImpl.Lbl.IsTickBetweenCategories=Croi&sement entre des catégories

BaseAxisAttributeSheetImpl.Lbl.AxisLineColor=&Couleur de la ligne de l'axe :

BaseAxisAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'axe... Le graphique doit être de type ChartWithAxes

BaseAxisAttributeSheetImpl.Title.SheetTitle=Attributs > Axe horizontal - Personnaliser les attributs de l'axe horizontal

BaseAxisMarkerAttributeSheetImpl.Lbl.Value=Vale&ur :

BaseAxisMarkerAttributeSheetImpl.Lbl.Anchor=An&cre :

BaseAxisMarkerAttributeSheetImpl.Lbl.Fill=&Remplissage :

BaseAxisLabelAttributeSheetImpl.Lbl.Label=Etiquette

BaseAxisLabelAttributeSheetImpl.Lbl.Title=Titre

BaseAxisLabelAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'étiquette d'axe... Le graphique doit être de type ChartWithAxes

BaseAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=Afficher les étiquettes de façon échelonnée

BaseAxisLabelAttributeSheetImpl.Title.SheetTitle=Attributs > Axe horizontal > Etiquettes - Personnaliser les étiquettes de l'axe horizontal

BaseAxisMarkerAttributeSheetImpl.Lbl.AddLine=&Ajouter une ligne

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRange=A&jouter une plage

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRegion=&Ajouter une zone

BaseAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=&Retirer une entrée

BaseAxisMarkerAttributeSheetImpl.Lbl.StartValue=Valeur de débu&t :

BaseAxisMarkerAttributeSheetImpl.Lbl.EndValue=&Valeur de fin :

BaseAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=Contour de la gamme

BaseAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ pour axe

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=Attributs de lignes de repères

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=Propriétés de repères

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0} {1}
BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange {0} {1}
BaseAxisMarkerAttributeSheetImpl.Title.SheetTitle=Attributs > Axe horizontal > Repères - Définir les repères de l'axe horizontal

BaseAxisMarkerAttributeSheetImpl.Lbl.InnerRadius=Rayon &interne :

BaseAxisMarkerAttributeSheetImpl.Lbl.OuterRadius=Rayon &externe :

BaseAxisMarkerAttributeSheetImpl.Lbl.DialProperties=Propriétés de la zone

BaseAxisMarkerAttributeSheetImpl.Lbl.DialLabelProperties=Propriétés de l'étiquette de la zone

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=Propriétés de l'étiquette du repère

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveDown=&Vers le bas

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveUp=Vers le &haut

BaseAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut de repère d'axe... Le graphique doit être de type ChartWithAxes

BaseSeriesDataSheetImpl.Choice.Unsorted=Non trié

BaseSeriesDataSheetImpl.Lbl.DataSorting=Tri des &données :

BaseSeriesDataSheetImpl.Lbl.YSeriesCount=Nombre de série Y :

BaseSeriesAttributeSheetImpl.Lbl.Palette=Palette

BaseAxisDataSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'axe... Le graphique doit être de type ChartWithAxes

BaseSeriesAttributeSheetImpl.Lbl.SeriesType=Type de séries :

BaseSeriesAttributeSheetImpl.Title.SheetTitle=Attributs > Série X - Personnaliser les attributs de la série de catégorie (X)

BaseSeriesDataSheetImpl.Lbl.DataDefinitions=Définitions de données

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinitions=Définitions de séries de valeurs

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinition=Définition de série de valeurs

BaseSeriesDataSheetImpl.Title.SheetTitle=Données > Série horizontale de catégories - Définir les données de la série horizontale de catégories

BaseSeriesDataSheetImpl.Lbl.DialSeriesCount=Nombre de cadrans :

BaseSeriesDataSheetImpl.Lbl.DialSeriesDefinitions=Définitions de séries de cadrans

DialScaleDialog.Title.DialScale=Echelle du cadran

DialTicksDialog.Title.DialTicks=Repères du cadran

OrthogonalAxisAttributeSheetImpl.Lbl.HideAxisLine=Masquer la ligne d'axe

OrthogonalAxisAttributeSheetImpl.Lbl.Orientation=Orientation

OrthogonalAxisAttributeSheetImpl.Lbl.PercentSign=%
OrthogonalAxisAttributeSheetImpl.Lbl.GapWidth=Largeur de l'intervalle :

OrthogonalAxisAttributeSheetImpl.Lbl.MajorGrid=Grille principale

OrthogonalAxisAttributeSheetImpl.Lbl.MinorGrid=Grille secondaire

OrthogonalAxisAttributeSheetImpl.Lbl.AxisLineColor=Couleur de la ligne de l'axe :

OrthogonalAxisAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'axe... Le graphique doit être de type ChartWithAxes

OrthogonalAxisAttributeSheetImpl.Title.SheetTitle=Attributs > Axe vertical - Personnaliser les attributs de l'axe vertical

OrthogonalAxisDataSheetImpl.Lbl.Type=Ty&pe :

OrthogonalAxisDataSheetImpl.Lbl.Title=Titre de l'axe :

OrthogonalAxisDataSheetImpl.Lbl.Origin=&Origine :

OrthogonalAxisDataSheetImpl.Lbl.Value=Valeur :

OrthogonalAxisDataSheetImpl.Lbl.PrimaryAxis=Est l'axe principal

OrthogonalAxisDataSheetImpl.Lbl.Scale=Echelle

OrthogonalAxisDataSheetImpl.Lbl.Minimum=Min :

OrthogonalAxisDataSheetImpl.Lbl.Maximum=Max :

OrthogonalAxisDataSheetImpl.Lbl.Step=Escalier :

OrthogonalAxisDataSheetImpl.Lbl.Unit=Unité :

OrthogonalAxisDataSheetImpl.Lbl.MinorGridCount=Nombre de grilles secondaires par unité :

OrthogonalAxisDataSheetImpl.Lbl.SeriesDefinitionCount=Nombre de définitions de série :

OrthogonalAxisDataSheetImpl.Lbl.SeriesGroupingKey=Clé de groupe de séries (facultatif)

OrthogonalAxisDataSheetImpl.Lbl.OrthogonalAxis=Axe de valeurs

OrthogonalAxisDataSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'axe... Le graphique doit être de type ChartWithAxes

OrthogonalAxisDataSheetImpl.Title.SheetTitle=Données > Axe vertical - Définir les données de l'axe vertical

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Label=Etiquette

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Title=Titre

OrthogonalAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=Afficher les étiquettes de façon échelonnée

OrthogonalAxisLabelAttributeSheetImpl.Title.SheetTitle=Attributs > Axe vertical > Etiquettes - Personnaliser les étiquettes de l'axe vertical

OrthogonalAxisLabelAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut d'étiquette d'axe... Le graphique doit être de type ChartWithAxes

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Values=Valeur :

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Anchor=Ancre :

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddLine=Ajouter une ligne

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddRange=Ajouter une plage

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.EndValue=Valeur de fin :

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ pour axe {0}

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=Retirer une entrée

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.StartValue=Valeur de début :

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=Contour de la gamme

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0,number,integer} {1}
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange 
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Fill=Remplissage :

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=Propriétés de repères

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=Attributs de lignes de repères

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=Propriétés de l'étiquette du repère

OrthogonalAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=Argument non valide pour la feuille d'attribut de repère d'axe... Le graphique doit être de type ChartWithAxes

OrthogonalSeriesAttributeSheetImpl.Lbl.Remove=&Supprimer

OrthogonalSeriesAttributeSheetImpl.Lbl.Add=&Ajouter

OrthogonalSeriesAttributeSheetImpl.Lbl.Up=Vers le ha&ut

OrthogonalSeriesAttributeSheetImpl.Lbl.Down=&Vers le bas

OrthogonalSeriesAttributeSheetImpl.Lbl.Prefix=Pré&fixe :

OrthogonalSeriesAttributeSheetImpl.Lbl.Suffix=Suffi&xe :

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesType=Type de séries :

OrthogonalSeriesAttributeSheetImpl.Lbl.HideSeries=Masquer séries

OrthogonalSeriesAttributeSheetImpl.Lbl.Palette=Palette

OrthogonalSeriesAttributeSheetImpl.Lbl.DataPoint=Point de données

OrthogonalSeriesAttributeSheetImpl.Lbl.Separator=Séparat&eur :

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDetails=Détails de séries

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPoint=Series DataPoint

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPointComponent=Composant de DataPoint de série - {0}

OrthogonalSeriesAttributeSheetImpl.Lbl.StackSeriesElements=Eléments de série empilés

OrthogonalSeriesAttributeSheetImpl.Title.SheetTitle=Attributs > Série verticale - Personnaliser les attributs de la série verticale de valeurs

OrthogonalSeriesDataSheetImpl.Lbl.Triggers=Interactivité...

OrthogonalSeriesDataSheetImpl.Lbl.DataDefinitions=Définitions de données

OrthogonalSeriesDataSheetImpl.Lbl.Scale=Echelle

OrthogonalSeriesDataSheetImpl.Lbl.Minimum=&Min :

OrthogonalSeriesDataSheetImpl.Lbl.Maximum=Ma&x :

OrthogonalSeriesDataSheetImpl.Lbl.Step=&Escalier :

OrthogonalSeriesDataSheetImpl.Lbl.Unit=Unité :

OrthogonalSeriesDataSheetImpl.Lbl.MinorGridCount=Nombre de grilles secondaires par &unité :

OrthogonalSeriesDataSheetImpl.Lbl.MajorGrid=Grille principale

OrthogonalSeriesDataSheetImpl.Lbl.MinorGrid=Grille secondaire

OrthogonalSeriesDataSheetImpl.Title.SheetTitle=Données > Série verticale de valeurs - Définir les données de la série verticale de valeurs

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Label=Etiquette

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Title=Titre

OrthogonalSeriesLabelAttributeSheetImpl.Title.SheetTitle=Attributs > Série verticale > Etiquettes - Personnaliser les étiquettes de la série verticale de valeurs

AreaChart.Txt.PercentStackedDescription=Les graphiques en aires empilées à pourcentage affichent des aires empilées les unes sur les autres de telle manière \nque la hauteur totale des aires (du point le plus bas au point le plus haut dans chaque unité) représente 100.

AreaChart.Txt.StackedDescription=Les graphiques en aires empilées affichent des aires les unes sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

AreaChart.Txt.OverlayDescription=Les graphiques en aires superposées affichent les aires de chaque série indépendamment des autres. \nLes aires regroupent les valeurs pour la série.

AreaChart.Txt.HelpText=Une aire représente chaque série en cours de rendu. Vous pouvez utiliser des repères facultatifs pour mettre en surbrillance les points pour lesquels les données sont tracées. Les aires empilées affichent chaque point de catégorie par rapport à l'emplacement du point de données de série de la ligne inférieure. Les aires de pourcentage empilées affichent chaque valeur de donnée sous la forme d'un pourcentage du total de la catégorie.

AreaChart.Txt.DefaultAreaChartTitle=Zone du titre du graphique

AreaChart.Txt.DisplayName=Zone

AreaChart.SubType.Stacked=Empilé

AreaChart.SubType.PercentStacked=Empilé à pourcentage

AreaChart.SubType.Overlay=Superposition

AreaSeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

MeterChart.Txt.DefaultMeterChartTitle=Titre de graphique à cadrans

MeterChart.Txt.DisplayName=Valeur

MeterChart.SubType.Standard=Graphique à cadrans standard

MeterChart.SubType.Superimposed=Graphique à cadrans superposé

MeterChart.Tooltip.InputExpression=Entrer une expression affichée comme texte de légende pour chaque élément

MeterChart.Txt.HelpText=Les graphiques à cadrans indiquent la valeur de données actuelle d'une mesure spécifique. Les zones de différentes couleurs représentent les plages de valeurs de mesure. Une aiguille est associée à chaque cadran et en indique la valeur.

MeterChart.Txt.Description=Les graphiques à cadrans standard contiennent un seul cadran par zone(s). \nL'arrière-plan du cadran peut être divisé en zones de différentes couleurs.

MeterChart.Txt.SuperimposedDescription=Les graphiques à cadrans superposés contiennent plusieurs cadrans avec des zones identiques. \nLes cadrans se chevauchent afin que plusieurs aiguilles apparaissent dans une même zone.

MeterSeriesAttributeComposite.Lbl.Radius=Ray&on :

MeterSeriesAttributeComposite.Lbl.StartAngle=An&gle de départ :

MeterSeriesAttributeComposite.Lbl.StopAngle=Angl&e de fin :

MeterSeriesAttributeSheetImpl.Lbl.Type=Type :

MeterSeriesAttributeSheetImpl.Lbl.Fill=Rempl&issage :

MeterSeriesAttributeComposite.Lbl.DialTicks=&Repères

MeterSeriesAttributeComposite.Lbl.DialScale=E&chelle

BarSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour BarSeriesAttributeComposite.

BarSeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

BarSeriesAttributeComposite.Lbl.SeriesOutline=C&ontour de la série :

BarBottomAreaComponent.Label.CategoryXSeries=Série horizontale de &catégories :

StockSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour StockSeriesAttributeComposite.

StockSeriesDataDefinitionComposite.Lbl.StockSeriesDefinition=Définitions de séries d'actions

StockSeriesAttributeComposite.Lbl.CandleFill=Remplissage bougie :

StockSeriesAttributeComposite.Lbl.StickLength=Longueur du bâton :

StockSeriesAttributeComposite.Lbl.Line=Ligne

StockSeriesDataDefinitionComposite.Lbl.High=Elevé :

StockSeriesDataDefinitionComposite.Lbl.HighValue=\ - Valeur élevée :

StockSeriesDataDefinitionComposite.Lbl.Low=Faible :

StockSeriesDataDefinitionComposite.Lbl.LowValue=\ - Valeur faible :

StockSeriesDataDefinitionComposite.Lbl.Open=Ouverte :

StockSeriesDataDefinitionComposite.Lbl.OpenValue=\ - Valeur ouverte :

StockSeriesDataDefinitionComposite.Lbl.Close=Fermée :

StockSeriesDataDefinitionComposite.Lbl.CloseValue=\ - Valeur fermée :

StockChart.Txt.DefaultStockChartTitle=Titre de graphique d'actions

StockChart.Txt.DisplayName=Action

StockChart.Txt.BarStickDescription=Un graphique boursier à barres se présente sous la forme d'une ligne verticale et de deux lignes horizontales associées. \nLes points supérieurs et inférieurs de la ligne verticale correspondent aux valeurs d'ouverture et de fermeture. \nLes deux lignes horizontales correspondent à la valeur la plus élevée et la plus basse.

StockChart.Txt.CandleStickDescription=Un graphique boursier en chandelier se présente sous la forme d'un cadre dont les côtés sont joints par des courbes. \nLes coins supérieurs et inférieurs du cadre correspondent aux valeurs d'ouverture et de fermeture. \nLes points supérieur et inférieur de la ligne correspondent à la valeur la plus élevée et la plus basse.

StockChart.Txt.HelpText=Les graphiques boursiers présentent des éléments graphiques où chaque élément représente une session de transactions unique. L'extrémité supérieure de la ligne indique la valeur la plus élevée de la session. L'extrémité inférieure de la ligne indique la valeur la plus basse de la session. Une barre connecte les valeurs d'ouverture et de fermeture.

StockChart.SubType.CandleStick=Graphique boursier en chandelier

StockChart.SubType.BarStick=Graphique boursier à barres

LineAttributesComposite.Lbl.Style=Style :

LineAttributesComposite.Lbl.Width=Largeur :

LineAttributesComposite.Lbl.Color=Couleur :

LineAttributesComposite.Lbl.IsVisible=Visible

LineSeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

LineSeriesAttributeComposite.Lbl.ShadowColor=O&mbre :

LineSeriesAttributeComposite.Lbl.Marker=Repère

LineChart.Txt.PercentStackedDescription=Les graphiques de lignes empilées à pourcentage affichent des lignes empilées les unes sur les autres de telle manière \nque la hauteur totale des lignes (du point le plus bas au point le plus haut dans chaque unité) représente 100.

LineSeriesAttributeComposite.Lbl.IsVisible=&Visible

LineSeriesAttributeComposite.Lbl.Type=Type :

LineSeriesAttributeComposite.Lbl.Size=&Format :

LineSeriesAttributeComposite.Lbl.Line=Ligne

LineSeriesMarkerSheet.Label.Markers=Repères

LineSeriesMarkerSheet.Label.Add=&Ajouter

LineSeriesMarkerSheet.Label.Remove=&Supprimer

LineSeriesAttributeComposite.Lbl.LinePalette=Utiliser la &palette de séries pour la couleur de trait

LineChart.Txt.DefaultLineChartTitle=Titre de graphique à ligne

LineSeriesAttributeComposite.Lbl.ConnectMissingValue=C&onnecter les valeurs manquantes

LineChart.Txt.DisplayName=Ligne

LineChart.SubType.Stacked=Empilé

LineChart.SubType.PercentStacked=Empilé à pourcentage

LineChart.SubType.Overlay=Superposition

LineChart.Txt.StackedDescription=Les graphiques de lignes empilées affichent des lignes les unes sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

LineChart.Txt.OverlayDescription=Les graphiques à lignes superposées affichent les lignes de chaque série indépendamment des autres. \nLes lignes regroupent les valeurs pour la série.

LineSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour LineSeriesAttributeComposite.

LineSeriesAttributeComposite.Lbl.ShowLinesAsCurves=A&fficher les lignes sous la forme de courbes

LineChart.Txt.HelpText=Une ligne représente chaque série en cours de rendu. Vous pouvez utiliser des repères facultatifs pour mettre en surbrillance les points pour lesquels les données sont tracées. Les lignes empilées affichent chaque point de catégorie par rapport à l'emplacement du point de données de série de la ligne inférieure. Les lignes de pourcentage empilées affichent chaque valeur de donnée sous la forme d'un pourcentage du total de la catégorie.

ScatterChart.Txt.Description=Les graphiques en nuage de points affichent les valeurs disposées sur le tracé en utilisant les données de catégorie et de valeur comme coordonnées. \nChaque valeur de données est indiquée par un repère.

ScatterChart.Txt.HelpText=Les graphiques en nuage de points affichent des valeurs de données espacées au hasard associées à des axes sans rapport avec les catégories. Chaque point de données est associé à l'échelle de l'axe des X et des Y.

ScatterSeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

ScatterChart.Txt.DefaultScatterChartTitle=Titre de graphique en nuage de points

ScatterChart.Txt.DisplayName=Nuage de points

ScatterChart.SubType.Standard=Graphique en nuage de points standard

BarChart.Txt.DefaultBarChartTitle=Titre du graphique à barres

BarChart.Txt.DisplayName=Barre

BarChart.SubType.Stacked=Empilé

BarChart.SubType.PercentStacked=Empilé à pourcentage

BarChart.SubType.Side=Côte à côte

BarChart.Txt.StackedDescription=Les graphiques à barres empilées affichent des barres les unes sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

BarChart.Txt.PercentStackedDescription=Les graphiques à barres empilées à pourcentage affichent les barres empilées les unes sur les autres, de sorte \nque la hauteur totale des barres empilées (du point le plus bas au point le plus haut) atteigne 100.

BarChart.Txt.HelpText=Les graphiques à barres sont créés afin de comparer des classes ou groupes de données. Les valeurs de données de séries différentes dans la même catégorie s'affichent les unes à côté des autres dans des colonnes séparées ou les unes sous les autres dans une seule colonne (en fonction du sous-type sélectionné).

BarChart.Txt.SideBySideDescription=Les graphiques à barres côte à côte affichent les barres de chaque série l'une à côté de l'autre. \nCes barres sont arrangées de sorte qu'elles aient la même largeur. \nLa largeur des barres dépend du nombre de séries tracées.

TubeChart.Txt.DefaultTubeChartTitle=Titre du graphique à cylindres

TubeChart.Txt.DisplayName=Cylindre

TubeChart.SubType.Stacked=Empilé

TubeChart.SubType.PercentStacked=Empilé à pourcentage

TubeChart.SubType.Side=Côte à côte

TubeChart.Txt.StackedDescription=Les graphiques à cylindres empilés affichent des cylindres empilés les uns sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

TubeChart.Txt.PercentStackedDescription=Les graphiques à cylindres empilés à pourcentage affichent les cylindres empilés les uns sur les autres, de sorte \nque la hauteur totale des cylindres empilés (du point le plus bas au point le plus haut) atteigne 100.

TubeChart.Txt.HelpText=Les graphiques à cylindres sont créés afin de comparer des classes ou groupes de données. Les valeurs de données de séries différentes dans la même catégorie s'affichent les unes à côté des autres dans des colonnes séparées ou les unes sous les autres dans une seule colonne (en fonction du sous-type sélectionné).

TubeChart.Txt.SideBySideDescription=Les graphiques à cylindres côte à côte affichent les cylindres de chaque série l'un à côté de l'autre. \nCes cylindres sont arrangés de sorte qu'ils aient la même largeur. \nLa largeur des cylindres dépend du nombre de séries tracées.

ConeChart.Txt.DefaultConeChartTitle=Titre du graphique à cônes

ConeChart.Txt.DisplayName=Cône

ConeChart.SubType.Stacked=Empilé

ConeChart.SubType.PercentStacked=Empilé à pourcentage

ConeChart.SubType.Side=Côte à côte

ConeChart.Txt.StackedDescription=Les graphiques à cônes empilés affichent des cônes empilés les uns sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

ConeChart.Txt.PercentStackedDescription=Les graphiques à cônes empilés à pourcentage affichent les cônes empilés les uns sur les autres, de sorte \nque la hauteur totale des cônes empilés (du point le plus bas au point le plus haut) atteigne 100.

ConeChart.Txt.HelpText=Les graphiques à cônes sont créés afin de comparer des classes ou groupes de données. Les valeurs de données de séries différentes dans la même catégorie s'affichent les unes à côté des autres dans des colonnes séparées ou les unes sous les autres dans une seule colonne (en fonction du sous-type sélectionné).

ConeChart.Txt.SideBySideDescription=Les graphiques à cônes côte à côte affichent les cônes de chaque série l'un à côté de l'autre. \nCes cônes sont arrangés de sorte qu'ils aient la même largeur. \nLa largeur des cônes dépend du nombre de séries tracées.

PyramidChart.Txt.DefaultPyramidChartTitle=Titre du graphique à pyramides

PyramidChart.Txt.DisplayName=Pyramide

PyramidChart.SubType.Stacked=Empilée

PyramidChart.SubType.PercentStacked=Empilée à pourcentage

PyramidChart.SubType.Side=Côte à côte

PyramidChart.Txt.StackedDescription=Les graphiques à pyramides empilées affichent des pyramides empilées les unes sur les autres. \nLes valeurs positives et négatives sont empilées séparément au-dessus et au-dessous de l'origine.

PyramidChart.Txt.PercentStackedDescription=Les graphiques à pyramides empilées à pourcentage affichent les pyramides empilées les unes sur les autres, de sorte \nque la hauteur totale des pyramides empilées (du point le plus bas au point le plus haut) atteigne 100.

PyramidChart.Txt.HelpText=Les graphiques à pyramides sont créés afin de comparer des classes ou groupes de données. Les valeurs de données de séries différentes dans la même catégorie s'affichent les unes à côté des autres dans des colonnes séparées ou les unes sous les autres dans une seule colonne (en fonction du sous-type sélectionné).

PyramidChart.Txt.SideBySideDescription=Les graphiques à pyramides côte à côte affichent les pyramides de chaque série l'une à côté de l'autre. \nCes pyramides sont arrangées de sorte qu'elles aient la même largeur. \nLa largeur des pyramides dépend du nombre de séries tracées.

PieChart.Txt.DefaultPieChartTitle=Titre de graphique à secteurs

PieChart.Txt.DisplayName=Secteur

PieChart.SubType.Standard=Graphique à secteurs standard

PieSeriesUIProvider.Lbl.OrthogonalPrefix=Valeur

PieSeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

PieBottomAreaComponent.Label.Percentage=Pourcentage

PieSeriesAttributeComposite.Button.Direction=Sens des aiguilles d'une montre

PieSeriesAttributeComposite.Button.Direction.ToolTipText=Indique si les secteurs sont affichés dans le sens des aiguilles d'une montre.

PieSeriesAttributeComposite.Button.InnerRadius=Rayon interne :

PieSeriesAttributeComposite.Grp.Slice=Tranche

PieSeriesAttributeComposite.Lbl.SliceOutline=C&ontour de la tranche :

PieSeriesAttributeComposite.Lbl.LeaderLine=Première ligne

PieSeriesAttributeComposite.Lbl.LeaderLineStyle=Style de l&a première ligne :

PieSeriesAttributeComposite.Lbl.LeaderLineLength=&Longueur de la première ligne :

PieBottomAreaComponent.Label.AnySliceWithASize=Les tranches dont la taille est inférieure à l'entrée seront combinées dans une autre catégorie.

PieBottomAreaComponent.Label.ExplodeSliceWhen=E&clater la tranche quand :

PieBottomAreaComponent.Label.ByDistance=Par &distance :

PieBaseSeriesComponent.Label.CategoryDefinition=Définition de &catégorie :

PieBaseSeriesComponent.Text.SpecifyExplodeSlice=Spécifier l'éclatement de la tranche

PieBaseSeriesComponent.Tooltip.EnterBooleanExpression=Entrez une expression booléenne pour contrôler les tranches à éclater. Si le champ reste vierge, la distance d'éclatement s'appliquera à toutes les tranches.

PieLeftAreaComponent.Label.SliceSizeDefinition=Définition de la taille de tranche :

PieSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour PieSeriesAttributeComposite.

PieSeriesAttributeComposite.InnerRadiusType.Points=Points

PieSeriesAttributeComposite.Lbl.Explosion=Explosion :

PiesBottomAreaComponent.Label.TheRotationOfTheChart=Rotation du secteur : angle de départ du premier secteur

PieBottomAreaComponent.Label.Rotation=Rotatio&n du secteur :

PieBottomAreaComponent.Label.MinimumSlice=&Tranche minimale :

PieBottomAreaComponent.Label.MinSliceLabel=&Etiquette de tranche :

PieSeriesUIProvider.Lbl.BasePrefix=Catégorie

PieBottomAreaComponent.Label.Value=Valeur

PieBottomAreaComponent.Label.Ratio=&Proportions du secteur :

PieBottomAreaComponent.Label.TheRatioOfTheChart=Proportions du secteur : rapport hauteur/largeur (0 : ajustement automatique)

PieChart.Txt.Description=Les graphiques à secteurs affichent les valeurs sous la forme de tranches de secteur. \nLa taille de chaque tranche est proportionnelle à la valeur qu'elle représente. \nLes graphiques à secteurs pour séries multiples sont tracés sous la forme de secteurs multiples, un secteur par série.

PieChart.Txt.HelpText=Les graphiques à secteurs affichent des valeurs de données pour une série ou une catégorie sous la forme d'un pourcentage de tranche du secteur entier. Les séries secteur multiples sont représentées dans une grille.

SeriesUIProvider.Lbl.OrthogonalPrefix=Valeur

SeriesUIProvider.Lbl.SeriesDefinition=Définition de la série

SeriesSheetImpl.Label.CategoryBaseSeries=Série de catégories

SeriesUIProvider.Lbl.BasePrefix=Catégorie

SeriesSheetImpl.Label.Title=Titre

SeriesSheetImpl.Label.Visible=Visible

SeriesSheetImpl.Label.Stacked=Empilé

SeriesSheetImpl.Label.Series=Série

SeriesYSheetImpl.Label.Needles=Aiguilles

SeriesYSheetImpl.Label.Needles&=&Aiguilles

SeriesYSheetImpl.Label.Region=Zones

SeriesYSheetImpl.Label.Region&=Régi&ons

SeriesYSheetImpl.Label.Labels=Etiquettes de séries

SeriesYSheetImpl.Label.Labels&=Eti&quettes

SeriesYSheetImpl.Label.DialLabels=Etiquettes de cadran

SeriesYSheetImpl.Label.DialLabels&=&Etiquettes de cadran

SeriesYSheetImpl.Label.Titles=Titres

SeriesYSheetImpl.Label.Titles&=&Titres

SeriesYSheetImpl.Label.Markers=Repères de série

SeriesYSheetImpl.Label.PositiveMarkers=Repères positifs

SeriesYSheetImpl.Label.NegativeMarkers=Repères négatifs

SeriesYSheetImpl.Label.Markers&=&Repères

SeriesYSheetImpl.Label.PositiveMarkers&=Repères &positifs

SeriesYSheetImpl.Label.NegativeMarkers&=Repères &négatifs

SeriesYSheetImpl.Label.Decoration=Tâches

SeriesYSheetImpl.Label.Decoration&=Etiquettes de &tâches

SeriesLabelSheet.Label.Format=Format

SeriesLabelSheet.Label.Values=Valeurs

SeriesGroupingComposite.Lbl.Type=&Type :

SeriesGroupingComposite.Lbl.Unit=&Unité :

SeriesYSheetImpl.Label.Trendline=Ligne d'ajustement de courbe

SeriesYSheetImpl.Label.Trendline&=&Ligne d'ajustement de courbe

SeriesTrendlineSheet.Label.Label=Etiquette

SeriesTrendlineSheet.Label.Label&=&Etiquette :

SeriesGroupingComposite.Lbl.Grouping=Regroupement

SeriesGroupingComposite.Lbl.Enabled=&Activé

SeriesSheetImpl.Label.ValueYSeries=Série verticale de valeurs

SeriesSheetImpl.Label.Translucent=Translucide

SeriesSheetImpl.Label.SeriesPalette=Palette de série

SeriesSheetImpl.Label.SeriesPalette&=&Palette de séries

SeriesYSheetImpl.Label.DataPoint=Point de données

SeriesTrendlineSheet.Label.Outline=Contour

SeriesTrendlineSheet.SeriesTrendlineSheet.Lbl.IsVisible=V&isible

SeriesGroupingComposite.Lbl.Interval=&Intervalle :

SeriesYSheetImpl.Label.ShowLabels=Afficher les étiquettes de &séries

SeriesYSheetImpl.Label.ShowDialLabels=Afficher les étiquette&s de cadran

SeriesYSheetImpl.Label.ShowDecoLabels=A&fficher les étiquettes de tâches

SeriesYSheetImpl.Label.ShowTrendline=&Afficher la ligne d'ajustement de courbe

SeriesYSheetImpl.Label.Interactivity&=Inte&ractivité

SeriesYSheetImpl.Label.Interactivity=Interactivité de séries

SeriesGroupingComposite.Lbl.AggregateExpression=&Fonction :
SeriesGroupingComposite.Tooltip.SelectIntervalForGrouping=Sélectionnez l'intervalle de regroupement. 0 indique un regroupement par X/valeur de catégorie

SeriesPaletteSheet.Label.Auto=Au&to

SeriesPaletteSheet.Tab.Axis=Axe

SeriesPaletteSheet.Tab.Series=Série

SeriesSheetImpl.Label.ValueOrthogonalSeries=Valeur de série

TitleBlockAttributeSheetImpl.Lbl.Caption=Légende d'étiquette :

TitleBlockAttributeSheetImpl.Lbl.BlockProperties=Propriétés du bloc

TitleBlockAttributeSheetImpl.Lbl.IsBlockVisible=Visibilité du bloc

TitleBlockAttributeSheetImpl.Lbl.Anchor=Ancre :

TitleBlockAttributeSheetImpl.Lbl.Stretch=Adapter :

TitleBlockAttributeSheetImpl.Lbl.Background=Arrière-plan :

TitleBlockAttributeSheetImpl.Lbl.Insets=En 3D vers l'avant

TitlePropertiesSheet.Label.TitleArea=Zone de titre

TitlePropertiesSheet.Label.Background=&Arrière-plan :

TitleBlockAttributeSheetImpl.Lbl.Outline=Contour

TitlePropertiesSheet.Label.Interactivity=Interactivité

TitleBlockAttributeSheetImpl.Lbl.LabelProperties=Propriétés de l'étiquette

TitleBlockAttributeSheetImpl.Lbl.ChartTitle=Titre du graphique

TitleBlockAttributeSheetImpl.Title.SheetTitle=Mise en page > Bloc du titre - Formater la zone de titre du graphique

LegendAttributeSheetImpl.Lbl.GeneralProperties=Propriétés générales - Zone entourant les légendes

LegendAttributeSheetImpl.Lbl.ClientAreaProperties=Propriétés de la zone client - Zone des légendes

LegendAttributeSheetImpl.Title.SheetTitle=Mise en page > Légende - Formater la zone de légende

LegendLayoutSheet.Label.TitlePercent=Pourcentage de &titre :

LegendLayoutSheet.Label.MaxPercent=Pourcentage &maximum :

LegendLayoutSheet.Label.WrappingWidth=&Largeur d'habillage :

SampleDataSheetImpl.Lbl.XSeries=Série X

SampleDataSheetImpl.Lbl.BaseSampleValues=Exemples de valeurs :\n {0}

SampleDataSheetImpl.Lbl.SampleValues=Exemples de valeurs :

SampleDataSheetImpl.Lbl.YSeries=Série Y

SampleDataSheetImpl.Lbl.SimulateSeriesCount=Simuler nombre de série :

SampleDataSheetImpl.Lbl.Update=Mettre à jour

SampleDataSheetImpl.Title.SheetTitle=Données > Exemple - Définir les exemples de données de prévisualisation

PlotAttributeSheetImpl.Lbl.GeneralProperties=Propriétés générales - Zone incluant les axes

PlotAttributeSheetImpl.Lbl.ClientAreaProperties=Propriétés de la zone client - Zone comprise entre les axes

PlotAttributeSheetImpl.Title.SheetTitle=Mise en page > Tracé - Formater la zone de tracé

LabelBlockAttributeSheetImpl.Lbl.LabelCaption=Légende d'étiquette :

LabelBlockAttributeSheetImpl.Lbl.BlockProperties=Propriétés du bloc

LabelBlockAttributeSheetImpl.Lbl.IsBlockVisible=Visibilité du bloc

LabelBlockAttributeSheetImpl.Lbl.Anchor=Ancre :

LabelBlockAttributeSheetImpl.Lbl.Stretch=Adapter :

LabelBlockAttributeSheetImpl.Lbl.Background=Arrière-plan :

LabelBlockAttributeSheetImpl.Lbl.Insets=En 3D vers l'avant

LabelAttributesComposite.Lbl.IsVisible=&Visible

LabelAttributesComposite.Lbl.IsVisible2=Visibl&e

LabelAttributesComposite.Lbl.Position=&Position :

LabelAttributesComposite.Lbl.Background=&Arrière-plan :

LabelAttributesComposite.Lbl.Outline=Contour

LabelBlockAttributeSheetImpl.Lbl.Outline=Contour

LabelBlockAttributeSheetImpl.Lbl.LabelProperties=Propriétés de l'étiquette

LabelBlockAttributeSheetImpl.Lbl.LabelBlock=Bloc de l'étiquette

DataDefinitionComposite.Tooltip.InvokeExpressionBuilder=Appeler le Générateur d'expression

DataDefinitionSelector.Exception.NotSupportedForMultipleAxes=\ n'est pas pris en charge pour plusieurs axes\!

DataDefinitionComposite.Tooltip.InvokeRuleEditor=Appeler l'éditeur de règles

RuleEditorDialog.Title.RuleEditor=Editeur de règles - {0}

RuleEditorDialog.Lbl.Rules=Règles

RuleEditorDialog.Lbl.Type=Type :

RuleEditorDialog.Lbl.Value=Valeur :

RuleEditorDialog.Lbl.Remove=Supprimer

RuleEditorDialog.Lbl.Add=Ajouter

RuleEditorDialog.Lbl.Update=Mettre à jour

RuleEditorDialog.Exception.InvalidRule=ERREUR\! Index de règles non valide transmis.

FillCanvas.Transparent=Transparent

FillCanvas.Auto=Auto

FillChooserComposite.Button.Pattern=Modèle

FillChooserComposite.Lbl.Opacity=Opacité : {0, number, integer}

FillChooserComposite.Lbl.Gradient=Dégradé

FillChooserComposite.Lbl.Transparent=Transparent

FillChooserComposite.Lbl.CustomColor=Couleur personnalisée

FillChooserComposite.Lbl.Image=Image

FillChooserComposite.Lbl.PositiveNegative=Positif/Négatif

FillChooserComposite.Lbl.Auto=Auto

ClientAreaAttributeComposite.Lbl.Background=Arrière-plan :

ClientAreaAttributeComposite.Lbl.Shadow=O&mbre :

ClientAreaAttributeComposite.Lbl.Outline=Contour

InsetsComposite.Lbl.Insets=En 3D vers l''avant ({0})

InsetsComposite.Lbl.Top=&Haut :

InsetsComposite.Lbl.Left=&Gauche :

InsetsComposite.Lbl.Bottom=Ba&s :

InsetsComposite.Lbl.Right=&Droite :

InsetsEditorDialog.Title.InsetsEditor=Boîte de dialogue de l'éditeur 3D

InsetsEditorDialog.Lbl.UnitsMessage=* Toutes les valeurs sont données en {0}

ExternalizedTextEditorDialog.Title.ExternalizeText=Externaliser le texte

ExternalizedTextEditorDialog.Lbl.ExternalizeText=E&xternaliser le texte

ExternalizedTextEditorComposite.Warn.KeyNotFound=Impossible de trouver la clé dans le fichier de propriétés... ou le fichier de propriétés n'est pas présent.

ExternalizedTextEditorComposite.Lbl.EditText=Appeler l'Editeur de texte externalisé

ExternalizedTextEditorDialog.Lbl.LookupKey=&Clé de recherche :

ExternalizedTextEditorDialog.Lbl.DefaultValue=&Valeur par défaut :

ExternalizedTextEditorDialog.Lbl.ExternalizedValue=Valeur externalisée :

ExternalizedTextEditorDialog.Warn.KeyNotFound=Impossible de trouver la clé dans le fichier de propriétés... ou le fichier de propriétés n'est pas présent.

ExternalizedTextEditorDialog.Lbl.Value=<Valeur de la clé ''{0}''>

Format.Button.Label=Format

Format.Button.Lbl&=For&mat

FormatSpecifierComposite.error.Title=Erreur d'indicateur de format

FormatSpecifierComposite.error.Message=Valeur du paramètre de l''indicateur de format incorrecte : "{0}"

FormatSpecifierComposite.Label.DenominatorDigits=Chiffres du dénominateur

FormatSpecifierComposite.Label.NumeratorValue=Valeur du numérateur

FormatSpecifierComposite.Lbl.DataType=Type &de données :

FormatSpecifierComposite.Lbl.DateTime=Date/heure

FormatSpecifierComposite.Lbl.Undefined=Aucu&n

FormatSpecifierComposite.Lbl.Numerator=&Valeur du numérateur (1-100) :

FormatSpecifierComposite.Lbl.Standard=&Standard

FormatSpecifierComposite.Lbl.String=Chaîne

FormatSpecifierComposite.Lbl.Type=T&ype :

FormatSpecifierComposite.Lbl.None=<Aucun>

FormatSpecifierComposite.Lbl.Details=Dét&ails :

FormatSpecifierComposite.Lbl.Delimiter=Délimit&eur :

FormatSpecifierComposite.Lbl.Pattern=&Correspondance :

FormatSpecifierComposite.Lbl.Prefix=&Préfixe :

FormatSpecifierComposite.Lbl.Preview=Aperçu :

FormatSpecifierComposite.Lbl.Approximate=App&roximation :

FormatSpecifierComposite.Lbl.Suffix=Suffi&xe :

FormatSpecifierComposite.Lbl.Number=Numéro

FormatSpecifierPreview.Lbl.NoFormat=Aucun format spécifié.

FormatSpecifierComposite.Lbl.Multiplier=&Multiplicateur :

FormatSpecifierComposite.Lbl.FractionDigits=Fracti&ons :

FormatSpecifierComposite.Tooltip.InputAPositiveInteger=Veuillez saisir un entier positif comme numérateur fixe

FormatSpecifierComposite.Tooltip.FractionDigits=Propriétés avancées : utilisé pour définir la précision approximative

FormatSpecifierComposite.Lbl.MaxRecursionTimes=Chiffres maximals du dén&ominateur (1-8) :

FormatSpecifierComposite.Lbl.Fraction=&Fraction

FormatSpecifierDialog.Title.EditFormat=Modifier le format

FormatSpecifierComposite.Lbl.Advanced=&Avancé

FormatSpecifierComposite.Lbl.DatePattern=&Correspondance :

FormatSpecifierComposite.Lbl.ExampleFormats=&Exemples de formats :

FormatSpecifierComposite.Lbl.NumberPattern=&Correspondance :

FormatSpecifierComposite.StringFormat.LowerCase=Minuscules

FormatSpecifierComposite.StringFormat.PhoneNumber=Numéro de téléphone

FormatSpecifierComposite.StringFormat.SocialSNumber=Numéro de sécurité sociale

FormatSpecifierComposite.StringFormat.UpperCase=Majuscules

FormatSpecifierComposite.StringFormat.WhiteSpace=Conserver l'espace

FormatSpecifierComposite.StringFormat.ZipCode=Code postal + 4

FormatSpecifierPreview.Lbl.NotAvailable=N/D

GridAttributesComposite.Lbl.Ticks=Repères

GridAttributesComposite.Lbl.Style=Style :

GradientEditorDialog.Lbl.EndColor=Couleur de fin :

GradientEditorDialog.Lbl.Rotation=Rotation

FontDefinitionDialog.Lbl.Rotation=Rotation :

FontDefinitionDialog.Tooltip.Accept=Accepter

FontDefinitionDialog.Tooltip.Bold=Gras

FontDefinitionDialog.Tooltip.Italic=Italique

FontDefinitionDialog.Tooltip.AlignTopCenter=Alignement - Centre haut

FontDefinitionDialog.Tooltip.AlignCenter=Alignement - Centre

FontDefinitionDialog.Tooltip.Underline=Texte souligné

FontDefinitionDialog.Tooltip.AlignTopRight=Alignement - Haut droit

FontDefinitionDialog.Tooltip.Strikethrough=Barré

FontDefinitionDialog.Title.FontDescriptor=Modifier la police

FontDefinitionDialog.Lbl.Font=&Police :

FontDefinitionDialog.Lbl.Size=For&mat :

FontDefinitionDialog.Lbl.Color=&Couleur :

FontDefinitionDialog.Lbl.Style=Style :

FontDefinitionDialog.Lbl.Format=Format :

FontDefinitionDialog.Lbl.Wrap=Retour à la ligne

FontDefinitionDialog.Lbl.Preview=Aperçu:

FontDefinitionDialog.Lbl.Alignment=Alignement:

FontDefinitionDialog.Label.Degree=&Degré :

FontDefinitionDialog.Tooltip.AlignTopLeft=Alignement - Haut gauche

FontDefinitionDialog.Tooltip.AlignCenterLeft=Alignement - Centre gauche

FontDefinitionDialog.Tooltip.AlignCenterRight=Alignement - Centre droit

FontDefinitionDialog.Tooltip.AlignBottomLeft=Alignement - Bas gauche

FontDefinitionDialog.Tooltip.AlignBottomCenter=Alignement - Bas centre

FontDefinitionDialog.Tooltip.AlignBottomRight=Alignement - Bas droit

FontDefinitionDialog.Lbl.Strikethrough=&Barré

FontDefinitionComposite.Tooltip.FontDialog=Appeler l'Editeur de police

TriggerEditorDialog.Title.TriggerEditor=Editeur d''interaction - {0}

TriggerDataComposite.Lbl.ActionDetails=Détails de l'action

TriggerDataComposite.Lbl.SeriesDefinition=Définition de la série :

TriggerDataComposite.Label.CallbackDescription=L'action de rappel automatique est destinée à une utilisation API dans un rendu SWT ou Swing et vous permet de lier un gestionnaire d'événements java.

TriggerDataComposite.Label.HighlightDescription=Met en surbrillance l'élément de données correspondant, le cas échéant.

TriggerDataComposite.Label.VisiblityDescription=Bascule la visibilité de l'élément de données correspondant, le cas échéant.

TriggerDataComposite.Label.Description=Modifiez l'URL en fonction de son type, y compris les paramètres suivants : URI, Signet Interne et Extraire.

TriggerDataComposite.Label.DPVisibilityDescription=Bascule la visibilité de l'étiquette de l'élément de données correspondant, le cas échéant.

TriggerDataComposite.Label.OptionalURLParameters=Nommez les paramètres URL optionnels qui représentent, pour chaque point de données, les valeurs suivantes :

TriggerDataComposite.Label.TooltipUsingDataLabelOfSeries=Si le texte infobulle reste annulé, il utilisera l'étiquette de données de la série correspondante à la place.

TriggerDataComposite.Tooltip.InvokeURLBuilder=Invoquer le générateur d'URL

TriggerDataComposite.Tooltip.Advanced=Afficher les paramètres URL optionnels

TriggerDataComposite.Label.None=Aucun

TriggerDataComposite.Tooltip.ParameterCategory=Nom de paramètre pour la catégorie :

TriggerDataComposite.Tooltip.ParameterValue=Nom de paramètre pour la valeur :

TriggerDataComposite.Tooltip.ParameterSeries=Nom de paramètre pour la série :

TriggerDataComposite.Lbl.TooltipDelay=Retard &infobulle (en ms) :

TriggerDataComposite.Lbl.ParameterNames=Paramètres URL de points de données optionnels

TriggerDataComposite.Lbl.CategorySeries=Série de &catégories :

TriggerDataComposite.Lbl.Cursor=Cur&seur :

TriggerDataComposite.TemporaryName.Hyperlink=Lien hypertexte

TriggerDataComposite.Text.EditBaseURL=Modifier l'&URL de base...

TriggerDataComposite.Text.Advanced=&Avancé>>

TriggerDataComposite.Text.OpenAdvanced=&Avancé<<

TriggerDataComposite.Lbl.ValueSeries=Série de &valeurs :

TriggerDataComposite.Lbl.ValueSeriesName=&Nom de série de valeurs :

TriggerDataComposite.Tooltip.InputScript=\ Entrez un script (le plus souvent JavaScript) à exécuter dans l'environnement de rendu.

TriggerEditorComposite.Lbl.Remove=&Supprimer

TriggerEditorComposite.Lbl.Add=&Ajouter

TriggerDataComposite.Lbl.Event=E&vénement :

TriggerDataComposite.Lbl.None.accessibility=<Aucun>

TriggerDataComposite.Lbl.None.MouseClick=<Aucun>

TriggerDataComposite.Lbl.None.MouseHover=<Aucun>

TriggerDataComposite.Lbl.None.onblur=<Aucun>

TriggerDataComposite.Lbl.None.onclick=<Aucun>

TriggerDataComposite.Lbl.None.ondblclick=<Aucun>

TriggerDataComposite.Lbl.None.onfocus=<Aucun>

TriggerDataComposite.Lbl.None.onkeydown=<Aucun>

TriggerDataComposite.Lbl.None.onkeypress=<Aucun>

TriggerDataComposite.Lbl.None.onkeyup=<Aucun>

TriggerDataComposite.Lbl.None.onload=<Aucun>

TriggerDataComposite.Lbl.None.onmousedown=<Aucun>

TriggerDataComposite.Lbl.None.onmousemove=<Aucun>

TriggerDataComposite.Lbl.None.onmouseout=<Aucun>

TriggerDataComposite.Lbl.None.onmouseover=<Aucun>

TriggerDataComposite.Lbl.None.onmouseup=<Aucun>

TriggerDataComposite.Lbl.Action=A&ction :

TriggerDataComposite.Lbl.Script=Scri&pt :

TriggerDataComposite.Lbl.Target=Cible :

TriggerEditorComposite.Lbl.Update=<< &Mettre à jour

TriggerDataComposite.Lbl.TooltipText=Te&xte infobulle :

TriggerDataComposite.Btn.Format=&Format

TriggerDataComposite.Lbl.BaseURL=Modifier l'URL de base :

TriggerDataComposite.Lbl.Image=&Image

GradientEditorDialog.Lbl.GradientEditor=Editeur de dégradé

GradientEditorDialog.Lbl.StartColor=Couleur de début :

GradientEditorDialog.Lbl.Preview=Aperçu

PaletteEditorComposite.Label.EditColor=Modifier la couleur

PaletteEditorComposite.Lbl.Add=&Ajouter

PaletteEditorComposite.Lbl.Remove=&Supprimer

PaletteEditorComposite.Lbl.Up=Vers le haut

PaletteEditorComposite.Lbl.Down=Vers le bas

PatternImageEditorDialog.Button.Cancel=&Annuler

PatternImageEditorDialog.Button.OK=&OK

PatternImageEditorDialog.Group.Color=Couleur :

PatternImageEditorDialog.Group.Pattern=Modèle :

PatternImageEditorDialog.Label.Background=A&rrière-plan :

PatternImageEditorDialog.Label.Foreground=&Premier plan :

PatternImageEditorDialog.Title.PatternFillEditor=Editeur d'images modèles

LabelAttributesComposite.Lbl.Label=Etiquette

LabelAttributesComposite.Lbl.Font=P&olice :

LabelAttributesComposite.Lbl.Shadow=&Ombre :

LabelBlockAttributeSheetImpl.Title.SheetTitle=Mise en page > Bloc de l'étiquette - Formater la zone de bloc de l'étiquette

BlockAttributeComposite.Lbl.IsBlockVisible=Visibilité du bloc

BlockAttributeComposite.Lbl.Anchor=&Ancre :

BlockAttributeComposite.Lbl.Stretch=Adap&ter :

BlockAttributeComposite.Lbl.Insets=En 3D vers l'avant

BlockPropertiesSheet.Label.Outline=Contour

BlockAttributeComposite.Lbl.Outline=Contour

BlockAttributeComposite.Lbl.HorizontalSpacing=Espacement &horizontal :

BlockAttributeComposite.Lbl.VerticalSpacing=Espacement &vertical :

BlockAttributeComposite.Lbl.Orientation=&Orientation

BlockAttributeComposite.Lbl.Direction=&Direction :

BlockAttributeComposite.Lbl.Position=&Position :

BlockAttributeComposite.Lbl.ItemType=Type d'élément :

BlockAttributeComposite.Title.PlotBlock=Bloc du tracé

BlockAttributeComposite.Title.LegendBlock=Bloc de la légende

BlockAttributeComposite.Title.TitleBlock=Bloc du titre

BlockAttributeComposite.Title.LabelBlock=Bloc de l'étiquette

BlockPropertiesSheet.Label.Interactivity=Interactivité

LayoutSheetImpl.Lbl.ChartProperties=Propriétés des blocs du graphique

LayoutSheetImpl.Lbl.Background=Arrière-plan :

LayoutSheetImpl.Lbl.Insets=En 3D vers l'avant

LayoutSheetImpl.Lbl.Outline=Contour

LayoutSheetImpl.Title.SheetTitle=Mise en page - Formater le bloc du graphique

AttributeSheetImpl.Lbl.ChartProperties=Propriétés du graphique

AttributeSheetImpl.Lbl.Type=Type :

AttributeSheetImpl.Lbl.Subtype=Sous-type :

AttributeSheetImpl.Lbl.Units=&Unités :

AttributeSheetImpl.Lbl.ColumnCount=Nombre de &colonnes de grille :

AttributeSheetImpl.Lbl.ChartBackground=Arrière-plan du graphique :

AttributeSheetImpl.Lbl.PropertyEditorDialog=Propriétés étendues

AttributeSheetImpl.Lbl.ChartWall=&Paroi du graphique :

AttributeSheetImpl.Lbl.ChartFloor=Base du grap&hique :

AttributeSheetImpl.Lbl.UnitSpacing=&Espacement des unités (0-100) :

AttributeSheetImpl.Title.SheetTitle=Attributs - Personnaliser les attributs du graphique

PropertyEditorDialog.Title.PropertyEditorDialog=Editeur de propriété étendue

PropertyEditorDialog.Lbl.Key=Clé

PropertyEditorDialog.Lbl.Value=Valeur

PropertyEditorDialog.Lbl.Add=&Ajouter

PropertyEditorDialog.Lbl.Remove=&Supprimer

HeadStyleAttributeComposite.Lbl.HeadStyle=Style de pointe :

HyperlinkEditorDialog.BaseURL.Message=Veuillez définir l'URL de base.

HyperlinkEditorDialog.ErrorMessage.ExistingText=Le nom existe déjà, veuillez le modifier.

HyperlinkEditorDialog.ErrorMessage.NullText=Le nom ne doit pas rester vierge.

HyperlinkEditorDialog.HyperlinkName.Title.Warning=Avertissement

HyperlinkEditorDialog.Text.MenuLabel=&Nom :

HyperlinkEditorDialog.Title.HyperlinkEditor=Editeur du lien hypertexte

TaskSelectType.TaskExp=Sélectionner le type de graphique

TaskSelectType.Label.Preview=Aperçu du graphique

TaskSelectType.Label.Oritention=Orientation

TaskSelectType.Label.FlipAxis=Inverser l'a&xe

TaskSelectType.Selection.None=Aucun

TaskSelectType.Label.MultipleYAxis=Axes verticaux &multiples :

TaskSelectType.Label.AddSecondaryAxis=Ajouter un axe secondaire

TaskSelectType.Selection.SecondaryAxis=Axe secondaire

TaskSelectType.Label.SeriesType=Type de &séries :

TaskSelectType.Task.Description=Sélectionner le type de graphique et choisir un format de sortie.

TaskSelectType.Label.OutputFormat=Format de s&ortie :

TaskSelectType.Selection.MoreAxes=Axes supplémentaires

TaskSelectType.Label.SelectChartType=Sélectionner le type de graphique

TaskSelectType.Label.SelectSubtype=Sélectionner le sous-type

TaskSelectType.Exception.CannotSupportAxes=Prise en charge des axes impossible dans ChartWithoutAxes \!

TaskSelectType.Exception.NotSupportedForMultipleAxes=\ n'est pas pris en charge pour plusieurs axes\!

TaskSelectType.Label.ChartTypes=Types de graphiques

TaskSelectType.Label.Dimension=&Dimension :

TaskSelectType.Label.ChartSubtypes=Sous-types de graphique

TaskSelectData.TaskExp=Sélectionner des données

TaskSelectData.Label.ToBindADataColumn=Utiliser le menu contextuel ou faites glisser la colonne dans les champs de série.

TaskSelectData.Label.ChartPreview=Aperçu du graphique

TaskSelectData.Label.SelectDataSet=Sélectionner des données

TaskSelectData.Label.UseReportData=&Hériter les données du conteneur

TaskSelectData.Label.UseReportItem=Utiliser un élément de &rapport

TaskSelectData.Label.UseDataSet=Utiliser le jeu de &données

TaskSelectData.Label.CreateNew=&Créer...

TaskSelectData.Label.DataPreview=Prévisualisation des données

TaskSelectData.Label.DataBinding=Li&aison de données...

TaskSelectData.Warning.TypeCheck=Le type de données de {0} est incompatible avec {1}, corrigez l'expression.

TaskSelectData.Label.Filters=Fil&tres...

TaskSelectData.Label.Parameters=&Paramètres...

TaskSelectData.Task.Description=Sélectionner les données à afficher dans le graphique et les lier à la série.

TaskSelectData.Exception.UnableToSwitchToDataset=Impossible d'utiliser le jeu de données

TaskSelectData.Label.InsertAggregation=Insérer une agrégation

TaskSelectData.Label.DataExpressionBuilder=Générateur d'expression de données

TaskSelectData.Label.Component=\ Composant

TaskSelectData.Label.Overlay=Superposition

TaskSelectData.Label.Series=Série

TaskSelectData.Label.UseAsCategoryXAxis=Utiliser comme axe horizontal de catégories

TaskSelectData.Label.UseAsCategorySeries=Utiliser comme série de catégories

TaskSelectData.Label.PlotAsValueYSeries=Tracer une série verticale de valeurs

TaskSelectData.Tooltip.CreateNewDataset=Créer un nouveau jeu de données

TaskSelectData.Label.PlotAsGaugeValue=Tracer une valeur de mesure

TaskSelectData.Label.PlotAsValueSeries=Tracer une série de valeurs

TaskSelectData.Label.UseToGroupYSeries=Utiliser la série verticale de groupes

TaskSelectData.Label.EnableLivePreview=Activer l'aperçu direct du graphique

TaskSelectData.Label.UseToGroupValueSeries=Utiliser la série de valeurs de groupes

TaskFormatChart.TaskExp=Sélectionner le format de graphique

TaskFormatChart.Label.Preview=Aperçu du graphique

TaskFormatChart.LivePreviewTask.BindData=Récupération et liaison des données pour l'aperçu du graphique

TaskFormatChart.Task.Description=Ajuster votre graphique en définissant l'interactivité, la mise en page et les propriétés de la série, ainsi que le format général du texte, des ombres, de l'arrière-plan et des bordures.

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=Index de colonne {0} incorrect ou colonnes non définies \!

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=Index de colonne spécifié incorrect \!

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=Index de colonne {0} incorrect \! La table ne comporte que {1} colonnes \!

CustomPreviewTable.Exception.RowIndexGreaterThan0=L'index de ligne doit être supérieur ou égal à 0 \!

AbstractSelectDataCustomizeUI.Label.SeriesGrouping=Regroupement de séries

AbstractSelectDataCustomizeUI.Label.YAxis=Axe vertical

AbstractSelectDataCustomizeUI.Label.Series=Série

AbstractScaleSheet.Label.ShowValuesOutside=Afficher les valeurs en deh&ors de l'intervalle de l'axe

MultipleHyperlinksComposite.Btn.Add=&Ajouter

MultipleHyperlinksComposite.Btn.Delete=&Supprimer

MultipleHyperlinksComposite.Btn.Down=&Vers le bas

MultipleHyperlinksComposite.Btn.Edit=Modifi&er

MultipleHyperlinksComposite.Btn.Properties=&Propriétés

MultipleHyperlinksComposite.Btn.Up=Vers le ha&ut

MultipleHyperlinksComposite.Group.Hyperlinks=Liens hypertextes

MultipleHyperlinksComposite.Label.Tooltip=&Info-bulle :

MultipleSeriesComponent.Label.OptionalYSeriesGrouping=Regr&oupement de séries verticales facultatif :

MultipleSeriesComponent.Label.OptionalOverlayGrouping=Regr&oupement de superpositions facultatif :

MultipleSeriesComponent.Label.OptionalGrouping=Regr&oupement facultatif :

MultipleSeriesComponent.Label.GroupSorting=Tri des &groupes :

SelectDataChartWithAxisUI.Label.ValueYSeries=Série verticale de valeurs :

MultipleSeriesComponent.Label.Series=Série

SelectDataChartWithoutAxisUI.Label.Series=Série

DataDefinitionSelector.Label.Series=Série

DataDefinitionSelector.Text.NewSeries=<Nouvelle série...>

DataDefinitionSelector.Text.NewAxis=<Nouvel axe...>

DataDefinitionSelector.Tooltip.RemoveSeries=Supprimer la série sélectionnée

DataDefinitionSelector.Tooltip.RemoveAxis=Supprimer l'axe sélectionné

DataDefinitionSelector.Label.YAxis=Axe vertical

DataDefinitionSelector.Label.Axis=Axe

DataDefinitionSelector.Label.DeleteAxis=Supprimer l'axe

DataDefinitionSelector.Label.DeleteSeries=Supprimer la série

DialBottomAreaComponent.Label.Dial=Cadran

DialBottomAreaComponent.Label.GaugeValueDefinition=Définition d'une valeur de mesure :

PieBottomAreaComponent.Label.TheExplosionCondition=La condition d'éclatement permet un éclatement par tranche en fonction de la condition.

PieBottomAreaComponent.Label.TheAmplitudeOfTheExplosion=L'amplitude de l'éclatement détermine l'étendue sur laquelle la tranche peut être éclatée.

AxisGridLinesSheet.MajorLabel.LineIsVisible=&Visible

AxisGridLinesSheet.MajorLabel.TickIsVisible=V&isible

AxisGridLinesSheet.MinorLabel.LineIsVisible=Vi&sible

AxisGridLinesSheet.MinorLabel.TickIsVisible=Visib&le

AxisLabelSheet.Label.Ellipsis=Po&ints de suspension :

AxisLabelSheet.Label.Ellipsis.Tooltip=définit le nombre minimum de caractères qui seront affichés avant que les points de suspension ne soient affichés.

AxisSheetImpl.Label.Aligned=Aligné

AxisSheetImpl.Label.Axis=Axe

AxisSheetImpl.Label.AxisPercent=Axe pourcentage

AxisSheetImpl.Label.Visible=Visible

AxisSheetImpl.Label.ValueY=Valeur (Y)

AxisYSheetImpl.Label.Labels=E&tiquettes :

AxisSheetImpl.Label.Type=Type

AxisSheetImpl.Label.Color=Couleur

AxisYSheetImpl.Label.Title=&Titre :

AxisYSheetImpl.Label.Scale=Echelle de l'axe

AxisYSheetImpl.Label.Scale&=&Echelle :

AxisSheetImpl.Label.CategoryX=Catégorie (X)

AxisSheetImpl.Label.AncillaryZ=Auxiliaire (Z)

AxisSheetImpl.Label.SideBySide=Juxtaposé

AxisXSheetImpl.Label.Visible=Visible

AxisYSheetImpl.Label.LabelFormat=Etiquette de l'axe

AxisYSheetImpl.Label.LabelFormat&=&Etiquette

AxisYSheetImpl.Label.TitleFormat=Titre de l'axe

AxisYSheetImpl.Label.TitleFormat&=&Titre

AxisYSheetImpl.Label.Gridlines=Quadrillage de l'axe

AxisYSheetImpl.Label.Gridlines&=Qua&drillage

AbstractAxisSubtask.Button.Fixed=Fixe

AbstractAxisSubtask.Lbl.IsCategoryAxis=A&xe de catégorie

AbstractAxisSubtask.Label.Visible2=V&isible

AbstractScaleSheet.Label.StepNumber=&Nombre d'étapes :

AxisYSheetImpl.Label.Markers=Repère des axes

AxisYSheetImpl.Label.Markers&=&Repères

AxisZSheetImpl.Label.Visible=&Visible

AxisXSheetImpl.Label.AxisData=Données de l'axe

AbstractAxisSubtask.Label.Stagger=Déf&inir plusieurs niveaux

AbstractAxisSubtask.Label.Interactivity=Interactivité de l'axe

AbstractAxisSubtask.Label.LabelSpan=&Plage de l'étiquette :

AbstractAxisSubtask.Label.Points=(Points)

AbstractAxisSubtask.Label.ReverseCategory=Inverser les &catégories

AxisTextSheet.Label.Interval=Int&ervalle :

AxisMarkersSheet.Title.MarkerLine=Ligne de repères

AxisMarkersSheet.Label.Label=&Etiquette :

AxisMarkersSheet.Title.MarkerRange=Gamme de repères

ChartLegendSheetImpl.Label.Outline=Contour :

ChartLegendSheetImpl.Label.ShowValue=Affic&her la valeur

ChartPlotSheetImpl.Label.Background=A&rrière-plan :

ChartPlotSheetImpl.Label.Background2=Arrière-p&lan :

ChartPlotSheetImpl.Label.ClientArea=Zone client

ChartTitleSheetImpl.Text.Auto=&Automatique

ChartTitleSheetImpl.Text.TitleLayout=Mise en page du titre

ChartTitleSheetImpl.Text.Layout&=&Mise en page

ChartTitleSheetImpl.Text.TitleText=Texte du titre

ChartTitleSheetImpl.Text.TitleText&=&Texte

ChartSheetImpl.Title.ChartTitle=Titre du graphique

ChartSheetImpl.Title.ChartArea=Zone graphique

ChartSheetImpl.Label.Visible=&Visible

ChartSheetImpl.Label.ColorBy=&Couleur par :

ChartSheetImpl.Label.Coverage=Couvert&ure :

ChartSheetImpl.Label.Background=A&rrière-plan :

ChartLegendSheetImpl.Label.Entries=&Entrées

ChartLegendSheetImpl.Label.LegendTitle&=&Titre

ChartLegendSheetImpl.Title.LegendLayout=Mise en page de la légende

ChartLegendSheetImpl.Tooltip.ShowDataPointValue=Affiche la valeur de point de données de la première ligne au-dessous du texte de légende saisi pour chaque entrée de légende.

ChartLegendSheetImpl.Title.LegendEntries=Entrées de légende

ChartLegendSheetImpl.Title.LegendTitle=Titre de légende

ChartLegendSheetImpl.Label.Layout=Mise en p&age

ChartLegendSheetImpl.Label.Legend=Légende

ChartLegendSheetImpl.Label.Title=Tit&re :

ChartLegendSheetImpl.Label.Value=Valeur :

ChartLegendSheetImpl.Title.Tooltip=Légende de l'infobulle

ChartLegendSheetImpl.Label.Interactivity=Interactivité de légende

ChartPlotSheetImpl.Label.AreaIncludingAxes=Zone contenant des axes

ChartSheetImpl.Label.EnableInPreview=A&perçu

ChartSheetImpl.Label.Font=&Police :

ChartSheetImpl.Label.ResetValue=Réinitialiser la &valeur

ChartPlotSheetImpl.Label.AreaWithinAxes=Zone délimitée par des axes

ChartSheetImpl.Label.Style=&Style :

ChartSheetImpl.Label.None=Aucun

ChartSheetImpl.Text.Outline=Contour

ChartSheetImpl.Text.Outline&=&Contour

ChartSheetImpl.Text.GeneralProperties=Propriétés générales

ChartSheetImpl.Text.GeneralProperties&=Propriétés &générales

ChartSheetImpl.Text.TitleInteractivity=&Interactivité du titre

ChartSheetImpl.Text.CustomProperties=Propriétés personnalisées

ChartSheetImpl.Text.CustomProperties&=&Propriétés personnalisées

ChartSheetImpl.Text.ChartAreaInteractivity=Interactivité de la &zone graphique

ChartSheetImpl.Label.Interactivity=Interactivité de la zone graphique

ChartSheetImpl.Label.InteractivityEnable=Activer l'int&eractivité du graphique

ChartSheetImpl.Label.Text=Te&xte :

ChartLegendSheetImpl.Label.LegendBehaviorType=C&omportement :

ChartLivePreviewThread_Text.PleaseWait=, veuillez patienter...

ChartLivePreviewThread.ErrorMessage.NoDataEngine=Aucun moteur de données pour traiter les données. Veuillez vous reporter à la précédente exception pour obtenir plus de détails.

SeriesSheetImpl.Label.Type=Type

SeriesSheetImpl.Label.ZOrder=Ordre Z

LegendTextSheet.Label.Ellipsis=Points de susp&ension :

LegendTextSheet.Label.Font=&Police :

LegendTextSheet.Label.Separator=Séparateur

LegendTextSheet.Tooltip.Ellipsis=Définit le nombre minimum de caractères qui seront affichés avant que les points de suspension ne soient affichés.

MoreOptionsChartLegendSheet.Label.TextArea=Zone de texte

MoreOptionsChartLegendSheet.Label.Outline=Contour

MoreOptionsChartLegendSheet.Label.LegendArea=Zone de légende

MoreOptionsChartPlotSheet.Label.AreaIncludingAxes=Zone contenant des axes

MoreOptionsChartPlotSheet.Label.Interactivity=Interactivité

MoreOptionsChartPlotSheet.Label.AreaWithinAxes=Zone délimitée par des axes

MoreOptionsChartPlotSheet.Label.Anchor=&Ancre :

MoreOptionsChartPlotSheet.Label.Outline=Contour

MoreOptionsChartPlotSheet.Label.Stretch=&Adapter :

TitlePropertiesSheet.Label.Title=&Titre

TitlePropertiesSheet.Label.Visible=Visible

TitlePropertiesSheet.Label.Anchor=&Ancre :

TitlePropertiesSheet.Label.Stretch=Adap&ter :

TitlePropertiesSheet.Label.Outline=Contour

TitlePropertiesSheet.Label.Text=Texte

BaseDataDefinitionComponent.Text.SpecifyDataDefinition=Spécifier la définition de données

BaseDataDefinitionComponent.Label.EditGroupSorting=Modifier le regroupement et le tri
BaseDataDefinitionComponent.Tooltip.InputValueExpression=Expression de la valeur d'entrée

BaseDataDefinitionComponent.Text.EditFormat=Modifier le format

BaseDataDefinitionComponent.WarningMessage.ExpressionsForbidden=Impossible de sélectionner des expressions d'une dimension permettant de définir des séries de catégories et des séries verticales facultatives en une seule fois.

BaseGroupSortingDialog.Label.SortOn=Trier sel&on :

MarkerEditorComposite.Button.Outline=&Contour

MarkerEditorComposite.Label.MarkerType=Type

MarkerIconDialog.Button.EmbeddedImage=I&mage incorporée

MarkerIconDialog.Title.MarkerIconSelector=Dispositif de sélection d'icône de repère

MarkerIconDialog.Label.Description.EmbeddedImage=Sélectionner l'image incorporée comme icône de repère.

MarkerIconDialog.Lbl.SelectIconFrom=Sélectionner l'icône de :

MarkerIconDialog.Lbl.URL=&URL

MarkerIconDialog.Lbl.Local=&Paramètres régionaux

MarkerIconDialog.Lbl.EnterURL=&Entrer l'URL :

MarkerIconDialog.Lbl.Browse=&Parcourir

MarkerIconDialog.Lbl.Preview=A&perçu

MarkerIconDialog.Lbl.Add=Ajouter

MarkerIconDialog.Chooser.Title=Sélecteur d'icône de repère

MarkerIconDialog.Lbl.Remove=Supprimer

MarkerIconDialog.Lbl.Description=Importer l'icône de repère à partir des fichiers image en local.

MarkerIconDialog.Exception.ImageNotAvailable=L'image n'est pas disponible actuellement.

MarkerIconDialog.Exception.InvalidURL=URL non valide. Veuillez la corriger.

MarkerIconDialog.ImageNotAvailableWarning=Avertissement

MarkerIconDialog.ImageNotAvailableWarningMessage=Souhaitez-vous l'utiliser quand même ?
exception.data.DataBindingsAreNull=Au moins une liaison de données est nulle.\

DialLabelSheet.Label.Format=Format :

ImageDialog.AddImage=&Ajouter une image...

ImageDialog.FileExist=Le nom de fichier existe déjà, veuillez le modifier et le charger à nouveau.

ImageDialog.ImportFail=Echec de l'importation

ImageDialog.label.SelectImageType=Sélectionner un type d'image :

ImageDialog.label.URLImage=&Image de l'URL

ImageDialog.label.EmbeddedImage=I&mage incorporée

ImageDialog.label.EnterURL=&Entrer l'URI de l'image :

ImageDialog.label.EnterEmbed=&Entrez le chemin de l'image à incorporer :

ImageDialog.label.Browse=&Parcourir...

ImageDialog.label.SelectFile=Sélectionner un fichier

ImageDialog.label.Preview=&Aperçu

ImageDialog.Label.ResourceImage=Fichier &image dans les ressources partagées

ImageDialog.label.SelectImage=Sélectionner une image

ImageDialog.uri.tooltip=(Exemples : http://host/cursor.gif, uri/cursor.gif)

ImageDialog.label.LocalImage=Fichier image l&ocal

ImageDialog.label.EnterLocal=&Entrez le chemin d'accès de l'image locale :

TextEditorComposite.Tooltip.EnterDecimalOrFractionValue=Entrez un nombre entier ou une valeur décimale ou fractionnelle

PlotClientAreaSheet.Btn.Auto=A&uto

PlotClientAreaSheet.Btn.Auto2=Aut&o

PlotClientAreaSheet.Label.HeightHint=Indication de &hauteur :

PlotClientAreaSheet.Label.WidthHint=Indication de &largeur :


AxisMarkersSheet.MarkerLine.displayName=MarkerLine
AxisMarkersSheet.MarkerRange.displayName=MarkerRange
AxisMarkersSheet.Label.Interactivity=&Interactivité

AxisMarkersSheet.Label.IsVisible=Vi&sible

AbstractPopupSheet.Label.Close=Fermer

AbstractPopupSheet.Label.Help=Aide

AggregateEditorComposite.Aggregate.Enabled=Activé

AggregateEditorComposite.AggregateDisplayName.Default=Par défaut

AggregateEditorComposite.AggregateDisplayName.None=Aucun

AggregateEditorComposite.AggregateParameterDefinition.Title=Regrouper les définitions de paramètre

AggregateEditorComposite.Button.Cancel=Annuler

AggregateEditorComposite.Button.OK=OK

AggregateEditorComposite.Tooltip.SetAggregateFunction=Définir la fonction d'agrégation

LocalizedNumberEditorComposite.error.Title=Erreur de format des nombres

LocalizedNumberEditorComposite.error.Message=Valeur de nombre non valide : "{0}"

SeriesRegionSheet.message.dialRegion=Région de l'indicatif -

GroupSortingDialog.Composite.Group.Sorting=Tri en cours

GroupSortingDialog.Composite.Label.SortLocale=&Local :

GroupSortingDialog.Composite.Label.SortStrength=Intensi&té :

GroupSortingDialog.Label.GroupAndSorting=Regroupement et tri
GroupSortingDialog.Sort.Locale.Auto=Auto

GroupSortingDialog.Sort.Strength.ASCII=ASCII
GroupSortingDialog.Sort.Strength.IDENTICAL=IDENTIQUE

GroupSortingDialog.Sort.Strength.PRIMARY=PRIMAIRE

GroupSortingDialog.Sort.Strength.QUATENARY=QUATERNAIRE

GroupSortingDialog.Sort.Strength.SECONDARY=SECONDAIRE

GroupSortingDialog.Sort.Strength.TERTIARY=TERTIAIRE

GroupSortingDialog.Sort.SortOn.Warning.Title=Avertissement SortOn

GroupSortingDialog.Sort.SortOn.Warning.Message=L'expression SortOn ne peut pas être vide.

GanttSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour GanttSeriesAttributeComposite.

GanttChart.Txt.DefaultGanttChartTitle=Titre du graphique de Gantt

GanttChart.Txt.DisplayName=Gantt

GanttChart.Txt.Description=Les graphiques de Gantt standard comportent une ligne de liaison avec des repères de début et de fin.

GanttChart.Txt.HelpText=Les graphiques de Gantt permettent de représenter la répartition de tâches ou d'activités sur un axe de temps.

GanttChart.SubType.Standard=Graphique de Gantt standard

GanttSeriesAttributeComposite.Lbl.Marker=Repères

GanttSeriesAttributeComposite.Lbl.Start=Début :

GanttSeriesAttributeComposite.Lbl.End=Fin :

GanttSeriesAttributeComposite.Lbl.Bars=Barres

GanttSeriesAttributeComposite.Lbl.Outline=Contour

GanttSeriesAttributeComposite.Lbl.OutlineFill=Remplissage du contour :

GanttSeriesAttributeComposite.Lbl.BarPalette=Utiliser la &palette de séries pour la couleur de barre

DecorationSheet.Label.DecorationLabels=Etiquettes de tâches

BubbleChart.Txt.DefaultBubbleChartTitle=Titre du graphique à bulles

BubbleChart.Txt.Description=Les graphiques à bulles affichent les valeurs disposées sur le tracé en utilisant les données de catégorie et de valeur comme coordonnées. \nChaque valeur de données est indiquée par un repère.

BubbleChart.Txt.HelpText=Les graphiques à bulles affichent des valeurs de données espacées au hasard associées à des axes sans rapport avec les catégories. Chaque point de données est associé à l'échelle de l'axe des X et des Y.

BubbleChart.Txt.DisplayName=Bulle

BubbleChart.SubType.Standard=Graphique à bulles standard

BubbleSeriesAttributeComposite.Lbl.ShadowColor=O&mbre :

BubbleSeriesAttributeComposite.Lbl.Marker=Repère

BubbleSeriesAttributeComposite.Lbl.IsVisible=Visible

BubbleSeriesAttributeComposite.Lbl.Type=Type :

BubbleSeriesAttributeComposite.Lbl.Size=Taille :

BubbleSeriesAttributeComposite.Lbl.Line=Ligne

BubbleSeriesAttributeComposite.Lbl.AccLine=Ligne d'accélération

BubbleSeriesAttributeComposite.Lbl.LinePalette=Utiliser la &palette de séries pour la couleur de trait

BubbleSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour BubbleSeriesAttributeComposite.

BubbleSeriesAttributeComposite.Lbl.ShowLinesAsCurves=Afficher les lignes sous la forme de cour&bes

BubbleSeriesAttributeComposite.Lbl.Orientation=&Orientation

DifferenceChart.Txt.DefaultDifferenceChartTitle=Titre du graphique de différence

DifferenceChart.Txt.Description=Les graphiques de différence utilisent deux remplissages pour représenter les zones positives et négatives.

DifferenceChart.Txt.HelpText=Les graphiques de différence servent généralement à représenter la différence entre deux champs de données.

DifferenceChart.Txt.DisplayName=Différence

DifferenceChart.SubType.Standard=Graphique de différence standard

DifferenceSeriesAttributeComposite.Exception.IllegalArgument=La série de type {0} est un argument non valide pour DifferenceSeriesAttributeComposite.

DifferenceSeriesAttributeComposite.Lbl.Line=Lignes

DifferenceSeriesAttributeComposite.Lbl.PositiveLine=Positif

DifferenceSeriesAttributeComposite.Lbl.NegativeLine=Négatif

DifferenceSeriesAttributeComposite.Lbl.ShowLinesAsCurves=Afficher les lignes sous la forme de &courbes

DifferenceSeriesAttributeComposite.Lbl.LinePalette=&Utiliser la palette de séries pour la couleur de trait

PositiveNegativeColorDialog.Lbl.PositiveNegativeColorEditor=Editeur de couleurs positives/négatives

PositiveNegativeColorDialog.Lbl.PositiveColor=Couleur positive

PositiveNegativeColorDialog.Lbl.NegativeColor=Couleur négative

PositiveNegativeColorDialog.Lbl.Preview=Aperçu

########### Field Assist Preferences ###########################
ssPreferencesContentAssistKey= Clé de l'assistant de contenu :

ssPreferencesContentAssistKeyCtlSpace= Ctrl+E&space

ssPreferencesContentAssistKeyAsterisk= * (Astéris&que)

ssPreferencesContentAssistKeyAnyKey= Touche alp&hanumérique (sur retard d'auto-activation)

ssPreferencesContentAssistKeyCustom= Perso&nnalisée

ssPreferencesContentAssistKeyPropagate= &Propager les touches pour vérifier que la fenêtre contextuelle est active

ssPreferencesContentAssistDelay= R&etard (en millisecondes) lorsque la fonction d'attribution de contenu est auto-activée :

ssPreferencesDescription= Cette page regroupe les décorations utilisées dans la boîte de dialogue du générateur de graphiques.

ssPreferencesDecoratorVert= Emplacement vertical :

ssPreferencesDecoratorTop= &Haut

ssPreferencesDecoratorCenter= &Centre

ssPreferencesDecoratorBottom= &Bas

ssPreferencesDecoratorHorz= Emplacement horizontal :

ssPreferencesDecoratorLeft= &Gauche

ssPreferencesDecoratorRight= &Droite

ssPreferencesDecoratorMargin= Largeur de &marge :

ssPreferencesContentAssistDescription= Cette page décrit le comportement de l'assistant de contenu.

ssPreferencesContentAssistResult= Lorsqu'une proposition de contenu est sélectionnée :

ssPreferencesContentAssistResultReplace= &Remplacer le contenu du champ

ssPreferencesContentAssistResultInsert= &Insérer dans le contenu du champ

ssPreferencesContentAssistFilter= Lorsque vous saisissez des informations alors que la fenêtre contextuelle est ouverte :

ssPreferencesContentAssistFilterCumulative= Fi&ltrage du contenu de la fenêtre avec une saisie cumulée

ssPreferencesContentAssistFilterCharacter= Fil&trage de la fenêtre en fonction du dernier caractère saisi

ssPreferencesContentAssistFilterNone= &Pas de filtrage

ssPreferencesShowRequiredFieldLabelIndicator= &Identifier les champs requis

ssPreferencesAssistSymbol= Emplacement du symbole d'assistance

ssDecoratorContentAssist= Un assistant de contenu est disponible sur ce champ, appuyez sur {0}

ssDecorationMenuItem=Supprimer les caractères incorrects


### Multiple Hyperlinks ###
MenuStyleDialog.Column.Properties=Propriétés

MenuStyleDialog.Column.Value=Valeur

MenuStyleDialog.Style.Menu=Menu

MenuStyleDialog.Style.MenuItem=Elément de menu

MenuStyleDialog.Style.OnMouseOver=Lors du déplacement de la souris sur l'élément

MenuStyleDialog.Style.OnMouseOut=Lors du déplacement de la souris hors de l'élément

MenuStylesDialog.Btn.Add=&Ajouter

MenuStylesDialog.Btn.Remove=Supp&rimer

MenuStylesDialog.Label.Style=&Style :

MenuStylesDialog.title=Propriétés du menu de lien hypertexte

MenuStylesDialog.Title=Styles de menu de lien hypertexte

ItemLabel.Auto=Auto
