Shared.Lbl.OK=\ \ \ 확인

Shared.Lbl.Cancel=취소

Shared.Lbl.Triggers=대화형 작업

Shared.Tooltip.FormatSpecifier=형식 지정자 편집기 호출

Shared.mne.Visibile_v=표시(&V)

Shared.mne.Visibile_s=표시(&S)

Shared.mne.Background_K=배경(&K):

ChartWithAxesImpl.Z_Axis.title=Z축 제목

ChartSheetImpl.Buttom.Auto=자동(&U)

ChartSheetImpl.Button.AutoHide=표시할 데이터가 없는 경우 차트 숨기기(&D)

ChartSheetImpl.Button.EnableStudyLayout=학습 레이아웃 사용

ChartSheetImpl.Button.ShowEmptyMsg=다음 메시지가 있는 차트 표시(&M):

ChartSheetImpl.Group.EmptyMessage=표시 유형

ChartSheetImpl.Group.EmptyMessage&=표시 유형(&V)

ChartSheetImpl.Label.Outline=윤곽선:

ChartLegendImpl.Group.Rotation=회전

ChartPlotSheetImpl.Label.Outline=윤곽선:

ChartPlotSheetImpl.Label.Visible=표시(&V)

ChartPlotSheetImpl.Label.Visible2=표시(&I)

ChartPlotSheetImpl.Label.PlotArea=플롯 영역

ChartPlotSheetImpl.Label.AreaFormat=영역 형식

ChartPlotSheetImpl.Label.AreaFormat&=영역 형식(&A)

ChartTitleSheetImpl.Label.ChartTitle=차트 제목(&H):

ChartTitleSheetImpl.Label.Interactivity=제목 대화형 작업

ChartTitleSheetImpl.Titel.Tooltip=제목 도구 설명

ChartTitleSheetImpl.Label.Tooltip=도구 설명:

ScriptSheetImpl.Lbl.Script=스크립트:

ScriptSheetImpl.Lbl.Update=업데이트

ScriptSheetImpl.Title.SheetTitle=스크립트 - 차트에 대한 스크립트 설정/편집

GeneralSheetImpl.Lbl.ChartTitle=차트 제목:

GeneralSheetImpl.Lbl.Description=설명(&D):

GeneralSheetImpl.Lbl.GeneralProperties=일반 속성

GeneralSheetImpl.Lbl.Type=형식:

GeneralSheetImpl.Lbl.Subtype=하위 형식:

GeneralSheetImpl.Lbl.Units=단위:

GeneralSheetImpl.Lbl.ColumnCount=열\n개수:

GeneralSheetImpl.Lbl.ChartBackground=배경:

GeneralSheetImpl.Lbl.ChartWall=벽:

GeneralSheetImpl.Lbl.ChartFloor=바닥:

GeneralSheetImpl.Lbl.ChartOutline=차트 윤곽선

GeneralSheetImpl.Lbl.TitleProperties=제목 속성

GeneralSheetImpl.Lbl.ExtendedProperties=확장 속성

GeneralSheetImpl.Lbl.SeriesWidth=계열 깊이(&S): \n ({0})

GeneralSheetImpl.Title.SheetTitle=일반 - 일반 차트 속성 설정

BaseAxisDataSheetImpl.Lbl.Type=형식:

BaseAxisDataSheetImpl.Lbl.Title=축 제목:

BaseAxisDataSheetImpl.Lbl.Origin=기점(&A):

BaseAxisDataSheetImpl.Lbl.Value=값(&U):

BaseAxisDataSheetImpl.Lbl.YAxisCount=Y 축 개수:

AbstractScaleSheet.AutoExpand=자동 확대(&A)

AbstractScaleSheet.Label.Step=단계형

AbstractScaleSheet.Label.Auto=자동(&A)

AbstractScaleSheet.Label.Factor=비율(값/포인트)(&F):

BaseAxisDataSheetImpl.Lbl.Minimum=최소(&M):

BaseAxisDataSheetImpl.Lbl.MajorGridStepNum=주 눈금 단계 번호(&N):

BaseAxisDataSheetImpl.Lbl.Maximum=최대(&X):

AbstractScaleSheet.Label.StepSize=단계 간격(&I):

BaseAxisDataSheetImpl.Lbl.Unit=단위(&U):

BaseAxisDataSheetImpl.Lbl.MinorGridCount=단위당 부 눈금 개수(&M):

BaseAxisDataSheetImpl.Lbl.BaseAxis=범주 축

BaseAxisDataSheetImpl.Title.SheetTitle=데이터 > X축 - X축 데이터 설정

BaseAxisDataSheetImpl.Lbl.BaseAxis2=범주 축 ({0})

BaseAxisAttributeSheetImpl.Lbl.GapWidth=간격 너비:

BaseAxisAttributeSheetImpl.Lbl.MajorGrid=주 눈금

BaseAxisAttributeSheetImpl.Lbl.MinorGrid=부 눈금

BaseAxisAttributeSheetImpl.Lbl.Orientation=방향:

BaseAxisAttributeSheetImpl.Lbl.PercentSign=%
BaseAxisAttributeSheetImpl.Lbl.ShowAxisLine=축 선 표시(&X)

BaseAxisAttributeSheetImpl.Lbl.IsTickBetweenCategories=범주 사이에 교차(&B)

BaseAxisAttributeSheetImpl.Lbl.AxisLineColor=축 선 색(&C):

BaseAxisAttributeSheetImpl.Exception.IllegalArgument=축 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

BaseAxisAttributeSheetImpl.Title.SheetTitle=특성 > X축 - X축 특성 사용자 지정

BaseAxisMarkerAttributeSheetImpl.Lbl.Value=값(&U):

BaseAxisMarkerAttributeSheetImpl.Lbl.Anchor=앵커(&C):

BaseAxisMarkerAttributeSheetImpl.Lbl.Fill=채우기(&F):

BaseAxisLabelAttributeSheetImpl.Lbl.Label=레이블

BaseAxisLabelAttributeSheetImpl.Lbl.Title=제목

BaseAxisLabelAttributeSheetImpl.Exception.IllegalArgument=레이블 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

BaseAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=교차 레이블 표시

BaseAxisLabelAttributeSheetImpl.Title.SheetTitle=특성 > X축 > 레이블 - X축 레이블 사용자 지정

BaseAxisMarkerAttributeSheetImpl.Lbl.AddLine=선 추가(&A)

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRange=범위 추가(&D)

BaseAxisMarkerAttributeSheetImpl.Lbl.AddRegion=영역 추가(&A)

BaseAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=항목 제거(&R)

BaseAxisMarkerAttributeSheetImpl.Lbl.StartValue=시작 값(&T):

BaseAxisMarkerAttributeSheetImpl.Lbl.EndValue=끝 값:(&E)

BaseAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=범위 윤곽선

BaseAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ 축

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=마커 선 특성

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=마커 속성

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0} {1}
BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange {0} {1}
BaseAxisMarkerAttributeSheetImpl.Title.SheetTitle=특성 > X축 > 표지 - X축 표지 설정

BaseAxisMarkerAttributeSheetImpl.Lbl.InnerRadius=내부 반경(&I):

BaseAxisMarkerAttributeSheetImpl.Lbl.OuterRadius=외부 반경(&O):

BaseAxisMarkerAttributeSheetImpl.Lbl.DialProperties=지역 속성

BaseAxisMarkerAttributeSheetImpl.Lbl.DialLabelProperties=지역 레이블 속성

BaseAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=표지 레이블 속성

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveDown=아래로(&N)

BaseAxisMarkerAttributeSheetImpl.Lbl.MoveUp=위로(&P)

BaseAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=표지 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

BaseSeriesDataSheetImpl.Choice.Unsorted=정렬되지 않음

BaseSeriesDataSheetImpl.Lbl.DataSorting=데이터 정렬(&S):

BaseSeriesDataSheetImpl.Lbl.YSeriesCount=Y 계열 수:

BaseSeriesAttributeSheetImpl.Lbl.Palette=색상표

BaseAxisDataSheetImpl.Exception.IllegalArgument=축 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

BaseSeriesAttributeSheetImpl.Lbl.SeriesType=계열 형식:

BaseSeriesAttributeSheetImpl.Title.SheetTitle=특성 > X 계열 - 범주 (X) 계열 특성 사용자 지정

BaseSeriesDataSheetImpl.Lbl.DataDefinitions=데이터 정의

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinitions=값 계열 정의

BaseSeriesDataSheetImpl.Lbl.OrthogonalSeriesDefinition=값 계열 정의

BaseSeriesDataSheetImpl.Title.SheetTitle=데이터 > 범주(X) 계열 - 범주(X) 계열 데이터 설정

BaseSeriesDataSheetImpl.Lbl.DialSeriesCount=다이얼 개수:

BaseSeriesDataSheetImpl.Lbl.DialSeriesDefinitions=다이얼 시리즈 정의

DialScaleDialog.Title.DialScale=다이얼 배율

DialTicksDialog.Title.DialTicks=다이얼 틱

OrthogonalAxisAttributeSheetImpl.Lbl.HideAxisLine=축 선 숨기기

OrthogonalAxisAttributeSheetImpl.Lbl.Orientation=방향:

OrthogonalAxisAttributeSheetImpl.Lbl.PercentSign=%
OrthogonalAxisAttributeSheetImpl.Lbl.GapWidth=간격 너비:

OrthogonalAxisAttributeSheetImpl.Lbl.MajorGrid=주 눈금

OrthogonalAxisAttributeSheetImpl.Lbl.MinorGrid=부 눈금

OrthogonalAxisAttributeSheetImpl.Lbl.AxisLineColor=축 선 색:

OrthogonalAxisAttributeSheetImpl.Exception.IllegalArgument=축 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

OrthogonalAxisAttributeSheetImpl.Title.SheetTitle=특성 > Y축 - Y축 특성 사용자 지정

OrthogonalAxisDataSheetImpl.Lbl.Type=형식(&P):

OrthogonalAxisDataSheetImpl.Lbl.Title=축 제목:

OrthogonalAxisDataSheetImpl.Lbl.Origin=기점(&O):

OrthogonalAxisDataSheetImpl.Lbl.Value=값:

OrthogonalAxisDataSheetImpl.Lbl.PrimaryAxis=주 축

OrthogonalAxisDataSheetImpl.Lbl.Scale=배율

OrthogonalAxisDataSheetImpl.Lbl.Minimum=최소:

OrthogonalAxisDataSheetImpl.Lbl.Maximum=최대:

OrthogonalAxisDataSheetImpl.Lbl.Step=단계:

OrthogonalAxisDataSheetImpl.Lbl.Unit=단위:

OrthogonalAxisDataSheetImpl.Lbl.MinorGridCount=단위당 부 눈금 개수:

OrthogonalAxisDataSheetImpl.Lbl.SeriesDefinitionCount=계열 정의 수:

OrthogonalAxisDataSheetImpl.Lbl.SeriesGroupingKey=계열 그룹화 키(옵션)

OrthogonalAxisDataSheetImpl.Lbl.OrthogonalAxis=값 축

OrthogonalAxisDataSheetImpl.Exception.IllegalArgument=축 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

OrthogonalAxisDataSheetImpl.Title.SheetTitle=데이터 > Y축  - Y축 데이터 설정

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Label=레이블

OrthogonalAxisLabelAttributeSheetImpl.Lbl.Title=제목

OrthogonalAxisLabelAttributeSheetImpl.Lbl.ShowLabelsStaggered=교차 레이블 표시

OrthogonalAxisLabelAttributeSheetImpl.Title.SheetTitle=특성 > Y축 > 레이블 - Y축 레이블 사용자 지정

OrthogonalAxisLabelAttributeSheetImpl.Exception.IllegalArgument=레이블 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Values=값:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Anchor=앵커:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddLine=선 추가

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.AddRange=범위 추가

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.EndValue=끝 값:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.ForAxis=\ 축 {0}

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RemoveEntry=항목 제거

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.StartValue=시작 값:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.RangeOutline=범위 윤곽선

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLine=MarkerLine {0,number,integer} {1}
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerRange=MarkerRange 
OrthogonalAxisMarkerAttributeSheetImpl.Lbl.Fill=채우기:

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerProperties=표지 속성

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLineAttributes=표지선 특성

OrthogonalAxisMarkerAttributeSheetImpl.Lbl.MarkerLabelProperties=표지 레이블 속성

OrthogonalAxisMarkerAttributeSheetImpl.Exception.IllegalArgument=표지 특성 시트에 대한 인수가 잘못되었습니다. 차트는 ChartWithAxes 형식이어야 합니다.

OrthogonalSeriesAttributeSheetImpl.Lbl.Remove=제거(&R)

OrthogonalSeriesAttributeSheetImpl.Lbl.Add=추가(&A)

OrthogonalSeriesAttributeSheetImpl.Lbl.Up=위로(&U)

OrthogonalSeriesAttributeSheetImpl.Lbl.Down=아래로(&D)

OrthogonalSeriesAttributeSheetImpl.Lbl.Prefix=접두사(&F):

OrthogonalSeriesAttributeSheetImpl.Lbl.Suffix=접미사(&X):

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesType=계열 형식:

OrthogonalSeriesAttributeSheetImpl.Lbl.HideSeries=계열 숨기기

OrthogonalSeriesAttributeSheetImpl.Lbl.Palette=색상표

OrthogonalSeriesAttributeSheetImpl.Lbl.DataPoint=데이터 요소

OrthogonalSeriesAttributeSheetImpl.Lbl.Separator=구분 기호(&E):

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDetails=계열 상세 정보

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPoint=계열 DataPoint

OrthogonalSeriesAttributeSheetImpl.Lbl.SeriesDataPointComponent=계열 DataPoint 구성 요소 - {0}

OrthogonalSeriesAttributeSheetImpl.Lbl.StackSeriesElements=누적 계열 요소

OrthogonalSeriesAttributeSheetImpl.Title.SheetTitle=특성 > Y 계열 - 값(Y) 계열 특성 사용자 지정

OrthogonalSeriesDataSheetImpl.Lbl.Triggers=대화형 작업

OrthogonalSeriesDataSheetImpl.Lbl.DataDefinitions=데이터 정의

OrthogonalSeriesDataSheetImpl.Lbl.Scale=배율

OrthogonalSeriesDataSheetImpl.Lbl.Minimum=최소(&M):

OrthogonalSeriesDataSheetImpl.Lbl.Maximum=최대(&X):

OrthogonalSeriesDataSheetImpl.Lbl.Step=단계(&S):

OrthogonalSeriesDataSheetImpl.Lbl.Unit=단위:

OrthogonalSeriesDataSheetImpl.Lbl.MinorGridCount=단위당 부 눈금 개수(&U):

OrthogonalSeriesDataSheetImpl.Lbl.MajorGrid=주 눈금

OrthogonalSeriesDataSheetImpl.Lbl.MinorGrid=부 눈금

OrthogonalSeriesDataSheetImpl.Title.SheetTitle=데이터 > 값(Y) 계열 - 값(Y) 계열 데이터 설정

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Label=레이블

OrthogonalSeriesLabelAttributeSheetImpl.Lbl.Title=제목

OrthogonalSeriesLabelAttributeSheetImpl.Title.SheetTitle=특성 > Y 계열 > 레이블 - 값(Y) 계열 레이블 사용자 지정

AreaChart.Txt.PercentStackedDescription=백분율 누적 영역형 차트에는 누적된 영역(각 단위에서 가장 낮은 점에서부터 \n가장 높은 점까지)의 총 높이가 100이 되도록 영역이 서로 누적되어 표시됩니다.

AreaChart.Txt.StackedDescription=누적 영역형 차트에는 서로 누적된 영역이 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

AreaChart.Txt.OverlayDescription=이중 영역형 차트에는 각 계열의 영역이 서로 독립적으로 표시됩니다. \n계열의 값을 결합하는 영역이 표시됩니다.

AreaChart.Txt.HelpText=영역은 렌더링되는 각 계열을 나타냅니다. 선택적인 표지를 사용하여 데이터를 그리는 시점을 강조할 수 있습니다. 누적된 영역은 그 아래 있는 영역 계열 데이터 요소의 위치에 상대적인 각 범주 요소를 표시합니다. 누적된 백분율 영역은 해당 범주에 대한 백분율로 그려진 각 데이터 요소를 표시합니다.

AreaChart.Txt.DefaultAreaChartTitle=영역형 차트 제목

AreaChart.Txt.DisplayName=영역형

AreaChart.SubType.Stacked=누적

AreaChart.SubType.PercentStacked=누적 백분율

AreaChart.SubType.Overlay=이중

AreaSeriesUIProvider.Lbl.SeriesDefinition=계열 정의

MeterChart.Txt.DefaultMeterChartTitle=측정기 차트 제목

MeterChart.Txt.DisplayName=측정기

MeterChart.SubType.Standard=표준 측정기 차트

MeterChart.SubType.Superimposed=중첩 측정기 차트

MeterChart.Tooltip.InputExpression=각 항목의 범례 텍스트로 표시되는 식을 입력합니다.

MeterChart.Txt.HelpText=측정기 차트에는 특정 측정에 대한 현재 데이터 값이 표시됩니다. 다른 색상의 영역은 측정 값 범위를 나타냅니다. 바늘은 다이얼과 연관되며, 다이얼 값을 표시합니다.

MeterChart.Txt.Description=표준 측정기 차트에는 영역을 포함한 단일 다이얼이 포함됩니다. \n다이얼 배경은 다른 색상을 가진 영역으로 분류할 수 있습니다.

MeterChart.Txt.SuperimposedDescription=중첩 측정기 차트에는 동일한 영역을 포함한 다중 다이얼이 포함됩니다. \n다이얼이 동시에 겹치므로 단일 영역 내 여러 바늘을 나타낼 수 있습니다.

MeterSeriesAttributeComposite.Lbl.Radius=반경(&U):

MeterSeriesAttributeComposite.Lbl.StartAngle=시작 각도(&G):

MeterSeriesAttributeComposite.Lbl.StopAngle=중지 각도(&E):

MeterSeriesAttributeSheetImpl.Lbl.Type=형식:

MeterSeriesAttributeSheetImpl.Lbl.Fill=채우기(&I):

MeterSeriesAttributeComposite.Lbl.DialTicks=틱(&T)

MeterSeriesAttributeComposite.Lbl.DialScale=배율(&C)

BarSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 BarSeriesAttributeComposite에 대한 잘못된 인수입니다.

BarSeriesUIProvider.Lbl.SeriesDefinition=계열 정의

BarSeriesAttributeComposite.Lbl.SeriesOutline=계열 윤곽선(&O):

BarBottomAreaComponent.Label.CategoryXSeries=범주 (X) 계열(&C):

StockSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 StockSeriesAttributeComposite에 대한 잘못된 인수입니다.

StockSeriesDataDefinitionComposite.Lbl.StockSeriesDefinition=주식형 계열 정의

StockSeriesAttributeComposite.Lbl.CandleFill=원통형 채우기:

StockSeriesAttributeComposite.Lbl.StickLength=스틱 길이:

StockSeriesAttributeComposite.Lbl.Line=꺽은선형

StockSeriesDataDefinitionComposite.Lbl.High=높음:

StockSeriesDataDefinitionComposite.Lbl.HighValue=\ - 고가

StockSeriesDataDefinitionComposite.Lbl.Low=낮음:

StockSeriesDataDefinitionComposite.Lbl.LowValue=\ - 저가

StockSeriesDataDefinitionComposite.Lbl.Open=열기:

StockSeriesDataDefinitionComposite.Lbl.OpenValue=\ - 시가

StockSeriesDataDefinitionComposite.Lbl.Close=닫기:

StockSeriesDataDefinitionComposite.Lbl.CloseValue=\ - 종가

StockChart.Txt.DefaultStockChartTitle=주식형 차트 제목

StockChart.Txt.DisplayName=주식형

StockChart.Txt.BarStickDescription=막대형 주식 차트에는 수직선 한 개가 있고 두 수평선이 이 수직선을 가리킵니다. \n수직선의 위쪽 점과 아래쪽 점이 주식의 시가와 종가 값입니다. \n두 수평선은 고가와 저가를 나타냅니다.

StockChart.Txt.CandleStickDescription=원통형 주식 차트에는 상자 한 개가 있고 상자의 끝에서부터 위 아래로 여러 선들이 확장 분포됩니다. \n상자의 위쪽 가장자리와 아래쪽 가장자리가 주식의 시가와 종가 값입니다. \n선의 위쪽 점과 아래쪽 점은 고가와 저가를 나타냅니다.

StockChart.Txt.HelpText=주식형 차트에는 각 요소가 단일 거래 세션을 나타내는 그래픽 요소가 표시됩니다. 선의 위쪽 끝은 세션의 고가를 나타내고 아래쪽 끝은 세션의 저가를 나타냅니다. 막대가 시가와 종가를 연결합니다.

StockChart.SubType.CandleStick=원통형 주식 차트

StockChart.SubType.BarStick=막대형 주식 차트

LineAttributesComposite.Lbl.Style=스타일:

LineAttributesComposite.Lbl.Width=너비:

LineAttributesComposite.Lbl.Color=색:

LineAttributesComposite.Lbl.IsVisible=표시

LineSeriesUIProvider.Lbl.SeriesDefinition=계열 정의

LineSeriesAttributeComposite.Lbl.ShadowColor=그림자(&D):

LineSeriesAttributeComposite.Lbl.Marker=표지

LineChart.Txt.PercentStackedDescription=백분율 누적 선형 차트에는 누적된 선(각 단위에서 가장 낮은 점에서부터 가장 높은 점까지)의 \n총 높이가 100이 되도록 선이 서로 누적되어 표시됩니다.

LineSeriesAttributeComposite.Lbl.IsVisible=표시(&V)

LineSeriesAttributeComposite.Lbl.Type=형식:

LineSeriesAttributeComposite.Lbl.Size=크기(&S):

LineSeriesAttributeComposite.Lbl.Line=꺾은선형

LineSeriesMarkerSheet.Label.Markers=표지

LineSeriesMarkerSheet.Label.Add=추가(&A)

LineSeriesMarkerSheet.Label.Remove=제거(&R)

LineSeriesAttributeComposite.Lbl.LinePalette=선 색으로 계열 색상표 사용(&P)

LineChart.Txt.DefaultLineChartTitle=선형 차트 제목

LineSeriesAttributeComposite.Lbl.ConnectMissingValue=누락된 값 연결(&O)

LineChart.Txt.DisplayName=선형

LineChart.SubType.Stacked=누적

LineChart.SubType.PercentStacked=누적 백분율

LineChart.SubType.Overlay=이중

LineChart.Txt.StackedDescription=누적 선형 차트에는 서로 누적된 선이 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

LineChart.Txt.OverlayDescription=이중 선형 차트에는 각 계열의 선이 서로 독립적으로 표시됩니다. \n계열의 값을 결합하는 선이 표시됩니다.

LineSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 LineSeriesAttributeComposite에 대한 잘못된 인수입니다.

LineSeriesAttributeComposite.Lbl.ShowLinesAsCurves=선을 곡선으로 표시(&H)

LineChart.Txt.HelpText=선은 렌더링되는 각 계열을 나타냅니다. 선택적인 표지를 사용하여 데이터를 그리는 시점을 강조할 수 있습니다. 누적된 선은 그 아래 있는 선 계열 데이터 요소의 위치에 상대적인 각 범주 요소를 표시합니다. 누적된 백분율 선은 해당 범주에 대한 백분율로 그려진 각 데이터 요소를 표시합니다.

ScatterChart.Txt.Description=분산형 차트에는 범주와 값 데이터를 좌표로 사용하여 플롯 위에 정렬된 값이 표시됩니다. \n각 데이터 값은 표지로 표시됩니다.

ScatterChart.Txt.HelpText=분산형 차트는 범주가 아닌 축에 연결된 임의로 배치된 데이터 값을 표시합니다. 각 데이터 요소는 X 및 Y 축 배율에 연결되어 있습니다.

ScatterSeriesUIProvider.Lbl.SeriesDefinition=계열 정의

ScatterChart.Txt.DefaultScatterChartTitle=분산형 차트 제목

ScatterChart.Txt.DisplayName=분산형

ScatterChart.SubType.Standard=표준 분산형 차트

BarChart.Txt.DefaultBarChartTitle=막대 차트 제목

BarChart.Txt.DisplayName=막대형

BarChart.SubType.Stacked=누적

BarChart.SubType.PercentStacked=누적 백분율

BarChart.SubType.Side=연속

BarChart.Txt.StackedDescription=누적 막대형 차트에는 서로 누적된 막대가 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

BarChart.Txt.PercentStackedDescription=백분율 누적 막대형 차트에는 누적된 막대(가장 낮은 점에서부터 가장 높은 점까지)의 \n총 높이가 100이 되도록 막대가 서로 누적되어 표시됩니다.

BarChart.Txt.HelpText=막대형 차트는 데이터 클래스 또는 그룹을 비교하기 위해 만든 것입니다. 같은 범주 내 서로 다른 계열의 데이터 값이 분리된 열로 서로 인접하여 나타나거나 단일 열 안의 섹션으로 누적되어 나타납니다. 이는 선택한 하위 형식에 의해 결정됩니다.

BarChart.Txt.SideBySideDescription=연속 막대형 차트에는 각 계열의 막대가 나란히 표시됩니다. \n이 막대는 동일한 너비로 정렬됩니다. \n막대의 너비는 그려지는 계열 수에 따라 달라집니다.

TubeChart.Txt.DefaultTubeChartTitle=튜브 차트 제목

TubeChart.Txt.DisplayName=튜브

TubeChart.SubType.Stacked=누적

TubeChart.SubType.PercentStacked=누적 백분율

TubeChart.SubType.Side=연속

TubeChart.Txt.StackedDescription=누적 튜브 차트에는 누적된 튜브가 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

TubeChart.Txt.PercentStackedDescription=백분율 누적 튜브 차트에는 누적된 튜브(최저점부터 최고점까지)의 \n전체 높이가 100이 되도록 튜브가 누적되어 표시됩니다.

TubeChart.Txt.HelpText=튜브 차트는 데이터 클래스 또는 그룹을 비교하기 위해 고안되었습니다. 선택한 하위 유형에 따라서, 같은 범주 내 서로 다른 계열의 데이터 값이 분리된 열로 서로 인접하여 나타나거나 단일 열 안의 섹션으로 누적되어 나타납니다.

TubeChart.Txt.SideBySideDescription=연속 튜브 차트에는 각 계열의 튜브가 나란히 표시됩니다. \n이 튜브는 동일한 너비로 정렬됩니다. \n튜브의 너비는 그려지는 계열 수에 따라 달라집니다.

ConeChart.Txt.DefaultConeChartTitle=원뿔 차트 제목

ConeChart.Txt.DisplayName=원뿔

ConeChart.SubType.Stacked=누적

ConeChart.SubType.PercentStacked=누적 백분율

ConeChart.SubType.Side=연속

ConeChart.Txt.StackedDescription=누적 원뿔 차트에는 누적된 원뿔이 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

ConeChart.Txt.PercentStackedDescription=백분율 누적 원뿔 차트에는 누적된 원뿔(최저점부터 최고점까지)의 \n전체 높이가 100이 되도록 원뿔이 누적되어 표시됩니다.

ConeChart.Txt.HelpText=원뿔 차트는 데이터 클래스 또는 그룹을 비교하기 위해 고안되었습니다. 선택한 하위 유형에 따라서, 같은 범주 내 서로 다른 계열의 데이터 값이 분리된 열로 서로 인접하여 나타나거나 단일 열 안의 섹션으로 누적되어 나타납니다.

ConeChart.Txt.SideBySideDescription=연속 원뿔 차트에는 각 계열의 원뿔이 나란히 표시됩니다. \n이 원뿔은 동일한 너비로 정렬됩니다. \n원뿔의 너비는 그려지는 계열 수에 따라 달라집니다.

PyramidChart.Txt.DefaultPyramidChartTitle=피라미드 차트 제목

PyramidChart.Txt.DisplayName=피라미드

PyramidChart.SubType.Stacked=누적

PyramidChart.SubType.PercentStacked=누적 백분율

PyramidChart.SubType.Side=연속

PyramidChart.Txt.StackedDescription=누적 피라미드 차트에는 누적된 피라미드가 표시됩니다. \n양수 값과 음수 값은 각각 기점 위와 아래에 따로 누적됩니다.

PyramidChart.Txt.PercentStackedDescription=백분율 누적 피라미드 차트에는 누적된 피라미드(최저점부터 최고점까지)의 \n총 높이가 100이 되도록 피라미드가 누적되어 표시됩니다.

PyramidChart.Txt.HelpText=피라미드 차트는 데이터 클래스 또는 그룹을 비교하기 위해 고안되었습니다. 선택한 하위 유형에 따라서, 같은 범주 내 서로 다른 계열의 데이터 값이 분리된 열로 서로 인접하여 나타나거나 단일 열 안의 섹션으로 누적되어 나타납니다.

PyramidChart.Txt.SideBySideDescription=연속 피라미드 차트에는 각 계열의 피라미드가 나란히 표시됩니다. \n이 피라미드는 동일한 너비로 정렬됩니다. \n피라미드의 너비는 그려지는 계열 수에 따라 달라집니다.

PieChart.Txt.DefaultPieChartTitle=원형 차트 제목

PieChart.Txt.DisplayName=원형

PieChart.SubType.Standard=표준 원형 차트

PieSeriesUIProvider.Lbl.OrthogonalPrefix=값

PieSeriesUIProvider.Lbl.SeriesDefinition=계열 정의

PieBottomAreaComponent.Label.Percentage=백분율

PieSeriesAttributeComposite.Button.Direction=시계 방향

PieSeriesAttributeComposite.Button.Direction.ToolTipText=원형 조각이 시계 방향에서 렌더링되는지 여부를 지정합니다.

PieSeriesAttributeComposite.Button.InnerRadius=내부 반경:

PieSeriesAttributeComposite.Grp.Slice=조각

PieSeriesAttributeComposite.Lbl.SliceOutline=조각 윤곽선(&O):

PieSeriesAttributeComposite.Lbl.LeaderLine=지시선

PieSeriesAttributeComposite.Lbl.LeaderLineStyle=지시선 스타일(&A):

PieSeriesAttributeComposite.Lbl.LeaderLineLength=지시선 길이(&L):

PieBottomAreaComponent.Label.AnySliceWithASize=입력값보다 크기가 작은 조각은 다른 범주에 결합됩니다.

PieBottomAreaComponent.Label.ExplodeSliceWhen=다음 조건에서 조각 쪼개기(&X):

PieBottomAreaComponent.Label.ByDistance=거리별(&D):

PieBaseSeriesComponent.Label.CategoryDefinition=범주 정의(&C):

PieBaseSeriesComponent.Text.SpecifyExplodeSlice=쪼개기 조각 지정

PieBaseSeriesComponent.Tooltip.EnterBooleanExpression=쪼갤 조각을 제어할 부울 식을 입력하십시오. 입력하지 않을 경우 모든 조각에 쪼개기 거리가 적용됩니다.

PieLeftAreaComponent.Label.SliceSizeDefinition=조각 크기 정의:

PieSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 PieSeriesAttributeComposite에 대한 잘못된 인수입니다.

PieSeriesAttributeComposite.InnerRadiusType.Points=포인트

PieSeriesAttributeComposite.Lbl.Explosion=급증:

PiesBottomAreaComponent.Label.TheRotationOfTheChart=파이 회전: 첫 파이 조각의 시작 각도

PieBottomAreaComponent.Label.Rotation=파이 회전(&N):

PieBottomAreaComponent.Label.MinimumSlice=최소 조각(&M):

PieBottomAreaComponent.Label.MinSliceLabel=조각 레이블(&L):

PieSeriesUIProvider.Lbl.BasePrefix=범주

PieBottomAreaComponent.Label.Value=값

PieBottomAreaComponent.Label.Ratio=파이 비율(&P) :

PieBottomAreaComponent.Label.TheRatioOfTheChart=파이 비율: 높이/너비 비율(0: 비율 자동 맞춤)

PieChart.Txt.Description=원형 차트에는 값이 원형의 조각으로 표시됩니다. \n각 조각의 크기는 해당 조각이 나타내는 값에 비례합니다. \n복수 계열의 원형 차트는 각 계열에 하나씩 복수의 원형으로 그려집니다.

PieChart.Txt.HelpText=원형 차트는 계열 또는 범주의 데이터 값을 전체 원형의 조각 비율로 나타냅니다. 복수 원형 계열이 한 눈금에 표현됩니다.

SeriesUIProvider.Lbl.OrthogonalPrefix=값

SeriesUIProvider.Lbl.SeriesDefinition=계열 정의

SeriesSheetImpl.Label.CategoryBaseSeries=범주 계열

SeriesUIProvider.Lbl.BasePrefix=범주

SeriesSheetImpl.Label.Title=제목

SeriesSheetImpl.Label.Visible=표시

SeriesSheetImpl.Label.Stacked=누적

SeriesSheetImpl.Label.Series=계열

SeriesYSheetImpl.Label.Needles=바늘

SeriesYSheetImpl.Label.Needles&=바늘(&N)

SeriesYSheetImpl.Label.Region=영역

SeriesYSheetImpl.Label.Region&=영역(&O)

SeriesYSheetImpl.Label.Labels=계열 레이블

SeriesYSheetImpl.Label.Labels&=레이블(&E)

SeriesYSheetImpl.Label.DialLabels=다이얼 레이블

SeriesYSheetImpl.Label.DialLabels&=다이얼 레이블(&D)

SeriesYSheetImpl.Label.Titles=제목

SeriesYSheetImpl.Label.Titles&=제목(&T)

SeriesYSheetImpl.Label.Markers=계열 표지

SeriesYSheetImpl.Label.PositiveMarkers=양수 표지

SeriesYSheetImpl.Label.NegativeMarkers=음수 표지

SeriesYSheetImpl.Label.Markers&=마커(&M)

SeriesYSheetImpl.Label.PositiveMarkers&=양수 표지(&P)

SeriesYSheetImpl.Label.NegativeMarkers&=음수 표지(&N)

SeriesYSheetImpl.Label.Decoration=작업

SeriesYSheetImpl.Label.Decoration&=작업 레이블(&T)

SeriesLabelSheet.Label.Format=형식

SeriesLabelSheet.Label.Values=값

SeriesGroupingComposite.Lbl.Type=형식(&T):

SeriesGroupingComposite.Lbl.Unit=단위(&U):

SeriesYSheetImpl.Label.Trendline=곡선 근사 줄

SeriesYSheetImpl.Label.Trendline&=곡선 근사 줄(&C)

SeriesTrendlineSheet.Label.Label=레이블

SeriesTrendlineSheet.Label.Label&=레이블(&L):

SeriesGroupingComposite.Lbl.Grouping=그룹화

SeriesGroupingComposite.Lbl.Enabled=사용(&E)

SeriesSheetImpl.Label.ValueYSeries=값 (Y) 계열

SeriesSheetImpl.Label.Translucent=반투명

SeriesSheetImpl.Label.SeriesPalette=계열 색상표

SeriesSheetImpl.Label.SeriesPalette&=계열 색상표(&S)

SeriesYSheetImpl.Label.DataPoint=데이터 요소

SeriesTrendlineSheet.Label.Outline=윤곽선

SeriesTrendlineSheet.SeriesTrendlineSheet.Lbl.IsVisible=표시(&I)

SeriesGroupingComposite.Lbl.Interval=간격(&V):

SeriesYSheetImpl.Label.ShowLabels=계열 레이블 표시(&S)

SeriesYSheetImpl.Label.ShowDialLabels=다이얼 레이블 표시(&S)

SeriesYSheetImpl.Label.ShowDecoLabels=작업 레이블 표시(&W)

SeriesYSheetImpl.Label.ShowTrendline=곡선 근사 줄 표시(&U)

SeriesYSheetImpl.Label.Interactivity&=대화형 작업(&R)

SeriesYSheetImpl.Label.Interactivity=계열 대화형 작업

SeriesGroupingComposite.Lbl.AggregateExpression=집계식(&A):

SeriesGroupingComposite.Tooltip.SelectIntervalForGrouping=그룹화 간격을 선택하십시오. 0은 그룹화 기준이 X/범주 값임을 나타냅니다.

SeriesPaletteSheet.Label.Auto=자동(&T)

SeriesPaletteSheet.Tab.Axis=축

SeriesPaletteSheet.Tab.Series=계열

SeriesSheetImpl.Label.ValueOrthogonalSeries=값 계열

TitleBlockAttributeSheetImpl.Lbl.Caption=레이블 캡션:

TitleBlockAttributeSheetImpl.Lbl.BlockProperties=블록 속성

TitleBlockAttributeSheetImpl.Lbl.IsBlockVisible=블록 표시 여부

TitleBlockAttributeSheetImpl.Lbl.Anchor=앵커:

TitleBlockAttributeSheetImpl.Lbl.Stretch=맞춤:

TitleBlockAttributeSheetImpl.Lbl.Background=배경:

TitleBlockAttributeSheetImpl.Lbl.Insets=음각

TitlePropertiesSheet.Label.TitleArea=제목 영역

TitlePropertiesSheet.Label.Background=배경(&B):

TitleBlockAttributeSheetImpl.Lbl.Outline=윤곽선

TitlePropertiesSheet.Label.Interactivity=대화형 작업

TitleBlockAttributeSheetImpl.Lbl.LabelProperties=레이블 속성

TitleBlockAttributeSheetImpl.Lbl.ChartTitle=차트 제목

TitleBlockAttributeSheetImpl.Title.SheetTitle=레이아웃 > 제목 블록 - 차트 제목 영역 형식 지정

LegendAttributeSheetImpl.Lbl.GeneralProperties=일반 속성 - 범례 주변 영역

LegendAttributeSheetImpl.Lbl.ClientAreaProperties=클라이언트 영역 속성 - 범례 영역

LegendAttributeSheetImpl.Title.SheetTitle=레이아웃 > 범례 - 범례 영역 형식 지정

LegendLayoutSheet.Label.TitlePercent=제목 백분율(&T):

LegendLayoutSheet.Label.MaxPercent=최대 백분율(&M):

LegendLayoutSheet.Label.WrappingWidth=배치 너비(&W):

SampleDataSheetImpl.Lbl.XSeries=X 계열

SampleDataSheetImpl.Lbl.BaseSampleValues=예제 값:\n {0}

SampleDataSheetImpl.Lbl.SampleValues=예제 값:

SampleDataSheetImpl.Lbl.YSeries=Y 계열

SampleDataSheetImpl.Lbl.SimulateSeriesCount=시뮬레이트 계열 수:

SampleDataSheetImpl.Lbl.Update=업데이트

SampleDataSheetImpl.Title.SheetTitle=데이터 > 예제 - 미리 보기를 위한 예제 데이터 설정

PlotAttributeSheetImpl.Lbl.GeneralProperties=일반 속성 - 축 포함 영역

PlotAttributeSheetImpl.Lbl.ClientAreaProperties=클라이언트 영역 속성 - 축 내 영역

PlotAttributeSheetImpl.Title.SheetTitle=레이아웃 > 플롯 - 플롯 영역 형식 지정

LabelBlockAttributeSheetImpl.Lbl.LabelCaption=레이블 캡션:

LabelBlockAttributeSheetImpl.Lbl.BlockProperties=블록 속성

LabelBlockAttributeSheetImpl.Lbl.IsBlockVisible=블록 표시 여부

LabelBlockAttributeSheetImpl.Lbl.Anchor=앵커:

LabelBlockAttributeSheetImpl.Lbl.Stretch=맞춤:

LabelBlockAttributeSheetImpl.Lbl.Background=배경:

LabelBlockAttributeSheetImpl.Lbl.Insets=음각

LabelAttributesComposite.Lbl.IsVisible=표시(&V)

LabelAttributesComposite.Lbl.IsVisible2=표시(&E)

LabelAttributesComposite.Lbl.Position=위치(&P):

LabelAttributesComposite.Lbl.Background=배경(&B):

LabelAttributesComposite.Lbl.Outline=윤곽선

LabelBlockAttributeSheetImpl.Lbl.Outline=윤곽선

LabelBlockAttributeSheetImpl.Lbl.LabelProperties=레이블 속성

LabelBlockAttributeSheetImpl.Lbl.LabelBlock=레이블 블록

DataDefinitionComposite.Tooltip.InvokeExpressionBuilder=연산식 빌더 호출

DataDefinitionSelector.Exception.NotSupportedForMultipleAxes=\ 다중 축에는 지원되지 않습니다\!

DataDefinitionComposite.Tooltip.InvokeRuleEditor=규칙 편집기 호출

RuleEditorDialog.Title.RuleEditor=규칙 편집기 - {0}

RuleEditorDialog.Lbl.Rules=규칙

RuleEditorDialog.Lbl.Type=형식:

RuleEditorDialog.Lbl.Value=값:

RuleEditorDialog.Lbl.Remove=제거

RuleEditorDialog.Lbl.Add=추가

RuleEditorDialog.Lbl.Update=업데이트

RuleEditorDialog.Exception.InvalidRule=오류\! 잘못된 규칙 인덱스가 전달되었습니다.

FillCanvas.Transparent=투명

FillCanvas.Auto=자동

FillChooserComposite.Button.Pattern=패턴

FillChooserComposite.Lbl.Opacity=불투명도: {0, number, integer}

FillChooserComposite.Lbl.Gradient=그라데이션

FillChooserComposite.Lbl.Transparent=투명

FillChooserComposite.Lbl.CustomColor=사용자 지정 색

FillChooserComposite.Lbl.Image=이미지

FillChooserComposite.Lbl.PositiveNegative=양수/음수

FillChooserComposite.Lbl.Auto=자동

ClientAreaAttributeComposite.Lbl.Background=배경:

ClientAreaAttributeComposite.Lbl.Shadow=그림자(&D):

ClientAreaAttributeComposite.Lbl.Outline=윤곽선

InsetsComposite.Lbl.Insets=음각 ({0})

InsetsComposite.Lbl.Top=위쪽(&T):

InsetsComposite.Lbl.Left=왼쪽(&L):

InsetsComposite.Lbl.Bottom=아래쪽(&M):

InsetsComposite.Lbl.Right=오른쪽(&R):

InsetsEditorDialog.Title.InsetsEditor=음각 편집기 대화 상자

InsetsEditorDialog.Lbl.UnitsMessage=* 모든 값은 {0} 단위입니다.

ExternalizedTextEditorDialog.Title.ExternalizeText=텍스트 외부화

ExternalizedTextEditorDialog.Lbl.ExternalizeText=텍스트 외부화(&X)

ExternalizedTextEditorComposite.Warn.KeyNotFound=속성 파일에서 키를 찾을 수 없거나 속성 파일이 없습니다.

ExternalizedTextEditorComposite.Lbl.EditText=외부화된 텍스트 편집기 호출

ExternalizedTextEditorDialog.Lbl.LookupKey=조사 키(&L):

ExternalizedTextEditorDialog.Lbl.DefaultValue=기본값(&D):

ExternalizedTextEditorDialog.Lbl.ExternalizedValue=외부화된 값:

ExternalizedTextEditorDialog.Warn.KeyNotFound=속성 파일에서 키를 찾을 수 없거나 속성 파일이 없습니다.

ExternalizedTextEditorDialog.Lbl.Value=<키 ''{0}''의 값>

Format.Button.Label=형식

Format.Button.Lbl&=형식(&M)

FormatSpecifierComposite.error.Title=형식 지정자 오류

FormatSpecifierComposite.error.Message=잘못된 형식 지정자 매개 변수 값: "{0}"

FormatSpecifierComposite.Label.DenominatorDigits=분모 숫자

FormatSpecifierComposite.Label.NumeratorValue=분자 값

FormatSpecifierComposite.Lbl.DataType=데이터 형식(&D):

FormatSpecifierComposite.Lbl.DateTime=날짜/시간

FormatSpecifierComposite.Lbl.Undefined=없음(&N)

FormatSpecifierComposite.Lbl.Numerator=분자 값(1-100)(&V):

FormatSpecifierComposite.Lbl.Standard=표준(&S)

FormatSpecifierComposite.Lbl.String=문자열

FormatSpecifierComposite.Lbl.Type=형식(&Y):

FormatSpecifierComposite.Lbl.None=<없음>

FormatSpecifierComposite.Lbl.Details=상세 정보(&E):

FormatSpecifierComposite.Lbl.Delimiter=구분 기호(&E):

FormatSpecifierComposite.Lbl.Pattern=패턴(&P):

FormatSpecifierComposite.Lbl.Prefix=접두사(&P):

FormatSpecifierComposite.Lbl.Preview=미리 보기:

FormatSpecifierComposite.Lbl.Approximate=근사값(&R):

FormatSpecifierComposite.Lbl.Suffix=접미사(&X):

FormatSpecifierComposite.Lbl.Number=번호

FormatSpecifierPreview.Lbl.NoFormat=지정된 서식 없음

FormatSpecifierComposite.Lbl.Multiplier=승수(&M):

FormatSpecifierComposite.Lbl.FractionDigits=부분 숫자(&G):

FormatSpecifierComposite.Tooltip.InputAPositiveInteger=고정된 분자로 양의 정수를 입력합니다.

FormatSpecifierComposite.Tooltip.FractionDigits=고급 속성: 근사값의 정밀도를 결정하는 데 사용합니다.

FormatSpecifierComposite.Lbl.MaxRecursionTimes=최대 분모 숫자(&O)(1-8):

FormatSpecifierComposite.Lbl.Fraction=분수(&F)

FormatSpecifierDialog.Title.EditFormat=형식 편집

FormatSpecifierComposite.Lbl.Advanced=고급(&A)

FormatSpecifierComposite.Lbl.DatePattern=패턴(&P):

FormatSpecifierComposite.Lbl.ExampleFormats=예 형식(&E):

FormatSpecifierComposite.Lbl.NumberPattern=패턴(&P):

FormatSpecifierComposite.StringFormat.LowerCase=소문자

FormatSpecifierComposite.StringFormat.PhoneNumber=전화 번호

FormatSpecifierComposite.StringFormat.SocialSNumber=주민 등록 번호

FormatSpecifierComposite.StringFormat.UpperCase=대문자

FormatSpecifierComposite.StringFormat.WhiteSpace=공백 유지

FormatSpecifierComposite.StringFormat.ZipCode=우편 번호 + 4

FormatSpecifierPreview.Lbl.NotAvailable=사용할 수 없음

GridAttributesComposite.Lbl.Ticks=틱

GridAttributesComposite.Lbl.Style=스타일:

GradientEditorDialog.Lbl.EndColor=끝 색:

GradientEditorDialog.Lbl.Rotation=회전

FontDefinitionDialog.Lbl.Rotation=회전:

FontDefinitionDialog.Tooltip.Accept=수락

FontDefinitionDialog.Tooltip.Bold=굵게

FontDefinitionDialog.Tooltip.Italic=기울임꼴

FontDefinitionDialog.Tooltip.AlignTopCenter=맞춤 - 가운데 위

FontDefinitionDialog.Tooltip.AlignCenter=맞춤 - 가운데

FontDefinitionDialog.Tooltip.Underline=밑줄

FontDefinitionDialog.Tooltip.AlignTopRight=맞춤 - 오른쪽 위

FontDefinitionDialog.Tooltip.Strikethrough=취소선

FontDefinitionDialog.Title.FontDescriptor=글꼴 편집

FontDefinitionDialog.Lbl.Font=글꼴(&F):

FontDefinitionDialog.Lbl.Size=크기(&Z):

FontDefinitionDialog.Lbl.Color=색(&C):

FontDefinitionDialog.Lbl.Style=스타일:

FontDefinitionDialog.Lbl.Format=형식:

FontDefinitionDialog.Lbl.Wrap=랩

FontDefinitionDialog.Lbl.Preview=미리 보기:

FontDefinitionDialog.Lbl.Alignment=맞춤:

FontDefinitionDialog.Label.Degree=각도(&D):

FontDefinitionDialog.Tooltip.AlignTopLeft=맞춤 - 왼쪽 위

FontDefinitionDialog.Tooltip.AlignCenterLeft=맞춤 - 왼쪽 가운데

FontDefinitionDialog.Tooltip.AlignCenterRight=맞춤 - 오른쪽 가운데

FontDefinitionDialog.Tooltip.AlignBottomLeft=맞춤 - 왼쪽 아래

FontDefinitionDialog.Tooltip.AlignBottomCenter=맞춤 - 가운데 아래

FontDefinitionDialog.Tooltip.AlignBottomRight=맞춤 - 오른쪽 아래

FontDefinitionDialog.Lbl.Strikethrough=취소선(&S)

FontDefinitionComposite.Tooltip.FontDialog=글꼴 편집기 호출

TriggerEditorDialog.Title.TriggerEditor=상호작용 편집기 - {0}

TriggerDataComposite.Lbl.ActionDetails=작업 상세 정보

TriggerDataComposite.Lbl.SeriesDefinition=계열 정의:

TriggerDataComposite.Label.CallbackDescription=CallBack 작업은 SWT 또는 Swing 렌더링에서 API 용도이며, Java 이벤트 처리기를 연결시킵니다.

TriggerDataComposite.Label.HighlightDescription=적용 가능할 때 해당 데이터 요소를 강조합니다.

TriggerDataComposite.Label.VisiblityDescription=적용 가능할 때 해당 데이터 요소의 표시 유형을 전환합니다.

TriggerDataComposite.Label.Description=유형, URI, 내부 책갈피 및 드릴스루에 따라 URL을 편집합니다.

TriggerDataComposite.Label.DPVisibilityDescription=적용 가능할 때 해당 데이터 요소 레이블의 표시 유형을 전환합니다.

TriggerDataComposite.Label.OptionalURLParameters=각각의 데이터 요소에 대해 다음 값을 표시하는 옵션 URL 매개 변수의 이름을 지정합니다.

TriggerDataComposite.Label.TooltipUsingDataLabelOfSeries=도구 설명 텍스트를 설정하지 않은 경우 해당 계열의 데이터 레이블을 사용합니다.

TriggerDataComposite.Tooltip.InvokeURLBuilder=URL 빌더 호출

TriggerDataComposite.Tooltip.Advanced=옵션 URL 매개 변수 표시

TriggerDataComposite.Label.None=없음

TriggerDataComposite.Tooltip.ParameterCategory=범주에 대한 매개 변수 이름: …&&&name=<범주>

TriggerDataComposite.Tooltip.ParameterValue=값에 대한 매개 변수 이름: …&&&name=<값>

TriggerDataComposite.Tooltip.ParameterSeries=계열에 대한 매개 변수 이름: …&&&name=<계열>

TriggerDataComposite.Lbl.TooltipDelay=도구 설명 지연(ms)(&D):

TriggerDataComposite.Lbl.ParameterNames=옵션 데이터 요소 URL 매개 변수

TriggerDataComposite.Lbl.CategorySeries=범주 계열(&C):

TriggerDataComposite.Lbl.Cursor=커서(&S):

TriggerDataComposite.TemporaryName.Hyperlink=하이퍼링크

TriggerDataComposite.Text.EditBaseURL=기본 URL 편집(&U)...

TriggerDataComposite.Text.Advanced=고급(&A)>>

TriggerDataComposite.Text.OpenAdvanced=고급(&A)<<

TriggerDataComposite.Lbl.ValueSeries=값 계열(&V):

TriggerDataComposite.Lbl.ValueSeriesName=값 계열 이름(&S):

TriggerDataComposite.Tooltip.InputScript=\ 렌더링 환경에서 실행할 스크립트(일반적으로 JavaScript) 를 입력합니다.

TriggerEditorComposite.Lbl.Remove=제거(&R)

TriggerEditorComposite.Lbl.Add=추가(&A)

TriggerDataComposite.Lbl.Event=이벤트(&V):

TriggerDataComposite.Lbl.None.accessibility=<없음>

TriggerDataComposite.Lbl.None.MouseClick=<없음>

TriggerDataComposite.Lbl.None.MouseHover=<없음>

TriggerDataComposite.Lbl.None.onblur=<없음>

TriggerDataComposite.Lbl.None.onclick=<없음>

TriggerDataComposite.Lbl.None.ondblclick=<없음>

TriggerDataComposite.Lbl.None.onfocus=<없음>

TriggerDataComposite.Lbl.None.onkeydown=<없음>

TriggerDataComposite.Lbl.None.onkeypress=<없음>

TriggerDataComposite.Lbl.None.onkeyup=<없음>

TriggerDataComposite.Lbl.None.onload=<없음>

TriggerDataComposite.Lbl.None.onmousedown=<없음>

TriggerDataComposite.Lbl.None.onmousemove=<없음>

TriggerDataComposite.Lbl.None.onmouseout=<없음>

TriggerDataComposite.Lbl.None.onmouseover=<없음>

TriggerDataComposite.Lbl.None.onmouseup=<없음>

TriggerDataComposite.Lbl.Action=작업:(&C)

TriggerDataComposite.Lbl.Script=스크립트(&P):

TriggerDataComposite.Lbl.Target=대상:

TriggerEditorComposite.Lbl.Update=<< 업데이트(&U)

TriggerDataComposite.Lbl.TooltipText=도구 설명 텍스트(&X):

TriggerDataComposite.Btn.Format=서식(&F)

TriggerDataComposite.Lbl.BaseURL=기본 URL 편집:

TriggerDataComposite.Lbl.Image=이미지(&I)

GradientEditorDialog.Lbl.GradientEditor=그라데이션 편집기

GradientEditorDialog.Lbl.StartColor=시작 색:

GradientEditorDialog.Lbl.Preview=미리 보기

PaletteEditorComposite.Label.EditColor=색 편집

PaletteEditorComposite.Lbl.Add=추가(&A)

PaletteEditorComposite.Lbl.Remove=제거(&R)

PaletteEditorComposite.Lbl.Up=위로

PaletteEditorComposite.Lbl.Down=아래로

PatternImageEditorDialog.Button.Cancel=취소(&C)

PatternImageEditorDialog.Button.OK=확인(&O)

PatternImageEditorDialog.Group.Color=색:

PatternImageEditorDialog.Group.Pattern=패턴:

PatternImageEditorDialog.Label.Background=배경(&B):

PatternImageEditorDialog.Label.Foreground=전경(&F):

PatternImageEditorDialog.Title.PatternFillEditor=패턴 이미지 편집기

LabelAttributesComposite.Lbl.Label=레이블

LabelAttributesComposite.Lbl.Font=글꼴(&O):

LabelAttributesComposite.Lbl.Shadow=그림자(&S):

LabelBlockAttributeSheetImpl.Title.SheetTitle=레이아웃 > 레이블 블록 - 레이블 블록 영역 형식 지정

BlockAttributeComposite.Lbl.IsBlockVisible=블록이 표시됩니다.

BlockAttributeComposite.Lbl.Anchor=앵커(&A):

BlockAttributeComposite.Lbl.Stretch=맞춤(&S):

BlockAttributeComposite.Lbl.Insets=음각

BlockPropertiesSheet.Label.Outline=윤곽선

BlockAttributeComposite.Lbl.Outline=윤곽선

BlockAttributeComposite.Lbl.HorizontalSpacing=가로 간격(&H):

BlockAttributeComposite.Lbl.VerticalSpacing=세로 간격(&V):

BlockAttributeComposite.Lbl.Orientation=방향(&O):

BlockAttributeComposite.Lbl.Direction=방향(&D):

BlockAttributeComposite.Lbl.Position=위치(&P):

BlockAttributeComposite.Lbl.ItemType=항목 형식:

BlockAttributeComposite.Title.PlotBlock=플롯 블록

BlockAttributeComposite.Title.LegendBlock=범례 블록

BlockAttributeComposite.Title.TitleBlock=제목 블록

BlockAttributeComposite.Title.LabelBlock=레이블 블록

BlockPropertiesSheet.Label.Interactivity=대화형 작업

LayoutSheetImpl.Lbl.ChartProperties=차트 블록 속성

LayoutSheetImpl.Lbl.Background=배경:

LayoutSheetImpl.Lbl.Insets=음각

LayoutSheetImpl.Lbl.Outline=윤곽선

LayoutSheetImpl.Title.SheetTitle=레이아웃 - 차트 블록 형식 지정

AttributeSheetImpl.Lbl.ChartProperties=차트 속성

AttributeSheetImpl.Lbl.Type=형식:

AttributeSheetImpl.Lbl.Subtype=하위 형식:

AttributeSheetImpl.Lbl.Units=단위(&U):

AttributeSheetImpl.Lbl.ColumnCount=눈금 열 개수(&C):

AttributeSheetImpl.Lbl.ChartBackground=차트 배경:

AttributeSheetImpl.Lbl.PropertyEditorDialog=확장 속성

AttributeSheetImpl.Lbl.ChartWall=차트 옆면(&W):

AttributeSheetImpl.Lbl.ChartFloor=차트 밑면(&F):

AttributeSheetImpl.Lbl.UnitSpacing=단위 간격(0-100)(&P):

AttributeSheetImpl.Title.SheetTitle=특성 - 차트 특성 사용자 지정

PropertyEditorDialog.Title.PropertyEditorDialog=확장 속성 편집기

PropertyEditorDialog.Lbl.Key=키

PropertyEditorDialog.Lbl.Value=값

PropertyEditorDialog.Lbl.Add=추가(&A)

PropertyEditorDialog.Lbl.Remove=제거(&R)

HeadStyleAttributeComposite.Lbl.HeadStyle=헤드 스타일:

HyperlinkEditorDialog.BaseURL.Message=기본 URL을 설정하십시오.

HyperlinkEditorDialog.ErrorMessage.ExistingText=이름이 이미 있습니다. 다른 이름으로 수정하십시오.

HyperlinkEditorDialog.ErrorMessage.NullText=이름은 비워둘 수 없습니다\!

HyperlinkEditorDialog.HyperlinkName.Title.Warning=경고

HyperlinkEditorDialog.Text.MenuLabel=이름(&N):

HyperlinkEditorDialog.Title.HyperlinkEditor=하이퍼링크 편집기

TaskSelectType.TaskExp=차트 형식 선택

TaskSelectType.Label.Preview=차트 미리 보기

TaskSelectType.Label.Oritention=방향:

TaskSelectType.Label.FlipAxis=축 반전(&X)

TaskSelectType.Selection.None=없음

TaskSelectType.Label.MultipleYAxis=다중 Y 축(&M):

TaskSelectType.Label.AddSecondaryAxis=보조 축 추가

TaskSelectType.Selection.SecondaryAxis=보조 축

TaskSelectType.Label.SeriesType=계열 형식(&S):

TaskSelectType.Task.Description=차트 형식과 출력 형식을 선택합니다.

TaskSelectType.Label.OutputFormat=출력 형식(&O):

TaskSelectType.Selection.MoreAxes=추가 축

TaskSelectType.Label.SelectChartType=차트 형식 선택

TaskSelectType.Label.SelectSubtype=하위 형식 선택

TaskSelectType.Exception.CannotSupportAxes=ChartWithoutAxes에서는 축을 지원할 수 없습니다\!

TaskSelectType.Exception.NotSupportedForMultipleAxes=\ 다중 축에는 지원되지 않습니다\!

TaskSelectType.Label.ChartTypes=차트 형식

TaskSelectType.Label.Dimension=차원(&D):

TaskSelectType.Label.ChartSubtypes=차트 하위 형식

TaskSelectData.TaskExp=데이터 선택

TaskSelectData.Label.ToBindADataColumn=오른쪽 단추 메뉴를 사용하거나 계열 필드로 열을 끌어 오십시오.

TaskSelectData.Label.ChartPreview=차트 미리 보기

TaskSelectData.Label.SelectDataSet=데이터 선택

TaskSelectData.Label.UseReportData=컨테이너에서 데이터 상속(&I)

TaskSelectData.Label.UseReportItem=보고서 항목 사용(&R)

TaskSelectData.Label.UseDataSet=데이터 집합 사용(&D)

TaskSelectData.Label.CreateNew=새로 생성(&C)...

TaskSelectData.Label.DataPreview=데이터 미리보기

TaskSelectData.Label.DataBinding=데이터 바인딩(&A)...

TaskSelectData.Warning.TypeCheck={0}의 데이터 유형이 {1}와(과) 호환되지 않습니다. 식을 고치십시오.

TaskSelectData.Label.Filters=필터(&T)...

TaskSelectData.Label.Parameters=매개 변수(&P)...

TaskSelectData.Task.Description=차트에 표시하고 계열에 바인딩할 데이터를 선택합니다.

TaskSelectData.Exception.UnableToSwitchToDataset=데이터 집합으로 전환할 수 없음

TaskSelectData.Label.InsertAggregation=집계 삽입

TaskSelectData.Label.DataExpressionBuilder=데이터 식 빌더

TaskSelectData.Label.Component=\ 구성 요소

TaskSelectData.Label.Overlay=이중

TaskSelectData.Label.Series=계열

TaskSelectData.Label.UseAsCategoryXAxis=범주 (X) 축으로 사용

TaskSelectData.Label.UseAsCategorySeries=범주 계열로 사용

TaskSelectData.Label.PlotAsValueYSeries=값 (Y) 계열로 플롯

TaskSelectData.Tooltip.CreateNewDataset=새 데이터 집합 만들기

TaskSelectData.Label.PlotAsGaugeValue=미터 값으로 플롯

TaskSelectData.Label.PlotAsValueSeries=값 계열로 플롯

TaskSelectData.Label.UseToGroupYSeries=Y 계열을 그룹화하는 데 사용

TaskSelectData.Label.EnableLivePreview=실시간 차트 미리 보기 사용

TaskSelectData.Label.UseToGroupValueSeries=값 계열을 그룹화하는 데 사용

TaskFormatChart.TaskExp=차트 형식 지정

TaskFormatChart.Label.Preview=차트 미리 보기

TaskFormatChart.LivePreviewTask.BindData=차트 미리 보기를 위한 데이트 검색 및 바인딩

TaskFormatChart.Task.Description=텍스트, 그림자, 배경, 테두리에 대한 전체적인 형식을 지정하고 계열 속성, 테마, 레이아웃을 정의하여 차트의 상세한 부분까지 조정합니다.

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=잘못된 열 인덱스 {0}이(가) 지정되었거나 열이 아직 정의되지 않았습니다\!

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=잘못된 열 인덱스가 지정되었습니다\!

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=잘못된 열 인덱스 {0}이(가) 지정되었습니다\! 테이블에 {1}개의 열만 있습니다\!

CustomPreviewTable.Exception.RowIndexGreaterThan0=행 인덱스는 0보다 크거나 같아야 합니다\!

AbstractSelectDataCustomizeUI.Label.SeriesGrouping=계열 그룹화

AbstractSelectDataCustomizeUI.Label.YAxis=Y축

AbstractSelectDataCustomizeUI.Label.Series=계열

AbstractScaleSheet.Label.ShowValuesOutside=축 범위 이외의 값 표시(&O)

MultipleHyperlinksComposite.Btn.Add=추가(&A)

MultipleHyperlinksComposite.Btn.Delete=삭제(&D)

MultipleHyperlinksComposite.Btn.Down=아래로(&N)

MultipleHyperlinksComposite.Btn.Edit=편집(&E)

MultipleHyperlinksComposite.Btn.Properties=속성(&P)

MultipleHyperlinksComposite.Btn.Up=위로(&U)

MultipleHyperlinksComposite.Group.Hyperlinks=하이퍼링크

MultipleHyperlinksComposite.Label.Tooltip=도구 설명(&T):

MultipleSeriesComponent.Label.OptionalYSeriesGrouping=옵션 Y 계열 그룹화(&O):

MultipleSeriesComponent.Label.OptionalOverlayGrouping=옵션 이중 그룹화(&O):

MultipleSeriesComponent.Label.OptionalGrouping=옵션 그룹화(&O):

MultipleSeriesComponent.Label.GroupSorting=그룹 정렬(&S):

SelectDataChartWithAxisUI.Label.ValueYSeries=값 (Y) 계열:

MultipleSeriesComponent.Label.Series=계열

SelectDataChartWithoutAxisUI.Label.Series=계열

DataDefinitionSelector.Label.Series=계열

DataDefinitionSelector.Text.NewSeries=<새 계열...>

DataDefinitionSelector.Text.NewAxis=<새 축...>

DataDefinitionSelector.Tooltip.RemoveSeries=선택한 계열 제거

DataDefinitionSelector.Tooltip.RemoveAxis=선택한 축 제거

DataDefinitionSelector.Label.YAxis=Y축

DataDefinitionSelector.Label.Axis=축

DataDefinitionSelector.Label.DeleteAxis=축 삭제

DataDefinitionSelector.Label.DeleteSeries=계열 삭제

DialBottomAreaComponent.Label.Dial=다이얼

DialBottomAreaComponent.Label.GaugeValueDefinition=미터 값 정의:

PieBottomAreaComponent.Label.TheExplosionCondition=쪼개짐 조건은 조건에 따라 조각별로 쪼개질 수 있도록 합니다.

PieBottomAreaComponent.Label.TheAmplitudeOfTheExplosion=쪼개짐의 크기는 조각이 얼마나 멀리 쪼개지는지 여부를 지정합니다.

AxisGridLinesSheet.MajorLabel.LineIsVisible=표시(&V)

AxisGridLinesSheet.MajorLabel.TickIsVisible=표시(&I)

AxisGridLinesSheet.MinorLabel.LineIsVisible=표시(&S)

AxisGridLinesSheet.MinorLabel.TickIsVisible=표시(&L)

AxisLabelSheet.Label.Ellipsis=생략 부호(&I):

AxisLabelSheet.Label.Ellipsis.Tooltip=생략 부호 앞에 표시할 최소 문자 수를 설정합니다.

AxisSheetImpl.Label.Aligned=맞춤

AxisSheetImpl.Label.Axis=축

AxisSheetImpl.Label.AxisPercent=축 백분율

AxisSheetImpl.Label.Visible=표시

AxisSheetImpl.Label.ValueY=값(Y)

AxisYSheetImpl.Label.Labels=레이블(&A):

AxisSheetImpl.Label.Type=형식

AxisSheetImpl.Label.Color=색

AxisYSheetImpl.Label.Title=제목(&E):

AxisYSheetImpl.Label.Scale=축 배율

AxisYSheetImpl.Label.Scale&=배율(&S)

AxisSheetImpl.Label.CategoryX=범주(X)

AxisSheetImpl.Label.AncillaryZ=보조(Z)

AxisSheetImpl.Label.SideBySide=세로 정렬

AxisXSheetImpl.Label.Visible=표시

AxisYSheetImpl.Label.LabelFormat=축 레이블

AxisYSheetImpl.Label.LabelFormat&=레이블(&L)

AxisYSheetImpl.Label.TitleFormat=축 제목

AxisYSheetImpl.Label.TitleFormat&=제목(&T)

AxisYSheetImpl.Label.Gridlines=축 눈금선

AxisYSheetImpl.Label.Gridlines&=눈금선(&D)

AbstractAxisSubtask.Button.Fixed=고정

AbstractAxisSubtask.Lbl.IsCategoryAxis=범주 축(&X)

AbstractAxisSubtask.Label.Visible2=표시(&I)

AbstractScaleSheet.Label.StepNumber=단계 수(&N):

AxisYSheetImpl.Label.Markers=축 마커

AxisYSheetImpl.Label.Markers&=마커(&M)

AxisZSheetImpl.Label.Visible=표시(&V)

AxisXSheetImpl.Label.AxisData=축 데이터

AbstractAxisSubtask.Label.Stagger=교차(&G)

AbstractAxisSubtask.Label.Interactivity=축 대화형 작업

AbstractAxisSubtask.Label.LabelSpan=레이블 범위(&N):

AbstractAxisSubtask.Label.Points=(포인트)

AbstractAxisSubtask.Label.ReverseCategory=역방향 범주(&C)

AxisTextSheet.Label.Interval=간격(&E):

AxisMarkersSheet.Title.MarkerLine=표지 선

AxisMarkersSheet.Label.Label=레이블(&L):

AxisMarkersSheet.Title.MarkerRange=표지 범위

ChartLegendSheetImpl.Label.Outline=윤곽선:

ChartLegendSheetImpl.Label.ShowValue=값 표시(&H)

ChartPlotSheetImpl.Label.Background=배경(&K):

ChartPlotSheetImpl.Label.Background2=배경(&G):

ChartPlotSheetImpl.Label.ClientArea=클라이언트 영역

ChartTitleSheetImpl.Text.Auto=자동(&A)

ChartTitleSheetImpl.Text.TitleLayout=제목 레이아웃

ChartTitleSheetImpl.Text.Layout&=레이아웃(&L)

ChartTitleSheetImpl.Text.TitleText=제목 텍스트

ChartTitleSheetImpl.Text.TitleText&=텍스트(&T)

ChartSheetImpl.Title.ChartTitle=차트 제목

ChartSheetImpl.Title.ChartArea=차트 영역

ChartSheetImpl.Label.Visible=표시(&V)

ChartSheetImpl.Label.ColorBy=색상 기준(&C):

ChartSheetImpl.Label.Coverage=적용 범위(&A):

ChartSheetImpl.Label.Background=배경(&K):

ChartLegendSheetImpl.Label.Entries=항목(&E)

ChartLegendSheetImpl.Label.LegendTitle&=제목(&T)

ChartLegendSheetImpl.Title.LegendLayout=범례 레이아웃

ChartLegendSheetImpl.Tooltip.ShowDataPointValue=각 범례 항목에 대해 범례 아래 첫 번째 행의 데이터 요소 값을 표시합니다.

ChartLegendSheetImpl.Title.LegendEntries=범례 항목

ChartLegendSheetImpl.Title.LegendTitle=범례 제목

ChartLegendSheetImpl.Label.Layout=레이아웃(&A)

ChartLegendSheetImpl.Label.Legend=범례

ChartLegendSheetImpl.Label.Title=제목(&L):

ChartLegendSheetImpl.Label.Value=값:

ChartLegendSheetImpl.Title.Tooltip=범례 도구

ChartLegendSheetImpl.Label.Interactivity=범례 대화형 작업

ChartPlotSheetImpl.Label.AreaIncludingAxes=축 포함 영역

ChartSheetImpl.Label.EnableInPreview=미리 보기(&P)

ChartSheetImpl.Label.Font=글꼴(&T):

ChartSheetImpl.Label.ResetValue=값 원래대로(&V)

ChartPlotSheetImpl.Label.AreaWithinAxes=축 내 영역

ChartSheetImpl.Label.Style=스타일(&S):

ChartSheetImpl.Label.None=없음

ChartSheetImpl.Text.Outline=윤곽선

ChartSheetImpl.Text.Outline&=윤곽선(&O)

ChartSheetImpl.Text.GeneralProperties=일반 속성

ChartSheetImpl.Text.GeneralProperties&=일반 속성(&G)

ChartSheetImpl.Text.TitleInteractivity=제목 대화형 작업(&I)

ChartSheetImpl.Text.CustomProperties=사용자 지정 속성

ChartSheetImpl.Text.CustomProperties&=사용자 지정 속성(&C)

ChartSheetImpl.Text.ChartAreaInteractivity=차트 영역 대화형 작업(&A)

ChartSheetImpl.Label.Interactivity=차트 영역 대화형 작업

ChartSheetImpl.Label.InteractivityEnable=차트 대화형 작업 사용(&E)

ChartSheetImpl.Label.Text=텍스트(&X):

ChartLegendSheetImpl.Label.LegendBehaviorType=동작(&O):

ChartLivePreviewThread_Text.PleaseWait=. 잠시 기다려 주십시오.

ChartLivePreviewThread.ErrorMessage.NoDataEngine=데이터를 처리할 데이터 엔진이 없습니다. 자세한 내용은 이전 예외를 참조하십시오.

SeriesSheetImpl.Label.Type=형식

SeriesSheetImpl.Label.ZOrder=Z 순서

LegendTextSheet.Label.Ellipsis=생략 부호(&E):

LegendTextSheet.Label.Font=글꼴(&F):

LegendTextSheet.Label.Separator=구분 기호

LegendTextSheet.Tooltip.Ellipsis=생략 부호 앞에 표시할 최소 문자 수를 설정합니다.

MoreOptionsChartLegendSheet.Label.TextArea=텍스트 영역

MoreOptionsChartLegendSheet.Label.Outline=윤곽선

MoreOptionsChartLegendSheet.Label.LegendArea=범례 영역

MoreOptionsChartPlotSheet.Label.AreaIncludingAxes=축 포함 영역

MoreOptionsChartPlotSheet.Label.Interactivity=대화형 작업

MoreOptionsChartPlotSheet.Label.AreaWithinAxes=축 내 영역

MoreOptionsChartPlotSheet.Label.Anchor=앵커(&A):

MoreOptionsChartPlotSheet.Label.Outline=윤곽선

MoreOptionsChartPlotSheet.Label.Stretch=맞춤(&S):

TitlePropertiesSheet.Label.Title=제목(&T)

TitlePropertiesSheet.Label.Visible=표시

TitlePropertiesSheet.Label.Anchor=앵커(&A):

TitlePropertiesSheet.Label.Stretch=맞춤(&S):

TitlePropertiesSheet.Label.Outline=윤곽선

TitlePropertiesSheet.Label.Text=텍스트

BaseDataDefinitionComponent.Text.SpecifyDataDefinition=데이터 정의 지정

BaseDataDefinitionComponent.Label.EditGroupSorting=그룹 편집 및 정렬

BaseDataDefinitionComponent.Tooltip.InputValueExpression=입력 값 식

BaseDataDefinitionComponent.Text.EditFormat=형식 편집

BaseDataDefinitionComponent.WarningMessage.ExpressionsForbidden=1차원 식을 선택하면 범주 계열과 Y 옵션을 동시에 설정할 수 없습니다.

BaseGroupSortingDialog.Label.SortOn=정렬 방법(&O):

MarkerEditorComposite.Button.Outline=윤곽선(&O)

MarkerEditorComposite.Label.MarkerType=형식

MarkerIconDialog.Button.EmbeddedImage=포함된 이미지(&M)

MarkerIconDialog.Title.MarkerIconSelector=표지 아이콘 선택기(Marker Icon Selector)

MarkerIconDialog.Label.Description.EmbeddedImage=마커 아이콘으로 포함된 이미지를 선택합니다.

MarkerIconDialog.Lbl.SelectIconFrom=다음에서 아이콘 선택:

MarkerIconDialog.Lbl.URL=URL(&U)

MarkerIconDialog.Lbl.Local=로컬(&L)

MarkerIconDialog.Lbl.EnterURL=URL 입력(&E):

MarkerIconDialog.Lbl.Browse=찾아보기(&B)

MarkerIconDialog.Lbl.Preview=미리 보기(&P)

MarkerIconDialog.Lbl.Add=추가

MarkerIconDialog.Chooser.Title=표지 아이콘 선택기(Marker Icon Chooser)

MarkerIconDialog.Lbl.Remove=제거

MarkerIconDialog.Lbl.Description=로컬 이미지 파일에서 표지 아이콘을 가져옵니다.

MarkerIconDialog.Exception.ImageNotAvailable=이미지는 현재 사용할 수 없습니다.

MarkerIconDialog.Exception.InvalidURL=잘못된 URL입니다. 올바른 URL을 입력하십시오.

MarkerIconDialog.ImageNotAvailableWarning=경고

MarkerIconDialog.ImageNotAvailableWarningMessage=그래도 사용하시겠습니까?

exception.data.DataBindingsAreNull=하나 이상의 데이터 바인딩이 널(null)입니다\!

DialLabelSheet.Label.Format=형식:

ImageDialog.AddImage=이미지 추가(&A)...

ImageDialog.FileExist=파일 이름이 이미 있습니다. 이름을 변경하고 다시 로드하십시오.

ImageDialog.ImportFail=가져오기 실패

ImageDialog.label.SelectImageType=이미지 형식 선택:

ImageDialog.label.URLImage=URL 이미지(&U)

ImageDialog.label.EmbeddedImage=내장된 이미지(&M)

ImageDialog.label.EnterURL=이미지의 URI 입력(&E):

ImageDialog.label.EnterEmbed=포함시킬 이미지의 경로 입력(&E):

ImageDialog.label.Browse=찾아보기(&B)...

ImageDialog.label.SelectFile=파일 선택

ImageDialog.label.Preview=미리 보기(&P)

ImageDialog.Label.ResourceImage=공유된 리소스의 이미지 파일(&I)

ImageDialog.label.SelectImage=이미지 선택

ImageDialog.uri.tooltip=(예: http://host/cursor.gif, uri/cursor.gif)

ImageDialog.label.LocalImage=로컬 이미지 파일(&O)

ImageDialog.label.EnterLocal=로컬 이미지의 경로 입력(&E):

TextEditorComposite.Tooltip.EnterDecimalOrFractionValue=정수, 십진수 또는 분수 값을 입력합니다.

PlotClientAreaSheet.Btn.Auto=자동(&U)

PlotClientAreaSheet.Btn.Auto2=자동(&O)

PlotClientAreaSheet.Label.HeightHint=높이 힌트(&N):

PlotClientAreaSheet.Label.WidthHint=너비 힌트(&T):


AxisMarkersSheet.MarkerLine.displayName=MarkerLine
AxisMarkersSheet.MarkerRange.displayName=MarkerRange
AxisMarkersSheet.Label.Interactivity=대화형 작업(&I)

AxisMarkersSheet.Label.IsVisible=표시(&S)

AbstractPopupSheet.Label.Close=닫기

AbstractPopupSheet.Label.Help=도움말

AggregateEditorComposite.Aggregate.Enabled=사용

AggregateEditorComposite.AggregateDisplayName.Default=기본값

AggregateEditorComposite.AggregateDisplayName.None=없음

AggregateEditorComposite.AggregateParameterDefinition.Title=집계 매개 변수 정의

AggregateEditorComposite.Button.Cancel=취소

AggregateEditorComposite.Button.OK=확인

AggregateEditorComposite.Tooltip.SetAggregateFunction=집계 함수 설정

LocalizedNumberEditorComposite.error.Title=숫자 형식 오류

LocalizedNumberEditorComposite.error.Message=잘못된 숫자 값: "{0}"

SeriesRegionSheet.message.dialRegion=DialRegion -

GroupSortingDialog.Composite.Group.Sorting=정렬

GroupSortingDialog.Composite.Label.SortLocale=로케일(&L):

GroupSortingDialog.Composite.Label.SortStrength=수준(&H):

GroupSortingDialog.Label.GroupAndSorting=그룹 및 정렬

GroupSortingDialog.Sort.Locale.Auto=자동

GroupSortingDialog.Sort.Strength.ASCII=ASCII
GroupSortingDialog.Sort.Strength.IDENTICAL=동일

GroupSortingDialog.Sort.Strength.PRIMARY=주

GroupSortingDialog.Sort.Strength.QUATENARY=4차

GroupSortingDialog.Sort.Strength.SECONDARY=보조

GroupSortingDialog.Sort.Strength.TERTIARY=3차

GroupSortingDialog.Sort.SortOn.Warning.Title=SortOn 경고

GroupSortingDialog.Sort.SortOn.Warning.Message=SortOn 식은 비워둘 수 없습니다.

GanttSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 GanttSeriesAttributeComposite에 대한 잘못된 인수입니다.

GanttChart.Txt.DefaultGanttChartTitle=Gantt 차트 제목

GanttChart.Txt.DisplayName=간트

GanttChart.Txt.Description=표준 간트 차트에는 시작 표지와 끝 표지를 잇는 연결선이 있습니다.

GanttChart.Txt.HelpText=Gantt 차트는 작업 또는 활동의 시간이 초과된 경우 해당 시간을 표시합니다.

GanttChart.SubType.Standard=표준 Gantt 차트

GanttSeriesAttributeComposite.Lbl.Marker=표지

GanttSeriesAttributeComposite.Lbl.Start=시작:

GanttSeriesAttributeComposite.Lbl.End=끝:

GanttSeriesAttributeComposite.Lbl.Bars=막대

GanttSeriesAttributeComposite.Lbl.Outline=윤곽선

GanttSeriesAttributeComposite.Lbl.OutlineFill=윤곽선 채우기:

GanttSeriesAttributeComposite.Lbl.BarPalette=막대 색으로 계열 색상표 사용(&P)

DecorationSheet.Label.DecorationLabels=작업 레이블

BubbleChart.Txt.DefaultBubbleChartTitle=거품형 차트 제목

BubbleChart.Txt.Description=거품형 차트에는 범주와 값 데이터를 좌표로 사용하여 플롯 위에 정렬된 값이 표시됩니다. \n각 데이터 값은 표지로 표시됩니다.

BubbleChart.Txt.HelpText=거품형 차트는 범주가 아닌 축에 연결된 임의로 배치된 데이터 값을 표시합니다. 각 데이터 요소는 X 및 Y 축 배율에 연결되어 있습니다.

BubbleChart.Txt.DisplayName=거품형

BubbleChart.SubType.Standard=표준 거품형 차트

BubbleSeriesAttributeComposite.Lbl.ShadowColor=그림자(&H):

BubbleSeriesAttributeComposite.Lbl.Marker=표지

BubbleSeriesAttributeComposite.Lbl.IsVisible=표시

BubbleSeriesAttributeComposite.Lbl.Type=형식:

BubbleSeriesAttributeComposite.Lbl.Size=크기:

BubbleSeriesAttributeComposite.Lbl.Line=선

BubbleSeriesAttributeComposite.Lbl.AccLine=가속 선

BubbleSeriesAttributeComposite.Lbl.LinePalette=선 색으로 계열 색상표 사용(&P)

BubbleSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 BubbleSeriesAttributeComposite에 대한 잘못된 인수입니다.

BubbleSeriesAttributeComposite.Lbl.ShowLinesAsCurves=선을 곡선으로 표시(&V)

BubbleSeriesAttributeComposite.Lbl.Orientation=방향(&O)

DifferenceChart.Txt.DefaultDifferenceChartTitle=차이 차트 제목

DifferenceChart.Txt.Description=차이 차트는 두 개의 채우기를 사용하여 양수 및 음수 영역을 표시합니다.

DifferenceChart.Txt.HelpText=차이 차트는 일반적으로 두 데이터 필드 간의 차이를 표시하는 데 사용됩니다.

DifferenceChart.Txt.DisplayName=차이

DifferenceChart.SubType.Standard=표준 차이 차트

DifferenceSeriesAttributeComposite.Exception.IllegalArgument=형식 {0}의 계열은 DifferenceSeriesAttributeComposite에 대한 잘못된 인수입니다.

DifferenceSeriesAttributeComposite.Lbl.Line=줄

DifferenceSeriesAttributeComposite.Lbl.PositiveLine=양수

DifferenceSeriesAttributeComposite.Lbl.NegativeLine=음수

DifferenceSeriesAttributeComposite.Lbl.ShowLinesAsCurves=선을 곡선으로 표시(&C)

DifferenceSeriesAttributeComposite.Lbl.LinePalette=선 색으로 계열 색상표 사용(&U)

PositiveNegativeColorDialog.Lbl.PositiveNegativeColorEditor=양수/음수 색상 편집기

PositiveNegativeColorDialog.Lbl.PositiveColor=양수 색상

PositiveNegativeColorDialog.Lbl.NegativeColor=음수 색상

PositiveNegativeColorDialog.Lbl.Preview=미리 보기

########### Field Assist Preferences ###########################
ssPreferencesContentAssistKey= 내용 지원 키:

ssPreferencesContentAssistKeyCtlSpace= Ctrl+스페이스바(&S)

ssPreferencesContentAssistKeyAsterisk= *(별표)(&K)

ssPreferencesContentAssistKeyAnyKey= 영숫자 키(자동 활성화 지연 시)(&H)

ssPreferencesContentAssistKeyCustom= 사용자 지정(&C)

ssPreferencesContentAssistKeyPropagate= 팝업 활성화 시 제어하는 키 입력 제공(&P)

ssPreferencesContentAssistDelay= 내용 지원 자동 활성화 시 지연 시간(밀리초)(&E):

ssPreferencesDescription= 이 페이지에서는 차트 빌더 대화 상자에 사용되는 장식을 제어합니다.

ssPreferencesDecoratorVert= 세로 위치:

ssPreferencesDecoratorTop= 위쪽(&T)

ssPreferencesDecoratorCenter= 가운데(&C)

ssPreferencesDecoratorBottom= 아래쪽(&B)

ssPreferencesDecoratorHorz= 가로 위치:

ssPreferencesDecoratorLeft= 왼쪽(&L)

ssPreferencesDecoratorRight= 오른쪽(&R)

ssPreferencesDecoratorMargin= 여백 너비(&M):

ssPreferencesContentAssistDescription= 이 페이지에서는 내용 지원 동작을 제어합니다.

ssPreferencesContentAssistResult= 내용 제안을 선택한 경우:

ssPreferencesContentAssistResultReplace= 필드 내용 바꾸기(&R)

ssPreferencesContentAssistResultInsert= 필드 내용에 삽입(&I)

ssPreferencesContentAssistFilter= 팝업이 열려 있는 동안 입력하는 경우:

ssPreferencesContentAssistFilterCumulative= 누적 입력으로 팝업 내용 필터링(&L)

ssPreferencesContentAssistFilterCharacter= 입력된 마지막 문자에 따라 팝업 필터링(&T)

ssPreferencesContentAssistFilterNone= 필터링하지 않음(&N)

ssPreferencesShowRequiredFieldLabelIndicator= 필수 필드 식별(&I)

ssPreferencesAssistSymbol= 지원 기호 위치

ssDecoratorContentAssist= 이 필드에 사용 가능한 내용 지원을 보려면 {0}을(를) 누르십시오.

ssDecorationMenuItem=잘못된 문자 제거


### Multiple Hyperlinks ###
MenuStyleDialog.Column.Properties=속성

MenuStyleDialog.Column.Value=값

MenuStyleDialog.Style.Menu=메뉴

MenuStyleDialog.Style.MenuItem=메뉴 항목

MenuStyleDialog.Style.OnMouseOver=마우스를 위에 놓았을 때

MenuStyleDialog.Style.OnMouseOut=마우스를 다른 곳에 놓았을 때

MenuStylesDialog.Btn.Add=추가(&A)

MenuStylesDialog.Btn.Remove=제거(&R)

MenuStylesDialog.Label.Style=스타일(&S):

MenuStylesDialog.title=하이퍼링크 메뉴 속성

MenuStylesDialog.Title=하이퍼링크 메뉴 스타일

ItemLabel.Auto=자동
