###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=クエリビルダ版 JDBC データベース接続

newwizard.description=JDBC データベース接続プロファイルを作成します。

wizard.window.title=クエリビルダ版 JDBC データベース接続の新規作成

wizard.data.source.page.title=クエリビルダ版 JDBC データベース接続

profile.propertypage.name=JDBC ドライバと接続の詳細

wizard.data.set.window.title=SQL Select クエリの新規作成 [クエリビルダ]

wizard.data.set.page.title=SQL Select クエリ
