###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Databases Profile Data Source ODA Designer
newwizard.name=JDBC 데이터베이스 프로필 데이터 원본[프로토타입]
newwizard.description=JDBC 데이터베이스 연결 프로필 생성
wizard.window.title=새 JDBC 데이터베이스 프로필[프로토타입]
wizard.data.source.page.title=JDBC 데이터베이스 프로필[프로토타입]
profile.propertypage.name=JDBC 드라이버 및 연결 상세 정보
wizard.data.set.window.title=새 SQL Select 쿼리[쿼리 빌더 프로토타입]
wizard.data.set.page.title=SQL Select 쿼리
