###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Databases Profile Data Source ODA Designer
newwizard.name=JDBC Databases Profile Data Source [Prototype]
newwizard.description=Crear un perfil de conexión de base de datos JDBC
wizard.window.title=New JDBC Databases Profile [Prototype]
wizard.data.source.page.title=JDBC Databases Profile [Prototype]
profile.propertypage.name=Detalles de conexión y controlador de JDBC
wizard.data.set.window.title=New JDBC SQL Query Builder Data Set [Prototype]
wizard.data.set.page.title=Consulta SQL
