###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Databases Profile Data Source ODA Designer
newwizard.name=JDBC データベースプロファイルデータソース [プロトタイプ]
newwizard.description=JDBC データベース接続プロファイルを作成します。
wizard.window.title=JDBC データベースプロファイルの新規作成 [プロトタイプ]
wizard.data.source.page.title=JDBC データベースプロファイル [プロトタイプ]
profile.propertypage.name=JDBC ドライバと接続の詳細
wizard.data.set.window.title=JDBC SQL クエリビルダデータセットの新規作成 [プロトタイプ]
wizard.data.set.page.title=SQL クエリ
