###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=JDBC Database Connection for Query Builder [Prototype]
newwizard.description=JDBC データベース接続プロファイルを作成します。
wizard.window.title=New JDBC Database Connection [Prototype]
wizard.data.source.page.title=JDBC Database Connection [Prototype]
profile.propertypage.name=JDBC ドライバと接続の詳細
wizard.data.set.window.title=SQL Select クエリの新規作成 [クエリビルダのプロトタイプ]
wizard.data.set.page.title=SQL Select クエリ
