###############################################################################
# Copyright (c) 2008, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=JDBC Database Connection for Query Builder [Prototype]
newwizard.description=Verbindungsprofil für JDBC-Datenbanken erstellen
wizard.window.title=Neue JDBC-Datenbankverbindung für Abfrageerstellung [Prototyp]
wizard.data.source.page.title=JDBC-Datenbankverbindung für Abfrageerstellung [Prototyp]
profile.propertypage.name=JDBC-Treiber- und Verbindungsdetails
wizard.data.set.window.title=Neue SQL Select-Abfrage [Abfrage-Editor-Prototyp]
wizard.data.set.page.title=SQL Select-Abfrage
