###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=Connexion aux bases de données JDBC pour générateur de requête

newwizard.description=Créer un profil de connexion de la base de données JDBC

wizard.window.title=Nouvelle connexion aux bases de données JDBC pour générateur de requête

wizard.data.source.page.title=Connexion aux bases de données JDBC pour générateur de requête

profile.propertypage.name=Pilote JDBC et informations de connexion

wizard.data.set.window.title=Nouvelle requête de sélection SQL [Générateur de requête]

wizard.data.set.page.title=Requête de sélection SQL
