###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=쿼리 빌더에 대한 JDBC 데이터베이스 연결

newwizard.description=JDBC 데이터베이스 연결 프로필 생성

wizard.window.title=쿼리 빌더에 대한 새 JDBC 데이터베이스 연결

wizard.data.source.page.title=쿼리 빌더에 대한 JDBC 데이터베이스 연결

profile.propertypage.name=JDBC 드라이버 및 연결 상세 정보

wizard.data.set.window.title=새 SQL Select 쿼리[쿼리 빌더]

wizard.data.set.page.title=SQL Select 쿼리
