###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Database Connection Data Source ODA Designer
newwizard.name=JDBC-Datenbankverbindung für Abfrageerstellung

newwizard.description=Verbindungsprofil für JDBC-Datenbanken erstellen

wizard.window.title=Neue JDBC-Datenbankverbindung für Abfrageerstellung

wizard.data.source.page.title=JDBC-Datenbankverbindung für Abfrageerstellung

profile.propertypage.name=JDBC-Treiber- und Verbindungsdetails

wizard.data.set.window.title=Neue SQL Select-Abfrage [Abfrage-Editor]

wizard.data.set.page.title=SQL-Select-Abfrage
