###############################################################################
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# NLS strings
#
plugin.name=JDBC Databases Profile Data Source ODA Designer
newwizard.name=Source de données des profils des bases de données JDBC [Prototype]
newwizard.description=Créer un profil de connexion de la base de données JDBC
wizard.window.title=Nouveau profil des bases de données JDBC [Prototype]
wizard.data.source.page.title=Profil des bases de données JDBC [Prototype]
profile.propertypage.name=Pilote JDBC et informations de connexion
wizard.data.set.window.title=Nouvelle requête de sélection SQL [Prototype de générateur de requête]
wizard.data.set.page.title=Requête de sélection SQL
