DimensionType.2D=2D
DimensionType.2DWithDepth=Profondeur 2D

DimensionType.3D=3D
Shared.Lbl.OK=\ \ \ OK

Shared.Lbl.Cancel=Annuler

ButtonPanel.Lbl.SelectChartType=<< Sélectionner le type de graphique

ButtonPanel.Lbl.Previous=< Retour

ButtonPanel.Lbl.Next=Suivant >

ChartAdapter.Info.NotificationRecieved=ChartAdapter : notification reçue pour {0}

ChartAdapter.Info.NewValue=ChartAdapter : la nouvelle valeur est {0}

ChartSelector.Lbl.ChartSubtypes=Sous-types de graphique

ChartDlg.Msg.ValidationErrors=Erreurs détectées pendant la vérification de la définition du graphique.\nVeuillez corriger ces problèmes avant d'afficher le rapport.\n\n

ChartDlg.Msg.AskCorrectLater=\nSouhaitez-vous fermer le générateur de graphiques quand même\net corriger ces problèmes plus tard ?

ChartDlg.Info.ChartDimension=Dimension :

ChartDlg.Info.AxisOrientation=\tOrientation :

ChartSelector.Lbl.ChartTypes2=Types de graphiques

ChartSelector.Lbl.DefineChart=Définir le graphique >>

ChartDlg.Info.AssociatedAxis=\t\tAxe associé :

ChartDlg.Info.LineThickness2=\tEpaisseur de la ligne :

ChartSelector.Lbl.ChartTypes=Types de graphiques :

ChartSelector.Lbl.Transposed=Transposé

ChartAdapter.Exception.Exception=Exception :

ChartAdapter.Exception.WrappedIn=Réparti dans :

ChartUIUtil.Exception.NoValueReturned=Aucune valeur renvoyée. Spécifiez un jeu de données valide.

ChartAdapter.Exception.Message=Message :

ChartDlg.Info.CannotChangeSelection=REMARQUE : Vous ne pouvez pas modifier la sélection de graphique si le type et le sous-type du graphique actuel ne sont pas réglés.

ChartAdapter.Exception.Trace=Trace :

ChartSelector.Title.ChartSelector=Dispositif de sélection du graphique

ChartDlg.Title.ValidationResults=Résultats de validation

ChartDlg.Title.ChartBuilder=Boîte de dialogue du graphique

DefaultChartTypeImpl.Label.ValueDefinitionName=Séries (&Y) de valeur :

DefaultUIServiceProviderImpl.Warn.Placeholder=DefaultUIServiceProviderImpl : ceci est une classe de marque de réservation et n'a pas de conséquence.

SheetPlaceHolder.Lbl.Placeholder=Il s'agit d'une marque de réservation pour {0}

ChartDlg.Info.ChartStart=--------------------------- Début des propriétés du graphique -------------------------

ChartDlg.Info.ChartType=Type :

ChartDlg.Info.ChartSubType=Sous-type :

ChartDlg.Info.Orientation=Orientation

ChartDlg.Info.AxisCount=Nombre d'axes :

ChartDlg.Info.AxisStart=--------------------------- Infos axes ----------------------------

ChartDlg.Info.AxisTitle=\tTitre :

ChartDlg.Info.SeriesCount=\tNombre de séries :

ChartDlg.Info.SeriesStart=--------------------------- Infos série ----------------------------

ChartDlg.Info.DataSource=\t\tPremière source :

ChartDlg.Info.SeriesType=\t\tType de séries :

ChartDlg.Info.Riser=\t\tBarre ascendante :

ChartDlg.Info.LineStyle=\t\tStyle de ligne :

ChartDlg.Info.Fill=\t\tRemplissage :

ChartDlg.Info.LineStyle2=\t\tStyle de ligne :

ChartDlg.Info.Values=\t\tValeurs :

ChartDlg.Info.AxisEnd=--------------------------- Infos axes ----------------------------

ChartDlg.Info.ChartEnd=--------------------------- Fin des propriétés du graphique -------------------------

ChartDlg.Info.ChartStart2=--------------------------- Début des propriétés du graphique -------------------------

ChartDlg.Info.ChartType2=Type :

ChartSelector.Lbl.Accept=Accepter

ChartWizard.Title.ChartBuilder=Générateur de graphiques

ChartWizard.Title.NewChart=Nouveau graphique

ChartWizard.Title.EditChart=Modifier le graphique

ChartUIUtil.SeriesLabel=Série {0}

ChartUIUtil.StockExp.Low=Faible

ChartUIUtil.Font.Auto=Auto

ChartDlg.Info.ChartSubType2=Sous-type :

ChartSelector.Lbl.Dimension=&Dimension :

ChartSelector.Lbl.EditChart=Modifier le graphique >>

ChartDlg.Info.Dimension=Dimension :

ChartDlg.Info.SeriesCount2=Nº de série :

ChartDlg.Info.SeriesStart2=--------------------------- Infos série ----------------------------

ChartSelector.Lbl.Subtypes=Sous-types :

ChartUIUtil.StockExp.Close=Fermer

ChartDlg.Info.DataSource2=\tPremière source :

ChartDlg.Info.SeriesType2=\tType de série :

ChartUIUtil.StockExp.High=Elevé

ChartUIUtil.StockExp.Open=Ouvrir

ChartDlg.Info.Riser2=\tBarre ascendante :

ChartDlg.Info.Values2=\tValeurs :

ChartDlg.Info.ChartEnd2=--------------------------- Fin des propriétés du graphique -------------------------

PreviewButtonPanel.Lbl.ShowPreview=Exemple de graphique >>

PreviewButtonPanel.Lbl.HidePreview=<< Exemple de graphique

PreviewPanel.Title.Preview=Exemple de graphique

ChartWizard.Label.SelectChartTypeDataFormat=Sélectionner le type de graphique, les données et le format.

TaskSelectData.Warning.CategoryGroupTypeCheck=Le type de groupe {0} est incompatible avec le type de données de série de catégorie.

TaskSelectData.Warning.YGroupTypeCheck=Le type de groupe {0} est incompatible avec le type de données de regroupement de séries verticales.

TaskSelectType.Caption.OverlayAxis1=Titre de l'axe des y

ApplyButtonHandler.Label.Apply=Appl&iquer

ChartUIUtil.GanttExp.Label=Etiquette de tâches

ChartUIUtil.GanttExp.Start=Date de début

ChartUIUtil.GanttExp.End=Date de fin

ChartUIUtil.BubbleExp.Label=Valeur Y

ChartUIUtil.BubbleExp.Size=Taille

ChartUIUtil.DifferenceExp.Postive=Positif

ChartUIUtil.DifferenceExp.Negative=Négatif

ChartUIUtil.TaskSelectData.Warning.CheckAgg.Aggregation=\ agrégation.

ChartUIUtil.TaskSelectData.Warning.CheckAgg.DefaultAggregate=défaut

ChartUIUtil.TaskSelectData.Warning.CheckAgg.GanttChart=Le graphique de Gantt ne permet pas

ChartUIUtil.TaskSelectData.Warning.CheckAgg.ValueSeriesAggregate=séries de valeurs

ChartUIUtil.TaskSelectData.Warning.CheckAggAs=\ comme

SimpleHyperlinkBuilder.Label.RadioNone=Auc&un lien

SimpleHyperlinkBuilder.Label.RadioURI=&URI
SimpleHyperlinkBuilder.Title=Options de lien hypertexte

SimpleHyperlinkBuilder.Label.SelectType=Sélectionner un type de lien hypertexte :

SimpleHyperlinkBuilder.Label.Location=Emp&lacement :

SimpleHyperlinkBuilder.Label.Target=&Cible :

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=Index de colonne {0} incorrect ou colonnes non définies \!

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=Index de colonne spécifié incorrect \!

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=Index de colonne {0} incorrect \! La table ne comporte que {1} colonnes \!

CustomPreviewTable.Exception.RowIndexGreaterThan0=L'index de ligne doit être supérieur ou égal à 0 \!

ExprEditComposite.InvokeExpressionBuilder=Appeler le Générateur d'expression
