DimensionType.2D=2D
DimensionType.2DWithDepth=2D 奥行き付き

DimensionType.3D=3D
Shared.Lbl.OK=\ \ \ OK

Shared.Lbl.Cancel=キャンセル

ButtonPanel.Lbl.SelectChartType=<< グラフの種類の選択

ButtonPanel.Lbl.Previous=< 戻る

ButtonPanel.Lbl.Next=次へ >

ChartAdapter.Info.NotificationRecieved=ChartAdapter : {0} の通知を受信しました。

ChartAdapter.Info.NewValue=ChartAdapter : 新しい値は {0} です。

ChartSelector.Lbl.ChartSubtypes=グラフのサブタイプ

ChartDlg.Msg.ValidationErrors=グラフの定義にエラーが見つかりました。\nレポートを表示する前にエラーを修正してください。\n\n

ChartDlg.Msg.AskCorrectLater=\nこのままグラフビルダを閉じて、\n後でエラーを修正しますか ?

ChartDlg.Info.ChartDimension=ディメンション:

ChartDlg.Info.AxisOrientation=\t向き :

ChartSelector.Lbl.ChartTypes2=グラフの種類

ChartSelector.Lbl.DefineChart=グラフの定義 >>

ChartDlg.Info.AssociatedAxis=\t\t関連付けられた軸 :

ChartDlg.Info.LineThickness2=\t線の太さ:

ChartSelector.Lbl.ChartTypes=グラフの種類 :

ChartSelector.Lbl.Transposed=置き換え後

ChartAdapter.Exception.Exception=例外 :

ChartAdapter.Exception.WrappedIn=ネスト先 :

ChartUIUtil.Exception.NoValueReturned=戻り値がありません。有効なデータセットを指定してください。

ChartAdapter.Exception.Message=メッセージ :

ChartDlg.Info.CannotChangeSelection=注 : 現在のグラフに種類とサブタイプが指定されていない場合は、選択したグラフを変更できません。

ChartAdapter.Exception.Trace=トレース :

ChartSelector.Title.ChartSelector=グラフセレクタ

ChartDlg.Title.ValidationResults=検証結果

ChartDlg.Title.ChartBuilder=グラフダイアログボックス

DefaultChartTypeImpl.Label.ValueDefinitionName=値系列 (&Y) :

DefaultUIServiceProviderImpl.Warn.Placeholder=DefaultUIServiceProviderImpl: これはプレースホルダークラスであり、何も動作しません。

SheetPlaceHolder.Lbl.Placeholder=これは、{0} のプレースホルダーです。

ChartDlg.Info.ChartStart=--------------------------- グラフの属性の開始 -------------------------

ChartDlg.Info.ChartType=種類 :

ChartDlg.Info.ChartSubType=サブタイプ :

ChartDlg.Info.Orientation=向き :

ChartDlg.Info.AxisCount=軸の数 :

ChartDlg.Info.AxisStart=--------------------------- 軸の情報 ----------------------------

ChartDlg.Info.AxisTitle=\tタイトル :

ChartDlg.Info.SeriesCount=\t系列の数 :

ChartDlg.Info.SeriesStart=--------------------------- 系列の情報 ----------------------------

ChartDlg.Info.DataSource=\t\t最初のソース :

ChartDlg.Info.SeriesType=\t\t系列の型 :

ChartDlg.Info.Riser=\t\tライザ :

ChartDlg.Info.LineStyle=\t\t線の種類 :

ChartDlg.Info.Fill=\t\t塗りつぶし :

ChartDlg.Info.LineStyle2=\t\t線の種類 :

ChartDlg.Info.Values=\t\t値 :

ChartDlg.Info.AxisEnd=--------------------------- 軸の情報 ----------------------------

ChartDlg.Info.ChartEnd=--------------------------- グラフの属性の終了 -------------------------

ChartDlg.Info.ChartStart2=--------------------------- グラフの属性の開始 -------------------------

ChartDlg.Info.ChartType2=種類 :

ChartSelector.Lbl.Accept=確認

ChartWizard.Title.ChartBuilder=グラフビルダ

ChartWizard.Title.NewChart=グラフの新規作成

ChartWizard.Title.EditChart=グラフの編集

ChartUIUtil.SeriesLabel=系列 {0}

ChartUIUtil.StockExp.Low=最安値

ChartUIUtil.Font.Auto=自動

ChartDlg.Info.ChartSubType2=サブタイプ :

ChartSelector.Lbl.Dimension=ディメンション(&D):

ChartSelector.Lbl.EditChart=グラフの編集 >>

ChartDlg.Info.Dimension=ディメンション:

ChartDlg.Info.SeriesCount2=系列の数 :

ChartDlg.Info.SeriesStart2=--------------------------- 系列の情報 ----------------------------

ChartSelector.Lbl.Subtypes=サブタイプ :

ChartUIUtil.StockExp.Close=終値

ChartDlg.Info.DataSource2=\t最初のソース :

ChartDlg.Info.SeriesType2=\t系列の型 :

ChartUIUtil.StockExp.High=最高値

ChartUIUtil.StockExp.Open=始値

ChartDlg.Info.Riser2=\tライザ :

ChartDlg.Info.Values2=\t値 :

ChartDlg.Info.ChartEnd2=--------------------------- グラフの属性の終了 -------------------------

PreviewButtonPanel.Lbl.ShowPreview=サンプルグラフ >>

PreviewButtonPanel.Lbl.HidePreview=<< サンプルグラフ

PreviewPanel.Title.Preview=サンプルグラフ

ChartWizard.Label.SelectChartTypeDataFormat=グラフの種類、データ、形式の選択

TaskSelectData.Warning.CategoryGroupTypeCheck=グループの型 {0} が、カテゴリ系列のデータ型と互換性がありません。

TaskSelectData.Warning.YGroupTypeCheck=グループの型 {0} が、Y 系列のグループ化のデータ型と互換性がありません。

TaskSelectType.Caption.OverlayAxis1=Y 軸のタイトル

ApplyButtonHandler.Label.Apply=適用(&Y)

ChartUIUtil.GanttExp.Label=タスクラベル

ChartUIUtil.GanttExp.Start=開始日

ChartUIUtil.GanttExp.End=完了日

ChartUIUtil.BubbleExp.Label=Y 値

ChartUIUtil.BubbleExp.Size=サイズ

ChartUIUtil.DifferenceExp.Postive=正数

ChartUIUtil.DifferenceExp.Negative=負数

ChartUIUtil.TaskSelectData.Warning.CheckAgg.Aggregation=\ 集計) を使用できません。

ChartUIUtil.TaskSelectData.Warning.CheckAgg.DefaultAggregate=デフォルト

ChartUIUtil.TaskSelectData.Warning.CheckAgg.GanttChart=ガントチャートでは、

ChartUIUtil.TaskSelectData.Warning.CheckAgg.ValueSeriesAggregate=値系列

ChartUIUtil.TaskSelectData.Warning.CheckAggAs=\ (

SimpleHyperlinkBuilder.Label.RadioNone=リンクなし(&O)

SimpleHyperlinkBuilder.Label.RadioURI=&URI
SimpleHyperlinkBuilder.Title=ハイパーリンクのオプション

SimpleHyperlinkBuilder.Label.SelectType=ハイパーテキストの種類 :

SimpleHyperlinkBuilder.Label.Location=場所(&L) :

SimpleHyperlinkBuilder.Label.Target=ターゲット(&T) :

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=指定した列インデックス {0} が無効か、列がまだ定義されていません。

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=指定した列インデックスが無効です。

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=指定した列インデックス {0} が無効です。テーブルには {1} 個の列しかありません。

CustomPreviewTable.Exception.RowIndexGreaterThan0=行インデックスは、0 かそれ以上にしてください。

ExprEditComposite.InvokeExpressionBuilder=式ビルダの起動
