/***********************************************************************
 * Copyright (c) 2005 IBM Corporation.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * IBM Corporation - initial API and implementation
 ***********************************************************************/

package org.eclipse.birt.chart.device.svg;

/**
 * This class provides javascript helper functions to enable user interactions such
 * as tooltip support.  Defines default styles for svg elements.
 */
public final class EventHandlers {

	public static StringBuffer styles = new StringBuffer()
		.append(".tooltip.text{ text-anchor:left;font-size:12pt;fill:black;}.tooltip{fill:rgb(244,245,235)}");
	
	public static StringBuffer content = new StringBuffer()
.append("function BuildHelper(tag, attrList, text) {\n")
.append("	this.tag = tag;\n")
.append("	this.attrList = attrList;\n")
.append("	this.text       = text;\n")
.append("	this.element  = null;\n")
.append("	this.textNode = null;\n")
.append("	}	\n")
.append("		\n")
.append("	BuildHelper.prototype.addToParent= function(parent) {	\n")
.append("	if (!parent) return;	\n")
.append("	var svgDocument = parent.ownerDocument;\n")
.append("	this.element = svgDocument.createElementNS(\"http://www.w3.org/2000/svg\",this.tag);\n")
.append("		\n")
.append("	for (var attribute in this.attrList){\n")
.append("	if (attribute == 'classType')	\n")
.append("		     this.element.setAttributeNS(null, 'class', this.attrList[attribute]);\n")
.append("	else	\n")
.append("		     this.element.setAttributeNS(null, attribute, this.attrList[attribute]);\n")
.append("	}	\n")
.append("		\n")
.append("	if (this.text) {\n")
.append("		this.textNode = svgDocument.createTextNode(this.text);\n")
.append("		this.element.appendChild(this.textNode);\n")
.append("	}\n")
.append("		\n")
.append("	parent.appendChild(this.element);\n")
.append("	};	\n")
.append("		\n")
.append("BuildHelper.prototype.insertBefore = function(parent, before) {\n")
.append("	if (typeof parent == 'undefined') return;	\n")
.append("	var svgDocument = parent.ownerDocument;\n")
.append("	this.element = svgDocument.createElementNS(\"http://www.w3.org/2000/svg\",this.tag);\n")
.append("		\n")
.append("	for (var attribute in this.attrList){\n")
.append("	if (attribute == 'classType')	\n")
.append("		     this.element.setAttributeNS(null, 'class', this.attrList[attribute]);\n")
.append("	else	\n")
.append("		     this.element.setAttributeNS(null, attribute, this.attrList[attribute]);\n")
.append("	}	\n")
.append("		\n")
.append("	if (this.text) {\n")
.append("		this.textNode = svgDocument.createTextNode(this.text);\n")
.append("		this.element.appendChild(textNode);\n")
.append("	}\n")
.append("		\n")
.append("	parent.insertBefore(this.element, before);\n")
.append("	};	\n")
.append("		\n")
.append("		\n")
.append("	BuildHelper.prototype.removeNode = function() {	\n")
.append("	if (this.element) this.element.parentNode.removeChild(this.element);\n")
.append("	this.tag = \"\";\n")
.append("	this.attrList = null;\n")
.append("	this.text = null;\n")
.append("	this.element = null;\n")
.append("	this.textNode = null;\n")
.append("	};	\n")
	.append("	function TM(){	\n")
	.append("	}	\n")
	.append("		\n")
	.append("TM.setParent = function TooltipManager_setParent(parent, mainSvg){\n")
	.append("	this.parent = parent;	\n")
	.append("	this.mainSvg = mainSvg	\n")
	.append("	}	\n")
	.append("		\n")
	.append("	TM.remove = function TooltipManager_removeTooltip(){	\n")
	.append("	if (typeof this.group != 'undefined'){	\n")
	.append("	  this.group.removeNode();\n")
	.append("	  this.group = undefined;\n")
	.append("	}	\n")
	.append("	}	\n")
	.append("		\n")
	.append("	TM.show = function TooltiplManager_showTooltip(evt){	\n")
	.append("	var text = TM.getText(TM.getTitleElement(evt));	\n")
	.append("	x = evt.clientX;	\n")
	.append("	y = evt.clientY;	\n")
	.append("	if (typeof this.group == 'undefined'){	\n")
	.append("	this.height = 15;	\n")
	.append("	this.xPadding = 5;	\n")
	.append("	   this.yPadding = -20;\n")
	.append("	   var mainSvg = evt.target.ownerDocument.documentElement;\n")
	.append("	   var off = mainSvg.currentTranslate;\n")
	.append("	   var scl = mainSvg.currentScale;\n")
	.append("	   this.group = new BuildHelper(\"g\",\n")
	.append("	     {\n")
	.append("	     transform:\"translate(\"+(((x+20))/scl)+\",\"+(((y+20))/scl)+\")\"\n")
	.append("	 } );\n")
	.append("	   this.group.addToParent(mainSvg);\n")
	.append("	   this.rectangle = new BuildHelper(\"rect\",\n")
	.append("	     {id:\"test\",\n")
	.append("	      x: 0,\n")
	.append("	      y: this.yPadding,\n")
	.append("	      height: this.height,\n")
	.append("	      classType: \"tooltip\"\n")
	.append("	 } );\n")
	.append("	   this.rectangle.addToParent(this.group.element);\n")
	.append("	   var textObj = new BuildHelper(\"text\",\n")
	.append("	     {id:\"tooltip\",\n")
	.append("	      x: this.xPadding,\n")
	.append("	      y: (this.height/2+4+this.yPadding),\n")
	.append("	      classType: \"tooltip text\"\n")
	.append("	 },text);\n")
	.append("	   textObj.addToParent(this.group.element);\n")
	.append("	   var itemlength = textObj.element.getComputedTextLength();\n")
	.append("	   this.rectangle.element.setAttributeNS(null, \"width\", (itemlength+2*this.xPadding));\n")
	.append("	  }\n")
	.append("	}\n")
	.append("		\n")
	.append("		\n")
	.append("	TM.getTitleElement = function TM_getTitleElement(evt){\n")
	.append("	    var elem = evt.currentTarget;\n")
	.append("	if (elem == null ) return;	\n")
	.append("	    var childs = elem.childNodes;\n")
	.append("	    for (var x=0; x<childs.length; x++){\n")
	.append("		if (childs.item(x).nodeType == 1 && childs.item(x).nodeName == \"title\")\n")
	.append("		    return childs.item(x);\n")
	.append("	    }\n")
	.append("	    return null;\n")
	.append("	}\n")
	.append("		\n")
	.append("	TM.getText = function TM_getText(elem){\n")
	.append("	   var childs = elem ? elem.childNodes : null;\n")
	.append("	   for (var x = 0;  childs && x < childs.length; x++)\n")
	.append("	      if (childs.item(x).nodeType == 3)\n")
	.append("		  return childs.item(x).nodeValue;\n")
	.append("	   return \"\";\n")
	.append("	}\n")
	.append("		\n");
}
