datasource.page.title=定义 ${odadesignerid.ds.displayname} 数据源

datasource.page.msg=连接到 Hive 的 JDBC 数据源。

datasource.page.driver.class=驱动程序类:

datasource.page.url=数据库 URL:

datasource.page.user=数据库用户:

datasource.upgrade.msg.firstLine=此数据集使用的数据源({0})是使用此产品的较旧版本创建的。

datasource.upgrade.msg.secondLine=其定义需要更新。 \n\n选择“确定”立即更新数据源 {0}。

datasource.upgrade.msg.thirdLine=然后您将需要重新打开此数据集编辑器。

datasource.propertyPage.tooltip=Hive Data Source
datasource.addfile=添加文件语句(&D):

datasource.group.text=Hive Server
datasource.label.ServerType=服务器类型(&S):

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=数据库 URL 不能为空。