datasource.page.title=${odadesignerid.ds.displayname} 데이터 원본 정의

datasource.page.msg=Hive에 연결하는 JDBC 데이터 원본

datasource.page.driver.class=드라이버 클래스:

datasource.page.url=데이터베이스 URL:

datasource.page.user=데이터베이스 사용자:

datasource.upgrade.msg.firstLine=이 데이터 집합에서 사용하는 데이터 원본({0})은 이 제품의 이전 릴리스에서 생성되었습니다.

datasource.upgrade.msg.secondLine=데이터 원본의 정의를 업데이트해야 합니다. \n\n지금 데이터 원본 {0}을(를) 업데이트하려면 "확인"을 선택하십시오.

datasource.upgrade.msg.thirdLine=그런 다음 이 데이터 집합 편집기를 다시 여십시오.

datasource.propertyPage.tooltip=Hive Data Source
datasource.addfile=파일 추가 문(&D):

datasource.group.text=Hive Server
datasource.label.ServerType=서버 유형(&S):

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=데이터베이스 URL을 입력해야 합니다.