datasource.page.title=Definir la fuente de datos de ${odadesignerid.ds.displayname}

datasource.page.msg=Una fuente de datos JDBC que se conecta a Hive.

datasource.page.driver.class=Clase de controlador:

datasource.page.url=Base de datos de URL:

datasource.page.user=Usuario de la base de datos:

datasource.upgrade.msg.firstLine=La fuente de datos ({0}) utilizada por este conjunto de datos se creó usando una versión más antigua de este producto.

datasource.upgrade.msg.secondLine=Es necesario actualizar la definición. \n\nSeleccione Aceptar para actualizar la fuente de datos {0} ahora.

datasource.upgrade.msg.thirdLine=Después tendrá que volver a abrir este editor de conjunto de datos.

datasource.propertyPage.tooltip=Hive Data Source
datasource.addfile=Sentencia Aña&dir archivo:

datasource.group.text=Hive Server
datasource.label.ServerType=Tipo de &servidor:

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=La URL de la base de datos no puede estar vacía.