datasource.page.title=${odadesignerid.ds.displayname} データソースの定義

datasource.page.msg=Hive に接続する JDBC データソースです。

datasource.page.driver.class=ドライバクラス :

datasource.page.url=データベースの URL :

datasource.page.user=データベースのユーザー :

datasource.upgrade.msg.firstLine=このデータセットで使用しているデータソース ({0}) は、この製品の以前のリリースで作成されています。

datasource.upgrade.msg.secondLine=データソースの定義を更新する必要があります。 \n\nデータソース {0} を今すぐ更新するには、[OK] をクリックしてください。

datasource.upgrade.msg.thirdLine=更新した後で、このデータセットエディタをもう一度開いてください。

datasource.propertyPage.tooltip=Hive Data Source
datasource.addfile=ファイルステートメントの追加(&D):

datasource.group.text=Hive Server
datasource.label.ServerType=サーバタイプ(&S):

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=データベース URL を空白にすることはできません。