datasource.page.title=Datenquelle für ${odadesignerid.ds.displayname} definieren

datasource.page.msg=Eine JDBC-Datenquelle, die mit Hive verknüpft ist.

datasource.page.driver.class=Treiberklasse:

datasource.page.url=Datenbank-URL:

datasource.page.user=Datenbank-Benutzer:

datasource.upgrade.msg.firstLine=Die von diesem Datensatz verwendete Datenquelle ({0}) wurde mit einer früheren Version dieses Programms erstellt.

datasource.upgrade.msg.secondLine=Die Definition muss aktualisiert werden. \n\nWählen Sie 'OK', um die Datenquelle {0} jetzt zu aktualisieren.

datasource.upgrade.msg.thirdLine=Öffnen Sie den Datensatzeditor anschließend erneut.

datasource.propertyPage.tooltip=Hive Data Source
datasource.addfile=Anweisung 'Datei h&inzufügen':

datasource.group.text=Hive Server
datasource.label.ServerType=&Servertyp:

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=Datenbank-URL darf nicht leer sein.