#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.xmlsource=XML 소스(&X)

template.xmlsource=XML 소스(&X)

library.xmlsource=XML 소스(&X)

pageSet.source=XML 소스 페이지(&X)