#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=PDF(Portable Document Format) 형식의 보고서 렌더링 옵션을 구성합니다.

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 처리

OptionDisplayValue.TextWrapping=텍스트 줄 바꿈

OptionDisplayValue.TextHyphenation=텍스트에 하이픈 넣기

OptionDisplayValue.PageOverFlow=페이지 오버플로 처리

OptionDisplayValue.CLIP_CONTENT=내용 자르기

OptionDisplayValue.FIT_TO_PAGE_SIZE=페이지 크기에 맞추기

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=여러 페이지로 출력

OptionDisplayValue.ENLARGE_PAGE_SIZE=페이지 크기 확대

OptionDisplayValue.FontSubstitution=글꼴 대체

OptionDisplayValue.EmbeddedFont=포함 글꼴

OptionDisplayValue.ChartDpi=차트 DPI

OptionDisplayValue.RenderChartInSVG=벡터 그래픽 차트 렌더링

OptionDisplayValue.RepaginateForPDF=PDF 렌더링 도중 페이지 새로 매기기

OptionDisplayValue.DisableFlashAnimation=인쇄에 플래시 애니메이션 사용 안 함

OptionDisplayValue.DisablePrint=인쇄 사용 안 함

###########################################################
#Option Description
OptionDescription.BidiProcessing=양방향 텍스트를 지원합니다.

OptionDescription.TextHyphenation=텍스트에 하이픈 넣기를 지원합니다.

OptionDescription.TextWrapping=텍스트 줄 바꿈 가능 여부를 나타냅니다.

OptionDescription.PageOverFlow=내용 출력 방식을 제어합니다.

OptionDescription.FontSubstitution=지정된 글꼴이 문자를 표시하지 못하는 경우 자동으로 글꼴을 선택합니다.

OptionDescription.EmbeddedFont=트루타입 글꼴은 생성된 PDF 파일에 포함됩니다.

OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.

OptionDescription.RenderChartInSVG=벡터 그래픽 차트를 렌더링합니다.

OptionDescription.RepaginateForPDF=PDF를 렌더링하는 도중 페이지를 새로 매깁니다.

OptionDescription.DisableFlashAnimation=인쇄에 플래시 애니메이션을 사용하지 않습니다.

OptionDescription.DisablePrint=인쇄를 사용하지 않습니다.

###########################################################
#tooltip
Tooltip.ChartDpi=차트 엔진에서 차트를 생성하는 데 사용하는 DPI입니다. 예: 192.