#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=Optionen zum Rendern eines Berichts im PDF-Format (Portable Document Format) konfigurieren.
PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung
OptionDisplayValue.TextWrapping=Zeilenumbruch
OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung
OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden
OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben
OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern
OptionDisplayValue.FontSubstitution=Schriftart ersetzen
OptionDisplayValue.EmbeddedFont=Eingebettete Schriftart
OptionDisplayValue.ChartDpi=Diagramm-DPI 

###########################################################
#Option Description
OptionDescription.BidiProcessing=Bidirektionale Unterstützung.
OptionDescription.TextWrapping=Text mit Zeilenumbrüchen.
OptionDescription.PageOverFlow=Legen Sie fest, wie der Inhalt ausgegeben wird.
OptionDescription.FontSubstitution=Schriftarten automatisch wählen, wenn die angegebene Schriftart das Zeichen nicht darstellen kann.
OptionDescription.EmbeddedFont=Die TrueType-Schrift muss in die erstellte PDF-Datei eingebettet werden.
OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.
