#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=Configure las opciones para procesar un informe en formato PDF (Portable Document Format).

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Procesamiento de BIDI

OptionDisplayValue.TextWrapping=Autoajuste de texto

OptionDisplayValue.TextHyphenation=Separación con guión de texto

OptionDisplayValue.PageOverFlow=Procesamiento del desbordamiento de página

OptionDisplayValue.CLIP_CONTENT=Cortar contenido

OptionDisplayValue.FIT_TO_PAGE_SIZE=Ajustar a tamaño de página

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Salida de varias páginas

OptionDisplayValue.ENLARGE_PAGE_SIZE=Aumentar tamaño de página

OptionDisplayValue.FontSubstitution=Sustitución de fuente

OptionDisplayValue.EmbeddedFont=Fuente incrustada

OptionDisplayValue.ChartDpi=Diagrama DPI

OptionDisplayValue.RenderChartInSVG=Procesar diagrama en los gráficos vectoriales

OptionDisplayValue.RepaginateForPDF=Repaginar mientras se procesa el PDF

OptionDisplayValue.DisableFlashAnimation=Desactivar animación Flash para impresión

OptionDisplayValue.DisablePrint=Desactivar impresión

###########################################################
#Option Description
OptionDescription.BidiProcessing=Admite texto bidireccional.

OptionDescription.TextHyphenation=Compatible con la separación con guión de texto.

OptionDescription.TextWrapping=Indica si el texto se puede autoajustar.

OptionDescription.PageOverFlow=Controla cómo se va a mostrar el contenido.

OptionDescription.FontSubstitution=Selecciona fuentes automáticamente cuando la fuente especificada no puede mostrar el carácter.

OptionDescription.EmbeddedFont=La fuente de tipo true estará incrustada en el archivo PDF generado.

OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

OptionDescription.RenderChartInSVG=Procesar diagrama en los gráficos vectoriales.

OptionDescription.RepaginateForPDF=Repaginar mientras se procesa el PDF.

OptionDescription.DisableFlashAnimation=Desactivar la animación Flash para la impresión.

OptionDescription.DisablePrint=Desactivar la impresión.

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.