#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=PDF(Portable Document Format) 형식의 보고서 렌더링 옵션을 구성합니다.
PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 처리
OptionDisplayValue.TextWrapping=텍스트 배치
OptionDisplayValue.PageOverFlow=페이지 오버플로 처리
OptionDisplayValue.CLIP_CONTENT=내용 자르기
OptionDisplayValue.FIT_TO_PAGE_SIZE=페이지 크기에 맞추기
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=여러 페이지로 출력
OptionDisplayValue.ENLARGE_PAGE_SIZE=페이지 크기 확대
OptionDisplayValue.FontSubstitution=글꼴 대체
OptionDisplayValue.EmbeddedFont = 포함 글꼴

###########################################################
#Option Description
OptionDescription.BidiProcessing=BIDI 처리를 사용합니다.
OptionDescription.TextWrapping=The text should be wrap.
OptionDescription.PageOverFlow=내용 출력 방식을 제어합니다.
OptionDescription.FontSubstitution=선택한 글꼴에 해당 문자가 있는지 확인해야 합니다.
OptionDescription.EmbeddedFont = 트루타입 글꼴은 생성된 PDF 파일에 포함되어야 합니다.
