#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=配置用于以 PDF（可移植文档格式）格式呈现报表的选项。

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 处理

OptionDisplayValue.TextWrapping=文字环绕

OptionDisplayValue.TextHyphenation=文本连接

OptionDisplayValue.PageOverFlow=页面溢出处理

OptionDisplayValue.CLIP_CONTENT=剪切内容

OptionDisplayValue.FIT_TO_PAGE_SIZE=适合页面大小

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=输出多页

OptionDisplayValue.ENLARGE_PAGE_SIZE=增加页面大小

OptionDisplayValue.FontSubstitution=字体替换

OptionDisplayValue.EmbeddedFont=嵌入字体

OptionDisplayValue.ChartDpi=图表 DPI

OptionDisplayValue.RenderChartInSVG=以向量图形呈现图表

OptionDisplayValue.RepaginateForPDF=呈现 PDF 时重标页码

OptionDisplayValue.DisableFlashAnimation=禁用打印 Flash 动画

OptionDisplayValue.DisablePrint=禁用打印

###########################################################
#Option Description
OptionDescription.BidiProcessing=支持双向文字。

OptionDescription.TextHyphenation=支持文本连接。

OptionDescription.TextWrapping=表示文字可否环绕。

OptionDescription.PageOverFlow=控制内容输出方式。

OptionDescription.FontSubstitution=指定的字体无法显示该字符时自动选择字体。

OptionDescription.EmbeddedFont=TrueType 字体将嵌入到生成的 PDF 文件中。

OptionDescription.ChartDpi=用于生成图表的 DPI。

OptionDescription.RenderChartInSVG=以向量图形呈现图表。

OptionDescription.RepaginateForPDF=呈现 PDF 时重标页码。

OptionDescription.DisableFlashAnimation=禁用打印 Flash 动画。

OptionDescription.DisablePrint=禁用打印。

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。例如，192。