#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=Configurez les options pour un rendu de rapport au format PDF (Portable Document Format).

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI

OptionDisplayValue.TextWrapping=Retour à la ligne automatique

OptionDisplayValue.TextHyphenation=Césure de texte

OptionDisplayValue.PageOverFlow=Traitement du dépassement de page

OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu

OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages

OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page

OptionDisplayValue.FontSubstitution=Changement de police

OptionDisplayValue.EmbeddedFont=Police intégrée

OptionDisplayValue.ChartDpi=DPI de graphique

OptionDisplayValue.RenderChartInSVG=Afficher le graphique en image vectorielle

OptionDisplayValue.RepaginateForPDF=Nouvelle mise en page lors du rendu PDF

OptionDisplayValue.DisableFlashAnimation=Désactiver l'animation Flash pour l'impression

OptionDisplayValue.DisablePrint=Désactiver l'impression

###########################################################
#Option Description
OptionDescription.BidiProcessing=Prend en charge le texte bidirectionnel.

OptionDescription.TextHyphenation=Prend en charge la césure de texte.

OptionDescription.TextWrapping=Indique si le retour à la ligne est autorisé pour le texte.

OptionDescription.PageOverFlow=Contrôle le mode de répartition du contenu.

OptionDescription.FontSubstitution=Sélectionne des polices automatiquement lorsque la police spécifiée ne peut pas afficher le caractère.

OptionDescription.EmbeddedFont=La police TrueType sera intégrée au fichier PDF généré.

OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

OptionDescription.RenderChartInSVG=Afficher le graphique en image vectorielle.

OptionDescription.RepaginateForPDF=Nouvelle mise en page lors du rendu PDF.

OptionDescription.DisableFlashAnimation=Désactiver l'animation Flash pour l'impression.

OptionDescription.DisablePrint=Désactiver l'impression.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.