#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=PDF (Portable Document Format) 形式でレポートをレンダリングするためのオプションを設定します。

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=双方向テキストの処理

OptionDisplayValue.TextWrapping=文字列の折り返し

OptionDisplayValue.TextHyphenation=テキストのハイフネーション

OptionDisplayValue.PageOverFlow=オーバーフローしているページの処理

OptionDisplayValue.CLIP_CONTENT=コンテンツのクリッピング

OptionDisplayValue.FIT_TO_PAGE_SIZE=ページサイズに合わせる

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=複数ページを出力

OptionDisplayValue.ENLARGE_PAGE_SIZE=ページサイズを大きくする

OptionDisplayValue.FontSubstitution=フォントの置き換え

OptionDisplayValue.EmbeddedFont=埋め込みフォント

OptionDisplayValue.ChartDpi=グラフの DPI

OptionDisplayValue.RenderChartInSVG=ベクタグラフィックでグラフをレンダリング

OptionDisplayValue.RepaginateForPDF=PDF のレンダリングのページ数再割り当て

OptionDisplayValue.DisableFlashAnimation=印刷時の Flash アニメーションを無効にする

OptionDisplayValue.DisablePrint=印刷を無効にする

###########################################################
#Option Description
OptionDescription.BidiProcessing=双方向テキストをサポートします。

OptionDescription.TextHyphenation=テキストのハイフネーションをサポートします。

OptionDescription.TextWrapping=文字列を折り返すことができるかどうかを示します。

OptionDescription.PageOverFlow=コンテンツの出力方法を制御します。

OptionDescription.FontSubstitution=指定されたフォントで表示できない文字がある場合は、フォントを自動的に選択します。

OptionDescription.EmbeddedFont=生成される PDF ファイルには、TrueType フォントが埋め込まれます。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

OptionDescription.RenderChartInSVG=ベクタグラフィックでグラフをレンダリングします。

OptionDescription.RepaginateForPDF=PDF のレンダリングのページ数再割り当て。

OptionDescription.DisableFlashAnimation=印刷時の Flash アニメーションを無効にします。

OptionDescription.DisablePrint=印刷を無効にします。

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。例: 192。