#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=Configurez les options pour un rendu de rapport au format PDF (Portable Document Format).
PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI
OptionDisplayValue.TextWrapping=Retour à la ligne automatique
OptionDisplayValue.PageOverFlow=Traitement du dépassement de page
OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu
OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages
OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page
OptionDisplayValue.FontSubstitution=Changement de police
OptionDisplayValue.EmbeddedFont=Police intégrée
OptionDisplayValue.ChartDpi=DPI de graphique 

###########################################################
#Option Description
OptionDescription.BidiProcessing=Prise en charge de BIDI.
OptionDescription.TextWrapping=Retour à la ligne.
OptionDescription.PageOverFlow=Vérifiez comment répartir le contenu.
OptionDescription.FontSubstitution=Sélectionnez des polices automatiquement si la police spécifiée ne peut pas afficher le caractère.
OptionDescription.EmbeddedFont=La police TrueType devrait être intégrée au fichier PDF généré.
OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.
