#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=Optionen zum Rendern eines Berichts im PDF-Format (Portable Document Format) konfigurieren.

PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung

OptionDisplayValue.TextWrapping=Zeilenumbruch

OptionDisplayValue.TextHyphenation=Textsilbentrennung

OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung

OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden

OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben

OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern

OptionDisplayValue.FontSubstitution=Schriftart ersetzen

OptionDisplayValue.EmbeddedFont=Eingebettete Schriftart

OptionDisplayValue.ChartDpi=Diagramm-DPI

OptionDisplayValue.RenderChartInSVG=Diagramm in Vektorgrafiken rendern

OptionDisplayValue.RepaginateForPDF=Während des Renderns der PDF neu paginieren

OptionDisplayValue.DisableFlashAnimation=Zum Drucken Flash-Animation deaktivieren

OptionDisplayValue.DisablePrint=Drucken deaktivieren

###########################################################
#Option Description
OptionDescription.BidiProcessing=Unterstützt bidirektionalen Text.

OptionDescription.TextHyphenation=Textsilbentrennung unterstützen.

OptionDescription.TextWrapping=Gibt an, ob der Text Zeilenumbrüche enthält.

OptionDescription.PageOverFlow=Legt fest, wie der Inhalt ausgegeben wird.

OptionDescription.FontSubstitution=Wählt Schriftarten automatisch aus, wenn die angegebene Schriftart das Zeichen nicht darstellen kann.

OptionDescription.EmbeddedFont=Die TrueType-Schrift wird in die erstellte PDF-Datei eingebettet.

OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

OptionDescription.RenderChartInSVG=Diagramm in Vektorgrafiken rendern.

OptionDescription.RepaginateForPDF=Während des Renderns der PDF neu paginieren.

OptionDescription.DisableFlashAnimation=Zum Drucken Flash-Animation deaktivieren.

OptionDescription.DisablePrint=Drucken deaktivieren.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.