#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#PDF Emitter
PDFEmitter.Description=配置用于以 PDF (可移植文档格式)格式呈现报表的选项。
PDFEmitter.DisplayName=PDF

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 处理
OptionDisplayValue.TextWrapping=自动换行
OptionDisplayValue.PageOverFlow=页面溢出处理
OptionDisplayValue.CLIP_CONTENT=剪裁内容
OptionDisplayValue.FIT_TO_PAGE_SIZE=适合大小
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=输出多页
OptionDisplayValue.ENLARGE_PAGE_SIZE=扩大页面大小
OptionDisplayValue.FontSubstitution=字体替代
OptionDisplayValue.EmbeddedFont = 嵌入字体

###########################################################
#Option Description
OptionDescription.BidiProcessing=已使用 BIDI 处理。
OptionDescription.TextWrapping=The text should be wrap.
OptionDescription.PageOverFlow=控制如何输出内容。
OptionDescription.FontSubstitution=需要检查所选字体中是否存在字符。
OptionDescription.EmbeddedFont = true-type 字体应嵌入到生成的 PDF 文件中。
