###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# data source messages
DataSource.RuntimeProperty=&Laufzeit-Eigenschaften

DataSource.DataSetClassPath=Gemeinsamer &Speicherort für benutzerdefinierte POJO-Datensatzklassen

DataSource.AddRelativeJars0=JARs &hinzufügen (Relativer Pfad)...

DataSource.AddAbsoluteJars0=&JARs hinzufügen (Absoluter Pfad)...

#To avoid duplicate short-cut keys
DataSource.AddRelativeJars1=JAR&s hinzufügen (Relativer Pfad)...

DataSource.AddAbsoluteJars1=JARs hinzufügen (A&bsoluter Pfad)...

DataSource.AddRelativeClassFolder1=Klassenordn&er hinzufügen (Relativer Pfad)...

DataSource.AddAbsoluteClassFolder1=Klassenordner hinzufügen (Absol&uter Pfad)...

DataSource.button.tooltip.AddJar.TwoItems=JARs zu den Klassenpfaden hinzufügen.\nRelativer Pfad: der auf dem Ressourcenordner beruhende relative Pfad.\nAbsoluter Pfad: der absolute Pfad im Dateisystem.

DataSource.button.tooltip.AddJar.OneItems=JARs zu den Klassenpfaden hinzufügen.\nAbsoluter Pfad: der absolute Pfad des Dateisystems.

DataSource.PojoClassPath=Gemeinsamer S&peicherort von POJO-Klassen

DataSource.MissDataSetPojoClassPath.runtime=Gemeinsamer Speicherort von zur Laufzeit verwendeten benutzerdefinierten POJO-Datensatzklassen fehlt.

DataSource.MissDataSetPojoClassPath.designtime=Gemeinsamer Speicherort von zur Designzeit verwendeten benutzerdefinierten POJO-Datensatzklassen fehlt.

DataSource.PageMessage=POJO-Datenquelleneigenschaften

DataSource.POJOClasses.tab.runtime=&Laufzeit-Eigenschaften

DataSource.POJOClasses.tab.designTime=Designzeit&eigenschaften

DataSource.POJOClassTabFolderPage.promptLabel.runtime=Gemeinsamer &Speicherort für benutzerdefinierte POJO-Datensatzklassen

DataSource.POJOClassTabFolderPage.promptLabel.designtime=Gemeinsamer &Speicherort für benutzerdefinierte POJO-Klassen

DataSource.POJOClassTabFolderPage.button.edit=&Bearbeiten...

DataSource.POJOClassTabFolderPage.button.up=&Nach oben

DataSource.POJOClassTabFolderPage.button.down=&Nach unten

DataSource.POJOClassTabFolderPage.button.remove=Entf&ernen

DataSource.POJOClassTabFolderPage.menuButton.addJar=JARs hinzufügen

DataSource.POJOClassTabFolderPage.menuButton.item.relativePath=Relativer Pfad

DataSource.POJOClassTabFolderPage.menuButton.item.absolutePath=Absoluter Pfad

DataSource.POJOClassTabFolderPage.error.title.empty.resourceIdentifier=Fehler

DataSource.POJOClassTabFolderPage.error.message.empty.resourceIdentifier=Basis-URI von Anwendungsressource konnte nicht abgerufen werden.

DataSource.ClassPathPage.synchronize.checkbox.message=Verwenden Sie Laufzeit-Eigenschaften für Laufzeit und Designzeit

DataSource.ClassPathPage.synchronize.checkbox.tooltip=Ist die Option ausgewählt, ist die Bearbeitung mit Designtime Properties Editor deaktiviert.

DataSource.ClassPathPage.synchronize.PrompMessage=Hinweis: Ist die Option ausgewählt, werden die Designtime Properties-Einstellungen ignoriert.

DataSource.ClassPathPage.testConnection.failed.runtime=Fehler beim Herstellen von Verbindung mit '{0}' von Laufzeiteigenschaft!

DataSource.ClassPathPage.testConnection.failed.designtime=Fehler beim Herstellen von Verbindung mit '{0}' von Designzeiteigenschaft!


# data set messages
DataSet.PojoDataSetClass=&POJO-Datensatzklassenname

DataSet.AppContextKey=&Anwendungskontextschlüssel

DataSet.PojoRootClass=POJO-&Klassenname

DataSet.Browse=&Durchsuchen...

DataSet.Browse.tooltip=Nach einer Klasse suchen.

#To avoid duplicate short-cut key
DataSet.Browse1=D&urchsuchen...

DataSet.DataType.Object=Java-Objekt

DataSet.FailedParseQueryTitle=Fehler bei Analyse von Abfragetext

DataSet.FailedParseQueryMsg=Abfragetext: '{0}'.

DataSet.FailedToSaveTitle=Fehler beim Speichern von Datensatz

DataSet.FailedToSaveMsg=Ausnahmefehler bei Speichern von Datensatz.

DataSet.Label.MethodNameFilter=&Methodennamefilter (? = beliebiges Zeichen, * = beliebige Zeichenfolge):

DataSet.MissPojoRootClass=Keine POJO-Klasse angegeben.

DataSet.Apply=Über&nehmen

DataSet.ClassStructure=POJO-Klassenstruktur

DataSet.ColumnMapping=&Spaltenzuordnung

DataSet.Add=&Hinzufügen...

DataSet.Edit=&Bearbeiten...

DataSet.Remove=&Entfernen

DataSet.Up=&Nach oben

DataSet.Down=&Nach unten

DataSet.Label.POJOClassName=POJO-Klassenname

DataSet.Label.prompt.ClassName=Methoden und &Felder zum Erstellen von Datensatzspalten auswählen.

DataSet.button.addColumn.tooltip.mapColumn=Ausgewähltes Element als Spalte hinzufügen.

DataSet.button.removeColumn.tooltip.mapColumn=Das ausgewählte Element aus der Spaltentabelle entfernen.

DataSet.button.tooltip.Add=Neue Spalte hinzufügen.

DataSet.button.tooltip.Edit=Aktuelle Spalte bearbeiten.

DataSet.button.tooltip.Remove=Aktuelle Spalte entfernen.

DataSet.button.tooltip.Up=Aktuelle Spalte nach oben verschieben.

DataSet.button.tooltip.Down=Aktuelle Spalte nach unten verschieben.

DataSet.ShowSampleData=Beispieldaten &anzeigen

DataSet.button.tooltip.ShowSampleData=Beispieldaten anzeigen.

DataSet.FailedToLoadClassTitle=Fehler beim Laden von Klasse.

DataSet.FailedToLoadPojoClassMsg=Fehler beim Laden von POJO-Klasse: '{0}'.

ColumnMappingPage.table.head.columnName=Name

ColumnMappingPage.table.head.MethodField=Methode/Feld

ColumnMappingPage.table.head.columnType=Typ

ColumnMappingWizardPage.error.getQueryText=Fehler bei Analyse von Originalabfragetext.

ColumnMappingWizardPage.button.apply.text=Ü&bernehmen

ColumnMappingWizardPage.button.apply.tooltip=Eingabe-POJO-Klassennamen zur Erstellung der Methodenbaumstruktur übernehmen.

ColumnMappingDialog.Label.ColumnName=&Spaltenname:

ColumnMappingDialog.Label.ColumnMethodField=&Methode/Feld:

ColumnMappingDialog.Label.Type=Spalten&typ:

ColumnMappingDialog.table.promptLabel=Zu Parameter zugeordnete Methoden&argumente auswählen:

ColumnMappingDialog.table.head.mapped=Zugeordnet

ColumnMappingDialog.table.head.name=Name

ColumnMappingDialog.table.head.value=Wert

ColumnMappingDialog.table.head.dataType=Java-Datentyp

ColumnMappingDialog.button.edit=&Bearbeiten...

ColumnMappingDialog.button.selectAll=Alles &markieren

ColumnMappingDialog.button.deselectAll=&Auswahl aufheben

ColumnMappingDialog.Label.methodHierarchy=Methodenaufrufhierarchie:

ColumnMappingDialog.error.DuplicatedColumnName=Der Spaltenname wurde bereits verwendet!

ColumnMappingDialog.error.EmptyColumnName=Der Spaltenname darf nicht leer sein!

ColumnMappingDialog.error.EmptyMappingPath=Der Spaltenzuordnungspfad darf nicht leer sein!

ColumnMappingDialog.MenuItem.remove=Entfernen

ColumnMappingDialog.MenuItem.removeAll=Alle entfernen

MethodParameterDialog.edit.title=Methodenparameter bearbeiten

MethodParameterDialog.label.name=&Name:

MethodParameterDialog.label.value=&Wert:

MethodParameterDialog.label.dataType=&Java-Datentyp:

MethodParameterDialog.checkBox.message=Zu Parameter zugeordnetes Argument einstellen.

MethodParameterDialog.error.missingName=Für den zugeordneten Parameter muss ein Name angegeben werden!

MethodParameterDialog.error.missingValue=Für den Konstantenparameter muss ein konstanter Wert angegeben werden!

MethodParameterDialog.error.invalidParamName=Für den Parameter ist bereits ein anderer Datentyp angegeben!

MethodParameterDialog.error.missingDataType=Der Parameterdatentyp darf nicht leer sein!

DataSet.DataType.String=Zeichenfolge

DataSet.DataType.Integer=Ganzzahl
#make the display label consistent with BIRT data type 
DataSet.DataType.Double=Float

DataSet.DataType.Decimal=Decimal

DataSet.DataType.Date=Datum

DataSet.DataType.Time=Zeit
#make the display label consistent with BIRT data type 
DataSet.DataType.Timestamp=Datum/Uhrzeit

DataSet.DataType.Boolean=Boolean

DataSet.DataType.Blob=Blob

DataSet.AddColumnMapping=Spaltenzuordnung hinzufügen

DataSet.EditColumnMapping=Spaltenzuordnung bearbeiten

DataSet.InvalidColumnMappingPath=Ungültiges Methode/Feld-Format: '{0}'.

DataSet.InvalidMethodName=Ungültiger Methodenname: '{0}'.

DataSet.InvalidFieldName=Ungültiger Feldname: '{0}'.

DataSet.JarsSelectDlg.Title=JARs/ZIPs wählen

DataSet.ClassFoldersSelectDlg.Title=Klassenordner wählen

DataSet.PropertyPageMsg=POJO-Datensatz-Eigenschaften

DataSet.ColumnMappingPageMsg=Spaltenzuordnung

DataSet.NoColumnMappingErrorMsg=Keine Spaltenzuordnung.

DataSet.ClassNameFilter=&Klassennamefilter (? = beliebiges Zeichen, * = beliebige Zeichenfolge):

DataSet.MatchingItems=&Übereinstimmendes Element:

DataSet.ClassInputDialogTitle=Klasse wählen

DataSet.PreviewDialogTitle=Beispieldaten

DataSet.FailedFetchSampleData=Fehler beim Abrufen von Beispieldaten

ExceptionDialog.title.erro=Fehler

ExceptionDialog.DataSource.AddDuplicatedJar=Dieselbe JAR-Datei kann nicht mehrere Male hinzugefügt werden.

error.PojoDataSet.emptyClassName=Der Klassenname darf nicht leer sein.

JarsSelectionDialog.button.importFile=Importdatei...

JarsSelectionDialog.title.error=Fehler

JarsSelectionDialog.title.overwrite=Überschreiben

JarsSelectionDialog.overwrite.msg=Eine Datei mit diesem Namen ist bereits vorhanden. Soll sie überschrieben werden?

JarsSelectionDialog.import.msg=Datei wird importiert...
