###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# data source messages
DataSource.RuntimeProperty=P&ropriétés d'exécution

DataSource.DataSetClassPath=Emp&lacement partagé de classes de jeu de données POJO personnalisées

DataSource.AddRelativeJars0=&Ajouter des JAR (chemin d'accès relatif)...

DataSource.AddAbsoluteJars0=Ajouter des &JAR (chemin d'accès absolu)...

#To avoid duplicate short-cut keys
DataSource.AddRelativeJars1=Ajouter de&s JAR (chemin d'accès relatif)...

DataSource.AddAbsoluteJars1=Ajouter des JAR (chemin d'accès a&bsolu)...

DataSource.AddRelativeClassFolder1=Ajouter un dossi&er de classe (chemin d'accès relatif)...

DataSource.AddAbsoluteClassFolder1=Ajouter un dossier de classe (chemin d'accès absol&u)...

DataSource.button.tooltip.AddJar.TwoItems=Ajouter des JAR aux chemins de classe.\nChemin d'accès relatif : chemin d'accès relatif basé sur le dossier de ressources.\nChemin d'accès absolu : chemin d'accès absolu du système de fichiers.

DataSource.button.tooltip.AddJar.OneItems=Ajouter des JAR aux chemins de classe.\nChemin d'accès absolu : chemin d'accès absolu du système de fichiers.

DataSource.PojoClassPath=E&mplacement partagé de classes POJO

DataSource.MissDataSetPojoClassPath.runtime=L'emplacement partagé des classes de jeu de données POJO personnalisées utilisé lors de l'exécution est manquant.

DataSource.MissDataSetPojoClassPath.designtime=L'emplacement partagé des classes de jeu de données POJO personnalisées pour l'heure de conception est manquant.

DataSource.PageMessage=Propriétés de la source de données POJO

DataSource.POJOClasses.tab.runtime=P&ropriétés d'exécution

DataSource.POJOClasses.tab.designTime=&Propriétés d'heure de conception

DataSource.POJOClassTabFolderPage.promptLabel.runtime=Emp&lacement partagé de classes de jeu de données POJO personnalisées

DataSource.POJOClassTabFolderPage.promptLabel.designtime=Emp&lacement partagé des classes POJO personnalisées

DataSource.POJOClassTabFolderPage.button.edit=Modifi&er...

DataSource.POJOClassTabFolderPage.button.up=Vers le ha&ut

DataSource.POJOClassTabFolderPage.button.down=&Vers le bas

DataSource.POJOClassTabFolderPage.button.remove=Suppri&mer

DataSource.POJOClassTabFolderPage.menuButton.addJar=Ajouter des JAR

DataSource.POJOClassTabFolderPage.menuButton.item.relativePath=Chemin d'accès relatif

DataSource.POJOClassTabFolderPage.menuButton.item.absolutePath=Chemin d'accès absolu

DataSource.POJOClassTabFolderPage.error.title.empty.resourceIdentifier=Erreur

DataSource.POJOClassTabFolderPage.error.message.empty.resourceIdentifier=Impossible d'obtenir l'URI de base des ressources de l'application.

DataSource.ClassPathPage.synchronize.checkbox.message=Utilisez les propriétés d'exécution pour l'heure d'exécution et l'heure de conception

DataSource.ClassPathPage.synchronize.checkbox.tooltip=Si l'option est cochée, l'éditeur des propriétés de conception sera désactivé.

DataSource.ClassPathPage.synchronize.PrompMessage=Remarque : si l'option est cochée, les paramètres des propriétés de conception seront ignorés.

DataSource.ClassPathPage.testConnection.failed.runtime=Impossible d'établir la connexion avec "{0}" de la propriété d'exécution.

DataSource.ClassPathPage.testConnection.failed.designtime=Impossible d'établir la connexion avec "{0}" de la propriété d'heure de conception.


# data set messages
DataSet.PojoDataSetClass=Nom de la classe de jeu de données &POJO

DataSet.AppContextKey=Clé de contexte d'&application

DataSet.PojoRootClass=Nom de la &classe POJO

DataSet.Browse=&Parcourir...

DataSet.Browse.tooltip=Parcourir pour sélectionner une classe.

#To avoid duplicate short-cut key
DataSet.Browse1=Pa&rcourir...

DataSet.DataType.Object=Objet Java

DataSet.FailedParseQueryTitle=Impossible d'analyser le texte de la requête

DataSet.FailedParseQueryMsg=Texte de la requête : "{0}".

DataSet.FailedToSaveTitle=Impossible d'enregistrer le jeu de données

DataSet.FailedToSaveMsg=Une exception s'est produite pendant l'enregistrement du jeu de données.

DataSet.Label.MethodNameFilter=Filtre du nom de la &méthode (? = tout caractère * = toute chaîne):

DataSet.MissPojoRootClass=La classe POJO n'est pas fournie.

DataSet.Apply=Appl&iquer

DataSet.ClassStructure=Structure de classe POJO

DataSet.ColumnMapping=Mise en correspondance de &colonne

DataSet.Add=&Ajouter...

DataSet.Edit=Modifi&er...

DataSet.Remove=Supp&rimer

DataSet.Up=Vers le ha&ut

DataSet.Down=&Vers le bas

DataSet.Label.POJOClassName=Nom de la classe POJO

DataSet.Label.prompt.ClassName=Sélectionner les méthodes et les c&hamps pour créer des colonnes de jeux de données.

DataSet.button.addColumn.tooltip.mapColumn=Ajouter l'élément sélectionné pour en faire la colonne.

DataSet.button.removeColumn.tooltip.mapColumn=Supprimer l'élément sélectionné de la table de colonnes.

DataSet.button.tooltip.Add=Ajouter une nouvelle colonne.

DataSet.button.tooltip.Edit=Modifier la colonne actuelle.

DataSet.button.tooltip.Remove=Supprimer la colonne actuelle.

DataSet.button.tooltip.Up=Déplacer la colonne actuelle vers le haut.

DataSet.button.tooltip.Down=Déplacer la colonne actuelle vers le bas.

DataSet.ShowSampleData=Afficher le&s exemples de données

DataSet.button.tooltip.ShowSampleData=Afficher des exemples de données.

DataSet.FailedToLoadClassTitle=Echec du chargement de la classe.

DataSet.FailedToLoadPojoClassMsg=Echec du chargement de la classe POJO : "{0}".

ColumnMappingPage.table.head.columnName=Nom

ColumnMappingPage.table.head.MethodField=Méthode/Champ

ColumnMappingPage.table.head.columnType=Type

ColumnMappingWizardPage.error.getQueryText=Impossible d'analyser le texte de la requête d'origine.

ColumnMappingWizardPage.button.apply.text=A&ppliquer

ColumnMappingWizardPage.button.apply.tooltip=Appliquer le nom de la classe POJO d'entrée pour générer l'arborescence de la méthode.

ColumnMappingDialog.Label.ColumnName=Nom de &colonne :

ColumnMappingDialog.Label.ColumnMethodField=&Méthode/Champ :

ColumnMappingDialog.Label.Type=&Type de colonne :

ColumnMappingDialog.table.promptLabel=Sélectionner les &arguments de la méthode associés au paramètre :

ColumnMappingDialog.table.head.mapped=Associé

ColumnMappingDialog.table.head.name=Nom

ColumnMappingDialog.table.head.value=Valeur

ColumnMappingDialog.table.head.dataType=Type de données Java

ColumnMappingDialog.button.edit=Modifi&er...

ColumnMappingDialog.button.selectAll=&Sélectionner tout

ColumnMappingDialog.button.deselectAll=&Désélectionner tout

ColumnMappingDialog.Label.methodHierarchy=Hiérarchie des appels de méthode :

ColumnMappingDialog.error.DuplicatedColumnName=Le nom de la colonne existe déjà.

ColumnMappingDialog.error.EmptyColumnName=Le nom de la colonne doit être renseigné.

ColumnMappingDialog.error.EmptyMappingPath=Le chemin de la mise en correspondance de colonne doit être renseigné.

ColumnMappingDialog.MenuItem.remove=Supprimer

ColumnMappingDialog.MenuItem.removeAll=Supprimer tout

MethodParameterDialog.edit.title=Modifier le paramètre de méthode

MethodParameterDialog.label.name=&Nom :

MethodParameterDialog.label.value=&Valeur :

MethodParameterDialog.label.dataType=Type de données &Java :

MethodParameterDialog.checkBox.message=Définir l'argument associé au paramètre.

MethodParameterDialog.error.missingName=Le nom du paramètre associé doit être renseigné.

MethodParameterDialog.error.missingValue=Le paramètre constant doit indiquer une valeur constante.

MethodParameterDialog.error.invalidParamName=Le paramètre a déjà été spécifié par un autre type de données.

MethodParameterDialog.error.missingDataType=Le type de données du paramètre doit être renseigné.

DataSet.DataType.String=Chaîne

DataSet.DataType.Integer=Entier
#make the display label consistent with BIRT data type 
DataSet.DataType.Double=Flottant

DataSet.DataType.Decimal=Décimal

DataSet.DataType.Date=Date

DataSet.DataType.Time=Heure
#make the display label consistent with BIRT data type 
DataSet.DataType.Timestamp=Date Heure

DataSet.DataType.Boolean=Booléen

DataSet.DataType.Blob=Blob

DataSet.AddColumnMapping=Ajouter une mise en correspondance de colonne

DataSet.EditColumnMapping=Modifier la mise en correspondance de colonne

DataSet.InvalidColumnMappingPath=Méthode/Format de champ non valide : "{0}".

DataSet.InvalidMethodName=Nom de méthode incorrect : "{0}".

DataSet.InvalidFieldName=Nom de champ incorrect : "{0}".

DataSet.JarsSelectDlg.Title=Sélectionner des JAR / Zip

DataSet.ClassFoldersSelectDlg.Title=Sélectionner des dossiers de classe

DataSet.PropertyPageMsg=Propriétés du jeu de données POJO

DataSet.ColumnMappingPageMsg=Mise en correspondance de colonne

DataSet.NoColumnMappingErrorMsg=Aucune mise en correspondance de colonne.

DataSet.ClassNameFilter=&Filtre du nom de la classe (? = tout caractère * = toute chaîne):

DataSet.MatchingItems=&Eléments correspondants :

DataSet.ClassInputDialogTitle=Choisir la classe

DataSet.PreviewDialogTitle=Exemples de données

DataSet.FailedFetchSampleData=Impossible de récupérer des exemples de données

ExceptionDialog.title.erro=Erreur

ExceptionDialog.DataSource.AddDuplicatedJar=Un même JAR ne peut pas être ajouté plusieurs fois.

error.PojoDataSet.emptyClassName=Le nom de la classe ne peut pas être vide.

JarsSelectionDialog.button.importFile=Fichier d'importation...

JarsSelectionDialog.title.error=Erreur

JarsSelectionDialog.title.overwrite=Ecraser

JarsSelectionDialog.overwrite.msg=Un fichier portant ce nom existe déjà. Voulez-vous l'écraser ?

JarsSelectionDialog.import.msg=Importation du fichier...
