###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# data source messages
DataSource.RuntimeProperty=Propiedades del &tiempo de ejecución

DataSource.DataSetClassPath=&Ubicación compartida de las clases de conjuntos de datos POJO personalizadas

DataSource.AddRelativeJars0=&Añadir archivos jar (ruta relativa)...

DataSource.AddAbsoluteJars0=Añadir archivos &jar (ruta absoluta)...

#To avoid duplicate short-cut keys
DataSource.AddRelativeJars1=Aña&dir archivos jar (ruta relativa)...

DataSource.AddAbsoluteJars1=Añadir archivos ja&r (ruta absoluta)...

DataSource.AddRelativeClassFolder1=Añadir car&peta de clase (ruta relativa)...

DataSource.AddAbsoluteClassFolder1=Añadir carpeta de clase (ru&ta absoluta)...

DataSource.button.tooltip.AddJar.TwoItems=Añadir archivos jar a las rutas de clase.\nRuta relativa: ruta relativa basada en la carpeta de recursos.\nRuta absoluta: ruta absoluta del sistema de archivos.

DataSource.button.tooltip.AddJar.OneItems=Añadir archivos jar a las rutas de clase.\nRuta absoluta: ruta absoluta del sistema de archivos.

DataSource.PojoClassPath=U&bicación compartida de las clases POJO

DataSource.MissDataSetPojoClassPath.runtime=Falta la ubicación compartida del tiempo de ejecución de las clases de conjuntos de datos POJO personalizadas.

DataSource.MissDataSetPojoClassPath.designtime=Falta la ubicación compartida de las clases de conjuntos de datos POJO personalizadas utilizadas en el tiempo de diseño.

DataSource.PageMessage=Propiedades de la fuente de datos POJO

DataSource.POJOClasses.tab.runtime=Propiedades del &tiempo de ejecución

DataSource.POJOClasses.tab.designTime=&Propiedades del tiempo de diseño

DataSource.POJOClassTabFolderPage.promptLabel.runtime=&Ubicación compartida de las clases de conjuntos de datos POJO personalizadas

DataSource.POJOClassTabFolderPage.promptLabel.designtime=&Ubicación compartida de las clases POJO personalizadas

DataSource.POJOClassTabFolderPage.button.edit=&Editar...

DataSource.POJOClassTabFolderPage.button.up=A&rriba

DataSource.POJOClassTabFolderPage.button.down=&Abajo

DataSource.POJOClassTabFolderPage.button.remove=Qui&tar

DataSource.POJOClassTabFolderPage.menuButton.addJar=Añadir archivos jar

DataSource.POJOClassTabFolderPage.menuButton.item.relativePath=Ruta relativa

DataSource.POJOClassTabFolderPage.menuButton.item.absolutePath=Ruta relativa

DataSource.POJOClassTabFolderPage.error.title.empty.resourceIdentifier=Error

DataSource.POJOClassTabFolderPage.error.message.empty.resourceIdentifier=Error al obtener URI de base de recurso de aplicación

DataSource.ClassPathPage.synchronize.checkbox.message=Usar las propiedades del tiempo de ejecución para tiempo de ejecución y tiempo de diseño

DataSource.ClassPathPage.synchronize.checkbox.tooltip=Si la opción está marcada, el editor de propiedades del tiempo de diseño se desactivará para la edición.

DataSource.ClassPathPage.synchronize.PrompMessage=Nota: si la opción está marcada, los ajustes de las propiedades del tiempo de diseño se ignorarán.

DataSource.ClassPathPage.testConnection.failed.runtime=Error al crear conexión con "{0}" de la propiedad del tiempo de ejecución.

DataSource.ClassPathPage.testConnection.failed.designtime=Error al crear conexión con "{0}" de la propiedad del tiempo de diseño.


# data set messages
DataSet.PojoDataSetClass=Nombre de clase del conjunto de datos &POJO

DataSet.AppContextKey=&Clave de contenido de aplicación

DataSet.PojoRootClass=Nombre de &clase de POJO

DataSet.Browse=&Examinar...

DataSet.Browse.tooltip=Examine para seleccionar una clase.

#To avoid duplicate short-cut key
DataSet.Browse1=Examina&r...

DataSet.DataType.Object=Objeto Java

DataSet.FailedParseQueryTitle=Error al analizar el texto de consulta

DataSet.FailedParseQueryMsg=Texto de consulta: "{0}".

DataSet.FailedToSaveTitle=Error al guardar el conjunto de datos

DataSet.FailedToSaveMsg=Se ha producido una excepción al guardar el conjunto de datos.

DataSet.Label.MethodNameFilter=&Filtro del nombre del método(? = cualquier carácter, * = cualquier string):

DataSet.MissPojoRootClass=No se ha proporcionado la clase POJO.

DataSet.Apply=Apl&icar

DataSet.ClassStructure=Estructura de la clase POJO

DataSet.ColumnMapping=&Asignación de columnas

DataSet.Add=Aña&dir...

DataSet.Edit=&Editar...

DataSet.Remove=Quita&r

DataSet.Up=A&rriba

DataSet.Down=&Abajo

DataSet.Label.POJOClassName=Nombre de clase POJO

DataSet.Label.prompt.ClassName=Seleccionar métodos y &campos para crear columnas de conjuntos de datos.

DataSet.button.addColumn.tooltip.mapColumn=Añada el elemento seleccionado para hacer de columna.

DataSet.button.removeColumn.tooltip.mapColumn=Quitar el elemento seleccionado de la tabla de columnas.

DataSet.button.tooltip.Add=Añada una columna nueva.

DataSet.button.tooltip.Edit=Edite la columna actual.

DataSet.button.tooltip.Remove=Quite la columna actual.

DataSet.button.tooltip.Up=Mueva hacia arriba la columna actual.

DataSet.button.tooltip.Down=Mueva hacia abajo la columna actual.

DataSet.ShowSampleData=Mo&strar datos de muestra

DataSet.button.tooltip.ShowSampleData=Muestre los datos de muestra.

DataSet.FailedToLoadClassTitle=No se ha podido cargar la clase.

DataSet.FailedToLoadPojoClassMsg=No se ha podido cargar la clase POJO:"{0}".

ColumnMappingPage.table.head.columnName=Nombre

ColumnMappingPage.table.head.MethodField=Método/Campo

ColumnMappingPage.table.head.columnType=Tipo

ColumnMappingWizardPage.error.getQueryText=Error al analizar el texto de consulta original.

ColumnMappingWizardPage.button.apply.text=A&plicar

ColumnMappingWizardPage.button.apply.tooltip=Aplique el nombre de clase POJO de entrada para generar el árbol de método.

ColumnMappingDialog.Label.ColumnName=Nombre de &columna:

ColumnMappingDialog.Label.ColumnMethodField=&Método/Campo:

ColumnMappingDialog.Label.Type=&Tipo de columna:

ColumnMappingDialog.table.promptLabel=Seleccionar los &argumentos del método asignados al parámetro:

ColumnMappingDialog.table.head.mapped=Asignado

ColumnMappingDialog.table.head.name=Nombre

ColumnMappingDialog.table.head.value=Valor

ColumnMappingDialog.table.head.dataType=Tipo de datos Java

ColumnMappingDialog.button.edit=&Editar...

ColumnMappingDialog.button.selectAll=&Seleccionar todo

ColumnMappingDialog.button.deselectAll=&Anular la selección de todo

ColumnMappingDialog.Label.methodHierarchy=Jerarquía de llamada del método:

ColumnMappingDialog.error.DuplicatedColumnName=El nombre de columna ya se ha utilizado.

ColumnMappingDialog.error.EmptyColumnName=El nombre de columna no puede estar vacío.

ColumnMappingDialog.error.EmptyMappingPath=La ruta de asignación de columnas no puede estar vacía.

ColumnMappingDialog.MenuItem.remove=Quitar

ColumnMappingDialog.MenuItem.removeAll=Quitar todos

MethodParameterDialog.edit.title=Editar parámetro de método

MethodParameterDialog.label.name=&Nombre:

MethodParameterDialog.label.value=&Valor:

MethodParameterDialog.label.dataType=Tipo de datos &Java:

MethodParameterDialog.checkBox.message=Establecer el argumento asignado al parámetro.

MethodParameterDialog.error.missingName=El parámetro asignado debe tener un nombre.

MethodParameterDialog.error.missingValue=El parámetro de constante debe tener un valor de constante.

MethodParameterDialog.error.invalidParamName=El parámetro ya tiene un tipo de datos diferente.

MethodParameterDialog.error.missingDataType=El tipo de datos de parámetro no puede estar vacío.

DataSet.DataType.String=String

DataSet.DataType.Integer=Entero
#make the display label consistent with BIRT data type 
DataSet.DataType.Double=Flotante

DataSet.DataType.Decimal=Decimal

DataSet.DataType.Date=Fecha

DataSet.DataType.Time=Hora
#make the display label consistent with BIRT data type 
DataSet.DataType.Timestamp=Fecha Hora

DataSet.DataType.Boolean=Booleano

DataSet.DataType.Blob=Blob

DataSet.AddColumnMapping=Añadir asignación de columna

DataSet.EditColumnMapping=Editar asignación de columna

DataSet.InvalidColumnMappingPath=Formato de método/campo no válido:"{0}".

DataSet.InvalidMethodName=Nombre de método no válido:"{0}".

DataSet.InvalidFieldName=Nombre de campo no válido:"{0}".

DataSet.JarsSelectDlg.Title=Seleccionar archivos Jar/Zip

DataSet.ClassFoldersSelectDlg.Title=Seleccionar carpetas de clase

DataSet.PropertyPageMsg=Propiedades de conjuntos de datos POJO

DataSet.ColumnMappingPageMsg=Asignación de columnas

DataSet.NoColumnMappingErrorMsg=Sin asignación de columna.

DataSet.ClassNameFilter=&Filtro del nombre de clase(? = cualquier carácter, * = cualquier string):

DataSet.MatchingItems=&Elementos coincidentes:

DataSet.ClassInputDialogTitle=Elegir clase

DataSet.PreviewDialogTitle=Datos de muestra

DataSet.FailedFetchSampleData=Error al recuperar los datos de muestra

ExceptionDialog.title.erro=Error

ExceptionDialog.DataSource.AddDuplicatedJar=No es posible añadir el mismo archivo Jar varias veces.

error.PojoDataSet.emptyClassName=El nombre de la clase no puede estar vacío.

JarsSelectionDialog.button.importFile=Importar archivo...

JarsSelectionDialog.title.error=Error

JarsSelectionDialog.title.overwrite=Sobrescribir

JarsSelectionDialog.overwrite.msg=Ya existe un archivo con este nombre, ¿desea sobrescribirlo?

JarsSelectionDialog.import.msg=Importando archivo...
