###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# data source messages
DataSource.RuntimeProperty=런타임 속성(&R)

DataSource.DataSetClassPath=사용자 지정 POJO 데이터 집합 클래스의 공유 위치(&L)

DataSource.AddRelativeJars0=Jar 추가(상대 경로)(&A)...

DataSource.AddAbsoluteJars0=Jar 추가(절대 경로)(&J)...

#To avoid duplicate short-cut keys
DataSource.AddRelativeJars1=Jar 추가(상대 경로)(&S)...

DataSource.AddAbsoluteJars1=Jar 추가(절대 경로)(&B)...

DataSource.AddRelativeClassFolder1=클래스 폴더 추가(상대 경로)(&E)...

DataSource.AddAbsoluteClassFolder1=클래스 폴더 추가(절대 경로)(&U)...

DataSource.button.tooltip.AddJar.TwoItems=클래스 경로에 jar를 추가합니다.\n상대 경로: 리소스 폴더에 따른 상대 경로입니다.\n절대 경로: 파일 시스템의 절대 경로입니다.

DataSource.button.tooltip.AddJar.OneItems=클래스 경로에 jar를 추가합니다.\n절대 경로: 파일 시스템의 절대 경로입니다.

DataSource.PojoClassPath=POJO 클래스 공유 위치(&O)

DataSource.MissDataSetPojoClassPath.runtime=런타임에 사용되는 사용자 지정 POJO 데이터 집합 클래스의 공유 위치가 없습니다.

DataSource.MissDataSetPojoClassPath.designtime=디자인 시간에 사용되는 사용자 지정 POJO 데이터 집합 클래스의 공유 위치가 없습니다.

DataSource.PageMessage=POJO 데이터 원본 속성

DataSource.POJOClasses.tab.runtime=런타임 속성(&R)

DataSource.POJOClasses.tab.designTime=디자인 시간 속성(&P)

DataSource.POJOClassTabFolderPage.promptLabel.runtime=사용자 지정 POJO 데이터 집합 클래스의 공유 위치(&L)

DataSource.POJOClassTabFolderPage.promptLabel.designtime=사용자 지정 POJO 클래스의 공유 위치(&L)

DataSource.POJOClassTabFolderPage.button.edit=편집(&E)...

DataSource.POJOClassTabFolderPage.button.up=위로(&U)

DataSource.POJOClassTabFolderPage.button.down=아래로(&D)

DataSource.POJOClassTabFolderPage.button.remove=제거(&V)

DataSource.POJOClassTabFolderPage.menuButton.addJar=Jar 추가

DataSource.POJOClassTabFolderPage.menuButton.item.relativePath=상대 경로

DataSource.POJOClassTabFolderPage.menuButton.item.absolutePath=절대 경로

DataSource.POJOClassTabFolderPage.error.title.empty.resourceIdentifier=오류

DataSource.POJOClassTabFolderPage.error.message.empty.resourceIdentifier=응용 프로그램 리소스 기본 URI를 가져오지 못했습니다!

DataSource.ClassPathPage.synchronize.checkbox.message=런타임 및 디자인 타임 모두에 대해 런타임 속성을 사용합니다.

DataSource.ClassPathPage.synchronize.checkbox.tooltip=이 옵션을 선택하면 디자인 타임 속성 편집기를 사용하여 편집할 수 없습니다.

DataSource.ClassPathPage.synchronize.PrompMessage=참고: 옵션을 선택하면 디자인 타임 속성 설정이 무시됩니다.

DataSource.ClassPathPage.testConnection.failed.runtime=런타임 속성의 "{0}"과(와)의 연결을 만들지 못했습니다!

DataSource.ClassPathPage.testConnection.failed.designtime=디자인 시간 속성의 "{0}"과(와)의 연결을 만들지 못했습니다!


# data set messages
DataSet.PojoDataSetClass=POJO 데이터 집합 클래스 이름(&P)

DataSet.AppContextKey=응용 프로그램 컨텍스트 키(&A)

DataSet.PojoRootClass=POJO 클래스 이름(&C)

DataSet.Browse=찾아보기(&B)...

DataSet.Browse.tooltip=클래스를 찾아 선택합니다.

#To avoid duplicate short-cut key
DataSet.Browse1=찾아보기(&R)...

DataSet.DataType.Object=Java 개체

DataSet.FailedParseQueryTitle=쿼리 텍스트 구문 분석 실패

DataSet.FailedParseQueryMsg=쿼리 텍스트: "{0}".

DataSet.FailedToSaveTitle=데이터 집합 저장 실패

DataSet.FailedToSaveMsg=데이터 집합을 저장하는 동안 예외가 발생했습니다.

DataSet.Label.MethodNameFilter=메서드 이름 필터(? = 모든 문자, * = 모든 문자열)(&M):

DataSet.MissPojoRootClass=POJO 클래스가 제공되지 않았습니다.

DataSet.Apply=적용(&Y)

DataSet.ClassStructure=POJO 클래스 구조

DataSet.ColumnMapping=열 매핑(&C)

DataSet.Add=추가(&A)...

DataSet.Edit=편집(&E)...

DataSet.Remove=제거(&R)

DataSet.Up=위로(&U)

DataSet.Down=아래로(&D)

DataSet.Label.POJOClassName=POJO 클래스 이름

DataSet.Label.prompt.ClassName=데이터 집합 열을 만들려면 메서드와 필드를 선택하십시오(&F).

DataSet.button.addColumn.tooltip.mapColumn=선택한 항목을 열에 추가합니다.

DataSet.button.removeColumn.tooltip.mapColumn=열 테이블에서 선택한 항목을 제거합니다.

DataSet.button.tooltip.Add=새 열을 추가합니다.

DataSet.button.tooltip.Edit=현재 열을 편집합니다.

DataSet.button.tooltip.Remove=현재 열을 제거합니다.

DataSet.button.tooltip.Up=현재 열 위로 이동합니다.

DataSet.button.tooltip.Down=현재 열 아래로 이동합니다.

DataSet.ShowSampleData=샘플 데이터 표시(&S)

DataSet.button.tooltip.ShowSampleData=샘플 데이터를 표시합니다.

DataSet.FailedToLoadClassTitle=클래스 로드 실패

DataSet.FailedToLoadPojoClassMsg=POJO 클래스를 로드하지 못했습니다:"{0}".

ColumnMappingPage.table.head.columnName=이름

ColumnMappingPage.table.head.MethodField=메서드/필드

ColumnMappingPage.table.head.columnType=형식

ColumnMappingWizardPage.error.getQueryText=원본 쿼리 텍스트를 구문 분석하지 못했습니다.

ColumnMappingWizardPage.button.apply.text=적용(&P)

ColumnMappingWizardPage.button.apply.tooltip=입력 POJO 클래스 이름을 적용하여 메서드 트리를 생성합니다.

ColumnMappingDialog.Label.ColumnName=열 이름(&C):

ColumnMappingDialog.Label.ColumnMethodField=메서드/필드(&M):

ColumnMappingDialog.Label.Type=열 형식(&T):

ColumnMappingDialog.table.promptLabel=매개 변수에 매핑된 메서드 인수 선택(&A):

ColumnMappingDialog.table.head.mapped=매핑됨

ColumnMappingDialog.table.head.name=이름

ColumnMappingDialog.table.head.value=값

ColumnMappingDialog.table.head.dataType=Java 데이터 형식

ColumnMappingDialog.button.edit=편집(&E)...

ColumnMappingDialog.button.selectAll=모두 선택(&S)

ColumnMappingDialog.button.deselectAll=모두 선택 취소(&D)

ColumnMappingDialog.Label.methodHierarchy=메서드 호출 계층:

ColumnMappingDialog.error.DuplicatedColumnName=열 이름이 이미 사용되었습니다.

ColumnMappingDialog.error.EmptyColumnName=열 이름을 입력해야 합니다.

ColumnMappingDialog.error.EmptyMappingPath=열 매핑 경로를 입력해야 합니다.

ColumnMappingDialog.MenuItem.remove=제거

ColumnMappingDialog.MenuItem.removeAll=모두 제거

MethodParameterDialog.edit.title=메서드 매개 변수 편집

MethodParameterDialog.label.name=이름(&N):

MethodParameterDialog.label.value=값(&V):

MethodParameterDialog.label.dataType=Java 데이터 형식(&J):

MethodParameterDialog.checkBox.message=매개 변수에 매핑된 인수를 설정합니다.

MethodParameterDialog.error.missingName=매핑된 매개 변수에 이름을 지정해야 합니다.

MethodParameterDialog.error.missingValue=상수 매개 변수에는 상수 값을 지정해야 합니다.

MethodParameterDialog.error.invalidParamName=매개 변수에 이미 다른 데이터 형식이 지정되어 있습니다.

MethodParameterDialog.error.missingDataType=매개 변수 데이터 형식을 입력해야 합니다.

DataSet.DataType.String=문자열

DataSet.DataType.Integer=정수
#make the display label consistent with BIRT data type 
DataSet.DataType.Double=고정 해제

DataSet.DataType.Decimal=십진수

DataSet.DataType.Date=날짜

DataSet.DataType.Time=시간
#make the display label consistent with BIRT data type 
DataSet.DataType.Timestamp=날짜 시간

DataSet.DataType.Boolean=부울

DataSet.DataType.Blob=Blob

DataSet.AddColumnMapping=열 매핑 추가

DataSet.EditColumnMapping=열 매핑 편집

DataSet.InvalidColumnMappingPath=잘못된 메서드/필드 형식:"{0}".

DataSet.InvalidMethodName=잘못된 메서드 이름:"{0}".

DataSet.InvalidFieldName=잘못된 필드 이름:"{0}".

DataSet.JarsSelectDlg.Title=Jar/Zip 선택

DataSet.ClassFoldersSelectDlg.Title=클래스 폴더 선택

DataSet.PropertyPageMsg=POJO 데이터 집합 속성

DataSet.ColumnMappingPageMsg=열 매핑

DataSet.NoColumnMappingErrorMsg=열 매핑이 없습니다.

DataSet.ClassNameFilter=클래스 이름 필터(? = 모든 문자, * = 모든 문자열)(&C):

DataSet.MatchingItems=일치하는 항목(&M):

DataSet.ClassInputDialogTitle=클래스 선택

DataSet.PreviewDialogTitle=샘플 데이터

DataSet.FailedFetchSampleData=샘플 데이터를 가져오지 못했습니다.

ExceptionDialog.title.erro=오류

ExceptionDialog.DataSource.AddDuplicatedJar=같은 jar를 여러 번 추가할 수 없습니다.

error.PojoDataSet.emptyClassName=클래스 이름을 입력해야 합니다.

JarsSelectionDialog.button.importFile=파일 가져오기...

JarsSelectionDialog.title.error=오류

JarsSelectionDialog.title.overwrite=덮어쓰기

JarsSelectionDialog.overwrite.msg=같은 이름의 파일이 이미 있습니다. 덮어쓰시겠습니까?

JarsSelectionDialog.import.msg=파일을 가져오는 중...
