datasource.page.title=Nueva fuente de datos de muestra de Classic Models Inc.

datasource.page.msg=Se creará una fuente de datos JDBC que conecte con la base de datos de muestra de Classic Models Inc. con las siguientes propiedades de conexión

datasource.page.driver.class=Clase de controlador:

datasource.page.url=Base de datos de URL:

datasource.page.user=Usuario de la base de datos:

datasource.upgrade.msg.firstLine=La fuente de datos ({0}) utilizada por este conjunto de datos se creó usando una versión más antigua de este producto.

datasource.upgrade.msg.secondLine=Es necesario actualizar la definición. \n\nSeleccione Aceptar para actualizar la fuente de datos {0} ahora.

datasource.upgrade.msg.thirdLine=Después tendrá que volver a abrir este editor de conjunto de datos.

datasource.propertyPage.tooltip=Fuente de datos JDBC

datasource.page.warning=El uso de un perfil de conexión externalizado no es compatible con la base de datos de muestra, el diseño se está modificando para utilizar propiedades locales