datasource.page.title=Nouvelle source de données exemple de Classic Models Inc.
datasource.page.msg=Une source de données JDBC se connectant à la base de données exemple Classic Models Inc. sera créée avec les propriétés de connexion suivantes
datasource.page.driver.class=Classe de pilote :
datasource.page.url=URL de la base de données : 
datasource.page.user=Utilisateur de la base de données :
datasource.upgrade.msg=La source de données ({0}) utilisée par ce jeu de données a été créée à l''aide d''une version antérieure de ce produit. \nSa définition doit être mise à jour. \n\nCliquez sur OK pour mettre à jour la source de données {0} maintenant. Vous devrez ensuite ouvrir à nouveau cet éditeur de jeux de données.
datasource.propertyPage.tooltip=Source de données JDBC
