datasource.page.title=新的 Classic Models Inc. 示例数据源

datasource.page.msg=将使用下列连接属性来创建连接至 Classic Models Inc. 示例数据库的 JDBC 数据源

datasource.page.driver.class=驱动程序类:

datasource.page.url=数据库 URL:

datasource.page.user=数据库用户:

datasource.upgrade.msg.firstLine=此数据集使用的数据源({0})是使用此产品的较旧版本创建的。

datasource.upgrade.msg.secondLine=其定义需要更新。 \n\n选择“确定”立即更新数据源 {0}。

datasource.upgrade.msg.thirdLine=然后您将需要重新打开此数据集编辑器。

datasource.propertyPage.tooltip=JDBC 数据源

datasource.page.warning=示例数据库不支持使用外部化的连接配置文件，设计正被更改为使用本地属性