datasource.page.title=Classic Models Inc. の新規サンプルデータソース

datasource.page.msg=次の接続プロパティに基づいて、Classic Models Inc. のサンプルデータベースへ接続する JDBC データソースを作成します。

datasource.page.driver.class=ドライバクラス :

datasource.page.url=データベースの URL :

datasource.page.user=データベースのユーザー :

datasource.upgrade.msg.firstLine=このデータセットで使用しているデータソース ({0}) は、この製品の以前のリリースで作成されています。

datasource.upgrade.msg.secondLine=データソースの定義を更新する必要があります。 \n\nデータソース {0} を今すぐ更新するには、[OK] をクリックしてください。

datasource.upgrade.msg.thirdLine=更新した後で、このデータセットエディタをもう一度開いてください。

datasource.propertyPage.tooltip=JDBC データソース

datasource.page.warning=サンプルデータベースでは外部化した接続プロファイルの使用はサポートされていません。ローカルプロパティを使用するように設計が変更されています。