datasource.page.title=Classic Models Inc. の新規サンプルデータソース
datasource.page.msg=次の接続プロパティに基づいて、Classic Models Inc. のサンプルデータベースへ接続する JDBC データソースを作成します。
datasource.page.driver.class=ドライバクラス :
datasource.page.url=データベースの URL : 
datasource.page.user=データベースのユーザー :
datasource.upgrade.msg=このデータセットで使用しているデータソース ({0}) は、この製品の以前のリリースで作成されています。\nデータソースの定義を更新する必要があります。\n\nデータソース {0} を今すぐ更新するには、[OK] をクリックしてください。更新した後で、このデータセットエディタをもう一度開いてください。
datasource.propertyPage.tooltip=JDBC データソース
