datasource.page.title=Neue Beispieldatenquelle "Classic Models Inc."
datasource.page.msg=Es wird eine JDBC-Datenquelle erstellt, die mit der Beispieldatenbank "Classic Models Inc." verknüpft ist. Dafür gelten folgende Verbindungsparameter:
datasource.page.driver.class=Treiberklasse:
datasource.page.url=Datenbank-URL: 
datasource.page.user=Datenbank-Benutzer:
datasource.upgrade.msg=Die von diesem Datensatz verwendete Datenquelle ({0}) wurde mit einer früheren Version dieses Programms erstellt. \nDie Definition muss aktualisiert werden.\n\nWählen Sie "OK", um die Datenquelle {0} jetzt zu aktualisieren. Öffnen Sie den Datensatzeditor anschließend erneut.
datasource.propertyPage.tooltip=JDBC-Datenquelle
