datasource.page.title=New Classic Models Inc. 예제 데이터 원본
datasource.page.msg=Classic Models Inc. 예제 데이터베이스에 연결하는 JDBC 데이터 원본은 다음 연결 속성으로 생성됩니다.
datasource.page.driver.class=드라이버 클래스:
datasource.page.url=데이터베이스 URL: 
datasource.page.user=데이터베이스 사용자:
datasource.upgrade.msg=이 데이터 집합에서 사용하는 데이터 원본 {0}은(는) 이 제품의 이전 릴리스로 생성되었습니다. \n업데이트하려면 정의가 필요합니다.\n\n지금 데이터 원본 {0}을(를) 업데이트하려면 '확인'을 선택하십시오. 그런 다음 이 데이터 집합 편집기를 다시 열어야 합니다.
datasource.propertyPage.tooltip=JDBC 데이터 원본
