datasource.page.title=Neue Beispieldatenquelle "Classic Models Inc."

datasource.page.msg=Es wird eine JDBC-Datenquelle erstellt, die mit der Beispieldatenbank "Classic Models Inc." verknüpft ist. Dafür gelten folgende Verbindungsparameter:

datasource.page.driver.class=Treiberklasse:

datasource.page.url=Datenbank-URL:

datasource.page.user=Datenbank-Benutzer:

datasource.upgrade.msg.firstLine=Die von diesem Datensatz verwendete Datenquelle ({0}) wurde mit einer früheren Version dieses Programms erstellt.

datasource.upgrade.msg.secondLine=Die Definition muss aktualisiert werden. \n\nWählen Sie 'OK', um die Datenquelle {0} jetzt zu aktualisieren.

datasource.upgrade.msg.thirdLine=Öffnen Sie den Datensatzeditor anschließend erneut.

datasource.propertyPage.tooltip=JDBC-Datenquelle

datasource.page.warning=Externalisiertes Verbindungsprofil wird für die Beispieldatenbank nicht unterstützt, das Design wird für die Verwendung lokaler Eigenschaften geändert.