datasource.page.title=Nouvelle source de données exemple de Classic Models Inc.

datasource.page.msg=Une source de données JDBC se connectant à la base de données exemple Classic Models Inc. sera créée avec les propriétés de connexion suivantes

datasource.page.driver.class=Classe de pilote :

datasource.page.url=URL de la base de données :

datasource.page.user=Utilisateur de la base de données :

datasource.upgrade.msg.firstLine=La source de données ({0}) utilisée par ce jeu de données a été créée à partir d'une ancienne version de ce produit.

datasource.upgrade.msg.secondLine=Sa définition doit être mise à jour. \n\nSélectionnez OK pour mettre à jour la source de données {0} maintenant.

datasource.upgrade.msg.thirdLine=Ensuite, vous devez ouvrir à nouveau cet éditeur de jeu de données.

datasource.propertyPage.tooltip=Source de données JDBC

datasource.page.warning=L'utilisation d'un profil de connexion externalisé n'est pas prise en charge pour la BD exemple. Le modèle sera modifié pour utiliser les propriétés locales