###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=レポートの表示

designer.preview.previewcascadingmenugroup.label=レポートの表示(&R)

document.preview.previewtoolbarmenuaction.label=文書の表示

document.preview.previewmenugroup.label=文書の表示(&D)

ActionSet.Preview=プレビュー

ActionSet.PreviewWithSecurity=ドキュメントのプレビュー

Action.GenDocument=文書の生成(&D)

template.preview=プレビュー(&V)

design.preview=プレビュー(&V)

preference.preview=プレビュー

preference.preview.server=プレビュー用のサーバ

preference.preview.data=データ

menu.run=実行(&R)

###############################################################################
# Actions
###############################################################################
Menu.Report=レポート(&T)

Action.RunReport=レポートの実行（&R)

Action.ViewDocument=文書の表示(&V)
