###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Afficher l'état
designer.preview.previewcascadingmenugroup.label=Run &Report
ActionSet.Preview=Aperçu

template.preview=&Aperçu
design.preview=&Aperçu

preference.preview=Aperçu
preference.preview.server=Serveur de prévisualisation
preference.preview.data=Données

###############################################################################
# Actions
###############################################################################
Menu.Report=Etat
Action.RunReport=Exécuter l'état
Action.ViewDocument=Afficher le document
