###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Afficher l'état

designer.preview.previewcascadingmenugroup.label=Affiche&r l'état

document.preview.previewtoolbarmenuaction.label=Afficher le document

document.preview.previewmenugroup.label=Afficher le &document

ActionSet.Preview=Aperçu

ActionSet.PreviewWithSecurity=Aperçu du document

Action.GenDocument=Générer le &document

template.preview=&Aperçu

design.preview=&Aperçu

preference.preview=Aperçu

preference.preview.server=Serveur de prévisualisation

preference.preview.data=Données

menu.run=Exécute&r

###############################################################################
# Actions
###############################################################################
Menu.Report=Eta&t

Action.RunReport=&Exécuter l'état

Action.ViewDocument=&Afficher le document
