###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=查看报表

designer.preview.previewcascadingmenugroup.label=查看报表(&R)

document.preview.previewtoolbarmenuaction.label=查看文档

document.preview.previewmenugroup.label=查看文档(&D)

ActionSet.Preview=预览

ActionSet.PreviewWithSecurity=预览文档

Action.GenDocument=生成文档(&D)

template.preview=预览(&V)

design.preview=预览(&V)

preference.preview=预览

preference.preview.server=预览服务器

preference.preview.data=数据

menu.run=运行(&R)

###############################################################################
# Actions
###############################################################################
Menu.Report=报表(&T)

Action.RunReport=运行报表(&R)

Action.ViewDocument=查看文档(&V)
