###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=보고서 보기
designer.preview.previewcascadingmenugroup.label=보고서 보기(&R)
ActionSet.Preview=미리 보기

template.preview=미리 보기(&P)
design.preview=미리 보기(&P)

preference.preview=미리 보기
preference.preview.server=서버 미리 보기

###############################################################################
# Actions
###############################################################################
Menu.Report=보고서
Action.RunReport=보고서 실행
Action.ViewDocument=문서 보기
