###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=查看报表
designer.preview.previewcascadingmenugroup.label=查看报表(&R)
ActionSet.Preview=预览
Action.GenDocument=生成文档(&D)

template.preview=预览(&V)
design.preview=预览(&V)

preference.preview=预览
preference.preview.server=预览服务器
preference.preview.data=数据

menu.run=运行(&R)

###############################################################################
# Actions
###############################################################################
Menu.Report=Repor&t
Action.RunReport=&Run Report
Action.ViewDocument=&View Document
