###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=レポートの表示
designer.preview.previewcascadingmenugroup.label=レポートの表示
ActionSet.Preview=プレビュー

template.preview=プレビュー
design.preview=プレビュー

preference.preview=プレビュー
preference.preview.server=プレビュー用のサーバ

###############################################################################
# Actions
###############################################################################
Menu.Report=レポート
Action.RunReport=レポートの実行
Action.ViewDocument=文書の表示