###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Ver informe

designer.preview.previewcascadingmenugroup.label=Ver &Informe

document.preview.previewtoolbarmenuaction.label=Ver documento

document.preview.previewmenugroup.label=Ver &documento

ActionSet.Preview=Vista previa

ActionSet.PreviewWithSecurity=Previsualizar documento

Action.GenDocument=Generar &documento

template.preview=&Vista previa

design.preview=&Vista previa

preference.preview=Vista previa

preference.preview.server=Servidor de vista previa

preference.preview.data=Datos

menu.run=Ejecuta&r

###############################################################################
# Actions
###############################################################################
Menu.Report=In&forme

Action.RunReport=&Ejecutar informe

Action.ViewDocument=&Ver documento
