###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Afficher l'état
designer.preview.previewcascadingmenugroup.label=Affiche&r l'état
ActionSet.Preview=Aperçu
Action.GenDocument=Générer le &document

template.preview=&Aperçu
design.preview=&Aperçu

preference.preview=Aperçu
preference.preview.server=Serveur de prévisualisation
preference.preview.data=Données

menu.run=&Run

###############################################################################
# Actions
###############################################################################
Menu.Report=Etat
Action.RunReport=Exécuter l'état
Action.ViewDocument=Afficher le document
