###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Bericht anzeigen

designer.preview.previewcascadingmenugroup.label=&Bericht anzeigen

document.preview.previewtoolbarmenuaction.label=Dokument anzeigen

document.preview.previewmenugroup.label=&Dokument anzeigen

ActionSet.Preview=Vorschau

ActionSet.PreviewWithSecurity=Dokumentenvorschau

Action.GenDocument=&Dokument erstellen

template.preview=Vor&schau

design.preview=Vor&schau

preference.preview=Vorschau

preference.preview.server=Vorschau-Server

preference.preview.data=Daten

menu.run=&Ausführen

###############################################################################
# Actions
###############################################################################
Menu.Report=Berich&t

Action.RunReport=Bericht aus&führen

Action.ViewDocument=Dokument an&zeigen
