ScriptMainTab.title.report=Principal

ScriptMainTab.msg.report.file.name=Nombre de archivo de informe

ScriptMainTab.msg.eclipse.home=Inicio de Eclipse

ScriptMainTab.msg.engine.home=Inicio de motor

ScriptMainTab.msg.temp.folder=Carpeta de plantillas

ScriptMainTab.msg.debug.type=Tipo de depuración

ScriptMainTab.msg.task.type=Tipo de tarea

ScriptMainTab.msg.output=Salida

ScriptMainTab.msg.format=Formato:

ScriptMainTab.msg.debug.type.all=Todos

ScriptMainTab.msg.debug.type.java=Java
ScriptMainTab.msg.debug.type.script=Java Script
ScriptMainTab.msg.task.type.run.and.render=Ejecutar y Procesar

ScriptMainTab.msg.task.type.run=Ejecutar

ScriptMainTab.msg.task.type.render=Procesar

ScriptMainTab.msg.task.type.run.plus.render=Ejecutar + Procesar

ScriptMainTab.error.msg.no.eclipse.home=Inicio de Eclipse no especificado.

ScriptMainTab.error.msg.nonexist.eclipse.home=El inicio de Eclipse no existe.

ScriptMainTab.error.msg.invalid.eclipse.home=El inicio de Eclipse debe ser un directorio.

ScriptMainTab.error.msg.no.engine.home=Inicio de motor no especificado.

ScriptMainTab.error.msg.nonexist.engine.home=El inicio de motor no existe.

ScriptMainTab.error.msg.invalid.engine.home=El inicio de motor debe ser un directorio.

ScriptMainTab.error.msg.no.temp.folder=Carpeta de plantillas no especificada.

ScriptMainTab.error.msg.nonexist.temp.folder=La carpeta de plantillas no existe.

ScriptMainTab.error.msg.invalid.temp.folder=La carpeta de plantillas debe ser un directorio.

ScriptMainTab.error.msg.no.report.file=Archivo de informe no especificado.

ScriptMainTab.error.msg.nonexist.report.file=El archivo de informe no existe.

ScriptMainTab.error.msg.invalid.report.file=El archivo seleccionado no es un archivo de diseño de informe válido.

ScriptMainTab.error.msg.invalid.document.file=El archivo seleccionado no es un archivo de documento de informe válido.

ScriptMainTab.title.eclipse.home=Directorio principal de Eclipse

ScriptMainTab.msg.select.eclipse.home=Seleccione un directorio de inicio de Eclipse

ScriptMainTab.title.temp.folder=Directorio de carpetas de plantillas

ScriptMainTab.msg.select.temp.folder=Seleccione un directorio de carpetas de plantillas

ScriptMainTab.title.engine.home=Directorio principal de motor

ScriptMainTab.msg.select.engine.home=Seleccione un directorio de inicio de motor

ScriptMainTab.msg.select.report.file=Seleccione un archivo de informe

ScriptMainTab.button.text.search=Búsqueda...

ScriptMainTab.button.text.variables=Variables...

ScriptMainTab.msg.open.target.file=Abrir archivo generado cuando haya finalizado

ScriptMainTab.msg.use.default.engine.home=Usar inicio de motor predeterminado
