ScriptMainTab.title.report=メイン

ScriptMainTab.msg.report.file.name=レポートファイル名

ScriptMainTab.msg.eclipse.home=Eclipse のホーム

ScriptMainTab.msg.engine.home=エンジンのホーム

ScriptMainTab.msg.temp.folder=一時フォルダ

ScriptMainTab.msg.debug.type=デバッグの種類

ScriptMainTab.msg.task.type=タスクの種類

ScriptMainTab.msg.output=出力

ScriptMainTab.msg.format=書式:

ScriptMainTab.msg.debug.type.all=すべて

ScriptMainTab.msg.debug.type.java=Java
ScriptMainTab.msg.debug.type.script=Java Script
ScriptMainTab.msg.task.type.run.and.render=実行およびレンダリング

ScriptMainTab.msg.task.type.run=実行

ScriptMainTab.msg.task.type.render=レンダリング

ScriptMainTab.msg.task.type.run.plus.render=実行 + レンダリング

ScriptMainTab.error.msg.no.eclipse.home=Eclipse のホームが指定されていません。

ScriptMainTab.error.msg.nonexist.eclipse.home=Eclipse のホームが存在しません。

ScriptMainTab.error.msg.invalid.eclipse.home=Eclipse のホームにはディレクトリを設定してください。

ScriptMainTab.error.msg.no.engine.home=エンジンのホームが指定されていません。

ScriptMainTab.error.msg.nonexist.engine.home=エンジンのホームが存在しません。

ScriptMainTab.error.msg.invalid.engine.home=エンジンのホームにはディレクトリを設定してください。

ScriptMainTab.error.msg.no.temp.folder=一時フォルダが指定されていません。

ScriptMainTab.error.msg.nonexist.temp.folder=一時フォルダが存在しません。

ScriptMainTab.error.msg.invalid.temp.folder=一時フォルダにはディレクトリを設定してください。

ScriptMainTab.error.msg.no.report.file=レポートファイルが指定されていません。

ScriptMainTab.error.msg.nonexist.report.file=レポートファイルが存在しません。

ScriptMainTab.error.msg.invalid.report.file=選択したファイルは、有効なレポートデザインファイルではありません。

ScriptMainTab.error.msg.invalid.document.file=選択したファイルは、有効なレポート文書ファイルではありません。

ScriptMainTab.title.eclipse.home=Eclipse のホームディレクトリ

ScriptMainTab.msg.select.eclipse.home=Eclipse のホームディレクトリを選択します

ScriptMainTab.title.temp.folder=一時フォルダのディレクトリ

ScriptMainTab.msg.select.temp.folder=一時フォルダのディレクトリを選択します

ScriptMainTab.title.engine.home=エンジンのホームディレクトリ

ScriptMainTab.msg.select.engine.home=エンジンのホームディレクトリを選択します

ScriptMainTab.msg.select.report.file=レポートファイルを選択します

ScriptMainTab.button.text.search=検索...

ScriptMainTab.button.text.variables=変数...

ScriptMainTab.msg.open.target.file=完了時に生成ファイルを開きます

ScriptMainTab.msg.use.default.engine.home=デフォルトのエンジンのホームを使用します
