ScriptMainTab.title.report=기본

ScriptMainTab.msg.report.file.name=보고서 파일 이름

ScriptMainTab.msg.eclipse.home=Eclipse 홈

ScriptMainTab.msg.engine.home=엔진 홈

ScriptMainTab.msg.temp.folder=임시 폴더

ScriptMainTab.msg.debug.type=디버그 형식

ScriptMainTab.msg.task.type=작업 형식

ScriptMainTab.msg.output=결과

ScriptMainTab.msg.format=형식:

ScriptMainTab.msg.debug.type.all=모두

ScriptMainTab.msg.debug.type.java=Java
ScriptMainTab.msg.debug.type.script=Java Script
ScriptMainTab.msg.task.type.run.and.render=실행 및 렌더링

ScriptMainTab.msg.task.type.run=실행

ScriptMainTab.msg.task.type.render=렌더링

ScriptMainTab.msg.task.type.run.plus.render=실행 + 렌더링

ScriptMainTab.error.msg.no.eclipse.home=Eclipse 홈이 지정되지 않았습니다.

ScriptMainTab.error.msg.nonexist.eclipse.home=Eclipse 홈이 존재하지 않습니다.

ScriptMainTab.error.msg.invalid.eclipse.home=Eclipse 홈은 디렉터리여야 합니다.

ScriptMainTab.error.msg.no.engine.home=엔진 홈이 지정되지 않았습니다.

ScriptMainTab.error.msg.nonexist.engine.home=엔진 홈이 존재하지 않습니다.

ScriptMainTab.error.msg.invalid.engine.home=엔진 홈은 디렉터리여야 합니다.

ScriptMainTab.error.msg.no.temp.folder=임시 폴더가 지정되지 않았습니다.

ScriptMainTab.error.msg.nonexist.temp.folder=임시 폴더가 존재하지 않습니다.

ScriptMainTab.error.msg.invalid.temp.folder=임시 폴더는 디렉터리여야 합니다.

ScriptMainTab.error.msg.no.report.file=보고서 파일이 지정되지 않았습니다.

ScriptMainTab.error.msg.nonexist.report.file=보고서 파일이 존재하지 않습니다.

ScriptMainTab.error.msg.invalid.report.file=선택한 파일이 올바른 보고서 디자인 파일이 아닙니다.

ScriptMainTab.error.msg.invalid.document.file=선택한 파일이 올바른 보고서 문서 파일이 아닙니다.

ScriptMainTab.title.eclipse.home=Eclipse 홈 디렉터리

ScriptMainTab.msg.select.eclipse.home=Eclipse 홈 디렉터리 선택

ScriptMainTab.title.temp.folder=임시 폴더 디렉터리

ScriptMainTab.msg.select.temp.folder=임시 폴더 디렉터리 선택

ScriptMainTab.title.engine.home=엔진 홈 디렉터리

ScriptMainTab.msg.select.engine.home=엔진 홈 디렉터리 선택

ScriptMainTab.msg.select.report.file=보고서 파일 선택

ScriptMainTab.button.text.search=검색...

ScriptMainTab.button.text.variables=변수...

ScriptMainTab.msg.open.target.file=완료되면 생성된 파일 열기

ScriptMainTab.msg.use.default.engine.home=기본 엔진 홈 사용
