ScriptMainTab.title.report=Principal

ScriptMainTab.msg.report.file.name=Nom du fichier d'état

ScriptMainTab.msg.eclipse.home=Racine Eclipse

ScriptMainTab.msg.engine.home=Racine Engine

ScriptMainTab.msg.temp.folder=Dossier temp

ScriptMainTab.msg.debug.type=Type de débogage

ScriptMainTab.msg.task.type=Type de tâche

ScriptMainTab.msg.output=Sortie

ScriptMainTab.msg.format=Format :

ScriptMainTab.msg.debug.type.all=Tous

ScriptMainTab.msg.debug.type.java=Java
ScriptMainTab.msg.debug.type.script=Java Script
ScriptMainTab.msg.task.type.run.and.render=Exécution et rendu

ScriptMainTab.msg.task.type.run=Exécution

ScriptMainTab.msg.task.type.render=Rendu

ScriptMainTab.msg.task.type.run.plus.render=Exécution + Rendu

ScriptMainTab.error.msg.no.eclipse.home=La racine Eclipse n'est pas spécifiée.

ScriptMainTab.error.msg.nonexist.eclipse.home=La racine Eclipse n'existe pas.

ScriptMainTab.error.msg.invalid.eclipse.home=La racine Eclipse doit être un répertoire.

ScriptMainTab.error.msg.no.engine.home=La racine Engine n'est pas spécifiée.

ScriptMainTab.error.msg.nonexist.engine.home=La racine Engine n'existe pas.

ScriptMainTab.error.msg.invalid.engine.home=La racine Engine doit être un répertoire.

ScriptMainTab.error.msg.no.temp.folder=Le dossier temp n'est pas spécifié.

ScriptMainTab.error.msg.nonexist.temp.folder=Le dossier temp n'existe pas.

ScriptMainTab.error.msg.invalid.temp.folder=Le dossier temp doit être un répertoire.

ScriptMainTab.error.msg.no.report.file=Le fichier d'état n'est pas spécifié.

ScriptMainTab.error.msg.nonexist.report.file=Le fichier d'état n'existe pas.

ScriptMainTab.error.msg.invalid.report.file=Le fichier sélectionné n'est pas un fichier du modèle d'état valide.

ScriptMainTab.error.msg.invalid.document.file=Le fichier sélectionné n'est pas un état valide.

ScriptMainTab.title.eclipse.home=Répertoire racine Eclipse

ScriptMainTab.msg.select.eclipse.home=Sélectionner un répertoire racine Eclipse

ScriptMainTab.title.temp.folder=Répertoire du dossier temp

ScriptMainTab.msg.select.temp.folder=Sélectionner un répertoire du dossier temp

ScriptMainTab.title.engine.home=Répertoire racine Engine

ScriptMainTab.msg.select.engine.home=Sélectionner un répertoire racine Engine

ScriptMainTab.msg.select.report.file=Sélectionner un fichier d'état

ScriptMainTab.button.text.search=Rechercher...

ScriptMainTab.button.text.variables=Variables...

ScriptMainTab.msg.open.target.file=Une fois terminé, ouvrir le fichier généré

ScriptMainTab.msg.use.default.engine.home=Utiliser la racine du moteur par défaut
