#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=BIRT Report
script.debug=Informe

LaunchActionSet.label=D&epurar informe

Script.source.locator=Localizador de fuente de script de informe

Debug.jsEditor=Editor de JavaScript para depuración de informe

javaSourceLocatorName=Java Source Locator
Watch.label=Añadir a Vigilar

ReportActionSet=Conjunto de acciones de informe

Run=Ejecuta&r

ScriptLaunchShortcut.label=Informe

DebugReportLaunchShortcut.description=Depurar un informe

EnableBreakpoint.label=Activar punto de interrupción

ToggleBreakpoint.label=Alternar punto de interrupción

Action.DebugReport=Depurar informe

Menu.Report=Informe