#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=BIRT Report
script.debug=보고서

LaunchActionSet.label=디버그 보고서(&E)

Script.source.locator=보고서 스크립트 원본 로케이터

Debug.jsEditor=보고서 디버그 JavaScript 편집기

javaSourceLocatorName=Java Source Locator
Watch.label=조사식에 추가

ReportActionSet=보고서 작업 집합

Run=실행(&R)

ScriptLaunchShortcut.label=보고서

DebugReportLaunchShortcut.description=보고서 디버그

EnableBreakpoint.label=중단점 사용

ToggleBreakpoint.label=중단점 전환

Action.DebugReport=디버그 보고서

Menu.Report=보고서