#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=BIRT Report
script.debug=レポート

LaunchActionSet.label=レポートのデバッグ(&E)

Script.source.locator=レポートスクリプトのソースロケータ

Debug.jsEditor=レポートデバッグ JavaScript エディタ

javaSourceLocatorName=Java Source Locator
Watch.label=ウォッチに追加

ReportActionSet=レポートのアクションセット

Run=実行(&R)

ScriptLaunchShortcut.label=レポート

DebugReportLaunchShortcut.description=レポートのデバッグ

EnableBreakpoint.label=ブレークポイントの有効化

ToggleBreakpoint.label=ブレークポイントの切り替え

Action.DebugReport=デバッグレポート

Menu.Report=レポート