#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=BIRT Report
script.debug=报表

LaunchActionSet.label=调试报表(&E)

Script.source.locator=报表脚本源定位器

Debug.jsEditor=报表调试 JavaScript 编辑器

javaSourceLocatorName=Java Source Locator
Watch.label=添加以观察

ReportActionSet=报表操作集

Run=运行(&R)

ScriptLaunchShortcut.label=报表

DebugReportLaunchShortcut.description=调试报表

EnableBreakpoint.label=启用断点

ToggleBreakpoint.label=切换断点

Action.DebugReport=调试报表

Menu.Report=报表