#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=BIRT Report
script.debug=Etat

LaunchActionSet.label=Débogu&er le rapport

Script.source.locator=Localisateur de source Script d'état

Debug.jsEditor=Editeur JavaScript de débogage d'état

javaSourceLocatorName=Java Source Locator
Watch.label=Ajouter pour suivi

ReportActionSet=Jeu d'actions d'état

Run=Exécute&r

ScriptLaunchShortcut.label=Etat

DebugReportLaunchShortcut.description=Déboguer un état

EnableBreakpoint.label=Activer point d'arrêt

ToggleBreakpoint.label=Basculer point d'arrêt

Action.DebugReport=Déboguer le rapport

Menu.Report=Rapport