birt.web.category.name=Business Intelligence 및 보고 도구(&B)

birt.web.project.name=BIRT 런타임이 포함된 웹 프로젝트

birt.web.project.description=BIRT 런타임 구성 요소를 포함한 웹 프로젝트 생성

birt.web.actionsets.description=BIRT 웹 프로젝트 작업

create.birt.web.module=BIRT 웹 모듈 생성

BIRT_FACET_LABEL=BIRT 보고 런타임 구성 요소

BIRT_FACET_DESCRIPTION=BIRT 보고 런타임 구성 요소

BIRT_FACET_TEMPLATE_LABEL=BIRT 보고 웹 프로젝트

BIRT_FACET_TEMPLATE_DESCRIPTION=BIRT 보고 런타임 구성 요소가 포함된 웹 프로젝트

JSP_New_context_type_Extension_Element.name=BIRT 태그를 사용한 새 JSP

JSP_Tag_context_type_Extension_Element.name=새 BIRT JSP 태그

BirtResourcesDefinition= BIRT 웹 응용 프로그램 리소스 정의

birt.action.importruntime.name=BIRT 런타임 구성 요소 가져오기(&B)...


plugin.version=4.3.1
