birt.web.category.name=&Herramientas de generación de informe para la actividad empresarial

birt.web.project.name=Proyecto Web con tiempo de ejecución de BIRT

birt.web.project.description=Crear un proyecto web que contenga un componente de tiempo de ejecución BIRT

birt.web.actionsets.description=Acciones para proyecto web BIRT

create.birt.web.module=Crear un módulo web BIRT

BIRT_FACET_LABEL=Componente de tiempo de ejecución de generación de informes BIRT

BIRT_FACET_DESCRIPTION=Componente de tiempo de ejecución de generación de informes BIRT

BIRT_FACET_TEMPLATE_LABEL=Proyecto web de generación de informes BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Proyecto web con el componente de tiempo de ejecución de generación de informes BIRT

JSP_New_context_type_Extension_Element.name=Nuevo JSP con etiqueta BIRT

JSP_Tag_context_type_Extension_Element.name=Nueva etiqueta JSP BIRT

BirtResourcesDefinition= Definición de recursos de la aplicación web BIRT

birt.action.importruntime.name=Importar componente de tiempo de ejecución de &BIRT...


plugin.version=4.4.0
