birt.web.category.name=商业智能及报表工具(&B)

birt.web.project.name=具有 BIRT 运行时的 Web 项目

birt.web.project.description=创建包含 BIRT 运行时组件的 web 项目

birt.web.actionsets.description=对 BIRT Web 项目的操作

create.birt.web.module=创建 BIRT Web 模块

BIRT_FACET_LABEL=BIRT 报告运行时组件

BIRT_FACET_DESCRIPTION=BIRT 报告运行时组件

BIRT_FACET_TEMPLATE_LABEL=BIRT 报告 Web 项目

BIRT_FACET_TEMPLATE_DESCRIPTION=具有 BIRT 报告运行时组件的 Web 项目

JSP_New_context_type_Extension_Element.name=新建具有 BIRT 标记的 JSP

JSP_Tag_context_type_Extension_Element.name=新建 BIRT JSP 标记

BirtResourcesDefinition= BIRT Web 应用程序资源定义

birt.action.importruntime.name=导入 BIRT 运行时组件(&B)...


plugin.version=4.4.0
