birt.web.category.name=ビジネスインテリジェンスとレポート作成ツール(&B)

birt.web.project.name=BIRT ランタイム付き Web プロジェクト

birt.web.project.description=BIRT ランタイムコンポーネントを含む Web プロジェクトを作成します。

birt.web.actionsets.description=BIRT Web プロジェクトでの操作

create.birt.web.module=BIRT Web モジュールの作成

BIRT_FACET_LABEL=BIRT レポート作成ランタイムコンポーネント

BIRT_FACET_DESCRIPTION=BIRT レポート作成ランタイムコンポーネント

BIRT_FACET_TEMPLATE_LABEL=BIRT レポート作成 Web プロジェクト

BIRT_FACET_TEMPLATE_DESCRIPTION=BIRT レポート作成ランタイムコンポーネントの Web プロジェクト

JSP_New_context_type_Extension_Element.name=新規 JSP (BIRT タグを使用)

JSP_Tag_context_type_Extension_Element.name=新規 BIRT JSP タグ

BirtResourcesDefinition= BIRT Web アプリケーションリソースの定義

birt.action.importruntime.name=BIRT ランタイムコンポーネントのインポート(&B)...


plugin.version=4.4.0
