birt.web.category.name=Outils de reporting et de Business Intelligence
birt.web.project.name=Projet Web 
birt.web.project.description=Créer un projet Web contenant le composant d'exécution BIRT
birt.web.actionsets.description=Actions pour le projet Web BIRT
create.birt.web.module=Créer un module Web BIRT

BIRT_FACET_LABEL=Composant d'exécution de reporting BIRT
BIRT_FACET_DESCRIPTION=Composant d'exécution de reporting BIRT
BIRT_FACET_TEMPLATE_LABEL=Projet Web de reporting BIRT

JSP_New_context_type_Extension_Element.name=Nouveau JSP avec balise BIRT
JSP_Tag_context_type_Extension_Element.name=Nouvelle balise JSP BIRT

BirtResourcesDefinition= Définition des ressources d'application Web BIRT

birt.action.importruntime.name=Importer le composant d'exécution BIRT...
