birt.web.category.name=&Business Intelligence & Reporting Tools

birt.web.project.name=Webprojekt mit BIRT-Runtime

birt.web.project.description=Ein Webprojekt mit der BIRT Runtime-Komponente erstellen

birt.web.actionsets.description=Aktionen für BIRT-Webprojekt

create.birt.web.module=BIRT-Webmodul erstellen

BIRT_FACET_LABEL=BIRT Reporting-Runtime-Komponente

BIRT_FACET_DESCRIPTION=BIRT Reporting-Runtime-Komponente

BIRT_FACET_TEMPLATE_LABEL=BIRT Reporting-Webprojekt

BIRT_FACET_TEMPLATE_DESCRIPTION=Webprojekt mit der BIRT Reporting-Runtime-Komponente

JSP_New_context_type_Extension_Element.name=Neue JSP mit BIRT-Tag

JSP_Tag_context_type_Extension_Element.name=Neuer BIRT-JSP-Tag

BirtResourcesDefinition= Ressourcendefinition für BIRT-Webanwendung

birt.action.importruntime.name=&BIRT-Runtime-Komponente importieren...


plugin.version=4.4.0
