birt.web.category.name=Outils de reporting et de &Business Intelligence

birt.web.project.name=Projet Web avec exécution BIRT

birt.web.project.description=Créer un projet Web contenant le composant d'exécution BIRT

birt.web.actionsets.description=Actions pour le projet Web BIRT

create.birt.web.module=Créer un module Web BIRT

BIRT_FACET_LABEL=Composant d'exécution de reporting BIRT

BIRT_FACET_DESCRIPTION=Composant d'exécution de reporting BIRT

BIRT_FACET_TEMPLATE_LABEL=Projet Web de reporting BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Projet Web avec le composant d'exécution de reporting BIRT

JSP_New_context_type_Extension_Element.name=Nouveau JSP avec balise BIRT

JSP_Tag_context_type_Extension_Element.name=Nouvelle balise JSP BIRT

BirtResourcesDefinition= Définition des ressources d'application Web BIRT

birt.action.importruntime.name=Importer le composant d'exécution &BIRT...


plugin.version=4.4.0
