# Localized messages for the oda-jdbc. Messages here give 
# the text of oda-jdbc exceptions.

###########################################################

#ODA-JDBC error code
odajdbc.CannotCloseConn=Verbindung kann nicht geschlossen werden.

odajdbc.ConnCommitError=Es ist ein Datenbankzugriffsfehler aufgetreten, oder ein Verbindungsobjekt befindet sich im Modus zum automatischen Ausführen.

odajdbc.CannotGetConnMetaData=Verbindungsmetadaten können nicht abgerufen werden.

odajdbc.CannotGetConn=Verbindung konnte nicht hergestellt werden.

odajdbc.ConnRollbackError=Verbindungs-Rollback-Fehler.

odajdbc.GetConnectionError=Fehler beim Aufbau der Verbindung, {0}.

odajdbc.CannotGetMaxStatements=Höchstanzahl der Anweisungen kann nicht aus den Datenbankmetadaten abgerufen werden.

odajdbc.CannotGetMaxConnections=Höchstanzahl der Verbindungen kann nicht aus den Datenbankmetadaten abgerufen werden.

odajdbc.CannotGetDatabaseMajorVersion=Hauptversion der Datenbank kann nicht abgerufen werden.

odajdbc.CannotGetDatabaseMinorVersion=Zusatzversion der Datenbank kann nicht abgerufen werden

odajdbc.CannotGetDataSourceProductName=Produktname der Datenquelle kann nicht abgerufen werden.

odajdbc.CannotGetDataSourceProductVersion=Produktversion der Datenquelle kann nicht abgerufen werden.

odajdbc.CannotGetSQLStateType=SQL-Statustyp kann nicht abgerufen werden.

odajdbc.CannotParseURL=Mit dem ausgewählten Treiber kann der angegebene URL nicht analysiert werden.

odajdbc.CannotParseJNDI=Mit dem ausgewählten Treiber kann die angegebene URL für die JNDI-Datenquelle nicht analysiert werden.

odajdbc.NoSuitableDriver=Kein passender Treiber.

odajdbc.CannotGetParameterCount=Parameteranzahl kann nicht abgerufen werden.

odajdbc.CannotGetParameterMode=Parametermodus kann nicht abgerufen werden.

odajdbc.CannotGetParameterType=Parametertyp kann nicht abgerufen werden.

odajdbc.CannotGetParameterTypeName=Name des Parametertyps kann nicht abgerufen werden.

odajdbc.CannotGetPrecision=Präzision kann nicht abgerufen werden.

odajdbc.CannotGetScale=Skalierung kann nicht abgerufen werden.

odajdbc.CannotDetermineSupportForNull=Es kann nicht festgestellt werden, ob Nullwerte für den Parameter zulässig sind.

odajdbc.CannotGetResultSet=Ergebnis kann nicht abgerufen werden.

odajdbc.CannotGetResultSetMetadata=Ergebnismetadaten können nicht abgerufen werden.

odajdbc.CannotCloseResultSet=Ergebnis kann nicht geschlossen werden.

odajdbc.CursorDownError=Kann nicht in nächste Zeile im Ergebnis verschoben werden.

odajdbc.ResultSetCannotGetStringValue=Zeichenfolgewert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetIntValue=Ganzzahlwert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetDoubleValue=Double-Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetBigDecimalValue=BigDecimal-Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetDateValue=Datumswert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetTimeValue=Zeitwert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetTimeStampValue=Timestamp-Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetBlobValue=BLOB-Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetClobValue=CLOB-Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotGetBooleanValue=Boolescher Wert in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetDetermineNull=Wert von "isNull" in Ergebnis kann nicht abgerufen werden.

odajdbc.ResultSetCannotFindColumn=Keine Spalten in Ergebnis gefunden.

odajdbc.CannotGetColumnCount=Spaltenanzahl kann nicht abgerufen werden.

odajdbc.CannotGetColumnName=Spaltenname kann nicht abgerufen werden.

odajdbc.CannotGetColumnLabel=Spaltenbeschriftung kann nicht abgerufen werden.

odajdbc.CannotGetColumnType=Spaltentyp kann nicht abgerufen werden.

odajdbc.CannotGetColumnTypeName=Name des Spaltentyps kann nicht abgerufen werden.

odajdbc.CannotGetColumnDisplaySize=Anzeigegröße der Spalten kann nicht abgerufen werden.

odajdbc.CannotGetResultSetMetaDataPrecision=Präzision für Ergebnismetadaten kann nicht abgerufen werden.

odajdbc.CannotGetResultSetMetaDataScale=Skalierung für Ergebnismetadaten kann nicht abgerufen werden.

odajdbc.CannotDetermineColumnSupportForNull=Unterstützung von Nullwerten für Spalte kann nicht festgestellt werden.

odajdbc.StatementCannotPrepared=Fehler bei der Vorbereitung einer SQL-Anweisung.

odajdbc.CannotGetMetaData=Ergebnismetadaten können nicht abgerufen werden.

odajdbc.CannotClosePreparedStatement=Vorbereitete Anweisung kann nicht geschlossen werden.

odajdbc.CannotGetPreparedStatementMetadata=Metadaten für vorbereitete Anweisung können nicht abgerufen werden.

odajdbc.ResultSetCannotReturn=SQL-Anweisung gibt kein Ergebnisobjekt zurück.

odajdbc.QueryExecuteFail=SQL-Anweisung gibt kein Ergebnisobjekt und keine Aktualisierungsanzahl zurück.

odajdbc.InvalidStoredPrecedure=Ungültige Anweisung für gespeicherten Prozeduraufruf.

odajdbc.PrepareStatement.CannotSetIntValue=Ganzzahlwert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetDoubleValue=Double-Wert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetBigDecimalValue=BigDecimal-Wert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetStringValue=Zeichenfolgewert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetDateValue=Datumswert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetTimeValue=Zeitwert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetTimestampValue=Timestamp-Wert des Parameters für vorbereitete Anweisung kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetBooleanValue=Boolescher Wert preparedStatement kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotSetNullValue=Null-Wert preparedStatement kann nicht festgelegt werden.

odajdbc.PrepareStatement.CannotGetParameterType=Parametertyp kann nicht aus Parametermetadaten abgerufen werden.

odajdbc.CannotGetParameterMetadata=Parametermetadaten können nicht abgerufen werden.

odajdbc.ClearParametersError=Fehler beim Löschen des aktuellen Parameterwerts.

odajdbc.missedUrlAndJndi=GetConnection: url und jndiNameUrl weisen beide den Wert 'Null' auf.

odajdbc.error.emptyDriverClass=GetConnection: Der Treiberklassenname weist den Wert 'Null' auf.

#used in assert error
odajdbc.driver.ConnNotOpen=Verbindung nicht hergestellt.

odajdbc.driver.DriverMissingProperties=Fehlende Eigenschaften in Connection.open(Properties).

odajdbc.driver.ParameterMetadataCannotNull=ParameterMetaData darf nicht Null sein.

odajdbc.driver.ResultSetCannotNull=ResultSet darf nicht Null sein.

odajdbc.driver.ResultSetMetadataCannotNull=ResultSetMetaData darf nicht Null sein.

odajdbc.driver.StatementCannotNull=Anweisung muss für diesen Vorgang vorbereitet werden.

odajdbc.CannotGetMaxQueries=MaxStatements kann nicht von zugrunde liegender JDBC-Verbindung abgerufen werden.

odajdbc.CannotSetQueryTimeout=Zeitüberschreitung der Abfrage kann für zugrunde liegende JDBC-Verbindung nicht festgelegt werden.

odajdbc.BadQueryProperty=Abfrageeigenschaft nicht unterstützt: {0}.

odajdbc.CannotLoadDriverClass=JDBC-Treiberklasse kann nicht geladen werden: {0}.

odajdbc.CannotInstantiateDriverClass=Instanz von JDBC-Treiberklasse kann nicht erstellt werden: {0}.

odajdbc.CannotInstantiateFactory=Die in der Erweiterung für Treiberklasse "{1}" definierte Instanz für die Verbindungs-Factory-Klasse "{0}" kann nicht erstellt werden.

odajdbc.jndi.InvalidJndiResource=JNDI-Ressourcentyp ({0}) gefunden; javax.sql.DataSource-Typ erwartet.

odajdbc.testfail=Test fehlgeschlagen