# Localized messages for the oda-jdbc. Messages here give 
# the text of oda-jdbc exceptions.

###########################################################

#ODA-JDBC error code
odajdbc.CannotCloseConn=接続を閉じる際にエラーが発生しました。

odajdbc.ConnCommitError=データベースへアクセスする際にエラーが発生したか、接続オブジェクトが自動コミットモードになっています。

odajdbc.CannotGetConnMetaData=接続メタデータを取得できません。

odajdbc.CannotGetConn=接続を取得する際にエラーが発生しました。

odajdbc.ConnRollbackError=接続をロールバックする際にエラーが発生しました。

odajdbc.GetConnectionError=接続 {0} を取得できません。

odajdbc.CannotGetMaxStatements=データベースのメタデータから、最大数の文を取得できません。

odajdbc.CannotGetMaxConnections=データベースのメタデータから、最大数の接続を取得できません。

odajdbc.CannotGetDatabaseMajorVersion=データベースのメジャーバージョンを取得できません。

odajdbc.CannotGetDatabaseMinorVersion=データベースのマイナーバージョンを取得できません。

odajdbc.CannotGetDataSourceProductName=データソースの製品の名前を取得できません。

odajdbc.CannotGetDataSourceProductVersion=データソースの製品のバージョンを取得できません。

odajdbc.CannotGetSQLStateType=SQL state の型を取得できません。

odajdbc.CannotParseURL=このドライバでは、指定された URL を解析できません。

odajdbc.CannotParseJNDI=このドライバでは、JNDIデータソースの指定された URL を解析できません。

odajdbc.NoSuitableDriver=適したドライバがありません。

odajdbc.CannotGetParameterCount=パラメタ数を取得できません。

odajdbc.CannotGetParameterMode=パラメタのモードを取得できません。

odajdbc.CannotGetParameterType=パラメタの型を取得できません。

odajdbc.CannotGetParameterTypeName=パラメタの型名を取得できません。

odajdbc.CannotGetPrecision=精度を取得できません。

odajdbc.CannotGetScale=スケールを取得できません。

odajdbc.CannotDetermineSupportForNull=パラメタに null を指定できるかどうかを識別できません。

odajdbc.CannotGetResultSet=結果セットを取得できません。

odajdbc.CannotGetResultSetMetadata=結果セットのメタデータを取得できません。

odajdbc.CannotCloseResultSet=結果セットを閉じることができません。

odajdbc.CursorDownError=結果セットの次の行に移動できません。

odajdbc.ResultSetCannotGetStringValue=結果セットの String 値を取得できません。

odajdbc.ResultSetCannotGetIntValue=結果セットの Integer 値を取得できません。

odajdbc.ResultSetCannotGetDoubleValue=結果セットの Double 値を取得できません。

odajdbc.ResultSetCannotGetBigDecimalValue=結果セットの BigDecimal 値を取得できません。

odajdbc.ResultSetCannotGetDateValue=結果セットの Date 値を取得できません。

odajdbc.ResultSetCannotGetTimeValue=結果セットの Time 値を取得できません。

odajdbc.ResultSetCannotGetTimeStampValue=結果セットの Timestamp 値を取得できません。

odajdbc.ResultSetCannotGetBlobValue=結果セットの BLOB 値を取得できません。

odajdbc.ResultSetCannotGetClobValue=結果セットの CLOB 値を取得できません。

odajdbc.ResultSetCannotGetBooleanValue=結果セットの論理値を取得できません。

odajdbc.ResultSetDetermineNull=結果セットの isNull 値を識別できません。

odajdbc.ResultSetCannotFindColumn=結果セットに列が見つかりません。

odajdbc.CannotGetColumnCount=列の数を取得できません。

odajdbc.CannotGetColumnName=列の名前を取得できません。

odajdbc.CannotGetColumnLabel=列のラベルを取得できません。

odajdbc.CannotGetColumnType=列の型を取得できません。

odajdbc.CannotGetColumnTypeName=列の型名を取得できません。

odajdbc.CannotGetColumnDisplaySize=列の表示サイズを取得できません。

odajdbc.CannotGetResultSetMetaDataPrecision=結果セットのメタデータの精度を取得できません。

odajdbc.CannotGetResultSetMetaDataScale=結果セットのメタデータのスケールを取得できません。

odajdbc.CannotDetermineColumnSupportForNull=列に null 値を指定できるかどうかを識別できません。

odajdbc.StatementCannotPrepared=SQL 文を記述する際にエラーが発生しました。

odajdbc.CannotGetMetaData=結果セットのメタデータを取得できません。

odajdbc.CannotClosePreparedStatement=preparedStatement を閉じることができません。

odajdbc.CannotGetPreparedStatementMetadata=preparedStatement メタデータを取得できません。

odajdbc.ResultSetCannotReturn=この SQL 文からは ResultSet オブジェクトが返されません。

odajdbc.QueryExecuteFail=この SQL 文からは ResultSet オブジェクトまたは更新数が返されません。

odajdbc.InvalidStoredPrecedure=ストアドプロシジャの呼び出し文が無効です。

odajdbc.PrepareStatement.CannotSetIntValue=preparedStatement パラメタの int 値を設定できません。

odajdbc.PrepareStatement.CannotSetDoubleValue=preparedStatement パラメタの Double 値を設定できません。

odajdbc.PrepareStatement.CannotSetBigDecimalValue=preparedStatement パラメタの BigDecimal 値を設定できません。

odajdbc.PrepareStatement.CannotSetStringValue=preparedStatement パラメタの String 値を設定できません。

odajdbc.PrepareStatement.CannotSetDateValue=preparedStatement パラメタの Date 値を設定できません。

odajdbc.PrepareStatement.CannotSetTimeValue=preparedStatement パラメタの Time 値を設定できません。

odajdbc.PrepareStatement.CannotSetTimestampValue=preparedStatement パラメタの Timestamp 値を設定できません。

odajdbc.PrepareStatement.CannotSetBooleanValue=preparedStatement の論理値を設定できません。

odajdbc.PrepareStatement.CannotSetNullValue=preparedStatement の NULL 値を設定できません。

odajdbc.PrepareStatement.CannotGetParameterType=パラメタのメタデータからパラメタの型を取得できません。

odajdbc.CannotGetParameterMetadata=パラメタのメタデータを取得できません。

odajdbc.ClearParametersError=現在のパラメタ値をクリアする際にエラーが発生しました。

odajdbc.missedUrlAndJndi=GetConnection: url と jndiNameUrl がいずれも NULL 値です。

odajdbc.error.emptyDriverClass=GetConnection : ドライバクラス名が NULL 値です。

#used in assert error
odajdbc.driver.ConnNotOpen=接続が開いていません。

odajdbc.driver.DriverMissingProperties=Connection.open(Properties) のプロパティが見つかりません。

odajdbc.driver.ParameterMetadataCannotNull=ParameterMetaData は null にできません。

odajdbc.driver.ResultSetCannotNull=ResultSet は null にできません。

odajdbc.driver.ResultSetMetadataCannotNull=ResultSetMetaData は null にできません。

odajdbc.driver.StatementCannotNull=この操作を実行する前に、文を記述する必要があります。

odajdbc.CannotGetMaxQueries=基本の JDBC 接続から MaxStatements を取得できません。

odajdbc.CannotSetQueryTimeout=基本の JDBC 文にクエリのタイムアウトを設定できません。

odajdbc.BadQueryProperty=クエリのプロパティはサポートされていません : {0}

odajdbc.CannotLoadDriverClass=JDBC ドライバクラスを読み込めません : {0}

odajdbc.CannotInstantiateDriverClass=JDBC ドライバクラスのインスタンスを作成できません : {0}

odajdbc.CannotInstantiateFactory=ドライバクラス "{1}" のエクステンションに定義されている、接続ファクトリクラス "{0}" のインスタンスを作成できません。

odajdbc.jndi.InvalidJndiResource=JNDI のリソースタイプ ({0}) が見つかりましたが、タイプ javax.sql.DataSource が必要です。

odajdbc.testfail=テストでエラーが発生しました。