# Localized messages for the oda-jdbc. Messages here give 
# the text of oda-jdbc exceptions.

###########################################################

#ODA-JDBC error code
odajdbc.CannotCloseConn=未能关闭连接。

odajdbc.ConnCommitError=发生数据库访问错误，或者连接对象处于自动提交模式。

odajdbc.CannotGetConnMetaData=无法获得连接元数据。

odajdbc.CannotGetConn=未能获得连接。

odajdbc.ConnRollbackError=连接回滚错误。

odajdbc.GetConnectionError=获取连接时出错，{0}。

odajdbc.CannotGetMaxStatements=无法从数据库元数据中获得最大数量的语句。

odajdbc.CannotGetMaxConnections=无法从数据库元数据中获得最大数量的连接。

odajdbc.CannotGetDatabaseMajorVersion=无法获得数据库主要版本。

odajdbc.CannotGetDatabaseMinorVersion=无法获得数据库次要版本。

odajdbc.CannotGetDataSourceProductName=无法获得数据源产品名称。

odajdbc.CannotGetDataSourceProductVersion=无法获得数据源产品版本。

odajdbc.CannotGetSQLStateType=无法获得 SQL 状态类型。

odajdbc.CannotParseURL=选定的驱动程序无法分析给定的 url。

odajdbc.CannotParseJNDI=选择的驱动程序无法分析给定的 JNDI 数据源 URL。

odajdbc.NoSuitableDriver=没有适合的驱动程序。

odajdbc.CannotGetParameterCount=无法获得参数计数。

odajdbc.CannotGetParameterMode=无法获得参数模式。

odajdbc.CannotGetParameterType=无法获得参数类型。

odajdbc.CannotGetParameterTypeName=无法获得参数类型名称。

odajdbc.CannotGetPrecision=无法获得精度。

odajdbc.CannotGetScale=无法获得进位制。

odajdbc.CannotDetermineSupportForNull=无法确定参数是否可为空。

odajdbc.CannotGetResultSet=无法获取结果集。

odajdbc.CannotGetResultSetMetadata=无法获取结果集元数据。

odajdbc.CannotCloseResultSet=无法关闭结果集。

odajdbc.CursorDownError=无法下移至结果集内的下一行。

odajdbc.ResultSetCannotGetStringValue=无法在结果集内获得字符串值。

odajdbc.ResultSetCannotGetIntValue=无法在结果集内获得整数值。

odajdbc.ResultSetCannotGetDoubleValue=无法在结果集内获得双精度值。

odajdbc.ResultSetCannotGetBigDecimalValue=无法在结果集内获得大十进制值。

odajdbc.ResultSetCannotGetDateValue=无法在结果集内获得日期值。

odajdbc.ResultSetCannotGetTimeValue=无法在结果集内获得时间值。

odajdbc.ResultSetCannotGetTimeStampValue=无法在结果集内获得时间戳值。

odajdbc.ResultSetCannotGetBlobValue=无法在结果集内获得 BLOB 值。

odajdbc.ResultSetCannotGetClobValue=无法在结果集内获得 CLOB 值。

odajdbc.ResultSetCannotGetBooleanValue=无法获得结果集内的布尔值。

odajdbc.ResultSetDetermineNull=无法在结果集内确定 isNull 值。

odajdbc.ResultSetCannotFindColumn=无法在结果集内找到列。

odajdbc.CannotGetColumnCount=无法获得列计数。

odajdbc.CannotGetColumnName=无法获得列名称。

odajdbc.CannotGetColumnLabel=无法获得列标签。

odajdbc.CannotGetColumnType=无法获得列类型。

odajdbc.CannotGetColumnTypeName=无法获得列类型名称。

odajdbc.CannotGetColumnDisplaySize=无法获得列显示大小。

odajdbc.CannotGetResultSetMetaDataPrecision=无法获得结果集元数据精度。

odajdbc.CannotGetResultSetMetaDataScale=无法获得结果集元数据进位制。

odajdbc.CannotDetermineColumnSupportForNull=无法确定列是否支持空值。

odajdbc.StatementCannotPrepared=准备 SQL 语句时出错。

odajdbc.CannotGetMetaData=无法获取结果集元数据。

odajdbc.CannotClosePreparedStatement=无法关闭 preparedStatement。

odajdbc.CannotGetPreparedStatementMetadata=无法获得 preparedStatement 元数据。

odajdbc.ResultSetCannotReturn=SQL 语句不返回 ResultSet 对象。

odajdbc.QueryExecuteFail=SQL 语句不返回 ResultSet 对象或更新计数。

odajdbc.InvalidStoredPrecedure=存储过程调用语句无效。

odajdbc.PrepareStatement.CannotSetIntValue=无法将 preparedStatement 参数设置为整数值。

odajdbc.PrepareStatement.CannotSetDoubleValue=无法将 preparedStatement 参数设置为双精度值。

odajdbc.PrepareStatement.CannotSetBigDecimalValue=无法将 preparedStatement 参数设置为大十进制值。

odajdbc.PrepareStatement.CannotSetStringValue=无法将 preparedStatement 参数设置为字符串值。

odajdbc.PrepareStatement.CannotSetDateValue=无法将 preparedStatement 参数设置为日期值。

odajdbc.PrepareStatement.CannotSetTimeValue=无法将 preparedStatement 参数设置为时间值。

odajdbc.PrepareStatement.CannotSetTimestampValue=无法将 preparedStatement 参数设置为时间戳值。

odajdbc.PrepareStatement.CannotSetBooleanValue=无法设置 preparedStatement 布尔值。

odajdbc.PrepareStatement.CannotSetNullValue=无法设置 preparedStatement 空值。

odajdbc.PrepareStatement.CannotGetParameterType=无法从参数元数据中获得参数类型。

odajdbc.CannotGetParameterMetadata=无法检索参数元数据。

odajdbc.ClearParametersError=清除当前参数值时出错。

odajdbc.missedUrlAndJndi=GetConnection: url 和 jndiNameUrl 均为空值。

odajdbc.error.emptyDriverClass=GetConnection: 驱动程序类名称为空值。

#used in assert error
odajdbc.driver.ConnNotOpen=连接未打开。

odajdbc.driver.DriverMissingProperties=Connection.open(Properties) 缺少属性。

odajdbc.driver.ParameterMetadataCannotNull=ParameterMetaData 不能为空。

odajdbc.driver.ResultSetCannotNull=ResultSet 不能为空。

odajdbc.driver.ResultSetMetadataCannotNull=ResultSetMetaData 不能为空。

odajdbc.driver.StatementCannotNull=在执行此操作之前，需要准备语句。

odajdbc.CannotGetMaxQueries=无法通过基础 JDBC 连接获得 MaxStatements。

odajdbc.CannotSetQueryTimeout=无法在基础 JDBC 语句中设置查询超时。

odajdbc.BadQueryProperty=不支持查询属性: {0}。

odajdbc.CannotLoadDriverClass=无法加载 JDBC 驱动程序类: {0}。

odajdbc.CannotInstantiateDriverClass=无法创建 JDBC 驱动程序类的实例: {0}。

odajdbc.CannotInstantiateFactory=无法创建驱动程序类 "{1}" 的扩展中定义的连接工厂类 "{0}" 的实例。

odajdbc.jndi.InvalidJndiResource=找到 JNDI 资源类型({0})；需要 javax.sql.DataSource 类型。

odajdbc.testfail=测试失败