# Localized messages for the oda-jdbc. Messages here give 
# the text of oda-jdbc exceptions.

###########################################################

#ODA-JDBC error code
odajdbc.CannotCloseConn=Error al cerrar la conexión.

odajdbc.ConnCommitError=Se ha producido un error al acceder a la base de datos o un objeto de conexión está en modo de confirmación automática.

odajdbc.CannotGetConnMetaData=No se pueden obtener los metadatos de conexión.

odajdbc.CannotGetConn=Error al obtener la conexión.

odajdbc.ConnRollbackError=Error al restituir la conexión.

odajdbc.GetConnectionError=Ha ocurrido un error al intentar acceder a la conexión, {0}.

odajdbc.CannotGetMaxStatements=No se puede obtener el número máximo de sentencias de los metadatos de la base de datos.

odajdbc.CannotGetMaxConnections=No se puede obtener el número máximo de conexiones de los metadatos de la base de datos.

odajdbc.CannotGetDatabaseMajorVersion=No se puede obtener la versión principal de la base de datos.

odajdbc.CannotGetDatabaseMinorVersion=No se puede obtener la versión secundaria de la base de datos.

odajdbc.CannotGetDataSourceProductName=No se puede obtener el nombre de producto de la fuente de datos.

odajdbc.CannotGetDataSourceProductVersion=No se puede obtener la versión del producto de la fuente de datos.

odajdbc.CannotGetSQLStateType=No se puede obtener el tipo de estado de SQL.

odajdbc.CannotParseURL=El controlador seleccionado no puede analizar el url proporcionado.

odajdbc.CannotParseJNDI=El controlador seleccionado no puede analizar la URL de fuente de datos JNDI indicada.

odajdbc.NoSuitableDriver=Sin controlador adecuado.

odajdbc.CannotGetParameterCount=No se puede obtener el recuento de parámetros.

odajdbc.CannotGetParameterMode=No se puede obtener el modo de parámetro.

odajdbc.CannotGetParameterType=No se puede obtener el tipo de parámetro.

odajdbc.CannotGetParameterTypeName=No se puede obtener el nombre del tipo de parámetro.

odajdbc.CannotGetPrecision=No se puede obtener la precisión.

odajdbc.CannotGetScale=No se puede obtener la escala.

odajdbc.CannotDetermineSupportForNull=No se puede determinar si el parámetro es nulo.

odajdbc.CannotGetResultSet=No se puede obtener el grupo de resultados.

odajdbc.CannotGetResultSetMetadata=No se pueden obtener los metadatos del grupo de resultados.

odajdbc.CannotCloseResultSet=No se puede cerrar el grupo de resultados.

odajdbc.CursorDownError=No se puede bajar a la siguiente fila en el conjunto de resultados.

odajdbc.ResultSetCannotGetStringValue=No se puede obtener el valor de string en el conjunto de resultados.

odajdbc.ResultSetCannotGetIntValue=No se puede obtener el valor entero en el conjunto de resultados.

odajdbc.ResultSetCannotGetDoubleValue=No se puede obtener el valor doble en el conjunto de resultados.

odajdbc.ResultSetCannotGetBigDecimalValue=No se puede obtener el valor BigDecimal en el conjunto de resultados.

odajdbc.ResultSetCannotGetDateValue=No se puede obtener el valor de fecha en el conjunto de resultados.

odajdbc.ResultSetCannotGetTimeValue=No se puede obtener el valor de hora en el conjunto de resultados.

odajdbc.ResultSetCannotGetTimeStampValue=No se puede obtener el valor de fecha/hora en el conjunto de resultados.

odajdbc.ResultSetCannotGetBlobValue=No se puede obtener el valor BLOB en el conjunto de resultados.

odajdbc.ResultSetCannotGetClobValue=No se puede obtener el valor CLOB en el conjunto de resultados.

odajdbc.ResultSetCannotGetBooleanValue=No se puede obtener el valor booleano en el conjunto de resultados.

odajdbc.ResultSetDetermineNull=No se puede determinar el valor isNull en el conjunto de resultados.

odajdbc.ResultSetCannotFindColumn=No se puede encontrar ninguna columna en el conjunto de resultados.

odajdbc.CannotGetColumnCount=No se puede obtener un recuento de columnas.

odajdbc.CannotGetColumnName=No se puede obtener el nombre de columna.

odajdbc.CannotGetColumnLabel=No se puede obtener la etiqueta de columna.

odajdbc.CannotGetColumnType=No se puede obtener el tipo de columna.

odajdbc.CannotGetColumnTypeName=No se puede obtener el nombre del tipo de columna.

odajdbc.CannotGetColumnDisplaySize=No se puede obtener el tamaño de visualización de columna.

odajdbc.CannotGetResultSetMetaDataPrecision=No se puede obtener la precisión de los metadatos del conjunto de resultados.

odajdbc.CannotGetResultSetMetaDataScale=No se puede obtener la escala de los metadatos del conjunto de resultados.

odajdbc.CannotDetermineColumnSupportForNull=No se puede determinar si la columna admite valores nulos.

odajdbc.StatementCannotPrepared=Error al preparar la sentencia de SQL.

odajdbc.CannotGetMetaData=No se pueden obtener los metadatos del grupo de resultados.

odajdbc.CannotClosePreparedStatement=No se puede cerrar preparedStatement.

odajdbc.CannotGetPreparedStatementMetadata=No se pueden obtener los metadatos de preparedStatement.

odajdbc.ResultSetCannotReturn=La sentencia de SQL no devuelve un objeto ResultSet.

odajdbc.QueryExecuteFail=La sentencia de SQL no devuelve un objeto ResultSet ni un recuento de actualización.

odajdbc.InvalidStoredPrecedure=Sentencia de llamada de stored procedure no válida.

odajdbc.PrepareStatement.CannotSetIntValue=No se puede establecer el valor tipo int del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetDoubleValue=No se puede establecer el valor doble del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetBigDecimalValue=No se puede establecer el valor BigDecimal del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetStringValue=No se puede establecer el valor de string del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetDateValue=No se puede establecer el valor de fecha del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetTimeValue=No se puede establecer el valor de hora del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetTimestampValue=No se puede establecer el valor de fecha/hora del parámetro preparedStatement.

odajdbc.PrepareStatement.CannotSetBooleanValue=No se puede establecer el valor booleano de preparedStatement.

odajdbc.PrepareStatement.CannotSetNullValue=No se puede establecer el valor nulo de preparedStatement.

odajdbc.PrepareStatement.CannotGetParameterType=No se puede obtener el tipo de parámetro de los metadatos del parámetro.

odajdbc.CannotGetParameterMetadata=No se pueden recuperar los metadatos del parámetro.

odajdbc.ClearParametersError=Error al eliminar el valor de parámetro actual.

odajdbc.missedUrlAndJndi=GetConnection: los valores url y jndiNameUrl son nulos.

odajdbc.error.emptyDriverClass=GetConnection: el valor del nombre de clase de controlador es nulo.

#used in assert error
odajdbc.driver.ConnNotOpen=La conexión no está abierta.

odajdbc.driver.DriverMissingProperties=Faltan propiedades en Connection.open(Properties).

odajdbc.driver.ParameterMetadataCannotNull=ParameterMetaData no puede ser nulo.

odajdbc.driver.ResultSetCannotNull=ResultSet no puede ser nulo.

odajdbc.driver.ResultSetMetadataCannotNull=ResultSetMetaData no puede ser nulo.

odajdbc.driver.StatementCannotNull=La sentencia debe estar preparada antes de esta operación.

odajdbc.CannotGetMaxQueries=No se pueden obtener MaxStatements de la conexión JDBC subyacente.

odajdbc.CannotSetQueryTimeout=No se puede establecer un límite de tiempo de consulta en la sentencia JDBC subyacente.

odajdbc.BadQueryProperty=No se admite la propiedad de la consulta: {0}.

odajdbc.CannotLoadDriverClass=No se puede cargar la clase del controlador JDBC: {0}.

odajdbc.CannotInstantiateDriverClass=No se puede crear una instancia de la clase del controlador JDBC: {0}.

odajdbc.CannotInstantiateFactory=No se puede crear una instancia de la clase de la fábrica de conexión "{0}" definida en la extensión de la clase de controlador "{1}".

odajdbc.jndi.InvalidJndiResource=Encontrado tipo de recurso JNDI ({0}); se esperaba javax.sql.DataSource.

odajdbc.testfail=Error en la prueba