# Localized messages for the oda-jdbc. Messages here give 
# the text of oda-jdbc exceptions.

###########################################################

#ODA-JDBC error code
odajdbc.CannotCloseConn=Echec de fermeture de la connexion.

odajdbc.ConnCommitError=Une erreur d'accès à la base de données s'est produite ou l'objet de connexion est en mode validation automatique.

odajdbc.CannotGetConnMetaData=Impossible d'obtenir les métadonnées de connexion.

odajdbc.CannotGetConn=Echec de la connexion.

odajdbc.ConnRollbackError=Erreur de retour arrière de la connexion.

odajdbc.GetConnectionError=Erreur lors de la récupération de la connexion, {0}.

odajdbc.CannotGetMaxStatements=Impossible d'obtenir le nombre maximum d'instructions à partir des métadonnées de la base de données.

odajdbc.CannotGetMaxConnections=Impossible d'obtenir le nombre maximum de connexions à partir des métadonnées de la base de données.

odajdbc.CannotGetDatabaseMajorVersion=Impossible d'obtenir la version principale de la base de données.

odajdbc.CannotGetDatabaseMinorVersion=Impossible d'obtenir la version secondaire de la base de données.

odajdbc.CannotGetDataSourceProductName=Impossible d'obtenir le nom de produit de la source de données.

odajdbc.CannotGetDataSourceProductVersion=Impossible d'obtenir la version de produit de la source de données.

odajdbc.CannotGetSQLStateType=Impossible d'obtenir le type d'état SQL.

odajdbc.CannotParseURL=Le pilote sélectionné ne peut pas analyser l'URL spécifiée.

odajdbc.CannotParseJNDI=Le pilote sélectionné ne peut pas analyser l'URL de la source de données JNDI spécifiée.

odajdbc.NoSuitableDriver=Pilote non adapté.

odajdbc.CannotGetParameterCount=Impossible d'obtenir le nombre de paramètres.

odajdbc.CannotGetParameterMode=Impossible d'obtenir le mode du paramètre.

odajdbc.CannotGetParameterType=Impossible d'obtenir le type du paramètre.

odajdbc.CannotGetParameterTypeName=Impossible d'obtenir le nom du type de paramètre.

odajdbc.CannotGetPrecision=Impossible d'obtenir la précision.

odajdbc.CannotGetScale=Impossible d'obtenir l'échelle.

odajdbc.CannotDetermineSupportForNull=Impossible de déterminer si le paramètre est annulable.

odajdbc.CannotGetResultSet=Impossible d'obtenir le jeu de résultats.

odajdbc.CannotGetResultSetMetadata=Impossible d'obtenir les métadonnées du jeu de résultats.

odajdbc.CannotCloseResultSet=Impossible de fermer le jeu de résultats.

odajdbc.CursorDownError=Impossible de se déplacer d'une ligne vers le bas dans le jeu de résultats.

odajdbc.ResultSetCannotGetStringValue=Impossible d'obtenir la valeur de chaîne dans le jeu de résultats.

odajdbc.ResultSetCannotGetIntValue=Impossible d'obtenir la valeur d'entier dans le jeu de résultats.

odajdbc.ResultSetCannotGetDoubleValue=Impossible d'obtenir la valeur double dans le jeu de résultats.

odajdbc.ResultSetCannotGetBigDecimalValue=Impossible d'obtenir la valeur BigDecimal dans le jeu de résultats.

odajdbc.ResultSetCannotGetDateValue=Impossible d'obtenir la valeur de date dans le jeu de résultats.

odajdbc.ResultSetCannotGetTimeValue=Impossible d'obtenir la valeur temporelle dans le jeu de résultats.

odajdbc.ResultSetCannotGetTimeStampValue=Impossible d'obtenir la valeur d'horodatage dans le jeu de résultats.

odajdbc.ResultSetCannotGetBlobValue=Impossible d'obtenir la valeur BLOB dans le jeu de résultats.

odajdbc.ResultSetCannotGetClobValue=Impossible d'obtenir la valeur CLOB dans le jeu de résultats.

odajdbc.ResultSetCannotGetBooleanValue=Impossible d'obtenir la valeur booléenne dans le jeu de résultats.

odajdbc.ResultSetDetermineNull=Impossible de déterminer la valeur isNull dans le jeu de résultats.

odajdbc.ResultSetCannotFindColumn=Impossible de trouver une colonne dans le jeu de résultats.

odajdbc.CannotGetColumnCount=Impossible d'obtenir un nombre de colonnes.

odajdbc.CannotGetColumnName=Impossible d'obtenir le nom de colonne.

odajdbc.CannotGetColumnLabel=Impossible d'obtenir l'étiquette de colonne.

odajdbc.CannotGetColumnType=Impossible d'obtenir le type de colonne.

odajdbc.CannotGetColumnTypeName=Impossible d'obtenir le nom du type de colonne.

odajdbc.CannotGetColumnDisplaySize=Impossible d'obtenir la taille d'affichage de colonne.

odajdbc.CannotGetResultSetMetaDataPrecision=Impossible d'obtenir la précision des métadonnées du jeu de résultats.

odajdbc.CannotGetResultSetMetaDataScale=Impossible d'obtenir l'échelle des métadonnées du jeu de résultats.

odajdbc.CannotDetermineColumnSupportForNull=Impossible de déterminer si la colonne prend en charge les valeurs nulles.

odajdbc.StatementCannotPrepared=Erreur de préparation d'instruction SQL.

odajdbc.CannotGetMetaData=Impossible d'obtenir les métadonnées du jeu de résultats.

odajdbc.CannotClosePreparedStatement=Impossible de fermer preparedStatement.

odajdbc.CannotGetPreparedStatementMetadata=Impossible d'obtenir les métadonnées preparedStatement.

odajdbc.ResultSetCannotReturn=L'instruction SQL ne renvoie pas d'objet ResultSet.

odajdbc.QueryExecuteFail=L'instruction SQL ne renvoie pas d'objet ResultSet ou de nombre mis à jour.

odajdbc.InvalidStoredPrecedure=Instruction d'appel de procédure stockée non valide.

odajdbc.PrepareStatement.CannotSetIntValue=Impossible de définir la valeur entière du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetDoubleValue=Impossible de définir la valeur double du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetBigDecimalValue=Impossible de définir la valeur BigDecimal du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetStringValue=Impossible de définir la valeur de chaîne du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetDateValue=Impossible de définir la valeur de date du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetTimeValue=Impossible de définir la valeur temporelle du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetTimestampValue=Impossible de définir la valeur d'horodatage du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetBooleanValue=Impossible de définir la valeur booléenne du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotSetNullValue=Impossible de définir la valeur nulle du paramètre preparedStatement.

odajdbc.PrepareStatement.CannotGetParameterType=Impossible d'obtenir le type de paramètre à partir des métadonnées du paramètre.

odajdbc.CannotGetParameterMetadata=Impossible de récupérer les métadonnées du paramètre.

odajdbc.ClearParametersError=Erreur d'effacement de la valeur actuelle du paramètre.

odajdbc.missedUrlAndJndi=GetConnection : les valeurs d'url et de jndiNameUrl sont toutes les deux nulles.

odajdbc.error.emptyDriverClass=GetConnection : le nom de classe du pilote est nul.

#used in assert error
odajdbc.driver.ConnNotOpen=La connexion n'est pas ouverte.

odajdbc.driver.DriverMissingProperties=Propriétés manquantes dans Connection.open(Properties).

odajdbc.driver.ParameterMetadataCannotNull=La valeur ParameterMetaData ne peut pas être nulle.

odajdbc.driver.ResultSetCannotNull=La valeur ResultSet ne peut pas être nulle.

odajdbc.driver.ResultSetMetadataCannotNull=La valeur ResultSetMetaData ne peut pas être nulle.

odajdbc.driver.StatementCannotNull=Il est nécessaire de préparer l'instruction avant d'effectuer cette opération.

odajdbc.CannotGetMaxQueries=Impossible d'obtenir le nombre maximum d'instructions à partir de la connexion JDBC sous-jacente.

odajdbc.CannotSetQueryTimeout=Impossible de définir le délai d'expiration de requête pour l'instruction JDBC sous-jacente.

odajdbc.BadQueryProperty=Les propriétés de la requête ne sont pas prises en charge : {0}.

odajdbc.CannotLoadDriverClass=Impossible de charger la classe de pilote JDBC : {0}.

odajdbc.CannotInstantiateDriverClass=Impossible de créer l'instance de la classe de pilote JDBC : {0}.

odajdbc.CannotInstantiateFactory=Impossible de créer l''instance de la classe de génération de connexion "{0}" définie dans l''extension de la classe de pilote "{1}".

odajdbc.jndi.InvalidJndiResource=Type de ressource JNDI identifié ({0}); type attendu : javax.sql.DataSource.

odajdbc.testfail=Echec du test