#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=グラフの DPI には、96 以上を指定する必要があります。96 より小さい場合、グラフは実行コンテキストでレンダリング DPI を使用して処理されます。

INVALID_CHART_DPI=グラフ DPI を認識できません。
