#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=Le DPI de graphique doit être supérieur à 96. Dans le cas contraire, le graphique sera traité avec le DPI du rendu dans le contexte d'exécution.

INVALID_CHART_DPI=Le DPI de graphique n'est pas reconnu\!
