#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=Die Diagrammauflösung darf nicht geringer als 96 DPI sein, da das Diagramm ansonsten mit der Rendern-DPI im Ausführungskontext verarbeitet wird.

INVALID_CHART_DPI=Diagrammauflösung nicht erkannt\!
