#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=El DPI del diagrama no debería ser inferior a 96, de lo contrario el diagrama se procesará con el DPI del contexto de ejecución.

INVALID_CHART_DPI=No se reconoce el DPI del diagrama\!
