#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=차트 DPI는 96 이상이 되어야 합니다. 그렇지 않을 경우 차트가 실행 컨텍스트에서 렌더링 DPI로 처리됩니다.

INVALID_CHART_DPI=차트 DPI를 인식할 수 없습니다\!
