#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
TOO_SMALL_CHART_DPI=图表 DPI 不应小于 96，否则执行上下文中将使用呈现 DPI 来处理图表。

INVALID_CHART_DPI=无法识别图表 DPI\!
