Connection.PropertiesMissing=いくつかの接続プロパティがありません。

Connection.InvalidAppContext=AppContext が無効です。

Constants.DriverName=ODA XML ドライバ

ResultSet.ResultSetClosed=結果セットを閉じました。

Query.QueryHasNotBeenPrepared=クエリがまだ記述されていません。

Query.ResultSetClosed=結果セットを閉じました。

Query.InvalidQueryText=クエリテキストが無効です。

RelationInformation.InputStringCannotBeNull=入力文字列は null または空白にできません。

RelationInformation.InvalidDataTypeName=指定されたデータ型の名前が無効です。

DateUtil.ConvertFails=日付に変換できません。ソース :