Connection.PropertiesMissing=Certaines propriétés de connexion sont manquantes.

Connection.InvalidAppContext=AppContext incorrect.

Constants.DriverName=Pilote XML ODA

ResultSet.ResultSetClosed=Jeu de résultats fermé

Query.QueryHasNotBeenPrepared=La requête n'a pas encore été préparée.

Query.ResultSetClosed=Jeu de résultats fermé

Query.InvalidQueryText=Le texte de la requête est incorrect.

RelationInformation.InputStringCannotBeNull=La chaîne d'entrée ne peut être ni nulle ni vierge.

RelationInformation.InvalidDataTypeName=Le nom du type de données fourni est incorrect.

DateUtil.ConvertFails=Echec de la conversion en date. Source :