Connection.PropertiesMissing=缺少某些连接属性。

Connection.InvalidAppContext=无效的 AppContext。

Constants.DriverName=ODA XML 驱动程序

ResultSet.ResultSetClosed=ResultSet 关闭。

Query.QueryHasNotBeenPrepared=查询尚未准备。

Query.ResultSetClosed=ResultSet 关闭。

Query.InvalidQueryText=查询文本无效。

RelationInformation.InputStringCannotBeNull=输入字符串不能为 null 或空白。

RelationInformation.InvalidDataTypeName=提供的数据类型名称无效。

DateUtil.ConvertFails=转换为日期失败。 源: