/* Generated By:JavaCC: Do not edit this line. XDepthParserConstants.java */
package org.eclipse.birt.report.model.util.xpathparser;

public interface XDepthParserConstants {

	int EOF = 0;
	int PROPPREFIX = 1;
	int EQUAL = 2;
	int QUOTE = 3;
	int LEFTB = 4;
	int RIGHTB = 5;
	int SEPARATOR = 6;
	int NONASCII = 7;
	int CHAR = 8;
	int DIGITAL = 9;
	int NMCHAR = 10;
	int PROPNAME = 11;
	int PROPID = 12;
	int PROPSLOTNAME = 13;
	int INDEX = 14;
	int NAME = 15;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\"@\"", "\"=\"", "\"\\\"\"", "\"[\"", "\"]\"", "\"/\"", "<NONASCII>", "<CHAR>",
			"<DIGITAL>", "<NMCHAR>", "\"name\"", "\"id\"", "\"slotName\"", "<INDEX>", "<NAME>", "\"*\"", };

}
