# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.

###########################################################
#for test only
Error.Msg001=En: Es ist ein {0} im {1}.

###########################################################
Error.OutputFormatNotSupported=Das Ausgabeformat {0} wird nicht unterstützt.

Error.NullOutputFormat=OutputFormat für Renderoption ist Null.

Error.InvalidParameter=Einige der erforderlichen Parameterwerte sind nicht angegeben bzw. die angegebenen Werte entsprechen einem inkompatiblen Datentyp.

Error.InvalidGroupParameter=Auswertung der Parametergruppe mit dem Namen "{0}" durch Berichts-Engine fehlgeschlagen.

Error.ParameterTypeIsInvalid=Der Parametertyp "{0}" wird als "{1}" erwartet, nicht als "{2}".

Error.ParamValidationFailure=Die Validierung des Parameters "{0}" ist fehlgeschlagen.

Error.ParameterValueIsNull=Der erforderliche Parameter {0} wurde nicht festgelegt.

Error.ParameterValueIsBlank=Erforderlicher Parameter {0} ist leer.

Error.ParamScriptValidationError=Validierungsfehler bei Skriptquelle zu Parameter "{0}".

Error.ParameterGroupIsNotFoundByGroupname=Parametergruppe wurde durch Namen "{0}" nicht gefunden.

Error.ParameterInvalidGroupLevel=Die Ebenenanzahl der Gruppe "{0}" stimmt nicht mit der angegebenen Anzahl überein.

Error.InvalidDesignFile=Die Designdatei {0} ist fehlerhaft und kann nicht ausgeführt werden.

Error.DesignFileNotFound=Die Designdatei {0} kann nicht gefunden werden.

Error.CannotCreateExtensionInstance=Berichts-Engine kann {0}-Emitter nicht initialisieren. Vergewissern Sie sich, dass die erforderlichen Bibliotheken für diesen Emitter installiert sind.

Error.MissingComputedColumnExpression=Die Definition für die berechnete Spalte {0} fehlt.

Error.ParameterInGroupIsnotScalar=Die Parameter in der Parametergruppe "{0}" müssen Skalargrößen-Parameter sein.

Error.ParameterEvaluationError=Die Auswertung der Parametergruppe "{0}" ist fehlgeschlagen.

Error.InvalidEmitterID = EmitterID {0} für Renderoption ist ungültig.

###########################################################
Error.ErrorsOnPage=Beim Erstellen des Berichts sind Fehler aufgetreten:

Error.Error=Fehler

Error.ScriptFileLoadError=Scriptdatei {0} kann nicht geladen werden.

Error.ScriptEvaluationError=Fehler beim Auswerten des Skripts "{0}":\n{1}.

Error.TextualItemProcessingError=Bei der Verarbeitung des Textelements {0} sind Probleme aufgetreten.

Error.TableItemProcessingError=Beim Verarbeiten der Tabelle {0} sind Probleme aufgetreten.

Error.ExtendedItemGenerationError=Beim Erstellen des erweiterten Elements {0} sind Probleme aufgetreten.

Error.ExtendedItemRenderingError=Beim Rendern {0} des erweiterten Elements {1} sind Probleme aufgetreten.

Error.GridItemProcessingError=Beim Verarbeiten des Rasters {0} sind Probleme aufgetreten.

Error.ImageItemProcessingError=Beim Verarbeiten des Bildes {0} sind Probleme aufgetreten.

Error.MissingImageFileError=Bilddatei fehlt.

Error.InvalidImageSourceError=Ungültiger Datenquellentyp für Bild.

Error.InvalidDatabaseImageError=Ungültiges Datenbank-Image. Ausdruck für Image lautet "{0}".

Error.EmbeddedExpressionError=Beim Evaluieren des eingebetteten Ausdrucks "{0}" ist ein Fehler aufgetreten.

Error.EmbeddedImageError=Beim Verarbeiten des eingebetteten Bildes ist ein Fehler aufgetreten.

Error.HTMLImageError=Beim Verarbeiten des in den HTML-Tag '<img>' eingebetteten Bildes ist ein Fehler aufgetreten.

Error.UndefinedDatasetError=Datensatz "{0}" ist im Bericht nicht definiert.

Error.InvalidExpressionError=Ausdruck "{0}" ist ungültig.

Error.ListProcessingError=Bei der Verarbeitung des Listenelements {0} sind Probleme aufgetreten.

Error.ErrorOnReportPage=Folgende Objekte weisen Fehler auf:

Error.ReportErrorMessage = {0} {1}:

Error.ReportErrorMessageWithID = {0} (id = {1}):

Error.ReportErrorID = {0} ({1} Mal)

Error.ReportErrorDetail = Detail:

Error.JarNotFoundError = JAR {0} nicht gefunden.

Error.ScriptClassCastError = Schnittstelle {1} wird nicht von Klasse {0} implementiert.

Error.ScriptClassNotFoundError = Klasse {0} nicht gefunden.

Error.ScriptClassIllegalAccessError = IllegalAccessException beim Laden der Klasse {0}.

Error.ScriptClassInstantiationError = Klasse {0} konnte nicht instanziiert werden. Stellen Sie sicher, dass es sich nicht um eine Schnittstelle oder eine abstrakte Klasse handelt.

Error.UnhandledScriptError = Unverarbeitete Ausnahme beim Ausführen des Skripts.

###########################################################
Error.PageNotFoundError = Seite {0} wurde nicht gefunden.

Error.PageNumberRangeError = Ungültiger Seitenbereich: {0}.

Error.PageHintLoadingError = Seitenhinweis kann nicht geladen werden.

Error.PagesLoadingError = Seiten {0} können nicht geladen werden.

Error.InvalidGroupError = Ungültige Gruppe: {0}.

Error.InvalidExtensionError = Ungültige Erweiterungs-ID: {0} und ungültiges Format: {1}.

Error.InvalidColumnIndexError = Ungültiger Spaltenindex.

Error.InvalidInstanceIDError = Ungültige Instanz-ID: {0}.

Error.InvalidBookmarkError = Ungültiges Lesezeichen: {0}.

Error.ExpressionEvaluationError = Das Ergebnis des folgenden Sichtbarkeitsausdrucks ist kein zulässiger boolescher Wert: {0}.

Error.BookmarkNotFoundError = Lesezeichen nicht gefunden: {0}.

Error.DateError = Datum:{0}.

Error.CubePositionError = Fehler beim Abrufen der Quaderposition.

Error.SubqueryCreateError = Unterabfrage kann nur in einer anderen (Unter-)Abfrage erstellt werden.

Error.BindDataRetrivingError = Fehler beim Abrufen der Bindungsdaten.

Error.DataSourceError = Datenquelle des Datensatzes darf nicht Null sein.

Error.UnsupportedQueryDefinitionError = Nicht unterstützte Abfragedefinition: {0}.

Error.ReportQueryLoadingError = Beim Laden der Berichtabfrage ist ein Fehler aufgetreten, Daten zur Erstellung des Berichts können nicht abgerufen werden.

Error.ReportQueryLoadingError2 = Berichtabfrage kann nicht geladen werden: {0}. Fehler beim Generieren des Berichtsdokuments für das Berichtselement mit ID {1}.

Error.ExtentionIDMissingError = Fehlende Erweiterungs-ID in Datenquellendefinition: {0}

Error.DataExportionError = Daten konnten nicht nach Instanz-ID exportiert werden:{0}.

Error.UnsupportedDocumentVersionError = Nicht unterstützte Dokumentversion: {0}.

Error.ResultsetIteratorError = Ergebnisiteration muss in gültige Zeile verschoben werden.

Error.ReportDesignNotFoundError = Berichtdesign in Berichtdokument nicht gefunden: {0}.

Error.PreparedQueryNotFoundError = Vorbereitete Abfrage {0} nicht gefunden.

Error.IncorrectParentResultSetError = Falsches übergeordnetes Ergebnis für Unterabfrage: {0}.

Error.UnsupportedQueryTypeError = Nicht unterstützter Abfragetyp: {0}.

Error.QueryNotBuiltError = Fehler beim Erstellen der Abfrage für Element: {0}.

Error.RenderTaskNotFinishedError = Rendern noch nicht abgeschlossen.

Error.RenderOptionError = Zum Rendern eines Berichts müssen Renderoptionen angegeben werden.

Error.ReportArchiveError = Berichtarchiv ist bei der Ausführung eines Berichts nicht angegeben.

Error.ReportDocNameNotSpecifiedError = Berichtdokumentname ist bei der Ausführung eines Berichts nicht angegeben.

Error.ReportRunError = Fehler bei der Ausführung des Berichts.

Error.ReportDocmentOpenError = Berichtdokument konnte nicht geöffnet werden.

Error.ReportArchiveOpenError = Berichtarchiv kann nicht geöffnet werden.

Error.SkipError = Fehler beim Ignorieren.

Error.ResultsetExtractError = Ergebnis nicht gefunden.

Error.FailedToInitializeEmitter = Emitter konnte nicht initialisiert werden.

###########################################################
PDFCreator = BIRT-Berichtengine {0} mit iText {1}.

###########################################################
Error.FlashObjectNotSupported = Berichtobjekte aus Flash-Objekten werden in diesem Berichtformat nicht unterstützt.

Error.ReportItemNotSupported = Das aktuelle Berichtobjekt wird in diesem Berichtformat nicht unterstützt.

Error.ResourceUnreachable = Die Ressource dieses Berichtobjekts ist nicht erreichbar.

Error.UpdateUserAgent = Aktivieren Sie die Flash-Unterstützung, oder laden Sie eine neuere Version des Adobe Readers herunter, um Flash-Inhalte in PDF-Dateien anzuzeigen.

###########################################################
Error.ReportRunnableNotSet = Auszuführender Bericht wurde nicht festgelegt.

Error.FailedToLoadTOCTree = TOC-Struktur konnte nicht geladen werden.

Error.ExceptionOnFetchingBookmarks = Fehler beim Abrufen der Lesezeichen.

Error.FailedToSaveDesign = Fehler beim Speichern des Designs.

Error.ExceptionOnCopyingArchives = Ausnahme beim Kopieren der Archive.

Error.UnsupportedCoreStreamVersion = Nicht unterstützte Core-Stream-Version: {0}.

Error.UnsupportedEngineExtension = Nicht unterstützte Engine-Erweiterung {0}.

Error.FailToCreateDataEngine = Daten-Engine kann nicht erstellt werden.

Error.FailedToCreateTOC = TOC konnte nicht erstellt werden.

Error.UnsupportedExprssionType = Unerwarteter Ausdruckstyp.

Error.UnknownContentVersion = Unbekannte Inhaltsversion.

Error.UnknownFieldID = Unbekannte Feld-ID: {0}.

Error.ResourceNotAccessible = Zugriff auf {0} nicht möglich.

Error.ERROR_WITH_STATUS=Fehler in Dokument: {0}.

###########################################################
Error.ElementID = Element-ID

###########################################################
Message.TaskCancel = Die Aufgabe wird abgebrochen.