# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.

###########################################################
#for test only
Error.Msg001=En: There is a {0} in the {1}.

###########################################################
Error.OutputFormatNotSupported=No se admite el formato de salida {0}.
Error.InvalidParameter=Algunos parámetros de valores necesarios no están establecidos o se han establecido con un tipo de datos incompatible.
Error.InvalidDesignFile=El archivo de diseño {0} contiene errores y no se puede ejecutar.
Error.DesignFileNotFound=No se puede encontrar el archivo de diseño {0}.
Error.CannotCreateExtensionInstance=El motor de informes no puede crear una extensión que controle esta solicitud.
Error.MissingComputedColumnExpression=Falta la expresión de la columna procesada {0}

###########################################################
Error.ErrorsOnPage=Hay errores al generar informe:
Error.Error=Error
Error.ScriptFileLoadError=No es posible cargar el archivo de script {0}.
Error.ScriptEvaluationError=Hay errores al evaluar el script "{0}".
Error.TextualItemProcessingError=Hay problemas al procesar el elemento de texto {0}.
Error.TableItemProcessingError=Hay problemas al procesar la tabla {0}.
Error.ExtendedItemGenerationError=Hay problemas al generar el elemento ampliado {0}.
Error.ExtendedItemRenderingError=Hay problemas al procesar el elemento ampliado {1} de {0}.
Error.GridItemProcessingError=Hay problemas al procesar la cuadrícula {0}.
Error.ImageItemProcessingError=Hay problemas al procesar la imagen {0}.
Error.MissingImageFileError=Falta el archivo de imagen.
Error.InvalidImageSourceError=Tipo de fuente de imagen no válido. 
Error.InvalidDatabaseImageError=Imagen de base de datos no válida. La expresión de la imagen es "{0}". 
Error.EmbeddedExpressionError=Hay errores al evaluar la expresión incrustada "{0}". 
Error.EmbeddedImageError=Hay errores al procesar la imagen incrustada. 
Error.HTMLImageError=Hay errores al procesar la imagen incrustada en la etiqueta HTML <img>. 

Error.UndefinedDatasetError=El conjunto de datos "{0}" no está definido en el informe. 
Error.InvalidExpressionError=La expresión "{0}" no es válida. 
Error.ListProcessingError=Hay problemas al procesar el elemento de lista {0}.
Error.ErrorOnReportPage=Los siguientes elementos tienen errores:

Error.ReportErrorMessage = {0} {1}:
Error.ReportErrorMessageWithID = {0} (id = {1}):
Error.ReportErrorID = {0} ({1} veces)
Error.ReportErrorDetail = detalle: 
Error.ScriptClassCastError = La clase {0} no implementa la interfaz {1}
Error.ScriptClassNotFoundError = No se ha encontrado la clase {0}
Error.ScriptClassIllegalAccessError = IllegalAccessException al intentar cargar la clase {0} 
Error.ScriptClassInstantiationError = No se ha podido crear una instancia de la clase {0}. Asegúrese de que no es una interfaz ni una clase abstracta.
Error.UnhandledScriptError = Excepción no controlada al ejecutar el script
