# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.

###########################################################
#for test only
Error.Msg001=En: There is a {0} in the {1}.

###########################################################
Error.OutputFormatNotSupported=不支持输出格式 {0}。
Error.InvalidParameter=某些所需的参数值未设置或设为不兼容的数据类型。
Error.InvalidDesignFile=设计文件 {0} 有错误且不能运行。
Error.DesignFileNotFound=无法找到设计文件 {0}。
Error.CannotCreateExtensionInstance=报表引擎无法初始化 {0} 发射器，请确保安装发射器必需的库。
Error.MissingComputedColumnExpression=缺少计算列 {0} 的表达式。

###########################################################
Error.ErrorsOnPage=生成报表时出错: 
Error.Error=错误
Error.ScriptFileLoadError=无法加载脚本文件 {0}。
Error.ScriptEvaluationError=判定脚本“{0}”时出错: {1}。
Error.TextualItemProcessingError=处理文本项 {0} 时出错。
Error.TableItemProcessingError=处理表 {0} 时出错。
Error.ExtendedItemGenerationError=生成扩展项 {0} 时出错。
Error.ExtendedItemRenderingError=呈现 {0} 扩展项 {1} 时出错。
Error.GridItemProcessingError=处理网格 {0} 时出错。
Error.ImageItemProcessingError=处理图像 {0} 时出错。
Error.MissingImageFileError=缺少图像文件。
Error.InvalidImageSourceError=无效图像源类型。 
Error.InvalidDatabaseImageError=无效数据库图像。图像表达式“{0}”。 
Error.EmbeddedExpressionError=判定嵌入表达式“{0}”时出错。 
Error.EmbeddedImageError=处理嵌入图像时出错。 
Error.HTMLImageError=处理 HTML <img> 标记中的嵌入图像时出错。 

Error.UndefinedDatasetError=报表中未定义数据集 "{0}"。 
Error.InvalidExpressionError=表达式 "{0}" 无效。 
Error.ListProcessingError=处理列表项 {0} 时出现问题。
Error.ErrorOnReportPage=下列项有错误:

Error.ReportErrorMessage = {0} {1}:
Error.ReportErrorMessageWithID = {0} (id = {1}):
Error.ReportErrorID = {0} ( {1} 次 )
Error.ReportErrorDetail = 详细资料: 

Error.ScriptClassCastError = 类 {0} 不实现 {1} 接口
Error.ScriptClassNotFoundError = 未找到类 {0}
Error.ScriptClassIllegalAccessError = 尝试加载类 {0} 时出现 IllegalAccessException 
Error.ScriptClassInstantiationError = 无法实例化类 {0}。 确保它不是接口或抽象类。
Error.UnhandledScriptError = 执行脚本时出现未处理的例外
