# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.

###########################################################
#for test only
Error.Msg001=En: There is a {0} in the {1}.

###########################################################
Error.OutputFormatNotSupported=Le format de sortie {0}n''est pas pris en charge.
Error.InvalidParameter=Certaines valeurs de paramètres requises ne sont pas définies ou sont définies sur un type de données incompatible.
Error.InvalidDesignFile=Le fichier modèle {0} comporte une erreur et ne peut pas être exécuté.
Error.DesignFileNotFound=Le fichier modèle {0} est introuvable.
Error.CannotCreateExtensionInstance=L''initialisation de l''émetteur {0} par le moteur d''états a échoué, assurez-vous que les bibliothèques nécessaires à cet émetteur sont installées.
Error.MissingComputedColumnExpression=L''expression de la colonne de calcul {0} est manquante.

###########################################################
Error.ErrorsOnPage=Des erreurs sont survenues lors de la création de l'état :
Error.Error=Erreur
Error.ScriptFileLoadError=Impossible de charger le fichier de script {0}.
Error.ScriptEvaluationError=Des erreurs sont survenues lors de l''évaluation du script « {0} ».
Error.TextualItemProcessingError=Problème(s) de traitement de l''élément de texte {0}.
Error.TableItemProcessingError=Problème(s) de traitement de la table {0}.
Error.ExtendedItemGenerationError=Problème(s) de création de l''élément étendu {0}.
Error.ExtendedItemRenderingError=Problème(s) de rendu {0} de l''élément étendu {1}.
Error.GridItemProcessingError=Problème(s) de traitement de la grille {0}.
Error.ImageItemProcessingError=Problème(s) de traitement de l''image {0}.
Error.MissingImageFileError=Fichier image manquant.
Error.InvalidImageSourceError=Type de source d'image incorrect. 
Error.InvalidDatabaseImageError=Image de base de données incorrecte. L''expression de l''image est « {0} ». 
Error.EmbeddedExpressionError=Des erreurs sont survenues lors de l''évaluation de l''expression incorporée « {0} ». 
Error.EmbeddedImageError=Des erreurs sont survenues lors du traitement de l'image incorporée. 
Error.HTMLImageError=Des erreurs sont survenues lors du traitement de l'image incorporée dans la balise HTML <img>. 

Error.UndefinedDatasetError=Le jeu de données "{0}" n''est pas défini dans l''état. 
Error.InvalidExpressionError=L''expression "{0}" est incorrecte. 
Error.ListProcessingError=Problème(s) de traitement de l''élément de liste {0}.
Error.ErrorOnReportPage=Les éléments suivants comportent des erreurs :

Error.ReportErrorMessage = {0} {1}:
Error.ReportErrorMessageWithID = {0} (id = {1}):
Error.ReportErrorID = {0} ( {1} fois )
Error.ReportErrorDetail = détails : 
Error.ScriptClassCastError = La classe {0} n''implémente pas l''interface {1}
Error.ScriptClassNotFoundError = Classe {0} introuvable
Error.ScriptClassIllegalAccessError = IllegalAccessException lors de la tentative de chargement de la classe {0} 
Error.ScriptClassInstantiationError = La classe {0} n''a pas pu être instanciée. Vérifiez qu''il ne s''agit pas d''une interface ou d''une classe abstraite.
Error.UnhandledScriptError = Exception non traitée lors de l'exécution du script
