# Localized messages for the Design Engine. Messages here give names
# of items in the Report Object Model, and the text of Design Engine
# errors.

###########################################################
#for test only
Error.Msg001=ja_JP: There is a {0} in the {1}.

###########################################################
Error.OutputFormatNotSupported=出力形式 {0} はサポートされていません。
Error.InvalidParameter=いくつかの必須パラメタの値が設定されていないか、互換性のないデータ型に設定されています。
Error.InvalidDesignFile=デザインファイル {0} にエラーがあるため、実行できません。
Error.DesignFileNotFound=デザインファイル {0} が見つかりません。
Error.CannotCreateExtensionInstance=レポートエンジンで {0} エミッターを初期化できません。このエミッターに必要なライブラリがインストールされていることを確認してください。
Error.MissingComputedColumnExpression=計算列 {0} の式が見つかりません。

###########################################################
Error.ErrorsOnPage=レポートの生成中にエラーが発生しました :
Error.Error=エラー
Error.ScriptFileLoadError=スクリプトファイル {0} を読み込めません。
Error.ScriptEvaluationError=スクリプト "{0}":{1} の評価中にエラーが発生しました。
Error.TextualItemProcessingError=テキスト項目 {0} の処理中にエラーが発生しました。
Error.TableItemProcessingError=テーブル項目 {0} の処理中にエラーが発生しました。
Error.ExtendedItemGenerationError=拡張項目 {0} の生成中にエラーが発生しました。
Error.ExtendedItemRenderingError=拡張項目 {1} のレンダリング中 {0} にエラーが発生しました。
Error.GridItemProcessingError=グリッド項目 {0} の処理中にエラーが発生しました。
Error.ImageItemProcessingError=イメージ {0} の処理中にエラーが発生しました。
Error.MissingImageFileError=イメージファイルが見つかりません。
Error.InvalidImageSourceError=イメージソースの型が無効です。 
Error.InvalidDatabaseImageError=データベースイメージが無効です。イメージの式は "{0}" です。 
Error.EmbeddedExpressionError=埋め込まれた式 "{0}" の評価中にエラーが発生しました。 
Error.EmbeddedImageError=埋め込まれたイメージの処理中にエラーが発生しました。 
Error.HTMLImageError=HTML の <img> タグで埋め込まれたイメージの処理中にエラーが発生しました。 

Error.UndefinedDatasetError=データセット "{0}" がレポートで定義されていません。 
Error.InvalidExpressionError=式 "{0}" が無効です。 
Error.ListProcessingError=リスト項目 {0} の処理中にエラーが発生しました。
Error.ErrorOnReportPage=次の項目にエラーがあります :

Error.ReportErrorMessage = {0} {1}:
Error.ReportErrorMessageWithID = {0} (id = {1}) :
Error.ReportErrorID = {0} ({1} 回)
Error.ReportErrorDetail = 詳細 : 

Error.ScriptClassCastError = クラス {0} には {1} インターフェイスが実装されていません。
Error.ScriptClassNotFoundError = クラス {0} が見つかりません。
Error.ScriptClassIllegalAccessError = クラス {0} を読み込み中に IllegalAccessException が発生しました。 
Error.ScriptClassInstantiationError = クラス {0} をインスタンス化できませんでした。インターフェイスまたは抽象クラスでないことを確認してください。
Error.UnhandledScriptError = スクリプトを実行中に未処理の例外が発生しました。
