preference.description = Format bidirectionnel par défaut pour la source de données JDBC
preference.bidiframe.title = Format bidirectionnel 
preference.bidiframe.arabictitle = Paramètres spécifiques à l'arabe
 

report.bidi.properties.externalbidiformat.orderingscheme=Modèle de commande
report.bidi.properties.externalbidiformat.orderingscheme.tooltip = Choisir la valeur du modèle de commande 
report.bidi.properties.externalbidiformat.textdirection=Direction du texte
report.bidi.properties.externalbidiformat.textdirection.tooltip = Choisir la valeur de direction du texte
report.bidi.properties.externalbidiformat.symswap=Echange symétrique
report.bidi.properties.externalbidiformat.symswap.tooltip = Choisir la valeur d'échange symétrique
report.bidi.properties.externalbidiformat.symswap.true=Vrai
report.bidi.properties.externalbidiformat.symswap.false=Faux
report.bidi.properties.externalbidiformat.shaping=Mise en forme du texte
report.bidi.properties.externalbidiformat.shaping.tooltip = Choisir la valeur de mise en forme du texte
report.bidi.properties.externalbidiformat.numshaping=Mise en forme numérique
report.bidi.properties.externalbidiformat.numshaping.tooltip = Choisir la mise en forme numérique
report.bidi.properties.externalbidiformat.orderingscheme.visual =Visuel
report.bidi.properties.externalbidiformat.orderingscheme.logical =Logique
report.bidi.properties.externalbidiformat.textdirection.ltr=Gauche à droite
report.bidi.properties.externalbidiformat.textdirection.rtl=Droite à gauche
report.bidi.properties.externalbidiformat.textdirection.contextltr=Contextuel, de gauche à droite
report.bidi.properties.externalbidiformat.textdirection.contextrtl=Contextuel, de droite à gauche
report.bidi.properties.externalbidiformat.shaping.shaped=Mis en forme 
report.bidi.properties.externalbidiformat.shaping.nominal=Nominal
report.bidi.properties.externalbidiformat.numshaping.national=National 
report.bidi.properties.externalbidiformat.numshaping.nominal=Nominal
report.bidi.properties.externalbidiformat.numshaping.contextual=Contextuel
report.bidi.properties.externalbidiformat = Format Bidi externe
report.bidi.properties.nonbididirection = Gauche à droite

advancedbididialog.title=Paramètres avancés de source de données Bidi
advancedbididialog.msg=Définir les métadonnées et les formats Bidi de contenu
advancedbidi.button=Paramètres Bidi...
metadata.bidiframe.title=Format Bidi des métadonnées du système externe
content.bidiframe.title=Format Bidi du contenu du système externe
disablebidi.checkbox=Désactiver la transformation Bidi

