preference.description = JDBC データソースのデフォルトの双方向形式
preference.bidiframe.title = 双方向形式 
preference.bidiframe.arabictitle = アラビア語固有の機能
 

report.bidi.properties.externalbidiformat.orderingscheme=スキームの順序
report.bidi.properties.externalbidiformat.orderingscheme.tooltip = スキームの順序値の選択 
report.bidi.properties.externalbidiformat.textdirection=文字列の向き
report.bidi.properties.externalbidiformat.textdirection.tooltip = 文字列の向きの値の選択
report.bidi.properties.externalbidiformat.symswap=対照的な置換
report.bidi.properties.externalbidiformat.symswap.tooltip = 対照的な置換の値の選択
report.bidi.properties.externalbidiformat.symswap.true=True
report.bidi.properties.externalbidiformat.symswap.false=False
report.bidi.properties.externalbidiformat.shaping=文字列整形
report.bidi.properties.externalbidiformat.shaping.tooltip = 文字列整形の値の選択
report.bidi.properties.externalbidiformat.numshaping=数値整形
report.bidi.properties.externalbidiformat.numshaping.tooltip = 数値整形の選択
report.bidi.properties.externalbidiformat.orderingscheme.visual =視覚
report.bidi.properties.externalbidiformat.orderingscheme.logical =論理
report.bidi.properties.externalbidiformat.textdirection.ltr=左から右
report.bidi.properties.externalbidiformat.textdirection.rtl=右から左
report.bidi.properties.externalbidiformat.textdirection.contextltr=左から右のコンテキスト
report.bidi.properties.externalbidiformat.textdirection.contextrtl=右から左のコンテキスト
report.bidi.properties.externalbidiformat.shaping.shaped=整形済み 
report.bidi.properties.externalbidiformat.shaping.nominal=名義
report.bidi.properties.externalbidiformat.numshaping.national=ナショナル 
report.bidi.properties.externalbidiformat.numshaping.nominal=名義
report.bidi.properties.externalbidiformat.numshaping.contextual=コンテキスト
report.bidi.properties.externalbidiformat = 外部双方向形式
report.bidi.properties.nonbididirection = 左から右

advancedbididialog.title=双方向データ ソースの詳細設定
advancedbididialog.msg=メタデータおよびコンテンツ双方向形式の設定
advancedbidi.button=双方向の設定 ...
metadata.bidiframe.title=外部システムのメタデータ双方向形式
content.bidiframe.title=外部システムのコンテンツ双方向形式
disablebidi.checkbox=双方向変換を無効にする

