preference.description = Formato bidireccional predeterminado para la fuente de datos JDBC

preference.bidiframe.title = Formato bidireccional

preference.bidiframe.arabictitle = Funciones específicas del árabe

report.bidi.properties.externalbidiformat.orderingscheme.metadata=Esquema de &orden

report.bidi.properties.externalbidiformat.orderingscheme.content=Esquema de o&rden

report.bidi.properties.externalbidiformat.shaping.metadata=Forma de te&xto

report.bidi.properties.externalbidiformat.shaping.content=Forma de t&exto

report.bidi.properties.externalbidiformat.numshaping.metadata=Forma &numérica

report.bidi.properties.externalbidiformat.numshaping.content=Forma n&umérica

report.bidi.properties.externalbidiformat.symswap.metadata=Intercambio &simétrico

report.bidi.properties.externalbidiformat.symswap.content=Intercambio s&imétrico

report.bidi.properties.externalbidiformat.textdirection.metadata=&Dirección de texto

report.bidi.properties.externalbidiformat.textdirection.content=Dirección de te&xto

report.bidi.properties.externalbidiformat.orderingscheme.tooltip = Elegir valor de esquema de orden

report.bidi.properties.externalbidiformat.textdirection.tooltip = Elegir valor de dirección del texto

report.bidi.properties.externalbidiformat.symswap.tooltip = Elegir valor de intercambio simétrico

report.bidi.properties.externalbidiformat.symswap.true=True

report.bidi.properties.externalbidiformat.symswap.false=False

report.bidi.properties.externalbidiformat.shaping.tooltip = Elegir valor de forma del texto

report.bidi.properties.externalbidiformat.numshaping.tooltip = Elegir forma numérica

report.bidi.properties.externalbidiformat.orderingscheme.visual =Visual

report.bidi.properties.externalbidiformat.orderingscheme.logical =Lógica

report.bidi.properties.externalbidiformat.textdirection.ltr=De izquierda a derecha

report.bidi.properties.externalbidiformat.textdirection.rtl=De derecha a izquierda

report.bidi.properties.externalbidiformat.textdirection.contextltr=Contextual de izquierda a derecha

report.bidi.properties.externalbidiformat.textdirection.contextrtl=Contextual de derecha a izquierda

report.bidi.properties.externalbidiformat.shaping.shaped=Con forma

report.bidi.properties.externalbidiformat.shaping.nominal=Nominal

report.bidi.properties.externalbidiformat.numshaping.national=Nacional

report.bidi.properties.externalbidiformat.numshaping.nominal=Nominal

report.bidi.properties.externalbidiformat.numshaping.contextual=Contextual

report.bidi.properties.externalbidiformat = Formato bidireccional externo

report.bidi.properties.nonbididirection = De izquierda a derecha

advancedbididialog.title=Ajustes avanzados de fuente de datos bidireccional

advancedbididialog.msg=Establecer formatos bidireccionales de metadatos y contenido

advancedbidi.button=Ajustes bidireccionales...

metadata.bidiframe.title=Formato bidireccional de metadatos del sistema externo

content.bidiframe.title=Formato bidireccional de contenido del sistema externo

disablebidi.checkbox.label=Desa&ctivar transformación bidimensional

