preference.description = JDBC 데이터 원본의 기본 양방향 형식

preference.bidiframe.title = 양방향 형식

preference.bidiframe.arabictitle = 아랍어 특정 기능

report.bidi.properties.externalbidiformat.orderingscheme.metadata=순서 체계(&O)

report.bidi.properties.externalbidiformat.orderingscheme.content=순서 체계(&R)

report.bidi.properties.externalbidiformat.shaping.metadata=텍스트 모양(&S)

report.bidi.properties.externalbidiformat.shaping.content=텍스트 모양(&H)

report.bidi.properties.externalbidiformat.numshaping.metadata=숫자 모양(&N)

report.bidi.properties.externalbidiformat.numshaping.content=숫자 모양(&U)

report.bidi.properties.externalbidiformat.symswap.metadata=대칭 변경(&W)

report.bidi.properties.externalbidiformat.symswap.content=대칭 변경(&)

report.bidi.properties.externalbidiformat.textdirection.metadata=텍스트 방향(&D)

report.bidi.properties.externalbidiformat.textdirection.content=텍스트 방향(&)

report.bidi.properties.externalbidiformat.orderingscheme.tooltip = 순서 체계 값 선택

report.bidi.properties.externalbidiformat.textdirection.tooltip = 텍스트 방향 값 선택

report.bidi.properties.externalbidiformat.symswap.tooltip = 대칭 변경 값 선택

report.bidi.properties.externalbidiformat.symswap.true=참

report.bidi.properties.externalbidiformat.symswap.false=거짓

report.bidi.properties.externalbidiformat.shaping.tooltip = 텍스트 모양 값 선택

report.bidi.properties.externalbidiformat.numshaping.tooltip = 숫자 모양 선택

report.bidi.properties.externalbidiformat.orderingscheme.visual =시각적

report.bidi.properties.externalbidiformat.orderingscheme.logical =논리적

report.bidi.properties.externalbidiformat.textdirection.ltr=왼쪽에서 오른쪽

report.bidi.properties.externalbidiformat.textdirection.rtl=오른쪽에서 왼쪽

report.bidi.properties.externalbidiformat.textdirection.contextltr=문맥에 따라 왼쪽에서 오른쪽

report.bidi.properties.externalbidiformat.textdirection.contextrtl=문맥에 따라 오른쪽에서 왼쪽

report.bidi.properties.externalbidiformat.shaping.shaped=Shaped

report.bidi.properties.externalbidiformat.shaping.nominal=Nominal

report.bidi.properties.externalbidiformat.numshaping.national=National

report.bidi.properties.externalbidiformat.numshaping.nominal=Nominal

report.bidi.properties.externalbidiformat.numshaping.contextual=Contextual

report.bidi.properties.externalbidiformat = 외부 양방향 형식

report.bidi.properties.nonbididirection = 왼쪽에서 오른쪽

advancedbididialog.title=고급 양방향 데이터 원본 설정

advancedbididialog.msg=메타데이터 및 내용 양방향 형식 설정

advancedbidi.button=양방향 설정...

metadata.bidiframe.title=외부 시스템의 메타데이터 양방향 형식

content.bidiframe.title=외부 시스템의 내용 양방향 형식

disablebidi.checkbox.label=양방향 변환 사용 안 함(&B)

