preference.description = JDBC 数据源的默认双向格式

preference.bidiframe.title = 双向格式

preference.bidiframe.arabictitle = 阿拉伯特定功能

report.bidi.properties.externalbidiformat.orderingscheme.metadata=排序方案(&O)

report.bidi.properties.externalbidiformat.orderingscheme.content=排序方案(&R)

report.bidi.properties.externalbidiformat.shaping.metadata=文本造型(&S)

report.bidi.properties.externalbidiformat.shaping.content=文本造型(&H)

report.bidi.properties.externalbidiformat.numshaping.metadata=数字造型(&N)

report.bidi.properties.externalbidiformat.numshaping.content=数字造型(&U)

report.bidi.properties.externalbidiformat.symswap.metadata=对称交换(&W)

report.bidi.properties.externalbidiformat.symswap.content=对称交换(&A)

report.bidi.properties.externalbidiformat.textdirection.metadata=文本方向(&D)

report.bidi.properties.externalbidiformat.textdirection.content=文本方向(&X)

report.bidi.properties.externalbidiformat.orderingscheme.tooltip = 选择排序方案值

report.bidi.properties.externalbidiformat.textdirection.tooltip = 选择文本方向值

report.bidi.properties.externalbidiformat.symswap.tooltip = 选择对称交换值

report.bidi.properties.externalbidiformat.symswap.true=真

report.bidi.properties.externalbidiformat.symswap.false=假

report.bidi.properties.externalbidiformat.shaping.tooltip = 选择文本造型值

report.bidi.properties.externalbidiformat.numshaping.tooltip = 选择数字造型

report.bidi.properties.externalbidiformat.orderingscheme.visual =视觉

report.bidi.properties.externalbidiformat.orderingscheme.logical =逻辑

report.bidi.properties.externalbidiformat.textdirection.ltr=从左到右

report.bidi.properties.externalbidiformat.textdirection.rtl=从右到左

report.bidi.properties.externalbidiformat.textdirection.contextltr=上下文从左到右

report.bidi.properties.externalbidiformat.textdirection.contextrtl=上下文从右到左

report.bidi.properties.externalbidiformat.shaping.shaped=成形

report.bidi.properties.externalbidiformat.shaping.nominal=名义

report.bidi.properties.externalbidiformat.numshaping.national=国家

report.bidi.properties.externalbidiformat.numshaping.nominal=名义

report.bidi.properties.externalbidiformat.numshaping.contextual=上下文

report.bidi.properties.externalbidiformat = 外部双向格式

report.bidi.properties.nonbididirection = 从左到右

advancedbididialog.title=高级双向数据源设置

advancedbididialog.msg=设置元数据和内容双向格式

advancedbidi.button=双向设置...

metadata.bidiframe.title=外部系统的元数据双向格式

content.bidiframe.title=外部系统的内容双向格式

disablebidi.checkbox.label=禁用双向转换(&B)

