###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Quader
cube.new=Neuer Quader
cube.action.new=Neuer Datenq&uader
cube.edit=Quader bearbeiten
CubeNodeProvider.menu.text=&Bearbeiten
cube.dimension.new=Neue Quaderdimension
cube.dimension.edit=Quaderdimension bearbeiten
CubeDimensionNodeProvider.menu.text=&Bearbeiten
CubeGroupContent.Message.Add.Message=Name des Zusammenfassungsfelds:
CubeGroupContent.Group.Edit.Message=Gruppenname:
CubeGroupContent.Measure.Edit.Title=Zusammenfassungsfeld bearbeiten
cube.level.new=Neue Quaderebene
cube.level.edit=Ebene bearbeiten
CubeLevelNodeProvider.menu.text=&Bearbeiten
cube.measure.new=Neue Quadereinheit
cube.measure.edit=Quadereinheit bearbeiten
CubeMeasureNodeProvider.menu.text=&Bearbeiten
CubeGroupContent.Group.Add.Title=Gruppe hinzufügen
CubeGroupContent.Group.Add.Message=Gruppen&name:
CubeGroupContent.Measure.Add.Title=Zusammenfassungsfeld hinzufügen
CubeGroupContent.Group.Edit.Title=Gruppe bearbeiten
cube.measuregroup.new=Neue Quadereinheitsgruppe
cube.measuregroup.edit=Quadereinheit bearbeiten
CubeMeasureGroupNodeProvider.menu.text=&Bearbeiten
CubeGroupContent.Measure.Edit.Message=Name des Zusammenfassungsfelds:
CubeModel.group.edit=Gruppe &bearbeiten
Cube.Other.Datasets=Andere
CubeModel.summaryfield.edit=Zusammenfassungsfeld &bearbeiten
Cube.Groups=Gruppen (Dimensionen)
Cube.MeasureGroup=Zusammenfassungsfelder (Einheiten)
CubeGroupContent.MeasureDataTypeErrorDialog.Message=Maßeinheit unterstützt nicht den Datentyp "Beliebig". Wählen Sie eine andere Datenspalte, oder ändern Sie den Datentyp der Spalte "{0}".
CubeGroupContent.MeasureDataTypeErrorDialog.Title=Warnung
###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Kreuztabellen-Cube Builder
DatasePage.EmptyName.ErrorMessage=Der Name des Quaders ist erforderlich.
DatasetPage.Title=Datensatz
GroupDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:
GroupDialog.Button.DateGroup=&Datumsgruppe
GroupDialog.Button.RegularGroup=&Reguläre Gruppe
GroupRenameDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:
GroupsPage.Title=Gruppen und Zusammenfassungen
LinkGroupsPage.Title=Gruppen verknüpfen
DatasetPage.Label.Name=&Name:
DateGroupDialog.Title=Gruppenebene hinzufügen/bearbeiten
DateGroupDialog.Message.NumericName=Gruppenname darf keine reine Zahl sein.
DateGroupDialog.Message.BlankName=Gruppenname darf nicht leer sein.
DateLevelDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:
DateLevelDialog.Button.Text.Edit=&Edit...
DateLevelDialog.Title=Datumsebene bearbeiten
DatasetPage.Label.PrimaryDataset=&Primärdatensatz:
DatasetPage.Button.Filter=&Filter...
DatasetPage.Button.Joint=Verknüpfungsdatensatz hinzufügen...
DatasetPage.Title.Title=Kreuztabellen-Cube Builder
DateGroupDialog.Message=Wählen Sie die einzuschließenden Datumsfelder aus.
DateGroupDialog.Message.Regular=Geben Sie den Gruppennamen ein.
DateLevelDialog.Message=Datumstypebene bearbeiten
DateLevelDialog.Message.NumericName=Ebenenname darf keine reine Zahl sein.
DateLevelDialog.Message.BlankName=Ebenenname darf nicht leer sein.
DatasetPage.Title.Message=Datensatz für Quader definieren. 
DatasetPage.Container.Title.Message=Datensatzauswahl
DatasetNodeEditPart.Primary.Dataset=(Primär)
GroupsPage.Title.Title=Kreuztabellen-Cube Builder
GroupsPage.Title.Message=Felder aus den verfügbaren Datensätzen in Gruppierungshierarchien und Zusammenfassungsdatenfelder ziehen. 
GroupsPage.Container.Title.Message=Gruppen und Zusammenfassungen
SimpleCubeBuilder.Title.Title=Kreuztabellen-Cube Builder
SimpleCubeBuilder.Title.Message=Daten für die Kreuztabelle durch das Angeben von Gruppierungshierarchien und Zusammenfassungsdatenfeldern verwalten. 
SimpleCubeBuilder.Title=Kreuztabellen-Cube Builder
SimpleCubeBuilder.Label.Name=Name:
DatasetSelectionPage.Combo.NewDataSet0=<Neuer Datensatz...>
GroupsPage.Button.Add=&Hinzufügen
GroupsPage.Button.Edit=&Bearbeiten
GroupsPage.Button.Delete=&Löschen...
GroupsPage.ArrowButton.Add.Tooltip=Ausgewähltes Feld hinzufügen
GroupsPage.ArrowButton.Remove.Tooltip=Ausgewähltes Feld entfernen
GroupsPage.Label.DataField=Verfügbare Felder:
GroupsPage.Label.Group=Gruppen und Zusammenfassungen:
GroupsPage.Primary.Dataset=(Primär)
GroupsPage.VirtualField.Measure=(Feld hier ablegen, um eine Maßeinheit zu erstellen)
GroupsPage.VirtualField.Level=(Feld hier ablegen, um eine Ebene zu erstellen)
GroupsPage.VirtualField.MeasureGroup=(Feld hier ablegen, um ein Zusammenfassungsfeld zu erstellen)
GroupsPage.VirtualField.Dimension=(Feld hier ablegen, um eine Gruppe zu erstellen)
GroupsPage.Reference=Verweis gefunden
GroupsPage.Clients=\ hat folgende Clients
GroupsPage.Dlg.Confirm=Möchten Sie das Element wirklich löschen?
LinkGroupsPage.Container.Title.Message=Gruppen verknüpfen
LinkGroupsPage.Title.Title=Kreuztabellen-Cube Builder
LinkGroupsPage.Title.Message=Um eine Gruppe aus einem anderen Datensatz mit dem primären Datensatz zu verknüpfen, ziehen Sie ein Feld aus der Gruppe auf ein Feld im primären Datensatz.
LevelDialog.Title=Eigenschaft
LevelDialog.Label.Name=Name:
LevelDialog.Label.Field=Feld wählen:
LevelDialog.Label.DataType=Datentyp:
LevelDialog.Label.Info=Ausgewählter Schlüssel:
LevelDialog.Label.Add=Gruppenebene hinzufügen
LevelDialog.Label.Edit=Gruppenebene bearbeiten
MeasureDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:
MeasureDialog.Button.Text.Edit=&Edit...
MeasureDialog.Title=Eigenschaften
MeasureDialog.Label.Name=&Name:
MeasureDialog.Label.Function=&Funktion:
MeasureDialog.Label.DataType=&Datentyp:
MeasureDialog.Label.Expression=&Ausdruck:
MeasureDialog.Label.LinkTo=&Link To:
MeasureDialog.MessageDialog.Message=Der empfohlene Datentyp für die aktuelle Funktion ist '{0}'. Möchten Sie den ausgewählten Datentypen wirklich beibehalten?
MeasureDialog.MessageDialog.Title=Warnung
MeasureDialog.Title.Property=Eigenschaften des Zusammenfassungsfelds
MeasureDialog.Message.NumericName=Name darf keine reine Zahl sein.
MeasureDialog.Message.BlankName=Einheitenname darf nicht leer sein.
LevelPropertyDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:
LevelPropertyDialog.Title.Add=Gruppenebene hinzufügen
LevelPropertyDialog.Title.Edit=Gruppenebene bearbeiten
LevelPropertyDialog.Member.Access.Control.List.Expression=&Mitglieds-Zugriffssteuerlisten-Ausdruck:
LevelPropertyDialog.Message=Gruppenebene als dynamisch oder statisch definieren und erforderliche Felder ausfüllen
LevelPropertyDialog.Message.NumericName=Eigenschaftsname darf keine reine Zahl sein.
LevelPropertyDialog.Message.BlankName=Eigenschaftsname darf nicht leer sein.
LevelPropertyDialog.None=Ohne
LevelPropertyDialog.GroupBy=Gruppieren nach:
LevelPropertyDialog.Name=&Name:
LevelPropertyDialog.MSG.Static.CreateNew=<Neues Mitglied erstellen>
LevelPropertyDialog.Shell.Title=Gruppenebene
LevelPropertyDialog.Button.Dynamic=D&ynamisch
LevelPropertyDialog.Button.Static=&Statisch
LevelPropertyDialog.DisplayField=&Anzeigefeld:
LevelPropertyDialog.Button.None=Ohne
LevelPropertyDialog.Button.Prefix=Präfix
LevelPropertyDialog.Button.Text.Edit=&Edit...
LevelPropertyDialog.Interval.Base=Festen Basiswert für Intervall verwenden:
LevelPropertyDialog.Label.Property=Ebeneneigenschaft
LevelPropertyDialog.Label.Attribute=Attribut
LevelPropertyDialog.Label.Name=Mitglied
LevelPropertyDialog.KeyField=&Schlüsselfeld:
LevelPropertyDialog.DataType=Daten&typ:
LevelPropertyDialog.Label.Expression=Bedingungsausdruck
LevelPropertyDialog.Label.LinkTo=&Link To:
LevelPropertyDialog.MSG.Dynamic.CreateNew=<Neues Attribut erstellen>
LevelPropertyDialog.MSG.Tooltip=(Alle anderen Werte anzeigen, die in keine dieser Kategorien fallen)
LevelPropertyDialog.MSG.DefaultValue=<Standardwert>

MissLinkDialog.Title=Fehlende Verknüpfung zwischen Datensätzen
MissLinkDialog.Question=Verknüpfen Sie alle Gruppen aus anderen Datensätzen mit dem primären Datensatz, um den Quader abzuschließen
SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Eingabe umbenennen
RenameInputDialog.DialogMessage=Geben Sie den neuen Namen ein.
RenameInputDialog.Message.BlankName=Name darf nicht leer sein.
RenameInputDialog.Message.NumericName=Name darf keine reine Zahl sein.
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Verfügbare Datensätze

DateGroupDialog.Shell.Title=Gruppenebene
DateLevelDialog.Shell.Title=Datumsebene bearbeiten
DateLevelDialog.Interval.Base=Festen Basiswert für Intervall verwenden:
DateGroupDialog.Name=&Name:
DateLevelDialog.Name=&Name:
DateLevelDialog.Type=&Typ:
DateLevelDialog.Format=&Format:
DateLevelDialog.KeyField=Key Field:
DateLevelDialog.Label.LinkTo=&Link To:
DateLevelDialog.None=Ohne

############################################################
#Cube Action properties
NewCubeAction.DataCube=Datenquader
NewCubeAction.trans.cube.new=Create Cube

###########################################################
#CubePageGenerator properties
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=&Primärer Datensatz:
CubePageGenerator.List.General=Allgemein

############################################################
#FilterListDialog properties
FilterListDialog.Shell.Title=Filter
FilterListDialog.Menu.ModifyProperty=Eigenschaft modifizieren
FilterListDialog.Button.AddWithDialog=&Hinzufügen...
FilterListDialog.Button.EditWithDialog=&Bearbeiten...
FilterListDialog.Button.Delete=&Entfernen
