###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=キューブ
cube.new=キューブの新規作成
cube.edit=キューブの編集
CubeNodeProvider.menu.text=編集
cube.dimension.new=キューブの次元の新規作成
cube.dimension.edit=キューブの次元の編集
CubeDimensionNodeProvider.menu.text=編集
cube.level.new=キューブのレベルの新規作成
cube.level.edit=キューブのレベルの編集
CubeLevelNodeProvider.menu.text=編集
cube.measure.new=キューブの計測の新規作成
cube.measure.edit=キューブの計測の編集
CubeMeasureNodeProvider.menu.text=編集
cube.measuregroup.new=キューブの計測グループの新規作成
cube.measure.edit=キューブの計測の編集
CubeMeasureGroupNodeProvider.menu.text=編集
CubeModel.group.edit=グループの編集
Cube.Other.Datasets=Other
CubeModel.summaryfield.edit=サマリフィールドの編集
Cube.Groups=グループ (サイズ)
Cube.MeasureGroup=サマリフィールド (計測)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=クロスタブキューブビルダ
DatasetPage.Title=データセット
GroupsPage.Title=グループ
DatasetPage.Label.Name=キューブ名 :
DatasetPage.Label.PrimaryDataset=プライマリデータセット :
DatasetPage.Button.Filter=フィルタ...
DatasetPage.Button.Joint=ジョイントのデータセットの追加...
DatasetPage.Title.Title=クロスタブキューブビルダ
DatasetPage.Title.Message=キューブのデータセットの定義
DatasetPage.Container.Title.Message=データセットの選択
GroupsPage.Title.Title=クロスタブキューブビルダ
GroupsPage.Title.Message=使用可能なデータセットのフィールドをグループ化の階層とサマリデータフィールドにドラッグしてください。
GroupsPage.Container.Title.Message=グループ
SimpleCubeBuilder.Title.Title=クロスタブキューブビルダ
SimpleCubeBuilder.Title.Message=グループ化の階層とサマリデータフィールドを指定して、クロスタブのデータを編成します。
SimpleCubeBuilder.Title=クロスタブキューブビルダ
SimpleCubeBuilder.Label.Name=名前 :
DatasetPage.Title.Message=キューブのデータセットの定義
GroupsPage.Button.Add=追加(&A)
GroupsPage.Button.Edit=編集(&E)
GroupsPage.Button.Delete=削除(&D)
GroupsPage.Button.Property=プロパティ(&P)
GroupsPage.Button.Join=ジョイントのデータセット(&J)
GroupsPage.Label.DataField=使用可能なデータフィールド :
GroupsPage.Label.Group=グループ :
GroupsPage.Button.Add=追加(&A)
GroupsPage.VirtualField.Measure=(サマリフィールドを作成するには、フィールドをここにドロップします)
GroupsPage.VirtualField.Level=(グループを作成するには、フィールドをここにドロップします)
GroupsPage.Reference=参照が見つかりました。
GroupsPage.Clients=\ には次のクライアントがあります。
GroupsPage.Dlg.Confirm=削除しますか ?
LevelDialog.Title=プロパティ
LevelDialog.Label.Name=名前 :
LevelDialog.Label.Field=フィールドの選択 :
LevelDialog.Label.DataType=データ型 :
LevelDialog.Label.Info=選択済みのキー :
LevelDialog.Label.Add=グループレベルの追加
LevelDialog.Label.Edit=グループレベルの編集
MeasureDialog.Title=プロパティ
MeasureDialog.Label.Name=名前 :
MeasureDialog.Label.Function=関数 :
MeasureDialog.Label.DataType=データ型 :
MeasureDialog.Label.Expression=式 :
MeasureDialog.Label.Info=選択済みのキー :
MeasureDialog.Label.Add=サマリフィールドの追加
MeasureDialog.Label.Edit=サマリフィールドの編集
LevelPropertyDialog.Title=グループレベルのプロパティ
LevelPropertyDialog.MSG.CreateNew=<パラメタの新規作成>
LevelPropertyDialog.Label.Name=名前 :
LevelPropertyDialog.Label.Interval=間隔 :
LevelPropertyDialog.Label.Range=範囲 :
LevelPropertyDialog.Button.IntervalBase=丸めた数値を間隔の基準値として使用する :
LevelPropertyDialog.Label.Info=選択済みのキー :
LevelPropertyDialog.Button.Dynamic=自動設定
LevelPropertyDialog.Button.Static=静的
LevelPropertyDialog.Label.Property=レベルのプロパティ
LevelPropertyDialog.Label.Attribute=属性
LevelPropertyDialog.Label.Name=名前 :
LevelPropertyDialog.Label.Expression=式

###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=名前の変更
RenameInputDialog.DialogMessage=新しい名前を入力してください。
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=使用可能なデータセット

