###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubes
cube.new=Nouveau cube
cube.edit=Modifier le cube
CubeNodeProvider.menu.text=Modifier
cube.dimension.new=Nouvelle dimension de cube
cube.dimension.edit=Modifier la dimension de cube
CubeDimensionNodeProvider.menu.text=Modifier
CubeGroupContent.Message.Add.Message=Noms des champs de récapitulation :
CubeGroupContent.Group.Edit.Message=Nom du groupe :
CubeGroupContent.Measure.Edit.Title=Modifier un champ de récapitulation
cube.level.new=Nouveau niveau de cube
cube.level.edit=Modifier le niveau de cube
CubeLevelNodeProvider.menu.text=Modifier
cube.measure.new=Nouvelle mesure de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureNodeProvider.menu.text=Modifier
CubeGroupContent.Group.Add.Title=Ajouter un groupe
CubeGroupContent.Group.Add.Message=Noms des groupes :
CubeGroupContent.Measure.Add.Title=Ajouter un champ de récapitulation
CubeGroupContent.Group.Edit.Title=Modifier le groupe
cube.measuregroup.new=Nouveau groupe de mesures de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureGroupNodeProvider.menu.text=Modifier
CubeGroupContent.Measure.Edit.Message=Nom du champ de récapitulation :
CubeModel.group.edit=Modifier le groupe
Cube.Other.Datasets=Autre
CubeModel.summaryfield.edit=Modifier le champ de récapitulation
Cube.Groups=Groupes (Dimensions)
Cube.MeasureGroup=Champs de récapitulation (Mesures)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Générateur de cube de tableau croisé
DatasetPage.Title=Jeu de données
GroupsPage.Title=Groupes et résumés
LinkGroupsPage.Title=Lier les groupes
DatasetPage.Label.Name=&Nom :
DateGroupDialog.Title=Ajouter/Modifier le niveau de groupe
DateLevelDialog.Title=Modifier le niveau de date
DatasetPage.Label.PrimaryDataset=Jeu de données &principal :
DatasetPage.Button.Filter=&Filtre...
DatasetPage.Button.Joint=Ajouter des jeux de données de jointure...
DatasetPage.Title.Title=Générateur de cube de tableau croisé
DateGroupDialog.Message=Sélectionnez les champs de date à inclure.
DateLevelDialog.Message=Modifier le niveau de type de date
DatasetPage.Title.Message=Définissez le jeu de données pour le cube
DatasetPage.Container.Title.Message=Sélection du jeu de données
DatasetNodeEditPart.Primary.Dataset=(Principal)
GroupsPage.Title.Title=Générateur de cube de tableau croisé
GroupsPage.Title.Message=Faites glisser les champs des jeux de données disponibles vers des hiérarchies de groupes et des champs de données de récapitulation
GroupsPage.Container.Title.Message=Groupes et résumés
SimpleCubeBuilder.Title.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Title.Message=Organisez vos données du tableau croisé en précisant les hiérarchies de groupes et les champs de données de récapitulation
SimpleCubeBuilder.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Label.Name=Nom :
DatasetPage.Title.Message=Définissez le jeu de données pour le cube
GroupsPage.Button.Add=&Ajouter
GroupsPage.Button.Edit=&Modifier
GroupsPage.Button.Delete=&Supprimer
GroupsPage.Label.DataField=Champs disponibles :
GroupsPage.Label.Group=Groupes et résumés :
GroupsPage.Primary.Dataset=(Principal)
GroupsPage.VirtualField.Measure=(Déposez un champ ici pour créer une mesure)
GroupsPage.VirtualField.Level=(Déposez un champ ici pour créer un niveau)
GroupsPage.VirtualField.MeasureGroup=(Déposez un champ ici pour créer un champ de récapitulation)
GroupsPage.VirtualField.Dimension=(Déposez un champ ici pour créer un groupe)
GroupsPage.Reference=Référence trouvée
GroupsPage.Clients=\ a les clients suivants
GroupsPage.Dlg.Confirm=Voulez-vous vraiment supprimer cet élément ?
LinkGroupsPage.Container.Title.Message=Lier les groupes
LinkGroupsPage.Title.Title=Générateur de cube de tableau croisé
LinkGroupsPage.Title.Message=Créez des liens en sélectionnant un champ à partir d'une dimension et en le faisant glisser vers un champ de jeu de données.
LevelDialog.Title=Propriété
LevelDialog.Label.Name=Nom :
LevelDialog.Label.Field=Sélection de champ :
LevelDialog.Label.DataType=Type de données :
LevelDialog.Label.Info=Clé sélectionnée :
LevelDialog.Label.Add=Ajouter un niveau de groupe
LevelDialog.Label.Edit=Modifier un niveau de groupe
MeasureDialog.Title=Propriétés
MeasureDialog.Label.Name=Nom :
MeasureDialog.Label.Function=Fonction :
MeasureDialog.Label.DataType=Type de données :
MeasureDialog.Label.Expression=Expression :
MeasureDialog.Title.Property=Propriétés du champ de récapitulation
LevelPropertyDialog.Title.Add=Ajouter un niveau de groupe
LevelPropertyDialog.Title.Edit=Modifier un niveau de groupe
LevelPropertyDialog.Message=Choisissez entre un niveau de groupe dynamique ou statique et remplissez les champs requis
LevelPropertyDialog.None=Aucun
LevelPropertyDialog.GroupBy=Grouper par :
LevelPropertyDialog.Name=Nom :
LevelPropertyDialog.MSG.Static.CreateNew=<Créer un nouveau membre>
LevelPropertyDialog.Label.Name=Membre
LevelPropertyDialog.Label.Interval=Intervalle :
LevelPropertyDialog.Label.Range=Plage :
LevelPropertyDialog.Shell.Title=Niveau de groupe
LevelPropertyDialog.Button.Interval=Intervalle
LevelPropertyDialog.Label.Info=Clé sélectionnée :
LevelPropertyDialog.Button.Dynamic=Dynamique
LevelPropertyDialog.Button.Static=Statique
LevelPropertyDialog.DisplayField=Afficher le champ :
LevelPropertyDialog.Button.None=Aucun
LevelPropertyDialog.Button.Prefix=Préfixe
LevelPropertyDialog.Interval.Base=Utiliser une valeur de base fixe pour l'intervalle :
LevelPropertyDialog.Label.Property=Propriété de niveau
LevelPropertyDialog.Label.Attribute=Attribut
LevelPropertyDialog.Label.Name=Membre
LevelPropertyDialog.KeyField=Champ clé :
LevelPropertyDialog.DataType=Type de données :
LevelPropertyDialog.Label.Expression=Expression de condition
LevelPropertyDialog.MSG.Dynamic.CreateNew=<Créer un nouvel attribut>
MissLinkDialog.Title=Lien manquant entre les jeux de données
MissLinkDialog.Question=Lier le champ de données du jeu de données principal aux autres jeux de données pour créer un cube
SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Renommer l'entrée
RenameInputDialog.DialogMessage=Saisissez le nouveau nom
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Jeux de données disponibles

DateGroupDialog.Shell.Title=Niveau de groupe
DateLevelDialog.Shell.Title=Modifier le niveau de date
DateLevelDialog.Interval.Base=Utiliser une valeur de base fixe pour l'intervalle :
DateGroupDialog.Name=Nom :
DateLevelDialog.Name=Nom :
DateLevelDialog.Type=Type :
DateLevelDialog.Format=Format:
DateLevelDialog.None=Aucun
FilterListDialog.Shell.Title=Filtre

############################################################
#Cube Action properties
NewCubeAction.DataCube=Cube de données
