###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Quader
cube.new=Neuer Quader
cube.edit=Quader bearbeiten
CubeNodeProvider.menu.text=Bearbeiten
cube.dimension.new=Neue Quaderdimension
cube.dimension.edit=Quaderdimension bearbeiten
CubeDimensionNodeProvider.menu.text=Bearbeiten
CubeGroupContent.Message.Add.Message=Namen der Zusammenfassungsfelder:
CubeGroupContent.Group.Edit.Message=Gruppenname:
CubeGroupContent.Measure.Edit.Title=Zusammenfassungsfeld bearbeiten
cube.level.new=Neue Quaderebene
cube.level.edit=Quaderebene bearbeiten
CubeLevelNodeProvider.menu.text=Bearbeiten
cube.measure.new=Neue Quadereinheit
cube.measure.edit=Quadereinheit bearbeiten
CubeMeasureNodeProvider.menu.text=Bearbeiten
CubeGroupContent.Group.Add.Title=Gruppe hinzufügen
CubeGroupContent.Group.Add.Message=Gruppennamen:
CubeGroupContent.Measure.Add.Title=Zusammenfassungsfeld hinzufügen
CubeGroupContent.Group.Edit.Title=Gruppe bearbeiten
cube.measuregroup.new=Neue Quadereinheitsgruppe
cube.measure.edit=Quadereinheit bearbeiten
CubeMeasureGroupNodeProvider.menu.text=Bearbeiten
CubeGroupContent.Measure.Edit.Message=Name des Zusammenfassungsfelds:
CubeModel.group.edit=Gruppe bearbeiten
Cube.Other.Datasets=Andere
CubeModel.summaryfield.edit=Zusammenfassungsfeld bearbeiten
Cube.Groups=Gruppen (Dimensionen)
Cube.MeasureGroup=Zusammenfassungsfelder (Einheiten)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Kreuztabellen-Cube Builder
DatasetPage.Title=Datensatz
GroupsPage.Title=Gruppen und Zusammenfassungen
LinkGroupsPage.Title=Gruppen verknüpfen
DatasetPage.Label.Name=&Name:
DateGroupDialog.Title=Gruppenebene hinzufügen/bearbeiten
DateLevelDialog.Title=Datumsebene bearbeiten
DatasetPage.Label.PrimaryDataset=&Primärdatensatz:
DatasetPage.Button.Filter=&Filter...
DatasetPage.Button.Joint=Verknüpfungsdatensatz hinzufügen...
DatasetPage.Title.Title=Kreuztabellen-Cube Builder
DateGroupDialog.Message=Wählen Sie die einzuschließenden Datumsfelder aus.
DateLevelDialog.Message=Datumstypebene bearbeiten
DatasetPage.Title.Message=Datensatz für Quader definieren
DatasetPage.Container.Title.Message=Datensatzauswahl
DatasetNodeEditPart.Primary.Dataset=(Primär)
GroupsPage.Title.Title=Kreuztabellen-Cube Builder
GroupsPage.Title.Message=Felder aus den verfügbaren Datensätzen in Gruppierungshierarchien und Zusammenfassungsdatenfelder ziehen
GroupsPage.Container.Title.Message=Gruppen und Zusammenfassungen
SimpleCubeBuilder.Title.Title=Kreuztabellen-Cube Builder
SimpleCubeBuilder.Title.Message=Daten für die Kreuztabelle durch das Angeben von Gruppierungshierarchien und Zusammenfassungsdatenfeldern verwalten
SimpleCubeBuilder.Title=Kreuztabellen-Cube Builder
SimpleCubeBuilder.Label.Name=Name:
DatasetPage.Title.Message=Datensatz für Quader definieren
GroupsPage.Button.Add=&Hinzufügen
GroupsPage.Button.Edit=&Bearbeiten
GroupsPage.Button.Delete=&Löschen...
GroupsPage.Label.DataField=Verfügbare Felder:
GroupsPage.Label.Group=Gruppen und Zusammenfassungen:
GroupsPage.Primary.Dataset=(Primär)
GroupsPage.VirtualField.Measure=(Feld hier ablegen, um eine Maßeinheit zu erstellen)
GroupsPage.VirtualField.Level=(Feld hier ablegen, um eine Ebene zu erstellen)
GroupsPage.VirtualField.MeasureGroup=(Feld hier ablegen, um ein Zusammenfassungsfeld zu erstellen)
GroupsPage.VirtualField.Dimension=(Feld hier ablegen, um eine Gruppe zu erstellen)
GroupsPage.Reference=Verweis gefunden
GroupsPage.Clients=\ hat folgende Clients
GroupsPage.Dlg.Confirm=Möchten Sie das Element wirklich löschen?
LinkGroupsPage.Container.Title.Message=Gruppen verknüpfen
LinkGroupsPage.Title.Title=Kreuztabellen-Cube Builder
LinkGroupsPage.Title.Message=To link a group from another data set to the primary data set, drag a field form the group to a field in the primary data set
LevelDialog.Title=Eigenschaft
LevelDialog.Label.Name=Name:
LevelDialog.Label.Field=Feld wählen:
LevelDialog.Label.DataType=Datentyp:
LevelDialog.Label.Info=Ausgewählter Schlüssel:
LevelDialog.Label.Add=Gruppenebene hinzufügen
LevelDialog.Label.Edit=Gruppenebene bearbeiten
MeasureDialog.Title=Eigenschaften
MeasureDialog.Label.Name=Name:
MeasureDialog.Label.Function=Funktion:
MeasureDialog.Label.DataType=Datentyp:
MeasureDialog.Label.Expression=Ausdruck:
MeasureDialog.Title.Property=Eigenschaften des Zusammenfassungsfelds
LevelPropertyDialog.Title.Add=Gruppenebene hinzufügen
LevelPropertyDialog.Title.Edit=Gruppenebene bearbeiten
LevelPropertyDialog.Message=Gruppenebene als dynamisch oder statisch definieren und erforderliche Felder ausfüllen
LevelPropertyDialog.None=Ohne
LevelPropertyDialog.GroupBy=Gruppieren nach:
LevelPropertyDialog.Name=Name:
LevelPropertyDialog.MSG.Static.CreateNew=<Neues Mitglied erstellen>
LevelPropertyDialog.Label.Name=Mitglied
LevelPropertyDialog.Label.Interval=Intervall:
LevelPropertyDialog.Label.Range=Bereich:
LevelPropertyDialog.Shell.Title=Gruppenebene
LevelPropertyDialog.Button.Interval=Intervall
LevelPropertyDialog.Label.Info=Ausgewählter Schlüssel:
LevelPropertyDialog.Button.Dynamic=Dynamisch
LevelPropertyDialog.Button.Static=Statisch
LevelPropertyDialog.DisplayField=Anzeigefeld:
LevelPropertyDialog.Button.None=Ohne
LevelPropertyDialog.Button.Prefix=Präfix
LevelPropertyDialog.Interval.Base=Festen Basiswert für Intervall verwenden:
LevelPropertyDialog.Label.Property=Ebeneneigenschaft
LevelPropertyDialog.Label.Attribute=Attribut
LevelPropertyDialog.Label.Name=Mitglied
LevelPropertyDialog.KeyField=Schlüsselfeld:
LevelPropertyDialog.DataType=Datentyp:
LevelPropertyDialog.Label.Expression=Bedingungsausdruck
LevelPropertyDialog.MSG.Dynamic.CreateNew=<Neues Attribut erstellen>
MissLinkDialog.Title=Fehlende Verknüpfung zwischen Datensätzen
MissLinkDialog.Question=Link all groups from other data sets to the primary data set to complete the cube
SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Eingabe umbenennen
RenameInputDialog.DialogMessage=Geben Sie den neuen Namen ein.
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Verfügbare Datensätze

DateGroupDialog.Shell.Title=Gruppenebene
DateLevelDialog.Shell.Title=Datumsebene bearbeiten
DateLevelDialog.Interval.Base=Festen Basiswert für Intervall verwenden:
DateGroupDialog.Name=Name:
DateLevelDialog.Name=Name:
DateLevelDialog.Type=Typ:
DateLevelDialog.Format=Format:
DateLevelDialog.None=Ohne
FilterListDialog.Shell.Title=Filters

############################################################
#Cube Action properties
NewCubeAction.DataCube=Datenquader

CubeBuilder.warning.title=Cross Tab
CubeBuilder.warning.message=A data cube has been created successfully.\nTo finish creating a cross tab, drag the fields from the created data cube to the cross tab container.
CubeBuilder.warning.prompt=Don't show this message again
