###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=큐브
cube.new=새 큐브
cube.edit=큐브 편집
CubeNodeProvider.menu.text=편집
cube.dimension.new=새 큐브 차원
cube.dimension.edit=큐브 차원 편집
CubeDimensionNodeProvider.menu.text=편집
cube.level.new=새 큐브 수준
cube.level.edit=큐브 수준 편집
CubeLevelNodeProvider.menu.text=편집
cube.measure.new=새 큐브 측정값
cube.measure.edit=큐브 측정값 편집
CubeMeasureNodeProvider.menu.text=편집
cube.measuregroup.new=새 큐브 측정값 그룹
cube.measure.edit=큐브 측정값 편집
CubeMeasureGroupNodeProvider.menu.text=편집
CubeModel.group.edit=그룹 편집
Cube.Other.Datasets=Other
CubeModel.summaryfield.edit=요약 필드 편집
Cube.Groups=그룹(차원)
Cube.MeasureGroup=요약 필드(측정값)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=크로스 탭 큐브 빌더
DatasetPage.Title=데이터 집합
GroupsPage.Title=그룹
DatasetPage.Label.Name=큐브 이름:
DatasetPage.Label.PrimaryDataset=기본 데이터 집합:
DatasetPage.Button.Filter=필터...
DatasetPage.Button.Joint=조인 데이터 집합 추가...
DatasetPage.Title.Title=크로스 탭 큐브 빌더
DatasetPage.Title.Message=큐브에 대한 데이터 집합 정의
DatasetPage.Container.Title.Message=데이터 집합 선택
GroupsPage.Title.Title=크로스 탭 큐브 빌더
GroupsPage.Title.Message=사용 가능한 데이터 집합에서 필드를 끌어 그룹화 계층 및 요약 데이터 필드에 놓으십시오.
GroupsPage.Container.Title.Message=그룹
SimpleCubeBuilder.Title.Title=크로스 탭 큐브 빌더
SimpleCubeBuilder.Title.Message=그룹화 계층 및 요약 데이터 필드를 지정하여 크로스 탭의 데이터를 구성하십시오.
SimpleCubeBuilder.Title=크로스 탭 큐브 빌더
SimpleCubeBuilder.Label.Name=이름:
DatasetPage.Title.Message=큐브에 대한 데이터 집합 정의
GroupsPage.Button.Add=추가(&A)
GroupsPage.Button.Edit=편집(&E)
GroupsPage.Button.Delete=삭제(&D)
GroupsPage.Button.Property=속성(&P)
GroupsPage.Button.Join=조인 데이터 집합(&J)
GroupsPage.Label.DataField=사용 가능한 데이터 필드:
GroupsPage.Label.Group=그룹:
GroupsPage.Button.Add=추가(&A)
GroupsPage.VirtualField.Measure=(요약 필드를 생성하려면 여기에 필드를 내려 놓으십시오)
GroupsPage.VirtualField.Level=(그룹을 생성하려면 여기에 필드를 내려 놓으십시오)
GroupsPage.Reference=Reference Found
GroupsPage.Clients=\ has following clients
GroupsPage.Dlg.Confirm=Do you really want to delete it?
LevelDialog.Title=속성
LevelDialog.Label.Name=이름:
LevelDialog.Label.Field=필드 선택:
LevelDialog.Label.DataType=데이터 형식:
LevelDialog.Label.Info=선택된 키:
LevelDialog.Label.Add=그룹 수준 추가
LevelDialog.Label.Edit=그룹 수준 편집
MeasureDialog.Title=속성
MeasureDialog.Label.Name=이름:
MeasureDialog.Label.Function=함수:
MeasureDialog.Label.DataType=데이터 형식:
MeasureDialog.Label.Expression=식:
MeasureDialog.Label.Info=선택된 키:
MeasureDialog.Label.Add=요약 필드 추가
MeasureDialog.Label.Edit=요약 필드 편집
LevelPropertyDialog.Title=그룹 수준 속성
LevelPropertyDialog.MSG.CreateNew=<새 매개 변수 생성>
LevelPropertyDialog.Label.Name=이름:
LevelPropertyDialog.Label.Interval=간격:
LevelPropertyDialog.Label.Range=범위:
LevelPropertyDialog.Button.IntervalBase=고정된 기본값을 간격으로 사용:
LevelPropertyDialog.Label.Info=선택된 키:
LevelPropertyDialog.Button.Dynamic=동적
LevelPropertyDialog.Button.Static=정적
LevelPropertyDialog.Label.Property=수준 속성
LevelPropertyDialog.Label.Attribute=특성
LevelPropertyDialog.Label.Name=이름:
LevelPropertyDialog.Label.Expression=식

###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=이름 바꾸기 입력
RenameInputDialog.DialogMessage=새 이름을 입력하십시오.
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=사용 가능한 데이터 집합

