###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=データキューブ
cube.new=データキューブの新規作成
cube.edit=データキューブの編集
CubeNodeProvider.menu.text=Edit
cube.dimension.new=次元の新規作成
cube.dimension.edit=次元の編集
CubeDimensionNodeProvider.menu.text=Edit
cube.level.new=レベルの新規作成
cube.level.edit=キューブのレベルの編集
CubeLevelNodeProvider.menu.text=Edit
cube.measure.new=計測の新規作成
cube.measure.edit=計測の編集
CubeMeasureNodeProvider.menu.text=Edit
cube.measuregroup.new=計測グループの新規作成
cube.measure.edit=計測の編集
CubeMeasureGroupNodeProvider.menu.text=Edit
CubeModel.group.edit=Edit Group
CubeModel.summaryfield.edit=Edit Summary Field
Cube.Groups=Groups (Dimensions)
Cube.MeasureGroup=Summary Fields (Measures)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Cross Tab Cube Builder
DatasetPage.Title=Dataset
GroupsPage.Title=Group
DatasetPage.Label.Name=Cube name:
DatasetPage.Label.PrimaryDataset=Primary dataset:
DatasetPage.Button.Filter=Filter...
DatasetPage.Button.Joint=Add joint datasets...
DatasetPage.Title.Title=Cross Tab Cube Builder
DatasetPage.Title.Message=Define data set for the cube
DatasetPage.Container.Title.Message=Dataset Selection
GroupsPage.Title.Title=Cross Tab Cube Builder
GroupsPage.Title.Message=Please drag fields from the available data sets to grouping hierarchies and summary data fields
GroupsPage.Container.Title.Message=Group
SimpleCubeBuilder.Title.Title=Cross Tab Cube Builder
SimpleCubeBuilder.Title.Message=Organize your data for the cross tab by specifying grouping hierarchies and summary data fields
SimpleCubeBuilder.Title=Cross Tab Cube Builder
SimpleCubeBuilder.Label.Name=Name:
DatasetPage.Title.Message=Define data set for the cube
GroupsPage.Button.Add=&Add
GroupsPage.Button.Edit=&Edit
GroupsPage.Button.Delete=&Delete
GroupsPage.Button.Property=&Property
GroupsPage.Button.Join=&Joint Data Set
GroupsPage.Label.DataField=Available data fields:
GroupsPage.Label.Group=Groups:
GroupsPage.Button.Add=&Add
GroupsPage.VirtualField.Measure=(Drop a field here to create a summary field)
GroupsPage.VirtualField.Level=(Drop a field here to create a group)
LevelDialog.Title=Property
LevelDialog.Label.Name=Name:
LevelDialog.Label.Field=Choose Field:
LevelDialog.Label.DataType=Data Type:
LevelDialog.Label.Info=Selected Key:
LevelDialog.Label.Add=Add Group Level
LevelDialog.Label.Edit=Edit Group Level
MeasureDialog.Title=Property
MeasureDialog.Label.Name=Name:
MeasureDialog.Label.Function=Function:
MeasureDialog.Label.DataType=Data Type:
MeasureDialog.Label.Expression=Expression:
MeasureDialog.Label.Info=Selected Key:
MeasureDialog.Label.Add=Add Summary Field
MeasureDialog.Label.Edit=Edit Summary Field
LevelPropertyDialog.Title=Group Level Property
LevelPropertyDialog.MSG.CreateNew=<Create New Parameter>
LevelPropertyDialog.Label.Name=Name:
LevelPropertyDialog.Label.Interval=Interval:
LevelPropertyDialog.Label.Range=Range:
LevelPropertyDialog.Button.IntervalBase=Use fixed base value for interval:
LevelPropertyDialog.Label.Info=Selected Key:
LevelPropertyDialog.Button.Dynamic=Dynamic
LevelPropertyDialog.Button.Static=Static
LevelPropertyDialog.Label.Property=Level Property
LevelPropertyDialog.Label.Attribute=Attribute
LevelPropertyDialog.Label.Name=Name:
LevelPropertyDialog.Label.Expression=Expression

###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Rename Input
RenameInputDialog.DialogMessage=Please input the new name
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Available Data Sets
