###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubes
cube.new=Nouveau cube
cube.edit=Modifier le cube
CubeNodeProvider.menu.text=Modifier
cube.dimension.new=Nouvelle dimension de cube
cube.dimension.edit=Modifier la dimension de cube
CubeDimensionNodeProvider.menu.text=Modifier
cube.level.new=Nouveau niveau de cube
cube.level.edit=Modifier le niveau de cube
CubeLevelNodeProvider.menu.text=Modifier
cube.measure.new=Nouvelle mesure de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureNodeProvider.menu.text=Modifier
cube.measuregroup.new=Nouveau groupe de mesures de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureGroupNodeProvider.menu.text=Modifier
CubeModel.group.edit=Modifier le groupe
Cube.Other.Datasets=Other
CubeModel.summaryfield.edit=Modifier le champ de récapitulation
Cube.Groups=Groupes (Dimensions)
Cube.MeasureGroup=Champs de récapitulation (Mesures)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Générateur de cube de tableau croisé
DatasetPage.Title=Jeu de données
GroupsPage.Title=Groupe
DatasetPage.Label.Name=Nom du cube :
DatasetPage.Label.PrimaryDataset=Jeu de données principal :
DatasetPage.Button.Filter=Filtre...
DatasetPage.Button.Joint=Ajouter des jeux de données de jointure...
DatasetPage.Title.Title=Générateur de cube de tableau croisé
DatasetPage.Title.Message=Définissez le jeu de données pour le cube
DatasetPage.Container.Title.Message=Sélection du jeu de données
GroupsPage.Title.Title=Générateur de cube de tableau croisé
GroupsPage.Title.Message=Faites glisser les champs des jeux de données disponibles vers des hiérarchies de groupes et des champs de données de récapitulation
GroupsPage.Container.Title.Message=Groupe
SimpleCubeBuilder.Title.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Title.Message=Organisez vos données du tableau croisé en précisant les hiérarchies de groupes et les champs de données de récapitulation
SimpleCubeBuilder.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Label.Name=Nom :
DatasetPage.Title.Message=Définissez le jeu de données pour le cube
GroupsPage.Button.Add=&Ajouter
GroupsPage.Button.Edit=&Modifier
GroupsPage.Button.Delete=&Supprimer
GroupsPage.Button.Property=&Propriété
GroupsPage.Button.Join=&Jeu de données de jointure
GroupsPage.Label.DataField=Champs de données disponibles :
GroupsPage.Label.Group=Groupes :
GroupsPage.Button.Add=&Ajouter
GroupsPage.VirtualField.Measure=(Ignorez un champ ici pour créer un champ de récapitulation)
GroupsPage.VirtualField.Level=(Ignorez un champ ici pour créer un groupe)
GroupsPage.Reference=Reference Found
GroupsPage.Clients=\ has following clients
GroupsPage.Dlg.Confirm=Do you really want to delete it?
LevelDialog.Title=Propriété
LevelDialog.Label.Name=Nom :
LevelDialog.Label.Field=Sélection de champ :
LevelDialog.Label.DataType=Type de données :
LevelDialog.Label.Info=Clé sélectionnée :
LevelDialog.Label.Add=Ajouter un niveau de groupe
LevelDialog.Label.Edit=Modifier un niveau de groupe
MeasureDialog.Title=Propriété
MeasureDialog.Label.Name=Nom :
MeasureDialog.Label.Function=Fonction :
MeasureDialog.Label.DataType=Type de données :
MeasureDialog.Label.Expression=Expression :
MeasureDialog.Label.Info=Clé sélectionnée :
MeasureDialog.Label.Add=Ajouter un champ de récapitulation
MeasureDialog.Label.Edit=Modifier un champ de récapitulation
LevelPropertyDialog.Title=Priorité de niveau de groupe
LevelPropertyDialog.MSG.CreateNew=<Créer un paramètre>
LevelPropertyDialog.Label.Name=Nom :
LevelPropertyDialog.Label.Interval=Intervalle :
LevelPropertyDialog.Label.Range=Plage :
LevelPropertyDialog.Button.IntervalBase=Utiliser une valeur de base fixe pour l'intervalle :
LevelPropertyDialog.Label.Info=Clé sélectionnée :
LevelPropertyDialog.Button.Dynamic=Dynamique
LevelPropertyDialog.Button.Static=Statique
LevelPropertyDialog.Label.Property=Propriété de niveau
LevelPropertyDialog.Label.Attribute=Attribut
LevelPropertyDialog.Label.Name=Nom :
LevelPropertyDialog.Label.Expression=Expression

###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Renommer l'entrée
RenameInputDialog.DialogMessage=Saisissez le nouveau nom
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Jeux de données disponibles

