###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=多维数据集
cube.new=新建多维数据集
cube.edit=编辑多维数据集
CubeNodeProvider.menu.text=编辑
cube.dimension.new=新建多维数据集维
cube.dimension.edit=编辑多维数据集维
CubeDimensionNodeProvider.menu.text=编辑
cube.level.new=新建多维数据集级别
cube.level.edit=编辑多维数据集级别
CubeLevelNodeProvider.menu.text=编辑
cube.measure.new=新建多维数据集度量
cube.measure.edit=编辑多维数据集度量
CubeMeasureNodeProvider.menu.text=编辑
cube.measuregroup.new=新建多维数据集度量组
cube.measure.edit=编辑多维数据集度量
CubeMeasureGroupNodeProvider.menu.text=编辑
CubeModel.group.edit=编辑组
Cube.Other.Datasets=Other
CubeModel.summaryfield.edit=编辑摘要字段
Cube.Groups=组(维)
Cube.MeasureGroup=摘要字段(度量)

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=交叉表多维数据集生成器
DatasetPage.Title=数据集
GroupsPage.Title=组
DatasetPage.Label.Name=多维数据集名称:
DatasetPage.Label.PrimaryDataset=主数据集:
DatasetPage.Button.Filter=筛选...
DatasetPage.Button.Joint=添加联接数据集...
DatasetPage.Title.Title=交叉表多维数据集生成器
DatasetPage.Title.Message=为多维数据集定义数据集
DatasetPage.Container.Title.Message=数据集选择
GroupsPage.Title.Title=交叉表多维数据集生成器
GroupsPage.Title.Message=请将字段从可用的数据集拖动到分组层次结构和摘要数据字段
GroupsPage.Container.Title.Message=组
SimpleCubeBuilder.Title.Title=交叉表多维数据集生成器
SimpleCubeBuilder.Title.Message=通过指定分组层次结构和摘要数据字段来为交叉表组织数据
SimpleCubeBuilder.Title=交叉表多维数据集生成器
SimpleCubeBuilder.Label.Name=名称:
DatasetPage.Title.Message=为多维数据集定义数据集
GroupsPage.Button.Add=添加(&A)
GroupsPage.Button.Edit=编辑(&E)
GroupsPage.Button.Delete=删除(&D)
GroupsPage.Button.Property=属性(&P)
GroupsPage.Button.Join=联接数据集(&J)
GroupsPage.Label.DataField=可用数据字段:
GroupsPage.Label.Group=组:
GroupsPage.Button.Add=添加(&A)
GroupsPage.VirtualField.Measure=（将字段拖至此处以创建摘要字段）
GroupsPage.VirtualField.Level=（将字段拖至此处以创建组）
GroupsPage.Reference=Reference Found
GroupsPage.Clients=\ has following clients
GroupsPage.Dlg.Confirm=Do you really want to delete it?
LevelDialog.Title=属性
LevelDialog.Label.Name=名称:
LevelDialog.Label.Field=选择字段:
LevelDialog.Label.DataType=数据类型:
LevelDialog.Label.Info=选择的关键字:
LevelDialog.Label.Add=添加组级别
LevelDialog.Label.Edit=编辑组级别
MeasureDialog.Title=属性
MeasureDialog.Label.Name=名称:
MeasureDialog.Label.Function=函数:
MeasureDialog.Label.DataType=数据类型:
MeasureDialog.Label.Expression=表达式:
MeasureDialog.Label.Info=选择的关键字:
MeasureDialog.Label.Add=添加摘要字段
MeasureDialog.Label.Edit=编辑摘要字段
LevelPropertyDialog.Title=组级别属性
LevelPropertyDialog.MSG.CreateNew=<创建新参数>
LevelPropertyDialog.Label.Name=名称:
LevelPropertyDialog.Label.Interval=间隔:
LevelPropertyDialog.Label.Range=范围:
LevelPropertyDialog.Button.IntervalBase=对间隔使用固定基值:
LevelPropertyDialog.Label.Info=选择的关键字:
LevelPropertyDialog.Button.Dynamic=动态
LevelPropertyDialog.Button.Static=静态
LevelPropertyDialog.Label.Property=级别属性
LevelPropertyDialog.Label.Attribute=属性
LevelPropertyDialog.Label.Name=名称:
LevelPropertyDialog.Label.Expression=表达式

###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=重命名输入
RenameInputDialog.DialogMessage=请输入新名称
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=可用数据集

