###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=キューブ

cube.new=キューブの新規作成

cube.action.new=データキューブの新規作成(&C)

cube.edit=キューブの編集

CubeNodeProvider.menu.text=編集(&E)

cube.dimension.new=キューブのディメンションの新規作成

cube.dimension.edit=キューブのディメンションの編集

CubeDimensionNodeProvider.menu.text=編集(&E)

CubeGroupContent.Message.Add.Message=サマリフィールド名 :

CubeGroupContent.Group.Edit.Message=グループ名 :

CubeGroupContent.Measure.Edit.Title=サマリフィールドの編集

cube.level.new=キューブのレベルの新規作成

cube.level.edit=レベルの編集

CubeLabelProvider.SharedDimensions=共有ディメンション

CubeLevelNodeProvider.menu.text=編集(&E)

cube.measure.new=キューブのメジャーの新規作成

cube.measure.edit=キューブのメジャーの編集

CubeMeasureNodeProvider.menu.text=編集(&E)

CubeGroupContent.Group.Add.Title=グループの追加

CubeGroupContent.Group.Add.Message=グループ名(&N) :

CubeGroupContent.Measure.Add.Title=サマリフィールドの追加

CubeGroupContent.Group.Edit.Title=グループの編集

cube.measuregroup.new=キューブのメジャーグループの新規作成

cube.measuregroup.edit=キューブのメジャーの編集

CubeMeasureGroupNodeProvider.menu.text=編集(&E)

CubeGroupContent.Measure.Edit.Message=サマリフィールド名 :

CubeModel.group.edit=グループの編集(&E)

Cube.Other.Datasets=その他

CubeModel.summaryfield.edit=サマリフィールドの編集(&E)

Cube.Groups=グループ (ディメンション)

Cube.MeasureGroup=サマリフィールド (メジャー)

CubeGroupContent.MeasureDataTypeErrorDialog.Message=メジャーでは Any 型のデータを使用できません。別のデータ列を選択するか、列 "{0}" のデータ型を変更してください。

CubeGroupContent.MeasureDataTypeErrorDialog.Title=警告
###########################################################
#Cube Builder Dialog properties
CubeBuilder.AutoPrimaryKeyDialog.Message=ジョインキーとして使用されている列の中に、レベルで定義されていないものがあります。「自動プライマリキー」オプションを確認して、キューブを完成しますか ?

CubeBuilder.AutoPrimaryKeyDialog.Title=自動プライマリキーの問題

CubeBuilder.SharedDimensionErrorLinkDialog.Message=共有ディメンションのすべてのプライマリキーはリンクされている必要があります。不明なリンクを定義してキューブを完成しますか ?

CubeBuilder.SharedDimensionErrorLinkDialog.Title=不明な共有ディメンションリンク

CubeBuilder.Title=データキューブビルダ

DatasePage.EmptyName.ErrorMessage=キューブの名前を指定する必要があります。

DatasetPage.Title=データセット

GroupDialog.Access.Control.List.Expression=アクセスコントロールリストの式(&A) :

GroupDialog.Button.DateGroup=日付グループ(&D)

GroupDialog.Button.RegularGroup=通常グループ(&R)

GroupRenameDialog.Access.Control.List.Expression=アクセスコントロールリストの式(&A) :

GroupsPage.Title=グループとサマリ

LinkGroupsPage.Title=リンクグループ

DatasetPage.Label.Name=名前(&N):

DateGroupDialog.Title=グループレベルの追加と編集

DateGroupDialog.Message.NumericName=グループ名に数字のみを指定することはできません。

DateGroupDialog.Message.DuplicateName=この名前はすでに使われています。

DateGroupDialog.Message.BlankName=グループ名は空白にできません。

DateLevelDialog.Access.Control.List.Expression=アクセスコントロールリストの式(&A) :

DateLevelDialog.Button.Text.Edit=編集(&E)...

DateLevelDialog.Title=日付レベルの編集

DatasetPage.Label.PrimaryDataset=プライマリデータセット(&P) :

DatasetPage.Button.Filter=フィルタ(&F)...

DatasetPage.Button.Joint=ジョインデータセットの追加...

DatasetPage.Title.Title=データセット

DateGroupDialog.Message=含める日付フィールドを選択してください。

DateGroupDialog.Message.Regular=グループ名を入力してください。

DateLevelDialog.Message=日付型レベルの編集

DateLevelDialog.Message.NumericName=レベル名に数字のみを指定することはできません。

DateLevelDialog.Message.BlankName=レベル名は空白にできません。

DatasetPage.Title.Message=キューブのデータセットを定義します。

DatasetPage.Container.Title.Message=データセットの選択

DatasetNodeEditPart.Primary.Dataset=(プライマリ)

GroupsPage.Title.Title=グループとサマリ

GroupsPage.Title.Message=使用可能なデータセットのフィールドをグループ化の階層とサマリデータフィールドにドラッグしてください。

GroupsPage.Container.Title.Message=グループとサマリ

SimpleCubeBuilder.Title.Title=クロスタブキューブビルダ

SimpleCubeBuilder.Title.Message=グループ化の階層とサマリデータフィールドを指定して、クロスタブのデータを編成します。

SimpleCubeBuilder.Title=クロスタブキューブビルダ

SimpleCubeBuilder.Label.Name=名前:

DatasetSelectionPage.Label.Auto.Primary.Key=キューブ生成中にプライマリデータセット内での事前集計を回避する場合、このオプションをオンにする(&C)

DatasetSelectionPage.Text.Auto.Primary.Key=ヒント - このオプションがオンの場合、BIRT はキューブ生成パフォーマンスを向上させるため、キューブ生成中のグループ化・集計の計算をスキップします。

DatasetSelectionPage.Combo.NewDataSet0=<新規データセット...>

GroupsPage.Button.Add=追加(&A)

GroupsPage.Button.Edit=編集(&E)

GroupsPage.Button.Delete=削除(&D)

GroupsPage.ArrowButton.Add.Tooltip=選択フィールドの追加

GroupsPage.ArrowButton.Remove.Tooltip=選択フィールドの削除

GroupsPage.Label.DataField=選択可能なフィールド :

GroupsPage.Label.Group=グループとサマリ :

GroupsPage.tooltip.Sort=ソート

GroupsPage.Primary.Dataset=(プライマリ)

GroupsPage.VirtualField.Measure=(メジャーを作成するには、フィールドをここにドロップします)

GroupsPage.VirtualField.Level=(レベルを作成するには、フィールドをここにドロップします)

GroupsPage.VirtualField.MeasureGroup=(サマリフィールドを作成するには、フィールドをここにドロップします)

GroupsPage.VirtualField.Dimension=(グループを作成するには、フィールドをここにドロップします)

GroupsPage.Reference=参照が見つかりました。

GroupsPage.Clients=\ には次のクライアントがあります。

GroupsPage.Dlg.Confirm=削除しますか ?

LinkGroupsPage.Container.Title.Message=リンクグループ

LinkGroupsPage.Title.Title=リンクグループ

LinkGroupsPage.Title.Message=グループを別のデータセットからプライマリデータセットにリンクするには、グループからフィールドをドラッグし、プライマリデータセットにドロップします。

LevelDialog.Title=プロパティ

LevelDialog.Label.Name=名前:

LevelDialog.Label.Field=フィールドの選択 :

LevelDialog.Label.DataType=データ型 :

LevelDialog.Label.Info=選択済みのキー :

LevelDialog.Label.Add=グループレベルの追加

LevelDialog.Label.Edit=グループレベルの編集

LevelDynamicAttributeDialog.Label.Member=メンバ(&M) :

MeasureDialog.Access.Control.List.Expression=アクセスコントロールリストの式(&A) :

MeasureDialog.Button.Text.Edit=編集(&E)...

MeasureDialog.Title=プロパティ

MeasureDialog.Label.Name=名前(&N):

MeasureDialog.Label.DisplayName=表示名(&A) :

MeasureDialog.Label.Function=関数(&F) :

MeasureDialog.Label.DataType=データ型(&D) :

MeasureDialog.Label.Expression=式(&P) :

MeasureDialog.Label.LinkTo=リンク先(&L) :

MeasureDialog.MessageDialog.Message=現在の関数に推奨されるデータ型は "{0}" です。選択したデータ型を保存しますか ?

MeasureDialog.MessageDialog.Title=警告

MeasureDialog.Title.Property=サマリフィールドの編集

MeasureDialog.Title.Description=サマリフィールド

MeasureDialog.Text.Description=サマリフィールドを変更するには、サマリ関数およびデータフィールドを使用する式を指定してください。

MeasureDialog.Message.NumericName=名前に数字のみを指定することはできません。

MeasureDialog.Message.BlankName=メジャー名は空白にできません。

MeasureDialog.Message.BlankExpression=式は空白にはできません。

MeasureDialog.Label.DerivedMeasure=派生メジャーにする(&I)

MeasureDialog.Label.ExprDesc=例 : dataSetRow["QUANTITYORDERED"]

MeasureDialog.Label.ExprDesc.Derived=例 : measure["QuantityOrdered"] * measure["PriceEach"]

MeasureDialog.Label.Visibility=メジャーの非表示(&M)

MeasureDialog.Label.Visibility.Group=表示/非表示

LevelPropertyDialog.Access.Control.List.Expression=アクセスコントロールリストの式(&A) :

LevelPropertyDialog.Title.Add=グループレベルの追加

LevelPropertyDialog.Title.Edit=グループレベルの編集

LevelPropertyDialog.Member.Access.Control.List.Expression=メンバアクセスコントロールリストの式(&M) :

LevelPropertyDialog.Message=動的または静的のいずれかのグループレベルを選択し、各フィールドに情報を入力してください。

LevelPropertyDialog.Message.NumericName=プロパティ名に数字のみを指定することはできません。

LevelPropertyDialog.Message.BlankName=プロパティ名は空白にできません。

LevelPropertyDialog.Message.BlankKeyField=キーフィールドは空白にできません。

LevelPropertyDialog.Message.BlankDataType=データ型フィールドは空白にできません。

LevelPropertyDialog.None=なし

LevelPropertyDialog.GroupBy=グループ化 :

LevelPropertyDialog.Name=名前(&N):

LevelPropertyDialog.MSG.Static.CreateNew=<新しいメンバを作成>

LevelPropertyDialog.Shell.Title=グループレベル

LevelPropertyDialog.StaticAttributeDialog.Title.Edit=レベル属性の編集

LevelPropertyDialog.StaticAttributeDialog.Title.New=レベル属性の新規作成

LevelPropertyDialog.StaticTable.Button.Add=追加(&D)...

LevelPropertyDialog.StaticTable.Button.Edit=編集(&E)...

LevelPropertyDialog.StaticTable.Button.Remove=削除(&R)

LevelPropertyDialog.Button.Dynamic=動的(&Y)

LevelPropertyDialog.Button.Static=静的(&S)

LevelPropertyDialog.DisplayField=表示フィールド(&D) :

LevelPropertyDialog.Button.None=なし

LevelPropertyDialog.Button.Prefix=接頭辞

LevelPropertyDialog.Button.Text.Edit=編集(&E)...

LevelPropertyDialog.Interval.Base=丸めた数値を間隔の基準値として使用する :

LevelPropertyDialog.Label.Property=レベルのプロパティ

LevelPropertyDialog.Label.Attribute=属性

LevelPropertyDialog.Label.Name=メンバ

LevelPropertyDialog.KeyField=キーフィールド(&K) :

LevelPropertyDialog.DataType=データ型(&T) :

LevelPropertyDialog.DefaultValue.Edit.Label=デフォルト値(&V) :

LevelPropertyDialog.DefaultValue.Edit.Title=編集

LevelPropertyDialog.DynamicAttributeDialog.Title.Edit=レベル属性の編集

LevelPropertyDialog.DynamicAttributeDialog.Title.New=レベル属性の新規作成

LevelPropertyDialog.DynamicTable.Button.Add=追加(&.)...

LevelPropertyDialog.DynamicTable.Button.Edit=編集(&I)...

LevelPropertyDialog.DynamicTable.Button.Remove=削除(&R)

LevelPropertyDialog.Label.Expression=条件式

LevelPropertyDialog.Label.LinkTo=リンク先(&L) :

LevelPropertyDialog.MSG.Dynamic.CreateNew=<新しい属性を作成>

LevelPropertyDialog.MSG.Tooltip=(上記の条件のいずれにも当てはまらないすべての値を表示します)

LevelPropertyDialog.MSG.DefaultValue=<デフォルト値>

MissLinkDialog.Title=データセット間のリンク作成

MissLinkDialog.Question=他のデータセットのすべてのグループをプライマリデータセットにリンクする必要があります。不明なリンクを定義してキューブを完成しますか ?

SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=名前の変更

RenameInputDialog.DialogMessage=新しい名前を入力してください。

RenameInputDialog.Message.BlankName=名前は空白にできません。

RenameInputDialog.Message.NumericName=名前に数字のみを指定することはできません。

RenameInputDialog.Message.DuplicateName=この名前はすでに使われています。
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=使用可能なデータセット

DateGroupDialog.Shell.Title=グループレベル

DateLevelDialog.Shell.Title=日付レベルの編集

DateLevelDialog.Interval.Base=丸めた数値を間隔の基準値として使用する :

DateGroupDialog.Name=名前(&N):

DateLevelDialog.Name=名前(&N):

DateLevelDialog.Type=型(&T) :

DateLevelDialog.Format=書式(&F):

DateLevelDialog.KeyField=キーフィールド :

DateLevelDialog.Label.LinkTo=リンク先(&L) :

DateLevelDialog.None=なし

############################################################
#Cube Action properties
NewCubeAction.DataCube=データキューブ

NewCubeAction.trans.cube.new=キューブの作成

###########################################################
#CubePageGenerator properties
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=プライマリデータセット(&P) :

CubePageGenerator.List.General=全般

############################################################
#FilterListDialog properties
FilterListDialog.Shell.Title=フィルタ

FilterListDialog.Menu.ModifyProperty=プロパティの変更

FilterListDialog.Button.AddWithDialog=追加(&A)...

FilterListDialog.Button.EditWithDialog=編集(&E)...

FilterListDialog.Button.Delete=削除(&R)

VirtualField.SharedDimensions=共有ディメンション

MeasureDialog.Label.Format=書式設定(&O) :

MeasureDialog.Button.Format.Edit=変更(&G)...

MeasureDialog.Label.Alignment=配置(&I) :

LevelPropertyDialog.Label.Format=書式設定(&F) :

LevelPropertyDialog.Button.Format.Edit=変更(&G)...

LevelStaticAttributeDialog.Error.Message=メンバは空白にできません。

LevelStaticAttributeDialog.Label.Expression=条件式(&E) :

LevelStaticAttributeDialog.Label.Member=メンバ(&M) :

LevelPropertyDialog.Label.Alignment=配置(&I) :

