###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubes
cube.new=Nouveau cube
cube.edit=Modifier le cube
CubeNodeProvider.menu.text=Modifier
cube.dimension.new=Nouvelle dimension de cube
cube.dimension.edit=Modifier la dimension de cube
CubeDimensionNodeProvider.menu.text=Modifier
CubeGroupContent.Message.Add.Message=Noms des champs de récapitulation :
CubeGroupContent.Group.Edit.Message=Nom du groupe :
CubeGroupContent.Measure.Edit.Title=Modifier un champ de récapitulation
cube.level.new=Nouveau niveau de cube
cube.level.edit=Modifier un niveau
CubeLevelNodeProvider.menu.text=Modifier
cube.measure.new=Nouvelle mesure de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureNodeProvider.menu.text=Modifier
CubeGroupContent.Group.Add.Title=Ajouter un groupe
CubeGroupContent.Group.Add.Message=Nom du groupe :
CubeGroupContent.Measure.Add.Title=Ajouter un champ de récapitulation
CubeGroupContent.Group.Edit.Title=Modifier le groupe
cube.measuregroup.new=Nouveau groupe de mesures de cube
cube.measure.edit=Modifier la mesure de cube
CubeMeasureGroupNodeProvider.menu.text=Modifier
CubeGroupContent.Measure.Edit.Message=Nom du champ de récapitulation :
CubeModel.group.edit=Modifier le groupe
Cube.Other.Datasets=Autre
CubeModel.summaryfield.edit=Modifier le champ de récapitulation
Cube.Groups=Groupes (Dimensions)
Cube.MeasureGroup=Champs de récapitulation (Mesures)
CubeGroupContent.MeasureDataTypeErrorDialog.Message=La mesure ne prend pas en charge le type de données "Indifférent" : sélectionnez une autre colonne de données ou modifiez le type de données de la colonne "{0}".
CubeGroupContent.MeasureDataTypeErrorDialog.Title=Avertissement
###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=Générateur de cube de tableau croisé
DatasetPage.Title=Jeu de données
GroupDialog.Button.DateGroup=Groupe de dates
GroupDialog.Button.RegularGroup=Groupe normal
GroupsPage.Title=Groupes et résumés
LinkGroupsPage.Title=Lier les groupes
DatasetPage.Label.Name=&Nom :
DateGroupDialog.Title=Ajouter/Modifier le niveau de groupe
DateGroupDialog.Message.NumericName=Le nom du groupe ne doit pas être constitué uniquement de chiffres
DateGroupDialog.Message.BlankName=Le nom du groupe ne doit pas rester vierge
DateLevelDialog.Title=Modifier le niveau de date
DatasetPage.Label.PrimaryDataset=Jeu de données &principal :
DatasetPage.Button.Filter=&Filtre...
DatasetPage.Button.Joint=Ajouter des jeux de données de jointure...
DatasetPage.Title.Title=Générateur de cube de tableau croisé
DateGroupDialog.Message=Sélectionnez les champs de date à inclure
DateGroupDialog.Message.Regular=Saisissez le nom du groupe
DateLevelDialog.Message=Modifier le niveau de type de date
DateLevelDialog.Message.NumericName=Le nom de niveau ne doit pas être constitué uniquement de chiffres
DateLevelDialog.Message.BlankName=Le nom de niveau ne doit pas rester vierge
DatasetPage.Title.Message=Définissez le jeu de données pour le cube. 
DatasetPage.Container.Title.Message=Sélection du jeu de données
DatasetNodeEditPart.Primary.Dataset=(Principal)
GroupsPage.Title.Title=Générateur de cube de tableau croisé
GroupsPage.Title.Message=Faites glisser les champs des jeux de données disponibles vers des hiérarchies de groupes et des champs de données de récapitulation. 
GroupsPage.Container.Title.Message=Groupes et résumés
SimpleCubeBuilder.Title.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Title.Message=Organisez vos données du tableau croisé en précisant les hiérarchies de groupes et les champs de données de récapitulation. 
SimpleCubeBuilder.Title=Générateur de cube de tableau croisé
SimpleCubeBuilder.Label.Name=Nom :
DatasetPage.Title.Message=Définissez le jeu de données pour le cube. 
GroupsPage.Button.Add=&Ajouter
GroupsPage.Button.Edit=&Modifier
GroupsPage.Button.Delete=&Supprimer
GroupsPage.Label.DataField=Champs disponibles :
GroupsPage.Label.Group=Groupes et résumés :
GroupsPage.Primary.Dataset=(Principal)
GroupsPage.VirtualField.Measure=(Déposez un champ ici pour créer une mesure)
GroupsPage.VirtualField.Level=(Déposez un champ ici pour créer un niveau)
GroupsPage.VirtualField.MeasureGroup=(Déposez un champ ici pour créer un champ de récapitulation)
GroupsPage.VirtualField.Dimension=(Déposez un champ ici pour créer un groupe)
GroupsPage.Reference=Référence trouvée
GroupsPage.Clients=\ a les clients suivants
GroupsPage.Dlg.Confirm=Voulez-vous vraiment supprimer cet élément ?
LinkGroupsPage.Container.Title.Message=Lier les groupes
LinkGroupsPage.Title.Title=Générateur de cube de tableau croisé
LinkGroupsPage.Title.Message=Pour établir une liaison entre un groupe d'un autre jeu de données et le jeu de données principal, faites glisser un champ du groupe vers un champ du jeu de données principal.
LevelDialog.Title=Propriété
LevelDialog.Label.Name=Nom :
LevelDialog.Label.Field=Sélection de champ :
LevelDialog.Label.DataType=Type de données :
LevelDialog.Label.Info=Clé sélectionnée :
LevelDialog.Label.Add=Ajouter un niveau de groupe
LevelDialog.Label.Edit=Modifier un niveau de groupe
MeasureDialog.Title=Propriétés
MeasureDialog.Label.Name=Nom :
MeasureDialog.Label.Function=Fonction :
MeasureDialog.Label.DataType=Type de données :
MeasureDialog.Label.Expression=Expression :
MeasureDialog.MessageDialog.Message=Le type de données requis pour la fonction actuelle est "{0}". Voulez-vous vraiment conserver le type de données sélectionné ?
MeasureDialog.MessageDialog.Title=Avertissement
MeasureDialog.Title.Property=Propriétés du champ de récapitulation
MeasureDialog.Message.NumericName=Le nom ne doit pas être constitué uniquement de chiffres
MeasureDialog.Message.BlankName=Le nom de mesure ne doit pas rester vierge
LevelPropertyDialog.Title.Add=Ajouter un niveau de groupe
LevelPropertyDialog.Title.Edit=Modifier un niveau de groupe
LevelPropertyDialog.Message=Choisissez entre un niveau de groupe dynamique ou statique et remplissez les champs requis
LevelPropertyDialog.Message.NumericName=Le nom de la propriété ne doit pas être constitué uniquement de chiffres
LevelPropertyDialog.Message.BlankName=Le nom de la propriété ne doit pas rester vierge
LevelPropertyDialog.None=Aucun
LevelPropertyDialog.GroupBy=Grouper par :
LevelPropertyDialog.Name=Nom :
LevelPropertyDialog.MSG.Static.CreateNew=<Créer un nouveau membre>
LevelPropertyDialog.Shell.Title=Niveau de groupe
LevelPropertyDialog.Button.Dynamic=Dynamique
LevelPropertyDialog.Button.Static=Statique
LevelPropertyDialog.DisplayField=Afficher le champ :
LevelPropertyDialog.Button.None=Aucun
LevelPropertyDialog.Button.Prefix=Préfixe
LevelPropertyDialog.Interval.Base=Utiliser une valeur de base fixe pour l'intervalle :
LevelPropertyDialog.Label.Property=Propriété de niveau
LevelPropertyDialog.Label.Attribute=Attribut
LevelPropertyDialog.Label.Name=Membre
LevelPropertyDialog.KeyField=Champ clé :
LevelPropertyDialog.DataType=Type de données :
LevelPropertyDialog.Label.Expression=Expression de condition
LevelPropertyDialog.MSG.Dynamic.CreateNew=<Créer un nouvel attribut>
LevelPropertyDialog.MSG.Tooltip=(Afficher toutes les autres valeurs qui ne correspondent à aucune des conditions ci-dessus)
LevelPropertyDialog.MSG.DefaultValue=<Valeur par défaut>

MissLinkDialog.Title=Lien manquant entre les jeux de données
MissLinkDialog.Question=Pour compléter le cube, établissez une liaison entre tous les groupes des autres jeux de données et le jeu de données principal
SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Renommer l'entrée
RenameInputDialog.DialogMessage=Saisissez le nouveau nom
RenameInputDialog.Message.BlankName=Le nom ne doit pas rester vierge
RenameInputDialog.Message.NumericName=Le nom ne doit pas être constitué uniquement de chiffres
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Jeux de données disponibles

DateGroupDialog.Shell.Title=Niveau de groupe
DateLevelDialog.Shell.Title=Modifier le niveau de date
DateLevelDialog.Interval.Base=Utiliser une valeur de base fixe pour l'intervalle :
DateGroupDialog.Name=Nom :
DateLevelDialog.Name=Nom :
DateLevelDialog.Type=Type :
DateLevelDialog.Format=Format :
DateLevelDialog.None=Aucun

############################################################
#Cube Action properties
NewCubeAction.DataCube=Cube de données

###########################################################
#CubePageGenerator properties
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=Jeu de données principal :
CubePageGenerator.List.General=Général

############################################################
#FilterListDialog properties
FilterListDialog.Shell.Title=Filtre
FilterListDialog.Menu.ModifyProperty=Modifier la propriété
FilterListDialog.Button.AddWithDialog=&Ajouter...
FilterListDialog.Button.EditWithDialog=Modifi&er...
FilterListDialog.Button.Delete=Supp&rimer
