###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Quader

cube.new=Neuer Quader

cube.action.new=Neuer Datenq&uader

cube.edit=Quader bearbeiten

CubeNodeProvider.menu.text=&Bearbeiten

cube.dimension.new=Neue Quaderdimension

cube.dimension.edit=Quaderdimension bearbeiten

CubeDimensionNodeProvider.menu.text=&Bearbeiten

CubeGroupContent.Message.Add.Message=Name des Zusammenfassungsfelds:

CubeGroupContent.Group.Edit.Message=Gruppenname:

CubeGroupContent.Measure.Edit.Title=Zusammenfassungsfeld bearbeiten

cube.level.new=Neue Quaderebene

cube.level.edit=Ebene bearbeiten

CubeLabelProvider.SharedDimensions=Gemeinsame Dimensionen

CubeLevelNodeProvider.menu.text=&Bearbeiten

cube.measure.new=Neue Quadereinheit

cube.measure.edit=Quadereinheit bearbeiten

CubeMeasureNodeProvider.menu.text=&Bearbeiten

CubeGroupContent.Group.Add.Title=Gruppe hinzufügen

CubeGroupContent.Group.Add.Message=Gruppen&name:

CubeGroupContent.Measure.Add.Title=Zusammenfassungsfeld hinzufügen

CubeGroupContent.Group.Edit.Title=Gruppe bearbeiten

cube.measuregroup.new=Neue Quadereinheitsgruppe

cube.measuregroup.edit=Quadereinheit bearbeiten

CubeMeasureGroupNodeProvider.menu.text=&Bearbeiten

CubeGroupContent.Measure.Edit.Message=Name des Zusammenfassungsfelds:

CubeModel.group.edit=Gruppe &bearbeiten

Cube.Other.Datasets=Andere

CubeModel.summaryfield.edit=Zusammenfassungsfeld &bearbeiten

Cube.Groups=Gruppen (Dimensionen)

Cube.MeasureGroup=Zusammenfassungsfelder (Einheiten)

CubeGroupContent.MeasureDataTypeErrorDialog.Message=Maßeinheit unterstützt nicht den Datentyp "Beliebig". Wählen Sie eine andere Datenspalte, oder ändern Sie den Datentyp der Spalte "{0}".

CubeGroupContent.MeasureDataTypeErrorDialog.Title=Warnung
###########################################################
#Cube Builder Dialog properties
CubeBuilder.AutoPrimaryKeyDialog.Message=Einige Spalten, die als Verknüpfungsschlüssel verwendet werden, sind nicht in Ebenen definiert. Möchten Sie die Option 'Automatischer Primärschlüssel' überprüfen, um den Quader abzuschließen?

CubeBuilder.AutoPrimaryKeyDialog.Title=Problem mit dem automatischen Primärschlüssel

CubeBuilder.SharedDimensionErrorLinkDialog.Message=Alle Primärschlüssel aus gemeinsamen Dimensionen müssen miteinander verknüpft sein. Möchten Sie die fehlenden Verknüpfungen angeben, um den Quader abzuschließen?

CubeBuilder.SharedDimensionErrorLinkDialog.Title=Fehlende Verknüpfung einer gemeinsamen Dimension

CubeBuilder.Title=Datenquadererstellung

DatasePage.EmptyName.ErrorMessage=Der Name des Quaders ist erforderlich.

DatasetPage.Title=Datensatz

GroupDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:

GroupDialog.Button.DateGroup=&Datumsgruppe

GroupDialog.Button.RegularGroup=&Reguläre Gruppe

GroupRenameDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:

GroupsPage.Title=Gruppen und Zusammenfassungen

LinkGroupsPage.Title=Gruppen verknüpfen

DatasetPage.Label.Name=&Name:

DateGroupDialog.Title=Gruppenebene hinzufügen/bearbeiten

DateGroupDialog.Message.NumericName=Gruppenname darf keine reine Zahl sein.

DateGroupDialog.Message.DuplicateName=Der Name wird bereits verwendet.

DateGroupDialog.Message.BlankName=Gruppenname darf nicht leer sein.

DateLevelDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:

DateLevelDialog.Button.Text.Edit=&Bearbeiten...

DateLevelDialog.Title=Datumsebene bearbeiten

DatasetPage.Label.PrimaryDataset=&Primärdatensatz:

DatasetPage.Button.Filter=&Filter...

DatasetPage.Button.Joint=Verknüpfungsdatensatz hinzufügen...

DatasetPage.Title.Title=Datensatz

DateGroupDialog.Message=Wählen Sie die einzuschließenden Datumsfelder aus.

DateGroupDialog.Message.Regular=Geben Sie den Gruppennamen ein.

DateLevelDialog.Message=Datumstypebene bearbeiten

DateLevelDialog.Message.NumericName=Ebenenname darf keine reine Zahl sein.

DateLevelDialog.Message.BlankName=Ebenenname darf nicht leer sein.

DatasetPage.Title.Message=Datensatz für Quader definieren.

DatasetPage.Container.Title.Message=Datensatzauswahl

DatasetNodeEditPart.Primary.Dataset=(Primär)

GroupsPage.Title.Title=Gruppen und Zusammenfassungen

GroupsPage.Title.Message=Felder aus den verfügbaren Datensätzen in Gruppierungshierarchien und Zusammenfassungsdatenfelder ziehen.

GroupsPage.Container.Title.Message=Gruppen und Zusammenfassungen

SimpleCubeBuilder.Title.Title=Kreuztabellen-Cube Builder

SimpleCubeBuilder.Title.Message=Daten für die Kreuztabelle durch das Angeben von Gruppierungshierarchien und Zusammenfassungsdatenfeldern verwalten.

SimpleCubeBuilder.Title=Kreuztabellen-Cube Builder

SimpleCubeBuilder.Label.Name=Name:

DatasetSelectionPage.Label.Auto.Primary.Key=&Diese Option wählen, um eine Vorverdichtung im primären Datensatz während der Quadererstellung zu vermeiden.

DatasetSelectionPage.Text.Auto.Primary.Key=Hinweis – Ist diese Option aktiviert, überspringt BIRT die Gruppierungs- und Aggregatberechnung beim Erstellen des Quaders, um eine bessere Leistung bei der Quadererstellung zu erzielen.

DatasetSelectionPage.Combo.NewDataSet0=<Neuer Datensatz...>

GroupsPage.Button.Add=&Hinzufügen

GroupsPage.Button.Edit=&Bearbeiten

GroupsPage.Button.Delete=&Löschen...

GroupsPage.ArrowButton.Add.Tooltip=Ausgewähltes Feld hinzufügen

GroupsPage.ArrowButton.Remove.Tooltip=Ausgewähltes Feld entfernen

GroupsPage.Label.DataField=Verfügbare Felder:

GroupsPage.Label.Group=Gruppen und Zusammenfassungen:

GroupsPage.tooltip.Sort=Sortieren

GroupsPage.Primary.Dataset=(Primär)

GroupsPage.VirtualField.Measure=(Feld hier ablegen, um eine Maßeinheit zu erstellen)

GroupsPage.VirtualField.Level=(Feld hier ablegen, um eine Ebene zu erstellen)

GroupsPage.VirtualField.MeasureGroup=(Feld hier ablegen, um ein Zusammenfassungsfeld zu erstellen)

GroupsPage.VirtualField.Dimension=(Feld hier ablegen, um eine Gruppe zu erstellen)

GroupsPage.Reference=Verweis gefunden

GroupsPage.Clients=\ hat folgende Clients

GroupsPage.Dlg.Confirm=Möchten Sie das Element wirklich löschen?

LinkGroupsPage.Container.Title.Message=Gruppen verknüpfen

LinkGroupsPage.Title.Title=Gruppen verknüpfen

LinkGroupsPage.Title.Message=Um eine Gruppe aus einem anderen Datensatz mit dem primären Datensatz zu verknüpfen, ziehen Sie ein Feld aus der Gruppe auf ein Feld im primären Datensatz.

LevelDialog.Title=Eigenschaft

LevelDialog.Label.Name=Name:

LevelDialog.Label.Field=Feld wählen:

LevelDialog.Label.DataType=Datentyp:

LevelDialog.Label.Info=Ausgewählter Schlüssel:

LevelDialog.Label.Add=Gruppenebene hinzufügen

LevelDialog.Label.Edit=Gruppenebene bearbeiten

LevelDynamicAttributeDialog.Label.Member=&Mitglied:

MeasureDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:

MeasureDialog.Button.Text.Edit=&Bearbeiten...

MeasureDialog.Title=Eigenschaften

MeasureDialog.Label.Name=&Name:

MeasureDialog.Label.DisplayName=Anzeigen&ame:

MeasureDialog.Label.Function=&Funktion:

MeasureDialog.Label.DataType=&Datentyp:

MeasureDialog.Label.Expression=Aus&druck:

MeasureDialog.Label.LinkTo=&Verknüpfen mit:

MeasureDialog.MessageDialog.Message=Der empfohlene Datentyp für die aktuelle Funktion ist '{0}'. Möchten Sie den ausgewählten Datentypen wirklich beibehalten?

MeasureDialog.MessageDialog.Title=Warnung

MeasureDialog.Title.Property=Zusammenfassungsfeld bearbeiten

MeasureDialog.Title.Description=Zusammenfassungsfeld

MeasureDialog.Text.Description=Um das Zusammenfassungsfeld zu bearbeiten, geben Sie eine Zusammenfassungsfunktion an und einen Ausdruck, der Datenfelder verwendet.

MeasureDialog.Message.NumericName=Name darf keine reine Zahl sein.

MeasureDialog.Message.BlankName=Einheitenname darf nicht leer sein.

MeasureDialog.Message.BlankExpression=Ausdruck darf nicht leer sein

MeasureDialog.Label.DerivedMeasure=&Ist abgeleitete Maßeinheit

MeasureDialog.Label.ExprDesc=z.B. dataSetRow["QUANTITYORDERED"]

MeasureDialog.Label.ExprDesc.Derived=z.B. measure["QuantityOrdered"] * measure["PriceEach"]

MeasureDialog.Label.Visibility=&Maßeinheit ausblenden

MeasureDialog.Label.Visibility.Group=Sichtbarkeit

LevelPropertyDialog.Access.Control.List.Expression=Zugriffssteuerlisten-&Ausdruck:

LevelPropertyDialog.Title.Add=Gruppenebene hinzufügen

LevelPropertyDialog.Title.Edit=Gruppenebene bearbeiten

LevelPropertyDialog.Member.Access.Control.List.Expression=&Mitglieds-Zugriffssteuerlisten-Ausdruck:

LevelPropertyDialog.Message=Gruppenebene als dynamisch oder statisch definieren und erforderliche Felder ausfüllen

LevelPropertyDialog.Message.NumericName=Eigenschaftsname darf keine reine Zahl sein.

LevelPropertyDialog.Message.BlankName=Eigenschaftsname darf nicht leer sein.

LevelPropertyDialog.Message.BlankKeyField=Schlüsselfeld darf nicht leer sein

LevelPropertyDialog.Message.BlankDataType=Datentypfeld darf nicht leer sein

LevelPropertyDialog.None=Ohne

LevelPropertyDialog.GroupBy=Gruppieren nach:

LevelPropertyDialog.Name=&Name:

LevelPropertyDialog.MSG.Static.CreateNew=<Neues Mitglied erstellen>

LevelPropertyDialog.Shell.Title=Gruppenebene

LevelPropertyDialog.StaticAttributeDialog.Title.Edit=Ebenenattribut bearbeiten

LevelPropertyDialog.StaticAttributeDialog.Title.New=Neues Ebenenattribut

LevelPropertyDialog.StaticTable.Button.Add=&Hinzufügen...

LevelPropertyDialog.StaticTable.Button.Edit=&Bearbeiten...

LevelPropertyDialog.StaticTable.Button.Remove=&Entfernen

LevelPropertyDialog.Button.Dynamic=D&ynamisch

LevelPropertyDialog.Button.Static=&Statisch

LevelPropertyDialog.DisplayField=&Anzeigefeld:

LevelPropertyDialog.Button.None=Ohne

LevelPropertyDialog.Button.Prefix=Präfix

LevelPropertyDialog.Button.Text.Edit=&Bearbeiten...

LevelPropertyDialog.Interval.Base=Festen Basiswert für Intervall verwenden:

LevelPropertyDialog.Label.Property=Ebeneneigenschaft

LevelPropertyDialog.Label.Attribute=Attribut

LevelPropertyDialog.Label.Name=Mitglied

LevelPropertyDialog.KeyField=&Schlüsselfeld:

LevelPropertyDialog.DataType=Daten&typ:

LevelPropertyDialog.DefaultValue.Edit.Label=&Standardwert:

LevelPropertyDialog.DefaultValue.Edit.Title=Bearbeiten

LevelPropertyDialog.DynamicAttributeDialog.Title.Edit=Ebenenattribut bearbeiten

LevelPropertyDialog.DynamicAttributeDialog.Title.New=Neues Ebenenattribut

LevelPropertyDialog.DynamicTable.Button.Add=Hinzufügen&...

LevelPropertyDialog.DynamicTable.Button.Edit=Bearbe&iten...

LevelPropertyDialog.DynamicTable.Button.Remove=&Entfernen

LevelPropertyDialog.Label.Expression=Bedingungsausdruck

LevelPropertyDialog.Label.LinkTo=&Verknüpfen mit:

LevelPropertyDialog.MSG.Dynamic.CreateNew=<Neues Attribut erstellen>

LevelPropertyDialog.MSG.Tooltip=(Alle anderen Werte anzeigen, die in keine dieser Kategorien fallen)

LevelPropertyDialog.MSG.DefaultValue=<Standardwert>

MissLinkDialog.Title=Fehlende Verknüpfung zwischen Datensätzen

MissLinkDialog.Question=Alle Gruppen aus anderen Datensätzen müssen mit dem primären Datensatz verknüpft sein. Möchten Sie die fehlenden Verknüpfungen angeben, um den Quader abzuschließen?

SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Eingabe umbenennen

RenameInputDialog.DialogMessage=Geben Sie den neuen Namen ein.

RenameInputDialog.Message.BlankName=Name darf nicht leer sein.

RenameInputDialog.Message.NumericName=Name darf keine reine Zahl sein.

RenameInputDialog.Message.DuplicateName=Der Name wird bereits verwendet.
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Verfügbare Datensätze

DateGroupDialog.Shell.Title=Gruppenebene

DateLevelDialog.Shell.Title=Datumsebene bearbeiten

DateLevelDialog.Interval.Base=Festen Basiswert für Intervall verwenden:

DateGroupDialog.Name=&Name:

DateLevelDialog.Name=&Name:

DateLevelDialog.Type=&Typ:

DateLevelDialog.Format=&Format:

DateLevelDialog.KeyField=Schlüsselfeld:

DateLevelDialog.Label.LinkTo=&Verknüpfen mit:

DateLevelDialog.None=Ohne

############################################################
#Cube Action properties
NewCubeAction.DataCube=Datenquader

NewCubeAction.trans.cube.new=Quader erstellen

###########################################################
#CubePageGenerator properties
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=&Primärer Datensatz:

CubePageGenerator.List.General=Allgemein

############################################################
#FilterListDialog properties
FilterListDialog.Shell.Title=Filter

FilterListDialog.Menu.ModifyProperty=Eigenschaft modifizieren

FilterListDialog.Button.AddWithDialog=&Hinzufügen...

FilterListDialog.Button.EditWithDialog=&Bearbeiten...

FilterListDialog.Button.Delete=&Entfernen

VirtualField.SharedDimensions=Gemeinsame Dimensionen

MeasureDialog.Label.Format=F&ormatieren als:

MeasureDialog.Button.Format.Edit=&Ändern...

MeasureDialog.Label.Alignment=Ausr&ichtung:

LevelPropertyDialog.Label.Format=&Formatieren als:

LevelPropertyDialog.Button.Format.Edit=&Ändern...

LevelStaticAttributeDialog.Error.Message=Mitglied darf nicht leer sein.

LevelStaticAttributeDialog.Label.Expression=B&edingungsausdruck:

LevelStaticAttributeDialog.Label.Member=&Mitglied:

LevelPropertyDialog.Label.Alignment=Ausr&ichtung:

