###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubos

cube.new=Nuevo cubo

cube.action.new=&Cubo de datos nuevo

cube.edit=Editar cubo

CubeNodeProvider.menu.text=&Editar

cube.dimension.new=Nueva dimensión de cubo

cube.dimension.edit=Editar dimensión de cubo

CubeDimensionNodeProvider.menu.text=&Editar

CubeGroupContent.Message.Add.Message=Nombre de campo de resumen:

CubeGroupContent.Group.Edit.Message=Nombre de grupo:

CubeGroupContent.Measure.Edit.Title=Editar campo de resumen

cube.level.new=Nuevo nivel de cubo

cube.level.edit=Editar nivel

CubeLabelProvider.SharedDimensions=Dimensiones compartidas

CubeLevelNodeProvider.menu.text=&Editar

cube.measure.new=Nueva medida de cubo

cube.measure.edit=Editar medida de cubo

CubeMeasureNodeProvider.menu.text=&Editar

CubeGroupContent.Group.Add.Title=Añadir grupo

CubeGroupContent.Group.Add.Message=Nom&bre del grupo

CubeGroupContent.Measure.Add.Title=Agregar campo de resumen

CubeGroupContent.Group.Edit.Title=Editar grupo

cube.measuregroup.new=Nuevo grupo de medida de cubo

cube.measuregroup.edit=Editar medida de cubo

CubeMeasureGroupNodeProvider.menu.text=&Editar

CubeGroupContent.Measure.Edit.Message=Nombre de campo de resumen:

CubeModel.group.edit=&Editar grupo

Cube.Other.Datasets=Otro

CubeModel.summaryfield.edit=&Editar campo de resumen

Cube.Groups=Grupos (Dimensiones)

Cube.MeasureGroup=Campos de resumen (Medidas)

CubeGroupContent.MeasureDataTypeErrorDialog.Message=La medida no admite el tipo de dato "Cualquiera", seleccione otra columna de datos o cambie el tipo de datos de la columna "{0}".

CubeGroupContent.MeasureDataTypeErrorDialog.Title=Advertencia
###########################################################
#Cube Builder Dialog properties
CubeBuilder.AutoPrimaryKeyDialog.Message=Hay algunas columnas utilizadas como claves de unión que no están definidas por niveles, ¿desea comprobar la opción "clave primaria automática" para completar el cubo?

CubeBuilder.AutoPrimaryKeyDialog.Title=Problema de clave primaria automática

CubeBuilder.SharedDimensionErrorLinkDialog.Message=Todas las claves primarias de las dimensiones compartidas deben estar vinculadas, ¿desea definir los links que faltan para completar el cubo?

CubeBuilder.SharedDimensionErrorLinkDialog.Title=Falta el link de dimensión compartida

CubeBuilder.Title=Compilador de cubos de datos

DatasePage.EmptyName.ErrorMessage=Se requiere el nombre de cubo.

DatasetPage.Title=Conjunto de datos

GroupDialog.Access.Control.List.Expression=Ex&presión de lista de control de acceso:

GroupDialog.Button.DateGroup=&Grupo de fecha

GroupDialog.Button.RegularGroup=G&rupo regular

GroupRenameDialog.Access.Control.List.Expression=Ex&presión de lista de control de acceso:

GroupsPage.Title=Grupos y resúmenes

LinkGroupsPage.Title=Grupos de link

DatasetPage.Label.Name=&Nombre:

DateGroupDialog.Title=Agregar/editar nivel de grupo

DateGroupDialog.Message.NumericName=El nombre de grupo no puede ser un número puro

DateGroupDialog.Message.DuplicateName=Este nombre ya existe.

DateGroupDialog.Message.BlankName=El nombre de grupo no puede estar en blanco

DateLevelDialog.Access.Control.List.Expression=Ex&presión de lista de control de acceso:

DateLevelDialog.Button.Text.Edit=&Editar...

DateLevelDialog.Title=Editar nivel de fecha

DatasetPage.Label.PrimaryDataset=&Conjunto de datos primario:

DatasetPage.Button.Filter=&Filtro...

DatasetPage.Button.Joint=Añadir conjunto de datos de combinación...

DatasetPage.Title.Title=Conjunto de datos

DateGroupDialog.Message=Seleccionar los campos de fecha que se incluirán

DateGroupDialog.Message.Regular=Introduzca el nombre de grupo

DateLevelDialog.Message=Editar nivel de tipo de fecha

DateLevelDialog.Message.NumericName=El nombre de nivel no puede ser un número puro

DateLevelDialog.Message.BlankName=El nombre de nivel no puede estar en blanco

DatasetPage.Title.Message=Definir conjunto de datos para el cubo.

DatasetPage.Container.Title.Message=Selección de conjunto de datos

DatasetNodeEditPart.Primary.Dataset=(Primario)

GroupsPage.Title.Title=Grupos y resúmenes

GroupsPage.Title.Message=Arrastre los campos de los conjuntos de datos disponibles a jerarquías de agrupación y campos de datos de resumen.

GroupsPage.Container.Title.Message=Grupos y resúmenes

SimpleCubeBuilder.Title.Title=Compilador de cubos de tabla de referencias cruzadas

SimpleCubeBuilder.Title.Message=Organice sus datos para la tabla de referencias cruzadas especificando las jerarquías de agrupación y los campos de datos de resumen.

SimpleCubeBuilder.Title=Compilador de cubos de tabla de referencias cruzadas

SimpleCubeBuilder.Label.Name=Nombre:

DatasetSelectionPage.Label.Auto.Primary.Key=&Active esta opción para evitar la preagregación en el conjunto de datos primarios durante la generación del cubo.

DatasetSelectionPage.Text.Auto.Primary.Key=Sugerencia: si se selecciona esta opción, BIRT omitirá el cálculo de la agrupación y la agregación durante la generación del cubo para lograr un mejor rendimiento en dicha generación.

DatasetSelectionPage.Combo.NewDataSet0=<Nuevo conjunto de datos...>

GroupsPage.Button.Add=&Añadir

GroupsPage.Button.Edit=&Editar

GroupsPage.Button.Delete=&Eliminar

GroupsPage.ArrowButton.Add.Tooltip=Añadir campo seleccionado

GroupsPage.ArrowButton.Remove.Tooltip=Eliminar campo seleccionado

GroupsPage.Label.DataField=Campos disponibles:

GroupsPage.Label.Group=Grupos y resúmenes:

GroupsPage.tooltip.Sort=Orden

GroupsPage.Primary.Dataset=(Primario)

GroupsPage.VirtualField.Measure=(Suelte un campo aquí para crear una medida)

GroupsPage.VirtualField.Level=(Suelte un campo aquí para crear un nivel)

GroupsPage.VirtualField.MeasureGroup=(Suelte un campo aquí para crear un campo de resumen)

GroupsPage.VirtualField.Dimension=(Suelte un campo aquí para crear un grupo)

GroupsPage.Reference=Se ha encontrado la referencia

GroupsPage.Clients=\ tiene los siguientes clientes

GroupsPage.Dlg.Confirm=¿Desea eliminarlo?

LinkGroupsPage.Container.Title.Message=Grupos de link

LinkGroupsPage.Title.Title=Grupos de link

LinkGroupsPage.Title.Message=Para enlazar un grupo de otro conjunto de datos al conjunto de datos primario, arrastre un campo del grupo hasta otro campo del conjunto de datos primario.

LevelDialog.Title=Propiedad

LevelDialog.Label.Name=Nombre:

LevelDialog.Label.Field=Seleccionar campo:

LevelDialog.Label.DataType=Tipo de datos:

LevelDialog.Label.Info=Tecla seleccionada:

LevelDialog.Label.Add=Agregar nivel de grupo

LevelDialog.Label.Edit=Editar nivel de grupo

LevelDynamicAttributeDialog.Label.Member=&Miembro:

MeasureDialog.Access.Control.List.Expression=Ex&presión de lista de control de acceso:

MeasureDialog.Button.Text.Edit=&Editar...

MeasureDialog.Title=Propiedades

MeasureDialog.Label.Name=&Nombre:

MeasureDialog.Label.DisplayName=Nom&bre en pantalla:

MeasureDialog.Label.Function=&Función:

MeasureDialog.Label.DataType=Tipo de &datos:

MeasureDialog.Label.Expression=&Expresión:

MeasureDialog.Label.LinkTo=&Link a:

MeasureDialog.MessageDialog.Message=El tipo de datos recomendado para la función actual es "{0}". ¿Desea mantener el tipo de datos que ha seleccionado?

MeasureDialog.MessageDialog.Title=Advertencia

MeasureDialog.Title.Property=Editar campo de resumen

MeasureDialog.Title.Description=Campo de resumen

MeasureDialog.Text.Description=Para modificar el campo de resumen, especifique una función de resumen y una expresión que use campos de datos

MeasureDialog.Message.NumericName=El nombre no puede ser un número puro

MeasureDialog.Message.BlankName=El nombre de medida no puede estar en blanco

MeasureDialog.Message.BlankExpression=La expresión no puede estar en blanco

MeasureDialog.Label.DerivedMeasure=&Es medida derivada

MeasureDialog.Label.ExprDesc=p. ej. dataSetRow["QUANTITYORDERED"]

MeasureDialog.Label.ExprDesc.Derived=p. ej. measure["QuantityOrdered"] * measure["PriceEach"]

MeasureDialog.Label.Visibility=&Ocultar medida

MeasureDialog.Label.Visibility.Group=Visibilidad

LevelPropertyDialog.Access.Control.List.Expression=Ex&presión de lista de control de acceso:

LevelPropertyDialog.Title.Add=Agregar nivel de grupo

LevelPropertyDialog.Title.Edit=Editar nivel de grupo

LevelPropertyDialog.Member.Access.Control.List.Expression=Ex&presión de lista de control de acceso de miembro:

LevelPropertyDialog.Message=Seleccionar el nivel de grupo dinámico o estático y rellenar los campos necesarios

LevelPropertyDialog.Message.NumericName=El nombre de propiedad no puede ser un número puro

LevelPropertyDialog.Message.BlankName=El nombre de propiedad no puede estar en blanco

LevelPropertyDialog.Message.BlankKeyField=El campo de clave no puede estar en blanco

LevelPropertyDialog.Message.BlankDataType=El campo de tipo de datos no puede estar en blanco

LevelPropertyDialog.None=Ninguno

LevelPropertyDialog.GroupBy=Agrupar por:

LevelPropertyDialog.Name=&Nombre:

LevelPropertyDialog.MSG.Static.CreateNew=<Crear nuevo miembro>

LevelPropertyDialog.Shell.Title=Nivel de grupo

LevelPropertyDialog.StaticAttributeDialog.Title.Edit=Editar atributo de nivel

LevelPropertyDialog.StaticAttributeDialog.Title.New=Nuevo atributo de nivel

LevelPropertyDialog.StaticTable.Button.Add=Añad&ir...

LevelPropertyDialog.StaticTable.Button.Edit=&Editar...

LevelPropertyDialog.StaticTable.Button.Remove=Quita&r

LevelPropertyDialog.Button.Dynamic=&Dinámico

LevelPropertyDialog.Button.Static=&Estático

LevelPropertyDialog.DisplayField=Visualizar c&ampo:

LevelPropertyDialog.Button.None=Ninguno

LevelPropertyDialog.Button.Prefix=Prefijo

LevelPropertyDialog.Button.Text.Edit=&Editar...

LevelPropertyDialog.Interval.Base=Utilizar un valor de base fijo para el intervalo:

LevelPropertyDialog.Label.Property=Propiedad de nivel

LevelPropertyDialog.Label.Attribute=Atributo

LevelPropertyDialog.Label.Name=Miembro

LevelPropertyDialog.KeyField=Campo de cla&ve:

LevelPropertyDialog.DataType=&Tipo de datos:

LevelPropertyDialog.DefaultValue.Edit.Label=&Valor predeterminado:

LevelPropertyDialog.DefaultValue.Edit.Title=Editar

LevelPropertyDialog.DynamicAttributeDialog.Title.Edit=Editar atributo de nivel

LevelPropertyDialog.DynamicAttributeDialog.Title.New=Nuevo atributo de nivel

LevelPropertyDialog.DynamicTable.Button.Add=Añadir&...

LevelPropertyDialog.DynamicTable.Button.Edit=Ed&itar...

LevelPropertyDialog.DynamicTable.Button.Remove=Quita&r

LevelPropertyDialog.Label.Expression=Expresión condicional

LevelPropertyDialog.Label.LinkTo=&Link a:

LevelPropertyDialog.MSG.Dynamic.CreateNew=<Crear nuevo atributo>

LevelPropertyDialog.MSG.Tooltip=(Mostrar el resto de valores que no cumplen ninguna de las condiciones previas)

LevelPropertyDialog.MSG.DefaultValue=<Valor predeterminado>

MissLinkDialog.Title=Falta el link entre los conjuntos de datos

MissLinkDialog.Question=Todos los grupos de otros conjuntos de datos deben estar vinculados al conjunto de datos primario, ¿desea definir los links que faltan para completar el cubo?

SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
#RenameInputDialog properties
RenameInputDialog.DialogTitle=Cambiar nombre de entrada

RenameInputDialog.DialogMessage=Introduzca el nuevo nombre

RenameInputDialog.Message.BlankName=El nombre no puede estar en blanco

RenameInputDialog.Message.NumericName=El nombre no puede ser un número puro

RenameInputDialog.Message.DuplicateName=Este nombre ya existe.
############################################################
#ExpressionBuilder properties
ExpressionProvider.Category.DataSets=Conjuntos de datos disponibles

DateGroupDialog.Shell.Title=Nivel de grupo

DateLevelDialog.Shell.Title=Editar nivel de fecha

DateLevelDialog.Interval.Base=Utilizar un valor de base fijo para el intervalo:

DateGroupDialog.Name=&Nombre:

DateLevelDialog.Name=&Nombre:

DateLevelDialog.Type=&Tipo:

DateLevelDialog.Format=&Formato:

DateLevelDialog.KeyField=Campo de clave:

DateLevelDialog.Label.LinkTo=&Link a:

DateLevelDialog.None=Ninguno

############################################################
#Cube Action properties
NewCubeAction.DataCube=Cubo de datos

NewCubeAction.trans.cube.new=Crear cubo

###########################################################
#CubePageGenerator properties
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=Conjunto de datos &primario:

CubePageGenerator.List.General=General

############################################################
#FilterListDialog properties
FilterListDialog.Shell.Title=Filtro

FilterListDialog.Menu.ModifyProperty=Modificar propiedad

FilterListDialog.Button.AddWithDialog=&Añadir...

FilterListDialog.Button.EditWithDialog=&Editar...

FilterListDialog.Button.Delete=Quita&r

VirtualField.SharedDimensions=Dimensiones compartidas

MeasureDialog.Label.Format=F&ormato como:

MeasureDialog.Button.Format.Edit=Camb&iar...

MeasureDialog.Label.Alignment=Al&ineación:

LevelPropertyDialog.Label.Format=&Formato como:

LevelPropertyDialog.Button.Format.Edit=Camb&iar...

LevelStaticAttributeDialog.Error.Message=El miembro no puede estar en blanco

LevelStaticAttributeDialog.Label.Expression=Expresión &condicional:

LevelStaticAttributeDialog.Label.Member=&Miembro:

LevelPropertyDialog.Label.Alignment=Al&ineación:

