dataset.editor.page.query=쿼리

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT Sample DB Data Source
newwizard.description=BIRT 샘플 DB 연결 프로필 생성

wizard.window.title=새 샘플 DB 데이터 원본 프로필

wizard.data.source.page.title=New Classic Models Inc. 샘플 데이터 원본

profile.propertypage.name=BIRT Sample DB Data Source Connection Properties
