dataset.editor.page.query=Requête

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT Sample DB Data Source
newwizard.description=Créer un profil de connexion à la BD exemple BIRT

wizard.window.title=Nouveau profil de source de données de BD exemple

wizard.data.source.page.title=Nouvelle source de données exemple de Classic Models Inc.

profile.propertypage.name=BIRT Sample DB Data Source Connection Properties
