dataset.editor.page.query=Requête

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
oda.data.source.name=BD exemple BIRT
connection.profile.name=Profil de connexion à la source de données de la BD exemple BIRT
newwizard.name=Source de données de la BD exemple BIRT
newwizard.description=Créer un profil de connexion à la BD exemple BIRT
wizard.window.title=Nouveau profil de source de données de BD exemple
wizard.data.source.page.title=Nouvelle source de données exemple de Classic Models Inc.
profile.propertypage.name=Propriétés de la connexion à la source de données de la BD exemple BIRT

#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
