dataset.editor.page.query=クエリ

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
oda.data.source.name=BIRT サンプルデータベース
connection.profile.name=BIRT サンプルデータベースのデータソース接続プロファイル
newwizard.name=BIRT サンプルデータベースのデータソース
newwizard.description=BIRT サンプルデータベースの接続プロファイルを作成します。
wizard.window.title=サンプルデータベースのデータソースプロファイルの新規作成
wizard.data.source.page.title=Classic Models Inc. の新規サンプルデータソース
profile.propertypage.name=BIRT サンプルデータベースのデータソース接続のプロパティ

#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリ
