dataset.editor.page.query=查询

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT 示例数据库数据源
newwizard.description=创建 BIRT 示例数据库连接配置文件
wizard.window.title=新建示例数据库数据源配置文件
wizard.data.source.page.title=新的 Classic Models Inc. 示例数据源
profile.propertypage.name=BIRT 示例数据库数据源连接属性
