dataset.editor.page.query=Abfrage

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT Sample DB Data Source
newwizard.description=Verbindungsprofil für BIRT-Beispieldatenbank erstellen

wizard.window.title=Neues Verbindungsprofil für Beispieldatenbank

wizard.data.source.page.title=Neue Beispieldatenquelle "Classic Models Inc."

profile.propertypage.name=BIRT Sample DB Data Source Connection Properties
