dataset.editor.page.query=Consulta

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
oda.data.source.name=Base de datos de muestra BIRT
connection.profile.name=Perfil de conexión de fuente de datos de base de datos de muestra BIRT
newwizard.name=Fuente de datos de base de datos de muestra BIRT
newwizard.description=Crear un perfil de conexión de base de datos de muestra BIRT
wizard.window.title=Nuevo perfil de fuente de datos de base de datos de muestra
wizard.data.source.page.title=Nueva fuente de datos de muestra de Classic Models Inc.
profile.propertypage.name=Propiedades de conexión de fuente de datos de base de datos de muestra BIRT

#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA

