dataset.editor.page.query=クエリ

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT サンプルデータベースデータソース
newwizard.description=BIRT サンプルデータベースの接続プロファイルを作成します。
wizard.window.title=サンプルデータベースデータソースプロファイルの新規作成
wizard.data.source.page.title=Classic Models Inc. 新規サンプルデータソース
profile.propertypage.name=BIRT サンプルデータベースデータソース接続のプロパティ
