dataset.editor.page.query=Abfrage

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
oda.data.source.name=BIRT-Beispieldatenbank
connection.profile.name=Verbindungsprofil für BIRT-Beispieldatenbank-Datenquelle
newwizard.name=BIRT-Beispieldatenbank-Datenquelle
newwizard.description=Verbindungsprofil für BIRT-Beispieldatenbank erstellen
wizard.window.title=Neues Verbindungsprofil für Beispieldatenbank
wizard.data.source.page.title=Neue Beispieldatenquelle "Classic Models Inc."
profile.propertypage.name=Verbindungseigenschaften für BIRT-Beispieldatenbank-Datenquelle

#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
