dataset.editor.page.query=쿼리

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
oda.data.source.name=BIRT 예제 DB
connection.profile.name=BIRT 예제 DB 데이터 원본 연결 프로필
newwizard.name=BIRT 예제 DB 데이터 원본
newwizard.description=BIRT 예제 DB 연결 프로필 생성
wizard.window.title=새 예제 DB 데이터 원본 프로필
wizard.data.source.page.title=New Classic Models Inc. 예제 데이터 원본
profile.propertypage.name=BIRT 예제 DB 데이터 원본 연결 속성

#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
