dataset.editor.page.query=Consulta

# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# NLS messages
#
plugin.name=BIRT Sample DB Designer
newwizard.name=BIRT Sample DB Data Source
newwizard.description=Crear un perfil de conexión de base de datos de muestra BIRT

wizard.window.title=Nuevo perfil de fuente de datos de base de datos de muestra

wizard.data.source.page.title=Nueva fuente de datos de muestra de Classic Models Inc.

profile.propertypage.name=BIRT Sample DB Data Source Connection Properties
