#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=PostScript 형식의 보고서 렌더링 옵션을 구성합니다.
PostscriptEmitter.DisplayName=PostScript

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 처리
OptionDisplayValue.TextWrapping=텍스트 배치
OptionDisplayValue.PageOverFlow=페이지 오버플로 처리
OptionDisplayValue.CLIP_CONTENT=내용 자르기
OptionDisplayValue.FIT_TO_PAGE_SIZE=페이지 크기에 맞추기
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=여러 페이지로 출력
OptionDisplayValue.ENLARGE_PAGE_SIZE=페이지 크기 확대
OptionDisplayValue.FontSubstitution=글꼴 대체
OptionDisplayValue.Copies=매수
OptionDisplayValue.Collate=한 부씩 인쇄
OptionDisplayValue.Duplex=양면
OptionDisplayValue.PaperSize=용지 크기
OptionDisplayValue.PaperTray=용지함
OptionDisplayValue.ChartDpi=차트 DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=BIDI 처리를 사용합니다.
OptionDescription.TextWrapping=텍스트를 줄 바꿈합니다.
OptionDescription.PageOverFlow=내용 출력 방식을 제어합니다.
OptionDescription.FontSubstitution=선택한 글꼴에 해당 문자가 있는지 확인해야 합니다.
OptionDescription.Copies=인쇄 매수입니다.
OptionDescription.Collate=한 부씩 인쇄합니다.
OptionDescription.Duplex=양면 인쇄입니다.
OptionDescription.PaperSize=용지 크기입니다.
OptionDescription.PaperTray=용지함입니다.
OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.
