#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=Optionen zum Rendern eines Berichts im PostScript-Format konfigurieren.
PostscriptEmitter.DisplayName=PostScript

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung
OptionDisplayValue.TextWrapping=Zeilenumbruch
OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung
OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden
OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben
OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern
OptionDisplayValue.FontSubstitution=Schriftart ersetzen
OptionDisplayValue.Copies=Anzahl der Exemplare
OptionDisplayValue.Collate=Sortieren
OptionDisplayValue.Duplex=Duplex
OptionDisplayValue.PaperSize=Papierformat
OptionDisplayValue.PaperTray=Papierschacht
OptionDisplayValue.ChartDpi=Chart DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=BIDI-Verarbeitung wird verwendet.
OptionDescription.TextWrapping=Text muss Zeilenumbrüche enthalten.
OptionDescription.PageOverFlow=Legen Sie fest, wie der Inhalt ausgegeben wird.
OptionDescription.FontSubstitution=Überprüfung erforderlich, ob die ausgewählte Schriftart das Zeichen unterstützt.
OptionDescription.Copies=Anzahl der Exemplare.
OptionDescription.Collate=Sortieren.
OptionDescription.Duplex=Duplex.
OptionDescription.PaperSize=Papierformat.
OptionDescription.PaperTray=Papierschacht.
OptionDescription.ChartDpi=The DPI used to generate chart.
