#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=Configurez les options pour un rendu de rapport au format PostScript.
PostscriptEmitter.DisplayName=PostScript

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI
OptionDisplayValue.TextWrapping=Retour à la ligne automatique
OptionDisplayValue.PageOverFlow=Traitement du dépassement de page
OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu
OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages
OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page
OptionDisplayValue.FontSubstitution=Changement de police
OptionDisplayValue.Copies=Number of Copies
OptionDisplayValue.Collate=Collate
OptionDisplayValue.Duplex=Duplex
OptionDisplayValue.PaperSize=Paper Size
OptionDisplayValue.PaperTray=Paper Tray

###########################################################
#Option Description
OptionDescription.BidiProcessing=Traitement BIDI utilisé.
OptionDescription.TextWrapping=Un retour à la ligne est nécessaire.
OptionDescription.PageOverFlow=Vérifiez comment répartir le contenu.
OptionDescription.FontSubstitution=Vérification nécessaire pour savoir si le caractère existe dans la police sélectionnée.
OptionDescription.Copies=Number of Copies.
OptionDescription.Collate=Collate.
OptionDescription.Duplex=Duplex.
OptionDescription.PaperSize=Paper size.
OptionDescription.PaperTray=Paper tray.
