#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=Configure las opciones para procesar un informe en formato PostScript.

PostscriptEmitter.DisplayName=PostScript (PS)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Procesamiento de BIDI

OptionDisplayValue.TextWrapping=Autoajuste de texto

OptionDisplayValue.PageOverFlow=Procesamiento del desbordamiento de página

OptionDisplayValue.CLIP_CONTENT=Cortar contenido

OptionDisplayValue.FIT_TO_PAGE_SIZE=Ajustar a tamaño de página

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Salida de varias páginas

OptionDisplayValue.ENLARGE_PAGE_SIZE=Aumentar tamaño de página

OptionDisplayValue.FontSubstitution=Sustitución de fuente

OptionDisplayValue.Copies=Número de copias

OptionDisplayValue.Collate=Intercalar

OptionDisplayValue.Duplex=Doble cara

OptionDisplayValue.PaperSize=Tamaño de papel

OptionDisplayValue.PaperTray=Bandeja de papel

OptionDisplayValue.ChartDpi=Diagrama DPI

OptionDisplayValue.Resolution=Resolución

OptionDisplayValue.Scale=Escala

OptionDisplayValue.Color=Color

OptionDisplayValue.AutoPaperSizeSelection=Selección automática de tamaño de papel

###########################################################
#Option Description
OptionDescription.BidiProcessing=Admite texto bidireccional.

OptionDescription.TextWrapping=Indica si el texto se puede autoajustar.

OptionDescription.PageOverFlow=Controla cómo se va a mostrar el contenido.

OptionDescription.FontSubstitution=Selecciona fuentes automáticamente cuando la fuente especificada no puede mostrar el carácter.

OptionDescription.Copies=Número de copias.

OptionDescription.Collate=Intercalar.

OptionDescription.Duplex=Doble cara.

OptionDescription.PaperSize=Tamaño de papel.

OptionDescription.PaperTray=Bandeja de papel.

OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

OptionDescription.Resolution=Resolución.

OptionDescription.Scale=Escala.

OptionDescription.Color=Color.

OptionDescription.AutoPaperSizeSelection=Selecciona el tamaño de papel de acuerdo con el tamaño de página.

OptionDescription.FitToPaper=Ajustar a papel.

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.
