#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=PostScript 形式でレポートをレンダリングするためのオプションを設定します。

PostscriptEmitter.DisplayName=PostScript (PS)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=双方向テキストの処理

OptionDisplayValue.TextWrapping=文字列の折り返し

OptionDisplayValue.PageOverFlow=オーバーフローしているページの処理

OptionDisplayValue.CLIP_CONTENT=コンテンツの切り抜き

OptionDisplayValue.FIT_TO_PAGE_SIZE=ページサイズに合わせる

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=複数ページに出力

OptionDisplayValue.ENLARGE_PAGE_SIZE=ページサイズを大きくする

OptionDisplayValue.FontSubstitution=フォントの置き換え

OptionDisplayValue.Copies=部数

OptionDisplayValue.Collate=部単位で印刷

OptionDisplayValue.Duplex=両面印刷

OptionDisplayValue.PaperSize=用紙サイズ

OptionDisplayValue.PaperTray=用紙トレイ

OptionDisplayValue.ChartDpi=グラフの DPI

OptionDisplayValue.Resolution=解像度

OptionDisplayValue.Scale=スケール

OptionDisplayValue.Color=カラー

OptionDisplayValue.AutoPaperSizeSelection=用紙サイズの自動選択

###########################################################
#Option Description
OptionDescription.BidiProcessing=双方向テキストをサポートします。

OptionDescription.TextWrapping=文字列を折り返すかどうかを示します。

OptionDescription.PageOverFlow=コンテンツの出力方法を制御します。

OptionDescription.FontSubstitution=指定されたフォントで表示できない文字がある場合は、フォントを自動的に選択します。

OptionDescription.Copies=部数。

OptionDescription.Collate=部単位で印刷。

OptionDescription.Duplex=両面印刷。

OptionDescription.PaperSize=用紙サイズ。

OptionDescription.PaperTray=用紙トレイ。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

OptionDescription.Resolution=解像度。

OptionDescription.Scale=スケール。

OptionDescription.Color=カラー。

OptionDescription.AutoPaperSizeSelection=ページサイズに合わせて用紙サイズを選択します。

OptionDescription.FitToPaper=用紙に合わせる。

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。 例 : 192
