#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=Optionen zum Rendern eines Berichts im PostScript-Format konfigurieren.

PostscriptEmitter.DisplayName=PostScript (PS)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung

OptionDisplayValue.TextWrapping=Zeilenumbruch

OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung

OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden

OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben

OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern

OptionDisplayValue.FontSubstitution=Schriftart ersetzen

OptionDisplayValue.Copies=Anzahl der Exemplare

OptionDisplayValue.Collate=Sortieren

OptionDisplayValue.Duplex=Duplex

OptionDisplayValue.PaperSize=Papierformat

OptionDisplayValue.PaperTray=Papierschacht

OptionDisplayValue.ChartDpi=Diagramm-DPI

OptionDisplayValue.Resolution=Auflösung

OptionDisplayValue.Scale=Skala

OptionDisplayValue.Color=Farbe

OptionDisplayValue.AutoPaperSizeSelection=Automatische Auswahl des Papierformats

###########################################################
#Option Description
OptionDescription.BidiProcessing=Unterstützt bidirektionalen Text.

OptionDescription.TextWrapping=Gibt an, ob der Text Zeilenumbrüche enthält.

OptionDescription.PageOverFlow=Legt fest, wie der Inhalt ausgegeben wird.

OptionDescription.FontSubstitution=Wählt Schriftarten automatisch aus, wenn die angegebene Schriftart das Zeichen nicht darstellen kann.

OptionDescription.Copies=Anzahl der Exemplare.

OptionDescription.Collate=Sortieren.

OptionDescription.Duplex=Duplex.

OptionDescription.PaperSize=Papierformat.

OptionDescription.PaperTray=Papierschacht.

OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

OptionDescription.Resolution=Auflösung.

OptionDescription.Scale=Skalierung.

OptionDescription.Color=Farbe.

OptionDescription.AutoPaperSizeSelection=Wählt Papierformat je nach Seitengröße aus.

OptionDescription.FitToPaper=An Papier anpassen.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.
