#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=Configurez les options pour un rendu de rapport au format PostScript.

PostscriptEmitter.DisplayName=PostScript (PS)

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI

OptionDisplayValue.TextWrapping=Retour à la ligne automatique

OptionDisplayValue.PageOverFlow=Traitement du dépassement de page

OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu

OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages

OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page

OptionDisplayValue.FontSubstitution=Changement de police

OptionDisplayValue.Copies=Nombre de copies

OptionDisplayValue.Collate=Assembler

OptionDisplayValue.Duplex=Recto verso

OptionDisplayValue.PaperSize=Taille de papier

OptionDisplayValue.PaperTray=Alimentation papier

OptionDisplayValue.ChartDpi=DPI de graphique

OptionDisplayValue.Resolution=Résolution

OptionDisplayValue.Scale=Echelle

OptionDisplayValue.Color=Couleur

OptionDisplayValue.AutoPaperSizeSelection=Sélection automatique de la taille de papier

###########################################################
#Option Description
OptionDescription.BidiProcessing=Prend en charge le texte bidirectionnel.

OptionDescription.TextWrapping=Indique si le retour à la ligne est autorisé pour le texte.

OptionDescription.PageOverFlow=Contrôle le mode de répartition du contenu.

OptionDescription.FontSubstitution=Sélectionne des polices automatiquement lorsque la police spécifiée ne peut pas afficher le caractère.

OptionDescription.Copies=Nombre de copies.

OptionDescription.Collate=Assembler.

OptionDescription.Duplex=Recto verso.

OptionDescription.PaperSize=Taille de papier.

OptionDescription.PaperTray=Alimentation papier.

OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

OptionDescription.Resolution=Résolution.

OptionDescription.Scale=Echelle.

OptionDescription.Color=Couleur.

OptionDescription.AutoPaperSizeSelection=Sélectionne la taille du papier en fonction de la taille de la page.

OptionDescription.FitToPaper=Ajuster au papier.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.
