#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Postscript Emitter
PostscriptEmitter.Description=配置用于以 PostScript 格式呈现报表的选项。
PostscriptEmitter.DisplayName=PostScript

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 处理
OptionDisplayValue.TextWrapping=自动换行
OptionDisplayValue.PageOverFlow=页面溢出处理
OptionDisplayValue.CLIP_CONTENT=剪裁内容
OptionDisplayValue.FIT_TO_PAGE_SIZE=适合大小
OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=输出多页
OptionDisplayValue.ENLARGE_PAGE_SIZE=扩大页面大小
OptionDisplayValue.FontSubstitution=字体替代
OptionDisplayValue.Copies=份数
OptionDisplayValue.Collate=逐份打印
OptionDisplayValue.Duplex=双面打印
OptionDisplayValue.PaperSize=纸张尺寸
OptionDisplayValue.PaperTray=纸盒
OptionDisplayValue.ChartDpi=Chart DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=已使用 BIDI 处理。
OptionDescription.TextWrapping=文本应自动换行。
OptionDescription.PageOverFlow=控制如何输出内容。
OptionDescription.FontSubstitution=需要检查所选字体中是否存在字符。
OptionDescription.Copies=份数。
OptionDescription.Collate=逐份打印。
OptionDescription.Duplex=双面打印。
OptionDescription.PaperSize=纸张尺寸。
OptionDescription.PaperTray=纸盒。
OptionDescription.ChartDpi=The DPI used to generate chart.
