###############################################################################
# Copyright (c) 2004,2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=Source de données JDBC

datasource.property.odaDriverClass=Classe de pilote JDBC
datasource.property.odaURL=URL de pilote JDBC
datasource.property.odaDataSource=Source de données
datasource.property.odaUser=Nom d'utilisateur
datasource.property.odaPassword=Mot de passe

dataset.query.sqltype=Requête de sélection SQL
dataset.query.sptype=Requête de procédure stockée SQL
dataset.property.queryTimeOut=Délai d'expiration de requête (en secondes)
