###############################################################################
# Copyright (c) 2004,2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=Fuente de datos JDBC

datasource.property.odaDriverClass=Clase del controlador JDBC
datasource.property.odaURL=URL del controlador JDBC
datasource.property.odaDataSource=Fuente de datos
datasource.property.odaUser=Nombre de usuario
datasource.property.odaPassword=Contraseña

dataset.query.sqltype=Consulta de selección de SQL
dataset.query.sptype=Consulta de stored procedure de SQL
dataset.property.queryTimeOut=Tiempo límite de consulta (en segundos)
