###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
datasource.name=JDBC 数据源
oda.data.source.name=BIRT JDBC 数据源
connection.profile.name=BIRT JDBC 数据源连接配置文件

datasource.property.odaDriverClass=JDBC 驱动程序类
datasource.property.odaURL=JDBC 驱动程序 URL
datasource.property.odaDataSource=数据源
datasource.property.odaUser=用户名
datasource.property.odaPassword=密码

dataset.query.sqltype=SQL 选择查询
dataset.query.sptype=SQL 存储过程查询
dataset.property.queryTimeOut=查询时间（秒）
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
