###############################################################################
# Copyright (c) 2004,2005 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# NLS String
###############################################################################
datasource.name=JDBC データソース

datasource.property.odaDriverClass=JDBC ドライバクラス
datasource.property.odaURL=JDBC ドライバ URL
datasource.property.odaDataSource=データソース
datasource.property.odaUser=ユーザ名
datasource.property.odaPassword=パスワード

dataset.query.sqltype=SQL Select クエリ
dataset.query.sptype=SQL ストアドプロシージャのクエリ
dataset.property.queryTimeOut=クエリのタイムアウト (秒)
