###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
datasource.name=Fuente de datos JDBC
oda.data.source.name=Fuente de datos JDBC BIRT
connection.profile.name=Perfil de conexión de fuente de datos JDBC BIRT

datasource.property.odaDriverClass=Clase del controlador JDBC
datasource.property.odaURL=URL del controlador JDBC
datasource.property.odaDataSource=Fuente de datos
datasource.property.odaUser=Nombre de usuario
datasource.property.odaPassword=Contraseña

dataset.query.sqltype=Consulta de selección de SQL
dataset.query.sptype=Consulta de stored procedure de SQL
dataset.property.queryTimeOut=Tiempo límite de consulta (en segundos)
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
