###########################################################
#AbstractDataSetWizard properties

AbstractDataSetWizard.ModelTrans.Create=Définir le type, la source et le nom du jeu de données
###########################################################
#CssErrDialog
CssErrDialog.shellTitle.ImportCssStyleMssageTitle=Message d'importation
CssErrDialog.AreaTitle=Message d'importation des styles CSS
CssErrDialog.AreaMessage=Des erreurs ou des avertissements sont apparus lors de l'importation des styles css.
CssErrDialog.Serverity=Gravité :
CssErrDialog.Message=Message :
CssErrDialog.FatalError=Erreur fatale
CssErrDialog.Error=Erreur
CssErrDialog.Warning=Avertissement

###########################################################
#AddGroupAction properties

AddGroupAction.actionMsg.addGroup=Insérer le groupe...
AddGroupAction.Menu.Text=Insérer le groupe...
AddGroupAction.stackMsg.addGroup=Insérer le groupe

###########################################################
#AddLibraryAction properties

AddLibraryAction.Error.FileNotFound=Fichier ''{0}'' introuvable.
AddLibraryAction.Error.FileIsNotLibrary=Le fichier ''{0}'' ne se termine pas par ''{1}''.
AddLibraryAction.Error.Message=Ce fichier existe déjà.
AddLibraryAction.Error.Title=Erreur
AddLibraryAction.Text=Ajouter une bibliothèque...
AddLibraryAction.Dialog.Tilte=Sélectionnez une bibliothèque

###########################################################
#DeleteLibraryAction properties
DeleteLibraryAction.Text=Supprimer
###########################################################
#AddStyleRuleAction properties

AddStyleAction.actionMsg.addStyleRule=&Nouveau style...
AddStyleAction.stackMsg.addStyle=&Nouveau style

###########################################################
#ApplyStyleAction properties

ApplyStyleAction.actionLabel.none=Aucun
ApplyStyleAction.stackMsg.applyStyle=Appliquer un style

###########################################################
#ApplyThemeAction properties

ApplyThemeAction.actionLabel.none=Aucun
ApplyThemeAction.stackMsg.applyStyle=Appliquer le thème

###########################################################
#AttributesBuilder properties

AttributesBuilder.Label.Cell=Editeur de propriétés - Cellule
AttributesBuilder.Label.Column=Editeur de propriétés - Colonne
AttributesBuilder.Label.Data=Editeur de propriétés - Données
AttributesBuilder.Label.Generic=Editeur de propriétés - {0}
AttributesBuilder.Label.Grid=Editeur de propriétés - Grille
AttributesBuilder.Label.Label=Editeur de propriétés - Etiquette
AttributesBuilder.Label.Library=Editeur de propriétés - Bibliothèque
AttributesBuilder.Label.List=Editeur de propriétés - Liste
AttributesBuilder.Label.MasterPage=Editeur de propriétés - Page maître
AttributesBuilder.Label.None=Editeur de propriétés - Aucun
AttributesBuilder.Label.Picture=Editeur de propriétés - Image
AttributesBuilder.Label.Report=Editeur de propriétés - Etat
AttributesBuilder.Label.Row=Editeur de propriétés - Ligne
AttributesBuilder.Label.Table=Editeur de propriétés - Table
AttributesBuilder.Label.Text=Editeur de propriétés - Texte
AttributesBuilder.Label.TextData=Editeur de propriétés - Texte dynamique
AttributesBuilder.Label.DataSourceHandle=Editeur de propriétés - Source de données
AttributesBuilder.Label.DataSetHandle=Editeur de propriétés - Jeu de données
AttributesBuilder.Label.ScalarParameterHandle=Editeur de propriétés - Paramètre
AttributesBuilder.Label.TemplateReportItemHandle=Editeur de propriétés - Elément d'état de modèle
AttributesBuilder.Label.AutoText=Editeur de propriétés - AutoText

###########################################################
#AttributeView properties
AttributeView.dialg.Message.Warning = Avertissement
AttributeView.dialg.Message.Yes=&Oui
AttributeView.dialg.Message.No=&Non
AttributeView.dialg.Message.Cancel=&Annuler
AttributeView.dialg.Message.PromptMsg=Voulez-vous vraiment supprimer toutes les propriétés locales ?
AttributeView.toolbar.tooltip.EditingToggleAction.ClearMsg=Effacer les propriétés locales.
AttributeView.toolbar.tooltip.EditingToggleAction.EnableEditingMsg=Activer la modification des propriétés.
AttributeView.toolbar.tooltip.EditingToggleAction.DisabledActionMsg=Cette action n'est pas disponible pour les éléments locaux.
AttributeView.view.message.Emptypage= {0} s''étend à partir de {1} dans la bibliothèque {2}. Pour activer la modification des propriétés de {3} dans ce modèle d''état, cliquez sur le bouton Activer la modification dans la barre d''outils de l''Editeur de propriétés.
AttributeView.toolbar.tooltip.RestoreLibraryPropertiesAction.RestoreMsg=Restaurer les propriétés
AttributeView.defaultText.noAttributeView = L'éditeur de propriétés n'est pas disponible.
###########################################################
#BackGroundPreferencePage properties

BackGroundPreferencePage.displayname.Title=Arrière-plan

###########################################################
#BasAttributePage properties

BasAttributePage.Label.Attributes=Propriétés :

###########################################################
#BaseInsertMenuAction properties

BaseInsertMenuAction.stackMsg.insertElement=Insérer un élément

###########################################################
#BasePaletteFactory properties

BasePaletteFactory.AutoText.Confidential=Confidentiel
BasePaletteFactory.AutoTextLabel.CreatedBy=Création par : 
BasePaletteFactory.AutoTextLabel.CreatedOn=Création le : 
BasePaletteFactory.AutoTextLabel.Filename=Nom de fichier : 
BasePaletteFactory.AutoTextLabel.LastPrinted=Dernière impression : 
BasePaletteFactory.AutoTextLabel.Page=Page : 
BasePaletteFactory.AutoTextLabel.PageCount=Nombre de pages :
BasePaletteFactory.AutoTextLabel.PageXofY=Page X sur Y
BasePaletteFactory.categoryName.PointerSelect=Sélection avec le pointeur
BasePaletteFactory.categoryName.RectangleSelect=Sélection avec le rectangle
BasePaletteFactory.Group.Items=Eléments
BasePaletteFactory.toolTip.PointerSelect=Cliquez sur un élément pour le sélectionner. Pour une sélection multiple, cliquez en maintenant la touche Ctrl enfoncée.
BasePaletteFactory.toolTip.RectangleSelect=Cliquez et faites glisser le pointeur pour sélectionner plusieurs éléments contigus. 

###########################################################
#BaseStylePreferencePage properties

BaseStylePreferencePage.displayname.Title=Général

###########################################################
#BgImageFieldEditor properties

BgImageFieldEditor.displayname.Browse=Par&courir...

###########################################################
#BindingPage properties

BindingPage.Label.Binding=Liaison
BindingPage.MessageDlg.SaveParamBinding=Enregistrer ParamBinding
BindingPage.None=Aucun
BindingPage.TableColumn.DataType=Type de données
BindingPage.TableColumn.Parameter=Paramètre
BindingPage.TableColumn.Value=Valeur

ColumnBingingDialog.Label.Warn=La modification du jeu de données peut rendre toutes les expressions de colonne du jeu de résultats non valides.
ColumnBindingDialog.Label.DataSet=Jeu de données :
ColumnBindingDialog.Column.Expression=Expression
ColumnBindingDialog.DialogTitle=Sélectionner la liaison de données
ColumnBindingDialog.Column.Name=Nom
ColumnBindingDialog.Column.displayName=Nom d'affichage
ColumnBindingDialog.InputPrompt=<Entrer la nouvelle valeur ici...>
ColumnBindingDialog.Button.Generate=Générer des liaisons de colonne
ColumnBindingDialog.Column.DataType=Type de données
ColumnBindingDialog.Column.AggregateOn=Regrouper par
ColumnBindingDialog.All=Tous
ColumnBindingDialog.NONE=Aucun
ColumnBindingDialog.Choice.FromContainer=Jeu de données du conteneur
ColumnBindingDialog.AGGREGATEON.NONE=N/A
ColumnBindingDialog.Text.Add=Ajouter
ColumnBindingDialog.Text.Edit=Modifier...
ColumnBindingDialog.Text.Del=Supprimer

###########################################################
#BlockPreferencePage properties

BlockPreferencePage.displayname.Title=Bloc de texte

###########################################################
#BorderPreferencePage properties

BorderPreferencePage.displayname.Color=Couleur
BorderPreferencePage.displayname.Style=Style
BorderPreferencePage.displayname.Title=Bordure
BorderPreferencePage.displayname.Width=Largeur
BorderPreferencePage.text.Bottom=Bas :
BorderPreferencePage.text.Left=Gauche :
BorderPreferencePage.text.Right=Droite :
BorderPreferencePage.text.Top=Haut :

###########################################################
#BordersPage properties

BordersPage.Label.Borders=&Bordures :
BordersPage.Label.Color=&Couleur :
BordersPage.Label.Presets=Valeurs par défaut :
BordersPage.Label.Style=&Style :
BordersPage.Label.Width=&Largeur :
BordersPage.Tooltip.All=Toutes les bordures
BordersPage.Tooltip.Bottom=Bordure inférieure
BordersPage.Tooltip.Left=Bordure de gauche
BordersPage.Tooltip.None=Aucun
BordersPage.Tooltip.Right=Bordure de droite
BordersPage.Tooltip.Top=Bordure supérieure
BordersPage.text.Preview=Aperçu :
BordersPage.Trans.SelectBorder=Sélectionner une bordure
BordersPage.Trans.UnSelectBorder=Désélectionner la bordure
BordersPage.Trans.SelectAllborders=Sélectionner toutes les bordures
BordersPage.Trans.UnSelectAllborders=Désélectionner toutes les bordures

###########################################################
#BoxPreferencePage properties

BoxPreferencePage.displayname.Title=Zone
BoxPreferencePage.text.Margin=Marge
BoxPreferencePage.text.Padding=Remplissage

###########################################################
#ButtonPaneComposite properties

ButtonPaneComposite.tooltip.MasterPage=Page maître
ButtonPaneComposite.tooltip.Normal=Normal
ButtonPaneComposite.tooltip.Ruler=Règle

###########################################################
#SettingsPage properties

SettingsPage.dataFetchSetting.label=Nombre maximum de lignes à récupérer à partir de la source de données :
SettingsPage.CachePreference.button.clear=Vider le &cache
SettingsPage.CachePreference.checkBox.text=Mettre en cac&he les données des jeux de données pour la prévisualisation de l'état
SettingsPage.CachePreference.description=Définir la taille du cache :
SettingsPage.CachePreference.Filter.Tooltip=Inclure ou exclure le cache de votre jeu de données
SettingsPage.CachePreference.label.text=lignes
SettingsPage.CachePreference.messageBox.info=Le cache a été vidé.
SettingsPage.CachePreference.messageBox.title=Cache vide
SettingsPage.CachePreference.radioBox.entireNumText=M&ettre en cache l'ensemble du jeu de données
SettingsPage.CachePreference.radioBox.numText=Mettre en cache et &utiliser en premier

###########################################################
#CascadingParametersDialog properties

CascadingParametersDialog.Button.AllowNull=&Autoriser une valeur nulle
CascadingParametersDialog.default.preview.string=Ma chaîne
CascadingParametersDialog.display.controlType.comboBox=Zone déroulante
CascadingParametersDialog.display.controlType.listBox=Liste déroulante
CascadingParametersDialog.Label.button.changeFormat=&Modifier...
CascadingParametersDialog.Label.button.createNew.dataset=&Créer...
CascadingParametersDialog.Label.cascadingParam.name=Nom de paramètre en &cascade :
CascadingParametersDialog.Label.column.displayText=Texte d'affichage
CascadingParametersDialog.Label.column.dataSet=Jeu de données
CascadingParametersDialog.Label.column.name=Nom
CascadingParametersDialog.Label.column.value=Valeur
CascadingParametersDialog.Label.createNewParam=<Créer un nouveau paramètre...>
CascadingParametersDialog.Label.dataSets=Jeu de donnée&s :
CascadingParametersDialog.Label.dataType=Type de &données
CascadingParametersDialog.Label.defaultValue=&Valeur par défaut :
CascadingParametersDialog.Label.displayType=&Type d'affichage :
CascadingParametersDialog.Label.formatAs=Format :
CascadingParametersDialog.Label.group.general=Général
CascadingParametersDialog.Label.group.moreOptions=Autres options
CascadingParametersDialog.Label.group.properties=Propriétés
CascadingParametersDialog.Label.helpText=&Texte d'aide :
CascadingParametersDialog.Label.listLimit=L&imite de liste :
CascadingParametersDialog.Label.NoColumnAvailable=<Aucune colonne disponible>
CascadingParametersDialog.Label.param.name=&Nom :
CascadingParametersDialog.Label.parameters=Paramètres
CascadingParametersDialog.Label.preview=Aperçu au format
CascadingParametersDialog.Label.groupPromptText=&Texte de l'invite :
CascadingParametersDialog.Label.parameterPromptText=Te&xte de l'invite :
CascadingParametersDialog.Label.selectDataSet=<Sélectionnez un jeu de données>
CascadingParametersDialog.Label.selectDisplayColumn=<Sélectionner une colonne à afficher>
CascadingParametersDialog.Label.selectValueColumn=<Sélectionner une colonne de valeur>
CascadingParametersDialog.Label.values=valeurs
CascadingParametersDialog.Label.SelectDataSetMode=Mode de jeu de données :
CascadingParametersDialog.Radio.Single=Jeu de données unique
CascadingParametersDialog.Radio.Mutli=Jeu de données multiple

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Propriétés

###########################################################
#CellPageGenerator properties

CellPageGenerator.List.Borders=Bordure
CellPageGenerator.List.CellPadding=Remplissage
CellPageGenerator.List.Font=Police
CellPageGenerator.List.General=Général
CellPageGenerator.TabItem.Highlights=Surbrillances
CellPageGenerator.TabItem.map=Mappage

###########################################################
#LabelPageGenerator properties
LabelPageGenerator.TabItem.Highlights=Surbrillances


###########################################################
#ChoiceSetFactory properties

ChoiceSetFactory.choice.Auto=Auto
ChoiceSetFactory.choice.None=Aucun

###########################################################
#CodePageAction properties

CodePageAction.actionText.code=Script

###########################################################
#ColorBuilder properties

ColorBuilder.text.None=Auto

###########################################################
#ColumnPageGenerator properties

ColumnPageGenerator.List.Borders=Bordure
ColumnPageGenerator.List.CellPadding=Marge intérieure
ColumnPageGenerator.List.Font=Police
ColumnPageGenerator.List.General=Général
ColumnPageGenerator.TabItem.Highlights=Surbrillances
ColumnPageGenerator.TabItem.map=Mappage
ColumnPageGenerator.List.Visibility=Visibilité

###########################################################
#Commom properties

Commom.ShortDateTime.Fri=VEN
Commom.ShortDateTime.Mon=LUN
Commom.ShortDateTime.Sat=SAM
Commom.ShortDateTime.Sun=DIM
Commom.ShortDateTime.Thu=JEU
Commom.ShortDateTime.Tue=MAR
Commom.ShortDateTime.Wed=MER

###########################################################
#Connection Profile Properties
connectionprofile.wizard.title=Nouvelle source de données
connectionprofile.wizard.title.connectionprofileselect=Sélectionner un profil de connexion
connectionprofile.wizard.defaultmessage.connectionprofileselect=Sélectionnez le profil de connexion à partir duquel créer la source de données
connectionprofile.wizard.label.connectionprofilestore=Emplacement de stockage des profils de connexion :
connectionprofile.wizard.label.datasourcename=Nom de la source de données :
connectionprofile.wizard.checkbox.datasourcenameusedefaultdsname=Utiliser le nom de la source de données par défaut
connectionprofile.wizard.tree.datasourcename=Sources de données ODA
connectionprofile.wizard.button.browse=Parcourir...

###########################################################
#CopyAction properties

CopyAction.text=&Copier

###########################################################
#CreatePlaceHolderAction properties

CreatePlaceHolderAction.text=Cré&er un élément d'état modèle...

###########################################################
#CutAction properties

CutAction.text=Co&uper
CutAction.trans=Couper les éléments

###########################################################
#dataBinding properties

dataBinding.label.selectBinding=Sélectionner la liaison de données :
dataBinding.message.changeDataSet=Vous allez modifier la liaison des données de l'élément.  \n\nVoulez-vous effacer toutes les informations des champs de données ?
dataBinding.title.changeDataSet=Modifier le jeu de données ?
dataBinding.title=Liaison de données

parameterBinding.title=Liaison de paramètre de jeu de données...



###########################################################
#DataEditPart properties

DataEditPart.Figure.Dafault=Données
DataEditPart.Figure.Expression=expression

###########################################################
#DataEditPart properties

DestroyEditPart.Message=Le contenu de cet élément d'état est corrompu. Pour continuer à utiliser cet état, vous devez d'abord supprimer cet élément. Dans le cas contraire, le fichier du modèle d'état risque de subir des dommages et/ou la réactivité de Report Designer risque d'être altérée.

###########################################################
#DataPageGenerator properties

DataPageGenerator.List.Bookmark=Signet
DataPageGenerator.List.Borders=Bordure
DataPageGenerator.List.Duplicates=Doublons
DataPageGenerator.List.Expression=Expression
DataPageGenerator.List.Format=Format
DataPageGenerator.List.formatDateTime=Date/heure
DataPageGenerator.List.formatNumber=Nombre
DataPageGenerator.List.formatString=Chaîne
DataPageGenerator.List.General=Général
DataPageGenerator.List.Highlights=Surbrillances
DataPageGenerator.List.HyperLink=Lien hypertexte
DataPageGenerator.List.Margin=Marge
DataPageGenerator.List.Padding=Remplissage
DataPageGenerator.List.Section=Saut de page
DataPageGenerator.List.TOC=Table des matières
DataPageGenerator.List.Visibility=Visibilité
DataPageGenerator.TabItem.map=Mappage

###########################################################
#dataset properties

dataset.edit=Modifier le jeu de données - {0}

dataset.editor.settings=Paramètres
dataset.editor.settings.dataFetchSetting.errorNumberFormat=Entrez un nombre supérieur à zéro pour la limite de récupération de ligne.
dataset.editor.settings.dataFetchSetting=Paramètre de récupération de données
dataset.editor.settings.cachePreference.errorNumberFormat=Entrez un nombre supérieur à zéro pour la taille des lignes en cache
dataset.editor.settings.cachePreference=Préférences de cache
dataset.editor.computedColumns=Colonnes de calcul
dataset.editor.dataSource.Tooltip=Afficher/modifier la source de données
dataset.editor.dataSource=Source de données
dataset.editor.error.columnOrAliasNameAlreadyUsed=Le nouveau nom ou alias de colonne ({0}) est déjà utilisé par la colonne à l''index {1}.
dataset.editor.error.computedColumnNameAlreadyUsed=Le nouveau nom de la colonne de calcul ({0}) est déjà utilisé comme alias pour la colonne ({1}) dans les Colonnes de sortie.
dataset.editor.error.duplicateParameterName=Nom de paramètre en double
dataset.editor.error.emptyName=Le nom ne doit pas rester vierge. 
dataset.editor.error.missingComputedColumnExpression=L''expression de la colonne de calcul {0} ne peut être ni nulle, ni vide.
dataset.editor.error.missingComputedColumnName=Le nom de la colonne de calcul ne peut être ni nul, ni vide.
dataset.editor.error.noDataSource=Aucune source de données disponible pour le jeu de données {0}, sélectionnez une source de données dans l''entrée Source de données de la vue des propriétés.
dataset.editor.error.noEditorsFound=Aucun éditeur trouvé pour le jeu de données {0}.
dataset.editor.error.noInputParameterDefaultValue=Le paramètre d''entrée {0} doit comporter une valeur non nulle par défaut.
dataset.editor.error.title=Avertissement
dataset.editor.error.unsupportedDataSet=Type de jeu de données non pris en charge - {0}.
dataset.editor.error.validationParameter=Un paramètre d'entrée [{0}] contient une valeur vierge. Voulez-vous laisser cette valeur vierge ?
dataset.editor.filters=Filtres
dataset.editor.label.selectDataSource=Sélectionner une source de &données :
dataset.editor.outputColumns=Colonnes de sortie
dataset.editor.parameters=Paramètres
dataset.editor.preview=Prévisualiser les résultats
dataset.editor.outputparameters=Prévisualiser les paramètres de sortie
dataset.editor.title.alias=Alias
dataset.editor.title.columnName=Nom de colonne
dataset.editor.title.dataType=Type de données
dataset.editor.title.defaultValue=Valeur par défaut
dataset.editor.title.direction=Direction
dataset.editor.title.displayName=Nom d'affichage
dataset.editor.title.expression=Expression
dataset.editor.title.helpText=Texte d'aide
dataset.editor.title.isInput=Est une entrée
dataset.editor.title.isNullable=Autorise une valeur nulle
dataset.editor.title.isOptional=Facultatif
dataset.editor.title.isOutput=Est une sortie
dataset.editor.title.name=Nom
dataset.editor.title.operator=Opérateur
dataset.editor.title.type=Type
dataset.editor.title.value1=Valeur 1
dataset.editor.title.value2=Valeur 2
dataset.editor.historybar.backward=Précédent
dataset.editor.historybar.forward=Suivant
dataset.editor.historybar.to=en
dataset.error.noDataSources=Aucune source de données disponible.\nAjoutez une source de données.
dataset.error.dataSourceMissing=La source de données du jeu de données est manquante.
dataset.error.title.noDataSources=Aucune source de données disponible.
dataset.message.create=Créez un nouveau jeu de données.
dataset.new.defaultName=Jeu de données
dataset.new=Nouveau jeu de données
dataset.join.new=Nouveau jeu de données de jointure
dataset.resultset.preview.tooltip=Prévisualiser les résultats de la requête
dataset.outputparameters.preview.tooltip=Prévisualiser les paramètres de sortie
dataset.wizard.label.datasetName=No&m du jeu de données :
dataset.wizard.label.datasetType=&Type de jeu de données :
dataset.wizard.label.dataSource=&Source de données :

###########################################################
#DataSetBasePage properties

DataSetBasePage.tooltip=Le nom doit être renseigné

###########################################################
#JointDataSetPage properties

JointDataSetPage.pageName=Jeu de données de jointure
JointDataSetPage.page.detail=Sélectionner un jeu de données et une colonne de chaque côté pour définir une jointure
JointDataSetPage.button.innerJoin=Jointure &interne
JointDataSetPage.button.leftJoin=&Jointure externe gauche
JointDataSetPage.button.rightJoin=&Jointure externe droite
JointDataSetPage.button.fullJoin=&Jointure externe complète
JointDataSetPage.joinType=Types de jointures
JointDataSetPage.error.nodataset.title=Aucun jeu de données n'a été trouvé
JointDataSetPage.error.nodataset.right=Le jeu de données droit n'a pas été trouvé
JointDataSetPage.error.nodataset.left=Le jeu de données gauche n'a pas été trouvé
JointDataSetPage.pageDescription=Définir le jeu de données de jointure
JointDataSetPage.query=Requête

###########################################################
#DataSetComputedColumnsPage properties

DataSetComputedColumnsPage.ComputedColumns.Tooltip=Définissez les colonnes de calcul. 
DataSetComputedColumnsPage.description=Définir des colonnes de calcul :
DataSetComputedColumnsPage.duplicatedName=Nom de colonne en double
DataSetComputedColumnsPage.toolTipText.Down=Déplacer la colonne de calcul vers le bas
DataSetComputedColumnsPage.toolTipText.Up=Déplacer la colonne de calcul vers le haut
DataSetComputedColumnsPage.toolTipText.Remove=Supprimer la colonne de calcul
DataSetComputedColumnsPage.toolTipText.New=Nouvelle colonne de calcul
DataSetComputedColumnsPage.toolTipText.Edit=Modifier la colonne de calcul
DataSetComputedColumnsPage.title.ComputedColumnInputDialog=Colonne de calcul

###########################################################
#DataSetFiltersPage properties

DataSetFiltersPage.description=Définir des filtres :
DataSetFiltersPage.exception.msg.operator.notSupport=Opérateur non pris en charge : 
DataSetFiltersPage.Filter.Tooltip=Filtrez vos lignes de données au moyen d'expressions BIRT.
DataSetFiltersPage.toolTipText.Down=Déplacer le filtre vers le bas
DataSetFiltersPage.toolTipText.Up=Déplacer le filtre vers le haut
DataSetFiltersPage.toolTipText.Remove=Supprimer le filtre :
DataSetFiltersPage.toolTipText.New=Nouveau filtre
DataSetFiltersPage.toolTipText.Edit=Modifier le filtre
DataSetFiltersPage.title.FilterInputDialog=Filtre
DataSetFiltersPage.messages.selectVauleUnavailable=Liste de valeurs non disponible avec l'expression spécifiée

###########################################################
#DataSetNodeProvider properties

DataSetNodeProvider.menu.text=Modifier

###########################################################
#DataSetParametersPage properties

DataSetParametersPage.description=Définir les paramètres d'entrée :
DataSetParametersPage.Filter.Tooltip=Inclure ou exclure des paramètres de votre jeu de données.
DataSetParameterBindingInputDialog.Title=Modifier la liaison de paramètre du jeu de données
DataSetParametersPage.ErrorTitle.InvalidInput=Entrée non valide
DataSetParameterBindingInputDialog.Label.Name=Nom du paramètre :
DataSetParametersPage.ErrorMessage.CanootBeNull=La valeur ne peut pas être nulle.
DataSetParameterBindingInputDialog.Label.DataType=Type de données :
DataSetParameterBindingInputDialog.Label.Value=Valeur :
DataSetParametersPage.Prompt.new=<Nouveau paramètre ici...>
DataSetParametersPage.default.None=N/A
DataSetParametersPage.reportParam.None=Aucun
DataSetParameterPage.cell.linkToSalarParameter=Lié au paramètre d'état
DataSetParameterPage.title.ParameterInputDialog=Paramètre
DataSetParameterPage.toolTipText.New=Nouveau paramètre
DataSetParameterPage.toolTipText.Edit=Modifier le paramètre
DataSetParameterPage.toolTipText.Remove=Supprimer le paramètre
DataSetParameterPage.toolTipText.Up=Déplacer le paramètre vers le haut
DataSetParameterPage.toolTipText.Down=Déplacer le paramètre vers le bas

###########################################################
#PropertyBindingpage properties
PropertyBindingPage.datasource.property.empty=Aucune propriété publique n'est définie par l'extension ODA de cette source de données
PropertyBindingPage.dataset.property.empty=Aucune propriété publique n'est définie par l'extension ODA de ce jeu de données
PropertyBindingPage.dataset.queryText=Texte de la re&quête
PropertyBindingPage.property.tooltip=Définir une liaison de propriété pour l'exécution
PropertyBindingPage.button.tooltip=Ouvrir le Générateur d''expression pour entrer la valeur {0}

###########################################################
#DataSetProcess properties

DataSetProcess.action.Delete=Supprimer le jeu de données
DataSetProcess.action.Edit=Modifier le jeu de données
DataSetProcess.action.Preview=Aperçu
DataSetProcess.text.DisplayName=Jeu de données
DataSetProcess.text.Prefix=Le(s) jeu(x) de données suivant(s) utilise(nt) cette source de données :
DataSetProcess.text.Show=Affiche la page de l'éditeur de jeu de données pour ce jeu de données.
DataSetProcess.text.Suffix=Supprimer cet élément ?

###########################################################
#datasource properties

datasource.action.edit=Modifier
datasource.edit=Modifier la source de données - {0}
datasource.new.defaultName=Source de données
datasource.new=Nouvelle source de données
datasource.wizard.label.dataSourceName=No&m de la source de données :
datasource.wizard.label.datasources=Créer à partir d'un type de source de données de la liste suivante
datasource.wizard.label.datasources=Créer à partir d'un type de source de données de la liste suivante
datasource.wizard.label.connectionfile=Créer à partir d'un profil de connexion de l'emplacement de stockage des profils
datasource.wizard.message.selectType=Indiquer tous les paramètres pour une nouvelle source de données ou choisir un profil de connexion prédéfini
datasource.wizard.title.select=Sélectionner un type de source de données ou choisir un profil de connexion
datasource.editor.property=Liaison de propriété

###########################################################
#DataSourceProcess properties

DataSourceProcess.action.Delete=Supprimer la source de données
DataSourceProcess.action.Edit=Modifier la source de données
DataSourceProcess.text.DisplayName=DataSource
DataSourceProcess.text.Prefix=Le(s) jeu(x) de données suivant(s) utilise(nt) cette source de données
DataSourceProcess.text.Show=Affiche la page de l'éditeur de source de données  
DataSourceProcess.text.Suffix=Supprimer cet élément ?

###########################################################
#DataSourceSelectionPage properties

DataSourceSelectionPage.ScriptDataSource.DisplayName=Source de données nécessitant un script

###########################################################
#DataSourcesSlotOutlineProcess properties

DataSourcesSlotOutlineProcess.action.New=Nouvelle source de données

###########################################################
#datatypes properties

datatypes.any=Indifféremment
datatypes.auto=Auto
datatypes.dateTime=Date Heure
datatypes.decimal=Décimales
datatypes.float=Flottante
datatypes.integer=Entier
datatypes.string=Chaîne

###########################################################
#DataView properties

DataView.defaultText.noDataView=Une vue de données n'est pas disponible.

###########################################################
#DataViewTreeViewerPage properties

DataViewTreeViewerPage.tooltip.DoubleClickToEdit=Cliquez deux fois pour modifier
DataViewTreeViewerPage.tooltip.DragToInsertColumn=Faites glisser pour insérer la colonne 
DataViewTreeViewerPage.tooltip.DragToInsertDataSetColumns=Faites glisser pour insérer toutes les colonnes de jeux de données 
DataViewTreeViewerPage.tooltip.DragToInsertParameter=Faites glisser pour insérer le paramètre d'état ; 

###########################################################
#DebugUtil properties

DebugUtil.importProject.fail=« Echec de l'importation du fichier existant. »

###########################################################
#DecorationFieldEditor properties

DecorationFieldEditor.text.Linethrough=Texte barré
DecorationFieldEditor.text.Overline=Texte surligné
DecorationFieldEditor.text.Underline=Soulignement

###########################################################
#DefaultNodeProvider properties

DefaultNodeProvider.Dlg.Confirm=Voulez-vous vraiment supprimer cet élément ?
DefaultNodeProvider.ParameterGroup.ConfirmMessage=Vous êtes sur le point de supprimer un groupe de paramètres. Si vous confirmez la suppression, tous les paramètres du groupe seront supprimés. Voulez-vous continuer ?
DefaultNodeProvider.ParameterGroup.ConfirmTitle=Confirmer la suppression du groupe de paramètres
DefaultNodeProvider.Tree.Body=Corps
DefaultNodeProvider.Tree.Clients=\\ a les clients suivants
DefaultNodeProvider.Tree.ColumnHedings=En-têtes de colonnes
DefaultNodeProvider.Tree.Components = Eléments d'état
DefaultNodeProvider.Tree.DataSets=Jeux de données
DefaultNodeProvider.Tree.DataSources=Sources de données
DefaultNodeProvider.Tree.Detail=Détails
DefaultNodeProvider.Tree.Footer=Pied de page
DefaultNodeProvider.Tree.Groups=Groupes
DefaultNodeProvider.Tree.Header=En-tête
DefaultNodeProvider.Tree.Images=Images incorporées
DefaultNodeProvider.Tree.Invalid=Noeud non valide
DefaultNodeProvider.Tree.MasterPages=MasterPages
DefaultNodeProvider.Tree.PageSetup=Mise en page
DefaultNodeProvider.Tree.Parameters=Paramètres de l'état
DefaultNodeProvider.Tree.Reference=Référence trouvée
DefaultNodeProvider.Tree.Scratch=Zone de travail
DefaultNodeProvider.Tree.Styles=Styles
DefaultNodeProvider.Tree.Themes=Thèmes
DefaultNodeProvider.WarningDialog.Title=Avertissement
DefaultNodeProvider.WarningDialog.EmptyList=Aucun élément disponible pour insertion.

###########################################################
#DeleteAction properties

DeleteAction.text=&Supprimer
DeleteAction.trans=Supprimer les éléments

###########################################################
#DeleteColumnAction properties

DeleteColumnAction.actionMsg.delete=&Supprimer

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.actionMsg.deleteGroup=Supprimer le &groupe

###########################################################
#DeleteListGroupAction properties

DeleteListGroupAction.actionMsg.deleteGroup=Supprimer le &groupe

###########################################################
#DeleteRowAction properties

DeleteRowAction.actionMsg.delete=&Supprimer

###########################################################
#designer properties

designer.preview.browserTitle=Aperçu
designer.preview.preference.browser.autoSave=Enregistrer automatiquement avant la prévisualisation
designer.preview.preference.browser.browse=& Parcourir...
designer.preview.preference.browser.currentBrowsers=Adaptate&urs externes de navigateur Web actuels :
designer.preview.preference.browser.description=Permet de choisir les navigateurs Web utilisés pour prévisualiser les états BIRT.\nSi un seul adaptateur de navigation a été configuré, la sélection ne\npeut pas être modifiée.
designer.preview.preference.browser.details=Sélectionner un programme de navigation
designer.preview.preference.browser.program=Commande du navigateur per&sonnalisé :
designer.preview.preference.browser.svg=Activ&er le graphique SVG
designer.preview.preference.masterpagecontent=Activer le contenu de la page &maître
designer.preview.preference.browser.useExternal=&Toujours utiliser des navigateurs externes
designer.preview.preference.elementname.columnwidth=125
designer.preview.preference.elementname.customname.Enabled=true
designer.preview.preference.elementname.customname=Nom par défaut
designer.preview.preference.elementname.defaultname.Enabled=false    
designer.preview.preference.elementname.defaultname=Nom de l'élément
designer.preview.preference.elementname.description.Enabled=false
designer.preview.preference.elementname.description=Description
designer.preview.preference.elementname.Enabled=true 
designer.preview.preference.locale.description=&Choisir vos informations locales :
designer.preview.preference.resultset.sqldatasetpage.group.title=Page de requête
designer.preview.preference.resultset.previewpage.group.title=Page de prévisualisation
designer.preview.preference.resultset.maxNoOfSchema.description=Nombre maximum de &schémas à afficher :
designer.preview.preference.resultset.maxNoOfTable.description=Nombre maximum de &tables de chaque schéma à afficher :
designer.preview.preference.resultset.maxNoOfSchema.errormessage=Entrez un chiffre compris entre 0 et {0} pour le nombre maximum de schémas.
designer.preview.preference.resultset.maxNoOfTable.errormessage=Entrez un chiffre compris entre 0 et {0} pour le nombre maximum de tables de chaque schéma.
designer.preview.preference.resultset.maxrow.description=Nombre maximum de lignes à affiche&r :
designer.preview.preference.resultset.maxrow.errormessage=Entrez un nombre compris entre 1 et {0} pour le nombre maximal de lignes.
designer.preview.preference.server.description=Configuration du serveur d'application interne. Le serveur est utilisé en interne par\nla structure de prévisualisation de BIRT Report Designer.
designer.preview.preference.server.hostDescription=Nom d'&hôte ou adresse IP de la machine locale. Ne pas renseigner, détermination\nautomatique.
designer.preview.preference.server.note=Remarque :
designer.preview.preference.server.portDescription=&Port pour l'écoute par le serveur. Réglé sur 0 pour une attribution dynamique.
designer.preview.preference.server.requireRestart=Si le serveur est déjà en cours d'exécution, ces préférences ne prendront effet\nqu'après redémarrage.
designer.preview.previewaction.label.webviewer=Afficher l'état dans le visualiseur Web
designer.preview.previewaction.label=Afficher l''état au format {0}
designer.preview.previewaction.ErrorMessage=La fonction de génération de PDF n'est pas activée car iText n'est pas installé ou est introuvable.
designer.preview.previewaction.ErrorMessage.title=Avertissement

###########################################################
#DesignerActionBarContributor properties

DesignerActionBarContributor.element.group=Insérer le &groupe
DesignerActionBarContributor.element.InsertColumnLeft=Insérer des colonnes à g&auche
DesignerActionBarContributor.element.InsertColumnRight=Insérer des colonnes à &droite
DesignerActionBarContributor.element.InsertRowAbove=Insérer une ligne au-de&ssus
DesignerActionBarContributor.element.InsertRowBelow=Insérer une ligne au-desso&us
DesignerActionBarContributor.element.merge=&Fusionner les cellules
DesignerActionBarContributor.element.split=Fractionner la &cellule
designerActionBarContributor.menu.data-newdataset=Nouveau jeu de donné&es
designerActionBarContributor.menu.data-newdatasource=Nouvelle source de d&onnées
DesignerActionBarContributor.menu.data=&Données
DesignerActionBarContributor.menu.element-EditGroup=&Modifier le groupe
DesignerActionBarContributor.menu.element-LayoutMode=Mode de mise en &page
DesignerActionBarContributor.menu.element-showRuler=&Afficher les règles 
DesignerActionBarContributor.menu.element.editDataBinding=Mod&ifier la liaison de données
DesignerActionBarContributor.menu.element=E&lément
DesignerActionBarContributor.menu.format=Format
DesignerActionBarContributor.menu.insert=&Insérer
DesignerActionBarContributor.menu.page=Pa&ge
DesignerActionBarContributor.menu.style-rule-apply=A&ppliquer un style
DesignerActionBarContributor.menu.style-rule-edit=Mo&difier le style
DesignerActionBarContributor.style.new=&Nouveau style...
DesignerActionBarContributor.menu.data-NewParameter=Nouveau &paramètre d'état

###########################################################
#DesignerOutlinePage properties

DesignerOutlinePage.action.Delete=Supprimer les sélections
DesignerOutlinePage.action.Hide=Masquer l'en-tête et le pied de page
DesignerOutlinePage.action.Redo=Rétablir
DesignerOutlinePage.action.Undo=Annuler
DesignerOutlinePage.menu.Filters=Filtres

###########################################################
#Content outline page switch action
ContentOutlinePage.action.text.reportOutline=Passer au contour de la source XML
ContentOutlinePage.action.text.reportXMLSourceOutline=Passer au contour de l'état

###########################################################
#DesignerPaletteFactory properties

DesignerPaletteFactory.categoryName.reportItems=Eléments d'état
DesignerPaletteFactory.elementLabel.data=Données
DesignerPaletteFactory.elementLabel.grid=Grille
DesignerPaletteFactory.elementLabel.image=Image
DesignerPaletteFactory.elementLabel.label=Etiquette
DesignerPaletteFactory.elementLabel.list=Liste
DesignerPaletteFactory.elementLabel.tabel=Table
DesignerPaletteFactory.elementLabel.text=Texte
DesignerPaletteFactory.elementName.data=Données
DesignerPaletteFactory.elementName.grid=Grille
DesignerPaletteFactory.elementName.image=Image
DesignerPaletteFactory.elementName.label=Etiquette
DesignerPaletteFactory.elementName.list=Liste
DesignerPaletteFactory.elementName.table=Table
DesignerPaletteFactory.elementName.text=Texte
DesignerPaletteFactory.elementName.textdata=Texte dynamique
DesignerPaletteFactory.toolTip.dataReportItem=Insérez une colonne de jeu de données ou le résultat d'une expression.
DesignerPaletteFactory.toolTip.gridReportItem=Insérez une présentation de ligne/colonne pour organiser d'autres éléments.
DesignerPaletteFactory.toolTip.imageReportItem=Insérez une image à partir d'un fichier ou d'une URL.
DesignerPaletteFactory.toolTip.labelReportItem=Insérez un champ de texte statique. 
DesignerPaletteFactory.toolTip.listReportItem=Insérer une présentation de format flexible composée de lignes de jeu de données dans la partie en-tête/détail/pied de page
DesignerPaletteFactory.toolTip.multiLineDataReportItem=Insérer un bloc de texte (texte brut/HTML/RTF) à partir d'un fichier, d'une colonne de jeu de données ou du résultat d'une expression.
DesignerPaletteFactory.toolTip.tableReportItem=Insérer une présentation en colonne composée de lignes de jeu de données dans la partie en-tête/détail/pied de page
DesignerPaletteFactory.toolTip.textDataReportItem=Insérer un bloc de texte avec insertion optionnelle d'expression(s) de données CLOB
DesignerPaletteFactory.toolTip.textReportItem=Insérez un bloc de texte (texte brut/HTML) avec insertion optionnelle d'expression(s).

###########################################################
#DimensionBuilderDialog properties

DimensionBuilderDialog.LabelMeasure=Mesure :
DimensionBuilderDialog.LabelUnit=Unités :
DimensionBuilderDialog.Title=Générateur de dimension

###########################################################
#DNDUtil properties

DNDUtil.trans.copy=Copier les éléments
DNDUtil.trans.cut=Déplacer les éléments

###########################################################
#DuplicatesPage properties

DuplicatesPage.Check.HideDuplicates=Masquer les doublons
DuplicatesPage.Group.Repeat=Reproduction(Répéter)
DuplicatesPage.Group.RepeatonPage=Reproduction(Répéter sur la page)
DuplicatesPage.Label.RepeatInfo=Masquer les valeurs qui sont identiques à la ligne de données précédente.
DuplicatesPage.Label.RepeatOnPage.1=Masquer les valeurs qui sont identiques à la ligne précédente,
DuplicatesPage.Label.RepeatOnPage.2=\\ \\ mais toujours afficher la valeur en haut de chaque nouvelle page.
DuplicatesPage.Label.ResetonGroup=Réinitialiser au groupe suivant
DuplicatesPage.Radio.Repeat=Répéter
DuplicatesPage.Radio.RepeatonPage=Répéter sur la page

###########################################################
#EditAction properties

EditAction.text=Modifier

###########################################################
#EditGroupAction properties

EditGroupAction.stackMsg.editGroup=Modifier le groupe

###########################################################
#EditGroupAction properties
InsertGroupHeaderFooterAction.stackMsg.editGroup=Insérer l'en-tête/le pied de page du groupe
InsertGroupHeaderFooterAction.Text.Header=En-tête
InsertGroupHeaderFooterAction.Text.Footer=Pied de page

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.stackMsg.deleteGroup=Supprimer le groupe

###########################################################
#EditLabelAction properties

EditLabelAction.text=Modifier

###########################################################
#Element properties

Element.Cell.colSpan=Plage de colonne :
Element.Cell.column=Colonne :
Element.Cell.drop=&Ignorer :
Element.Cell.height=Hauteur :
Element.Cell.rowSpan=Plage de ligne :
Element.Cell.slot.content=Contenu :
Element.Cell.verticalAlign=Alignement vertical :
Element.Cell.width=Largeur :
Element.Column.alignment=Alignement :
Element.Column.repeat=Répéter :
Element.Column.width=&Largeur :
Element.Column.suppressDuplicates=Supprimer les doublons
Element.Container.slot.reportItems=Eléments d'état :
Element.Data.action=Action :
Element.Data.helpText=Texte d'aide :
Element.Data.helpTextID=Clé du texte d'aide
Element.TextData.valueExpr=Expression de &valeur :
Element.DataSet.afterClose.toolTip=Commande appelée juste après la fermeture du jeu de données.
Element.DataSet.afterClose=Après la fermeture :
Element.DataSet.afterOpen.toolTip=Commande appelée juste après l'ouverture du jeu de données.
Element.DataSet.afterOpen=Après l'ouverture :
Element.DataSet.beforeClose.toolTip=Commande appelée juste avant la fermeture du jeu de données.
Element.DataSet.beforeClose=Avant la fermeture :
Element.DataSet.beforeOpen.toolTip=Commande appelée juste avant l'ouverture du jeu de données.
Element.DataSet.beforeOpen=Avant l'ouverture :
Element.DataSet.cachedMetaData=Métadonnées en cache :
Element.DataSet.columnHints=Astuces de colonne :
Element.DataSet.computedColumns=Colonnes de calcul :
Element.DataSet.dataSource=Source de données :
Element.DataSet.filter=Filtre :
Element.DataSet.inputParameters=Paramètres d'entrée :
Element.DataSet.onFetch.toolTip=Commande appelée juste avant la récupération d'une ligne de données du jeu de données.
Element.DataSet.onFetch=A la récupération :
Element.DataSet.outputParameters=Paramètres de sortie :
Element.DataSet.paramBindings=Liaisons de paramètres :
Element.DataSet.resultSet=Jeu de résultats :
Element.DataSource.afterClose.toolTip=Commande appelée juste après la fermeture de la source de données.
Element.DataSource.afterClose=Après la fermeture :
Element.DataSource.afterOpen.toolTip=Commande appelée juste après l'ouverture de la source de données.
Element.DataSource.afterOpen=Après l'ouverture :
Element.DataSource.beforeClose.toolTip=Commande appelée juste avant la fermeture de la source de données.
Element.DataSource.beforeClose=Avant la fermeture :
Element.DataSource.beforeOpen.toolTip=Commande appelée juste avant l'ouverture de la source de données.
Element.DataSource.beforeOpen=Avant l'ouverture :
Element.ExtendedItem.extension=nom d'extension :
Element.ExtendedItem.extensionName=nom d'extension :
Element.FreeForm.slot.reportItems=Eléments d'état :
Element.GraphicMasterPage.columns=Colonnes :
Element.GraphicMasterPage.columnSpacing=Espacement des colonnes :
Element.GraphicMasterPage.slot.contents=Contenu :
Element.Grid.slot.columns=colonnes :
Element.Grid.slot.row=ligne :
Element.Image.action=Action :
Element.Image.altText=&Autre texte :
Element.Image.altTextID=Clé d'autre texte :
Element.Image.helpText=Texte d'aide :
Element.Image.helpTextID=Clé du texte d'aide
Element.Image.imageName=Nom de l'image :
Element.Image.scale=échelle :
Element.Image.size=taille :
Element.Image.source=Source :
Element.Image.typeExpr=Expression de type :
Element.Image.uri=uri :
Element.Image.valueExpr=Expression de valeur :
Element.JdbcDataSource.dataSource=Source de données :
Element.JdbcDataSource.driver=Pilote :
Element.JdbcDataSource.password=Mot de passe :
Element.JdbcDataSource.url=Url :
Element.JdbcDataSource.userName=Nom d'utilisateur :
Element.JdbcSelectDataSet.getStatement.toolTip=Renvoie une instruction SQL personnalisée pour la requête.
Element.JdbcSelectDataSet.getStatement=Obtenir l'instruction :
Element.JdbcSelectDataSet.statement=Instruction :
Element.Label.action=Action :
Element.Label.helpText=Texte d'aide :
Element.Label.helpTextID=Clé du texte d'aide
Element.Label.text=Texte :
Element.Label.textID=Clé de &texte :
Element.Line.orientation=orientation :
Element.List.slot.columnHeader=columnHeader :
Element.List.slot.detail=détails :
Element.List.slot.footer=pied de page :
Element.List.slot.group=groupe :
Element.List.slot.header=en-tête :
Element.ListGroup.slot.footer=pied de page :
Element.ListGroup.slot.header=en-tête :
Element.Listing.filter=Filtre :
Element.Listing.onFinish.toolTip=Commande appelée après la lecture de la dernière ligne du jeu de données pour cet élément, mais avant la création de la bande du pied de page.
Element.Listing.onFinish=A la fin :
Element.Listing.onRow.toolTip=Commande appelée pour chaque ligne extraite du jeu de données pour cet élément, mais avant la création de tout contenu pour cette ligne.
Element.Listing.onRow=A la ligne :
Element.Listing.onStart.toolTip=Commande appelée après l'ouverture du jeu de données, mais avant la création de la bande d'en-tête et avant l'extraction de la première ligne du jeu de données pour cet élément. 
Element.Listing.onStart=Au début :
Element.Listing.pageBreakInterval=Intervalle de saut de &page :
Element.Listing.sorting=Tri :
Element.ListingGroup.filter=Filtre :
Element.ListingGroup.groupName=Nom
Element.ListingGroup.interval=Intervalle :
Element.ListingGroup.intervalRange=Plage d'intervalles :
Element.ListingGroup.keyExpr=Expression clé :
Element.ListingGroup.onFinish.toolTip=Commande appelée après la lecture de la dernière ligne du jeu de données pour cet élément, mais avant la création de la bande du pied de page.
Element.ListingGroup.onFinish=A la fin :
Element.ListingGroup.onRow.toolTip=Commande appelée pour chaque ligne extraite du jeu de données pour cet élément, mais avant la création de tout contenu pour la ligne.
Element.ListingGroup.onRow=A la ligne :
Element.ListingGroup.onStart.toolTip=Commande appelée après l'ouverture du jeu de données, mais avant la création de la bande d'en-tête et avant l'extraction de la première ligne du jeu de données pour cet élément.
Element.ListingGroup.onStart=Au début :
Element.ListingGroup.pageBreakAfter=Saut de page après :
Element.ListingGroup.pageBreakBefore=Saut de page avant :
Element.ListingGroup.sort=Trier :
Element.ListingGroup.sortDirection=Direction du tri :
Element.ListingGroup.toc=Table des matières :
Element.MasterPage.bottomMargin=Marge inférieure :
Element.MasterPage.columns=Colonnes :
Element.MasterPage.columnSpacing=Espacement de colonne :
Element.MasterPage.height=Haut&eur :
Element.MasterPage.leftMargin=Marge de gauche :
Element.MasterPage.margin=Marge :
Element.MasterPage.orientation=&Orientation
Element.MasterPage.rightMargin=Marge de droite :
Element.MasterPage.slot.contents=Contenu :
Element.MasterPage.topMargin=Marge supérieure :
Element.MasterPage.type=&Type :
Element.MasterPage.width=&Largeur :
Element.Module.author=A&uteur :
Element.Module.base=Base :
Element.Module.colorPalette=Palette de couleurs :
Element.Module.comments=&Commentaires :
Element.Module.configVars=Configurer les variables :
Element.Module.createdBy=&Créé par :
Element.Module.description=&Description :
Element.Module.descriptionID=Clé de description :
Element.Module.helpGuide=Guide d'aide :
Element.Module.images=Images :
Element.Module.includeLibraries=Inclure les bibliothèques :
Element.Module.includeResource=Fichier de &ressources :
Element.Module.includeScripts=Inclure les scripts :
Element.Module.initialize.toolTip=Commande appelée au début de l'exécution de l'état.
Element.Module.initialize=Initialiser :
Element.Module.theme=Thè&mes
Element.Module.title=&Titre :
Element.Module.titleID=Clé de titre :
Element.Module.units=Unité&s :
Element.MultiLineData.contentTypeExpr=Expression de type de contenu :
Element.MultiLineData.valueExpr=Expression de valeur :
Element.OdaDataSet.privateDriverDesignState=Etat de conception de pilote privé :
Element.OdaDataSet.privateDriverProperties=Propriétés de pilote privé :
Element.OdaDataSet.publicDriverProperties=Propriétés de pilote public :
Element.OdaDataSet.queryScript.toolTip=TBD:
Element.OdaDataSet.queryScript=Script :
Element.OdaDataSet.queryText=Requête :
Element.OdaDataSet.resultSetName=Nom de jeu de résultats :
Element.OdaDataSet.type=Type :
Element.OdaDataSource.driverName=Nom du pilote :
Element.OdaDataSource.privateDriverProperties=Propriétés de pilote privé :
Element.OdaDataSource.publicDriverProperties=Propriétés de pilote public :
Element.Parameter.helpText=Texte d'aide :
Element.Parameter.helpTextID=Clé du texte d'aide
Element.Parameter.hidden=Masqué :
Element.ParameterGroup.helpText=Texte d'aide :
Element.ParameterGroup.helpTextID=Clé du texte d'aide
Element.ParameterGroup.slot.parameters=Paramètres :
Element.ParameterGroup.startExpanded=Lancement développé :
Element.ReportDesign.afterCloseDoc.toolTip=Commande appelée juste après la fermeture de l'état pendant le processus de génération.
Element.ReportDesign.afterCloseDoc=Après fermeture du document :
Element.ReportDesign.afterFactory.toolTip=Commande appelée à la fin du processus de génération, après fermeture de l'état (le cas échéant). Il s'agit de la dernière méthode appelée au cours du processus de génération.
Element.ReportDesign.afterFactory=Après génération :
Element.ReportDesign.afterOpenDoc.toolTip=Commande appelée juste après l'ouverture de l'état pendant le processus de génération.
Element.ReportDesign.afterOpenDoc=Après ouverture du document :
Element.ReportDesign.afterRender.toolTip=Commande appelée après le début d'une action chronologique de présentation.
Element.ReportDesign.afterRender=Après rendu :
Element.ReportDesign.beforeCloseDoc.toolTip=Commande appelée juste avant la fermeture de l'état pendant le processus de génération.
Element.ReportDesign.beforeCloseDoc=Avant fermeture du document :
Element.ReportDesign.beforeFactory.toolTip=Commande appelée au début du processus de génération après la méthode d'initialisation( ) mais avant l'ouverture de l'état (le cas échéant).
Element.ReportDesign.beforeFactory=Avant génération :
Element.ReportDesign.beforeOpenDoc.toolTip=Commande appelée juste avant l'ouverture de l'état pendant le processus de génération.
Element.ReportDesign.beforeOpenDoc=Avant ouverture du document :
Element.ReportDesign.beforeRender.toolTip=Commande appelée avant le début d'une action chronologique de présentation.
Element.ReportDesign.beforeRender=Avant rendu :
Element.ReportDesign.displayName=Nom d'afficha&ge : 
Element.ReportDesign.eventHandlerClass=Classe de gestionnaire d'é&vénements :
Element.ReportDesign.iconFile=&Prévisualiser l'image : 
Element.ReportDesign.refreshRate=Fréquence d'actualisation :
Element.ReportElement.comments=&Commentaires :
Element.ReportElement.customXml=XML personnalisé :
Element.ReportElement.displayName=Nom d'affichage :
Element.ReportElement.displayNameID=Clé de nom d'affichage :
Element.ReportElement.extends=Etend :
Element.ReportElement.javaClass=Classe Java :
Element.ReportElement.name=&Nom :
Element.ReportElement.propertyMask=Masque de propriété :
Element.ReportElement.style=S&tyle :
Element.ReportItem.bookmark=&Signet :
Element.ReportItem.dataSet=Jeu de données :
Element.ReportItem.height=&Hauteur :
Element.ReportItem.onCreate.toolTip=Action exécutée quand l'élément est créé pendant le processus de génération.
Element.ReportItem.onCreate=A la création :
Element.ReportItem.onRender.toolTip=Action exécutée quand l'élément est préparé pour le rendu pendant la phase de présentation.
Element.ReportItem.onRender=Au rendu :  
Element.ReportItem.paramBindings=Liaisons de paramètres :
Element.ReportItem.toc=&Table des matières :
Element.ReportItem.visibility=Visibilité :
Element.ReportItem.width=&Largeur :
Element.ReportItem.x=X :
Element.ReportItem.y=Y :
Element.Row.bookmark=Signet :
Element.Row.height=&Hauteur :
Element.Row.slot.cell=cellule :
Element.Row.visibility=Visibilité :
Element.ScalarParameter.alignment=Alignement :
Element.ScalarParameter.allowBlank=Autoriser une valeur vierge :
Element.ScalarParameter.allowNull=Autoriser une valeur nulle :
Element.ScalarParameter.concealValue=Masquer la valeur :
Element.ScalarParameter.controlType=Type de &contrôle :
Element.ScalarParameter.dataType=Type de &données :
Element.ScalarParameter.defaultValue=Valeur par défaut :
Element.ScalarParameter.dynamicList.dataSetName=Nom du jeu de données :
Element.ScalarParameter.dynamicList.labelExpr=Expression de l'étiquette :
Element.ScalarParameter.dynamicList.valueExpr=Expression de valeur :
Element.ScalarParameter.dynamicList=Liste dynamique :
Element.ScalarParameter.format=Format :
Element.ScalarParameter.selectionList.fixedOrder=Ordre fixe :
Element.ScalarParameter.selectionList.mustMatch=Doit correspondre :
Element.ScalarParameter.selectionList.selectionList=Liste de sélection :
Element.ScalarParameter.selectionList=Liste de sélection :
Element.ScalarParameter.promptTextID=&Clé de texte :
Element.ScriptDataSet.close.toolTip=Ferme le jeu de données.
Element.ScriptDataSet.close=Fermer :
Element.ScriptDataSet.describe.toolTip=Décrit le jeu de résultats.
Element.ScriptDataSet.describe=Décrire :
Element.ScriptDataSet.fetch.toolTip=Crée, définit et renvoie un objet de type DataRow. 
Element.ScriptDataSet.fetch=Récupérer :
Element.ScriptDataSet.open.toolTip=Ouvre le jeu de données.
Element.ScriptDataSet.open=Ouvrir :
Element.ScriptDataSource.close.toolTip=Supprime la connexion à la source de données. 
Element.ScriptDataSource.close=Fermer :
Element.ScriptDataSource.open.toolTip=Etablit une connexion à la source de données. 
Element.ScriptDataSource.open=Ouvrir :
Element.SimpleMasterPage.floatingFooter=&Pied de page flottant
Element.SimpleMasterPage.footerHeight=Hau&teur de pied de page :
Element.SimpleMasterPage.headerHeight=&Hauteur d'en-tête :
Element.SimpleMasterPage.showFooterOnLast=Affic&her l'en-tête sur la dernière page
Element.SimpleMasterPage.showHeaderOnFirst=&Afficher l'en-tête sur la première page
Element.SimpleMasterPage.slot.pageFooter=Pied de page :
Element.SimpleMasterPage.slot.pageHeader=En-tête de page :
Element.Style.background.attachment=&Pièce jointe :
Element.Style.background.color=&Couleur d'arrière-plan :
Element.Style.background.image=&Image d'arrière-plan :
Element.Style.background.positionX=Position &horizontale :
Element.Style.background.positionY=Position &verticale :
Element.Style.background.repeat=&Répéter :
Element.Style.background=Arrière-plan :
Element.Style.border.bottom.color=Ba&s :
Element.Style.border.bottom.style=&Bas :
Element.Style.border.bottom.width=Bas :
Element.Style.border.fillColor=Couleur de remplissage de bordure :
Element.Style.border.hmiddle.color=Couleur de milieu de bordure à l'horizontale :
Element.Style.border.hmiddle.style=Style de milieu de bordure à l'horizontale :
Element.Style.border.hmiddle.width=Largeur de milieu de bordure à l'horizontale :
Element.Style.border.left.color=Ga&uche :
Element.Style.border.left.style=&Gauche :
Element.Style.border.left.width=G&auche :
Element.Style.border.right.color=Dr&oite :
Element.Style.border.right.style=&Droite :
Element.Style.border.right.width=Dro&ite :
Element.Style.border.top.color=H&aut :
Element.Style.border.top.style=&Haut :
Element.Style.border.top.width=Ha&ut :
Element.Style.border.vmiddle.color=Couleur de milieu de bordure à la verticale :
Element.Style.border.vmiddle.style=Style de milieu de bordure à la verticale :
Element.Style.border.vmiddle.width=Largeur de milieu de bordure à la verticale :
Element.Style.border=Bordure :
Element.Style.box=Zone :
Element.Style.canShrink=Rétréci&ssement possible
Element.Style.color=&Couleur :
Element.Style.display=&Afficher :
Element.Style.font.family=&Police :
Element.Style.font.size=&Taille :
Element.Style.font.style=S&tyle :
Element.Style.font.textLineThrough=&Texte barré
Element.Style.font.textOverline=&Texte surligné
Element.Style.font.textUnderline=&Texte souligné
Element.Style.font.variant=Variante de police :
Element.Style.font.weight=&Epaisseur :
Element.Style.font=&Police :
Element.Style.format.dateTime=Date/heure :
Element.Style.format.number.align=Alignement des nombres formatés :
Element.Style.format.number=Numéro :
Element.Style.format.string=Chaîne :
Element.Style.format=Format :
Element.Style.highlight.rules=Mettre les règles en surbrillance :
Element.Style.highlight.testExpr=Mettre l'expression de test en surbrillance :
Element.Style.letterSpacing=Espacement des le&ttres :
Element.Style.lineHeight=Hauteur de lig&ne :
Element.Style.map.rules=Règles de mappage :
Element.Style.map.testExpr=Expression de test de mappage :
Element.Style.margin.bottom=Ba&s :
Element.Style.margin.left=Gauch&e :
Element.Style.margin.right=Dro&ite :
Element.Style.margin.top=Hau&t :
Element.Style.masterPage=Page &maître :
Element.Style.orphans=&Orphelins :
Element.Style.padding.bottom=&Bas :
Element.Style.padding.left=&Gauche :
Element.Style.padding.right=&Droite :
Element.Style.padding.top=&Haut :
Element.Style.padding=Remplissage :
Element.Style.pageBreakAfter=&Après :
Element.Style.pageBreakBefore=&Avant :
Element.Style.pageBreakInside=&A l'intérieur :
Element.Style.section=Section :
Element.Style.showIfBlank=&Afficher si vierge :
Element.Style.text.align=Alignement du te&xte :
Element.Style.text.indent=Retrait du te&xte :
Element.Style.text.transform=T&ransformation du texte :
Element.Style.text=Texte :
Element.Style.verticalAlign=Alignement &vertical :
Element.Style.whiteSpace=&Espace :
Element.Style.widows=&Veuves :
Element.Style.wordSpacing=&Espacement des mots :
Element.Table.caption=Légende :
Element.Table.captionID=Clé de légende :
Element.Table.repeatHeader=Répéter l'en-tête :
Element.Table.slot.columnHeader=columnHeader :
Element.Table.slot.columns=colonnes :
Element.Table.slot.detail=détails :
Element.Table.slot.footer=pied de page :
Element.Table.slot.group=groupe :
Element.Table.slot.header=en-tête :
Element.TableGroup.slot.footer=pied de page :
Element.TableGroup.slot.header=en-tête :
Element.Text.content=Contenu :
Element.Text.contentID=&Clé de contenu :
Element.Text.contentType=Ty&pe de contenu :
Element.TemplateElement.name=&Nom
Element.Toc.Sytle=&Style

###########################################################
#EmbeddedImageNodeProvider properties

EmbeddedImageNodeProvider.action.New=Nouvelle image incorporée

###########################################################
#EmbeddedImagesNodeProvider properties

EmbeddedImagesNodeProvider.action.New=Nouvelle image incorporée

###########################################################
#EmptyEditPart properties

EmptyEditPart.Msg.EmptyLib=La bibliothèque ne contient aucun élément visuel. Pour ajouter des éléments visuels, faites glisser l'élément de la palette vers la structure de la bibliothèque ou utilisez le menu d'insertion dans la vue de contour.
EmptyEditPart.Msg.NonVisual=Elément non visuel sélectionné.

###########################################################
#error properties

error.duplicateName=Le nouveau nom est le doublon d'un nom existant dans le même espace de noms.
error.emptyName=Le nom de la source de données doit être renseigné.
error.invalidName=Le nom "{0}" n'est pas valide car il contient le caractère ".".

###########################################################
#ExceptionHandler properties

ExceptionHandler.Label.ErrorCode=Code d'erreur
ExceptionHandler.Label.ErrorMessage=Message d'erreur
ExceptionHandler.Label.PluginId=Plug-in ID :
ExceptionHandler.Label.PluginName=Plug-in Name :
ExceptionHandler.Label.PluginProvider=Plug-in Provider :
ExceptionHandler.Label.PluginVersion=Version :
ExceptionHandler.Label.UnknownPlugin=Unknown plug-in
ExceptionHandler.Meesage.UnexceptedExceptionOccur=Une exception interne inattendue s'est produite. Pour plus de détails, consultez le fichier journal.
ExceptionHandler.Message.BirtExceptionOccur=Une exception BIRT s'est produite.
ExceptionHandler.Message.CausedBy=Caused by {0}.
ExceptionHandler.Message.FileNotFound=File not found :
ExceptionHandler.Message.OutOfMemory=Mémoire insuffisante.
ExceptionHandler.Message.PartInitError=Echec de l'initialisation.
ExceptionHandler.Message.SemanticFail=Echec de la vérification sémantique.
ExceptionHandler.Message.UnexceptedExceptionOccur=Une exception interne s'est produite. Pour plus de détails, consultez le fichier journal.
ExceptionHandler.Message.UnknownHost=Hôte inconnu :
ExceptionHandler.Title.Error=Erreur
ExceptionHandler.Title.FileNotFound=Fichier introuvable.
ExceptionHandler.Title.PartInitError=Erreur de l'initialisation.
ExceptionHandler.Title.UnknownHost=Hôte inconnu

###########################################################
#ExportAction properties

ExportAction.actionMsg.export=Exporter

###########################################################
#ExportToLibraryAction properties

ExportToLibraryAction.action.text=&Exporter vers la bibliothèque...
ExportToLibraryAction.Button.Cancel=Annuler
ExportToLibraryAction.Button.No=Non
ExportToLibraryAction.Button.Yes=Oui
ExportToLibraryAction.Dialog.Message=\nLa bibliothèque cible dispose peut-être du même élément de modèle, souhaitez-vous l'écraser ?
ExportToLibraryAction.Dialog.Title=Exporter l'élément
ExportToLibraryAction.Message.RememberDecision=Mémoriser ma décision.

###########################################################
#LibraryExplorerTreeViewPage tooltips
LibraryExplorerTreeViewPage.toolTips.DragAndDropOutline=Glisser-déplacer vers la vue de contour
LibraryExplorerTreeViewPage.toolTips.DragAndDropLayout=Glisser-déplacer vers l'éditeur de présentation
LibraryExplorerTreeViewPage.toolTips.DragAndDropToOutlineORLayout=Glisser-déplacer vers la vue de contour ou l'éditeur de présentation

###########################################################
#ExpressionBuidler properties

ExpressionBuidler.Dialog.Title=Générateur d'expression
ExpressionBuilder.toolTipText.Button=Ouvrir le Générateur d'expression

###########################################################
#ExpressionBuilder properties

ExpressionBuilder.Label.Category=Catégorie :
ExpressionBuilder.Label.Functions=Double clic pour insérer :
ExpressionBuilder.Label.Operators=Opérateurs :
ExpressionBuilder.Label.SubCategory=Sous-catégorie :
ExpressionBuilder.Message.Prompt=Entrez une expression dans le champ Expression. Parcourez la liste des objets disponibles et cliquez deux fois sur un objet pour le copier dans votre expression.

###########################################################
#ExpressionPropertyDescriptor properties

ExpressionPropertyDescriptor.text.Edit=Générateur d'e&xpression...

###########################################################
#ExpressionProvider properties

ExpressionProvider.Category.Context=Contexte
ExpressionProvider.Category.BirtObjects=Fonctions BIRT
ExpressionProvider.Category.DataSets=Jeux de données disponibles
ExpressionProvider.Category.NativeObjects=Fonctions JavaScript natives
ExpressionProvider.Category.ColumnBinding=Liaisons de colonnes disponibles
ExpressionProvider.Category.Operators=Opérateurs
ExpressionProvider.Category.Parameters=Paramètres de l'état
ExpressionProvider.Label.All=---Tout---
ExpressionProvider.Operator.Add=Ajoute deux valeurs ensemble.
ExpressionProvider.Operator.AddTo=Raccourci pour ajouter à la valeur actuelle.
ExpressionProvider.Operator.And=Compare deux expressions et renvoie une valeur true si les deux expressions sont vraies.
ExpressionProvider.Operator.Assign=Définit une valeur égale à l'autre.
ExpressionProvider.Operator.BitAnd=A & B : Renvoie la manipulation de bits ET le résultat de A et B.
ExpressionProvider.Operator.BitOr=A | B : Renvoie la manipulation de bits OU le résultat de A et B.
ExpressionProvider.Operator.Dec=Réduit la valeur et renvoie le résultat.
ExpressionProvider.Operator.DividingFrom=Raccourci pour diviser la valeur actuelle.
ExpressionProvider.Tooltip.ColumnBinding=Fait référence à 
ExpressionProvider.Operator.Divides=Divise la valeur de gauche par celle de droite et renvoie le résultat.
ExpressionProvider.Operator.Equals=Renvoie une valeur Vrai (True) si les éléments sont identiques.
ExpressionProvider.Operator.Greater=A > B : renvoie une valeur Vrai (True) si A est supérieur à B.
ExpressionProvider.Operator.GreaterEquals=A > B : renvoie une valeur Vrai (True) si A est supérieur ou égal à B.
ExpressionProvider.Operator.Inc=Augmente la valeur et renvoie le résultat.
ExpressionProvider.Operator.LeftBracket=Parenthèse de gauche
ExpressionProvider.Operator.RightBracket=Parenthèse de droite
ExpressionProvider.Operator.Less=A < B : renvoie une valeur Vrai (True) si A est inférieur à B.
ExpressionProvider.Operator.LessEqual=A > B : renvoie une valeur Vrai (True) si A est inférieur ou égal à B.
ExpressionProvider.Operator.Mult=Multiplie deux valeurs.
ExpressionProvider.Operator.MultTo=Raccourci pour multiplier la valeur actuelle.
ExpressionProvider.Operator.Not=!A : Renvoie une valeur vraie sur A est faux ou une valeur fausse si A est vrai.
ExpressionProvider.Operator.NotEqual=A <> B : renvoie une valeur Vrai (True) si A n'est pas égal à B.
ExpressionProvider.Operator.Or=Compare deux expressions et renvoie une valeur true si l'une des expressions est vraie, mais pas les deux.
ExpressionProvider.Operator.ReturnDec=Renvoie la valeur, puis réduit la valeur.
ExpressionProvider.Operator.ReturnInc=Renvoie la valeur, puis augmente la valeur.
ExpressionProvider.Operator.Sub=Soustrait une valeur d'une autre.
ExpressionProvider.Operator.SubFrom=Raccourci pour soustraire de la valeur actuelle.
ExpressionProvider.Operators.Assignment=Attribution
ExpressionProvider.Operators.Comparison=Comparaison
ExpressionProvider.Operators.Computational=Calcul
ExpressionProvider.Operators.Logical=Logique
ExpressionProvider.EditBindings=Modification des liaisons...
ExpressionProvider.Expression.RowNumName=RowNum
ExpressionProvider.Expression.RowNumTooltip=Expression qui renvoie le nombre de lignes actuel.

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Générer une expression...>
ExpressionValueCellEditor.selectValueAction=<Sélectionner une valeur...>
ExpressionValueCellEditor.title=Sélectionner une valeur

###########################################################
#ExtendedEditPart properties

ExtendedEditPart.edit=Modifier {0}

###########################################################
#ExtendedItemPageGenerator properties

ExtendedItemPageGenerator.List.Bookmark=Signet
ExtendedItemPageGenerator.List.TOC=Table des matières

###########################################################
#FilterHandleProvider properties

FilterHandleProvider.ColumnName.Value=Valeur
FilterHandleProvider.Label.Filterby=Filtrer par :
FilterHandleProvider.Modify.SaveValues=Enregistrer les valeurs

###########################################################
#filters properties

filters.empty.columnName=L'expression ne peut pas être vide.
filters.error.title=Entrée non valide.
filters.operators.any=est indifféremment
filters.operators.between=Est compris entre
filters.operators.bottomN=(n) éléments du bas
filters.operators.bottomPercent=(n) pourcentage du bas
filters.operators.equal=est égal à 
filters.operators.false=est faux
filters.operators.greaterThan=est supérieur à
filters.operators.greaterThanEqual=est supérieur ou égal à
filters.operators.lessThan=est inférieur à
filters.operators.lessThanEqual=est inférieur ou égal à
filters.operators.like=est identique à
filters.operators.notBetween=n'est pas compris entre
filters.operators.notEqual=n'est pas égal à
filters.operators.notNull=n'est pas nul
filters.operators.null=est nul
filters.operators.topN=fait partie des (n) premiers éléments
filters.operators.topPercent=fait partie des (n) premiers pourcentages
filters.operators.true=est vrai
filters.prompt.new=<Nouveau filtre ici...>

###########################################################
#FixTableLayoutCalculator properties

FixTableLayoutCalculator.Error.CannotParse=Impossible d'analyser la valeur d'entrée

###########################################################
#FlowMoveChildCommand properties

FlowMoveChildCommand.transLabel.moveElement=Déplacer l'élément

###########################################################
#FontPreferencePage properties

FontPreferencePage.displayname.Title=Police
FontPreferencePage.label.fontDecoration=Décoration :
FontPreferencePage.text.Preview=Aperçu de l'exemple
FontPreferencePage.text.PreviewContent=AaBbYyZz

###########################################################
#FontSizeBuilder properties

FontSizeBuilder.displayname.Auto=Auto

###########################################################
#FormatBuilder properties

FormatBuilder.Title=Générateur de format

###########################################################
#FormatDateTimeAttributePage properties

FormatDateTimeAttributePage.Trans.SetDateTimeFormat = Définissez le format Date/Heure.

###########################################################
#FormatDateTimePage properties

FormatDateTimePage.label.custom.settings.label=Exemples de formats (cliquez sur l'un d'entre eux pour le copier ci-dessous et le modifier) :
FormatDateTimePage.label.custom.settings=Paramètres personnalisés
FormatDateTimePage.label.format.code=Code de format :
FormatDateTimePage.label.format.page=&Format :
FormatDateTimePage.label.general.preview.group=Aperçu au format
FormatDateTimePage.label.guide.text=Saisissez les valeurs de date selon le modèle suivant : JJ/MM/AAAA hh:mm:ss
FormatDateTimePage.label.preview.dateTime=Aperçu de date/heure : 
FormatDateTimePage.label.preview.group=Aperçu
FormatDateTimePage.label.preview.label=Aperçu au format :
FormatDateTimePage.label.table.column.format.name=Format exemple
FormatDateTimePage.label.table.column.format.result=Exemple de résultat de format
FormatDateTimePage.label.table.column.format.code=Exemple de code
FormatDateTimePage.preview.invalid.dateTime=Format de date/heure incorrect pour l'aperçu
FormatDateTimePage.preview.invalid.formatCode=Code de format incorrect

###########################################################
#FormatDateTimePreferencePage properties

FormatDateTimePreferencePage.formatDateTime.title=Date/heure

###########################################################
#FormatNumberAttributePage properties

FormatNumberAttributePage.Trans.SetNumberFormat = Définissez le format des nombres.

###########################################################
#FormatNumberPage properties

FormatNumberPage.currency.symbol.none=Aucun symbole
FormatNumberPage.label.currency.settings=Paramètres d'unité monétaire
FormatNumberPage.label.custom.preview.group=Aperçu
FormatNumberPage.label.custom.preview.label=Aperçu au format :
FormatNumberPage.label.custom.settings.lable=Exemples de formats (cliquez sur l'un d'entre eux pour le copier ci-dessous et le modifier) :
FormatNumberPage.label.custom.settings=Paramètres personnalisés
FormatNumberPage.label.decimal.places=Emplacement des décimales : 
FormatNumberPage.label.fixed.settings=Paramètres fixés
FormatNumberPage.label.format.code=Code de format :
FormatNumberPage.label.format.number.page=&Format :
FormatNumberPage.label.general.preview.group=Aperçu au format
FormatNumberPage.label.negative.numbers=Chiffres négatifs : 
FormatNumberPage.label.percent.settings=Paramètres de pourcentage
FormatNumberPage.label.preview.number=Aperçu du nombre : 
FormatNumberPage.label.scientific.settings=Paramètres scientifiques
FormatNumberPage.label.symbol.position=Position du symbole : 
FormatNumberPage.label.symbol=Symbole : 
FormatNumberPage.label.table.column.format.code=Format exemple
FormatNumberPage.label.table.column.format.result=Exemple de résultat de format
FormatNumberPage.label.use1000sSeparator=Utiliser un séparateur de milliers
FormatNumberPage.label.useLeadingZero=Utiliser un zéro à gauche
FormatNumberPage.preview.invalidFormatCode=Code de format incorrect
FormatNumberPage.preview.invalidNumber=Format de nombre incorrect pour l'aperçu
FormatNumberPage.symblePos.after=Après
FormatNumberPage.symblePos.before=Avant

###########################################################
#FormatNumberPreferencePage properties

FormatNumberPreferencePage.formatNumber.title=Nombre

###########################################################
#FormatPreferencePage properties

FormatPreferencePage.displayname.Title=Format

###########################################################
#FormatStringAttributePage properties

FormatStringAttributePage.Trans.SetStringFormat = Définissez le format de chaîne.

###########################################################
#FormatStringPage properties

FormatStringPage.default.preview.text=ma chaîne
FormatStringPage.label.custom.preview.label=Aperçu au format :
FormatStringPage.label.custom.settings.label=Exemples de formats (cliquez sur l'un d'entre eux pour le copier ci-dessous et le modifier) :
FormatStringPage.label.customSettings=Paramètres personnalisés
FormatStringPage.label.format.code=Code de format :
FormatStringPage.label.formatStringAs=&Format :
FormatStringPage.label.preview.group=Aperçu
FormatStringPage.label.preview.string=Aperçu de la chaîne : 
FormatStringPage.label.previewWithFormat=Aperçu au format
FormatStringPage.label.table.collumn.exampleFormatCode=Format exemple
FormatStringPage.label.table.collumn.exampleFormatResult=Exemple de résultat de format
FormatStringPage.previewText.invalidFormatCode=Code de format incorrect

###########################################################
#FormatStringPreferencePage properties

FormatStringPreferencePage.formatString.title=Chaîne

###########################################################
#FormPage properties

FormPage.Button.Add=&Ajouter
FormPage.Button.AddWithDialog=&Ajouter...
FormPage.Button.Delete=&Supprimer
FormPage.Button.Down=&Bas
FormPage.Button.Edit=&Modifier
FormPage.Button.EditWithDialog=&Modifier...
FormPage.Button.Up=&Vers le haut
FormPage.Menu.ModifyProperty=modifier la propriété
FormPage.toolTipText.Up=Déplacer vers le haut
FormPage.toolTipText.Down=Déplacer vers le bas

###########################################################
#GeneralInsertMenuAction properties

GeneralInsertMenuAction.text.Data=&Données
GeneralInsertMenuAction.text.DynamicText=Texte d&ynamique
GeneralInsertMenuAction.text.Grid=&Grille
GeneralInsertMenuAction.text.Image=&Image
GeneralInsertMenuAction.text.Label=&Etiquette
GeneralInsertMenuAction.text.List=&Liste
GeneralInsertMenuAction.text.Table=Ta&ble
GeneralInsertMenuAction.text.Text=&Texte

###########################################################
#GeneralPreferencePage properties

GeneralPreferencePage.errorMsg.duplicate.styleName=Nom de style en double
GeneralPreferencePage.label.styleNameDuplicate=Le nom de style "{0}" existe déjà, choisissez un autre nom.
GeneralPreferencePage.label.customStyle=&Style personnalisé
GeneralPreferencePage.label.predefinedStyle=Style &prédéfini
GeneralPreferencePage.label.nameEmpty=Nom de style vide non autorisé. 

###########################################################
#GridEditPart properties

GridEditPart.GUIDEHANDLE_TEXT = Grille

###########################################################
#GridFigure properties

GridFigure.BORDER_TEXT=Grille

###########################################################
#GridPageGenerator properties

GridPageGenerator.List.Bookmark=Signet
GridPageGenerator.List.Borders=Bordure
GridPageGenerator.List.Font=Police
GridPageGenerator.List.General=Général
GridPageGenerator.List.Margin=Marge
GridPageGenerator.List.Section=Saut de page
GridPageGenerator.List.TOC=Table des matières
GridPageGenerator.List.Visibility=Visibilité
GridPageGenerator.TabItem.Highlights=Surbrillances
GridPageGenerator.TabItem.map=Mappage

###########################################################
#GridProvider properties

GridProvider.action.text=Insérer une ligne

###########################################################
#GroupDialog properties

GroupDialog.Dialog.GroupDetail=Détails du groupe
GroupDialog.Dialog.TOCGroup=Table des matières
GroupDialog.Dialog.TOC=Express&ion d'élément :
GroupDialog.Dialog.TOCStyle=St&yle :
GroupDialog.DialogTitle.NoData=Echec de l'initialisation
GroupDialog.DialogTitle.SemanticCheckFailed=Echec de la vérification sémantique
GroupDialog.ErrorMesaage.IllegalGroup=Ce groupe est incorrect.
GroupDialog.ErrorMessage.NoData=Aucune ligne de données disponible
GroupDialog.Label.FilterSorting=Filtres et tri
GroupDialog.Label.GroupOn=Re&grouper :
GroupDialog.Label.HeaderFooter=En-tête et pied de page
GroupDialog.Label.IncludeFooter=&Inclure un pied de page de groupe
GroupDialog.Label.IncludeHeader=&Inclure un en-tête de groupe
GroupDialog.Label.Interval=&Intervalle :
GroupDialog.PageBreakBefore=Avant :
GroupDialog.PageBreakAfter=Après :
GroupDialog.PageBreakInside=A l'intérieur :
GroupDialog.Label.IntervalBase=&Utiliser une valeur de base fixe pour l'intervalle :
GroupDialog.Label.Name=&Nom :
GroupDialog.Label.Range=&Plage :
GroupDialog.Tab.Binding=Liaisons de données
GroupDialog.Tab.Filter=Filtres
GroupDialog.Tab.Sorting=Tri en cours
GroupDialog.RepeatHeader=Répéter l'en-tête
GroupDialog.Title.Edit=Modifier le groupe
GroupDialog.Title.New=Nouveau groupe
GroupDialog.PageBreak=Saut de page
GroupDialog.buttion.HideDetail=Masquer des &détails
GroupDialog.toolTipText.openExprButton=Ouvrir le Générateur d'expression

###########################################################
#GroupHandleProvider properties

GroupHandleProvider.Label.Groups=Liste de groupe :

###########################################################
#GroupProvider properties

GroupProvider.action.text=Modifier le groupe

###########################################################
#GuiExtensionManager properties

GuiExtensionManager.label.name=Elément étendu
GuiExtensionManager.tooltip.insert=Insérer {0}

###########################################################
#HighlightHandleProvider properties

HighlightHandleProvider.text.Preview=AaBbCcYyZz (taille de police 

###########################################################
#HighlightRuleBuilderDialog properties

HighlightRuleBuilderDialog.choice.ValueOfThisDataItem=Valeur de l'élément de données
HighlightRuleBuilderDialog.text.AND=AND
HighlightRuleBuilderDialog.text.Any=est indifféremment
HighlightRuleBuilderDialog.text.BackgroundColor=Couleur d'arrière-plan :
HighlightRuleBuilderDialog.text.Between=Est compris entre
HighlightRuleBuilderDialog.text.Color=Couleur :
HighlightRuleBuilderDialog.text.Condition=Si la condition suivante est vraie : 
HighlightRuleBuilderDialog.text.Default=Auto
HighlightRuleBuilderDialog.text.ET=est égal à
HighlightRuleBuilderDialog.text.False=est faux
HighlightRuleBuilderDialog.text.Font=Police :
HighlightRuleBuilderDialog.text.Format=Alors appliquer le formatage suivant : 
HighlightRuleBuilderDialog.text.GE=est supérieur ou égal à
HighlightRuleBuilderDialog.text.GT=est supérieur à
HighlightRuleBuilderDialog.text.LE=est inférieur ou égal à
HighlightRuleBuilderDialog.text.Like=est identique à
HighlightRuleBuilderDialog.text.LT=est inférieur à
HighlightRuleBuilderDialog.text.NE=n'est pas égal à
HighlightRuleBuilderDialog.text.NotBetween=n'est pas compris entre
HighlightRuleBuilderDialog.text.NotNull=n'est pas nul
HighlightRuleBuilderDialog.text.Null=est nul
HighlightRuleBuilderDialog.text.Preview=Aperçu :
HighlightRuleBuilderDialog.text.PreviewContent=AaBbCcYyZz
HighlightRuleBuilderDialog.text.Size=Taille :
HighlightRuleBuilderDialog.text.Title=Ajouter/Modifier la règle de surbrillance
HighlightRuleBuilderDialog.text.True=est vrai
HighlightRuleBuilderDialog.tooltip.ExpBuilder=Cliquez ici pour appeler le Générateur d'expression.
HighlightRuleBuilderDialog.tooltip.Bold=Gras
HighlightRuleBuilderDialog.tooltip.Italic=Italique
HighlightRuleBuilderDialog.tooltip.Underline=Texte souligné
HighlightRuleBuilderDialog.tooltip.Text_Line_Through=Ligne de texte barré
HighlightRuleBuilderDialog.text.applyStyle=Utiliser le formatage à partir du style :
HighlightRuleBuilderDialog.displayText.None=Aucun

###########################################################
#HighlightsPage properties

HighlightsPage.Button.Add=&Ajouter...
HighlightsPage.Button.Delete=&Supprimer
HighlightsPage.Dialog.EditHighlight=Modifier la mise en surbrillance
HighlightsPage.Dialog.NewHighlight=Nouvelle mise en surbrillance
HighlightsPage.Label.Highlights=Liste de surbrillance :
HighlightsPage.TableColumn.Condition=Condition
HighlightsPage.TableColumn.Preview=Aperçu :
HighlightsPage.trans.Add=Ajouter la règle de surbrillance
HighlightsPage.trans.Delete=Supprimer la règle de surbrillance
HighlightsPage.trans.Edit=Modifier la règle de surbrillance
HighlightsPage.trans.MoveDown=Déplacer la règle de surbrillance vers le bas
HighlightsPage.trans.MoveUp=Déplacer la règle de surbrillance vers le haut
HighlightsPage.toolTipText.MoveDown=Déplacer la règle de surbrillance vers le bas
HighlightsPage.toolTipText.MoveUp=Déplacer la règle de surbrillance vers le haut

###########################################################
#HighlightsPreferencePage properties

HighlightsPreferencePage.displayname.Condition=Condition
HighlightsPreferencePage.displayname.Preview=Aperçu
HighlightsPreferencePage.displayname.Title=Surbrillances
HighlightsPreferencePage.text.Add=&Ajouter...
HighlightsPreferencePage.text.Delete=&Supprimer
HighlightsPreferencePage.text.Description=Liste de surbrillance :
HighlightsPreferencePage.text.Edit=&Modifier...
HighlightsPreferencePage.toolTipText.Up=Déplacer la mise en surbrillance vers le haut
HighlightsPreferencePage.toolTipText.Down=Déplacer la mise en surbrillance vers le bas

###########################################################
#HyperlinkBuilder properties

HyperlinkBuilder.Column.Parameters=Paramètres
HyperlinkBuilder.DrillThroughStep1=Etape 1 : sélection d'un état cible 
HyperlinkBuilder.DrillThroughStep2=Etape 2 : sélection d'une ancre cible 
HyperlinkBuilder.DrillThroughStep3=Etape 3 : création d'une expression de lien correspondant au signet cible
HyperlinkBuilder.DrillThroughStep4=Etape 4 : affichage de l'état cible dans 
HyperlinkBuilder.DrillThroughStep5=Etape 5 : choix du format de l'état cible
HyperlinkBuilder.ParameterRequired=requis
HyperlinkBuilder.Column.Values=Valeurs
HyperlinkBuilder.DialogTitle=Options de lien hypertexte
HyperlinkBuilder.ErrorMessage.InvalidReport=Modèle d'état non valide.
HyperlinkBuilder.ErrorMessage.ReportReqired=Le fichier d'état doit être spécifié.
HyperlinkBuilder.DrillThroughTargetBookmark=Signet cible
HyperlinkBuilder.DrillThroughLinkExpression=Expression de lien :
HyperlinkBuilder.Label.Bookmark=Signet :
HyperlinkBuilder.Label.Format=Format :
HyperlinkBuilder.Label.LinkedExpression=Expression liée :
HyperlinkBuilder.DrillThroughTargetToc=Entrée de la table des matières dans l'état cible
HyperlinkBuilder.DrillThroughSamewindow=Même fenêtre
HyperlinkBuilder.DrillThroughNewWindow=Nouvelle fenêtre
HyperlinkBuilder.Label.Location=Emplacement :
HyperlinkBuilder.Label.Parameters=Paramètres de l'état :
HyperlinkBuilder.Label.Report=Etat :
HyperlinkBuilder.Label.SelectType=Sélectionner un type de lien hypertexte :
HyperlinkBuilder.DrillThroughHtml=HTML
HyperlinkBuilder.Label.Target=Cible :
HyperlinkBuilder.Radio.Bookmark=Signet interne
HyperlinkBuilder.DrillThroughPdf=PDF
HyperlinkBuilder.Radio.DrillThrough=Extraire
HyperlinkBuilder.ReportDesignButton=Modèle d'état :
HyperlinkBuilder.ReportDocumentButton=Etat :
HyperlinkBuilder.Radio.None=Aucun lien
HyperlinkBuilder.Radio.Uri=URI
HyperlinkBuilder.BrowseForFile=Rechercher le fichier
HyperlinkBuilder.OpenExpression=Ouvrir le Générateur d'expression
HyperlinkBuilder.FileNameError.Title=Erreur
HyperlinkBuilder.FileNameError.Message=Le fichier sélectionné n'est pas valide.
HyperlinkBuilder.TargetReportFormat=Formatage de l'état cible dans :

###########################################################
#HyperLinkPage properties

HyperLinkPage.Label.LnikTo=&Lien vers :
HyperLinkPage.Label.None=Aucun
HyperLinkPage.Menu.Save=Modifier le lien hypertexte
HyperLinkPage.toolTipText.Button=Ouvrir les options de lien hypertexte

###########################################################
#I18nPage properties

I18nPage.text.Note=Remarque : pour définir la version localisée, sélectionnez l'état et définissez le nom du fichier de ressources dans l'onglet Ressources de l'Editeur de propriétés.

###########################################################
#ImageBuilder properties

ImageBuilder.Button.Dynamic=Image &dynamique
ImageBuilder.Button.Import=&Ajouter une image...
ImageBuilder.Button.Insert=&Insertion
ImageBuilder.Button.Preview=A&perçu
ImageBuilder.Button.Remove=Supprimer
ImageBuilder.ButtonBrowser=Parcourir...
ImageBuilder.Chooser.Title=Ouvrir le fichier image
ImageBuilder.DialogTitle.Edit=Modifier l'élément image
ImageBuilder.DialogTitle.ImportFailed=Echec de l'importation
ImageBuilder.DialogTitle.LoadingFailed=Echec de chargement de l'image
ImageBuilder.DialogTitle.New=Nouvel élément image
ImageBuilder.ErrorMessage.FileLoaded=Ce fichier a déjà été chargé.
ImageBuilder.ErrorMessage.LoadingFailed=L'image ne peut être chargée correctement.
ImageBuilder.BrowserResourceDialog.Title=Parcourir les fichiers image
ImageBuilder.BrowserResourceDialog.Message=Sélectionnez les fichiers image depuis le dossier de ressources
ImageBuilder.ErrorMessage.OutOfMemory=La mémoire est insuffisante pour contenir l'image.
ImageBuilder.FileDialog.FilterMessage=Fichier image pris en charge
ImageBuilder.Label.Binding=&Liaison
ImageBuilder.Label.EmbededImage=Imag&e incorporée
ImageBuilder.Label.EnterExpr=E&ntrer une expression d'image dynamique :
ImageBuilder.Label.EnterUri=E&ntrer l'URI :
ImageBuilder.Label.Open=Générateur d'e&xpression...
ImageBuilder.Label.SelectFrom=Sélectionner une image dans :
ImageBuilder.ResourceFileType=Fichier image dans le dossier de ressources
ImageBuilder.Label.URI=&URI
ImageBuilder.Label.EnterResourceFile=E&ntrer le fichier de ressources :

###########################################################
#ImageEditPart properties

ImageEditPart.trans.editImage=Modifier l'image

###########################################################
#ImagePageGenerator properties

ImagePageGenerator.List.AltText=Texte de légende
ImagePageGenerator.List.Bookmark=Signet
ImagePageGenerator.List.Borders=Bordure
ImagePageGenerator.List.General=Général
ImagePageGenerator.List.HyperLink=Lien hypertexte
ImagePageGenerator.List.Reference=Référence
ImagePageGenerator.List.Section=Saut de page
ImagePageGenerator.List.TOC=Table des matières
ImagePageGenerator.List.Visibility=Visibilité

###########################################################
#ImportCSSStyleAction properties

ImportCSSStyleAction.text=Importer un style CSS...

###########################################################
#ImportLibraryAction properties

ImportLibraryAction.Error.CannotBeEmpty=L'espace nom ne peut pas être vide.
ImportLibraryAction.Error.HasBeenUsed=Cet espace nom est en cours d'utilisation.
ImportLibraryAction.Error.HasDot=L'espace nom ne peut pas contenir de point (« . »).
ImportLibraryAction.Message.ImportSuccessfully=La bibliothèque {0} a été importée.
ImportLibraryAction.Message=Voulez-vous utiliser cette bibliothèque dans le modèle d'état ?
ImportLibraryAction.Namespace=Espace nom :
ImportLibraryAction.Prefix=Préfixe :
ImportLibraryAction.Title.ImportSuccessfully=Importation réussie
ImportLibraryAction.Dialog.Titile=Utiliser la bibliothèque
ImportLibraryAction.Dialog.Message=Sélectionnez une bibliothèque à inclure dans l'état. 

###########################################################
#ImportLibraryDialog properties

ImportLibraryDialog.Title=Utiliser la bibliothèque

###########################################################
#ImportValueDialog properties

ImportValueDialog.Label.SelectColumn=Sélectionner une &colonne :
ImportValueDialog.Label.SelectDataSet=Sélectionner un jeu de &données :
ImportValueDialog.Label.SelectValue=&Sélectionner ou entrer la valeur à ajouter
ImportValueDialog.Title=Importer valeurs

###########################################################
#IncludeDetailAction properties

IncludeDetailAction.actionMsg.includeDetail=&Détails

###########################################################
#IncludeFooterAction properties

IncludeFooterAction.actionMsg.includeFooter=&Pied de page

###########################################################
#IncludeHeaderAction properties

IncludeHeaderAction.actionMsg.includeHeader=&En-tête

###########################################################
#IncludeListDetailAction properties

IncludeListDetailAction.actionMsg.includeDetail=Inclure le détail

###########################################################
#IncludeListFooterAction properties

IncludeListFooterAction.actionMsg.includeFooter=Inclure le pied de page

###########################################################
#IncludeListHeaderAction properties

IncludeListHeaderAction.actionMsg.includeHeader=Inclure l'en-tête

###########################################################
#IncludeTableGroupFooterAction properties

IncludeTableGroupFooterAction.actionMsg.includeFooter=Pied de page de groupe

###########################################################
#IncludeTableGroupHeaderAction properties

IncludeTableGroupHeaderAction.actionMsg.includeHeader=En-tête de groupe

###########################################################
#InputParameterDailog properties

InputParameterDailog.dialog.title.required=Le paramètre requis doit contenir une valeur.
InputParameterDailog.dialog.title=Entrer les paramètres
InputParameterDailog.parameter.noparameter=Aucun paramètre associé à cet état.
InputParameterDialog.ErrorMessage.InvalidFile=Cet état contient une erreur.
InputParameterDailog.parameter.null=Valeur nulle
InputParameterDialog.ErrorTitle.Error=Erreur

###########################################################
#InsertAction properties

InsertAction.text=Insérer l'élément

###########################################################
#InsertColumnAction properties

InsertColumnAction.actionMsg.insert=Insérer

###########################################################
#InsertColumnLeftAction properties

InsertColumnLeftAction.actionMsg.columnToLeft=Colonne à &gauche

###########################################################
#InsertColumnRightAction properties

InsertColumnRightAction.actionMsg.columnToRight=Colonne à &droite

###########################################################
#InsertExpressionMenuAction properties

InsertExpressionMenuAction.text.Expression=Expression...

###########################################################
#InsertGroupAction properties

InsertGroupAction.actionMsg.group=I&nsérer le groupe
InsertGroupAction.stackMsg.addGroup=Ajouter un groupe

###########################################################
#InsertGroupActionFactory properties

InsertGroupActionFactory.label.insertGroup=I&nsérer le groupe

###########################################################
#InsertInLayoutAction properties

InsertInLayoutAction.action.text=Insérer dans la mise en page

###########################################################
#InsertListGroupAction properties

InsertListGroupAction.actionMsg.insertGroup=Insérer le groupe
InsertListGroupAction.stackMsg.insertListGroup=insérer le groupe de listes

###########################################################
#InsertPasteColumnAction properties

InsertPasteColumnAction.text=In&sérer la colonne copiée

###########################################################
#InsertPositionGroupAction properties

InsertPositionGroupAction.Label.Above=&Au-dessus
InsertPositionGroupAction.Label.Below=&En dessous
InsertPositionGroupAction.Label.Into=Vers

###########################################################
#InsertRowAboveAction properties

InsertRowAboveAction.actionMsg.rowAbove=&Au-dessus

###########################################################
#InsertRowAction properties

InsertRowAction.actionMsg.insert=&Insérer

###########################################################
#InsertRowBelowAction properties

InsertRowBelowAction.actionMsg.rowBelow=&En dessous

###########################################################
#IReportGraphicConstants properties

IReportGraphicConstants.ImageType.All=Tous les fichiers image (*.bmp,*.JPG,*.JPEG,*.GIF,*.TIF,*.PNG,*.ICO)
IReportGraphicConstants.ImageType.Bmp=Fichiers Bitmap (*.bmp)
IReportGraphicConstants.ImageType.Gif=Fichiers GIF (*.GIF)
IReportGraphicConstants.ImageType.Icon=Fichiers icône (*.ICO)
IReportGraphicConstants.ImageType.Jpg=Fichiers JPEG (*.JPG,*.JPEG)
IReportGraphicConstants.ImageType.Png=Fichiers PNG (*.PNG)
IReportGraphicConstants.ImageType.Tif=Fichiers TIF (*.TIF)

###########################################################
#JSDocumentProvider properties

JSDocumentProvider.Content.Default=Nouveau contenu
JSDocumentProvider.document.newName=Nouveau contenu

###########################################################
#JSEditor properties

JSEditor.Button.Reset=Réinitialiser la méthode
JSEditor.Display.DefaultText=//Editeur de scripts JS \n
JSEditor.Display.NoExpression=Cet élément ne contient pas de méthode.
JSEditor.Input.trial=évaluation
JSEditor.Text.NoText=Aucun texte

###########################################################
#label properties

label.defaultValue=(Valeur par défaut)
label.input=Entrée
label.inputOutput=Entrée/Sortie
label.no=Non
label.output=Sortie
label.redo=Rétablir
label.undo=Annuler
label.yes=Oui

###########################################################
#LabelEditPart properties

LabelEditPart.Figure.Default=Etiquette

###########################################################
#LabelPageGenerator properties

LabelPageGenerator.List.Bookmark=Signet
LabelPageGenerator.List.Borders=Bordure
LabelPageGenerator.List.General=Général
LabelPageGenerator.List.HyperLink=Lien hypertexte
LabelPageGenerator.List.I18n=Localisation
LabelPageGenerator.List.Margin=Marge
LabelPageGenerator.List.Padding=Remplissage
LabelPageGenerator.List.Section=Saut de page
LabelPageGenerator.List.TOC=Table des matières
LabelPageGenerator.List.Visibility=Visibilité

###########################################################
#LayoutEditor properties

LayoutEditor.ErrorMessage.OpenError=Une erreur s'est produite lors de l'ouverture de l'éditeur.
LayoutEditor.Page.Layout=Normal
LayoutEditor.Page.MasterPage=Page maître
LayoutEditor.Page.Source=Source XML

###########################################################
#LayoutPageAction properties

LayoutPageAction.actionText.layout=Mise en page

###########################################################
#LibrariesNodeProvider properties

LibrariesNodeProvider.DisplayLabel.Libraries=Bibliothèques

###########################################################
#LibraryExplorerView properties

LibraryExplorerView.defaultText.notAvailable=Les bibliothèques ne sont pas disponibles.

###########################################################
#LibraryExplorerProvider properties
LibraryExplorerProvider.FolderNotExist=Le dossier de ressources BIRT défini dans les préférences n'existe pas.

###########################################################
#LibraryPage properties

LibraryPage.Label.Namespace=Espace nom :
LibraryPage.Label.Path=Chemin :

###########################################################
#LibraryProvider properties

LibraryProvider.openDefinedLibrary.error.dialog.message=Erreur d'ouverture de bibliothèque définie
LibraryProvider.openDefinedLibrary.error.dialog.title=Erreur

###########################################################
#ListBandControlFigure properties

ListBandControlFigure.tooltip.GroupFooter=Groupe de listes - Pied de page
ListBandControlFigure.tooltip.GroupHeader=Groupe de listes - En-tête
ListBandControlFigure.tooltip.ListDetail=Liste - Détail
ListBandControlFigure.tooltip.ListFooter=Liste - Pied de page
ListBandControlFigure.tooltip.ListHeader=Liste - En-tête

###########################################################
#ListBandProvider properties

ListBandProvider.action.text=Insérer le groupe

###########################################################
#ListBandProxy properties

ListBandProxy.list.detail=Détails
ListBandProxy.list.footer=Pied de page
ListBandProxy.list.groupFooter=PPG
ListBandProxy.list.groupHeader=ETG
ListBandProxy.list.header=En-tête

###########################################################
#ListContainProcess properties

ListContainProcess.action.New=Nouveau...
ListContainProcess.action.NewRow=Nouvelle ligne
ListContainProcess.action.NewSubSection=Nouvelle sous-section

###########################################################
#ListEditPart properties

ListEditPart.GUIDEHANDLE_TEXT = Liste

###########################################################
#ListFigure properties

ListFigure.BORDER_TEXT=Liste

###########################################################
#ListHandleAdapt properties

ListHandleAdapt.transLabel.insertGroup=insérer le groupe

###########################################################
#ListPageGenerator properties

ListPageGenerator.List.Bookmark=Signet
ListPageGenerator.List.Borders=Bordure
ListPageGenerator.List.Font=Police
ListPageGenerator.List.General=Général
ListPageGenerator.List.Section=Saut de page
ListPageGenerator.List.TOC=Table des matières
ListPageGenerator.List.Visibility=Visibilité
ListPageGenerator.TabItem.Binding=Liaison
ListPageGenerator.TabItem.Filters=Filtres
ListPageGenerator.TabItem.Groups=Groupes
ListPageGenerator.TabItem.Highlights=Surbrillances
ListPageGenerator.TabItem.map=Mappage
ListPageGenerator.TabItem.Sorting=Tri

###########################################################
#MapPage properties

MapPage.label.add=&Ajouter...
MapPage.label.condition=Condition
MapPage.label.delete=&Supprimer
MapPage.label.displayValue=Valeur d'affichage :
MapPage.label.mapList=Liste de mappage :
MapPage.transName.addMapRule=Ajouter la règle de mappage
MapPage.transName.deleteMapRule=Supprimer la règle de mappage
MapPage.transName.editMapRule=Modifier la règle de mappage
MapPage.transName.moveDownRule=Déplacer la règle de mappage vers le bas
MapPage.transName.moveUpMapRule=Déplacer la règle de mappage vers le haut
MapPage.toolTipText.moveUp=Déplacer la règle de mappage vers le haut
MapPage.toolTipText.moveDown=Déplacer la règle de mappage vers le bas

###########################################################
#MapPreferencePage properties

MapPreferencePage.displayname.Condition=Condition
MapPreferencePage.displayname.DisplayValue=Valeur d'affichage
MapPreferencePage.displayname.Title=Mappage
MapPreferencePage.text.Add=&Ajouter...
MapPreferencePage.text.Delete=&Supprimer
MapPreferencePage.text.Description=Règles de mappage :
MapPreferencePage.text.Edit=&Modifier...
MapPreferencePage.toolTipText.Up=Déplacer la règle de mappage vers le haut
MapPreferencePage.toolTipText.Down=Déplacer la règle de mappage vers le bas

###########################################################
#MapRuleBuilderDialog properties

MapRuleBuilder.DialogTitle.New=Nouvelle règle de mappage
MapRuleBuilder.DialogTitle.Edit=Modifier la règle de mappage


MapRuleBuilderDialog.text.Between=est compris entre
MapRuleBuilderDialog.text.Condition=S&i la condition suivante est vraie : 
MapRuleBuilderDialog.text.Display=Alors afficher la valeur suivan&te : 
MapRuleBuilderDialog.text.ET=est égal à
MapRuleBuilderDialog.text.GE=est supérieur ou égal à
MapRuleBuilderDialog.text.GT=est supérieur à
MapRuleBuilderDialog.text.LE=est inférieur ou égal à
MapRuleBuilderDialog.text.Like=est identique à
MapRuleBuilderDialog.text.LT=est inférieur à
MapRuleBuilderDialog.text.NE=n'est pas égal à
MapRuleBuilderDialog.text.NotBetween=n'est pas compris entre
MapRuleBuilderDialog.text.NotNull=n'est pas nul
MapRuleBuilderDialog.text.Null=est nul
MapRuleBuilderDialog.text.Title=Ajouter/Modifier la règle de mappage

###########################################################
#SortkeyBuilder dialog properties
SortkeyBuilder.DialogTitle.New=Nouvelle clé de tri
SortkeyBuilder.DialogTitle.Edit=Modifier clé de tri
SortkeyBuilder.DialogTitle.Label.Prompt=Entrez une clé pour le tri :
SortkeyBuilder.DialogTitle.Label.Key=Clé :
SortkeyBuilder.DialogTitle.Label.Direction=Direction :
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Cliquez ici pour appeler le Générateur d'expression
SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Erreur

###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=Nouvelle condition de filtre
FilterConditionBuilder.DialogTitle.Edit=Modifier la condition de filtre
FilterConditionBuilder.choice.ValueOfThisDataItem=Valeur de l'élément de données
FilterConditionBuilder.tooltip.ExpBuilder=Cliquez ici pour appeler le Générateur d'expression.
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=Entrez une condition de filtre :

###########################################################
#MarignPropertyDescriptor properties

MarignPropertyDescriptor.error.message=La valeur entrée est trop grande.
MarignPropertyDescriptor.error.title=Valeur trop grande

###########################################################
#MasterPageAction properties

MasterPageAction.actionText.masterPage=Page maître

###########################################################
#MasterPageGenerator properties

MasterPageGenerator.List.General=Général
MasterPageGenerator.List.Header&Footer=En-tête/Pied de page
MasterPageGenerator.List.Margins=Marge

###########################################################
#MasterPagePaletteFactory properties

MasterPagePaletteFactory.Autotext.TotalPageCount=Nombre total de pages
MasterPagePaletteFactory.Autotext.Author_Page_Date=Auteur\#, Page\#, Date\#
MasterPagePaletteFactory.Autotext.Confidential_Page=Confidentiel, Page\#
MasterPagePaletteFactory.Autotext.CreatedBy=Création par
MasterPagePaletteFactory.Autotext.CreatedOn=Création le
MasterPagePaletteFactory.Autotext.Date=Date
MasterPagePaletteFactory.Autotext.Filename=Nom de fichier
MasterPagePaletteFactory.Autotext.Label=AutoText
MasterPagePaletteFactory.Autotext.LastPrinted=Dernière impression
MasterPagePaletteFactory.Autotext.Page=Page
MasterPagePaletteFactory.Autotext.PageXofY=Page n sur m
MasterPagePaletteFactory.AutotextTooltip.TotalPageCount=Elément d'état - Nombre total de pages
MasterPagePaletteFactory.AutotextTooltip.AuthorPageDate=Elément d'état N° auteur, N° date
MasterPagePaletteFactory.AutotextTooltip.ConfidentialPage=Elément d'état Confidentiel
MasterPagePaletteFactory.AutotextTooltip.CreatedBy=Elément d'état Création par 
MasterPagePaletteFactory.AutotextTooltip.CreatedOn=Elément d'état Création le
MasterPagePaletteFactory.AutotextTooltip.Date=Elément d'état Date
MasterPagePaletteFactory.AutoTextTooltip.Filename=Elément d'état Nom de fichier
MasterPagePaletteFactory.AutotextTooltip.LastPrinted=Dernier élément d'état imprimé
MasterPagePaletteFactory.AutotextTooltip.Page=Elément d'état Page
MasterPagePaletteFactory.AutotextTooltip.PageXofY=Elément d'état Page n sur m
MasterPagePaletteFactory.elementLabel.authorPageDate=N° auteur, N° page, N° date
MasterPagePaletteFactory.elementLabel.confidentialPage=Confidentiel, Page
MasterPagePaletteFactory.elementLabel.createdBy=Création par
MasterPagePaletteFactory.elementLabel.createdOn=Création le
MasterPagePaletteFactory.elementLabel.date=Date
MasterPagePaletteFactory.elementLabel.fileName=Nom de fichier
MasterPagePaletteFactory.elementLabel.lastPrinted=Dernière impression
MasterPagePaletteFactory.elementLabel.page=Page
MasterPagePaletteFactory.elementLabel.pageOf=Page n sur m
MasterPagePaletteFactory.paletteDrawerName.autoText=AutoText
MasterPagePaletteFactory.ToolTip.Grid=Elément d'état Grille
MasterPagePaletteFactory.ToolTip.Text=Elément d'état Texte

###########################################################
#MasterPageProcess properties

MasterPageProcess.action.Edit=Modifier
MasterPageProcess.action.New=Nouveau
MasterPageProcess.text.CannotDelete=Le modèle ne contient qu'une page maître, que vous ne pouvez pas supprimer
MasterPageProcess.text.Display=Affiche la boîte de dialogue Mise en page
MasterPageProcess.text.DisplayName=MasterPage

###########################################################
#MergeAction properties

MergeAction.actionMsg.merge=&Fusionner les cellules

###########################################################
#ModulePage properties

ModulePage.ErrorMessage.Duplicate=Le nom est le doublon d'un nom existant.
ModulePage.ErrorMessage.WrongExtensionName=Le nom doit se terminer par « .properties ».
ModulePage.ErrorMessage.InfoExtensionName=Veuillez entrer un nom se terminant par .properties.
ModulePage.text.Add=&Ajouter...
ModulePage.text.ExistingFile=Fichiers de ressources existants :
ModulePage.title.AddNewFile=Ajouter un nouveau fichier de ressource
ModulePage.Resourcefile.Dialog.Title=Parcourir les fichiers de ressources
ModulePage.Resourcefile.Dialog.Message=Sélectionnez un fichier de ressources ou sélectionnez un dossier et créez un nouveau fichier.
ModulePage.text.Path=Chemin :

###########################################################
#MultiPageEditorContributor properties

MultiPageEditorContributor.actionText.sampleAction=Exemple d'action
MultiPageEditorContributor.actionToolTip.sampleActionToolTip=Info-bulle d'exemple d'action
MultiPageEditorContributor.actionToolTipText.sampleActionToolTip=Info-bulle d'exemple d'action
MultiPageEditorContributor.dialogMsg.sampleActionExecuted=Exemple d'action exécutée
MultiPageEditorContributor.dialogTitle.infoObjectDesignerPlugIn=Plug-in Information Object Designer
MultiPageEditorContributor.menuText.editorMenu=&Menu Editeur

###########################################################
#NewLibraryWizard properties

NewLibraryWizard.choicePageTitle.report=Bibliothèque
NewLibraryWizard.displayName.NewReportFileExtension=.rptlibrary
NewLibraryWizard.displayName.NewReportFileNamePrefix=new_library
NewLibraryWizard.error.NoProject=Aucun projet n'est ouvert dans l'espace de travail. Choisissez Fichier->Nouveau->Projet pour créer un projet ou ouvrir un projet existant.
NewLibraryWizard.pageDescription.createNewReport=Créer une nouvelle bibliothèque
NewLibraryWizard.taskName.openFileForEdit=Ouverture du fichier à modifier...
NewLibraryWizard.text.ConfirmSwitchPerspective=Confirmer le changement de perspective
NewLibraryWizard.text.Container=Conteneur "
NewLibraryWizard.text.CreateReport=Créer une nouvelle bibliothèque
NewLibraryWizard.text.Creating=Création en cours 
NewLibraryWizard.text.DoesNotExist=" n'existe pas.
NewLibraryWizard.text.OpenFileForEditing=Ouverture du fichier à modifier...
NewLibraryWizard.text.SwitchPerspective=Ce type de fichier est associé à la perspective {0}. Souhaitez-vous basculer maintenant vers cette perspective ?
NewLibraryWizard.title.Choose=Choisir le mode de création de la bibliothèque
NewLibraryWizard.title.Error=Erreur
NewLibraryWizard.title.New=Nouvelle bibliothèque
NewLibraryWizard.title.Report=Nouvelle bibliothèque
NewLibraryWizard.title.ReportWizard=Assistant de bibliothèque
NewLibraryWizard.title.Template=TemplateChoicePage
NewLibraryWizard.title.WizardPage=WizardPage
NewLibraryWizard.widowTitle.new=Nouvelle
NewLibraryWizard.wizardPageTitle.report=Bibliothèque

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=La casse n''est pas prise en compte par le système de fichiers. Un projet existant est en conflit avec ''{0}''.
NewReportProjectWizard.description=Crée un projet d'état.
NewReportProjectWizard.errorMessage=Problème lors de la création du projet d'état
NewReportProjectWizard.errorOpeningWindow=Problème d'ouverture d'une fenêtre.
NewReportProjectWizard.internalError=Erreur interne : {0}
NewReportProjectWizard.javaProject=Créer un projet Java
NewReportProjectWizard.perspSwitchMessage=Ce type de projet est associé à la perspective {0}. Souhaitez-vous basculer vers cette perspective maintenant ?
NewReportProjectWizard.perspSwitchTitle=Confirmer le changement de perspective
NewReportProjectWizard.projectSetting=Paramètre du projet
NewReportProjectWizard.src=src
NewReportProjectWizard.title=Projet d'état
NewReportProjectWizard.windowTitle=Nouveau projet d'état

###########################################################
#NewReportWizard properties

NewReportWizard.choicePageTitle.report=Etat
NewReportWizard.displayName.NewReportFileExtension=.rptdesign
NewReportWizard.displayName.NewReportFileNamePrefix=new_report
NewReportWizard.error.NoProject=Aucun projet n'est ouvert dans l'espace de travail. Choisissez Fichier->Nouveau->Projet pour créer un nouveau projet ou ouvrir un projet existant.
NewReportWizard.pageDescription.createNewReport=Créer un nouvel état
NewReportWizard.pageDescription.selectReportTemplate=Sélectionner un état à copier
NewReportWizard.taskName.openFileForEdit=Ouverture du fichier à modifier...
NewReportWizard.text.ConfirmSwitchPerspective=Confirmer le changement de perspective
NewReportWizard.text.Container=Conteneur "
NewReportWizard.text.CreateReport=Créer un état
NewReportWizard.text.Creating=Création en cours 
NewReportWizard.text.DoesNotExist=" n'existe pas.
NewReportWizard.text.OpenFileForEditing=Ouverture du fichier à modifier...
NewReportWizard.text.SelectTemplate=Sélectionner un état à copier
NewReportWizard.text.SwitchPerspective=Ce type de fichier est associé à la perspective {0}. Souhaitez-vous basculer maintenant vers cette perspective ?
NewReportWizard.title.Choose=Choisir le mode de création de l'état
NewReportWizard.title.Error=Erreur
NewReportWizard.title.New=Nouvel état
NewReportWizard.title.Report=Nouvel état
NewReportWizard.title.ReportWizard=Assistant d'état
NewReportWizard.title.Template=TemplateChoicePage
NewReportWizard.title.WizardPage=WizardPage
NewReportWizard.widowTitle.new=Nouveau


###########################################################
#NewResourceFileDialog properties

NewResourceFileDialog.label.NewFile=Nom du nouveau fichier :
NewResourceFileDialog.ErrorMessage=Le nom de fichier doit se terminer par .properties
NewResourceFileDialog.ErrorMessageInvalid=Le nom de fichier est incorrect

###########################################################
#ProjectFileDialog properties

ProjectFileDialog.ErrorMessage=La sélection doit correspondre à un fichier et non à un répertoire.
ProjectFileDialog.Title=Sélectionner un fichier projet
ProjectFileDialog.Message=Sélectionner un fichier dans le projet en cours.

###########################################################
#NewSectionDialog properties

NewSectionDialog.displayname.Container=Conteneur
NewSectionDialog.displayname.Data=Données
NewSectionDialog.displayname.Grid=Grille
NewSectionDialog.displayname.Image=Image
NewSectionDialog.displayname.Label=Etiquette
NewSectionDialog.displayname.Line=Ligne
NewSectionDialog.displayname.List=Liste
NewSectionDialog.displayname.Rectangle=Rectangle
NewSectionDialog.displayname.Table=Table
NewSectionDialog.displayname.Text=Texte
NewSectionDialog.text.Prefix=Sections disponibles :
NewSectionDialog.title.insertElement=Insérer un élément
NewSectionDialog.Title=Insérer un élément

###########################################################
#NewTemplateWizard properties

NewTemplateWizard.displayName.NewReportFileNamePrefix=new_template
NewTemplateWizard.pageDescription.createNewTemplate=Créer un nouveau modèle d'état
NewTemplateWizard.text.CreateReport=Créer un nouveau modèle
NewTemplateWizard.text.Creating=Création en cours
NewTemplateWizard.text.OpenFileForEditing=Ouverture du fichier modèle à modifier...
NewTemplateWizard.title.New=Nouveau modèle
NewTemplateWizard.title.Report=Nouvel état
NewTemplateWizard.title.Template=Nouveau modèle
NewTemplateWizard.title.WizardPage=WizardPage

###########################################################
#NoneAction properties

NoneAction.text=Aucun

###########################################################
#OutputColumnDefnPage properties

OutputColumnDefnPage.description=Entrer la définition des colonnes de sortie produites par le script de récupération : 
OutputColumnDefnPage.OutputColumns.Tooltip=Afficher et définir les colonnes au sein d'une ligne de données 

###########################################################
#OutputColumnPage properties

OutputColumnPage.OutputColumns.Tooltip=Afficher et définir les colonnes au sein d'une ligne de données 
OutputColumnPage.toolTipText.Edit=Modifier la colonne de sortie
OutputColumnPage.title.OutputColumnInputDialog=Colonne de sortie

###########################################################
#OutputColumnsPage properties

OutputColumnsPage.description=Définir les colonnes de sortie :

###########################################################
#PageBreakPreferencePage properties

PageBreakPreferencePage.displayname.Title=Saut de page

###########################################################
#PageSetAction properties

PageSetAction.text.code=&Script
PageSetAction.Text.EditCode=Modifier le &script...
PageSetAction.text.layout=&Mise en page
PageSetAction.text.master=&Principal
PageSetAction.text.normal=&Normal
PageSetAction.text.preview=&Aperçu

###########################################################
#PageSetupOutlineProcess properties

PageSetupOutlineProcess.action.Edit=Modifier la mise en page
PageSetupOutlineProcess.action.New=Nouvelle page maître
PageSetupOutlineProcess.text.Display=Affiche la boîte de dialogue Mise en page
PageSetupOutlineProcess.text.Switch=Bascule vers l'éditeur maître de page

###########################################################
#ParameterDialog properties

ParameterDialog.Boolean.False=False
ParameterDialog.Boolean.True=True
ParameterDialog.Button.ChangeFormat=&Modifier...
ParameterDialog.Button.CreateDataSet=&Créer...
ParameterDialog.Button.ImportValue=Importer des vale&urs...
ParameterDialog.Button.RemoveDefault=Supprimer la valeur par défaut
ParameterDialog.Button.SetDefault=Définir p&ar défaut
ParameterDialog.CheckBox.AllowBlank=&Autoriser les valeurs vierges
ParameterDialog.CheckBox.AllowNull=Autoriser une &valeur nulle
ParameterDialog.CheckBox.DoNotEchoInput=Ne pas repr&oduire l'entrée
ParameterDialog.CheckBox.Hidden=&Masqué
ParameterDialog.CheckBox.Sort=T&rier par ordre alphabétique à l'invite
ParameterDialog.Choice.NoDefault=Aucune valeur par défaut
ParameterDialog.Column.Default=Par défaut
ParameterDialog.Column.DisplayText=Texte d'affichage
ParameterDialog.Column.Value=Valeur
ParameterDialog.DisplayLabel.Combo=Zone déroulante
ParameterDialog.DisplayLabel.List=Liste déroulante
ParameterDialog.ErrorMessage.CanootBeBlank=La valeur ne peut pas être vide.
ParameterDialog.ErrorMessage.CanootBeNull=La valeur ne peut pas être nulle.
ParameterDialog.ErrorMessage.DuplicatedLabel=Le texte d'affichage existe déjà.
ParameterDialog.ErrorMessage.DuplicatedName=Ce nom est en cours d'utilisation.
ParameterDialog.ErrorMessage.DuplicatedValue=Cette valeur existe déjà.
ParameterDialog.ErrorMessage.EmptyName=Le nom n'est pas renseigné.
ParameterDialog.ErrorMessage.InvalidListLimit=La valeur de limitation doit être comprise entre 0 et {0}
ParameterDialog.ErrorMessage.MismatchDataType=La valeur ne correspond pas au type de données.
ParameterDialog.ErrorMessage.NoAvailableColumn=Aucune colonne n'est disponible.
ParameterDialog.ErrorMessage.NoDefaultValue=Vous devez définir une valeur par défaut.
ParameterDialog.ErrorTitle.InvalidListLimit=Limite de liste incorrecte
ParameterDialog.Flag.Default=Par défaut
ParameterDialog.Group.MoreOption=Afficher sous
ParameterDialog.Group.Properties=Propriétés
ParameterDialog.Label.DataType=Type de &données :
ParameterDialog.SelectionDialog.Edit=Modifier le choix de sélection
ParameterDialog.Label.DefaultValue=Valeur par dé&faut :
ParameterDialog.Label.DisplayPrompt=Afficher une invite :
ParameterDialog.Label.DisplayType=&Type d'affichage :
ParameterDialog.Label.Format=For&mat :
ParameterDialog.Label.HelpText=&Texte d'aide :
ParameterDialog.Label.ListOfValue=Liste de valeurs :
ParameterDialog.Label.Name=&Nom :
ParameterDialog.Label.None=<Aucun>
ParameterDialog.Label.Null=Nul
ParameterDialog.Label.Preview=Aperçu au format
ParameterDialog.Label.PromptText=&Texte de l'invite :
ParameterDialog.Label.SelectDataSet=&Jeu de données :
ParameterDialog.SelectionDialog.New=Nouveau choix de sélection
ParameterDialog.Label.SelectDisplayText=Sélectionner le te&xte à afficher :
ParameterDialog.Label.SelectValueColumn=Sélectionner une colonne de vale&ur :
ParameterDialog.Label.Value=Valeurs de sélection :
ParameterDialog.Label.values=valeurs
ParameterDialog.Label.Sample=Echantillon
ParameterDialog.Label.Listlimit=L&imite de liste :
ParameterDialog.Radio.Dynamic=D&ynamique
ParameterDialog.Radio.Static=&Statique
ParameterDialog.toolTipText.OpenExprButton=Ouvrir le Générateur d'expression

###########################################################
#ParameterDropListener properties

ParameterDropListener.Command.Copy=Copier l'élément
ParameterDropListener.Command.Move=Déplacer l'élément

###########################################################
#ParameterGroupDialog properties

ParameterGroupDialog.Page.Title=Général
ParameterGroupDialog.pageTitle.general=Général

###########################################################
#ParameterGroupGeneralPage properties

ParameterGroupGeneralPage.Label.DisplayName=Nom &d'affichage :
ParameterGroupGeneralPage.Label.Name=&Nom :

###########################################################
#ParameterGroupNodeProvider properties

ParameterGroupNodeProvider.Action.GroupNew=Nouveau groupe de paramètres
ParameterGroupNodeProvider.Action.ParameterEdit=Modifier
ParameterGroupNodeProvider.Action.ParameterNew=Nouveau paramètre
ParameterGroupNodeProvider.Dialogue.ParameterEdit=Modifier le groupe de paramètres
ParameterGroupNodeProvider.Dialogue.ParameterNew=Nouveau paramètre
ParameterGroupNodeProvider.Node.Group=Groupe de paramètres

###########################################################
#ParameterGroupProcess properties

ParameterGroupProcess.action.Delete=Supprimer Parametergroup
ParameterGroupProcess.action.Edit=Modifier Parametergroup
ParameterGroupProcess.action.New=Nouveau paramètre
ParameterGroupProcess.text.DisplayName=ParameterGroup
ParameterGroupProcess.text.Show=affiche la page de l'éditeur de source de données  

###########################################################
#ParameterNodeProvider properties

ParameterNodeProvider.dial.title.editCascading=Modifier le paramètre en cascade
ParameterNodeProvider.dial.title.editScalar=Modifier le paramètre
ParameterNodeProvider.dial.title.newCascading=Nouveau paramètre en cascade
ParameterNodeProvider.menu.text.edit=Modifier
ParameterNodeProvider.menu.text.new=Nouveau paramètre

###########################################################
#ParameterProcess properties

ParameterProcess.action.Delete=Supprimer le paramètre
ParameterProcess.action.Edit=Modifier le paramètre
ParameterProcess.text.DisplayName=Paramètre
ParameterProcess.text.Show=affiche la page de l'éditeur de source de données  

###########################################################
#parameters properties

parameters.datatypes.boolean=Booléen
parameters.datatypes.dateTime=Date/heure
parameters.datatypes.decimal=Décimale
parameters.datatypes.float=Flottante
parameters.datatypes.string=Chaîne
parameters.menuItem.refresh=Actualiser

###########################################################
#ParametersNodeProvider properties

ParametersNodeProvider.dialogue.title.group=Nouveau groupe de paramètres
ParametersNodeProvider.dialogue.title.parameter=Nouveau paramètre
ParametersNodeProvider.menu.text.cascadingParameter=Nouveau paramètre en cascade
ParametersNodeProvider.menu.text.group=Nouveau groupe de paramètres
ParametersNodeProvider.menu.text.parameter=Nouveau paramètre

###########################################################
#ParametersOutlineProcess properties

ParametersOutlineProcess.action.Edit=Modifier
ParametersOutlineProcess.action.New=Nouveau paramètre
ParametersOutlineProcess.action.NewGroup=Nouveau groupe
ParametersOutlineProcess.text.Open=ouvrir l'éditeur de paramètre
ParametersOutlineProcess.text.Show=affiche la page de l'éditeur de jeu de données pour ce jeu de données

###########################################################
#PasteAction properties

PasteAction.text=&Coller

###########################################################
#PlaceHolderEditPart properties

PlaceHolderEditPart.Trans.TransferToElement=Transférer vers l'élément d'état

###########################################################
#PreviewAction properties

PreviewAction.Text=Aperçu

###########################################################
#PreviewEditor properties

PreviewEditor.parameter.tooltip=Afficher les paramètres de l'état

###########################################################
#PreviewPageAction properties

PreviewPageAction.actionText.preview=Aperçu

###########################################################
#PropertiesAction properties

PropertiesAction.Text=Propriétés

###########################################################
#PropertyHandleTableViewer properties

PropertyHandleTableViewer.Button.New=&Nouveau...
PropertyHandleTableViewer.Button.Edit=&Edition
PropertyHandleTableViewer.Button.Remove=&Supprimer
PropertyHandleTableViewer.Button.Up=&Vers le haut
PropertyHandleTableViewer.Button.Down=&Vers le bas
PropertyHandleTableViewer.Menu.Remove=Supprimer
PropertyHandleTableViewer.Menu.Up=Vers le haut
PropertyHandleTableViewer.Menu.Down=Vers le bas
PropertyHandleTableViewer.Menu.RemoveAll=Supprimer tout

###########################################################
#PropertyHandleInputDialog properties

PropertyHandleInputDialog.Action.New=Nouveau
PropertyHandleInputDialog.Action.Edit=Modifier
PropertyHandleInputDialog.messages.error.blankProperty={0} ne peut pas être vide

###########################################################
#PublishTemplateAction properties

PublishTemplateAction.wizard.page.browse.cheatsheet.title=Choisir une feuille de fraude
PublishTemplateAction.wizard.page.browse.title=Choisir un fichier image
PublishTemplateAction.wizard.page.btn.browse=Par&courir...
PublishTemplateAction.wizard.page.cheatsheetError=La feuille de fraude ''{0}'' n''existe pas.
PublishTemplateAction.wizard.page.desc=Publier dans le dossier modèle.
PublishTemplateAction.wizard.page.imageError=Le fichier image ''{0}'' n''existe pas.
PublishTemplateAction.wizard.page.label.cheatsheet=Feuille de fraude :
PublishTemplateAction.wizard.page.label.description=&Description :
PublishTemplateAction.wizard.page.label.displayName=No&m d'affichage :
PublishTemplateAction.wizard.page.label.image=&Image modèle :
PublishTemplateAction.wizard.page.title=Publier dans le dossier modèle
PublishTemplateAction.wizard.title=Publier dans le dossier modèle
PublishTemplateAction.wizard.errorTitle=Erreur
PublishTemplateAction.wizard.message=Impossible de publier le modèle dans son propre répertoire ; sélectionnez un autre répertoire pour procéder à la publication.
PublishTemplateAction.wizard.notvalidfolder=Le dossier modèle défini dans la préférence n'est pas valide.
PublishTemplateAction.wizard.page.nameInfo=Le nom d'affichage est requis
PublishTemplateAction.wizard.message.SourceFileNotExist=Le fichier source n'existe pas.
PublishTemplateAction.wizard.message.PreviewImageNotExist=Le fichier de prévisualisation de l'image n'existe pas.
PublishTemplateAction.wizard.message.PreviewImageNotValid=Le fichier de prévisualisation de l'image n'est pas une image valide.

###########################################################
#PublishLibraryAction properties
PublishLibraryAction.wizard.errorTitle=Erreur
PublishLibraryAction.wizard.message=Impossible de publier la bibliothèque dans son propre répertoire ; sélectionnez un autre répertoire pour procéder à la publication.
PublishLibraryAction.wizard.message.SourceFileNotExist=Le fichier source n'existe pas.
PublishLibraryAction.wizard.notvalidfolder=Le dossier de bibliothèque défini dans la préférence n'est pas valide.

###########################################################
#RedoAction properties

RedoAction.Tooltip=Rétablir {0}

###########################################################
#ExportReportWizard
ExportToLibraryAction.wizard.windowTitle=Exporter
ExportToLibraryAction.wizard.page.title=Exporter le fichier dans la bibliothèque
ExportToLibraryAction.wizard.page.desc=Exporter le modèle d'état dans la bibliothèque
ExportToLibraryAction.wizard.page.label.filename=&Nom de fichier :
ExportToLibraryAction.wizard.page.label.folder=&Dossier :
ExportToLibraryAction.wizard.page.button.browser=& Parcourir...
ExportToLibraryAction.wizard.page.dirdialog.message=Sélectionner le répertoire de contenu du fichier
ExportToLibraryAction.wizard.page.nameempty=Le nom de fichier doit être spécifié.
ExportToLibraryAction.wizard.page.folderempty=Le dossier doit être spécifié.
ExportToLibraryAction.wizard.page.foldererror=Le dossier spécifié n'existe pas.

###########################################################
#PublishLibraryToResourceFolderAction
PublishLibraryToResourceFolderAction.Action.Text=Placer la bibliothèque dans le dossier de ressources...

###########################################################
#PublishTemplateViewAction
DefaultNodeProvider.template.suffix=.rpttemplate
PublishTemplateViewAction.action.displaytext=Enregistrer le modèle avec l'assistant Nouvel état...

###########################################################
#RefreshModuleHandleAction
RefreshModuleHandleAction.Action.Text=Actualiser la bibliothèque

###########################################################
#ReferencePage properties

ReferencePage.Button.Edit=&Modifier...
ReferencePage.Label.Source=&Source:

###########################################################
#RefreshAction properties

RefreshAction.text=Actualiser

###########################################################
#RefreshLibExplorerAction properties

RefreshLibExplorerAction.Text=Actualiser

###########################################################
#RemoveLibraryAction properties

RemoveLibraryAction.Text=Supprimer la bibliothèque

###########################################################
#RenameAction properties

RenameAction.text=Renommer

###########################################################
#RenameDialog properties

RenameDialog.action.Cancel=Annuler
RenameDialog.action.Ok=\\ \\ OK  
RenameDialog.text.NewName=Nouveau nom :
RenameDialog.text.Rename=Renommer 
RenameDialog.text.ToolTip=Le nom doit être renseigné.

###########################################################
#RenameInlineTool properties

RenameInlineTool.DialogTitle.RenameFailed=Impossible de renommer
RenameInlineTool.TransLabel.Rename=Renommer

###########################################################
#RenameInputDialog properties

RenameInputDialog.DialogTitle=Renommer l'entrée
RenameInputDialog.DialogMessage=Saisissez le nouveau nom

###########################################################
#report properties

report.designer.ui.preferences.buttonadd=&Ajouter...
report.designer.ui.preferences.buttonremove=&Supprimer
report.designer.ui.preferences.buttonremoveall=Suppri&mer tout
report.designer.ui.preferences.dialogtitle=Ouvrir une bibliothèque
report.designer.ui.preferences.errormessage=Cette bibliothèque existe déjà.
report.designer.ui.preferences.errortitle=Erreur
report.designer.ui.preferences.extensions=*.rptlibrary
report.designer.ui.preferences.labeltitle=Ajouter/Supprimer des bibliothèques
report.designer.ui.preferences.library.export.overwrite.always=&Toujours
report.designer.ui.preferences.library.export.overwrite.never=&Jamais
report.designer.ui.preferences.library.export.overwrite.prompt=&Invite
report.designer.ui.preferences.library.export.title=Ecraser l'élément existant lors de l'exportation de l'élément de modèle vers la bibliothèque
report.designer.ui.preferences.template.openDialogTitle=Sélectionnez un dossier pour les modèles.
report.designer.ui.preferences.template.select=&Sélectionner...
report.designer.ui.preferences.template.templatedir=modèles
report.designer.ui.preferences.template.templatefolder= &Dossier modèle
report.designer.ui.preferences.template.title=Sélectionnez le dossier modèle.
org.eclipse.birt.report.designer.ui.preference.commenttemplates.enablecomment=Générer un commentaire lors de la création du modèle d'état
org.eclipse.birt.report.designer.ui.preference.commenttemplates.defaultcomment=Copyright (c) 2006 <<Nom de votre entreprise>>

###########################################################
#Resource Preference page properties
ResourecePreferencePage.title=Sélectionnez le dossier de ressources par défaut à utiliser pour l'explorateur de bibliothèques, les images, les fichiers de propriété, etc.
ResourecePreferencePage.folder=Dossier de &ressources
ResourecePreferencePage.select=&Sélectionner...
ResourecePreferencePage.openDialogTitle=Parcourir le dossier
ResourecePreferencePage.openDialogMessage=Sélectionnez le dossier de ressources par défaut :
ResourecePreferencePage.defaultResourceFolder.dispaly=<Current Project Folder>

###########################################################
#ReportAdvancedLauncherTab properties

ReportAdvancedLauncherTab.DefaultsButtonText=&Restaurer les paramètres par défaut
ReportAdvancedLauncherTab.DeselectButtonText=&Désélectionner tout
ReportAdvancedLauncherTab.Name=Projets d'état
ReportAdvancedLauncherTab.SelectAllButtonText=&Sélectionner tout
ReportAdvancedLauncherTab.UseListRadioText=Sélectionnez les projets à démarrer dans la liste
ReportAdvancedLauncherTab.VisibleLabelText=&Projets disponibles
ReportAdvancedLauncherTab.WorkspaceReportProjects=projets d'état d'espace de travail

###########################################################
#ReportClasspathLaucnTab properties

ReportClasspathLaucnTab.DefaultButtonText=&Restaurer les paramètres par défaut
ReportClasspathLaucnTab.DeselectButtonText=&Désélectionner tout
ReportClasspathLaucnTab.Name=Projets Java
ReportClasspathLaucnTab.SelectAllButtonText=&Sélectionner tout
ReportClasspathLaucnTab.UseListRadioText=Sélectionnez un projet à lancer dans la liste. Le dossier de sortie de classe du projet sélectionné sera ajouté au chemin de classe.
ReportClasspathLaucnTab.VisibleLabelText=&Projets disponibles
ReportClasspathLaucnTab.WorkspaceJavaProjects=projets java d'espace de travail

###########################################################
#ReportCreationTool properties

ReportCreationTool.ModelTrans.CreateElement=Insérer l'élément

###########################################################
#ReportEditor properties

ReportEditor.Button.Close=Fermer
ReportEditor.Button.Save=Enregistrer
ReportEditor.Dlg.Confirm=Le fichier a été supprimé du système de fichiers. Souhaitez-vous enregistrer vos modifications ou fermer l'éditeur sans enregistrer ?
ReportEditor.Dlg.Save=Enregistrer...
ReportEditor.error.activated.outofsync.message=Le fichier a été modifié dans le système de fichiers. Voulez-vous enregistrer les modifications?
ReportEditor.error.activated.outofsync.title=Fichier modifié
ReportEditor.Error.Open=Erreur à l'ouverture
ReportEditor.Error.OpenEditor=Impossible d'ouvrir le fichier.
ReportEditor.Page.Code=Script
ReportEditor.Page.Layout=Mise en page
ReportEditor.Page.MasterPage=MasterPage
ReportEditor.Page.Preview=Aperçu
ReportEditor.Page.PreviewSaveMessage=Le fichier d'état a été modifié. Souhaitez-vous l'enregistrer avant de lancer l'aperçu ?
ReportEditor.Page.PreviewSaveTitle=Enregistrer
ReportEditor.Page.PreviewSaveToggle=Toujours enregistrer le fichier avant la prévisualisation.

###########################################################
#ReportLaunchConfigurationDelegate properties

ReportLaunchConfigurationDelegate.badFeatureSetup=Mauvaise configuration des fonctions
ReportLaunchConfigurationDelegate.noStartup=Pas de démarrage

###########################################################
#ReportPage properties
ReportPage.text.Add=&Ajouter...
ReportPage.text.Browse=& Parcourir...
ReportPage.title.Location=Emplacement :
ReportPage.title.setPrewImg=Sélectionner un fichier image
ReportPage.text.Resource.Add=&Ajouter...
ReportPage.text.Thumbnail=Miniat&ure...

###########################################################
#ReportPageGenerator properties

ReportPageGenerator.List.Comments=Commentaires
ReportPageGenerator.List.Description=Description
ReportPageGenerator.List.EventHandler=Gestionnaire d'événements
ReportPageGenerator.List.General=Général
ReportPageGenerator.List.Measurement=Mesure
ReportPageGenerator.List.NamedExpressions=Expressions nommées
ReportPageGenerator.List.UserProperties=Propriétés de l'utilisateur
ReportPageGenerator.List.Resources=Ressources
ReportPageGenerator.List.Resources.JarFile=Fichiers Jar :
ReportPageGenerator.List.AdvancedProperty=Avancé

#OdaDataSourceGenerator properties
DataSourcePageGenerator.List.General=Général

#OdaDataSetGenerator properties
DataSetPageGenerator.List.General=Général
DataSetPageGenerator.DataSourceName=Source de &données

#ScalarParameterPageGenerator properties
ScalarParameterPageGenerator.List.General=Général
ScalarParameterPageGenerator.List.I18n=Localisation

#TemplateReportItemPageGenerator properties
TemplateReportItemPageGenerator.List.General=Général
TemplateReportItemPage.description.Label.Instructions=&Instructions :
TemplateReportItemPageGenerator.List.I18n=Localisation
TemplateReportItemPageGenerator.List.TextKey=Clé de texte :

###########################################################
#ReportPropertySheetPage properties

ReportPropertySheetPage.Column.Title.Property=Propriété
ReportPropertySheetPage.Column.Title.Value=Valeur
ReportPropertySheetPage.Root.Default.Title=Infos

###########################################################
#ReportTemplateTransferDropTargetListener properties

ReportTemplateTransferDropTargetListener.ModelTrans.CreateElement=Créer l'élément
ReportTemplateTransferDropTargetListener.transLabel.createElement=Insérer l'élément

###########################################################
#ResourceEditDialog properties

ResourceEditDialog.message.AddNote=La fonction Ajout rapide enregistre la clé dans le fichier de ressources en cours.
ResourceEditDialog.message.ResourceFile=Fichier de ressources : 
ResourceEditDialog.text.Add=Ajouter
ResourceEditDialog.text.AddWarningMsg=Les clés doivent être renseignées.
ResourceEditDialog.text.AddWarningTitle=Warning
ResourceEditDialog.text.Delete=Supprimer
ResourceEditDialog.text.Key=Key
ResourceEditDialog.text.QuickAdd=Ajout rapide
ResourceEditDialog.text.Value=Valeur

###########################################################
#ResourceKeyDescriptor properties

ResourceKeyDescriptor.text.Reset=Réinitialiser
ResourceKeyDescriptor.title.SelectKey=Sélectionner la clé

###########################################################
#RevertToReportItemAction properties

RevertToReportItemAction.text=&Restaurer l'élément d'état

###########################################################
#RevertToTemplateAction properties

RevertToTemplateAction.text=Res&taurer le modèle

###########################################################
#RowHandle properties

RowHandle.tooltip.GridRow=Grille - Ligne
RowHandle.tooltip.GroupFooter=Groupe de tables - Pied de page de groupe
RowHandle.tooltip.GroupHeader=Groupe de tables - En-tête de groupe
RowHandle.tooltip.TableDetail=Table - Détail
RowHandle.tooltip.TableFooter=Table - Pied de page
RowHandle.tooltip.TableHeader=Table - &En-tête

###########################################################
#RowHandleAdapter properties

RowHandleAdapter.table.detail=Ligne de détail
RowHandleAdapter.table.footer=Ligne de pied de page
RowHandleAdapter.table.groupFooter=Ligne de pied de page de groupe
RowHandleAdapter.table.groupHeader=Ligne d'en-tête de groupe
RowHandleAdapter.table.header=Ligne d'en-tête

###########################################################
#RowPageGenerator properties

RowPageGenerator.List.Bookmark=Signet
RowPageGenerator.List.Borders=Bordure
RowPageGenerator.List.Section=Saut de page
RowPageGenerator.List.CellPadding=Marge intérieure
RowPageGenerator.List.Font=Police
RowPageGenerator.List.General=Général
RowPageGenerator.TabItem.Highlights=Surbrillances
RowPageGenerator.TabItem.map=Mappage
RowPageGenerator.List.Visibility=Visibilité

###########################################################
#RowProvider properties

RowProvider.action.text.above=Insérer une ligne &au-dessus
RowProvider.action.text.below=Insérer une ligne au-&dessous

###########################################################
#SaveAsDialog properties

SaveAsDialog.message=Enregistrer le fichier à un autre emplacement.
SaveAsDialog.overwriteQuestion=The file ''{0}'' already exists. Do you want to replace the existing file?
SaveAsDialog.Question=Question
SaveAsDialog.text=Enregistrer sous
SaveAsDialog.title=Enregistrer sous

###########################################################
#CreateDirectory properties
DirectoryDialog.createQuestion=Le répertoire ''{0}'' n''existe pas. Souhaitez-vous le créer ?
DirectoryDialog.Question=Question

###########################################################
#SchematicContextMenuProvider properties

SchematicContextMenuProvider.ActionText.editData=Modifier une &valeur/expression\u2026
SchematicContextMenuProvider.ActionText.editLabel=Mo&difier
SchematicContextMenuProvider.Menu.Apply=A&ppliquer un style
SchematicContextMenuProvider.Menu.EditGroup=&Modifier le groupe
SchematicContextMenuProvider.Menu.Insert=&Insérer
SchematicContextMenuProvider.Menu.insertElement=&Insérer
SchematicContextMenuProvider.Menu.insertRow=&Ligne
SchematicContextMenuProvider.Menu.List=Liste
SchematicContextMenuProvider.Menu.Show=Afficher
SchematicContextMenuProvider.Menu.Style=St&yle
SchematicContextMenuProvider.Menu.Theme=Thè&me
SchematicContextMenuProvider.menutitle.applystylerule=Appliquer un style
SchematicContextMenuProvider.menutitle.applythemerule=Appliquer le thème
SchematicContextMenuProvider.menutitle.editgroup=Modifier le groupe
SchematicContextMenuProvider.menutitle.insert=Insérer
SchematicContextMenuProvider.menutitle.list=Liste
SchematicContextMenuProvider.menutitle.show=Afficher
SchematicContextMenuProvider.menutitle.style=Style
SchematicContextMenuProvider.Menu.EditStyle=&Modifier le style
SchematicContextMenuProvider.Menu.DeleteStyle=Supprimer le st&yle
SchematicContextMenuProvider.Menu.DeleteGroup=Suppri&mer le groupe
SchematicContextMenuProvider.Menu.InsertGroupHeaderFooter=Insérer l'en-tête/le pied de page du grou&pe
SchematicContextMenuProvider.Menu.NewStyle=Nouveau st&yle

###########################################################
#SectionProcess properties

SectionProcess.action.Clear=Effacer
SectionProcess.action.Delete=Supprimer
SectionProcess.action.DeleteRow=Supprimer la ligne
SectionProcess.action.New=Nouveau
SectionProcess.action.NewCell=Nouvelle cellule
SectionProcess.action.NewGroup=Nouveau groupe
SectionProcess.action.NewRow=Nouvelle ligne
SectionProcess.action.NewSection=Nouvelle section
SectionProcess.action.NewSubSection=Nouvelle sous-section
SectionProcess.displayname.GridProcess=Grille
SectionProcess.displayname.GroupProcess=Groupe
SectionProcess.displayname.ListProcess=Liste
SectionProcess.displayname.TableProcess=Table
SectionProcess.displayname.TableRowProcess=Ligne
SectionProcess.type.Container=(Conteneur)
SectionProcess.type.Data=(Données)
SectionProcess.type.Image=(Image)
SectionProcess.type.Label=(Etiquette)
SectionProcess.type.List=(Liste)
SectionProcess.type.Prefix=Colonne
SectionProcess.type.Table=(Table)
SectionProcess.type.Text=(Texte)

###########################################################
#SelectAllAction properties

SelectAllAction.text=Sélectionner &tout

###########################################################
#SelectCssStyleWizard properties

SelectCssStyleWizard.wizard.title=Importer les styles CSS
SelectCssStyleWizard.wizardPage.description=Sélectionnez un fichier CSS, puis importez les styles dans le modèle d'état.
SelectCssStyleWizard.wizardPage.name=Sélectionner les styles CSS
SelectCssStyleWizard.wizardPage.title=Importer le style depuis un fichier CSS

###########################################################
#SelectValueDialog properties

SelectValueDialog.errorRetrievinglist=Erreur de récupération de la liste
SelectValueDialog.messages.info.selectVauleUnavailable=Seules les expressions aux formats de type ligne["nom"], ligne[index] ou ligne.nom peuvent récupérer leur liste de valeurs. 
SelectValueDialog.messages.error.selectVauleUnavailable=La valeur de l'expression ne peut pas être récupérée.
SelectValueDialog.noExpressionSet=Une expression n'a pas été définie
SelectValueDialog.retrieving=Récupération de la liste...
SelectValueDialog.selectValue=Sélectionner une valeur 

###########################################################
#SetConstraintCommand properties

SetConstraintCommand.Error.SetConstraintError=Une erreur s'est produite lors de la définition d'une contrainte pour ce modèle.
SetConstraintCommand.transLabel.setConstraint=Définir une contrainte

###########################################################
#ShowPropertyAction properties

ShowPropertyAction.text=Propriétés

###########################################################
#SortingHandleProvider properties

SortingHandleProvider.Label.SortOn=Trier selon :

###########################################################
#Spinner properties

Spinner.DialogTitle.InvalidNumber=Invalid number

###########################################################
#SplitAction properties

SplitAction.actionMsg.splitCells=&Fractionner la cellule

###########################################################
#StyleBuilder properties

StyleBuilder.action.Apply=&Appliquer
SytleBuilder.DialogTitle.New=Nouveau style
SytleBuilder.DialogTitle.Edit=Modifier le style

###########################################################
#StyleComboProvider properties

StyleComboProvider.LineStyle.None=Aucun style

###########################################################
#StyleNodeProvider properties

StyleNodeProvider.action.Edit=Modifi&er le style...
StyleNodeProvider.action.New=&Nouveau style...

###########################################################
#StyleProcess properties

StyleProcess.action.Delete=Supprimer le style
StyleProcess.action.Edit=Modifi&er le style...
StyleProcess.action.New=&Nouveau style...
StyleProcess.text.CannotDelete=Impossible de supprimer le style par défaut. 
StyleProcess.text.Show=Affiche l'éditeur de jeu de données pour ce jeu de données.

###########################################################
#StylesNodeProvider properties

StylesNodeProvider.action.New=Nouveau style...

###########################################################
#StylesOutlineProcess properties

StylesOutlineProcess.action.New=Nouveau style...

###########################################################
#TableBandProvider properties

TableBandProvider.action.text.group=Insérer le groupe
TableBandProvider.action.text.row=Insérer une ligne

###########################################################
#TableEditPart properties

TableEditPart.GUIDEHANDLE_TEXT = Table
TableEditPart.Label.Merge=Merge Cells
TableEditPart.Label.ResizeColumn=Redimensionner la colonne
TableEditPart.Label.ResizeRow=Redimensionner la ligne

###########################################################
#TableFigure properties

TableFigure.BORDER_TEXT=Table
TableArea.Button.New=&Nouveau...
TableArea.Button.Edit=&Edition
TableArea.Button.Remove=&Supprimer
TableArea.Button.Down=Vers le &bas

###########################################################
#TableHandleAdapter properties

TableHandleAdapter.name.detail=détails
TableHandleAdapter.name.footer=pied de page
TableHandleAdapter.name.header=en-tête
TableHandleAdapter.transLabel.deleteColumn=Supprimer la colonne
TableHandleAdapter.transLabel.deleteColumns=Supprimer les colonnes
TableHandleAdapter.transLabel.deleteRow=Supprimer la ligne
TableHandleAdapter.transLabel.deleteRows=Supprimer les lignes
TableHandleAdapter.transLabel.include=inclure 
TableHandleAdapter.transLabel.insertColumn=insérer une colonne
TableHandleAdapter.transLabel.insertGroup=insérer le groupe
TableHandleAdapter.transLabel.insertRow=insérer une ligne
TableHandleAdapter.transLabel.notInclude=ne pas inclure 
TableHandleAdapter.transLabel.splitCells=Fractionner la cellule
TableHandleAdapter.transLable.deleteGroup=Supprimer le groupe de tables

###########################################################
#TableOptionDialog properties

TableOptionDialog.message.RememberGrid=&Utiliser ces dimensions pour les nouvelles grilles
TableOptionDialog.message.RememberTable=&Utiliser ces dimensions pour les nouvelles tables
TableOptionDialog.text.Column=Nombre de &colonnes :
TableOptionDialog.text.GridRow=Nombre de &lignes :
TableOptionDialog.text.GridSize=Taille de la grille
TableOptionDialog.text.TableDetail=Nombre de &détails :
TableOptionDialog.text.TableSize=Taille de la table
TableOptionDialog.title.InsertGrid=Insérer une grille
TableOptionDialog.title.InsertTable=Insérer une table
TableOptionDialog.text.DataSet=Jeu de données :

###########################################################
#TablePageGenerator properties

TablePageGenerator.List.Bookmark=Signet
TablePageGenerator.List.Borders=Bordure
TablePageGenerator.List.CellPadding=Marge intérieure
TablePageGenerator.List.Font=Police
TablePageGenerator.List.General=Général
TablePageGenerator.List.Marign=Marge
TablePageGenerator.List.Section=Saut de page
TablePageGenerator.List.TOC=Table des matières
TablePageGenerator.List.Visibility=Visibilité
TablePageGenerator.TabItem.Binding=Liaison
TablePageGenerator.TabItem.Filters=Filtres
TablePageGenerator.TabItem.Groups=Groupes
TablePageGenerator.TabItem.Highlights=Surbrillances
TablePageGenerator.TabItem.map=Mappage
TablePageGenerator.TabItem.Sorting=Tri

###########################################################
#TemplateReportItemPropertiesDialog properties

TemplateReportItemPropertiesDialog.errorMessage=Le texte d'invite ne peut pas être vierge.
TemplateReportItemPropertiesDialog.errorTitle=Erreur
TemplateReportItemPropertiesDialog.group=Propriétés de l'élément d'état modèle
TemplateReportItemPropertiesDialog.objectType=Type d'élément :
TemplateReportItemPropertiesDialog.nameText=&Nom :
TemplateReportItemPropertiesDialog.promptText=&Instructions :
TemplateReportItemPropertiesDialog.title=Créer un élément d'état modèle

###########################################################
#performCreatePlaceHolder action
performCreatePlaceHolder.errorMessage.title=Erreur
performCreatePlaceHolder.errorMessage.content=Le nom spécifié existe déjà. Veuillez en choisir un autre ou laisser ce champ vierge.

###########################################################
#TogglePropertyDescriptor properties
TogglePropertyDescriptor.toolTipText.Bold=Gras
TogglePropertyDescriptor.toolTipText.Italic=Italique
TogglePropertyDescriptor.toolTipText.Underline=Texte souligné
TogglePropertyDescriptor.toolTipText.Text_Line_Through=Ligne de texte barré

###########################################################
#TextAlignPropertyDescriptor properties

TextAlignPropertyDescriptor.0=Gauche
TextAlignPropertyDescriptor.1=Centre
TextAlignPropertyDescriptor.2=Droite
TextAlignPropertyDescriptor.3=Justifié

###########################################################
#TextAreaContextMenu properties

TextAreaContextMenu.Copy.description=Copier
TextAreaContextMenu.Copy.image=
TextAreaContextMenu.Copy.label=&Copier
TextAreaContextMenu.Copy.tooltip=Copier
TextAreaContextMenu.Cut.description=Couper
TextAreaContextMenu.Cut.image=
TextAreaContextMenu.Cut.label=Co&uper
TextAreaContextMenu.Cut.tooltip=Couper
TextAreaContextMenu.Paste.description=Coller
TextAreaContextMenu.Paste.image=
TextAreaContextMenu.Paste.label=C&oller
TextAreaContextMenu.Paste.tooltip=Coller
TextAreaContextMenu.Redo.description=Rétablir
TextAreaContextMenu.Redo.image=
TextAreaContextMenu.Redo.label=&Rétablir
TextAreaContextMenu.Redo.tooltip=Rétablir
TextAreaContextMenu.SelectAll.description=Sélectionner tout
TextAreaContextMenu.SelectAll.image=
TextAreaContextMenu.SelectAll.label=Sélecti&onner tout
TextAreaContextMenu.SelectAll.tooltip=Sélectionner tout
TextAreaContextMenu.Undo.description=Annuler
TextAreaContextMenu.Undo.image=
TextAreaContextMenu.Undo.label=&Annuler
TextAreaContextMenu.Undo.tooltip=Annuler

###########################################################
#TextDataEditPart properties

TextDataEditPart.Figure.Dafault=Texte dynamique

###########################################################
#TextEditDialog properties

TextEditDialog.action.text.editDynamicText=&Modifier le texte dynamique
TextEditDialog.action.text.formatDateTime=Date/heur&e
TextEditDialog.action.text.formatNumber=&Nombre
TextEditDialog.action.text.formatString=&Chaîne de format
TextEditDialog.choice.HTML=Texte HTML/Texte dynamique
TextEditDialog.choice.plainText=Texte brut
TextEditDialog.choice.Auto=Auto
TextEditDialog.comboText.formattingAndLayout=Formatage et mise en page
TextEditDialog.format.dynamicText=Texte dynamique
TextEditDialog.format.formatting=Formatage et mise en page
TextEditDialog.format.lists=Listes
TextEditDialog.format.pageComposition=Composition de page
TextEditDialog.format.pageElements=Eléments de page
TextEditDialog.formatChoice.content=Contenu
TextEditDialog.formatChoice.dynamicText=Texte dynamique
TextEditDialog.formatChoice.formatting=Formatage
TextEditDialog.formatChoice.layout=Mise en page
TextEditDialog.formatChoice.lists=Listes
TextEditDialog.toolTip.tag.a=Ancre
TextEditDialog.toolTip.tag.b=Style de texte en gras
TextEditDialog.toolTip.tag.birtImage=Image BIRT spécifique
TextEditDialog.toolTip.tag.br=Saut de ligne
TextEditDialog.toolTip.tag.center=Centrer le texte
TextEditDialog.toolTip.tag.code=Fragment de code machine
TextEditDialog.toolTip.tag.dd=Description de la définition
TextEditDialog.toolTip.tag.del=Texte supprimé
TextEditDialog.toolTip.tag.dl=Liste de définition
TextEditDialog.toolTip.tag.dt=Terme de la définition
TextEditDialog.toolTip.tag.em=Accentuation
TextEditDialog.toolTip.tag.font=Remplacement local de police
TextEditDialog.toolTip.tag.genericStyleContainer=Conteneur de styles/Langage générique
TextEditDialog.toolTip.tag.h1=Niveau de titre 1
TextEditDialog.toolTip.tag.h2=Niveau de titre 2
TextEditDialog.toolTip.tag.h3=Niveau de titre 3
TextEditDialog.toolTip.tag.h4=Niveau de titre 4
TextEditDialog.toolTip.tag.h5=Niveau de titre 5
TextEditDialog.toolTip.tag.h6=Niveau de titre 6
TextEditDialog.toolTip.tag.i=Style de texte en italique
TextEditDialog.toolTip.tag.img=Référence d'image HTML standard
TextEditDialog.toolTip.tag.ins=Texte inséré
TextEditDialog.toolTip.tag.li=Elément de liste
TextEditDialog.toolTip.tag.p=Paragraphe
TextEditDialog.toolTip.tag.pre=Texte préformaté
TextEditDialog.toolTip.tag.strong=Accentuation renforcée
TextEditDialog.toolTip.tag.sub=Indice
TextEditDialog.toolTip.tag.sup=Exposant
TextEditDialog.toolTip.tag.tt=Style de texte télétype ou à espacement fixe
TextEditDialog.toolTip.tag.u=Style de texte souligné
TextEditDialog.toolTip.tag.ul=Liste non numérotée
TextEditDialog.toolTip.valueOf=Value Of
TextEditDialog.toolTipText.copy=Copier
TextEditDialog.toolTipText.cut=Couper
TextEditDialog.toolTipText.delete=Supprimer
TextEditDialog.toolTipText.paste=Coller
TextEditDialog.toolTipText.redo=Rétablir
TextEditDialog.toolTipText.undo=Annuler

###########################################################
#TextEditPart properties

TextEditPart.Figure.Dafault=Texte
TextEditPart.trans.editText=Modifier l'élément de texte

###########################################################
#TextExtendsTools properties

TextExtendsTools.Message.DefaultAuthor=Version de Birt Eclipse Report Designer

###########################################################
#TextPageGenerator properties

TextPageGenerator.List.Bookmark=Signet
TextPageGenerator.List.Borders=Bordure
TextPageGenerator.List.General=Général
TextPageGenerator.List.I18n=Localisation
TextPageGenerator.List.Margin=Marge
TextPageGenerator.List.Padding=Remplissage
TextPageGenerator.List.Section=Saut de page
TextPageGenerator.List.TOC=Table des matières
TextPageGenerator.List.Visibility=Visibilité

###########################################################
#TextPropertyDescriptor properties

TextPropertyDescriptor.Message.Version=Eclipse BIRT Designer Version {0} Build <{1}>

###########################################################
#AutoTextPageGenerator properties

AutoTextPageGenerator.List.Bookmark=Signet
AutoTextPageGenerator.List.Borders=Bordure
AutoTextPageGenerator.List.General=Général
AutoTextPageGenerator.List.Margin=Marge
AutoTextPageGenerator.List.Padding=Remplissage
AutoTextPageGenerator.List.Section=Saut de page
AutoTextPageGenerator.List.TOC=Table des matières
AutoTextPageGenerator.List.Visibility=Visibilité

###########################################################
#ThemesNodeProvider properties

ThemesNodeProvider.action.New=Nouveau thème

###########################################################
#TimeOptionDialog properties

TimeOptionDialog.Label.Format=Format
TimeOptionDialog.Label.TimeZone=Fuseau horaire

###########################################################
#ToggleMarginVisibilityAction properties

ToggleMarginVisibilityAction.text.Label=Afficher les &marges
ToggleMarginVisibilityAction.text.Tooltip=Basculer les marges

###########################################################
#TwinExpressionDialog properties

TwinExpressionDialog.Dialog.Title=Sélectionner des valeurs
TwinExpressionDialog.lable.value1=Valeur1 :
TwinExpressionDialog.lable.value2=Valeur2 :

###########################################################
#UndoAction properties

UndoAction.Tooltip=Annuler {0}

###########################################################
#UnitPropertyDescriptor properties

UnitPropertyDescriptor.error.message=Please enter a smaller value\!
UnitPropertyDescriptor.error.title=Too Big Value

###########################################################
#UseLibraryAction properties

UseLibraryAction.Text=&Utiliser la bibliothèque
UseLibraryAction.Error.Title=Remplacer le fichier existant
UseLibraryAction.Error.Message=Le fichier ''{0}'' existe déjà dans le dossier de ressources BIRT. Souhaitez-vous remplacer le fichier existant ?

###########################################################
#UserPropertyBuilder properties

UserPropertyBuilder.0=Nouvelle propriété d'utilisateur
UserPropertyBuilder.ErrorMessage.DuplicatedName=Le nom spécifié est déjà utilisé.
UserPropertyBuilder.ErrorMessage.NoName=Veuillez spécifier un nom.
UserPropertiesHandleProvier.Column.Name=Nom
UserPropertiesHandleProvier.Column.Type=Type
UserPropertyBuilder.Label.DefaultValue=&Valeur par défaut :
UserPropertyBuilder.Label.ExpressionName=&Nom de l'expression :
UserPropertyBuilder.Label.PropertyName=&Nom de la propriété :
UserPropertyBuilder.Label.PropertyType=&Type de propriété :
UserPropertyBuilder.Title.NamedExpression=Nouvelle expression nommée

###########################################################
#VisibilityPage properties

VisibilityPage.Check.HideElement=&Masquer l'élément
VisibilityPage.Check.HTML=H&TML
VisibilityPage.Check.PDF=&PDF
VisibilityPage.Label.DetailAll=Détails (Toutes les sorties)
VisibilityPage.Label.DetailSpecific=Détails (Sorties spécifiques)
VisibilityPage.Label.Expression=&Expression :
VisibilityPage.menu.SaveHides=Enregistrer les éléments masqués
VisibilityPage.Radio.AllOutputs=&Pour toutes les sorties
VisibilityPage.Radio.SpecificOutputs=Pour les sorties &spécifiques...

###########################################################
#WidgetUtil properties

WidgetUtil.MessageBox.Error=Erreur

###########################################################
#wizard properties

wizard.transaction.createDataSource=Définir le nom et le type de la source de données.

###########################################################
#WizardChoicePage properties

WizardChoicePage.radio.createBlank=Créer un état vierge sans modèle.
WizardChoicePage.radio.createFromCustom=Créer l'état comme copie d'un autre état.
WizardChoicePage.radio.createFromTemplate=Créer l'état d'après un modèle.

###########################################################
#WizardCustomTemplatePage properties

WizardCustomTemplatePage.button.Browse=Parcourir
WizardCustomTemplatePage.label.FileName=Enter ou sélectionner le nom d'un fichier d'état existant.
WizardCustomTemplatePage.label.FromLocal=Parcourir depuis le système de fichiers local.
WizardCustomTemplatePage.label.FromProjectDescription=Choisir un fichier d'état existant.
WizardCustomTemplatePage.label.FromProjectTitle=Sélection du fichier d'état

###########################################################
#WizardNewReportCreationPage properties

WizardNewReportCreationPage.Errors.nameExists=Ce nom existe déjà.
WizardNewReportCreationPage.label.browse=Parcourir...
WizardNewReportCreationPage.label.directory=Répertoire :
WizardNewReportCreationPage.label.file.location=Emplacement du fichier
WizardNewReportCreationPage.label.file.name=Nom du fichier :
WizardNewReportCreationPage.label.select.directory=Sélectionnez un répertoire.
WizardNewReportCreationPage.label.useDefault=Utiliser la valeur par défaut
WizardNewReportCreationPage.msg.duplicate.fileName=Ce nom existe déjà.
WizardNewReportCreationPage.msg.empty.file.locationDirectory=Le répertoire d'emplacement du fichier doit être renseigné.
WizardNewReportCreationPage.msg.empty.file.name=Le nom du fichier doit être renseigné.

###########################################################
#WizardSelectCssStylePage properties

WizardSelectCssStylePage.button.label.browse=& Parcourir...
WizardSelectCssStylePage.button.label.deselectAll=&Désélectionner tout
WizardSelectCssStylePage.button.label.selectAll=&Sélectionner tout
WizardSelectCssStylePage.errorMsg.FileNotExist=Le fichier n'existe pas.
WizardSelectCssStylePage.info.canNotImport=\ \ (importation impossible)
WizardSelectCssStylePage.label.fileName=&Nom de fichier :
WizardSelectCssStylePage.label.importToReportDesign=\ pour importer dans le modèle d'état.
WizardSelectCssStylePage.label.notifications=Notifications :
WizardSelectCssStylePage.label.selectStylesFrom=Sélectionner les styles dans 
WizardSelectCssStylePage.msg.FileNameEmpty=Le nom du fichier doit être renseigné.
WizardSelectCssStylePage.text.cannot.import.style=\ - Impossible d'importer le style.
WizardSelectCssStylePage.FileNameError.Title=Erreur
WizardSelectCssStylePage.FileNameError.Message=Le fichier sélectionné n'est pas valide.

###########################################################
#WizardTemplateChoicePage properties

WizardTemplateChoicePage.label.Description=Description :
WizardTemplateChoicePage.label.Preview=Aperçu :
WizardTemplateChoicePage.label.ReportTemplates=Modèles d'état :
WizardTemplateChoicePage.label.ShowCheatSheets=&Afficher la feuille de fraude de création d'état
WizardTemplateChoicePage.message.BlankReport=Crée un état vierge sans aucun contenu prédéfini.
WizardTemplateChoicePage.message.ChartListing=Crée un état groupé avec un graphique fournissant une représentation visuelle de chaque donnée de groupe.
WizardTemplateChoicePage.message.DualColumnChartListing=Crée un état groupé avec deux sous-groupes Graphiques et listes.
WizardTemplateChoicePage.message.DualColumnListing=Crée un état groupé avec deux sous-groupes.
WizardTemplateChoicePage.message.FirstReport=Fournit des instructions sur la création de listes de clients.
WizardTemplateChoicePage.message.GroupedListing=Crée une liste dans les états avec regroupement dans certains champs.
WizardTemplateChoicePage.message.Letter=Crée un modèle de création de lettres personnalisées au moyen des champs issus de la source de données
WizardTemplateChoicePage.message.MailingLabels=Etiquettes de publipostage
WizardTemplateChoicePage.message.SideBySideChartListing=Crée un état groupé dans lequel les groupes contiennent chacun un graphique et une liste côte à côte.
WizardTemplateChoicePage.message.SimpleListing=Crée une liste avec des champs issus de la source de données.
WizardTemplateChoicePage.title.BlankReport=Etat vierge
WizardTemplateChoicePage.title.ChartListing=Graphiques et listes
WizardTemplateChoicePage.title.DualColumnChartListing=Graphiques et listes de colonnes doubles
WizardTemplateChoicePage.title.DualColumnListing=Listes de colonnes doubles
WizardTemplateChoicePage.title.FirstReport=Mon premier état
WizardTemplateChoicePage.title.GroupedListing=Listes groupées
WizardTemplateChoicePage.title.Letter=Lettre
WizardTemplateChoicePage.title.MailingLabels=Etiquettes de publipostage
WizardTemplateChoicePage.title.SideBySideChartListing=Graphiques et listes juxtaposés
WizardTemplateChoicePage.title.SimpleListing=Listes simples

###########################################################
#XMLSourcePage properties

XMLSourcePage.Error.Dialog.Message.InvalidFile=Une erreur dans la page XML source doit être corrigée avant l'utilisation d'autres pages.
XMLSourcePage.Error.Dialog.Message.SaveFile=La page XML source a été modifiée. Les autres pages ne pourront être utilisées qu'une fois la source XML enregistrée.
XMLSourcePage.Error.Dialog.title=Erreur
XMLSourcePage.Error.Dialog.Message.PromptMsg=La source du modèle d'état XML a été modifiée. Voulez-vous enregistrer les modifications ?
XMLSourcePage.Error.Dialog.Message.Yes=Oui
XMLSourcePage.Error.Dialog.Message.No=Non
XMLSourcePage.Error.Dialog.Message.Cancel=Annuler

###########################################################
#SaveReportAsWizard properties
SaveReportAsWizard.SettingPage.title=Définir les propriétés du modèle
SaveReportAsWizard.SaveAsPageTitle=Enregistrer sous
SaveReportAsWizard.SaveAsLibraryMessage=Enregistrez le fichier en tant que bibliothèque sous un autre nom.
SaveReportAsWizard.SaveAsReportorTemplateMessage=Enregistrez le fichier en tant que modèle d'état ou modèle sous un autre nom.
SaveReportAsWizard.SettingPageTitle=Définir la propriété de l'état
SaveReportAsWizard.SettingPage.message=Ces propriétés sont utilisées dans les cas où l'état est enregistré en tant que modèle.
SaveReportAsWizard.SaveAsWizardWindowTitle=Enregistrer sous
SaveReportAsWizard.SaveAsWizardPageTitle=Enregistrer sous
SaveReportAsWizard.SaveAsWizardPageDesc=Enregistrer le fichier à un autre emplacement.

###########################################################
#WizardReportSettingPage properties
WizardReportSettingPage.Error.ReportorTemplate=Le nom de fichier doit se terminer par {0} ou .rpttemplate.
WizardReportSettingPage.Error.Library=Le nom de fichier doit se terminer par .rptlibrary.

###########################################################
#WizardSaveAsPage properties
WizardSaveAsPage.FileLabel=&Nom de fichier :
WizardSaveAsPage.Question=Question
WizardSaveAsPage.FolderEmpty=\ Le dossier est vide.
WizardSaveAsPage.NoProject=\ Le projet spécifié n'existe pas.
WizardSaveAsPage.PathOccupied=\ Un fichier existe déjà à cet emplacement : {0}
WizardSaveAsPage.EmptyName=\ Le nom ''{0}'' est vide.
WizardSaveAsPage.SelectFolder=\ Sélectionner le dossier :
WizardSaveAsPage.NameExists=\ Ce nom existe déjà.
WizardSaveAsPage.OverwriteQuestion=Le fichier ''{0}'' existe déjà. Voulez-vous remplacer le fichier existant ?
WizardSaveAsPage.InvalidFileName=\ ''{0}'' n''est pas un nom de fichier valide.
WizardSaveAsPage.ContainerGroup=\ &Entrer ou sélectionner le dossier parent :

###########################################################
#Library DND message
Library.DND.messages.outofsync = La bibliothèque utilisée dans l'état a probablement été modifiée ; fermez l'état puis ouvrez-le de nouveau pour utiliser la bibliothèque mise à jour.
NamedExpressionsHandleProvier.Column.Name=Nom
NamedExpressionsHandleProvier.Column.DefaultValue=Valeur par défaut
Library.DND.messages.cannotApplyTheme=Le thème ne peut pas être appliqué.

JarFileFormProvider.Column.Name=Nom

###########################################################
#ClassFinder
ClassFinder.TaskStart=Recherche de la classe de gestionnaire...
ClassFinder.DialogTitle=Sélection de la classe
ClassFinder.DialogMessage=Choisir une classe de gestionnaire
ClassFinder.ErrorMessage=Aucune classe trouvée

###########################################################
#ListingSectionPage
ListingSectionPage.RepeatHeader=Répéter l'en-tête

###########################################################
#ResourceEditDialog
ResourceEditDialog.NotFile.Title=Fichier introuvable
ResourceEditDialog.NotFile.Message=Le fichier ''{0}'' n'existe pas.
ResourceEditDialog.ReadOnlyEncounter.Title=Fichier en lecture seule
ResourceEditDialog.ReadOnlyEncounter.Message=Le fichier ''{0}'' est en lecture seule, vous devez d''abord disposer des droits en écriture.

###########################################################
#EventHandler
EventHandlerPage.Browse=& Parcourir...


###########################################################
#IDEFileReportProvider
IDEFileReportProvider.ReadOnlyEncounter.Title=Fichier en lecture seule
IDEFileReportProvider.ReadOnlyEncounter.Message=Le fichier ''{0}'' est en lecture seule, vous devez d''abord disposer des droits en écriture.

###########################################################
#DataSetColumnBindingsFormHandleProvider
DataSetColumnBindingsFormHandleProvider.Column.Name=Nom
DataSetColumnBindingsFormHandleProvider.Column.displayName=Nom d'affichage
DataSetColumnBindingsFormHandleProvider.TableTitle=Liaison de colonne de données :
DataSetColumnBindingsFormHandleProvider.NewBinding=Nouvelle liaison  
DataSetColumnBindingsFormHandleProvider.Column.DataType=Type de données
DataSetColumnBindingsFormHandleProvider.Column.Expression=Expression
DataSetColumnBindingsFormHandleProvider.Column.AggregateOn=Regrouper par
DataSetColumnBindingsFormHandleProvider.ALL=Tous
DataSetColumnBindingsFormHandleProvider.NONE=N/A

###########################################################
#DataSetColumnBindingsFormPage
DataSetColumnBindingsFormPage.Button.RemoveUnused=Supprimer une colonne inutilisée
###########################################################
#ResourceSelectionValidator
ResourceSelectionValidator.ExtError=Le fichier sélectionné doit se terminer par 
ResourceSelectionValidator.EmptyError=Sélectionnez un fichier
ResourceSelectionValidator.ExtErrorSplitter=\ ou 

###########################################################
#GeneralPage
GeneralPage.Library.Included=Bibliothèque :
###########################################################
#
FormatStringPage.SimpleTextZipCode=94103
FormatStringPage.SimpleTextZipCode4=941031234
FormatStringPage.PhoneNumber=4155551111
FormatStringPage.SocialSecurityNumber=123456789
FormatStringPage.simpleTexZipCodeFormat=@@@@@
FormatStringPage.simpleTexZipCode4Format=@@@@@
FormatStringPage.phoneNumberFormat=@@-@@-@@-@@-@@
FormatStringPage.securityNumberFormat=@@@-@@-@@@@


###########################################################
#PublishLibraryDialog
PublishLibraryDialog.ShellText=Publier la bibliothèque
PublishLibraryDialog.TitleArea=Publier la bibliothèque
PublishLibraryDialog.Message=Publier la bibliothèque dans le dossier de ressources BIRT
PublishLibraryDialog.Label.SourceFileName=&Fichier source :
PublishLibraryDialog.Label.FileName=&Nom de fichier :
PublishLibraryDialog.Label.Folder=&Dossier :
PublishLibraryDialog.Label.Browse=& Parcourir...
PublishLibraryDialog.Message.FileNameEmpty=Nom de fichier requis.
PublishLibraryDialog.Message.FileNameError=Le nom de fichier doit se terminer par .rptlibrary.
PublishLibraryDialog.Message.FolderEmpty=Dossier de publication requis.
PublishLibraryDialog.Message.SourceFileEmpty=Nom de fichier source requis.
PublishLibraryDialog.Label.Browse2=Par&courir...
PublishLibraryDialog.AddText=Ajouter une bibliothèque
PublishLibraryDialog.AddMessage=Ajouter la bibliothèque dans le dossier de ressources BIRT

WizardLibrarySettingPage.ErrorMessage=Sélectionner un dossier

WizardLibrarySettingPage.Resourcefile.Dialog.Title=Parcourir les dossiers de ressources
WizardLibrarySettingPage.Resourcefile.Dialog.Message=Sélectionnez le dossier de ressources ou un de ses sous-dossiers.

PublishLibraryDialog.AddLibrary=Ajouter une bibliothèque

###########################################################
#EmbeddedImagesNodeProvider
EmbeddedImagesNodeProvider.FileNameError.Title=Erreur
EmbeddedImagesNodeProvider.FileNameError.Message=Le fichier sélectionné n'est pas une image.

###########################################################
#AddElementtoAction properties
AddElementtoAction.Text=&Ajouter à l'état

###########################################################
#MultiPageReportEditor properties
MultiPageReportEditor.CheckVersion.Dialog.Title=Avertissement
TableArea.Button.Up=&Vers le haut

###########################################################
#AddJarResourceFileFolderSelectionDialog
AddJarResourceFileFolderSelectionDialog.ErrorMessage.Exist=Un ou plusieurs fichiers existent déjà.
AddJarResourceFileFolderSelectionDialog.Message=Sélectionnez les fichiers jar :
AddJarResourceFileFolderSelectionDialog.ErrorMessage.ExtError=Le nom de fichier doit se terminer par .jar.

###########################################################
#AddImageResourceFileFolderSelectionDialog
AddImageResourceFileFolderSelectionDialog.Title=Un ou plusieurs fichiers existent déjà.
AddImageResourceFileFolderSelectionDialog.Message=Veuillez sélectionner une image :

###########################################################
#DataItemBindingDialog properties

DataItemBindingDialog.text.Name=Nom :
DataItemBindingDialog.text.displayName=Nom d'affichage :
DataItemBindingDialog.text.DataType=Type de données :
DataItemBindingDialog.text.Expression=Expression :
DataItemBindingDialog.text.AggregateOn=Regrouper par :
DataItemBindingDialog.text.ForceBinding=Crée une nouvelle liaison avec la même expression
DataItemBindingDialog.text.All=Tous
DataItemBindingDialog.text.None=N/A
DataItemBindingDialog.title.CreateNewItem=Nouvelle liaison d'élément de données
DataItemBindingDialog.title.EditDataItem=Modifier la liaison d'élément de données

###########################################################
#DataColumBindingDialog properties
DataColumBindingDialog.title.CreateNewDataBinding=Nouvelle liaison de données
DataColumBindingDialog.title.EditDataBinding=Modifier la liaison de données

###########################################################
#CreatePlaceHolderAction properties
ChangeDataColumnAction.text=Modifier la colonne de données

###########################################################
#ThumbnailBuilder properties
ThumbnailBuilder.Text.Title=Gérer la miniature
ThumbnailBuilder.Button.Text.Generate=&Générer
ThumbnailBuilder.Button.Text.Remove=&Supprimer
ThumbnailBuilder.Button.Text.Import=&Importer...
ThumbnailBuilder.FileDialog.Title=Sélectionner un fichier image
ThumbnailBuilder.FileDialog.FileNameError.Title=Erreur
ThumbnailBuilder.FileDialog.FileNameError.Message=Le fichier sélectionné n'est pas une image.

###########################################################
#FragmentResourceEntry properties
FragmentResourceEntry.RootName=Fragments
FragmentResourceEntry.RootDisplayName=Bibliothèques intégrées

###########################################################
#PathResourceEntry properties
PathResourceEntry.RootName=Dossier de ressources
PathResourceEntry.RootDisplayName=Bibliothèques partagées

###########################################################
#BIRTGotoMarker properties
BIRTGotoMarker.Error.Title=Erreur
BIRTGotoMarker.Error.Message=L'élément d'état n'existe pas.

###########################################################
#TabbedList properties
TabbedPropertyList.properties.not.available=Les propriétés ne sont pas disponibles.

###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubes
cube.new=New Cube
cube.edit=Edit Cube
CubeNodeProvider.menu.text=Modifier
cube.dimension.new=New Cube Dimension
cube.dimension.edit=Edit Cube Dimension
CubeDimensionNodeProvider.menu.text=Modifier
cube.level.new=New Cube Level
cube.level.edit=Edit Cube Level
CubeLevelNodeProvider.menu.text=Modifier
cube.measure.new=New Cube Measure
cube.measure.edit=Edit Cube Measure
CubeMeasureNodeProvider.menu.text=Modifier
cube.measuregroup.new=New Cube Measure Group
cube.measure.edit=Edit Cube Measure Group
CubeMeasureGroupNodeProvider.menu.text=Modifier

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=OLAP Cube Builder
DatasetPage.Title=Dataset
DimensionPage.Title=Dimension
MeasurePage.Title=Measures
DatasetPage.Label.Name=Cube name:
DatasetPage.Label.PrimaryDataset=Primary dataset:
DatasetPage.Button.Filter=Filter...
DatasetPage.Button.Joint=Add joint datasets...
DimensionPage.Label.Title=Dimension:
DimensionPage.Button.Add=&Ajouter
DimensionPage.Button.Edit=&Edit
DimensionPage.Button.Delete=&Supprimer
DimensionPage.Button.Property=&Property
MeasuresPage.Label.DataField=Available data fields:
MeasuresPage.Label.Measures=Measures:
MeasuresPage.Button.Add=Ajouter
MeasuresPage.Label.Name=&Nom :
MeasuresPage.Label.Function=&Function:
MeasuresPage.Label.Expression=&Expression :
DatasetDialog.Title.Label=Add Datasets
DatasetDialog.Title.OKButton.Text=Ajouter
DimensionDialog.Title=OLAP Cube Builder
DimensionDialog.Button.Primary=Use primary dataset as Dimension dataset
DimensionDialog.Button.Other=Use other dataset as Dimension dataset:
DimensionDialog.Label.DatasetField=Available data fields:
DimensionDialog.Label.Dimensions=Dimensions:
DimensionDialog.Label.Name=Dimension Name:
DimensionDialog.Label.Add=Add Dimension
DimensionDialog.Label.Edit=Edit Dimension
CubeDialog.Title=Insérer
CubeDialog.Label.Select=Selected data for Cross Tab:
CubeDialog.Button.Define=Define data for Cross Tab
LevelDialog.Title=OLAP Cube Builder
LevelDialog.Label.Name=Nom :
LevelDialog.Label.Field=Choose Field:
LevelDialog.Label.Info=Selected Key:
LevelDialog.Label.Add=Add Level
LevleDialog.Label.Edit=Edit Level
LevelPropertyDialog.Title=Level
LevelPropertyDialog.MSG.CreateNew=<Create New Parameter>
LevelPropertyDialog.Label.Name=Nom :
LevelPropertyDialog.Label.Interval=Intervalle :
LevelPropertyDialog.Label.Range=Range:
LevelPropertyDialog.Button.IntervalBase=Use fixed base value for interval:
LevelPropertyDialog.Label.Info=Selected Key:
LevelPropertyDialog.Button.Dynamic=Dynamic
LevelPropertyDialog.Button.Static=Static
LevelPropertyDialog.Label.Property=Level Property
LevelPropertyDialog.Label.Attribute=Attribute
LevelPropertyDialog.Label.Name=Nom :
LevelPropertyDialog.Label.Expression=Expression
