###########################################################
#AbstractDataSetWizard properties

AbstractDataSetWizard.ModelTrans.Create=Geben Sie den Namen, die Quelle und die Art des Datensatzes an.
###########################################################
#CssErrDialog
CssErrDialog.shellTitle.ImportCssStyleMssageTitle=Importmeldung
CssErrDialog.AreaTitle=CSS-Stile importieren – Meldung
CssErrDialog.AreaMessage=Beim Importieren von CSS-Stilen sind Fehler bzw. Warnungen aufgetreten.
CssErrDialog.Serverity=Schweregrad:
CssErrDialog.Message=Meldung:
CssErrDialog.FatalError=Nicht behebbarer Fehler
CssErrDialog.Error=Fehler
CssErrDialog.Warning=Warnung

###########################################################
#AddGroupAction properties

AddGroupAction.actionMsg.addGroup=Gruppe einfügen...
AddGroupAction.Menu.Text=Gruppe einfügen...
AddGroupAction.stackMsg.addGroup=Gruppe einfügen

###########################################################
#AddLibraryAction properties

AddLibraryAction.Error.FileNotFound=Datei ''{0}'' wurde nicht gefunden.
AddLibraryAction.Error.FileIsNotLibrary=Datei ''{0}'' endet nicht mit ''{1}''.
AddLibraryAction.Error.Message=Die Datei ist bereits vorhanden.
AddLibraryAction.Error.Title=Fehler
AddLibraryAction.Text=Bibliothek hinzufügen...
AddLibraryAction.Dialog.Tilte=Bibliothek auswählen

###########################################################
#DeleteLibraryAction properties
DeleteLibraryAction.Text=Löschen
###########################################################
#AddStyleRuleAction properties

AddStyleAction.actionMsg.addStyleRule=&Neuer Stil...
AddStyleAction.stackMsg.addStyle=&Neuer Stil

###########################################################
#ApplyStyleAction properties

ApplyStyleAction.actionLabel.none=Keine
ApplyStyleAction.stackMsg.applyStyle=Stil anwenden

###########################################################
#ApplyThemeAction properties

ApplyThemeAction.actionLabel.none=Kein
ApplyThemeAction.stackMsg.applyStyle=Thema verwenden

###########################################################
#AttributesBuilder properties

AttributesBuilder.Label.Cell=Eigenschaftseditor - Zelle
AttributesBuilder.Label.Column=Eigenschaftseditor - Spalte
AttributesBuilder.Label.Data=Eigenschaftseditor - Daten
AttributesBuilder.Label.Generic=Eigenschaftseditor - {0}
AttributesBuilder.Label.Grid=Eigenschaftseditor - Raster
AttributesBuilder.Label.Label=Eigenschaftseditor - Beschriftung
AttributesBuilder.Label.Library=Eigenschaftseditor - Bibliothek
AttributesBuilder.Label.List=Eigenschaftseditor - Liste
AttributesBuilder.Label.MasterPage=Eigenschaftseditor - Master-Seite
AttributesBuilder.Label.None=Eigenschaftseditor - Keine
AttributesBuilder.Label.Picture=Eigenschaftseditor - Bild
AttributesBuilder.Label.Report=Eigenschaftseditor - Bericht
AttributesBuilder.Label.Row=Eigenschaftseditor - Zeile
AttributesBuilder.Label.Table=Eigenschaftseditor - Tabelle
AttributesBuilder.Label.Text=Eigenschaftseditor - Text
AttributesBuilder.Label.TextData=Eigenschafteneditor - Dynamischer Text
AttributesBuilder.Label.DataSourceHandle=Eigenschaftseditor - Datenquelle
AttributesBuilder.Label.DataSetHandle=Eigenschaftseditor - Datensatz
AttributesBuilder.Label.ScalarParameterHandle=Eigenschaftseditor - Parameter
AttributesBuilder.Label.TemplateReportItemHandle=Eigenschaftseditor - Berichtobjekt für Vorlage
AttributesBuilder.Label.AutoText=Eigenschaftseditor - AutoText

###########################################################
#AttributeView properties
AttributeView.dialg.Message.Warning = Warnung
AttributeView.dialg.Message.Yes=J&a
AttributeView.dialg.Message.No=N&ein
AttributeView.dialg.Message.Cancel=&Abbrechen
AttributeView.dialg.Message.PromptMsg=Möchten Sie wirklich alle lokalen Eigenschaften löschen?
AttributeView.toolbar.tooltip.EditingToggleAction.ClearMsg=Löschen Sie die lokalen Eigenschaften.
AttributeView.toolbar.tooltip.EditingToggleAction.EnableEditingMsg=Aktivieren Sie das Bearbeiten der Eigenschaften.
AttributeView.toolbar.tooltip.EditingToggleAction.DisabledActionMsg=Diese Aktion ist für lokale Elemente nicht verfügbar.
AttributeView.view.message.Emptypage= {0} ist eine Erweiterung von {1} in Bibliothek {2}. Wenn Sie das Ändern der Eigenschaften von {3} in diesem Berichtdesign ermöglichen möchten, klicken Sie in der Symbolleiste des Eigenschaftseditors auf die Schaltfläche für das Aktivieren der Bearbeitungsfunktion.
AttributeView.toolbar.tooltip.RestoreLibraryPropertiesAction.RestoreMsg=Eigenschaften wiederherstellen
AttributeView.defaultText.noAttributeView = Der Eigenschaftseditor ist nicht verfügbar.
###########################################################
#BackGroundPreferencePage properties

BackGroundPreferencePage.displayname.Title=Hintergrund

###########################################################
#BasAttributePage properties

BasAttributePage.Label.Attributes=Eigenschaften:

###########################################################
#BaseInsertMenuAction properties

BaseInsertMenuAction.stackMsg.insertElement=Element einfügen

###########################################################
#BasePaletteFactory properties

BasePaletteFactory.AutoText.Confidential=Vertraulich
BasePaletteFactory.AutoTextLabel.CreatedBy=Erstellt von: 
BasePaletteFactory.AutoTextLabel.CreatedOn=Erstellt am: 
BasePaletteFactory.AutoTextLabel.Filename=Dateiname: 
BasePaletteFactory.AutoTextLabel.LastPrinted=Zuletzt ausgedruckt: 
BasePaletteFactory.AutoTextLabel.Page=Seite: 
BasePaletteFactory.AutoTextLabel.PageCount=Seitenzähler:
BasePaletteFactory.AutoTextLabel.PageXofY=Seite X von Y
BasePaletteFactory.categoryName.PointerSelect=Zeigerauswahl
BasePaletteFactory.categoryName.RectangleSelect=Rechteckauswahl
BasePaletteFactory.Group.Items=Elemente
BasePaletteFactory.toolTip.PointerSelect=Klicken Sie auf ein Element, um es auszuwählen, oder klicken Sie bei gedrückter Strg-Taste auf mehrere Elemente, um diese auszuwählen.
BasePaletteFactory.toolTip.RectangleSelect=Ziehen Sie mit gedrückter Maustaste ein Rechteck um mehrere Elemente, um diese auszuwählen. 

###########################################################
#BaseStylePreferencePage properties

BaseStylePreferencePage.displayname.Title=Allgemein

###########################################################
#BgImageFieldEditor properties

BgImageFieldEditor.displayname.Browse=&Durchsuchen...

###########################################################
#BindingPage properties

BindingPage.Label.Binding=Bindung
BindingPage.MessageDlg.SaveParamBinding=ParamBinding speichern
BindingPage.None=Keine
BindingPage.TableColumn.DataType=Datentyp
BindingPage.TableColumn.Parameter=Parameter
BindingPage.TableColumn.Value=Wert

ColumnBingingDialog.Label.Warn=Das Ändern des Datensatzes könnte zur Folge haben, dass alle Ausdrücke in den Ergebnisspalten ungültig werden.
ColumnBindingDialog.Label.DataSet=Datensatz:
ColumnBindingDialog.Column.Expression=Ausdruck
ColumnBindingDialog.DialogTitle=Datenbindung auswählen
ColumnBindingDialog.Column.Name=Name
ColumnBindingDialog.Column.displayName=Angezeigter Name
ColumnBindingDialog.InputPrompt=<Hier den neuen Wert eingeben...>
ColumnBindingDialog.Button.Generate=Spaltenbindungen generieren
ColumnBindingDialog.Column.DataType=Datentyp
ColumnBindingDialog.Column.AggregateOn=Aggregat ein
ColumnBindingDialog.All=Alles
ColumnBindingDialog.NONE=Ohne
ColumnBindingDialog.Choice.FromContainer=Datensatz des Containers
ColumnBindingDialog.AGGREGATEON.NONE=n.a.
ColumnBindingDialog.Text.Add=Hinzufügen
ColumnBindingDialog.Text.Edit=Bearbeiten...
ColumnBindingDialog.Text.Del=Löschen

###########################################################
#BlockPreferencePage properties

BlockPreferencePage.displayname.Title=Textblock

###########################################################
#BorderPreferencePage properties

BorderPreferencePage.displayname.Color=Farbe
BorderPreferencePage.displayname.Style=Stil
BorderPreferencePage.displayname.Title=Rahmen
BorderPreferencePage.displayname.Width=Breite
BorderPreferencePage.text.Bottom=Unten:
BorderPreferencePage.text.Left=Links:
BorderPreferencePage.text.Right=Rechts:
BorderPreferencePage.text.Top=Oben:

###########################################################
#BordersPage properties

BordersPage.Label.Borders=&Rahmen:
BordersPage.Label.Color=&Farbe:
BordersPage.Label.Presets=Voreinstellungen:
BordersPage.Label.Style=&Stil:
BordersPage.Label.Width=&Breite:
BordersPage.Tooltip.All=Alle Rahmen
BordersPage.Tooltip.Bottom=Unterer Rahmen
BordersPage.Tooltip.Left=Linker Rahmen
BordersPage.Tooltip.None=Keine
BordersPage.Tooltip.Right=Rechter Rahmen
BordersPage.Tooltip.Top=Oberer Rahmen
BordersPage.text.Preview=Vorschau:
BordersPage.Trans.SelectBorder=Rahmen auswählen
BordersPage.Trans.UnSelectBorder=Auswahl des Rahmens aufheben
BordersPage.Trans.SelectAllborders=Alle Rahmen auswählen
BordersPage.Trans.UnSelectAllborders=Auswahl aller Rahmen aufheben

###########################################################
#BoxPreferencePage properties

BoxPreferencePage.displayname.Title=Feld
BoxPreferencePage.text.Margin=Rand
BoxPreferencePage.text.Padding=Umrandungsfüllung

###########################################################
#ButtonPaneComposite properties

ButtonPaneComposite.tooltip.MasterPage=Master-Seite
ButtonPaneComposite.tooltip.Normal=Normal
ButtonPaneComposite.tooltip.Ruler=Regler

###########################################################
#SettingsPage properties

SettingsPage.dataFetchSetting.label=Maximale Anzahl der aus Datenquelle abzurufenden Zeilen:
SettingsPage.CachePreference.button.clear=&Cache löschen
SettingsPage.CachePreference.checkBox.text=&Daten aus Datensatz für Berichtvorschau zwischenspeichern
SettingsPage.CachePreference.description=Cache-Größe festlegen:
SettingsPage.CachePreference.Filter.Tooltip=Cache in Datensatz importieren oder daraus exportieren
SettingsPage.CachePreference.label.text=Zeilen verwenden
SettingsPage.CachePreference.messageBox.info=Der Cache wurde gelöscht
SettingsPage.CachePreference.messageBox.title=Cache gelöscht
SettingsPage.CachePreference.radioBox.entireNumText=&Kompletten Datensatz zwischenspeichern
SettingsPage.CachePreference.radioBox.numText=&Zwischenspeichern und zuerst verwenden

###########################################################
#CascadingParametersDialog properties

CascadingParametersDialog.Button.AllowNull=&Nullwert zulassen
CascadingParametersDialog.default.preview.string=Beispielzeichenfolge
CascadingParametersDialog.display.controlType.comboBox=Kombinationsfeld
CascadingParametersDialog.display.controlType.listBox=Listenfeld
CascadingParametersDialog.Label.button.changeFormat=&Ändern...
CascadingParametersDialog.Label.button.createNew.dataset=&Neu erstellen...
CascadingParametersDialog.Label.cascadingParam.name=&Name des Verschachtelungsparameters:
CascadingParametersDialog.Label.column.displayText=Angezeigter Text
CascadingParametersDialog.Label.column.dataSet=Datensatz
CascadingParametersDialog.Label.column.name=Name
CascadingParametersDialog.Label.column.value=Wert
CascadingParametersDialog.Label.createNewParam=<Neuen Parameter erstellen...>
CascadingParametersDialog.Label.dataSets=&Datensatz:
CascadingParametersDialog.Label.dataType=&Datentyp
CascadingParametersDialog.Label.defaultValue=&Standardwert:
CascadingParametersDialog.Label.displayType=&Anzeigetyp:
CascadingParametersDialog.Label.formatAs=Formatieren als:
CascadingParametersDialog.Label.group.general=Allgemein
CascadingParametersDialog.Label.group.moreOptions=Weitere Optionen
CascadingParametersDialog.Label.group.properties=Eigenschaften
CascadingParametersDialog.Label.helpText=&Hilfetext:
CascadingParametersDialog.Label.listLimit=&Listenbegrenzung:
CascadingParametersDialog.Label.NoColumnAvailable=<Keine Spalte verfügbar>
CascadingParametersDialog.Label.param.name=&Name:
CascadingParametersDialog.Label.parameters=Parameter
CascadingParametersDialog.Label.preview=Vorschau mit Format
CascadingParametersDialog.Label.groupPromptText=&Aufforderungstext:
CascadingParametersDialog.Label.parameterPromptText=Auffo&rderungstext:
CascadingParametersDialog.Label.selectDataSet=<Datensatz auswählen>
CascadingParametersDialog.Label.selectDisplayColumn=<Anzeigespalte auswählen>
CascadingParametersDialog.Label.selectValueColumn=<Wertespalte auswählen>
CascadingParametersDialog.Label.values=Werte
CascadingParametersDialog.Label.SelectDataSetMode=Datensatzmodus:
CascadingParametersDialog.Radio.Single=Einfacher Datensatz
CascadingParametersDialog.Radio.Mutli=Mehrfacher Datensatz

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=Eigenschaften

###########################################################
#CellPageGenerator properties

CellPageGenerator.List.Borders=Rahmen
CellPageGenerator.List.CellPadding=Umrandungsfüllung
CellPageGenerator.List.Font=Schriftart
CellPageGenerator.List.General=Allgemein
CellPageGenerator.TabItem.Highlights=Kennzeichnungen
CellPageGenerator.TabItem.map=Zuordnung

###########################################################
#LabelPageGenerator properties
LabelPageGenerator.TabItem.Highlights=Kennzeichnungen


###########################################################
#ChoiceSetFactory properties

ChoiceSetFactory.choice.Auto=Automatisch
ChoiceSetFactory.choice.None=Keine

###########################################################
#CodePageAction properties

CodePageAction.actionText.code=Skript

###########################################################
#ColorBuilder properties

ColorBuilder.text.None=Automatisch

###########################################################
#ColumnPageGenerator properties

ColumnPageGenerator.List.Borders=Rahmen
ColumnPageGenerator.List.CellPadding=Zellfüllung
ColumnPageGenerator.List.Font=Schriftart
ColumnPageGenerator.List.General=Allgemein
ColumnPageGenerator.TabItem.Highlights=Kennzeichnungen
ColumnPageGenerator.TabItem.map=Zuordnung
ColumnPageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#Commom properties

Commom.ShortDateTime.Fri=FR
Commom.ShortDateTime.Mon=MO
Commom.ShortDateTime.Sat=SA
Commom.ShortDateTime.Sun=SO
Commom.ShortDateTime.Thu=DO
Commom.ShortDateTime.Tue=DI
Commom.ShortDateTime.Wed=MI

###########################################################
#Connection Profile Properties
connectionprofile.wizard.title=Neue Datenquelle
connectionprofile.wizard.title.connectionprofileselect=Verbindungsprofil wählen
connectionprofile.wizard.defaultmessage.connectionprofileselect=Wählen Sie das Verbindungsprofil, aus dem eine Datenquelle erstellt werden soll
connectionprofile.wizard.label.connectionprofilestore=Speicher für Verbindungsprofile:
connectionprofile.wizard.label.datasourcename=Datenquellenname:
connectionprofile.wizard.checkbox.datasourcenameusedefaultdsname=Wählen Sie den standardmäßigen Datenquellennamen
connectionprofile.wizard.tree.datasourcename=ODA-Datenquellen
connectionprofile.wizard.button.browse=Durchsuchen ...

###########################################################
#CopyAction properties

CopyAction.text=&Kopieren

###########################################################
#CreatePlaceHolderAction properties

CreatePlaceHolderAction.text=Berichtobjekt für Vorlage &erstellen

###########################################################
#CutAction properties

CutAction.text=A&usschneiden
CutAction.trans=Elemente ausschneiden

###########################################################
#dataBinding properties

dataBinding.label.selectBinding=Datenbindung auswählen:
dataBinding.message.changeDataSet=Sie sind im Begriff, die Datenbindung des Elements zu ändern.\n\nMöchten Sie alle bestehenden Datenfeldinformationen löschen?
dataBinding.title.changeDataSet=Datensatz ändern?
dataBinding.title=Datenbindung

parameterBinding.title=Parameterbindung für Datensatz...



###########################################################
#DataEditPart properties

DataEditPart.Figure.Dafault=Daten
DataEditPart.Figure.Expression=Ausdruck

###########################################################
#DataEditPart properties

DestroyEditPart.Message=Der Inhalt dieses Berichtobjekts ist beschädigt. Wenn Sie weiter mit diesem Bericht arbeiten möchten, sollten Sie zuerst dieses Objekt löschen. Anderenfalls könnte die Berichtdesigndatei beschädigt werden, oder der Report Designer könnte abstürzen.

###########################################################
#DataPageGenerator properties

DataPageGenerator.List.Bookmark=Lesezeichen
DataPageGenerator.List.Borders=Rahmen
DataPageGenerator.List.Duplicates=Duplikate
DataPageGenerator.List.Expression=Ausdruck
DataPageGenerator.List.Format=Format
DataPageGenerator.List.formatDateTime=Format Datum/Uhrzeit
DataPageGenerator.List.formatNumber=Format Zahl
DataPageGenerator.List.formatString=Format Zeichenfolge
DataPageGenerator.List.General=Allgemein
DataPageGenerator.List.Highlights=Kennzeichnungen
DataPageGenerator.List.HyperLink=Hyperlink
DataPageGenerator.List.Margin=Rand
DataPageGenerator.List.Padding=Umrandungsfüllung
DataPageGenerator.List.Section=Seitenumbruch
DataPageGenerator.List.TOC=Inhaltsverzeichnis
DataPageGenerator.List.Visibility=Sichtbarkeit
DataPageGenerator.TabItem.map=Zuordnung

###########################################################
#dataset properties

dataset.edit=Datensatz bearbeiten - {0}

dataset.editor.settings=Einstellungen
dataset.editor.settings.dataFetchSetting.errorNumberFormat=Geben Sie für die maximal abzurufende Zeilenanzahl eine Zahl ein, die größer als Null ist.
dataset.editor.settings.dataFetchSetting=Einstellung für den Abruf von Daten
dataset.editor.settings.cachePreference.errorNumberFormat=Geben Sie für die Zeilengröße des Caches eine Zahl ein, die größer als Null ist.
dataset.editor.settings.cachePreference=Voreinstellungen für Cache
dataset.editor.computedColumns=Berechnete Spalten
dataset.editor.dataSource.Tooltip=Datenquelle anzeigen/ändern
dataset.editor.dataSource=Datenquelle
dataset.editor.error.columnOrAliasNameAlreadyUsed=Der neue Spaltenname oder -alias ({0}) wird bereits von der Spalte bei Index {1} verwendet.
dataset.editor.error.computedColumnNameAlreadyUsed=Der neu berechnete Spaltenname ({0}) wird unter "Ausgabespalten" bereits als Spaltenalias für Spalte ({1}) verwendet.
dataset.editor.error.duplicateParameterName=Parametername doppelt vergeben
dataset.editor.error.emptyName=Der Name darf nicht leer sein. 
dataset.editor.error.missingComputedColumnExpression=Der Ausdruck der berechneten Spalte {0} darf nicht leer oder gleich Null sein.
dataset.editor.error.missingComputedColumnName=Der berechnete Spaltenname darf nicht leer oder gleich Null sein.
dataset.editor.error.noDataSource=Keine Datenquelle verfügbar für den Datensatz {0}; wählen Sie einen Datenquellen-Eintrag in der Eigenschaftenansicht aus.
dataset.editor.error.noEditorsFound=Keinen Editor für Datensatz gefunden {0}.
dataset.editor.error.noInputParameterDefaultValue=Eingabeparameter {0} muss einen Standardwert, der ungleich Null ist, aufweisen.
dataset.editor.error.title=Warnung
dataset.editor.error.unsupportedDataSet=Nicht unterstützter Datensatztyp - {0}.
dataset.editor.error.validationParameter=Für den Eingabeparameter [{0}] liegt kein Wert vor. Soll der Parameter ohne Wert bleiben?
dataset.editor.filters=Filter
dataset.editor.label.selectDataSource=&Datenquelle wählen:
dataset.editor.outputColumns=Ausgabespalten
dataset.editor.parameters=Parameter
dataset.editor.preview=Ergebnisvorschau
dataset.editor.outputparameters=Vorschau der Ausgabeparameter anzeigen
dataset.editor.title.alias=Alias
dataset.editor.title.columnName=Spaltenname
dataset.editor.title.dataType=Datentyp
dataset.editor.title.defaultValue=Standardwert
dataset.editor.title.direction=Richtung
dataset.editor.title.displayName=Angezeigter Name
dataset.editor.title.expression=Ausdruck
dataset.editor.title.helpText=Hilfetext
dataset.editor.title.isInput=Ist Eingabe
dataset.editor.title.isNullable=Nullwert zulässig
dataset.editor.title.isOptional=Optional
dataset.editor.title.isOutput=Ist Ausgabe
dataset.editor.title.name=Name
dataset.editor.title.operator=Operator
dataset.editor.title.type=Typ
dataset.editor.title.value1=Wert 1
dataset.editor.title.value2=Wert 2
dataset.editor.historybar.backward=Zurück
dataset.editor.historybar.forward=Vor
dataset.editor.historybar.to=nach
dataset.error.noDataSources=Es ist keine Datenquelle verfügbar.\nBitte fügen Sie eine Datenquelle hinzu.
dataset.error.dataSourceMissing=Die Datenquelle dieses Datensatzes ist nicht vorhanden.
dataset.error.title.noDataSources=Keine Datenquellen verfügbar.
dataset.message.create=Erstellen Sie einen neuen Datensatz.
dataset.new.defaultName=Datensatz
dataset.new=Neuer Datensatz
dataset.join.new=Neuer Verknüpfungsdatensatz
dataset.resultset.preview.tooltip=Vorschau der Abfrageergebnisse anzeigen
dataset.outputparameters.preview.tooltip=Vorschau der Ausgabeparameter anzeigen
dataset.wizard.label.datasetName=&Datensatzname:
dataset.wizard.label.datasetType=&Datensatztyp:
dataset.wizard.label.dataSource=&Datenquelle:

###########################################################
#DataSetBasePage properties

DataSetBasePage.tooltip=Der Name darf nicht leer sein.

###########################################################
#JointDataSetPage properties

JointDataSetPage.pageName=Verknüpfungsdatensatz
JointDataSetPage.page.detail=Wählen Sie einen Datensatz und eine Spalte von jeder Seite aus, um einen Knotenpunkt zu definieren
JointDataSetPage.button.innerJoin=&Inner Join
JointDataSetPage.button.leftJoin=&Left Outer Join
JointDataSetPage.button.rightJoin=&Right Outer Join
JointDataSetPage.button.fullJoin=&Full Outer Join
JointDataSetPage.joinType=Knotenpunktarten
JointDataSetPage.error.nodataset.title=Kein Datensatz gefunden
JointDataSetPage.error.nodataset.right=Der rechte Datensatz wurde nicht gefunden
JointDataSetPage.error.nodataset.left=Der linke Datensatz wurde nicht gefunden
JointDataSetPage.pageDescription=Verknüpfungsdatensatz definieren
JointDataSetPage.query=Abfrage

###########################################################
#DataSetComputedColumnsPage properties

DataSetComputedColumnsPage.ComputedColumns.Tooltip=Geben Sie die berechneten Spalten an. 
DataSetComputedColumnsPage.description=Berechnete Spalten definieren:
DataSetComputedColumnsPage.duplicatedName=Doppelter Spaltenname
DataSetComputedColumnsPage.toolTipText.Down=Berechnete Spalte nach unten verschieben
DataSetComputedColumnsPage.toolTipText.Up=Berechnete Spalte nach oben verschieben
DataSetComputedColumnsPage.toolTipText.Remove=Berechnete Spalte entfernen
DataSetComputedColumnsPage.toolTipText.New=Neu berechnete Spalte
DataSetComputedColumnsPage.toolTipText.Edit=Berechnete Spalte bearbeiten
DataSetComputedColumnsPage.title.ComputedColumnInputDialog=Berechnete Spalte

###########################################################
#DataSetFiltersPage properties

DataSetFiltersPage.description=Filter definieren:
DataSetFiltersPage.exception.msg.operator.notSupport=Der folgende Operator wird nicht unterstützt: 
DataSetFiltersPage.Filter.Tooltip=Datenzeilen nach BIRT-Ausdrücken filtern.
DataSetFiltersPage.toolTipText.Down=Filter nach unten verschieben
DataSetFiltersPage.toolTipText.Up=Filter nach oben verschieben
DataSetFiltersPage.toolTipText.Remove=Filter entfernen
DataSetFiltersPage.toolTipText.New=Neuer Filter
DataSetFiltersPage.toolTipText.Edit=Filter bearbeiten
DataSetFiltersPage.title.FilterInputDialog=Filter
DataSetFiltersPage.messages.selectVauleUnavailable=Wertliste mit angegebenem Ausdruck nicht verfügbar

###########################################################
#DataSetNodeProvider properties

DataSetNodeProvider.menu.text=Bearbeiten

###########################################################
#DataSetParametersPage properties

DataSetParametersPage.description=Eingabeparameter definieren:
DataSetParametersPage.Filter.Tooltip=Parameter in Datensatz importieren oder daraus exportieren.
DataSetParameterBindingInputDialog.Title=Parameterbindung des Datensatzes bearbeiten
DataSetParametersPage.ErrorTitle.InvalidInput=Ungültige Eingabe
DataSetParameterBindingInputDialog.Label.Name=Parametername:
DataSetParametersPage.ErrorMessage.CanootBeNull=Der Wert darf nicht Null sein.
DataSetParameterBindingInputDialog.Label.DataType=Datentyp:
DataSetParameterBindingInputDialog.Label.Value=Wert:
DataSetParametersPage.Prompt.new=<New param here...>
DataSetParametersPage.default.None=n.a.
DataSetParametersPage.reportParam.None=Ohne
DataSetParameterPage.cell.linkToSalarParameter=Mit Berichtparameter verknüpft
DataSetParameterPage.title.ParameterInputDialog=Parameter
DataSetParameterPage.toolTipText.New=Neuer Parameter
DataSetParameterPage.toolTipText.Edit=Parameter bearbeiten
DataSetParameterPage.toolTipText.Remove=Parameter entfernen
DataSetParameterPage.toolTipText.Up=Parameter nach oben verschieben
DataSetParameterPage.toolTipText.Down=Parameter nach unten verschieben

###########################################################
#PropertyBindingpage properties
PropertyBindingPage.datasource.property.empty=Keine öffentliche Eigenschaft für diese Datenquelle durch die ODA-Erweiterung definiert
PropertyBindingPage.dataset.property.empty=Keine öffentliche Eigenschaft für diesen Datensatz durch die ODA-Erweiterung definiert
PropertyBindingPage.dataset.queryText=&Abfragetext
PropertyBindingPage.property.tooltip=Eigenschaftenbindung für Laufzeit auswählen
PropertyBindingPage.button.tooltip=Ausdruckerstellung zum Eingeben des Werts {0} öffnen

###########################################################
#DataSetProcess properties

DataSetProcess.action.Delete=Datensatz löschen
DataSetProcess.action.Edit=Datensatz bearbeiten
DataSetProcess.action.Preview=Vorschau
DataSetProcess.text.DisplayName=DataSet
DataSetProcess.text.Prefix=Die folgenden Datensätze verwenden diese Datenquelle:
DataSetProcess.text.Show=Blendet die Datensatzeditor-Seite für den Datensatz ein.
DataSetProcess.text.Suffix=Möchten Sie dieses Element wirklich löschen?

###########################################################
#datasource properties

datasource.action.edit=Bearbeiten
datasource.edit=Datenquelle bearbeiten - {0}
datasource.new.defaultName=Datenquelle
datasource.new=Neue Datenquelle
datasource.wizard.label.dataSourceName=&Datenquellenname:
datasource.wizard.label.datasources=Aus einem Datenquellentyp aus der folgenden Liste erstellen
datasource.wizard.label.datasources=Aus einem Datenquellentyp aus der folgenden Liste erstellen
datasource.wizard.label.connectionfile=Aus einem Verbindungsprofil im Profilspeicher erstellen
datasource.wizard.message.selectType=Geben Sie alle Einstellungen für eine neue Datenquelle an, oder wählen Sie ein vordefiniertes Verbindungsprofil.
datasource.wizard.title.select=Wählen Sie einen Datenquellentyp, oder wählen Sie ein Verbindungsprofil.
datasource.editor.property=Eigenschaftenbindung

###########################################################
#DataSourceProcess properties

DataSourceProcess.action.Delete=Datenquelle löschen
DataSourceProcess.action.Edit=Datenquelle bearbeiten
DataSourceProcess.text.DisplayName=DataSource
DataSourceProcess.text.Prefix=Die folgenden Datensätze verwenden diese Datenquelle
DataSourceProcess.text.Show=Blendet die Datensatzeditor-Seite ein  
DataSourceProcess.text.Suffix=Möchten Sie dieses Element wirklich löschen?

###########################################################
#DataSourceSelectionPage properties

DataSourceSelectionPage.ScriptDataSource.DisplayName=Geskriptete Datenquelle

###########################################################
#DataSourcesSlotOutlineProcess properties

DataSourcesSlotOutlineProcess.action.New=Neue Datenquelle

###########################################################
#datatypes properties

datatypes.any=Beliebig
datatypes.auto=Automatisch
datatypes.dateTime=Datum/Uhrzeit
datatypes.decimal=Dezimal
datatypes.float=Gleitkomma
datatypes.integer=Ganzzahl
datatypes.string=Zeichenfolge

###########################################################
#DataView properties

DataView.defaultText.noDataView=Keine Datenansicht verfügbar.

###########################################################
#DataViewTreeViewerPage properties

DataViewTreeViewerPage.tooltip.DoubleClickToEdit=Zum Bearbeiten doppelklicken
DataViewTreeViewerPage.tooltip.DragToInsertColumn=Spalte durch Ziehen einfügen 
DataViewTreeViewerPage.tooltip.DragToInsertDataSetColumns=Sämtliche Datensatzspalten durch Ziehen einfügen 
DataViewTreeViewerPage.tooltip.DragToInsertParameter=Berichtparameter durch Ziehen einfügen; 

###########################################################
#DebugUtil properties

DebugUtil.importProject.fail="Import des vorhandenen Projekts fehlgeschlagen."

###########################################################
#DecorationFieldEditor properties

DecorationFieldEditor.text.Linethrough=Durchgestrichen
DecorationFieldEditor.text.Overline=Überstrichen
DecorationFieldEditor.text.Underline=Unterstreichen

###########################################################
#DefaultNodeProvider properties

DefaultNodeProvider.Dlg.Confirm=Möchten Sie das Element wirklich löschen?
DefaultNodeProvider.ParameterGroup.ConfirmMessage=Sie sind im Begriff, eine Parametergruppe zu löschen. Wenn Sie diese Parametergruppe löschen, werden alle Parameter innerhalb der Gruppe gelöscht. Möchten Sie fortfahren?
DefaultNodeProvider.ParameterGroup.ConfirmTitle=Löschen der Parametergruppe bestätigen
DefaultNodeProvider.Tree.Body=Hauptteil
DefaultNodeProvider.Tree.Clients=\\ hat folgende Clients
DefaultNodeProvider.Tree.ColumnHedings=Spaltenüberschriften
DefaultNodeProvider.Tree.Components = Berichtobjekte
DefaultNodeProvider.Tree.DataSets=Datensätze
DefaultNodeProvider.Tree.DataSources=Datenquellen
DefaultNodeProvider.Tree.Detail=Detail
DefaultNodeProvider.Tree.Footer=Fußzeile
DefaultNodeProvider.Tree.Groups=Gruppen
DefaultNodeProvider.Tree.Header=Kopfzeile
DefaultNodeProvider.Tree.Images=Eingebettete Bilder
DefaultNodeProvider.Tree.Invalid=Ungültiger Knoten
DefaultNodeProvider.Tree.MasterPages=Master-Seiten
DefaultNodeProvider.Tree.PageSetup=Seite einrichten
DefaultNodeProvider.Tree.Parameters=Berichtparameter
DefaultNodeProvider.Tree.Reference=Verweis gefunden
DefaultNodeProvider.Tree.Scratch=Skizzenblock
DefaultNodeProvider.Tree.Styles=Stile
DefaultNodeProvider.Tree.Themes=Themen
DefaultNodeProvider.WarningDialog.Title=Warnung
DefaultNodeProvider.WarningDialog.EmptyList=Kein Element zum Einfügen verfügbar.

###########################################################
#DeleteAction properties

DeleteAction.text=&Löschen
DeleteAction.trans=Elemente löschen

###########################################################
#DeleteColumnAction properties

DeleteColumnAction.actionMsg.delete=&Löschen

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.actionMsg.deleteGroup=&Gruppe löschen

###########################################################
#DeleteListGroupAction properties

DeleteListGroupAction.actionMsg.deleteGroup=&Gruppe löschen

###########################################################
#DeleteRowAction properties

DeleteRowAction.actionMsg.delete=&Löschen

###########################################################
#designer properties

designer.preview.browserTitle=Vorschau
designer.preview.preference.browser.autoSave=Automatisch vor Vorschau speichern
designer.preview.preference.browser.browse=&Durchsuchen...
designer.preview.preference.browser.currentBrowsers=&Aktuelle Adapter für externe Webbrowser:
designer.preview.preference.browser.description=Mit dieser Auswahl werden die für die Vorschau von BIRT-Berichten verwendeten Webbrowser festgelegt.\nWurde nur ein Browser-Adapter konfiguriert, kann die Auswahl nicht\ngeändert werden.
designer.preview.preference.browser.details=Browser-Programm auswählen
designer.preview.preference.browser.program=&Benutzerdefinierter Browser-Befehl:
designer.preview.preference.browser.svg=&SVG-Diagramm aktivieren
designer.preview.preference.masterpagecontent=&Inhalt der Master-Seite aktivieren
designer.preview.preference.browser.useExternal=&Immer externe Browser verwenden
designer.preview.preference.elementname.columnwidth=125
designer.preview.preference.elementname.customname.Enabled=true
designer.preview.preference.elementname.customname=Standardname
designer.preview.preference.elementname.defaultname.Enabled=false    
designer.preview.preference.elementname.defaultname=Elementname
designer.preview.preference.elementname.description.Enabled=false
designer.preview.preference.elementname.description=Beschreibung
designer.preview.preference.elementname.Enabled=true 
designer.preview.preference.locale.description=&Gebietsschema auswählen:
designer.preview.preference.resultset.sqldatasetpage.group.title=Abfrageseite
designer.preview.preference.resultset.previewpage.group.title=Vorschauseite
designer.preview.preference.resultset.maxNoOfSchema.description=&Maximale Anzahl anzuzeigender Schemata:
designer.preview.preference.resultset.maxNoOfTable.description=&Maximale Anzahl von Tabellen in den anzuzeigenden Schemata:
designer.preview.preference.resultset.maxNoOfSchema.errormessage=Geben Sie eine Zahl zwischen 0 und {0} an, um die maximale Anzahl an Schemata zu definieren.
designer.preview.preference.resultset.maxNoOfTable.errormessage=Geben Sie eine Zahl zwischen 0 und {0} an, um die maximale Anzahl von Tabellen in den Schemata zu definieren.
designer.preview.preference.resultset.maxrow.description=&Maximale Anzahl anzuzeigender Zeilen:
designer.preview.preference.resultset.maxrow.errormessage=Geben Sie für die maximale Zeilenanzahl eine Zahl zwischen 1 und {0} ein.
designer.preview.preference.server.description=Konfiguration des internen Anwendungsservers. Der Server wird intern vom\nBIRT Report Designer Preview Framework verwendet.
designer.preview.preference.server.hostDescription=&Host-Name oder IP-Adresse des lokalen Rechners. Leer lassen, damit eine automatische\nFestlegung erfolgt.
designer.preview.preference.server.note=Hinweis:
designer.preview.preference.server.portDescription=&Anschluss für die Serververbindung. Auf 0 stellen, da Zuordnung dynamisch.
designer.preview.preference.server.requireRestart=Wird der Server bereits ausgeführt, werden diese Einstellungen erst\nnach dem Neustart übernommen.
designer.preview.previewaction.label.webviewer=Bericht in Web Viewer anzeigen
designer.preview.previewaction.label=Bericht als {0} anzeigen
designer.preview.previewaction.ErrorMessage=Die PDF-Erzeugung ist nicht aktiviert, da iText weder installiert ist noch gefunden wurde.
designer.preview.previewaction.ErrorMessage.title=Warnung

###########################################################
#DesignerActionBarContributor properties

DesignerActionBarContributor.element.group=&Gruppe einfügen
DesignerActionBarContributor.element.InsertColumnLeft=Spalten &links einfügen
DesignerActionBarContributor.element.InsertColumnRight=Spalten &rechts einfügen
DesignerActionBarContributor.element.InsertRowAbove=Zeile &oben einfügen
DesignerActionBarContributor.element.InsertRowBelow=Zeile &unten einfügen
DesignerActionBarContributor.element.merge=Zellen &verbinden
DesignerActionBarContributor.element.split=Zelle &teilen
designerActionBarContributor.menu.data-newdataset=Neuer D&atensatz
designerActionBarContributor.menu.data-newdatasource=Neue Dat&enquelle
DesignerActionBarContributor.menu.data=&Daten
DesignerActionBarContributor.menu.element-EditGroup=Gruppe b&earbeiten
DesignerActionBarContributor.menu.element-LayoutMode=Layout-Mo&dus
DesignerActionBarContributor.menu.element-showRuler=&Regeln anzeigen 
DesignerActionBarContributor.menu.element.editDataBinding=Datenbindung &bearbeiten
DesignerActionBarContributor.menu.element=Ele&ment
DesignerActionBarContributor.menu.format=Format
DesignerActionBarContributor.menu.insert=E&infügen
DesignerActionBarContributor.menu.page=Sei&te
DesignerActionBarContributor.menu.style-rule-apply=Stil an&wenden
DesignerActionBarContributor.menu.style-rule-edit=Stil bea&rbeiten
DesignerActionBarContributor.style.new=&Neuer Stil...
DesignerActionBarContributor.menu.data-NewParameter=Neuer Bericht&parameter

###########################################################
#DesignerOutlinePage properties

DesignerOutlinePage.action.Delete=Auswahlen löschen
DesignerOutlinePage.action.Hide=Kopf- und Fußzeile ausblenden
DesignerOutlinePage.action.Redo=Wiederherstellen
DesignerOutlinePage.action.Undo=Rückgängig
DesignerOutlinePage.menu.Filters=Filter

###########################################################
#Content outline page switch action
ContentOutlinePage.action.text.reportOutline=Zu XML-Quellgliederung wechseln
ContentOutlinePage.action.text.reportXMLSourceOutline=Zu Berichtsgliederung wechseln

###########################################################
#DesignerPaletteFactory properties

DesignerPaletteFactory.categoryName.reportItems=Berichtobjekte
DesignerPaletteFactory.elementLabel.data=Daten
DesignerPaletteFactory.elementLabel.grid=Raster
DesignerPaletteFactory.elementLabel.image=Bild
DesignerPaletteFactory.elementLabel.label=Beschriftung
DesignerPaletteFactory.elementLabel.list=Liste
DesignerPaletteFactory.elementLabel.tabel=Tabelle
DesignerPaletteFactory.elementLabel.text=Text
DesignerPaletteFactory.elementName.data=Daten
DesignerPaletteFactory.elementName.grid=Raster
DesignerPaletteFactory.elementName.image=Bild
DesignerPaletteFactory.elementName.label=Beschriftung
DesignerPaletteFactory.elementName.list=Liste
DesignerPaletteFactory.elementName.table=Tabelle
DesignerPaletteFactory.elementName.text=Text
DesignerPaletteFactory.elementName.textdata=Dynamischer Text
DesignerPaletteFactory.toolTip.dataReportItem=Fügen Sie eine Datensatzspalte oder ein Ausdruckergebnis ein.
DesignerPaletteFactory.toolTip.gridReportItem=Fügen Sie ein Zeilen- oder Spalten-Layout ein, um andere Elemente sichtbar anzuordnen.
DesignerPaletteFactory.toolTip.imageReportItem=Fügen Sie ein Bild aus einer Datei oder von einer URL-Adresse ein.
DesignerPaletteFactory.toolTip.labelReportItem=Fügen Sie einen Teil eines statischen Textes ein. 
DesignerPaletteFactory.toolTip.listReportItem=Darstellung von Datensatzzeilen mit flexiblem Format in Kopfzeilen-, Detail- oder Fußzeilenbänder einfügen
DesignerPaletteFactory.toolTip.multiLineDataReportItem=Textblock (einfacher Text, HTML oder RTF) aus einer Datei, einer Datensatzspalte oder einem Ausdruckergebnis einfügen.
DesignerPaletteFactory.toolTip.tableReportItem=Darstellung von Datensatzzeilen mit Spalten in Kopfzeilen-, Detail- oder Fußzeilenbänder einfügen
DesignerPaletteFactory.toolTip.textDataReportItem=Textblock mit optionalen CLOB-Ausdrücken einfügen
DesignerPaletteFactory.toolTip.textReportItem=Fügen Sie einen Textblock (einfacher Text oder HTML) mit optionalen Inline-Ausdrücken ein.

###########################################################
#DimensionBuilderDialog properties

DimensionBuilderDialog.LabelMeasure=Maßeinheit:
DimensionBuilderDialog.LabelUnit=Einheiten:
DimensionBuilderDialog.Title=Dimension Builder

###########################################################
#DNDUtil properties

DNDUtil.trans.copy=Elemente kopieren
DNDUtil.trans.cut=Elemente verschieben

###########################################################
#DuplicatesPage properties

DuplicatesPage.Check.HideDuplicates=Elemente duplizieren
DuplicatesPage.Group.Repeat=Duplikation (Wiederholen)
DuplicatesPage.Group.RepeatonPage=Duplikation (Auf Seite wiederholen)
DuplicatesPage.Label.RepeatInfo=Werte, die identisch mit denen der vorigen Datenzeile sind, ausblenden.
DuplicatesPage.Label.RepeatOnPage.1=Werte, die identisch mit denen der vorigen Zeile sind, ausblenden,
DuplicatesPage.Label.RepeatOnPage.2=\\ aber den Wert am oberen Rand jeder neuen Seite einblenden.
DuplicatesPage.Label.ResetonGroup=Bei folgender Gruppe zurücksetzen
DuplicatesPage.Radio.Repeat=Wiederholen
DuplicatesPage.Radio.RepeatonPage=Auf Seite wiederholen

###########################################################
#EditAction properties

EditAction.text=Bearbeiten

###########################################################
#EditGroupAction properties

EditGroupAction.stackMsg.editGroup=Gruppe bearbeiten

###########################################################
#EditGroupAction properties
InsertGroupHeaderFooterAction.stackMsg.editGroup=Gruppenkopfzeile/-fußzeile einfügen
InsertGroupHeaderFooterAction.Text.Header=Kopfzeile
InsertGroupHeaderFooterAction.Text.Footer=Fuß.zeile

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.stackMsg.deleteGroup=Gruppe löschen

###########################################################
#EditLabelAction properties

EditLabelAction.text=Bearbeiten

###########################################################
#Element properties

Element.Cell.colSpan=Spaltenbereich:
Element.Cell.column=Spalte:
Element.Cell.drop=&Verwerfen:
Element.Cell.height=Höhe:
Element.Cell.rowSpan=Zeilenbereich:
Element.Cell.slot.content=Inhalt:
Element.Cell.verticalAlign=Vertikale Ausrichtung:
Element.Cell.width=Breite:
Element.Column.alignment=Ausrichtung:
Element.Column.repeat=Wiederholen:
Element.Column.width=&Breite:
Element.Column.suppressDuplicates=Duplikate ausblenden
Element.Container.slot.reportItems=Berichtobjekte:
Element.Data.action=Aktion:
Element.Data.helpText=Hilfetext:
Element.Data.helpTextID=Hilfetextschlüssel
Element.TextData.valueExpr=&Wertausdruck:
Element.DataSet.afterClose.toolTip=Wird direkt nach dem Schließen des Datensatzes aufgerufen.
Element.DataSet.afterClose=Nach dem Schließen:
Element.DataSet.afterOpen.toolTip=Wird direkt nach dem Öffnen des Datensatzes aufgerufen.
Element.DataSet.afterOpen=Nach dem Öffnen:
Element.DataSet.beforeClose.toolTip=Wird direkt vor dem Schließen des Datensatzes aufgerufen.
Element.DataSet.beforeClose=Vor dem Schließen:
Element.DataSet.beforeOpen.toolTip=Wird direkt vor dem Öffnen des Datensatzes aufgerufen.
Element.DataSet.beforeOpen=Vor dem Öffnen:
Element.DataSet.cachedMetaData=Zwischengespeicherte Metadaten:
Element.DataSet.columnHints=Spaltenhinweise:
Element.DataSet.computedColumns=Berechnete Spalten:
Element.DataSet.dataSource=Datenquelle:
Element.DataSet.filter=Filter:
Element.DataSet.inputParameters=Eingabeparameter:
Element.DataSet.onFetch.toolTip=Wird direkt vor dem Abrufen einer Datenzeile aus dem Datensatz aufgerufen.
Element.DataSet.onFetch=Beim Abrufen:
Element.DataSet.outputParameters=Ausgabeparameter:
Element.DataSet.paramBindings=Parameterbindungen:
Element.DataSet.resultSet=Ergebnis:
Element.DataSource.afterClose.toolTip=Wird direkt nach dem Schließen der Datenquelle aufgerufen.
Element.DataSource.afterClose=Nach dem Schließen:
Element.DataSource.afterOpen.toolTip=Wird direkt nach dem Öffnen der Datenquelle aufgerufen.
Element.DataSource.afterOpen=Nach dem Öffnen:
Element.DataSource.beforeClose.toolTip=Wird direkt vor dem Schließen der Datenquelle aufgerufen.
Element.DataSource.beforeClose=Vor dem Schließen:
Element.DataSource.beforeOpen.toolTip=Wird direkt vor dem Öffnen der Datenquelle aufgerufen.
Element.DataSource.beforeOpen=Vor dem Öffnen:
Element.ExtendedItem.extension=Name der Erweiterung:
Element.ExtendedItem.extensionName=Name der Erweiterung:
Element.FreeForm.slot.reportItems=Berichtobjekte:
Element.GraphicMasterPage.columns=Spalten:
Element.GraphicMasterPage.columnSpacing=Spaltenabstand:
Element.GraphicMasterPage.slot.contents=Inhalt:
Element.Grid.slot.columns=Spalten:
Element.Grid.slot.row=Zeile:
Element.Image.action=Aktion:
Element.Image.altText=&Alternativer Text:
Element.Image.altTextID=Alternativtextschlüssel:
Element.Image.helpText=Hilfetext:
Element.Image.helpTextID=Hilfetextschlüssel
Element.Image.imageName=Bildname:
Element.Image.scale=Skalieren:
Element.Image.size=Größe:
Element.Image.source=Quelle:
Element.Image.typeExpr=Typausdruck:
Element.Image.uri=URI:
Element.Image.valueExpr=Wertausdruck:
Element.JdbcDataSource.dataSource=Datenquelle:
Element.JdbcDataSource.driver=Treiber:
Element.JdbcDataSource.password=Kennwort:
Element.JdbcDataSource.url=URL:
Element.JdbcDataSource.userName=Benutzername:
Element.JdbcSelectDataSet.getStatement.toolTip=Gibt eine benutzerdefinierte SQL-Anweisung für die Abfrage zurück.
Element.JdbcSelectDataSet.getStatement=Anweisung abrufen:
Element.JdbcSelectDataSet.statement=Anweisung:
Element.Label.action=Aktion:
Element.Label.helpText=Hilfetext:
Element.Label.helpTextID=Hilfetextschlüssel
Element.Label.text=Text:
Element.Label.textID=&Textschlüssel:
Element.Line.orientation=Seitenausrichtung:
Element.List.slot.columnHeader=Spaltenüberschrift:
Element.List.slot.detail=Detail:
Element.List.slot.footer=Fußzeile:
Element.List.slot.group=Gruppe:
Element.List.slot.header=Kopfzeile:
Element.ListGroup.slot.footer=Fußzeile:
Element.ListGroup.slot.header=Kopfzeile:
Element.Listing.filter=Filter:
Element.Listing.onFinish.toolTip=Wird aufgerufen, sobald die letzte Zeile aus dem Datensatz für dieses Element abgerufen wurde, jedoch bevor das Fußzeilenband erstellt wird.
Element.Listing.onFinish=Beim Beenden:
Element.Listing.onRow.toolTip=Wird für jede Zeile aufgerufen, die aus dem Datensatz für dieses Element abgerufen wird, jedoch bevor Inhalt für diese Zeile erstellt wird.
Element.Listing.onRow=Bei Zeile:
Element.Listing.onStart.toolTip=Wird aufgerufen, sobald der Datensatz geöffnet wurde, jedoch bevor das Kopfzeilenband erstellt wird und zwar noch bevor die erste Zeile aus dem Datensatz für dieses Element abgerufen wurde. 
Element.Listing.onStart=Beim Starten:
Element.Listing.pageBreakInterval=&Intervall für Seitenumbruch:
Element.Listing.sorting=Sortierung:
Element.ListingGroup.filter=Filter:
Element.ListingGroup.groupName=Name
Element.ListingGroup.interval=Intervall:
Element.ListingGroup.intervalRange=Intervallbereich:
Element.ListingGroup.keyExpr=Schlüsselausdruck
Element.ListingGroup.onFinish.toolTip=Wird aufgerufen, sobald die letzte Zeile aus dem Datensatz für dieses Element abgerufen wurde, jedoch bevor das Fußzeilenband erstellt wird.
Element.ListingGroup.onFinish=Beim Beenden:
Element.ListingGroup.onRow.toolTip=Wird für jede Zeile aufgerufen, die aus dem Datensatz für dieses Element abgerufen wird, jedoch bevor Inhalt für die Zeile erstellt wird.
Element.ListingGroup.onRow=Bei Zeile:
Element.ListingGroup.onStart.toolTip=Wird aufgerufen, sobald der Datensatz geöffnet wurde, jedoch bevor das Kopfzeilenband erstellt wird und zwar noch bevor die erste Zeile aus dem Datensatz für dieses Element abgerufen wurde.
Element.ListingGroup.onStart=Beim Starten:
Element.ListingGroup.pageBreakAfter=Seitenumbruch nach:
Element.ListingGroup.pageBreakBefore=Seitenumbruch vor:
Element.ListingGroup.sort=Sortieren:
Element.ListingGroup.sortDirection=Sortierreihenfolge:
Element.ListingGroup.toc=Inhaltsverzeichnis:
Element.MasterPage.bottomMargin=Unterer Rand:
Element.MasterPage.columns=Spalten:
Element.MasterPage.columnSpacing=Spaltenabstand:
Element.MasterPage.height=Höh&e:
Element.MasterPage.leftMargin=Linker Rand:
Element.MasterPage.margin=Rand:
Element.MasterPage.orientation=&Seitenausrichtung:
Element.MasterPage.rightMargin=Rechter Rand:
Element.MasterPage.slot.contents=Inhalt:
Element.MasterPage.topMargin=Oberer Rand:
Element.MasterPage.type=&Typ:
Element.MasterPage.width=&Breite:
Element.Module.author=&Verfasser:
Element.Module.base=Basis:
Element.Module.colorPalette=Farbpalette:
Element.Module.comments=&Kommentare:
Element.Module.configVars=Konfigurationsvariablen:
Element.Module.createdBy=&Erstellt von:
Element.Module.description=&Beschreibung:
Element.Module.descriptionID=Beschreibungsschlüssel:
Element.Module.helpGuide=Hilfe-Handbuch:
Element.Module.images=Bilder:
Element.Module.includeLibraries=Bibliotheken einschließen:
Element.Module.includeResource=&Ressourcendatei:
Element.Module.includeScripts=Skripte einschließen:
Element.Module.initialize.toolTip=Wird zu Beginn der Berichtausführung aufgerufen.
Element.Module.initialize=Initialisieren:
Element.Module.theme=The&men
Element.Module.title=&Titel:
Element.Module.titleID=Titelschlüssel:
Element.Module.units=&Einheiten:
Element.MultiLineData.contentTypeExpr=Inhaltstypausdruck:
Element.MultiLineData.valueExpr=Wertausdruck:
Element.OdaDataSet.privateDriverDesignState=Designzustand des privaten Treibers:
Element.OdaDataSet.privateDriverProperties=Eigenschaften des privaten Treibers:
Element.OdaDataSet.publicDriverProperties=Eigenschaften des öffentlichen Treibers:
Element.OdaDataSet.queryScript.toolTip=TBD:
Element.OdaDataSet.queryScript=Skript:
Element.OdaDataSet.queryText=Abfrage:
Element.OdaDataSet.resultSetName=Name des Ergebnisses:
Element.OdaDataSet.type=Typ:
Element.OdaDataSource.driverName=Treibername:
Element.OdaDataSource.privateDriverProperties=Eigenschaften des privaten Treibers:
Element.OdaDataSource.publicDriverProperties=Eigenschaften des öffentlichen Treibers:
Element.Parameter.helpText=Hilfetext:
Element.Parameter.helpTextID=Hilfetextschlüssel
Element.Parameter.hidden=Verborgen:
Element.ParameterGroup.helpText=Hilfetext:
Element.ParameterGroup.helpTextID=Hilfetextschlüssel
Element.ParameterGroup.slot.parameters=Parameter:
Element.ParameterGroup.startExpanded=Erweiterte starten:
Element.ReportDesign.afterCloseDoc.toolTip=Wird direkt nach dem Schließen des Berichtdokuments in der Erstellungsphase aufgerufen.
Element.ReportDesign.afterCloseDoc=Nach dem Schließen des Dokuments:
Element.ReportDesign.afterFactory.toolTip=Wird am Ende der Erstellungsphase nach dem Schließen des Berichtdokuments (falls vorhanden) aufgerufen. Dies ist die letzte in der Erstellungsphase aufgerufene Methode.
Element.ReportDesign.afterFactory=Nach Factory:
Element.ReportDesign.afterOpenDoc.toolTip=Wird direkt nach dem Öffnen des Berichtdokuments in der Erstellungsphase aufgerufen.
Element.ReportDesign.afterOpenDoc=Nach dem Öffnen des Dokuments:
Element.ReportDesign.afterRender.toolTip=Wird nach dem Starten einer Aktion während der Präsentation aufgerufen.
Element.ReportDesign.afterRender=Nach dem Rendern:
Element.ReportDesign.beforeCloseDoc.toolTip=Wird direkt vor dem Schließen des Berichtdokuments in der Erstellungsphase aufgerufen.
Element.ReportDesign.beforeCloseDoc=Vor dem Schließen des Dokuments:
Element.ReportDesign.beforeFactory.toolTip=Wird zu Beginn der Erstellungsphase nach der Methode "initialize( )" und vor dem Öffnen des Berichtdokuments (falls vorhanden) aufgerufen.
Element.ReportDesign.beforeFactory=Vor Factory:
Element.ReportDesign.beforeOpenDoc.toolTip=Wird direkt vor dem Öffnen des Berichtdokuments in der Erstellungsphase aufgerufen.
Element.ReportDesign.beforeOpenDoc=Vor dem Öffnen des Dokuments:
Element.ReportDesign.beforeRender.toolTip=Wird vor dem Starten einer Aktion während der Präsentation aufgerufen.
Element.ReportDesign.beforeRender=Vor dem Rendern:
Element.ReportDesign.displayName=&Anzeigename: 
Element.ReportDesign.eventHandlerClass=E&reignis-Handler-Klasse:
Element.ReportDesign.iconFile=&Vorschaubild: 
Element.ReportDesign.refreshRate=Aktualisierungsrate:
Element.ReportElement.comments=&Kommentare:
Element.ReportElement.customXml=Benutzerdefinierte XML:
Element.ReportElement.displayName=Anzeigename:
Element.ReportElement.displayNameID=Anzeigenamenschlüssel:
Element.ReportElement.extends=Erweitert:
Element.ReportElement.javaClass=Java-Klasse:
Element.ReportElement.name=&Name:
Element.ReportElement.propertyMask=Eigenschaftsmaske:
Element.ReportElement.style=&Stil:
Element.ReportItem.bookmark=&Lesezeichen:
Element.ReportItem.dataSet=Datensatz:
Element.ReportItem.height=&Höhe:
Element.ReportItem.onCreate.toolTip=Wird ausgeführt, wenn das Element in der Erstellungsphase erstellt wird.
Element.ReportItem.onCreate=Beim Erstellen:
Element.ReportItem.onRender.toolTip=Wird ausgeführt, wenn das Element in der Präsentationsphase zum Rendern vorbereitet wird.
Element.ReportItem.onRender=Beim Rendern:  
Element.ReportItem.paramBindings=Parameterbindungen:
Element.ReportItem.toc=&Inhaltsverzeichnis:
Element.ReportItem.visibility=Sichtbarkeit:
Element.ReportItem.width=&Breite:
Element.ReportItem.x=X:
Element.ReportItem.y=Y:
Element.Row.bookmark=Lesezeichen:
Element.Row.height=&Höhe:
Element.Row.slot.cell=Zelle:
Element.Row.visibility=Sichtbarkeit:
Element.ScalarParameter.alignment=Ausrichtung:
Element.ScalarParameter.allowBlank=Leerwert zulässig:
Element.ScalarParameter.allowNull=Nullwert zulässig:
Element.ScalarParameter.concealValue=Wert verbergen:
Element.ScalarParameter.controlType=&Steuerelementtyp:
Element.ScalarParameter.dataType=&Datentyp:
Element.ScalarParameter.defaultValue=Standardwert:
Element.ScalarParameter.dynamicList.dataSetName=Name des Datensatzes:
Element.ScalarParameter.dynamicList.labelExpr=Beschriftungsausdruck:
Element.ScalarParameter.dynamicList.valueExpr=Wertausdruck:
Element.ScalarParameter.dynamicList=Dynamische Liste:
Element.ScalarParameter.format=Format:
Element.ScalarParameter.selectionList.fixedOrder=Feste Reihenfolge:
Element.ScalarParameter.selectionList.mustMatch=Muss übereinstimmen mit:
Element.ScalarParameter.selectionList.selectionList=Auswahlliste:
Element.ScalarParameter.selectionList=Auswahlliste:
Element.ScalarParameter.promptTextID=&Textschlüssel:
Element.ScriptDataSet.close.toolTip=Schließt den Datensatz.
Element.ScriptDataSet.close=Schließen:
Element.ScriptDataSet.describe.toolTip=Beschreibt das Ergebnis.
Element.ScriptDataSet.describe=Beschreiben:
Element.ScriptDataSet.fetch.toolTip=Erstellt ein Objekt vom Typ "DataRow", füllt dieses Objekt und gibt es zurück. 
Element.ScriptDataSet.fetch=Abrufen:
Element.ScriptDataSet.open.toolTip=Öffnet den Datensatz.
Element.ScriptDataSet.open=Öffnen:
Element.ScriptDataSource.close.toolTip=Beendet die Verbindung zur Datenquelle. 
Element.ScriptDataSource.close=Schließen:
Element.ScriptDataSource.open.toolTip=Baut eine Verbindung zur Datenquelle auf. 
Element.ScriptDataSource.open=Öffnen:
Element.SimpleMasterPage.floatingFooter=Unverankerte &Fußzeile
Element.SimpleMasterPage.footerHeight=Höhe der &Fußzeile:
Element.SimpleMasterPage.headerHeight=&Höhe der Kopfzeile:
Element.SimpleMasterPage.showFooterOnLast=Fußzeile auf letzter &Seite anzeigen
Element.SimpleMasterPage.showHeaderOnFirst=&Kopfzeile auf erster Seite anzeigen
Element.SimpleMasterPage.slot.pageFooter=Seitenfußzeile:
Element.SimpleMasterPage.slot.pageHeader=Seitenkopfzeile:
Element.Style.background.attachment=&Anlage:
Element.Style.background.color=&Hintergrundfarbe:
Element.Style.background.image=&Hintergrundbild:
Element.Style.background.positionX=&Horizontale Position:
Element.Style.background.positionY=&Vertikale Position:
Element.Style.background.repeat=&Wiederholen:
Element.Style.background=Hintergrund:
Element.Style.border.bottom.color=&Unten:
Element.Style.border.bottom.style=&Unten:
Element.Style.border.bottom.width=Unten:
Element.Style.border.fillColor=Rahmenfüllfarbe:
Element.Style.border.hmiddle.color=Farbe für horizontalen mittleren Rahmen:
Element.Style.border.hmiddle.style=Stil für horizontalen mittleren Rahmen:
Element.Style.border.hmiddle.width=Breite für horizontalen mittleren Rahmen:
Element.Style.border.left.color=Li&nks:
Element.Style.border.left.style=&Links:
Element.Style.border.left.width=&Links:
Element.Style.border.right.color=&Rechts:
Element.Style.border.right.style=&Rechts:
Element.Style.border.right.width=&Rechts:
Element.Style.border.top.color=&Oben:
Element.Style.border.top.style=&Oben:
Element.Style.border.top.width=&Oben:
Element.Style.border.vmiddle.color=Farbe für vertikalen mittleren Rahmen:
Element.Style.border.vmiddle.style=Stil für vertikalen mittleren Rahmen:
Element.Style.border.vmiddle.width=Breite für vertikalen mittleren Rahmen:
Element.Style.border=Rahmen:
Element.Style.box=Feld:
Element.Style.canShrink=&Verkleinerbar
Element.Style.color=&Farbe:
Element.Style.display=&Anzeige:
Element.Style.font.family=&Schriftart:
Element.Style.font.size=&Größe:
Element.Style.font.style=&Stil:
Element.Style.font.textLineThrough=&Durchgestrichen
Element.Style.font.textOverline=&Überstrichen
Element.Style.font.textUnderline=&Unterstrichen
Element.Style.font.variant=Schriftartvariante:
Element.Style.font.weight=&Schriftbreite:
Element.Style.font=&Schriftart:
Element.Style.format.dateTime=Datum/Uhrzeit:
Element.Style.format.number.align=Zahlenformat ausrichten:
Element.Style.format.number=Nummer:
Element.Style.format.string=Zeichenfolge:
Element.Style.format=Format:
Element.Style.highlight.rules=Regeln hervorheben:
Element.Style.highlight.testExpr=Testausdruck hervorheben:
Element.Style.letterSpacing=&Zeichenabstand:
Element.Style.lineHeight=&Zeilenhöhe:
Element.Style.map.rules=Regeln zuordnen:
Element.Style.map.testExpr=Testausdruck zuordnen:
Element.Style.margin.bottom=&Unten:
Element.Style.margin.left=&Links:
Element.Style.margin.right=&Rechts:
Element.Style.margin.top=&Oben:
Element.Style.masterPage=&Masterseite:
Element.Style.orphans=&Verwaist:
Element.Style.padding.bottom=&Unten:
Element.Style.padding.left=&Links:
Element.Style.padding.right=&Rechts:
Element.Style.padding.top=&Oben:
Element.Style.padding=Umrandungsfüllung:
Element.Style.pageBreakAfter=&Nachher:
Element.Style.pageBreakBefore=&Vorher:
Element.Style.pageBreakInside=&Innen:
Element.Style.section=Abschnitt:
Element.Style.showIfBlank=&Anzeigen, wenn leer
Element.Style.text.align=Te&xtausrichtung:
Element.Style.text.indent=&Texteinzug:
Element.Style.text.transform=Text&umwandlung:
Element.Style.text=Text:
Element.Style.verticalAlign=&Vertikale Ausrichtung:
Element.Style.whiteSpace=&Leerzeichen:
Element.Style.widows=&Verwitwet:
Element.Style.wordSpacing=&Wortabstand:
Element.Table.caption=Beschriftung:
Element.Table.captionID=Beschriftungsschlüssel:
Element.Table.repeatHeader=Kopfzeile wiederholen:
Element.Table.slot.columnHeader=Spaltenüberschrift:
Element.Table.slot.columns=Spalten:
Element.Table.slot.detail=Detail:
Element.Table.slot.footer=Fußzeile:
Element.Table.slot.group=Gruppe:
Element.Table.slot.header=Kopfzeile:
Element.TableGroup.slot.footer=Fußzeile:
Element.TableGroup.slot.header=Kopfzeile:
Element.Text.content=Inhalt:
Element.Text.contentID=&Inhaltsschlüssel:
Element.Text.contentType=&Inhaltstyp:
Element.TemplateElement.name=&Name
Element.Toc.Sytle=&Stil

###########################################################
#EmbeddedImageNodeProvider properties

EmbeddedImageNodeProvider.action.New=Neues eingebettetes Bild

###########################################################
#EmbeddedImagesNodeProvider properties

EmbeddedImagesNodeProvider.action.New=Neues eingebettetes Bild

###########################################################
#EmptyEditPart properties

EmptyEditPart.Msg.EmptyLib=Es befinden sich keine visuellen Elemente in der Bibliothek. Fügen Sie der Bibliothek visuelle Elemente hinzu, indem Sie das Element von der Palette in die Gliederungsansicht der Bibliothek ziehen oder das Menü "Einfügen" der Gliederungsansicht verwenden.
EmptyEditPart.Msg.NonVisual=Es wurde ein nicht-visuelles Element gewählt.

###########################################################
#error properties

error.duplicateName=Der neue Name ist im gleichen Namensraum bereits vorhanden.
error.emptyName=Der Datenquellenname darf nicht leer sein.
error.invalidName=Der Name "{0}" ist unzulässig, da er das Zeichen "." enthält.

###########################################################
#ExceptionHandler properties

ExceptionHandler.Label.ErrorCode=Fehlercode
ExceptionHandler.Label.ErrorMessage=Fehlermeldung
ExceptionHandler.Label.PluginId=Plug-in ID:
ExceptionHandler.Label.PluginName=Plug-in Name:
ExceptionHandler.Label.PluginProvider=Plug-in Provider:
ExceptionHandler.Label.PluginVersion=Version:
ExceptionHandler.Label.UnknownPlugin=Unknown plug-in
ExceptionHandler.Meesage.UnexceptedExceptionOccur=Es ist ein unerwarteter interner Ausnahmefehler aufgetreten. Nähere Informationen können Sie dem Protokoll entnehmen.
ExceptionHandler.Message.BirtExceptionOccur=In BIRT ist ein Ausnahmefehler aufgetreten.
ExceptionHandler.Message.CausedBy=Caused by {0}.
ExceptionHandler.Message.FileNotFound=File not found:
ExceptionHandler.Message.OutOfMemory=Nicht genug Arbeitsspeicher.
ExceptionHandler.Message.PartInitError=Teilinitialisierung fehlgeschlagen.
ExceptionHandler.Message.SemanticFail=Semantische Prüfung fehlgeschlagen.
ExceptionHandler.Message.UnexceptedExceptionOccur=Es ist ein interner Ausnahmefehler aufgetreten. Weitere Informationen finden Sie in der Protokolldatei.
ExceptionHandler.Message.UnknownHost=Unbekannter Host:
ExceptionHandler.Title.Error=Fehler
ExceptionHandler.Title.FileNotFound=Datei nicht gefunden.
ExceptionHandler.Title.PartInitError=Teilinitialisierungsfehler.
ExceptionHandler.Title.UnknownHost=Unbekannter Host

###########################################################
#ExportAction properties

ExportAction.actionMsg.export=Exportieren

###########################################################
#ExportToLibraryAction properties

ExportToLibraryAction.action.text=In Bibliothek &exportieren...
ExportToLibraryAction.Button.Cancel=Abbrechen
ExportToLibraryAction.Button.No=Nein
ExportToLibraryAction.Button.Yes=Ja
ExportToLibraryAction.Dialog.Message=\nZielbibliothek verfügt eventuell über dasselbe Designelement. Möchten Sie es überschreiben?
ExportToLibraryAction.Dialog.Title=Element exportieren
ExportToLibraryAction.Message.RememberDecision=Antwort merken

###########################################################
#LibraryExplorerTreeViewPage tooltips
LibraryExplorerTreeViewPage.toolTips.DragAndDropOutline=Mit Drag & Drop in Gliederungsansicht
LibraryExplorerTreeViewPage.toolTips.DragAndDropLayout=Mit Drag & Drop in Layout-Editor
LibraryExplorerTreeViewPage.toolTips.DragAndDropToOutlineORLayout=Mit Drag & Drop in Gliederungsansicht oder Layout-Editor

###########################################################
#ExpressionBuidler properties

ExpressionBuidler.Dialog.Title=Ausdruckserstellung
ExpressionBuilder.toolTipText.Button=Ausdruckserstellung öffnen

###########################################################
#ExpressionBuilder properties

ExpressionBuilder.Label.Category=Kategorie:
ExpressionBuilder.Label.Functions=Einfügen durch Doppelklicken:
ExpressionBuilder.Label.Operators=Operatoren:
ExpressionBuilder.Label.SubCategory=Unterkategorie:
ExpressionBuilder.Message.Prompt=Geben Sie in das Feld für die Ausdruckserstellung einen Ausdruck ein. Durchsuchen Sie die Liste der verfügbaren Objekte, und kopieren Sie sie per Doppelklick in den Ausdruck.

###########################################################
#ExpressionPropertyDescriptor properties

ExpressionPropertyDescriptor.text.Edit=&Ausdruckserstellung...

###########################################################
#ExpressionProvider properties

ExpressionProvider.Category.Context=Kontext
ExpressionProvider.Category.BirtObjects=BIRT-Funktionen
ExpressionProvider.Category.DataSets=Verfügbare Datensätze
ExpressionProvider.Category.NativeObjects=Native JavaScript-Funktionen
ExpressionProvider.Category.ColumnBinding=Verfügbare Spaltenbindungen
ExpressionProvider.Category.Operators=Operatoren
ExpressionProvider.Category.Parameters=Berichtparameter
ExpressionProvider.Label.All=---Alle---
ExpressionProvider.Operator.Add=Fügt zwei Werte zusammen.
ExpressionProvider.Operator.AddTo=Verknüpfung zum Hinzufügen zum aktuellen Wert.
ExpressionProvider.Operator.And=Vergleicht zwei Ausdrücke und gibt den Wert TRUE zurück, wenn beide Ausdrücke wahr sind.
ExpressionProvider.Operator.Assign=Setzt einen Wert dem anderen gleich.
ExpressionProvider.Operator.BitAnd=A & B: Gibt das bitweise UND-Ergebnis von A und B zurück.
ExpressionProvider.Operator.BitOr=A | B: Gibt das bitweise ODER-Ergebnis von A und B zurück.
ExpressionProvider.Operator.Dec=Verringert den Wert und gibt das Ergebnis zurück.
ExpressionProvider.Operator.DividingFrom=Verknüpfung zum Teilen des aktuellen Wertes.
ExpressionProvider.Tooltip.ColumnBinding=Verweist auf 
ExpressionProvider.Operator.Divides=Teilt den linken Wert durch den rechten Wert und gibt das Ergebnis zurück.
ExpressionProvider.Operator.Equals=Gibt den Wert TRUE zurück, wenn die Elemente gleich sind.
ExpressionProvider.Operator.Greater=A > B: Gibt einen wahren Wert zurück, wenn A größer als B ist.
ExpressionProvider.Operator.GreaterEquals=A >= B: Gibt einen wahren Wert zurück, wenn A größer als oder gleich B ist.
ExpressionProvider.Operator.Inc=Erhöht den Wert und gibt das Ergebnis zurück.
ExpressionProvider.Operator.LeftBracket=Linke Klammer
ExpressionProvider.Operator.RightBracket=Rechte Klammer
ExpressionProvider.Operator.Less=A < B: Gibt einen wahren Wert zurück, wenn A kleiner als B ist.
ExpressionProvider.Operator.LessEqual=A <= B: Gibt einen wahren Wert zurück, wenn A kleiner als oder gleich B ist.
ExpressionProvider.Operator.Mult=Multipliziert zwei Werte.
ExpressionProvider.Operator.MultTo=Verknüpfung zum Multiplizieren des aktuellen Wertes.
ExpressionProvider.Operator.Not=!A: Gibt einen wahren Wert zurück, wenn A falsch ist, bzw. einen falschen Wert, wenn A wahr ist.
ExpressionProvider.Operator.NotEqual=A <> B: Gibt einen wahren Wert zurück, wenn A nicht gleich B ist.
ExpressionProvider.Operator.Or=Vergleicht zwei Ausdrücke und gibt den Wert TRUE zurück, wenn ein Ausdruck, nicht aber beide Ausdrücke wahr sind.
ExpressionProvider.Operator.ReturnDec=Gibt den Wert zurück und verringert ihn dann.
ExpressionProvider.Operator.ReturnInc=Gibt den Wert zurück und erhöht ihn dann.
ExpressionProvider.Operator.Sub=Subtrahiert einen Wert vom anderen.
ExpressionProvider.Operator.SubFrom=Verknüpfung zum Subtrahieren vom aktuellen Wert.
ExpressionProvider.Operators.Assignment=Zuweisung
ExpressionProvider.Operators.Comparison=Vergleich
ExpressionProvider.Operators.Computational=Rechnerische
ExpressionProvider.Operators.Logical=Logische
ExpressionProvider.EditBindings=Bindungen bearbeiten...
ExpressionProvider.Expression.RowNumName=RowNum
ExpressionProvider.Expression.RowNumTooltip=Ausdruck, der die aktuelle Zeilenanzahl zurückgibt.

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<Ausdruckserstellung ...>
ExpressionValueCellEditor.selectValueAction=<Wert auswählen ...>
ExpressionValueCellEditor.title=Wert auswählen

###########################################################
#ExtendedEditPart properties

ExtendedEditPart.edit=Bearbeiten {0}

###########################################################
#ExtendedItemPageGenerator properties

ExtendedItemPageGenerator.List.Bookmark=Lesezeichen
ExtendedItemPageGenerator.List.TOC=Inhaltsverzeichnis

###########################################################
#FilterHandleProvider properties

FilterHandleProvider.ColumnName.Value=Wert
FilterHandleProvider.Label.Filterby=Filtern nach:
FilterHandleProvider.Modify.SaveValues=Werte speichern

###########################################################
#filters properties

filters.empty.columnName=Der Ausdruck darf nicht leer sein.
filters.error.title=Ungültige Eingabe.
filters.operators.any=ist beliebig
filters.operators.between=Ist zwischen
filters.operators.bottomN=Letzte (n) Elemente
filters.operators.bottomPercent=Unterste (n) Prozent
filters.operators.equal=ist gleich 
filters.operators.false=ist FALSE
filters.operators.greaterThan=ist größer als
filters.operators.greaterThanEqual=größer als oder gleich
filters.operators.lessThan=ist kleiner als
filters.operators.lessThanEqual=ist kleiner als oder gleich
filters.operators.like=ist wie
filters.operators.notBetween=ist nicht zwischen
filters.operators.notEqual=ist nicht gleich
filters.operators.notNull=ist nicht Null
filters.operators.null=ist Null
filters.operators.topN=ist erste (n) Elemente
filters.operators.topPercent=ist oberste (n) Prozent
filters.operators.true=ist TRUE
filters.prompt.new=<Neuer Filter hier...>

###########################################################
#FixTableLayoutCalculator properties

FixTableLayoutCalculator.Error.CannotParse=Der Eingabewert kann nicht analysiert werden.

###########################################################
#FlowMoveChildCommand properties

FlowMoveChildCommand.transLabel.moveElement=Element verschieben

###########################################################
#FontPreferencePage properties

FontPreferencePage.displayname.Title=Schriftart
FontPreferencePage.label.fontDecoration=Dekoration:
FontPreferencePage.text.Preview=Mustervorschau
FontPreferencePage.text.PreviewContent=AaBbYyZz

###########################################################
#FontSizeBuilder properties

FontSizeBuilder.displayname.Auto=Automatisch

###########################################################
#FormatBuilder properties

FormatBuilder.Title=Formaterstellung

###########################################################
#FormatDateTimeAttributePage properties

FormatDateTimeAttributePage.Trans.SetDateTimeFormat = Legen Sie das Datum-/Uhrzeitformat fest.

###########################################################
#FormatDateTimePage properties

FormatDateTimePage.label.custom.settings.label=Beispielformate (Klicken Sie auf ein Beispiel, um es zu kopieren und zu bearbeiten):
FormatDateTimePage.label.custom.settings=Benutzerdefinierte Einstellungen
FormatDateTimePage.label.format.code=Formatcode:
FormatDateTimePage.label.format.page=&Formatieren als:
FormatDateTimePage.label.general.preview.group=Vorschau mit Format
FormatDateTimePage.label.guide.text=Im Format MM/TT/JJJJ hh:mm:ss AM/PM eingeben
FormatDateTimePage.label.preview.dateTime=Datum/Uhrzeit für Vorschau: 
FormatDateTimePage.label.preview.group=Vorschau
FormatDateTimePage.label.preview.label=Vorschau mit Format:
FormatDateTimePage.label.table.column.format.name=Beispielformat
FormatDateTimePage.label.table.column.format.result=Beispiel-Formatergebnis
FormatDateTimePage.label.table.column.format.code=Beispielcode
FormatDateTimePage.preview.invalid.dateTime=Ungültige(s) Datum/Uhrzeit für Vorschau
FormatDateTimePage.preview.invalid.formatCode=Ungültiger Formatcode

###########################################################
#FormatDateTimePreferencePage properties

FormatDateTimePreferencePage.formatDateTime.title=Format Datum/Uhrzeit

###########################################################
#FormatNumberAttributePage properties

FormatNumberAttributePage.Trans.SetNumberFormat = Legen Sie das Zahlenformat fest.

###########################################################
#FormatNumberPage properties

FormatNumberPage.currency.symbol.none=Kein Symbol
FormatNumberPage.label.currency.settings=Währungseinstellungen
FormatNumberPage.label.custom.preview.group=Vorschau
FormatNumberPage.label.custom.preview.label=Vorschau mit Format:
FormatNumberPage.label.custom.settings.lable=Beispielformate (Klicken Sie auf ein Beispiel, um es zu kopieren und zu bearbeiten):
FormatNumberPage.label.custom.settings=Benutzerdefinierte Einstellungen
FormatNumberPage.label.decimal.places=Dezimalstellen: 
FormatNumberPage.label.fixed.settings=Feste Einstellungen
FormatNumberPage.label.format.code=Formatcode:
FormatNumberPage.label.format.number.page=&Formatieren als:
FormatNumberPage.label.general.preview.group=Vorschau mit Format
FormatNumberPage.label.negative.numbers=Negative Zahlen: 
FormatNumberPage.label.percent.settings=Prozenteinstellungen
FormatNumberPage.label.preview.number=Zahl für Vorschau: 
FormatNumberPage.label.scientific.settings=Wissenschaftliche Einstellungen
FormatNumberPage.label.symbol.position=Symbolposition: 
FormatNumberPage.label.symbol=Symbol: 
FormatNumberPage.label.table.column.format.code=Beispielformat
FormatNumberPage.label.table.column.format.result=Beispiel-Formatergebnis
FormatNumberPage.label.use1000sSeparator=1000er-Trennzeichen verwenden
FormatNumberPage.label.useLeadingZero=Führende Null verwenden
FormatNumberPage.preview.invalidFormatCode=Ungültiger Formatcode
FormatNumberPage.preview.invalidNumber=Zahl für Vorschau ungültig
FormatNumberPage.symblePos.after=Nach
FormatNumberPage.symblePos.before=Vor

###########################################################
#FormatNumberPreferencePage properties

FormatNumberPreferencePage.formatNumber.title=Format Zahl

###########################################################
#FormatPreferencePage properties

FormatPreferencePage.displayname.Title=Format

###########################################################
#FormatStringAttributePage properties

FormatStringAttributePage.Trans.SetStringFormat = Legen Sie das Zeichenkettenformat fest.

###########################################################
#FormatStringPage properties

FormatStringPage.default.preview.text=Beispielzeichenfolge
FormatStringPage.label.custom.preview.label=Vorschau mit Format:
FormatStringPage.label.custom.settings.label=Beispielformate (Klicken Sie auf ein Beispiel, um es zu kopieren und zu bearbeiten):
FormatStringPage.label.customSettings=Benutzerdefinierte Einstellungen
FormatStringPage.label.format.code=Formatcode:
FormatStringPage.label.formatStringAs=&Formatieren als:
FormatStringPage.label.preview.group=Vorschau
FormatStringPage.label.preview.string=Zeichenfolge für Vorschau: 
FormatStringPage.label.previewWithFormat=Vorschau mit Format
FormatStringPage.label.table.collumn.exampleFormatCode=Beispielformat
FormatStringPage.label.table.collumn.exampleFormatResult=Beispiel-Formatergebnis
FormatStringPage.previewText.invalidFormatCode=Ungültiger Formatcode

###########################################################
#FormatStringPreferencePage properties

FormatStringPreferencePage.formatString.title=Format Zeichenfolge

###########################################################
#FormPage properties

FormPage.Button.Add=&Hinzufügen
FormPage.Button.AddWithDialog=&Hinzufügen...
FormPage.Button.Delete=&Entfernen
FormPage.Button.Down=Nach-&unten
FormPage.Button.Edit=&Bearbeiten
FormPage.Button.EditWithDialog=&Bearbeiten...
FormPage.Button.Up=&Nach oben
FormPage.Menu.ModifyProperty=Eigenschaft modifizieren
FormPage.toolTipText.Up=Nach oben
FormPage.toolTipText.Down=Nach unten

###########################################################
#GeneralInsertMenuAction properties

GeneralInsertMenuAction.text.Data=&Daten
GeneralInsertMenuAction.text.DynamicText=D&ynamischer Text
GeneralInsertMenuAction.text.Grid=Ra&ster
GeneralInsertMenuAction.text.Image=&Bild
GeneralInsertMenuAction.text.Label=Bes&chriftung
GeneralInsertMenuAction.text.List=&Liste
GeneralInsertMenuAction.text.Table=&Tabelle
GeneralInsertMenuAction.text.Text=T&ext

###########################################################
#GeneralPreferencePage properties

GeneralPreferencePage.errorMsg.duplicate.styleName=Der Stilname ist bereits vorhanden.
GeneralPreferencePage.label.styleNameDuplicate=Stilname "{0}" ist bereits vorhanden. Wählen Sie einen anderen Namen.
GeneralPreferencePage.label.customStyle=&Benutzerdefinierter Stil
GeneralPreferencePage.label.predefinedStyle=&Vordefinierter Stil
GeneralPreferencePage.label.nameEmpty=Leerer Stilname ist nicht zulässig. 

###########################################################
#GridEditPart properties

GridEditPart.GUIDEHANDLE_TEXT = Raster

###########################################################
#GridFigure properties

GridFigure.BORDER_TEXT=Raster

###########################################################
#GridPageGenerator properties

GridPageGenerator.List.Bookmark=Lesezeichen
GridPageGenerator.List.Borders=Rahmen
GridPageGenerator.List.Font=Schriftart
GridPageGenerator.List.General=Allgemein
GridPageGenerator.List.Margin=Rand
GridPageGenerator.List.Section=Seitenumbruch
GridPageGenerator.List.TOC=Inhaltsverzeichnis
GridPageGenerator.List.Visibility=Sichtbarkeit
GridPageGenerator.TabItem.Highlights=Kennzeichnungen
GridPageGenerator.TabItem.map=Zuordnung

###########################################################
#GridProvider properties

GridProvider.action.text=Zeile einfügen

###########################################################
#GroupDialog properties

GroupDialog.Dialog.GroupDetail=Gruppendetails
GroupDialog.Dialog.TOCGroup=Inhaltsverzeichnis
GroupDialog.Dialog.TOC=Elemen&tausdruck:
GroupDialog.Dialog.TOCStyle=St&il:
GroupDialog.DialogTitle.NoData=Initialisierungsfehler
GroupDialog.DialogTitle.SemanticCheckFailed=Semantische Prüfung fehlgeschlagen
GroupDialog.ErrorMesaage.IllegalGroup=Diese Gruppe ist unerlaubt.
GroupDialog.ErrorMessage.NoData=Es ist keine Datenzeile verfügbar.
GroupDialog.Label.FilterSorting=Filter und Sortierung
GroupDialog.Label.GroupOn=&Gruppierung nach:
GroupDialog.Label.HeaderFooter=Kopfzeile und Fußzeile
GroupDialog.Label.IncludeFooter=&Gruppenfußzeile einschließen
GroupDialog.Label.IncludeHeader=&Gruppenkopfzeile einschließen
GroupDialog.Label.Interval=&Intervall:
GroupDialog.PageBreakBefore=Vorher:
GroupDialog.PageBreakAfter=Nachher:
GroupDialog.PageBreakInside=Innen:
GroupDialog.Label.IntervalBase=&Festen Basiswert für Intervall verwenden:
GroupDialog.Label.Name=&Name:
GroupDialog.Label.Range=&Bereich:
GroupDialog.Tab.Binding=Datenbindungen
GroupDialog.Tab.Filter=Filter
GroupDialog.Tab.Sorting=Sortierung
GroupDialog.RepeatHeader=Kopfzeile wiederholen
GroupDialog.Title.Edit=Gruppe bearbeiten
GroupDialog.Title.New=Neue Gruppe
GroupDialog.PageBreak=Seitenumbruch
GroupDialog.buttion.HideDetail=&Detail ausblenden
GroupDialog.toolTipText.openExprButton=Ausdruckserstellung öffnen

###########################################################
#GroupHandleProvider properties

GroupHandleProvider.Label.Groups=Gruppenliste:

###########################################################
#GroupProvider properties

GroupProvider.action.text=Gruppe bearbeiten

###########################################################
#GuiExtensionManager properties

GuiExtensionManager.label.name=Erweitertes Element
GuiExtensionManager.tooltip.insert={0} einfügen

###########################################################
#HighlightHandleProvider properties

HighlightHandleProvider.text.Preview=AaBbCcYyZz (Schriftgröße = 

###########################################################
#HighlightRuleBuilderDialog properties

HighlightRuleBuilderDialog.choice.ValueOfThisDataItem=Wert dieses Datenelements
HighlightRuleBuilderDialog.text.AND=UND
HighlightRuleBuilderDialog.text.Any=ist beliebig
HighlightRuleBuilderDialog.text.BackgroundColor=Hintergrundfarbe:
HighlightRuleBuilderDialog.text.Between=Ist zwischen
HighlightRuleBuilderDialog.text.Color=Farbe:
HighlightRuleBuilderDialog.text.Condition=Wenn folgende Bedingung wahr ist: 
HighlightRuleBuilderDialog.text.Default=Automatisch
HighlightRuleBuilderDialog.text.ET=ist gleich
HighlightRuleBuilderDialog.text.False=ist FALSE
HighlightRuleBuilderDialog.text.Font=Schriftart:
HighlightRuleBuilderDialog.text.Format=Dann wird folgende Formatierung angewendet:
HighlightRuleBuilderDialog.text.GE=größer als oder gleich
HighlightRuleBuilderDialog.text.GT=ist größer als
HighlightRuleBuilderDialog.text.LE=ist kleiner als oder gleich
HighlightRuleBuilderDialog.text.Like=ist wie
HighlightRuleBuilderDialog.text.LT=ist kleiner als
HighlightRuleBuilderDialog.text.NE=ist nicht gleich
HighlightRuleBuilderDialog.text.NotBetween=ist nicht zwischen
HighlightRuleBuilderDialog.text.NotNull=ist nicht Null
HighlightRuleBuilderDialog.text.Null=ist Null
HighlightRuleBuilderDialog.text.Preview=Vorschau:
HighlightRuleBuilderDialog.text.PreviewContent=AaBbCcYyZz
HighlightRuleBuilderDialog.text.Size=Größe:
HighlightRuleBuilderDialog.text.Title=Kennzeichnungsregel hinzufügen/bearbeiten
HighlightRuleBuilderDialog.text.True=ist TRUE
HighlightRuleBuilderDialog.tooltip.ExpBuilder=Klicken Sie hier, um die Ausdruckserstellung zu starten.
HighlightRuleBuilderDialog.tooltip.Bold=Fett
HighlightRuleBuilderDialog.tooltip.Italic=Kursiv
HighlightRuleBuilderDialog.tooltip.Underline=Unterstrichen
HighlightRuleBuilderDialog.tooltip.Text_Line_Through=Durchgestrichener Text
HighlightRuleBuilderDialog.text.applyStyle=Verwenden Sie die Formatierung von Stil:
HighlightRuleBuilderDialog.displayText.None=Ohne

###########################################################
#HighlightsPage properties

HighlightsPage.Button.Add=&Hinzufügen...
HighlightsPage.Button.Delete=&Entfernen
HighlightsPage.Dialog.EditHighlight=Markierung bearbeiten
HighlightsPage.Dialog.NewHighlight=Neue Kennzeichnung
HighlightsPage.Label.Highlights=Kennzeichnungsliste:
HighlightsPage.TableColumn.Condition=Bedingung
HighlightsPage.TableColumn.Preview=Vorschau:
HighlightsPage.trans.Add=Kennzeichnungsregel hinzufügen
HighlightsPage.trans.Delete=Kennzeichnungsregel löschen
HighlightsPage.trans.Edit=Kennzeichnungsregel bearbeiten
HighlightsPage.trans.MoveDown=Kennzeichnungsregel nach unten verschieben
HighlightsPage.trans.MoveUp=Kennzeichnungsregel nach oben verschieben
HighlightsPage.toolTipText.MoveDown=Kennzeichnungsregel nach unten verschieben
HighlightsPage.toolTipText.MoveUp=Kennzeichnungsregel nach oben verschieben

###########################################################
#HighlightsPreferencePage properties

HighlightsPreferencePage.displayname.Condition=Bedingung
HighlightsPreferencePage.displayname.Preview=Vorschau
HighlightsPreferencePage.displayname.Title=Kennzeichnungen
HighlightsPreferencePage.text.Add=&Hinzufügen...
HighlightsPreferencePage.text.Delete=&Entfernen
HighlightsPreferencePage.text.Description=Kennzeichnungsliste:
HighlightsPreferencePage.text.Edit=&Bearbeiten...
HighlightsPreferencePage.toolTipText.Up=Markierung nach oben verschieben
HighlightsPreferencePage.toolTipText.Down=Markierung nach unten verschieben

###########################################################
#HyperlinkBuilder properties

HyperlinkBuilder.Column.Parameters=Parameter
HyperlinkBuilder.DrillThroughStep1=Schritt 1: Zielbericht auswählen 
HyperlinkBuilder.DrillThroughStep2=Schritt 2: Zielanker auswählen 
HyperlinkBuilder.DrillThroughStep3=Schritt 3: Verknüpfungsausdruck erstellen, der mit dem Ziellesezeichen übereinstimmt
HyperlinkBuilder.DrillThroughStep4=Schritt 4: Zielbericht anzeigen in 
HyperlinkBuilder.DrillThroughStep5=Schritt 5: Format für Zielbericht auswählen
HyperlinkBuilder.ParameterRequired=erforderlich
HyperlinkBuilder.Column.Values=Werte
HyperlinkBuilder.DialogTitle=Optionen für Hyperlink
HyperlinkBuilder.ErrorMessage.InvalidReport=Berichtdesign ungültig.
HyperlinkBuilder.ErrorMessage.ReportReqired=Sie müssen die Berichtdatei angeben.
HyperlinkBuilder.DrillThroughTargetBookmark=Ziellesezeichen
HyperlinkBuilder.DrillThroughLinkExpression=Verknüpfungsausdruck:
HyperlinkBuilder.Label.Bookmark=Lesezeichen:
HyperlinkBuilder.Label.Format=Format:
HyperlinkBuilder.Label.LinkedExpression=Verknüpfter Ausdruck:
HyperlinkBuilder.DrillThroughTargetToc=Inhaltsverzeichniseintrag im Zielbericht
HyperlinkBuilder.DrillThroughSamewindow=Gleiches Fenster
HyperlinkBuilder.DrillThroughNewWindow=Neues Fenster
HyperlinkBuilder.Label.Location=Speicherort:
HyperlinkBuilder.Label.Parameters=Berichtparameter:
HyperlinkBuilder.Label.Report=Bericht:
HyperlinkBuilder.Label.SelectType=Art des Hyperlinks wählen:
HyperlinkBuilder.DrillThroughHtml=HTML
HyperlinkBuilder.Label.Target=Ziel:
HyperlinkBuilder.Radio.Bookmark=Internes Lesezeichen
HyperlinkBuilder.DrillThroughPdf=PDF
HyperlinkBuilder.Radio.DrillThrough=Drill-through
HyperlinkBuilder.ReportDesignButton=Berichtdesign:
HyperlinkBuilder.ReportDocumentButton=Berichtdokument:
HyperlinkBuilder.Radio.None=Keine Verknüpfung
HyperlinkBuilder.Radio.Uri=URI
HyperlinkBuilder.BrowseForFile=Nach Datei suchen
HyperlinkBuilder.OpenExpression=Ausdruckserstellung öffnen
HyperlinkBuilder.FileNameError.Title=Fehler
HyperlinkBuilder.FileNameError.Message=Die ausgewählte Datei ist ungültig.
HyperlinkBuilder.TargetReportFormat=Zielbericht formatieren in:

###########################################################
#HyperLinkPage properties

HyperLinkPage.Label.LnikTo=&Verknüpfen mit:
HyperLinkPage.Label.None=Kein
HyperLinkPage.Menu.Save=Hyperlink ändern
HyperLinkPage.toolTipText.Button=Optionen für Öffnen des Hyperlink

###########################################################
#I18nPage properties

I18nPage.text.Note=Hinweis: Um die Lokalisierung einzustellen, wählen Sie den Bericht aus, und legen Sie den Namen der Ressourcendatei im Eigenschaftseditor auf der Registerkarte 'Ressourcen' fest.

###########################################################
#ImageBuilder properties

ImageBuilder.Button.Dynamic=&Dynamisches Bild
ImageBuilder.Button.Import=&Bild hinzufügen...
ImageBuilder.Button.Insert=&Einfügen
ImageBuilder.Button.Preview=&Vorschau
ImageBuilder.Button.Remove=Entfernen
ImageBuilder.ButtonBrowser=Durchsuchen...
ImageBuilder.Chooser.Title=Bilddatei öffnen
ImageBuilder.DialogTitle.Edit=Bildobjekt bearbeiten
ImageBuilder.DialogTitle.ImportFailed=Import fehlgeschlagen
ImageBuilder.DialogTitle.LoadingFailed=Bild konnte nicht geladen werden
ImageBuilder.DialogTitle.New=Neues Bildobjekt
ImageBuilder.ErrorMessage.FileLoaded=Diese Datei ist bereits geladen.
ImageBuilder.ErrorMessage.LoadingFailed=Das Bild kann nicht korrekt geladen werden.
ImageBuilder.BrowserResourceDialog.Title=Nach Bilddateien suchen
ImageBuilder.BrowserResourceDialog.Message=Wählen Sie die Bilddateien aus dem Ressourcenpfadordner aus.
ImageBuilder.ErrorMessage.OutOfMemory=Das Bild ist zu groß für den verfügbaren Speicher.
ImageBuilder.FileDialog.FilterMessage=Unterstützte Bilddatei
ImageBuilder.Label.Binding=&Bindung
ImageBuilder.Label.EmbededImage=&Eingebettetes Bild
ImageBuilder.Label.EnterExpr=&Ausdruck für dynamisches Bild eingeben:
ImageBuilder.Label.EnterUri=&URI eingeben:
ImageBuilder.Label.Open=&Ausdruckserstellung...
ImageBuilder.Label.SelectFrom=Bild auswählen aus:
ImageBuilder.ResourceFileType=Bilddatei in Ressourcenordner
ImageBuilder.Label.URI=&URI
ImageBuilder.Label.EnterResourceFile=Ressourcendatei ei&ngeben:

###########################################################
#ImageEditPart properties

ImageEditPart.trans.editImage=Bild ändern

###########################################################
#ImagePageGenerator properties

ImagePageGenerator.List.AltText=Alternativer Text
ImagePageGenerator.List.Bookmark=Lesezeichen
ImagePageGenerator.List.Borders=Rahmen
ImagePageGenerator.List.General=Allgemein
ImagePageGenerator.List.HyperLink=Hyperlink
ImagePageGenerator.List.Reference=Referenz
ImagePageGenerator.List.Section=Seitenumbruch
ImagePageGenerator.List.TOC=Inhaltsverzeichnis
ImagePageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#ImportCSSStyleAction properties

ImportCSSStyleAction.text=CSS-Stil importieren...

###########################################################
#ImportLibraryAction properties

ImportLibraryAction.Error.CannotBeEmpty=Der Namensraum darf nicht leer sein.
ImportLibraryAction.Error.HasBeenUsed=Der Namensraum wird bereits verwendet.
ImportLibraryAction.Error.HasDot=Der Namensraum darf keinen Punkt ('.') enthalten.
ImportLibraryAction.Message.ImportSuccessfully=Die Bibliothek {0} wurde importiert.
ImportLibraryAction.Message=Diese Bibliothek für das Berichtdesign verwenden?
ImportLibraryAction.Namespace=Namensraum:
ImportLibraryAction.Prefix=Präfix:
ImportLibraryAction.Title.ImportSuccessfully=Importieren erfolgreich
ImportLibraryAction.Dialog.Titile=Bibliothek verwenden
ImportLibraryAction.Dialog.Message=Wählen Sie eine Bibliothek, die in den Bericht aufgenommen werden soll. 

###########################################################
#ImportLibraryDialog properties

ImportLibraryDialog.Title=Bibliothek verwenden

###########################################################
#ImportValueDialog properties

ImportValueDialog.Label.SelectColumn=&Spalte auswählen:
ImportValueDialog.Label.SelectDataSet=&Datensatz auswählen:
ImportValueDialog.Label.SelectValue=&Hinzuzufügenden Wert auswählen oder eingeben
ImportValueDialog.Title=Werte importieren

###########################################################
#IncludeDetailAction properties

IncludeDetailAction.actionMsg.includeDetail=&Detail

###########################################################
#IncludeFooterAction properties

IncludeFooterAction.actionMsg.includeFooter=&Fußzeile

###########################################################
#IncludeHeaderAction properties

IncludeHeaderAction.actionMsg.includeHeader=&Kopfzeile

###########################################################
#IncludeListDetailAction properties

IncludeListDetailAction.actionMsg.includeDetail=Detail einschließen

###########################################################
#IncludeListFooterAction properties

IncludeListFooterAction.actionMsg.includeFooter=Fußzeile einschließen

###########################################################
#IncludeListHeaderAction properties

IncludeListHeaderAction.actionMsg.includeHeader=Kopfzeile einschließen

###########################################################
#IncludeTableGroupFooterAction properties

IncludeTableGroupFooterAction.actionMsg.includeFooter=Gruppenfußzeile

###########################################################
#IncludeTableGroupHeaderAction properties

IncludeTableGroupHeaderAction.actionMsg.includeHeader=Gruppenkopfzeile

###########################################################
#InputParameterDailog properties

InputParameterDailog.dialog.title.required=Erforderlicher Parameter – muss einen Wert aufweisen
InputParameterDailog.dialog.title=Parameter eingeben
InputParameterDailog.parameter.noparameter=Mit diesem Bericht ist kein Parameter verknüpft.
InputParameterDialog.ErrorMessage.InvalidFile=Der Bericht ist fehlerhaft.
InputParameterDailog.parameter.null=Null-Wert
InputParameterDialog.ErrorTitle.Error=Fehler

###########################################################
#InsertAction properties

InsertAction.text=Element einfügen

###########################################################
#InsertColumnAction properties

InsertColumnAction.actionMsg.insert=Einfügen

###########################################################
#InsertColumnLeftAction properties

InsertColumnLeftAction.actionMsg.columnToLeft=Spalte nach &links

###########################################################
#InsertColumnRightAction properties

InsertColumnRightAction.actionMsg.columnToRight=Spalte nach &rechts

###########################################################
#InsertExpressionMenuAction properties

InsertExpressionMenuAction.text.Expression=Ausdruck...

###########################################################
#InsertGroupAction properties

InsertGroupAction.actionMsg.group=Gruppe e&infügen
InsertGroupAction.stackMsg.addGroup=Gruppe hinzufügen

###########################################################
#InsertGroupActionFactory properties

InsertGroupActionFactory.label.insertGroup=Gruppe ei&nfügen

###########################################################
#InsertInLayoutAction properties

InsertInLayoutAction.action.text=In Layout einfügen

###########################################################
#InsertListGroupAction properties

InsertListGroupAction.actionMsg.insertGroup=Gruppe einfügen
InsertListGroupAction.stackMsg.insertListGroup=Listengruppe einfügen

###########################################################
#InsertPasteColumnAction properties

InsertPasteColumnAction.text=Kopierte &Spalte einfügen

###########################################################
#InsertPositionGroupAction properties

InsertPositionGroupAction.Label.Above=&Oben
InsertPositionGroupAction.Label.Below=&Unten
InsertPositionGroupAction.Label.Into=Hinein

###########################################################
#InsertRowAboveAction properties

InsertRowAboveAction.actionMsg.rowAbove=&Oben

###########################################################
#InsertRowAction properties

InsertRowAction.actionMsg.insert=E&infügen

###########################################################
#InsertRowBelowAction properties

InsertRowBelowAction.actionMsg.rowBelow=&Unten

###########################################################
#IReportGraphicConstants properties

IReportGraphicConstants.ImageType.All=Alle Bilddateien (*.BMP,*.JPG,*.JPEG,*.GIF,*.TIF,*.PNG,*.ICO)
IReportGraphicConstants.ImageType.Bmp=Bitmap-Dateien (*.BMP)
IReportGraphicConstants.ImageType.Gif=GIF-Dateien (*.GIF)
IReportGraphicConstants.ImageType.Icon=Symboldateien (*.ICO)
IReportGraphicConstants.ImageType.Jpg=JPEG-Dateien (*.JPG,*.JPEG)
IReportGraphicConstants.ImageType.Png=PNG-Dateien (*.PNG)
IReportGraphicConstants.ImageType.Tif=TIF-Dateien (*.TIF)

###########################################################
#JSDocumentProvider properties

JSDocumentProvider.Content.Default=Neuer Inhalt
JSDocumentProvider.document.newName=Neuer Inhalt

###########################################################
#JSEditor properties

JSEditor.Button.Reset=Methode zurücksetzen
JSEditor.Display.DefaultText=//JS Script-Editor \n
JSEditor.Display.NoExpression=Dieses Element verfügt über keine Methoden.
JSEditor.Input.trial=Test
JSEditor.Text.NoText=Kein Text

###########################################################
#label properties

label.defaultValue=(Standardwert)
label.input=Eingabe
label.inputOutput=Eingabe/Ausgabe
label.no=Nein
label.output=Ausgabe
label.redo=Wiederherstellen
label.undo=Rückgängig
label.yes=Ja

###########################################################
#LabelEditPart properties

LabelEditPart.Figure.Default=Beschriftung

###########################################################
#LabelPageGenerator properties

LabelPageGenerator.List.Bookmark=Lesezeichen
LabelPageGenerator.List.Borders=Rahmen
LabelPageGenerator.List.General=Allgemein
LabelPageGenerator.List.HyperLink=Hyperlink
LabelPageGenerator.List.I18n=Lokalisierung
LabelPageGenerator.List.Margin=Rand
LabelPageGenerator.List.Padding=Umrandungsfüllung
LabelPageGenerator.List.Section=Seitenumbruch
LabelPageGenerator.List.TOC=Inhaltsverzeichnis
LabelPageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#LayoutEditor properties

LayoutEditor.ErrorMessage.OpenError=Beim Öffnen des Editors ist ein Fehler aufgetreten.
LayoutEditor.Page.Layout=Normal
LayoutEditor.Page.MasterPage=Master-Seite
LayoutEditor.Page.Source=XML-Quelldatei

###########################################################
#LayoutPageAction properties

LayoutPageAction.actionText.layout=Layout

###########################################################
#LibrariesNodeProvider properties

LibrariesNodeProvider.DisplayLabel.Libraries=Bibliotheken

###########################################################
#LibraryExplorerView properties

LibraryExplorerView.defaultText.notAvailable=Es stehen keine Bibliotheken zur Verfügung.

###########################################################
#LibraryExplorerProvider properties
LibraryExplorerProvider.FolderNotExist=Der in der Einstellung definierte BIRT-Ressourcenordner ist nicht vorhanden.

###########################################################
#LibraryPage properties

LibraryPage.Label.Namespace=Namensraum:
LibraryPage.Label.Path=Pfad:

###########################################################
#LibraryProvider properties

LibraryProvider.openDefinedLibrary.error.dialog.message=Fehler beim Öffnen der angegebenen Bibliothek
LibraryProvider.openDefinedLibrary.error.dialog.title=Fehler

###########################################################
#ListBandControlFigure properties

ListBandControlFigure.tooltip.GroupFooter=Listengruppe - Fußzeile
ListBandControlFigure.tooltip.GroupHeader=Listengruppe - Kopfzeile
ListBandControlFigure.tooltip.ListDetail=Liste - Detail
ListBandControlFigure.tooltip.ListFooter=Liste - Fußzeile
ListBandControlFigure.tooltip.ListHeader=Liste - Kopfzeile

###########################################################
#ListBandProvider properties

ListBandProvider.action.text=Gruppe einfügen

###########################################################
#ListBandProxy properties

ListBandProxy.list.detail=Detail
ListBandProxy.list.footer=Fußzeile
ListBandProxy.list.groupFooter=GF
ListBandProxy.list.groupHeader=GK
ListBandProxy.list.header=Kopfzeile

###########################################################
#ListContainProcess properties

ListContainProcess.action.New=Neu....
ListContainProcess.action.NewRow=Neue Zeile
ListContainProcess.action.NewSubSection=Neuer Teilbereich

###########################################################
#ListEditPart properties

ListEditPart.GUIDEHANDLE_TEXT = Liste

###########################################################
#ListFigure properties

ListFigure.BORDER_TEXT=Liste

###########################################################
#ListHandleAdapt properties

ListHandleAdapt.transLabel.insertGroup=Gruppe einfügen

###########################################################
#ListPageGenerator properties

ListPageGenerator.List.Bookmark=Lesezeichen
ListPageGenerator.List.Borders=Rahmen
ListPageGenerator.List.Font=Schriftart
ListPageGenerator.List.General=Allgemein
ListPageGenerator.List.Section=Seitenumbruch
ListPageGenerator.List.TOC=Inhaltsverzeichnis
ListPageGenerator.List.Visibility=Sichtbarkeit
ListPageGenerator.TabItem.Binding=Bindung
ListPageGenerator.TabItem.Filters=Filter
ListPageGenerator.TabItem.Groups=Gruppen
ListPageGenerator.TabItem.Highlights=Kennzeichnungen
ListPageGenerator.TabItem.map=Zuordnung
ListPageGenerator.TabItem.Sorting=Sortierung

###########################################################
#MapPage properties

MapPage.label.add=&Hinzufügen...
MapPage.label.condition=Bedingung
MapPage.label.delete=&Entfernen
MapPage.label.displayValue=Angezeigter Wert:
MapPage.label.mapList=Zuordnungsliste:
MapPage.transName.addMapRule=Zuordnungsregel hinzufügen
MapPage.transName.deleteMapRule=Zuordnungsregel löschen
MapPage.transName.editMapRule=Zuordnungsregel bearbeiten
MapPage.transName.moveDownRule=Zuordnungsregel nach unten verschieben
MapPage.transName.moveUpMapRule=Zuordnungsregel nach oben verschieben
MapPage.toolTipText.moveUp=Zuordnungsregel nach oben verschieben
MapPage.toolTipText.moveDown=Zuordnungsregel nach unten verschieben

###########################################################
#MapPreferencePage properties

MapPreferencePage.displayname.Condition=Bedingung
MapPreferencePage.displayname.DisplayValue=Angezeigter Wert
MapPreferencePage.displayname.Title=Zuordnung
MapPreferencePage.text.Add=&Hinzufügen...
MapPreferencePage.text.Delete=&Entfernen
MapPreferencePage.text.Description=Zuordnungsregeln:
MapPreferencePage.text.Edit=&Bearbeiten...
MapPreferencePage.toolTipText.Up=Zuordnungsregel nach oben verschieben
MapPreferencePage.toolTipText.Down=Zuordnungsregel nach unten verschieben

###########################################################
#MapRuleBuilderDialog properties

MapRuleBuilder.DialogTitle.New=Neue Zuordnungsregel
MapRuleBuilder.DialogTitle.Edit=Zuordnungsregel bearbeiten


MapRuleBuilderDialog.text.Between=ist zwischen
MapRuleBuilderDialog.text.Condition=&Wenn folgende Bedingung wahr ist: 
MapRuleBuilderDialog.text.Display=&Dann wird folgender Wert angezeigt: 
MapRuleBuilderDialog.text.ET=ist gleich
MapRuleBuilderDialog.text.GE=größer als oder gleich
MapRuleBuilderDialog.text.GT=ist größer als
MapRuleBuilderDialog.text.LE=ist kleiner als oder gleich
MapRuleBuilderDialog.text.Like=ist wie
MapRuleBuilderDialog.text.LT=ist kleiner als
MapRuleBuilderDialog.text.NE=ist nicht gleich
MapRuleBuilderDialog.text.NotBetween=ist nicht zwischen
MapRuleBuilderDialog.text.NotNull=ist nicht Null
MapRuleBuilderDialog.text.Null=ist Null
MapRuleBuilderDialog.text.Title=Zuordnungsregeln hinzufügen/bearbeiten

###########################################################
#SortkeyBuilder dialog properties
SortkeyBuilder.DialogTitle.New=Neuer Sortierschlüssel
SortkeyBuilder.DialogTitle.Edit=Sortierschlüssel bearbeiten
SortkeyBuilder.DialogTitle.Label.Prompt=Sortierschlüssel eingeben:
SortkeyBuilder.DialogTitle.Label.Key=Schlüssel:
SortkeyBuilder.DialogTitle.Label.Direction=Richtung:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Zum Öffnen der Ausdruckserstellung hier klicken
SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Fehler

###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=Neue Filterbedingung
FilterConditionBuilder.DialogTitle.Edit=Filterbedingung bearbeiten
FilterConditionBuilder.choice.ValueOfThisDataItem=Wert dieses Datenelements
FilterConditionBuilder.tooltip.ExpBuilder=Zum Öffnen der Ausdruckserstellung hier klicken.
FilterConditionBuilder.text.AND=UND
FilterConditionBuilder.text.Condition=Filterbedingung eingeben:

###########################################################
#MarignPropertyDescriptor properties

MarignPropertyDescriptor.error.message=Der eingegebene Wert ist zu groß.
MarignPropertyDescriptor.error.title=Wert zu groß

###########################################################
#MasterPageAction properties

MasterPageAction.actionText.masterPage=Master-Seite

###########################################################
#MasterPageGenerator properties

MasterPageGenerator.List.General=Allgemein
MasterPageGenerator.List.Header&Footer=Kopfzeile/Fußzeile
MasterPageGenerator.List.Margins=Seitenrand

###########################################################
#MasterPagePaletteFactory properties

MasterPagePaletteFactory.Autotext.TotalPageCount=Gesamt-Seitenzähler
MasterPagePaletteFactory.Autotext.Author_Page_Date=Verfasser\Nr., Seite\Nr., Datum\Nr.
MasterPagePaletteFactory.Autotext.Confidential_Page=Vertraulich, Seite\Nr.
MasterPagePaletteFactory.Autotext.CreatedBy=Erstellt von
MasterPagePaletteFactory.Autotext.CreatedOn=Erstellt für
MasterPagePaletteFactory.Autotext.Date=Datum
MasterPagePaletteFactory.Autotext.Filename=Dateiname
MasterPagePaletteFactory.Autotext.Label=AutoText
MasterPagePaletteFactory.Autotext.LastPrinted=Zuletzt ausgedruckt
MasterPagePaletteFactory.Autotext.Page=Seite
MasterPagePaletteFactory.Autotext.PageXofY=Seite n von m
MasterPagePaletteFactory.AutotextTooltip.TotalPageCount=Berichtobjekt des Gesamt-Seitenzählers
MasterPagePaletteFactory.AutotextTooltip.AuthorPageDate=Verfasser-Nr., Datumsnr.-Berichtobjekt
MasterPagePaletteFactory.AutotextTooltip.ConfidentialPage=Vertrauliches Berichtobjekt
MasterPagePaletteFactory.AutotextTooltip.CreatedBy=Erstellt durch Berichtobjekt
MasterPagePaletteFactory.AutotextTooltip.CreatedOn=Erstellt für Berichtobjekt
MasterPagePaletteFactory.AutotextTooltip.Date=Datum des Berichtobjekts
MasterPagePaletteFactory.AutoTextTooltip.Filename=Dateiname des Berichtobjekts
MasterPagePaletteFactory.AutotextTooltip.LastPrinted=Zuletzt gedrucktes Berichtobjekt
MasterPagePaletteFactory.AutotextTooltip.Page=Seite des Berichtsobjekts
MasterPagePaletteFactory.AutotextTooltip.PageXofY=Seite n von m Berichtobjekt
MasterPagePaletteFactory.elementLabel.authorPageDate=Verfasser#, Seite#, Datum
MasterPagePaletteFactory.elementLabel.confidentialPage=Vertraulich, Seite
MasterPagePaletteFactory.elementLabel.createdBy=Erstellt von
MasterPagePaletteFactory.elementLabel.createdOn=Erstellt für
MasterPagePaletteFactory.elementLabel.date=Datum
MasterPagePaletteFactory.elementLabel.fileName=Dateiname
MasterPagePaletteFactory.elementLabel.lastPrinted=Zuletzt ausgedruckt
MasterPagePaletteFactory.elementLabel.page=Seite
MasterPagePaletteFactory.elementLabel.pageOf=Seite n von m
MasterPagePaletteFactory.paletteDrawerName.autoText=AutoText
MasterPagePaletteFactory.ToolTip.Grid=Rasterberichtobjekt
MasterPagePaletteFactory.ToolTip.Text=Textberichtobjekt

###########################################################
#MasterPageProcess properties

MasterPageProcess.action.Edit=Bearbeiten
MasterPageProcess.action.New=Neu
MasterPageProcess.text.CannotDelete=Das Design enthält nur eine Master-Seite, die nicht gelöscht werden kann.
MasterPageProcess.text.Display=Zeigt das Dialogfeld zur Seiteneinrichtung an
MasterPageProcess.text.DisplayName=MasterPage

###########################################################
#MergeAction properties

MergeAction.actionMsg.merge=&Zellen verbinden

###########################################################
#ModulePage properties

ModulePage.ErrorMessage.Duplicate=Der Name wird bereits verwendet.
ModulePage.ErrorMessage.WrongExtensionName=Der Name muss auf ".properties" enden.
ModulePage.ErrorMessage.InfoExtensionName=Geben Sie einen Namen ein, der mit ".properties" endet.
ModulePage.text.Add=&Hinzufügen...
ModulePage.text.ExistingFile=Vorhandene Ressourcendateien:
ModulePage.title.AddNewFile=Neue Ressourcendatei hinzufügen
ModulePage.Resourcefile.Dialog.Title=Ressourcendateien durchsuchen
ModulePage.Resourcefile.Dialog.Message=Wählen Sie eine Ressourcendatei oder einen Ordner aus, und geben Sie zum Erstellen einen neuen Dateinamen ein.
ModulePage.text.Path=Pfad:

###########################################################
#MultiPageEditorContributor properties

MultiPageEditorContributor.actionText.sampleAction=Beispielaktion
MultiPageEditorContributor.actionToolTip.sampleActionToolTip=Kontexthilfe für Beispielaktion
MultiPageEditorContributor.actionToolTipText.sampleActionToolTip=Kontexthilfe für Beispielaktion
MultiPageEditorContributor.dialogMsg.sampleActionExecuted=Beispielaktion ausgeführt
MultiPageEditorContributor.dialogTitle.infoObjectDesignerPlugIn=Infoobjectdesigner-Plug-in
MultiPageEditorContributor.menuText.editorMenu=Editor&menü

###########################################################
#NewLibraryWizard properties

NewLibraryWizard.choicePageTitle.report=Bibliothek
NewLibraryWizard.displayName.NewReportFileExtension=.rptlibrary
NewLibraryWizard.displayName.NewReportFileNamePrefix=new_library
NewLibraryWizard.error.NoProject=Kein geöffnetes Projekt im Arbeitsbereich vorhanden. Erstellen Sie ein neues Projekt über "Datei -> Neu -> Projekt", oder öffnen Sie ein vorhandenes Projekt.
NewLibraryWizard.pageDescription.createNewReport=Neue Bibliothek erstellen
NewLibraryWizard.taskName.openFileForEdit=Datei zum Bearbeiten wird geöffnet...
NewLibraryWizard.text.ConfirmSwitchPerspective=Wechsel der Perspektive bestätigen
NewLibraryWizard.text.Container=Behälter "
NewLibraryWizard.text.CreateReport=Neue Bibliothek erstellen
NewLibraryWizard.text.Creating=Wird erstellt 
NewLibraryWizard.text.DoesNotExist=" existiert nicht.
NewLibraryWizard.text.OpenFileForEditing=Datei zum Bearbeiten wird geöffnet...
NewLibraryWizard.text.SwitchPerspective=Dieser Dateityp ist mit der Perspektive {0} verknüpft. Möchten Sie nun zu dieser Perspektive wechseln?
NewLibraryWizard.title.Choose=Wählen Sie aus, wie die Bibliothek erstellt werden soll.
NewLibraryWizard.title.Error=Fehler
NewLibraryWizard.title.New=Neue Bibliothek
NewLibraryWizard.title.Report=Neue Bibliothek
NewLibraryWizard.title.ReportWizard=Bibliotheksassistent
NewLibraryWizard.title.Template=TemplateChoicePage
NewLibraryWizard.title.WizardPage=WizardPage
NewLibraryWizard.widowTitle.new=Neu
NewLibraryWizard.wizardPageTitle.report=Bibliothek

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=Im Dateisystem wird Groß- und Kleinschreibung nicht unterschieden. Es ist bereits ein Projekt vorhanden, dessen Benennung zu ''{0}'' im Widerspruch steht.
NewReportProjectWizard.description=Erstellt ein neues Berichtprojekt.
NewReportProjectWizard.errorMessage=Beim Erstellen des neuen Berichtprojekts ist ein Fehler aufgetreten.
NewReportProjectWizard.errorOpeningWindow=Beim Öffnen eines Fensters ist ein Fehler aufgetreten.
NewReportProjectWizard.internalError=Interner Fehler: {0}
NewReportProjectWizard.javaProject=Java-Projekt erstellen
NewReportProjectWizard.perspSwitchMessage=Diese Art von Projekt ist mit der Perspektive {0} verknüpft. Jetzt zu dieser Perspektive wechseln?
NewReportProjectWizard.perspSwitchTitle=Wechsel der Perspektive bestätigen
NewReportProjectWizard.projectSetting=Projekteinstellung
NewReportProjectWizard.src=src
NewReportProjectWizard.title=Berichtprojekt
NewReportProjectWizard.windowTitle=Neues Berichtprojekt

###########################################################
#NewReportWizard properties

NewReportWizard.choicePageTitle.report=Bericht
NewReportWizard.displayName.NewReportFileExtension=.rptdesign
NewReportWizard.displayName.NewReportFileNamePrefix=new_report
NewReportWizard.error.NoProject=Kein geöffnetes Projekt im Arbeitsbereich vorhanden. Erstellen Sie ein neues Projekt über "Datei -> Neu -> Projekt", oder öffnen Sie ein vorhandenes Projekt.
NewReportWizard.pageDescription.createNewReport=Neuen Bericht erstellen
NewReportWizard.pageDescription.selectReportTemplate=Bericht zum Kopieren auswählen
NewReportWizard.taskName.openFileForEdit=Datei zum Bearbeiten wird geöffnet...
NewReportWizard.text.ConfirmSwitchPerspective=Wechsel der Perspektive bestätigen
NewReportWizard.text.Container=Behälter "
NewReportWizard.text.CreateReport=Neuen Bericht erstellen
NewReportWizard.text.Creating=Wird erstellt 
NewReportWizard.text.DoesNotExist=" existiert nicht.
NewReportWizard.text.OpenFileForEditing=Datei zum Bearbeiten wird geöffnet...
NewReportWizard.text.SelectTemplate=Bericht zum Kopieren auswählen
NewReportWizard.text.SwitchPerspective=Dieser Dateityp ist mit der Perspektive {0} verknüpft. Möchten Sie nun zu dieser Perspektive wechseln?
NewReportWizard.title.Choose=Wählen Sie aus, wie der Bericht erstellt werden soll.
NewReportWizard.title.Error=Fehler
NewReportWizard.title.New=Neuer Bericht
NewReportWizard.title.Report=Neuer Bericht
NewReportWizard.title.ReportWizard=Berichtsassistent
NewReportWizard.title.Template=TemplateChoicePage
NewReportWizard.title.WizardPage=WizardPage
NewReportWizard.widowTitle.new=Neu


###########################################################
#NewResourceFileDialog properties

NewResourceFileDialog.label.NewFile=Neuer Dateiname:
NewResourceFileDialog.ErrorMessage=Dateiname muss auf ".properties" enden.
NewResourceFileDialog.ErrorMessageInvalid=Ungültiger Dateiname

###########################################################
#ProjectFileDialog properties

ProjectFileDialog.ErrorMessage=Datei muss eine Datei sein, kein Verzeichnis.
ProjectFileDialog.Title=Projektdatei wählen
ProjectFileDialog.Message=Wählen Sie eine Datei im aktuellen Projekt.

###########################################################
#NewSectionDialog properties

NewSectionDialog.displayname.Container=Behälter
NewSectionDialog.displayname.Data=Daten
NewSectionDialog.displayname.Grid=Raster
NewSectionDialog.displayname.Image=Bild
NewSectionDialog.displayname.Label=Beschriftung
NewSectionDialog.displayname.Line=Linie
NewSectionDialog.displayname.List=Liste
NewSectionDialog.displayname.Rectangle=Rechteck
NewSectionDialog.displayname.Table=Tabelle
NewSectionDialog.displayname.Text=Text
NewSectionDialog.text.Prefix=Verfügbare Bereiche:
NewSectionDialog.title.insertElement=Element einfügen
NewSectionDialog.Title=Element einfügen

###########################################################
#NewTemplateWizard properties

NewTemplateWizard.displayName.NewReportFileNamePrefix=NEUE_VORLAGE
NewTemplateWizard.pageDescription.createNewTemplate=Neue Berichtvorlage erstellen
NewTemplateWizard.text.CreateReport=Neue Vorlage erstellen
NewTemplateWizard.text.Creating=Wird erstellt
NewTemplateWizard.text.OpenFileForEditing=Vorlagendatei wird zum Bearbeiten geöffnet...
NewTemplateWizard.title.New=Neue Vorlage
NewTemplateWizard.title.Report=Neuer Bericht
NewTemplateWizard.title.Template=Neue Vorlage
NewTemplateWizard.title.WizardPage=WizardPage

###########################################################
#NoneAction properties

NoneAction.text=Keine

###########################################################
#OutputColumnDefnPage properties

OutputColumnDefnPage.description=Definition für Ausgabespalten eingeben, die vom Abrufskript erstellt werden: 
OutputColumnDefnPage.OutputColumns.Tooltip=Spalten innerhalb einer Datenzeile anzeigen und definieren 

###########################################################
#OutputColumnPage properties

OutputColumnPage.OutputColumns.Tooltip=Spalten innerhalb einer Datenzeile anzeigen und definieren 
OutputColumnPage.toolTipText.Edit=Ausgabespalte bearbeiten
OutputColumnPage.title.OutputColumnInputDialog=Ausgabespalte

###########################################################
#OutputColumnsPage properties

OutputColumnsPage.description=Ausgabespalten definieren:

###########################################################
#PageBreakPreferencePage properties

PageBreakPreferencePage.displayname.Title=Seitenumbruch

###########################################################
#PageSetAction properties

PageSetAction.text.code=&Skript
PageSetAction.Text.EditCode=&Skript bearbeiten...
PageSetAction.text.layout=&Layout
PageSetAction.text.master=&Master
PageSetAction.text.normal=&Normal
PageSetAction.text.preview=&Vorschau

###########################################################
#PageSetupOutlineProcess properties

PageSetupOutlineProcess.action.Edit=Seiteneinrichtung bearbeiten
PageSetupOutlineProcess.action.New=Neue MasterPage
PageSetupOutlineProcess.text.Display=Zeigt das Dialogfeld zur Seiteneinrichtung an
PageSetupOutlineProcess.text.Switch=Wechselt zum Seiten-Master-Editor

###########################################################
#ParameterDialog properties

ParameterDialog.Boolean.False=False
ParameterDialog.Boolean.True=True
ParameterDialog.Button.ChangeFormat=&Ändern...
ParameterDialog.Button.CreateDataSet=&Neu erstellen...
ParameterDialog.Button.ImportValue=&Werte importieren...
ParameterDialog.Button.RemoveDefault=Standard entfernen
ParameterDialog.Button.SetDefault=&Als Standard einstellen
ParameterDialog.CheckBox.AllowBlank=&Leerwerte zulassen
ParameterDialog.CheckBox.AllowNull=&Nullwert zulassen
ParameterDialog.CheckBox.DoNotEchoInput=&Keine Wiedergabe auf Eingabe
ParameterDialog.CheckBox.Hidden=&Ausgeblendet
ParameterDialog.CheckBox.Sort=&Bei Aufforderung alphabetisch sortieren
ParameterDialog.Choice.NoDefault=Kein Standardwert
ParameterDialog.Column.Default=Standard
ParameterDialog.Column.DisplayText=Angezeigter Text
ParameterDialog.Column.Value=Wert
ParameterDialog.DisplayLabel.Combo=Kombinationsfeld
ParameterDialog.DisplayLabel.List=Listenfeld
ParameterDialog.ErrorMessage.CanootBeBlank=Der Wert darf nicht leer sein.
ParameterDialog.ErrorMessage.CanootBeNull=Der Wert darf nicht Null sein.
ParameterDialog.ErrorMessage.DuplicatedLabel=Der Anzeigetext ist bereits vorhanden.
ParameterDialog.ErrorMessage.DuplicatedName=Der Name wird bereits verwendet.
ParameterDialog.ErrorMessage.DuplicatedValue=Der Wert existiert bereits.
ParameterDialog.ErrorMessage.EmptyName=Name ist leer.
ParameterDialog.ErrorMessage.InvalidListLimit=Der Begrenzungswert sollte zwischen 0 und {0} liegen.
ParameterDialog.ErrorMessage.MismatchDataType=Der Wert stimmt nicht mit dem Datentyp überein.
ParameterDialog.ErrorMessage.NoAvailableColumn=Es ist keine Spalte verfügbar.
ParameterDialog.ErrorMessage.NoDefaultValue=Sie müssen einen Standardwert angeben.
ParameterDialog.ErrorTitle.InvalidListLimit=Listenbegrenzung ungültig
ParameterDialog.Flag.Default=Standard
ParameterDialog.Group.MoreOption=Anzeigen als
ParameterDialog.Group.Properties=Eigenschaften
ParameterDialog.Label.DataType=&Datentyp:
ParameterDialog.SelectionDialog.Edit=Auswahl bearbeiten
ParameterDialog.Label.DefaultValue=&Standardwert:
ParameterDialog.Label.DisplayPrompt=Anzeige-Aufforderung:
ParameterDialog.Label.DisplayType=&Anzeigetyp:
ParameterDialog.Label.Format=For&matieren als:
ParameterDialog.Label.HelpText=&Hilfetext:
ParameterDialog.Label.ListOfValue=Werteliste:
ParameterDialog.Label.Name=&Name:
ParameterDialog.Label.None=<Keine>
ParameterDialog.Label.Null=Null
ParameterDialog.Label.Preview=Vorschau mit Format
ParameterDialog.Label.PromptText=&Aufforderungstext:
ParameterDialog.Label.SelectDataSet=&Datensatz:
ParameterDialog.SelectionDialog.New=Neue Auswahl
ParameterDialog.Label.SelectDisplayText=&Anzeigetext auswählen:
ParameterDialog.Label.SelectValueColumn=&Wertespalte auswählen:
ParameterDialog.Label.Value=Auswahlwerte:
ParameterDialog.Label.values=Werte
ParameterDialog.Label.Sample=Beispiel
ParameterDialog.Label.Listlimit=L&istenbegrenzung:
ParameterDialog.Radio.Dynamic=D&ynamisch
ParameterDialog.Radio.Static=&Statisch
ParameterDialog.toolTipText.OpenExprButton=Ausdruckserstellung öffnen

###########################################################
#ParameterDropListener properties

ParameterDropListener.Command.Copy=Element kopieren
ParameterDropListener.Command.Move=Element verschieben

###########################################################
#ParameterGroupDialog properties

ParameterGroupDialog.Page.Title=Allgemein
ParameterGroupDialog.pageTitle.general=Allgemein

###########################################################
#ParameterGroupGeneralPage properties

ParameterGroupGeneralPage.Label.DisplayName=&Anzeigename:
ParameterGroupGeneralPage.Label.Name=&Name:

###########################################################
#ParameterGroupNodeProvider properties

ParameterGroupNodeProvider.Action.GroupNew=Neue Parametergruppe
ParameterGroupNodeProvider.Action.ParameterEdit=Bearbeiten
ParameterGroupNodeProvider.Action.ParameterNew=Neuer Parameter
ParameterGroupNodeProvider.Dialogue.ParameterEdit=Parametergruppe bearbeiten
ParameterGroupNodeProvider.Dialogue.ParameterNew=Neuer Parameter
ParameterGroupNodeProvider.Node.Group=Parametergruppe

###########################################################
#ParameterGroupProcess properties

ParameterGroupProcess.action.Delete=Parametergruppe löschen
ParameterGroupProcess.action.Edit=Parametergruppe bearbeiten
ParameterGroupProcess.action.New=Neuer Parameter
ParameterGroupProcess.text.DisplayName=ParameterGroup
ParameterGroupProcess.text.Show=Blendet die Datenquelleditor-Seite ein  

###########################################################
#ParameterNodeProvider properties

ParameterNodeProvider.dial.title.editCascading=Überlappenden Parameter bearbeiten
ParameterNodeProvider.dial.title.editScalar=Parameter bearbeiten
ParameterNodeProvider.dial.title.newCascading=Neuer Verschachtelungsparameter                                       
ParameterNodeProvider.menu.text.edit=Bearbeiten
ParameterNodeProvider.menu.text.new=Neuer Parameter

###########################################################
#ParameterProcess properties

ParameterProcess.action.Delete=Parameter löschen
ParameterProcess.action.Edit=Parameter bearbeiten
ParameterProcess.text.DisplayName=Parameter
ParameterProcess.text.Show=Blendet die Datenquelleditor-Seite ein  

###########################################################
#parameters properties

parameters.datatypes.boolean=Boolesch
parameters.datatypes.dateTime=DATETIME
parameters.datatypes.decimal=Dezimal
parameters.datatypes.float=FLOAT
parameters.datatypes.string=Zeichenfolge
parameters.menuItem.refresh=Aktualisieren

###########################################################
#ParametersNodeProvider properties

ParametersNodeProvider.dialogue.title.group=Neue Parametergruppe
ParametersNodeProvider.dialogue.title.parameter=Neuer Parameter
ParametersNodeProvider.menu.text.cascadingParameter=Neuer Verschachtelungsparameter
ParametersNodeProvider.menu.text.group=Neue Parametergruppe
ParametersNodeProvider.menu.text.parameter=Neuer Parameter

###########################################################
#ParametersOutlineProcess properties

ParametersOutlineProcess.action.Edit=Bearbeiten
ParametersOutlineProcess.action.New=Neuer Parameter
ParametersOutlineProcess.action.NewGroup=Neue Gruppe
ParametersOutlineProcess.text.Open=Parameter-Editor öffnen
ParametersOutlineProcess.text.Show=Blendet die Datensatzeditor-Seite für den Datensatz ein

###########################################################
#PasteAction properties

PasteAction.text=&Einfügen

###########################################################
#PlaceHolderEditPart properties

PlaceHolderEditPart.Trans.TransferToElement=An Berichtobjekt übertragen

###########################################################
#PreviewAction properties

PreviewAction.Text=Vorschau

###########################################################
#PreviewEditor properties

PreviewEditor.parameter.tooltip=Berichtparameter anzeigen

###########################################################
#PreviewPageAction properties

PreviewPageAction.actionText.preview=Vorschau

###########################################################
#PropertiesAction properties

PropertiesAction.Text=Eigenschaften

###########################################################
#PropertyHandleTableViewer properties

PropertyHandleTableViewer.Button.New=&Neu...
PropertyHandleTableViewer.Button.Edit=&Bearbeiten...
PropertyHandleTableViewer.Button.Remove=&Entfernen
PropertyHandleTableViewer.Button.Up=&Nach oben
PropertyHandleTableViewer.Button.Down=&Nach unten
PropertyHandleTableViewer.Menu.Remove=Entfernen
PropertyHandleTableViewer.Menu.Up=Nach oben
PropertyHandleTableViewer.Menu.Down=Nach unten
PropertyHandleTableViewer.Menu.RemoveAll=Alles entfernen

###########################################################
#PropertyHandleInputDialog properties

PropertyHandleInputDialog.Action.New=Neu
PropertyHandleInputDialog.Action.Edit=Bearbeiten
PropertyHandleInputDialog.messages.error.blankProperty={0} darf nicht leer sein

###########################################################
#PublishTemplateAction properties

PublishTemplateAction.wizard.page.browse.cheatsheet.title=Wählen Sie eine Datei für den Spickzettel
PublishTemplateAction.wizard.page.browse.title=Wählen Sie eine Bilddatei
PublishTemplateAction.wizard.page.btn.browse=&Durchsuchen...
PublishTemplateAction.wizard.page.cheatsheetError=Die Spickzetteldatei ''{0}'' existiert nicht.
PublishTemplateAction.wizard.page.desc=In Vorlagenordner veröffentlichen.
PublishTemplateAction.wizard.page.imageError=Die Bilddatei ''{0}'' existiert nicht.
PublishTemplateAction.wizard.page.label.cheatsheet=Datei für Spickzettel:
PublishTemplateAction.wizard.page.label.description=&Beschreibung:
PublishTemplateAction.wizard.page.label.displayName=&Anzeigename:
PublishTemplateAction.wizard.page.label.image=&Vorlagenbild:
PublishTemplateAction.wizard.page.title=In Vorlagenordner veröffentlichen
PublishTemplateAction.wizard.title=In Vorlagenordner veröffentlichen
PublishTemplateAction.wizard.errorTitle=Fehler
PublishTemplateAction.wizard.message=Die Vorlage kann nicht in dem Verzeichnis veröffentlich werden, in dem sie sich befindet. Wählen Sie ein anderes Verzeichnis für die Veröffentlichung.
PublishTemplateAction.wizard.notvalidfolder=Der in den Voreinstellungen festgelegte Vorlagenordner ist ungültig.
PublishTemplateAction.wizard.page.nameInfo=Anzeigename erforderlich
PublishTemplateAction.wizard.message.SourceFileNotExist=Die Quelldatei ist nicht vorhanden.
PublishTemplateAction.wizard.message.PreviewImageNotExist=Vorschaubilddatei nicht vorhanden.
PublishTemplateAction.wizard.message.PreviewImageNotValid=Die Vorschaubilddatei ist kein gültiges Bild.

###########################################################
#PublishLibraryAction properties
PublishLibraryAction.wizard.errorTitle=Fehler
PublishLibraryAction.wizard.message=Die Bibliothek kann nicht in dem Verzeichnis veröffentlicht werden, in dem sie sich befindet. Wählen Sie zur Veröffentlichung ein anderes Verzeichnis.
PublishLibraryAction.wizard.message.SourceFileNotExist=Die Quelldatei ist nicht vorhanden.
PublishLibraryAction.wizard.notvalidfolder=Der in der Einstellung definierte Berichtordner ist ungültig.

###########################################################
#RedoAction properties

RedoAction.Tooltip={0} wiederherstellen

###########################################################
#ExportReportWizard
ExportToLibraryAction.wizard.windowTitle=Exportieren
ExportToLibraryAction.wizard.page.title=Datei in Bibliothek exportieren
ExportToLibraryAction.wizard.page.desc=Berichtdesign in Bibliothek exportieren
ExportToLibraryAction.wizard.page.label.filename=&Dateiname:
ExportToLibraryAction.wizard.page.label.folder=&Ordner:
ExportToLibraryAction.wizard.page.button.browser=&Durchsuchen...
ExportToLibraryAction.wizard.page.dirdialog.message=Wählen Sie das Verzeichnis mit den Dateiinhalten aus.
ExportToLibraryAction.wizard.page.nameempty=Dateiname muss angegeben werden.
ExportToLibraryAction.wizard.page.folderempty=Ordner muss angegeben werden.
ExportToLibraryAction.wizard.page.foldererror=Der angegebene Ordner ist nicht vorhanden.

###########################################################
#PublishLibraryToResourceFolderAction
PublishLibraryToResourceFolderAction.Action.Text=Bibliothek in Ressourcenordner aufnehmen...

###########################################################
#PublishTemplateViewAction
DefaultNodeProvider.template.suffix=.rpttemplate
PublishTemplateViewAction.action.displaytext=Vorlage mit Assistent für neuen Bericht registrieren...

###########################################################
#RefreshModuleHandleAction
RefreshModuleHandleAction.Action.Text=Bibliothek aktualisieren

###########################################################
#ReferencePage properties

ReferencePage.Button.Edit=&Bearbeiten...
ReferencePage.Label.Source=&Quelle:

###########################################################
#RefreshAction properties

RefreshAction.text=Aktualisieren

###########################################################
#RefreshLibExplorerAction properties

RefreshLibExplorerAction.Text=Aktualisieren

###########################################################
#RemoveLibraryAction properties

RemoveLibraryAction.Text=Bibliothek entfernen

###########################################################
#RenameAction properties

RenameAction.text=Umbenennen

###########################################################
#RenameDialog properties

RenameDialog.action.Cancel=Abbrechen
RenameDialog.action.Ok=\\ \\ OK  
RenameDialog.text.NewName=Neuer Name:
RenameDialog.text.Rename=Umbenennen 
RenameDialog.text.ToolTip=Name darf nicht leer sein

###########################################################
#RenameInlineTool properties

RenameInlineTool.DialogTitle.RenameFailed=Umbenennen fehlgeschlagen
RenameInlineTool.TransLabel.Rename=Umbenennen

###########################################################
#RenameInputDialog properties

RenameInputDialog.DialogTitle=Eingabe umbenennen
RenameInputDialog.DialogMessage=Geben Sie den neuen Namen ein.

###########################################################
#report properties

report.designer.ui.preferences.buttonadd=&Hinzufügen...
report.designer.ui.preferences.buttonremove=&Entfernen
report.designer.ui.preferences.buttonremoveall=&Alles entfernen
report.designer.ui.preferences.dialogtitle=Bibliotheken öffnen
report.designer.ui.preferences.errormessage=Die Bibliothek ist bereits vorhanden.
report.designer.ui.preferences.errortitle=Fehler
report.designer.ui.preferences.extensions=*.rptlibrary
report.designer.ui.preferences.labeltitle=Bibliotheken hinzufügen oder entfernen
report.designer.ui.preferences.library.export.overwrite.always=&Immer
report.designer.ui.preferences.library.export.overwrite.never=&Nie
report.designer.ui.preferences.library.export.overwrite.prompt=&Eingabeaufforderung
report.designer.ui.preferences.library.export.title=Vorhandenes Element beim Exportieren des Designelements in die Bibliothek überschreiben.
report.designer.ui.preferences.template.openDialogTitle=Wählen Sie einen Ordner für die Vorlagen.
report.designer.ui.preferences.template.select=&Auswählen...
report.designer.ui.preferences.template.templatedir=Vorlagen
report.designer.ui.preferences.template.templatefolder= &Vorlagenordner
report.designer.ui.preferences.template.title=Wählen Sie den Vorlagenordner.
org.eclipse.birt.report.designer.ui.preference.commenttemplates.enablecomment=Kommentar beim Erstellen eines Berichtdesigns erzeugen
org.eclipse.birt.report.designer.ui.preference.commenttemplates.defaultcomment=Copyright (c) 2006 <<Name Ihrer Firma>>

###########################################################
#Resource Preference page properties
ResourecePreferencePage.title=Wählen Sie den Standard-Ressourcenordner für Bibliotheks-Explorer, Bilder, Eigenschaftendateien usw. aus.
ResourecePreferencePage.folder=&Ressourcenordner
ResourecePreferencePage.select=&Auswählen...
ResourecePreferencePage.openDialogTitle=Nach Ordner suchen
ResourecePreferencePage.openDialogMessage=Wählen Sie den Standard-Ressourcenordner:
ResourecePreferencePage.defaultResourceFolder.dispaly=<Current Project Folder>

###########################################################
#ReportAdvancedLauncherTab properties

ReportAdvancedLauncherTab.DefaultsButtonText=&Standardwerte wiederherstellen
ReportAdvancedLauncherTab.DeselectButtonText=&Markierung aufheben
ReportAdvancedLauncherTab.Name=Berichtprojekte
ReportAdvancedLauncherTab.SelectAllButtonText=&Alles markieren
ReportAdvancedLauncherTab.UseListRadioText=Wählen Sie aus der Liste die zu startenden Projekte aus.
ReportAdvancedLauncherTab.VisibleLabelText=&Verfügbare Projekte
ReportAdvancedLauncherTab.WorkspaceReportProjects=Berichtprojekte im Arbeitsplatz

###########################################################
#ReportClasspathLaucnTab properties

ReportClasspathLaucnTab.DefaultButtonText=&Standardwerte wiederherstellen
ReportClasspathLaucnTab.DeselectButtonText=&Markierung aufheben
ReportClasspathLaucnTab.Name=Java-Projekte
ReportClasspathLaucnTab.SelectAllButtonText=&Alles markieren
ReportClasspathLaucnTab.UseListRadioText=Wählen Sie aus der Liste ein zu startendes Projekt. Das Klassen-Ausgabeverzeichnis des gewählten Projekts wird dem Pfad für die Klasse hinzugefügt.
ReportClasspathLaucnTab.VisibleLabelText=&Verfügbare Projekte
ReportClasspathLaucnTab.WorkspaceJavaProjects=Java-Projekte im Arbeitsplatz

###########################################################
#ReportCreationTool properties

ReportCreationTool.ModelTrans.CreateElement=Element einfügen

###########################################################
#ReportEditor properties

ReportEditor.Button.Close=Schließen
ReportEditor.Button.Save=Speichern
ReportEditor.Dlg.Confirm=Die Datei wurde aus dem Dateisystem gelöscht. Möchten Sie Ihre Änderungen speichern oder den Editor ohne zu speichern schließen?
ReportEditor.Dlg.Save=Speichern ...
ReportEditor.error.activated.outofsync.message=Die Datei wurde im Dateisystem geändert. Sollen die Änderungen geladen werden?
ReportEditor.error.activated.outofsync.title=Datei geändert
ReportEditor.Error.Open=Fehler beim Öffnen
ReportEditor.Error.OpenEditor=Datei kann nicht geöffnet werden.
ReportEditor.Page.Code=Skript
ReportEditor.Page.Layout=Layout
ReportEditor.Page.MasterPage=MasterPage
ReportEditor.Page.Preview=Vorschau
ReportEditor.Page.PreviewSaveMessage=Die Berichtdatei wurde geändert. Möchten Sie sie vor dem Anzeigen der Vorschau speichern?
ReportEditor.Page.PreviewSaveTitle=Speichern
ReportEditor.Page.PreviewSaveToggle=Datei immer vor der Vorschau speichern.

###########################################################
#ReportLaunchConfigurationDelegate properties

ReportLaunchConfigurationDelegate.badFeatureSetup=Fehlerhafte Einstellungen für Funktion
ReportLaunchConfigurationDelegate.noStartup=Kein Autostart

###########################################################
#ReportPage properties
ReportPage.text.Add=&Hinzufügen...
ReportPage.text.Browse=&Durchsuchen...
ReportPage.title.Location=Speicherort:
ReportPage.title.setPrewImg=Wählen Sie eine Bilddatei
ReportPage.text.Resource.Add=&Hinzufügen...
ReportPage.text.Thumbnail=&Miniatur...

###########################################################
#ReportPageGenerator properties

ReportPageGenerator.List.Comments=Kommentare
ReportPageGenerator.List.Description=Beschreibung
ReportPageGenerator.List.EventHandler=Ereignis-Handler
ReportPageGenerator.List.General=Allgemein
ReportPageGenerator.List.Measurement=Maßeinheit
ReportPageGenerator.List.NamedExpressions=Benannte Ausdrücke
ReportPageGenerator.List.UserProperties=Benutzereigenschaften
ReportPageGenerator.List.Resources=Ressourcen
ReportPageGenerator.List.Resources.JarFile=JAR-Dateien:
ReportPageGenerator.List.AdvancedProperty=Erweitert

#OdaDataSourceGenerator properties
DataSourcePageGenerator.List.General=Allgemein

#OdaDataSetGenerator properties
DataSetPageGenerator.List.General=Allgemein
DataSetPageGenerator.DataSourceName=&Datenquelle

#ScalarParameterPageGenerator properties
ScalarParameterPageGenerator.List.General=Allgemein
ScalarParameterPageGenerator.List.I18n=Lokalisierung

#TemplateReportItemPageGenerator properties
TemplateReportItemPageGenerator.List.General=Allgemein
TemplateReportItemPage.description.Label.Instructions=&Anweisungen:
TemplateReportItemPageGenerator.List.I18n=Lokalisierung
TemplateReportItemPageGenerator.List.TextKey=Textschlüssel:

###########################################################
#ReportPropertySheetPage properties

ReportPropertySheetPage.Column.Title.Property=Eigenschaft
ReportPropertySheetPage.Column.Title.Value=Wert
ReportPropertySheetPage.Root.Default.Title=Info

###########################################################
#ReportTemplateTransferDropTargetListener properties

ReportTemplateTransferDropTargetListener.ModelTrans.CreateElement=Element erstellen
ReportTemplateTransferDropTargetListener.transLabel.createElement=Element einfügen

###########################################################
#ResourceEditDialog properties

ResourceEditDialog.message.AddNote=Beim schnellen Hinzufügen wird der Schlüssel in der aktuellen Ressourcendatei gespeichert.
ResourceEditDialog.message.ResourceFile=Ressourcendatei: 
ResourceEditDialog.text.Add=Hinzufügen
ResourceEditDialog.text.AddWarningMsg=Leere Schlüssel sind nicht zulässig.
ResourceEditDialog.text.AddWarningTitle=Warning
ResourceEditDialog.text.Delete=Löschen
ResourceEditDialog.text.Key=Schlüssel
ResourceEditDialog.text.QuickAdd=Schnelles Hinzufügen
ResourceEditDialog.text.Value=Wert

###########################################################
#ResourceKeyDescriptor properties

ResourceKeyDescriptor.text.Reset=Zurücksetzen
ResourceKeyDescriptor.title.SelectKey=Schlüssel auswählen

###########################################################
#RevertToReportItemAction properties

RevertToReportItemAction.text=&Auf Berichtobjekt zurücksetzen

###########################################################
#RevertToTemplateAction properties

RevertToTemplateAction.text=Zu Vorlagenobjekt zurück&verwandeln

###########################################################
#RowHandle properties

RowHandle.tooltip.GridRow=Raster - Zeile
RowHandle.tooltip.GroupFooter=Tabellengruppe – Gruppenfußzeile
RowHandle.tooltip.GroupHeader=Tabellengruppe – Gruppenkopfzeile
RowHandle.tooltip.TableDetail=Tabelle - Detail
RowHandle.tooltip.TableFooter=Tabelle - Fußzeile
RowHandle.tooltip.TableHeader=Tabelle - &Kopfzeile

###########################################################
#RowHandleAdapter properties

RowHandleAdapter.table.detail=Detailzeile
RowHandleAdapter.table.footer=Fußzeile
RowHandleAdapter.table.groupFooter=Gruppenfußzeile
RowHandleAdapter.table.groupHeader=Gruppenkopfzeile
RowHandleAdapter.table.header=Kopfzeile

###########################################################
#RowPageGenerator properties

RowPageGenerator.List.Bookmark=Lesezeichen
RowPageGenerator.List.Borders=Rahmen
RowPageGenerator.List.Section=Seitenumbruch
RowPageGenerator.List.CellPadding=Zellfüllung
RowPageGenerator.List.Font=Schriftart
RowPageGenerator.List.General=Allgemein
RowPageGenerator.TabItem.Highlights=Kennzeichnungen
RowPageGenerator.TabItem.map=Zuordnung
RowPageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#RowProvider properties

RowProvider.action.text.above=Zeile &oben einfügen
RowProvider.action.text.below=Zeile &unten einfügen

###########################################################
#SaveAsDialog properties

SaveAsDialog.message=Speichern Sie die Datei an einem anderen Ort.
SaveAsDialog.overwriteQuestion=The file ''{0}'' already exists. Do you want to replace the existing file?
SaveAsDialog.Question=Frage
SaveAsDialog.text=Speichern unter
SaveAsDialog.title=Speichern unter

###########################################################
#CreateDirectory properties
DirectoryDialog.createQuestion=Das Verzeichnis ''{0}'' ist nicht vorhanden. Möchten Sie es erstellen?
DirectoryDialog.Question=Frage

###########################################################
#SchematicContextMenuProvider properties

SchematicContextMenuProvider.ActionText.editData=&Wert/Ausdruck bearbeiten\u2026
SchematicContextMenuProvider.ActionText.editLabel=&Bearbeiten
SchematicContextMenuProvider.Menu.Apply=&Stil anwenden...
SchematicContextMenuProvider.Menu.EditGroup=Gru&ppe bearbeiten
SchematicContextMenuProvider.Menu.Insert=E&infügen
SchematicContextMenuProvider.Menu.insertElement=&Einfügen
SchematicContextMenuProvider.Menu.insertRow=&Zeile
SchematicContextMenuProvider.Menu.List=Liste
SchematicContextMenuProvider.Menu.Show=Anzeigen
SchematicContextMenuProvider.Menu.Style=S&til
SchematicContextMenuProvider.Menu.Theme=The&ma
SchematicContextMenuProvider.menutitle.applystylerule=Stil anwenden
SchematicContextMenuProvider.menutitle.applythemerule=Thema verwenden
SchematicContextMenuProvider.menutitle.editgroup=Gruppe bearbeiten
SchematicContextMenuProvider.menutitle.insert=Einfügen
SchematicContextMenuProvider.menutitle.list=Liste
SchematicContextMenuProvider.menutitle.show=Anzeigen
SchematicContextMenuProvider.menutitle.style=Stil
SchematicContextMenuProvider.Menu.EditStyle=S&til bearbeiten
SchematicContextMenuProvider.Menu.DeleteStyle=&Stil löschen
SchematicContextMenuProvider.Menu.DeleteGroup=Gruppe &löschen
SchematicContextMenuProvider.Menu.InsertGroupHeaderFooter=Gru&ppenkopfzeile/-fußzeile einfügen
SchematicContextMenuProvider.Menu.NewStyle=Neuer St&il

###########################################################
#SectionProcess properties

SectionProcess.action.Clear=Löschen
SectionProcess.action.Delete=Löschen
SectionProcess.action.DeleteRow=Zeile löschen
SectionProcess.action.New=Neu
SectionProcess.action.NewCell=Neue Zelle
SectionProcess.action.NewGroup=Neue Gruppe
SectionProcess.action.NewRow=Neue Zeile
SectionProcess.action.NewSection=Neuer Bereich
SectionProcess.action.NewSubSection=Neuer Teilbereich
SectionProcess.displayname.GridProcess=Raster
SectionProcess.displayname.GroupProcess=Gruppe
SectionProcess.displayname.ListProcess=Liste
SectionProcess.displayname.TableProcess=Tabelle
SectionProcess.displayname.TableRowProcess=Zeile
SectionProcess.type.Container=(Behälter)
SectionProcess.type.Data=(Daten)
SectionProcess.type.Image=(Bild)
SectionProcess.type.Label=(Beschriftung)
SectionProcess.type.List=(Liste)
SectionProcess.type.Prefix=Spalte
SectionProcess.type.Table=(Tabelle)
SectionProcess.type.Text=(Text)

###########################################################
#SelectAllAction properties

SelectAllAction.text=&Alles markieren

###########################################################
#SelectCssStyleWizard properties

SelectCssStyleWizard.wizard.title=CSS-Stile importieren
SelectCssStyleWizard.wizardPage.description=Wählen Sie eine CSS-Datei, und importieren Sie die Stile in das Berichtdesign.
SelectCssStyleWizard.wizardPage.name=CSS-Stile auswählen
SelectCssStyleWizard.wizardPage.title=Stile aus CSS-Datei importieren

###########################################################
#SelectValueDialog properties

SelectValueDialog.errorRetrievinglist=Fehler beim Abrufen der Liste
SelectValueDialog.messages.info.selectVauleUnavailable=Die den Ausdrücken zugeordneten Wertlisten können nur für Ausdrücke im Format "Reihe["Name"]", "Reihe[Index]" und "Reihe.Name" abgerufen werden. 
SelectValueDialog.messages.error.selectVauleUnavailable=Der Wert für den Ausdruck kann nicht abgerufen werden.
SelectValueDialog.noExpressionSet=Ein Ausdruck wurde nicht festgelegt
SelectValueDialog.retrieving=Liste wird abgerufen ...
SelectValueDialog.selectValue=Wert auswählen

###########################################################
#SetConstraintCommand properties

SetConstraintCommand.Error.SetConstraintError=Beim Festlegen einer Einschränkung für das Modell ist ein Fehler aufgetreten.
SetConstraintCommand.transLabel.setConstraint=Einschränkung festlegen

###########################################################
#ShowPropertyAction properties

ShowPropertyAction.text=Eigenschaften

###########################################################
#SortingHandleProvider properties

SortingHandleProvider.Label.SortOn=Sortieren nach:

###########################################################
#Spinner properties

Spinner.DialogTitle.InvalidNumber=Invalid number

###########################################################
#SplitAction properties

SplitAction.actionMsg.splitCells=&Zelle teilen

###########################################################
#StyleBuilder properties

StyleBuilder.action.Apply=&Anwenden
SytleBuilder.DialogTitle.New=Neuer Stil
SytleBuilder.DialogTitle.Edit=Stil bearbeiten

###########################################################
#StyleComboProvider properties

StyleComboProvider.LineStyle.None=Kein Stil

###########################################################
#StyleNodeProvider properties

StyleNodeProvider.action.Edit=Stil b&earbeiten...
StyleNodeProvider.action.New=&Neuer Stil...

###########################################################
#StyleProcess properties

StyleProcess.action.Delete=Stil löschen
StyleProcess.action.Edit=Stil b&earbeiten...
StyleProcess.action.New=&Neuer Stil...
StyleProcess.text.CannotDelete=Der Standardstil kann nicht gelöscht werden. 
StyleProcess.text.Show=Blendet den Datensatzeditor für den Datensatz ein.

###########################################################
#StylesNodeProvider properties

StylesNodeProvider.action.New=Neuer Stil...

###########################################################
#StylesOutlineProcess properties

StylesOutlineProcess.action.New=Neuer Stil...

###########################################################
#TableBandProvider properties

TableBandProvider.action.text.group=Gruppe einfügen
TableBandProvider.action.text.row=Zeile einfügen

###########################################################
#TableEditPart properties

TableEditPart.GUIDEHANDLE_TEXT = Tabelle
TableEditPart.Label.Merge=Merge Cells
TableEditPart.Label.ResizeColumn=Spaltengröße anpassen
TableEditPart.Label.ResizeRow=Zeilengröße anpassen

###########################################################
#TableFigure properties

TableFigure.BORDER_TEXT=Tabelle
TableArea.Button.New=&Neu...
TableArea.Button.Edit=&Bearbeiten...
TableArea.Button.Remove=&Entfernen
TableArea.Button.Down=Nach &unten

###########################################################
#TableHandleAdapter properties

TableHandleAdapter.name.detail=Detail
TableHandleAdapter.name.footer=Fußzeile
TableHandleAdapter.name.header=Kopfzeile
TableHandleAdapter.transLabel.deleteColumn=Spalte löschen
TableHandleAdapter.transLabel.deleteColumns=Spalten löschen
TableHandleAdapter.transLabel.deleteRow=Zeile löschen
TableHandleAdapter.transLabel.deleteRows=Zeilen löschen
TableHandleAdapter.transLabel.include=Einschließen 
TableHandleAdapter.transLabel.insertColumn=Spalte einfügen
TableHandleAdapter.transLabel.insertGroup=Gruppe einfügen
TableHandleAdapter.transLabel.insertRow=Zeile einfügen
TableHandleAdapter.transLabel.notInclude=nicht einschließen 
TableHandleAdapter.transLabel.splitCells=Zelle teilen
TableHandleAdapter.transLable.deleteGroup=Tabellengruppe löschen

###########################################################
#TableOptionDialog properties

TableOptionDialog.message.RememberGrid=&Diese Dimensionen für neue Raster verwenden
TableOptionDialog.message.RememberTable=&Diese Dimensionen für neue Tabellen verwenden
TableOptionDialog.text.Column=&Anzahl der Spalten:
TableOptionDialog.text.GridRow=&Anzahl der Zeilen:
TableOptionDialog.text.GridSize=Rastergröße
TableOptionDialog.text.TableDetail=&Anzahl der Details:
TableOptionDialog.text.TableSize=Tabellengröße
TableOptionDialog.title.InsertGrid=Raster einfügen
TableOptionDialog.title.InsertTable=Tabelle einfügen
TableOptionDialog.text.DataSet=Datensatz:

###########################################################
#TablePageGenerator properties

TablePageGenerator.List.Bookmark=Lesezeichen
TablePageGenerator.List.Borders=Rahmen
TablePageGenerator.List.CellPadding=Zellfüllung
TablePageGenerator.List.Font=Schriftart
TablePageGenerator.List.General=Allgemein
TablePageGenerator.List.Marign=Rand
TablePageGenerator.List.Section=Seitenumbruch
TablePageGenerator.List.TOC=Inhaltsverzeichnis
TablePageGenerator.List.Visibility=Sichtbarkeit
TablePageGenerator.TabItem.Binding=Bindung
TablePageGenerator.TabItem.Filters=Filter
TablePageGenerator.TabItem.Groups=Gruppen
TablePageGenerator.TabItem.Highlights=Kennzeichnungen
TablePageGenerator.TabItem.map=Zuordnung
TablePageGenerator.TabItem.Sorting=Sortierung

###########################################################
#TemplateReportItemPropertiesDialog properties

TemplateReportItemPropertiesDialog.errorMessage=Eingabeaufforderung muss Text enthalten.
TemplateReportItemPropertiesDialog.errorTitle=Fehler
TemplateReportItemPropertiesDialog.group=Eigenschaften für Berichtobjekt-Vorlage
TemplateReportItemPropertiesDialog.objectType=Elementtyp:
TemplateReportItemPropertiesDialog.nameText=&Name:
TemplateReportItemPropertiesDialog.promptText=&Anweisungen:
TemplateReportItemPropertiesDialog.title=Berichtobjekt-Vorlage erstellen

###########################################################
#performCreatePlaceHolder action
performCreatePlaceHolder.errorMessage.title=Fehler
performCreatePlaceHolder.errorMessage.content=Der angegebene Name existiert bereits. Wählen Sie einen anderen Namen, oder lassen Sie das Feld leer.

###########################################################
#TogglePropertyDescriptor properties
TogglePropertyDescriptor.toolTipText.Bold=Fett
TogglePropertyDescriptor.toolTipText.Italic=Kursiv
TogglePropertyDescriptor.toolTipText.Underline=Unterstrichen
TogglePropertyDescriptor.toolTipText.Text_Line_Through=Durchgestrichener Text

###########################################################
#TextAlignPropertyDescriptor properties

TextAlignPropertyDescriptor.0=Links
TextAlignPropertyDescriptor.1=Zentrieren
TextAlignPropertyDescriptor.2=Rechts
TextAlignPropertyDescriptor.3=Blocksatz

###########################################################
#TextAreaContextMenu properties

TextAreaContextMenu.Copy.description=Kopieren
TextAreaContextMenu.Copy.image=
TextAreaContextMenu.Copy.label=&Kopieren
TextAreaContextMenu.Copy.tooltip=Kopieren
TextAreaContextMenu.Cut.description=Ausschneiden
TextAreaContextMenu.Cut.image=
TextAreaContextMenu.Cut.label=Auss&chneiden
TextAreaContextMenu.Cut.tooltip=Ausschneiden
TextAreaContextMenu.Paste.description=Einfügen
TextAreaContextMenu.Paste.image=
TextAreaContextMenu.Paste.label=&Einfügen
TextAreaContextMenu.Paste.tooltip=Einfügen
TextAreaContextMenu.Redo.description=Wiederherstellen
TextAreaContextMenu.Redo.image=
TextAreaContextMenu.Redo.label=&Wiederherstellen
TextAreaContextMenu.Redo.tooltip=Wiederherstellen
TextAreaContextMenu.SelectAll.description=Alles markieren
TextAreaContextMenu.SelectAll.image=
TextAreaContextMenu.SelectAll.label=Alles m&arkieren
TextAreaContextMenu.SelectAll.tooltip=Alles markieren
TextAreaContextMenu.Undo.description=Rückgängig
TextAreaContextMenu.Undo.image=
TextAreaContextMenu.Undo.label=&Rückgängig
TextAreaContextMenu.Undo.tooltip=Rückgängig

###########################################################
#TextDataEditPart properties

TextDataEditPart.Figure.Dafault=Dynamischer Text

###########################################################
#TextEditDialog properties

TextEditDialog.action.text.editDynamicText=Dynamischen T&ext bearbeiten
TextEditDialog.action.text.formatDateTime=Format Datum/Uhrz&eit
TextEditDialog.action.text.formatNumber=Format &Zahl
TextEditDialog.action.text.formatString=Formatzeichenfol&ge
TextEditDialog.choice.HTML=HTML/Dynamischer Text
TextEditDialog.choice.plainText=Einfacher Text
TextEditDialog.choice.Auto=Automatisch
TextEditDialog.comboText.formattingAndLayout=Formatierung und Layout
TextEditDialog.format.dynamicText=Dynamischer Text
TextEditDialog.format.formatting=Formatierung und Layout
TextEditDialog.format.lists=Listen
TextEditDialog.format.pageComposition=Seitenzusammenstellung
TextEditDialog.format.pageElements=Seitenelemente
TextEditDialog.formatChoice.content=Inhalt
TextEditDialog.formatChoice.dynamicText=Dynamischer Text
TextEditDialog.formatChoice.formatting=Formatierung
TextEditDialog.formatChoice.layout=Layout
TextEditDialog.formatChoice.lists=Listen
TextEditDialog.toolTip.tag.a=Anker
TextEditDialog.toolTip.tag.b=Textstil "Fett"
TextEditDialog.toolTip.tag.birtImage=BIRT-spezifisches Bild
TextEditDialog.toolTip.tag.br=Zeilenumbruch
TextEditDialog.toolTip.tag.center=Zentriert den Text
TextEditDialog.toolTip.tag.code=Computercode-Fragment
TextEditDialog.toolTip.tag.dd=Definitionsbeschreibung
TextEditDialog.toolTip.tag.del=Gelöschter Text
TextEditDialog.toolTip.tag.dl=Definitionsliste
TextEditDialog.toolTip.tag.dt=Definitionsbegriff
TextEditDialog.toolTip.tag.em=Betonung
TextEditDialog.toolTip.tag.font=Lokale Schriftartauswahl
TextEditDialog.toolTip.tag.genericStyleContainer=Generischer Sprach-/Stilbehälter
TextEditDialog.toolTip.tag.h1=Überschrift 1
TextEditDialog.toolTip.tag.h2=Überschrift 2
TextEditDialog.toolTip.tag.h3=Überschrift 3
TextEditDialog.toolTip.tag.h4=Überschrift 4
TextEditDialog.toolTip.tag.h5=Überschrift 5
TextEditDialog.toolTip.tag.h6=Überschrift 6
TextEditDialog.toolTip.tag.i=Textstil "Kursiv"
TextEditDialog.toolTip.tag.img=Standard-HTML-Bildreferenz
TextEditDialog.toolTip.tag.ins=Eingefügter Text
TextEditDialog.toolTip.tag.li=Listenelement
TextEditDialog.toolTip.tag.p=Absatz
TextEditDialog.toolTip.tag.pre=Vorformatierter Text
TextEditDialog.toolTip.tag.strong=Starke Hervorhebung
TextEditDialog.toolTip.tag.sub=Tiefgestellt
TextEditDialog.toolTip.tag.sup=Hochgestellt
TextEditDialog.toolTip.tag.tt=Text mit fester Zeichenbreite ("Videotext")
TextEditDialog.toolTip.tag.u=Textstil "Unterstrichen"
TextEditDialog.toolTip.tag.ul=Unsortierte Liste
TextEditDialog.toolTip.valueOf=Value Of
TextEditDialog.toolTipText.copy=Kopieren
TextEditDialog.toolTipText.cut=Ausschneiden
TextEditDialog.toolTipText.delete=Löschen
TextEditDialog.toolTipText.paste=Einfügen
TextEditDialog.toolTipText.redo=Wiederherstellen
TextEditDialog.toolTipText.undo=Rückgängig

###########################################################
#TextEditPart properties

TextEditPart.Figure.Dafault=Text
TextEditPart.trans.editText=Textelement bearbeiten

###########################################################
#TextExtendsTools properties

TextExtendsTools.Message.DefaultAuthor=Birt Eclipse Report Designer-Version

###########################################################
#TextPageGenerator properties

TextPageGenerator.List.Bookmark=Lesezeichen
TextPageGenerator.List.Borders=Rahmen
TextPageGenerator.List.General=Allgemein
TextPageGenerator.List.I18n=Lokalisierung
TextPageGenerator.List.Margin=Rand
TextPageGenerator.List.Padding=Umrandungsfüllung
TextPageGenerator.List.Section=Seitenumbruch
TextPageGenerator.List.TOC=Inhaltsverzeichnis
TextPageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#TextPropertyDescriptor properties

TextPropertyDescriptor.Message.Version=Eclipse BIRT Designer Version {0} Build <{1}>

###########################################################
#AutoTextPageGenerator properties

AutoTextPageGenerator.List.Bookmark=Lesezeichen
AutoTextPageGenerator.List.Borders=Rahmen
AutoTextPageGenerator.List.General=Allgemein
AutoTextPageGenerator.List.Margin=Rand
AutoTextPageGenerator.List.Padding=Füllung
AutoTextPageGenerator.List.Section=Seitenumbruch
AutoTextPageGenerator.List.TOC=Inhaltsverzeichnis
AutoTextPageGenerator.List.Visibility=Sichtbarkeit

###########################################################
#ThemesNodeProvider properties

ThemesNodeProvider.action.New=Neues Thema

###########################################################
#TimeOptionDialog properties

TimeOptionDialog.Label.Format=Format
TimeOptionDialog.Label.TimeZone=TimeZone

###########################################################
#ToggleMarginVisibilityAction properties

ToggleMarginVisibilityAction.text.Label=Ränder &anzeigen
ToggleMarginVisibilityAction.text.Tooltip=Ränder umschalten

###########################################################
#TwinExpressionDialog properties

TwinExpressionDialog.Dialog.Title=Werte auswählen
TwinExpressionDialog.lable.value1=Wert1:
TwinExpressionDialog.lable.value2=Wert2:

###########################################################
#UndoAction properties

UndoAction.Tooltip={0} rückgängig machen

###########################################################
#UnitPropertyDescriptor properties

UnitPropertyDescriptor.error.message=Please enter a smaller value\!
UnitPropertyDescriptor.error.title=Too Big Value

###########################################################
#UseLibraryAction properties

UseLibraryAction.Text=&Bibliothek verwenden
UseLibraryAction.Error.Title=Vorhandene Datei ersetzen
UseLibraryAction.Error.Message=Die Datei ''{0}'' ist bereits im BIRT-Ressourcenordner vorhanden. Ersetzen?

###########################################################
#UserPropertyBuilder properties

UserPropertyBuilder.0=Neue Benutzereigenschaft
UserPropertyBuilder.ErrorMessage.DuplicatedName=Der angegebene Name wird bereits verwendet.
UserPropertyBuilder.ErrorMessage.NoName=Legen Sie einen Namen fest.
UserPropertiesHandleProvier.Column.Name=Name
UserPropertiesHandleProvier.Column.Type=Typ
UserPropertyBuilder.Label.DefaultValue=&Standardwert:
UserPropertyBuilder.Label.ExpressionName=&Ausdrucksname:
UserPropertyBuilder.Label.PropertyName=&Eigenschaftsname:
UserPropertyBuilder.Label.PropertyType=&Eigenschaftstyp:
UserPropertyBuilder.Title.NamedExpression=Neuer benannter Ausdruck

###########################################################
#VisibilityPage properties

VisibilityPage.Check.HideElement=&Element ausblenden
VisibilityPage.Check.HTML=&HTML
VisibilityPage.Check.PDF=&PDF
VisibilityPage.Label.DetailAll=Detail (Alle Ausgaben)
VisibilityPage.Label.DetailSpecific=Detail (Bestimmte Ausgaben)
VisibilityPage.Label.Expression=&Ausdruck:
VisibilityPage.menu.SaveHides=Versteckte Elemente speichern
VisibilityPage.Radio.AllOutputs=&Für alle Ausgaben
VisibilityPage.Radio.SpecificOutputs=&Für spezifische Ausgaben...

###########################################################
#WidgetUtil properties

WidgetUtil.MessageBox.Error=Fehler

###########################################################
#wizard properties

wizard.transaction.createDataSource=Geben Sie den Namen und die Art der Datenquelle an.

###########################################################
#WizardChoicePage properties

WizardChoicePage.radio.createBlank=Einen leeren Bericht erstellen, ohne eine Vorlage zu verwenden.
WizardChoicePage.radio.createFromCustom=Bericht als Kopie eines anderen Berichts erstellen.
WizardChoicePage.radio.createFromTemplate=Bericht aus Vorlage erstellen.

###########################################################
#WizardCustomTemplatePage properties

WizardCustomTemplatePage.button.Browse=Durchsuchen
WizardCustomTemplatePage.label.FileName=Berichtdateinamen eingeben oder auswählen.
WizardCustomTemplatePage.label.FromLocal=Lokales Dateisystem durchsuchen.
WizardCustomTemplatePage.label.FromProjectDescription=Vorhandene Berichtdatei auswählen.
WizardCustomTemplatePage.label.FromProjectTitle=Berichtdatei-Auswahl

###########################################################
#WizardNewReportCreationPage properties

WizardNewReportCreationPage.Errors.nameExists=Dieser Name ist bereits vorhanden.
WizardNewReportCreationPage.label.browse=Durchsuchen ...
WizardNewReportCreationPage.label.directory=Verzeichnis:
WizardNewReportCreationPage.label.file.location=Speicherort der Datei
WizardNewReportCreationPage.label.file.name=Dateiname:
WizardNewReportCreationPage.label.select.directory=Wählen Sie ein Verzeichnis.
WizardNewReportCreationPage.label.useDefault=Standard verwenden
WizardNewReportCreationPage.msg.duplicate.fileName=Dieser Name ist bereits vorhanden.
WizardNewReportCreationPage.msg.empty.file.locationDirectory=Sie müssen ein Verzeichnis für den Speicherort der Datei angeben.
WizardNewReportCreationPage.msg.empty.file.name=Sie müssen einen Dateinamen angeben.

###########################################################
#WizardSelectCssStylePage properties

WizardSelectCssStylePage.button.label.browse=&Durchsuchen...
WizardSelectCssStylePage.button.label.deselectAll=&Markierung aufheben
WizardSelectCssStylePage.button.label.selectAll=&Alles markieren
WizardSelectCssStylePage.errorMsg.FileNotExist=Datei existiert nicht.
WizardSelectCssStylePage.info.canNotImport=\ \ (Importieren nicht möglich)
WizardSelectCssStylePage.label.fileName=&Dateiname:
WizardSelectCssStylePage.label.importToReportDesign=\ für Import in das Berichtdesign.
WizardSelectCssStylePage.label.notifications=Benachrichtigungen:
WizardSelectCssStylePage.label.selectStylesFrom=Wählen Sie die Stile aus 
WizardSelectCssStylePage.msg.FileNameEmpty=Sie müssen einen Dateinamen angeben.
WizardSelectCssStylePage.text.cannot.import.style=\ - Stil kann nicht importiert werden.
WizardSelectCssStylePage.FileNameError.Title=Fehler
WizardSelectCssStylePage.FileNameError.Message=Die ausgewählte Datei ist ungültig.

###########################################################
#WizardTemplateChoicePage properties

WizardTemplateChoicePage.label.Description=Beschreibung:
WizardTemplateChoicePage.label.Preview=Vorschau:
WizardTemplateChoicePage.label.ReportTemplates=Berichtvorlagen:
WizardTemplateChoicePage.label.ShowCheatSheets=&Spickzettel für Berichterstellung anzeigen
WizardTemplateChoicePage.message.BlankReport=Erstellt einen leeren Bericht ohne vordefinierten Inhalt.
WizardTemplateChoicePage.message.ChartListing=Erstellt einen Gruppenbericht mit einem Diagramm, in dem die jeweiligen Daten der einzelnen Gruppen dargestellt sind.
WizardTemplateChoicePage.message.DualColumnChartListing=Erstellt einen Gruppenbericht mit zwei "Diagramm und Liste"-Untergruppen.
WizardTemplateChoicePage.message.DualColumnListing=Erstellt einen Gruppenbericht mit zwei Untergruppen.
WizardTemplateChoicePage.message.FirstReport=Enthält Anweisungen zum Erstellen von Berichten mit Kundenlisten.
WizardTemplateChoicePage.message.GroupedListing=Erstellt einen Bericht mit einer Liste, in dem bestimmte Felder gruppiert sind.
WizardTemplateChoicePage.message.Letter=Erstellt eine Vorlage zum Erstellen personalisierter Briefe unter Einbeziehung der Felder aus der Datenquelle.
WizardTemplateChoicePage.message.MailingLabels=Nachrichtenbeschriftungen
WizardTemplateChoicePage.message.SideBySideChartListing=Erstellt einen Gruppenbericht, in dem für jede Gruppe ein Diagramm und eine Liste nebeneinander angezeigt werden.
WizardTemplateChoicePage.message.SimpleListing=Erstellt einen Bericht mit einer Liste, dessen Felder aus der Datenquelle übernommen werden.
WizardTemplateChoicePage.title.BlankReport=Leerer Bericht
WizardTemplateChoicePage.title.ChartListing=Diagramm & Liste
WizardTemplateChoicePage.title.DualColumnChartListing=Zwei-Spalten-Diagramm & -Listen
WizardTemplateChoicePage.title.DualColumnListing=Liste mit zwei Spalten
WizardTemplateChoicePage.title.FirstReport=Der erste Bericht
WizardTemplateChoicePage.title.GroupedListing=Gruppierte Liste
WizardTemplateChoicePage.title.Letter=Letter
WizardTemplateChoicePage.title.MailingLabels=Nachrichtenbeschriftungen
WizardTemplateChoicePage.title.SideBySideChartListing=Diagramm & Liste nebeneinander
WizardTemplateChoicePage.title.SimpleListing=Einfache Liste

###########################################################
#XMLSourcePage properties

XMLSourcePage.Error.Dialog.Message.InvalidFile=Bevor andere Seiten verwendet werden können, muss der Fehler in der XML-Quellseite behoben werden.
XMLSourcePage.Error.Dialog.Message.SaveFile=Die XML-Quellseite wurde geändert. Bevor andere Seiten verwendet werden können, muss die XML-Quellseite gespeichert werden.
XMLSourcePage.Error.Dialog.title=Fehler
XMLSourcePage.Error.Dialog.Message.PromptMsg=Die XML-Quelle für das Bericht-Design wurde geändert. Möchten Sie die Änderungen speichern?
XMLSourcePage.Error.Dialog.Message.Yes=Ja
XMLSourcePage.Error.Dialog.Message.No=Nein
XMLSourcePage.Error.Dialog.Message.Cancel=Abbrechen

###########################################################
#SaveReportAsWizard properties
SaveReportAsWizard.SettingPage.title=Vorlageneigenschaft festlegen
SaveReportAsWizard.SaveAsPageTitle=Speichern unter
SaveReportAsWizard.SaveAsLibraryMessage=Datei als Bibliothek mit einem anderen Namen speichern.
SaveReportAsWizard.SaveAsReportorTemplateMessage=Datei als Berichtdesign oder Vorlage mit einem anderen Namen speichern.
SaveReportAsWizard.SettingPageTitle=Eigenschaft für Bericht festlegen
SaveReportAsWizard.SettingPage.message=Diese Eigenschaften gelten beim Speichern des Berichts als Vorlage.
SaveReportAsWizard.SaveAsWizardWindowTitle=Speichern unter
SaveReportAsWizard.SaveAsWizardPageTitle=Speichern unter
SaveReportAsWizard.SaveAsWizardPageDesc=Speichern Sie die Datei an einem anderen Ort.

###########################################################
#WizardReportSettingPage properties
WizardReportSettingPage.Error.ReportorTemplate=Dateiname muss auf {0} oder .rpttemplate enden.
WizardReportSettingPage.Error.Library=Dateiname muss auf .rptlibrary enden.

###########################################################
#WizardSaveAsPage properties
WizardSaveAsPage.FileLabel=&Dateiname:
WizardSaveAsPage.Question=Frage
WizardSaveAsPage.FolderEmpty=\ Der Ordner ist leer.
WizardSaveAsPage.NoProject=\ Das angegebene Projekt existiert nicht.
WizardSaveAsPage.PathOccupied=\ An diesem Speicherort ist bereits eine Datei vorhanden: {0}
WizardSaveAsPage.EmptyName=\ Der Name ''{0}" ist leer.
WizardSaveAsPage.SelectFolder=\ Wählen Sie den Ordner aus:
WizardSaveAsPage.NameExists=\ Dieser Name ist bereits vorhanden.
WizardSaveAsPage.OverwriteQuestion=Die Datei "{0}" ist bereits vorhanden. Ersetzen?
WizardSaveAsPage.InvalidFileName=\ ''{0}'' ist kein gültiger Dateiname.
WizardSaveAsPage.ContainerGroup=\ Wählen Sie den übergeordneten Ordner aus oder &geben Sie einen Namen ein:

###########################################################
#Library DND message
Library.DND.messages.outofsync = Die im Bericht verwendete Bibliothek wurde möglicherweise geändert. Schließen Sie diesen Bericht, und öffnen Sie ihn erneut, um die aktualisierte Bibliothek zu verwenden.
NamedExpressionsHandleProvier.Column.Name=Name
NamedExpressionsHandleProvier.Column.DefaultValue=Standardwert
Library.DND.messages.cannotApplyTheme=Das Thema kann nicht verwendet werden.

JarFileFormProvider.Column.Name=Name

###########################################################
#ClassFinder
ClassFinder.TaskStart=Handler-Klasse wird gesucht...
ClassFinder.DialogTitle=Auswahl der Klasse
ClassFinder.DialogMessage=Wählen Sie eine Handler-Klasse.
ClassFinder.ErrorMessage=Es wurde keine Klasse gefunden.

###########################################################
#ListingSectionPage
ListingSectionPage.RepeatHeader=Kopfzeile wiederholen

###########################################################
#ResourceEditDialog
ResourceEditDialog.NotFile.Title=Datei nicht gefunden
ResourceEditDialog.NotFile.Message=Die Datei ''{0}'' existiert nicht.
ResourceEditDialog.ReadOnlyEncounter.Title=Schreibgeschützte Datei gefunden
ResourceEditDialog.ReadOnlyEncounter.Message=Datei ''{0}'' ist schreibgeschützt. Heben Sie den Schreibschutz auf.

###########################################################
#EventHandler
EventHandlerPage.Browse=&Durchsuchen...


###########################################################
#IDEFileReportProvider
IDEFileReportProvider.ReadOnlyEncounter.Title=Schreibgeschützte Datei gefunden
IDEFileReportProvider.ReadOnlyEncounter.Message=Datei ''{0}'' ist schreibgeschützt. Heben Sie den Schreibschutz auf.

###########################################################
#DataSetColumnBindingsFormHandleProvider
DataSetColumnBindingsFormHandleProvider.Column.Name=Name
DataSetColumnBindingsFormHandleProvider.Column.displayName=Angezeigter Name
DataSetColumnBindingsFormHandleProvider.TableTitle=Datenspaltenbindung:
DataSetColumnBindingsFormHandleProvider.NewBinding=Neue Bindung  
DataSetColumnBindingsFormHandleProvider.Column.DataType=Datentyp
DataSetColumnBindingsFormHandleProvider.Column.Expression=Ausdruck
DataSetColumnBindingsFormHandleProvider.Column.AggregateOn=Aggregat ein
DataSetColumnBindingsFormHandleProvider.ALL=Alles
DataSetColumnBindingsFormHandleProvider.NONE=n.a.

###########################################################
#DataSetColumnBindingsFormPage
DataSetColumnBindingsFormPage.Button.RemoveUnused=Nicht verwendete Spalte entfernen
###########################################################
#ResourceSelectionValidator
ResourceSelectionValidator.ExtError=Ausgewählte Datei muss enden auf: 
ResourceSelectionValidator.EmptyError=Wählen Sie eine Datei aus.
ResourceSelectionValidator.ExtErrorSplitter=\ oder 

###########################################################
#GeneralPage
GeneralPage.Library.Included=Bibliothek:
###########################################################
#
FormatStringPage.SimpleTextZipCode=94103
FormatStringPage.SimpleTextZipCode4=941031234
FormatStringPage.PhoneNumber=4155551111
FormatStringPage.SocialSecurityNumber=123456789
FormatStringPage.simpleTexZipCodeFormat=@@@@@
FormatStringPage.simpleTexZipCode4Format=@@@@@
FormatStringPage.phoneNumberFormat=(@@@) @@@-@@@@
FormatStringPage.securityNumberFormat=@@@-@@-@@@@


###########################################################
#PublishLibraryDialog
PublishLibraryDialog.ShellText=Bibliothek veröffentlichen
PublishLibraryDialog.TitleArea=Bibliothek veröffentlichen
PublishLibraryDialog.Message=Bibliothek im BIRT-Ressourcenordner veröffentlichen
PublishLibraryDialog.Label.SourceFileName=&Quelldatei:
PublishLibraryDialog.Label.FileName=Datei&name:
PublishLibraryDialog.Label.Folder=&Ordner:
PublishLibraryDialog.Label.Browse=&Durchsuchen...
PublishLibraryDialog.Message.FileNameEmpty=Dateiname erforderlich.
PublishLibraryDialog.Message.FileNameError=Dateiname muss auf .rptlibrary enden.
PublishLibraryDialog.Message.FolderEmpty=Veröffentlichungsordner erforderlich.
PublishLibraryDialog.Message.SourceFileEmpty=Name der Quelldatei erforderlich.
PublishLibraryDialog.Label.Browse2=D&urchsuchen...
PublishLibraryDialog.AddText=Bibliothek hinzufügen
PublishLibraryDialog.AddMessage=Bibliothek zum BIRT-Ressourcenordner hinzufügen

WizardLibrarySettingPage.ErrorMessage=Wählen Sie einen Ordner aus.

WizardLibrarySettingPage.Resourcefile.Dialog.Title=Ressourcenordner durchsuchen
WizardLibrarySettingPage.Resourcefile.Dialog.Message=Wählen Sie den Ressourcenordner oder dessen Unterordner aus.

PublishLibraryDialog.AddLibrary=Bibliothek hinzufügen

###########################################################
#EmbeddedImagesNodeProvider
EmbeddedImagesNodeProvider.FileNameError.Title=Fehler
EmbeddedImagesNodeProvider.FileNameError.Message=Die ausgewählte Datei ist keine Bilddatei.

###########################################################
#AddElementtoAction properties
AddElementtoAction.Text=&Zum Bericht hinzufügen

###########################################################
#MultiPageReportEditor properties
MultiPageReportEditor.CheckVersion.Dialog.Title=Warnung
TableArea.Button.Up=&Nach oben

###########################################################
#AddJarResourceFileFolderSelectionDialog
AddJarResourceFileFolderSelectionDialog.ErrorMessage.Exist=Eine oder mehrere der ausgewählten Dateien existieren bereits.
AddJarResourceFileFolderSelectionDialog.Message=JAR-Dateien auswählen:
AddJarResourceFileFolderSelectionDialog.ErrorMessage.ExtError=Dateiname muss auf \".jar\" enden.

###########################################################
#AddImageResourceFileFolderSelectionDialog
AddImageResourceFileFolderSelectionDialog.Title=Eine oder mehrere der ausgewählten Dateien existieren bereits.
AddImageResourceFileFolderSelectionDialog.Message=Wählen Sie ein Bild aus:

###########################################################
#DataItemBindingDialog properties

DataItemBindingDialog.text.Name=Name:
DataItemBindingDialog.text.displayName=Anzeigename:
DataItemBindingDialog.text.DataType=Datentyp:
DataItemBindingDialog.text.Expression=Ausdruck:
DataItemBindingDialog.text.AggregateOn=Aggregat ein:
DataItemBindingDialog.text.ForceBinding=Erstellt neue Bindung mit demselben Ausdruck
DataItemBindingDialog.text.All=Alles
DataItemBindingDialog.text.None=n.a.
DataItemBindingDialog.title.CreateNewItem=Neue Datenelementbindung
DataItemBindingDialog.title.EditDataItem=Datenelementbindung bearbeiten

###########################################################
#DataColumBindingDialog properties
DataColumBindingDialog.title.CreateNewDataBinding=Neue Datenbindung
DataColumBindingDialog.title.EditDataBinding=Datenbindung bearbeiten

###########################################################
#CreatePlaceHolderAction properties
ChangeDataColumnAction.text=Datenspalte ändern

###########################################################
#ThumbnailBuilder properties
ThumbnailBuilder.Text.Title=Miniatur verwalten
ThumbnailBuilder.Button.Text.Generate=&Generieren
ThumbnailBuilder.Button.Text.Remove=&Entfernen
ThumbnailBuilder.Button.Text.Import=&Importieren...
ThumbnailBuilder.FileDialog.Title=Bilddatei auswählen
ThumbnailBuilder.FileDialog.FileNameError.Title=Fehler
ThumbnailBuilder.FileDialog.FileNameError.Message=Die ausgewählte Datei ist keine Bilddatei.

###########################################################
#FragmentResourceEntry properties
FragmentResourceEntry.RootName=Fragmente
FragmentResourceEntry.RootDisplayName=Integrierte Bibliotheken

###########################################################
#PathResourceEntry properties
PathResourceEntry.RootName=Ressourcenordner
PathResourceEntry.RootDisplayName=Gemeinsam genutzte Bibliotheken

###########################################################
#BIRTGotoMarker properties
BIRTGotoMarker.Error.Title=Fehler
BIRTGotoMarker.Error.Message=Das Berichtelement ist nicht vorhanden.

###########################################################
#TabbedList properties
TabbedPropertyList.properties.not.available=Eigenschaften sind nicht verfügbar.

###########################################################
#Cube treeNode properties
DefaultNodeProvider.Tree.Cubes=Cubes
cube.new=New Cube
cube.edit=Edit Cube
CubeNodeProvider.menu.text=Bearbeiten
cube.dimension.new=New Cube Dimension
cube.dimension.edit=Edit Cube Dimension
CubeDimensionNodeProvider.menu.text=Bearbeiten
cube.level.new=New Cube Level
cube.level.edit=Edit Cube Level
CubeLevelNodeProvider.menu.text=Bearbeiten
cube.measure.new=New Cube Measure
cube.measure.edit=Edit Cube Measure
CubeMeasureNodeProvider.menu.text=Bearbeiten
cube.measuregroup.new=New Cube Measure Group
cube.measure.edit=Edit Cube Measure
CubeMeasureGroupNodeProvider.menu.text=Bearbeiten

###########################################################
#Cube Builder Dialog properties
CubeBuilder.Title=OLAP Cube Builder
DatasetPage.Title=Dataset
DimensionPage.Title=Dimension
MeasurePage.Title=Measures
DatasetPage.Label.Name=Cube name:
DatasetPage.Label.PrimaryDataset=Primary dataset:
DatasetPage.Button.Filter=Filter...
DatasetPage.Button.Joint=Add joint datasets...
DimensionPage.Label.Title=Dimension:
DimensionPage.Button.Add=&Hinzufügen
DimensionPage.Button.Edit=&Edit
DimensionPage.Button.Delete=&Löschen
DimensionPage.Button.Property=&Property
MeasuresPage.Label.DataField=Available data fields:
MeasuresPage.Label.Measures=Measures:
MeasuresPage.Button.Add=Hinzufügen
MeasuresPage.Label.Name=&Name:
MeasuresPage.Label.Function=&Function:
MeasuresPage.Label.Expression=&Ausdruck:
DatasetDialog.Title.Label=Add Datasets
DatasetDialog.Title.OKButton.Text=Hinzufügen
DimensionDialog.Title=OLAP Cube Builder
DimensionDialog.Button.Primary=Use primary dataset as Dimension dataset
DimensionDialog.Button.Other=Use other dataset as Dimension dataset:
DimensionDialog.Label.DatasetField=Available data fields:
DimensionDialog.Label.Dimensions=Dimensions:
DimensionDialog.Label.Name=Dimension Name:
DimensionDialog.Label.Add=Add Dimension
DimensionDialog.Label.Edit=Edit Dimension
CubeDialog.Title=Einfügen
CubeDialog.Label.Select=Selected data for Cross Tab:
CubeDialog.Button.Define=Define data for Cross Tab
LevelDialog.Title=OLAP Cube Builder
LevelDialog.Label.Name=Name:
LevelDialog.Label.Field=Choose Field:
LevelDialog.Label.Info=Selected Key:
LevelDialog.Label.Add=Add Level
LevelDialog.Label.Edit=Edit Level
LevelPropertyDialog.Title=Level
LevelPropertyDialog.MSG.CreateNew=<Create New Parameter>
LevelPropertyDialog.Label.Name=Name:
LevelPropertyDialog.Label.Interval=Intervall:
LevelPropertyDialog.Label.Range=Range:
LevelPropertyDialog.Button.IntervalBase=Use fixed base value for interval:
LevelPropertyDialog.Label.Info=Selected Key:
LevelPropertyDialog.Button.Dynamic=Dynamic
LevelPropertyDialog.Button.Static=Static
LevelPropertyDialog.Label.Property=Level Property
LevelPropertyDialog.Label.Attribute=Attribute
LevelPropertyDialog.Label.Name=Name:
LevelPropertyDialog.Label.Expression=Ausdruck
