###########################################################
#AbstractDataSetWizard properties

AbstractDataSetWizard.ModelTrans.Create=データセットの名前、ソース、型を定義
###########################################################
#CssErrDialog
CssErrDialog.shellTitle.ImportCssStyleMssageTitle=インポートに関するメッセージ
CssErrDialog.AreaTitle=CSS スタイルのインポートに関するメッセージ
CssErrDialog.AreaMessage=CSS スタイルのインポート中にエラーまたは警告が発生しました。
CssErrDialog.Serverity=重要度 :
CssErrDialog.Message=メッセージ :
CssErrDialog.FatalError=重大なエラー
CssErrDialog.Error=エラー
CssErrDialog.Warning=警告

###########################################################
#AddGroupAction properties

AddGroupAction.actionMsg.addGroup=グループの挿入...
AddGroupAction.Menu.Text=グループの挿入...
AddGroupAction.stackMsg.addGroup=グループの挿入

###########################################################
#AddLibraryAction properties

AddLibraryAction.Error.FileNotFound=ファイル ''{0}'' が見つかりません。
AddLibraryAction.Error.FileIsNotLibrary=ファイル ''{0}'' の拡張子が ''{1}'' ではありません。
AddLibraryAction.Error.Message=ファイルはすでに存在します。
AddLibraryAction.Error.Title=エラー
AddLibraryAction.Text=ライブラリの追加...
AddLibraryAction.Dialog.Tilte=ライブラリの選択

###########################################################
#DeleteLibraryAction properties
DeleteLibraryAction.Text=削除
###########################################################
#AddStyleRuleAction properties

AddStyleAction.actionMsg.addStyleRule=スタイルの新規作成(&N)...
AddStyleAction.stackMsg.addStyle=スタイルの新規作成(&N)

###########################################################
#ApplyStyleAction properties

ApplyStyleAction.actionLabel.none=なし
ApplyStyleAction.stackMsg.applyStyle=スタイルの適用

###########################################################
#ApplyThemeAction properties

ApplyThemeAction.actionLabel.none=なし
ApplyThemeAction.stackMsg.applyStyle=テーマの適用

###########################################################
#AttributesBuilder properties

AttributesBuilder.Label.Cell=プロパティエディタ - セル
AttributesBuilder.Label.Column=プロパティエディタ - 列
AttributesBuilder.Label.Data=プロパティエディタ - データ
AttributesBuilder.Label.Generic=プロパティエディタ - {0}
AttributesBuilder.Label.Grid=プロパティエディタ - グリッド
AttributesBuilder.Label.Label=プロパティエディタ - ラベル
AttributesBuilder.Label.Library=プロパティエディタ - ライブラリ
AttributesBuilder.Label.List=プロパティエディタ - リスト
AttributesBuilder.Label.MasterPage=プロパティエディタ - マスタページ
AttributesBuilder.Label.None=プロパティエディタ - なし
AttributesBuilder.Label.Picture=プロパティエディタ - 図
AttributesBuilder.Label.Report=プロパティエディタ - レポート
AttributesBuilder.Label.Row=プロパティエディタ - 行
AttributesBuilder.Label.Table=プロパティエディタ - テーブル
AttributesBuilder.Label.Text=プロパティエディタ - テキスト
AttributesBuilder.Label.TextData=プロパティエディタ - ダイナミックテキスト
AttributesBuilder.Label.DataSourceHandle=プロパティエディタ - データソース
AttributesBuilder.Label.DataSetHandle=プロパティエディタ - データセット
AttributesBuilder.Label.ScalarParameterHandle=プロパティエディタ - パラメタ
AttributesBuilder.Label.TemplateReportItemHandle=プロパティエディタ - テンプレートレポート項目
AttributesBuilder.Label.AutoText=プロパティエディタ - 定型句

###########################################################
#AttributeView properties

AttributeView.dialg.Message.Warning = 警告
AttributeView.dialg.Message.Yes=はい(&E)
AttributeView.dialg.Message.No=いいえ(&O)
AttributeView.dialg.Message.Cancel=キャンセル(&A)
AttributeView.dialg.Message.PromptMsg=すべてのローカルプロパティをクリアしますか ?
AttributeView.toolbar.tooltip.EditingToggleAction.ClearMsg=ローカルプロパティをクリアします。
AttributeView.toolbar.tooltip.EditingToggleAction.EnableEditingMsg=プロパティの編集を有効にします。
AttributeView.toolbar.tooltip.EditingToggleAction.DisabledActionMsg=この操作は、ローカル要素には行えません。
AttributeView.view.message.Emptypage= このレポートデザインの {3} のプロパティを編集するには、プロパティエディタのツールバーにあるボタンをクリックして編集を有効にしてください。
AttributeView.toolbar.tooltip.RestoreLibraryPropertiesAction.RestoreMsg=プロパティの復元
AttributeView.defaultText.noAttributeView = The property editor is not available.

###########################################################
#BackGroundPreferencePage properties

BackGroundPreferencePage.displayname.Title=背景

###########################################################
#BasAttributePage properties

BasAttributePage.Label.Attributes=プロパティ :

###########################################################
#BaseInsertMenuAction properties

BaseInsertMenuAction.stackMsg.insertElement=要素の挿入

###########################################################
#BasePaletteFactory properties

BasePaletteFactory.AutoText.Confidential=社外秘
BasePaletteFactory.AutoTextLabel.CreatedBy=作成者 : 
BasePaletteFactory.AutoTextLabel.CreatedOn=作成日 : 
BasePaletteFactory.AutoTextLabel.Filename=ファイル名 : 
BasePaletteFactory.AutoTextLabel.LastPrinted=最終印刷日 : 
BasePaletteFactory.AutoTextLabel.Page=ページ : 
BasePaletteFactory.AutoTextLabel.PageCount=ページ数 :
BasePaletteFactory.AutoTextLabel.PageXofY=X/Y ページ
BasePaletteFactory.categoryName.PointerSelect=ポインタでの選択
BasePaletteFactory.categoryName.RectangleSelect=ドラッグでの選択
BasePaletteFactory.Group.Items=項目
BasePaletteFactory.toolTip.PointerSelect=項目をクリックして選択します。複数の項目を選択するには、Ctrl キーを押しながらクリックします。
BasePaletteFactory.toolTip.RectangleSelect=選択範囲を囲むようにドラッグすると、囲んだ中のすべての項目が選択されます。 

###########################################################
#BaseStylePreferencePage properties

BaseStylePreferencePage.displayname.Title=全般

###########################################################
#BgImageFieldEditor properties

BgImageFieldEditor.displayname.Browse=参照(&W)...

###########################################################
#BindingPage properties

BindingPage.Label.Binding=バインド
BindingPage.MessageDlg.SaveParamBinding=ParamBinding の保存
BindingPage.None=なし
BindingPage.TableColumn.DataType=データ型
BindingPage.TableColumn.Parameter=パラメタ
BindingPage.TableColumn.Value=値

ColumnBingingDialog.Label.Warn=データセットの変更は、すべての結果セットカラム式を無効にする可能性があります。
ColumnBindingDialog.Label.DataSet=データセット :
ColumnBindingDialog.Column.Expression=式
ColumnBindingDialog.DialogTitle=データバインドの選択
ColumnBindingDialog.Column.Name=名前
ColumnBindingDialog.InputPrompt=<ここに新しい値を入力してください...>
ColumnBindingDialog.Button.Generate=カラムバインドの生成
ColumnBindingDialog.Column.DataType=データ型
ColumnBindingDialog.Column.AggregateOn=集計条件
ColumnBindingDialog.All=すべて
ColumnBindingDialog.NONE=なし
ColumnBindingDialog.Choice.FromContainer=コンテナのデータセット
ColumnBindingDialog.AGGREGATEON.NONE=N/A
ColumnBindingDialog.Text.Add=追加
ColumnBindingDialog.Text.Edit=編集...
ColumnBindingDialog.Text.Del=削除

###########################################################
#BlockPreferencePage properties

BlockPreferencePage.displayname.Title=テキストブロック

###########################################################
#BorderPreferencePage properties

BorderPreferencePage.displayname.Color=カラー
BorderPreferencePage.displayname.Style=スタイル
BorderPreferencePage.displayname.Title=罫線
BorderPreferencePage.displayname.Width=幅
BorderPreferencePage.text.Bottom=下 :
BorderPreferencePage.text.Left=左 :
BorderPreferencePage.text.Right=右 :
BorderPreferencePage.text.Top=上 :

###########################################################
#BordersPage properties

BordersPage.Label.Borders=罫線(&B) :
BordersPage.Label.Color=カラー(&C) :
BordersPage.Label.Presets=プリセット :
BordersPage.Label.Style=スタイル(&S) :
BordersPage.Label.Width=幅(&T) :
BordersPage.Tooltip.All=すべての罫線
BordersPage.Tooltip.Bottom=下罫線
BordersPage.Tooltip.Left=左罫線
BordersPage.Tooltip.None=なし
BordersPage.Tooltip.Right=右罫線
BordersPage.Tooltip.Top=上罫線

###########################################################
#BoxPreferencePage properties

BoxPreferencePage.displayname.Title=ボックス
BoxPreferencePage.text.Margin=余白
BoxPreferencePage.text.Padding=パディング

###########################################################
#ButtonPaneComposite properties

ButtonPaneComposite.tooltip.MasterPage=マスタページ
ButtonPaneComposite.tooltip.Normal=標準
ButtonPaneComposite.tooltip.Ruler=ルーラ

###########################################################
#CachePreferencePage properties

CachePreferencePage.button.clear=キャッシュのクリア(&C)
CachePreferencePage.checkBox.text=レポートをプレビューするためにデータセットのデータをキャッシュする(&H)
CachePreferencePage.description=キャッシュサイズの定義 :
CachePreferencePage.Filter.Tooltip=データセットのキャッシュを使用します。
CachePreferencePage.label.text=行
CachePreferencePage.messageBox.info=キャッシュがクリアされました。
CachePreferencePage.messageBox.title=キャッシュのクリア
CachePreferencePage.radioBox.entireNumText=データセット全体をキャッシュする(&E)
CachePreferencePage.radioBox.numText=キャッシュして最初に使用する(&U)

###########################################################
#CascadingParametersDialog properties

CascadingParametersDialog.Button.AllowNull=Null 値を許可する(&A)
CascadingParametersDialog.default.preview.string=サンプル文字列
CascadingParametersDialog.display.controlType.comboBox=コンボボックス
CascadingParametersDialog.display.controlType.listBox=リストボックス
CascadingParametersDialog.Label.button.changeFormat=変更(&G)...
CascadingParametersDialog.Label.button.createNew.dataset=新規作成(&W)...
CascadingParametersDialog.Label.cascadingParam.name=カスケードパラメタ名(&C) :
CascadingParametersDialog.Label.column.displayText=表示テキスト
CascadingParametersDialog.Label.column.dataSet=データセット
CascadingParametersDialog.Label.column.name=名前
CascadingParametersDialog.Label.column.value=値
CascadingParametersDialog.Label.createNewParam=<パラメタの新規作成...>
CascadingParametersDialog.Label.dataSets=データセット(&S) :
CascadingParametersDialog.Label.dataType=データ型(&D)
CascadingParametersDialog.Label.defaultValue=デフォルト値(&V) :
CascadingParametersDialog.Label.displayType=表示の種類(&T) :
CascadingParametersDialog.Label.formatAs=書式設定 :
CascadingParametersDialog.Label.group.general=全般
CascadingParametersDialog.Label.group.moreOptions=詳細設定
CascadingParametersDialog.Label.group.properties=プロパティ
CascadingParametersDialog.Label.helpText=ヘルプテキスト(&H) :
CascadingParametersDialog.Label.listLimit=一覧の制限(&I) :
CascadingParametersDialog.Label.NoColumnAvailable=<使用可能な列がありません>
CascadingParametersDialog.Label.param.name=名前(&N) :
CascadingParametersDialog.Label.parameters=パラメタ
CascadingParametersDialog.Label.preview=書式付きプレビュー
CascadingParametersDialog.Label.groupPromptText=プロンプトテキスト(&P) :
CascadingParametersDialog.Label.parameterPromptText=プロンプトテキスト(&R) :
CascadingParametersDialog.Label.selectDataSet=<データセットの選択>
CascadingParametersDialog.Label.selectDisplayColumn=<表示列を選択>
CascadingParametersDialog.Label.selectValueColumn=<値の列を選択>
CascadingParametersDialog.Label.values=個の値
CascadingParametersDialog.Label.SelectDataSetMode=データセットモード :
CascadingParametersDialog.Radio.Single=1 つのデータセット
CascadingParametersDialog.Radio.Mutli=複数のデータセット

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=プロパティ

###########################################################
#CellPageGenerator properties

CellPageGenerator.List.Borders=罫線
CellPageGenerator.List.CellPadding=パディング
CellPageGenerator.List.Font=フォント
CellPageGenerator.List.General=全般
CellPageGenerator.TabItem.Highlights=ハイライト
CellPageGenerator.TabItem.map=マップ

###########################################################
#LabelPageGenerator properties
LabelPageGenerator.TabItem.Highlights=ハイライト

###########################################################
#ChoiceSetFactory properties

ChoiceSetFactory.choice.Auto=自動
ChoiceSetFactory.choice.None=なし

###########################################################
#CodePageAction properties

CodePageAction.actionText.code=スクリプト

###########################################################
#ColorBuilder properties

ColorBuilder.text.None=自動

###########################################################
#ColumnPageGenerator properties

ColumnPageGenerator.List.Borders=罫線
ColumnPageGenerator.List.CellPadding=セルのパディング
ColumnPageGenerator.List.Font=フォント
ColumnPageGenerator.List.General=全般
ColumnPageGenerator.TabItem.Highlights=ハイライト
ColumnPageGenerator.TabItem.map=マップ
ColumnPageGenerator.List.Visibility=表示/非表示

###########################################################
#Commom properties

Commom.ShortDateTime.Fri=金
Commom.ShortDateTime.Mon=月
Commom.ShortDateTime.Sat=土
Commom.ShortDateTime.Sun=日
Commom.ShortDateTime.Thu=木
Commom.ShortDateTime.Tue=火
Commom.ShortDateTime.Wed=水

###########################################################
#Connection Profile Properties
connectionprofile.wizard.title=新規データソース
connectionprofile.wizard.title.connectionprofileselect=接続プロファイルの選択
connectionprofile.wizard.defaultmessage.connectionprofileselect=データソースの作成元とする接続プロファイルを選択してください。
connectionprofile.wizard.label.connectionprofilestore=接続プロファイルストア :
connectionprofile.wizard.label.datasourcename=データソース名 :
connectionprofile.wizard.checkbox.datasourcenameusedefaultdsname=デフォルトのデータソース名を使用する
connectionprofile.wizard.tree.datasourcename=ODA データソース
connectionprofile.wizard.button.browse=参照...

###########################################################
#CopyAction properties

CopyAction.text=コピー(&C)

###########################################################
#CreatePlaceHolderAction properties

CreatePlaceHolderAction.text=テンプレートのレポート項目を作成(&E)...

###########################################################
#CutAction properties

CutAction.text=切り取り(&t)
CutAction.trans=要素の切り取り

###########################################################
#dataBinding properties

dataBinding.label.selectBinding=データバインドの選択
dataBinding.message.changeDataSet=要素のデータバインドを変更しようとしています。\n\n既存のデータフィールド情報をすべて削除しますか ?
dataBinding.title.changeDataSet=データセットを変更しますか ?
dataBinding.title=データバインド

parameterBinding.title=データセットパラメタのバインド



###########################################################
#DataEditPart properties

DataEditPart.Figure.Dafault=データ
DataEditPart.Figure.Expression=式

###########################################################
#DataEditPart properties

DestroyEditPart.Message=このレポート項目のコンテンツが破損しています。このレポートで作業を続けるには、まずこの項目を削除してください。そうしないと、レポートデザインファイルがさらに破損し、Report Designerが応答しなくなる可能性があります。

###########################################################
#DataPageGenerator properties

DataPageGenerator.List.Bookmark=ブックマーク
DataPageGenerator.List.Borders=罫線
DataPageGenerator.List.Duplicates=重複
DataPageGenerator.List.Expression=式
DataPageGenerator.List.Format=書式
DataPageGenerator.List.formatDateTime=日時の書式設定
DataPageGenerator.List.formatNumber=数値の書式設定
DataPageGenerator.List.formatString=文字列の書式
DataPageGenerator.List.General=全般
DataPageGenerator.List.Highlights=ハイライト
DataPageGenerator.List.HyperLink=ハイパーリンク
DataPageGenerator.List.Margin=余白
DataPageGenerator.List.Padding=パディング
DataPageGenerator.List.Section=ページ区切り
DataPageGenerator.List.TOC=目次
DataPageGenerator.List.Visibility=可視性
DataPageGenerator.TabItem.map=マップ

###########################################################
#dataset properties

dataset.edit=データセットの編集 - {0}
dataset.editor.cachePreference.errorNumberFormat=キャッシュの行サイズには、0 よりも大きい数値を入力してください。
dataset.editor.cachePreference=キャッシュの設定
dataset.editor.computedColumns=計算列
dataset.editor.dataSource.Tooltip=データソースの表示と変更
dataset.editor.dataSource=データソース
dataset.editor.error.columnOrAliasNameAlreadyUsed=新しい列の名前またはエイリアス ({0}) は、すでにインデックス {1} の列で使用されています。
dataset.editor.error.duplicateParameterName=パラメタ名が重複しています。
dataset.editor.error.emptyName=名前は空白にできません。 
dataset.editor.error.missingComputedColumnExpression=計算列 {0} の式は null または空白にできません。
dataset.editor.error.missingComputedColumnName=計算列名は null または空白にできません。
dataset.editor.error.noDataSource=データセット {0} にデータソースがありません。プロパティビューの [データソース] エントリでデータソースを選択してください。
dataset.editor.error.noEditorsFound=データセットのエディタが見つかりません {0}。
dataset.editor.error.noInputParameterDefaultValue=入力パラメタ {0} に NULL 以外のデフォルト値を設定してください。
dataset.editor.error.title=警告
dataset.editor.error.unsupportedDataSet=このデータセット型は使用できません - {0}。
dataset.editor.error.validationParameter=入力パラメタ [{0}] の値が空です。空のままにしておきますか ?
dataset.editor.filters=フィルタ
dataset.editor.label.selectDataSource=データソースの選択(&D) :
dataset.editor.outputColumns=出力列
dataset.editor.parameters=パラメタ
dataset.editor.preview=結果のプレビュー
dataset.editor.outputparameters=出力パラメタのプレビュー
dataset.editor.title.alias=エイリアス
dataset.editor.title.columnName=列名
dataset.editor.title.dataType=データ型
dataset.editor.title.defaultValue=デフォルト値
dataset.editor.title.direction=方向
dataset.editor.title.displayName=表示名
dataset.editor.title.expression=式
dataset.editor.title.helpText=ヘルプテキスト
dataset.editor.title.isInput=入力
dataset.editor.title.isNullable=Null を許可する
dataset.editor.title.isOptional=オプション
dataset.editor.title.isOutput=出力
dataset.editor.title.name=名前
dataset.editor.title.operator=演算子
dataset.editor.title.type=型
dataset.editor.title.value1=値 1
dataset.editor.title.value2=値 2
dataset.editor.historybar.backward=戻る
dataset.editor.historybar.forward=進む
dataset.editor.historybar.to=:
dataset.error.noDataSources=使用できるデータソースがありません。\nデータソースを追加してください。
dataset.error.dataSourceMissing=このデータセットにはデータソースがありません。
dataset.error.title.noDataSources=使用できるデータソースがありません。
dataset.message.create=新規データセットを作成します。
dataset.new.defaultName=データセット
dataset.new=新規データセット
dataset.join.new=ジョイントデータセットの新規作成
dataset.resultset.preview.tooltip=クエリ結果のプレビュー
dataset.outputparameters.preview.tooltip=出力パラメタのプレビュー
dataset.wizard.label.datasetName=データセット名(&M) :
dataset.wizard.label.datasetType=データセットの型(&T) :
dataset.wizard.label.dataSource=データソース(&S) :

###########################################################
#DataSetBasePage properties

DataSetBasePage.tooltip=名前は空白にできません。

###########################################################
#JointDataSetPage properties

JointDataSetPage.pageName=ジョイントデータセット
JointDataSetPage.page.detail=ジョインを定義するには、左右のフィールドからデータセットとカラムを選択してください。
JointDataSetPage.button.innerJoin=インナージョイン(&I)
JointDataSetPage.button.leftJoin=左アウタージョイン(&L)
JointDataSetPage.button.rightJoin=右アウタージョイン(&R)
JointDataSetPage.button.fullJoin=左右アウタージョイン(&F)
JointDataSetPage.joinType=ジョインの型
JointDataSetPage.error.nodataset.title=データセットが見つかりません
JointDataSetPage.error.nodataset.right=右側のデータセットが見つかりません。
JointDataSetPage.error.nodataset.left=左側のデータセットが見つかりません。
JointDataSetPage.pageDescription=ジョイントデータセットの定義
JointDataSetPage.query=クエリ

###########################################################
#DataSetComputedColumnsPage properties

DataSetComputedColumnsPage.ComputedColumns.Tooltip=計算列の定義。
DataSetComputedColumnsPage.description=計算列の定義 :
DataSetComputedColumnsPage.duplicatedName=列名の重複
DataSetComputedColumnsPage.toolTipText.Down=計算カラムを下に移動
DataSetComputedColumnsPage.toolTipText.Up=計算カラムを上に移動
DataSetComputedColumnsPage.toolTipText.Remove=計算カラムを削除
DataSetComputedColumnsPage.toolTipText.New=計算列の新規作成
DataSetComputedColumnsPage.toolTipText.Edit=計算列の編集
DataSetComputedColumnsPage.title.ComputedColumnInputDialog=計算列

###########################################################
#DataSetFiltersPage properties

DataSetFiltersPage.description=フィルタの定義 :
DataSetFiltersPage.exception.msg.operator.notSupport=この演算子は使用できません : 
DataSetFiltersPage.Filter.Tooltip=BIRT 式でデータロウをフィルタ
DataSetFiltersPage.toolTipText.Down=フィルタを下に移動
DataSetFiltersPage.toolTipText.Up=フィルタを上に移動
DataSetFiltersPage.toolTipText.Remove=フィルタを削除
DataSetFiltersPage.toolTipText.New=フィルタの新規作成
DataSetFiltersPage.toolTipText.Edit=フィルタの編集
DataSetFiltersPage.title.FilterInputDialog=フィルタ
DataSetFiltersPage.messages.selectVauleUnavailable=この式では値リストを使用できません。

###########################################################
#DataSetNodeProvider properties

DataSetNodeProvider.menu.text=編集

###########################################################
#DataSetParametersPage properties

DataSetParametersPage.description=入力パラメタの定義 :
DataSetParametersPage.Filter.Tooltip=データセットへのパラメタのパスと取得
DataSetParameterBindingInputDialog.Title=データセットパラメタのバインドの編集
DataSetParametersPage.ErrorTitle.InvalidInput=入力エラー
DataSetParameterBindingInputDialog.Label.Name=パラメタ名 :
DataSetParametersPage.ErrorMessage.CanootBeNull=値は null にできません。
DataSetParameterBindingInputDialog.Label.DataType=データ型 :
DataSetParameterBindingInputDialog.Label.Value=値 :
DataSetParametersPage.Prompt.new=<ここに新しいパラメタを入力してください...>
DataSetParametersPage.default.None=N/A
DataSetParametersPage.reportParam.None=なし
DataSetParameterPage.cell.linkToSalarParameter=リンク先のレポートパラメタ
DataSetParameterPage.title.ParameterInputDialog=パラメタ
DataSetParameterPage.toolTipText.New=パラメタの新規作成
DataSetParameterPage.toolTipText.Edit=パラメタの編集
DataSetParameterPage.toolTipText.Remove=パラメタの削除
DataSetParameterPage.toolTipText.Up=パラメタを上に移動
DataSetParameterPage.toolTipText.Down=パラメタを下に移動

###########################################################
#PropertyBindingpage properties
PropertyBindingPage.datasource.property.empty=このデータソースのパブリックプロパティは、ODA 拡張で定義されていません。
PropertyBindingPage.dataset.property.empty=このデータセットのパブリックプロパティは、ODA 拡張で定義されていません。
PropertyBindingPage.dataset.queryText=クエリテキスト(&Q)
PropertyBindingPage.property.tooltip=実行時のプロパティのバインドを定義します。
PropertyBindingPage.button.tooltip=式ビルダを開き、{0} の値を入力します。

###########################################################
#DataSetProcess properties

DataSetProcess.action.Delete=データセットの削除
DataSetProcess.action.Edit=データセットの編集
DataSetProcess.action.Preview=プレビュー
DataSetProcess.text.DisplayName=データセット
DataSetProcess.text.Prefix=このデータソースは、次のデータセットで使用されています:
DataSetProcess.text.Show=このデータセットのエディタページを表示します。
DataSetProcess.text.Suffix=この要素を削除しますか ?

###########################################################
#datasource properties

datasource.action.edit=編集
datasource.edit=データソースの編集 - {0}
datasource.new.defaultName=データソース
datasource.new=新規データソース
datasource.wizard.label.dataSourceName=データソース名(&M) :
datasource.wizard.label.datasources=次の一覧のデータソース型を使って作成する
datasource.wizard.label.datasources=次の一覧のデータソース型を使って作成する
datasource.wizard.label.connectionfile=プロファイルストアの接続プロファイルを使って作成する
datasource.wizard.message.selectType=新しいデータソースのすべての設定を指定するか、定義済みの接続プロファイルを選択してください。
datasource.wizard.title.select=データソースの種類または接続プロファイルの選択
datasource.editor.property=プロパティのバインド

###########################################################
#DataSourceProcess properties

DataSourceProcess.action.Delete=データソースの削除
DataSourceProcess.action.Edit=データソースの編集
DataSourceProcess.text.DisplayName=データソース
DataSourceProcess.text.Prefix=このデータソースは、次のデータセットで使用されています。
DataSourceProcess.text.Show=このデータソースのエディタページを表示します。  
DataSourceProcess.text.Suffix=この要素を削除しますか ?

###########################################################
#DataSourceSelectionPage properties

DataSourceSelectionPage.ScriptDataSource.DisplayName=スクリプト記述済みのデータソース

###########################################################
#DataSourcesSlotOutlineProcess properties

DataSourcesSlotOutlineProcess.action.New=新規データソース

###########################################################
#datatypes properties

datatypes.any=任意
datatypes.auto=自動
datatypes.dateTime=日時
datatypes.decimal=10進
datatypes.float=浮動
datatypes.integer=整数
datatypes.string=文字列

###########################################################
#DataView properties

DataView.defaultText.noDataView=データビューがありません。

###########################################################
#DataViewTreeViewerPage properties

DataViewTreeViewerPage.tooltip.DoubleClickToEdit=ダブルクリックして編集します。
DataViewTreeViewerPage.tooltip.DragToInsertColumn=列をドラッグして挿入します。 
DataViewTreeViewerPage.tooltip.DragToInsertDataSetColumns=すべてのデータセット列をドラッグして挿入します。 
DataViewTreeViewerPage.tooltip.DragToInsertParameter=レポートパラメタをドラッグして挿入します。 

###########################################################
#DebugUtil properties

DebugUtil.importProject.fail="既存のプロジェクトをインポートできません。"

###########################################################
#DecorationFieldEditor properties

DecorationFieldEditor.text.Linethrough=取り消し線
DecorationFieldEditor.text.Overline=上線
DecorationFieldEditor.text.Underline=下線

###########################################################
#DefaultNodeProvider properties

DefaultNodeProvider.Dlg.Confirm=削除しますか ?
DefaultNodeProvider.ParameterGroup.ConfirmMessage=パラメタグループを削除しようとしています。パラメタグループを削除すると、そのグループに含まれるすべてのパラメタが削除されます。続行しますか ?
DefaultNodeProvider.ParameterGroup.ConfirmTitle=パラメタグループの削除確認
DefaultNodeProvider.Tree.Body=本文
DefaultNodeProvider.Tree.Clients=\\ には次のクライアントがあります。
DefaultNodeProvider.Tree.ColumnHedings=列見出し
DefaultNodeProvider.Tree.Components = レポート項目
DefaultNodeProvider.Tree.DataSets=データセット
DefaultNodeProvider.Tree.DataSources=データソース
DefaultNodeProvider.Tree.Detail=詳細
DefaultNodeProvider.Tree.Footer=フッタ
DefaultNodeProvider.Tree.Groups=グループ
DefaultNodeProvider.Tree.Header=ヘッダ
DefaultNodeProvider.Tree.Images=埋め込まれたイメージ
DefaultNodeProvider.Tree.Invalid=ノードが無効です
DefaultNodeProvider.Tree.MasterPages=マスタページ
DefaultNodeProvider.Tree.PageSetup=ページ設定
DefaultNodeProvider.Tree.Parameters=レポートパラメタ
DefaultNodeProvider.Tree.Reference=参照が見つかりました。
DefaultNodeProvider.Tree.Scratch=スクラッチパッド
DefaultNodeProvider.Tree.Styles=スタイル
DefaultNodeProvider.Tree.Themes=テーマ
DefaultNodeProvider.WarningDialog.Title=警告
DefaultNodeProvider.WarningDialog.EmptyList=挿入できる要素はありません。

###########################################################
#DeleteAction properties

DeleteAction.text=削除(&D)
DeleteAction.trans=要素の削除

###########################################################
#DeleteColumnAction properties

DeleteColumnAction.actionMsg.delete=削除(&D)

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.actionMsg.deleteGroup=グループの削除(&G)

###########################################################
#DeleteListGroupAction properties

DeleteListGroupAction.actionMsg.deleteGroup=グループの削除(&G)

###########################################################
#DeleteRowAction properties

DeleteRowAction.actionMsg.delete=削除(&D)

###########################################################
#designer properties

designer.preview.browserTitle=プレビュー
designer.preview.preference.browser.autoSave=プレビュー前に自動的に保存する
designer.preview.preference.browser.browse=参照(&B)...
designer.preview.preference.browser.currentBrowsers=現在の外部 Web ブラウザのアダプタ(&U) :
designer.preview.preference.browser.description=BIRT レポートをプレビューする Web ブラウザを選択します。\nWeb ブラウザのアダプタが 1 つしか設定されていない場合は、\n選択内容を変更できません。
designer.preview.preference.browser.details=ブラウザプログラムの選択
designer.preview.preference.browser.program=カスタムブラウザコマンド(&S) :
designer.preview.preference.browser.svg=SVG グラフを有効にする(&E)
designer.preview.preference.masterpagecontent=マスタページコンテンツを有効にする(&M)
designer.preview.preference.browser.useExternal=常に外部ブラウザを使用する(&W)
designer.preview.preference.elementname.columnwidth=125
designer.preview.preference.elementname.customname.Enabled=true
designer.preview.preference.elementname.customname=デフォルトの名前
designer.preview.preference.elementname.defaultname.Enabled=false    
designer.preview.preference.elementname.defaultname=要素名
designer.preview.preference.elementname.description.Enabled=false
designer.preview.preference.elementname.description=説明
designer.preview.preference.elementname.Enabled=true 
designer.preview.preference.locale.description=ロケールの選択(&C) :
designer.preview.preference.resultset.sqldatasetpage.group.title=クエリページ
designer.preview.preference.resultset.previewpage.group.title=プレビューページ
designer.preview.preference.resultset.maxNoOfSchema.description=表示するスキーマの最大数(&S) :
designer.preview.preference.resultset.maxNoOfTable.description=各スキーマに表示するテーブルの最大数(&T) :
designer.preview.preference.resultset.maxNoOfSchema.errormessage=最大スキーマ数には、0 から {0} までの数を入力してください。
designer.preview.preference.resultset.maxNoOfTable.errormessage=各スキーマの最大テーブル数には、0 から {0} までの数を入力してください。
designer.preview.preference.resultset.maxrow.description=表示する行の最大数(&R) :
designer.preview.preference.resultset.maxrow.errormessage=最大行数には、1 から {0} までの数を入力してください。
designer.preview.preference.server.description=内部アプリケーションサーバの設定。サーバは、BIRT Report Designer\nPreview Framework 内部で使用されます。
designer.preview.preference.server.hostDescription=ローカルマシンのホスト名または IP アドレス(&H)\n自動的に決定するには、空白のままにしてください。
designer.preview.preference.server.note=注 :
designer.preview.preference.server.portDescription=サーバがリスンするポート(&P)\n動的に割り当てるには 0 に設定します。
designer.preview.preference.server.requireRestart=サーバがすでに実行している場合は、サーバを再起動するまでこれらの設定は\n有効になりません。
designer.preview.previewaction.label.webviewer=Web ビューアでレポートを表示する
designer.preview.previewaction.label=レポートを {0} として表示する
designer.preview.previewaction.ErrorMessage=iText がインストールされていないか見つからないため、PDF の生成は有効になっていません。
designer.preview.previewaction.ErrorMessage.title=警告

###########################################################
#DesignerActionBarContributor properties

DesignerActionBarContributor.element.group=グループの挿入(&G)
DesignerActionBarContributor.element.InsertColumnLeft=左側に列を挿入(&L)
DesignerActionBarContributor.element.InsertColumnRight=右側に列を挿入(&R)
DesignerActionBarContributor.element.InsertRowAbove=上に行を挿入(&A)
DesignerActionBarContributor.element.InsertRowBelow=下に行を挿入(&B)
DesignerActionBarContributor.element.merge=セルを結合する(&M)
DesignerActionBarContributor.element.split=セルの分割(&S)
designerActionBarContributor.menu.data-newdataset=新規データセット(&E)
designerActionBarContributor.menu.data-newdatasource=新規データソース(&O)
DesignerActionBarContributor.menu.data=データ(&D)
DesignerActionBarContributor.menu.element-EditGroup=グループの編集(&E)
DesignerActionBarContributor.menu.element-LayoutMode=レイアウトモード(&D)
DesignerActionBarContributor.menu.element-showRuler=ルーラの表示(&R)
DesignerActionBarContributor.menu.element.editDataBinding=データバインドの編集(&B)
DesignerActionBarContributor.menu.element=要素(&l)
DesignerActionBarContributor.menu.format=書式
DesignerActionBarContributor.menu.insert=挿入(&I)
DesignerActionBarContributor.menu.page=ページ(&G)
DesignerActionBarContributor.menu.style-rule-apply=スタイルの適用(&P)
DesignerActionBarContributor.menu.style-rule-edit=スタイルの編集(&D)
DesignerActionBarContributor.style.new=スタイルの新規作成(&N)...
DesignerActionBarContributor.menu.data-NewParameter=新規レポートパラメタ(&P)

###########################################################
#DesignerOutlinePage properties

DesignerOutlinePage.action.Delete=選択項目の削除
DesignerOutlinePage.action.Hide=ヘッダとフッタの非表示
DesignerOutlinePage.action.Redo=やり直し
DesignerOutlinePage.action.Undo=元に戻す
DesignerOutlinePage.menu.Filters=フィルタ

###########################################################
#DesignerPaletteFactory properties

DesignerPaletteFactory.categoryName.reportItems=レポート項目
DesignerPaletteFactory.elementLabel.data=データ
DesignerPaletteFactory.elementLabel.grid=グリッド
DesignerPaletteFactory.elementLabel.image=イメージ
DesignerPaletteFactory.elementLabel.label=ラベル
DesignerPaletteFactory.elementLabel.list=リスト
DesignerPaletteFactory.elementLabel.tabel=テーブル
DesignerPaletteFactory.elementLabel.text=テキスト
DesignerPaletteFactory.elementName.data=データ
DesignerPaletteFactory.elementName.grid=グリッド
DesignerPaletteFactory.elementName.image=イメージ
DesignerPaletteFactory.elementName.label=ラベル
DesignerPaletteFactory.elementName.list=リスト
DesignerPaletteFactory.elementName.table=テーブル
DesignerPaletteFactory.elementName.text=テキスト
DesignerPaletteFactory.elementName.textdata=ダイナミックテキスト
DesignerPaletteFactory.toolTip.dataReportItem=データセットの列または式の結果を挿入します。
DesignerPaletteFactory.toolTip.gridReportItem=その他の項目を視覚的に整列するための行と列のレイアウトを挿入します。
DesignerPaletteFactory.toolTip.imageReportItem=ファイルまたは URL からイメージを挿入します。
DesignerPaletteFactory.toolTip.labelReportItem=スタティックテキストを挿入します。 
DesignerPaletteFactory.toolTip.listReportItem=ヘッダ、詳細、フッタのデータセット行に、自由書式のプレゼンテーションを挿入します。
DesignerPaletteFactory.toolTip.multiLineDataReportItem=ファイル、データセット列、または式の結果から、テキストブロック (標準のテキスト、HTML、RTF のいずれか) を挿入します。
DesignerPaletteFactory.toolTip.tableReportItem=ヘッダ、詳細、フッタのデータセット行に、列のプレゼンテーションを挿入します。
DesignerPaletteFactory.toolTip.textDataReportItem=オプションで CLOB データ式を含むテキストブロックを挿入します。
DesignerPaletteFactory.toolTip.textReportItem=オプションでインライン式を含むテキストブロック (標準のテキストまたは HTML) を挿入します。

###########################################################
#DimensionBuilderDialog properties

DimensionBuilderDialog.LabelMeasure=計測 :
DimensionBuilderDialog.LabelUnit=単位 :
DimensionBuilderDialog.Title=次元ビルダ

###########################################################
#DNDUtil properties

DNDUtil.trans.copy=要素のコピー
DNDUtil.trans.cut=要素の移動

###########################################################
#DuplicatesPage properties

DuplicatesPage.Check.HideDuplicates=重複の非表示
DuplicatesPage.Group.Repeat=重複 (繰り返し)
DuplicatesPage.Group.RepeatonPage=重複 (ページ内の繰り返し)
DuplicatesPage.Label.RepeatInfo=直前のデータ行と同じ値を非表示にします。
DuplicatesPage.Label.RepeatOnPage.1=直前の行と同じ値を非表示にしますが、
DuplicatesPage.Label.RepeatOnPage.2=\\ \\ 各ページの先頭の値は常に表示します。
DuplicatesPage.Label.ResetonGroup=次のグループのリセット
DuplicatesPage.Radio.Repeat=繰り返し
DuplicatesPage.Radio.RepeatonPage=ページ内で繰り返し

###########################################################
#EditAction properties

EditAction.text=編集

###########################################################
#EditGroupAction properties

EditGroupAction.stackMsg.editGroup=グループの編集

###########################################################
#EditGroupAction properties
InsertGroupHeaderFooterAction.stackMsg.editGroup=グループヘッダ/フッタの挿入
InsertGroupHeaderFooterAction.Text.Header=ヘッダ
InsertGroupHeaderFooterAction.Text.Footer=フッタ

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.stackMsg.deleteGroup=グループの削除

###########################################################
#EditLabelAction properties

EditLabelAction.text=編集

###########################################################
#Element properties

Element.Cell.colSpan=列の幅 :
Element.Cell.column=列 :
Element.Cell.drop=ドロップ(&D) :
Element.Cell.height=高さ :
Element.Cell.rowSpan=行の幅 :
Element.Cell.slot.content=コンテンツ :
Element.Cell.verticalAlign=垂直方向の配置 :
Element.Cell.width=幅 :
Element.Column.alignment=配置 :
Element.Column.repeat=繰り返し :
Element.Column.width=幅(&W) :
Element.Column.suppressDuplicates=重複を表示しない
Element.Container.slot.reportItems=レポート項目 :
Element.Data.action=実行 :
Element.Data.helpText=ヘルプテキスト :
Element.Data.helpTextID=ヘルプテキストキー
Element.TextData.valueExpr=値式(&V) :
Element.DataSet.afterClose.toolTip=データセットを閉じた直後に呼び出されます。
Element.DataSet.afterClose=閉じた後 :
Element.DataSet.afterOpen.toolTip=データセットを開いた直後に呼び出されます。
Element.DataSet.afterOpen=開いた後 :
Element.DataSet.beforeClose.toolTip=データセットを閉じる直前に呼び出されます。
Element.DataSet.beforeClose=閉じる前 :
Element.DataSet.beforeOpen.toolTip=データセットを開いく直前に呼び出されます。
Element.DataSet.beforeOpen=開く前 :
Element.DataSet.cachedMetaData=キャッシュされたメタデータ :
Element.DataSet.columnHints=列のヒント :
Element.DataSet.computedColumns=計算列 :
Element.DataSet.dataSource=データソース :
Element.DataSet.filter=フィルタ :
Element.DataSet.inputParameters=入力パラメタ :
Element.DataSet.onFetch.toolTip=データセットからデータ行をフェッチする直前に呼び出されます。
Element.DataSet.onFetch=フェッチ時 :
Element.DataSet.outputParameters=出力パラメタ :
Element.DataSet.paramBindings=パラメタバインド :
Element.DataSet.resultSet=結果セット :
Element.DataSource.afterClose.toolTip=データソースを閉じた直後に呼び出されます。
Element.DataSource.afterClose=閉じた後 :
Element.DataSource.afterOpen.toolTip=データソースを開いた直後に呼び出されます。
Element.DataSource.afterOpen=開いた後 :
Element.DataSource.beforeClose.toolTip=データソースを閉じる直前に呼び出されます。
Element.DataSource.beforeClose=閉じる前 :
Element.DataSource.beforeOpen.toolTip=データソースを開いく直前に呼び出されます。
Element.DataSource.beforeOpen=開く前 :
Element.ExtendedItem.extension=拡張子名 :
Element.ExtendedItem.extensionName=拡張子名 :
Element.FreeForm.slot.reportItems=レポート項目 :
Element.GraphicMasterPage.columns=列 :
Element.GraphicMasterPage.columnSpacing=列の間隔 :
Element.GraphicMasterPage.slot.contents=コンテンツ :
Element.Grid.slot.columns=列 :
Element.Grid.slot.row=行 :
Element.Image.action=実行 :
Element.Image.altText=代替テキスト(&A) :
Element.Image.altTextID=代替テキストキー
Element.Image.helpText=ヘルプテキスト :
Element.Image.helpTextID=ヘルプテキストキー
Element.Image.imageName=イメージ名 :
Element.Image.scale=スケール :
Element.Image.size=サイズ :
Element.Image.source=ソース :
Element.Image.typeExpr=型式 :
Element.Image.uri=URI :
Element.Image.valueExpr=値式 :
Element.JdbcDataSource.dataSource=データソース :
Element.JdbcDataSource.driver=ドライバ :
Element.JdbcDataSource.password=パスワード :
Element.JdbcDataSource.url=URL :
Element.JdbcDataSource.userName=ユーザ名 :
Element.JdbcSelectDataSet.getStatement.toolTip=クエリのカスタム SQL 文を返します。
Element.JdbcSelectDataSet.getStatement=Get 文 :
Element.JdbcSelectDataSet.statement=文 :
Element.Label.action=実行 :
Element.Label.helpText=ヘルプテキスト :
Element.Label.helpTextID=ヘルプテキストキー
Element.Label.text=テキスト :
Element.Label.textID=テキストキー(&T) :
Element.Line.orientation=向き :
Element.List.slot.columnHeader=列ヘッダ :
Element.List.slot.detail=詳細 :
Element.List.slot.footer=フッタ :
Element.List.slot.group=グループ :
Element.List.slot.header=ヘッダ :
Element.ListGroup.slot.footer=フッタ :
Element.ListGroup.slot.header=ヘッダ :
Element.Listing.filter=フィルタ :
Element.Listing.onFinish.toolTip=この要素のデータセットから最後の行が読み込まれた後で、フッタバンドが作成される前に呼び出されます。
Element.Listing.onFinish=終了時 :
Element.Listing.onRow.toolTip=この要素のデータセットから各行が取得された際に、その行のコンテンツが作成される前に呼び出されます。
Element.Listing.onRow=行ごと :
Element.Listing.onStart.toolTip=データセットを開いた後、ヘッダバンドを作成して、この要素のデータセットから最初の行が取得される前に呼び出されます。 
Element.Listing.onStart=開始時 :
Element.Listing.pageBreakInterval=改ページの間隔(&P) :
Element.Listing.sorting=ソート :
Element.ListingGroup.filter=フィルタ :
Element.ListingGroup.groupName=名前
Element.ListingGroup.interval=間隔 :
Element.ListingGroup.intervalRange=間隔の範囲 :
Element.ListingGroup.keyExpr=キーの式
Element.ListingGroup.onFinish.toolTip=この要素のデータセットから最後の行が読み込まれた後で、フッタバンドが作成される前に呼び出されます。
Element.ListingGroup.onFinish=終了時 :
Element.ListingGroup.onRow.toolTip=この要素のデータセットから各行を取得した際に、その行のコンテンツを作成する前に呼び出されます。
Element.ListingGroup.onRow=行ごと :
Element.ListingGroup.onStart.toolTip=データセットを開いた後、ヘッダバンドを作成して、この要素のデータセットから最初の行が取得される前に呼び出されます。
Element.ListingGroup.onStart=開始時 :
Element.ListingGroup.pageBreakAfter=次の後で改ページ :
Element.ListingGroup.pageBreakBefore=次の前で改ページ :
Element.ListingGroup.sort=ソート :
Element.ListingGroup.sortDirection=ソート方向 :
Element.ListingGroup.toc=目次 :
Element.MasterPage.bottomMargin=下余白 :
Element.MasterPage.columns=列 :
Element.MasterPage.columnSpacing=列の間隔 :
Element.MasterPage.height=高さ (&E):
Element.MasterPage.leftMargin=左余白 :
Element.MasterPage.margin=余白 :
Element.MasterPage.orientation=向き (&O):
Element.MasterPage.rightMargin=右余白 :
Element.MasterPage.slot.contents=コンテンツ :
Element.MasterPage.topMargin=上余白 :
Element.MasterPage.type=タイプ (&T):
Element.MasterPage.width=幅 (&W):
Element.Module.author=作成者(&U) :
Element.Module.base=基本 :
Element.Module.colorPalette=カラーパレット :
Element.Module.comments=コメント(&C) :
Element.Module.configVars=設定変数 :
Element.Module.createdBy=作成環境(&C) :
Element.Module.description=説明(&D) :
Element.Module.descriptionID=説明キー :
Element.Module.helpGuide=ヘルプガイド :
Element.Module.images=イメージ :
Element.Module.includeLibraries=インクルードするライブラリ :
Element.Module.includeResource=リソースファイル(&R) :
Element.Module.includeScripts=インクルードするスクリプト :
Element.Module.initialize.toolTip=レポートの実行を開始する際に呼び出されます。
Element.Module.initialize=初期化 :
Element.Module.theme=テーマ(&M)
Element.Module.title=タイトル(&T) :
Element.Module.titleID=タイトルキー :
Element.Module.units=単位(&S) :
Element.MultiLineData.contentTypeExpr=コンテンツ型の式 :
Element.MultiLineData.valueExpr=値式 :
Element.OdaDataSet.privateDriverDesignState=プライベートドライバの設計情報 :
Element.OdaDataSet.privateDriverProperties=プライベートドライバのプロパティ :
Element.OdaDataSet.publicDriverProperties=パブリックドライバのプロパティ :
Element.OdaDataSet.queryScript.toolTip=TBD :
Element.OdaDataSet.queryScript=スクリプト :
Element.OdaDataSet.queryText=クエリ :
Element.OdaDataSet.resultSetName=結果セット名 :
Element.OdaDataSet.type=次のように入力します。
Element.OdaDataSource.driverName=ドライバ名 :
Element.OdaDataSource.privateDriverProperties=プライベートドライバのプロパティ :
Element.OdaDataSource.publicDriverProperties=パブリックドライバのプロパティ :
Element.Parameter.helpText=ヘルプテキスト :
Element.Parameter.helpTextID=ヘルプテキストキー
Element.Parameter.hidden=非表示 :
Element.ParameterGroup.helpText=ヘルプテキスト :
Element.ParameterGroup.helpTextID=ヘルプテキストキー
Element.ParameterGroup.slot.parameters=パラメタ :
Element.ParameterGroup.startExpanded=開始時に展開 :
Element.ReportDesign.afterCloseDoc.toolTip=生成フェーズでレポート文書ファイルを閉じた直後に呼び出されます。
Element.ReportDesign.afterCloseDoc=文書を閉じた後 :
Element.ReportDesign.afterFactory.toolTip=生成フェーズでの処理が終了した際に、レポート文書 (該当する場合) を閉じた後に呼び出されます。これは、生成フェーズで呼び出される最後のメソッドです。
Element.ReportDesign.afterFactory=Factory での処理後 :
Element.ReportDesign.afterOpenDoc.toolTip=生成フェーズでレポート文書を開いた直後に呼び出されます。
Element.ReportDesign.afterOpenDoc=文書を開いた後 :
Element.ReportDesign.afterRender.toolTip=プレゼンテーション時のアクションを開始した後に呼び出されます。
Element.ReportDesign.afterRender=レンダリング後 :
Element.ReportDesign.beforeCloseDoc.toolTip=生成フェーズでレポート文書ファイルを閉じる直前に呼び出されます。
Element.ReportDesign.beforeCloseDoc=文書を閉じる前 :
Element.ReportDesign.beforeFactory.toolTip=生成フェーズでの処理を開始する際に、initialize( ) メソッドを実行した後、レポート文書 (該当する場合) を開く前に呼び出されます。
Element.ReportDesign.beforeFactory=Factory での処理前 :
Element.ReportDesign.beforeOpenDoc.toolTip=生成フェーズでレポート文書を開く直前に呼び出されます。
Element.ReportDesign.beforeOpenDoc=文書を開く前 :
Element.ReportDesign.beforeRender.toolTip=プレゼンテーション時のアクションを開始する前に呼び出されます。
Element.ReportDesign.beforeRender=レンダリング前 :
Element.ReportDesign.displayName=表示名(&Y) : 
Element.ReportDesign.eventHandlerClass=イベントハンドラのクラス(&V) :
Element.ReportDesign.iconFile=プレビューイメージ(&P) : 
Element.ReportDesign.refreshRate=更新頻度 :
Element.ReportElement.comments=コメント(&C) :
Element.ReportElement.customXml=カスタム XML :
Element.ReportElement.displayName=表示名 :
Element.ReportElement.displayNameID=表示名キー :
Element.ReportElement.extends=拡張 :
Element.ReportElement.javaClass=Java クラス :
Element.ReportElement.name=名前(&N) :
Element.ReportElement.propertyMask=プロパティマスク :
Element.ReportElement.style=スタイル(&T) :
Element.ReportItem.bookmark=ブックマーク(&B) :
Element.ReportItem.dataSet=データセット :
Element.ReportItem.height=高さ(&H) :
Element.ReportItem.onCreate.toolTip=生成フェーズで要素を作成する際に実行されました。
Element.ReportItem.onCreate=作成時 :
Element.ReportItem.onRender.toolTip=プレゼンテーションフェーズで要素をレンダリング用に準備する際に実行されます。
Element.ReportItem.onRender=レンダリング時 :  
Element.ReportItem.paramBindings=パラメタバインド :
Element.ReportItem.toc=目次(&T) :
Element.ReportItem.visibility=可視性 :
Element.ReportItem.width=幅(&W) :
Element.ReportItem.x=X :
Element.ReportItem.y=Y :
Element.Row.bookmark=ブックマーク :
Element.Row.height=高さ(&H) :
Element.Row.slot.cell=セル :
Element.Row.visibility=可視性 :
Element.ScalarParameter.alignment=配置 :
Element.ScalarParameter.allowBlank=空白を許可する :
Element.ScalarParameter.allowNull=Null を許可する :
Element.ScalarParameter.concealValue=値を隠す :
Element.ScalarParameter.controlType=コントロール型(&C) :
Element.ScalarParameter.dataType=データ型(&D) :
Element.ScalarParameter.defaultValue=デフォルト値 :
Element.ScalarParameter.dynamicList.dataSetName=データセット名 :
Element.ScalarParameter.dynamicList.labelExpr=ラベル式 :
Element.ScalarParameter.dynamicList.valueExpr=値式 :
Element.ScalarParameter.dynamicList=動的なリスト :
Element.ScalarParameter.format=書式 :
Element.ScalarParameter.selectionList.fixedOrder=固定順序 :
Element.ScalarParameter.selectionList.mustMatch=必ず一致 :
Element.ScalarParameter.selectionList.selectionList=選択リスト :
Element.ScalarParameter.selectionList=選択リスト :
Element.ScalarParameter.promptTextID=テキストキー(&T) :
Element.ScriptDataSet.close.toolTip=データセットを閉じます。
Element.ScriptDataSet.close=閉じる :
Element.ScriptDataSet.describe.toolTip=結果セットを記述します。
Element.ScriptDataSet.describe=記述 :
Element.ScriptDataSet.fetch.toolTip=DataRow 型のオブジェクトを作成し、読み込み、返します。 
Element.ScriptDataSet.fetch=フェッチ :
Element.ScriptDataSet.open.toolTip=データセットを開きます。
Element.ScriptDataSet.open=開く :
Element.ScriptDataSource.close.toolTip=データソースへの接続を切断します。 
Element.ScriptDataSource.close=閉じる :
Element.ScriptDataSource.open.toolTip=データソースへの接続を確立します。 
Element.ScriptDataSource.open=開く :
Element.SimpleMasterPage.floatingFooter=浮動フッタ(&F)
Element.SimpleMasterPage.footerHeight=フッタの高さ (&F):
Element.SimpleMasterPage.headerHeight=ヘッダの高さ (&H):
Element.SimpleMasterPage.showFooterOnLast=最終ページにフッタを表示(&H)
Element.SimpleMasterPage.showHeaderOnFirst=先頭ページにヘッダを表示(&S)
Element.SimpleMasterPage.slot.pageFooter=ページフッタ :
Element.SimpleMasterPage.slot.pageHeader=ページヘッダ :
Element.Style.background.attachment=添付ファイル(&A) :
Element.Style.background.color=背景色(&B) :
Element.Style.background.image=背景イメージ(&G) :
Element.Style.background.positionX=左右の位置(&H) :
Element.Style.background.positionY=上下の位置(&V) :
Element.Style.background.repeat=繰り返し(&R) :
Element.Style.background=背景 :
Element.Style.border.bottom.color=下(&M) :
Element.Style.border.bottom.style=下(&B) :
Element.Style.border.bottom.width=下 :
Element.Style.border.fillColor=罫線の塗りつぶしの色 :
Element.Style.border.hmiddle.color=中央横の罫線の色 :
Element.Style.border.hmiddle.style=中央横の罫線の線種 :
Element.Style.border.hmiddle.width=中央横の罫線の幅 :
Element.Style.border.left.color=左(&F) :
Element.Style.border.left.style=左(&L) :
Element.Style.border.left.width=左(&E) :
Element.Style.border.right.color=右(&H) :
Element.Style.border.right.style=右(&R) :
Element.Style.border.right.width=右(&I) :
Element.Style.border.top.color=上(&P) :
Element.Style.border.top.style=上(&T) :
Element.Style.border.top.width=上(&O) :
Element.Style.border.vmiddle.color=中央縦の罫線の色 :
Element.Style.border.vmiddle.style=中央縦の罫線の線種 :
Element.Style.border.vmiddle.width=中央縦の罫線の幅 :
Element.Style.border=罫線 :
Element.Style.box=ボックス :
Element.Style.canShrink=縮小可能(&S)
Element.Style.color=カラー(&C) :
Element.Style.display=表示(&Y) :
Element.Style.font.family=フォント(&F) :
Element.Style.font.size=サイズ(&Z) :
Element.Style.font.style=スタイル(&T) :
Element.Style.font.textLineThrough=取り消し線(&L)
Element.Style.font.textOverline=上線(&O)
Element.Style.font.textUnderline=下線(&U)
Element.Style.font.variant=バリエーション :
Element.Style.font.weight=太さ(&W) :
Element.Style.font=フォント(&F) :
Element.Style.format.dateTime=日付 / 時間 :
Element.Style.format.number.align=数値の配置 :
Element.Style.format.number=数値 :
Element.Style.format.string=文字列 :
Element.Style.format=書式 :
Element.Style.highlight.rules=ハイライトの規則 :
Element.Style.highlight.testExpr=テスト式のハイライト :
Element.Style.letterSpacing=文字間隔(&T) :
Element.Style.lineHeight=行の高さ(&N) :
Element.Style.map.rules=マップ規則 :
Element.Style.map.testExpr=マップのテスト式 :
Element.Style.margin.bottom=下(&O) :
Element.Style.margin.left=左(&E) :
Element.Style.margin.right=右(&I) :
Element.Style.margin.top=上(&P) :
Element.Style.masterPage=マスタページ(&M) :
Element.Style.orphans=オーファン(&O) :
Element.Style.padding.bottom=下(&B) :
Element.Style.padding.left=左(&L) :
Element.Style.padding.right=右(&R) :
Element.Style.padding.top=上(&T) :
Element.Style.padding=パディング :
Element.Style.pageBreakAfter=次の後で改ページ(&A) :
Element.Style.pageBreakBefore=次の前で改ページ(&B) :
Element.Style.pageBreakInside=途中で改ページ(&I) :
Element.Style.section=セクション :
Element.Style.showIfBlank=空白でも表示(&W)
Element.Style.text.align=文字列の位置揃え(&X) :
Element.Style.text.indent=文字列のインデント(&X) :
Element.Style.text.transform=文字列の位置変更(&R) :
Element.Style.text=テキスト :
Element.Style.verticalAlign=垂直方向の配置(&V) :
Element.Style.whiteSpace=スペース(&H) :
Element.Style.widows=ウィドウ(&D) :
Element.Style.wordSpacing=単語間の間隔(&W) :
Element.Table.caption=キャプション :
Element.Table.captionID=キャプションキー :
Element.Table.repeatHeader=ヘッダの繰り返し :
Element.Table.slot.columnHeader=列ヘッダ :
Element.Table.slot.columns=列 :
Element.Table.slot.detail=詳細 :
Element.Table.slot.footer=フッタ :
Element.Table.slot.group=グループ :
Element.Table.slot.header=ヘッダ :
Element.TableGroup.slot.footer=フッタ :
Element.TableGroup.slot.header=ヘッダ :
Element.Text.content=コンテンツ :
Element.Text.contentID=コンテンツキー(&K) :
Element.Text.contentType=コンテンツの種類(&P) :
Element.TemplateElement.name=名前(&N)

###########################################################
#EmbeddedImageNodeProvider properties

EmbeddedImageNodeProvider.action.New=新しく埋め込まれたイメージ

###########################################################
#EmbeddedImagesNodeProvider properties

EmbeddedImagesNodeProvider.action.New=新しく埋め込まれたイメージ

###########################################################
#EmptyEditPart properties

EmptyEditPart.Msg.EmptyLib=ライブラリにビジュアル要素がありません。ビジュアル要素を追加するには、項目をパレットからライブラリのアウトラインビューへドラッグするか、アウトラインビューの［挿入］メニューを使用します。
EmptyEditPart.Msg.NonVisual=選択した要素は、ビジュアル要素ではありません。

###########################################################
#error properties

error.duplicateName=この名前は、同じ名前空間ですでに使用されています。
error.emptyName=データソース名は空白にできません。
error.invalidName="{0}" は無効な名前です。名前には "." (ピリオド) を使用できません。

###########################################################
#ExceptionHandler properties

ExceptionHandler.Label.ErrorCode=エラーコード
ExceptionHandler.Label.ErrorMessage=エラーメッセージ
ExceptionHandler.Label.PluginId=Plug-in ID:
ExceptionHandler.Label.PluginName=Plug-in Name:
ExceptionHandler.Label.PluginProvider=Plug-in Provider:
ExceptionHandler.Label.PluginVersion=Version:
ExceptionHandler.Label.UnknownPlugin=Unknown plug-in
ExceptionHandler.Meesage.UnexceptedExceptionOccur=内部で例外が発生しました。詳しくはログファイルを参照してください。
ExceptionHandler.Message.BirtExceptionOccur=BIRT で例外が発生しました。
ExceptionHandler.Message.CausedBy=Caused by {0}
ExceptionHandler.Message.FileNotFound=File not found:
ExceptionHandler.Message.OutOfMemory=空きメモリが不足しています。
ExceptionHandler.Message.PartInitError=部分初期化中にエラーが発生しました。
ExceptionHandler.Message.SemanticFail=Semantic Checker でエラーが発生しました。
ExceptionHandler.Message.UnexceptedExceptionOccur=内部で例外が発生しました。詳しくはログファイルを参照してください。
ExceptionHandler.Message.UnknownHost=不明なホストです :
ExceptionHandler.Title.Error=エラー
ExceptionHandler.Title.FileNotFound=ファイルが見つかりません。
ExceptionHandler.Title.PartInitError=部分初期化中にエラーが発生しました。
ExceptionHandler.Title.UnknownHost=不明なホストです。

###########################################################
#ExportAction properties

ExportAction.actionMsg.export=エクスポート

###########################################################
#ExportToLibraryAction properties

ExportToLibraryAction.action.text=ライブラリにエクスポート(&E)...
ExportToLibraryAction.Button.Cancel=キャンセル
ExportToLibraryAction.Button.No=いいえ
ExportToLibraryAction.Button.Yes=はい
ExportToLibraryAction.Dialog.Message=\nエクスポート先のライブラリには、同じデザイン要素があります。上書きしますか ?
ExportToLibraryAction.Dialog.Title=要素のエクスポート
ExportToLibraryAction.Message.RememberDecision=次回から同じ設定を使う

###########################################################
#LibraryExplorerTreeViewPage tooltips
LibraryExplorerTreeViewPage.toolTips.DragAndDropOutline=アウトラインビューへドラッグ＆ドロップ
LibraryExplorerTreeViewPage.toolTips.DragAndDropLayout=レイアウトエディタへドラッグ＆ドロップ
LibraryExplorerTreeViewPage.toolTips.DragAndDropToOutlineORLayout=アウトラインビューまたはレイアウトエディタへドラッグ＆ドロップ

###########################################################
#ExpressionBuidler properties

ExpressionBuidler.Dialog.Title=計算式ビルダ
ExpressionBuilder.toolTipText.Button=式ビルダを開く

###########################################################
#ExpressionBuilder properties

ExpressionBuilder.Label.Category=カテゴリ :
ExpressionBuilder.Label.Functions=ダブルクリックして挿入 :
ExpressionBuilder.Label.Operators=演算子 :
ExpressionBuilder.Label.SubCategory=サブカテゴリ :
ExpressionBuilder.Message.Prompt=[式] フィールドに式を入力してください。使用可能なオブジェクトの一覧を参照し、式に使用する項目をダブルクリックしてコピーします。

###########################################################
#ExpressionPropertyDescriptor properties

ExpressionPropertyDescriptor.text.Edit=計算式ビルダ(&X)...

###########################################################
#ExpressionProvider properties

ExpressionProvider.Category.Context=コンテキスト
ExpressionProvider.Category.BirtObjects=BIRT 関数
ExpressionProvider.Category.DataSets=使用可能なデータセット
ExpressionProvider.Category.NativeObjects=ネイディブ JavaScript 関数
ExpressionProvider.Category.ColumnBinding=使用可能なカラムバインド
ExpressionProvider.Category.Operators=演算子
ExpressionProvider.Category.Parameters=レポートパラメタ
ExpressionProvider.Label.All=---すべて---
ExpressionProvider.Operator.Add=2 つの値を加算します。
ExpressionProvider.Operator.AddTo=現在の値に加算するショートカットです。
ExpressionProvider.Operator.And=2 つの式を調べ、両方の式が True の場合に、True 値を返します。
ExpressionProvider.Operator.Assign=値を別の値と等しくします。
ExpressionProvider.Operator.BitAnd=A & B : A と B のビット単位の AND を返します。
ExpressionProvider.Operator.BitOr=A | B : A と B のビット単位の OR を返します。
ExpressionProvider.Operator.Dec=値を減少させ、結果を返します。
ExpressionProvider.Operator.DividingFrom=現在の値を除算するショートカットです。
ExpressionProvider.Tooltip.ColumnBinding=参照先 
ExpressionProvider.Operator.Divides=左側の値を右側の値で除算し、結果を返します。
ExpressionProvider.Operator.Equals=項が等しい場合に、True 値を返します。
ExpressionProvider.Operator.Greater=A > B : A が B より大きい場合に、True 値を返します。
ExpressionProvider.Operator.GreaterEquals=A >= B : A が B 以上の場合に、True 値を返します。
ExpressionProvider.Operator.Inc=値を増加させ、結果を返します。
ExpressionProvider.Operator.LeftBracket=左かっこ
ExpressionProvider.Operator.RightBracket=右かっこ
ExpressionProvider.Operator.Less=A < B : A が B より小さい場合に、True 値を返します。
ExpressionProvider.Operator.LessEqual=A <= B : A が B 以下の場合に、True 値を返します。
ExpressionProvider.Operator.Mult=2 つの値を乗算します。
ExpressionProvider.Operator.MultTo=現在の値を乗算するショートカットです。
ExpressionProvider.Operator.Not=!A : A が false である場合は true を、A が true である場合は false を返します。
ExpressionProvider.Operator.NotEqual=A <> B : A が B と等しくない場合に、True 値を返します。
ExpressionProvider.Operator.Or=2 つの式を調べ、どちらか一方の式だけが True の場合に、True 値を返します。
ExpressionProvider.Operator.ReturnDec=値を返してから、減少させます。
ExpressionProvider.Operator.ReturnInc=値を返してから、増加させます。
ExpressionProvider.Operator.Sub=1 つの値からもう 1 つの値を減算します。
ExpressionProvider.Operator.SubFrom=現在の値から減算するショートカットです。
ExpressionProvider.Operators.Assignment=代入
ExpressionProvider.Operators.Comparison=比較
ExpressionProvider.Operators.Computational=演算
ExpressionProvider.Operators.Logical=論理
ExpressionProvider.EditBindings=バインドの編集...
ExpressionProvider.Expression.RowNumName=行数
ExpressionProvider.Expression.RowNumTooltip=現在の行数を返す式です。

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<式の構築...>
ExpressionValueCellEditor.selectValueAction=<値の選択...>
ExpressionValueCellEditor.title=値の選択

###########################################################
#ExtendedEditPart properties

ExtendedEditPart.edit={0} の編集

###########################################################
#ExtendedItemPageGenerator properties

ExtendedItemPageGenerator.List.Bookmark=ブックマーク
ExtendedItemPageGenerator.List.TOC=目次

###########################################################
#FilterHandleProvider properties

FilterHandleProvider.ColumnName.Value=値
FilterHandleProvider.Label.Filterby=フィルタの条件 :
FilterHandleProvider.Modify.SaveValues=値の保存

###########################################################
#filters properties

filters.empty.columnName=式は空白にできません。
filters.error.title=入力エラー。
filters.operators.any=次の値のいずれか
filters.operators.between=値に挟まれる
filters.operators.bottomN=下位 (n) 項目
filters.operators.bottomPercent=下位 (n) %
filters.operators.equal=次の値に等しい 
filters.operators.false=False
filters.operators.greaterThan=次の値より大きい
filters.operators.greaterThanEqual=次の値以上
filters.operators.lessThan=次の値より小さい
filters.operators.lessThanEqual=次の値以下
filters.operators.like=次の値に類似
filters.operators.notBetween=値に挟まれない
filters.operators.notEqual=次の値に等しくない
filters.operators.notNull=Not Null
filters.operators.null=Null
filters.operators.topN=上位 (n) 個の項目
filters.operators.topPercent=上位 (n) パーセント
filters.operators.true=True
filters.prompt.new=<ここに新しいフィルタを入力してください...>

###########################################################
#FixTableLayoutCalculator properties

FixTableLayoutCalculator.Error.CannotParse=入力値をパースできません。

###########################################################
#FlowMoveChildCommand properties

FlowMoveChildCommand.transLabel.moveElement=要素の移動

###########################################################
#FontPreferencePage properties

FontPreferencePage.displayname.Title=フォント
FontPreferencePage.label.fontDecoration=文字飾り :
FontPreferencePage.text.Preview=サンプルのプレビュー
FontPreferencePage.text.PreviewContent=Aaあぁアァ亜宇

###########################################################
#FontSizeBuilder properties

FontSizeBuilder.displayname.Auto=自動

###########################################################
#FormatBuilder properties

FormatBuilder.Title=書式ビルダ

###########################################################
#FormatDateTimeAttributePage properties

FormatDateTimeAttributePage.Trans.SetDateTimeFormat = 日付/時間の形式を設定します。

###########################################################
#FormatDateTimePage properties

FormatDateTimePage.label.custom.settings.label=サンプルの書式 (次のいずれかをコピーして変更) :
FormatDateTimePage.label.custom.settings=カスタム設定
FormatDateTimePage.label.format.code=書式コード :
FormatDateTimePage.label.format.page=書式設定(&F) :
FormatDateTimePage.label.general.preview.group=書式付きプレビュー
FormatDateTimePage.label.guide.text=yyyy/mm/dd hh:mm:ss の形式で入力してください。
FormatDateTimePage.label.preview.dateTime=プレビューする日時 : 
FormatDateTimePage.label.preview.group=プレビュー
FormatDateTimePage.label.preview.label=書式付きプレビュー :
FormatDateTimePage.label.table.column.format.code=サンプルの書式
FormatDateTimePage.label.table.column.format.result=サンプルの書式の結果
FormatDateTimePage.preview.invalid.dateTime=プレビューする日時形式が無効です。
FormatDateTimePage.preview.invalid.formatCode=書式コードが無効です。

###########################################################
#FormatDateTimePreferencePage properties

FormatDateTimePreferencePage.formatDateTime.title=日時の書式設定

###########################################################
#FormatNumberAttributePage properties

FormatNumberAttributePage.Trans.SetNumberFormat = 数値の書式を設定します。

###########################################################
#FormatNumberPage properties

FormatNumberPage.currency.symbol.none=記号なし
FormatNumberPage.label.currency.settings=通貨の設定
FormatNumberPage.label.custom.preview.group=プレビュー
FormatNumberPage.label.custom.preview.label=書式付きプレビュー :
FormatNumberPage.label.custom.settings.lable=サンプルの書式 (次のいずれかをコピーして変更) :
FormatNumberPage.label.custom.settings=カスタム設定
FormatNumberPage.label.decimal.places=小数点以下の桁数 : 
FormatNumberPage.label.fixed.settings=固定設定
FormatNumberPage.label.format.code=書式コード :
FormatNumberPage.label.format.number.page=書式設定(&F) :
FormatNumberPage.label.general.preview.group=書式付きプレビュー
FormatNumberPage.label.negative.numbers=負の数値 : 
FormatNumberPage.label.percent.settings=パーセントの設定
FormatNumberPage.label.preview.number=プレビューする数値 : 
FormatNumberPage.label.scientific.settings=指数の設定
FormatNumberPage.label.symbol.position=記号の位置 : 
FormatNumberPage.label.symbol=記号 : 
FormatNumberPage.label.table.column.format.code=サンプルの書式
FormatNumberPage.label.table.column.format.result=サンプルの書式の結果
FormatNumberPage.label.use1000sSeparator=桁区切りを使用する
FormatNumberPage.label.useLeadingZero=先頭に 0 を付ける
FormatNumberPage.preview.invalidFormatCode=書式コードが無効です。
FormatNumberPage.preview.invalidNumber=プレビューする数値が無効です。
FormatNumberPage.symblePos.after=後ろ
FormatNumberPage.symblePos.before=前

###########################################################
#FormatNumberPreferencePage properties

FormatNumberPreferencePage.formatNumber.title=数値の書式設定

###########################################################
#FormatPreferencePage properties

FormatPreferencePage.displayname.Title=書式設定

###########################################################
#FormatStringAttributePage properties

FormatStringAttributePage.Trans.SetStringFormat = 文字列の書式を設定します。

###########################################################
#FormatStringPage properties

FormatStringPage.default.preview.text=サンプル文字列
FormatStringPage.label.custom.preview.label=書式付きプレビュー :
FormatStringPage.label.custom.settings.label=サンプルの書式 (次のいずれかをコピーして変更) :
FormatStringPage.label.customSettings=カスタム設定
FormatStringPage.label.format.code=書式コード :
FormatStringPage.label.formatStringAs=書式設定(&F) :
FormatStringPage.label.preview.group=プレビュー
FormatStringPage.label.preview.string=プレビューする文字列 : 
FormatStringPage.label.previewWithFormat=書式付きプレビュー
FormatStringPage.label.table.collumn.exampleFormatCode=サンプルの書式
FormatStringPage.label.table.collumn.exampleFormatResult=サンプルの書式の結果
FormatStringPage.previewText.invalidFormatCode=書式コードが無効です。

###########################################################
#FormatStringPreferencePage properties

FormatStringPreferencePage.formatString.title=文字列の書式

###########################################################
#FormPage properties

FormPage.Button.Add=追加(&A)
FormPage.Button.AddWithDialog=追加(&A)...
FormPage.Button.Delete=削除(&L)
FormPage.Button.Down=下へ(&N)
FormPage.Button.Edit=編集(&D)
FormPage.Button.EditWithDialog=編集(&D)...
FormPage.Button.Up=上へ(&U)
FormPage.Menu.ModifyProperty=プロパティの変更
FormPage.toolTipText.Up=上に移動
FormPage.toolTipText.Down=下に移動

###########################################################
#GeneralInsertMenuAction properties

GeneralInsertMenuAction.text.Data=データ(&D)
GeneralInsertMenuAction.text.DynamicText=ダイナミックテキスト(&Y)...
GeneralInsertMenuAction.text.Grid=グリッド(&G)
GeneralInsertMenuAction.text.Image=イメージ(&I)
GeneralInsertMenuAction.text.Label=ラベル(&L)
GeneralInsertMenuAction.text.List=リスト(&S)
GeneralInsertMenuAction.text.Table=テーブル(&B)
GeneralInsertMenuAction.text.Text=テキスト(&T)

###########################################################
#GeneralPreferencePage properties

GeneralPreferencePage.errorMsg.duplicate.styleName=スタイル名が重複しています。
GeneralPreferencePage.label.choose.different.name=はすでに使用されています。別の名前を付けてください。
GeneralPreferencePage.label.customStyle=ユーザ設定のスタイル(&C)...
GeneralPreferencePage.label.predefinedStyle=設定済みのスタイル(&P)...
GeneralPreferencePage.label.styleName=スタイル名

###########################################################
#GridEditPart properties

GridEditPart.GUIDEHANDLE_TEXT = グリッド

###########################################################
#GridFigure properties

GridFigure.BORDER_TEXT=グリッド

###########################################################
#GridPageGenerator properties

GridPageGenerator.List.Bookmark=ブックマーク
GridPageGenerator.List.Borders=罫線
GridPageGenerator.List.Font=フォント
GridPageGenerator.List.General=全般
GridPageGenerator.List.Margin=余白
GridPageGenerator.List.Section=ページ区切り
GridPageGenerator.List.TOC=目次
GridPageGenerator.List.Visibility=可視性
GridPageGenerator.TabItem.Highlights=ハイライト
GridPageGenerator.TabItem.map=マップ

###########################################################
#GridProvider properties

GridProvider.action.text=行の挿入

###########################################################
#GroupDialog properties

GroupDialog.Dialog.GroupDetail=グループの詳細
GroupDialog.Dialog.TOC=目次項目の式(&T) :
GroupDialog.DialogTitle.NoData=初期化エラー
GroupDialog.DialogTitle.SemanticCheckFailed=Semantic Checker でエラーが発生しました。
GroupDialog.ErrorMesaage.IllegalGroup=このグループは正しくありません。
GroupDialog.ErrorMessage.NoData=使用できるデータ行がありません。
GroupDialog.Label.FilterSorting=フィルタとソート
GroupDialog.Label.GroupOn=グループ化(&G) :
GroupDialog.Label.HeaderFooter=ヘッダとフッタ
GroupDialog.Label.IncludeFooter=グループフッタを含める(&F)
GroupDialog.Label.IncludeHeader=グループヘッダを含める(&H)
GroupDialog.Label.Interval=間隔(&I) :
GroupDialog.PageBreakBefore=次の前で改ページ :
GroupDialog.PageBreakAfter=次の後で改ページ :
GroupDialog.PageBreakInside=Inside:
GroupDialog.Label.IntervalBase=丸めた数値を間隔の基準値として使用する(&U) :
GroupDialog.Label.Name=名前(&N) :
GroupDialog.Label.Range=範囲(&R) :
GroupDialog.Tab.Binding=データのバインド
GroupDialog.Tab.Filter=フィルタ
GroupDialog.Tab.Sorting=ソート
GroupDialog.RepeatHeader=ヘッダの繰り返し
GroupDialog.Title.Edit=グループの編集
GroupDialog.Title.New=グループの新規作成
GroupDialog.PageBreak=ページ区切り
GroupDialog.buttion.HideDetail=詳細の非表示(&D)
GroupDialog.toolTipText.openExprButton=式ビルダを開く

###########################################################
#GroupHandleProvider properties

GroupHandleProvider.Label.Groups=グループリスト :

###########################################################
#GroupProvider properties

GroupProvider.action.text=グループの編集

###########################################################
#GuiExtensionManager properties

GuiExtensionManager.label.name=拡張項目
GuiExtensionManager.tooltip.insert={0} の挿入

###########################################################
#HighlightHandleProvider properties

HighlightHandleProvider.text.Preview=Aaあぁアァ亜宇  (フォントサイズ : 

###########################################################
#HighlightRuleBuilderDialog properties

HighlightRuleBuilderDialog.choice.ValueOfThisDataItem=このデータ項目の値
HighlightRuleBuilderDialog.text.AND=AND
HighlightRuleBuilderDialog.text.Any=次の値のいずれか
HighlightRuleBuilderDialog.text.BackgroundColor=背景色 :
HighlightRuleBuilderDialog.text.Between=値に挟まれる
HighlightRuleBuilderDialog.text.Color=カラー :
HighlightRuleBuilderDialog.text.Condition=次の条件が True の場合 : 
HighlightRuleBuilderDialog.text.Default=自動
HighlightRuleBuilderDialog.text.ET=次の値に等しい
HighlightRuleBuilderDialog.text.False=False
HighlightRuleBuilderDialog.text.Font=フォント名 :
HighlightRuleBuilderDialog.text.Format=次の書式を適用 : 
HighlightRuleBuilderDialog.text.GE=次の値以上
HighlightRuleBuilderDialog.text.GT=次の値より大きい
HighlightRuleBuilderDialog.text.LE=次の値以下
HighlightRuleBuilderDialog.text.Like=次の値に類似
HighlightRuleBuilderDialog.text.LT=次の値より小さい
HighlightRuleBuilderDialog.text.NE=次の値に等しくない
HighlightRuleBuilderDialog.text.NotBetween=値に挟まれない
HighlightRuleBuilderDialog.text.NotNull=Not Null
HighlightRuleBuilderDialog.text.Null=Null
HighlightRuleBuilderDialog.text.Preview=プレビュー :
HighlightRuleBuilderDialog.text.PreviewContent=Aaあぁアァ亜宇
HighlightRuleBuilderDialog.text.Size=サイズ :
HighlightRuleBuilderDialog.text.Title=ハイライトの規則の追加と編集
HighlightRuleBuilderDialog.text.True=True
HighlightRuleBuilderDialog.tooltip.ExpBuilder=計算式ビルダを起動するには、ここをクリックしてしてください
HighlightRuleBuilderDialog.tooltip.Bold=太字
HighlightRuleBuilderDialog.tooltip.Italic=斜体
HighlightRuleBuilderDialog.tooltip.Underline=下線
HighlightRuleBuilderDialog.tooltip.Text_Line_Through=テキストの取り消し線

###########################################################
#HighlightsPage properties

HighlightsPage.Button.Add=追加(&A)...
HighlightsPage.Button.Delete=削除(&D)
HighlightsPage.Dialog.EditHighlight=ハイライトの編集
HighlightsPage.Dialog.NewHighlight=ハイライトの新規作成
HighlightsPage.Label.Highlights=ハイライトの一覧 :
HighlightsPage.TableColumn.Condition=条件
HighlightsPage.TableColumn.Preview=プレビュー :
HighlightsPage.trans.Add=ハイライトの規則の追加
HighlightsPage.trans.Delete=ハイライトの規則の削除
HighlightsPage.trans.Edit=ハイライトの規則の編集
HighlightsPage.trans.MoveDown=ハイライトの規則を下に移動
HighlightsPage.trans.MoveUp=ハイライトの規則を上に移動
HighlightsPage.toolTipText.MoveDown=ハイライトの規則を下に移動
HighlightsPage.toolTipText.MoveUp=ハイライトの規則を上に移動

###########################################################
#HighlightsPreferencePage properties

HighlightsPreferencePage.displayname.Condition=条件
HighlightsPreferencePage.displayname.Preview=プレビュー
HighlightsPreferencePage.displayname.Title=ハイライト
HighlightsPreferencePage.text.Add=追加(&A)...
HighlightsPreferencePage.text.Delete=削除(&L)
HighlightsPreferencePage.text.Description=ハイライトの一覧 :
HighlightsPreferencePage.text.Edit=編集(&D)...
HighlightsPreferencePage.toolTipText.Up=ハイライト部分を上に移動
HighlightsPreferencePage.toolTipText.Down=ハイライト部分を下に移動

###########################################################
#HyperlinkBuilder properties

HyperlinkBuilder.Column.Parameters=パラメタ
HyperlinkBuilder.DrillThroughStep1=手順 1 : ターゲットレポートの選択 
HyperlinkBuilder.DrillThroughStep2=手順 2 : ターゲットアンカーの選択 
HyperlinkBuilder.DrillThroughStep3=手順 3 : ターゲットのブックマークに一致するリンク式の作成
HyperlinkBuilder.DrillThroughStep4=手順 4 : ターゲットのレポートの表示 
HyperlinkBuilder.DrillThroughStep5=手順 5 : ターゲットのレポートの書式設定 
HyperlinkBuilder.ParameterRequired=必須
HyperlinkBuilder.Column.Values=値
HyperlinkBuilder.DialogTitle=ハイパーリンクのオプション
HyperlinkBuilder.ErrorMessage.InvalidReport=レポートデザインが無効です。
HyperlinkBuilder.ErrorMessage.ReportReqired=レポートファイルを指定してください。
HyperlinkBuilder.DrillThroughTargetBookmark=ターゲットのブックマーク
HyperlinkBuilder.DrillThroughLinkExpression=リンク式 :
HyperlinkBuilder.Label.Bookmark=ブックマーク :
HyperlinkBuilder.Label.Format=書式 :
HyperlinkBuilder.Label.LinkedExpression=リンクされた式 :
HyperlinkBuilder.DrillThroughTargetToc=ターゲットレポートの目次エントリ
HyperlinkBuilder.DrillThroughSamewindow=同じウィンドウで開く
HyperlinkBuilder.DrillThroughNewWindow=新しいウィンドウを開く
HyperlinkBuilder.Label.Location=場所 :
HyperlinkBuilder.Label.Parameters=レポートパラメタ :
HyperlinkBuilder.Label.Report=レポート :
HyperlinkBuilder.Label.SelectType=ハイパーリンクの種類 :
HyperlinkBuilder.DrillThroughHtml=HTML
HyperlinkBuilder.Label.Target=ターゲット :
HyperlinkBuilder.Radio.Bookmark=内部ブックマーク
HyperlinkBuilder.DrillThroughPdf=PDF
HyperlinkBuilder.Radio.DrillThrough=ドリルスルー
HyperlinkBuilder.ReportDesignButton=レポートデザイン :
HyperlinkBuilder.ReportDocumentButton=レポート文書 :
HyperlinkBuilder.Radio.None=リンクなし
HyperlinkBuilder.Radio.Uri=URI
HyperlinkBuilder.BrowseForFile=ファイルの参照
HyperlinkBuilder.OpenExpression=式ビルダを開く
HyperlinkBuilder.FileNameError.Title=エラー
HyperlinkBuilder.FileNameError.Message=選択したファイルは無効です。

###########################################################
#HyperLinkPage properties

HyperLinkPage.Label.LnikTo=リンク先(&L) :
HyperLinkPage.Label.None=なし
HyperLinkPage.Menu.Save=ハイパーリンクの変更
HyperLinkPage.toolTipText.Button=ハイパーリンクのオプションを開く　

###########################################################
#I18nPage properties

I18nPage.text.Note=注 : ローカライズを設定するには、レポートを選択し、[プロパティエディタ] の [リソース] タブでリソースファイルの名前を指定してください。

###########################################################
#ImageBuilder properties

ImageBuilder.Button.Dynamic=動的なイメージ(&D)
ImageBuilder.Button.Import=イメージの追加(&A)...
ImageBuilder.Button.Insert=挿入(&S)
ImageBuilder.Button.Preview=プレビュー(&P)
ImageBuilder.Button.Remove=削除
ImageBuilder.ButtonBrowser=参照...
ImageBuilder.Chooser.Title=イメージファイルを開く
ImageBuilder.DialogTitle.Edit=イメージ項目の編集
ImageBuilder.DialogTitle.ImportFailed=インポ?[トエラ?[
ImageBuilder.DialogTitle.LoadingFailed=イメージの読み込みエラー
ImageBuilder.DialogTitle.New=イメージ項目の新規作成
ImageBuilder.ErrorMessage.FileLoaded=このファイルはすでに読み込まれています。
ImageBuilder.ErrorMessage.LoadingFailed=イメージを正しく読み込めません。
ImageBuilder.BrowserResourceDialog.Title=イメージファイルの参照
ImageBuilder.BrowserResourceDialog.Message=BIRT リソースパスのフォルダからイメージファイルを選択してください。
ImageBuilder.ErrorMessage.OutOfMemory=イメージが大きすぎるため、メモリに入りきりません。
ImageBuilder.FileDialog.FilterMessage=サポートされているイメージファイル
ImageBuilder.Label.Binding=バインド(&B)
ImageBuilder.Label.EmbededImage=埋め込まれたイメージ(&E)
ImageBuilder.Label.EnterExpr=動的なイメージの式を入力(&N) :
ImageBuilder.Label.EnterUri=URI を入力(&N) :
ImageBuilder.Label.Open=計算式ビルダ(&X)...
ImageBuilder.Label.SelectFrom=図の選択元 :
ImageBuilder.ResourceFileType=BIRT リソースフォルダ内のイメージファイル
ImageBuilder.Label.URI=URI(&U)
ImageBuilder.Label.EnterResourceFile=リソースファイルの入力(&N) :

###########################################################
#ImageEditPart properties

ImageEditPart.trans.editImage=イメージの変更

###########################################################
#ImagePageGenerator properties

ImagePageGenerator.List.AltText=代替テキスト
ImagePageGenerator.List.Bookmark=ブックマーク
ImagePageGenerator.List.Borders=罫線
ImagePageGenerator.List.General=全般
ImagePageGenerator.List.HyperLink=ハイパーリンク
ImagePageGenerator.List.Reference=参照
ImagePageGenerator.List.Section=ページ区切り
ImagePageGenerator.List.TOC=目次
ImagePageGenerator.List.Visibility=可視性

###########################################################
#ImportCSSStyleAction properties

ImportCSSStyleAction.text=CSS スタイルのインポート...

###########################################################
#ImportLibraryAction properties

ImportLibraryAction.Error.CannotBeEmpty=名前空間を空白にすることはできません。
ImportLibraryAction.Error.HasBeenUsed=この名前空間はすでに使用されています。
ImportLibraryAction.Error.HasDot=名前空間には '.' を使用できません。
ImportLibraryAction.Message.ImportSuccessfully=ライブラリ {0} をインポートしました。
ImportLibraryAction.Message=このライブラリをレポートデザイン内で使用しますか ?
ImportLibraryAction.Namespace=名前空間 :
ImportLibraryAction.Prefix=接頭辞 :
ImportLibraryAction.Title.ImportSuccessfully=インポート完了
ImportLibraryAction.Dialog.Titile=Use Library
ImportLibraryAction.Dialog.Message=Select a library to be included  in the report. 

###########################################################
#ImportLibraryDialog properties

ImportLibraryDialog.Title=ライブラリの使用

###########################################################
#ImportValueDialog properties

ImportValueDialog.Label.SelectColumn=列を選択(&C) :
ImportValueDialog.Label.SelectDataSet=データセットを選択(&D) :
ImportValueDialog.Label.SelectValue=追加する値を選択・入力(&S)
ImportValueDialog.Title=値のインポート

###########################################################
#IncludeDetailAction properties

IncludeDetailAction.actionMsg.includeDetail=詳細(&D)

###########################################################
#IncludeFooterAction properties

IncludeFooterAction.actionMsg.includeFooter=フッタ(&F)

###########################################################
#IncludeHeaderAction properties

IncludeHeaderAction.actionMsg.includeHeader=ヘッダ(&H)

###########################################################
#IncludeListDetailAction properties

IncludeListDetailAction.actionMsg.includeDetail=詳細を含める

###########################################################
#IncludeListFooterAction properties

IncludeListFooterAction.actionMsg.includeFooter=フッタを含める

###########################################################
#IncludeListHeaderAction properties

IncludeListHeaderAction.actionMsg.includeHeader=ヘッダを含める

###########################################################
#IncludeTableGroupFooterAction properties

IncludeTableGroupFooterAction.actionMsg.includeFooter=グループフッタ

###########################################################
#IncludeTableGroupHeaderAction properties

IncludeTableGroupHeaderAction.actionMsg.includeHeader=グループヘッダ

###########################################################
#InputParameterDailog properties

InputParameterDailog.dialog.title.required=必須パラメタ (値を指定してください)
InputParameterDailog.dialog.title=パラメタの入力
InputParameterDailog.parameter.noparameter=このレポートには、パラメタが関連付けられていません。
InputParameterDialog.ErrorMessage.InvalidFile=このレポートにはエラーがあります。
InputParameterDailog.parameter.null=NULL 値
InputParameterDialog.ErrorTitle.Error=エラー

###########################################################
#InsertAction properties

InsertAction.text=挿入

###########################################################
#InsertColumnAction properties

InsertColumnAction.actionMsg.insert=挿入

###########################################################
#InsertColumnLeftAction properties

InsertColumnLeftAction.actionMsg.columnToLeft=列 (左)(&L)

###########################################################
#InsertColumnRightAction properties

InsertColumnRightAction.actionMsg.columnToRight=列 (右)(&R)

###########################################################
#InsertExpressionMenuAction properties

InsertExpressionMenuAction.text.Expression=式...

###########################################################
#InsertGroupAction properties

InsertGroupAction.actionMsg.group=グループを挿入(&N)
InsertGroupAction.stackMsg.addGroup=グループの追加

###########################################################
#InsertGroupActionFactory properties

InsertGroupActionFactory.label.insertGroup=グループを挿入(&N)

###########################################################
#InsertInLayoutAction properties

InsertInLayoutAction.action.text=レイアウトに含める

###########################################################
#InsertListGroupAction properties

InsertListGroupAction.actionMsg.insertGroup=グループを挿入
InsertListGroupAction.stackMsg.insertListGroup=リストグループを挿入

###########################################################
#InsertPasteColumnAction properties

InsertPasteColumnAction.text=コピーした列の挿入(&S)

###########################################################
#InsertPositionGroupAction properties

InsertPositionGroupAction.Label.Above=上(&A)
InsertPositionGroupAction.Label.Below=下(&B)
InsertPositionGroupAction.Label.Into=挿入先

###########################################################
#InsertRowAboveAction properties

InsertRowAboveAction.actionMsg.rowAbove=上(&A)

###########################################################
#InsertRowAction properties

InsertRowAction.actionMsg.insert=挿入(&I)

###########################################################
#InsertRowBelowAction properties

InsertRowBelowAction.actionMsg.rowBelow=下(&B)

###########################################################
#IReportGraphicConstants properties

IReportGraphicConstants.ImageType.All=すべてのイメージファイル (*.bmp,*.JPG,*.JPEG,*.GIF,*.TIF,*.PNG,*.ICO)
IReportGraphicConstants.ImageType.Bmp=ビットマップファイル (*.bmp)
IReportGraphicConstants.ImageType.Gif=GIF ファイル (*.GIF)
IReportGraphicConstants.ImageType.Icon=アイコンファイル (*.ICO)
IReportGraphicConstants.ImageType.Jpg=JPEG ファイル (*.JPG,*.JPEG)
IReportGraphicConstants.ImageType.Png=PNG ファイル (*.PNG)
IReportGraphicConstants.ImageType.Tif=TIF ファイル (*.TIF)

###########################################################
#JSDocumentProvider properties

JSDocumentProvider.Content.Default=コンテンツの新規作成
JSDocumentProvider.document.newName=コンテンツの新規作成

###########################################################
#JSEditor properties

JSEditor.Button.Reset=メソッドのリセット
JSEditor.Display.DefaultText=//JS スクリプトエディタ \n
JSEditor.Display.NoExpression=この要素にはメソッドがありません。
JSEditor.Input.trial=試用
JSEditor.Text.NoText=テキストがありません。

###########################################################
#label properties

label.defaultValue=(デフォルト値)
label.input=入力
label.inputOutput=入力/出力
label.no=なし
label.output=出力
label.redo=やり直し
label.undo=元に戻す
label.yes=はい

###########################################################
#LabelEditPart properties

LabelEditPart.Figure.Default=ラベル

###########################################################
#LabelPageGenerator properties

LabelPageGenerator.List.Bookmark=ブックマーク
LabelPageGenerator.List.Borders=罫線
LabelPageGenerator.List.General=全般
LabelPageGenerator.List.HyperLink=ハイパーリンク
LabelPageGenerator.List.I18n=ローカライゼーション
LabelPageGenerator.List.Margin=余白
LabelPageGenerator.List.Padding=パディング
LabelPageGenerator.List.Section=ページ区切り
LabelPageGenerator.List.TOC=目次
LabelPageGenerator.List.Visibility=可視性

###########################################################
#LayoutEditor properties

LayoutEditor.ErrorMessage.OpenError=エディタを開く際にエラーが発生しました。
LayoutEditor.Page.Layout=標準
LayoutEditor.Page.MasterPage=マスタページ
LayoutEditor.Page.Source=XML ソース

###########################################################
#LayoutPageAction properties

LayoutPageAction.actionText.layout=レイアウト

###########################################################
#LibrariesNodeProvider properties

LibrariesNodeProvider.DisplayLabel.Libraries=ライブラリ

###########################################################
#LibraryExplorerView properties

LibraryExplorerView.defaultText.notAvailable=ライブラリがありません。

###########################################################
#LibraryExplorerProvider properties
LibraryExplorerProvider.FolderNotExist=定義されている BIRT リソースフォルダは存在しません。

###########################################################
#LibraryPage properties

LibraryPage.Label.Namespace=名前空間 :
LibraryPage.Label.Path=パス :

###########################################################
#LibraryProvider properties

LibraryProvider.openDefinedLibrary.error.dialog.message=定義済みライブラリを開けません
LibraryProvider.openDefinedLibrary.error.dialog.title=エラー

###########################################################
#ListBandControlFigure properties

ListBandControlFigure.tooltip.GroupFooter=リストグループ - フッタ
ListBandControlFigure.tooltip.GroupHeader=リストグループ - ヘッダ
ListBandControlFigure.tooltip.ListDetail=リスト - 詳細
ListBandControlFigure.tooltip.ListFooter=リスト - フッタ
ListBandControlFigure.tooltip.ListHeader=リスト - ヘッダ

###########################################################
#ListBandProvider properties

ListBandProvider.action.text=グループを挿入

###########################################################
#ListBandProxy properties

ListBandProxy.list.detail=詳細
ListBandProxy.list.footer=フッタ
ListBandProxy.list.groupFooter=GF
ListBandProxy.list.groupHeader=GH
ListBandProxy.list.header=ヘッダ

###########################################################
#ListContainProcess properties

ListContainProcess.action.New=新規作成...
ListContainProcess.action.NewRow=行の新規作成
ListContainProcess.action.NewSubSection=サブセクションの新規作成

###########################################################
#ListEditPart properties

ListEditPart.GUIDEHANDLE_TEXT = リスト

###########################################################
#ListFigure properties

ListFigure.BORDER_TEXT=リスト

###########################################################
#ListHandleAdapt properties

ListHandleAdapt.transLabel.insertGroup=グループの挿入

###########################################################
#ListPageGenerator properties

ListPageGenerator.List.Bookmark=ブックマーク
ListPageGenerator.List.Borders=罫線
ListPageGenerator.List.Font=フォント
ListPageGenerator.List.General=全般
ListPageGenerator.List.Section=ページ区切り
ListPageGenerator.List.TOC=目次
ListPageGenerator.List.Visibility=可視性
ListPageGenerator.TabItem.Binding=バインド
ListPageGenerator.TabItem.Filters=フィルタ
ListPageGenerator.TabItem.Groups=グループ
ListPageGenerator.TabItem.Highlights=ハイライト
ListPageGenerator.TabItem.map=マップ
ListPageGenerator.TabItem.Sorting=ソート

###########################################################
#MapPage properties

MapPage.label.add=追加(&A)...
MapPage.label.condition=条件
MapPage.label.delete=削除(&L)
MapPage.label.displayValue=表示値 :
MapPage.label.mapList=マップの一覧 :
MapPage.transName.addMapRule=マップ規則の追加
MapPage.transName.deleteMapRule=マップ規則の削除
MapPage.transName.editMapRule=マップ規則の編集
MapPage.transName.moveDownRule=マップ規則を下に移動
MapPage.transName.moveUpMapRule=マップ規則を上に移動
MapPage.toolTipText.moveUp=マップの規則を上に移動
MapPage.toolTipText.moveDown=マップの規則を下に移動

###########################################################
#MapPreferencePage properties

MapPreferencePage.displayname.Condition=条件
MapPreferencePage.displayname.DisplayValue=表示値
MapPreferencePage.displayname.Title=マップ
MapPreferencePage.text.Add=追加(&A)...
MapPreferencePage.text.Delete=削除(&L)
MapPreferencePage.text.Description=マップ規則 :
MapPreferencePage.text.Edit=編集(&D)...
MapPreferencePage.toolTipText.Up=マップの規則を上に移動
MapPreferencePage.toolTipText.Down=マップの規則を下に移動

###########################################################
#MapRuleBuilderDialog properties

MapRuleBuilder.DialogTitle.New=マップ規則の新規作成
MapRuleBuilder.DialogTitle.Edit=マップ規則の編集

MapRuleBuilderDialog.text.Between=値に挟まれる
MapRuleBuilderDialog.text.Condition=次の条件が True の場合(&I) : 
MapRuleBuilderDialog.text.Display=次の値を表示(&T) : 
MapRuleBuilderDialog.text.ET=次の値に等しい
MapRuleBuilderDialog.text.GE=次の値以上
MapRuleBuilderDialog.text.GT=次の値より大きい
MapRuleBuilderDialog.text.LE=次の値以下
MapRuleBuilderDialog.text.Like=次の値に類似
MapRuleBuilderDialog.text.LT=次の値より小さい
MapRuleBuilderDialog.text.NE=次の値に等しくない
MapRuleBuilderDialog.text.NotBetween=値に挟まれない
MapRuleBuilderDialog.text.NotNull=Not Null
MapRuleBuilderDialog.text.Null=Null
MapRuleBuilderDialog.text.Title=マップ規則の追加と編集

###########################################################
#SortkeyBuilder dialog properties
SortkeyBuilder.DialogTitle.New=ソートキーの新規作成
SortkeyBuilder.DialogTitle.Edit=ソートキーの編集
SortkeyBuilder.DialogTitle.Label.Prompt=ソートキーの入力 :
SortkeyBuilder.DialogTitle.Label.Key=キー :
SortkeyBuilder.DialogTitle.Label.Direction=方向 :
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=式ビルダを起動するには、ここをクリックしてしてください
SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=エラー

###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=フィルタの条件の新規作成
FilterConditionBuilder.DialogTitle.Edit=フィルタの条件の編集
FilterConditionBuilder.choice.ValueOfThisDataItem=このデータ項目の値
FilterConditionBuilder.tooltip.ExpBuilder=式ビルダを起動するには、ここをクリックしてしてください
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=フィルタの条件の入力 :

###########################################################
#MarignPropertyDescriptor properties

MarignPropertyDescriptor.error.message=入力した値が大きすぎます。
MarignPropertyDescriptor.error.title=入力した値が大きすぎます

###########################################################
#MasterPageAction properties

MasterPageAction.actionText.masterPage=マスタページ

###########################################################
#MasterPageGenerator properties

MasterPageGenerator.List.General=全般
MasterPageGenerator.List.Header&Footer=ヘッダ/フッタ
MasterPageGenerator.List.Margins=余白

###########################################################
#MasterPagePaletteFactory properties

MasterPagePaletteFactory.Autotext.TotalPageCount=合計ページ数
MasterPagePaletteFactory.Autotext.Author_Page_Date=作成者番号、ページ番号、日付
MasterPagePaletteFactory.Autotext.Confidential_Page=社外秘、ページ番号
MasterPagePaletteFactory.Autotext.CreatedBy=作成者
MasterPagePaletteFactory.Autotext.CreatedOn=作成日
MasterPagePaletteFactory.Autotext.Date=日付
MasterPagePaletteFactory.Autotext.Filename=ファイル名
MasterPagePaletteFactory.Autotext.Label=定型句
MasterPagePaletteFactory.Autotext.LastPrinted=最終印刷日
MasterPagePaletteFactory.Autotext.Page=ページ
MasterPagePaletteFactory.Autotext.PageXofY=n/m ページ
MasterPagePaletteFactory.AutotextTooltip.TotalPageCount=合計ページ数のレポート項目
MasterPagePaletteFactory.AutotextTooltip.AuthorPageDate=作成者番号、レポート項目の日付
MasterPagePaletteFactory.AutotextTooltip.ConfidentialPage=社外秘のレポート項目
MasterPagePaletteFactory.AutotextTooltip.CreatedBy=作成者のレポート項目
MasterPagePaletteFactory.AutotextTooltip.CreatedOn=作成日のレポート項目
MasterPagePaletteFactory.AutotextTooltip.Date=日付のレポート項目
MasterPagePaletteFactory.AutoTextTooltip.Filename=ファイル名のレポート項目
MasterPagePaletteFactory.AutotextTooltip.LastPrinted=最後に印刷したレポート項目
MasterPagePaletteFactory.AutotextTooltip.Page=ページのレポート項目
MasterPagePaletteFactory.AutotextTooltip.PageXofY=レポート項目の n/m ページ
MasterPagePaletteFactory.elementLabel.authorPageDate=作成者番号、ページ番号、日付
MasterPagePaletteFactory.elementLabel.confidentialPage=社外秘、ページ
MasterPagePaletteFactory.elementLabel.createdBy=作成者
MasterPagePaletteFactory.elementLabel.createdOn=作成日
MasterPagePaletteFactory.elementLabel.date=日付
MasterPagePaletteFactory.elementLabel.fileName=ファイル名
MasterPagePaletteFactory.elementLabel.lastPrinted=最終印刷日
MasterPagePaletteFactory.elementLabel.page=ページ
MasterPagePaletteFactory.elementLabel.pageOf=n/m ページ
MasterPagePaletteFactory.paletteDrawerName.autoText=定型句
MasterPagePaletteFactory.ToolTip.Grid=グリッドのレポート項目
MasterPagePaletteFactory.ToolTip.Text=テキストのレポート項目

###########################################################
#MasterPageProcess properties

MasterPageProcess.action.Edit=編集
MasterPageProcess.action.New=新規作成
MasterPageProcess.text.CannotDelete=デザインには、マスタページが 1 つしか含まれていないため、削除できません。
MasterPageProcess.text.Display=[ページ設定] ダイアログボックスを表示します。
MasterPageProcess.text.DisplayName=マスタページ

###########################################################
#MergeAction properties

MergeAction.actionMsg.merge=セルを結合する(&M)

###########################################################
#ModulePage properties

ModulePage.ErrorMessage.Duplicate=この名前はすでに使われています。
ModulePage.ErrorMessage.WrongExtensionName=ファイル名の拡張子は ".properties" にしてください。
ModulePage.ErrorMessage.InfoExtensionName=ファイル名の拡張子は ".properties" にしてください。
ModulePage.text.Add=追加(&A)...
ModulePage.text.ExistingFile=既存のリソースファイル :
ModulePage.title.AddNewFile=新しいリソースファイルの追加
ModulePage.Resourcefile.Dialog.Title=リソースファイルの参照
ModulePage.Resourcefile.Dialog.Message=リソースファイルを選択するか、フォルダを選択して新しいファイル名を入力し、ファイルを作成してください。
ModulePage.text.Path=パス :

###########################################################
#MultiPageEditorContributor properties

MultiPageEditorContributor.actionText.sampleAction=サンプルアクション
MultiPageEditorContributor.actionToolTip.sampleActionToolTip=サンプルアクションのツールヒント
MultiPageEditorContributor.actionToolTipText.sampleActionToolTip=サンプルアクションのツールヒント
MultiPageEditorContributor.dialogMsg.sampleActionExecuted=サンプルアクションを実行しました。
MultiPageEditorContributor.dialogTitle.infoObjectDesignerPlugIn=Infoobjectdesigner プラグイン
MultiPageEditorContributor.menuText.editorMenu=エディタメニュー(&M)

###########################################################
#NewLibraryWizard properties

NewLibraryWizard.choicePageTitle.report=ライブラリ
NewLibraryWizard.displayName.NewReportFileExtension=.rptlibrary
NewLibraryWizard.displayName.NewReportFileNamePrefix=new_library
NewLibraryWizard.error.NoProject=ワークスペースには開いているプロジェクトがありません。[ファイル]→[新規作成]→[プロジェクト] を選択して新しいプロジェクトを作成するか、既存のプロジェクトを開いてください。
NewLibraryWizard.pageDescription.createNewReport=新しいライブラリを作成します。
NewLibraryWizard.taskName.openFileForEdit=ファイルを編集モードで開く...
NewLibraryWizard.text.ConfirmSwitchPerspective=パースペクティブの切り替え確認
NewLibraryWizard.text.Container=コンテナ "
NewLibraryWizard.text.CreateReport=新しいライブラリを作成します。
NewLibraryWizard.text.Creating=作成 
NewLibraryWizard.text.DoesNotExist=" は存在しません。
NewLibraryWizard.text.OpenFileForEditing=ファイルを編集モードで開く...
NewLibraryWizard.text.SwitchPerspective=この種類のファイルは {0} パースペクティブに関連付けられています。今すぐこのパースペクティブに切り替えますか ?
NewLibraryWizard.title.Choose=ライブラリの作成方法の選択
NewLibraryWizard.title.Error=エラー
NewLibraryWizard.title.New=新規ライブラリ
NewLibraryWizard.title.Report=新規ライブラリ
NewLibraryWizard.title.ReportWizard=ライブラリウィザード
NewLibraryWizard.title.Template=TemplateChoicePage
NewLibraryWizard.title.WizardPage=WizardPage
NewLibraryWizard.widowTitle.new=新規
NewLibraryWizard.wizardPageTitle.report=ライブラリ

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=ファイルシステムでは、大文字と小文字が区別されないため、既存のプロジェクトと同じ名前 "{0}" は使用できません。
NewReportProjectWizard.description=新しいレポートプロジェクトを作成します。
NewReportProjectWizard.errorMessage=新しいレポートプロジェクトを作成中にエラーが発生しました。
NewReportProjectWizard.errorOpeningWindow=ウィンドウを開けませんでした。
NewReportProjectWizard.internalError=内部エラー : {0}
NewReportProjectWizard.javaProject=Java プロジェクトの作成
NewReportProjectWizard.perspSwitchMessage=この種類のプロジェクトは {0} パースペクティブに関連付けられています。今すぐこのパースペクティブに切り替えますか ?
NewReportProjectWizard.perspSwitchTitle=パースペクティブの切り替え確認
NewReportProjectWizard.projectSetting=プロジェクトの設定
NewReportProjectWizard.src=src
NewReportProjectWizard.title=レポートプロジェクト
NewReportProjectWizard.windowTitle=新規レポートプロジェクト

###########################################################
#NewReportWizard properties

NewReportWizard.choicePageTitle.report=レポート
NewReportWizard.displayName.NewReportFileExtension=.rptdesign
NewReportWizard.displayName.NewReportFileNamePrefix=new_report
NewReportWizard.error.NoProject=ワークスペースには開いているプロジェクトがありません。[ファイル]→[新規作成]→[プロジェクト] を選択して新しいプロジェクトを作成するか、既存のプロジェクトを開いてください。
NewReportWizard.pageDescription.createNewReport=レポートの新規作成
NewReportWizard.pageDescription.selectReportTemplate=コピーするレポートを選択します。
NewReportWizard.taskName.openFileForEdit=ファイルを編集モードで開く...
NewReportWizard.text.ConfirmSwitchPerspective=パースペクティブの切り替え確認
NewReportWizard.text.Container=コンテナ "
NewReportWizard.text.CreateReport=新しいレポートを作成します。
NewReportWizard.text.Creating=作成 
NewReportWizard.text.DoesNotExist=" は存在しません。
NewReportWizard.text.OpenFileForEditing=ファイルを編集モードで開く...
NewReportWizard.text.SelectTemplate=コピーするレポートを選択します。
NewReportWizard.text.SwitchPerspective=この種類のファイルは {0} パースペクティブに関連付けられています。今すぐこのパースペクティブに切り替えますか ?
NewReportWizard.title.Choose=レポートの作成方法の選択
NewReportWizard.title.Error=エラー
NewReportWizard.title.New=新規レポート
NewReportWizard.title.Report=新規レポート
NewReportWizard.title.ReportWizard=レポートウィザード
NewReportWizard.title.Template=TemplateChoicePage
NewReportWizard.title.WizardPage=WizardPage
NewReportWizard.widowTitle.new=新規作成

###########################################################
#NewResourceFileDialog properties

NewResourceFileDialog.label.NewFile=新規ファイル名 :
NewResourceFileDialog.ErrorMessage=ファイル名の拡張子は .properties にしてください。
NewResourceFileDialog.ErrorMessageInvalid=ファイル名が無効です。

###########################################################
#ProjectFileDialog properties

ProjectFileDialog.ErrorMessage=File must be a file , not a directory.
ProjectFileDialog.Title=Select Project File
ProjectFileDialog.Message=Select a file in the current project.

###########################################################
#NewSectionDialog properties

NewSectionDialog.displayname.Container=コンテナ
NewSectionDialog.displayname.Data=データ
NewSectionDialog.displayname.Grid=グリッド
NewSectionDialog.displayname.Image=イメージ
NewSectionDialog.displayname.Label=ラベル
NewSectionDialog.displayname.Line=線
NewSectionDialog.displayname.List=リスト
NewSectionDialog.displayname.Rectangle=四角形
NewSectionDialog.displayname.Table=テーブル
NewSectionDialog.displayname.Text=テキスト
NewSectionDialog.text.Prefix=使用可能なセクション :
NewSectionDialog.title.insertElement=要素の挿入
NewSectionDialog.Title=要素の挿入

###########################################################
#NewTemplateWizard properties

NewTemplateWizard.displayName.NewReportFileNamePrefix=new_template
NewTemplateWizard.pageDescription.createNewTemplate=レポートテンプレートを新しく作成します。
NewTemplateWizard.text.CreateReport=テンプレートの新規作成
NewTemplateWizard.text.Creating=作成中
NewTemplateWizard.text.OpenFileForEditing=テンプレートファイルを編集モードで開く...
NewTemplateWizard.title.New=新規テンプレート
NewTemplateWizard.title.Report=新規レポート
NewTemplateWizard.title.Template=新規テンプレート
NewTemplateWizard.title.WizardPage=WizardPage

###########################################################
#NoneAction properties

NoneAction.text=なし

###########################################################
#OutputColumnDefnPage properties

OutputColumnDefnPage.description=フェッチスクリプトによって作成される出力列の定義を入力 : 
OutputColumnDefnPage.OutputColumns.Tooltip=データ行内の列の表示と定義 

###########################################################
#OutputColumnPage properties

OutputColumnPage.OutputColumns.Tooltip=データ行内の列の表示と定義 
OutputColumnPage.toolTipText.Edit=出力列の編集
OutputColumnPage.title.OutputColumnInputDialog=出力列

###########################################################
#OutputColumnsPage properties

OutputColumnsPage.description=出力列の定義 :

###########################################################
#PageBreakPreferencePage properties

PageBreakPreferencePage.displayname.Title=ページ区切り

###########################################################
#PageSetAction properties

PageSetAction.text.code=スクリプト(&S)
PageSetAction.Text.EditCode=スクリプトの編集(&S)...
PageSetAction.text.layout=レイアウト(&L)
PageSetAction.text.master=マスタ(&M)
PageSetAction.text.normal=標準(&N)
PageSetAction.text.preview=プレビュー(&P)

###########################################################
#PageSetupOutlineProcess properties

PageSetupOutlineProcess.action.Edit=ページ設定の編集
PageSetupOutlineProcess.action.New=マスタページの新規作成
PageSetupOutlineProcess.text.Display=[ページ設定] ダイアログボックスを表示します。
PageSetupOutlineProcess.text.Switch=ページマスタエディタに切り替えます。

###########################################################
#ParameterDialog properties

ParameterDialog.Boolean.False=False
ParameterDialog.Boolean.True=True
ParameterDialog.Button.ChangeFormat=変更(&G)...
ParameterDialog.Button.CreateDataSet=新規作成(&W)...
ParameterDialog.Button.ImportValue=値のインポート(&U)...
ParameterDialog.Button.RemoveDefault=デフォルトの削除
ParameterDialog.Button.SetDefault=デフォルトに設定(&A)
ParameterDialog.CheckBox.AllowBlank=空白値を許可する(&B)
ParameterDialog.CheckBox.AllowNull=Null 値を許可する(&V)
ParameterDialog.CheckBox.DoNotEchoInput=入力値を繰り返さない(&O)
ParameterDialog.CheckBox.Hidden=非表示(&D)
ParameterDialog.CheckBox.Sort=確認時にアルファベット順にソートする(&R)
ParameterDialog.Choice.NoDefault=デフォルト値がありません
ParameterDialog.Column.Default=デフォルト
ParameterDialog.Column.DisplayText=表示テキスト
ParameterDialog.Column.Value=値
ParameterDialog.DisplayLabel.Combo=コンボボックス
ParameterDialog.DisplayLabel.List=リストボックス
ParameterDialog.ErrorMessage.CanootBeBlank=値は空白にできません。
ParameterDialog.ErrorMessage.CanootBeNull=値は null にできません。
ParameterDialog.ErrorMessage.DuplicatedLabel=この表示テキストはすでに存在します。
ParameterDialog.ErrorMessage.DuplicatedName=この名前はすでに使われています。
ParameterDialog.ErrorMessage.DuplicatedValue=この値はすでに存在します。
ParameterDialog.ErrorMessage.EmptyName=名前が指定されていません。
ParameterDialog.ErrorMessage.InvalidListLimit=制限値は、0 ～ {0} の範囲で指定してください。
ParameterDialog.ErrorMessage.MismatchDataType=この値はデータ型に一致しません。
ParameterDialog.ErrorMessage.NoAvailableColumn=使用できる列がありません。
ParameterDialog.ErrorMessage.NoDefaultValue=デフォルト値を設定してください。
ParameterDialog.ErrorTitle.InvalidListLimit=一覧の制限が無効です。
ParameterDialog.Flag.Default=デフォルト
ParameterDialog.Group.MoreOption=次の形式で表示
ParameterDialog.Group.Properties=プロパティ
ParameterDialog.Label.DataType=データ型(&D) :
ParameterDialog.SelectionDialog.Edit=選択項目の編集
ParameterDialog.Label.DefaultValue=デフォルト値(&F) :
ParameterDialog.Label.DisplayPrompt=プロンプトの表示 :
ParameterDialog.Label.DisplayType=表示の種類(&T) :
ParameterDialog.Label.Format=書式設定(&M) :
ParameterDialog.Label.HelpText=ヘルプテキスト(&H) :
ParameterDialog.Label.ListOfValue=値リスト :
ParameterDialog.Label.Name=名前(&N) :
ParameterDialog.Label.None=<なし>
ParameterDialog.Label.Null=Null
ParameterDialog.Label.Preview=書式付きプレビュー
ParameterDialog.Label.PromptText=プロンプトテキスト(&P) :
ParameterDialog.Label.SelectDataSet=データセット(&A) :
ParameterDialog.SelectionDialog.New=選択項目の新規作成
ParameterDialog.Label.SelectDisplayText=表示テキストを選択(&X) :
ParameterDialog.Label.SelectValueColumn=値列を選択(&U) :
ParameterDialog.Label.Value=選択した値 :
ParameterDialog.Label.values=個の値
ParameterDialog.Label.Sample=サンプル
ParameterDialog.Label.Listlimit=一覧の制限(&I) :
ParameterDialog.Radio.Dynamic=動的(&Y)
ParameterDialog.Radio.Static=静的(&S)
ParameterDialog.toolTipText.OpenExprButton=Open Expression Builder

###########################################################
#ParameterDropListener properties

ParameterDropListener.Command.Copy=要素のコピー
ParameterDropListener.Command.Move=要素の移動

###########################################################
#ParameterGroupDialog properties

ParameterGroupDialog.Page.Title=全般
ParameterGroupDialog.pageTitle.general=全般

###########################################################
#ParameterGroupGeneralPage properties

ParameterGroupGeneralPage.Label.DisplayName=表示名(&D) :
ParameterGroupGeneralPage.Label.Name=名前(&N) :

###########################################################
#ParameterGroupNodeProvider properties

ParameterGroupNodeProvider.Action.GroupNew=パラメタグループの新規作成
ParameterGroupNodeProvider.Action.ParameterEdit=編集
ParameterGroupNodeProvider.Action.ParameterNew=パラメタの新規作成
ParameterGroupNodeProvider.Dialogue.ParameterEdit=パラメタグループの編集
ParameterGroupNodeProvider.Dialogue.ParameterNew=パラメタの新規作成
ParameterGroupNodeProvider.Node.Group=パラメタグループ

###########################################################
#ParameterGroupProcess properties

ParameterGroupProcess.action.Delete=パラメタグループの削除
ParameterGroupProcess.action.Edit=パラメタグループの編集
ParameterGroupProcess.action.New=パラメタの新規作成
ParameterGroupProcess.text.DisplayName=パラメタグループ
ParameterGroupProcess.text.Show=このデータソースのエディタページを表示します。  

###########################################################
#ParameterNodeProvider properties

ParameterNodeProvider.dial.title.editCascading=カスケードパラメタの編集
ParameterNodeProvider.dial.title.editScalar=パラメタの編集
ParameterNodeProvider.dial.title.newCascading=カスケードパラメタの新規作成
ParameterNodeProvider.menu.text.edit=編集
ParameterNodeProvider.menu.text.new=パラメタの新規作成

###########################################################
#ParameterProcess properties

ParameterProcess.action.Delete=パラメタの削除
ParameterProcess.action.Edit=パラメタの編集
ParameterProcess.text.DisplayName=パラメタ
ParameterProcess.text.Show=このデータソースのエディタページを表示します。  

###########################################################
#parameters properties

parameters.datatypes.boolean=論理
parameters.datatypes.dateTime=日時
parameters.datatypes.decimal=10進
parameters.datatypes.float=浮動
parameters.datatypes.string=文字列
parameters.menuItem.refresh=更新

###########################################################
#ParametersNodeProvider properties

ParametersNodeProvider.dialogue.title.group=パラメタグループの新規作成
ParametersNodeProvider.dialogue.title.parameter=パラメタの新規作成
ParametersNodeProvider.menu.text.cascadingParameter=カスケードパラメタの新規作成
ParametersNodeProvider.menu.text.group=パラメタグループの新規作成
ParametersNodeProvider.menu.text.parameter=パラメタの新規作成

###########################################################
#ParametersOutlineProcess properties

ParametersOutlineProcess.action.Edit=編集
ParametersOutlineProcess.action.New=パラメタの新規作成
ParametersOutlineProcess.action.NewGroup=グループの新規作成
ParametersOutlineProcess.text.Open=パラメタエディタを開きます。
ParametersOutlineProcess.text.Show=このデータセットのエディタページを表示します。

###########################################################
#PasteAction properties

PasteAction.text=貼り付け(&P)

###########################################################
#PlaceHolderEditPart properties

PlaceHolderEditPart.Trans.TransferToElement=レポート項目への転送

###########################################################
#PreviewAction properties

PreviewAction.Text=プレビュー

###########################################################
#PreviewEditor properties

PreviewEditor.parameter.tooltip=レポートパラメタを表示します。

###########################################################
#PreviewPageAction properties

PreviewPageAction.actionText.preview=プレビュー

###########################################################
#PropertiesAction properties

PropertiesAction.Text=プロパティ

###########################################################
#PropertyHandleTableViewer properties

PropertyHandleTableViewer.Button.New=新規(&N)...
PropertyHandleTableViewer.Button.Edit=編集(&E)...
PropertyHandleTableViewer.Button.Remove=削除(&R)
PropertyHandleTableViewer.Button.Up=上へ(&U)
PropertyHandleTableViewer.Button.Down=下へ(&D)
PropertyHandleTableViewer.Menu.Remove=削除
PropertyHandleTableViewer.Menu.Up=上へ
PropertyHandleTableViewer.Menu.Down=下へ
PropertyHandleTableViewer.Menu.RemoveAll=すべて削除

###########################################################
#PropertyHandleInputDialog properties

PropertyHandleInputDialog.Action.New=新規
PropertyHandleInputDialog.Action.Edit=編集
PropertyHandleInputDialog.messages.error.blankProperty={0} は空白にできません。

###########################################################
#PublishTemplateAction properties

PublishTemplateAction.wizard.page.browse.cheatsheet.title=ガイドファイルの選択
PublishTemplateAction.wizard.page.browse.title=イメージファイルの選択
PublishTemplateAction.wizard.page.btn.browse=参照(&W)...
PublishTemplateAction.wizard.page.cheatsheetError=ガイドファイル ''{0}'' は存在しません。
PublishTemplateAction.wizard.page.desc=テンプレートフォルダに公開します。
PublishTemplateAction.wizard.page.imageError=イメージファイル ''{0}'' は存在しません。
PublishTemplateAction.wizard.page.label.cheatsheet=ガイドファイル :
PublishTemplateAction.wizard.page.label.description=説明(&D) :
PublishTemplateAction.wizard.page.label.displayName=表示名(&M) :
PublishTemplateAction.wizard.page.label.image=テンプレートのイメージ(&I) :
PublishTemplateAction.wizard.page.title=テンプレートフォルダへ公開
PublishTemplateAction.wizard.title=テンプレートフォルダへ公開
PublishTemplateAction.wizard.errorTitle=エラー
PublishTemplateAction.wizard.message=テンプレートがすでに存在するディレクトリには、テンプレートを公開できません。公開するには、別のディレクトリを選択してください。
PublishTemplateAction.wizard.notvalidfolder=設定に無効なテンプレートフォルダが定義されています。
PublishTemplateAction.wizard.page.nameInfo=表示名を指定してください。
PublishTemplateAction.wizard.message.SourceFileNotExist=ソースファイルが存在しません。
PublishTemplateAction.wizard.message.PreviewImageNotExist=プレビュー用のイメージファイルは存在しません。
PublishTemplateAction.wizard.message.PreviewImageNotValid=プレビュー用のイメージファイルは、有効なイメージではありません。

###########################################################
#PublishLibraryAction properties
PublishLibraryAction.wizard.errorTitle=エラー
PublishLibraryAction.wizard.message=ライブラリがすでに存在するディレクトリには、ライブラリを公開できません。公開するには、別のディレクトリを選択してください。
PublishLibraryAction.wizard.message.SourceFileNotExist=ソースファイルが存在しません。
PublishLibraryAction.wizard.notvalidfolder=定義されているライブラリフォルダは無効です。

###########################################################
#RedoAction properties

RedoAction.Tooltip={0} をやり直し

###########################################################
#ExportReportWizard
ExportToLibraryAction.wizard.windowTitle=エクスポート
ExportToLibraryAction.wizard.page.title=ファイルをライブラリにエクスポート
ExportToLibraryAction.wizard.page.desc=レポートデザインをライブラリにエクスポート
ExportToLibraryAction.wizard.page.label.filename=ファイル名(&N) :
ExportToLibraryAction.wizard.page.label.folder=フォルダ(&F) :
ExportToLibraryAction.wizard.page.button.browser=参照(&B)...
ExportToLibraryAction.wizard.page.dirdialog.message=ファイルのコンテンツディレクトリを選択してください。
ExportToLibraryAction.wizard.page.nameempty=ファイル名を指定してください。
ExportToLibraryAction.wizard.page.folderempty=フォルダを指定してください。
ExportToLibraryAction.wizard.page.foldererror=指定されたフォルダが存在しません。

###########################################################
#PublishLibraryToResourceFolderAction
PublishLibraryToResourceFolderAction.Action.Text=リソースフォルダに公開...

###########################################################
#PublishTemplateViewAction
DefaultNodeProvider.template.suffix=.rpttemplate
PublishTemplateViewAction.action.displaytext=テンプレートフォルダへ公開...

###########################################################
#RefreshModuleHandleAction
RefreshModuleHandleAction.Action.Text=ライブラリの更新

###########################################################
#ReferencePage properties

ReferencePage.Button.Edit=編集(&D)...
ReferencePage.Label.Source=ソース(&S) :

###########################################################
#RefreshAction properties

RefreshAction.text=更新

###########################################################
#RefreshLibExplorerAction properties

RefreshLibExplorerAction.Text=更新

###########################################################
#RemoveLibraryAction properties

RemoveLibraryAction.Text=ライブラリの削除

###########################################################
#RenameAction properties

RenameAction.text=名前の変更

###########################################################
#RenameDialog properties

RenameDialog.action.Cancel=キャンセル
RenameDialog.action.Ok=\\ \\ OK  
RenameDialog.text.NewName=新しい名前 :
RenameDialog.text.Rename=名前の変更 
RenameDialog.text.ToolTip=名前を空白にすることはできません。

###########################################################
#RenameInlineTool properties

RenameInlineTool.DialogTitle.RenameFailed=名前を変更できません。
RenameInlineTool.TransLabel.Rename=名前の変更

###########################################################
#RenameInputDialog properties

RenameInputDialog.DialogTitle=名前の変更
RenameInputDialog.DialogMessage=新しい名前を入力してください。

###########################################################
#report properties

report.designer.ui.preferences.buttonadd=追加(&D)...
report.designer.ui.preferences.buttonremove=削除(&R)
report.designer.ui.preferences.buttonremoveall=すべて削除(&A)
report.designer.ui.preferences.dialogtitle=ライブラリを開く
report.designer.ui.preferences.errormessage=ライブラリはすでに存在します。
report.designer.ui.preferences.errortitle=エラー
report.designer.ui.preferences.extensions=*.rptlibrary
report.designer.ui.preferences.labeltitle=ライブラリの追加と削除
report.designer.ui.preferences.library.export.overwrite.always=上書きする(&W)
report.designer.ui.preferences.library.export.overwrite.never=上書きしない(&N)
report.designer.ui.preferences.library.export.overwrite.prompt=確認メッセージを表示する(&P)
report.designer.ui.preferences.library.export.title=デザイン要素をライブラリにエクスポートするときに、既存の要素を上書きしますか ?
report.designer.ui.preferences.template.openDialogTitle=テンプレート用のフォルダを選択してください。
report.designer.ui.preferences.template.select=選択(&S)...
report.designer.ui.preferences.template.templatedir=テンプレート
report.designer.ui.preferences.template.templatefolder= テンプレートフォルダ(&T)
report.designer.ui.preferences.template.title=テンプレートフォルダを選択してください。
org.eclipse.birt.report.designer.ui.preference.commenttemplates.enablecomment=レポートデザインの作成時にコメントを生成する
org.eclipse.birt.report.designer.ui.preference.commenttemplates.defaultcomment=Copyright (c) 2006 <<ここに会社名を入力>>

###########################################################
#Resource Preference page properties
ResourecePreferencePage.title=ライブラリエクスプローラで使用するデフォルトのリソースフォルダを選択してください。
ResourecePreferencePage.folder=リソースフォルダ(&R)
ResourecePreferencePage.select=選択(&S)...
ResourecePreferencePage.openDialogTitle=フォルダの参照
ResourecePreferencePage.openDialogMessage=デフォルトのリソースフォルダを選択してください :

###########################################################
#ReportAdvancedLauncherTab properties

ReportAdvancedLauncherTab.DefaultsButtonText=デフォルトに戻す(&R)
ReportAdvancedLauncherTab.DeselectButtonText=すべて選択解除(&D)
ReportAdvancedLauncherTab.Name=レポートプロジェクト
ReportAdvancedLauncherTab.SelectAllButtonText=すべて選択(&S)
ReportAdvancedLauncherTab.UseListRadioText=起動するプロジェクトを一覧から選択する
ReportAdvancedLauncherTab.VisibleLabelText=選択可能なプロジェクト(&A)
ReportAdvancedLauncherTab.WorkspaceReportProjects=ワークスースのレポートプロジェクト

###########################################################
#ReportClasspathLaucnTab properties

ReportClasspathLaucnTab.DefaultButtonText=デフォルトに戻す(&R)
ReportClasspathLaucnTab.DeselectButtonText=すべて選択解除(&D)
ReportClasspathLaucnTab.Name=Java プロジェクト
ReportClasspathLaucnTab.SelectAllButtonText=すべて選択(&S)
ReportClasspathLaucnTab.UseListRadioText=起動するプロジェクトを一覧から選択する (選択したプロジェクトのクラス出力フォルダがクラスパスに追加されます)。
ReportClasspathLaucnTab.VisibleLabelText=選択可能なプロジェクト(&A)
ReportClasspathLaucnTab.WorkspaceJavaProjects=ワークスペースの Java プロジェクト

###########################################################
#ReportCreationTool properties

ReportCreationTool.ModelTrans.CreateElement=要素の作成

###########################################################
#ReportEditor properties

ReportEditor.Button.Close=閉じる
ReportEditor.Button.Save=保存
ReportEditor.Dlg.Confirm=このファイルは、ファイルシステムから削除されました。変更を保存しますか ? または、変更を保存せずにエディタを閉じますか ?
ReportEditor.Dlg.Save=保存...
ReportEditor.error.activated.outofsync.message=このファイルは、ファイルシステムで変更されました。変更を読み込みますか ?
ReportEditor.error.activated.outofsync.title=ファイルの変更
ReportEditor.Error.Open=開けません。
ReportEditor.Error.OpenEditor=ファイルを開けません。
ReportEditor.Page.Code=スクリプト
ReportEditor.Page.Layout=レイアウト
ReportEditor.Page.MasterPage=マスタページ
ReportEditor.Page.Preview=プレビュー
ReportEditor.Page.PreviewSaveMessage=レポートファイルは変更されています。プレビューする前に保存しますか ?
ReportEditor.Page.PreviewSaveTitle=保存
ReportEditor.Page.PreviewSaveToggle=常にプレビュー前に保存する

###########################################################
#ReportLaunchConfigurationDelegate properties

ReportLaunchConfigurationDelegate.badFeatureSetup=機能の設定が正しくありません
ReportLaunchConfigurationDelegate.noStartup=スタートアップがありません

###########################################################
#ReportPage properties
ReportPage.text.Add=追加(&A)...
ReportPage.text.Browse=参照(&B)...
ReportPage.title.Location=場所 :
ReportPage.title.setPrewImg=イメージファイルの選択
ReportPage.text.Resource.Add=追加(&D)...
ReportPage.text.Thumbnail=サムネール(&H)...

###########################################################
#ReportPageGenerator properties

ReportPageGenerator.List.Comments=コメント
ReportPageGenerator.List.Description=説明
ReportPageGenerator.List.EventHandler=イベントハンドラ
ReportPageGenerator.List.General=全般
ReportPageGenerator.List.Measurement=計測
ReportPageGenerator.List.NamedExpressions=名前付き式
ReportPageGenerator.List.UserProperties=ユーザのプロパティ
ReportPageGenerator.List.Resources=リソース
ReportPageGenerator.List.Resources.JarFile=JAR ファイル :

#OdaDataSourceGenerator properties
DataSourcePageGenerator.List.General=全般

#OdaDataSetGenerator properties
DataSetPageGenerator.List.General=全般
DataSetPageGenerator.DataSourceName=データソース(&D)

#ScalarParameterPageGenerator properties
ScalarParameterPageGenerator.List.General=全般
ScalarParameterPageGenerator.List.I18n=ローカライゼーション

#TemplateReportItemPageGenerator properties
TemplateReportItemPageGenerator.List.General=全般
TemplateReportItemPage.description.Label.Instructions=手順(&I) :
TemplateReportItemPageGenerator.List.I18n=ローカライゼーション
TemplateReportItemPageGenerator.List.TextKey=テキストキー :

###########################################################
#ReportPropertySheetPage properties

ReportPropertySheetPage.Column.Title.Property=プロパティ
ReportPropertySheetPage.Column.Title.Value=値
ReportPropertySheetPage.Root.Default.Title=情報

###########################################################
#ReportTemplateTransferDropTargetListener properties

ReportTemplateTransferDropTargetListener.ModelTrans.CreateElement=要素の作成
ReportTemplateTransferDropTargetListener.transLabel.createElement=要素の作成

###########################################################
#ResourceEditDialog properties

ResourceEditDialog.message.AddNote=[今すぐ追加] をクリックすると、現在のリソースファイルにキーが保存されます。
ResourceEditDialog.message.ResourceFile=リソースファイル : 
ResourceEditDialog.text.Add=追加
ResourceEditDialog.text.AddWarningMsg=キーは空白にできません。
ResourceEditDialog.text.AddWarningTitle=Warning
ResourceEditDialog.text.Delete=削除
ResourceEditDialog.text.Key=キー
ResourceEditDialog.text.QuickAdd=今すぐ追加
ResourceEditDialog.text.Value=値

###########################################################
#ResourceKeyDescriptor properties

ResourceKeyDescriptor.text.Reset=リセット
ResourceKeyDescriptor.title.SelectKey=キーの選択

###########################################################
#RevertToReportItemAction properties

RevertToReportItemAction.text=レポート項目に戻す(&R)

###########################################################
#RevertToTemplateAction properties

RevertToTemplateAction.text=テンプレート項目に戻す(&V)

###########################################################
#RowHandle properties

RowHandle.tooltip.GridRow=グリッド - 行
RowHandle.tooltip.GroupFooter=テーブルグループ - グループフッタ
RowHandle.tooltip.GroupHeader=テーブルグループ - グループヘッダ
RowHandle.tooltip.TableDetail=テーブル - 詳細
RowHandle.tooltip.TableFooter=テーブル - フッタ
RowHandle.tooltip.TableHeader=テーブル - ヘッダ(&H)

###########################################################
#RowHandleAdapter properties

RowHandleAdapter.table.detail=詳細行
RowHandleAdapter.table.footer=フッタ行
RowHandleAdapter.table.groupFooter=グループフッタ行
RowHandleAdapter.table.groupHeader=グループヘッダ行
RowHandleAdapter.table.header=ヘッダ行

###########################################################
#RowPageGenerator properties

RowPageGenerator.List.Bookmark=ブックマーク
RowPageGenerator.List.Borders=罫線
RowPageGenerator.List.Section=Page Break
RowPageGenerator.List.CellPadding=セルのパディング
RowPageGenerator.List.Font=フォント
RowPageGenerator.List.General=全般
RowPageGenerator.TabItem.Highlights=ハイライト
RowPageGenerator.TabItem.map=マップ
RowPageGenerator.List.Visibility=表示/非表示

###########################################################
#RowProvider properties

RowProvider.action.text.above=上に行を挿入(&A)
RowProvider.action.text.below=下に行を挿入(&B)

###########################################################
#SaveAsDialog properties

SaveAsDialog.message=ファイルを別の場所に保存します。
SaveAsDialog.overwriteQuestion=The file ''{0}'' already exists. Do you want to replace the existing file?
SaveAsDialog.Question=質問
SaveAsDialog.text=名前を付けて保存
SaveAsDialog.title=名前を付けて保存

###########################################################
#CreateDirectory properties
DirectoryDialog.createQuestion=ディレクトリ "{0}" は存在しません。新しく作成しますか ?
DirectoryDialog.Question=質問

###########################################################
#SchematicContextMenuProvider properties

SchematicContextMenuProvider.ActionText.editData=値と式の編集\u2026(&V)
SchematicContextMenuProvider.ActionText.editLabel=編集(&D)
SchematicContextMenuProvider.Menu.Apply=スタイルの適用(&P)
SchematicContextMenuProvider.Menu.EditGroup=グループの編集(&E)
SchematicContextMenuProvider.Menu.Insert=挿入(&I)
SchematicContextMenuProvider.Menu.insertElement=挿入(&I)
SchematicContextMenuProvider.Menu.insertRow=行(&R)
SchematicContextMenuProvider.Menu.List=リスト
SchematicContextMenuProvider.Menu.Show=表示
SchematicContextMenuProvider.Menu.Style=スタイル(&Y)
SchematicContextMenuProvider.Menu.Theme=テーマ(&M)
SchematicContextMenuProvider.menutitle.applystylerule=スタイルの適用
SchematicContextMenuProvider.menutitle.applythemerule=テーマの適用
SchematicContextMenuProvider.menutitle.editgroup=グループの編集
SchematicContextMenuProvider.menutitle.insert=挿入
SchematicContextMenuProvider.menutitle.list=リスト
SchematicContextMenuProvider.menutitle.show=表示
SchematicContextMenuProvider.menutitle.style=スタイル
SchematicContextMenuProvider.Menu.EditStyle=スタイルの編集(&T)
SchematicContextMenuProvider.Menu.DeleteStyle=スタイルの削除(&S)
SchematicContextMenuProvider.Menu.DeleteGroup=グループの削除(&T)
SchematicContextMenuProvider.Menu.InsertGroupHeaderFooter=グループヘッダ/フッタの挿入(&P)
SchematicContextMenuProvider.Menu.NewStyle=スタイルの新規作成(&Y)

###########################################################
#SectionProcess properties

SectionProcess.action.Clear=クリア
SectionProcess.action.Delete=削除
SectionProcess.action.DeleteRow=行の削除
SectionProcess.action.New=新規作成
SectionProcess.action.NewCell=新規セル
SectionProcess.action.NewGroup=グループの新規作成
SectionProcess.action.NewRow=行の新規作成
SectionProcess.action.NewSection=新規セクション
SectionProcess.action.NewSubSection=サブセクションの新規作成
SectionProcess.displayname.GridProcess=グリッド
SectionProcess.displayname.GroupProcess=グループ
SectionProcess.displayname.ListProcess=リスト
SectionProcess.displayname.TableProcess=テーブル
SectionProcess.displayname.TableRowProcess=行
SectionProcess.type.Container=(コンテナ)
SectionProcess.type.Data=(データ)
SectionProcess.type.Image=(イメージ)
SectionProcess.type.Label=(ラベル)
SectionProcess.type.List=(リスト)
SectionProcess.type.Prefix=列
SectionProcess.type.Table=(テーブル)
SectionProcess.type.Text=(テキスト)

###########################################################
#SelectAllAction properties

SelectAllAction.text=すべて選択(&A)

###########################################################
#SelectCssStyleWizard properties

SelectCssStyleWizard.wizard.title=CSS スタイルのインポート
SelectCssStyleWizard.wizardPage.description=ここで選択した CSS ファイルから、レポートデザインにスタイルをインポートします。
SelectCssStyleWizard.wizardPage.name=CSS スタイルの選択
SelectCssStyleWizard.wizardPage.title=CSS ファイルからスタイルをインポート

###########################################################
#SelectValueDialog properties

SelectValueDialog.errorRetrievinglist=リストを検索する際にエラーが発生しました。
SelectValueDialog.messages.info.selectVauleUnavailable=値の一覧を取得できるのは、row["name"]、row[index]、または row.name という形式の式だけです。 
SelectValueDialog.messages.error.selectVauleUnavailable=式の値を取得できません。
SelectValueDialog.noExpressionSet=式が設定されていません。
SelectValueDialog.retrieving=リストの取得中...
SelectValueDialog.selectValue=値の選択 

###########################################################
#SetConstraintCommand properties

SetConstraintCommand.Error.SetConstraintError=モデルに制約を設定中にエラーが発生しました。
SetConstraintCommand.transLabel.setConstraint=制約の設定

###########################################################
#ShowPropertyAction properties

ShowPropertyAction.text=プロパティ

###########################################################
#SortingHandleProvider properties

SortingHandleProvider.Label.SortOn=ソート :

###########################################################
#Spinner properties

Spinner.DialogTitle.InvalidNumber=Invalid number

###########################################################
#SplitAction properties

SplitAction.actionMsg.splitCells=セルの分割(&S)

###########################################################
#StyleBuilder properties

StyleBuilder.action.Apply=適用(&A)
SytleBuilder.DialogTitle.New=スタイルの新規作成
SytleBuilder.DialogTitle.Edit=スタイルの編集

###########################################################
#StyleComboProvider properties

StyleComboProvider.LineStyle.None=スタイルなし

###########################################################
#StyleNodeProvider properties

StyleNodeProvider.action.Edit=スタイルの編集(&E)...
StyleNodeProvider.action.New=スタイルの新規作成(&N)...

###########################################################
#StyleProcess properties

StyleProcess.action.Delete=スタイルの削除
StyleProcess.action.Edit=スタイルの編集(&E)...
StyleProcess.action.New=スタイルの新規作成(&N)...
StyleProcess.text.CannotDelete=デフォルトのスタイルを削除できません。 
StyleProcess.text.Show=データセットのエディタを表示します。

###########################################################
#StylesNodeProvider properties

StylesNodeProvider.action.New=スタイルの新規作成...

###########################################################
#StylesOutlineProcess properties

StylesOutlineProcess.action.New=スタイルの新規作成...

###########################################################
#TableBandProvider properties

TableBandProvider.action.text.group=グループを挿入
TableBandProvider.action.text.row=行の挿入

###########################################################
#TableEditPart properties

TableEditPart.GUIDEHANDLE_TEXT = テーブル
TableEditPart.Label.Merge=Merge Cells
TableEditPart.Label.ResizeColumn=列幅の変更
TableEditPart.Label.ResizeRow=行幅の変更

###########################################################
#TableFigure properties

TableFigure.BORDER_TEXT=テーブル
TableArea.Button.New=新規(&N)...
TableArea.Button.Edit=編集(&E)...
TableArea.Button.Remove=削除(&R)
TableArea.Button.Down=下へ(&O)

###########################################################
#TableHandleAdapter properties

TableHandleAdapter.name.detail=詳細
TableHandleAdapter.name.footer=フッタ
TableHandleAdapter.name.header=ヘッダ
TableHandleAdapter.transLabel.deleteColumn=列の削除
TableHandleAdapter.transLabel.deleteColumns=列の削除
TableHandleAdapter.transLabel.deleteRow=行の削除
TableHandleAdapter.transLabel.deleteRows=行の削除
TableHandleAdapter.transLabel.include=含める 
TableHandleAdapter.transLabel.insertColumn=列の挿入
TableHandleAdapter.transLabel.insertGroup=グループの挿入
TableHandleAdapter.transLabel.insertRow=行の挿入
TableHandleAdapter.transLabel.notInclude=含めない 
TableHandleAdapter.transLabel.splitCells=セルの分割
TableHandleAdapter.transLable.deleteGroup=テーブルグループの削除

###########################################################
#TableOptionDialog properties

TableOptionDialog.message.RememberGrid=新しいグリッドのサイズを使用する(&U)
TableOptionDialog.message.RememberTable=新しいテーブルのサイズを使用する(&U)
TableOptionDialog.text.Column=列数(&C) :
TableOptionDialog.text.GridRow=行数(&R) :
TableOptionDialog.text.GridSize=グリッドのサイズ
TableOptionDialog.text.TableDetail=表示する詳細の数(&D) :
TableOptionDialog.text.TableSize=テーブルのサイズ
TableOptionDialog.title.InsertGrid=グリッドの挿入
TableOptionDialog.title.InsertTable=テーブルの挿入
TableOptionDialog.text.DataSet=データセット :

###########################################################
#TablePageGenerator properties

TablePageGenerator.List.Bookmark=ブックマーク
TablePageGenerator.List.Borders=罫線
TablePageGenerator.List.CellPadding=セルのパディング
TablePageGenerator.List.Font=フォント
TablePageGenerator.List.General=全般
TablePageGenerator.List.Marign=余白
TablePageGenerator.List.Section=ページ区切り
TablePageGenerator.List.TOC=目次
TablePageGenerator.List.Visibility=可視性
TablePageGenerator.TabItem.Binding=バインド
TablePageGenerator.TabItem.Filters=フィルタ
TablePageGenerator.TabItem.Groups=グループ
TablePageGenerator.TabItem.Highlights=ハイライト
TablePageGenerator.TabItem.map=マップ
TablePageGenerator.TabItem.Sorting=ソート

###########################################################
#TemplateReportItemPropertiesDialog properties

TemplateReportItemPropertiesDialog.errorMessage=プロンプトテキストは空白にできません。
TemplateReportItemPropertiesDialog.errorTitle=エラー
TemplateReportItemPropertiesDialog.group=テンプレートのレポート項目のプロパティ
TemplateReportItemPropertiesDialog.objectType=要素型 :
TemplateReportItemPropertiesDialog.nameText=名前(&N) :
TemplateReportItemPropertiesDialog.promptText=手順(&I) :
TemplateReportItemPropertiesDialog.title=テンプレートのレポート項目の作成

###########################################################
#performCreatePlaceHolder action
performCreatePlaceHolder.errorMessage.title=エラー
performCreatePlaceHolder.errorMessage.content=指定した名前はすでに存在します。別の名前を指定するか、空白にしてください。

###########################################################
#TogglePropertyDescriptor properties
TogglePropertyDescriptor.toolTipText.Bold=太字
TogglePropertyDescriptor.toolTipText.Italic=斜体
TogglePropertyDescriptor.toolTipText.Underline=下線
TogglePropertyDescriptor.toolTipText.Text_Line_Through=テキストの取り消し線

###########################################################
#TextAlignPropertyDescriptor properties

TextAlignPropertyDescriptor.0=左揃え
TextAlignPropertyDescriptor.1=中央揃え
TextAlignPropertyDescriptor.2=右揃え
TextAlignPropertyDescriptor.3=両端揃え

###########################################################
#TextAreaContextMenu properties

TextAreaContextMenu.Copy.description=コピー
TextAreaContextMenu.Copy.image=
TextAreaContextMenu.Copy.label=コピー(&C)
TextAreaContextMenu.Copy.tooltip=コピー
TextAreaContextMenu.Cut.description=切り取り
TextAreaContextMenu.Cut.image=
TextAreaContextMenu.Cut.label=切り取り(&T)
TextAreaContextMenu.Cut.tooltip=切り取り
TextAreaContextMenu.Paste.description=貼り付け
TextAreaContextMenu.Paste.image=
TextAreaContextMenu.Paste.label=貼り付け(&P)
TextAreaContextMenu.Paste.tooltip=貼り付け
TextAreaContextMenu.Redo.description=やり直し
TextAreaContextMenu.Redo.image=
TextAreaContextMenu.Redo.label=やり直し(&R)
TextAreaContextMenu.Redo.tooltip=やり直し
TextAreaContextMenu.SelectAll.description=すべて選択
TextAreaContextMenu.SelectAll.image=
TextAreaContextMenu.SelectAll.label=すべて選択(&A)
TextAreaContextMenu.SelectAll.tooltip=すべて選択
TextAreaContextMenu.Undo.description=元に戻す
TextAreaContextMenu.Undo.image=
TextAreaContextMenu.Undo.label=元に戻す(&U)
TextAreaContextMenu.Undo.tooltip=元に戻す

###########################################################
#TextDataEditPart properties

TextDataEditPart.Figure.Dafault=ダイナミックテキスト

###########################################################
#TextEditDialog properties

TextEditDialog.action.text.editDynamicText=ダイナミックテキストの編集(&X)
TextEditDialog.action.text.formatDateTime=日時の書式設定(&E)
TextEditDialog.action.text.formatNumber=数値の書式設定(&N)
TextEditDialog.action.text.formatString=書式文字列(&G)
TextEditDialog.choice.HTML=HTML / ダイナミックテキスト形式
TextEditDialog.choice.plainText=標準のテキスト形式
TextEditDialog.choice.Auto=自動
TextEditDialog.comboText.formattingAndLayout=書式とレイアウト
TextEditDialog.format.dynamicText=ダイナミックテキスト
TextEditDialog.format.formatting=書式とレイアウト
TextEditDialog.format.lists=リスト
TextEditDialog.format.pageComposition=ページ構成
TextEditDialog.format.pageElements=ページ要素
TextEditDialog.formatChoice.content=コンテンツ
TextEditDialog.formatChoice.dynamicText=ダイナミックテキスト
TextEditDialog.formatChoice.formatting=書式設定
TextEditDialog.formatChoice.layout=レイアウト
TextEditDialog.formatChoice.lists=リスト
TextEditDialog.toolTip.tag.a=アンカー
TextEditDialog.toolTip.tag.b=太字テキスト
TextEditDialog.toolTip.tag.birtImage=BIRT 固有のイメージ
TextEditDialog.toolTip.tag.br=改行
TextEditDialog.toolTip.tag.center=テキストの中央揃え
TextEditDialog.toolTip.tag.code=プログラミングコード
TextEditDialog.toolTip.tag.dd=定義の説明
TextEditDialog.toolTip.tag.del=削除されたテキスト
TextEditDialog.toolTip.tag.dl=定義リスト
TextEditDialog.toolTip.tag.dt=定義の条件
TextEditDialog.toolTip.tag.em=強調
TextEditDialog.toolTip.tag.font=フォントの部分変更
TextEditDialog.toolTip.tag.genericStyleContainer=汎用言語 /スタイルコンテナ
TextEditDialog.toolTip.tag.h1=見出し 1
TextEditDialog.toolTip.tag.h2=見出し 2
TextEditDialog.toolTip.tag.h3=見出し 3
TextEditDialog.toolTip.tag.h4=見出し 4
TextEditDialog.toolTip.tag.h5=見出し 5
TextEditDialog.toolTip.tag.h6=見出し 6
TextEditDialog.toolTip.tag.i=斜体テキスト
TextEditDialog.toolTip.tag.img=標準 HTML イメージの参照
TextEditDialog.toolTip.tag.ins=挿入されたテキスト
TextEditDialog.toolTip.tag.li=リスト項目
TextEditDialog.toolTip.tag.p=段落
TextEditDialog.toolTip.tag.pre=書式設定済みテキスト
TextEditDialog.toolTip.tag.strong=より強い強調
TextEditDialog.toolTip.tag.sub=下付き
TextEditDialog.toolTip.tag.sup=上付き
TextEditDialog.toolTip.tag.tt=等幅テキスト
TextEditDialog.toolTip.tag.u=下線付きテキスト
TextEditDialog.toolTip.tag.ul=順不同リスト
TextEditDialog.toolTip.valueOf=Value Of
TextEditDialog.toolTipText.copy=コピー
TextEditDialog.toolTipText.cut=切り取り
TextEditDialog.toolTipText.delete=削除
TextEditDialog.toolTipText.paste=貼り付け
TextEditDialog.toolTipText.redo=やり直し
TextEditDialog.toolTipText.undo=元に戻す

###########################################################
#TextEditPart properties

TextEditPart.Figure.Dafault=テキスト
TextEditPart.trans.editText=テキスト項目の編集

###########################################################
#TextExtendsTools properties

TextExtendsTools.Message.DefaultAuthor=Birt Eclipse Report Designer のバージョン

###########################################################
#TextPageGenerator properties

TextPageGenerator.List.Bookmark=ブックマーク
TextPageGenerator.List.Borders=罫線
TextPageGenerator.List.General=全般
TextPageGenerator.List.I18n=ローカライゼーション
TextPageGenerator.List.Margin=余白
TextPageGenerator.List.Padding=パディング
TextPageGenerator.List.Section=ページ区切り
TextPageGenerator.List.TOC=目次
TextPageGenerator.List.Visibility=可視性

###########################################################
#TextPropertyDescriptor properties

TextPropertyDescriptor.Message.Version=Eclipse BIRT Designer Version {0} Build <{1}>

###########################################################
#AutoTextPageGenerator properties

AutoTextPageGenerator.List.Bookmark=ブックマーク
AutoTextPageGenerator.List.Borders=罫線
AutoTextPageGenerator.List.General=全般
AutoTextPageGenerator.List.Margin=余白
AutoTextPageGenerator.List.Padding=パディング
AutoTextPageGenerator.List.Section=ページ区切り
AutoTextPageGenerator.List.TOC=目次
AutoTextPageGenerator.List.Visibility=表示/非表示

###########################################################
#ThemesNodeProvider properties

ThemesNodeProvider.action.New=新規テーマ

###########################################################
#TimeOptionDialog properties

TimeOptionDialog.Label.Format=形式
TimeOptionDialog.Label.TimeZone=タイムゾーン

###########################################################
#ToggleMarginVisibilityAction properties

ToggleMarginVisibilityAction.text.Label=余白の表示(&M)
ToggleMarginVisibilityAction.text.Tooltip=余白の切り替え

###########################################################
#TwinExpressionDialog properties

TwinExpressionDialog.Dialog.Title=値の選択
TwinExpressionDialog.lable.value1=値 1 :
TwinExpressionDialog.lable.value2=値 2 :

###########################################################
#UndoAction properties

UndoAction.Tooltip={0} を元に戻す

###########################################################
#UnitPropertyDescriptor properties

UnitPropertyDescriptor.error.message=Please enter a smaller value\!
UnitPropertyDescriptor.error.title=Too Big Value

###########################################################
#UseLibraryAction properties

UseLibraryAction.Text=ライブラリの使用(&U)
UseLibraryAction.Error.Title=既存のファイルの上書き
UseLibraryAction.Error.Message=BIRT リソースフォルダには、ファイル ''{0}'' がすでに存在します。既存のファイルを上書きしますか ?

###########################################################
#UserPropertyBuilder properties

UserPropertyBuilder.0=ユーザープロパティの新規作成
UserPropertyBuilder.ErrorMessage.DuplicatedName=この名前はすでに使用されています。
UserPropertyBuilder.ErrorMessage.NoName=名前を指定してください。
UserPropertiesHandleProvier.Column.Name=名前
UserPropertiesHandleProvier.Column.Type=型
UserPropertyBuilder.Label.DefaultValue=デフォルト値(&V) :
UserPropertyBuilder.Label.ExpressionName=式の名前(&N) :
UserPropertyBuilder.Label.PropertyName=プロパティ名(&N) :
UserPropertyBuilder.Label.PropertyType=プロパティの種類(&T) :
UserPropertyBuilder.Title.NamedExpression=名前付き式の新規作成

###########################################################
#VisibilityPage properties

VisibilityPage.Check.HideElement=要素の非表示(&H)
VisibilityPage.Check.HTML=HTML(&T)
VisibilityPage.Check.PDF=PDF(&P)
VisibilityPage.Label.DetailAll=詳細 (すべての出力ファイル)
VisibilityPage.Label.DetailSpecific=詳細 (特定の出力ファイル)
VisibilityPage.Label.Expression=式(&E) :
VisibilityPage.menu.SaveHides=非表示の項目を保存
VisibilityPage.Radio.AllOutputs=すべての出力ファイル(&A)
VisibilityPage.Radio.SpecificOutputs=特定の出力ファイル(&S)...

###########################################################
#WidgetUtil properties

WidgetUtil.MessageBox.Error=エラー

###########################################################
#wizard properties

wizard.transaction.createDataSource=データソースの名前と型を定義してください。

###########################################################
#WizardChoicePage properties

WizardChoicePage.radio.createBlank=テンプレートを使わずに空のレポートを作成する。
WizardChoicePage.radio.createFromCustom=別のレポートをコピーしてレポートを作成する。
WizardChoicePage.radio.createFromTemplate=テンプレートを使ってレポートを作成する。

###########################################################
#WizardCustomTemplatePage properties

WizardCustomTemplatePage.button.Browse=参照
WizardCustomTemplatePage.label.FileName=既存のレポートファイル名の入力または選択。
WizardCustomTemplatePage.label.FromLocal=ローカルファイルシステムの参照。
WizardCustomTemplatePage.label.FromProjectDescription=既存のレポートファイルの選択。
WizardCustomTemplatePage.label.FromProjectTitle=レポートファイルの選択

###########################################################
#WizardNewReportCreationPage properties

WizardNewReportCreationPage.Errors.nameExists=この名前はすでに使われています。
WizardNewReportCreationPage.label.browse=参照...
WizardNewReportCreationPage.label.directory=ディレクトリ :
WizardNewReportCreationPage.label.file.location=ファイルの場所
WizardNewReportCreationPage.label.file.name=ファイル名 :
WizardNewReportCreationPage.label.select.directory=ディレクトリを選択してください。
WizardNewReportCreationPage.label.useDefault=デフォルト使用
WizardNewReportCreationPage.msg.duplicate.fileName=この名前はすでに使われています。
WizardNewReportCreationPage.msg.empty.file.locationDirectory=ファイルの場所のディレクトリは空白にできません。
WizardNewReportCreationPage.msg.empty.file.name=ファイル名は空白にできません。

###########################################################
#WizardSelectCssStylePage properties

WizardSelectCssStylePage.button.label.browse=参照(&B)...
WizardSelectCssStylePage.button.label.deselectAll=すべて選択解除(&D)
WizardSelectCssStylePage.button.label.selectAll=すべて選択(&S)
WizardSelectCssStylePage.errorMsg.FileNotExist=ファイルが見つかりません。
WizardSelectCssStylePage.info.canNotImport=\ \ (インポートできません)
WizardSelectCssStylePage.label.fileName=ファイル名(&F) :
WizardSelectCssStylePage.label.importToReportDesign=\ レポートデザインにインポート。
WizardSelectCssStylePage.label.notifications=通知 :
WizardSelectCssStylePage.label.selectStylesFrom=次のファイルからスタイルを選択 
WizardSelectCssStylePage.msg.FileNameEmpty=ファイル名は空白にできません。
WizardSelectCssStylePage.text.cannot.import.style=\ - スタイルをインポートできません。
WizardSelectCssStylePage.FileNameError.Title=エラー
WizardSelectCssStylePage.FileNameError.Message=選択したファイルは無効です。

###########################################################
#WizardTemplateChoicePage properties

WizardTemplateChoicePage.label.Description=説明 :
WizardTemplateChoicePage.label.Preview=プレビュー :
WizardTemplateChoicePage.label.ReportTemplates=レポートテンプレート :
WizardTemplateChoicePage.label.ShowCheatSheets=レポート作成ガイドの表示(&S)
WizardTemplateChoicePage.message.BlankReport=内容が定義されていない空白のレポートを作成します。
WizardTemplateChoicePage.message.ChartListing=グループ化されたレポートを作成します。グラフは、それぞれのグループのデータを視覚的に表します。
WizardTemplateChoicePage.message.DualColumnChartListing=グラフとリストのサブグループを 2 つ持つグループ化されたレポートを作成します。
WizardTemplateChoicePage.message.DualColumnListing=サブグループを 2 つ持つグループ化されたレポートを作成します。 
WizardTemplateChoicePage.message.FirstReport=顧客リストレポートの作成手順が表示されます。
WizardTemplateChoicePage.message.GroupedListing=一部のフィールドをグループ化したリストレポートを作成します。
WizardTemplateChoicePage.message.Letter=データソースのフィールドを使用して個人用の手紙を生成するためのテンプレートを作成します。
WizardTemplateChoicePage.message.MailingLabels=郵便用のラベル
WizardTemplateChoicePage.message.SideBySideChartListing=グループ化されたレポートを作成します。それぞれのグループには、グラフとリストが並列表示されます。
WizardTemplateChoicePage.message.SimpleListing=データソースのフィールドを使用したリストレポートを作成します。
WizardTemplateChoicePage.title.BlankReport=空のレポート
WizardTemplateChoicePage.title.ChartListing=グラフとリスト
WizardTemplateChoicePage.title.DualColumnChartListing=列グラフとリストの同時表示
WizardTemplateChoicePage.title.DualColumnListing=列リストの同時表示
WizardTemplateChoicePage.title.FirstReport=はじめてのレポート
WizardTemplateChoicePage.title.GroupedListing=グループごとのリスト
WizardTemplateChoicePage.title.Letter=レター
WizardTemplateChoicePage.title.MailingLabels=郵便用のラベル
WizardTemplateChoicePage.title.SideBySideChartListing=グラフとリストの並列表示
WizardTemplateChoicePage.title.SimpleListing=簡易リスト

###########################################################
#XMLSourcePage properties

XMLSourcePage.Error.Dialog.Message.InvalidFile=XML のソースページにあるエラーを修正しないと、他のページを使用できません。
XMLSourcePage.Error.Dialog.Message.SaveFile=XML のソースページが変更されました。XML のソースページを保存しないと、他のページを使用できません。
XMLSourcePage.Error.Dialog.title=警告
XMLSourcePage.Error.Dialog.Message.PromptMsg=XML レポートデザインのソースが変更されました。変更内容を保存しますか ?
XMLSourcePage.Error.Dialog.Message.Yes=はい
XMLSourcePage.Error.Dialog.Message.No=いいえ
XMLSourcePage.Error.Dialog.Message.Cancel=キャンセル

###########################################################
#SaveReportAsWizard properties
SaveReportAsWizard.SettingPage.title=テンプレートプロパティの設定
SaveReportAsWizard.SaveAsPageTitle=名前を付けて保存
SaveReportAsWizard.SaveAsLibraryMessage=このファイルをライブラリとして別名で保存します。
SaveReportAsWizard.SaveAsReportorTemplateMessage=このファイルをレポートデザインまたはテンプレートとして別名で保存します。
SaveReportAsWizard.SettingPageTitle=レポートプロパティの設定
SaveReportAsWizard.SettingPage.message=レポートをテンプレートとして保存すると、これらのプロパティが使用されます。
SaveReportAsWizard.SaveAsWizardWindowTitle=名前を付けて保存
SaveReportAsWizard.SaveAsWizardPageTitle=名前を付けて保存
SaveReportAsWizard.SaveAsWizardPageDesc=ファイルを別の場所に保存します。

###########################################################
#WizardReportSettingPage properties
WizardReportSettingPage.Error.ReportorTemplate=ファイル名の拡張子は、{0} または .rpttemplate にしてください。
WizardReportSettingPage.Error.Library=ファイル名の拡張子は、.rptlibrary にしてください。

###########################################################
#WizardSaveAsPage properties
WizardSaveAsPage.FileLabel=ファイル名(&F) :
WizardSaveAsPage.Question=質問
WizardSaveAsPage.FolderEmpty=\ フォルダが空です。
WizardSaveAsPage.NoProject=\ 指定したプロジェクトは存在しません。
WizardSaveAsPage.PathOccupied=\ その場所にはすでにファイルがあります : {0}
WizardSaveAsPage.EmptyName=\ ''{0}'' の名前が空です。
WizardSaveAsPage.SelectFolder=\ フォルダの選択 :
WizardSaveAsPage.NameExists=\ 同じ名前はすでに使用されています。
WizardSaveAsPage.OverwriteQuestion=指定したファイル ''{0}'' はすでに存在します。既存のファイルを上書きしますか ?
WizardSaveAsPage.InvalidFileName=\ ''{0}'' は有効なファイル名ではありません。
WizardSaveAsPage.ContainerGroup=\ 親フォルダの入力・選択(&E) :

###########################################################
#Library DND message
Library.DND.messages.outofsync = レポートで使用しているライブラリは、変更されています。更新されているライブラリを使用するには、このレポートをいったん閉じてから開き直してください。
NamedExpressionsHandleProvier.Column.Name=名前
NamedExpressionsHandleProvier.Column.DefaultValue=デフォルト値
Library.DND.messages.cannotApplyTheme=テーマを適用できません。

JarFileFormProvider.Column.Name=名前

###########################################################
#ClassFinder
ClassFinder.TaskStart=ハンドラクラスを検索中...
ClassFinder.DialogTitle=クラスの選択
ClassFinder.DialogMessage=ハンドラクラスの選択
ClassFinder.ErrorMessage=クラスが見つかりません。

###########################################################
#ListingSectionPage
ListingSectionPage.RepeatHeader=ヘッダの繰り返し

###########################################################
#ResourceEditDialog
ResourceEditDialog.NotFile.Title=ファイルが見つかりません。
ResourceEditDialog.NotFile.Message=ファイル ''{0}'' は存在しません。
ResourceEditDialog.ReadOnlyEncounter.Title=読み取り専用ファイル
ResourceEditDialog.ReadOnlyEncounter.Message=ファイル ''{0}'' は読み取り専用です。先に、このファイルを書き込み可能にしてください。

###########################################################
#EventHandler
EventHandlerPage.Browse=参照(&B)...


###########################################################
#IDEFileReportProvider
IDEFileReportProvider.ReadOnlyEncounter.Title=読み取り専用ファイル
IDEFileReportProvider.ReadOnlyEncounter.Message=ファイル ''{0}'' は読み取り専用です。先に、このファイルを書き込み可能にしてください。

###########################################################
#DataSetColumnBindingsFormHandleProvider
DataSetColumnBindingsFormHandleProvider.Column.Name=名前
DataSetColumnBindingsFormHandleProvider.TableTitle=データカラムのバインド :
DataSetColumnBindingsFormHandleProvider.NewBinding=新規バインド  
DataSetColumnBindingsFormHandleProvider.Column.DataType=データ型
DataSetColumnBindingsFormHandleProvider.Column.Expression=式
DataSetColumnBindingsFormHandleProvider.Column.AggregateOn=集計条件
DataSetColumnBindingsFormHandleProvider.ALL=すべて
DataSetColumnBindingsFormHandleProvider.NONE=N/A

###########################################################
#DataSetColumnBindingsFormPage
DataSetColumnBindingsFormPage.Button.RemoveUnused=未使用のカラムの削除

###########################################################
#ResourceSelectionValidator
ResourceSelectionValidator.ExtError=選択したファイルの拡張子は次のようにしてください : 
ResourceSelectionValidator.EmptyError=ファイルを選択してください。
ResourceSelectionValidator.ExtErrorSplitter=\ または 

###########################################################
#GeneralPage
GeneralPage.Library.Included=ライブラリ :
###########################################################
#
FormatStringPage.SimpleTextZipCode=94103
FormatStringPage.SimpleTextZipCode4=941031234
FormatStringPage.PhoneNumber=4155551111
FormatStringPage.SocialSecurityNumber=123456789
FormatStringPage.simpleTexZipCodeFormat=@@@
FormatStringPage.simpleTexZipCode4Format=@@@-@@@@
FormatStringPage.phoneNumberFormat=(@@@)@@@-@@@@
FormatStringPage.securityNumberFormat=@@@-@@-@@@@

###########################################################
#PublishLibraryDialog
PublishLibraryDialog.ShellText=ライブラリの公開
PublishLibraryDialog.TitleArea=ライブラリの公開
PublishLibraryDialog.Message=BIRT リソースフォルダにライブラリを公開します。
PublishLibraryDialog.Label.SourceFileName=ソースファイル(&S) :
PublishLibraryDialog.Label.FileName=ファイル名(&N) :
PublishLibraryDialog.Label.Folder=フォルダ(&F) :
PublishLibraryDialog.Label.Browse=参照(&B)...
PublishLibraryDialog.Message.FileNameEmpty=ファイル名を指定してください。
PublishLibraryDialog.Message.FileNameError=ファイル名の拡張子は、.rptlibrary にしてください。
PublishLibraryDialog.Message.FolderEmpty=フォルダを公開してください。
PublishLibraryDialog.Message.SourceFileEmpty=ソースファイルの名前を指定してください。
PublishLibraryDialog.Label.Browse2=参照(&W)...
PublishLibraryDialog.AddText=ライブラリの追加
PublishLibraryDialog.AddMessage=BIRT リソースフォルダにライブラリを追加します。

WizardLibrarySettingPage.ErrorMessage=フォルダを選択してください。

WizardLibrarySettingPage.Resourcefile.Dialog.Title=リソースフォルダの参照
WizardLibrarySettingPage.Resourcefile.Dialog.Message=サブフォルダからリソースフォルダを選択してください。

PublishLibraryDialog.AddLibrary=ライブラリの追加

###########################################################
#EmbeddedImagesNodeProvider
EmbeddedImagesNodeProvider.FileNameError.Title=エラー
EmbeddedImagesNodeProvider.FileNameError.Message=選択したファイルは、イメージではありません。

###########################################################
#AddElementtoAction properties
AddElementtoAction.Text=レポートに追加(&A)

###########################################################
#MultiPageReportEditor properties
MultiPageReportEditor.CheckVersion.Dialog.Title=警告
TableArea.Button.Up=上へ(&U)

###########################################################
#AddJarResourceFileFolderSelectionDialog
AddJarResourceFileFolderSelectionDialog.ErrorMessage.Exist=すでに存在するファイルを選択しています。
AddJarResourceFileFolderSelectionDialog.Message=JAR ファイルを選択してください :
AddJarResourceFileFolderSelectionDialog.ErrorMessage.ExtError=ファイル名の拡張子は .jar にしてください。

###########################################################
#AddImageResourceFileFolderSelectionDialog
AddImageResourceFileFolderSelectionDialog.Title=すでに存在するファイルを選択しています。
AddImageResourceFileFolderSelectionDialog.Message=イメージの選択 :

###########################################################
#DataItemBindingDialog properties

DataItemBindingDialog.text.Name=名前 :
DataItemBindingDialog.text.DataType=データ型 :
DataItemBindingDialog.text.Expression=式 :
DataItemBindingDialog.text.AggregateOn=集計条件 :
DataItemBindingDialog.text.ForceBinding=同じ式で新しいバインドを作成します。
DataItemBindingDialog.text.All=すべて
DataItemBindingDialog.text.None=N/A
DataItemBindingDialog.title.CreateNewItem=データ項目の新規作成
DataItemBindingDialog.title.EditDataItem=データ項目の編集

###########################################################
#DataColumBindingDialog properties
DataColumBindingDialog.title.CreateNewDataBinding=データバインドの新規作成
DataColumBindingDialog.title.EditDataBinding=データバインドの編集

###########################################################
#CreatePlaceHolderAction properties
ChangeDataColumnAction.text=データ列の変更

###########################################################
#ThumbnailBuilder properties
ThumbnailBuilder.Text.Title=サムネールの管理
ThumbnailBuilder.Button.Text.Generate=生成(&G)
ThumbnailBuilder.Button.Text.Remove=削除(&R)
ThumbnailBuilder.Button.Text.Import=インポート(&I)...
ThumbnailBuilder.FileDialog.Title=イメージファイルの選択
ThumbnailBuilder.FileDialog.FileNameError.Title=エラー
ThumbnailBuilder.FileDialog.FileNameError.Message=選択したファイルは、イメージではありません。

###########################################################
#FragmentResourceEntry properties
FragmentResourceEntry.RootName=フラグメント
FragmentResourceEntry.RootDisplayName=Built-in Libraries

###########################################################
#PathResourceEntry properties
PathResourceEntry.RootName=リソースフォルダ
PathResourceEntry.RootDisplayName=Shared Libraries

###########################################################
#BIRTGotoMarker properties
BIRTGotoMarker.Error.Title=エラー
BIRTGotoMarker.Error.Message=レポート要素は存在しません。

###########################################################
#TabbedList properties
TabbedPropertyList.properties.not.available=Properties are not available.
