###########################################################
#AbstractDataSetWizard properties

AbstractDataSetWizard.ModelTrans.Create=定义数据集的名称、源和类型
###########################################################
#CssErrDialog
CssErrDialog.shellTitle.ImportCssStyleMssageTitle=导入消息
CssErrDialog.AreaTitle=导入 CSS 样式消息
CssErrDialog.AreaMessage=导入 css 样式时出现某些错误或警告。
CssErrDialog.Serverity=严重性:
CssErrDialog.Message=消息:
CssErrDialog.FatalError=致命错误
CssErrDialog.Error=错误
CssErrDialog.Warning=警告

###########################################################
#AddGroupAction properties

AddGroupAction.actionMsg.addGroup=插入组...
AddGroupAction.Menu.Text=插入组...
AddGroupAction.stackMsg.addGroup=插入组

###########################################################
#AddLibraryAction properties

AddLibraryAction.Error.FileNotFound=未找到文件 ''{0}''。
AddLibraryAction.Error.FileIsNotLibrary=文件“{0}”没有以“{1}”结束。
AddLibraryAction.Error.Message=文件已经存在。
AddLibraryAction.Error.Title=错误
AddLibraryAction.Text=添加库...
AddLibraryAction.Dialog.Tilte=选择库

###########################################################
#DeleteLibraryAction properties
DeleteLibraryAction.Text=删除
###########################################################
#AddStyleRuleAction properties

AddStyleAction.actionMsg.addStyleRule=新建样式(&N)...
AddStyleAction.stackMsg.addStyle=新建样式(&N)

###########################################################
#ApplyStyleAction properties

ApplyStyleAction.actionLabel.none=无
ApplyStyleAction.stackMsg.applyStyle=应用样式

###########################################################
#ApplyThemeAction properties

ApplyThemeAction.actionLabel.none=无
ApplyThemeAction.stackMsg.applyStyle=应用主题

###########################################################
#AttributesBuilder properties

AttributesBuilder.Label.Cell=属性编辑器 - 单元格
AttributesBuilder.Label.Column=属性编辑器 - 列
AttributesBuilder.Label.Data=属性编辑器 - 数据
AttributesBuilder.Label.Generic=属性编辑器 - {0}
AttributesBuilder.Label.Grid=属性编辑器 - 网格
AttributesBuilder.Label.Label=属性编辑器 - 标签
AttributesBuilder.Label.Library=属性编辑器 - 库
AttributesBuilder.Label.List=属性编辑器 - 列表
AttributesBuilder.Label.MasterPage=属性编辑器 - 主页
AttributesBuilder.Label.None=属性编辑器 - 无
AttributesBuilder.Label.Picture=属性编辑器 - 图片
AttributesBuilder.Label.Report=属性编辑器 - 报表
AttributesBuilder.Label.Row=属性编辑器 - 行
AttributesBuilder.Label.Table=属性编辑器 - 表
AttributesBuilder.Label.Text=属性编辑器 - 文本
AttributesBuilder.Label.TextData=属性编辑器 - 动态文本
AttributesBuilder.Label.DataSourceHandle=属性编辑器 - 数据源
AttributesBuilder.Label.DataSetHandle=属性编辑器 - 数据集
AttributesBuilder.Label.ScalarParameterHandle=属性编辑器 - 参数
AttributesBuilder.Label.TemplateReportItemHandle=属性编辑器 - 模板报表项
AttributesBuilder.Label.AutoText=属性编辑器 - 自动文本

###########################################################
#AttributeView properties
AttributeView.dialg.Message.Warning = 警告
AttributeView.dialg.Message.Yes=是(&E)
AttributeView.dialg.Message.No=否(&O)
AttributeView.dialg.Message.Cancel=取消(&A)
AttributeView.dialg.Message.PromptMsg=是否确实要清除所有本地属性?
AttributeView.toolbar.tooltip.EditingToggleAction.ClearMsg=清除本地属性。
AttributeView.toolbar.tooltip.EditingToggleAction.EnableEditingMsg=启用属性编辑。
AttributeView.toolbar.tooltip.EditingToggleAction.DisabledActionMsg=此操作不适用于本地元素。
AttributeView.view.message.Emptypage= 此 {0} 扩展自库 {2} 中的 {1}。要在此报表设计中修改 {3} 的属性，请单击"属性编辑器"工具栏中的"启用编辑"按钮。
AttributeView.toolbar.tooltip.RestoreLibraryPropertiesAction.RestoreMsg=还原属性
AttributeView.defaultText.noAttributeView = 属性编辑器不可用。
###########################################################
#BackGroundPreferencePage properties

BackGroundPreferencePage.displayname.Title=背景

###########################################################
#BasAttributePage properties

BasAttributePage.Label.Attributes=属性:

###########################################################
#BaseInsertMenuAction properties

BaseInsertMenuAction.stackMsg.insertElement=插入元素

###########################################################
#BasePaletteFactory properties

BasePaletteFactory.AutoText.Confidential=机密
BasePaletteFactory.AutoTextLabel.CreatedBy=创建者: 
BasePaletteFactory.AutoTextLabel.CreatedOn=创建时间: 
BasePaletteFactory.AutoTextLabel.Filename=文件名: 
BasePaletteFactory.AutoTextLabel.LastPrinted=上次打印时间: 
BasePaletteFactory.AutoTextLabel.Page=页: 
BasePaletteFactory.AutoTextLabel.PageCount=页数:
BasePaletteFactory.AutoTextLabel.PageXofY=第 X 页，共 Y 页
BasePaletteFactory.categoryName.PointerSelect=选择指针
BasePaletteFactory.categoryName.RectangleSelect=选择矩形
BasePaletteFactory.Group.Items=数据项
BasePaletteFactory.toolTip.PointerSelect=单击要选择的某个项，或按住 Ctrl 键单击要选择的多个项。
BasePaletteFactory.toolTip.RectangleSelect=单击并拖动以选择矩形中的所有项。 

###########################################################
#BaseStylePreferencePage properties

BaseStylePreferencePage.displayname.Title=常规

###########################################################
#BgImageFieldEditor properties

BgImageFieldEditor.displayname.Browse=浏览(&W)...

###########################################################
#BindingPage properties

BindingPage.Label.Binding=绑定
BindingPage.MessageDlg.SaveParamBinding=保存 ParamBinding
BindingPage.None=无
BindingPage.TableColumn.DataType=数据类型
BindingPage.TableColumn.Parameter=参数
BindingPage.TableColumn.Value=值

ColumnBingingDialog.Label.Warn=更改数据集会使所有结果集列表达式无效。
ColumnBindingDialog.Label.DataSet=数据集:
ColumnBindingDialog.Column.Expression=表达式
ColumnBindingDialog.DialogTitle=选择数据绑定
ColumnBindingDialog.Column.Name=名称
ColumnBindingDialog.InputPrompt=<在此处输入新值...>
ColumnBindingDialog.Button.Generate=生成列绑定
ColumnBindingDialog.Column.DataType=数据类型
ColumnBindingDialog.Column.AggregateOn=聚合条件
ColumnBindingDialog.All=全部
ColumnBindingDialog.NONE=无
ColumnBindingDialog.Choice.FromContainer=容器的数据集
ColumnBindingDialog.AGGREGATEON.NONE=不适用
ColumnBindingDialog.Text.Add=添加
ColumnBindingDialog.Text.Edit=编辑...
ColumnBindingDialog.Text.Del=删除

###########################################################
#BlockPreferencePage properties

BlockPreferencePage.displayname.Title=文本块

###########################################################
#BorderPreferencePage properties

BorderPreferencePage.displayname.Color=颜色
BorderPreferencePage.displayname.Style=样式
BorderPreferencePage.displayname.Title=边框
BorderPreferencePage.displayname.Width=宽度
BorderPreferencePage.text.Bottom=底部:
BorderPreferencePage.text.Left=左:
BorderPreferencePage.text.Right=右:
BorderPreferencePage.text.Top=顶部:

###########################################################
#BordersPage properties

BordersPage.Label.Borders=边框(&B):
BordersPage.Label.Color=颜色(&C):
BordersPage.Label.Presets=预设:
BordersPage.Label.Style=样式(&S):
BordersPage.Label.Width=宽度(&T):
BordersPage.Tooltip.All=所有框线
BordersPage.Tooltip.Bottom=下框线
BordersPage.Tooltip.Left=左框线
BordersPage.Tooltip.None=无
BordersPage.Tooltip.Right=右框线
BordersPage.Tooltip.Top=上框线
BordersPage.text.Preview=预览:
BordersPage.Trans.SelectBorder=Select Border
BordersPage.Trans.UnSelectBorder=Unselect Border
BordersPage.Trans.SelectAllborders=Select all borders
BordersPage.Trans.UnSelectAllborders=Unselect all borders

###########################################################
#BoxPreferencePage properties

BoxPreferencePage.displayname.Title=框
BoxPreferencePage.text.Margin=边距
BoxPreferencePage.text.Padding=填充

###########################################################
#ButtonPaneComposite properties

ButtonPaneComposite.tooltip.MasterPage=主页
ButtonPaneComposite.tooltip.Normal=正常
ButtonPaneComposite.tooltip.Ruler=标尺

###########################################################
#SettingsPage properties

SettingsPage.dataFetchSetting.label=Max number of rows to fetch from data source:
SettingsPage.CachePreference.button.clear=清除缓存(&C)
SettingsPage.CachePreference.checkBox.text=缓存数据集数据以便进行报表预览(&H)
SettingsPage.CachePreference.description=定义缓存大小:
SettingsPage.CachePreference.Filter.Tooltip=使用缓存将数据传入或传出数据集
SettingsPage.CachePreference.label.text=行
SettingsPage.CachePreference.messageBox.info=缓存已被清除
SettingsPage.CachePreference.messageBox.title=缓存清除
SettingsPage.CachePreference.radioBox.entireNumText=缓存整个数据集(&E)
SettingsPage.CachePreference.radioBox.numText=缓存和使用第一个(&U)

###########################################################
#CascadingParametersDialog properties

CascadingParametersDialog.Button.AllowNull=允许空值(&A)
CascadingParametersDialog.default.preview.string=我的字符串
CascadingParametersDialog.display.controlType.comboBox=组合框
CascadingParametersDialog.display.controlType.listBox=列表框
CascadingParametersDialog.Label.button.changeFormat=更改(&G)...
CascadingParametersDialog.Label.button.createNew.dataset=新建(&W)...
CascadingParametersDialog.Label.cascadingParam.name=级联参数名称(&C):
CascadingParametersDialog.Label.column.displayText=显示文本
CascadingParametersDialog.Label.column.dataSet=数据集
CascadingParametersDialog.Label.column.name=名称
CascadingParametersDialog.Label.column.value=值
CascadingParametersDialog.Label.createNewParam=<创建新参数...>
CascadingParametersDialog.Label.dataSets=数据集(&S):
CascadingParametersDialog.Label.dataType=数据类型(&D)
CascadingParametersDialog.Label.defaultValue=默认值(&V):
CascadingParametersDialog.Label.displayType=显示类型(&T):
CascadingParametersDialog.Label.formatAs=格式为:
CascadingParametersDialog.Label.group.general=常规
CascadingParametersDialog.Label.group.moreOptions=更多选项
CascadingParametersDialog.Label.group.properties=属性
CascadingParametersDialog.Label.helpText=帮助文本(&H):
CascadingParametersDialog.Label.listLimit=列表限制(&I):
CascadingParametersDialog.Label.NoColumnAvailable=<没有可用的列>
CascadingParametersDialog.Label.param.name=名称(&N):
CascadingParametersDialog.Label.parameters=参数
CascadingParametersDialog.Label.preview=带格式预览
CascadingParametersDialog.Label.groupPromptText=提示文本(&P):
CascadingParametersDialog.Label.parameterPromptText=提示文本(&R):
CascadingParametersDialog.Label.selectDataSet=<选择数据集>
CascadingParametersDialog.Label.selectDisplayColumn=<选择显示列>
CascadingParametersDialog.Label.selectValueColumn=<选择值列>
CascadingParametersDialog.Label.values=值
CascadingParametersDialog.Label.SelectDataSetMode=数据集模式:
CascadingParametersDialog.Radio.Single=单个数据集
CascadingParametersDialog.Radio.Mutli=多个数据集

###########################################################
#CategoryPageGenerator properties

CategoryPageGenerator.TabItem.Attributes=属性

###########################################################
#CellPageGenerator properties

CellPageGenerator.List.Borders=边框
CellPageGenerator.List.CellPadding=填充
CellPageGenerator.List.Font=字体
CellPageGenerator.List.General=常规
CellPageGenerator.TabItem.Highlights=突出显示
CellPageGenerator.TabItem.map=映射

###########################################################
#LabelPageGenerator properties
LabelPageGenerator.TabItem.Highlights=突出显示


###########################################################
#ChoiceSetFactory properties

ChoiceSetFactory.choice.Auto=自动
ChoiceSetFactory.choice.None=无

###########################################################
#CodePageAction properties

CodePageAction.actionText.code=脚本

###########################################################
#ColorBuilder properties

ColorBuilder.text.None=自动

###########################################################
#ColumnPageGenerator properties

ColumnPageGenerator.List.Borders=边框
ColumnPageGenerator.List.CellPadding=单元格边距
ColumnPageGenerator.List.Font=字体
ColumnPageGenerator.List.General=常规
ColumnPageGenerator.TabItem.Highlights=突出显示
ColumnPageGenerator.TabItem.map=映射
ColumnPageGenerator.List.Visibility=可见性

###########################################################
#Commom properties

Commom.ShortDateTime.Fri=五
Commom.ShortDateTime.Mon=一
Commom.ShortDateTime.Sat=六
Commom.ShortDateTime.Sun=日
Commom.ShortDateTime.Thu=四
Commom.ShortDateTime.Tue=二
Commom.ShortDateTime.Wed=三

###########################################################
#Connection Profile Properties
connectionprofile.wizard.title=新建数据源
connectionprofile.wizard.title.connectionprofileselect=选择连接配置文件
connectionprofile.wizard.defaultmessage.connectionprofileselect=选择用于创建数据源的连接配置文件
connectionprofile.wizard.label.connectionprofilestore=连接配置文件存储:
connectionprofile.wizard.label.datasourcename=数据源名称:
connectionprofile.wizard.checkbox.datasourcenameusedefaultdsname=使用默认数据源名称
connectionprofile.wizard.tree.datasourcename=ODA 数据源
connectionprofile.wizard.button.browse=浏览...

###########################################################
#CopyAction properties

CopyAction.text=复制(&C)

###########################################################
#CreatePlaceHolderAction properties

CreatePlaceHolderAction.text=创建模板报表项(&E)...

###########################################################
#CutAction properties

CutAction.text=剪切(&T)
CutAction.trans=剪切元素

###########################################################
#dataBinding properties

dataBinding.label.selectBinding=选择数据绑定:
dataBinding.message.changeDataSet=您将要更改元素的数据绑定。\n\n是否要清除全部现有的数据字段信息?
dataBinding.title.changeDataSet=是否更改数据集？
dataBinding.title=数据绑定

parameterBinding.title=数据集参数绑定



###########################################################
#DataEditPart properties

DataEditPart.Figure.Dafault=数据
DataEditPart.Figure.Expression=表达式

###########################################################
#DataEditPart properties

DestroyEditPart.Message=此报表项的内容已损坏。如要继续使用此报表，请先删除此项目。此操作可能会导致报表设计文件进一步损坏和/或致使 report designer 无响应。

###########################################################
#DataPageGenerator properties

DataPageGenerator.List.Bookmark=书签
DataPageGenerator.List.Borders=边框
DataPageGenerator.List.Duplicates=重复项
DataPageGenerator.List.Expression=表达式
DataPageGenerator.List.Format=格式
DataPageGenerator.List.formatDateTime=日期时间格式
DataPageGenerator.List.formatNumber=数值格式
DataPageGenerator.List.formatString=字符串格式
DataPageGenerator.List.General=常规
DataPageGenerator.List.Highlights=突出显示
DataPageGenerator.List.HyperLink=超级链接
DataPageGenerator.List.Margin=边距
DataPageGenerator.List.Padding=填充
DataPageGenerator.List.Section=分页符
DataPageGenerator.List.TOC=目录
DataPageGenerator.List.Visibility=可见性
DataPageGenerator.TabItem.map=映射

###########################################################
#dataset properties

dataset.edit=编辑数据集 - {0}

dataset.editor.settings=Settings
dataset.editor.settings.dataFetchSetting.errorNumberFormat=Please enter a number larger than zero for row fetch limit
dataset.editor.settings.dataFetchSetting=Data Fetch Setting
dataset.editor.settings.cachePreference.errorNumberFormat=请为缓存行大小输入一个大于零的数。
dataset.editor.settings.cachePreference=缓存首选项
dataset.editor.computedColumns=计算列
dataset.editor.dataSource.Tooltip=查看/更改数据源
dataset.editor.dataSource=数据源
dataset.editor.error.columnOrAliasNameAlreadyUsed=新的列名称或别名 ({0}) 已经由索引 {1} 处的列使用。
dataset.editor.error.computedColumnNameAlreadyUsed=The new computed column name ({0}) is already used as column alias of column ({1}) in Output Columns.
dataset.editor.error.duplicateParameterName=重复的参数名称
dataset.editor.error.emptyName=名称不能为空白。 
dataset.editor.error.missingComputedColumnExpression=计算列 {0} 的表达式不能为空或空白。
dataset.editor.error.missingComputedColumnName=计算列名称不能为空或空白。
dataset.editor.error.noDataSource=没有可用于数据集的数据源 {0}，请在属性视图的“数据源”条目中选择数据源。
dataset.editor.error.noEditorsFound=未找到可用于数据集的编辑器 {0}。
dataset.editor.error.noInputParameterDefaultValue=输入参数 {0} 应具有非空默认值。
dataset.editor.error.title=警告
dataset.editor.error.unsupportedDataSet=不支持的数据集类型 - {0}。
dataset.editor.error.validationParameter=输入参数 [{0}] 具有空值。是否要保留为空?
dataset.editor.filters=筛选器
dataset.editor.label.selectDataSource=选择数据源(&D):
dataset.editor.outputColumns=输出列
dataset.editor.parameters=参数
dataset.editor.preview=预览结果
dataset.editor.outputparameters=预览输出参数
dataset.editor.title.alias=别名
dataset.editor.title.columnName=列名称
dataset.editor.title.dataType=数据类型
dataset.editor.title.defaultValue=默认值
dataset.editor.title.direction=方向
dataset.editor.title.displayName=显示名称
dataset.editor.title.expression=表达式
dataset.editor.title.helpText=帮助文本
dataset.editor.title.isInput=输入
dataset.editor.title.isNullable=允许 Null
dataset.editor.title.isOptional=可选
dataset.editor.title.isOutput=输出
dataset.editor.title.name=名称
dataset.editor.title.operator=运算符
dataset.editor.title.type=类型
dataset.editor.title.value1=值 1
dataset.editor.title.value2=值 2
dataset.editor.historybar.backward=后退
dataset.editor.historybar.forward=前进
dataset.editor.historybar.to=到
dataset.error.noDataSources=没有可用的数据源。\n请添加数据源。
dataset.error.dataSourceMissing=缺少此数据集的数据源。
dataset.error.title.noDataSources=无可用数据源。
dataset.message.create=创建新数据集。
dataset.new.defaultName=数据集
dataset.new=新建数据集
dataset.join.new=新建联接数据集
dataset.resultset.preview.tooltip=预览查询结果
dataset.outputparameters.preview.tooltip=预览输出参数
dataset.wizard.label.datasetName=数据集名称(&M):
dataset.wizard.label.datasetType=数据集类型(&T):
dataset.wizard.label.dataSource=数据源(&S):

###########################################################
#DataSetBasePage properties

DataSetBasePage.tooltip=名称不能为空

###########################################################
#JointDataSetPage properties

JointDataSetPage.pageName=联接数据集
JointDataSetPage.page.detail=从每端选择一个数据集和一个列以定义联接。
JointDataSetPage.button.innerJoin=内联接(&I)
JointDataSetPage.button.leftJoin=左外联接(&L)
JointDataSetPage.button.rightJoin=右外联接(&R)
JointDataSetPage.button.fullJoin=完全外部联接(&F)
JointDataSetPage.joinType=联接类型
JointDataSetPage.error.nodataset.title=未找到数据集
JointDataSetPage.error.nodataset.right=未找到右数据集
JointDataSetPage.error.nodataset.left=未找到左数据集
JointDataSetPage.pageDescription=定义联接数据集
JointDataSetPage.query=查询

###########################################################
#DataSetComputedColumnsPage properties

DataSetComputedColumnsPage.ComputedColumns.Tooltip=定义计算列。 
DataSetComputedColumnsPage.description=定义计算列
DataSetComputedColumnsPage.duplicatedName=重复的列名称
DataSetComputedColumnsPage.toolTipText.Down=计算列下移
DataSetComputedColumnsPage.toolTipText.Up=计算列上移
DataSetComputedColumnsPage.toolTipText.Remove=删除计算列
DataSetComputedColumnsPage.toolTipText.New=New Computed Column
DataSetComputedColumnsPage.toolTipText.Edit=Edit Computed Column
DataSetComputedColumnsPage.title.ComputedColumnInputDialog=Computed Column

###########################################################
#DataSetFiltersPage properties

DataSetFiltersPage.description=定义筛选器:
DataSetFiltersPage.exception.msg.operator.notSupport=不支持此运算符: 
DataSetFiltersPage.Filter.Tooltip=使用 BIRT 表达式筛选数据行。
DataSetFiltersPage.toolTipText.Down=筛选器下移
DataSetFiltersPage.toolTipText.Up=筛选器上移
DataSetFiltersPage.toolTipText.Remove=删除筛选器
DataSetFiltersPage.toolTipText.New=新建筛选器
DataSetFiltersPage.toolTipText.Edit=编辑筛选器
DataSetFiltersPage.title.FilterInputDialog=筛选器
DataSetFiltersPage.messages.selectVauleUnavailable=值列表对给定的表达式不可用

###########################################################
#DataSetNodeProvider properties

DataSetNodeProvider.menu.text=编辑

###########################################################
#DataSetParametersPage properties

DataSetParametersPage.description=定义输入参数:
DataSetParametersPage.Filter.Tooltip=将参数传入或传出数据集。 
DataSetParameterBindingInputDialog.Title=编辑数据集参数绑定
DataSetParametersPage.ErrorTitle.InvalidInput=无效输入
DataSetParameterBindingInputDialog.Label.Name=参数名称:
DataSetParametersPage.ErrorMessage.CanootBeNull=该值不能为 null。
DataSetParameterBindingInputDialog.Label.DataType=数据类型:
DataSetParameterBindingInputDialog.Label.Value=值:
DataSetParametersPage.Prompt.new=<此处为新参数...>
DataSetParametersPage.default.None=不适用
DataSetParametersPage.reportParam.None=无
DataSetParameterPage.cell.linkToSalarParameter=链接到报表参数
DataSetParameterPage.title.ParameterInputDialog=参数
DataSetParameterPage.toolTipText.New=新建参数
DataSetParameterPage.toolTipText.Edit=编辑参数
DataSetParameterPage.toolTipText.Remove=删除参数
DataSetParameterPage.toolTipText.Up=参数上移
DataSetParameterPage.toolTipText.Down=参数下移

###########################################################
#PropertyBindingpage properties
PropertyBindingPage.datasource.property.empty=ODA 扩展没有为此数据源定义公共属性
PropertyBindingPage.dataset.property.empty=ODA 扩展没有为此数据集定义公共属性
PropertyBindingPage.dataset.queryText=查询文本(&Q)
PropertyBindingPage.property.tooltip=为运行时定义属性绑定
PropertyBindingPage.button.tooltip=打开表达式生成器以输入 {0} 值

###########################################################
#DataSetProcess properties

DataSetProcess.action.Delete=删除数据集
DataSetProcess.action.Edit=编辑数据集
DataSetProcess.action.Preview=预览
DataSetProcess.text.DisplayName=DataSet
DataSetProcess.text.Prefix=以下数据集使用此数据源:
DataSetProcess.text.Show=显示该数据集的数据集编辑器页。
DataSetProcess.text.Suffix=是否确定删除此元素？

###########################################################
#datasource properties

datasource.action.edit=编辑
datasource.edit=编辑数据源 - {0}
datasource.new.defaultName=数据源
datasource.new=新建数据源
datasource.wizard.label.dataSourceName=数据源名称(&M):
datasource.wizard.label.datasources=从以下列表中的数据源类型创建
datasource.wizard.label.datasources=从以下列表中的数据源类型创建
datasource.wizard.label.connectionfile=从配置文件存储中的连接配置文件创建
datasource.wizard.message.selectType=为新数据源提供所有设置，或选择预定义的连接配置文件
datasource.wizard.title.select=选择数据源类型，或选择连接配置文件
datasource.editor.property=属性绑定

###########################################################
#DataSourceProcess properties

DataSourceProcess.action.Delete=删除数据源
DataSourceProcess.action.Edit=编辑数据源
DataSourceProcess.text.DisplayName=DataSource
DataSourceProcess.text.Prefix=以下数据集使用此数据源
DataSourceProcess.text.Show=显示数据源编辑器页  
DataSourceProcess.text.Suffix=是否确定删除此元素？

###########################################################
#DataSourceSelectionPage properties

DataSourceSelectionPage.ScriptDataSource.DisplayName=脚本化数据源

###########################################################
#DataSourcesSlotOutlineProcess properties

DataSourcesSlotOutlineProcess.action.New=新建数据源

###########################################################
#datatypes properties

datatypes.any=任何
datatypes.auto=自动
datatypes.dateTime=日期时间
datatypes.decimal=小数
datatypes.float=浮点
datatypes.integer=整型
datatypes.string=字符串

###########################################################
#DataView properties

DataView.defaultText.noDataView=数据视图不可用

###########################################################
#DataViewTreeViewerPage properties

DataViewTreeViewerPage.tooltip.DoubleClickToEdit=双击以进行编辑
DataViewTreeViewerPage.tooltip.DragToInsertColumn=拖动插入列 
DataViewTreeViewerPage.tooltip.DragToInsertDataSetColumns=拖动以插入所有数据集列 
DataViewTreeViewerPage.tooltip.DragToInsertParameter=拖动以插入报表参数; 

###########################################################
#DebugUtil properties

DebugUtil.importProject.fail="导入现有项目失败。"

###########################################################
#DecorationFieldEditor properties

DecorationFieldEditor.text.Linethrough=删除线
DecorationFieldEditor.text.Overline=上划线
DecorationFieldEditor.text.Underline=下划线

###########################################################
#DefaultNodeProvider properties

DefaultNodeProvider.Dlg.Confirm=是否确实要将其删除？
DefaultNodeProvider.ParameterGroup.ConfirmMessage=您即将删除参数组。如果您要删除参数组，将会删除该组内的所有参数。是否继续？
DefaultNodeProvider.ParameterGroup.ConfirmTitle=确认参数组删除
DefaultNodeProvider.Tree.Body=正文
DefaultNodeProvider.Tree.Clients=\\ 具有以下客户端
DefaultNodeProvider.Tree.ColumnHedings=列标题
DefaultNodeProvider.Tree.Components = 报表项
DefaultNodeProvider.Tree.DataSets=数据集
DefaultNodeProvider.Tree.DataSources=数据源
DefaultNodeProvider.Tree.Detail=明细数据
DefaultNodeProvider.Tree.Footer=页脚
DefaultNodeProvider.Tree.Groups=组
DefaultNodeProvider.Tree.Header=页眉
DefaultNodeProvider.Tree.Images=嵌入图像
DefaultNodeProvider.Tree.Invalid=无效节点
DefaultNodeProvider.Tree.MasterPages=主页
DefaultNodeProvider.Tree.PageSetup=页面设置
DefaultNodeProvider.Tree.Parameters=报表参数
DefaultNodeProvider.Tree.Reference=找到参考
DefaultNodeProvider.Tree.Scratch=便笺簿
DefaultNodeProvider.Tree.Styles=样式
DefaultNodeProvider.Tree.Themes=主题
DefaultNodeProvider.WarningDialog.Title=警告
DefaultNodeProvider.WarningDialog.EmptyList=没有可供插入的元素。

###########################################################
#DeleteAction properties

DeleteAction.text=删除(&D)
DeleteAction.trans=删除元素

###########################################################
#DeleteColumnAction properties

DeleteColumnAction.actionMsg.delete=删除(&D)

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.actionMsg.deleteGroup=删除组(&G)

###########################################################
#DeleteListGroupAction properties

DeleteListGroupAction.actionMsg.deleteGroup=删除组(&G)

###########################################################
#DeleteRowAction properties

DeleteRowAction.actionMsg.delete=删除(&D)

###########################################################
#designer properties

designer.preview.browserTitle=预览
designer.preview.preference.browser.autoSave=预览前自动保存
designer.preview.preference.browser.browse=浏览(&B)...
designer.preview.preference.browser.currentBrowsers=当前外部 Web 浏览器适配器(&U):
designer.preview.preference.browser.description=该选择确定用于预览 BIRT 报表的 web 浏览器。\n如果仅配置了一个浏览器适配器，则无法更改\n选择。
designer.preview.preference.browser.details=选择浏览器程序
designer.preview.preference.browser.program=自定义浏览器命令(&S):
designer.preview.preference.browser.svg=启用 SVG 图表(&E)
designer.preview.preference.masterpagecontent=启用主页内容(&M)
designer.preview.preference.browser.useExternal=始终使用外部浏览器(&W)
designer.preview.preference.elementname.columnwidth=125
designer.preview.preference.elementname.customname.Enabled=true
designer.preview.preference.elementname.customname=默认名称
designer.preview.preference.elementname.defaultname.Enabled=false    
designer.preview.preference.elementname.defaultname=元素名称
designer.preview.preference.elementname.description.Enabled=false
designer.preview.preference.elementname.description=说明
designer.preview.preference.elementname.Enabled=true 
designer.preview.preference.locale.description=选择区域设置(&C):
designer.preview.preference.resultset.sqldatasetpage.group.title=查询页面
designer.preview.preference.resultset.previewpage.group.title=预览页面
designer.preview.preference.resultset.maxNoOfSchema.description=要显示的最大架构数(&S):
designer.preview.preference.resultset.maxNoOfTable.description=每个架构中要显示的最大表数(&T):
designer.preview.preference.resultset.maxNoOfSchema.errormessage=请为最大架构数输入一个介于 0 和 {0} 之间的数。
designer.preview.preference.resultset.maxNoOfTable.errormessage=请在每个架构中分别为最大表数输入一个介于 0 和 {0} 之间的数。
designer.preview.preference.resultset.maxrow.description=要显示的最大行数(&R):
designer.preview.preference.resultset.maxrow.errormessage=请为最大行数输入一个介于 1 和 {0} 之间的数。
designer.preview.preference.server.description=Internal Application Server 配置。该服务器由 \nBIRT Report Designer Preview Framework 内部使用。
designer.preview.preference.server.hostDescription=本地计算机的主机名或 IP 地址。将其留空以自动\n确定(&H)。
designer.preview.preference.server.note=注：
designer.preview.preference.server.portDescription=要监听的服务器端口。设置为 0 以动态分配(&P)。
designer.preview.preference.server.requireRestart=如果该服务器已在运行，这些首选项只有在\n重新启动后才生效。
designer.preview.previewaction.label.webviewer=在 Web 查看器中查看报表
designer.preview.previewaction.label=以 {0} 格式查看报表
designer.preview.previewaction.ErrorMessage=由于未安装或未找到 iText，不支持 PDF 生成。
designer.preview.previewaction.ErrorMessage.title=警告

###########################################################
#DesignerActionBarContributor properties

DesignerActionBarContributor.element.group=插入组(&G)
DesignerActionBarContributor.element.InsertColumnLeft=在左侧插入列(&L)
DesignerActionBarContributor.element.InsertColumnRight=在右侧插入列(&R)
DesignerActionBarContributor.element.InsertRowAbove=在上方插入行(&A)
DesignerActionBarContributor.element.InsertRowBelow=在下方插入行(&B)
DesignerActionBarContributor.element.merge=合并单元格(&M)
DesignerActionBarContributor.element.split=拆分单元格(&S)
designerActionBarContributor.menu.data-newdataset=新建数据集(&E)
designerActionBarContributor.menu.data-newdatasource=新建数据源(&O)
DesignerActionBarContributor.menu.data=数据(&D)
DesignerActionBarContributor.menu.element-EditGroup=编辑组(&E)
DesignerActionBarContributor.menu.element-LayoutMode=布局模式(&D)
DesignerActionBarContributor.menu.element-showRuler=显示标尺(&R)
DesignerActionBarContributor.menu.element.editDataBinding=编辑数据绑定(&B)
DesignerActionBarContributor.menu.element=元素(&L)
DesignerActionBarContributor.menu.format=格式
DesignerActionBarContributor.menu.insert=插入(&I)
DesignerActionBarContributor.menu.page=页面(&G)
DesignerActionBarContributor.menu.style-rule-apply=应用样式(&P)
DesignerActionBarContributor.menu.style-rule-edit=编辑样式(&D)
DesignerActionBarContributor.style.new=新建样式(&N)...
DesignerActionBarContributor.menu.data-NewParameter=新报表参数(&P)

###########################################################
#DesignerOutlinePage properties

DesignerOutlinePage.action.Delete=删除选择
DesignerOutlinePage.action.Hide=隐藏页眉和页脚
DesignerOutlinePage.action.Redo=恢复
DesignerOutlinePage.action.Undo=撤消
DesignerOutlinePage.menu.Filters=筛选器

###########################################################
#Content outline page switch action
ContentOutlinePage.action.text.reportOutline=Switch to XML source outline
ContentOutlinePage.action.text.reportXMLSourceOutline=Switch to report outline

###########################################################
#DesignerPaletteFactory properties

DesignerPaletteFactory.categoryName.reportItems=报表项
DesignerPaletteFactory.elementLabel.data=数据
DesignerPaletteFactory.elementLabel.grid=网格
DesignerPaletteFactory.elementLabel.image=图像
DesignerPaletteFactory.elementLabel.label=标签
DesignerPaletteFactory.elementLabel.list=列表
DesignerPaletteFactory.elementLabel.tabel=表
DesignerPaletteFactory.elementLabel.text=文本
DesignerPaletteFactory.elementName.data=数据
DesignerPaletteFactory.elementName.grid=网格
DesignerPaletteFactory.elementName.image=图像
DesignerPaletteFactory.elementName.label=标签
DesignerPaletteFactory.elementName.list=列表
DesignerPaletteFactory.elementName.table=表
DesignerPaletteFactory.elementName.text=文本
DesignerPaletteFactory.elementName.textdata=动态文本
DesignerPaletteFactory.toolTip.dataReportItem=插入数据集列或表达式结果。
DesignerPaletteFactory.toolTip.gridReportItem=插入行/列布局以直观排列其它项。
DesignerPaletteFactory.toolTip.imageReportItem=从文件或 URL 中插入图像。
DesignerPaletteFactory.toolTip.labelReportItem=插入一段静态文本。 
DesignerPaletteFactory.toolTip.listReportItem=在页眉/详细信息/页脚区段中插入数据集行的灵活格式表示
DesignerPaletteFactory.toolTip.multiLineDataReportItem=从文件、数据集列或表达式结果中插入文本块（纯文本/HTML/RTF）。
DesignerPaletteFactory.toolTip.tableReportItem=在页眉/详细信息/页脚区段中插入数据集行的列表示
DesignerPaletteFactory.toolTip.textDataReportItem=插入带有可选 CLOB 数据表达式的文本块
DesignerPaletteFactory.toolTip.textReportItem=插入文本块（纯文本/HTML）和可选嵌入表达式。

###########################################################
#DimensionBuilderDialog properties

DimensionBuilderDialog.LabelMeasure=度量:
DimensionBuilderDialog.LabelUnit=单位:
DimensionBuilderDialog.Title=维生成器

###########################################################
#DNDUtil properties

DNDUtil.trans.copy=复制元素
DNDUtil.trans.cut=移动元素

###########################################################
#DuplicatesPage properties

DuplicatesPage.Check.HideDuplicates=隐藏重复项
DuplicatesPage.Group.Repeat=复制（重复）
DuplicatesPage.Group.RepeatonPage=复制（页上重复）
DuplicatesPage.Label.RepeatInfo=隐藏与上一数据行相同的值。
DuplicatesPage.Label.RepeatOnPage.1=隐藏与上一行相同的值，
DuplicatesPage.Label.RepeatOnPage.2=\\ 但始终在每个新页顶部显示该值。
DuplicatesPage.Label.ResetonGroup=对以下组进行重置
DuplicatesPage.Radio.Repeat=重复
DuplicatesPage.Radio.RepeatonPage=页上重复

###########################################################
#EditAction properties

EditAction.text=编辑

###########################################################
#EditGroupAction properties

EditGroupAction.stackMsg.editGroup=编辑组

###########################################################
#EditGroupAction properties
InsertGroupHeaderFooterAction.stackMsg.editGroup=插入组页眉/页脚
InsertGroupHeaderFooterAction.Text.Header=页眉
InsertGroupHeaderFooterAction.Text.Footer=页脚

###########################################################
#DeleteGroupAction properties

DeleteGroupAction.stackMsg.deleteGroup=删除组

###########################################################
#EditLabelAction properties

EditLabelAction.text=编辑

###########################################################
#Element properties

Element.Cell.colSpan=列跨度:
Element.Cell.column=列:
Element.Cell.drop=放置(&D):
Element.Cell.height=高度:
Element.Cell.rowSpan=行跨度:
Element.Cell.slot.content=内容:
Element.Cell.verticalAlign=垂直对齐:
Element.Cell.width=宽度:
Element.Column.alignment=对齐:
Element.Column.repeat=重复:
Element.Column.width=宽度(&W):
Element.Column.suppressDuplicates=抑制重复
Element.Container.slot.reportItems=报表项:
Element.Data.action=操作:
Element.Data.helpText=帮助文本:
Element.Data.helpTextID=帮助文本关键字
Element.TextData.valueExpr=值表达式(&V):
Element.DataSet.afterClose.toolTip=仅在关闭数据集之后调用。
Element.DataSet.afterClose=关闭后:
Element.DataSet.afterOpen.toolTip=仅在打开数据集之后调用。
Element.DataSet.afterOpen=打开后:
Element.DataSet.beforeClose.toolTip=仅在关闭数据集之前调用。
Element.DataSet.beforeClose=关闭前:
Element.DataSet.beforeOpen.toolTip=仅在打开数据集之前调用。
Element.DataSet.beforeOpen=打开前:
Element.DataSet.cachedMetaData=缓存元数据:
Element.DataSet.columnHints=列提示:
Element.DataSet.computedColumns=计算列:
Element.DataSet.dataSource=数据源:
Element.DataSet.filter=筛选器:
Element.DataSet.inputParameters=输入参数:
Element.DataSet.onFetch.toolTip=仅在从数据集获取数据行之前调用。
Element.DataSet.onFetch=获取中:
Element.DataSet.outputParameters=输出参数:
Element.DataSet.paramBindings=参数绑定:
Element.DataSet.resultSet=结果集:
Element.DataSource.afterClose.toolTip=仅在关闭数据源之后调用。
Element.DataSource.afterClose=关闭后:
Element.DataSource.afterOpen.toolTip=仅在打开数据源之后调用。
Element.DataSource.afterOpen=打开后:
Element.DataSource.beforeClose.toolTip=仅在关闭数据源之前调用。
Element.DataSource.beforeClose=关闭前:
Element.DataSource.beforeOpen.toolTip=仅在打开数据源之前调用。
Element.DataSource.beforeOpen=打开前:
Element.ExtendedItem.extension=扩展名:
Element.ExtendedItem.extensionName=扩展名:
Element.FreeForm.slot.reportItems=报表项:
Element.GraphicMasterPage.columns=列:
Element.GraphicMasterPage.columnSpacing=列间距:
Element.GraphicMasterPage.slot.contents=内容:
Element.Grid.slot.columns=列:
Element.Grid.slot.row=行:
Element.Image.action=操作:
Element.Image.altText=替代文本(&A):
Element.Image.altTextID=替代文本关键字
Element.Image.helpText=帮助文本:
Element.Image.helpTextID=帮助文本关键字
Element.Image.imageName=图像名称:
Element.Image.scale=比例: 
Element.Image.size=大小:
Element.Image.source=源:
Element.Image.typeExpr=类型表达式:
Element.Image.uri=uri:
Element.Image.valueExpr=值表达式:
Element.JdbcDataSource.dataSource=数据源:
Element.JdbcDataSource.driver=驱动程序:
Element.JdbcDataSource.password=密码:
Element.JdbcDataSource.url=URL:
Element.JdbcDataSource.userName=用户名:
Element.JdbcSelectDataSet.getStatement.toolTip=返回查询的自定义 SQL 语句。
Element.JdbcSelectDataSet.getStatement=获取语句:
Element.JdbcSelectDataSet.statement=语句:
Element.Label.action=操作:
Element.Label.helpText=帮助文本:
Element.Label.helpTextID=帮助文本关键字
Element.Label.text=文本:
Element.Label.textID=文本关键字(&T):
Element.Line.orientation=方向:
Element.List.slot.columnHeader=列题头:
Element.List.slot.detail=详细资料:
Element.List.slot.footer=页脚:
Element.List.slot.group=组:
Element.List.slot.header=页眉:
Element.ListGroup.slot.footer=页脚:
Element.ListGroup.slot.header=页眉:
Element.Listing.filter=筛选器:
Element.Listing.onFinish.toolTip=在从此元素的数据集内读取最后一行之后调用，但在创建页脚区段之前。
Element.Listing.onFinish=完成时:
Element.Listing.onRow.toolTip=为从此元素的数据集中检索出的每行调用，但在为该行创建内容之前。
Element.Listing.onRow=遇到行时:
Element.Listing.onStart.toolTip=在打开数据集之后、在创建题头区段之前并且在从此元素的数据集检索首行之前调用。 
Element.Listing.onStart=启动时:
Element.Listing.pageBreakInterval=分页符间隔(&P):
Element.Listing.sorting=排序:
Element.ListingGroup.filter=筛选器:
Element.ListingGroup.groupName=名称
Element.ListingGroup.interval=间隔:
Element.ListingGroup.intervalRange=间隔范围:
Element.ListingGroup.keyExpr=关键字表达式
Element.ListingGroup.onFinish.toolTip=在从此元素的数据集内读取最后一行之后调用，但在创建页脚区段之前。
Element.ListingGroup.onFinish=完成时:
Element.ListingGroup.onRow.toolTip=对从此元素的数据集检索的每行调用，但是在为该行创建任何内容之前调用。
Element.ListingGroup.onRow=遇到行时:
Element.ListingGroup.onStart.toolTip=在打开数据集之后、在创建题头区段之前并且在从此元素的数据集检索首行之前调用。
Element.ListingGroup.onStart=启动时:
Element.ListingGroup.pageBreakAfter=对象后面的分页符:
Element.ListingGroup.pageBreakBefore=对象前面的分页符:
Element.ListingGroup.sort=排序:
Element.ListingGroup.sortDirection=排序方向:
Element.ListingGroup.toc=目录:
Element.MasterPage.bottomMargin=下边距:
Element.MasterPage.columns=列:
Element.MasterPage.columnSpacing=列间距:
Element.MasterPage.height=高度(&E):
Element.MasterPage.leftMargin=左边距:
Element.MasterPage.margin=边距:
Element.MasterPage.orientation=方向(&O):
Element.MasterPage.rightMargin=右边距:
Element.MasterPage.slot.contents=内容:
Element.MasterPage.topMargin=上边距:
Element.MasterPage.type=类型(&T):
Element.MasterPage.width=宽度(&W):
Element.Module.author=作者(&U):
Element.Module.base=基本:
Element.Module.colorPalette=调色板:
Element.Module.comments=备注(&C):
Element.Module.configVars=配置变量:
Element.Module.createdBy=创建者(&C):
Element.Module.description=描述(&D):
Element.Module.descriptionID=说明关键字:
Element.Module.helpGuide=帮助指南:
Element.Module.images=图像:
Element.Module.includeLibraries=包含库:
Element.Module.includeResource=资源文件(&R):
Element.Module.includeScripts=包含脚本:
Element.Module.initialize.toolTip=开始执行报表时调用。
Element.Module.initialize=初始化:
Element.Module.theme=主题(&M)
Element.Module.title=标题(&T):
Element.Module.titleID=标题关键字:
Element.Module.units=单位(&S):
Element.MultiLineData.contentTypeExpr=内容类型表达式:
Element.MultiLineData.valueExpr=值表达式:
Element.OdaDataSet.privateDriverDesignState=私有驱动程序设计状态:
Element.OdaDataSet.privateDriverProperties=私有驱动程序属性:
Element.OdaDataSet.publicDriverProperties=公共驱动程序属性:
Element.OdaDataSet.queryScript.toolTip=TBD:
Element.OdaDataSet.queryScript=脚本:
Element.OdaDataSet.queryText=查询:
Element.OdaDataSet.resultSetName=结果集名称:
Element.OdaDataSet.type=类型:
Element.OdaDataSource.driverName=驱动程序名称:
Element.OdaDataSource.privateDriverProperties=私有驱动程序属性:
Element.OdaDataSource.publicDriverProperties=公共驱动程序属性:
Element.Parameter.helpText=帮助文本:
Element.Parameter.helpTextID=帮助文本关键字
Element.Parameter.hidden=隐藏:
Element.ParameterGroup.helpText=帮助文本:
Element.ParameterGroup.helpTextID=帮助文本关键字
Element.ParameterGroup.slot.parameters=参数:
Element.ParameterGroup.startExpanded=开始展开:
Element.ReportDesign.afterCloseDoc.toolTip=仅在生成阶段关闭报表文档文件之后调用。
Element.ReportDesign.afterCloseDoc=关闭文档后:
Element.ReportDesign.afterFactory.toolTip=在生成阶段结束时并且在关闭报表文档（如果有）之后调用。这是生成阶段调用的最后一个方法。
Element.ReportDesign.afterFactory=出厂后:
Element.ReportDesign.afterOpenDoc.toolTip=仅在生成阶段打开报表文档之后调用。
Element.ReportDesign.afterOpenDoc=打开文档后:
Element.ReportDesign.afterRender.toolTip=开始展示时间操作后调用。
Element.ReportDesign.afterRender=实施后:
Element.ReportDesign.beforeCloseDoc.toolTip=仅在生成阶段关闭报表文档文件之前调用。
Element.ReportDesign.beforeCloseDoc=关闭文档前:
Element.ReportDesign.beforeFactory.toolTip=在生成阶段开始时，在 initialize( ) 方法之后并且在打开报表文档（如果有）之前调用。
Element.ReportDesign.beforeFactory=出厂前:
Element.ReportDesign.beforeOpenDoc.toolTip=仅在生成阶段打开报表文档之前调用。
Element.ReportDesign.beforeOpenDoc=打开文档前:
Element.ReportDesign.beforeRender.toolTip=开始展示时间操作前调用。
Element.ReportDesign.beforeRender=实施前:
Element.ReportDesign.displayName=显示名称(&Y): 
Element.ReportDesign.eventHandlerClass=事件处理程序类(&V):
Element.ReportDesign.iconFile=预览图像(&P): 
Element.ReportDesign.refreshRate=刷新率:
Element.ReportElement.comments=备注(&C):
Element.ReportElement.customXml=自定义 XML:
Element.ReportElement.displayName=显示名称:
Element.ReportElement.displayNameID=显示名称关键字:
Element.ReportElement.extends=扩展:
Element.ReportElement.javaClass=Java 类:
Element.ReportElement.name=名称(&N):
Element.ReportElement.propertyMask=属性掩码:
Element.ReportElement.style=样式(&T):
Element.ReportItem.bookmark=书签(&B):
Element.ReportItem.dataSet=数据集:
Element.ReportItem.height=高度(&H):
Element.ReportItem.onCreate.toolTip=在生成阶段创建该元素时执行。
Element.ReportItem.onCreate=创建时:
Element.ReportItem.onRender.toolTip=在展示阶段准备该元素以便绘制时执行。
Element.ReportItem.onRender=实施时:  
Element.ReportItem.paramBindings=参数绑定:
Element.ReportItem.toc=目录(&T):
Element.ReportItem.visibility=可见性:
Element.ReportItem.width=宽度(&W):
Element.ReportItem.x=X:
Element.ReportItem.y=Y:
Element.Row.bookmark=书签:
Element.Row.height=高度(&H):
Element.Row.slot.cell=单元格:
Element.Row.visibility=可见性:
Element.ScalarParameter.alignment=对齐:
Element.ScalarParameter.allowBlank=允许为空:
Element.ScalarParameter.allowNull=允许 Null:
Element.ScalarParameter.concealValue=隐藏值:
Element.ScalarParameter.controlType=控件类型(&C):
Element.ScalarParameter.dataType=数据类型(&D):
Element.ScalarParameter.defaultValue=默认值:
Element.ScalarParameter.dynamicList.dataSetName=数据集名称:
Element.ScalarParameter.dynamicList.labelExpr=标签表达式:
Element.ScalarParameter.dynamicList.valueExpr=值表达式:
Element.ScalarParameter.dynamicList=动态列表:
Element.ScalarParameter.format=格式:
Element.ScalarParameter.selectionList.fixedOrder=固定顺序:
Element.ScalarParameter.selectionList.mustMatch=必须匹配:
Element.ScalarParameter.selectionList.selectionList=选择列表:
Element.ScalarParameter.selectionList=选择列表:
Element.ScalarParameter.promptTextID=文本关键字(&T):
Element.ScriptDataSet.close.toolTip=关闭数据集。
Element.ScriptDataSet.close=关闭:
Element.ScriptDataSet.describe.toolTip=说明结果集。
Element.ScriptDataSet.describe=说明:
Element.ScriptDataSet.fetch.toolTip=创建、填写并返回类型“数据行”对象。 
Element.ScriptDataSet.fetch=获取:
Element.ScriptDataSet.open.toolTip=打开数据集。
Element.ScriptDataSet.open=打开:
Element.ScriptDataSource.close.toolTip=断开与数据源的连接。 
Element.ScriptDataSource.close=关闭:
Element.ScriptDataSource.open.toolTip=建立至数据源的连接。 
Element.ScriptDataSource.open=打开:
Element.SimpleMasterPage.floatingFooter=浮动脚注(&F)
Element.SimpleMasterPage.footerHeight=页脚高度(&F):
Element.SimpleMasterPage.headerHeight=页眉高度(&H):
Element.SimpleMasterPage.showFooterOnLast=在最后一行显示脚注(&H)
Element.SimpleMasterPage.showHeaderOnFirst=在第一行显示题头(&S)
Element.SimpleMasterPage.slot.pageFooter=页脚:
Element.SimpleMasterPage.slot.pageHeader=页眉:
Element.Style.background.attachment=附件(&A):
Element.Style.background.color=背景色(&B):
Element.Style.background.image=背景图像(&G):
Element.Style.background.positionX=水平位置(&H):
Element.Style.background.positionY=垂直位置(&V):
Element.Style.background.repeat=重复(&R):
Element.Style.background=背景:
Element.Style.border.bottom.color=下(&M):
Element.Style.border.bottom.style=下(&B):
Element.Style.border.bottom.width=下:
Element.Style.border.fillColor=边框填充色:
Element.Style.border.hmiddle.color=边框水平中间色:
Element.Style.border.hmiddle.style=边框水平中间样式:
Element.Style.border.hmiddle.width=边框水平中间宽度:
Element.Style.border.left.color=左(&F):
Element.Style.border.left.style=左(&L):
Element.Style.border.left.width=左(&E):
Element.Style.border.right.color=右(&H):
Element.Style.border.right.style=右(&R)
Element.Style.border.right.width=右(&I):
Element.Style.border.top.color=上(&P):
Element.Style.border.top.style=上(&T):
Element.Style.border.top.width=上(&O):
Element.Style.border.vmiddle.color=边框垂直中间色:
Element.Style.border.vmiddle.style=边框垂直中间样式:
Element.Style.border.vmiddle.width=边框垂直中间宽度:
Element.Style.border=边框:
Element.Style.box=框:
Element.Style.canShrink=可以缩小(&S)
Element.Style.color=颜色(&C):
Element.Style.display=显示(&Y):
Element.Style.font.family=字体(&F):
Element.Style.font.size=大小(&Z):
Element.Style.font.style=样式(&T):
Element.Style.font.textLineThrough=删除线(&L)
Element.Style.font.textOverline=上划线(&O)
Element.Style.font.textUnderline=下划线(&U)
Element.Style.font.variant=字体变体:
Element.Style.font.weight=粗细(&W):
Element.Style.font=字体(&F):
Element.Style.format.dateTime=日期/时间:
Element.Style.format.number.align=格式数值对齐:
Element.Style.format.number=编号:
Element.Style.format.string=字符串:
Element.Style.format=格式:
Element.Style.highlight.rules=突出显示规则:
Element.Style.highlight.testExpr=突出显示测试表达式:
Element.Style.letterSpacing=字母间距(&T):
Element.Style.lineHeight=行高(&N):
Element.Style.map.rules=映射规则:
Element.Style.map.testExpr=映射测试表达式:
Element.Style.margin.bottom=下(&O):
Element.Style.margin.left=左(&E):
Element.Style.margin.right=右(&I)
Element.Style.margin.top=上(&P):
Element.Style.masterPage=主页(&M):
Element.Style.orphans=孤行(&O):
Element.Style.padding.bottom=下(&B):
Element.Style.padding.left=左(&L):
Element.Style.padding.right=右(&R)
Element.Style.padding.top=上(&T):
Element.Style.padding=填充:
Element.Style.pageBreakAfter=之后(&A):
Element.Style.pageBreakBefore=之前(&B):
Element.Style.pageBreakInside=内部(&I):
Element.Style.section=区域:
Element.Style.showIfBlank=如果为空白则显示(&W)
Element.Style.text.align=文本对齐(&X):
Element.Style.text.indent=文本缩进(&X):
Element.Style.text.transform=文本转换(&R):
Element.Style.text=文本:
Element.Style.verticalAlign=垂直对齐(&V):
Element.Style.whiteSpace=空白(&H):
Element.Style.widows=窗口(&D):
Element.Style.wordSpacing=字间距(&W):
Element.Table.caption=标题:
Element.Table.captionID=标题关键字:
Element.Table.repeatHeader=重复标题:
Element.Table.slot.columnHeader=列题头:
Element.Table.slot.columns=列:
Element.Table.slot.detail=详细资料:
Element.Table.slot.footer=页脚:
Element.Table.slot.group=组:
Element.Table.slot.header=页眉:
Element.TableGroup.slot.footer=页脚:
Element.TableGroup.slot.header=页眉:
Element.Text.content=内容:
Element.Text.contentID=内容关键字(&K):
Element.Text.contentType=内容类型(&P):
Element.TemplateElement.name=名称(&N)

###########################################################
#EmbeddedImageNodeProvider properties

EmbeddedImageNodeProvider.action.New=新建嵌入图像

###########################################################
#EmbeddedImagesNodeProvider properties

EmbeddedImagesNodeProvider.action.New=新建嵌入图像

###########################################################
#EmptyEditPart properties

EmptyEditPart.Msg.EmptyLib=库未包含可见元素。要添加可见元素，将项目从选项板拖动到库大纲视图，或者使用大纲视图中的插入菜单。
EmptyEditPart.Msg.NonVisual=选择了不可见元素。

###########################################################
#error properties

error.duplicateName=新名称与同一名称空间中的现有名称重复。
error.emptyName=数据源名称不能为空。
error.invalidName=名称“{0}”无效，因为它包含字符“.”。

###########################################################
#ExceptionHandler properties

ExceptionHandler.Label.ErrorCode=错误代码
ExceptionHandler.Label.ErrorMessage=错误消息
ExceptionHandler.Label.PluginId=Plug-in ID:
ExceptionHandler.Label.PluginName=Plug-in Name:
ExceptionHandler.Label.PluginProvider=Plug-in Provider:
ExceptionHandler.Label.PluginVersion=Version:
ExceptionHandler.Label.UnknownPlugin=Unknown plug-in
ExceptionHandler.Meesage.UnexceptedExceptionOccur=发生意外的内部例外。详情请参阅日志。
ExceptionHandler.Message.BirtExceptionOccur=发生 BIRT 例外。
ExceptionHandler.Message.CausedBy=Caused by {0}。
ExceptionHandler.Message.FileNotFound=File not found:
ExceptionHandler.Message.OutOfMemory=内存不足。
ExceptionHandler.Message.PartInitError=部分初始化失败。
ExceptionHandler.Message.SemanticFail=语义检查失败。
ExceptionHandler.Message.UnexceptedExceptionOccur=出现内部例外。详情请参阅日志文件。
ExceptionHandler.Message.UnknownHost=未知主机:
ExceptionHandler.Title.Error=错误
ExceptionHandler.Title.FileNotFound=未找到文件。
ExceptionHandler.Title.PartInitError=部分初始化错误。
ExceptionHandler.Title.UnknownHost=未知主机

###########################################################
#ExportAction properties

ExportAction.actionMsg.export=导出

###########################################################
#ExportToLibraryAction properties

ExportToLibraryAction.action.text=导出到库(&E)...
ExportToLibraryAction.Button.Cancel=取消
ExportToLibraryAction.Button.No=否
ExportToLibraryAction.Button.Yes=是
ExportToLibraryAction.Dialog.Message=\n目标库可能具有相同的设计元素，是否要覆盖?
ExportToLibraryAction.Dialog.Title=导出元素
ExportToLibraryAction.Message.RememberDecision=记住我的决定。

###########################################################
#LibraryExplorerTreeViewPage tooltips
LibraryExplorerTreeViewPage.toolTips.DragAndDropOutline=拖放到“大纲”视图
LibraryExplorerTreeViewPage.toolTips.DragAndDropLayout=拖放到“布局”编辑器
LibraryExplorerTreeViewPage.toolTips.DragAndDropToOutlineORLayout=拖放到“大纲”视图或“布局”编辑器

###########################################################
#ExpressionBuidler properties

ExpressionBuidler.Dialog.Title=表达式生成器
ExpressionBuilder.toolTipText.Button=打开表达式生成器

###########################################################
#ExpressionBuilder properties

ExpressionBuilder.Label.Category=类别:
ExpressionBuilder.Label.Functions=双击以插入:
ExpressionBuilder.Label.Operators=运算符:
ExpressionBuilder.Label.SubCategory=子类别:
ExpressionBuilder.Message.Prompt=在“表达式”字段中输入一个表达式。浏览可用对象列表并双击对象以将其复制到表达式中。

###########################################################
#ExpressionPropertyDescriptor properties

ExpressionPropertyDescriptor.text.Edit=表达式生成器(&X)...

###########################################################
#ExpressionProvider properties

ExpressionProvider.Category.Context=上下文
ExpressionProvider.Category.BirtObjects=BIRT 函数
ExpressionProvider.Category.DataSets=可用数据集
ExpressionProvider.Category.NativeObjects=本地 JavaScript 函数
ExpressionProvider.Category.ColumnBinding=可用列绑定
ExpressionProvider.Category.Operators=运算符
ExpressionProvider.Category.Parameters=报表参数
ExpressionProvider.Label.All=---全部---
ExpressionProvider.Operator.Add=将两个值相加。
ExpressionProvider.Operator.AddTo=在当前值上加值的快捷方式。
ExpressionProvider.Operator.And=判断两个表达式，并且在两个表达式均为真时返回真值。
ExpressionProvider.Operator.Assign=将一个值设置为与另一个值相等。
ExpressionProvider.Operator.BitAnd=A & B: 返回 A 和 B 的逐位 AND 结果。
ExpressionProvider.Operator.BitOr=A | B: 返回 A 和 B 的逐位 OR 结果。
ExpressionProvider.Operator.Dec=递减该值，然后返回结果。
ExpressionProvider.Operator.DividingFrom=除当前值的快捷方式。
ExpressionProvider.Tooltip.ColumnBinding=引用 
ExpressionProvider.Operator.Divides=将左侧的值除以右侧的值并返回结果。
ExpressionProvider.Operator.Equals=如果这些项相同，则返回真值。
ExpressionProvider.Operator.Greater=A > B: 如果 A 大于 B，则返回真值。
ExpressionProvider.Operator.GreaterEquals=A >= B: 如果 A 大于或等于 B，则返回真值。
ExpressionProvider.Operator.Inc=递增该值，然后返回结果。
ExpressionProvider.Operator.LeftBracket=左括号
ExpressionProvider.Operator.RightBracket=右括号
ExpressionProvider.Operator.Less=A < B: 如果 A 小于 B，则返回真值。
ExpressionProvider.Operator.LessEqual=A <= B: 如果 A 小于或等于 B，则返回真值。
ExpressionProvider.Operator.Mult=将两个值相乘。
ExpressionProvider.Operator.MultTo=乘以当前值的快捷方式。
ExpressionProvider.Operator.Not=!A: A 为假则返回真，A 为真则返回假。
ExpressionProvider.Operator.NotEqual=A <> B: 如果 A 不等于 B，则返回真值。
ExpressionProvider.Operator.Or=判断两个表达式，并且在两个表达式之一（而非全部）为真时返回真值。
ExpressionProvider.Operator.ReturnDec=返回该值，然后递减该值。
ExpressionProvider.Operator.ReturnInc=返回该值，然后递增该值。
ExpressionProvider.Operator.Sub=从另一值中减去一个值。
ExpressionProvider.Operator.SubFrom=从当前值中减值的快捷方式。
ExpressionProvider.Operators.Assignment=赋值
ExpressionProvider.Operators.Comparison=比较
ExpressionProvider.Operators.Computational=计算的
ExpressionProvider.Operators.Logical=逻辑
ExpressionProvider.EditBindings=编辑绑定...
ExpressionProvider.Expression.RowNumName=行数
ExpressionProvider.Expression.RowNumTooltip=返回当前行数的表达式。

###########################################################
#ExpressionValueCellEditor properties

ExpressionValueCellEditor.buildExpressionAction=<构建表达式...>
ExpressionValueCellEditor.selectValueAction=<选择值...>
ExpressionValueCellEditor.title=<选择值...>

###########################################################
#ExtendedEditPart properties

ExtendedEditPart.edit=编辑 {0}

###########################################################
#ExtendedItemPageGenerator properties

ExtendedItemPageGenerator.List.Bookmark=书签
ExtendedItemPageGenerator.List.TOC=目录

###########################################################
#FilterHandleProvider properties

FilterHandleProvider.ColumnName.Value=值
FilterHandleProvider.Label.Filterby=筛选依据:
FilterHandleProvider.Modify.SaveValues=保存值

###########################################################
#filters properties

filters.empty.columnName=表达式不能为空。
filters.error.title=无效输入。
filters.operators.any=任意
filters.operators.between=介于
filters.operators.bottomN=下 (n) 项
filters.operators.bottomPercent=下 (n) 百分比
filters.operators.equal=等于 
filters.operators.false=为假
filters.operators.greaterThan=大于
filters.operators.greaterThanEqual=大于或等于
filters.operators.lessThan=小于
filters.operators.lessThanEqual=小于或等于
filters.operators.like=类似
filters.operators.notBetween=不介于
filters.operators.notEqual=不等于
filters.operators.notNull=不为 NULL
filters.operators.null=为 NULL
filters.operators.topN=顶部项目
filters.operators.topPercent=顶部百分比
filters.operators.true=为真
filters.prompt.new=<此处为新筛选...>

###########################################################
#FixTableLayoutCalculator properties

FixTableLayoutCalculator.Error.CannotParse=无法分析输入值。

###########################################################
#FlowMoveChildCommand properties

FlowMoveChildCommand.transLabel.moveElement=移动元素

###########################################################
#FontPreferencePage properties

FontPreferencePage.displayname.Title=字体
FontPreferencePage.label.fontDecoration=修饰:
FontPreferencePage.text.Preview=示例预览
FontPreferencePage.text.PreviewContent=AaBbYyZz

###########################################################
#FontSizeBuilder properties

FontSizeBuilder.displayname.Auto=自动

###########################################################
#FormatBuilder properties

FormatBuilder.Title=格式生成器

###########################################################
#FormatDateTimeAttributePage properties

FormatDateTimeAttributePage.Trans.SetDateTimeFormat = 设置日期时间格式。

###########################################################
#FormatDateTimePage properties

FormatDateTimePage.label.custom.settings.label=格式示例（单击下面要复制的一项，然后进行修改）:
FormatDateTimePage.label.custom.settings=自定义设置
FormatDateTimePage.label.format.code=格式代码:
FormatDateTimePage.label.format.page=格式为(&F):
FormatDateTimePage.label.general.preview.group=带格式预览
FormatDateTimePage.label.guide.text=Please enter as: MM/DD/YYYY hh:mm:ss AM/PM
FormatDateTimePage.label.preview.dateTime=要预览的日期时间: 
FormatDateTimePage.label.preview.group=预览
FormatDateTimePage.label.preview.label=带格式预览:
FormatDateTimePage.label.table.column.format.name=示例格式
FormatDateTimePage.label.table.column.format.result=示例格式结果
FormatDateTimePage.label.table.column.format.code=Example code
FormatDateTimePage.preview.invalid.dateTime=要预览的日期时间无效
FormatDateTimePage.preview.invalid.formatCode=无效格式代码

###########################################################
#FormatDateTimePreferencePage properties

FormatDateTimePreferencePage.formatDateTime.title=日期时间格式

###########################################################
#FormatNumberAttributePage properties

FormatNumberAttributePage.Trans.SetNumberFormat = 设置数值格式。

###########################################################
#FormatNumberPage properties

FormatNumberPage.currency.symbol.none=无符号
FormatNumberPage.label.currency.settings=货币设置
FormatNumberPage.label.custom.preview.group=预览
FormatNumberPage.label.custom.preview.label=带格式预览:
FormatNumberPage.label.custom.settings.lable=格式示例 （单击下面要复制的一项，然后进行修改）:
FormatNumberPage.label.custom.settings=自定义设置
FormatNumberPage.label.decimal.places=小数位: 
FormatNumberPage.label.fixed.settings=固定设置
FormatNumberPage.label.format.code=格式代码:
FormatNumberPage.label.format.number.page=格式为(&F):
FormatNumberPage.label.general.preview.group=带格式预览
FormatNumberPage.label.negative.numbers=负数: 
FormatNumberPage.label.percent.settings=百分比设置
FormatNumberPage.label.preview.number=要预览的数值: 
FormatNumberPage.label.scientific.settings=科学记数设置
FormatNumberPage.label.symbol.position=符号位置: 
FormatNumberPage.label.symbol=符号: 
FormatNumberPage.label.table.column.format.code=示例格式
FormatNumberPage.label.table.column.format.result=示例格式结果
FormatNumberPage.label.use1000sSeparator=使用千位分隔符
FormatNumberPage.label.useLeadingZero=使用前导零
FormatNumberPage.preview.invalidFormatCode=无效格式代码
FormatNumberPage.preview.invalidNumber=要预览的数值无效
FormatNumberPage.symblePos.after=之后
FormatNumberPage.symblePos.before=之前

###########################################################
#FormatNumberPreferencePage properties

FormatNumberPreferencePage.formatNumber.title=数值格式

###########################################################
#FormatPreferencePage properties

FormatPreferencePage.displayname.Title=格式

###########################################################
#FormatStringAttributePage properties

FormatStringAttributePage.Trans.SetStringFormat = 设置字符串格式。

###########################################################
#FormatStringPage properties

FormatStringPage.default.preview.text=我的字符串
FormatStringPage.label.custom.preview.label=带格式预览:
FormatStringPage.label.custom.settings.label=格式示例（单击下面要复制的一项，然后进行修改）:
FormatStringPage.label.customSettings=自定义设置
FormatStringPage.label.format.code=格式代码:
FormatStringPage.label.formatStringAs=格式为(&F):
FormatStringPage.label.preview.group=预览
FormatStringPage.label.preview.string=要预览的字符串: 
FormatStringPage.label.previewWithFormat=带格式预览
FormatStringPage.label.table.collumn.exampleFormatCode=示例格式
FormatStringPage.label.table.collumn.exampleFormatResult=示例格式结果
FormatStringPage.previewText.invalidFormatCode=无效格式代码

###########################################################
#FormatStringPreferencePage properties

FormatStringPreferencePage.formatString.title=字符串格式

###########################################################
#FormPage properties

FormPage.Button.Add=添加(&A)
FormPage.Button.AddWithDialog=添加(&A)...
FormPage.Button.Delete=删除(&L)
FormPage.Button.Down=下移(&N)
FormPage.Button.Edit=编辑(&D)
FormPage.Button.EditWithDialog=编辑(&D)...
FormPage.Button.Up=上移(&U)
FormPage.Menu.ModifyProperty=修改属性
FormPage.toolTipText.Up=上移
FormPage.toolTipText.Down=下移

###########################################################
#GeneralInsertMenuAction properties

GeneralInsertMenuAction.text.Data=数据(&D)
GeneralInsertMenuAction.text.DynamicText=动态文本(&Y)
GeneralInsertMenuAction.text.Grid=网格(&G)
GeneralInsertMenuAction.text.Image=图像(&I)
GeneralInsertMenuAction.text.Label=标签(&L)
GeneralInsertMenuAction.text.List=列表(&S)
GeneralInsertMenuAction.text.Table=表(&B)
GeneralInsertMenuAction.text.Text=文本(&T)

###########################################################
#GeneralPreferencePage properties

GeneralPreferencePage.errorMsg.duplicate.styleName=重复的样式名称。
GeneralPreferencePage.label.styleNameDuplicate=样式名称“{0}”已存在，请选择另一个名称
GeneralPreferencePage.label.customStyle=自定义样式(&C)
GeneralPreferencePage.label.predefinedStyle=预定义样式(&P)
GeneralPreferencePage.label.nameEmpty=不允许空样式名称。 

###########################################################
#GridEditPart properties

GridEditPart.GUIDEHANDLE_TEXT = 网格

###########################################################
#GridFigure properties

GridFigure.BORDER_TEXT=网格

###########################################################
#GridPageGenerator properties

GridPageGenerator.List.Bookmark=书签
GridPageGenerator.List.Borders=边框
GridPageGenerator.List.Font=字体
GridPageGenerator.List.General=常规
GridPageGenerator.List.Margin=边距
GridPageGenerator.List.Section=分页符
GridPageGenerator.List.TOC=目录
GridPageGenerator.List.Visibility=可见性
GridPageGenerator.TabItem.Highlights=突出显示
GridPageGenerator.TabItem.map=映射

###########################################################
#GridProvider properties

GridProvider.action.text=插入行

###########################################################
#GroupDialog properties

GroupDialog.Dialog.GroupDetail=组详细资料
GroupDialog.Dialog.TOC=TOC 项目表达式(&T):
GroupDialog.DialogTitle.NoData=初始化失败
GroupDialog.DialogTitle.SemanticCheckFailed=语义检查失败
GroupDialog.ErrorMesaage.IllegalGroup=此组非法。
GroupDialog.ErrorMessage.NoData=没有可用的数据行。
GroupDialog.Label.FilterSorting=筛选器和排序
GroupDialog.Label.GroupOn=分组依据(&G):
GroupDialog.Label.HeaderFooter=页眉和页脚
GroupDialog.Label.IncludeFooter=包含组页脚(&F)
GroupDialog.Label.IncludeHeader=包含组页眉(&H)
GroupDialog.Label.Interval=间隔(&I):
GroupDialog.PageBreakBefore=之前:
GroupDialog.PageBreakAfter=之后:
GroupDialog.PageBreakInside=内部:
GroupDialog.Label.IntervalBase=对间隔使用固定基值(&U):
GroupDialog.Label.Name=名称(&N):
GroupDialog.Label.Range=区域(&R):
GroupDialog.Tab.Binding=数据绑定
GroupDialog.Tab.Filter=筛选器
GroupDialog.Tab.Sorting=排序
GroupDialog.RepeatHeader=重复页眉
GroupDialog.Title.Edit=编辑组
GroupDialog.Title.New=新建组
GroupDialog.PageBreak=分页符
GroupDialog.buttion.HideDetail=隐藏详细信息(&D)
GroupDialog.toolTipText.openExprButton=打开表达式生成器

###########################################################
#GroupHandleProvider properties

GroupHandleProvider.Label.Groups=组列表:

###########################################################
#GroupProvider properties

GroupProvider.action.text=编辑组

###########################################################
#GuiExtensionManager properties

GuiExtensionManager.label.name=扩展项
GuiExtensionManager.tooltip.insert=插入 {0}

###########################################################
#HighlightHandleProvider properties

HighlightHandleProvider.text.Preview=AaBbCcYyZz  (font size = 

###########################################################
#HighlightRuleBuilderDialog properties

HighlightRuleBuilderDialog.choice.ValueOfThisDataItem=此数据项的值
HighlightRuleBuilderDialog.text.AND=AND
HighlightRuleBuilderDialog.text.Any=任意
HighlightRuleBuilderDialog.text.BackgroundColor=背景色:
HighlightRuleBuilderDialog.text.Between=介于
HighlightRuleBuilderDialog.text.Color=颜色:
HighlightRuleBuilderDialog.text.Condition=如果以下条件为真: 
HighlightRuleBuilderDialog.text.Default=自动
HighlightRuleBuilderDialog.text.ET=等于
HighlightRuleBuilderDialog.text.False=为假
HighlightRuleBuilderDialog.text.Font=字体:
HighlightRuleBuilderDialog.text.Format=则应用以下格式: 
HighlightRuleBuilderDialog.text.GE=大于或等于
HighlightRuleBuilderDialog.text.GT=大于
HighlightRuleBuilderDialog.text.LE=小于或等于
HighlightRuleBuilderDialog.text.Like=类似
HighlightRuleBuilderDialog.text.LT=小于
HighlightRuleBuilderDialog.text.NE=不等于
HighlightRuleBuilderDialog.text.NotBetween=不介于
HighlightRuleBuilderDialog.text.NotNull=不为 NULL
HighlightRuleBuilderDialog.text.Null=为 NULL
HighlightRuleBuilderDialog.text.Preview=预览:
HighlightRuleBuilderDialog.text.PreviewContent=AaBbCcYyZz
HighlightRuleBuilderDialog.text.Size=大小:
HighlightRuleBuilderDialog.text.Title=添加/编辑突出显示规则
HighlightRuleBuilderDialog.text.True=为真
HighlightRuleBuilderDialog.tooltip.ExpBuilder=单击以调用表达式生成器。
HighlightRuleBuilderDialog.tooltip.Bold=粗体
HighlightRuleBuilderDialog.tooltip.Italic=斜体
HighlightRuleBuilderDialog.tooltip.Underline=下划线
HighlightRuleBuilderDialog.tooltip.Text_Line_Through=文本删除线
HighlightRuleBuilderDialog.text.applyStyle=使用样式中的格式:
HighlightRuleBuilderDialog.displayText.None=无

###########################################################
#HighlightsPage properties

HighlightsPage.Button.Add=添加(&A)...
HighlightsPage.Button.Delete=删除(&D)
HighlightsPage.Dialog.EditHighlight=编辑突出显示
HighlightsPage.Dialog.NewHighlight=新建突出显示
HighlightsPage.Label.Highlights=突出显示列表:
HighlightsPage.TableColumn.Condition=条件
HighlightsPage.TableColumn.Preview=预览:
HighlightsPage.trans.Add=添加突出显示规则
HighlightsPage.trans.Delete=删除突出显示规则
HighlightsPage.trans.Edit=编辑突出显示规则
HighlightsPage.trans.MoveDown=下移突出显示规则
HighlightsPage.trans.MoveUp=上移突出显示规则
HighlightsPage.toolTipText.MoveDown=突出显示规则下移
HighlightsPage.toolTipText.MoveUp=突出显示规则上移

###########################################################
#HighlightsPreferencePage properties

HighlightsPreferencePage.displayname.Condition=条件
HighlightsPreferencePage.displayname.Preview=预览
HighlightsPreferencePage.displayname.Title=突出显示
HighlightsPreferencePage.text.Add=添加(&A)...
HighlightsPreferencePage.text.Delete=删除(&L)
HighlightsPreferencePage.text.Description=突出显示列表:
HighlightsPreferencePage.text.Edit=编辑(&D)...
HighlightsPreferencePage.toolTipText.Up=突出显示上移
HighlightsPreferencePage.toolTipText.Down=突出显示下移

###########################################################
#HyperlinkBuilder properties

HyperlinkBuilder.Column.Parameters=参数
HyperlinkBuilder.DrillThroughStep1=第 1 步: 选择目标报表 
HyperlinkBuilder.DrillThroughStep2=第 2 步: 选择目标定位标记 
HyperlinkBuilder.DrillThroughStep3=第 3 步: 创建与目标书签匹配的链接表达式
HyperlinkBuilder.DrillThroughStep4=第 4 步: 显示目标报表 
HyperlinkBuilder.DrillThroughStep5=Step 5: Select a format for target report
HyperlinkBuilder.ParameterRequired=必需
HyperlinkBuilder.Column.Values=值
HyperlinkBuilder.DialogTitle=超级链接选项
HyperlinkBuilder.ErrorMessage.InvalidReport=无效的报表设计。
HyperlinkBuilder.ErrorMessage.ReportReqired=必须指定报表文件。
HyperlinkBuilder.DrillThroughTargetBookmark=目标书签
HyperlinkBuilder.DrillThroughLinkExpression=链接表达式:
HyperlinkBuilder.Label.Bookmark=书签:
HyperlinkBuilder.Label.Format=格式:
HyperlinkBuilder.Label.LinkedExpression=链接表达式:
HyperlinkBuilder.DrillThroughTargetToc=目标报表中的目录项
HyperlinkBuilder.DrillThroughSamewindow=同一窗口
HyperlinkBuilder.DrillThroughNewWindow=新窗口
HyperlinkBuilder.Label.Location=位置:
HyperlinkBuilder.Label.Parameters=报表参数:
HyperlinkBuilder.Label.Report=报表:
HyperlinkBuilder.Label.SelectType=选择超级链接类型:
HyperlinkBuilder.DrillThroughHtml=HTML
HyperlinkBuilder.Label.Target=目标:
HyperlinkBuilder.Radio.Bookmark=内部书签
HyperlinkBuilder.DrillThroughPdf=PDF
HyperlinkBuilder.Radio.DrillThrough=追溯
HyperlinkBuilder.ReportDesignButton=报表设计:
HyperlinkBuilder.ReportDocumentButton=报表文档:
HyperlinkBuilder.Radio.None=无链接
HyperlinkBuilder.Radio.Uri=URI
HyperlinkBuilder.BrowseForFile=浏览文件
HyperlinkBuilder.OpenExpression=打开表达式生成器
HyperlinkBuilder.FileNameError.Title=错误
HyperlinkBuilder.FileNameError.Message=选择的文件无效。
HyperlinkBuilder.TargetReportFormat=Format the target report in:

###########################################################
#HyperLinkPage properties

HyperLinkPage.Label.LnikTo=链接至(&L):
HyperLinkPage.Label.None=无
HyperLinkPage.Menu.Save=更改超级链接
HyperLinkPage.toolTipText.Button=打开超级链接选项

###########################################################
#I18nPage properties

I18nPage.text.Note=注：要设置本地化，请选择报表，然后在属性编辑器的“资源”选项卡上设置资源文件名称。

###########################################################
#ImageBuilder properties

ImageBuilder.Button.Dynamic=动态图像(&D)
ImageBuilder.Button.Import=添加图像(&A)...
ImageBuilder.Button.Insert=插入(&S)
ImageBuilder.Button.Preview=预览(&P)
ImageBuilder.Button.Remove=删除
ImageBuilder.ButtonBrowser=浏览...
ImageBuilder.Chooser.Title=打开图像文件
ImageBuilder.DialogTitle.Edit=编辑图像项
ImageBuilder.DialogTitle.ImportFailed=导入失败
ImageBuilder.DialogTitle.LoadingFailed=图像加载失败
ImageBuilder.DialogTitle.New=新建图像项
ImageBuilder.ErrorMessage.FileLoaded=已加载此文件。
ImageBuilder.ErrorMessage.LoadingFailed=无法正确加载图像。
ImageBuilder.BrowserResourceDialog.Title=浏览图像文件
ImageBuilder.BrowserResourceDialog.Message=Select the image files from Resource Path Folder
ImageBuilder.ErrorMessage.OutOfMemory=该图像太大，无法装入内存。
ImageBuilder.FileDialog.FilterMessage=支持的图像文件
ImageBuilder.Label.Binding=绑定(&B)
ImageBuilder.Label.EmbededImage=嵌入图像(&E)
ImageBuilder.Label.EnterExpr=输入动态图像表达式(&N):
ImageBuilder.Label.EnterUri=输入 URI(&N):
ImageBuilder.Label.Open=表达式生成器(&X)...
ImageBuilder.Label.SelectFrom=选择图片自:
ImageBuilder.ResourceFileType=Image file in resource folder
ImageBuilder.Label.URI=&URI
ImageBuilder.Label.EnterResourceFile=输入资源文件(&N):

###########################################################
#ImageEditPart properties

ImageEditPart.trans.editImage=更改图像

###########################################################
#ImagePageGenerator properties

ImagePageGenerator.List.AltText=Alt 文本
ImagePageGenerator.List.Bookmark=书签
ImagePageGenerator.List.Borders=边框
ImagePageGenerator.List.General=常规
ImagePageGenerator.List.HyperLink=超级链接
ImagePageGenerator.List.Reference=引用
ImagePageGenerator.List.Section=分页符
ImagePageGenerator.List.TOC=目录
ImagePageGenerator.List.Visibility=可见性

###########################################################
#ImportCSSStyleAction properties

ImportCSSStyleAction.text=导入 CSS 样式...

###########################################################
#ImportLibraryAction properties

ImportLibraryAction.Error.CannotBeEmpty=名称空间不能为空。
ImportLibraryAction.Error.HasBeenUsed=此名称空间已经在使用。
ImportLibraryAction.Error.HasDot=名称空间不应包含'.'
ImportLibraryAction.Message.ImportSuccessfully=库 {0} 已导入。
ImportLibraryAction.Message=是否要在报表设计中使用此库?
ImportLibraryAction.Namespace=名称空间:
ImportLibraryAction.Prefix=前缀:
ImportLibraryAction.Title.ImportSuccessfully=导入成功
ImportLibraryAction.Dialog.Titile=使用库
ImportLibraryAction.Dialog.Message=选择要包括在报表中的库。 

###########################################################
#ImportLibraryDialog properties

ImportLibraryDialog.Title=使用库

###########################################################
#ImportValueDialog properties

ImportValueDialog.Label.SelectColumn=选择列(&C):
ImportValueDialog.Label.SelectDataSet=选择数据集(&D):
ImportValueDialog.Label.SelectValue=选择或输入要添加的值(&S)
ImportValueDialog.Title=导入值

###########################################################
#IncludeDetailAction properties

IncludeDetailAction.actionMsg.includeDetail=细节(&D)

###########################################################
#IncludeFooterAction properties

IncludeFooterAction.actionMsg.includeFooter=页脚(&F)

###########################################################
#IncludeHeaderAction properties

IncludeHeaderAction.actionMsg.includeHeader=页眉(&H)

###########################################################
#IncludeListDetailAction properties

IncludeListDetailAction.actionMsg.includeDetail=包含详细资料

###########################################################
#IncludeListFooterAction properties

IncludeListFooterAction.actionMsg.includeFooter=包含页脚

###########################################################
#IncludeListHeaderAction properties

IncludeListHeaderAction.actionMsg.includeHeader=包含页眉

###########################################################
#IncludeTableGroupFooterAction properties

IncludeTableGroupFooterAction.actionMsg.includeFooter=组页脚

###########################################################
#IncludeTableGroupHeaderAction properties

IncludeTableGroupHeaderAction.actionMsg.includeHeader=组页眉

###########################################################
#InputParameterDailog properties

InputParameterDailog.dialog.title.required=所需的参数 - 必须具有值
InputParameterDailog.dialog.title=输入参数
InputParameterDailog.parameter.noparameter=没有与此报表相关联的参数。
InputParameterDialog.ErrorMessage.InvalidFile=报表包含错误。
InputParameterDailog.parameter.null=空值
InputParameterDialog.ErrorTitle.Error=错误

###########################################################
#InsertAction properties

InsertAction.text=插入元素

###########################################################
#InsertColumnAction properties

InsertColumnAction.actionMsg.insert=插入

###########################################################
#InsertColumnLeftAction properties

InsertColumnLeftAction.actionMsg.columnToLeft=在左侧插入列(&L)

###########################################################
#InsertColumnRightAction properties

InsertColumnRightAction.actionMsg.columnToRight=在右侧插入列(&R)

###########################################################
#InsertExpressionMenuAction properties

InsertExpressionMenuAction.text.Expression=表达式...

###########################################################
#InsertGroupAction properties

InsertGroupAction.actionMsg.group=插入组(&N)
InsertGroupAction.stackMsg.addGroup=添加组

###########################################################
#InsertGroupActionFactory properties

InsertGroupActionFactory.label.insertGroup=插入组(&N)

###########################################################
#InsertInLayoutAction properties

InsertInLayoutAction.action.text=在布局中插入

###########################################################
#InsertListGroupAction properties

InsertListGroupAction.actionMsg.insertGroup=插入组
InsertListGroupAction.stackMsg.insertListGroup=插入列表组

###########################################################
#InsertPasteColumnAction properties

InsertPasteColumnAction.text=插入复制的列(&S)

###########################################################
#InsertPositionGroupAction properties

InsertPositionGroupAction.Label.Above=在上面(&A)
InsertPositionGroupAction.Label.Below=在下面(&B)
InsertPositionGroupAction.Label.Into=到

###########################################################
#InsertRowAboveAction properties

InsertRowAboveAction.actionMsg.rowAbove=在上面(&A)

###########################################################
#InsertRowAction properties

InsertRowAction.actionMsg.insert=插入(&I)

###########################################################
#InsertRowBelowAction properties

InsertRowBelowAction.actionMsg.rowBelow=在下面(&B)

###########################################################
#IReportGraphicConstants properties

IReportGraphicConstants.ImageType.All=所有图像文件 (*.bmp,*.JPG,*.JPEG,*.GIF,*.TIF,*.PNG,*.ICO)
IReportGraphicConstants.ImageType.Bmp=位图文件 (*.bmp)
IReportGraphicConstants.ImageType.Gif=GIF 文件 (*.GIF)
IReportGraphicConstants.ImageType.Icon=图标文件 (*.ICO)
IReportGraphicConstants.ImageType.Jpg=JPEG 文件 (*.JPG,*.JPEG)
IReportGraphicConstants.ImageType.Png=PNG 文件 (*.PNG)
IReportGraphicConstants.ImageType.Tif=TIF 文件 (*.TIF)

###########################################################
#JSDocumentProvider properties

JSDocumentProvider.Content.Default=新内容
JSDocumentProvider.document.newName=新内容

###########################################################
#JSEditor properties

JSEditor.Button.Reset=重置方法
JSEditor.Display.DefaultText=//JS 脚本编辑器 \n
JSEditor.Display.NoExpression=此元素无方法。
JSEditor.Input.trial=试用版
JSEditor.Text.NoText=无文本

###########################################################
#label properties

label.defaultValue=（默认值）
label.input=输入
label.inputOutput=输入/输出
label.no=否
label.output=输出
label.redo=重复
label.undo=撤消
label.yes=是

###########################################################
#LabelEditPart properties

LabelEditPart.Figure.Default=标签

###########################################################
#LabelPageGenerator properties

LabelPageGenerator.List.Bookmark=书签
LabelPageGenerator.List.Borders=边框
LabelPageGenerator.List.General=常规
LabelPageGenerator.List.HyperLink=超级链接
LabelPageGenerator.List.I18n=定位
LabelPageGenerator.List.Margin=边距
LabelPageGenerator.List.Padding=填充
LabelPageGenerator.List.Section=分页符
LabelPageGenerator.List.TOC=目录
LabelPageGenerator.List.Visibility=可见性

###########################################################
#LayoutEditor properties

LayoutEditor.ErrorMessage.OpenError=打开编辑器时出错。
LayoutEditor.Page.Layout=正常
LayoutEditor.Page.MasterPage=主页
LayoutEditor.Page.Source=XML 源

###########################################################
#LayoutPageAction properties

LayoutPageAction.actionText.layout=布局

###########################################################
#LibrariesNodeProvider properties

LibrariesNodeProvider.DisplayLabel.Libraries=库

###########################################################
#LibraryExplorerView properties

LibraryExplorerView.defaultText.notAvailable=库不可用。

###########################################################
#LibraryExplorerProvider properties
LibraryExplorerProvider.FolderNotExist=首选项中定义的 BIRT 资源文件夹不存在。

###########################################################
#LibraryPage properties

LibraryPage.Label.Namespace=名称空间:
LibraryPage.Label.Path=路径:

###########################################################
#LibraryProvider properties

LibraryProvider.openDefinedLibrary.error.dialog.message=打开定义库错误
LibraryProvider.openDefinedLibrary.error.dialog.title=错误

###########################################################
#ListBandControlFigure properties

ListBandControlFigure.tooltip.GroupFooter=列表组 - 页脚
ListBandControlFigure.tooltip.GroupHeader=列表组 - 页眉
ListBandControlFigure.tooltip.ListDetail=列表 - 详细资料
ListBandControlFigure.tooltip.ListFooter=列表 - 页脚
ListBandControlFigure.tooltip.ListHeader=列表 - 页眉

###########################################################
#ListBandProvider properties

ListBandProvider.action.text=插入组

###########################################################
#ListBandProxy properties

ListBandProxy.list.detail=明细数据
ListBandProxy.list.footer=页脚
ListBandProxy.list.groupFooter=GF
ListBandProxy.list.groupHeader=GH
ListBandProxy.list.header=页眉

###########################################################
#ListContainProcess properties

ListContainProcess.action.New=新建...
ListContainProcess.action.NewRow=新建行
ListContainProcess.action.NewSubSection=新建子区域

###########################################################
#ListEditPart properties

ListEditPart.GUIDEHANDLE_TEXT = 列表

###########################################################
#ListFigure properties

ListFigure.BORDER_TEXT=列表

###########################################################
#ListHandleAdapt properties

ListHandleAdapt.transLabel.insertGroup=插入组

###########################################################
#ListPageGenerator properties

ListPageGenerator.List.Bookmark=书签
ListPageGenerator.List.Borders=边框
ListPageGenerator.List.Font=字体
ListPageGenerator.List.General=常规
ListPageGenerator.List.Section=分页符
ListPageGenerator.List.TOC=目录
ListPageGenerator.List.Visibility=可见性
ListPageGenerator.TabItem.Binding=绑定
ListPageGenerator.TabItem.Filters=筛选器
ListPageGenerator.TabItem.Groups=组
ListPageGenerator.TabItem.Highlights=突出显示
ListPageGenerator.TabItem.map=映射
ListPageGenerator.TabItem.Sorting=排序

###########################################################
#MapPage properties

MapPage.label.add=添加(&A)...
MapPage.label.condition=条件
MapPage.label.delete=删除(&L)
MapPage.label.displayValue=显示值:
MapPage.label.mapList=映射列表:
MapPage.transName.addMapRule=添加映射规则
MapPage.transName.deleteMapRule=删除映射规则
MapPage.transName.editMapRule=编辑映射规则
MapPage.transName.moveDownRule=下移映射规则
MapPage.transName.moveUpMapRule=上移映射规则
MapPage.toolTipText.moveUp=映射规则上移
MapPage.toolTipText.moveDown=映射规则下移

###########################################################
#MapPreferencePage properties

MapPreferencePage.displayname.Condition=条件
MapPreferencePage.displayname.DisplayValue=显示值
MapPreferencePage.displayname.Title=映射
MapPreferencePage.text.Add=添加(&A)...
MapPreferencePage.text.Delete=删除(&L)
MapPreferencePage.text.Description=映射规则:
MapPreferencePage.text.Edit=编辑(&D)...
MapPreferencePage.toolTipText.Up=映射规则上移
MapPreferencePage.toolTipText.Down=映射规则下移

###########################################################
#MapRuleBuilderDialog properties

MapRuleBuilder.DialogTitle.New=新建映射规则
MapRuleBuilder.DialogTitle.Edit=编辑映射规则


MapRuleBuilderDialog.text.Between=介于
MapRuleBuilderDialog.text.Condition=如果以下条件为真(&I): 
MapRuleBuilderDialog.text.Display=则显示以下值(&T): 
MapRuleBuilderDialog.text.ET=等于
MapRuleBuilderDialog.text.GE=大于或等于
MapRuleBuilderDialog.text.GT=大于
MapRuleBuilderDialog.text.LE=小于或等于
MapRuleBuilderDialog.text.Like=类似
MapRuleBuilderDialog.text.LT=小于
MapRuleBuilderDialog.text.NE=不等于
MapRuleBuilderDialog.text.NotBetween=不介于
MapRuleBuilderDialog.text.NotNull=不为 NULL
MapRuleBuilderDialog.text.Null=为 NULL
MapRuleBuilderDialog.text.Title=添加/编辑映射规则

###########################################################
#SortkeyBuilder dialog properties
SortkeyBuilder.DialogTitle.New=新建排序关键字
SortkeyBuilder.DialogTitle.Edit=编辑排序关键字
SortkeyBuilder.DialogTitle.Label.Prompt=输入用作排序依据的关键字:
SortkeyBuilder.DialogTitle.Label.Key=关键字:
SortkeyBuilder.DialogTitle.Label.Direction=方向:
SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=单击以调用表达式生成器
SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=错误

###########################################################
#FilterConditionBuilder dialog properties
FilterConditionBuilder.DialogTitle.New=新建筛选条件
FilterConditionBuilder.DialogTitle.Edit=编辑筛选条件
FilterConditionBuilder.choice.ValueOfThisDataItem=此数据项的值
FilterConditionBuilder.tooltip.ExpBuilder=单击以调用表达式生成器。
FilterConditionBuilder.text.AND=AND
FilterConditionBuilder.text.Condition=输入筛选条件:

###########################################################
#MarignPropertyDescriptor properties

MarignPropertyDescriptor.error.message=输入的值太大。
MarignPropertyDescriptor.error.title=值太大

###########################################################
#MasterPageAction properties

MasterPageAction.actionText.masterPage=主页

###########################################################
#MasterPageGenerator properties

MasterPageGenerator.List.General=常规
MasterPageGenerator.List.Header&Footer=页眉/页脚
MasterPageGenerator.List.Margins=边距

###########################################################
#MasterPagePaletteFactory properties

MasterPagePaletteFactory.Autotext.TotalPageCount=总页数
MasterPagePaletteFactory.Autotext.Author_Page_Date=作者\#，页\#，日期\#
MasterPagePaletteFactory.Autotext.Confidential_Page=机密，页\#
MasterPagePaletteFactory.Autotext.CreatedBy=创建者
MasterPagePaletteFactory.Autotext.CreatedOn=创建时间
MasterPagePaletteFactory.Autotext.Date=日期
MasterPagePaletteFactory.Autotext.Filename=文件名
MasterPagePaletteFactory.Autotext.Label=自动图文集
MasterPagePaletteFactory.Autotext.LastPrinted=上次打印
MasterPagePaletteFactory.Autotext.Page=页面
MasterPagePaletteFactory.Autotext.PageXofY=第 n 页，共 m 页
MasterPagePaletteFactory.AutotextTooltip.TotalPageCount=总页数报表项
MasterPagePaletteFactory.AutotextTooltip.AuthorPageDate=作者#，日期# 报表项
MasterPagePaletteFactory.AutotextTooltip.ConfidentialPage=机密报表项
MasterPagePaletteFactory.AutotextTooltip.CreatedBy=按报表项创建
MasterPagePaletteFactory.AutotextTooltip.CreatedOn=在创建报表项时创建
MasterPagePaletteFactory.AutotextTooltip.Date=日期报表项
MasterPagePaletteFactory.AutoTextTooltip.Filename=文件名报表项
MasterPagePaletteFactory.AutotextTooltip.LastPrinted=上次打印的报表项
MasterPagePaletteFactory.AutotextTooltip.Page=页报表项
MasterPagePaletteFactory.AutotextTooltip.PageXofY=“第 n 页，共 m 页”报表项
MasterPagePaletteFactory.elementLabel.authorPageDate=作者编号，页码，日期
MasterPagePaletteFactory.elementLabel.confidentialPage=机密，页
MasterPagePaletteFactory.elementLabel.createdBy=创建者
MasterPagePaletteFactory.elementLabel.createdOn=创建时间
MasterPagePaletteFactory.elementLabel.date=日期
MasterPagePaletteFactory.elementLabel.fileName=文件名
MasterPagePaletteFactory.elementLabel.lastPrinted=上次打印
MasterPagePaletteFactory.elementLabel.page=页面
MasterPagePaletteFactory.elementLabel.pageOf=第 n 页，共 m 页
MasterPagePaletteFactory.paletteDrawerName.autoText=自动图文集
MasterPagePaletteFactory.ToolTip.Grid=网格报表项
MasterPagePaletteFactory.ToolTip.Text=文本报表项

###########################################################
#MasterPageProcess properties

MasterPageProcess.action.Edit=编辑
MasterPageProcess.action.New=新建
MasterPageProcess.text.CannotDelete=设计仅包含一个主页，无法删除
MasterPageProcess.text.Display=显示页面设置对话框
MasterPageProcess.text.DisplayName=主页

###########################################################
#MergeAction properties

MergeAction.actionMsg.merge=合并单元格(&M)

###########################################################
#ModulePage properties

ModulePage.ErrorMessage.Duplicate=该名称与现有名称重复。
ModulePage.ErrorMessage.WrongExtensionName=名称必须以 ".properties" 结尾。
ModulePage.ErrorMessage.InfoExtensionName=请输入以 ".properties" 结尾的名称。
ModulePage.text.Add=添加(&A)...
ModulePage.text.ExistingFile=现有源文件:
ModulePage.title.AddNewFile=添加新源文件
ModulePage.Resourcefile.Dialog.Title=浏览资源文件
ModulePage.Resourcefile.Dialog.Message=选择资源文件，或者选择文件夹并输入新的文件名创建资源文件。
ModulePage.text.Path=路径:

###########################################################
#MultiPageEditorContributor properties

MultiPageEditorContributor.actionText.sampleAction=示例操作
MultiPageEditorContributor.actionToolTip.sampleActionToolTip=示例操作工具提示
MultiPageEditorContributor.actionToolTipText.sampleActionToolTip=示例操作工具提示
MultiPageEditorContributor.dialogMsg.sampleActionExecuted=执行的示例操作
MultiPageEditorContributor.dialogTitle.infoObjectDesignerPlugIn=Infoobjectdesigner 插件
MultiPageEditorContributor.menuText.editorMenu=编辑器菜单(&M)

###########################################################
#NewLibraryWizard properties

NewLibraryWizard.choicePageTitle.report=库
NewLibraryWizard.displayName.NewReportFileExtension=.rptlibrary
NewLibraryWizard.displayName.NewReportFileNamePrefix=new_library
NewLibraryWizard.error.NoProject=工作区中没有任何打开项目。请选择“文件”->“新建”->“项目”，创建新项目或打开现有项目。
NewLibraryWizard.pageDescription.createNewReport=新建库
NewLibraryWizard.taskName.openFileForEdit=打开文件进行编辑...
NewLibraryWizard.text.ConfirmSwitchPerspective=确认切换透视图
NewLibraryWizard.text.Container=容器 "
NewLibraryWizard.text.CreateReport=新建库
NewLibraryWizard.text.Creating=创建 
NewLibraryWizard.text.DoesNotExist=" 不存在。
NewLibraryWizard.text.OpenFileForEditing=打开文件进行编辑...
NewLibraryWizard.text.SwitchPerspective=此文件类型与 {0} 透视图相关联。是否立即切换至此透视图？
NewLibraryWizard.title.Choose=选择创建库的方式
NewLibraryWizard.title.Error=错误
NewLibraryWizard.title.New=新建库
NewLibraryWizard.title.Report=新建库
NewLibraryWizard.title.ReportWizard=库向导
NewLibraryWizard.title.Template=TemplateChoicePage
NewLibraryWizard.title.WizardPage=WizardPage
NewLibraryWizard.widowTitle.new=新建
NewLibraryWizard.wizardPageTitle.report=库

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=文件系统不区分大小写。存在一个与 ''{0}'' 冲突的现有项目。
NewReportProjectWizard.description=创建新报表项目。
NewReportProjectWizard.errorMessage=创建新报表项目时出现问题。
NewReportProjectWizard.errorOpeningWindow=打开某个窗口时出现问题。
NewReportProjectWizard.internalError=内部错误:{0}
NewReportProjectWizard.javaProject=创建 Java 项目
NewReportProjectWizard.perspSwitchMessage=此项目类型与 {0} 透视图相关联。是否立即切换至此透视图？
NewReportProjectWizard.perspSwitchTitle=确定切换透视图
NewReportProjectWizard.projectSetting=项目设置
NewReportProjectWizard.src=src
NewReportProjectWizard.title=报表项目
NewReportProjectWizard.windowTitle=新建报表项目

###########################################################
#NewReportWizard properties

NewReportWizard.choicePageTitle.report=报表
NewReportWizard.displayName.NewReportFileExtension=.rptdesign
NewReportWizard.displayName.NewReportFileNamePrefix=new_report
NewReportWizard.error.NoProject=工作区中没有任何打开项目。请选择“文件”->“新建”->“项目”，以创建新项目或打开现有项目。
NewReportWizard.pageDescription.createNewReport=创建新报表
NewReportWizard.pageDescription.selectReportTemplate=选择要复制的报表
NewReportWizard.taskName.openFileForEdit=打开文件进行编辑...
NewReportWizard.text.ConfirmSwitchPerspective=确认切换透视图
NewReportWizard.text.Container=容器 "
NewReportWizard.text.CreateReport=新建报表
NewReportWizard.text.Creating=创建 
NewReportWizard.text.DoesNotExist=" 不存在。
NewReportWizard.text.OpenFileForEditing=打开文件进行编辑...
NewReportWizard.text.SelectTemplate=选择要复制的报表
NewReportWizard.text.SwitchPerspective=此文件类型与 {0} 透视图相关联。是否立即切换至此透视图？
NewReportWizard.title.Choose=选择如何创建报表
NewReportWizard.title.Error=错误
NewReportWizard.title.New=新建报表
NewReportWizard.title.Report=新建报表
NewReportWizard.title.ReportWizard=报表向导
NewReportWizard.title.Template=TemplateChoicePage
NewReportWizard.title.WizardPage=WizardPage
NewReportWizard.widowTitle.new=新建


###########################################################
#NewResourceFileDialog properties

NewResourceFileDialog.label.NewFile=新文件名:
NewResourceFileDialog.ErrorMessage=文件名必须以 .properties 结尾
NewResourceFileDialog.ErrorMessageInvalid=文件名无效

###########################################################
#ProjectFileDialog properties

ProjectFileDialog.ErrorMessage=文件必须是文件，而不是目录。
ProjectFileDialog.Title=选择项目文件
ProjectFileDialog.Message=选择当前项目中的文件。

###########################################################
#NewSectionDialog properties

NewSectionDialog.displayname.Container=容器
NewSectionDialog.displayname.Data=数据
NewSectionDialog.displayname.Grid=网格
NewSectionDialog.displayname.Image=图像
NewSectionDialog.displayname.Label=标签
NewSectionDialog.displayname.Line=线条
NewSectionDialog.displayname.List=列表
NewSectionDialog.displayname.Rectangle=矩形
NewSectionDialog.displayname.Table=表
NewSectionDialog.displayname.Text=文本
NewSectionDialog.text.Prefix=可用区域:
NewSectionDialog.title.insertElement=插入元素
NewSectionDialog.Title=插入元素

###########################################################
#NewTemplateWizard properties

NewTemplateWizard.displayName.NewReportFileNamePrefix=new_template
NewTemplateWizard.pageDescription.createNewTemplate=创建新的报表模板
NewTemplateWizard.text.CreateReport=创建新模板
NewTemplateWizard.text.Creating=创建
NewTemplateWizard.text.OpenFileForEditing=打开模板文件进行编辑...
NewTemplateWizard.title.New=新模板
NewTemplateWizard.title.Report=新建报表
NewTemplateWizard.title.Template=新模板
NewTemplateWizard.title.WizardPage=WizardPage

###########################################################
#NoneAction properties

NoneAction.text=无

###########################################################
#OutputColumnDefnPage properties

OutputColumnDefnPage.description=输入取数脚本生成的输出列的定义: 
OutputColumnDefnPage.OutputColumns.Tooltip=查看并定义数据行中的列 

###########################################################
#OutputColumnPage properties

OutputColumnPage.OutputColumns.Tooltip=查看并定义数据行中的列 
OutputColumnPage.toolTipText.Edit=编辑输出列
OutputColumnPage.title.OutputColumnInputDialog=输出列

###########################################################
#OutputColumnsPage properties

OutputColumnsPage.description=定义输出列:

###########################################################
#PageBreakPreferencePage properties

PageBreakPreferencePage.displayname.Title=分页符

###########################################################
#PageSetAction properties

PageSetAction.text.code=脚本(&S)
PageSetAction.Text.EditCode=编辑脚本(&S)...
PageSetAction.text.layout=布局(&L)
PageSetAction.text.master=主(&M)
PageSetAction.text.normal=正常(&N)
PageSetAction.text.preview=预览(&P)

###########################################################
#PageSetupOutlineProcess properties

PageSetupOutlineProcess.action.Edit=编辑页面设置
PageSetupOutlineProcess.action.New=新建主页
PageSetupOutlineProcess.text.Display=显示页面设置对话框
PageSetupOutlineProcess.text.Switch=切换至页面主编辑器

###########################################################
#ParameterDialog properties

ParameterDialog.Boolean.False=假
ParameterDialog.Boolean.True=真
ParameterDialog.Button.ChangeFormat=更改(&G)...
ParameterDialog.Button.CreateDataSet=新建(&W)...
ParameterDialog.Button.ImportValue=导入值(&U)...
ParameterDialog.Button.RemoveDefault=删除默认值
ParameterDialog.Button.SetDefault=设为默认值(&A)
ParameterDialog.CheckBox.AllowBlank=允许空白值(&B)
ParameterDialog.CheckBox.AllowNull=允许空值(&V)
ParameterDialog.CheckBox.DoNotEchoInput=不回显输入内容(&O)
ParameterDialog.CheckBox.Hidden=隐藏(&D)
ParameterDialog.CheckBox.Sort=提示时按字母顺序排序(&B)
ParameterDialog.Choice.NoDefault=无默认值
ParameterDialog.Column.Default=默认值
ParameterDialog.Column.DisplayText=显示文本
ParameterDialog.Column.Value=值
ParameterDialog.DisplayLabel.Combo=组合框
ParameterDialog.DisplayLabel.List=列表框
ParameterDialog.ErrorMessage.CanootBeBlank=该值不能为空。
ParameterDialog.ErrorMessage.CanootBeNull=该值不能为 null。
ParameterDialog.ErrorMessage.DuplicatedLabel=该显示文本已经存在。
ParameterDialog.ErrorMessage.DuplicatedName=该名称已经在使用。
ParameterDialog.ErrorMessage.DuplicatedValue=值已经存在。
ParameterDialog.ErrorMessage.EmptyName=名称为空。
ParameterDialog.ErrorMessage.InvalidListLimit=限制值应介于 0 和 {0} 之间
ParameterDialog.ErrorMessage.MismatchDataType=值与日期类型不匹配。
ParameterDialog.ErrorMessage.NoAvailableColumn=没有可用的列。
ParameterDialog.ErrorMessage.NoDefaultValue=必须设置默认值。
ParameterDialog.ErrorTitle.InvalidListLimit=无效列表限制
ParameterDialog.Flag.Default=默认
ParameterDialog.Group.MoreOption=显示为
ParameterDialog.Group.Properties=属性
ParameterDialog.Label.DataType=数据类型(&D):
ParameterDialog.SelectionDialog.Edit=编辑选择选项
ParameterDialog.Label.DefaultValue=默认值(&F):
ParameterDialog.Label.DisplayPrompt=显示提示:
ParameterDialog.Label.DisplayType=显示类型(&T):
ParameterDialog.Label.Format=格式为(&M):
ParameterDialog.Label.HelpText=帮助文本(&H):
ParameterDialog.Label.ListOfValue=值列表:
ParameterDialog.Label.Name=名称(&N):
ParameterDialog.Label.None=<无>
ParameterDialog.Label.Null=Null
ParameterDialog.Label.Preview=带格式预览
ParameterDialog.Label.PromptText=提示文本(&P):
ParameterDialog.Label.SelectDataSet=数据集(&A):
ParameterDialog.SelectionDialog.New=新建选择选项
ParameterDialog.Label.SelectDisplayText=选择显示文本(&X):
ParameterDialog.Label.SelectValueColumn=选择值列(&U):
ParameterDialog.Label.Value=选择值:
ParameterDialog.Label.values=值
ParameterDialog.Label.Sample=示例
ParameterDialog.Label.Listlimit=列表限制(&I):
ParameterDialog.Radio.Dynamic=动态(&Y)
ParameterDialog.Radio.Static=静态(&S)
ParameterDialog.toolTipText.OpenExprButton=打开表达式生成器

###########################################################
#ParameterDropListener properties

ParameterDropListener.Command.Copy=复制元素
ParameterDropListener.Command.Move=移动元素

###########################################################
#ParameterGroupDialog properties

ParameterGroupDialog.Page.Title=常规
ParameterGroupDialog.pageTitle.general=常规

###########################################################
#ParameterGroupGeneralPage properties

ParameterGroupGeneralPage.Label.DisplayName=显示名称(&D):
ParameterGroupGeneralPage.Label.Name=名称(&N):

###########################################################
#ParameterGroupNodeProvider properties

ParameterGroupNodeProvider.Action.GroupNew=新建参数组
ParameterGroupNodeProvider.Action.ParameterEdit=编辑
ParameterGroupNodeProvider.Action.ParameterNew=新建参数
ParameterGroupNodeProvider.Dialogue.ParameterEdit=编辑参数组
ParameterGroupNodeProvider.Dialogue.ParameterNew=新建参数
ParameterGroupNodeProvider.Node.Group=参数组

###########################################################
#ParameterGroupProcess properties

ParameterGroupProcess.action.Delete=删除参数组
ParameterGroupProcess.action.Edit=编辑参数组
ParameterGroupProcess.action.New=新建参数
ParameterGroupProcess.text.DisplayName=参数组
ParameterGroupProcess.text.Show=显示数据源编辑器页  

###########################################################
#ParameterNodeProvider properties

ParameterNodeProvider.dial.title.editCascading=编辑级联参数
ParameterNodeProvider.dial.title.editScalar=编辑参数
ParameterNodeProvider.dial.title.newCascading=新级联参数
ParameterNodeProvider.menu.text.edit=编辑
ParameterNodeProvider.menu.text.new=新建参数

###########################################################
#ParameterProcess properties

ParameterProcess.action.Delete=删除参数
ParameterProcess.action.Edit=编辑参数
ParameterProcess.text.DisplayName=参数
ParameterProcess.text.Show=显示数据源编辑器页  

###########################################################
#parameters properties

parameters.datatypes.boolean=布尔
parameters.datatypes.dateTime=日期时间
parameters.datatypes.decimal=小数
parameters.datatypes.float=浮点
parameters.datatypes.string=字符串
parameters.menuItem.refresh=刷新

###########################################################
#ParametersNodeProvider properties

ParametersNodeProvider.dialogue.title.group=新建参数组
ParametersNodeProvider.dialogue.title.parameter=新建参数
ParametersNodeProvider.menu.text.cascadingParameter=新建级联参数
ParametersNodeProvider.menu.text.group=新建参数组
ParametersNodeProvider.menu.text.parameter=新建参数

###########################################################
#ParametersOutlineProcess properties

ParametersOutlineProcess.action.Edit=编辑
ParametersOutlineProcess.action.New=新建参数
ParametersOutlineProcess.action.NewGroup=新建组
ParametersOutlineProcess.text.Open=打开参数编辑器
ParametersOutlineProcess.text.Show=显示数据集的数据集编辑器页

###########################################################
#PasteAction properties

PasteAction.text=粘贴(&P)

###########################################################
#PlaceHolderEditPart properties

PlaceHolderEditPart.Trans.TransferToElement=传送到报表项

###########################################################
#PreviewAction properties

PreviewAction.Text=预览

###########################################################
#PreviewEditor properties

PreviewEditor.parameter.tooltip=显示报表参数

###########################################################
#PreviewPageAction properties

PreviewPageAction.actionText.preview=预览

###########################################################
#PropertiesAction properties

PropertiesAction.Text=属性

###########################################################
#PropertyHandleTableViewer properties

PropertyHandleTableViewer.Button.New=新建(&N)...
PropertyHandleTableViewer.Button.Edit=编辑(&E)...
PropertyHandleTableViewer.Button.Remove=删除(&R)
PropertyHandleTableViewer.Button.Up=上移(&U)
PropertyHandleTableViewer.Button.Down=下移(&D)
PropertyHandleTableViewer.Menu.Remove=删除
PropertyHandleTableViewer.Menu.Up=上移
PropertyHandleTableViewer.Menu.Down=下移
PropertyHandleTableViewer.Menu.RemoveAll=全部删除

###########################################################
#PropertyHandleInputDialog properties

PropertyHandleInputDialog.Action.New=新建
PropertyHandleInputDialog.Action.Edit=编辑
PropertyHandleInputDialog.messages.error.blankProperty={0} 不能为空白

###########################################################
#PublishTemplateAction properties

PublishTemplateAction.wizard.page.browse.cheatsheet.title=选择备忘单文件
PublishTemplateAction.wizard.page.browse.title=选择图像文件
PublishTemplateAction.wizard.page.btn.browse=浏览(&W)...
PublishTemplateAction.wizard.page.cheatsheetError=备忘单文件 ''{0}'' 不存在。
PublishTemplateAction.wizard.page.desc=发布到模板文件夹。
PublishTemplateAction.wizard.page.imageError=图像文件 ''{0}'' 不存在。
PublishTemplateAction.wizard.page.label.cheatsheet=备忘单文件:
PublishTemplateAction.wizard.page.label.description=描述(&D):
PublishTemplateAction.wizard.page.label.displayName=显示名称(&M):
PublishTemplateAction.wizard.page.label.image=模板图像(&I):
PublishTemplateAction.wizard.page.title=发布到模板文件夹
PublishTemplateAction.wizard.title=发布到模板文件夹
PublishTemplateAction.wizard.errorTitle=错误
PublishTemplateAction.wizard.message=无法将模板发布到其所在的目录，请选择其它目录进行发布。
PublishTemplateAction.wizard.notvalidfolder=首选项中定义的模板文件夹无效。
PublishTemplateAction.wizard.page.nameInfo=必须提供显示名称
PublishTemplateAction.wizard.message.SourceFileNotExist=源文件不存在。
PublishTemplateAction.wizard.message.PreviewImageNotExist=预览图像文件不存在。
PublishTemplateAction.wizard.message.PreviewImageNotValid=预览图像文件不是有效的图像。

###########################################################
#PublishLibraryAction properties
PublishLibraryAction.wizard.errorTitle=错误
PublishLibraryAction.wizard.message=无法将该库发布到其所在的目录，请选择其它目录进行发布。
PublishLibraryAction.wizard.message.SourceFileNotExist=源文件不存在。
PublishLibraryAction.wizard.notvalidfolder=首选项中定义的库文件夹无效。

###########################################################
#RedoAction properties

RedoAction.Tooltip=恢复 {0}

###########################################################
#ExportReportWizard
ExportToLibraryAction.wizard.windowTitle=导出
ExportToLibraryAction.wizard.page.title=文件导出到库
ExportToLibraryAction.wizard.page.desc=报表设计导出到库
ExportToLibraryAction.wizard.page.label.filename=文件名(&N):
ExportToLibraryAction.wizard.page.label.folder=文件夹(&F):
ExportToLibraryAction.wizard.page.button.browser=浏览(&B)...
ExportToLibraryAction.wizard.page.dirdialog.message=选择文件内容目录
ExportToLibraryAction.wizard.page.nameempty=必须指定文件名
ExportToLibraryAction.wizard.page.folderempty=必须指定文件夹
ExportToLibraryAction.wizard.page.foldererror=指定的文件夹不存在

###########################################################
#PublishLibraryToResourceFolderAction
PublishLibraryToResourceFolderAction.Action.Text=将库置于资源文件夹...

###########################################################
#PublishTemplateViewAction
DefaultNodeProvider.template.suffix=.rpttemplate
PublishTemplateViewAction.action.displaytext=使用新建报表向导来注册模板...

###########################################################
#RefreshModuleHandleAction
RefreshModuleHandleAction.Action.Text=刷新库

###########################################################
#ReferencePage properties

ReferencePage.Button.Edit=编辑(&D)...
ReferencePage.Label.Source=源(&S):

###########################################################
#RefreshAction properties

RefreshAction.text=刷新

###########################################################
#RefreshLibExplorerAction properties

RefreshLibExplorerAction.Text=刷新

###########################################################
#RemoveLibraryAction properties

RemoveLibraryAction.Text=删除库

###########################################################
#RenameAction properties

RenameAction.text=重命名

###########################################################
#RenameDialog properties

RenameDialog.action.Cancel=取消
RenameDialog.action.Ok=\\ \\ 确定  
RenameDialog.text.NewName=新名称:
RenameDialog.text.Rename=重命名 
RenameDialog.text.ToolTip=名称不能为空

###########################################################
#RenameInlineTool properties

RenameInlineTool.DialogTitle.RenameFailed=重命名失败
RenameInlineTool.TransLabel.Rename=重命名

###########################################################
#RenameInputDialog properties

RenameInputDialog.DialogTitle=重命名输入
RenameInputDialog.DialogMessage=请输入新名称

###########################################################
#report properties

report.designer.ui.preferences.buttonadd=添加(&D)...
report.designer.ui.preferences.buttonremove=删除(&R)
report.designer.ui.preferences.buttonremoveall=全部删除(&A)
report.designer.ui.preferences.dialogtitle=打开库
report.designer.ui.preferences.errormessage=库已经存在。
report.designer.ui.preferences.errortitle=错误
report.designer.ui.preferences.extensions=*.rptlibrary
report.designer.ui.preferences.labeltitle=添加/删除库
report.designer.ui.preferences.library.export.overwrite.always=始终(&W)
report.designer.ui.preferences.library.export.overwrite.never=从不(&N)
report.designer.ui.preferences.library.export.overwrite.prompt=提示(&P)
report.designer.ui.preferences.library.export.title=在将设计元素导出到库中时覆盖现有元素。
report.designer.ui.preferences.template.openDialogTitle=请为模板选择一个文件夹。
report.designer.ui.preferences.template.select=选择(&S)...
report.designer.ui.preferences.template.templatedir=模板
report.designer.ui.preferences.template.templatefolder= 模板文件夹(&T)
report.designer.ui.preferences.template.title=请选择模板文件夹。
org.eclipse.birt.report.designer.ui.preference.commenttemplates.enablecomment=创建报表设计时生成注释
org.eclipse.birt.report.designer.ui.preference.commenttemplates.defaultcomment=版权所有 (c) 2006 <<此处是您公司的名称>>

###########################################################
#Resource Preference page properties
ResourecePreferencePage.title=Please select the default Resource Folder to use for the library explorer,images,property files and etc.
ResourecePreferencePage.folder=资源文件夹(&R)
ResourecePreferencePage.select=选择(&S)...
ResourecePreferencePage.openDialogTitle=浏览文件夹
ResourecePreferencePage.openDialogMessage=请选择默认资源文件夹:

###########################################################
#ReportAdvancedLauncherTab properties

ReportAdvancedLauncherTab.DefaultsButtonText=还原默认值(&R)
ReportAdvancedLauncherTab.DeselectButtonText=取消全选(&D)
ReportAdvancedLauncherTab.Name=报表项目
ReportAdvancedLauncherTab.SelectAllButtonText=全选(&S)
ReportAdvancedLauncherTab.UseListRadioText=从列表中选择要启动的项目
ReportAdvancedLauncherTab.VisibleLabelText=可用项目(&A)
ReportAdvancedLauncherTab.WorkspaceReportProjects=工作区报表项目

###########################################################
#ReportClasspathLaucnTab properties

ReportClasspathLaucnTab.DefaultButtonText=还原默认值(&R)
ReportClasspathLaucnTab.DeselectButtonText=取消全选(&D)
ReportClasspathLaucnTab.Name=Java 项目
ReportClasspathLaucnTab.SelectAllButtonText=全选(&S)
ReportClasspathLaucnTab.UseListRadioText=从列表中选择要启动的项目，选择项目的类输出文件夹将被添加到类路径中
ReportClasspathLaucnTab.VisibleLabelText=可用项目(&A)
ReportClasspathLaucnTab.WorkspaceJavaProjects=工作区 java 项目

###########################################################
#ReportCreationTool properties

ReportCreationTool.ModelTrans.CreateElement=插入元素

###########################################################
#ReportEditor properties

ReportEditor.Button.Close=关闭
ReportEditor.Button.Save=保存
ReportEditor.Dlg.Confirm=文件已从文件系统中删除。是要保存更改还是要关闭编辑器而不保存？
ReportEditor.Dlg.Save=保存...
ReportEditor.error.activated.outofsync.message=文件系统上的文件已更改。是否要加载更改？
ReportEditor.error.activated.outofsync.title=文件已更改
ReportEditor.Error.Open=打开错误
ReportEditor.Error.OpenEditor=无法打开文件。
ReportEditor.Page.Code=脚本
ReportEditor.Page.Layout=布局
ReportEditor.Page.MasterPage=主页
ReportEditor.Page.Preview=预览
ReportEditor.Page.PreviewSaveMessage=报表文件已被修改。在预览之前是否要保存该文件？
ReportEditor.Page.PreviewSaveTitle=保存
ReportEditor.Page.PreviewSaveToggle=始终在预览前保存文件。

###########################################################
#ReportLaunchConfigurationDelegate properties

ReportLaunchConfigurationDelegate.badFeatureSetup=错误的功能设置
ReportLaunchConfigurationDelegate.noStartup=无启动

###########################################################
#ReportPage properties
ReportPage.text.Add=添加(&A)...
ReportPage.text.Browse=浏览(&B)...
ReportPage.title.Location=位置:
ReportPage.title.setPrewImg=选择图像文件
ReportPage.text.Resource.Add=添加(&D)...
ReportPage.text.Thumbnail=缩略图(&H)...

###########################################################
#ReportPageGenerator properties

ReportPageGenerator.List.Comments=备注
ReportPageGenerator.List.Description=描述
ReportPageGenerator.List.EventHandler=事件处理程序
ReportPageGenerator.List.General=常规
ReportPageGenerator.List.Measurement=度量
ReportPageGenerator.List.NamedExpressions=命名表达式
ReportPageGenerator.List.UserProperties=用户属性
ReportPageGenerator.List.Resources=资源
ReportPageGenerator.List.Resources.JarFile=Jar 文件:
ReportPageGenerator.List.AdvancedProperty=Advanced

#OdaDataSourceGenerator properties
DataSourcePageGenerator.List.General=常规

#OdaDataSetGenerator properties
DataSetPageGenerator.List.General=常规
DataSetPageGenerator.DataSourceName=数据源(&D)

#ScalarParameterPageGenerator properties
ScalarParameterPageGenerator.List.General=常规
ScalarParameterPageGenerator.List.I18n=本地化

#TemplateReportItemPageGenerator properties
TemplateReportItemPageGenerator.List.General=常规
TemplateReportItemPage.description.Label.Instructions=说明(&I):
TemplateReportItemPageGenerator.List.I18n=本地化
TemplateReportItemPageGenerator.List.TextKey=文本关键字:

###########################################################
#ReportPropertySheetPage properties

ReportPropertySheetPage.Column.Title.Property=属性
ReportPropertySheetPage.Column.Title.Value=值
ReportPropertySheetPage.Root.Default.Title=信息

###########################################################
#ReportTemplateTransferDropTargetListener properties

ReportTemplateTransferDropTargetListener.ModelTrans.CreateElement=创建元素
ReportTemplateTransferDropTargetListener.transLabel.createElement=插入元素

###########################################################
#ResourceEditDialog properties

ResourceEditDialog.message.AddNote=快速添加”将关键字保存至当前源文件。
ResourceEditDialog.message.ResourceFile=源文件: 
ResourceEditDialog.text.Add=添加
ResourceEditDialog.text.AddWarningMsg=不允许空白键。
ResourceEditDialog.text.AddWarningTitle=Warning
ResourceEditDialog.text.Delete=删除
ResourceEditDialog.text.Key=关键字
ResourceEditDialog.text.QuickAdd=快速添加
ResourceEditDialog.text.Value=值

###########################################################
#ResourceKeyDescriptor properties

ResourceKeyDescriptor.text.Reset=重置
ResourceKeyDescriptor.title.SelectKey=选择关键字

###########################################################
#RevertToReportItemAction properties

RevertToReportItemAction.text=回复到报表项(&R)

###########################################################
#RevertToTemplateAction properties

RevertToTemplateAction.text=还原到模板项(&V)

###########################################################
#RowHandle properties

RowHandle.tooltip.GridRow=网格 - 行
RowHandle.tooltip.GroupFooter=表组 － 组页脚
RowHandle.tooltip.GroupHeader=表组 － 组页眉
RowHandle.tooltip.TableDetail=表 - 详细资料
RowHandle.tooltip.TableFooter=表 - 页脚
RowHandle.tooltip.TableHeader=表 - 页眉(&H)

###########################################################
#RowHandleAdapter properties

RowHandleAdapter.table.detail=明细数据行
RowHandleAdapter.table.footer=页脚行
RowHandleAdapter.table.groupFooter=组页脚行
RowHandleAdapter.table.groupHeader=组页眉行
RowHandleAdapter.table.header=页眉行

###########################################################
#RowPageGenerator properties

RowPageGenerator.List.Bookmark=书签
RowPageGenerator.List.Borders=边框
RowPageGenerator.List.Section=分页符
RowPageGenerator.List.CellPadding=单元格边距
RowPageGenerator.List.Font=字体
RowPageGenerator.List.General=常规
RowPageGenerator.TabItem.Highlights=突出显示
RowPageGenerator.TabItem.map=映射
RowPageGenerator.List.Visibility=可见性

###########################################################
#RowProvider properties

RowProvider.action.text.above=在上方插入行(&A)
RowProvider.action.text.below=在下方插入行(&B)

###########################################################
#SaveAsDialog properties

SaveAsDialog.message=将文件保存至另一个位置。
SaveAsDialog.overwriteQuestion=The file ''{0}'' already exists. Do you want to replace the existing file?
SaveAsDialog.Question=问题
SaveAsDialog.text=另存为
SaveAsDialog.title=另存为

###########################################################
#CreateDirectory properties
DirectoryDialog.createQuestion=目录“{0}”不存在。是否要创建该目录?
DirectoryDialog.Question=问题

###########################################################
#SchematicContextMenuProvider properties

SchematicContextMenuProvider.ActionText.editData=编辑值/表达式\u2026(&V)
SchematicContextMenuProvider.ActionText.editLabel=编辑(&D)
SchematicContextMenuProvider.Menu.Apply=应用样式(&P)
SchematicContextMenuProvider.Menu.EditGroup=编辑组(&E)
SchematicContextMenuProvider.Menu.Insert=插入(&I)
SchematicContextMenuProvider.Menu.insertElement=插入(&I)
SchematicContextMenuProvider.Menu.insertRow=行(&R)
SchematicContextMenuProvider.Menu.List=列表
SchematicContextMenuProvider.Menu.Show=显示
SchematicContextMenuProvider.Menu.Style=样式(&Y)
SchematicContextMenuProvider.Menu.Theme=主题(&M)
SchematicContextMenuProvider.menutitle.applystylerule=应用样式
SchematicContextMenuProvider.menutitle.applythemerule=应用主题
SchematicContextMenuProvider.menutitle.editgroup=编辑组
SchematicContextMenuProvider.menutitle.insert=插入
SchematicContextMenuProvider.menutitle.list=列表
SchematicContextMenuProvider.menutitle.show=显示
SchematicContextMenuProvider.menutitle.style=样式
SchematicContextMenuProvider.Menu.EditStyle=编辑样式(&T:)
SchematicContextMenuProvider.Menu.DeleteStyle=删除样式(&S)
SchematicContextMenuProvider.Menu.DeleteGroup=删除组(&T)
SchematicContextMenuProvider.Menu.InsertGroupHeaderFooter=插入组页眉/页脚(&P)
SchematicContextMenuProvider.Menu.NewStyle=新样式(&Y)

###########################################################
#SectionProcess properties

SectionProcess.action.Clear=清除
SectionProcess.action.Delete=删除
SectionProcess.action.DeleteRow=删除行
SectionProcess.action.New=新建
SectionProcess.action.NewCell=新建单元格
SectionProcess.action.NewGroup=新建组
SectionProcess.action.NewRow=新建行
SectionProcess.action.NewSection=新建区域
SectionProcess.action.NewSubSection=新建子区域
SectionProcess.displayname.GridProcess=网格
SectionProcess.displayname.GroupProcess=组
SectionProcess.displayname.ListProcess=列表
SectionProcess.displayname.TableProcess=表
SectionProcess.displayname.TableRowProcess=行
SectionProcess.type.Container=（容器）
SectionProcess.type.Data=（数据）
SectionProcess.type.Image=（图像）
SectionProcess.type.Label=（标签）
SectionProcess.type.List=（列表）
SectionProcess.type.Prefix=列
SectionProcess.type.Table=（表）
SectionProcess.type.Text=（文本）

###########################################################
#SelectAllAction properties

SelectAllAction.text=全选(&A)

###########################################################
#SelectCssStyleWizard properties

SelectCssStyleWizard.wizard.title=导入 CSS 样式
SelectCssStyleWizard.wizardPage.description=选择一个 CSS 文件，将样式导入到报表设计。
SelectCssStyleWizard.wizardPage.name=选择 Css 样式
SelectCssStyleWizard.wizardPage.title=从 CSS 文件导入样式

###########################################################
#SelectValueDialog properties

SelectValueDialog.errorRetrievinglist=检索列表时出错
SelectValueDialog.messages.info.selectVauleUnavailable=只有 row["name"]、row[index] 或 row.name 之类格式的表达式才能获得值列表。 
SelectValueDialog.messages.error.selectVauleUnavailable=无法检索该表达式的值。
SelectValueDialog.noExpressionSet=尚未设置表达式
SelectValueDialog.retrieving=正在检索列表...
SelectValueDialog.selectValue=选择值

###########################################################
#SetConstraintCommand properties

SetConstraintCommand.Error.SetConstraintError=对模型设置约束时出错。
SetConstraintCommand.transLabel.setConstraint=设置约束

###########################################################
#ShowPropertyAction properties

ShowPropertyAction.text=属性

###########################################################
#SortingHandleProvider properties

SortingHandleProvider.Label.SortOn=排序依据:

###########################################################
#Spinner properties

Spinner.DialogTitle.InvalidNumber=Invalid number

###########################################################
#SplitAction properties

SplitAction.actionMsg.splitCells=拆分单元格(&S)

###########################################################
#StyleBuilder properties

StyleBuilder.action.Apply=应用(&A)
SytleBuilder.DialogTitle.New=新建样式
SytleBuilder.DialogTitle.Edit=编辑样式

###########################################################
#StyleComboProvider properties

StyleComboProvider.LineStyle.None=无样式

###########################################################
#StyleNodeProvider properties

StyleNodeProvider.action.Edit=编辑样式(&E)...
StyleNodeProvider.action.New=新建样式(&N)...

###########################################################
#StyleProcess properties

StyleProcess.action.Delete=删除样式
StyleProcess.action.Edit=编辑样式(&E)...
StyleProcess.action.New=新建样式(&N)...
StyleProcess.text.CannotDelete=无法删除默认样式。 
StyleProcess.text.Show=显示该数据集的数据集编辑器。

###########################################################
#StylesNodeProvider properties

StylesNodeProvider.action.New=新建样式...

###########################################################
#StylesOutlineProcess properties

StylesOutlineProcess.action.New=新建样式...

###########################################################
#TableBandProvider properties

TableBandProvider.action.text.group=插入组
TableBandProvider.action.text.row=插入行

###########################################################
#TableEditPart properties

TableEditPart.GUIDEHANDLE_TEXT = 表
TableEditPart.Label.Merge=Merge Cells
TableEditPart.Label.ResizeColumn=重新设定列大小
TableEditPart.Label.ResizeRow=重新设定行大小

###########################################################
#TableFigure properties

TableFigure.BORDER_TEXT=表
TableArea.Button.New=新建(&N)...
TableArea.Button.Edit=编辑(&E)...
TableArea.Button.Remove=删除(&R)
TableArea.Button.Down=下移(&O)

###########################################################
#TableHandleAdapter properties

TableHandleAdapter.name.detail=详细资料
TableHandleAdapter.name.footer=页脚
TableHandleAdapter.name.header=页眉
TableHandleAdapter.transLabel.deleteColumn=删除列
TableHandleAdapter.transLabel.deleteColumns=删除列
TableHandleAdapter.transLabel.deleteRow=删除行
TableHandleAdapter.transLabel.deleteRows=删除行
TableHandleAdapter.transLabel.include=包含 
TableHandleAdapter.transLabel.insertColumn=插入列
TableHandleAdapter.transLabel.insertGroup=插入组
TableHandleAdapter.transLabel.insertRow=插入行
TableHandleAdapter.transLabel.notInclude=不包含 
TableHandleAdapter.transLabel.splitCells=拆分单元格
TableHandleAdapter.transLable.deleteGroup=删除表组

###########################################################
#TableOptionDialog properties

TableOptionDialog.message.RememberGrid=对新网格使用这些维(&U)。
TableOptionDialog.message.RememberTable=对新表使用这些维(&U)。
TableOptionDialog.text.Column=列数(&C):
TableOptionDialog.text.GridRow=行数(&R):
TableOptionDialog.text.GridSize=网格大小
TableOptionDialog.text.TableDetail=明细数据数(&D):
TableOptionDialog.text.TableSize=表大小
TableOptionDialog.title.InsertGrid=插入网格
TableOptionDialog.title.InsertTable=插入表
TableOptionDialog.text.DataSet=数据集:

###########################################################
#TablePageGenerator properties

TablePageGenerator.List.Bookmark=书签
TablePageGenerator.List.Borders=边框
TablePageGenerator.List.CellPadding=单元格边距
TablePageGenerator.List.Font=字体
TablePageGenerator.List.General=常规
TablePageGenerator.List.Marign=边距
TablePageGenerator.List.Section=分页符
TablePageGenerator.List.TOC=目录
TablePageGenerator.List.Visibility=可见性
TablePageGenerator.TabItem.Binding=绑定
TablePageGenerator.TabItem.Filters=筛选器
TablePageGenerator.TabItem.Groups=组
TablePageGenerator.TabItem.Highlights=突出显示
TablePageGenerator.TabItem.map=映射
TablePageGenerator.TabItem.Sorting=排序

###########################################################
#TemplateReportItemPropertiesDialog properties

TemplateReportItemPropertiesDialog.errorMessage=提示文本不能为空。
TemplateReportItemPropertiesDialog.errorTitle=错误
TemplateReportItemPropertiesDialog.group=模板报表项属性
TemplateReportItemPropertiesDialog.objectType=元素类型:
TemplateReportItemPropertiesDialog.nameText=名称(&N):
TemplateReportItemPropertiesDialog.promptText=说明(&I):
TemplateReportItemPropertiesDialog.title=创建模板报表项

###########################################################
#performCreatePlaceHolder action
performCreatePlaceHolder.errorMessage.title=错误
performCreatePlaceHolder.errorMessage.content=您指定的名称已存在，请选择另一个名称或保留为空白。

###########################################################
#TogglePropertyDescriptor properties
TogglePropertyDescriptor.toolTipText.Bold=粗体
TogglePropertyDescriptor.toolTipText.Italic=斜体
TogglePropertyDescriptor.toolTipText.Underline=下划线
TogglePropertyDescriptor.toolTipText.Text_Line_Through=文本删除线

###########################################################
#TextAlignPropertyDescriptor properties

TextAlignPropertyDescriptor.0=左对齐
TextAlignPropertyDescriptor.1=居中
TextAlignPropertyDescriptor.2=右对齐
TextAlignPropertyDescriptor.3=对齐

###########################################################
#TextAreaContextMenu properties

TextAreaContextMenu.Copy.description=复制
TextAreaContextMenu.Copy.image=
TextAreaContextMenu.Copy.label=复制(&C)
TextAreaContextMenu.Copy.tooltip=复制
TextAreaContextMenu.Cut.description=剪切
TextAreaContextMenu.Cut.image=
TextAreaContextMenu.Cut.label=剪切(&T)
TextAreaContextMenu.Cut.tooltip=剪切
TextAreaContextMenu.Paste.description=粘贴
TextAreaContextMenu.Paste.image=
TextAreaContextMenu.Paste.label=粘贴(&P)
TextAreaContextMenu.Paste.tooltip=粘贴
TextAreaContextMenu.Redo.description=恢复
TextAreaContextMenu.Redo.image=
TextAreaContextMenu.Redo.label=恢复(&R)
TextAreaContextMenu.Redo.tooltip=恢复
TextAreaContextMenu.SelectAll.description=全选
TextAreaContextMenu.SelectAll.image=
TextAreaContextMenu.SelectAll.label=全选(&A)
TextAreaContextMenu.SelectAll.tooltip=全选
TextAreaContextMenu.Undo.description=撤消
TextAreaContextMenu.Undo.image=
TextAreaContextMenu.Undo.label=撤消(&U)
TextAreaContextMenu.Undo.tooltip=撤消

###########################################################
#TextDataEditPart properties

TextDataEditPart.Figure.Dafault=动态文本

###########################################################
#TextEditDialog properties

TextEditDialog.action.text.editDynamicText=编辑动态文本(&X)
TextEditDialog.action.text.formatDateTime=日期时间格式(&E)
TextEditDialog.action.text.formatNumber=数值格式(&N)
TextEditDialog.action.text.formatString=格式字符串(&G)
TextEditDialog.choice.HTML=HTML/动态文本
TextEditDialog.choice.plainText=纯文本
TextEditDialog.choice.Auto=自动
TextEditDialog.comboText.formattingAndLayout=格式和布局
TextEditDialog.format.dynamicText=动态文本
TextEditDialog.format.formatting=格式和布局
TextEditDialog.format.lists=列表
TextEditDialog.format.pageComposition=页合成
TextEditDialog.format.pageElements=页面元素
TextEditDialog.formatChoice.content=内容
TextEditDialog.formatChoice.dynamicText=动态文本
TextEditDialog.formatChoice.formatting=格式化
TextEditDialog.formatChoice.layout=布局
TextEditDialog.formatChoice.lists=列表
TextEditDialog.toolTip.tag.a=定位
TextEditDialog.toolTip.tag.b=粗体文本样式
TextEditDialog.toolTip.tag.birtImage=BIRT 特定图像
TextEditDialog.toolTip.tag.br=换行符
TextEditDialog.toolTip.tag.center=文本居中
TextEditDialog.toolTip.tag.code=计算机代码片段
TextEditDialog.toolTip.tag.dd=定义描述
TextEditDialog.toolTip.tag.del=删除的文本
TextEditDialog.toolTip.tag.dl=定义列表
TextEditDialog.toolTip.tag.dt=定义术语
TextEditDialog.toolTip.tag.em=着重
TextEditDialog.toolTip.tag.font=字体的本地更改
TextEditDialog.toolTip.tag.genericStyleContainer=一般语言/风格容器
TextEditDialog.toolTip.tag.h1=第 1 级标题
TextEditDialog.toolTip.tag.h2=第 2 级标题
TextEditDialog.toolTip.tag.h3=第 3 级标题
TextEditDialog.toolTip.tag.h4=第 4 级标题
TextEditDialog.toolTip.tag.h5=第 5 级标题
TextEditDialog.toolTip.tag.h6=第 6 级标题
TextEditDialog.toolTip.tag.i=斜体文本样式
TextEditDialog.toolTip.tag.img=标准 HTML 图像引用
TextEditDialog.toolTip.tag.ins=插入的文本
TextEditDialog.toolTip.tag.li=列表项
TextEditDialog.toolTip.tag.p=段
TextEditDialog.toolTip.tag.pre=预设文本
TextEditDialog.toolTip.tag.strong=特别强调
TextEditDialog.toolTip.tag.sub=下标
TextEditDialog.toolTip.tag.sup=上标
TextEditDialog.toolTip.tag.tt=电传或等距文本样式
TextEditDialog.toolTip.tag.u=下划线文本样式
TextEditDialog.toolTip.tag.ul=无序列表
TextEditDialog.toolTip.valueOf=值
TextEditDialog.toolTipText.copy=复制
TextEditDialog.toolTipText.cut=剪切
TextEditDialog.toolTipText.delete=删除
TextEditDialog.toolTipText.paste=粘贴
TextEditDialog.toolTipText.redo=恢复
TextEditDialog.toolTipText.undo=撤消

###########################################################
#TextEditPart properties

TextEditPart.Figure.Dafault=文本
TextEditPart.trans.editText=编辑文本项

###########################################################
#TextExtendsTools properties

TextExtendsTools.Message.DefaultAuthor=Birt Eclipse Report Designer 版本

###########################################################
#TextPageGenerator properties

TextPageGenerator.List.Bookmark=书签
TextPageGenerator.List.Borders=边框
TextPageGenerator.List.General=常规
TextPageGenerator.List.I18n=定位
TextPageGenerator.List.Margin=边距
TextPageGenerator.List.Padding=填充
TextPageGenerator.List.Section=分页符
TextPageGenerator.List.TOC=目录
TextPageGenerator.List.Visibility=可见性

###########################################################
#TextPropertyDescriptor properties

TextPropertyDescriptor.Message.Version=Eclipse BIRT Designer Version {0} Build <{1}>

###########################################################
#AutoTextPageGenerator properties

AutoTextPageGenerator.List.Bookmark=书签
AutoTextPageGenerator.List.Borders=边框
AutoTextPageGenerator.List.General=常规
AutoTextPageGenerator.List.Margin=边距
AutoTextPageGenerator.List.Padding=填充
AutoTextPageGenerator.List.Section=分页符
AutoTextPageGenerator.List.TOC=目录
AutoTextPageGenerator.List.Visibility=可见性

###########################################################
#ThemesNodeProvider properties

ThemesNodeProvider.action.New=新主题

###########################################################
#TimeOptionDialog properties

TimeOptionDialog.Label.Format=格式
TimeOptionDialog.Label.TimeZone=TimeZone

###########################################################
#ToggleMarginVisibilityAction properties

ToggleMarginVisibilityAction.text.Label=显示边距(&M)
ToggleMarginVisibilityAction.text.Tooltip=切换边距

###########################################################
#TwinExpressionDialog properties

TwinExpressionDialog.Dialog.Title=<选择值...>
TwinExpressionDialog.lable.value1=值 1:
TwinExpressionDialog.lable.value2=值 2:

###########################################################
#UndoAction properties

UndoAction.Tooltip=撤销 {0}

###########################################################
#UnitPropertyDescriptor properties

UnitPropertyDescriptor.error.message=Please enter a smaller value\!
UnitPropertyDescriptor.error.title=Too Big Value

###########################################################
#UseLibraryAction properties

UseLibraryAction.Text=使用库(&U)
UseLibraryAction.Error.Title=替换现有文件
UseLibraryAction.Error.Message=BIRT 资源文件夹中已经存在文件“{0}”。是否要替换现有文件？

###########################################################
#UserPropertyBuilder properties

UserPropertyBuilder.0=新用户属性
UserPropertyBuilder.ErrorMessage.DuplicatedName=您指定的名称已被使用。
UserPropertyBuilder.ErrorMessage.NoName=请指定一个名称。
UserPropertiesHandleProvier.Column.Name=名称
UserPropertiesHandleProvier.Column.Type=类型
UserPropertyBuilder.Label.DefaultValue=默认值(&V):
UserPropertyBuilder.Label.ExpressionName=表达式名称(&N):
UserPropertyBuilder.Label.PropertyName=属性名称(&N):
UserPropertyBuilder.Label.PropertyType=属性类型(&T):
UserPropertyBuilder.Title.NamedExpression=新命名表达式

###########################################################
#VisibilityPage properties

VisibilityPage.Check.HideElement=隐藏元素(&H)
VisibilityPage.Check.HTML=H&TML
VisibilityPage.Check.PDF=&PDF
VisibilityPage.Label.DetailAll=详细资料（所有输出）
VisibilityPage.Label.DetailSpecific=详细资料（特定输出）
VisibilityPage.Label.Expression=表达式(&E):
VisibilityPage.menu.SaveHides=保存隐藏内容
VisibilityPage.Radio.AllOutputs=适用于所有输出(&A)
VisibilityPage.Radio.SpecificOutputs=适用于特定输出(&S)...

###########################################################
#WidgetUtil properties

WidgetUtil.MessageBox.Error=错误

###########################################################
#wizard properties

wizard.transaction.createDataSource=定义数据源的名称和类型。

###########################################################
#WizardChoicePage properties

WizardChoicePage.radio.createBlank=在不使用模板的情况下创建新的空白报表。
WizardChoicePage.radio.createFromCustom=通过复制其他报表来创建报表。
WizardChoicePage.radio.createFromTemplate=使用模板创建报表。

###########################################################
#WizardCustomTemplatePage properties

WizardCustomTemplatePage.button.Browse=浏览
WizardCustomTemplatePage.label.FileName=输入或选择现有报表文件名。
WizardCustomTemplatePage.label.FromLocal=从本地文件系统中浏览。
WizardCustomTemplatePage.label.FromProjectDescription=选择现有报表文件。
WizardCustomTemplatePage.label.FromProjectTitle=报表文件选择

###########################################################
#WizardNewReportCreationPage properties

WizardNewReportCreationPage.Errors.nameExists=该名称已经存在。
WizardNewReportCreationPage.label.browse=浏览...
WizardNewReportCreationPage.label.directory=目录:
WizardNewReportCreationPage.label.file.location=文件位置
WizardNewReportCreationPage.label.file.name=文件名:
WizardNewReportCreationPage.label.select.directory=选择目录。
WizardNewReportCreationPage.label.useDefault=使用默认设置
WizardNewReportCreationPage.msg.duplicate.fileName=该名称已经存在。
WizardNewReportCreationPage.msg.empty.file.locationDirectory=文件位置目录不能为空。
WizardNewReportCreationPage.msg.empty.file.name=文件名不能为空。

###########################################################
#WizardSelectCssStylePage properties

WizardSelectCssStylePage.button.label.browse=浏览(&B)...
WizardSelectCssStylePage.button.label.deselectAll=取消全选(&D)
WizardSelectCssStylePage.button.label.selectAll=全选(&S)
WizardSelectCssStylePage.errorMsg.FileNotExist=文件不存在。
WizardSelectCssStylePage.info.canNotImport=\ \ (无法导入)
WizardSelectCssStylePage.label.fileName=文件名(&F):
WizardSelectCssStylePage.label.importToReportDesign=\ 导入到报表设计。
WizardSelectCssStylePage.label.notifications=通知:
WizardSelectCssStylePage.label.selectStylesFrom=选择样式自 
WizardSelectCssStylePage.msg.FileNameEmpty=文件名不能为空。
WizardSelectCssStylePage.text.cannot.import.style=\ - 无法导入样式。
WizardSelectCssStylePage.FileNameError.Title=错误
WizardSelectCssStylePage.FileNameError.Message=选择的文件无效。

###########################################################
#WizardTemplateChoicePage properties

WizardTemplateChoicePage.label.Description=描述:
WizardTemplateChoicePage.label.Preview=预览:
WizardTemplateChoicePage.label.ReportTemplates=报表模板:
WizardTemplateChoicePage.label.ShowCheatSheets=显示报表创建备忘单(&S)
WizardTemplateChoicePage.message.BlankReport=创建无预定义内容的空报表。
WizardTemplateChoicePage.message.ChartListing=创建分组报表，并附带直观表示每个组数据的图表。
WizardTemplateChoicePage.message.DualColumnChartListing=创建带两个“图表和列表”子组的分组报表。
WizardTemplateChoicePage.message.DualColumnListing=创建带两个子组的分组报表。
WizardTemplateChoicePage.message.FirstReport=提供创建客户列表报表的说明。
WizardTemplateChoicePage.message.GroupedListing=创建一个根据某些字段分组的列表报表。
WizardTemplateChoicePage.message.Letter=使用数据源中的字段创建一个模板以生成个性化字母
WizardTemplateChoicePage.message.MailingLabels=邮寄标签
WizardTemplateChoicePage.message.SideBySideChartListing=创建一个分组报表，其中每个组都并排包含一个图表和一个列表。
WizardTemplateChoicePage.message.SimpleListing=使用数据源中的字段创建列表报表。
WizardTemplateChoicePage.title.BlankReport=空白报表
WizardTemplateChoicePage.title.ChartListing=图表和列表
WizardTemplateChoicePage.title.DualColumnChartListing=双列图表和列表
WizardTemplateChoicePage.title.DualColumnListing=双列列表
WizardTemplateChoicePage.title.FirstReport=我的第一份报表
WizardTemplateChoicePage.title.GroupedListing=分组列表
WizardTemplateChoicePage.title.Letter=信件
WizardTemplateChoicePage.title.MailingLabels=邮寄标签
WizardTemplateChoicePage.title.SideBySideChartListing=并排图表和列表
WizardTemplateChoicePage.title.SimpleListing=简易列表

###########################################################
#XMLSourcePage properties

XMLSourcePage.Error.Dialog.Message.InvalidFile=必须先改正 XML 源页中的错误，然后才能使用其它页。
XMLSourcePage.Error.Dialog.Message.SaveFile=XML 源页已更改。 直到保存 XML 源之后才能使用其它页。
XMLSourcePage.Error.Dialog.title=警告
XMLSourcePage.Error.Dialog.Message.PromptMsg=XML 报表设计源已更改。 是否要保存这些更改？
XMLSourcePage.Error.Dialog.Message.Yes=是
XMLSourcePage.Error.Dialog.Message.No=否
XMLSourcePage.Error.Dialog.Message.Cancel=取消

###########################################################
#SaveReportAsWizard properties
SaveReportAsWizard.SettingPage.title=设置模板属性
SaveReportAsWizard.SaveAsPageTitle=另存为
SaveReportAsWizard.SaveAsLibraryMessage=使用另一个名称将文件另存为库。
SaveReportAsWizard.SaveAsReportorTemplateMessage=使用另一个名称将文件另存为报表设计或模板。
SaveReportAsWizard.SettingPageTitle=设置报表属性
SaveReportAsWizard.SettingPage.message=如果报表另存为模板，使用这些属性。
SaveReportAsWizard.SaveAsWizardWindowTitle=另存为
SaveReportAsWizard.SaveAsWizardPageTitle=另存为
SaveReportAsWizard.SaveAsWizardPageDesc=将文件保存至另一个位置。

###########################################################
#WizardReportSettingPage properties
WizardReportSettingPage.Error.ReportorTemplate=文件名应该以 {0} 或 .rpttemplate 结尾。
WizardReportSettingPage.Error.Library=文件名应该以 .rptlibrary 结尾。

###########################################################
#WizardSaveAsPage properties
WizardSaveAsPage.FileLabel=文件名(&F):
WizardSaveAsPage.Question=问题
WizardSaveAsPage.FolderEmpty=\ 文件夹为空。
WizardSaveAsPage.NoProject=\ 指定的项目不存在。
WizardSaveAsPage.PathOccupied=\ 该位置已经存在一个文件: {0}
WizardSaveAsPage.EmptyName=\ ''{0}'' 名称为空。
WizardSaveAsPage.SelectFolder=\ 选择文件夹:
WizardSaveAsPage.NameExists=\ 相同名称已经存在。
WizardSaveAsPage.OverwriteQuestion=文件 ''{0}'' 已经存在。是否要替换现有文件？
WizardSaveAsPage.InvalidFileName=\ ''{0}''不是有效文件名。
WizardSaveAsPage.ContainerGroup=\ 输入或选择父文件夹(&E):

###########################################################
#Library DND message
Library.DND.messages.outofsync = 报表中使用的库可能已被更改，请关闭并重新打开此报表以使用更新的库。
NamedExpressionsHandleProvier.Column.Name=名称
NamedExpressionsHandleProvier.Column.DefaultValue=默认值
Library.DND.messages.cannotApplyTheme=主题无法应用。

JarFileFormProvider.Column.Name=名称

###########################################################
#ClassFinder
ClassFinder.TaskStart=正在搜索处理程序类...
ClassFinder.DialogTitle=类选择
ClassFinder.DialogMessage=选择处理程序类
ClassFinder.ErrorMessage=未找到类

###########################################################
#ListingSectionPage
ListingSectionPage.RepeatHeader=重复页眉

###########################################################
#ResourceEditDialog
ResourceEditDialog.NotFile.Title=未找到文件
ResourceEditDialog.NotFile.Message=文件“{0}”不存在。
ResourceEditDialog.ReadOnlyEncounter.Title=遇到只读文件
ResourceEditDialog.ReadOnlyEncounter.Message=文件“{0}”为只读，请首先确保它可以写入。

###########################################################
#EventHandler
EventHandlerPage.Browse=浏览(&B)...


###########################################################
#IDEFileReportProvider
IDEFileReportProvider.ReadOnlyEncounter.Title=遇到只读文件
IDEFileReportProvider.ReadOnlyEncounter.Message=文件“{0}”为只读，请首先确保它可以写入。

###########################################################
#DataSetColumnBindingsFormHandleProvider
DataSetColumnBindingsFormHandleProvider.Column.Name=名称
DataSetColumnBindingsFormHandleProvider.TableTitle=数据列绑定:
DataSetColumnBindingsFormHandleProvider.NewBinding=新绑定  
DataSetColumnBindingsFormHandleProvider.Column.DataType=数据类型
DataSetColumnBindingsFormHandleProvider.Column.Expression=表达式
DataSetColumnBindingsFormHandleProvider.Column.AggregateOn=聚合条件
DataSetColumnBindingsFormHandleProvider.ALL=全部
DataSetColumnBindingsFormHandleProvider.NONE=不适用

###########################################################
#DataSetColumnBindingsFormPage
DataSetColumnBindingsFormPage.Button.RemoveUnused=删除未使用的列
###########################################################
#ResourceSelectionValidator
ResourceSelectionValidator.ExtError=选中的文件的结尾必须是 
ResourceSelectionValidator.EmptyError=请选择文件
ResourceSelectionValidator.ExtErrorSplitter=\ 或 

###########################################################
#GeneralPage
GeneralPage.Library.Included=库:
###########################################################
#
FormatStringPage.SimpleTextZipCode=94103
FormatStringPage.SimpleTextZipCode4=941031234
FormatStringPage.PhoneNumber=4155551111
FormatStringPage.SocialSecurityNumber=123456789
FormatStringPage.simpleTexZipCodeFormat=@@@@@@
FormatStringPage.simpleTexZipCode4Format=@@@@@@
FormatStringPage.phoneNumberFormat=(@@@)@@@@@@@@
FormatStringPage.securityNumberFormat=@@@-@@-@@@@


###########################################################
#PublishLibraryDialog
PublishLibraryDialog.ShellText=发布库
PublishLibraryDialog.TitleArea=发布库
PublishLibraryDialog.Message=将库发布到 BIRT 资源文件夹
PublishLibraryDialog.Label.SourceFileName=源文件(&S):
PublishLibraryDialog.Label.FileName=文件名(&N):
PublishLibraryDialog.Label.Folder=文件夹(&F):
PublishLibraryDialog.Label.Browse=浏览(&B)...
PublishLibraryDialog.Message.FileNameEmpty=需要提供文件名。
PublishLibraryDialog.Message.FileNameError=文件名应该以 .rptlibrary 结尾。
PublishLibraryDialog.Message.FolderEmpty=需要提供发布文件夹。
PublishLibraryDialog.Message.SourceFileEmpty=需要提供源文件名。
PublishLibraryDialog.Label.Browse2=浏览(&W)...
PublishLibraryDialog.AddText=添加库
PublishLibraryDialog.AddMessage=将库添加到 BIRT 资源文件夹

WizardLibrarySettingPage.ErrorMessage=请选择文件夹

WizardLibrarySettingPage.Resourcefile.Dialog.Title=浏览资源文件夹
WizardLibrarySettingPage.Resourcefile.Dialog.Message=Please select the resource folder or its sub-folders.

PublishLibraryDialog.AddLibrary=添加库

###########################################################
#EmbeddedImagesNodeProvider
EmbeddedImagesNodeProvider.FileNameError.Title=错误
EmbeddedImagesNodeProvider.FileNameError.Message=您选择的文件不是图像。

###########################################################
#AddElementtoAction properties
AddElementtoAction.Text=添加到报表(&A)

###########################################################
#MultiPageReportEditor properties
MultiPageReportEditor.CheckVersion.Dialog.Title=警告
TableArea.Button.Up=上移(&U)

###########################################################
#AddJarResourceFileFolderSelectionDialog
AddJarResourceFileFolderSelectionDialog.ErrorMessage.Exist=一个或多个选定的文件已经存在。
AddJarResourceFileFolderSelectionDialog.Message=请选择 jar 文件:
AddJarResourceFileFolderSelectionDialog.ErrorMessage.ExtError=文件名必须以 .jar 结尾。

###########################################################
#AddImageResourceFileFolderSelectionDialog
AddImageResourceFileFolderSelectionDialog.Title=选择的一个或多个文件已存在。
AddImageResourceFileFolderSelectionDialog.Message=请选择图像:

###########################################################
#DataItemBindingDialog properties

DataItemBindingDialog.text.Name=名称:
DataItemBindingDialog.text.DataType=数据类型:
DataItemBindingDialog.text.Expression=表达式:
DataItemBindingDialog.text.AggregateOn=聚合条件:
DataItemBindingDialog.text.ForceBinding=创建与同一表达式的新绑定
DataItemBindingDialog.text.All=全部
DataItemBindingDialog.text.None=不适用
DataItemBindingDialog.title.CreateNewItem=新建数据项绑定
DataItemBindingDialog.title.EditDataItem=编辑数据项绑定

###########################################################
#DataColumBindingDialog properties
DataColumBindingDialog.title.CreateNewDataBinding=新建数据绑定
DataColumBindingDialog.title.EditDataBinding=编辑数据绑定

###########################################################
#CreatePlaceHolderAction properties
ChangeDataColumnAction.text=更改数据列

###########################################################
#ThumbnailBuilder properties
ThumbnailBuilder.Text.Title=管理缩略图
ThumbnailBuilder.Button.Text.Generate=生成(&G)
ThumbnailBuilder.Button.Text.Remove=删除(&R)
ThumbnailBuilder.Button.Text.Import=导入(&I)...
ThumbnailBuilder.FileDialog.Title=选择图像文件
ThumbnailBuilder.FileDialog.FileNameError.Title=错误
ThumbnailBuilder.FileDialog.FileNameError.Message=您选择的文件不是图像。

###########################################################
#FragmentResourceEntry properties
FragmentResourceEntry.RootName=片段
FragmentResourceEntry.RootDisplayName=内置库

###########################################################
#PathResourceEntry properties
PathResourceEntry.RootName=资源文件夹
PathResourceEntry.RootDisplayName=共享库

###########################################################
#BIRTGotoMarker properties
BIRTGotoMarker.Error.Title=错误
BIRTGotoMarker.Error.Message=报表元素不存在。

###########################################################
#TabbedList properties
TabbedPropertyList.properties.not.available=属性不可用。
