#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#ODP Emitter
ODPEmitter.Description=Configurez les options pour un rendu de rapport au format Présentation OpenDocument.

ODPEmitter.DisplayName=Présentation OpenDocument

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=Traitement BIDI

OptionDisplayValue.TextWrapping=Retour à la ligne automatique

OptionDisplayValue.PageOverFlow=Traitement du dépassement de page

OptionDisplayValue.CLIP_CONTENT=Recadrer le contenu

OptionDisplayValue.FIT_TO_PAGE_SIZE=Adapter à la taille de la page

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Répartir sur plusieurs pages

OptionDisplayValue.ENLARGE_PAGE_SIZE=Agrandir la taille de la page

OptionDisplayValue.FontSubstitution=Changement de police

OptionDisplayValue.ChartDpi=DPI de graphique

###########################################################
#Option Description
OptionDescription.BidiProcessing=Traitement BIDI utilisé.

OptionDescription.TextWrapping=Un retour à la ligne est nécessaire.

OptionDescription.PageOverFlow=Vérifiez comment répartir le contenu.

OptionDescription.FontSubstitution=Vérification nécessaire pour savoir si le caractère existe dans la police sélectionnée.

OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.