#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#ODP Emitter
ODPEmitter.Description=OpenDocument 프레젠테이션 형식의 보고서 렌더링 옵션을 구성합니다.

ODPEmitter.DisplayName=OpenDocument 프레젠테이션

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI 처리

OptionDisplayValue.TextWrapping=텍스트 줄 바꿈

OptionDisplayValue.PageOverFlow=페이지 오버플로 처리

OptionDisplayValue.CLIP_CONTENT=내용 자르기

OptionDisplayValue.FIT_TO_PAGE_SIZE=페이지 크기에 맞추기

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=여러 페이지로 출력

OptionDisplayValue.ENLARGE_PAGE_SIZE=페이지 크기 확대

OptionDisplayValue.FontSubstitution=글꼴 대체

OptionDisplayValue.ChartDpi=차트 DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=BIDI 처리를 사용합니다.

OptionDescription.TextWrapping=텍스트를 줄 바꿈합니다.

OptionDescription.PageOverFlow=내용 출력 방식을 제어합니다.

OptionDescription.FontSubstitution=선택한 글꼴에 해당 문자가 있는지 확인해야 합니다.

OptionDescription.ChartDpi=DPI는 차트를 생성하는 데 사용합니다.

###########################################################
#tooltip
Tooltip.ChartDpi=차트 엔진에서 차트를 생성하는 데 사용하는 DPI입니다. 예: 192.