#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#ODP Emitter
ODPEmitter.Description=Optionen zum Rendern eines Berichts im OpenDocument Presentation-Format konfigurieren.

ODPEmitter.DisplayName=OpenDocument Präsentation

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=BIDI-Verarbeitung

OptionDisplayValue.TextWrapping=Zeilenumbruch

OptionDisplayValue.PageOverFlow=Seitenüberlauf-Verarbeitung

OptionDisplayValue.CLIP_CONTENT=Inhalt zuschneiden

OptionDisplayValue.FIT_TO_PAGE_SIZE=An Seitengröße anpassen

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Mehrere Seiten ausgeben

OptionDisplayValue.ENLARGE_PAGE_SIZE=Seite vergrößern

OptionDisplayValue.FontSubstitution=Schriftart ersetzen

OptionDisplayValue.ChartDpi=Diagramm-DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=BIDI-Verarbeitung wird verwendet.

OptionDescription.TextWrapping=Text enthält Zeilenumbrüche.

OptionDescription.PageOverFlow=Legen Sie fest, wie der Inhalt ausgegeben wird.

OptionDescription.FontSubstitution=Überprüfung erforderlich, ob die ausgewählte Schriftart das Zeichen unterstützt.

OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.