#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#ODP Emitter
ODPEmitter.Description=OpenDocument プレゼンテーション形式でレポートをレンダリングするためのオプションを設定します。

ODPEmitter.DisplayName=OpenDocument プレゼンテーション

###########################################################
#Option Display Value
OptionDisplayValue.BidiProcessing=双方向テキストの処理

OptionDisplayValue.TextWrapping=文字列の折り返し

OptionDisplayValue.PageOverFlow=オーバーフローしているページの処理

OptionDisplayValue.CLIP_CONTENT=コンテンツのクリッピング

OptionDisplayValue.FIT_TO_PAGE_SIZE=ページサイズに合わせる

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=複数ページを出力

OptionDisplayValue.ENLARGE_PAGE_SIZE=ページサイズを大きくする

OptionDisplayValue.FontSubstitution=フォントの置き換え

OptionDisplayValue.ChartDpi=グラフの DPI

###########################################################
#Option Description
OptionDescription.BidiProcessing=双方向テキストの処理が使用されています。

OptionDescription.TextWrapping=テキストを折り返す必要があります。

OptionDescription.PageOverFlow=コンテンツの出力方法を制御します。

OptionDescription.FontSubstitution=選択したフォントにその文字が存在しているかどうかを確認する必要があります。

OptionDescription.ChartDpi=グラフの生成に使用する DPI です。

###########################################################
#tooltip
Tooltip.ChartDpi=グラフエンジンがグラフの生成に使用する DPI です。例: 192。