###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
#
###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=쿼리

datasource.name=JDBC 데이터 원본

dataset.jdbcselect=JDBC를 통한 SQL SELECT

datasource.editor.page.connection=데이터 원본 연결

preference.datasetpreview=JDBC 데이터 집합

preference.bidi.datasource.title =JDBC 데이터 원본

wizard.data.set.title=새 데이터 집합


plugin.name=BIRT JDBC UI Plug-in
newwizard.name=BIRT JDBC Data Source
newwizard.description=BIRT JDBC 연결 프로필 생성

wizard.window.title=새 JDBC 데이터 원본 프로필

wizard.data.source.page.title=새 데이터 원본 생성

profile.propertypage.name=BIRT JDBC Data Source
