###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=查询
datasource.name=JDBC 数据源
dataset.jdbcselect=通过 JDBC 执行 SQL SELECT
datasource.editor.page.connection=数据源连接
preference.datasetpreview=JDBC 数据集

plugin.name=BIRT JDBC UI Plug-in
oda.data.source.name=BIRT JDBC 数据源
connection.profile.name=BIRT JDBC 数据源连接配置文件
newwizard.name=BIRT JDBC 数据源
newwizard.description=创建 BIRT JDBC 连接配置文件
wizard.window.title=新建 JDBC 数据源配置文件
wizard.data.source.page.title=创建新的数据源
profile.propertypage.name=BIRT JDBC 数据源

oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂

