###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
#
###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=Consulta

datasource.name=Fuente de datos JDBC

dataset.jdbcselect=SQL SELECT mediante JDBC

datasource.editor.page.connection=Conexión de fuente de datos

preference.datasetpreview=Conjunto de datos JDBC

preference.bidi.datasource.title =Fuente de datos JDBC

wizard.data.set.title=Nuevo conjunto de datos


plugin.name=BIRT JDBC UI Plug-in
newwizard.name=BIRT JDBC Data Source
newwizard.description=Crear un perfil de conexión JDBC BIRT

wizard.window.title=Nuevo perfil de fuente de datos JDBC

wizard.data.source.page.title=Crear una nueva fuente de datos

profile.propertypage.name=BIRT JDBC Data Source
