###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=쿼리
datasource.name=JDBC 데이터 원본
dataset.jdbcselect=JDBC를 통한 SQL SELECT
datasource.editor.page.connection=데이터 원본 연결
preference.datasetpreview=JDBC 데이터 집합

plugin.name=BIRT JDBC UI Plug-in
oda.data.source.name=BIRT JDBC 데이터 원본
connection.profile.name=BIRT JDBC 데이터 원본 연결 프로필
newwizard.name=BIRT JDBC 데이터 원본
newwizard.description=BIRT JDBC 연결 프로필 생성
wizard.window.title=새 JDBC 데이터 원본 프로필
wizard.data.source.page.title=새 데이터 원본 생성
profile.propertypage.name=BIRT JDBC 데이터 원본

oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리

