###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
#
###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=Requête

datasource.name=Source de données JDBC

dataset.jdbcselect=SQL SELECT via JDBC

datasource.editor.page.connection=Connexion à une source de données

preference.datasetpreview=Jeu de données JDBC

preference.bidi.datasource.title =Source de données JDBC

wizard.data.set.title=Nouveau jeu de données


plugin.name=BIRT JDBC UI Plug-in
newwizard.name=BIRT JDBC Data Source
newwizard.description=Créer un profil de connexion JDBC BIRT

wizard.window.title=Nouveau profil de source de données JDBC

wizard.data.source.page.title=Créer une nouvelle source de données

profile.propertypage.name=BIRT JDBC Data Source
