###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=Abfrage
datasource.name=JDBC-Datenquelle
dataset.jdbcselect=SQL SELECT über JDBC
datasource.editor.page.connection=Datenquellen-Verbindung
preference.datasetpreview=JDBC-Datensatz

plugin.name=BIRT JDBC UI Plug-in
oda.data.source.name=BIRT-JDBC-Datenquelle
connection.profile.name=BIRT-JDBC-Datenquellenverbindungsprofil
newwizard.name=BIRT-JDBC-Datenquelle
newwizard.description=BIRT-JDBC-Datenquellenverbindungsprofil erstellen
wizard.window.title=Neues JDBC-Datenquellenprofil
wizard.data.source.page.title=Neue Datenquelle erstellen
profile.propertypage.name=BIRT-JDBC-Datenquelle

oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory

