###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Viewer Path
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# NLS String
###############################################################################
dataset.editor.page.query=Consulta
datasource.name=Fuente de datos JDBC
dataset.jdbcselect=SQL SELECT mediante JDBC
datasource.editor.page.connection=Conexión de fuente de datos
preference.datasetpreview=Conjunto de datos JDBC

plugin.name=BIRT JDBC UI Plug-in
oda.data.source.name=Fuente de datos JDBC BIRT
connection.profile.name=Perfil de conexión de fuente de datos JDBC BIRT
newwizard.name=Fuente de datos JDBC BIRT
newwizard.description=Crear un perfil de conexión JDBC BIRT 
wizard.window.title=Nuevo perfil de fuente de datos JDBC
wizard.data.source.page.title=Crear una nueva fuente de datos
profile.propertypage.name=Fuente de datos JDBC BIRT

oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA

