#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.layout=Diseñ&o

design.masterPage=&Página maestra

design.script=&Script

design.xmlsource=&Fuente XML

template.layout=Diseñ&o

template.masterPage=&Página maestra

template.script=&Script

template.xmlsource=&Fuente XML

pageSet.layout=&Diseño de página

pageSet.master=Página &maestra

pageSet.preview=&Página de vista previa

pageSet.script=Página de &script

pageSet.source=Página fuente &XML