#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.layout=&Mise en page

design.masterPage=&Page maître

design.script=&Script

design.xmlsource=Source &XML

template.layout=&Mise en page

template.masterPage=&Page maître

template.script=&Script

template.xmlsource=Source &XML

pageSet.layout=&Page de présentation

pageSet.master=&Page maître

pageSet.preview=&Page de prévisualisation

pageSet.script=&Page de script

pageSet.source=&Page XML source