design.layout=Diseñ&o
design.masterPage=&Página maestra
design.script=&Script
design.xmlsource=&Fuente XML

template.layout=Diseñ&o
template.masterPage=&Página maestra
template.script=&Script
template.xmlsource=&Fuente XML

pageSet.layout=&Diseño de página
pageSet.master=Página &maestra
pageSet.preview=&Página de vista previa
pageSet.script=Página de &script
pageSet.source=Página fuente &XML
