#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.layout=レイアウト(&O)

design.masterPage=マスターページ(&M)

design.script=スクリプト(&S)

design.xmlsource=XML ソース(&X)

template.layout=レイアウト(&O)

template.masterPage=マスターページ(&M)

template.script=スクリプト(&S)

template.xmlsource=XML ソース(&X)

pageSet.layout=レイアウトページ(&L)

pageSet.master=マスターページ(&M)

pageSet.preview=プレビューページ(&P)

pageSet.script=スクリプトページ(&S)

pageSet.source=XML ソースページ(&X)