#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.layout=布局(&O)

design.masterPage=主页(&M)

design.script=脚本(&S)

design.xmlsource=XML 源(&X)

template.layout=布局(&O)

template.masterPage=主页(&M)

template.script=脚本(&S)

template.xmlsource=XML 源(&X)

pageSet.layout=布局页(&L)

pageSet.master=主页(&M)

pageSet.preview=预览页(&P)

pageSet.script=脚本页(&S)

pageSet.source=XML 源页(&X)