#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/
design.layout=Lay&out

design.masterPage=&Master-Seite

design.script=&Skript

design.xmlsource=&XML-Quelldatei

template.layout=Lay&out

template.masterPage=&Master-Seite

template.script=&Skript

template.xmlsource=&XML-Quelldatei

pageSet.layout=&Layout-Seite

pageSet.master=&Master-Seite

pageSet.preview=&Vorschauseite

pageSet.script=&Skript-Seite

pageSet.source=&XML-Quellseite