#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Word Emitter
WordEmitter.Description=Configurez les options pour un rendu de rapport au format document XML 2003.

WordEmitter.DisplayName=Word (DOC)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=DPI de graphique

###########################################################
#Option Description
OptionDescription.ChartDpi=DPI utilisé pour générer un graphique.

###########################################################
#tooltip
Tooltip.ChartDpi=DPI utilisé par le moteur de graphique pour générer des graphiques. Par exemple, 192.