#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Word Emitter
WordEmitter.Description=配置用于以 XML Document 2003 格式呈现报表的选项。

WordEmitter.DisplayName=Word (DOC)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=图表 DPI

###########################################################
#Option Description
OptionDescription.ChartDpi=DPI 用于生成图表。

###########################################################
#tooltip
Tooltip.ChartDpi=图表引擎用于生成图表的 DPI。 例如，192。