#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Word Emitter
WordEmitter.Description=Optionen zum Rendern eines Berichts im Format XML Document 2003 konfigurieren.

WordEmitter.DisplayName=Word (DOC)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=Diagramm-DPI

###########################################################
#Option Description
OptionDescription.ChartDpi=DPI zum Erstellen von Diagrammen.

###########################################################
#tooltip
Tooltip.ChartDpi=Von der Diagramm-Engine zum Erstellen von Diagrammen verwendete DPI. Zum Beispiel 192.