#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#Word Emitter
WordEmitter.Description=Configure las opciones para presentar un informe en formato de documento XML 2003.

WordEmitter.DisplayName=Word (DOC)

###########################################################
#Option Display Value
OptionDisplayValue.ChartDpi=Diagrama DPI

###########################################################
#Option Description
OptionDescription.ChartDpi=El DPI utilizado para generar el diagrama.

###########################################################
#tooltip
Tooltip.ChartDpi=El DPI que utiliza el motor de diagramas para generar diagramas. Por ejemplo, 192.