#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#HTML Emitter
HTMLEmitter.Description=HTML(HyperText Markup Language) 형식의 보고서 렌더링 옵션을 구성합니다.

HTMLEmitter.DisplayName=HTML
XHTMLEmitter.Description=XHTML 형식의 보고서 렌더링 옵션을 구성합니다.

XHTMLEmitter.DisplayName=XHTML

###########################################################
#Option Display Value
OptionDisplayValue.AgentStyleEngine=사용자 에이전트에 스타일 처리 위임

OptionDisplayValue.Enable=사용

OptionDisplayValue.Disable=사용 안 함

OptionDisplayValue.OutputMasterPageMargins=마스터 페이지 여백 출력

OptionDisplayValue.MasterPageContent=출력 페이지 머리글 및 바닥글

OptionDisplayValue.PageFooterFloat=부동 페이지 바닥글

OptionDisplayValue.LayoutPreference=레이아웃 기본 설정:

OptionDisplayValue.FixedLayout=고정 레이아웃

OptionDisplayValue.AutoLayout=자동 레이아웃

OptionDisplayValue.HTMLType=출력 유형:

OptionDisplayValue.CompleteHTML=완전한 HTML

OptionDisplayValue.HTMLNoCSS=HTML(CSS 제외)

###########################################################
#Option Description
OptionDescription.AgentStyleEngine=참: HTML 이미터가 BIRT 스타일을 직접 보고서로 출력하며 브라우저에 따라 스타일 계산을 구현합니다.\n거짓: HTML 이미터가 BIRT 스타일 엔진을 사용하여 스타일을 계산하고 결과를 보고서로 출력합니다.

OptionDescription.OutputMasterPageMargins=자동 레이아웃 보고서에 대한 마스터 페이지 여백을 출력합니다.

OptionDescription.MasterPageContent=페이지 머리글과 바닥글을 포함하며, 페이지 매김 사용 시에만 적용됩니다.

OptionDescription.PageFooterFloat=페이지 바닥글을 배치하며, 페이지 매김 사용 시에만 적용됩니다.

OptionDescription.HTMLType=HTML 유형입니다.
