#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
#HTML Emitter
HTMLEmitter.Description=Optionen zum Rendern eines Berichts im HTML-Format (HyperText Markup Language) konfigurieren.

HTMLEmitter.DisplayName=HTML
XHTMLEmitter.Description=Optionen zum Rendern eines Berichts im XHTML-Format konfigurieren.

XHTMLEmitter.DisplayName=XHTML

###########################################################
#Option Display Value
OptionDisplayValue.AgentStyleEngine=Stilverarbeitung an Benutzeragenten delegieren

OptionDisplayValue.Enable=Aktivieren

OptionDisplayValue.Disable=Deaktivieren

OptionDisplayValue.OutputMasterPageMargins=Ränder von Master-Seite ausgeben

OptionDisplayValue.MasterPageContent=Kopf- und Fußzeile ausgeben

OptionDisplayValue.PageFooterFloat=Unverankerte Fußzeile

OptionDisplayValue.LayoutPreference=Layoutvoreinstellungen:

OptionDisplayValue.FixedLayout=Festes Layout

OptionDisplayValue.AutoLayout=Automatisches Layout

OptionDisplayValue.HTMLType=Ausgabetyp:

OptionDisplayValue.CompleteHTML=Vollständiges HTML

OptionDisplayValue.HTMLNoCSS=HTML ohne CSS

###########################################################
#Option Description
OptionDescription.AgentStyleEngine=True: Der HTML-Emitter gibt die BIRT-Stile direkt im Bericht aus. Die Implementierung der Stilberechnung hängt vom Browser ab.\nFalse: Der HTML-Emitter berechnet die Stile mithilfe der BIRT-Stil-Engine und gibt die Ergebnisse im Bericht aus.

OptionDescription.OutputMasterPageMargins=Ränder von Master-Seite in Bericht mit automatischem Layout ausgeben.

OptionDescription.MasterPageContent=Enthält Kopf- und Fußzeile; nur bei aktivierter Paginierung verfügbar.

OptionDescription.PageFooterFloat=Unverankerte Fußzeile; nur bei aktivierter Paginierung verfügbar.

OptionDescription.HTMLType=HTML-Typ.
