RadarSeriesImpl.displayName=Radardatenreihe

RadarChart.Txt.DefaultRadarChartTitle=Radardiagrammtitel
RadarChart.Txt.DisplayName=Radar
RadarChart.SubType.Standard=Standardradardiagramm
RadarChart.SubType.Spider=Netzradardiagramm
RadarChart.SubType.Bullseye=Punktradardiagramm

RadarChart.Tooltip.InputExpression=Geben Sie einen Ausdruck ein, der für jedes Objekt als Legendentext angezeigt wird.
RadarChart.Txt.HelpText=Radardiagramme zeigen den aktuellen Datenwert einer bestimmten Messgröße an. Die verschiedenfarbigen Abschnitte stellen die Bereiche der Messgrößenwerte dar. Nadeln sind mit Tachometern verknüpft und zeigen deren Wert an.
RadarChart.Txt.Description=Standardradardiagramme enthalten ein zirkuläres Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.
RadarChart.Txt.SpiderDescription=Netzradardiagramme enthalten ein polygonales Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.
RadarChart.Txt.BullseyeDescription=Punktradardiagramme enthalten ein zirkuläres, gefülltes Raster, das von einem oder mehreren Reihenpolygonen bzw. einer oder mehreren Reihenlinien überlagert wird.

RadarSeriesAttributeComposite.Lbl.Radius=Radi&us:
RadarSeriesAttributeComposite.Lbl.StartAngle=&Startwinkel:
RadarSeriesAttributeComposite.Lbl.StopAngle=Endwink&el:
RadarSeriesAttributeSheetImpl.Lbl.Type=Geben Sie Folgendes ein:
RadarSeriesAttributeSheetImpl.Lbl.Fill=Füllung:
RadarSeriesAttributeComposite.Lbl.DialTicks=&Häkchen
RadarSeriesAttributeComposite.Lbl.DialScale=S&kalierung
RadarBaseSeriesComponent.Label.CategoryDefinition=&Kategoriedefinition:
RadarSeriesAttributeComposite.Lbl.ShowWeb=&Web-/Radarbeschriftungen anzeigen

RadarSeriesAttributeComposite.Exception.IllegalArgument=Datenreihe vom Typ {0} ist ein ungültiges Argument für RadarSeriesAttributeComposite.
RadarSeriesAttributeComposite.Lbl.LinePalette=&Palette für Datenreihe als Linienfarbe verwenden
RadarSeriesAttributeComposite.Lbl.FillPoly=Poly&gons füllen
RadarSeriesAttributeComposite.Lbl.ConnectPoints=Datensatzendpunkte verbinden (polygonal)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=&Linien als Kurven anzeigen

RadarSeriesMarkerSheet.Label.Markers=&Markierung
RadarSeriesMarkerSheet.GroupLabel.Markers=Markierung

RadarSeriesMarkerSheet.Label.Web=Diagrammlinienkonfiguration
RadarSeriesMarkerSheet.Label.Series=Reihenlinienkonfiguration

Radar.Composite.Label.ScaleCount=A&nzahl Skalenschritte in Diagramm
Radar.Composite.Label.ScaleCountToolTip=Anzahl Skalenschritte zum Erstellen im Diagramm
Radar.Composite.Label.bullsEye=Punktfarben als transparent festlegen




Radar.Composite.Label.PlotPercentageToolTip=Prozentsatz der Zeichnungsfläche, der für den Radar erforderlich ist
