RadarSeriesImpl.displayName=レーダー系列

RadarChart.Txt.DefaultRadarChartTitle=レーダーチャートのタイトル
RadarChart.Txt.DisplayName=レーダー
RadarChart.SubType.Standard=標準レーダーチャート
RadarChart.SubType.Spider=スパイダーレーダーチャート
RadarChart.SubType.Bullseye=ブルズアイレーダーチャート

RadarChart.Tooltip.InputExpression=各項目の凡例として表示されている式を入力してください。
RadarChart.Txt.HelpText=レーダーチャート。データの測定値を示します。 測定値の範囲に応じて領域を色分けします。 レーダー上のダイアルを指す針によって値が示されます。
RadarChart.Txt.Description=標準レーダーチャート。円形のグリッド上に多角形と線を重ね合わせて表示します。
RadarChart.Txt.SpiderDescription=スパイダーレーダーチャート。多角形のグリッド上に多角形と線を重ね合わせて表示します。
RadarChart.Txt.BullseyeDescription=ブルズアイレーダーチャート。円形の塗りつぶされたグリッド上に多角形と線を重ね合わせて表示します。

RadarSeriesAttributeComposite.Lbl.Radius=半径(&U) :
RadarSeriesAttributeComposite.Lbl.StartAngle=始点の角度(&G) :
RadarSeriesAttributeComposite.Lbl.StopAngle=終端の角度(&E) :
RadarSeriesAttributeSheetImpl.Lbl.Type=型 :
RadarSeriesAttributeSheetImpl.Lbl.Fill=塗りつぶし :
RadarSeriesAttributeComposite.Lbl.DialTicks=目盛を付ける(&T)
RadarSeriesAttributeComposite.Lbl.DialScale=スケール(&C)
RadarBaseSeriesComponent.Label.CategoryDefinition=カテゴリの定義(&C) :
RadarSeriesAttributeComposite.Lbl.ShowWeb=Web / レーダーラベルを表示(&W)

Radar=標準レーダグラフ。円形のグリッド上に多角形と線を重ね合わせて表示します。
SampleChartName.Radar=レーダ


RadarSeriesAttributeComposite.Exception.IllegalArgument={0} 型の系列は、RadarSeriesAttributeComposite の引数としては使用できません。
RadarSeriesAttributeComposite.Lbl.LinePalette=系列パレットを線の色として使用する(&P)
RadarSeriesAttributeComposite.Lbl.FillPoly=多角形の塗りつぶし(&G)
RadarSeriesAttributeComposite.Lbl.ConnectPoints=データセットエンドポイントの接続（多角形）(&C)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=線を曲線で表示(&H)

RadarSeriesMarkerSheet.Label.Markers=マーカ(&M)
RadarSeriesMarkerSheet.GroupLabel.Markers=マーカ

RadarSeriesMarkerSheet.Label.Web=グラフの線の設定
RadarSeriesMarkerSheet.Label.Series=系列の線の設定

Radar.Composite.Label.ScaleCount=グラフの目盛(&N)
Radar.Composite.Label.ScaleCountToolTip=グラフで使用する目盛を設定
Radar.Composite.Label.bullsEye=ブルズアイの色を半透明に設定




Radar.Composite.Label.PlotPercentageToolTip=レーダーチャートで使用するプロット領域の割合
