RadarSeriesImpl.displayName=Serie radial

RadarChart.Txt.DefaultRadarChartTitle=Título de diagrama radial
RadarChart.Txt.DisplayName=Radial
RadarChart.SubType.Standard=Diagrama radial estándar
RadarChart.SubType.Spider=Diagrama radial de araña
RadarChart.SubType.Bullseye=Diagrama radial de ojo de buey

RadarChart.Tooltip.InputExpression=Introduzca una expresión que se muestre como texto de leyenda para cada elemento
RadarChart.Txt.HelpText=Los diagramas radiales muestran el valor de los datos actuales de una medida. Las regiones con colores diferentes representan los intervalos de los valores de medida. Un indicador asociado a un cuadrante muestra su valor.
RadarChart.Txt.Description=Los diagramas radiales estándar contienen una cuadrícula circular a la que se superponen series de líneas o polígonos
RadarChart.Txt.SpiderDescription=Los diagramas radiales de araña contienen una cuadrícula de polígonos a la que se superponen series de líneas o polígonos
RadarChart.Txt.BullseyeDescription=Los diagramas radiales de ojo de buey contienen una cuadrícula circular rellena a la que se superponen series de líneas o polígonos

RadarSeriesAttributeComposite.Lbl.Radius=Radi&o:
RadarSeriesAttributeComposite.Lbl.StartAngle=Án&gulo de inicio:
RadarSeriesAttributeComposite.Lbl.StopAngle=Áng&ulo de detención:
RadarSeriesAttributeSheetImpl.Lbl.Type=Tipo:
RadarSeriesAttributeSheetImpl.Lbl.Fill=Relleno:
RadarSeriesAttributeComposite.Lbl.DialTicks=&Marcas
RadarSeriesAttributeComposite.Lbl.DialScale=E&scala
RadarBaseSeriesComponent.Label.CategoryDefinition=Definición de &categoría:
RadarSeriesAttributeComposite.Lbl.ShowWeb=Mostrar etiquetas &Web/Radial

RadarSeriesAttributeComposite.Exception.IllegalArgument=La serie de tipo {0} no es un argumento válido para RadarSeriesAttributeComposite.
RadarSeriesAttributeComposite.Lbl.LinePalette=Usar &paleta de series como color de línea
RadarSeriesAttributeComposite.Lbl.FillPoly=Rellenar polí&gonos
RadarSeriesAttributeComposite.Lbl.ConnectPoints=&Conectar puntos finales de conjunto de datos (polígono)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=M&ostrar líneas como curvas

RadarSeriesMarkerSheet.Label.Markers=&Marcador
RadarSeriesMarkerSheet.GroupLabel.Markers=Marcador

RadarSeriesMarkerSheet.Label.Web=Configuración de línea de diagrama
RadarSeriesMarkerSheet.Label.Series=Configuración de línea de serie

Radar.Composite.Label.ScaleCount=&Número de pasos de escala en el diagrama
Radar.Composite.Label.ScaleCountToolTip=Numero de pasos de escala con los que crear el diagrama
Radar.Composite.Label.bullsEye=Establecer los colores de ojo de buey como translúcidos




Radar.Composite.Label.PlotPercentageToolTip=Porcentaje de área de dibujo que consumirá el radial
