RadarSeriesImpl.displayName=Radar Series

RadarChart.Txt.DefaultRadarChartTitle=Radar Chart Title
RadarChart.Txt.DisplayName=Radar
RadarChart.SubType.Standard=Standard Radar Chart
RadarChart.SubType.Spider=Spider Radar Chart
RadarChart.SubType.Bullseye=Bullseye Radar Chart

RadarChart.Tooltip.InputExpression=Input an expression which is displayed as Legend text for each item
RadarChart.Txt.HelpText=Radar charts show the current data value of a certain measurement. The regions with different colors represent the ranges of measurement values. A needle associates with a dial and shows the value of it.
RadarChart.Txt.Description=Standard Radar charts contain a circular grid overlaid with one or more series polygons/lines
RadarChart.Txt.SpiderDescription=Spider Radar charts contain a polygon grid overlaid with one or more series polygons/lines
RadarChart.Txt.BullseyeDescription=Bullseye Radar charts contain a circular filled grid overlaid with one or more series polygons/lines

RadarSeriesAttributeComposite.Lbl.Radius=Radi&us:
RadarSeriesAttributeComposite.Lbl.StartAngle=Start An&gle:
RadarSeriesAttributeComposite.Lbl.StopAngle=Stop Angl&e:
RadarSeriesAttributeSheetImpl.Lbl.Type=Type:
RadarSeriesAttributeSheetImpl.Lbl.Fill=Fill:
RadarSeriesAttributeComposite.Lbl.DialTicks=&Ticks
RadarSeriesAttributeComposite.Lbl.DialScale=S&cale
RadarBaseSeriesComponent.Label.CategoryDefinition=&Category Definition:
RadarSeriesAttributeComposite.Lbl.ShowWeb=Show &Web/Radar Labels

RadarSeriesAttributeComposite.Exception.IllegalArgument=Series of type {0} is an invalid argument for RadarSeriesAttributeComposite.
RadarSeriesAttributeComposite.Lbl.LinePalette=Use Series &Palette as Line Color
RadarSeriesAttributeComposite.Lbl.FillPoly=Fill Poly&gons
RadarSeriesAttributeComposite.Lbl.ConnectPoints=&Connect Data Set Endpoints(polygon)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=S&how Lines as Curves

RadarSeriesMarkerSheet.Label.Markers=&Marker
RadarSeriesMarkerSheet.GroupLabel.Markers=Marker

RadarSeriesMarkerSheet.Label.Web=Chart Line Configuration
RadarSeriesMarkerSheet.Label.Series=Series Line Configuration

Radar.Composite.Label.ScaleCount=&Number Scale Steps in Chart
Radar.Composite.Label.ScaleCountToolTip=Number Scale Steps with which to create in the Chart
Radar.Composite.Label.bullsEye=Set the Bullseye colors to translucent




Radar.Composite.Label.PlotPercentageToolTip=Percentage of Plot Area the Radar will Consume
